### PR TITLE
fix(turbopack): use correct layout for 404 page

### LINKED ISSUE #60688: Default 404 route doesn't render root layout when using turbopack
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/epic-christian-frtl8t

### To Reproduce

1. Add the root layout
```tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ height: 60, backgroundColor: "red" }} />
        {children}
      </body>
    </html>
  );
}
```
2. Run the app in development mode (`next dev` and `next dev --turbo`)
3. Access an unhandled route

### Current vs. Expected behavior

The development server that uses Webpack (default) includes the root layout on the default 404 route
Screenshot 2024-01-15 at 23 10 50

The development server that uses Turbopack (`next dev --turbo`) doesn't include the root layout on the default 404 route
Screenshot 2024-01-15 at 23 10 58

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.5-canary.58
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

_No response_

<sub>[PACK-2241](https://linear.app/vercel/issue/PACK-2241/default-404-route-doesnt-render-root-layout-when-using-turbopack)</sub>

### PR DESCRIPTION
**Pull request by ForsakenHarmony**
### What?

This fixes 2 issues with app 404 pages.
1. The root layout in a group was previously ignored when hitting the 404 page.
2. The default app 404 page was missing the correct path for dev `/not-found` so it would fall back to the pages 404 page.

Closes PACK-2241
Fixes #60688

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/pack-2241-app-404-route-layout | Change |
| - | - | - | - |
| buildDuration | 11.8s | 12.1s | ⚠️ +337ms |
| buildDurationCached | 6.1s | 5s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ✓ |
| nextStartRea..uration (ms) | 429ms | 429ms | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/pack-2241-app-404-route-layout | Change |
| - | - | - | - |
| 193.HASH.js gzip | 181 B | 182 B | N/A |
| 3f784ff6-HASH.js gzip | 53.4 kB | 53.4 kB | ✓ |
| 433-HASH.js gzip | 29 kB | 29 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 239 B | 242 B | N/A |
| main-HASH.js gzip | 31.8 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.6 kB | 98.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/pack-2241-app-404-route-layout | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/pack-2241-app-404-route-layout | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 183 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 502 B | N/A |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 253 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.18 kB | 4.18 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | ✓ |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.4 kB | 3.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/pack-2241-app-404-route-layout | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 485 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/pack-2241-app-404-route-layout | Change |
| - | - | - | - |
| index.html gzip | 528 B | 525 B | N/A |
| link.html gzip | 540 B | 538 B | N/A |
| withRouter.html gzip | 524 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/pack-2241-app-404-route-layout | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94 kB | 94 kB | N/A |
| page.js gzip | 149 kB | 149 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/pack-2241-app-404-route-layout | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 626 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.5 kB | 37.5 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/pack-2241-app-404-route-layout | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 169 kB | 169 kB | ✓ |
| app-page-exp..prod.js gzip | 95.6 kB | 95.6 kB | ✓ |
| app-page-tur..prod.js gzip | 96.3 kB | 96.3 kB | ✓ |
| app-page-tur..prod.js gzip | 90.9 kB | 90.9 kB | ✓ |
| app-page.run...dev.js gzip | 142 kB | 142 kB | ✓ |
| app-page.run..prod.js gzip | 90.2 kB | 90.2 kB | ✓ |
| app-route-ex...dev.js gzip | 24.2 kB | 24.2 kB | ✓ |
| app-route-ex..prod.js gzip | 16.9 kB | 16.9 kB | ✓ |
| app-route-tu..prod.js gzip | 16.9 kB | 16.9 kB | ✓ |
| app-route-tu..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route.ru...dev.js gzip | 23.6 kB | 23.6 kB | ✓ |
| app-route.ru..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.41 kB | 9.41 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.68 kB | 9.68 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.4 kB | 9.4 kB | ✓ |
| pages-turbo...prod.js gzip | 22 kB | 22 kB | ✓ |
| pages.runtim...dev.js gzip | 22.6 kB | 22.6 kB | ✓ |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | ✓ |
| server.runti..prod.js gzip | 49.7 kB | 49.7 kB | ✓ |
| Overall change | 944 kB | 944 kB | ✓ |

</details>

</details>
Commit: f773d8b47d3328273d9901e4b3f2947c8d6faaa8

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f773d8b47d3328273d9901e4b3f2947c8d6faaa8

`pnpm test-dev test/development/basic/next-rs-api.test.ts`
- next.rs api > should detect the correct routes

<details>
<summary>Expand output</summary>

  ● next.rs api › should detect the correct routes

    expect(received).toEqual(expected) // deep equality

    - Expected  - 0
    + Received  + 1

    @@ -4,10 +4,11 @@
        "/api/edge",
        "/api/nodejs",
        "/app",
        "/app-edge",
        "/app-nodejs",
    +   "/not-found",
        "/page-edge",
        "/page-nodejs",
        "/route-edge",
        "/route-nodejs",
      ]

      232 |     const entrypoints = await entrypointsSubscribtion.next()
      233 |     expect(entrypoints.done).toBe(false)
    > 234 |     expect(Array.from(entrypoints.value.routes.keys()).sort()).toEqual([
          |                                                                ^
      235 |       '/',
      236 |       '/_not-found',
      237 |       '/api/edge',

      at Object.toEqual (development/basic/next-rs-api.test.ts:234:64)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: packages/next-swc/crates/next-core/src/app_structure.rs [hunk 1]
```diff
@@ -697,7 +697,9 @@ async fn directory_tree_to_loader_tree(
 
     components.metadata.base_page = Some(app_page.clone());
 
-    if app_page.is_root() && components.not_found.is_none() {
+    if (app_page.is_root() || (app_path.is_root() && components.layout.is_some()))
```
Comment (timneutkens) [inline packages/next-swc/crates/next-core/src/app_structure.rs:700]: It's hard to understand the order of operations here, seems there's a set of parenthesis missing?

```
(
    app_page.is_root() || 
    (app_path.is_root() && components.layout.is_some()) && 
    components.not_found.is_none()
)
```

The first condition `app_page.is_root() || ` also has to check if `not_found.is_none()` so maybe something like:

```
(
    (
    app_page.is_root() || 
    (app_path.is_root() && components.layout.is_some())
    ) && 
    components.not_found.is_none()
)
```

Even if it already handles that correctly (I'm not sure if it does) the parenthesis will make it clearer what the order is.

Comment (timneutkens) [reply packages/next-swc/crates/next-core/src/app_structure.rs:700]: It's currently unclear to me if `components.not_found.is_none()` is also checked for the `app_page.is_root()` case, just looking at it's really hard to know for certain it is checking that for the first condition as `||` and `&&` are combined

Comment (sokra) [reply packages/next-swc/crates/next-core/src/app_structure.rs:700]: Isn't `app_page.is_root()` and `app_path.is_root()` the same?

Comment (ForsakenHarmony) [reply packages/next-swc/crates/next-core/src/app_structure.rs:700]: @sokra no, route groups (and parallel routes) are only represented in the `app_page`, `app_path` is the url path which doesn't have route groups in it

Comment (ForsakenHarmony) [reply packages/next-swc/crates/next-core/src/app_structure.rs:700]: @timneutkens the `&&` and `||` are separated by parenthesis already, none of the conditions here use operator precedence, but I can try to pull something out

**Comment by ForsakenHarmony** [comment]
* `canary`
  * **#61032** <a href="https://app.graphite.dev/github/pr/vercel/next.js/61032?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ForsakenHarmony and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by timneutkens — APPROVED** [review]
Great update 💯
