### PR TITLE
fix(next-swc/ssg): less aggressive exports drop

### LINKED ISSUE #31855: Exported members that are used in SSR/SSG/ISG page function are undefined on the client (Attempted import error: '..' is not exported from '..' (imported as '..').)
### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome Version 96 (Official Build) (64-bit)

### What operating system are you using?

Ubuntu 20.04 via WSL 2 & Windows 10

### How are you deploying your application?

next start

### Describe the Bug

When you export a member that is used in the page function of `getStaticProps`, it will be `undefined` on the client.

For example:

```ts
// pages/index.tsx
export const revalidateInSeconds = 5 * 60;

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {},
    revalidate: revalidateInSeconds,
  };
};

// components/TestComponent.tsx
import { revalidateInSeconds } from "../pages";

export function TestComponent(): JSX.Element {
  console.log("revalidateInSeconds: ", revalidateInSeconds);
  return <p>Test component</p>;
}
```

### Expected Behavior

Exported variables shouldn't be `undefined` on the client.

## Reproduction repo

I created a reproduction repo for this bug:

[https://github.com/bennettdams/nextjs-bug-export-undefined](https://github.com/bennettdams/nextjs-bug-export-undefined)

1. `git clone git@github.com:bennettdams/nextjs-bug-export-undefined.git`
2. `npm i`
3. `npm run build`
4. `npm run start`

## Manual reproduce

1. [Create Next.js app](https://github.com/bennettdams/nextjs-bug-export-undefined/commit/0c812c6fcc7f86a6d49b6c51c94669fc0574b48e): `npx create-next-app@latest --use-npm --ts .`
2. [Add `getStaticProps` and a `const` to export](https://github.com/bennettdams/nextjs-bug-export-undefined/commit/851a9b4e12699c505dc82cc0c587b9abdf3160c6):
```tsx
export const revalidateInSeconds = 5 * 60;

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {},
    revalidate: revalidateInSeconds,
  };
};
```
3. [Add a test component](https://github.com/bennettdams/nextjs-bug-export-undefined/commit/65064110c06af6b6ef20aa08a1e6f49078af45d4) that logs the imported `const` (`revalidateInSeconds`) and use the component on the page:
```tsx
// components/TestComponent.tsx
import { revalidateInSeconds } from "../pages";

export function TestComponent(): JSX.Element {
  console.log("revalidateInSeconds: ", revalidateInSeconds);
  return <p>Test component</p>;
}

// pages/index.ts
...
  <main className={styles.main}>
        <TestComponent />

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
...
```
4. Build & start the app: `npm run build` & `npm run start`

# Results, looking at the console logs

### Terminal that is used for building:

<details>
  <summary>Click for text!</summary>
  
```
> next build

info  - Checking validity of types  
info  - Creating an optimized production build  
warn  - Compiled with warnings

./components/TestComponent.tsx
Attempted import error: 'revalidateInSeconds' is not exported from '../pages' (imported as 'revalidateInSeconds').

Import trace for requested module:
./pages/index.tsx

info  - Collecting page data  
```
</details>

image

### Browser:

image

---

## Additional information:

- When you run `npm run dev` instead of using the build, you can see that the `console.log` on the server actually has the value, instead of being `undefined`:
image
Just on the client it is still `undefined`.

- I checked this behavior also for Next.js `v11.1.2` - there, it is not happening. The variable has its value on the client as expected.

### PR DESCRIPTION
**Pull request by kwonoj**
This PR attempts to fix #31855, by loosening conditions to determine what to drop when swc runs transform. Currently, it drops all the export declaration if it's being referenced only in getstatic* in local scope. But as `export` implies, there's no guarantee given export will be used in other modules even if it's not being used in local scope. PR tries to not to drop exports declarations as much if it's not being used locally other than getstatic*. This makes dropping bit ineffecient, but as long as we can't cross-ref across modules that's something unavoidable in my opinion.

I don't think implementation itself is quite acceptable: probably need review & revise to the logics. 

## Bug

- Attempt to close #31855

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| buildDuration | 15.6s | 15.5s | -112ms |
| buildDurationCached | 6.2s | 6.1s | -72ms |
| nodeModulesSize | 485 MB | 485 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.207 | 3.22 | ⚠️ +0.01 |
| / avg req/sec | 779.59 | 776.41 | ⚠️ -3.18 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.395 | 1.383 | -0.01 |
| /error-in-render avg req/sec | 1791.67 | 1807.96 | +16.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72 kB | 72 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.74 kB | 5.74 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16 kB | 16 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 461 B | 461 B | ✓ |
| Overall change | 461 B | 461 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| buildDuration | 18.3s | 18.5s | ⚠️ +232ms |
| buildDurationCached | 6.2s | 6.1s | -43ms |
| nodeModulesSize | 485 MB | 485 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.169 | 3.192 | ⚠️ +0.02 |
| / avg req/sec | 788.97 | 783.2 | ⚠️ -5.77 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.364 | 1.343 | -0.02 |
| /error-in-render avg req/sec | 1833.32 | 1861.96 | +28.64 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.7 kB | 28.7 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.6 kB | 72.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.02 kB | 3.02 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.78 kB | 5.78 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.44 kB | 2.44 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.1 kB | 16.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 457 B | 457 B | ✓ |
| Overall change | 457 B | 457 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | kwonoj/next.js fix-less-aggressive-ssr-drop | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 9d5c91da206fa004b268f2e275b7ee7847f44d5a

File: packages/next-swc/crates/core/src/next_ssg.rs [hunk 1]
```diff
@@ -132,12 +132,34 @@ impl Fold for Analyzer<'_> {
...
     }
 
+    fn fold_export_decl(&mut self, s: ExportDecl) -> ExportDecl {
+        if let Decl::Var(d) = &s.decl {
+            if d.decls.is_empty() {
+                return s;
+            }
+
+            if let Pat::Ident(id) = &d.decls[0].name {
+                let ssg_exports = &["getStaticProps", "getStaticPaths", "getServerSideProps"];
```
Comment (ijjk) [inline packages/next-swc/crates/core/src/next_ssg.rs:152]: Should we define this at the top-level so it can be shared instead of re-defining it each time or could we re-use the `is_data_identifier` method here?

**Review by ijjk — COMMENTED** [review]
Are we able to add a test case for this to ensure it's working as expected?

File: packages/next-swc/crates/core/src/next_ssg.rs (hunk 1 above)
Comment (kwonoj) [reply packages/next-swc/crates/core/src/next_ssg.rs:152]: Probably yes. I wrote PR to gut check if this sounds correct idea first before trying to refactor.

**Comment by kwonoj** [comment]
> Are we able to add a test case for this to ensure it's working as expected?

Added one simple test cases to verify its behavior.

**Review by timneutkens — APPROVED** [review]
