### PR TITLE
fix navigation applying stale data when triggered from global not found

### LINKED ISSUE #61956: Calling `headers()` in root layout breaks navigations while in 404 page
### Link to the code that reproduces this issue

https://github.com/panteliselef/nextjs-404-route-bug

### To Reproduce

1. Build and serve the app
1. Click the link to go to 404 page. 1 
1. From the 404 page, attempt to go back to the `/` root via the `<Link>` in the navbar, url changes but we still see the 404 page

### Current vs. Expected behavior

From the 404 page, navigate correctly back to `'/'`. 
To see the expected behaviour
1. Remove `headers()` from `RootLayout`  

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: 8.15.0
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next start (local), Vercel (Deployed)

### Additional context

I tested the app in next@14.1.0 and next@13.5.6, same issue in both

<sub>[NEXT-2481](https://linear.app/vercel/issue/NEXT-2481/calling-headers-in-root-layout-breaks-navigations-while-in-404-page)</sub>

### PR DESCRIPTION
**Pull request by ztanner**
### What
When a global not found page is rendered, and when the not-found page or containing layout has a link with `prefetch: auto` back to the root page, the router would update the URL but not correctly swap out the not-found component with the page component.

### Why
With auto prefetching (which is the default when `prefetch` is left unspecified on a link), the router will perform a partial prefetch on dynamic pages. This means it'll fetch the flight data _without_ React nodes and store it in the prefetch cache. On navigation, this is used to determine where we already have cached React nodes and where we need to trigger a lazy fetch to get new data. However, global not found pages are peculiar in that they will always contain a data path like: `['', { children: ['__PAGE__', {}] }]` since they are inserted at the root. This means that if there's also a page component that corresponds with the same path, the router will incorrectly think it already has cache node data for it.

### How
During SSR when the `asNotFound` flag signals to the renderer that the component we're rendering is matching the global not-found page, we modify the segment key to be something unique so the data path won't collide with a top-level page.

In [fc01c8e](https://github.com/vercel/next.js/pull/62033/commits/fc01c8e7f7970253a241f00b2a9879fb35b03276) I added handling only on the server to modify the segment key. This still fixes the issue, but at the cost of triggering an MPA navigation on the client because it's treated as a root layout change

In [69d5687](https://github.com/vercel/next.js/pull/62033/commits/69d5687765b4ab9dbd974e8db5c6c87a6a3084d4) I added client handling to not treat this special segment key as a root layout change, and to signal to the router it needs to refetch the data. This ensures we don't do an MPA navigation. 

Fixes #61956
Closes NEXT-2481

### CODE REVIEW

**Comment by ztanner** [comment]
* `canary`
  * **#62033** <a href="https://app.graphite.dev/github/pr/vercel/next.js/62033?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ztanner and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 02-13-fix_navigation_applying_stale_data_when_triggered_from_global_not_found | Change |
| - | - | - | - |
| buildDuration | 19.4s | 19.3s | N/A |
| buildDurationCached | 7.1s | 7s | N/A |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +14.7 kB |
| nextStartRea..uration (ms) | 426ms | 433ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-13-fix_navigation_applying_stale_data_when_triggered_from_global_not_found | Change |
| - | - | - | - |
| 1068-HASH.js gzip | 30 kB | 30 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.5 kB | 53.5 kB | N/A |
| 4944-HASH.js gzip | 4.96 kB | 4.96 kB | N/A |
| 8423.HASH.js gzip | 181 B | 181 B | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 244 B | N/A |
| main-HASH.js gzip | 32 kB | 32 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 47.1 kB | 47.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-13-fix_navigation_applying_stale_data_when_triggered_from_global_not_found | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-13-fix_navigation_applying_stale_data_when_triggered_from_global_not_found | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 196 B | ✓ |
| _error-HASH.js gzip | 184 B | 183 B | N/A |
| amp-HASH.js gzip | 503 B | 504 B | N/A |
| css-HASH.js gzip | 323 B | 324 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.51 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 353 B | 351 B | N/A |
| hooks-HASH.js gzip | 370 B | 370 B | ✓ |
| image-HASH.js gzip | 4.21 kB | 4.2 kB | N/A |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.68 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 313 B | 314 B | N/A |
| script-HASH.js gzip | 386 B | 385 B | N/A |
| withRouter-HASH.js gzip | 309 B | 311 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 931 B | 931 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-13-fix_navigation_applying_stale_data_when_triggered_from_global_not_found | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-13-fix_navigation_applying_stale_data_when_triggered_from_global_not_found | Change |
| - | - | - | - |
| index.html gzip | 529 B | 528 B | N/A |
| link.html gzip | 541 B | 540 B | N/A |
| withRouter.html gzip | 525 B | 523 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-13-fix_navigation_applying_stale_data_when_triggered_from_global_not_found | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94.4 kB | 94.4 kB | N/A |
| page.js gzip | 151 kB | 151 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-13-fix_navigation_applying_stale_data_when_triggered_from_global_not_found | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 626 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 44.4 kB | 44.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.94 kB | 1.94 kB | ✓ |
| Overall change | 2.1 kB | 2.1 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-13-fix_navigation_applying_stale_data_when_triggered_from_global_not_found | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 166 kB | 166 kB | N/A |
| app-page-exp..prod.js gzip | 95.5 kB | 95.5 kB | N/A |
| app-page-tur..prod.js gzip | 97.2 kB | 97.3 kB | N/A |
| app-page-tur..prod.js gzip | 91.7 kB | 91.7 kB | N/A |
| app-page.run...dev.js gzip | 136 kB | 136 kB | N/A |
| app-page.run..prod.js gzip | 90.2 kB | 90.3 kB | N/A |
| app-route-ex...dev.js gzip | 22 kB | 22 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.7 kB | 9.7 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-turbo...prod.js gzip | 22.1 kB | 22.1 kB | ✓ |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | ✓ |
| pages.runtim..prod.js gzip | 22.1 kB | 22.1 kB | ✓ |
| server.runti..prod.js gzip | 49.9 kB | 49.9 kB | ✓ |
| Overall change | 248 kB | 248 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 0cf2e7379b78cc16156ac88791037455b568fd70

**Review by ijjk — APPROVED** [review]

File: packages/next/src/client/components/router-reducer/is-navigating-to-new-root-layout.ts [hunk 1]
```diff
@@ -7,6 +8,10 @@ export function isNavigatingToNewRootLayout(
   // Compare segments
   const currentTreeSegment = currentTree[0]
   const nextTreeSegment = nextTree[0]
+
+  // We currently special-case the global not found segment key, but we don't it to be treated as a root layout change
```
Comment (ijjk) [inline packages/next/src/client/components/router-reducer/is-navigating-to-new-root-layout.ts:12]:
```suggestion
  // We currently special-case the global not found segment key, but we don't want it to be treated as a root layout change
```

**Comment by ijjk** [comment]
## Failing test suites 
Commit: a547b3a3ffa68ef2e65ef15ac9a8c0187f3fb45b

`pnpm test-dev test/e2e/app-dir/interception-route-prefetch-cache/interception-route-prefetch-cache.test.ts` (PPR)
- interception-route-prefetch-cache > runtime = edge > should render the correct interception when two distinct layouts share the same path structure

<details>
<summary>Expand output</summary>

  ● interception-route-prefetch-cache › runtime = edge › should render the correct interception when two distinct layouts share the same path structure

    TIMED OUT: /Intercepted on Foo Page/



    TimeoutError: page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('#slot')
    ============================================================

      636 |
      637 |   if (hardError) {
    > 638 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      639 |   }
      640 |   return false
      641 | }

      at check (lib/next-test-utils.ts:638:11)
      at Object.<anonymous> (e2e/app-dir/interception-route-prefetch-cache/interception-route-prefetch-cache.test.ts:21:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by huozhi — APPROVED** [review]
