### PR TITLE
Fix SSR error handling in the global scope

### LINKED ISSUE #3864: Dev swallowing errors and showing 404 instead, since 5.0.1-canary.5
When developing, it's useful to see if changed dependencies break something. Since 5.0.1-canary.5, instead of error overlays, under certain circumstances there is now a blank 404 page, with no console errors on either client or server console.

I upgraded react-apollo to 2.1.0-beta.0. There is some breakage with this package in my codebase which under 5.0.1-canary.4 shows the following in the browser:

```
Object(...) is not a function
TypeError: Object(...) is not a function
    at Object.libApolloMutationsCreateCredentialsTs (/src/app/lib/apollo/queries/withCredentials.ts:5:19)
    at __webpack_require__ (/src/app/.next/dist/bundles/pages/webpack/bootstrap 09a1c451b2869cd2289b:25:1)
    at Object.libApolloMutationsIndexTs (/src/app/.next/dist/bundles/pages/home.js:2367:60)
```

This makes it very clear that something is wrong with the apollo setup. Under 5.0.1-canary.5, hitting the same page gives a blank 404 page, which makes it very hard to figure out what went wrong. This behaviour is still present in canary.6.

(This report is not about the breakage itself, but the lack of error info.)

Perhaps this is because I'm doing SSR, and Next is not loading a script it knows is broken? Given the few patches that landed between canary.4 and canary.5, this one looks like the most likely candidate: https://github.com/zeit/next.js/pull/3749.

### PR DESCRIPTION
**Pull request by arunoda**
Fixes https://github.com/zeit/next.js/issues/3864

* [x] - Implement the fix
* [x] - Add a test case

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]

File: server/require.js [hunk 1]
```diff
@@ -55,9 +55,18 @@ export function getPagePath (page, {dir, dist}) {
 
 export default function requirePage (page, {dir, dist}) {
   const pagePath = getPagePath(page, {dir, dist})
+
   try {
     return require(pagePath)
   } catch (err) {
-    throw pageNotFoundError(page)
+    console.error(err)
```
Comment (timneutkens) [inline server/require.js]: This should be under the `MODULE_NOT_FOUND` check, because otherwise *every* page that doesn't exist will be shot into the console. This includes things like favicon.ico and robots.txt in development.

**Comment by majelbstoat** [comment]
Thank you!
