### PR TITLE
fix router revalidation behavior for dynamic interception routes

### LINKED ISSUE #59796: revalidateTag and revalidatePath redirect to intercepting route when inside dynamic route
### Link to the code that reproduces this issue

https://github.com/kahnclusions/nextgram/tree/bug/revalidate-tag-reloads

### To Reproduce

1. Open `http://localhost:3000/en` in a browser
2. Click on a photo
3. Click on "Click me to see the bug" to see the bug

### Current vs. Expected behavior

I expected
* the modal to remain visible
* the rest of my click handler to execute
* the component state to update
* the component to re-render and display the text "The answer is: 42"

Instead
* After the server action completes, the page immediately reloads on the intercepting route. It never executes the rest of the click handler.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020
Binaries:
  Node: 20.8.1
  npm: 10.1.0
  Yarn: N/A
  pnpm: 8.10.5
Relevant Packages:
  next: 14.0.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

The change that causes the bug is adding the `[locale]` directory and putting everything into the dynamic route. This is a necessary step for doing basic internationalisation. The server action with revalidateTag/Path seems to work fine when added to the base NextGram repo, but after adding the `[locale]/` directory and moving everything in there causes it to break.

I can reproduce the issue locally in multiple browsers.

The code here never executes when the bug happens: https://github.com/vercel-labs/nextgram/compare/main...kahnclusions:nextgram:bug/revalidate-tag-reloads?expand=1#diff-17ba861615c90b344dff6c88255f992f1cfaae5da0f4d414d9e64d8f518443d8R15-R21

<sub>[NEXT-2079](https://linear.app/vercel/issue/NEXT-2079/revalidatetag-and-revalidatepath-redirect-to-intercepting-route-when)</sub>

### PR DESCRIPTION
**Pull request by ztanner**
### What
When calling `revalidatePath` or `revalidateTag` in a server action for an intercepted route with dynamic segments, the page would do a full browser refresh.

### Why
When constructing rewrites for interception routes, the route params leading up to the interception route are "voided" with a `__NEXT_EMPTY_PARAM__` demarcation. When it comes time to look up the values for these dynamic segments, since the params aren't going to be part of the URL, they get matched via `FlightRouterState` ([ref](https://github.com/vercel/next.js/blob/d67d658ce7396c4b6be1b724be5f45763d5a1803/packages/next/src/server/app-render/app-render.tsx#L153-L201)). 

The `shouldProvideFlightRouterState` variable only passes it through for RSC requests; however, since the server action will perform the action & return the flight data in a single pass, that means the updated tree from the server action isn't going to receive the `FlightRouterState` when constructing the new tree. This means the old tree will have a `["locale", "en", "d"]` segment, and the new tree from the server action will have `"[locale]"`. When the router detects this kind of segment mismatch, it assumes the user navigated to a new root layout, and triggers an MPA navigation. 

### How
This unconditionally provides the `FlightRouterState` to `makeGetDynamicParamFromSegment` so that it can properly extract dynamic params for interception routes. We currently enforce interception routes to be dynamic due to this `FlightRouterState` dependency.

Fixes #59796
Closes NEXT-2079

### CODE REVIEW

**Comment by ztanner** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vercel/next.js/63768?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#63768** <a href="https://app.graphite.dev/github/pr/vercel/next.js/63768?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#63608** <a href="https://app.graphite.dev/github/pr/vercel/next.js/63608?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#63607** <a href="https://app.graphite.dev/github/pr/vercel/next.js/63607?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#63606** <a href="https://app.graphite.dev/github/pr/vercel/next.js/63606?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ztanner and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: d67d658ce7396c4b6be1b724be5f45763d5a1803

`TURBOPACK=1 pnpm test-start test/e2e/app-dir/dynamic-interception-route-revalidate/parallel-routes-revalidation.test.ts` (turbopack)
- dynamic-interception-route-revalidate > should refresh the dynamic intercepted route when the interception route is revalidated

<details>
<summary>Expand output</summary>

  ● dynamic-interception-route-revalidate › should refresh the dynamic intercepted route when the interception route is revalidated

    thrown: "Exceeded timeout of 60000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

       7 |   })
       8 |
    >  9 |   it('should refresh the dynamic intercepted route when the interception route is revalidated', async () => {
         |   ^
      10 |     const browser = await next.browser('/en')
      11 |
      12 |     // trigger the interception

      at it (e2e/app-dir/dynamic-interception-route-revalidate/parallel-routes-revalidation.test.ts:9:3)
      at Object.describe (e2e/app-dir/dynamic-interception-route-revalidate/parallel-routes-revalidation.test.ts:4:1)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 03-27-fix_router_revalidation_behavior_for_dynamic_interception_routes | Change |
| - | - | - | - |
| buildDuration | 14s | 13.9s | N/A |
| buildDurationCached | 7.5s | 6.1s | N/A |
| nodeModulesSize | 198 MB | 198 MB | ⚠️ +29.7 kB |
| nextStartRea..uration (ms) | 411ms | 401ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 03-27-fix_router_revalidation_behavior_for_dynamic_interception_routes | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 31 kB | 31.3 kB | ⚠️ +305 B |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | ✓ |
| 8299-HASH.js gzip | 5.04 kB | 5.04 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 242 B | 242 B | ✓ |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 130 kB | 131 kB | ⚠️ +305 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-27-fix_router_revalidation_behavior_for_dynamic_interception_routes | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-27-fix_router_revalidation_behavior_for_dynamic_interception_routes | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.21 kB | 4.21 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.57 kB | 6.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-27-fix_router_revalidation_behavior_for_dynamic_interception_routes | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-27-fix_router_revalidation_behavior_for_dynamic_interception_routes | Change |
| - | - | - | - |
| index.html gzip | 529 B | 528 B | N/A |
| link.html gzip | 541 B | 541 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.06 kB | 1.06 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-27-fix_router_revalidation_behavior_for_dynamic_interception_routes | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.3 kB | 95.3 kB | N/A |
| page.js gzip | 3.04 kB | 3.04 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-27-fix_router_revalidation_behavior_for_dynamic_interception_routes | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 622 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-27-fix_router_revalidation_behavior_for_dynamic_interception_routes | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | N/A |
| app-page-exp..prod.js gzip | 97 kB | 97 kB | N/A |
| app-page-tur..prod.js gzip | 98.7 kB | 98.7 kB | N/A |
| app-page-tur..prod.js gzip | 93 kB | 93 kB | N/A |
| app-page.run...dev.js gzip | 144 kB | 144 kB | N/A |
| app-page.run..prod.js gzip | 91.5 kB | 91.5 kB | N/A |
| app-route-ex...dev.js gzip | 21.4 kB | 21.4 kB | ✓ |
| app-route-ex..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| app-route.ru...dev.js gzip | 21 kB | 21 kB | ✓ |
| app-route.ru..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim...dev.js gzip | 23.1 kB | 23.1 kB | ✓ |
| pages.runtim..prod.js gzip | 22.4 kB | 22.4 kB | ✓ |
| server.runti..prod.js gzip | 51 kB | 51 kB | ✓ |
| Overall change | 250 kB | 250 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 03-27-fix_router_revalidation_behavior_for_dynamic_interception_routes | Change |
| - | - | - | - |
| 0.pack gzip | 1.57 MB | 1.58 MB | ⚠️ +7.28 kB |
| index.pack gzip | 106 kB | 106 kB | N/A |
| Overall change | 1.57 MB | 1.58 MB | ⚠️ +7.28 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>2453-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: d67d658ce7396c4b6be1b724be5f45763d5a1803

File: packages/next/src/server/app-render/app-render.tsx [hunk 1]
```diff
@@ -787,7 +787,9 @@ async function renderToHTMLOrFlightImpl(
     isPrefetch: isPrefetchRSCRequest,
     requestTimestamp,
     appUsingSizeAdjustment,
-    providedFlightRouterState,
+    providedFlightRouterState: shouldProvideFlightRouterState
```
Comment (feedthejim) [inline packages/next/src/server/app-render/app-render.tsx:790]: wonder if we should have better naming here 👀

**Review by feedthejim — APPROVED** [review]

**Review by timneutkens — APPROVED** [review]
