### PR TITLE
fixes #31060: NullReferenceException

### LINKED ISSUE #31060: NullReferenceException: "packages/next/client/head-manager.ts"
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next export

### Describe the Bug

NullReferenceException

There was another NullReferenceException in this file(`packages/next/client/head-manager.ts`) that has been resolved before. The related issue and the PR are below.

Issue: https://github.com/vercel/next.js/issues/30604
PR: https://github.com/vercel/next.js/pull/30919

I did not understand the point of using exclamation marks for the possible Null Reference Exceptions instead of question marks as a shorthand?

I will refactor the file again that the file name has been provided in the issue title, and will open another PR.
Or, maybe the Next.js team can be considered to refactor the related file from scratch as well. 

Thanks in advance.

### Expected Behavior

Should work like a charm.

### To Reproduce

Using `next/head` within any of the components and deploying the app with `next export`.

```js
import Head from 'next/head';
```

### PR DESCRIPTION
**Pull request by furcan**
- Fixes https://github.com/vercel/next.js/issues/31060

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 20.7s | 20.6s | -180ms |
| buildDurationCached | 4.1s | 4.1s | ⚠️ +26ms |
| nodeModulesSize | 332 MB | 332 MB | ⚠️ +398 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.547 | 3.516 | -0.03 |
| / avg req/sec | 704.76 | 711.02 | +6.26 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.946 | 1.972 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1284.57 | 1268.06 | ⚠️ -16.51 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28.1 kB | ⚠️ +27 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ⚠️ +27 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 522 B | 521 B | -1 B |
| link.html gzip | 535 B | 533 B | -2 B |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -116,7 +116,11 @@
         for (
           var i = 0, j = headCountEl.previousElementSibling;
           i < headCount;
-          i++, j = j.previousElementSibling
+          i++,
+            j =
+              (j === null || j === void 0
+                ? void 0
+                : j.previousElementSibling) || null
         ) {
           var ref;
           if (
@@ -142,7 +146,12 @@
             return true;
           });
         oldTags.forEach(function(t) {
-          return t.parentNode.removeChild(t);
+          var ref;
+          return t === null || t === void 0
+            ? void 0
+            : (ref = t.parentNode) === null || ref === void 0
+            ? void 0
+            : ref.removeChild(t);
         });
         newTags.forEach(function(t) {
           return headEl.insertBefore(t, headCountEl);
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8b1326231534a220.js"
+      src="/_next/static/chunks/main-04aa15efc127d73e.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8b1326231534a220.js"
+      src="/_next/static/chunks/main-04aa15efc127d73e.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8b1326231534a220.js"
+      src="/_next/static/chunks/main-04aa15efc127d73e.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 22.7s | 22.4s | -314ms |
| buildDurationCached | 4.1s | 4.1s | -4ms |
| nodeModulesSize | 332 MB | 332 MB | ⚠️ +398 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.673 | 3.61 | -0.06 |
| / avg req/sec | 680.59 | 692.43 | +11.84 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.83 | 1.951 | ⚠️ +0.12 |
| /error-in-render avg req/sec | 1365.84 | 1281.25 | ⚠️ -84.59 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ⚠️ +13 B |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +13 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 521 B | 522 B | ⚠️ +1 B |
| link.html gzip | 534 B | 535 B | ⚠️ +1 B |
| withRouter.html gzip | 515 B | 516 B | ⚠️ +1 B |
| Overall change | 1.57 kB | 1.57 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -116,7 +116,11 @@
         for (
           var i = 0, j = headCountEl.previousElementSibling;
           i < headCount;
-          i++, j = j.previousElementSibling
+          i++,
+            j =
+              (j === null || j === void 0
+                ? void 0
+                : j.previousElementSibling) || null
         ) {
           var ref;
           if (
@@ -142,7 +146,12 @@
             return true;
           });
         oldTags.forEach(function(t) {
-          return t.parentNode.removeChild(t);
+          var ref;
+          return t === null || t === void 0
+            ? void 0
+            : (ref = t.parentNode) === null || ref === void 0
+            ? void 0
+            : ref.removeChild(t);
         });
         newTags.forEach(function(t) {
           return headEl.insertBefore(t, headCountEl);
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8b1326231534a220.js"
+      src="/_next/static/chunks/main-04aa15efc127d73e.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8b1326231534a220.js"
+      src="/_next/static/chunks/main-04aa15efc127d73e.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8b1326231534a220.js"
+      src="/_next/static/chunks/main-04aa15efc127d73e.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: de9d4c606e7c7da68991f3b2952a6628be024e63

**Comment by furcan** [comment]
Hi,
Any comments?
Thanks in advance.

**Review by timneutkens — DISMISSED** [review]
Could you add an integration test for this?

File: packages/next/client/head-manager.ts [hunk 1]
```diff
@@ -60,7 +60,7 @@ function updateElements(type: string, components: JSX.Element[]): void {
   for (
     let i = 0, j = headCountEl.previousElementSibling;
     i < headCount;
-    i++, j = j!.previousElementSibling
+    i++, j = j?.previousElementSibling || null
```
Comment (styfle) [inline packages/next/client/head-manager.ts:63]:
```suggestion
    i++, j = j?.previousElementSibling
```

I don't think null is necessary

Comment (furcan) [reply packages/next/client/head-manager.ts:63]: The second commit that related to this. 

"Type 'undefined' is not assignable to type 'Element | null'"

Thanks.

File: packages/next/client/head-manager.ts [hunk 2]
```diff
@@ -60,7 +60,7 @@ function updateElements(type: string, components: JSX.Element[]): void {
...
   ) {
     if (j?.tagName?.toLowerCase() === type) {
       oldTags.push(j!)
```
Comment (styfle) [inline packages/next/client/head-manager.ts:66]:
```suggestion
      oldTags.push(j)
```

This can be removed now

File: packages/next/client/head-manager.ts [hunk 3]
```diff
@@ -79,7 +79,7 @@ function updateElements(type: string, components: JSX.Element[]): void {
     }
   )
 
-  oldTags.forEach((t) => t.parentNode!.removeChild(t))
+  oldTags.forEach((t) => t?.parentNode?.removeChild(t))
```
Comment (styfle) [inline packages/next/client/head-manager.ts:82]:
```suggestion
  oldTags.forEach((t) => t.parentNode?.removeChild(t))
```

I don't think `t` can be null/undefined anymore

**Review by styfle — COMMENTED** [review]
I agree we need a test.

I suspect that the actual failure is that the meta element is missing from the DOM.

Try this on your page:

```js
document.querySelector('meta[name=next-head-count]')
```

**Comment by furcan** [comment]
Hi @styfle ,

I already checked the `'meta[name=next-head-count]'` meta element before creating the issue and PR. 
And also, the error would be on line 61(head-manager.ts) if this element would be missing.

I already have that meta element in my application and it has 46 content.

I think these null checks in this PR (with your additional suggestions) will be solved the issue.

In addition, there is a ScreenShot below that might be helpful. (A console demonstration)

console-example

**Review by styfle — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 24.6s | 24.4s | -222ms |
| buildDurationCached | 4.8s | 4.8s | ⚠️ +11ms |
| nodeModulesSize | 332 MB | 332 MB | ⚠️ +289 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.112 | 4.173 | ⚠️ +0.06 |
| / avg req/sec | 608.04 | 599.13 | ⚠️ -8.91 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.048 | 2.077 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1220.58 | 1203.9 | ⚠️ -16.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28.1 kB | ⚠️ +21 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ⚠️ +21 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 521 B | 522 B | ⚠️ +1 B |
| link.html gzip | 534 B | 535 B | ⚠️ +1 B |
| withRouter.html gzip | 515 B | 516 B | ⚠️ +1 B |
| Overall change | 1.57 kB | 1.57 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -116,7 +116,11 @@
         for (
           var i = 0, j = headCountEl.previousElementSibling;
           i < headCount;
-          i++, j = j.previousElementSibling
+          i++,
+            j =
+              (j === null || j === void 0
+                ? void 0
+                : j.previousElementSibling) || null
         ) {
           var ref;
           if (
@@ -142,7 +146,10 @@
             return true;
           });
         oldTags.forEach(function(t) {
-          return t.parentNode.removeChild(t);
+          var ref;
+          return (ref = t.parentNode) === null || ref === void 0
+            ? void 0
+            : ref.removeChild(t);
         });
         newTags.forEach(function(t) {
           return headEl.insertBefore(t, headCountEl);
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a15e759cfdc093b7.js"
+      src="/_next/static/chunks/main-c7b7c9634a5a8b7e.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a15e759cfdc093b7.js"
+      src="/_next/static/chunks/main-c7b7c9634a5a8b7e.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a15e759cfdc093b7.js"
+      src="/_next/static/chunks/main-c7b7c9634a5a8b7e.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 27.3s | 26.9s | -341ms |
| buildDurationCached | 4.7s | 4.8s | ⚠️ +39ms |
| nodeModulesSize | 332 MB | 332 MB | ⚠️ +289 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.078 | 4.084 | ⚠️ +0.01 |
| / avg req/sec | 613.07 | 612.16 | ⚠️ -0.91 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.103 | 2.094 | -0.01 |
| /error-in-render avg req/sec | 1188.9 | 1193.89 | +4.99 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ⚠️ +13 B |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +13 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 521 B | 522 B | ⚠️ +1 B |
| link.html gzip | 534 B | 535 B | ⚠️ +1 B |
| withRouter.html gzip | 515 B | 516 B | ⚠️ +1 B |
| Overall change | 1.57 kB | 1.57 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -116,7 +116,11 @@
         for (
           var i = 0, j = headCountEl.previousElementSibling;
           i < headCount;
-          i++, j = j.previousElementSibling
+          i++,
+            j =
+              (j === null || j === void 0
+                ? void 0
+                : j.previousElementSibling) || null
         ) {
           var ref;
           if (
@@ -142,7 +146,10 @@
             return true;
           });
         oldTags.forEach(function(t) {
-          return t.parentNode.removeChild(t);
+          var ref;
+          return (ref = t.parentNode) === null || ref === void 0
+            ? void 0
+            : ref.removeChild(t);
         });
         newTags.forEach(function(t) {
           return headEl.insertBefore(t, headCountEl);
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a15e759cfdc093b7.js"
+      src="/_next/static/chunks/main-c7b7c9634a5a8b7e.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a15e759cfdc093b7.js"
+      src="/_next/static/chunks/main-c7b7c9634a5a8b7e.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a15e759cfdc093b7.js"
+      src="/_next/static/chunks/main-c7b7c9634a5a8b7e.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: c15475b07a38123b8f0b91d29c24586e6eb4e3c8

**Comment by styfle** [comment]
I think this is safe to merge, even without tests, since its unlikely to cause any harm and probably wont regress because TS will complain if someone tries to remove the `?` in a future PR 👍
