### PR TITLE
Fix server not closing properly in dev mode 

### LINKED ISSUE #2540: Server.close does not allow Node process to exit in dev mode
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Assuming I've assigned an instance of next to the variable ```app``` and called ```app.prepare()```, calling ```app.close()``` should stop all middleware and allow the Node process to exit.

## Current Behavior

In dev mode, the Node process keeps running with some middleware remaining active.  If a page was recently accessed, the "Disposing active pages" message will eventually be logged after ```app.close()``` was called, indicating that something has not stopped.  It will not stop after disposing pages either.

When not running in dev mode, the Node process will exit as expected.

## Steps to Reproduce (for bugs)

1. Follow the basic setup instructions, then create the following ```server.js```:

```
const path = require('path');

const { createServer } = require('http')
const { parse } = require('url')
const next = require('next')

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev, dir: path.resolve(__dirname) })
const handle = app.getRequestHandler()

app.prepare().then(() => {
  const http = createServer((req, res) => {
    const { parsedUrl } = parse(req.url, true)
    handle(req, res, parsedUrl)
      .then(() => http.close())
      .then(() => app.close())
  })

  http.listen(8080)
})
```

2. Build with ```npm run build```

3. Run ```node server.js``` and point browser at app.  The Node process will NOT exit after request is handled.  Must Ctrl-C to exit.

4. Run ```NODE_ENV=production node server.js``` and point browser at app.  The Node process will exit after request is handled.

## Context

Came across this while working on a monitoring app to start/discover/stop instances of a Next app.  Instances wouldn't exit when told to via a ```/stop``` http request.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   3.0.1-beta.13      |
| node    |    7.10.0     |
| OS      |    Ubuntu 14.04.5 LTS     |
| browser |    Chrome     |

### PR DESCRIPTION
**Pull request by lucleray**
Fixes #2540

Hello,

I am suggesting here a solution for the issue #2540.

The issue is coming from the hot-reloader staying alive after the server has been stopped.

The hot-reloader starts 3 "webpack middlewares" :
1. `webpackDevMiddleware`
2. `webpackHotMiddleware`
3. `onDemandEntryHandler`

1 is stopped when the hot reloader is stopped.
2 is stopping as soon as all the connections in the browser are stopped (all tabs are closed).
3 is the one causing the server stay alive.

3 starts a setInterval :

https://github.com/zeit/next.js/blob/9263ad13f73cb4583720f3b284cf6015a7c50f47/server/on-demand-entry-handler.js#L105-L108

The solution is to simply `unref` the interval so that it is does not keep the process active : https://nodejs.org/api/timers.html#timers_timeout_unref

### CODE REVIEW

File: server/on-demand-entry-handler.js [hunk 1]
```diff
@@ -107,6 +107,8 @@ export default function onDemandEntryHandler (devMiddleware, compiler, {
     disposeInactiveEntries(devMiddleware, entries, lastAccessPages, maxInactiveAge)
   }, 5000)
 
+  disposeHandler.unref()
```
Comment (oliviertassinari) [inline server/on-demand-entry-handler.js]: [unref() API docs](https://nodejs.org/api/timers.html#timers_timeout_unref)

**Comment by lucleray** [comment]
I think some tests ran during the issue with npm packages missing :
https://status.npmjs.org/incidents/41zfb8qpvrdj

Could someone re-run them to check if they are passing now ?

**Review by arunoda — APPROVED** [review]
This looks great.
