### PR TITLE
fix: issue #18338 - don't add a trailing slash to external links

### LINKED ISSUE #18338: Trailing slashes appends slashes to external links
# Bug report

## Describe the bug

Using the configuration Trailing slashes true, <Link></Link> components append the slash to external URLs.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Repo: https://github.com/conanbatt/nextjs-export-slashes
Steps:
```
// next.config.js
module.exports = {
  trailingSlash: true,
}
```
And
```
// pages/index.js
<Link href="https://example.com">Without slash</Link>
```

## Expected behavior

1- External links do not append trailing slashes.
2- Export and next dev exhibit the same behavior? (```next dev``` does not append trailing slash)

## Screenshots

Result
```
<h1 class="Home_title__3DjR7">Welcome to <a href="https://nextjs.org">Without slash</a></h1>
<h1 class="Home_title__3DjR7">Welcome to <a href="https://nextjs.org/">With slash?</a></h1>
```

## Additional context

If I remember right, Link components should not be used for external urls. This used to be caught by Next. It would be nice to detect external or absolute paths for trailing slash purposes.

### PR DESCRIPTION
**Pull request by toshi1127**
## Description

Fixes #18338 - Fixed an issue with `trailingSlash: true` adding a slash to the end of an external link.

After
```
<h1 class="Home_title__3DjR7">Welcome to <a href="https://nextjs.org">Without slash</a></h1>
<h1 class="Home_title__3DjR7">Welcome to <a href="https://nextjs.org">With slash?</a></h1>
```

Before
```
<h1 class="Home_title__3DjR7">Welcome to <a href="https://nextjs.org">Without slash</a></h1>
<h1 class="Home_title__3DjR7">Welcome to <a href="https://nextjs.org/">With slash?</a></h1>
```

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| buildDuration | 14.2s | 13.7s | -481ms |
| nodeModulesSize | 90.1 MB | 90.1 MB | ⚠️ +412 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.514 | 2.685 | ⚠️ +0.17 |
| / avg req/sec | 994.57 | 931 | ⚠️ -63.57 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.38 | 1.374 | -0.01 |
| /error-in-render avg req/sec | 1811.42 | 1819.05 | +7.63 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| 677f882d2ed8..3aa9.js gzip | 11.3 kB | 11.3 kB | ⚠️ +8 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-41cbdbf..2c20.js gzip | 7.35 kB | 7.35 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ⚠️ +8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.03 kB | 7.03 kB | ⚠️ +2 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-9cda5a7..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-41ceea0..6b62.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-2d41a89..dule.js gzip | 1.31 kB | 1.31 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.4 kB | 5.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | -1 B |
| withRouter.html gzip | 997 B | 996 B | -1 B |
| Overall change | 3.01 kB | 3.01 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..77.module.js</strong></summary>

```diff
@@ -731,7 +731,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         var urlAsString =
           typeof href === "string"
             ? href
-            : (0, _utils.formatWithValidation)(href);
+            : (0, _utils.formatWithValidation)(href); // Return because it cannot be routed by the Next.js router
+
+        if (!isLocalURL(urlAsString)) {
+          return resolveAs ? [urlAsString] : urlAsString;
+        }
 
         try {
           var finalUrl = new URL(urlAsString, base);
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..05a42e394.js</strong></summary>

```diff
@@ -872,7 +872,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         var urlAsString =
           typeof href === "string"
             ? href
-            : (0, _utils.formatWithValidation)(href);
+            : (0, _utils.formatWithValidation)(href); // Return because it cannot be routed by the Next.js router
+
+        if (!isLocalURL(urlAsString)) {
+          return resolveAs ? [urlAsString] : urlAsString;
+        }
 
         try {
           var finalUrl = new URL(urlAsString, base);
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.4c5c4f34cb1aaaa3c077.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.1ef96d63f1bad54f78ce.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -121,13 +121,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5ddaca5d46f05a42e394.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.abfac8a616acfe982c56.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.4c5c4f34cb1aaaa3c077.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.1ef96d63f1bad54f78ce.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.4c5c4f34cb1aaaa3c077.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.1ef96d63f1bad54f78ce.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -126,13 +126,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5ddaca5d46f05a42e394.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.abfac8a616acfe982c56.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.4c5c4f34cb1aaaa3c077.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.1ef96d63f1bad54f78ce.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.4c5c4f34cb1aaaa3c077.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.1ef96d63f1bad54f78ce.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -121,13 +121,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5ddaca5d46f05a42e394.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.abfac8a616acfe982c56.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.4c5c4f34cb1aaaa3c077.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.1ef96d63f1bad54f78ce.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| buildDuration | 16.4s | 17.9s | ⚠️ +1.6s |
| nodeModulesSize | 90.1 MB | 90.1 MB | ⚠️ +412 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| 677f882d2ed8..3aa9.js gzip | 11.3 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-41cbdbf..2c20.js gzip | 7.35 kB | 7.35 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..c1cf.js gzip | N/A | 11.3 kB | N/A |
| Overall change | 58.3 kB | 58.3 kB | ⚠️ +8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.03 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-9cda5a7..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..dule.js gzip | N/A | 7.03 kB | N/A |
| Overall change | 53.1 kB | 53.1 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-41ceea0..6b62.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-2d41a89..dule.js gzip | 1.31 kB | 1.31 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.4 kB | 5.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _error.js | 1.06 MB | 1.06 MB | ✓ |
| 404.html | 4.73 kB | 4.73 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.06 MB | 1.06 MB | ✓ |
| link.js | 1.11 MB | 1.11 MB | ⚠️ +151 B |
| routerDirect.js | 1.1 MB | 1.1 MB | ⚠️ +151 B |
| withRouter.js | 1.1 MB | 1.1 MB | ⚠️ +151 B |
| Overall change | 5.43 MB | 5.43 MB | ⚠️ +453 B |

</details>

</details>
Commit: 9777f1339d8fa928bf71aef41d1f1227ee26ef35

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| buildDuration | 13.4s | 14.4s | ⚠️ +933ms |
| nodeModulesSize | 90.1 MB | 90.1 MB | ⚠️ +412 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.586 | 2.56 | -0.03 |
| / avg req/sec | 966.56 | 976.41 | +9.85 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.449 | 1.419 | -0.03 |
| /error-in-render avg req/sec | 1725 | 1761.82 | +36.82 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| 677f882d2ed8..3aa9.js gzip | 11.3 kB | 11.3 kB | ⚠️ +8 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-41cbdbf..2c20.js gzip | 7.35 kB | 7.35 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ⚠️ +8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.03 kB | 7.03 kB | ⚠️ +2 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-9cda5a7..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-41ceea0..6b62.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-2d41a89..dule.js gzip | 1.31 kB | 1.31 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.4 kB | 5.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | -1 B |
| withRouter.html gzip | 997 B | 996 B | -1 B |
| Overall change | 3.01 kB | 3.01 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..77.module.js</strong></summary>

```diff
@@ -731,7 +731,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         var urlAsString =
           typeof href === "string"
             ? href
-            : (0, _utils.formatWithValidation)(href);
+            : (0, _utils.formatWithValidation)(href); // Return because it cannot be routed by the Next.js router
+
+        if (!isLocalURL(urlAsString)) {
+          return resolveAs ? [urlAsString] : urlAsString;
+        }
 
         try {
           var finalUrl = new URL(urlAsString, base);
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..05a42e394.js</strong></summary>

```diff
@@ -872,7 +872,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         var urlAsString =
           typeof href === "string"
             ? href
-            : (0, _utils.formatWithValidation)(href);
+            : (0, _utils.formatWithValidation)(href); // Return because it cannot be routed by the Next.js router
+
+        if (!isLocalURL(urlAsString)) {
+          return resolveAs ? [urlAsString] : urlAsString;
+        }
 
         try {
           var finalUrl = new URL(urlAsString, base);
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.4c5c4f34cb1aaaa3c077.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.1ef96d63f1bad54f78ce.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -121,13 +121,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5ddaca5d46f05a42e394.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.abfac8a616acfe982c56.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.4c5c4f34cb1aaaa3c077.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.1ef96d63f1bad54f78ce.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.4c5c4f34cb1aaaa3c077.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.1ef96d63f1bad54f78ce.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -126,13 +126,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5ddaca5d46f05a42e394.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.abfac8a616acfe982c56.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.4c5c4f34cb1aaaa3c077.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.1ef96d63f1bad54f78ce.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.4c5c4f34cb1aaaa3c077.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.1ef96d63f1bad54f78ce.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -121,13 +121,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5ddaca5d46f05a42e394.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.abfac8a616acfe982c56.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.4c5c4f34cb1aaaa3c077.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.1ef96d63f1bad54f78ce.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| buildDuration | 15.5s | 15.4s | -51ms |
| nodeModulesSize | 90.1 MB | 90.1 MB | ⚠️ +412 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| 677f882d2ed8..3aa9.js gzip | 11.3 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-41cbdbf..2c20.js gzip | 7.35 kB | 7.35 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..c1cf.js gzip | N/A | 11.3 kB | N/A |
| Overall change | 58.3 kB | 58.3 kB | ⚠️ +8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.03 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-9cda5a7..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..dule.js gzip | N/A | 7.03 kB | N/A |
| Overall change | 53.1 kB | 53.1 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-41ceea0..6b62.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-2d41a89..dule.js gzip | 1.31 kB | 1.31 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.4 kB | 5.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _error.js | 1.06 MB | 1.06 MB | ✓ |
| 404.html | 4.73 kB | 4.73 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.06 MB | 1.06 MB | ✓ |
| link.js | 1.11 MB | 1.11 MB | ⚠️ +151 B |
| routerDirect.js | 1.1 MB | 1.1 MB | ⚠️ +151 B |
| withRouter.js | 1.1 MB | 1.1 MB | ⚠️ +151 B |
| Overall change | 5.43 MB | 5.43 MB | ⚠️ +453 B |

</details>

</details>
Commit: a303ab7e4fc77a6a635216a782233448c1b78a28

File: packages/next/next-server/lib/router/router.ts [hunk 1]
```diff
@@ -188,6 +188,10 @@ export function resolveHref(
   const base = new URL(currentPath, 'http://n')
   const urlAsString =
     typeof href === 'string' ? href : formatWithValidation(href)
+  // Return because it cannot be routed by the Next.js router
+  if (!isLocalURL(urlAsString)) {
```
Comment (Janpot) [inline packages/next/next-server/lib/router/router.ts:192]: This check is already further up in the code path:
https://github.com/vercel/next.js/blob/a303ab7e4fc77a6a635216a782233448c1b78a28/packages/next/next-server/lib/router/router.ts#L604

Maybe it makes sense to rather move that check in the `push` and `replace` methods, right before `prepareUrlAs`? That way we short-circuit this case earlier and avoid doing the check twice.

Comment (toshi1127) [reply packages/next/next-server/lib/router/router.ts:192]: Sorry if I'm wrong.
I don't think that implementation would solve the problem of trailing slashes in the href attribute for external links.

Since the return value of resolveHref is the base of the href attribute, I thought I needed to modify the resolveHref.
```
  const { href, as } = React.useMemo(() => {
    const [resolvedHref, resolvedAs] = resolveHref(pathname, props.href, true)
    return {
      href: resolvedHref,
      as: props.as
        ? resolveHref(pathname, props.as)
        : resolvedAs || resolvedHref,
    }
  }, [pathname, props.href, props.as])
```

Comment (Janpot) [reply packages/next/next-server/lib/router/router.ts:192]: In this version, there will always be two calls to `isLocalURL(url)`, once in `resolveHref` (to skip appending a slash) and once in `change` (to circumvent client side routing). I was just wondering if it was possible to avoid executing this double logic (`isLocalURL` does a url parse on every call). Probably requires too much refactoring to make it worth doing in this PR, so let's leave it.

**Comment by Mike-Koech** [comment]
Upwork.com//mikekoech588@gmail.com.freelancer-i will attach all my files
there& too, launch 1.00 version of all coded errors.less

**Review by Timer — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| buildDuration | 13s | 12.8s | -216ms |
| nodeModulesSize | 84.9 MB | 84.9 MB | ⚠️ +412 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.366 | 2.296 | -0.07 |
| / avg req/sec | 1056.66 | 1089.02 | +32.36 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.296 | 1.196 | -0.1 |
| /error-in-render avg req/sec | 1929.71 | 2089.81 | +160.1 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| 677f882d2ed8..d4b6.js gzip | 12.6 kB | 12.7 kB | ⚠️ +11 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-43dd9e5..8439.js gzip | 6.48 kB | 6.48 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.8 kB | 58.9 kB | ⚠️ +11 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 8.22 kB | 8.23 kB | ⚠️ +7 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-472f7d5..dule.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.5 kB | 53.5 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d9a15a0..130a.js gzip | 1.57 kB | 1.57 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.98 kB | 7.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-973cce3..dule.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.6 kB | 5.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| index.html gzip | 970 B | 972 B | ⚠️ +2 B |
| link.html gzip | 977 B | 977 B | ✓ |
| withRouter.html gzip | 962 B | 964 B | ⚠️ +2 B |
| Overall change | 2.91 kB | 2.91 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..ae9f202fa.js</strong></summary>

```diff
@@ -1326,7 +1326,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         var urlAsString =
           typeof href === "string"
             ? href
-            : (0, _utils.formatWithValidation)(href);
+            : (0, _utils.formatWithValidation)(href); // Return because it cannot be routed by the Next.js router
+
+        if (!isLocalURL(urlAsString)) {
+          return resolveAs ? [urlAsString] : urlAsString;
+        }
 
         try {
           var finalUrl = new URL(urlAsString, base);
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..bd.module.js</strong></summary>

```diff
@@ -1105,7 +1105,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         var urlAsString =
           typeof href === "string"
             ? href
-            : (0, _utils.formatWithValidation)(href);
+            : (0, _utils.formatWithValidation)(href); // Return because it cannot be routed by the Next.js router
+
+        if (!isLocalURL(urlAsString)) {
+          return resolveAs ? [urlAsString] : urlAsString;
+        }
 
         try {
           var finalUrl = new URL(urlAsString, base);
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9a602fa3ecd8963feabd.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -118,13 +118,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.70c34b1d8a5ae9f202fa.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9a602fa3ecd8963feabd.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9a602fa3ecd8963feabd.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -123,13 +123,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.70c34b1d8a5ae9f202fa.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9a602fa3ecd8963feabd.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9a602fa3ecd8963feabd.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -118,13 +118,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.70c34b1d8a5ae9f202fa.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9a602fa3ecd8963feabd.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| buildDuration | 14.5s | 14.6s | ⚠️ +113ms |
| nodeModulesSize | 84.9 MB | 84.9 MB | ⚠️ +412 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| 677f882d2ed8..d4b6.js gzip | 12.6 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-43dd9e5..8439.js gzip | 6.48 kB | 6.48 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..d9fb.js gzip | N/A | 12.7 kB | N/A |
| Overall change | 58.8 kB | 58.9 kB | ⚠️ +11 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 8.22 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-472f7d5..dule.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..dule.js gzip | N/A | 8.23 kB | N/A |
| Overall change | 53.5 kB | 53.5 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d9a15a0..130a.js gzip | 1.57 kB | 1.57 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.98 kB | 7.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-973cce3..dule.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.6 kB | 5.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | toshi1127/next.js fix/href-in-external-link | Change |
| - | - | - | - |
| _error.js | 916 kB | 916 kB | ✓ |
| 404.html | 4.61 kB | 4.61 kB | ✓ |
| hooks.html | 3.86 kB | 3.86 kB | ✓ |
| index.js | 916 kB | 916 kB | ✓ |
| link.js | 974 kB | 974 kB | ⚠️ +151 B |
| routerDirect.js | 967 kB | 967 kB | ⚠️ +151 B |
| withRouter.js | 967 kB | 967 kB | ⚠️ +151 B |
| Overall change | 4.75 MB | 4.75 MB | ⚠️ +453 B |

</details>

</details>
Commit: 50cc565d014ddd47f203f4c5f5f8fd246854bf54
