### PR TITLE
Always add `?ts=` query for scripts during development

### LINKED ISSUE #53281: Next canary 13.4.13-canary.5 will crash in only Safari when server actions is enabled
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 18.17.0
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 8.6.10
    Relevant Packages:
      next: 13.4.13-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Server Actions / Browser Compatibility / Mac OS

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/tangye1234/nextjs-bug-test

### To Reproduce

install latest 2 versions of next@canary

```
pnpm dev
```

1. In latest Safari, open localhost:3000, the error overlay will 100% come out when server actions is enabled.
2. If I disable server actions, then I long press command+R to keep refresh homepage, the console will also prints error info sometimes.

### Describe the Bug

In Safari 16.5.2

Unhandled Runtime Error
TypeError: undefined is not an object (evaluating 'originalFactory.call')

### Expected Behavior

works well in safari

### Which browser are you using? (if relevant)

Safari 16.5.2

### How are you deploying your application? (if relevant)

_No response_

<sub>[NEXT-1481](https://linear.app/vercel/issue/NEXT-1481/next-canary-13413-canary5-will-crash-in-only-safari-when-server)</sub>

### PR DESCRIPTION
**Pull request by shuding**
Safari caches scripts during the same browsing session no matter what cache headers are set. This makes it impossible to update our runtime bundles (e.g. Webpack's runtime) during development as the legacy bundle might be cached and still served. If an updated client bundle uses a feature (e.g. `__webpack_require__.n`) that causes a change of the runtime, it triggers an error.

The most straightforward solution would be adding a query to prevent caching.

Fixes #53281.

### CODE REVIEW

File: packages/next/src/server/app-render/app-render.tsx [hunk 1]
```diff
@@ -1583,14 +1583,20 @@ export async function renderToHTMLOrFlight(
                       src:
                         `${assetPrefix}/_next/` +
                         src +
-                        getAssetQueryString(false),
+                        // Always include the timestamp query in development
```
Comment (styfle) [inline packages/next/src/server/app-render/app-render.tsx:1586]: Do you need to check `process.env.NODE_ENV === 'development'` here?

Comment (shuding) [reply packages/next/src/server/app-render/app-render.tsx:1586]: It's included inside `getAssetQueryString`

**Review by ijjk — APPROVED** [review]

File: packages/next/src/server/app-render/app-render.tsx (hunk 1 above)
Comment (styfle) [reply packages/next/src/server/app-render/app-render.tsx:1586]: Nice!

Another option could be adding `Vary: *` if we want to try to preserve the url.
