### PR TITLE
fix: improve logging for _devPagesManifest.json loading failures

### LINKED ISSUE #38047: Routing error in dev mode: TypeError: Cannot read property 'includes' of undefined (take two)
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
  Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:
      Node: 18.2.0
      npm: 8.9.0
      Yarn: 1.22.19
      pnpm: 6.11.0
    Relevant packages:
      next: 12.1.7-canary.48
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Chrome, but n/a 

### How are you deploying your application? (if relevant)

n/a

### Describe the Bug

#16874 is still impacting users. I have a repro! If the network request to `/_next/static/development/_devPagesManifest.json` fails for any reason, the Next.js dev application crashes with:

```plaintext
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at resolveDynamicRoute (router.js?8684:1314:16)
    at _callee$ (router.js?8684:969:31)
    at tryCatch (runtime.js?ecd4:45:16)
    at Generator.invoke [as _invoke] (runtime.js?ecd4:274:1)
    at prototype.<computed> [as next] (runtime.js?ecd4:97:1)
    at asyncGeneratorStep (_async_to_generator.js?0e30:23:1)
    at _next (_async_to_generator.js?0e30:12:1)
```

### Expected Behavior

Next.js should be resilient to that manifest failing to load.

I took a dive into the source code and there are some _spicy_ TypeScript shenanigans happening 😄. And some TODOs about handling this correctly! #38046 is a draft PR showing what I'd suggest doing to resolve this issue.

1. The crash is coming from inside the framework, on [`if (pages.includes(fsPathname))`](https://github.com/vercel/next.js/blob/252d3b72f4f52b4308873ce7ad88be030d434df9/packages/next/shared/lib/router/utils/resolve-rewrites.ts#L89)
2. [`pages` is a parameter of `resolveRewrites`](https://github.com/vercel/next.js/blob/252d3b72f4f52b4308873ce7ad88be030d434df9/packages/next/shared/lib/router/utils/resolve-rewrites.ts#L12)
3. In calls to `resolveRewrites`, `pages` comes from [`this.pageLoader.getPageList()`](https://github.com/vercel/next.js/blob/8019cf002a32af9fad22375faeb90ddc16764b83/packages/next/shared/lib/router/router.ts#L1159)
4. [`getPageList`](https://github.com/vercel/next.js/blob/8019cf002a32af9fad22375faeb90ddc16764b83/packages/next/client/page-loader.ts#L56) doesn't properly handle the case of [`fetch(.../_next/static/development/_devPagesManifest.json)`](https://github.com/vercel/next.js/blob/8019cf002a32af9fad22375faeb90ddc16764b83/packages/next/client/page-loader.ts#L66) failing: [`return this.promisedDevPagesManifest!`](https://github.com/vercel/next.js/blob/8019cf002a32af9fad22375faeb90ddc16764b83/packages/next/client/page-loader.ts#L79) has a `// TODO Remove this assertion as this could be undefined` comment

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-flnphe?file=pages%2Findex.tsx

_(really, any Next.js app with a `Link` can demonstrate this issue)_

### To Reproduce

1. Start any Next.js app in development mode
2. Add a `<Link>` somewhere on the page
3. Visit localhost:3000 (or equivalent) in Chrome (or equivalent)
4. In the network tab, right click on the __devPagesManifest.json_ request and select _Block request url_
5. Refresh the page

Step 3 is the easiest way to simulate any of the reasons why that URL wouldn't be accessible that are mentioned in #16874. Apparently nginx configurations are more common culprits. Anecdotally I think I've seen this on CI runs that have flaky network layers (both GitHub Actions and CircleCI).

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## Bug

- [x] Fixes #38047
- ~[ ] Integration tests added: do you want them added for such an unusual edge case?~ [Comment below: skipping](https://github.com/vercel/next.js/pull/38046#issuecomment-1207444526)
- [x] Errors have helpful link attached, see `contributing.md`: ~I'll wait until this approach & error message are confirmed before thinking more deeply on how to explain the error~

Sending a draft PR as reference ahead of time. 🙂 

Doesn't resolve the root issue of why `_devPagesManifest.json` might fail to load. But does improve the log for when it happens. I'd suggest applying this same fix to `_devMiddlewareManifest.json` too.

<table>
<thead>
<tr>
<th></th>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<th>Console</th>
<td>
<pre>
<code>
Failed to fetch devPagesManifest TypeError: Failed to fetch
    at PageLoader.getPageList (page-loader.js?e87a:30:53)
    at _callee$ (router.js?8684:955:45)
    at ...
</code>
</pre>
<pre>
<code>
router.js?8684:1319 Uncaught (in promise) TypeError: Cannot \
read properties of undefined (reading 'includes')
    at resolveDynamicRoute (router.js?8684:1319:16)
    at _callee$
    at ...
</code>
</pre>
</td>
<td>
<pre>
<code>
Failed to fetch devPagesManifest: TypeError: Failed to fetch
    at PageLoader.getPageList (page-loader.js?e87a:30:53)
    at _callee$ (router.js?8684:955:45)
    at ...
</code>
</pre>
</td>
</tr>
<tr>
<th>Visual</th>
<td>Screenshot of a Next.js runtime error: TypeError: Cannot read properties of undefined (reading 'includes')</td>
<td>Screenshot of a Next.js runtime error: Error: Failed to fetch _devPagesManifest.json. Is something blocking that network request?</td>
</tr>
</tbody>
</table>

Edit: you can read more about how this PR was made here: https://www.typescriptcourse.com/careful-using-any-in-typescript

### CODE REVIEW

File: packages/next/client/page-loader.ts [hunk 1]
```diff
@@ -75,23 +75,18 @@ export default class PageLoader {
       if (window.__DEV_PAGES_MANIFEST) {
         return window.__DEV_PAGES_MANIFEST.pages
       } else {
-        if (!this.promisedDevPagesManifest) {
-          // TODO: Decide what should happen when fetching fails instead of asserting
-          // @ts-ignore
```
Comment (JoshuaKGoldberg) [inline packages/next/client/page-loader.ts:80]: Psst - may I suggest using [`@ts-expect-error`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments) instead? I would be very happy to send a PR migrating over! 🙂 

More broadly: I'd also suggest enabling typescript-eslint's [`prefer-ts-expect-error` rule](https://typescript-eslint.io/rules/prefer-ts-expect-error) and, even more broadly, much more of typescript-eslint's rules.

File: packages/next/client/page-loader.ts [hunk 2]
```diff
@@ -75,23 +75,18 @@ export default class PageLoader {
...
+          `${this.assetPrefix}/_next/static/development/_devPagesManifest.json`
+        )
+          .then((res) => res.json())
+          .then((manifest: { pages: string[] }) => {
+            window.__DEV_PAGES_MANIFEST = manifest
+            return manifest.pages
+          })
+          .catch((err) => {
+            throw new Error(`Failed to fetch devPagesManifest: ${err}`)
+          })
```
Comment (JoshuaKGoldberg) [inline packages/next/client/page-loader.ts:88]: Another alternative instead of throwing on failure would be to make the `getPageList` function return `string | undefined`. I personally prefer informative return types rather than mysterious error throwing. However, I think this code path is only ever called in dev mode within [code that already try/catches](https://github.com/vercel/next.js/blob/8019cf002a32af9fad22375faeb90ddc16764b83/packages/next/shared/lib/router/router.ts#L1157).

File: packages/next/shared/lib/router/router.ts [hunk 3]
```diff
@@ -1092,7 +1092,7 @@ export default class Router implements BaseRouter {
     // The build manifest needs to be loaded before auto-static dynamic pages
     // get their query parameters to allow ensuring they can be parsed properly
     // when rewritten to
-    let pages: any, rewrites: any
+    let pages: string[], rewrites: any
```
Comment (JoshuaKGoldberg) [inline packages/next/shared/lib/router/router.ts:1095]: > `any`

TypeScript would have caught this crash were it not for the `any` and `!`.

cc @delbaoliveira since we'd been chatting about this at Prisma Day - happy to help clean up these types! 🙂

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| buildDuration | 26.9s | 26.6s | -318ms |
| buildDurationCached | 9s | 9s | ⚠️ +3ms |
| nodeModulesSize | 1.94 GB | 1.94 GB | -620 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 6.745 | 6.599 | -0.15 |
| / avg req/sec | 370.63 | 378.82 | +8.19 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 3.267 | 3.208 | -0.06 |
| /error-in-render avg req/sec | 765.12 | 779.19 | +14.07 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| 299.HASH.js gzip | 179 B | 180 B | ⚠️ +1 B |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 30.7 kB | 30.6 kB | -15 B |
| webpack-HASH.js gzip | 1.54 kB | 1.54 kB | ⚠️ +1 B |
| Overall change | 74.4 kB | 74.4 kB | -13 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| _app-HASH.js gzip | 825 B | 824 B | -1 B |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 495 B | 498 B | ⚠️ +3 B |
| css-HASH.js gzip | 328 B | 328 B | ✓ |
| dynamic-HASH.js gzip | 2.4 kB | 2.4 kB | ✓ |
| head-HASH.js gzip | 356 B | 353 B | -3 B |
| hooks-HASH.js gzip | 805 B | 804 B | -1 B |
| image-HASH.js gzip | 5.49 kB | 5.48 kB | -9 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.34 kB | 2.34 kB | ⚠️ +2 B |
| routerDirect..HASH.js gzip | 321 B | 320 B | -1 B |
| script-HASH.js gzip | 391 B | 392 B | ⚠️ +1 B |
| withRouter-HASH.js gzip | 318 B | 319 B | ⚠️ +1 B |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.6 kB | 14.6 kB | -8 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| index.html gzip | 520 B | 524 B | ⚠️ +4 B |
| link.html gzip | 535 B | 538 B | ⚠️ +3 B |
| withRouter.html gzip | 516 B | 517 B | ⚠️ +1 B |
| Overall change | 1.57 kB | 1.58 kB | ⚠️ +8 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,25 +1,25 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-006025f296d93d1f.js"],
-  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-ec6f2dc249481230.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-a331316989d05f14.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-1ecb7a225a122304.js"],
+  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-7c674188292aca70.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-abb2ab71d4fb2340.js"],
   "/css": [
     "static\u002Fcss\u002F94fdbc56eafa2039.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-68d7610c482ac563.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-100e45427e857c65.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-058b7161e5324863.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-7470a3870d481122.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-c040cbe8d466bcb1.js"],
-  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-6bf8c96929eda019.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-0ac2521ca0cdc17f.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-d5bf2b3900d2bf53.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-d456b89ea2e58ccb.js"],
+  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-05db224a0b1fb76a.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-54bd7602a6a07579.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-3a3db92194a522ff.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-19c824ccc8950973.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-8a036a4ae9e5d6ed.js"
   ],
-  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-c3bfac97d4fbba00.js"],
+  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-d318755acc6c0b22.js"],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-d6891bab587638a3.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-dee19dca16003991.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 3479: /***/ function(
+    /***/ 122: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_app",
         function() {
-          return __webpack_require__(5909);
+          return __webpack_require__(777);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 5909: /***/ function(
+    /***/ 777: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -31,7 +31,7 @@
       var _interop_require_default = __webpack_require__(6993) /* ["default"] */
         .Z;
       var _create_super = __webpack_require__(7615) /* ["default"] */.Z;
-      var _runtimeJs = _interop_require_default(__webpack_require__(739));
+      var _runtimeJs = _interop_require_default(__webpack_require__(3994));
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
@@ -49,7 +49,7 @@
       });
       exports["default"] = void 0;
       var _react = _interopRequireDefault(__webpack_require__(9496));
-      var _utils = __webpack_require__(2973);
+      var _utils = __webpack_require__(6326);
       function asyncGeneratorStep(
         gen,
         resolve,
@@ -179,7 +179,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 179], function() {
-      return __webpack_exec__(3479), __webpack_exec__(3668);
+      return __webpack_exec__(122), __webpack_exec__(7489);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [820],
   {
-    /***/ 2929: /***/ function(
+    /***/ 3560: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_error",
         function() {
-          return __webpack_require__(9103);
+          return __webpack_require__(2509);
         }
       ]);
       if (false) {
@@ -24,7 +24,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function() {
-      return __webpack_exec__(2929);
+      return __webpack_exec__(3560);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>amp-HASH.js</strong></summary>

```diff
@@ -1,17 +1,17 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [216],
   {
-    /***/ 94: /***/ function(
+    /***/ 7941: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(2562);
+      module.exports = __webpack_require__(6824);
 
       /***/
     },
 
-    /***/ 9028: /***/ function(
+    /***/ 8958: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -19,7 +19,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/amp",
         function() {
-          return __webpack_require__(6385);
+          return __webpack_require__(9302);
         }
       ]);
       if (false) {
@@ -28,7 +28,7 @@
       /***/
     },
 
-    /***/ 2562: /***/ function(module, exports, __webpack_require__) {
+    /***/ 6824: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -36,8 +36,8 @@
       });
       exports.useAmp = useAmp;
       var _react = _interopRequireDefault(__webpack_require__(9496));
-      var _ampContext = __webpack_require__(2556);
-      var _ampMode = __webpack_require__(7853);
+      var _ampContext = __webpack_require__(5789);
+      var _ampMode = __webpack_require__(9208);
       function _interopRequireDefault(obj) {
         return obj && obj.__esModule
           ? obj
@@ -66,7 +66,7 @@
       /***/
     },
 
-    /***/ 6385: /***/ function(
+    /***/ 9302: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -83,7 +83,7 @@
         /* harmony export */
       });
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
-        94
+        7941
       );
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/ __webpack_require__.n(
         next_amp__WEBPACK_IMPORTED_MODULE_0__
@@ -107,7 +107,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function() {
-      return __webpack_exec__(9028);
+      return __webpack_exec__(8958);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>css-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [706],
   {
-    /***/ 8281: /***/ function(
+    /***/ 9557: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/css",
         function() {
-          return __webpack_require__(4347);
+          return __webpack_require__(79);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 4347: /***/ function(
+    /***/ 79: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -29,7 +29,7 @@
         4637
       );
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        4542
+        2054
       );
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         _css_module_css__WEBPACK_IMPORTED_MODULE_1__
@@ -48,7 +48,7 @@
       /***/
     },
 
-    /***/ 4542: /***/ function(module) {
+    /***/ 2054: /***/ function(module) {
       // extracted by mini-css-extract-plugin
       module.exports = { helloWorld: "css_helloWorld__qqNwY" };
 
@@ -61,7 +61,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(8281);
+      return __webpack_exec__(9557);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [739],
   {
-    /***/ 2744: /***/ function(
+    /***/ 5695: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/dynamic",
         function() {
-          return __webpack_require__(5547);
+          return __webpack_require__(9525);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 3005: /***/ function(module, exports, __webpack_require__) {
+    /***/ 6014: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       var _instanceof = __webpack_require__(186) /* ["default"] */.Z;
@@ -29,7 +29,7 @@
       exports["default"] = dynamic;
       exports.noSSR = noSSR;
       var _react = _interopRequireDefault(__webpack_require__(9496));
-      var _loadable = _interopRequireDefault(__webpack_require__(9675));
+      var _loadable = _interopRequireDefault(__webpack_require__(7679));
       function dynamic(dynamicOptions, options) {
         var loadableFn = _loadable.default;
         var loadableOptions = {
@@ -132,7 +132,7 @@
       /***/
     },
 
-    /***/ 577: /***/ function(
+    /***/ 8416: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -159,7 +159,7 @@
       /***/
     },
 
-    /***/ 9675: /***/ function(
+    /***/ 7679: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -175,7 +175,7 @@
       });
       exports["default"] = void 0;
       var _react = _interopRequireDefault(__webpack_require__(9496));
-      var _loadableContext = __webpack_require__(577);
+      var _loadableContext = __webpack_require__(8416);
       function _interopRequireDefault(obj) {
         return obj && obj.__esModule
           ? obj
@@ -496,7 +496,7 @@
       /***/
     },
 
-    /***/ 5547: /***/ function(
+    /***/ 9525: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -513,7 +513,7 @@
         4637
       );
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        1605
+        2123
       );
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_dynamic__WEBPACK_IMPORTED_MODULE_1__
@@ -522,13 +522,13 @@
       var DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
         function() {
           return __webpack_require__
-            .e(/* import() */ 299)
-            .then(__webpack_require__.bind(__webpack_require__, 5299));
+            .e(/* import() */ 128)
+            .then(__webpack_require__.bind(__webpack_require__, 5128));
         },
         {
           loadableGenerated: {
             webpack: function() {
-              return [/*require.resolve*/ 5299];
+              return [/*require.resolve*/ 5128];
             }
           }
         }
@@ -558,12 +558,12 @@
       /***/
     },
 
-    /***/ 1605: /***/ function(
+    /***/ 2123: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(3005);
+      module.exports = __webpack_require__(6014);
 
       /***/
     },
@@ -665,7 +665,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(2744);
+      return __webpack_exec__(5695);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>head-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [645],
   {
-    /***/ 4337: /***/ function(
+    /***/ 7148: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/head",
         function() {
-          return __webpack_require__(9288);
+          return __webpack_require__(7481);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 9288: /***/ function(
+    /***/ 7481: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -35,7 +35,7 @@
         4637
       );
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        8915
+        4616
       );
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_head__WEBPACK_IMPORTED_MODULE_1__
@@ -71,12 +71,12 @@
       /***/
     },
 
-    /***/ 8915: /***/ function(
+    /***/ 4616: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(681);
+      module.exports = __webpack_require__(4790);
 
       /***/
     }
@@ -87,7 +87,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(4337);
+      return __webpack_exec__(7148);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>hooks-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [757],
   {
-    /***/ 4853: /***/ function(
+    /***/ 3515: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/hooks",
         function() {
-          return __webpack_require__(8892);
+          return __webpack_require__(3451);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 8892: /***/ function(
+    /***/ 3451: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -132,7 +132,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(4853);
+      return __webpack_exec__(3515);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [358],
   {
-    /***/ 7570: /***/ function(
+    /***/ 1487: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function() {
-          return __webpack_require__(1576);
+          return __webpack_require__(4789);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 8976: /***/ function(module, exports, __webpack_require__) {
+    /***/ 361: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       var _define_property = __webpack_require__(6599)["default"];
@@ -29,12 +29,12 @@
       });
       exports["default"] = Image;
       var _react = _interopRequireWildcard(__webpack_require__(9496));
-      var _head = _interopRequireDefault(__webpack_require__(681));
-      var _imageConfig = __webpack_require__(5282);
-      var _useIntersection = __webpack_require__(227);
-      var _imageConfigContext = __webpack_require__(8584);
-      var _utils = __webpack_require__(2973);
-      var _normalizeTrailingSlash = __webpack_require__(3892);
+      var _head = _interopRequireDefault(__webpack_require__(4790));
+      var _imageConfig = __webpack_require__(5676);
+      var _useIntersection = __webpack_require__(5668);
+      var _imageConfigContext = __webpack_require__(76);
+      var _utils = __webpack_require__(6326);
+      var _normalizeTrailingSlash = __webpack_require__(7600);
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -1033,7 +1033,7 @@
       /***/
     },
 
-    /***/ 227: /***/ function(module, exports, __webpack_require__) {
+    /***/ 5668: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       var _sliced_to_array = __webpack_require__(7694) /* ["default"] */.Z;
@@ -1042,7 +1042,7 @@
       });
       exports.useIntersection = useIntersection;
       var _react = __webpack_require__(9496);
-      var _requestIdleCallback = __webpack_require__(5757);
+      var _requestIdleCallback = __webpack_require__(5617);
       var hasIntersectionObserver = typeof IntersectionObserver === "function";
       function useIntersection(param) {
         var rootRef = param.rootRef,
@@ -1175,7 +1175,7 @@
       /***/
     },
 
-    /***/ 1576: /***/ function(
+    /***/ 4789: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -1196,8 +1196,8 @@
 
       // EXTERNAL MODULE: ./node_modules/.pnpm/react@17.0.2/node_modules/react/jsx-runtime.js
       var jsx_runtime = __webpack_require__(4637);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_sfoxds7t5ydpegc3knd667wn6m/node_modules/next/image.js
-      var next_image = __webpack_require__(8114);
+      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_sfoxds7t5ydpegc3knd667wn6m/node_modules/next/image.js
+      var next_image = __webpack_require__(4033);
       var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // CONCATENATED MODULE: ./pages/nextjs.png
       /* harmony default export */ var nextjs = {
         src: "/_next/static/media/nextjs.cae0b805.png",
@@ -1225,12 +1225,12 @@
       /***/
     },
 
-    /***/ 8114: /***/ function(
+    /***/ 4033: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(8976);
+      module.exports = __webpack_require__(361);
 
       /***/
     }
@@ -1241,7 +1241,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(7570);
+      return __webpack_exec__(1487);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>index-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [405],
   {
-    /***/ 4786: /***/ function(
+    /***/ 6967: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/",
         function() {
-          return __webpack_require__(5355);
+          return __webpack_require__(3973);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 5355: /***/ function(
+    /***/ 3973: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -46,7 +46,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function() {
-      return __webpack_exec__(4786);
+      return __webpack_exec__(6967);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [644],
   {
-    /***/ 2783: /***/ function(
+    /***/ 9367: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/link",
         function() {
-          return __webpack_require__(4917);
+          return __webpack_require__(1849);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 8494: /***/ function(module, exports) {
+    /***/ 1908: /***/ function(module, exports) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -54,7 +54,7 @@
       /***/
     },
 
-    /***/ 861: /***/ function(module, exports, __webpack_require__) {
+    /***/ 882: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       var _sliced_to_array = __webpack_require__(7694) /* ["default"] */.Z;
@@ -64,13 +64,13 @@
       });
       exports["default"] = void 0;
       var _react = _interopRequireDefault(__webpack_require__(9496));
-      var _router = __webpack_require__(7733);
-      var _addLocale = __webpack_require__(6049);
-      var _routerContext = __webpack_require__(2488);
-      var _appRouterContext = __webpack_require__(1849);
-      var _useIntersection = __webpack_require__(227);
-      var _getDomainLocale = __webpack_require__(8494);
-      var _addBasePath = __webpack_require__(5090);
+      var _router = __webpack_require__(8340);
+      var _addLocale = __webpack_require__(9465);
+      var _routerContext = __webpack_require__(1349);
+      var _appRouterContext = __webpack_require__(3407);
+      var _useIntersection = __webpack_require__(5668);
+      var _getDomainLocale = __webpack_require__(1908);
+      var _addBasePath = __webpack_require__(8126);
       function _interopRequireDefault(obj) {
         return obj && obj.__esModule
           ? obj
@@ -406,7 +406,7 @@
       /***/
     },
 
-    /***/ 227: /***/ function(module, exports, __webpack_require__) {
+    /***/ 5668: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       var _sliced_to_array = __webpack_require__(7694) /* ["default"] */.Z;
@@ -415,7 +415,7 @@
       });
       exports.useIntersection = useIntersection;
       var _react = __webpack_require__(9496);
-      var _requestIdleCallback = __webpack_require__(5757);
+      var _requestIdleCallback = __webpack_require__(5617);
       var hasIntersectionObserver = typeof IntersectionObserver === "function";
       function useIntersection(param) {
         var rootRef = param.rootRef,
@@ -548,7 +548,7 @@
       /***/
     },
 
-    /***/ 1849: /***/ function(
+    /***/ 3407: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -575,7 +575,7 @@
       /***/
     },
 
-    /***/ 4917: /***/ function(
+    /***/ 1849: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -592,7 +592,7 @@
         4637
       );
       /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        8168
+        8728
       );
       /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_link__WEBPACK_IMPORTED_MODULE_1__
@@ -623,12 +623,12 @@
       /***/
     },
 
-    /***/ 8168: /***/ function(
+    /***/ 8728: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(861);
+      module.exports = __webpack_require__(882);
 
       /***/
     }
@@ -639,7 +639,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(2783);
+      return __webpack_exec__(9367);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>routerDirect-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [58],
   {
-    /***/ 5863: /***/ function(
+    /***/ 4538: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/routerDirect",
         function() {
-          return __webpack_require__(7585);
+          return __webpack_require__(7451);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 7585: /***/ function(
+    /***/ 7451: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -35,7 +35,7 @@
         4637
       );
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        9393
+        7084
       );
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_router__WEBPACK_IMPORTED_MODULE_1__
@@ -57,12 +57,12 @@
       /***/
     },
 
-    /***/ 9393: /***/ function(
+    /***/ 7084: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(3668);
+      module.exports = __webpack_require__(7489);
 
       /***/
     }
@@ -73,7 +73,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(5863);
+      return __webpack_exec__(4538);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>script-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [797],
   {
-    /***/ 581: /***/ function(
+    /***/ 2644: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/script",
         function() {
-          return __webpack_require__(6723);
+          return __webpack_require__(5292);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 6723: /***/ function(
+    /***/ 5292: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -35,7 +35,7 @@
         4637
       );
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        2311
+        7635
       );
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_script__WEBPACK_IMPORTED_MODULE_1__
@@ -70,12 +70,12 @@
       /***/
     },
 
-    /***/ 2311: /***/ function(
+    /***/ 7635: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(3948);
+      module.exports = __webpack_require__(3951);
 
       /***/
     }
@@ -86,7 +86,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(581);
+      return __webpack_exec__(2644);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>withRouter-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [807],
   {
-    /***/ 4573: /***/ function(
+    /***/ 5577: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/withRouter",
         function() {
-          return __webpack_require__(667);
+          return __webpack_require__(2161);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 667: /***/ function(
+    /***/ 2161: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -35,7 +35,7 @@
         4637
       );
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        9393
+        7084
       );
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_router__WEBPACK_IMPORTED_MODULE_1__
@@ -54,12 +54,12 @@
       /***/
     },
 
-    /***/ 9393: /***/ function(
+    /***/ 7084: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(3668);
+      module.exports = __webpack_require__(7489);
 
       /***/
     }
@@ -70,7 +70,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(4573);
+      return __webpack_exec__(5577);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>299.HASH.js</strong></summary>

```diff
@@ -1,8 +1,8 @@
 "use strict";
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
-  [299],
+  [128],
   {
-    /***/ 5299: /***/ function(
+    /***/ 5128: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
```
</details>
<details>
<summary>Diff for <strong>framework-HASH.js</strong></summary>

```diff
@@ -19,7 +19,7 @@
  Modernizr 3.0.0pre (Custom Build) | MIT
 */
       var aa = __webpack_require__(9496),
-        m = __webpack_require__(9260),
+        m = __webpack_require__(2048),
         r = __webpack_require__(8051);
       function y(a) {
         for (
@@ -7895,7 +7895,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      __webpack_require__(9260);
+      __webpack_require__(2048);
       var f = __webpack_require__(9496),
         g = 60103;
       exports.Fragment = 60107;
@@ -7948,7 +7948,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      var l = __webpack_require__(9260),
+      var l = __webpack_require__(2048),
         n = 60103,
         p = 60106;
       exports.Fragment = 60107;
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
@@ -159,7 +159,7 @@
     /******/ __webpack_require__.u = function(chunkId) {
       /******/ // return url for filenames based on template
       /******/ return (
-        "static/chunks/" + chunkId + "." + "06a0ec22d4e398e5" + ".js"
+        "static/chunks/" + chunkId + "." + "e030bda2b87fb167" + ".js"
       );
       /******/
     };
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -11,23 +11,23 @@
       src="/_next/static/chunks/polyfills-0d1b80a048d4787e.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-eac555bfdd3554da.js"
+      src="/_next/static/chunks/webpack-7d45352f17e74673.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/framework-8755e6e713f733ae.js"
+      src="/_next/static/chunks/framework-044d557c64574856.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-84865a9c4e9b01eb.js"
+      src="/_next/static/chunks/main-d519c4ddf6a358f7.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-40c7d3c28f60fe67.js"
+      src="/_next/static/chunks/pages/_app-bc22dfa04aca59af.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/index-006025f296d93d1f.js"
+      src="/_next/static/chunks/pages/index-1ecb7a225a122304.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -11,23 +11,23 @@
       src="/_next/static/chunks/polyfills-0d1b80a048d4787e.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-eac555bfdd3554da.js"
+      src="/_next/static/chunks/webpack-7d45352f17e74673.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/framework-8755e6e713f733ae.js"
+      src="/_next/static/chunks/framework-044d557c64574856.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-84865a9c4e9b01eb.js"
+      src="/_next/static/chunks/main-d519c4ddf6a358f7.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-40c7d3c28f60fe67.js"
+      src="/_next/static/chunks/pages/_app-bc22dfa04aca59af.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-d5bf2b3900d2bf53.js"
+      src="/_next/static/chunks/pages/link-3a3db92194a522ff.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -11,23 +11,23 @@
       src="/_next/static/chunks/polyfills-0d1b80a048d4787e.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-eac555bfdd3554da.js"
+      src="/_next/static/chunks/webpack-7d45352f17e74673.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/framework-8755e6e713f733ae.js"
+      src="/_next/static/chunks/framework-044d557c64574856.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-84865a9c4e9b01eb.js"
+      src="/_next/static/chunks/main-d519c4ddf6a358f7.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-40c7d3c28f60fe67.js"
+      src="/_next/static/chunks/pages/_app-bc22dfa04aca59af.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/withRouter-d6891bab587638a3.js"
+      src="/_next/static/chunks/pages/withRouter-dee19dca16003991.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| buildDuration | 28.2s | 27.9s | -350ms |
| buildDurationCached | 9s | 8.7s | -294ms |
| nodeModulesSize | 1.94 GB | 1.94 GB | -620 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 6.662 | 6.791 | ⚠️ +0.13 |
| / avg req/sec | 375.24 | 368.12 | ⚠️ -7.12 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 3.213 | 3.305 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 778.19 | 756.51 | ⚠️ -21.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| 299.HASH.js gzip | 179 B | 178 B | -1 B |
| framework-HASH.js gzip | 42.7 kB | 42.7 kB | ⚠️ +1 B |
| main-HASH.js gzip | 31.1 kB | 31.1 kB | -12 B |
| webpack-HASH.js gzip | 1.54 kB | 1.54 kB | ✓ |
| Overall change | 75.5 kB | 75.5 kB | -12 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| _app-HASH.js gzip | 836 B | 835 B | -1 B |
| _error-HASH.js gzip | 187 B | 188 B | ⚠️ +1 B |
| amp-HASH.js gzip | 510 B | 510 B | ✓ |
| css-HASH.js gzip | 332 B | 330 B | -2 B |
| dynamic-HASH.js gzip | 2.61 kB | 2.61 kB | ⚠️ +3 B |
| head-HASH.js gzip | 365 B | 363 B | -2 B |
| hooks-HASH.js gzip | 797 B | 794 B | -3 B |
| image-HASH.js gzip | 5.54 kB | 5.54 kB | -4 B |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.4 kB | 2.4 kB | -1 B |
| routerDirect..HASH.js gzip | 327 B | 327 B | ✓ |
| script-HASH.js gzip | 399 B | 400 B | ⚠️ +1 B |
| withRouter-HASH.js gzip | 323 B | 324 B | ⚠️ +1 B |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15 kB | 15 kB | -7 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 457 B | -2 B |
| Overall change | 459 B | 457 B | -2 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | JoshuaKGoldberg/next.js resilient-promised-dev-pages-manifest | Change |
| - | - | - | - |
| index.html gzip | 521 B | 524 B | ⚠️ +3 B |
| link.html gzip | 537 B | 538 B | ⚠️ +1 B |
| withRouter.html gzip | 517 B | 519 B | ⚠️ +2 B |
| Overall change | 1.57 kB | 1.58 kB | ⚠️ +6 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,25 +1,25 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-006025f296d93d1f.js"],
-  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-ec6f2dc249481230.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-a331316989d05f14.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-1ecb7a225a122304.js"],
+  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-7c674188292aca70.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-abb2ab71d4fb2340.js"],
   "/css": [
     "static\u002Fcss\u002F94fdbc56eafa2039.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-68d7610c482ac563.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-100e45427e857c65.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-058b7161e5324863.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-7470a3870d481122.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-c040cbe8d466bcb1.js"],
-  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-6bf8c96929eda019.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-0ac2521ca0cdc17f.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-d5bf2b3900d2bf53.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-d456b89ea2e58ccb.js"],
+  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-05db224a0b1fb76a.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-54bd7602a6a07579.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-3a3db92194a522ff.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-19c824ccc8950973.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-8a036a4ae9e5d6ed.js"
   ],
-  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-c3bfac97d4fbba00.js"],
+  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-d318755acc6c0b22.js"],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-d6891bab587638a3.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-dee19dca16003991.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 3479: /***/ function(
+    /***/ 122: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_app",
         function() {
-          return __webpack_require__(5909);
+          return __webpack_require__(777);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 5909: /***/ function(
+    /***/ 777: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -31,7 +31,7 @@
       var _interop_require_default = __webpack_require__(6993) /* ["default"] */
         .Z;
       var _create_super = __webpack_require__(7615) /* ["default"] */.Z;
-      var _runtimeJs = _interop_require_default(__webpack_require__(739));
+      var _runtimeJs = _interop_require_default(__webpack_require__(3994));
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
@@ -49,7 +49,7 @@
       });
       exports["default"] = void 0;
       var _react = _interopRequireDefault(__webpack_require__(9496));
-      var _utils = __webpack_require__(2973);
+      var _utils = __webpack_require__(6326);
       function asyncGeneratorStep(
         gen,
         resolve,
@@ -179,7 +179,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 179], function() {
-      return __webpack_exec__(3479), __webpack_exec__(3668);
+      return __webpack_exec__(122), __webpack_exec__(7489);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [820],
   {
-    /***/ 2929: /***/ function(
+    /***/ 3560: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_error",
         function() {
-          return __webpack_require__(9103);
+          return __webpack_require__(2509);
         }
       ]);
       if (false) {
@@ -24,7 +24,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function() {
-      return __webpack_exec__(2929);
+      return __webpack_exec__(3560);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>amp-HASH.js</strong></summary>

```diff
@@ -1,17 +1,17 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [216],
   {
-    /***/ 94: /***/ function(
+    /***/ 7941: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(2562);
+      module.exports = __webpack_require__(6824);
 
       /***/
     },
 
-    /***/ 9028: /***/ function(
+    /***/ 8958: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -19,7 +19,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/amp",
         function() {
-          return __webpack_require__(6385);
+          return __webpack_require__(9302);
         }
       ]);
       if (false) {
@@ -28,7 +28,7 @@
       /***/
     },
 
-    /***/ 2562: /***/ function(module, exports, __webpack_require__) {
+    /***/ 6824: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -36,8 +36,8 @@
       });
       exports.useAmp = useAmp;
       var _react = _interopRequireDefault(__webpack_require__(9496));
-      var _ampContext = __webpack_require__(2556);
-      var _ampMode = __webpack_require__(7853);
+      var _ampContext = __webpack_require__(5789);
+      var _ampMode = __webpack_require__(9208);
       function _interopRequireDefault(obj) {
         return obj && obj.__esModule
           ? obj
@@ -66,7 +66,7 @@
       /***/
     },
 
-    /***/ 6385: /***/ function(
+    /***/ 9302: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -83,7 +83,7 @@
         /* harmony export */
       });
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
-        94
+        7941
       );
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/ __webpack_require__.n(
         next_amp__WEBPACK_IMPORTED_MODULE_0__
@@ -107,7 +107,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function() {
-      return __webpack_exec__(9028);
+      return __webpack_exec__(8958);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>css-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [706],
   {
-    /***/ 8281: /***/ function(
+    /***/ 9557: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/css",
         function() {
-          return __webpack_require__(4347);
+          return __webpack_require__(79);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 4347: /***/ function(
+    /***/ 79: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -29,7 +29,7 @@
         4637
       );
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        4542
+        2054
       );
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         _css_module_css__WEBPACK_IMPORTED_MODULE_1__
@@ -48,7 +48,7 @@
       /***/
     },
 
-    /***/ 4542: /***/ function(module) {
+    /***/ 2054: /***/ function(module) {
       // extracted by mini-css-extract-plugin
       module.exports = { helloWorld: "css_helloWorld__qqNwY" };
 
@@ -61,7 +61,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(8281);
+      return __webpack_exec__(9557);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [739],
   {
-    /***/ 2744: /***/ function(
+    /***/ 5695: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/dynamic",
         function() {
-          return __webpack_require__(5547);
+          return __webpack_require__(9525);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 3005: /***/ function(module, exports, __webpack_require__) {
+    /***/ 6014: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       var _instanceof = __webpack_require__(186) /* ["default"] */.Z;
@@ -29,7 +29,7 @@
       exports["default"] = dynamic;
       exports.noSSR = noSSR;
       var _react = _interopRequireDefault(__webpack_require__(9496));
-      var _loadable = _interopRequireDefault(__webpack_require__(9675));
+      var _loadable = _interopRequireDefault(__webpack_require__(7679));
       function dynamic(dynamicOptions, options) {
         var loadableFn = _loadable.default;
         var loadableOptions = {
@@ -132,7 +132,7 @@
       /***/
     },
 
-    /***/ 577: /***/ function(
+    /***/ 8416: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -159,7 +159,7 @@
       /***/
     },
 
-    /***/ 9675: /***/ function(
+    /***/ 7679: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -175,7 +175,7 @@
       });
       exports["default"] = void 0;
       var _react = _interopRequireDefault(__webpack_require__(9496));
-      var _loadableContext = __webpack_require__(577);
+      var _loadableContext = __webpack_require__(8416);
       function _interopRequireDefault(obj) {
         return obj && obj.__esModule
           ? obj
@@ -496,7 +496,7 @@
       /***/
     },
 
-    /***/ 5547: /***/ function(
+    /***/ 9525: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -513,7 +513,7 @@
         4637
       );
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        1605
+        2123
       );
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_dynamic__WEBPACK_IMPORTED_MODULE_1__
@@ -522,13 +522,13 @@
       var DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
         function() {
           return __webpack_require__
-            .e(/* import() */ 299)
-            .then(__webpack_require__.bind(__webpack_require__, 5299));
+            .e(/* import() */ 128)
+            .then(__webpack_require__.bind(__webpack_require__, 5128));
         },
         {
           loadableGenerated: {
             webpack: function() {
-              return [/*require.resolve*/ 5299];
+              return [/*require.resolve*/ 5128];
             }
           }
         }
@@ -558,12 +558,12 @@
       /***/
     },
 
-    /***/ 1605: /***/ function(
+    /***/ 2123: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(3005);
+      module.exports = __webpack_require__(6014);
 
       /***/
     },
@@ -665,7 +665,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(2744);
+      return __webpack_exec__(5695);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>head-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [645],
   {
-    /***/ 4337: /***/ function(
+    /***/ 7148: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/head",
         function() {
-          return __webpack_require__(9288);
+          return __webpack_require__(7481);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 9288: /***/ function(
+    /***/ 7481: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -35,7 +35,7 @@
         4637
       );
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        8915
+        4616
       );
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_head__WEBPACK_IMPORTED_MODULE_1__
@@ -71,12 +71,12 @@
       /***/
     },
 
-    /***/ 8915: /***/ function(
+    /***/ 4616: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(681);
+      module.exports = __webpack_require__(4790);
 
       /***/
     }
@@ -87,7 +87,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(4337);
+      return __webpack_exec__(7148);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>hooks-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [757],
   {
-    /***/ 4853: /***/ function(
+    /***/ 3515: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/hooks",
         function() {
-          return __webpack_require__(8892);
+          return __webpack_require__(3451);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 8892: /***/ function(
+    /***/ 3451: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -132,7 +132,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(4853);
+      return __webpack_exec__(3515);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [358],
   {
-    /***/ 7570: /***/ function(
+    /***/ 1487: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function() {
-          return __webpack_require__(1576);
+          return __webpack_require__(4789);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 8976: /***/ function(module, exports, __webpack_require__) {
+    /***/ 361: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       var _define_property = __webpack_require__(6599)["default"];
@@ -29,12 +29,12 @@
       });
       exports["default"] = Image;
       var _react = _interopRequireWildcard(__webpack_require__(9496));
-      var _head = _interopRequireDefault(__webpack_require__(681));
-      var _imageConfig = __webpack_require__(5282);
-      var _useIntersection = __webpack_require__(227);
-      var _imageConfigContext = __webpack_require__(8584);
-      var _utils = __webpack_require__(2973);
-      var _normalizeTrailingSlash = __webpack_require__(3892);
+      var _head = _interopRequireDefault(__webpack_require__(4790));
+      var _imageConfig = __webpack_require__(5676);
+      var _useIntersection = __webpack_require__(5668);
+      var _imageConfigContext = __webpack_require__(76);
+      var _utils = __webpack_require__(6326);
+      var _normalizeTrailingSlash = __webpack_require__(7600);
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -1033,7 +1033,7 @@
       /***/
     },
 
-    /***/ 227: /***/ function(module, exports, __webpack_require__) {
+    /***/ 5668: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       var _sliced_to_array = __webpack_require__(7694) /* ["default"] */.Z;
@@ -1042,7 +1042,7 @@
       });
       exports.useIntersection = useIntersection;
       var _react = __webpack_require__(9496);
-      var _requestIdleCallback = __webpack_require__(5757);
+      var _requestIdleCallback = __webpack_require__(5617);
       var hasIntersectionObserver = typeof IntersectionObserver === "function";
       function useIntersection(param) {
         var rootRef = param.rootRef,
@@ -1175,7 +1175,7 @@
       /***/
     },
 
-    /***/ 1576: /***/ function(
+    /***/ 4789: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -1196,8 +1196,8 @@
 
       // EXTERNAL MODULE: ./node_modules/.pnpm/react@17.0.2/node_modules/react/jsx-runtime.js
       var jsx_runtime = __webpack_require__(4637);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_sfoxds7t5ydpegc3knd667wn6m/node_modules/next/image.js
-      var next_image = __webpack_require__(8114);
+      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_sfoxds7t5ydpegc3knd667wn6m/node_modules/next/image.js
+      var next_image = __webpack_require__(4033);
       var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // CONCATENATED MODULE: ./pages/nextjs.png
       /* harmony default export */ var nextjs = {
         src: "/_next/static/media/nextjs.cae0b805.png",
@@ -1225,12 +1225,12 @@
       /***/
     },
 
-    /***/ 8114: /***/ function(
+    /***/ 4033: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(8976);
+      module.exports = __webpack_require__(361);
 
       /***/
     }
@@ -1241,7 +1241,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(7570);
+      return __webpack_exec__(1487);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>index-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [405],
   {
-    /***/ 4786: /***/ function(
+    /***/ 6967: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/",
         function() {
-          return __webpack_require__(5355);
+          return __webpack_require__(3973);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 5355: /***/ function(
+    /***/ 3973: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -46,7 +46,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function() {
-      return __webpack_exec__(4786);
+      return __webpack_exec__(6967);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [644],
   {
-    /***/ 2783: /***/ function(
+    /***/ 9367: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/link",
         function() {
-          return __webpack_require__(4917);
+          return __webpack_require__(1849);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 8494: /***/ function(module, exports) {
+    /***/ 1908: /***/ function(module, exports) {
       "use strict";
 
       O
Post job cleanup.
[command]/usr/bin/git version
git version 2.36.1
Temporarily overriding HOME='/home/runner/work/_temp/0fcaabc4-2a5c-48eb-bb1e-4e1f0f84bf49' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
[command]/usr/bin/git config --global --add safe.directory /home/runner/work/next.js/next.js
[command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
[command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
[command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
[command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
[command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
Cleaning up orphan processes
Commit: 4d68044eab95d14fd190477ab096a91188f1090e

**Comment by jsjoeio** [comment]
> Integration tests added: do you want them added for such an unusual edge case?

What's the downside to adding them?

**Comment by JoshuaKGoldberg** [comment]
Heh, I won't claim to speak for the Next/Vercel folks. But the more tests you have, the longer it takes to get through them all. And higher-level tests have a higher chance of flakiness. Putting that together, overloading on too many integration/end-to-end tests can mean longer and slower CI with more frequent random failures.

**Comment by JoshuaKGoldberg** [comment]
Since this has been in draft for a while, I'll just go ahead and open it up. Would love advice on the open questions in the description please!

File: packages/next/client/page-loader.ts (hunk 1 above)
Comment (ijjk) [reply packages/next/client/page-loader.ts:80]: Definitely open to migrating this over to `ts-expect-error` and investigating better TypeScript lint checks!

**Comment by ijjk** [comment]
> Integration tests added: do you want them added for such an unusual edge case?

If we can narrow in on a stable test case we're always glad to add those, although this one seems trickier to have a stable test for so understandable to not have one here. 

> Errors have helpful link attached, see contributing.md: I'll wait until this approach & error message are confirmed before thinking more deeply on how to explain the error

I think the improved error message looks good, would definitely be nice to have an `errors/` doc expanding on the cases this could potentially occur (`pnpm new-error` can be used for this).

**Comment by JoshuaKGoldberg** [comment]
Super, thanks @ijjk! Added an error description, updated the PR description, and merged from `canary`.

File: packages/next/client/page-loader.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply packages/next/client/page-loader.ts:63]: Super! I'll file a GitHub issue.

For investigating more lint checks, I'd been chatting with @elsigh to try to get a more formal effort set up. Will check back in tomorrow!

Comment (JoshuaKGoldberg) [reply packages/next/client/page-loader.ts:63]: Super! For investigating more lint checks, I'd been chatting with @elsigh to try to get a more formal effort set up. Will check back in tomorrow!

**Review by ijjk — APPROVED** [review]
Thanks!
