### PR TITLE
Fix default server host value causing issues on Windows

### LINKED ISSUE #4456: Error on reloading page in the initial next.js installation
**Describe the bug**
I get the following error shown in the console when I reload a page in firefox:
`The connection to http://localhost:3000/_next/webpack-hmr was interrupted while the page was loading.`

This seems to happen even with a new next.js installation.

**To Reproduce**
- Create a new folder `mkdir nextjs-test`
- navigate to the folder and install dependencies `npm install --save next react react-dom`
- add the dev script to package.json `"dev": "next"`
- create `./pages/index.js` and copy the following code:
```export default () => <div>Welcome to next.js!</div>```
- `npm run dev` and open localhost:3000 in firefox.
- Reload the browser and open the console. The error should show up in your console.

**Expected behavior**
I expect no error since I only followed the basic setup.

**System information**
 - OS: macOS
 - Browser: firefox 60.0.1 (no error when using chrome)
 - Version of Next.js: 6.0.3

### LINKED ISSUE #27254: Fast refresh not working on browser, a very weird case
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chrome, Edge, Firefox

### What operating system are you using?

Windows 10, 11

### How are you deploying your application?

did not deploy

### Describe the Bug

I encountered a very weird case which fast refresh not working on browser, I have done a lot of research and tests but still no luck to find out why it happens.

All the tests below are done on the same bootstrap project with following command

```
yarn create next-app
cd my-app
yarn dev
```

Node version is the same 14.17.3

**Laptop 1 Windows 10 latest build**

When I modify `pages/index.js` (change the "Welcome to..." text) and save the file, the terminal print out a new line says `compiling ...`, but the page on browser not auto refresh at all. Tried on Chrome, Firefox, Edge, all not working.
I was using fnm to as my node manager, but I tried to install node,js binary directly, still not working. I tried use nvm-windows as my node manager, still not working.

Then I think it's maybe fast refresh has some bug, I tried `yarn create react-app`, then run `yarn start`, then do similar modification and save the file. The page on browser refreshed as expected!

**Another Laptop 2 Windows 11 latest preview build** (Windows 11 may not make any difference)

When I modify `pages/index.js` (change the "Welcome to..." text) and save the file, it just works fine!

So only when I use `next.js` on Laptop 1, fast refresh does not working at all, which I have to manual refresh.
The behavior indicates the file change is detected which means webpack watch works fine, but he communication to notify change is broken, that's why the browser doesn't auto refresh the page when there is a new change.
I'm not using WSL, and my shell is Powershell 7 latest version.

### Expected Behavior

Fast refresh would refresh the page whenever a file is changed

### To Reproduce

Mentioned above

### LINKED ISSUE #27298: Hot reload connection can fail on Windows
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

Edge 91.0.864.67 - Chrome 91.0.4472.124

### What operating system are you using?

Windows 10 Pro 20H2

### How are you deploying your application?

npm run dev

### Describe the Bug

Hot reload / Fast Refresh isn't working.

I'm following the next tutorial, so here's my code:
npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"

Here https://nextjs.org/learn/basics/create-nextjs-app/editing-the-page it says that the page will live reload, just like react / vue, but it doenst reload.

On network tab I see this errors:
image

Approaches tried following google/yt tutorials:
Create next.config.js with FAST_REFRESH='TRUE'
Create webpack.config.js with TARGET = 'WEB'
Delete project and restarted from 0
npm ci
Delete node_modules and .next and recreated

### Expected Behavior

Live reload should work.

### To Reproduce

npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"

### PR DESCRIPTION
**Pull request by ijjk**
This fixes a case where the HMR connection for fast refresh would fail to connect on Windows due to a change being made to the default host being listened to. Previously we didn't set a default for the `host` value when calling `server.listen` which allowed the default listening behavior to be used although in https://github.com/vercel/next.js/pull/20409 a default of `0.0.0.0` was added which causes conflicts for some set-ups mainly on Windows it seems. 

## Bug

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added (N/A)
- [x] Errors have helpful link attached, see `contributing.md`

Fixes: https://github.com/vercel/next.js/issues/27298
Fixes: https://github.com/vercel/next.js/issues/27254
Fixes: https://github.com/vercel/next.js/issues/4456#issuecomment
Fixes: https://github.com/vercel/next.js/pull/20409#issuecomment-849933092
x-ref: https://github.com/vercel/next.js/pull/20409

### CODE REVIEW

File: packages/next/cli/next-dev.ts [hunk 1]
```diff
@@ -73,12 +73,16 @@ const nextDev: cliCommand = (argv) => {
 
   const port =
     args['--port'] || (process.env.PORT && parseInt(process.env.PORT)) || 3000
-  const host = args['--hostname'] || '0.0.0.0'
-  const appUrl = `http://${host === '0.0.0.0' ? 'localhost' : host}:${port}`
+
+  // We do not set a default host value here to prevent breaking
+  // some set-ups that rely on listening on other interfaces
+  const host = args['--hostname']
+  const ipPort = `${!host ? 'localhost' : host}:${port}`
```
Comment (styfle) [inline packages/next/cli/next-dev.ts:80]:
```suggestion
  const ipPort = `${host || 'localhost'}:${port}`
```

I think this is equivalent

**Review by styfle — COMMENTED** [review]
Can we add a test for this to ensure it fixes the bug?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| buildDuration | 16.1s | 16.3s | ⚠️ +155ms |
| buildDurationCached | 3.7s | 3.6s | -54ms |
| nodeModulesSize | 49.5 MB | 49.5 MB | ⚠️ +288 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.577 | 2.531 | -0.05 |
| / avg req/sec | 970.29 | 987.69 | +17.4 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.38 | 1.382 | 0 |
| /error-in-render avg req/sec | 1812.05 | 1809.34 | ⚠️ -2.71 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| 359.HASH.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 745.HASH.js gzip | 180 B | 180 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 20.9 kB | 20.9 kB | ✓ |
| webpack-HASH.js gzip | 1.53 kB | 1.53 kB | ✓ |
| Overall change | 67.8 kB | 67.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 554 B | 554 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.52 kB | 2.52 kB | ✓ |
| head-HASH.js gzip | 2.28 kB | 2.28 kB | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.6 kB | 5.6 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.1 kB | 19.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _buildManifest.js gzip | 489 B | 489 B | ✓ |
| Overall change | 489 B | 489 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.7s | -138ms |
| buildDurationCached | 5s | 4.9s | -69ms |
| nodeModulesSize | 49.5 MB | 49.5 MB | ⚠️ +288 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.514 | 2.521 | ⚠️ +0.01 |
| / avg req/sec | 994.45 | 991.77 | ⚠️ -2.68 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.378 | 1.39 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1813.74 | 1799.15 | ⚠️ -14.59 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| 17.HASH.js gzip | 2.98 kB | 2.98 kB | ✓ |
| 18.HASH.js gzip | 185 B | 185 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 8.4 kB | 8.4 kB | ✓ |
| webpack-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| Overall change | 68.4 kB | 68.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.76 kB | 3.76 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.71 kB | 2.71 kB | ✓ |
| head-HASH.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.02 kB | 3.02 kB | ✓ |
| withRouter-HASH.js gzip | 294 B | 294 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 17.6 kB | 17.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| index.html gzip | 577 B | 577 B | ✓ |
| link.html gzip | 588 B | 588 B | ✓ |
| withRouter.html gzip | 569 B | 569 B | ✓ |
| Overall change | 1.73 kB | 1.73 kB | ✓ |

</details>

</details>
Commit: 67990900cd7650589eb86f94d0bd219849ffc0ba

**Comment by ijjk** [comment]
It doesn't look like we can add a test case for this since it affects specific Windows configurations/network setups, although an affected user helped confirm this resolved the issue here https://github.com/vercel/next.js/issues/27298#issuecomment-882851936

**Review by styfle — DISMISSED** [review]
Thanks! 🎉

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 70de745e15b5152472729222f884d7848b56601d

**test/integration/cli/test/index.test.js** 
- CLI Usage > dev > --port
- CLI Usage > dev > NODE_OPTIONS='--inspect'
- CLI Usage > dev > -p
- CLI Usage > dev > --hostname
- CLI Usage > dev > -H

<details>
<summary>Expand output</summary>

  ● CLI Usage › dev › --port

    expect(received).toMatch(expected)

    Expected pattern: /on 0.0.0.0:37347/
    Received string:  "ready - started server on localhost:37347, url: http://localhost:37347
    "

      138 |       const port = await findPort()
      139 |       const output = await runNextCommandDev([dir, '--port', port], true)
    > 140 |       expect(output).toMatch(new RegExp(`on 0.0.0.0:${port}`))
          |                      ^
      141 |       expect(output).toMatch(new RegExp(`http://localhost:${port}`))
      142 |     })
      143 |

      at Object.<anonymous> (integration/cli/test/index.test.js:140:22)

  ● CLI Usage › dev › NODE_OPTIONS='--inspect'

    expect(received).toMatch(expected)

    Expected pattern: /on 0.0.0.0:46789/
    Received string:  "ready - started server on localhost:46789, url: http://localhost:46789
    "

      149 |         env: { NODE_OPTIONS: '--inspect' },
      150 |       })
    > 151 |       expect(output).toMatch(new RegExp(`on 0.0.0.0:${port}`))
          |                      ^
      152 |       expect(output).toMatch(new RegExp(`http://localhost:${port}`))
      153 |     })
      154 |

      at Object.<anonymous> (integration/cli/test/index.test.js:151:22)

  ● CLI Usage › dev › -p

    expect(received).toMatch(expected)

    Expected pattern: /on 0.0.0.0:36965/
    Received string:  "ready - started server on localhost:36965, url: http://localhost:36965
    "

      156 |       const port = await findPort()
      157 |       const output = await runNextCommandDev([dir, '-p', port], true)
    > 158 |       expect(output).toMatch(new RegExp(`on 0.0.0.0:${port}`))
          |                      ^
      159 |       expect(output).toMatch(new RegExp(`http://localhost:${port}`))
      160 |     })
      161 |

      at Object.<anonymous> (integration/cli/test/index.test.js:158:22)

  ● CLI Usage › dev › --hostname

    expect(received).toMatch(expected)

    Expected pattern: /http:\/\/localhost:34075/
    Received string:  "ready - started server on 0.0.0.0:34075, url: http://0.0.0.0:34075
    "

      200 |       )
      201 |       expect(output).toMatch(new RegExp(`on 0.0.0.0:${port}`))
    > 202 |       expect(output).toMatch(new RegExp(`http://localhost:${port}`))
          |                      ^
      203 |     })
      204 |
      205 |     test('-H', async () => {

      at Object.<anonymous> (integration/cli/test/index.test.js:202:22)

  ● CLI Usage › dev › -H

    expect(received).toMatch(expected)

    Expected pattern: /http:\/\/localhost:46337/
    Received string:  "ready - started server on 0.0.0.0:46337, url: http://0.0.0.0:46337
    "

      210 |       )
      211 |       expect(output).toMatch(new RegExp(`on 0.0.0.0:${port}`))
    > 212 |       expect(output).toMatch(new RegExp(`http://localhost:${port}`))
          |                      ^
      213 |     })
      214 |
      215 |     test('should warn when unknown argument provided', async () => {

      at Object.<anonymous> (integration/cli/test/index.test.js:212:22)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| buildDuration | 15.6s | 15.4s | -228ms |
| buildDurationCached | 3.5s | 3.5s | -33ms |
| nodeModulesSize | 49.5 MB | 49.5 MB | ⚠️ +264 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.433 | 2.432 | 0 |
| / avg req/sec | 1027.41 | 1027.79 | +0.38 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.364 | 1.322 | -0.04 |
| /error-in-render avg req/sec | 1833.36 | 1891.3 | +57.94 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| 359.HASH.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 745.HASH.js gzip | 180 B | 180 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 20.9 kB | 20.9 kB | ✓ |
| webpack-HASH.js gzip | 1.53 kB | 1.53 kB | ✓ |
| Overall change | 67.8 kB | 67.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 554 B | 554 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.52 kB | 2.52 kB | ✓ |
| head-HASH.js gzip | 2.28 kB | 2.28 kB | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.6 kB | 5.6 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.1 kB | 19.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _buildManifest.js gzip | 489 B | 489 B | ✓ |
| Overall change | 489 B | 489 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.2s | -159ms |
| buildDurationCached | 4.8s | 4.8s | -25ms |
| nodeModulesSize | 49.5 MB | 49.5 MB | ⚠️ +264 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.443 | 2.499 | ⚠️ +0.06 |
| / avg req/sec | 1023.53 | 1000.43 | ⚠️ -23.1 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.318 | 1.306 | -0.01 |
| /error-in-render avg req/sec | 1896.26 | 1914.04 | +17.78 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| 17.HASH.js gzip | 2.98 kB | 2.98 kB | ✓ |
| 18.HASH.js gzip | 185 B | 185 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 8.4 kB | 8.4 kB | ✓ |
| webpack-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| Overall change | 68.4 kB | 68.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.76 kB | 3.76 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.71 kB | 2.71 kB | ✓ |
| head-HASH.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.02 kB | 3.02 kB | ✓ |
| withRouter-HASH.js gzip | 294 B | 294 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 17.6 kB | 17.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| index.html gzip | 577 B | 577 B | ✓ |
| link.html gzip | 588 B | 588 B | ✓ |
| withRouter.html gzip | 569 B | 569 B | ✓ |
| Overall change | 1.73 kB | 1.73 kB | ✓ |

</details>

</details>
Commit: 70de745e15b5152472729222f884d7848b56601d

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.3s | -287ms |
| buildDurationCached | 2.9s | 2.9s | ⚠️ +3ms |
| nodeModulesSize | 49.5 MB | 49.5 MB | ⚠️ +347 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.98 | 2.048 | ⚠️ +0.07 |
| / avg req/sec | 1262.9 | 1220.52 | ⚠️ -42.38 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.122 | 1.123 | 0 |
| /error-in-render avg req/sec | 2228.57 | 2227.16 | ⚠️ -1.41 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| 359.HASH.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 745.HASH.js gzip | 180 B | 180 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 20.9 kB | 20.9 kB | ✓ |
| webpack-HASH.js gzip | 1.53 kB | 1.53 kB | ✓ |
| Overall change | 67.8 kB | 67.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 554 B | 554 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.52 kB | 2.52 kB | ✓ |
| head-HASH.js gzip | 2.28 kB | 2.28 kB | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.6 kB | 5.6 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.1 kB | 19.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _buildManifest.js gzip | 489 B | 489 B | ✓ |
| Overall change | 489 B | 489 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| buildDuration | 10s | 10s | ⚠️ +13ms |
| buildDurationCached | 4s | 4s | ⚠️ +81ms |
| nodeModulesSize | 49.5 MB | 49.5 MB | ⚠️ +347 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.933 | 2.018 | ⚠️ +0.08 |
| / avg req/sec | 1293.18 | 1238.8 | ⚠️ -54.38 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.052 | 1.057 | 0 |
| /error-in-render avg req/sec | 2375.51 | 2365.42 | ⚠️ -10.09 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| 17.HASH.js gzip | 2.98 kB | 2.98 kB | ✓ |
| 18.HASH.js gzip | 185 B | 185 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 8.4 kB | 8.4 kB | ✓ |
| webpack-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| Overall change | 68.4 kB | 68.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.76 kB | 3.76 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.71 kB | 2.71 kB | ✓ |
| head-HASH.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.02 kB | 3.02 kB | ✓ |
| withRouter-HASH.js gzip | 294 B | 294 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 17.6 kB | 17.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| index.html gzip | 577 B | 577 B | ✓ |
| link.html gzip | 588 B | 588 B | ✓ |
| withRouter.html gzip | 569 B | 569 B | ✓ |
| Overall change | 1.73 kB | 1.73 kB | ✓ |

</details>

</details>
Commit: 9bd9e1b7dd155d3d2be0e28fac54c86d4a88c429

**Review by styfle — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| buildDuration | 13s | 12.9s | -97ms |
| buildDurationCached | 3s | 3s | -34ms |
| nodeModulesSize | 49.5 MB | 49.5 MB | ⚠️ +349 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.079 | 2.057 | -0.02 |
| / avg req/sec | 1202.39 | 1215.48 | +13.09 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.114 | 1.13 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2244.41 | 2211.66 | ⚠️ -32.75 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| 359.HASH.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 745.HASH.js gzip | 180 B | 180 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 20.9 kB | 20.9 kB | ✓ |
| webpack-HASH.js gzip | 1.53 kB | 1.53 kB | ✓ |
| Overall change | 67.8 kB | 67.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 554 B | 554 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.52 kB | 2.52 kB | ✓ |
| head-HASH.js gzip | 2.28 kB | 2.28 kB | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.6 kB | 5.6 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.1 kB | 19.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _buildManifest.js gzip | 489 B | 489 B | ✓ |
| Overall change | 489 B | 489 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.4s | -92ms |
| buildDurationCached | 4.1s | 4s | -78ms |
| nodeModulesSize | 49.5 MB | 49.5 MB | ⚠️ +349 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.07 | 2.044 | -0.03 |
| / avg req/sec | 1207.75 | 1223.33 | +15.58 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.1 | 1.113 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2272.58 | 2246.22 | ⚠️ -26.36 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| 17.HASH.js gzip | 2.98 kB | 2.98 kB | ✓ |
| 18.HASH.js gzip | 185 B | 185 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 8.4 kB | 8.4 kB | ✓ |
| webpack-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| Overall change | 68.4 kB | 68.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.76 kB | 3.76 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.71 kB | 2.71 kB | ✓ |
| head-HASH.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.02 kB | 3.02 kB | ✓ |
| withRouter-HASH.js gzip | 294 B | 294 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 17.6 kB | 17.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/windows-listening | Change |
| - | - | - | - |
| index.html gzip | 577 B | 577 B | ✓ |
| link.html gzip | 588 B | 588 B | ✓ |
| withRouter.html gzip | 569 B | 569 B | ✓ |
| Overall change | 1.73 kB | 1.73 kB | ✓ |

</details>

</details>
Commit: 0edc2e5ad48e5c0dd6ec889e1d3b34470409c7be
