### PR TITLE
Fix extra swc optimizer applied to node_modules in browser layer

### LINKED ISSUE #60644: Worker not compiling correctly, window is undefined in files after canary 14.0.5-canary.19
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/trusting-glade-g3l38y?file=%2Fapp%2Fpage.tsx%3A7%2C1

### To Reproduce

pnpm install
pnpm dev

show the console and see the window is undefined

### Current vs. Expected behavior

window var is undefined and should be defined as this is in the browser context

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
after any canary 14.0.5-canary.19
```

### Which area(s) are affected? (Select all that apply)

App Router, SWC transpilation

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

canary 14.0.5-canary.19 works perfectly

### LINKED ISSUE #60920: worker with `type=module` in `use client` page causing error `Uncaught ReferenceError: window is not defined` since 14.0.5-canary.20
### Link to the code that reproduces this issue

https://codesandbox.io/p/github/rbox-risk/workerv1_1/main?file=%2Fpackage.json

### To Reproduce

I'm using tensorflow in the worker, so kept this in, otherwise a minimal example with next 14.0.4 (working)
`https://codesandbox.io/p/github/rbox-risk/workerv2_1/main`

In sandbox, client page rendered, `useEffect` loads worker  with `type: module` and worker posts a result back `tf ok` is all went well. 

Confirm error emits with latest release `14.1` and latest canary. 
Error appeared at `canary.20` and confirmed works with `canary.19`.

`https://codesandbox.io/p/github/rbox-risk/workerv1_1/main?file=%2Fpackage.json`

Here worker doesn't return. Hangs on `working...`. In `console` error appears. 

Capture-worker1

### Current vs. Expected behavior

Expect worker to load, work and return value as per pre `canary.20`

### Provide environment information

```bash
//sandbox instance....

Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.14.1
Relevant Packages:
  next: 14.0.5-canary.20
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), Vercel (Deployed)

### Additional context

Tested on chrome, sandbox, dev local and when deployed to Vercel. Issues remain the same

### LINKED ISSUE #61740: Video.js in App Route - window is not defined
### Link to the code that reproduces this issue

https://codesandbox.io/p/github/mufteev/nextjs-videojs-app-bug/main

### To Reproduce

1. pnpm build
2. pnpm start

### Current vs. Expected behavior

**Current**
Catch `Uncaught Error: Uncaught ReferenceError: window is not defined` in console and not work video.js
Cloned an example from a folder [https://github.com/vercel/next.js/tree/canary/examples/with-videojs](examples/with-videojs) and ported to App Router
I get an error when using `App Router` in `14.1.0` (latest), but if I change the version to `^13.5.6` - Video.js worked.

**Expected**
Video.js libraries initialized and mount component similar like previous major version
  
It is worth noting that everything works fine in `dev` mode, and the bug itself occurs in production

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #15-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan  9 17:03:36 UTC 2024
Binaries:
  Node: 21.6.1
  npm: 10.2.4
  Yarn: N/A
  pnpm: 8.15.1
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next start (local)

### Additional context

I tested my reproduction in `14.1.1-canary.38` and and I still got the error:
```
blob:https://ly5p9t-3000.csb.app/b8589df3-9974-4a07-9038-ff100f3439fd:545 Uncaught ReferenceError: window is not defined
blob:https://ly5p9t-3000.csb.app/e2588c9a-dda0-447c-bc9c-69f532a83de7:6147 Uncaught ReferenceError: window is not defined
blob:https://ly5p9t-3000.csb.app/2f11b57f-873e-410d-b799-d7e1b46807a6:6147 Uncaught ReferenceError: window is not defined
```

Link github reproduction: [nextjs-videojs-app-bug](https://github.com/mufteev/nextjs-videojs-app-bug)

### LINKED ISSUE #61858: In web worker, typeof window === 'undefined' is falsely bundled to `true`
### Link to the code that reproduces this issue

https://github.com/yf-yang/next-webworker-bug

### To Reproduce

1. pnpm i
2. pnpm dev
3. open the window, click the button

### Current vs. Expected behavior

Expected:
Web worker started, then debugjs can log a message "worker started" (console log level should be "verbose")
Current:
Error: Uncaught ReferenceError: window is not defined

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.14.3
Relevant Packages:
  next: 14.1.1-canary.45 // Latest available version is detected (14.1.1-canary.45).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

SWC transpilation

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

The error is this line in `debug.js`:
https://github.com/debug-js/debug/blob/f66cb2d9f729e1a592e72d3698e3b75329d75a25/src/browser.js#L119-L121
``` javascript
if (typeof window !== 'undefined' && window.process ...) {
  ...
}
```
In the bundled output file `.next/static/chunks/_app-pages-browser_app_worker_js.js`, this line is transpiled to
``` javascript
if (true && window.process ...) {
  ...
}
```
The bundled output is wrong, because in web worker, `window` does not exist.

NOTE: This bug does not exist in next@13.5.6
> Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.14.3
Relevant Packages:
  next: 13.5.6
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A

<sub>[NEXT-2418](https://linear.app/vercel/issue/NEXT-2418/in-web-worker-typeof-window-===-undefined-is-falsely-bundled-to-true)</sub>

### PR DESCRIPTION
**Pull request by huozhi**
### What

Disable swc transform optimizer for node_modules in browser layer of app router bundles

Fixes #61858
Fixes #60644 
Fixes #60920
Fixes #61740
Closes NEXT-2418

### Why

In browser there could be not only one runtime, it could have both js worker and browser. In js worker the `typeof window` is not as same as in browser, so disabling the swc optimizer which will replace the code. Leave the condition as it as.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: e890c60759b20ccd7c0a4c83256de51cb23defb1

`pnpm test-start test/e2e/app-dir/app/experimental-compile.test.ts` (PPR)
- app dir - basic > known bugs > should support React fetch instrumentation > server component client-navigation

<details>
<summary>Expand output</summary>

  ● app dir - basic › known bugs › should support React fetch instrumentation › server component client-navigation

    expect(received).toBe(expected) // Object.is equality

    Expected: "0.23454354467229566"
    Received: "0.7632030125027818"

      1490 |           // TODO: enable when fetch cache is enabled in dev
      1491 |           if (!isDev) {
    > 1492 |             expect(val1).toBe(val2)
           |                          ^
      1493 |           }
      1494 |         })
      1495 |

      at Object.toBe (e2e/app-dir/app/index.test.ts:1492:26)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/swc-optimize-node-modules | Change |
| - | - | - | - |
| buildDuration | 19.6s | 19.8s | ⚠️ +180ms |
| buildDurationCached | 7.7s | 6.9s | N/A |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +1.21 kB |
| nextStartRea..uration (ms) | 427ms | 431ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/swc-optimize-node-modules | Change |
| - | - | - | - |
| 1068-HASH.js gzip | 30 kB | 30.2 kB | ⚠️ +144 B |
| 3f784ff6-HASH.js gzip | 53.5 kB | 53.5 kB | N/A |
| 4944-HASH.js gzip | 4.96 kB | 5.03 kB | N/A |
| 8423.HASH.js gzip | 181 B | 181 B | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 241 B | ✓ |
| main-HASH.js gzip | 32 kB | 32 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 77.4 kB | 77.5 kB | ⚠️ +144 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/swc-optimize-node-modules | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/swc-optimize-node-modules | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 196 B | ✓ |
| _error-HASH.js gzip | 184 B | 183 B | N/A |
| amp-HASH.js gzip | 503 B | 504 B | N/A |
| css-HASH.js gzip | 323 B | 324 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.51 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 353 B | 351 B | N/A |
| hooks-HASH.js gzip | 370 B | 370 B | ✓ |
| image-HASH.js gzip | 4.21 kB | 4.2 kB | N/A |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.68 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 313 B | 314 B | N/A |
| script-HASH.js gzip | 386 B | 385 B | N/A |
| withRouter-HASH.js gzip | 309 B | 311 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 931 B | 931 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/swc-optimize-node-modules | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/swc-optimize-node-modules | Change |
| - | - | - | - |
| index.html gzip | 529 B | 527 B | N/A |
| link.html gzip | 541 B | 540 B | N/A |
| withRouter.html gzip | 525 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/swc-optimize-node-modules | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94.4 kB | 94.5 kB | N/A |
| page.js gzip | 151 kB | 151 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/swc-optimize-node-modules | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 625 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 44.4 kB | 44.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.94 kB | 1.94 kB | ✓ |
| Overall change | 2.1 kB | 2.1 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/swc-optimize-node-modules | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 166 kB | 166 kB | ✓ |
| app-page-exp..prod.js gzip | 95.5 kB | 95.5 kB | ✓ |
| app-page-tur..prod.js gzip | 97.2 kB | 97.2 kB | ✓ |
| app-page-tur..prod.js gzip | 91.7 kB | 91.7 kB | ✓ |
| app-page.run...dev.js gzip | 136 kB | 136 kB | ✓ |
| app-page.run..prod.js gzip | 90.2 kB | 90.2 kB | ✓ |
| app-route-ex...dev.js gzip | 22 kB | 22 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.7 kB | 9.7 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-turbo...prod.js gzip | 22 kB | 22 kB | ✓ |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | ✓ |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | ✓ |
| server.runti..prod.js gzip | 50 kB | 50 kB | ✓ |
| Overall change | 925 kB | 925 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/swc-optimize-node-modules | Change |
| - | - | - | - |
| 0.pack gzip | 1.55 MB | 1.54 MB | N/A |
| index.pack gzip | 103 kB | 103 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>1068-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>4944-HASH.js</strong></summary>

```diff
@@ -1,8 +1,8 @@
 "use strict";
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
-  [4944],
+  [1363],
   {
-    /***/ 4944: /***/ function (module, exports, __webpack_require__) {
+    /***/ 1363: /***/ function (module, exports, __webpack_require__) {
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
         value: true,
@@ -13,25 +13,25 @@
           return Image;
         },
       });
-      const _interop_require_default = __webpack_require__(5811);
-      const _interop_require_wildcard = __webpack_require__(9075);
-      const _jsxruntime = __webpack_require__(6435);
+      const _interop_require_default = __webpack_require__(267);
+      const _interop_require_wildcard = __webpack_require__(9754);
+      const _jsxruntime = __webpack_require__(2260);
       const _react = /*#__PURE__*/ _interop_require_wildcard._(
-        __webpack_require__(8288)
+        __webpack_require__(4978)
       );
       const _reactdom = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(4364)
+        __webpack_require__(7)
       );
       const _head = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(1046)
+        __webpack_require__(4780)
       );
-      const _getimgprops = __webpack_require__(6028);
-      const _imageconfig = __webpack_require__(1939);
-      const _imageconfigcontextsharedruntime = __webpack_require__(9525);
-      const _warnonce = __webpack_require__(8915);
-      const _routercontextsharedruntime = __webpack_require__(9139);
+      const _getimgprops = __webpack_require__(8291);
+      const _imageconfig = __webpack_require__(8794);
+      const _imageconfigcontextsharedruntime = __webpack_require__(978);
+      const _warnonce = __webpack_require__(134);
+      const _routercontextsharedruntime = __webpack_require__(6183);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(5732)
+        __webpack_require__(7857)
       );
       // This is replaced by webpack define plugin
       const configEnv = {
@@ -42,7 +42,8 @@
         dangerouslyAllowSVG: false,
         unoptimized: false,
       };
-      if (false) {
+      if (typeof window === "undefined") {
+        globalThis.__NEXT_IMAGE_IMPORTED = true;
       }
       // See https://stackoverflow.com/q/39777833/266535 for why we use this ref
       // handler instead of the img's onLoad attribute.
@@ -362,7 +363,7 @@
       /***/
     },
 
-    /***/ 9331: /***/ function (
+    /***/ 5768: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -376,9 +377,9 @@
           return AmpStateContext;
         },
       });
-      const _interop_require_default = __webpack_require__(5811);
+      const _interop_require_default = __webpack_require__(267);
       const _react = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(8288)
+        __webpack_require__(4978)
       );
       const AmpStateContext = _react.default.createContext({});
       if (false) {
@@ -387,7 +388,7 @@
       /***/
     },
 
-    /***/ 6039: /***/ function (__unused_webpack_module, exports) {
+    /***/ 9854: /***/ function (__unused_webpack_module, exports) {
       Object.defineProperty(exports, "__esModule", {
         value: true,
       });
@@ -409,7 +410,7 @@
       /***/
     },
 
-    /***/ 6028: /***/ function (
+    /***/ 8291: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -423,9 +424,9 @@
           return getImgProps;
         },
       });
-      const _warnonce = __webpack_require__(8915);
-      const _imageblursvg = __webpack_require__(1185);
-      const _imageconfig = __webpack_require__(1939);
+      const _warnonce = __webpack_require__(134);
+      const _imageblursvg = __webpack_require__(2769);
+      const _imageconfig = __webpack_require__(8794);
       const VALID_LOADING_VALUES =
         /* unused pure expression or super */ null && [
           "lazy",
@@ -794,7 +795,7 @@
       /***/
     },
 
-    /***/ 1046: /***/ function (module, exports, __webpack_require__) {
+    /***/ 4780: /***/ function (module, exports, __webpack_require__) {
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
         value: true,
@@ -815,19 +816,19 @@
           return _default;
         },
       });
-      const _interop_require_default = __webpack_require__(5811);
-      const _interop_require_wildcard = __webpack_require__(9075);
-      const _jsxruntime = __webpack_require__(6435);
+      const _interop_require_default = __webpack_require__(267);
+      const _interop_require_wildcard = __webpack_require__(9754);
+      const _jsxruntime = __webpack_require__(2260);
       const _react = /*#__PURE__*/ _interop_require_wildcard._(
-        __webpack_require__(8288)
+        __webpack_require__(4978)
       );
       const _sideeffect = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(3273)
+        __webpack_require__(5743)
       );
-      const _ampcontextsharedruntime = __webpack_require__(9331);
-      const _headmanagercontextsharedruntime = __webpack_require__(1138);
-      const _ampmode = __webpack_require__(6039);
-      const _warnonce = __webpack_require__(8915);
+      const _ampcontextsharedruntime = __webpack_require__(5768);
+      const _headmanagercontextsharedruntime = __webpack_require__(6898);
+      const _ampmode = __webpack_require__(9854);
+      const _warnonce = __webpack_require__(134);
       function defaultHead(inAmpMode) {
         if (inAmpMode === void 0) inAmpMode = false;
         const head = [
@@ -1003,7 +1004,7 @@
       /***/
     },
 
-    /***/ 1185: /***/ function (__unused_webpack_module, exports) {
+    /***/ 2769: /***/ function (__unused_webpack_module, exports) {
       /**
        * A shared function, used on both client and server, to generate a SVG blur placeholder.
        */
@@ -1057,7 +1058,7 @@
       /***/
     },
 
-    /***/ 9525: /***/ function (
+    /***/ 978: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1071,11 +1072,11 @@
           return ImageConfigContext;
         },
       });
-      const _interop_require_default = __webpack_require__(5811);
+      const _interop_require_default = __webpack_require__(267);
       const _react = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(8288)
+        __webpack_require__(4978)
       );
-      const _imageconfig = __webpack_require__(1939);
+      const _imageconfig = __webpack_require__(8794);
       const ImageConfigContext = _react.default.createContext(
         _imageconfig.imageConfigDefault
       );
@@ -1085,7 +1086,7 @@
       /***/
     },
 
-    /***/ 1939: /***/ function (__unused_webpack_module, exports) {
+    /***/ 8794: /***/ function (__unused_webpack_module, exports) {
       Object.defineProperty(exports, "__esModule", {
         value: true,
       });
@@ -1132,7 +1133,7 @@
       /***/
     },
 
-    /***/ 5732: /***/ function (__unused_webpack_module, exports) {
+    /***/ 7857: /***/ function (__unused_webpack_module, exports) {
       Object.defineProperty(exports, "__esModule", {
         value: true,
       });
@@ -1165,7 +1166,7 @@
       /***/
     },
 
-    /***/ 9139: /***/ function (
+    /***/ 6183: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1179,9 +1180,9 @@
           return RouterContext;
         },
       });
-      const _interop_require_default = __webpack_require__(5811);
+      const _interop_require_default = __webpack_require__(267);
       const _react = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(8288)
+        __webpack_require__(4978)
       );
       const RouterContext = _react.default.createContext(null);
       if (false) {
@@ -1190,7 +1191,7 @@
       /***/
     },
 
-    /***/ 3273: /***/ function (
+    /***/ 5743: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1204,8 +1205,8 @@
           return SideEffect;
         },
       });
-      const _react = __webpack_require__(8288);
-      const isServer = "object" === "undefined";
+      const _react = __webpack_require__(4978);
+      const isServer = typeof window === "undefined";
       const useClientOnlyLayoutEffect = isServer
         ? () => {}
         : _react.useLayoutEffect;
```
</details>

</details>

</details>
Commit: e890c60759b20ccd7c0a4c83256de51cb23defb1

File: packages/next/src/build/swc/options.ts [hunk 1]
```diff
@@ -482,6 +482,12 @@ export function getLoaderSWCOptions({
     options.isPageFile = false
     options.optimizeServerReact = undefined
     options.cjsRequireOptimizer = undefined
+    // Disable optimizer for node_modules in app browser layer, to avoid unnecessary replacement.
+    // e.g. typeof window could result differently in js worker or browser.
+    // override for non-jest mode
+    if (options.jsc.transform.optimizer.globals) {
```
Comment (ijjk) [inline packages/next/src/build/swc/options.ts:488]:
```suggestion
    if (options.jsc.transform.optimizer.globals?.typeofs) {
```
Should we make this check more specific

**Review by ijjk — APPROVED** [review]

File: test/turbopack-tests-manifest.json [hunk 2]
```diff
@@ -2567,7 +2567,8 @@
     ],
     "failed": [
       "app dir - external dependency server actions should compile server actions from node_modules in client components",
-      "app dir - external dependency should be able to opt-out 3rd party packages being bundled in server components"
+      "app dir - external dependency should be able to opt-out 3rd party packages being bundled in server components",
+      "app dir - external dependency should not apply swc optimizer transform for external packages in browser layer"
```
Comment (ForsakenHarmony) [inline test/turbopack-tests-manifest.json:2571]: I think we agreed that any new tests have to pass for turbopack with the PR they get added with 👀

Comment (huozhi) [reply test/turbopack-tests-manifest.json:2571]: Will follow up this separately since we also need to visit the worker support in turbopack later
