### PR TITLE
Fix react packages are not bundled for metadata routes

### LINKED ISSUE #55561: Build fail when using `React.cache` in `sitemap.ts`
### Link to the code that reproduces this issue

https://github.com/mwskwong/cache-in-sitemap

### To Reproduce

1. Call a function, e.g. fetcher, wrapped in `React.cache` in `sitemap.ts`
2. Attempt to build the project

### Current vs. Expected behavior

Current: the following error will appear during build

```
   Collecting page data ..TypeError: (0 , p.cache) is not a function
    at 5398 (\.next\server\app\sitemap.xml\route.js:1:605)
    at t (\.next\server\webpack-runtime.js:1:127)
    at a (\.next\server\app\sitemap.xml\route.js:1:1737)
    at \.next\server\app\sitemap.xml\route.js:1:1764
    at t.X (\.next\server\webpack-runtime.js:1:1191)
    at \.next\server\app\sitemap.xml\route.js:1:1750
    at Object.<anonymous> (\.next\server\app\sitemap.xml\route.js:1:1791)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)

> Build error occurred
Error: Failed to collect page data for /sitemap.xml
    at \node_modules\next\dist\build\utils.js:1191:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```

Expected: build should be successful

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.17.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.40
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by huozhi**
`isAppLayer` condition was missing `app-metadata-route` layer, made it as a util now like other webpack layer utils, add metadata route layer to the group. Then `React.cache` can be available there. 

Also update regex to be compatible across platform

Fixes #55561 
Closes NEXT-1635

### CODE REVIEW

File: packages/next/src/build/webpack/loaders/next-flight-loader/module-proxy.ts [hunk 1]
```diff
@@ -1,5 +1,4 @@
-/* eslint-disable import/no-extraneous-dependencies */
-import { createClientModuleProxy } from 'react-server-dom-webpack/server.edge'
+import { createClientModuleProxy } from 'next/dist/compiled/react-server-dom-webpack/server.edge'
```
Comment (feedthejim) [inline packages/next/src/build/webpack/loaders/next-flight-loader/module-proxy.ts:1]: do we still need this?

**Review by feedthejim — DISMISSED** [review]

**Review by feedthejim — DISMISSED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8525a00a0d6c1e2739abe16bcde55f5c3b6173d2

`pnpm test test/integration/preload-viewport/test/index.test.js` 
- Prefetching Links in viewport > should prefetch with non-bot UA

<details>
<summary>Expand output</summary>

  ● Prefetching Links in viewport › should prefetch with non-bot UA

    expect(received).toHaveLength(expected)

    Expected length: 1
    Received length: 0
    Received array:  []

      126 |       )
      127 |       const links = await browser.elementsByCss('link[rel=prefetch]')
    > 128 |       expect(links).toHaveLength(1)
          |                     ^
      129 |     } finally {
      130 |       if (browser) await browser.close()
      131 |     }

      at Object.<anonymous> (integration/preload-viewport/test/index.test.js:128:21)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).
