### PR TITLE
sort dependencies for smaller diffs

### LINKED ISSUE #82290: Running `npm install` on a new Next.js project created from the CLI can create an unnecessarily large `diff`
### Link to the code that reproduces this issue

https://github.com/hamirmahal/large-next-diff

### To Reproduce

1. Run
```
npx create-next-app@latest
```
2. Run an install command, e.g.,
```
npm install eslint
```

### Current vs. Expected behavior

# Current behavior
There is a large `diff`.
```diff
diff --git a/package-lock.json b/package-lock.json
index b07f4ca..6c13e33 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -18,7 +18,7 @@
         "@types/node": "^20",
         "@types/react": "^19",
         "@types/react-dom": "^19",
-        "eslint": "^9",
+        "eslint": "^9.32.0",
         "eslint-config-next": "15.4.5",
         "tailwindcss": "^4",
         "typescript": "^5"
diff --git a/package.json b/package.json
index 79b4ae7..532ee0c 100644
--- a/package.json
+++ b/package.json
@@ -9,19 +9,19 @@
     "lint": "next lint"
   },
   "dependencies": {
+    "next": "15.4.5",
     "react": "19.1.0",
-    "react-dom": "19.1.0",
-    "next": "15.4.5"
+    "react-dom": "19.1.0"
   },
   "devDependencies": {
-    "typescript": "^5",
+    "@eslint/eslintrc": "^3",
+    "@tailwindcss/postcss": "^4",
     "@types/node": "^20",
     "@types/react": "^19",
     "@types/react-dom": "^19",
-    "@tailwindcss/postcss": "^4",
-    "tailwindcss": "^4",
-    "eslint": "^9",
+    "eslint": "^9.32.0",
     "eslint-config-next": "15.4.5",
-    "@eslint/eslintrc": "^3"
+    "tailwindcss": "^4",
+    "typescript": "^5"
   }
 }
```

# Expected Behavior

The `diff` is minimal, and users of Next.js experience less noise.

### Provide environment information

```bash
$  npx --no-install next info
/bin/sh: 1: yarn: not found

Operating System:
  Platform: linux
  Arch: x64
  Version: #27~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 22 17:38:49 UTC 2
  Available memory (MB): 32036
  Available CPU cores: 8
Binaries:
  Node: 22.16.0
  npm: 11.4.2
  Yarn: N/A
  pnpm: 10.12.4
Relevant Packages:
  next: 15.4.5 // Latest available version is detected (15.4.5).
  eslint-config-next: 15.4.5
  react: 19.1.0
  react-dom: 19.1.0
  typescript: 5.8.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hamirmahal**
Fixes #82290

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [x] approve CI run for commit: 4b338795cb26c262623e733afe1d6ae2830f6e1f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

File: packages/create-next-app/templates/index.ts [hunk 1]
```diff
@@ -269,6 +269,27 @@ export const installTemplate = async ({
...
 
+  // Sort dependencies and devDependencies alphabetically
+  if (packageJson.dependencies) {
+    const sortedDeps = Object.keys(packageJson.dependencies)
+      .sort()
+      .reduce((acc: Record<string, string>, key: string) => {
+        acc[key] = packageJson.dependencies[key];
+        return acc;
+      }, {});
+    packageJson.dependencies = sortedDeps;
```
Comment (noahsilas) [inline packages/create-next-app/templates/index.ts]: I just bumped into this same behavior and was bothered by it as well, thanks for fixing it! I was considering an alternative strategy of adding a [`replacer` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#using_a_function_as_replacer) that could emit everything in order, but doing that naively was also going to sort the root keys, which would be awkward. Mutating these values specifically seems like a better approach! Nice :tada:

Comment (hamirmahal) [reply packages/create-next-app/templates/index.ts]: Thanks!

**Comment by hamirmahal** [comment]
@styfle are you open to this change?

File: packages/create-next-app/templates/index.ts (hunk 1 above)
Comment (styfle) [reply packages/create-next-app/templates/index.ts]: Since its the same code for `devDependencies and `devDependencies`, lets move it into a function. Something like

```ts
function sortKeys(obj: Record<string, string>): Record<string, string> {
    return Object.keys(obj)
      .sort()
      .reduce((acc) => {
        acc[key] = obj[key];
        return acc;
      }, {});
}
```

And actually I think you could improve this code by using `Object.entries()` instead of keys

Comment (hamirmahal) [reply packages/create-next-app/templates/index.ts]: That makes sense. I'll update the code to use a reusable function right now.

**Review by styfle — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 4b72733d33285b15f334706ae18b319ec65d3096 | [About building and testing Next.js](https://github.com/vercel/next.js/blob/canary/contributing.md)
