### PR TITLE
remove optimistic navigation behavior when prefetch is false

### LINKED ISSUE #50670: next/link prefetch=false broken for dynamic routes
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 1.22.5
      pnpm: 6.23.6
    Relevant packages:
      next: 13.5.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/cjonesdoordash/nextjs-prefetch-issue

### To Reproduce

Run the example and click the link to navigate between pages. You'll notice that the async data fetched within the layout.tsx file that shouldn't be re-fetched between navigations is refetched every time (it will hit cache eventually, but this behavior is incorrect as layouts shouldn't be re-rendered)

Another interesting side effect of this is if you hard reload a page after you've hit the fetch cache is that you'll get new data, but clicking a link to navigate will actually give you a cache hit on the old cache entry, which definitely shouldn't happen.

### Describe the Bug

To start off I've only been able to reproduce this issue when utilizing a dynamic segment (pages without a dynamic segment above them don't run into this issue).

If you use one and have pages below it that share a common layout and link to each other with prefetch set to false you can validate via console logs or fetch calls that the layout is re-ran on every navigation.

According to the docs layouts are meant to not re-render when you're just navigating within their segment.

### Expected Behavior

Setting prefetch to false on links doesn't break the documented layout behavior for dynamic routes

### Which browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

### PR DESCRIPTION
**Pull request by ztanner**
### What?
When navigating between pages (via `prefetch: false`) within a dynamic segment, the shared layout is re-rendered. This can cause unexpected behavior like layout data changing when navigating between child segments.

### Why?
When prefetch is false, we're currently opting into an "optimistic navigation" codepath, which will optimistically render layout-routers up to the point where data is missing, while kicking off data fetches. It attempts to determine where refetching needs to happen by traversing the router cache nodes and checking where data is missing. However, it locates these cache nodes by using "segments" obtained by [deconstructing the URL](https://github.com/vercel/next.js/blob/fix/optimistic-bailout/packages/next/src/client/components/router-reducer/reducers/navigate-reducer.ts#L142), which won't accurately contain dynamic segment data. For ex, `/en` which corresponds with `/app/[lang]/page.tsx` will have a cache node key of `lang|en|d`, not `en`. Similarly, the optimistic tree that gets constructed will also be incorrect, since it uses the URL segment.

### How?
My initial fix was to match the dynamic segment against the segment constructed by the URL. But after discussion with @sebmarkbage and the team, it seems more correct to remove the optimistic case all together as there's no guarantee that the url will actually match to that segment.

Fixes #50670

### CODE REVIEW

File: packages/next/src/client/components/match-segments.ts [hunk 1]
```diff
@@ -20,6 +21,35 @@ export const matchSegment = (
   return existingSegment[0] === segment[0] && existingSegment[1] === segment[1]
 }
 
+export const matchDynamicSegment = (
+  existingSegment: Segment,
```
Comment (feedthejim) [inline packages/next/src/client/components/match-segments.ts:25]: nit: is there a better for this parameter that would better indicate that the two segments' arguments are treated differently? it's not apparent from the name of the fn.

Comment (feedthejim) [reply packages/next/src/client/components/match-segments.ts:25]: maybe a JS doc at the top of the fn is enough

File: packages/next/src/client/components/router-reducer/fill-cache-with-data-property.ts [hunk 2]
```diff
@@ -39,9 +48,22 @@ export function fillCacheWithDataProperty(
     newCache.parallelRoutes.set(parallelRouteKey, childSegmentMap)
   }
 
-  const existingChildCacheNode = existingChildSegmentMap.get(cacheKey)
+  let existingChildCacheNode = existingChildSegmentMap.get(cacheKey)
   let childCacheNode = childSegmentMap.get(cacheKey)
 
+  if (!childCacheNode || !existingChildCacheNode) {
+    for (const key of existingChildSegmentMap.keys()) {
```
Comment (feedthejim) [inline packages/next/src/client/components/router-reducer/fill-cache-with-data-property.ts:55]: nit: could just use object.entries here to avoid the the `get` call on line 60

File: packages/next/src/client/components/match-segments.ts [hunk 3]
```diff
@@ -20,6 +21,35 @@ export const matchSegment = (
...
+  segment: Segment
+) => {
+  // If segment is dynamic (an array), we can't match
+  if (Array.isArray(segment)) {
```
Comment (feedthejim) [inline packages/next/src/client/components/match-segments.ts:29]: why can't we?

File: packages/next/src/client/components/match-segments.ts [hunk 4]
```diff
@@ -20,6 +20,31 @@ export const matchSegment = (
...
 }
 
+/*
+ * This function takes an existing dynamic segment and attempts to match it against
+ * an incoming segment
+ */
+export const matchDynamicSegment = (
+  existingSegment: Segment,
+  segment: Segment
+) => {
```
Comment (timneutkens) [inline packages/next/src/client/components/match-segments.ts:30]:
```suggestion
): boolean => {
```

File: packages/next/src/client/components/router-reducer/create-optimistic-tree.ts [hunk 5]
```diff
@@ -12,11 +15,23 @@ export function createOptimisticTree(
...
     flightRouterState || [null, {}]
-  const segment = segments[0]
+  let segment: Segment = segments[0]
+  let segmentMatches = false
   const isLastSegment = segments.length === 1
 
-  const segmentMatches =
-    existingSegment !== null && matchSegment(existingSegment, segment)
+  if (existingSegment !== null) {
+    // attempts to match a dynamic segment. Since "segment" is derived from the URL
```
[the remark this answers is not in the document]
Comment (ztanner) [reply packages/next/src/client/components/router-reducer/create-optimistic-tree.ts:23]: Yeah this was my first approach in [d515ba1](https://github.com/vercel/next.js/pull/58413/commits/d515b81cc1bd4c91e6affcfb54efd1d5a7b8eeb6) — I could revert back to that if we prefer that. Are you thinking it might not be safe to loosely match here?

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/optimistic-bailout | Change |
| - | - | - | - |
| buildDuration | 10.9s | 10.8s | N/A |
| buildDurationCached | 5.9s | 6s | N/A |
| nodeModulesSize | 199 MB | 199 MB | N/A |
| nextStartRea..uration (ms) | 428ms | 421ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/optimistic-bailout | Change |
| - | - | - | - |
| 199-HASH.js gzip | 29.2 kB | 28.8 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | N/A |
| 494.HASH.js gzip | 180 B | 181 B | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 239 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 46.9 kB | 46.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/optimistic-bailout | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/optimistic-bailout | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 506 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | ✓ |
| edge-ssr-HASH.js gzip | 253 B | 255 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.3 kB | 4.3 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.65 kB | 2.63 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 311 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.17 kB | 3.17 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/optimistic-bailout | Change |
| - | - | - | - |
| _buildManifest.js gzip | 486 B | 483 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/optimistic-bailout | Change |
| - | - | - | - |
| index.html gzip | 529 B | 527 B | N/A |
| link.html gzip | 541 B | 541 B | ✓ |
| withRouter.html gzip | 524 B | 523 B | N/A |
| Overall change | 541 B | 541 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/optimistic-bailout | Change |
| - | - | - | - |
| edge-ssr.js gzip | 92.6 kB | 92.6 kB | N/A |
| page.js gzip | 145 kB | 145 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/optimistic-bailout | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 626 B | 626 B | ✓ |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 24.8 kB | 24.8 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.55 kB | 2.55 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/optimistic-bailout | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 167 kB | 167 kB | ✓ |
| app-page-exp..prod.js gzip | 93.2 kB | 93.2 kB | ✓ |
| app-page-tur..prod.js gzip | 93.9 kB | 93.9 kB | ✓ |
| app-page-tur..prod.js gzip | 88.5 kB | 88.5 kB | ✓ |
| app-page.run...dev.js gzip | 137 kB | 137 kB | ✓ |
| app-page.run..prod.js gzip | 87.9 kB | 87.9 kB | ✓ |
| app-route-ex...dev.js gzip | 23.8 kB | 23.8 kB | ✓ |
| app-route-ex..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route-tu..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route-tu..prod.js gzip | 16 kB | 16 kB | ✓ |
| app-route.ru...dev.js gzip | 23.2 kB | 23.2 kB | ✓ |
| app-route.ru..prod.js gzip | 16 kB | 16 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.8 kB | 21.8 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.8 kB | 21.8 kB | ✓ |
| server.runti..prod.js gzip | 49 kB | 49 kB | ✓ |
| Overall change | 923 kB | 923 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [644],
   {
-    /***/ 1794: /***/ function (
+    /***/ 8959: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/link",
         function () {
-          return __webpack_require__(1921);
+          return __webpack_require__(9877);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 172: /***/ function (module, exports) {
+    /***/ 91: /***/ function (module, exports) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -100,7 +100,7 @@
       /***/
     },
 
-    /***/ 4847: /***/ function (module, exports, __webpack_require__) {
+    /***/ 2976: /***/ function (module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -112,7 +112,7 @@
           return getDomainLocale;
         },
       });
-      const _normalizetrailingslash = __webpack_require__(2003);
+      const _normalizetrailingslash = __webpack_require__(9076);
       const basePath =
         /* unused pure expression or super */ null && (false || "");
       function getDomainLocale(path, locale, locales, domainLocales) {
@@ -136,7 +136,7 @@
       /***/
     },
 
-    /***/ 7414: /***/ function (module, exports, __webpack_require__) {
+    /***/ 106: /***/ function (module, exports, __webpack_require__) {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -152,17 +152,17 @@
       const _react = /*#__PURE__*/ _interop_require_default._(
         __webpack_require__(959)
       );
-      const _resolvehref = __webpack_require__(279);
-      const _islocalurl = __webpack_require__(7377);
-      const _formaturl = __webpack_require__(9616);
-      const _utils = __webpack_require__(3869);
-      const _addlocale = __webpack_require__(5752);
-      const _routercontextsharedruntime = __webpack_require__(1840);
-      const _approutercontextsharedruntime = __webpack_require__(3057);
-      const _useintersection = __webpack_require__(9285);
-      const _getdomainlocale = __webpack_require__(4847);
-      const _addbasepath = __webpack_require__(5853);
-      const _routerreducertypes = __webpack_require__(172);
+      const _resolvehref = __webpack_require__(8873);
+      const _islocalurl = __webpack_require__(1023);
+      const _formaturl = __webpack_require__(3482);
+      const _utils = __webpack_require__(4597);
+      const _addlocale = __webpack_require__(6845);
+      const _routercontextsharedruntime = __webpack_require__(1049);
+      const _approutercontextsharedruntime = __webpack_require__(4095);
+      const _useintersection = __webpack_require__(4991);
+      const _getdomainlocale = __webpack_require__(2976);
+      const _addbasepath = __webpack_require__(7677);
+      const _routerreducertypes = __webpack_require__(91);
       const prefetched = new Set();
       function prefetch(router, href, as, options, appOptions, isAppRouter) {
         if (false) {
@@ -221,8 +221,7 @@
         shallow,
         scroll,
         locale,
-        isAppRouter,
-        prefetchEnabled
+        isAppRouter
       ) {
         const { nodeName } = e.currentTarget;
         // anchors inside an svg have a lowercase nodeName
@@ -247,7 +246,6 @@
             });
           } else {
             router[replace ? "replace" : "push"](as || href, {
-              forceOptimisticNavigation: !prefetchEnabled,
               scroll: routerScroll,
             });
           }
@@ -443,8 +441,7 @@
                 shallow,
                 scroll,
                 locale,
-                isAppRouter,
-                prefetchEnabled
+                isAppRouter
               );
             },
             onMouseEnter(e) {
@@ -581,7 +578,7 @@
       /***/
     },
 
-    /***/ 9285: /***/ function (module, exports, __webpack_require__) {
+    /***/ 4991: /***/ function (module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -594,7 +591,7 @@
         },
       });
       const _react = __webpack_require__(959);
-      const _requestidlecallback = __webpack_require__(5781);
+      const _requestidlecallback = __webpack_require__(3136);
       const hasIntersectionObserver =
         typeof IntersectionObserver === "function";
       const observers = new Map();
@@ -707,7 +704,7 @@
       /***/
     },
 
-    /***/ 1921: /***/ function (
+    /***/ 9877: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -723,7 +720,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(1527);
       /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(3639);
+        __webpack_require__(2075);
       /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_link__WEBPACK_IMPORTED_MODULE_1__
@@ -754,12 +751,12 @@
       /***/
     },
 
-    /***/ 3639: /***/ function (
+    /***/ 2075: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(7414);
+      module.exports = __webpack_require__(106);
 
       /***/
     },
@@ -770,7 +767,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function () {
-      return __webpack_exec__(1794);
+      return __webpack_exec__(8959);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>199-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 324609462797f0fad6b591c621895bbd0062463f

File: packages/next/src/client/components/router-reducer/fill-cache-with-data-property.ts [hunk 6]
```diff
@@ -11,9 +11,8 @@ export function fillCacheWithDataProperty(
   newCache: CacheNode,
   existingCache: CacheNode,
   flightSegmentPath: FlightSegmentPath,
-  fetchResponse: () => Promise<FetchServerResponseResult>,
-  bailOnParallelRoutes: boolean = false
-): { bailOptimistic: boolean } | undefined {
+  fetchResponse: () => Promise<FetchServerResponseResult>
+) {
```
Comment (timneutkens) [inline packages/next/src/client/components/router-reducer/fill-cache-with-data-property.ts:15]: Missing return type, I'm guessing it's now `void`?

```suggestion
): void {
```

**Review by timneutkens — APPROVED** [review]

File: packages/next/src/shared/lib/app-router-context.shared-runtime.ts [hunk 7]
```diff
@@ -69,7 +69,6 @@ export type CacheNode =
 
 export interface NavigateOptions {
   /** @internal */
```
Comment (amannn) [inline packages/next/src/shared/lib/app-router-context.shared-runtime.ts:71]: I think this should have been removed too, I've opened a PR here: https://github.com/vercel/next.js/pull/59001
