### PR TITLE
Turbopack: switch from base40 to base38 hash encoding (remove ~ and . from charset)

### LINKED ISSUE #91678: Turbopack 16.2.0 generates filenames with reserved characters (~~, ...) breaking Enterprise WAF/Nginx rules
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/eager-shirley-333t5w

### To Reproduce

1. Use Next.js version `16.2.0`.
2. Run a production build using Turbopack: `next build`.
3. Deploy the application behind an Nginx server or a WAF (Web Application Firewall) with standard security hardening rules (e.g., `block_common_exploits.conf`).
4. Attempt to load the application.
5. The browser console shows **403 Forbidden** errors for static CSS and JS chunks.

### Current vs. Expected behavior

**Comparison of generated filenames:**

| Version | Filename Example | Naming Strategy | Status |
| :--- | :--- | :--- | :--- |
| **16.1.7** | `turbopack-01ca012029ca2e66.js` | Clean Hexadecimal | **PASS** |
| **16.2.0** | `turbopack-0c3o1svijj_~~.js` | **Reserved (`~~`)** | **FAIL (403)** |
| **16.2.0** | `0...f7~att2_2.js` | **Reserved (`...` and `~`)** | **FAIL (403)** |
| **16.2.0** | `0q~2copru0zy0.css` | **Reserved (`~`)** | **FAIL (403)** |

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 24284
  Available CPU cores: 12
Binaries:
  Node: 24.14.0
  npm: 11.9.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 16.2.0
  eslint-config-next: 16.2.0
  react: 19.2.4
  react-dom: 19.2.4
  typescript: 5.9.3
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sokra**
### What?

Fixes a regression from https://github.com/vercel/next.js/pull/91137

Switch Turbopack's hash encoding charset from base40 (`0-9 a-z _ - ~ .`) to base38 (`0-9 a-z _ -`), removing the `~` and `.` characters. Pure rename/charset change — no structural changes.

### Why?

The `~` and `.` characters in base40-encoded filenames are blocked by standard Nginx hardening rules (`block_common_exploits.conf`) and enterprise WAF configurations, causing **403 Forbidden errors** when applications are deployed behind security-hardened infrastructure.

Examples of problematic filenames:
- `turbopack-0c3o1svijj_~~.js` — `~~` flagged as directory traversal / injection
- `0...f7~att2_2.js` — `...` flagged as path traversal attempt  
- `0q~2copru0zy0.css` — `~` filtered by some WAF rulesets

Previous hex-only filenames (e.g. `turbopack-01ca012029ca2e66.js`) had no such issues.

Fixes https://github.com/vercel/next.js/issues/91678

### How?

**Charset change** (`turbo-tasks-hash/src/base38.rs`, renamed from `base40.rs`):
- Alphabet reduced from 40 to 38 characters: `0123456789abcdefghijklmnopqrstuvwxyz_-`
- All constants and functions renamed: `BASE40_*` → `BASE38_*`, `encode_base40` → `encode_base38`
- Hash lengths unchanged: 13 chars for 64-bit, 25 chars for 128-bit (`38^13 > 2^64`, `38^25 > 2^128`)
- Content hash length stays at 13 (68.2 bits vs 69.2 bits with base40 — negligible)

**`HashAlgorithm` enum variants** (`turbo-tasks-hash/src/lib.rs`):
- `Xxh3Hash64Base40` → `Xxh3Hash64Base38`
- `Xxh3Hash128Base40` → `Xxh3Hash128Base38`

**Bit computation comment** (`turbopack-core/src/ident.rs`):
- Updated `7 base38 chars ≈ 37 bits` → `≈ 36 bits` (log2(38) × 7 = 36.7)

**Test regex patterns** (15 test files):
- Updated `[0-9a-z_.~-]` → `[0-9a-z_-]` to match the new charset

### CODE REVIEW

File: turbopack/crates/turbo-tasks-hash/src/base38.rs [hunk 1]
```diff
@@ -1,10 +1,10 @@
-/// URL-safe, filesystem-safe alphabet for hash encoding: `0-9 a-z _ - ~ .`
+/// URL-safe, filesystem-safe alphabet for hash encoding: `0-9 a-z _ -`
 ///
-/// All 40 characters are RFC 3986 unreserved characters and are safe on
+/// All 38 characters are RFC 3986 unreserved characters and are safe on
 /// case-insensitive filesystems (macOS HFS+/APFS, Windows NTFS).
```
Comment (styfle) [inline turbopack/crates/turbo-tasks-hash/src/base38.rs:4]: Maybe this comment should mention why we can't include `~` or `.` since those are no longer about the filesystem.

Comment (sokra) [reply turbopack/crates/turbo-tasks-hash/src/base38.rs:4]: :robot: Good point — added a note explaining that `~` and `.` are excluded because they trigger false-positive path traversal/injection blocks in common Nginx hardening rules (`block_common_exploits.conf`) and enterprise WAF configurations, generating 403 errors on sequences like `~~` or `...` in asset filenames.

File: turbopack/crates/turbo-tasks-hash/src/base38.rs [hunk 2]
```diff
@@ -32,38 +37,38 @@ const fn digits_for_bits(base: u128, bits: u32) -> usize {
     n
 }
 
-/// Number of base40 characters needed to represent a 64-bit value without
+/// Number of base38 characters needed to represent a 64-bit value without
 /// information loss.
-pub const BASE40_LEN_64: usize = digits_for_bits(BASE, 64);
+pub const BASE38_LEN_64: usize = digits_for_bits(BASE, 64);
```
Comment (styfle) [inline turbopack/crates/turbo-tasks-hash/src/base38.rs:42]: In my opinion we should just increase from 64bit (13 chars) to 84bit (16 chars).

That would be an increase of 252x meaning 751 billion IDs until a 1% chance of collision.

Then we could probably omit the 128bit manifest.

**Review by styfle — APPROVED** [review]

**Comment by lukesandberg** [comment]
so we avoid uppercase characters due to case insensitive file systems, but URLs are case sensitive, so using upper case character is fine we just don't want to produce two outputs that differ only by case.  This is essentially a hash collision... do we need to care about it?

**Review by lukesandberg — APPROVED** [review]
