### PR TITLE
fix: Include CSP nonce in next/dynamic preload

### LINKED ISSUE #81260: next/dynamic does not work on the client with strict CSP
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/bold-einstein-z6c9zh?workspaceId=ws_V7ijyD2eX436taCWyegNhc

### To Reproduce

1. Start the application in dev mode
2. Load the homepage
3. Open Chrome inspector console to see the CSP error

### Current vs. Expected behavior

When using `next/dynamic` in a client component with strict CSP (`nonce` and `strict-dynamic`), the injected preload `link` tag does not the generated `nonce`.

This cause the preloading to fail and shows the following error:
```
Refused to load the script 'https://qtft5c-3000.csb.app/_next/static/chunks/_app-pages-browser_app_dynamicComponent_dynamicComponent_tsx.js' because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-NGNlMWRhMmMtNjJmNi00NzJjLWJhODUtMmQzMjI1NjJlMTAy' 'strict-dynamic' https: http: 'unsafe-eval'". Note that 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

The expected behavior is that Next.js automatically adds the `nonce` on the preload `link` tag it generates.

Not sure if this file is causing the issue, but it's using `preload` from `react-dom` without providing the `nonce`:
https://github.com/vercel/next.js/blob/029a8199ce5f4877d4d272a5bd03cc5a13dab3e5/packages/next/src/shared/lib/lazy-dynamic/preload-chunks.tsx#L61-L64

In the case of `next/script`, we see that the `nonce` is set in the same function:
https://github.com/vercel/next.js/blob/b8d5f262429f6543e975fd11255297883dace1d6/packages/next/src/client/script.tsx#L339-L349

As a reference, here's a GitHub discussion about this issue:
https://github.com/vercel/next.js/discussions/75152

Hopefully this will be enough context to reproduce and solve it.
Thanks!

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.5.0: Tue Apr 22 19:54:49 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.13.1
  npm: 10.5.2
  Yarn: N/A
  pnpm: 9.15.9
Relevant Packages:
  next: 15.3.4 // Latest available version is detected (15.3.4).
  eslint-config-next: 15.3.4
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Lazy Loading

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed)

### Additional context

_No response_

<sub>[NEXT-4702](https://linear.app/vercel/issue/NEXT-4702/nextdynamic-does-not-work-on-the-client-with-strict-csp)</sub>

### PR DESCRIPTION
**Pull request by TrevorBurnham**
(This is a second attempt at fixing this bug. The first attempt was https://github.com/vercel/next.js/pull/81954.)

Calling react-dom's `preload` without the CSP's `nonce` causes Chrome to log an error and refuse to preload the script. This commit supplies the required nonce and adds e2e test coverage for this scenario.

The fix here is simply to pass the `nonce` into the `preload` function in `lazy-dynamic/preload-chunks.tsx`, as suggested in the issue description on #81260. The interesting part is obtaining the  `nonce`: My first attempt used

```tsx
const { nonce } = useContext(HeadManagerContext)
```

which didn't work. Here, the nonce is instead obtained from the WorkStore. All of the other changes here are plumbing to get the nonce into the WorkStore and back out.

**LLM disclosure:** Claude Sonnet 4 did the legwork here, but I've reviewed this code, iterated on it, and verified that the tests pass.

Fixes #81260

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 5413c25a4c35548204d1bab3e887bf23908e8418

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 7f620fde22fea0a540aa44cb4e3a4e4419a15f2d

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

File: test/e2e/app-dir/dynamic/app/csp-nonce/dynamic-component.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+'use client'
```
Comment (huozhi) [inline test/e2e/app-dir/dynamic/app/csp-nonce/dynamic-component.js]: Hi thanks for the PR, can you create a new e2e test case with `pnpm new-test` instead of reusing the existing test? As the csp solution is enabled for the whole app and we'd like to keep the existing fxitures simple and testing the basic cases

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 3edf6db2d88a4ddfcf943a8ae336750876f3e160 | [About building and testing Next.js](https://github.com/vercel/next.js/blob/canary/contributing.md)

`pnpm test-start-experimental test/e2e/app-dir/next-dynamic-csp-nonce/next-dynamic-csp-nonce.test.ts`(Experimental)
- next/dynamic with CSP nonce > should include nonce attribute on preload links generated by next/dynamic ([DD](https://app.datadoghq.com/ci/test/runs?query=%40git.repository.id%3A%22github.com%2Fvercel%2Fnext.js%22+%40git.commit.head_sha%3A%223edf6db2d88a4ddfcf943a8ae336750876f3e160%22+%40test.name%3A%22next%2Fdynamic+with+CSP+nonce+should+include+nonce+attribute+on+preload+links+generated+by+next%2Fdynamic%22+%40test.type%3A%22nextjs%22+%40test.status%3A%22fail%22))

<details>
<summary>Expand output</summary>

  ● next/dynamic with CSP nonce › should include nonce attribute on preload links generated by next/dynamic

    expect(received).toBe(expected) // Object.is equality

    Expected: "test-nonce"
    Received: undefined

      27 |       // Only check preload links for dynamic chunks
      28 |       if (href && href.includes('_next/static/chunks/')) {
    > 29 |         expect($element.attr('nonce')).toBe('test-nonce')
         |                                        ^
      30 |       }
      31 |     })
      32 |   })

      at Object.toBe (e2e/app-dir/next-dynamic-csp-nonce/next-dynamic-csp-nonce.test.ts:29:40)
      at initialize.Object.<anonymous>.exports.each (../node_modules/.pnpm/cheerio@0.22.0/node_modules/cheerio/lib/api/traversing.js:300:24)
      at Object.each (e2e/app-dir/next-dynamic-csp-nonce/next-dynamic-csp-nonce.test.ts:23:25)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | TrevorBurnham/next.js next-dynamic-preload-nonce-fix | Change |
| - | - | - | - |
| buildDuration | 18.9s | 18.8s | N/A |
| buildDurationCached | 15.1s | 12.3s | N/A |
| nodeModulesSize | 450 MB | 450 MB | N/A |
| nextStartRea..uration (ms) | 711ms | 712ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | TrevorBurnham/next.js next-dynamic-preload-nonce-fix | Change |
| - | - | - | - |
| 234bef07-HASH.js gzip | 54.3 kB | 54.3 kB | N/A |
| 3414-HASH.js gzip | 4.32 kB | N/A | N/A |
| 5194.HASH.js gzip | 169 B | 169 B | ✓ |
| 8863-HASH.js gzip | 5.32 kB | 5.27 kB | N/A |
| 9304-HASH.js gzip | 46.3 kB | 45.8 kB | N/A |
| framework-HASH.js gzip | 57.7 kB | 57.7 kB | N/A |
| main-app-HASH.js gzip | 254 B | 254 B | ✓ |
| main-HASH.js gzip | 37 kB | 36.8 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 423 B | 423 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | TrevorBurnham/next.js next-dynamic-preload-nonce-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | TrevorBurnham/next.js next-dynamic-preload-nonce-fix | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 193 B | N/A |
| _error-HASH.js gzip | 182 B | 182 B | ✓ |
| amp-HASH.js gzip | 502 B | 507 B | N/A |
| css-HASH.js gzip | 335 B | 333 B | N/A |
| dynamic-HASH.js gzip | 1.83 kB | 1.83 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 255 B | ✓ |
| head-HASH.js gzip | 350 B | 352 B | N/A |
| hooks-HASH.js gzip | 385 B | 383 B | N/A |
| image-HASH.js gzip | 581 B | 4.66 kB | ⚠️ +4.08 kB |
| index-HASH.js gzip | 257 B | 259 B | N/A |
| link-HASH.js gzip | 2.29 kB | 2.29 kB | N/A |
| routerDirect..HASH.js gzip | 320 B | 318 B | N/A |
| script-HASH.js gzip | 387 B | 386 B | N/A |
| withRouter-HASH.js gzip | 315 B | 313 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.12 kB | 5.2 kB | ⚠️ +4.08 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | TrevorBurnham/next.js next-dynamic-preload-nonce-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 770 B | 752 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | TrevorBurnham/next.js next-dynamic-preload-nonce-fix | Change |
| - | - | - | - |
| index.html gzip | 524 B | 523 B | N/A |
| link.html gzip | 539 B | 535 B | N/A |
| withRouter.html gzip | 521 B | 519 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | TrevorBurnham/next.js next-dynamic-preload-nonce-fix | Change |
| - | - | - | - |
| edge-ssr.js gzip | 121 kB | 121 kB | N/A |
| page.js gzip | 242 kB | 242 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | TrevorBurnham/next.js next-dynamic-preload-nonce-fix | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 689 B | 676 B | N/A |
| middleware-r..fest.js gzip | 156 B | 155 B | N/A |
| middleware.js gzip | 33 kB | 33.3 kB | ⚠️ +322 B |
| edge-runtime..pack.js gzip | 853 B | 853 B | ✓ |
| Overall change | 33.8 kB | 34.2 kB | ⚠️ +322 B |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | TrevorBurnham/next.js next-dynamic-preload-nonce-fix | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 285 kB | 285 kB | N/A |
| app-page-exp..prod.js gzip | 158 kB | 157 kB | N/A |
| app-page-tur...dev.js gzip | 285 kB | 285 kB | N/A |
| app-page-tur..prod.js gzip | 158 kB | 157 kB | N/A |
| app-page-tur...dev.js gzip | 273 kB | 273 kB | N/A |
| app-page-tur..prod.js gzip | 152 kB | 152 kB | N/A |
| app-page.run...dev.js gzip | 272 kB | 272 kB | N/A |
| app-page.run..prod.js gzip | 152 kB | 152 kB | N/A |
| app-route-ex...dev.js gzip | 70.4 kB | 70.3 kB | N/A |
| app-route-ex..prod.js gzip | 49.5 kB | 49.4 kB | N/A |
| app-route-tu...dev.js gzip | 70.4 kB | 70.3 kB | N/A |
| app-route-tu..prod.js gzip | 49.5 kB | 49.4 kB | N/A |
| app-route-tu...dev.js gzip | 69.8 kB | 69.7 kB | N/A |
| app-route-tu..prod.js gzip | 49.1 kB | 49.1 kB | N/A |
| app-route.ru...dev.js gzip | 69.7 kB | 69.7 kB | N/A |
| app-route.ru..prod.js gzip | 49.1 kB | 49.1 kB | N/A |
| dist_client_...dev.js gzip | 326 B | 326 B | ✓ |
| dist_client_...dev.js gzip | 328 B | 328 B | ✓ |
| dist_client_...dev.js gzip | 320 B | 320 B | ✓ |
| dist_client_...dev.js gzip | 318 B | 318 B | ✓ |
| pages-api-tu...dev.js gzip | 42.8 kB | 42.8 kB | ✓ |
| pages-api-tu..prod.js gzip | 32.9 kB | 32.9 kB | ✓ |
| pages-api.ru...dev.js gzip | 42.7 kB | 42.7 kB | ✓ |
| pages-api.ru..prod.js gzip | 32.9 kB | 32.9 kB | ✓ |
| pages-turbo....dev.js gzip | 53 kB | 53 kB | N/A |
| pages-turbo...prod.js gzip | 40.4 kB | 40.4 kB | N/A |
| pages.runtim...dev.js gzip | 53.1 kB | 53.1 kB | N/A |
| pages.runtim..prod.js gzip | 40.5 kB | 40.5 kB | N/A |
| server.runti..prod.js gzip | 76.5 kB | 76.4 kB | N/A |
| Overall change | 153 kB | 153 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | TrevorBurnham/next.js next-dynamic-preload-nonce-fix | Change |
| - | - | - | - |
| 0.pack gzip | 3.16 MB | 3.16 MB | N/A |
| index.pack gzip | 96.4 kB | 96.8 kB | ⚠️ +382 B |
| Overall change | 96.4 kB | 96.8 kB | ⚠️ +382 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware-b..-manifest.js</strong></summary>

```diff
@@ -4,98 +4,97 @@ globalThis.__BUILD_MANIFEST = {
   ampDevFiles: [],
   lowPriorityFiles: [],
   rootMainFiles: [
-    "static/chunks/webpack-9033d89fb26d0013.js",
-    "static/chunks/234bef07-637d112c291add38.js",
-    "static/chunks/9304-74c691fdd5aa648a.js",
-    "static/chunks/main-app-8eb1178d5434dc45.js",
+    "static/chunks/webpack-9ac9ccb761b5e915.js",
+    "static/chunks/066e8be7-2270bdfae20275fb.js",
+    "static/chunks/2426-5dcb9014812c543a.js",
+    "static/chunks/main-app-abbee9043bf11bec.js",
   ],
   rootMainFilesTree: {},
   pages: {
     "/": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
-      "static/chunks/pages/index-a7fb71e5f6213aa9.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
+      "static/chunks/pages/index-75ff7f75f4c9520b.js",
     ],
     "/_app": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
-      "static/chunks/pages/_app-4f1e07139b8bc0f4.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
+      "static/chunks/pages/_app-0e29c8719fa68d07.js",
     ],
     "/_error": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
-      "static/chunks/pages/_error-8f4e796cc66bb887.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
+      "static/chunks/pages/_error-21398e242bebd4bd.js",
     ],
     "/amp": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
-      "static/chunks/pages/amp-97249b00762d04b9.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
+      "static/chunks/pages/amp-96acbf1ec5bf4dbf.js",
     ],
     "/css": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
       "static/css/ded6b86ab9cc0a1f.css",
-      "static/chunks/pages/css-30fd1831d1c5954d.js",
+      "static/chunks/pages/css-f0abb8f1d5d6aafc.js",
     ],
     "/dynamic": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
-      "static/chunks/pages/dynamic-933632969493a23b.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
+      "static/chunks/pages/dynamic-a6de0bd7312dbe87.js",
     ],
     "/edge-ssr": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
-      "static/chunks/pages/edge-ssr-fbde6d2b170ddc8a.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
+      "static/chunks/pages/edge-ssr-8437b1c654938313.js",
     ],
     "/head": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
-      "static/chunks/pages/head-0fcabd05d9a7b019.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
+      "static/chunks/pages/head-957c9636cda350bb.js",
     ],
     "/hooks": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
-      "static/chunks/pages/hooks-52423902769dcda6.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
+      "static/chunks/pages/hooks-48956e83e76a0b7c.js",
     ],
     "/image": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
-      "static/chunks/3414-0fcfc359d1626bc2.js",
-      "static/chunks/pages/image-bcf65fa5afa25af3.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
+      "static/chunks/pages/image-87ef6d0382b99071.js",
     ],
     "/link": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
-      "static/chunks/pages/link-107187295a8a4aea.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
+      "static/chunks/pages/link-1312906a9876c4c3.js",
     ],
     "/routerDirect": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
-      "static/chunks/pages/routerDirect-1422147417dba74a.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
+      "static/chunks/pages/routerDirect-77c6ee7fa90e109b.js",
     ],
     "/script": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
-      "static/chunks/pages/script-a68c215ba4b2c288.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
+      "static/chunks/pages/script-32f0c3e4bc363d50.js",
     ],
     "/withRouter": [
-      "static/chunks/webpack-9033d89fb26d0013.js",
-      "static/chunks/framework-01cd9f2fab3511bf.js",
-      "static/chunks/main-4603c88410e00c3c.js",
-      "static/chunks/pages/withRouter-0af6fb4f6ceaec8e.js",
+      "static/chunks/webpack-9ac9ccb761b5e915.js",
+      "static/chunks/framework-1382d6eb4c03f4cb.js",
+      "static/chunks/main-b33b20fc3c76e3c6.js",
+      "static/chunks/pages/withRouter-0a50058d9954ea8e.js",
     ],
   },
   ampFirstPages: [],
```
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -611,36 +611,33 @@ self.__BUILD_MANIFEST = (function (a, b, c) {
       numHashes: NaN,
       bitArray: [],
     },
-    "/": ["static\u002Fchunks\u002Fpages\u002Findex-a7fb71e5f6213aa9.js"],
+    "/": ["static\u002Fchunks\u002Fpages\u002Findex-75ff7f75f4c9520b.js"],
     "/_error": [
-      "static\u002Fchunks\u002Fpages\u002F_error-8f4e796cc66bb887.js",
+      "static\u002Fchunks\u002Fpages\u002F_error-21398e242bebd4bd.js",
     ],
-    "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-97249b00762d04b9.js"],
+    "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-96acbf1ec5bf4dbf.js"],
     "/css": [
       "static\u002Fcss\u002Fded6b86ab9cc0a1f.css",
-      "static\u002Fchunks\u002Fpages\u002Fcss-30fd1831d1c5954d.js",
+      "static\u002Fchunks\u002Fpages\u002Fcss-f0abb8f1d5d6aafc.js",
     ],
     "/dynamic": [
-      "static\u002Fchunks\u002Fpages\u002Fdynamic-933632969493a23b.js",
+      "static\u002Fchunks\u002Fpages\u002Fdynamic-a6de0bd7312dbe87.js",
     ],
     "/edge-ssr": [
-      "static\u002Fchunks\u002Fpages\u002Fedge-ssr-fbde6d2b170ddc8a.js",
+      "static\u002Fchunks\u002Fpages\u002Fedge-ssr-8437b1c654938313.js",
     ],
-    "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-0fcabd05d9a7b019.js"],
-    "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-52423902769dcda6.js"],
-    "/image": [
-      "static\u002Fchunks\u002F3414-0fcfc359d1626bc2.js",
-      "static\u002Fchunks\u002Fpages\u002Fimage-bcf65fa5afa25af3.js",
-    ],
-    "/link": ["static\u002Fchunks\u002Fpages\u002Flink-107187295a8a4aea.js"],
+    "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-957c9636cda350bb.js"],
+    "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-48956e83e76a0b7c.js"],
+    "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-87ef6d0382b99071.js"],
+    "/link": ["static\u002Fchunks\u002Fpages\u002Flink-1312906a9876c4c3.js"],
     "/routerDirect": [
-      "static\u002Fchunks\u002Fpages\u002FrouterDirect-1422147417dba74a.js",
+      "static\u002Fchunks\u002Fpages\u002FrouterDirect-77c6ee7fa90e109b.js",
     ],
     "/script": [
-      "static\u002Fchunks\u002Fpages\u002Fscript-a68c215ba4b2c288.js",
+      "static\u002Fchunks\u002Fpages\u002Fscript-32f0c3e4bc363d50.js",
     ],
     "/withRouter": [
-      "static\u002Fchunks\u002Fpages\u002FwithRouter-0af6fb4f6ceaec8e.js",
+      "static\u002Fchunks\u002Fpages\u002FwithRouter-0a50058d9954ea8e.js",
     ],
     sortedPages: [
       "\u002F",
```
</details>
<details>
<summary>Diff for <strong>amp-HASH.js</strong></summary>

```diff
@@ -1,17 +1,65 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [5034],
   {
-    /***/ 4105: /***/ (
+    /***/ 6212: /***/ (
+      __unused_webpack_module,
+      __webpack_exports__,
+      __webpack_require__
+    ) => {
+      "use strict";
+      __webpack_require__.r(__webpack_exports__);
+      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
+        /* harmony export */ config: () => /* binding */ config,
+        /* harmony export */ default: () => /* binding */ Amp,
+        /* harmony export */
+      });
+      /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0__ =
+        __webpack_require__(7023);
+      /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0___default =
+        /*#__PURE__*/ __webpack_require__.n(
+          next_amp__WEBPACK_IMPORTED_MODULE_0__
+        );
+
+      const config = {
+        amp: "hybrid",
+      };
+      function Amp(props) {
+        return (0, next_amp__WEBPACK_IMPORTED_MODULE_0__.useAmp)()
+          ? "AMP mode"
+          : "normal mode";
+      }
+
+      /***/
+    },
+
+    /***/ 7023: /***/ (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) => {
-      module.exports = __webpack_require__(4642);
+      module.exports = __webpack_require__(9926);
+
+      /***/
+    },
+
+    /***/ 8647: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/amp",
+        function () {
+          return __webpack_require__(6212);
+        },
+      ]);
+      if (false) {
+      }
 
       /***/
     },
 
-    /***/ 4642: /***/ (module, exports, __webpack_require__) => {
+    /***/ 9926: /***/ (module, exports, __webpack_require__) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -27,8 +75,8 @@
       const _react = /*#__PURE__*/ _interop_require_default._(
         __webpack_require__(5977)
       );
-      const _ampcontextsharedruntime = __webpack_require__(8358);
-      const _ampmode = __webpack_require__(242);
+      const _ampcontextsharedruntime = __webpack_require__(5418);
+      const _ampmode = __webpack_require__(3494);
       function useAmp() {
         // Don't assign the context value to a variable to save bytes
         return (0, _ampmode.isInAmpMode)(
@@ -49,61 +97,13 @@
 
       /***/
     },
-
-    /***/ 5261: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/amp",
-        function () {
-          return __webpack_require__(9550);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 9550: /***/ (
-      __unused_webpack_module,
-      __webpack_exports__,
-      __webpack_require__
-    ) => {
-      "use strict";
-      __webpack_require__.r(__webpack_exports__);
-      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
-        /* harmony export */ config: () => /* binding */ config,
-        /* harmony export */ default: () => /* binding */ Amp,
-        /* harmony export */
-      });
-      /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(4105);
-      /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0___default =
-        /*#__PURE__*/ __webpack_require__.n(
-          next_amp__WEBPACK_IMPORTED_MODULE_0__
-        );
-
-      const config = {
-        amp: "hybrid",
-      };
-      function Amp(props) {
-        return (0, next_amp__WEBPACK_IMPORTED_MODULE_0__.useAmp)()
-          ? "AMP mode"
-          : "normal mode";
-      }
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(5261)
+      __webpack_exec__(8647)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>css-HASH.js</strong></summary>

```diff
@@ -1,7 +1,14 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [9813],
   {
-    /***/ 5267: /***/ (
+    /***/ 1978: /***/ (module) => {
+      // extracted by mini-css-extract-plugin
+      module.exports = { helloWorld: "css_helloWorld__aUdUq" };
+
+      /***/
+    },
+
+    /***/ 6941: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -15,7 +22,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(7765);
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(6320);
+        __webpack_require__(1978);
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           _css_module_css__WEBPACK_IMPORTED_MODULE_1__
@@ -35,14 +42,7 @@
       /***/
     },
 
-    /***/ 6320: /***/ (module) => {
-      // extracted by mini-css-extract-plugin
-      module.exports = { helloWorld: "css_helloWorld__aUdUq" };
-
-      /***/
-    },
-
-    /***/ 9643: /***/ (
+    /***/ 8685: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -50,7 +50,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/css",
         function () {
-          return __webpack_require__(5267);
+          return __webpack_require__(6941);
         },
       ]);
       if (false) {
@@ -64,7 +64,7 @@
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(9643)
+      __webpack_exec__(8685)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -1,17 +1,63 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [2291],
   {
-    /***/ 2406: /***/ (
-      module,
-      __unused_webpack_exports,
+    /***/ 2839: /***/ (
+      __unused_webpack_module,
+      __webpack_exports__,
       __webpack_require__
     ) => {
-      module.exports = __webpack_require__(8949);
+      "use strict";
+      __webpack_require__.r(__webpack_exports__);
+      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
+        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
+        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
+        /* harmony export */
+      });
+      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
+        __webpack_require__(7765);
+      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ =
+        __webpack_require__(7444);
+      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default =
+        /*#__PURE__*/ __webpack_require__.n(
+          next_dynamic__WEBPACK_IMPORTED_MODULE_1__
+        );
+
+      const DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
+        () =>
+          __webpack_require__
+            .e(/* import() */ 1376)
+            .then(__webpack_require__.bind(__webpack_require__, 1376))
+            .then((mod) => mod.Hello),
+        {
+          loadableGenerated: {
+            webpack: () => [/*require.resolve*/ 1376],
+          },
+        }
+      );
+      const Page = () =>
+        /*#__PURE__*/ (0, react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)(
+          react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.Fragment,
+          {
+            children: [
+              /*#__PURE__*/ (0,
+              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("p", {
+                children: "testing next/dynamic size",
+              }),
+              /*#__PURE__*/ (0,
+              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
+                DynamicHello,
+                {}
+              ),
+            ],
+          }
+        );
+      var __N_SSP = true;
+      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = Page;
 
       /***/
     },
 
-    /***/ 4466: /***/ (
+    /***/ 4478: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -53,7 +99,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       const _react = /*#__PURE__*/ _interop_require_default._(
         __webpack_require__(5977)
       );
-      const _loadablecontextsharedruntime = __webpack_require__(8452);
+      const _loadablecontextsharedruntime = __webpack_require__(5792);
       function resolve(obj) {
         return obj && obj.default ? obj.default : obj;
       }
@@ -288,63 +334,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       /***/
     },
 
-    /***/ 4545: /***/ (
-      __unused_webpack_module,
-      __webpack_exports__,
-      __webpack_require__
-    ) => {
-      "use strict";
-      __webpack_require__.r(__webpack_exports__);
-      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
-        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
-        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
-        /* harmony export */
-      });
-      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(7765);
-      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(2406);
-      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default =
-        /*#__PURE__*/ __webpack_require__.n(
-          next_dynamic__WEBPACK_IMPORTED_MODULE_1__
-        );
-
-      const DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
-        () =>
-          __webpack_require__
-            .e(/* import() */ 5194)
-            .then(__webpack_require__.bind(__webpack_require__, 5194))
-            .then((mod) => mod.Hello),
-        {
-          loadableGenerated: {
-            webpack: () => [/*require.resolve*/ 5194],
-          },
-        }
-      );
-      const Page = () =>
-        /*#__PURE__*/ (0, react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)(
-          react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.Fragment,
-          {
-            children: [
-              /*#__PURE__*/ (0,
-              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("p", {
-                children: "testing next/dynamic size",
-              }),
-              /*#__PURE__*/ (0,
-              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
-                DynamicHello,
-                {}
-              ),
-            ],
-          }
-        );
-      var __N_SSP = true;
-      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = Page;
-
-      /***/
-    },
-
-    /***/ 8452: /***/ (
+    /***/ 5792: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -371,24 +361,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       /***/
     },
 
-    /***/ 8931: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/dynamic",
-        function () {
-          return __webpack_require__(4545);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 8949: /***/ (module, exports, __webpack_require__) => {
+    /***/ 6153: /***/ (module, exports, __webpack_require__) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -421,7 +394,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
         __webpack_require__(5977)
       );
       const _loadablesharedruntime = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(4466)
+        __webpack_require__(4478)
       );
       const isServerSide = "object" === "undefined";
       // Normalize loader to return the module as form { default: Component } for `React.lazy`.
@@ -521,13 +494,40 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
 
       /***/
     },
+
+    /***/ 7444: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(6153);
+
+      /***/
+    },
+
+    /***/ 9805: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/dynamic",
+        function () {
+          return __webpack_require__(2839);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(8931)
+      __webpack_exec__(9805)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>edge-ssr-HASH.js</strong></summary>

```diff
@@ -1,24 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [676],
   {
-    /***/ 4717: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/edge-ssr",
-        function () {
-          return __webpack_require__(7776);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 7776: /***/ (
+    /***/ 170: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -37,13 +20,30 @@
 
       /***/
     },
+
+    /***/ 8079: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/edge-ssr",
+        function () {
+          return __webpack_require__(170);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(4717)
+      __webpack_exec__(8079)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>head-HASH.js</strong></summary>

```diff
@@ -1,34 +1,17 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [5350],
   {
-    /***/ 943: /***/ (
+    /***/ 1177: /***/ (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) => {
-      module.exports = __webpack_require__(2554);
+      module.exports = __webpack_require__(8366);
 
       /***/
     },
 
-    /***/ 3829: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/head",
-        function () {
-          return __webpack_require__(4662);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 4662: /***/ (
+    /***/ 1992: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -43,7 +26,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(7765);
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(943);
+        __webpack_require__(1177);
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_head__WEBPACK_IMPORTED_MODULE_1__
@@ -76,13 +59,30 @@
 
       /***/
     },
+
+    /***/ 8751: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/head",
+        function () {
+          return __webpack_require__(1992);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(3829)
+      __webpack_exec__(8751)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>hooks-HASH.js</strong></summary>

```diff
@@ -1,7 +1,24 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [9804],
   {
-    /***/ 2452: /***/ (
+    /***/ 2227: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/hooks",
+        function () {
+          return __webpack_require__(2770);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 2770: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -59,30 +76,13 @@
 
       /***/
     },
-
-    /***/ 6105: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/hooks",
-        function () {
-          return __webpack_require__(2452);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(6105)
+      __webpack_exec__(2227)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -1,143 +1,63 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [4672],
   {
-    /***/ 1585: /***/ (module, exports, __webpack_require__) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "useIntersection", {
-        enumerable: true,
-        get: function () {
-          return useIntersection;
-        },
-      });
-      const _react = __webpack_require__(5977);
-      const _requestidlecallback = __webpack_require__(356);
-      const hasIntersectionObserver =
-        typeof IntersectionObserver === "function";
-      const observers = new Map();
-      const idList = [];
-      function createObserver(options) {
-        const id = {
-          root: options.root || null,
-          margin: options.rootMargin || "",
-        };
-        const existing = idList.find(
-          (obj) => obj.root === id.root && obj.margin === id.margin
-        );
-        let instance;
-        if (existing) {
-          instance = observers.get(existing);
-          if (instance) {
-            return instance;
-          }
-        }
-        const elements = new Map();
-        const observer = new IntersectionObserver((entries) => {
-          entries.forEach((entry) => {
-            const callback = elements.get(entry.target);
-            const isVisible =
-              entry.isIntersecting || entry.intersectionRatio > 0;
-            if (callback && isVisible) {
-              callback(isVisible);
-            }
-          });
-        }, options);
-        instance = {
-          id,
-          observer,
-          elements,
-        };
-        idList.push(id);
-        observers.set(id, instance);
-        return instance;
-      }
-      function observe(element, callback, options) {
-        const { id, observer, elements } = createObserver(options);
-        elements.set(element, callback);
-        observer.observe(element);
-        return function unobserve() {
-          elements.delete(element);
-          observer.unobserve(element);
-          // Destroy observer when there's nothing left to watch:
-          if (elements.size === 0) {
-            observer.disconnect();
-            observers.delete(id);
-            const index = idList.findIndex(
-              (obj) => obj.root === id.root && obj.margin === id.margin
-            );
-            if (index > -1) {
-              idList.splice(index, 1);
-            }
-          }
-        };
-      }
-      function useIntersection(param) {
-        let { rootRef, rootMargin, disabled } = param;
-        const isDisabled = disabled || !hasIntersectionObserver;
-        const [visible, setVisible] = (0, _react.useState)(false);
-        const elementRef = (0, _react.useRef)(null);
-        const setElement = (0, _react.useCallback)((element) => {
-          elementRef.current = element;
-        }, []);
-        (0, _react.useEffect)(() => {
-          if (hasIntersectionObserver) {
-            if (isDisabled || visible) return;
-            const element = elementRef.current;
-            if (element && element.tagName) {
-              const unobserve = observe(
-                element,
-                (isVisible) => isVisible && setVisible(isVisible),
-                {
-                  root: rootRef == null ? void 0 : rootRef.current,
-                  rootMargin,
-                }
-              );
-              return unobserve;
-            }
-          } else {
-            if (!visible) {
-              const idleCallback = (0,
-              _requestidlecallback.requestIdleCallback)(() => setVisible(true));
-              return () =>
-                (0, _requestidlecallback.cancelIdleCallback)(idleCallback);
-            }
-          }
-          // eslint-disable-next-line react-hooks/exhaustive-deps
-        }, [isDisabled, rootMargin, rootRef, visible, elementRef.current]);
-        const resetVisible = (0, _react.useCallback)(() => {
-          setVisible(false);
-        }, []);
-        return [setElement, visible, resetVisible];
-      }
-      if (
-        (typeof exports.default === "function" ||
-          (typeof exports.default === "object" && exports.default !== null)) &&
-        typeof exports.default.__esModule === "undefined"
-      ) {
-        Object.defineProperty(exports.default, "__esModule", {
-          value: true,
-        });
-        Object.assign(exports.default, exports);
-        module.exports = exports.default;
-      } //# sourceMappingURL=use-intersection.js.map
+    /***/ 2783: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(5926);
 
       /***/
     },
 
-    /***/ 2621: /***/ (
-      module,
-      __unused_webpack_exports,
+    /***/ 4174: /***/ (
+      __unused_webpack_module,
+      __webpack_exports__,
       __webpack_require__
     ) => {
-      module.exports = __webpack_require__(5410);
+      "use strict";
+      __webpack_require__.r(__webpack_exports__);
+      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
+        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
+        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
+        /* harmony export */
+      });
+      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
+        __webpack_require__(7765);
+      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ =
+        __webpack_require__(2783);
+      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default =
+        /*#__PURE__*/ __webpack_require__.n(
+          next_link__WEBPACK_IMPORTED_MODULE_1__
+        );
+
+      function aLink(props) {
+        return /*#__PURE__*/ (0,
+        react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)("div", {
+          children: [
+            /*#__PURE__*/ (0,
+            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("h3", {
+              children: "A Link page!",
+            }),
+            /*#__PURE__*/ (0,
+            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
+              next_link__WEBPACK_IMPORTED_MODULE_1___default(),
+              {
+                href: "/",
+                children: "Go to /",
+              }
+            ),
+          ],
+        });
+      }
+      var __N_SSP = true;
+      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = aLink;
 
       /***/
     },
 
-    /***/ 5410: /***/ (module, exports, __webpack_require__) => {
+    /***/ 5926: /***/ (module, exports, __webpack_require__) => {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -164,16 +84,16 @@
       const _react = /*#__PURE__*/ _interop_require_wildcard._(
         __webpack_require__(5977)
       );
-      const _resolvehref = __webpack_require__(224);
-      const _islocalurl = __webpack_require__(7746);
-      const _formaturl = __webpack_require__(315);
-      const _utils = __webpack_require__(8709);
-      const _addlocale = __webpack_require__(6358);
-      const _routercontextsharedruntime = __webpack_require__(4095);
-      const _useintersection = __webpack_require__(1585);
-      const _getdomainlocale = __webpack_require__(8802);
-      const _addbasepath = __webpack_require__(6151);
-      const _usemergedref = __webpack_require__(9100);
+      const _resolvehref = __webpack_require__(6708);
+      const _islocalurl = __webpack_require__(6526);
+      const _formaturl = __webpack_require__(5575);
+      const _utils = __webpack_require__(3497);
+      const _addlocale = __webpack_require__(722);
+      const _routercontextsharedruntime = __webpack_require__(1235);
+      const _useintersection = __webpack_require__(8069);
+      const _getdomainlocale = __webpack_require__(9734);
+      const _addbasepath = __webpack_require__(4419);
+      const _usemergedref = __webpack_require__(6136);
       const prefetched = new Set();
       function prefetch(router, href, as, options) {
         if (false) {
@@ -495,43 +415,7 @@
       /***/
     },
 
-    /***/ 8802: /***/ (module, exports, __webpack_require__) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "getDomainLocale", {
-        enumerable: true,
-        get: function () {
-          return getDomainLocale;
-        },
-      });
-      const _normalizetrailingslash = __webpack_require__(1652);
-      const basePath =
-        /* unused pure expression or super */ null && (false || "");
-      function getDomainLocale(path, locale, locales, domainLocales) {
-        if (false) {
-        } else {
-          return false;
-        }
-      }
-      if (
-        (typeof exports.default === "function" ||
-          (typeof exports.default === "object" && exports.default !== null)) &&
-        typeof exports.default.__esModule === "undefined"
-      ) {
-        Object.defineProperty(exports.default, "__esModule", {
-          value: true,
-        });
-        Object.assign(exports.default, exports);
-        module.exports = exports.default;
-      } //# sourceMappingURL=get-domain-locale.js.map
-
-      /***/
-    },
-
-    /***/ 9100: /***/ (module, exports, __webpack_require__) => {
+    /***/ 6136: /***/ (module, exports, __webpack_require__) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -609,7 +493,7 @@
       /***/
     },
 
-    /***/ 9693: /***/ (
+    /***/ 7047: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -617,7 +501,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/link",
         function () {
-          return __webpack_require__(9948);
+          return __webpack_require__(4174);
         },
       ]);
       if (false) {
@@ -626,48 +510,164 @@
       /***/
     },
 
-    /***/ 9948: /***/ (
-      __unused_webpack_module,
-      __webpack_exports__,
-      __webpack_require__
-    ) => {
+    /***/ 8069: /***/ (module, exports, __webpack_require__) => {
       "use strict";
-      __webpack_require__.r(__webpack_exports__);
-      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
-        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
-        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
-        /* harmony export */
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
       });
-      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(7765);
-      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(2621);
-      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default =
-        /*#__PURE__*/ __webpack_require__.n(
-          next_link__WEBPACK_IMPORTED_MODULE_1__
+      Object.defineProperty(exports, "useIntersection", {
+        enumerable: true,
+        get: function () {
+          return useIntersection;
+        },
+      });
+      const _react = __webpack_require__(5977);
+      const _requestidlecallback = __webpack_require__(3432);
+      const hasIntersectionObserver =
+        typeof IntersectionObserver === "function";
+      const observers = new Map();
+      const idList = [];
+      function createObserver(options) {
+        const id = {
+          root: options.root || null,
+          margin: options.rootMargin || "",
+        };
+        const existing = idList.find(
+          (obj) => obj.root === id.root && obj.margin === id.margin
         );
-
-      function aLink(props) {
-        return /*#__PURE__*/ (0,
-        react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)("div", {
-          children: [
-            /*#__PURE__*/ (0,
-            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("h3", {
-              children: "A Link page!",
-            }),
-            /*#__PURE__*/ (0,
-            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
-              next_link__WEBPACK_IMPORTED_MODULE_1___default(),
-              {
-                href: "/",
-                children: "Go to /",
-              }
-            ),
-          ],
+        let instance;
+        if (existing) {
+          instance = observers.get(existing);
+          if (instance) {
+            return instance;
+          }
+        }
+        const elements = new Map();
+        const observer = new IntersectionObserver((entries) => {
+          entries.forEach((entry) => {
+            const callback = elements.get(entry.target);
+            const isVisible =
+              entry.isIntersecting || entry.intersectionRatio > 0;
+            if (callback && isVisible) {
+              callback(isVisible);
+            }
+          });
+        }, options);
+        instance = {
+          id,
+          observer,
+          elements,
+        };
+        idList.push(id);
+        observers.set(id, instance);
+        return instance;
+      }
+      function observe(element, callback, options) {
+        const { id, observer, elements } = createObserver(options);
+        elements.set(element, callback);
+        observer.observe(element);
+        return function unobserve() {
+          elements.delete(element);
+          observer.unobserve(element);
+          // Destroy observer when there's nothing left to watch:
+          if (elements.size === 0) {
+            observer.disconnect();
+            observers.delete(id);
+            const index = idList.findIndex(
+              (obj) => obj.root === id.root && obj.margin === id.margin
+            );
+            if (index > -1) {
+              idList.splice(index, 1);
+            }
+          }
+        };
+      }
+      function useIntersection(param) {
+        let { rootRef, rootMargin, disabled } = param;
+        const isDisabled = disabled || !hasIntersectionObserver;
+        const [visible, setVisible] = (0, _react.useState)(false);
+        const elementRef = (0, _react.useRef)(null);
+        const setElement = (0, _react.useCallback)((element) => {
+          elementRef.current = element;
+        }, []);
+        (0, _react.useEffect)(() => {
+          if (hasIntersectionObserver) {
+            if (isDisabled || visible) return;
+            const element = elementRef.current;
+            if (element && element.tagName) {
+              const unobserve = observe(
+                element,
+                (isVisible) => isVisible && setVisible(isVisible),
+                {
+                  root: rootRef == null ? void 0 : rootRef.current,
+                  rootMargin,
+                }
+              );
+              return unobserve;
+            }
+          } else {
+            if (!visible) {
+              const idleCallback = (0,
+              _requestidlecallback.requestIdleCallback)(() => setVisible(true));
+              return () =>
+                (0, _requestidlecallback.cancelIdleCallback)(idleCallback);
+            }
+          }
+          // eslint-disable-next-line react-hooks/exhaustive-deps
+        }, [isDisabled, rootMargin, rootRef, visible, elementRef.current]);
+        const resetVisible = (0, _react.useCallback)(() => {
+          setVisible(false);
+        }, []);
+        return [setElement, visible, resetVisible];
+      }
+      if (
+        (typeof exports.default === "function" ||
+          (typeof exports.default === "object" && exports.default !== null)) &&
+        typeof exports.default.__esModule === "undefined"
+      ) {
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true,
         });
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
+      } //# sourceMappingURL=use-intersection.js.map
+
+      /***/
+    },
+
+    /***/ 9734: /***/ (module, exports, __webpack_require__) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "getDomainLocale", {
+        enumerable: true,
+        get: function () {
+          return getDomainLocale;
+        },
+      });
+      const _normalizetrailingslash = __webpack_require__(504);
+      const basePath =
+        /* unused pure expression or super */ null && (false || "");
+      function getDomainLocale(path, locale, locales, domainLocales) {
+        if (false) {
+        } else {
+          return false;
+        }
       }
-      var __N_SSP = true;
-      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = aLink;
+      if (
+        (typeof exports.default === "function" ||
+          (typeof exports.default === "object" && exports.default !== null)) &&
+        typeof exports.default.__esModule === "undefined"
+      ) {
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true,
+        });
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
+      } //# sourceMappingURL=get-domain-locale.js.map
 
       /***/
     },
@@ -677,7 +677,7 @@
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(9693)
+      __webpack_exec__(7047)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>script-HASH.js</strong></summary>

```diff
@@ -1,7 +1,34 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [1209],
   {
-    /***/ 3699: /***/ (
+    /***/ 1008: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(2817);
+
+      /***/
+    },
+
+    /***/ 6951: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/script",
+        function () {
+          return __webpack_require__(8889);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 8889: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -16,7 +43,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(7765);
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(4802);
+        __webpack_require__(1008);
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_script__WEBPACK_IMPORTED_MODULE_1__
@@ -48,40 +75,13 @@
 
       /***/
     },
-
-    /***/ 4802: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(8661);
-
-      /***/
-    },
-
-    /***/ 7861: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/script",
-        function () {
-          return __webpack_require__(3699);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(7861)
+      __webpack_exec__(6951)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>234bef07-HASH.js</strong></summary>

```diff
@@ -1,13 +1,13 @@
 "use strict";
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
-  [5862],
+  [3008],
   {
-    /***/ 5357: /***/ (
+    /***/ 4580: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
     ) => {
-      /* provided dependency */ var process = __webpack_require__(1549);
+      /* provided dependency */ var process = __webpack_require__(8475);
       /**
        * @license React
        * react-dom-client.production.js
@@ -22,9 +22,9 @@
  Modernizr 3.0.0pre (Custom Build) | MIT
 */
 
-      var Scheduler = __webpack_require__(5046),
-        React = __webpack_require__(2786),
-        ReactDOM = __webpack_require__(1407);
+      var Scheduler = __webpack_require__(8532),
+        React = __webpack_require__(2224),
+        ReactDOM = __webpack_require__(1345);
       function formatProdErrorMessage(code) {
         var url = "https://react.dev/errors/" + code;
         if (1 < arguments.length) {
@@ -564,8 +564,7 @@
         x >>>= 0;
         return 0 === x ? 32 : (31 - ((log(x) / LN2) | 0)) | 0;
       }
-      var nextTransitionUpdateLane = 256,
-        nextTransitionDeferredLane = 262144,
+      var nextTransitionLane = 256,
         nextRetryLane = 4194304;
       function getHighestPriorityLanes(lanes) {
         var pendingSyncLanes = lanes & 42;
@@ -597,12 +596,11 @@
           case 32768:
           case 65536:
           case 131072:
-            return lanes & 261888;
           case 262144:
           case 524288:
           case 1048576:
           case 2097152:
-            return lanes & 3932160;
+            return lanes & 4194048;
           case 4194304:
           case 8388608:
           case 16777216:
@@ -712,6 +710,12 @@
             return -1;
         }
       }
+      function claimNextTransitionLane() {
+        var lane = nextTransitionLane;
+        nextTransitionLane <<= 1;
+        0 === (nextTransitionLane & 4194048) && (nextTransitionLane = 256);
+        return lane;
+      }
       function claimNextRetryLane() {
         var lane = nextRetryLane;
         nextRetryLane <<= 1;
@@ -785,7 +789,7 @@
         root.entanglements[spawnedLaneIndex] =
           root.entanglements[spawnedLaneIndex] |
           1073741824 |
-          (entangledLanes & 261930);
+          (entangledLanes & 4194090);
       }
       function markRootEntangled(root, entangledLanes) {
         var rootEntangledLanes = (root.entangledLanes |= entangledLanes);
@@ -2111,19 +2115,19 @@
       }
       var isInputEventSupported = !1;
       if (canUseDOM) {
-        var JSCompiler_inline_result$jscomp$285;
+        var JSCompiler_inline_result$jscomp$284;
         if (canUseDOM) {
-          var isSupported$jscomp$inline_428 = "oninput" in document;
-          if (!isSupported$jscomp$inline_428) {
-            var element$jscomp$inline_429 = document.createElement("div");
-            element$jscomp$inline_429.setAttribute("oninput", "return;");
-            isSupported$jscomp$inline_428 =
-              "function" === typeof element$jscomp$inline_429.oninput;
+          var isSupported$jscomp$inline_427 = "oninput" in document;
+          if (!isSupported$jscomp$inline_427) {
+            var element$jscomp$inline_428 = document.createElement("div");
+            element$jscomp$inline_428.setAttribute("oninput", "return;");
+            isSupported$jscomp$inline_427 =
+              "function" === typeof element$jscomp$inline_428.oninput;
           }
-          JSCompiler_inline_result$jscomp$285 = isSupported$jscomp$inline_428;
-        } else JSCompiler_inline_result$jscomp$285 = !1;
+          JSCompiler_inline_result$jscomp$284 = isSupported$jscomp$inline_427;
+        } else JSCompiler_inline_result$jscomp$284 = !1;
         isInputEventSupported =
-          JSCompiler_inline_result$jscomp$285 &&
+          JSCompiler_inline_result$jscomp$284 &&
           (!document.documentMode || 9 < document.documentMode);
       }
       function stopWatchingForValueChange() {
@@ -5392,11 +5396,7 @@
         return prevState;
       }
       function mountDeferredValueImpl(hook, value, initialValue) {
-        if (
-          void 0 === initialValue ||
-          (0 !== (renderLanes & 1073741824) &&
-            0 === (workInProgressRootRenderLanes & 261930))
-        )
+        if (void 0 === initialValue || 0 !== (renderLanes & 1073741824))
           return (hook.memoizedState = value);
         hook.memoizedState = initialValue;
         hook = requestDeferredLane();
@@ -5412,11 +5412,7 @@
             objectIs(hook, prevValue) || (didReceiveUpdate = !0),
             hook
           );
-        if (
-          0 === (renderLanes & 42) ||
-          (0 !== (renderLanes & 1073741824) &&
-            0 === (workInProgressRootRenderLanes & 261930))
-        )
+        if (0 === (renderLanes & 42) || 0 !== (renderLanes & 1073741824))
           return (didReceiveUpdate = !0), (hook.memoizedState = value);
         hook = requestDeferredLane();
         currentlyRenderingFiber.lanes |= hook;
@@ -11203,19 +11199,13 @@
           : resolveUpdatePriority();
       }
       function requestDeferredLane() {
-        if (0 === workInProgressDeferredLane)
-          if (
-            0 === (workInProgressRootRenderLanes & 536870912) ||
-            isHydrating
-          ) {
-            var lane = nextTransitionDeferredLane;
-            nextTransitionDeferredLane <<= 1;
-            0 === (nextTransitionDeferredLane & 3932160) &&
-              (nextTransitionDeferredLane = 262144);
-            workInProgressDeferredLane = lane;
-          } else workInProgressDeferredLane = 536870912;
-        lane = suspenseHandlerStackCursor.current;
-        null !== lane && (lane.flags |= 32);
+        0 === workInProgressDeferredLane &&
+          (workInProgressDeferredLane =
+            0 === (workInProgressRootRenderLanes & 536870912) || isHydrating
+              ? claimNextTransitionLane()
+              : 536870912);
+        var suspenseHandler = suspenseHandlerStackCursor.current;
+        null !== suspenseHandler && (suspenseHandler.flags |= 32);
         return workInProgressDeferredLane;
       }
       function scheduleUpdateOnFiber(root, fiber, lane) {
@@ -12330,7 +12320,7 @@
           0 !== (pendingEffectsLanes & 3) && flushPendingEffects();
           ensureRootIsScheduled(root);
           remainingLanes = root.pendingLanes;
-          0 !== (lanes & 261930) && 0 !== (remainingLanes & 42)
+          0 !== (lanes & 4194090) && 0 !== (remainingLanes & 42)
             ? root === rootWithNestedUpdates
               ? nestedUpdateCount++
               : ((nestedUpdateCount = 0), (rootWithNestedUpdates = root))
@@ -12746,12 +12736,8 @@
       function requestTransitionLane() {
         if (0 === currentEventTransitionLane) {
           var actionScopeLane = currentEntangledLane;
-          0 === actionScopeLane &&
-            ((actionScopeLane = nextTransitionUpdateLane),
-            (nextTransitionUpdateLane <<= 1),
-            0 === (nextTransitionUpdateLane & 261888) &&
-              (nextTransitionUpdateLane = 256));
-          currentEventTransitionLane = actionScopeLane;
+          currentEventTransitionLane =
+            0 !== actionScopeLane ? actionScopeLane : claimNextTransitionLane();
         }
         return currentEventTransitionLane;
       }
@@ -12858,20 +12844,20 @@
         }
       }
       for (
-        var i$jscomp$inline_1578 = 0;
-        i$jscomp$inline_1578 < simpleEventPluginEvents.length;
-        i$jscomp$inline_1578++
+        var i$jscomp$inline_1573 = 0;
+        i$jscomp$inline_1573 < simpleEventPluginEvents.length;
+        i$jscomp$inline_1573++
       ) {
-        var eventName$jscomp$inline_1579 =
-            simpleEventPluginEvents[i$jscomp$inline_1578],
-          domEventName$jscomp$inline_1580 =
-            eventName$jscomp$inline_1579.toLowerCase(),
-          capitalizedEvent$jscomp$inline_1581 =
-            eventName$jscomp$inline_1579[0].toUpperCase() +
-            eventName$jscomp$inline_1579.slice(1);
+        var eventName$jscomp$inline_1574 =
+            simpleEventPluginEvents[i$jscomp$inline_1573],
+          domEventName$jscomp$inline_1575 =
+            eventName$jscomp$inline_1574.toLowerCase(),
+          capitalizedEvent$jscomp$inline_1576 =
+            eventName$jscomp$inline_1574[0].toUpperCase() +
+            eventName$jscomp$inline_1574.slice(1);
         registerSimpleEvent(
-          domEventName$jscomp$inline_1580,
-          "on" + capitalizedEvent$jscomp$inline_1581
+          domEventName$jscomp$inline_1575,
+          "on" + capitalizedEvent$jscomp$inline_1576
         );
       }
       registerSimpleEvent(ANIMATION_END, "onAnimationEnd");
@@ -16744,16 +16730,16 @@
           0 === i && attemptExplicitHydrationTarget(target);
         }
       };
-      var isomorphicReactPackageVersion$jscomp$inline_1838 = React.version;
+      var isomorphicReactPackageVersion$jscomp$inline_1833 = React.version;
       if (
-        "19.2.0-canary-3302d1f7-20250903" !==
-        isomorphicReactPackageVersion$jscomp$inline_1838
+        "19.2.0-canary-bb6f0c8d-20250901" !==
+        isomorphicReactPackageVersion$jscomp$inline_1833
       )
         throw Error(
           formatProdErrorMessage(
             527,
-            isomorphicReactPackageVersion$jscomp$inline_1838,
-            "19.2.0-canary-3302d1f7-20250903"
+            isomorphicReactPackageVersion$jscomp$inline_1833,
+            "19.2.0-canary-bb6f0c8d-20250901"
           )
         );
       ReactDOMSharedInternals.findDOMNode = function (componentOrElement) {
@@ -16773,24 +16759,24 @@
           null === componentOrElement ? null : componentOrElement.stateNode;
         return componentOrElement;
       };
-      var internals$jscomp$inline_2341 = {
+      var internals$jscomp$inline_2336 = {
         bundleType: 0,
-        version: "19.2.0-canary-3302d1f7-20250903",
+        version: "19.2.0-canary-bb6f0c8d-20250901",
         rendererPackageName: "react-dom",
         currentDispatcherRef: ReactSharedInternals,
-        reconcilerVersion: "19.2.0-canary-3302d1f7-20250903",
+        reconcilerVersion: "19.2.0-canary-bb6f0c8d-20250901",
       };
       if ("undefined" !== typeof __REACT_DEVTOOLS_GLOBAL_HOOK__) {
-        var hook$jscomp$inline_2342 = __REACT_DEVTOOLS_GLOBAL_HOOK__;
+        var hook$jscomp$inline_2337 = __REACT_DEVTOOLS_GLOBAL_HOOK__;
         if (
-          !hook$jscomp$inline_2342.isDisabled &&
-          hook$jscomp$inline_2342.supportsFiber
+          !hook$jscomp$inline_2337.isDisabled &&
+          hook$jscomp$inline_2337.supportsFiber
         )
           try {
-            (rendererID = hook$jscomp$inline_2342.inject(
-              internals$jscomp$inline_2341
+            (rendererID = hook$jscomp$inline_2337.inject(
+              internals$jscomp$inline_2336
             )),
-              (injectedHook = hook$jscomp$inline_2342);
+              (injectedHook = hook$jscomp$inline_2337);
           } catch (err) {}
       }
       exports.createRoot = function (container, options) {
@@ -16880,7 +16866,7 @@
         listenToAllSupportedEvents(container);
         return new ReactDOMHydrationRoot(initialChildren);
       };
-      exports.version = "19.2.0-canary-3302d1f7-20250903";
+      exports.version = "19.2.0-canary-bb6f0c8d-20250901";
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>3414-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>8863-HASH.js</strong></summary>

```diff
@@ -1,8 +1,33 @@
 "use strict";
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
-  [8863],
+  [7009],
   {
-    /***/ 22: /***/ (module, exports, __webpack_require__) => {
+    /***/ 414: /***/ (
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) => {
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "AmpStateContext", {
+        enumerable: true,
+        get: function () {
+          return AmpStateContext;
+        },
+      });
+      const _interop_require_default = __webpack_require__(2726);
+      const _react = /*#__PURE__*/ _interop_require_default._(
+        __webpack_require__(2224)
+      );
+      const AmpStateContext = _react.default.createContext({});
+      if (false) {
+      } //# sourceMappingURL=amp-context.shared-runtime.js.map
+
+      /***/
+    },
+
+    /***/ 1912: /***/ (module, exports, __webpack_require__) => {
       Object.defineProperty(exports, "__esModule", {
         value: true,
       });
@@ -12,7 +37,7 @@
           return useMergedRef;
         },
       });
-      const _react = __webpack_require__(2786);
+      const _react = __webpack_require__(2224);
       function useMergedRef(refA, refB) {
         const cleanupA = (0, _react.useRef)(null);
         const cleanupB = (0, _react.useRef)(null);
@@ -78,87 +103,99 @@
       /***/
     },
 
-    /***/ 639: /***/ (__unused_webpack_module, exports) => {
+    /***/ 2843: /***/ (
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) => {
       Object.defineProperty(exports, "__esModule", {
         value: true,
       });
-      Object.defineProperty(exports, "findClosestQuality", {
+      Object.defineProperty(exports, "RouterContext", {
         enumerable: true,
         get: function () {
-          return findClosestQuality;
+          return RouterContext;
         },
       });
-      function findClosestQuality(quality, config) {
+      const _interop_require_default = __webpack_require__(2726);
+      const _react = /*#__PURE__*/ _interop_require_default._(
+        __webpack_require__(2224)
+      );
+      const RouterContext = _react.default.createContext(null);
+      if (false) {
+      } //# sourceMappingURL=router-context.shared-runtime.js.map
+
+      /***/
+    },
+
+    /***/ 3003: /***/ (__unused_webpack_module, exports) => {
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "default", {
+        enumerable: true,
+        get: function () {
+          return _default;
+        },
+      });
+      const DEFAULT_Q = 75;
+      function defaultLoader(param) {
+        let { config, src, width, quality } = param;
         var _config_qualities;
-        const q = quality || 75;
-        if (
-          !(config == null
-            ? void 0
-            : (_config_qualities = config.qualities) == null
-            ? void 0
-            : _config_qualities.length)
-        ) {
-          return q;
+        if (false) {
         }
-        return config.qualities.reduce(
-          (prev, cur) => (Math.abs(cur - q) < Math.abs(prev - q) ? cur : prev),
-          0
+        const q =
+          quality ||
+          ((_config_qualities = config.qualities) == null
+            ? void 0
+            : _config_qualities.reduce((prev, cur) =>
+                Math.abs(cur - DEFAULT_Q) < Math.abs(prev - DEFAULT_Q)
+                  ? cur
+                  : prev
+              )) ||
+          DEFAULT_Q;
+        return (
+          config.path +
+          "?url=" +
+          encodeURIComponent(src) +
+          "&w=" +
+          width +
+          "&q=" +
+          q +
+          (src.startsWith("/_next/static/media/") && false ? 0 : "")
         );
-      } //# sourceMappingURL=find-closest-quality.js.map
+      }
+      // We use this to determine if the import is the default loader
+      // or a custom loader defined by the user in next.config.js
+      defaultLoader.__next_img_default = true;
+      const _default = defaultLoader; //# sourceMappingURL=image-loader.js.map
 
       /***/
     },
 
-    /***/ 936: /***/ (__unused_webpack_module, exports) => {
+    /***/ 3810: /***/ (__unused_webpack_module, exports) => {
       Object.defineProperty(exports, "__esModule", {
         value: true,
       });
-      0 && 0;
-      function _export(target, all) {
-        for (var name in all)
-          Object.defineProperty(target, name, {
-            enumerable: true,
-            get: all[name],
-          });
-      }
-      _export(exports, {
-        VALID_LOADERS: function () {
-          return VALID_LOADERS;
-        },
-        imageConfigDefault: function () {
-          return imageConfigDefault;
+      Object.defineProperty(exports, "isInAmpMode", {
+        enumerable: true,
+        get: function () {
+          return isInAmpMode;
         },
       });
-      const VALID_LOADERS = [
-        "default",
-        "imgix",
-        "cloudinary",
-        "akamai",
-        "custom",
-      ];
-      const imageConfigDefault = {
-        deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
-        imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
-        path: "/_next/image",
-        loader: "default",
-        loaderFile: "",
-        domains: [],
-        disableStaticImages: false,
-        minimumCacheTTL: 60,
-        formats: ["image/webp"],
-        dangerouslyAllowSVG: false,
-        contentSecurityPolicy: "script-src 'none'; frame-src 'none'; sandbox;",
-        contentDispositionType: "attachment",
-        localPatterns: undefined,
-        remotePatterns: [],
-        qualities: [75],
-        unoptimized: false,
-      }; //# sourceMappingURL=image-config.js.map
+      function isInAmpMode(param) {
+        let {
+          ampFirst = false,
+          hybrid = false,
+          hasQuery = false,
+        } = param === void 0 ? {} : param;
+        return ampFirst || (hybrid && hasQuery);
+      } //# sourceMappingURL=amp-mode.js.map
 
       /***/
     },
 
-    /***/ 1268: /***/ (__unused_webpack_module, exports) => {
+    /***/ 5218: /***/ (__unused_webpack_module, exports) => {
       /**
        * A shared function, used on both client and server, to generate a SVG blur placeholder.
        */
@@ -212,7 +249,7 @@
       /***/
     },
 
-    /***/ 1796: /***/ (module, exports, __webpack_require__) => {
+    /***/ 5402: /***/ (module, exports, __webpack_require__) => {
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
         value: true,
@@ -233,19 +270,19 @@
           return defaultHead;
         },
       });
-      const _interop_require_default = __webpack_require__(8182);
-      const _interop_require_wildcard = __webpack_require__(8319);
-      const _jsxruntime = __webpack_require__(1050);
+      const _interop_require_default = __webpack_require__(2726);
+      const _interop_require_wildcard = __webpack_require__(2527);
+      const _jsxruntime = __webpack_require__(8204);
       const _react = /*#__PURE__*/ _interop_require_wildcard._(
-        __webpack_require__(2786)
+        __webpack_require__(2224)
       );
       const _sideeffect = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(5581)
+        __webpack_require__(9319)
       );
-      const _ampcontextsharedruntime = __webpack_require__(3800);
-      const _headmanagercontextsharedruntime = __webpack_require__(4950);
-      const _ampmode = __webpack_require__(7824);
-      const _warnonce = __webpack_require__(2854);
+      const _ampcontextsharedruntime = __webpack_require__(414);
+      const _headmanagercontextsharedruntime = __webpack_require__(3100);
+      const _ampmode = __webpack_require__(3810);
+      const _warnonce = __webpack_require__(4504);
       function defaultHead(inAmpMode) {
         if (inAmpMode === void 0) inAmpMode = false;
         const head = [
@@ -410,7 +447,7 @@
       /***/
     },
 
-    /***/ 2843: /***/ (
+    /***/ 6745: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -424,9 +461,9 @@
           return getImgProps;
         },
       });
-      const _warnonce = __webpack_require__(2854);
-      const _imageblursvg = __webpack_require__(1268);
-      const _imageconfig = __webpack_require__(936);
+      const _warnonce = __webpack_require__(4504);
+      const _imageblursvg = __webpack_require__(5218);
+      const _imageconfig = __webpack_require__(9278);
       const VALID_LOADING_VALUES =
         /* unused pure expression or super */ null && [
           "lazy",
@@ -563,7 +600,6 @@
           sizes,
           unoptimized = false,
           priority = false,
-          preload = false,
           loading,
           className,
           quality,
@@ -738,9 +774,7 @@
         }
         src = typeof src === "string" ? src : staticSrc;
         let isLazy =
-          !priority &&
-          !preload &&
-          (loading === "lazy" || typeof loading === "undefined");
+          !priority && (loading === "lazy" || typeof loading === "undefined");
         if (!src || src.startsWith("data:") || src.startsWith("blob:")) {
           // https://developer.mozilla.org/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
           unoptimized = true;
@@ -824,12 +858,11 @@
           sizes,
           loader,
         });
-        const loadingFinal = isLazy ? "lazy" : loading;
         if (false) {
         }
         const props = {
           ...rest,
-          loading: loadingFinal,
+          loading: isLazy ? "lazy" : loading,
           fetchPriority,
           width: widthInt,
           height: heightInt,
@@ -845,7 +878,7 @@
         };
         const meta = {
           unoptimized,
-          preload: preload || priority,
+          priority,
           placeholder,
           fill,
         };
@@ -858,239 +891,7 @@
       /***/
     },
 
-    /***/ 3800: /***/ (
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) => {
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "AmpStateContext", {
-        enumerable: true,
-        get: function () {
-          return AmpStateContext;
-        },
-      });
-      const _interop_require_default = __webpack_require__(8182);
-      const _react = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(2786)
-      );
-      const AmpStateContext = _react.default.createContext({});
-      if (false) {
-      } //# sourceMappingURL=amp-context.shared-runtime.js.map
-
-      /***/
-    },
-
-    /***/ 5581: /***/ (
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) => {
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "default", {
-        enumerable: true,
-        get: function () {
-          return SideEffect;
-        },
-      });
-      const _react = __webpack_require__(2786);
-      const isServer = "object" === "undefined";
-      const useClientOnlyLayoutEffect = isServer
-        ? () => {}
-        : _react.useLayoutEffect;
-      const useClientOnlyEffect = isServer ? () => {} : _react.useEffect;
-      function SideEffect(props) {
-        const { headManager, reduceComponentsToState } = props;
-        function emitChange() {
-          if (headManager && headManager.mountedInstances) {
-            const headElements = _react.Children.toArray(
-              Array.from(headManager.mountedInstances).filter(Boolean)
-            );
-            headManager.updateHead(
-              reduceComponentsToState(headElements, props)
-            );
-          }
-        }
-        if (isServer) {
-          var _headManager_mountedInstances;
-          headManager == null
-            ? void 0
-            : (_headManager_mountedInstances = headManager.mountedInstances) ==
-              null
-            ? void 0
-            : _headManager_mountedInstances.add(props.children);
-          emitChange();
-        }
-        useClientOnlyLayoutEffect(() => {
-          var _headManager_mountedInstances;
-          headManager == null
-            ? void 0
-            : (_headManager_mountedInstances = headManager.mountedInstances) ==
-              null
-            ? void 0
-            : _headManager_mountedInstances.add(props.children);
-          return () => {
-            var _headManager_mountedInstances;
-            headManager == null
-              ? void 0
-              : (_headManager_mountedInstances =
-                  headManager.mountedInstances) == null
-              ? void 0
-              : _headManager_mountedInstances.delete(props.children);
-          };
-        });
-        // We need to call `updateHead` method whenever the `SideEffect` is trigger in all
-        // life-cycles: mount, update, unmount. However, if there are multiple `SideEffect`s
-        // being rendered, we only trigger the method from the last one.
-        // This is ensured by keeping the last unflushed `updateHead` in the `_pendingUpdate`
-        // singleton in the layout effect pass, and actually trigger it in the effect pass.
-        useClientOnlyLayoutEffect(() => {
-          if (headManager) {
-            headManager._pendingUpdate = emitChange;
-          }
-          return () => {
-            if (headManager) {
-              headManager._pendingUpdate = emitChange;
-            }
-          };
-        });
-        useClientOnlyEffect(() => {
-          if (headManager && headManager._pendingUpdate) {
-            headManager._pendingUpdate();
-            headManager._pendingUpdate = null;
-          }
-          return () => {
-            if (headManager && headManager._pendingUpdate) {
-              headManager._pendingUpdate();
-              headManager._pendingUpdate = null;
-            }
-          };
-        });
-        return null;
-      } //# sourceMappingURL=side-effect.js.map
-
-      /***/
-    },
-
-    /***/ 7053: /***/ (
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) => {
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "RouterContext", {
-        enumerable: true,
-        get: function () {
-          return RouterContext;
-        },
-      });
-      const _interop_require_default = __webpack_require__(8182);
-      const _react = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(2786)
-      );
-      const RouterContext = _react.default.createContext(null);
-      if (false) {
-      } //# sourceMappingURL=router-context.shared-runtime.js.map
-
-      /***/
-    },
-
-    /***/ 7281: /***/ (
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) => {
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "default", {
-        enumerable: true,
-        get: function () {
-          return _default;
-        },
-      });
-      const _findclosestquality = __webpack_require__(639);
-      function defaultLoader(param) {
-        let { config, src, width, quality } = param;
-        if (false) {
-        }
-        const q = (0, _findclosestquality.findClosestQuality)(quality, config);
-        return (
-          config.path +
-          "?url=" +
-          encodeURIComponent(src) +
-          "&w=" +
-          width +
-          "&q=" +
-          q +
-          (src.startsWith("/_next/static/media/") && false ? 0 : "")
-        );
-      }
-      // We use this to determine if the import is the default loader
-      // or a custom loader defined by the user in next.config.js
-      defaultLoader.__next_img_default = true;
-      const _default = defaultLoader; //# sourceMappingURL=image-loader.js.map
-
-      /***/
-    },
-
-    /***/ 7480: /***/ (
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) => {
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "ImageConfigContext", {
-        enumerable: true,
-        get: function () {
-          return ImageConfigContext;
-        },
-      });
-      const _interop_require_default = __webpack_require__(8182);
-      const _react = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(2786)
-      );
-      const _imageconfig = __webpack_require__(936);
-      const ImageConfigContext = _react.default.createContext(
-        _imageconfig.imageConfigDefault
-      );
-      if (false) {
-      } //# sourceMappingURL=image-config-context.shared-runtime.js.map
-
-      /***/
-    },
-
-    /***/ 7824: /***/ (__unused_webpack_module, exports) => {
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "isInAmpMode", {
-        enumerable: true,
-        get: function () {
-          return isInAmpMode;
-        },
-      });
-      function isInAmpMode(param) {
-        let {
-          ampFirst = false,
-          hybrid = false,
-          hasQuery = false,
-        } = param === void 0 ? {} : param;
-        return ampFirst || (hybrid && hasQuery);
-      } //# sourceMappingURL=amp-mode.js.map
-
-      /***/
-    },
-
-    /***/ 8863: /***/ (module, exports, __webpack_require__) => {
+    /***/ 7009: /***/ (module, exports, __webpack_require__) => {
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
         value: true,
@@ -1101,32 +902,31 @@
           return Image;
         },
       });
-      const _interop_require_default = __webpack_require__(8182);
-      const _interop_require_wildcard = __webpack_require__(8319);
-      const _jsxruntime = __webpack_require__(1050);
+      const _interop_require_default = __webpack_require__(2726);
+      const _interop_require_wildcard = __webpack_require__(2527);
+      const _jsxruntime = __webpack_require__(8204);
       const _react = /*#__PURE__*/ _interop_require_wildcard._(
-        __webpack_require__(2786)
+        __webpack_require__(2224)
       );
       const _reactdom = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(1407)
+        __webpack_require__(1345)
       );
       const _head = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(1796)
+        __webpack_require__(5402)
       );
-      const _getimgprops = __webpack_require__(2843);
-      const _imageconfig = __webpack_require__(936);
-      const _imageconfigcontextsharedruntime = __webpack_require__(7480);
-      const _warnonce = __webpack_require__(2854);
-      const _routercontextsharedruntime = __webpack_require__(7053);
+      const _getimgprops = __webpack_require__(6745);
+      const _imageconfig = __webpack_require__(9278);
+      const _imageconfigcontextsharedruntime = __webpack_require__(9690);
+      const _warnonce = __webpack_require__(4504);
+      const _routercontextsharedruntime = __webpack_require__(2843);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(7281)
+        __webpack_require__(3003)
       );
-      const _usemergedref = __webpack_require__(22);
+      const _usemergedref = __webpack_require__(1912);
       // This is replaced by webpack define plugin
       const configEnv = {
         deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
         imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
-        qualities: [75],
         path: "/_next/image",
         loader: "default",
         dangerouslyAllowSVG: false,
@@ -1423,7 +1223,7 @@
                 sizesInput: props.sizes,
                 ref: forwardedRef,
               }),
-              imgMeta.preload
+              imgMeta.priority
                 ? /*#__PURE__*/ (0, _jsxruntime.jsx)(ImagePreload, {
                     isAppRouter: isAppRouter,
                     imgAttributes: imgAttributes,
@@ -1447,5 +1247,175 @@
 
       /***/
     },
+
+    /***/ 9278: /***/ (__unused_webpack_module, exports) => {
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      0 && 0;
+      function _export(target, all) {
+        for (var name in all)
+          Object.defineProperty(target, name, {
+            enumerable: true,
+            get: all[name],
+          });
+      }
+      _export(exports, {
+        VALID_LOADERS: function () {
+          return VALID_LOADERS;
+        },
+        imageConfigDefault: function () {
+          return imageConfigDefault;
+        },
+      });
+      const VALID_LOADERS = [
+        "default",
+        "imgix",
+        "cloudinary",
+        "akamai",
+        "custom",
+      ];
+      const imageConfigDefault = {
+        deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
+        imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
+        path: "/_next/image",
+        loader: "default",
+        loaderFile: "",
+        domains: [],
+        disableStaticImages: false,
+        minimumCacheTTL: 60,
+        formats: ["image/webp"],
+        dangerouslyAllowSVG: false,
+        contentSecurityPolicy: "script-src 'none'; frame-src 'none'; sandbox;",
+        contentDispositionType: "attachment",
+        localPatterns: undefined,
+        remotePatterns: [],
+        qualities: undefined,
+        unoptimized: false,
+      }; //# sourceMappingURL=image-config.js.map
+
+      /***/
+    },
+
+    /***/ 9319: /***/ (
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) => {
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "default", {
+        enumerable: true,
+        get: function () {
+          return SideEffect;
+        },
+      });
+      const _react = __webpack_require__(2224);
+      const isServer = "object" === "undefined";
+      const useClientOnlyLayoutEffect = isServer
+        ? () => {}
+        : _react.useLayoutEffect;
+      const useClientOnlyEffect = isServer ? () => {} : _react.useEffect;
+      function SideEffect(props) {
+        const { headManager, reduceComponentsToState } = props;
+        function emitChange() {
+          if (headManager && headManager.mountedInstances) {
+            const headElements = _react.Children.toArray(
+              Array.from(headManager.mountedInstances).filter(Boolean)
+            );
+            headManager.updateHead(
+              reduceComponentsToState(headElements, props)
+            );
+          }
+        }
+        if (isServer) {
+          var _headManager_mountedInstances;
+          headManager == null
+            ? void 0
+            : (_headManager_mountedInstances = headManager.mountedInstances) ==
+              null
+            ? void 0
+            : _headManager_mountedInstances.add(props.children);
+          emitChange();
+        }
+        useClientOnlyLayoutEffect(() => {
+          var _headManager_mountedInstances;
+          headManager == null
+            ? void 0
+            : (_headManager_mountedInstances = headManager.mountedInstances) ==
+              null
+            ? void 0
+            : _headManager_mountedInstances.add(props.children);
+          return () => {
+            var _headManager_mountedInstances;
+            headManager == null
+              ? void 0
+              : (_headManager_mountedInstances =
+                  headManager.mountedInstances) == null
+              ? void 0
+              : _headManager_mountedInstances.delete(props.children);
+          };
+        });
+        // We need to call `updateHead` method whenever the `SideEffect` is trigger in all
+        // life-cycles: mount, update, unmount. However, if there are multiple `SideEffect`s
+        // being rendered, we only trigger the method from the last one.
+        // This is ensured by keeping the last unflushed `updateHead` in the `_pendingUpdate`
+        // singleton in the layout effect pass, and actually trigger it in the effect pass.
+        useClientOnlyLayoutEffect(() => {
+          if (headManager) {
+            headManager._pendingUpdate = emitChange;
+          }
+          return () => {
+            if (headManager) {
+              headManager._pendingUpdate = emitChange;
+            }
+          };
+        });
+        useClientOnlyEffect(() => {
+          if (headManager && headManager._pendingUpdate) {
+            headManager._pendingUpdate();
+            headManager._pendingUpdate = null;
+          }
+          return () => {
+            if (headManager && headManager._pendingUpdate) {
+              headManager._pendingUpdate();
+              headManager._pendingUpdate = null;
+            }
+          };
+        });
+        return null;
+      } //# sourceMappingURL=side-effect.js.map
+
+      /***/
+    },
+
+    /***/ 9690: /***/ (
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) => {
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "ImageConfigContext", {
+        enumerable: true,
+        get: function () {
+          return ImageConfigContext;
+        },
+      });
+      const _interop_require_default = __webpack_require__(2726);
+      const _react = /*#__PURE__*/ _interop_require_default._(
+        __webpack_require__(2224)
+      );
+      const _imageconfig = __webpack_require__(9278);
+      const ImageConfigContext = _react.default.createContext(
+        _imageconfig.imageConfigDefault
+      );
+      if (false) {
+      } //# sourceMappingURL=image-config-context.shared-runtime.js.map
+
+      /***/
+    },
   },
 ]);
```
</details>
<details>
<summary>Diff for <strong>9304-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-app-HASH.js</strong></summary>

```diff
@@ -1,64 +1,64 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [4977],
   {
-    /***/ 3228: /***/ () => {
-      /* (ignored) */
-      /***/
-    },
-
-    /***/ 6759: /***/ (
+    /***/ 2043: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
     ) => {
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 2374, 23)
+        __webpack_require__.t.bind(__webpack_require__, 2816, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 2673, 23)
+        __webpack_require__.t.bind(__webpack_require__, 3319, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 4710, 23)
+        __webpack_require__.t.bind(__webpack_require__, 3564, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 9138, 23)
+        __webpack_require__.t.bind(__webpack_require__, 4932, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 9207, 23)
+        __webpack_require__.t.bind(__webpack_require__, 4549, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 4379, 23)
+        __webpack_require__.t.bind(__webpack_require__, 3877, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 631, 23)
+        __webpack_require__.t.bind(__webpack_require__, 6769, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 6231, 23)
+        __webpack_require__.t.bind(__webpack_require__, 5521, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 4706, 23)
+        __webpack_require__.t.bind(__webpack_require__, 9520, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 7121, 23)
+        __webpack_require__.t.bind(__webpack_require__, 5947, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 6594, 23)
+        __webpack_require__.t.bind(__webpack_require__, 1720, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.bind(__webpack_require__, 2231)
+        __webpack_require__.bind(__webpack_require__, 977)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 9683, 23)
+        __webpack_require__.t.bind(__webpack_require__, 7569, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 174, 23)
+        __webpack_require__.t.bind(__webpack_require__, 1504, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 3496, 23)
+        __webpack_require__.t.bind(__webpack_require__, 4186, 23)
       );
 
       /***/
     },
+
+    /***/ 3550: /***/ () => {
+      /* (ignored) */
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
@@ -66,8 +66,8 @@
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(
       0,
-      [5862, 9304],
-      () => (__webpack_exec__(7007), __webpack_exec__(6759))
+      [3008, 2426],
+      () => (__webpack_exec__(6401), __webpack_exec__(2043))
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page-exp..time.prod.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page-tur..ntime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page-tur..ntime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page.runtime.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.ru..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-turbo...ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-turbo...time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 189b273df35ec7b0ae200dd544addb98f2e2859a

File: test/e2e/app-dir/dynamic/app/csp-nonce/dynamic-component.js (hunk 1 above)
Comment (TrevorBurnham) [reply test/e2e/app-dir/dynamic/app/csp-nonce/dynamic-component.js]: Got it! I've made that change and rebased this branch.

I'm still seeing test failures in CI, but I believe those are unrelated to this change. Let me know if I'm mistaken.

**Review by huozhi — APPROVED** [review]

File: test/e2e/app-dir/dynamic/app/csp-nonce/dynamic-component.js (hunk 1 above)
Comment (huozhi) [reply test/e2e/app-dir/dynamic/app/csp-nonce/dynamic-component.js]: Fixed and merged, thanks for the contribution!
