### PR TITLE
fix(turbopack): preserve resolveExtensions priority in read_matches fast path

### LINKED ISSUE #91117: [Turbopack] Import statements are not resolved in the order specified in the resolve extensions config
### Link to the code that reproduces this issue

https://github.com/gabrieltrompiz/turbopack-rn-reproduction-app

### To Reproduce

1. Start the application in dev mode (`pnpm dev`, `yarn dev` or `npm run dev`)
2. Go to localhost:3000 (or whatever port Next is using)

### Current vs. Expected behavior

Using Turbopack, the app throws an error while compiling the page because it tries to import React Native code. I assume this happens because it's not resolving the modules using the order specified in the resolve extensions config. The extension `web.js` should be evaluated before `.js` since that's the usual way third-party React Native libraries allow for React Native for Web usage.

If Webpack is used (with `--webpack` flag), then the application compiles successfully. I would expect the resolve extensions from Turbopack to work similarly to how Webpack resolve extensions option works.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 25.2.0: Tue Nov 18 21:07:05 PST 2025; root:xnu-12377.61.12~1/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 24.11.1
  npm: 11.6.2
  Yarn: 1.22.22
  pnpm: 10.26.2
Relevant Packages:
  next: 16.2.0-canary.85 // Latest available version is detected (16.2.0-canary.85).
  eslint-config-next: N/A
  react: 19.2.4
  react-dom: 19.2.4
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

Next config being used:

```js
const nextConfig: NextConfig = {
  turbopack: {
    resolveAlias: {
      "react-native": "react-native-web",
    },
    resolveExtensions: [
      ".web.js",
      ".web.jsx",
      ".web.ts",
      ".web.tsx",
      ".mdx",
      ".tsx",
      ".ts",
      ".jsx",
      ".js",
      ".mjs",
      ".json",
    ],
    root: __dirname,
  },

  webpack: (config) => {
    config.resolve.alias = {
      ...(config.resolve.alias || {}),
      // Transform all direct `react-native` imports to `react-native-web`
      "react-native$": "react-native-web",
    };
    config.resolve.extensions = [
      ".web.js",
      ".web.jsx",
      ".web.ts",
      ".web.tsx",
      ...config.resolve.extensions,
    ];
    return config;
  },
};
```

### PR DESCRIPTION
**Pull request by sokra**
### What?

Fix a bug where Turbopack ignored the priority order of `resolveExtensions` when both a platform-specific variant (e.g. `Component.web.tsx`) and a default variant (`Component.tsx`) exist for the same module path. The first-listed extension should always win, but it often didn't.

### Why?

Turbopack's `read_matches` function iterates over constant alternatives extracted from a resolve pattern (one per extension in `resolveExtensions`). It uses `enumerate()` to assign a priority `index` to each alternative — lower index = higher priority — so the correct file is picked after sorting.

The `until_end=true` branch (direct file existence check) correctly threaded `index` through. But the `until_end=false` branch (subdirectory descent, the path taken when the pattern contains a `/` before the dynamic suffix) had a **hardcoded `0`** instead of `index`:

```rust
// before — all alternatives get the same priority
nested.push((0, read_matches(fs_path.clone(), ...)));

// after — priority matches the extension's position in resolveExtensions
nested.push((index, read_matches(fs_path.clone(), ...)));
```

With all alternatives at priority 0, the tie-breaking sort was effectively arbitrary. In practice `Component.tsx` frequently beat `Component.web.tsx` even when `.web.tsx` was listed first, breaking platform-specific module overrides — a common React Native Web / Expo Web pattern.

### How?

**One-line Rust fix** in `turbopack/crates/turbopack-core/src/resolve/pattern.rs`: replace the hardcoded `0` with the loop variable `index` in the `until_end=false` branch of the fast path.

**Turbopack unit tests** (`turbopack-core`):
- `test_custom_extensions_web_before_default` — `.web.tsx` wins when listed first in `resolveExtensions`
- `test_custom_extensions_fallback_when_web_missing` — correctly falls back to `.tsx` when `.web.tsx` is absent
- Extended `test_read_matches` with `extension_ordering` and `subpath_ordering` cases covering both the `until_end=true` and `until_end=false` branches

**Next.js e2e test** (extended `test/e2e/app-dir/resolve-extensions/`):
- Added `PlatformComponent.web.tsx` (renders `"hello web platform"`) and `PlatformComponent.tsx` (renders `"hello default platform"`)
- `.web.tsx` is placed before `.tsx` in `resolveExtensions` in `next.config.js` (for both Turbopack and webpack)
- New assertion: SSR'd HTML must contain `"hello web platform"` and must **not** contain `"hello default platform"`

Fixes #91117

- [x] Tests added. See: https://github.com/vercel/next.js/blob/canary/contributing/core/testing.md#writing-tests-for-nextjs

### CODE REVIEW

File: turbopack/crates/turbopack-core/src/resolve/pattern.rs [hunk 1]
```diff
@@ -1632,7 +1632,7 @@ pub async fn read_matches(
                             continue;
                         };
                         nested.push((
-                            0,
+                            index,
```
Comment (sokra) [inline turbopack/crates/turbopack-core/src/resolve/pattern.rs:1635]: This is the fix. The remaining changes are test code

**Review by lukesandberg — APPROVED** [review]
