### PR TITLE
Fix running server with Polyfilled fetch

### LINKED ISSUE #30398: Getting "ReferenceError: Response is not defined" while trying to upgrade an app from next 11 to next 12
### What version of Next.js are you using?

12.0.0

### What version of Node.js are you using?

16.3.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next build + next start

### Describe the Bug

I am trying to upgrade Next.js version in a big application from v11.0.1 to Next.js 12. It uses Next with express.js.
I'm getting the following error:
```
ReferenceError: Response is not defined
    at Object.<anonymous> (/Users/andreisena/projects/.../node_modules/next/dist/server/web/spec-extension/response.js:23:28)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.wrappedLoad [as _load] (/Users/andreisena/projects/.../node_modules/newrelic/lib/shimmer.js:373:24)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/andreisena/projects/.../node_modules/next/dist/server/next-server.js:47:17)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
```

### Expected Behavior

To work correctly like v11

### To Reproduce

I couldn't reproduce it yet on a fresh install of Next.js and I cannot share the repo since it is private. But if I find something new I will post here.

What I could see in a fresh install is that when I debug Response in `server/web/spec-extension/response.js`, it has the same contract as **node-fetch** Response. Is that correct?

```
Object [Response] {
  url: [Getter],
  status: [Getter],
  ok: [Getter],
  redirected: [Getter],
  statusText: [Getter],
  headers: [Getter],
  clone: [Function: clone],
  body: [Getter],
  bodyUsed: [Getter],
  arrayBuffer: [Function: arrayBuffer],
  blob: [Function: blob],
  json: [Function: json],
  text: [Function: text],
  buffer: [Function: buffer],
  textConverted: [Function: textConverted]
}
```

By the way, on the main application, Response always come as undefined.

### PR DESCRIPTION
**Pull request by javivelasco**
This PR fixes #30398

By default Next will polyfill some fetch APIs (Request, Response, Header and fetch) only if fetch is not found in the global scope in certain entry points. If we have a custom server which is adding a global fetch (and only fetch) at the very top then the rest of APIs will not be polyfilled.

This PR adds a test on the custom server where we can add a custom polyfill for fetch with an env variable. This reproduces the issue since next-server.js will be required without having a polyfill for Response which makes it fail on requiring NextResponse. Then we remove the code that checks for subrequests to happen within the **sandbox** so that we don't need to polyfill `next-server` anymore.

The we also introduce an improvement on how we handle relative requests. Since #31858 introduced a `port` and `hostname` options for the server, we can always pass absolute URLs to the Middleware so we can always use the original `nextUrl` to pass it to fetch. This brings a lot of simplification for `NextURL` since we don't have to consider relative URLs no more.

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [x] Errors have helpful link attached, see `contributing.md`

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 18.8s | 18.9s | ⚠️ +78ms |
| buildDurationCached | 3.4s | 3.5s | ⚠️ +22ms |
| nodeModulesSize | 346 MB | 346 MB | ⚠️ +3.08 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.978 | 2.952 | -0.03 |
| / avg req/sec | 839.49 | 846.87 | +7.38 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.4 | 1.392 | -0.01 |
| /error-in-render avg req/sec | 1785.57 | 1795.68 | +10.11 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.45 kB | 4.45 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 20.1s | 20.3s | ⚠️ +242ms |
| buildDurationCached | 3.5s | 3.4s | -92ms |
| nodeModulesSize | 346 MB | 346 MB | ⚠️ +3.08 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.955 | 3.021 | ⚠️ +0.07 |
| / avg req/sec | 845.99 | 827.41 | ⚠️ -18.58 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.41 | 1.38 | -0.03 |
| /error-in-render avg req/sec | 1773.19 | 1811.11 | +37.92 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.47 kB | 4.47 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 495454a247f1ee95bb3a109f7d34fb8cef832446

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 056131ba6c7753021add3c466297ee062439701b

**test/integration/amphtml-fragment-style/test/index.test.js** 
- AMP Fragment Styles > adds styles from fragment in AMP mode correctly

<details>
<summary>Expand output</summary>

  ● AMP Fragment Styles › adds styles from fragment in AMP mode correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "PASS"
    Received: "FAIL"



      at Object.validateAMP (lib/amp-test-utils.js:26:27)
      at Object.<anonymous> (integration/amphtml-fragment-style/test/index.test.js:32:9)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 20.7s | 21.7s | ⚠️ +1s |
| buildDurationCached | 3.7s | 3.9s | ⚠️ +158ms |
| nodeModulesSize | 346 MB | 346 MB | ⚠️ +3.09 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.309 | 3.363 | ⚠️ +0.05 |
| / avg req/sec | 755.46 | 743.29 | ⚠️ -12.17 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.578 | 1.591 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1584.56 | 1571.56 | ⚠️ -13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.45 kB | 4.45 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 21.7s | 23.2s | ⚠️ +1.5s |
| buildDurationCached | 3.7s | 4.1s | ⚠️ +395ms |
| nodeModulesSize | 346 MB | 346 MB | ⚠️ +3.09 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.417 | 3.418 | 0 |
| / avg req/sec | 731.71 | 731.49 | ⚠️ -0.22 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.571 | 1.736 | ⚠️ +0.17 |
| /error-in-render avg req/sec | 1591.36 | 1440.22 | ⚠️ -151.14 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.47 kB | 4.47 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 056131ba6c7753021add3c466297ee062439701b

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f8983ee526f92a75b9c66ac8d567e540caad9577

**test/integration/amphtml-fragment-style/test/index.test.js** 
- AMP Fragment Styles > adds styles from fragment in AMP mode correctly

<details>
<summary>Expand output</summary>

  ● AMP Fragment Styles › adds styles from fragment in AMP mode correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "PASS"
    Received: "FAIL"



      at Object.validateAMP (lib/amp-test-utils.js:26:27)
      at Object.<anonymous> (integration/amphtml-fragment-style/test/index.test.js:32:9)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 21.9s | 22.3s | ⚠️ +433ms |
| buildDurationCached | 4.1s | 4.1s | ⚠️ +28ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +3.09 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.749 | 3.77 | ⚠️ +0.02 |
| / avg req/sec | 666.92 | 663.09 | ⚠️ -3.83 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.025 | 1.958 | -0.07 |
| /error-in-render avg req/sec | 1234.61 | 1276.87 | +42.26 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 24.2s | 23.6s | -545ms |
| buildDurationCached | 4.1s | 4s | -63ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +3.09 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.75 | 3.697 | -0.05 |
| / avg req/sec | 666.63 | 676.21 | +9.58 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.971 | 1.951 | -0.02 |
| /error-in-render avg req/sec | 1268.34 | 1281.5 | +13.16 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.53 kB | 4.53 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: f8983ee526f92a75b9c66ac8d567e540caad9577

**Comment by ijjk** [comment]
## Failing test suites 
Commit: dca207fca082a8151a49ad6c917bd6d518a6c737

**test/integration/image-component/default/test/static.test.js** 
- Static Image Component Tests > Should allow an image with a static src to omit height and width
- Static Image Component Tests > Should use immutable cache-control header for static import
- Static Image Component Tests > Should use immutable cache-control header even when unoptimized
- Static Image Component Tests > Should automatically provide an image height and width
- Static Image Component Tests > Should allow provided width and height to override intrinsic
- Static Image Component Tests > Should add a blur placeholder to statically imported jpg
- Static Image Component Tests > Should add a blur placeholder to statically imported png

<details>
<summary>Expand output</summary>

  ● Static Image Component Tests › Should allow an image with a static src to omit height and width

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:43541/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/default/test/static.test.js:77:19

  ● Static Image Component Tests › Should use immutable cache-control header for static import

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:43541/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/default/test/static.test.js:77:19

  ● Static Image Component Tests › Should use immutable cache-control header even when unoptimized

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:43541/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/default/test/static.test.js:77:19

  ● Static Image Component Tests › Should automatically provide an image height and width

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:43541/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/default/test/static.test.js:77:19

  ● Static Image Component Tests › Should allow provided width and height to override intrinsic

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:43541/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/default/test/static.test.js:77:19

  ● Static Image Component Tests › Should add a blur placeholder to statically imported jpg

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:43541/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/default/test/static.test.js:77:19

  ● Static Image Component Tests › Should add a blur placeholder to statically imported png

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:43541/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/default/test/static.test.js:77:19

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 22.2s | 21.7s | -447ms |
| buildDurationCached | 3.8s | 3.8s | -44ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +4.15 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.709 | 3.727 | ⚠️ +0.02 |
| / avg req/sec | 673.95 | 670.77 | ⚠️ -3.18 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.017 | 1.866 | -0.15 |
| /error-in-render avg req/sec | 1239.27 | 1339.92 | +100.65 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 22.9s | 23.2s | ⚠️ +274ms |
| buildDurationCached | 3.9s | 3.8s | -137ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +4.15 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.787 | 3.558 | -0.23 |
| / avg req/sec | 660.17 | 702.64 | +42.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.973 | 1.861 | -0.11 |
| /error-in-render avg req/sec | 1267.1 | 1343.1 | +76 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.53 kB | 4.53 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: dca207fca082a8151a49ad6c917bd6d518a6c737

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 24.5s | 24.5s | ⚠️ +20ms |
| buildDurationCached | 4.3s | 4.4s | ⚠️ +89ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +4.15 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.387 | 3.966 | -0.42 |
| / avg req/sec | 569.9 | 630.35 | +60.45 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.234 | 2.313 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1118.88 | 1080.71 | ⚠️ -38.17 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 26.8s | 26.9s | ⚠️ +92ms |
| buildDurationCached | 4.5s | 4.5s | -45ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +4.15 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.082 | 4.09 | ⚠️ +0.01 |
| / avg req/sec | 612.47 | 611.27 | ⚠️ -1.2 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.355 | 2.212 | -0.14 |
| /error-in-render avg req/sec | 1061.35 | 1130.37 | +69.02 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.53 kB | 4.53 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 90dc5ae1be9307fc56e230f2005130d48f8ed808

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 90dc5ae1be9307fc56e230f2005130d48f8ed808

**test/integration/image-component/base-path/test/static.test.js** 
- Static Image Component Tests for basePath > dev mode > Should allow an image with a static src to omit height and width
- Static Image Component Tests for basePath > dev mode > Should use immutable cache-control header for static import
- Static Image Component Tests for basePath > dev mode > Should automatically provide an image height and width
- Static Image Component Tests for basePath > dev mode > Should allow provided width and height to override intrinsic
- Static Image Component Tests for basePath > dev mode > Should add a blur placeholder to statically imported jpg
- Static Image Component Tests for basePath > dev mode > Should add a blur placeholder to statically imported png

<details>
<summary>Expand output</summary>

  ● Static Image Component Tests for basePath › dev mode › Should allow an image with a static src to omit height and width

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:41717/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should use immutable cache-control header for static import

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:41717/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should automatically provide an image height and width

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:41717/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should allow provided width and height to override intrinsic

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:41717/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should add a blur placeholder to statically imported jpg

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:41717/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should add a blur placeholder to statically imported png

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:41717/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 24.1s | 24.3s | ⚠️ +154ms |
| buildDurationCached | 4.3s | 4.3s | -12ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +4.13 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.027 | 3.995 | -0.03 |
| / avg req/sec | 620.76 | 625.71 | +4.95 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.183 | 2.109 | -0.07 |
| /error-in-render avg req/sec | 1145.2 | 1185.5 | +40.3 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 26.3s | 26.3s | ⚠️ +12ms |
| buildDurationCached | 4.3s | 4.3s | ⚠️ +50ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +4.13 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.999 | 3.953 | -0.05 |
| / avg req/sec | 625.16 | 632.47 | +7.31 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.108 | 2.114 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1185.77 | 1182.57 | ⚠️ -3.2 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.53 kB | 4.53 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 5a4b78ca0ee8937510d71f4dc3fe37457efce972

File: packages/next/server/web/next-url.ts [hunk 1]
```diff
@@ -1,66 +1,67 @@
...
-const REGEX_LOCALHOST_HOSTNAME =
-  /(?!^https?:\/\/)(127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}|::1)/
-
 export class NextURL extends URL {
-  private _basePath: string
-  private _locale?: {
+  #url: URL
+  #options: Options
+  #basePath: string
+  #locale?: {
```
Comment (ijjk) [inline packages/next/server/web/next-url.ts:19]: This syntax doesn't seem to be transpiled correctly and breaks node 12 on Azure:

```sh
 D:\a\1\s\node_modules\next\dist\server\web\next-url.js:36
         #analyzeUrl() {
                    ^

    SyntaxError: Unexpected token '('
```

x-ref: https://dev.azure.com/nextjs/next.js/_build/results?buildId=31424&view=logs&jobId=8af7cf9c-43a1-584d-6f5c-57bad8880974&j=8af7cf9c-43a1-584d-6f5c-57bad8880974&t=c6df12fd-6020-5e41-5b45-429ae6a49942

**Comment by ijjk** [comment]
## Failing test suites 
Commit: ec744321cde8f297bf4eac26091f2d7e52271add

**test/production/middleware-typescript/test/index.test.ts** 
- should set-up next > should have built and started

<details>
<summary>Expand output</summary>

  ● should set-up next › should have built and started

    thrown: "Exceeded timeout of 90000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

       6 | import { renderViaHTTP } from 'next-test-utils'
       7 |
    >  8 | const appDir = join(__dirname, '../app')
         |     ^
       9 |
      10 | describe('should set-up next', () => {
      11 |   let next: NextInstance

      at production/middleware-typescript/test/index.test.ts:8:5
      at Object.<anonymous> (production/middleware-typescript/test/index.test.ts:6:1)


  ● Test suite failed to run

    TypeError: Cannot read property 'destroy' of undefined

      20 |       dependencies: {
      21 |         typescript: 'latest',
    > 22 |         '@types/react': 'latest',
         |                       ^
      23 |         '@types/react-dom': 'latest',
      24 |       },
      25 |     })

      at production/middleware-typescript/test/index.test.ts:22:23

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 23.9s | 24s | ⚠️ +135ms |
| buildDurationCached | 4.3s | 4.2s | -39ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +4.14 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.987 | 3.927 | -0.06 |
| / avg req/sec | 627.01 | 636.61 | +9.6 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.073 | 2.022 | -0.05 |
| /error-in-render avg req/sec | 1205.99 | 1236.18 | +30.19 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 26.2s | 26.1s | -40ms |
| buildDurationCached | 4.3s | 4.2s | -36ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +4.14 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.056 | 3.937 | -0.12 |
| / avg req/sec | 616.4 | 635.03 | +18.63 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.174 | 2.011 | -0.16 |
| /error-in-render avg req/sec | 1149.94 | 1243.23 | +93.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.53 kB | 4.53 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: ec744321cde8f297bf4eac26091f2d7e52271add

File: packages/next/server/web/next-url.ts (hunk 1 above)
Comment (javivelasco) [reply packages/next/server/web/next-url.ts:19]: Interesting, I will migrate it to use symbols in order to hide the internals 🙏

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 23.8s | 23.2s | -603ms |
| buildDurationCached | 4.2s | 4.2s | -23ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +5.36 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.965 | 3.999 | ⚠️ +0.03 |
| / avg req/sec | 630.55 | 625.21 | ⚠️ -5.34 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.057 | 2.004 | -0.05 |
| /error-in-render avg req/sec | 1215.64 | 1247.6 | +31.96 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| buildDuration | 26.5s | 26.3s | -161ms |
| buildDurationCached | 4.3s | 4.2s | -137ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +5.36 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.876 | 3.977 | ⚠️ +0.1 |
| / avg req/sec | 645.02 | 628.62 | ⚠️ -16.4 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.032 | 2.03 | 0 |
| /error-in-render avg req/sec | 1230.15 | 1231.31 | +1.16 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.53 kB | 4.53 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30398 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: d027c2b55a751355ef4065689cb5315dc1ca5c1f

**Review by ijjk — APPROVED** [review]
