### PR TITLE
Replace worker-farm with jest-worker

### LINKED ISSUE #4647: npm run build hangs forever
# Bug report

## Describe the bug

npm run build with invokes 'next build' is hanging forever.

## To Reproduce

Cannot specify steps to reproduce because it suddenly not 

## Expected behavior

It should build normally so that I can run npm start.

## Screenshots
image

## System information
 - OS: [e.g. macOS, Windows]
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: [e.g. 6.0.2]

### LINKED ISSUE #7766: Build process doesn't end
# Bug report

## Describe the bug

I keep trying to run "next build", and it won't work. I've tried deleting the .next folder, and I've ran both yarn and npm (after deleting yarn.lock, and package-lock, respectively)
## To Reproduce

Checkout 

1.Clone  https://github.com/AmherstStudent/amherst-student-site/tree/code-clean
2. Run yarn && yarn build
3. See error

## Expected behavior

Finished build process

## System information

- Windows
- Version of Next.js:  v8. canary

### PR DESCRIPTION
**Pull request by ijjk**
Removes `worker-farm`/`serialize-javascript` and replaces them with `jest-worker`.

---

Fixes #4647
Fixes #7766

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| buildDuration | 21.2s | 21.8s | ⚠️ +676ms |
| nodeModulesSize | 41.2 MB | 41.3 MB | ⚠️ +62.4 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| buildDuration | 23.5s | 25.4s | ⚠️ +1.8s |
| nodeModulesSize | 41.2 MB | 41.3 MB | ⚠️ +62.4 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | -8 B |
| _error.js gzip | 66.2 kB | 66.4 kB | ⚠️ +161 B |
| hooks.html | 3.81 kB | 3.81 kB | -3 B |
| hooks.html gzip | 977 B | 977 B | ✓ |
| index.js | 248 kB | 248 kB | -8 B |
| index.js gzip | 66.6 kB | 66.7 kB | ⚠️ +149 B |
| link.js | 255 kB | 255 kB | -8 B |
| link.js gzip | 68.8 kB | 68.8 kB | ⚠️ +87 B |
| routerDirect.js | 249 kB | 249 kB | -8 B |
| routerDirect.js gzip | 66.7 kB | 66.7 kB | ⚠️ +60 B |
| withRouter.js | 248 kB | 248 kB | -8 B |
| withRouter.js gzip | 66.8 kB | 66.6 kB | -261 B |
| Overall change |  |  | -43 B |

</details>

</details>

File: packages/next/build/index.ts [hunk 1]
```diff
@@ -208,13 +208,9 @@ export default async function build(dir: string, conf = null): Promise<void> {
...
   })
-  const staticCheckWorkers = workerFarm(
-    {
-      maxConcurrentWorkers: config.experimental.cpus,
-    },
-    staticCheckWorker,
-    ['default']
-  )
+  const staticCheckWorkers = new Worker(staticCheckWorker, {
+    numWorkers: config.experimental.cpus,
```
Comment (Timer) [inline packages/next/build/index.ts]:
```suggestion
    numWorkers: config.experimental.cpus,
    enableWorkerThreads: true,
```

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js [hunk 2]
```diff
@@ -31,30 +29,19 @@ export default class TaskRunner {
...
-        }
-      }
+      let enableWorkerThreads = false
+      try {
+        require('worker_threads')
+        enableWorkerThreads = true
+      } catch (_) {}
+
+      this.workers = new Worker(worker, {
+        enableWorkerThreads,
```
Comment (Timer) [inline packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js]:
```suggestion
        enableWorkerThreads: true,
```

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js [hunk 3]
```diff
@@ -31,30 +29,19 @@ export default class TaskRunner {
...
-      this.workers = workerFarm(workerOptions, worker)
-      this.boundWorkers = (options, cb) => {
-        try {
-          this.workers(serialize(options), cb)
-        } catch (error) {
-          // worker-farm can fail with ENOMEM or something else
-          cb(error)
-        }
-      }
+      let enableWorkerThreads = false
```
Comment (Timer) [inline packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js]:
```suggestion
```

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js [hunk 4]
```diff
@@ -31,30 +29,19 @@ export default class TaskRunner {
...
+      try {
```
Comment (Timer) [inline packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js]:
```suggestion
```

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js [hunk 5]
```diff
@@ -31,30 +29,19 @@ export default class TaskRunner {
...
+        require('worker_threads')
```
Comment (Timer) [inline packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js]:
```suggestion
```

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js [hunk 6]
```diff
@@ -31,30 +29,19 @@ export default class TaskRunner {
...
+        enableWorkerThreads = true
```
Comment (Timer) [inline packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js]:
```suggestion
```

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js [hunk 7]
```diff
@@ -31,30 +29,19 @@ export default class TaskRunner {
...
+      } catch (_) {}
```
Comment (Timer) [inline packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js]:
```suggestion
```

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js [hunk 8]
```diff
@@ -31,30 +29,19 @@ export default class TaskRunner {
...
+
```
Comment (Timer) [inline packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js]:
```suggestion
```

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js [hunk 9]
```diff
@@ -71,20 +58,19 @@ export default class TaskRunner {
...
+          if (cachePath) {
+            writeFileP(cachePath, JSON.stringify(result), 'utf8')
               .then(done)
               .catch(done)
-          } else {
-            done()
           }
-        })
+        } catch (error) {
+          console.error('Error occurred minifying', error)
```
Comment (Timer) [inline packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js]:
```suggestion
```

We already handle this elsewhere, right? Was this for debugging?

**Review by Timer — CHANGES_REQUESTED** [review]

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/worker.js [hunk 10]
```diff
@@ -1,21 +1,2 @@
...
-      '__dirname',
-      `'use strict'\nreturn ${options}`
-    )(exports, require, module, __filename, __dirname)
-
-    callback(null, minify(options))
-  } catch (errors) {
-    callback(errors)
-  }
-}
+export default options => minify(options)
```
Comment (Timer) [inline packages/next/build/webpack/plugins/terser-webpack-plugin/src/worker.js]: Can we unwind this shell file?

File: packages/next/build/index.ts [hunk 11]
```diff
@@ -208,13 +208,9 @@ export default async function build(dir: string, conf = null): Promise<void> {
   const staticCheckSema = new Sema(config.experimental.cpus, {
```
Comment (Timer) [inline packages/next/build/index.ts]: Does `jest-worker` still need a semaphore?

**Review by Timer — CHANGES_REQUESTED** [review]

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js (hunk 9 above)
Comment (ijjk) [reply packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js]: Yeah, I added it for debugging, although the error shown without this isn't very helpful so I left it in

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/worker.js (hunk 10 above)
Comment (ijjk) [reply packages/next/build/webpack/plugins/terser-webpack-plugin/src/worker.js]: What do you mean by unwind?

File: packages/next/build/index.ts (hunk 11 above)
Comment (ijjk) [reply packages/next/build/index.ts]: Yeah, it's probably still good to use the semaphore

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| buildDuration | 22.3s | 22.1s | -186ms |
| nodeModulesSize | 41.2 MB | 41.3 MB | ⚠️ +62 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| buildDuration | 24.4s | 24.2s | -222ms |
| nodeModulesSize | 41.2 MB | 41.3 MB | ⚠️ +62 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.4 kB | 66.4 kB | ⚠️ +1 B |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| hooks.html gzip | 975 B | 977 B | ⚠️ +2 B |
| index.js | 248 kB | 248 kB | ✓ |
| index.js gzip | 66.7 kB | 66.7 kB | -33 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.8 kB | 68.7 kB | -137 B |
| routerDirect.js | 249 kB | 249 kB | ✓ |
| routerDirect.js gzip | 66.6 kB | 66.6 kB | ⚠️ +63 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.6 kB | 66.7 kB | ⚠️ +60 B |
| Overall change |  |  | ✓ |

</details>

</details>

File: packages/next/build/index.ts (hunk 11 above)
Comment (Timer) [reply packages/next/build/index.ts]: IIRC we only needed this for flying shuttle (because the bundles were so big). @timneutkens recently remarked that `cpu * 3` was actually pretty small -- can we try to remove it and see if it works on `front`?

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/worker.js (hunk 10 above)
Comment (Timer) [reply packages/next/build/webpack/plugins/terser-webpack-plugin/src/worker.js]: Just delete it and make `jest-worker` call the `minify.js` file directly.

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js (hunk 9 above)
Comment (Timer) [reply packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js]: Hmm, the terser error should be pushed into the webpack errors -- are we sure the terser error is propagating correctly? Or what specific error is this for, an internal `jest-worker` error?

File: packages/next/build/index.ts (hunk 11 above)
Comment (Timer) [reply packages/next/build/index.ts]: Like, `jest-worker` should already be handling "semaphoring" right? There's only so many workers -- I feel like it's better to defer the backoff/queuing to `jest-worker`.

Comment (Timer) [reply packages/next/build/index.ts]: Also, we can probably remove the semaphore from the terser taskrunner as well.

Comment (ijjk) [reply packages/next/build/index.ts]: Letting `jest-worker` handle the queueing makes sense, removed the semaphore from both and appears to handle `front` fine locally

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/worker.js (hunk 10 above)
Comment (ijjk) [reply packages/next/build/webpack/plugins/terser-webpack-plugin/src/worker.js]: Ah yeah makes sense 👍

File: packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js (hunk 9 above)
Comment (ijjk) [reply packages/next/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js]: Terser errors are propagated correctly it wasn't logging the errors I encountered when adding `jest-worker` so thought it would be good to log them there also but I guess it's not needed since that shouldn't happen, removed it

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| buildDuration | 23.6s | 23.4s | -192ms |
| nodeModulesSize | 41.2 MB | 41.3 MB | ⚠️ +61.1 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.64 kB | 6.64 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.37 kB | 6.37 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| index.html | 3.69 kB | 3.69 kB | ⚠️ +3 B |
| index.html gzip | 955 B | 959 B | ⚠️ +4 B |
| link.html | 3.74 kB | 3.74 kB | ⚠️ +3 B |
| link.html gzip | 964 B | 968 B | ⚠️ +4 B |
| withRouter.html | 3.75 kB | 3.75 kB | ⚠️ +3 B |
| withRouter.html gzip | 950 B | 955 B | ⚠️ +5 B |
| Overall change |  |  | ⚠️ +9 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[11],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_app.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
 
 /***/ "B5Ud":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_error.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
 
 /***/ "+iuc":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>hooks.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
 
 /***/ "+MDD":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>index.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
 
 /***/ "RNiq":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[9],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[9],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
 
 /***/ "LtRI":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[11],{
 
 /***/ "0Hlz":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_app.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_error.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
 
 /***/ "+iuc":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>hooks.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
 
 /***/ "+MDD":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>index.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
 
 /***/ "RNiq":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>routerDirect.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[9],{
 
 /***/ "LtRI":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>withRouter.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[9],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
 
 /***/ "0Hlz":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -6,19 +6,19 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/NzVavano2P1kNmmRhMLzM/pages/index.module.js"
+        <link rel="preload" href="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/index.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/NzVavano2P1kNmmRhMLzM/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-9c0b8b62a2fb27af35b2.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-57fd58f9724110a1d2ca.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/KptZlOTZwSDjzQtRwvGB8y9ZYo=.72ab6ea1ebeafbd8c735.module.js"
+        <link rel="preload" href="/_next/static/chunks/4xixvm7YpVwKIXXMT0PZaZm1D+s=.72ab6ea1ebeafbd8c735.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/NzVavano2P1kNmmRhMLzM/_buildManifest.module.js"
+        <link rel="preload" href="/_next/static/scXnk1WWgOXzqugyGU3VS/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -26,40 +26,40 @@
         <div id="__next">Hello world 👋</div>
         <script id="__NEXT_DATA__" type="application/json"
         crossorigin="anonymous">
-            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"NzVavano2P1kNmmRhMLzM"}
+            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"scXnk1WWgOXzqugyGU3VS"}
         </script>
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script async="" data-next-page="/" src="/_next/static/NzVavano2P1kNmmRhMLzM/pages/index.js"
+        <script async="" data-next-page="/" src="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/index.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/" src="/_next/static/NzVavano2P1kNmmRhMLzM/pages/index.module.js"
+        <script async="" data-next-page="/" src="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/index.module.js"
         crossorigin="anonymous" type="module"></script>
-        <script async="" data-next-page="/_app" src="/_next/static/NzVavano2P1kNmmRhMLzM/pages/_app.js"
+        <script async="" data-next-page="/_app" src="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/_app.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/_app" src="/_next/static/NzVavano2P1kNmmRhMLzM/pages/_app.module.js"
+        <script async="" data-next-page="/_app" src="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/_app.module.js"
         crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-97617d800ec2b207a20a.js"
+        <script src="/_next/static/runtime/main-758fcb9b9994c6769dbb.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-9c0b8b62a2fb27af35b2.module.js"
+        <script src="/_next/static/runtime/main-57fd58f9724110a1d2ca.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.js"
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/chunks/+QATEkzP89Ad53IC1yRuxvB23w=.155621535702fe040780.js"
+        <script src="/_next/static/chunks/63UgzG2Jn9a5Xr5AslgCks65pA=.155621535702fe040780.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/KptZlOTZwSDjzQtRwvGB8y9ZYo=.c99adde05e467047c83e.js"
+        <script src="/_next/static/chunks/4xixvm7YpVwKIXXMT0PZaZm1D+s=.c99adde05e467047c83e.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/KptZlOTZwSDjzQtRwvGB8y9ZYo=.72ab6ea1ebeafbd8c735.module.js"
+        <script src="/_next/static/chunks/4xixvm7YpVwKIXXMT0PZaZm1D+s=.72ab6ea1ebeafbd8c735.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/NzVavano2P1kNmmRhMLzM/_buildManifest.js"
+        <script src="/_next/static/scXnk1WWgOXzqugyGU3VS/_buildManifest.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/NzVavano2P1kNmmRhMLzM/_buildManifest.module.js"
+        <script src="/_next/static/scXnk1WWgOXzqugyGU3VS/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
     </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -6,19 +6,19 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/NzVavano2P1kNmmRhMLzM/pages/link.module.js"
+        <link rel="preload" href="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/link.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/NzVavano2P1kNmmRhMLzM/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/KptZlOTZwSDjzQtRwvGB8y9ZYo=.72ab6ea1ebeafbd8c735.module.js"
+        <link rel="preload" href="/_next/static/chunks/4xixvm7YpVwKIXXMT0PZaZm1D+s=.72ab6ea1ebeafbd8c735.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-9c0b8b62a2fb27af35b2.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-57fd58f9724110a1d2ca.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/NzVavano2P1kNmmRhMLzM/_buildManifest.module.js"
+        <link rel="preload" href="/_next/static/scXnk1WWgOXzqugyGU3VS/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -29,18 +29,18 @@
             </div>
         </div>
         <script id="__NEXT_DATA__" type="application/json" crossorigin="anonymous">
-            {"dataManager":"[]","props":{"pageProps":{}},"page":"/link","query":{},"buildId":"NzVavano2P1kNmmRhMLzM"}
+            {"dataManager":"[]","props":{"pageProps":{}},"page":"/link","query":{},"buildId":"scXnk1WWgOXzqugyGU3VS"}
         </script>
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script async="" data-next-page="/link" src="/_next/static/NzVavano2P1kNmmRhMLzM/pages/link.js"
+        <script async="" data-next-page="/link" src="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/link.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/link" src="/_next/static/NzVavano2P1kNmmRhMLzM/pages/link.module.js"
+        <script async="" data-next-page="/link" src="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/link.module.js"
         crossorigin="anonymous" type="module"></script>
-        <script async="" data-next-page="/_app" src="/_next/static/NzVavano2P1kNmmRhMLzM/pages/_app.js"
+        <script async="" data-next-page="/_app" src="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/_app.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/_app" src="/_next/static/NzVavano2P1kNmmRhMLzM/pages/_app.module.js"
+        <script async="" data-next-page="/_app" src="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/_app.module.js"
         crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
         async="" crossorigin="anonymous" nomodule=""></script>
@@ -50,19 +50,19 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/chunks/+QATEkzP89Ad53IC1yRuxvB23w=.155621535702fe040780.js"
+        <script src="/_next/static/chunks/63UgzG2Jn9a5Xr5AslgCks65pA=.155621535702fe040780.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/KptZlOTZwSDjzQtRwvGB8y9ZYo=.c99adde05e467047c83e.js"
+        <script src="/_next/static/chunks/4xixvm7YpVwKIXXMT0PZaZm1D+s=.c99adde05e467047c83e.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/KptZlOTZwSDjzQtRwvGB8y9ZYo=.72ab6ea1ebeafbd8c735.module.js"
+        <script src="/_next/static/chunks/4xixvm7YpVwKIXXMT0PZaZm1D+s=.72ab6ea1ebeafbd8c735.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-97617d800ec2b207a20a.js"
+        <script src="/_next/static/runtime/main-758fcb9b9994c6769dbb.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-9c0b8b62a2fb27af35b2.module.js"
+        <script src="/_next/static/runtime/main-57fd58f9724110a1d2ca.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/NzVavano2P1kNmmRhMLzM/_buildManifest.js"
+        <script src="/_next/static/scXnk1WWgOXzqugyGU3VS/_buildManifest.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/NzVavano2P1kNmmRhMLzM/_buildManifest.module.js"
+        <script src="/_next/static/scXnk1WWgOXzqugyGU3VS/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
     </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -6,19 +6,19 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/NzVavano2P1kNmmRhMLzM/pages/withRouter.module.js"
+        <link rel="preload" href="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/withRouter.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/NzVavano2P1kNmmRhMLzM/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/KptZlOTZwSDjzQtRwvGB8y9ZYo=.72ab6ea1ebeafbd8c735.module.js"
+        <link rel="preload" href="/_next/static/chunks/4xixvm7YpVwKIXXMT0PZaZm1D+s=.72ab6ea1ebeafbd8c735.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-9c0b8b62a2fb27af35b2.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-57fd58f9724110a1d2ca.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/NzVavano2P1kNmmRhMLzM/_buildManifest.module.js"
+        <link rel="preload" href="/_next/static/scXnk1WWgOXzqugyGU3VS/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -27,18 +27,18 @@
             <div>I use withRouter</div>
         </div>
         <script id="__NEXT_DATA__" type="application/json" crossorigin="anonymous">
-            {"dataManager":"[]","props":{"pageProps":{}},"page":"/withRouter","query":{},"buildId":"NzVavano2P1kNmmRhMLzM"}
+            {"dataManager":"[]","props":{"pageProps":{}},"page":"/withRouter","query":{},"buildId":"scXnk1WWgOXzqugyGU3VS"}
         </script>
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script async="" data-next-page="/withRouter" src="/_next/static/NzVavano2P1kNmmRhMLzM/pages/withRouter.js"
+        <script async="" data-next-page="/withRouter" src="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/withRouter.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/withRouter" src="/_next/static/NzVavano2P1kNmmRhMLzM/pages/withRouter.module.js"
+        <script async="" data-next-page="/withRouter" src="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/withRouter.module.js"
         crossorigin="anonymous" type="module"></script>
-        <script async="" data-next-page="/_app" src="/_next/static/NzVavano2P1kNmmRhMLzM/pages/_app.js"
+        <script async="" data-next-page="/_app" src="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/_app.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/_app" src="/_next/static/NzVavano2P1kNmmRhMLzM/pages/_app.module.js"
+        <script async="" data-next-page="/_app" src="/_next/static/scXnk1WWgOXzqugyGU3VS/pages/_app.module.js"
         crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
         async="" crossorigin="anonymous" nomodule=""></script>
@@ -48,19 +48,19 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/chunks/+QATEkzP89Ad53IC1yRuxvB23w=.155621535702fe040780.js"
+        <script src="/_next/static/chunks/63UgzG2Jn9a5Xr5AslgCks65pA=.155621535702fe040780.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/KptZlOTZwSDjzQtRwvGB8y9ZYo=.c99adde05e467047c83e.js"
+        <script src="/_next/static/chunks/4xixvm7YpVwKIXXMT0PZaZm1D+s=.c99adde05e467047c83e.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/KptZlOTZwSDjzQtRwvGB8y9ZYo=.72ab6ea1ebeafbd8c735.module.js"
+        <script src="/_next/static/chunks/4xixvm7YpVwKIXXMT0PZaZm1D+s=.72ab6ea1ebeafbd8c735.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-97617d800ec2b207a20a.js"
+        <script src="/_next/static/runtime/main-758fcb9b9994c6769dbb.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-9c0b8b62a2fb27af35b2.module.js"
+        <script src="/_next/static/runtime/main-57fd58f9724110a1d2ca.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/NzVavano2P1kNmmRhMLzM/_buildManifest.js"
+        <script src="/_next/static/scXnk1WWgOXzqugyGU3VS/_buildManifest.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/NzVavano2P1kNmmRhMLzM/_buildManifest.module.js"
+        <script src="/_next/static/scXnk1WWgOXzqugyGU3VS/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
     </body>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| buildDuration | 25s | 25.3s | ⚠️ +263ms |
| nodeModulesSize | 41.2 MB | 41.3 MB | ⚠️ +61.1 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.64 kB | 6.64 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.37 kB | 6.37 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | ijjk/next.js add-jest-worker | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | -5 B |
| _error.js gzip | 66.2 kB | 66.3 kB | ⚠️ +17 B |
| hooks.html | 3.81 kB | 3.81 kB | -1 B |
| hooks.html gzip | 981 B | 981 B | ✓ |
| index.js | 248 kB | 248 kB | -5 B |
| index.js gzip | 66.6 kB | 66.5 kB | -97 B |
| link.js | 255 kB | 255 kB | -5 B |
| link.js gzip | 68.8 kB | 68.8 kB | ⚠️ +17 B |
| routerDirect.js | 249 kB | 249 kB | -5 B |
| routerDirect.js gzip | 66.6 kB | 66.6 kB | -7 B |
| withRouter.js | 248 kB | 248 kB | -5 B |
| withRouter.js gzip | 66.6 kB | 66.6 kB | ✓ |
| Overall change |  |  | -26 B |

</details>

</details>

**Review by Timer — APPROVED** [review]
Awesome! This gives us a great advantage for Docker and Windows users!
