### PR TITLE
Fix image blur cover when `fill` and `blurDataURL`

### LINKED ISSUE #40644: next/future/image blur placeholder does not fill parent div
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Binaries:
      Node: 14.17.3
      npm: 8.19.1
      Yarn: 1.22.4
      pnpm: N/A
    Relevant packages:
      next: 12.3.1-canary.3
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

The blur placeholder in next/future/image with fill=true is shown at the original image dimensions instead of filling the parent div (as the image does when loaded)

### Expected Behavior

Same behaviour as next/image, that the placeholder fills the parent div

Above: next/image
Below: next/future/image
futureImageBug

### Link to reproduction

https://github.com/tiotdev/next-future-image-blur-fill-bug

### To Reproduce

```
import Image from "next/image";
import FutureImage from "next/future/image";

export default function Home() {
  return (
    <>
      <div
        style={{
          width: "100%",
          height: "200px",
          backgroundColor: "red",
          position: "relative",
        }}
      >
        <Image
          src="https://img.travelfeed.io/jpphotography%2F20200609T140211386Z-reisen-127.jpg"
          alt=""
          blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAACCAIAAADwyuo0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAI0lEQVR4nGMINGf4/+3at/t7+2viGNQZGKbE69UlOSV5mgEAnuYKmizl818AAAAASUVORK5CYII="
          placeholder="blur"
          layout="fill"
          objectFit="cover"
        />
      </div>
      <div
        style={{
          width: "100%",
          height: "200px",
          backgroundColor: "red",
          position: "relative",
        }}
      >
        <FutureImage
          src="https://img.travelfeed.io/jpphotography%2F20200609T140211386Z-reisen-127.jpg"
          alt=""
          blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAACCAIAAADwyuo0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAI0lEQVR4nGMINGf4/+3at/t7+2viGNQZGKbE69UlOSV5mgEAnuYKmizl818AAAAASUVORK5CYII="
          placeholder="blur"
          fill
          sizes="100vw"
          style={{ objectFit: "cover" }}
        />
      </div>
    </>
  );
}

```

### LINKED ISSUE #42765: Image blur placeholder not taking full width with fill image
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 8.12.1
      Yarn: 1.22.19
      pnpm: 7.14.2
    Relevant packages:
      next: 13.0.2
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107.0.5304.87

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

When using the `Image` component (Next.js v13) with `fill` and a `blurDataURL`, the blurred placeholder is not taking the full width of the viewport as the loaded image does.

<table>
<tr>
	<th> Blurred placeholder
	<th> Loaded image
<tr>
	<td> Screenshot 2022-11-10 at 16 11 51
	<td> Screenshot 2022-11-10 at 16 11 58
</table>

I stumbled across [this PR](https://github.com/vercel/next.js/pull/41573) which fixed some bugs related to the blur placeholder. It seems that adding `preserveAspectRatio="none"` to the generated SVG without width / height would fix the issue but I don't know the implications.
Also, why is it an SVG and not just the `base64` image as it was on Next.js v12?

### Expected Behavior

The blurred SVG should take the full width of the viewport and not display empty spaces around the image. It was working correctly on Next.js v12.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://codesandbox.io/s/goofy-orla-v8kciw

### To Reproduce

Use an `Image` component with `fill` and a `blurDataURL`.

### PR DESCRIPTION
**Pull request by styfle**
- Fixes #42765 
- Fixes #40644 
fix NEXT-259 ([link](https://linear.app/vercel/issue/NEXT-259))

### CODE REVIEW

File: packages/next/server/image-optimizer.ts [hunk 1]
```diff
@@ -631,6 +631,7 @@ export async function imageOptimizer(
         // will inline a special url to lazily generate the blur placeholder at request time.
         const meta = await getMetadata(optimizedBuffer)
         const opts = {
+          objectFit: undefined, // TODO: what value should go here?
```
Comment (styfle) [inline packages/next/server/image-optimizer.ts:634]: Need to do some investigation here to test this case. 

I think it won't need objectFit now that I think about it because it can guarantee `blurWidth` and `blurHeight`.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-259-images-with-fill-and-blurdataurl-props | Change |
| - | - | - | - |
| buildDuration | 34.9s | 34.6s | -334ms |
| buildDurationCached | 9.8s | 9.5s | -284ms |
| nodeModulesSize | 95 MB | 95 MB | ✓ |
| nextStartRea..uration (ms) | 275ms | 276ms | ⚠️ +1ms |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-259-images-with-fill-and-blurdataurl-props | Change |
| - | - | - | - |
| 152-HASH.js gzip | 64.5 kB | 64.5 kB | ✓ |
| 53.HASH.js gzip | 182 B | 182 B | ✓ |
| main-app-HASH.js gzip | 205 B | 205 B | ✓ |
| main-HASH.js gzip | 79.2 kB | 79.2 kB | ✓ |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 146 kB | 146 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-259-images-with-fill-and-blurdataurl-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-259-images-with-fill-and-blurdataurl-props | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 192 B | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 484 B | 484 B | ✓ |
| css-HASH.js gzip | 804 B | 804 B | ✓ |
| dynamic-HASH.js gzip | 2.29 kB | 2.29 kB | ✓ |
| edge-ssr-HASH.js gzip | 255 B | 255 B | ✓ |
| head-HASH.js gzip | 827 B | 827 B | ✓ |
| hooks-HASH.js gzip | 848 B | 848 B | ✓ |
| image-HASH.js gzip | 4.3 kB | 4.3 kB | ✓ |
| index-HASH.js gzip | 252 B | 252 B | ✓ |
| link-HASH.js gzip | 2.69 kB | 2.69 kB | ✓ |
| routerDirect..HASH.js gzip | 782 B | 782 B | ✓ |
| script-HASH.js gzip | 857 B | 857 B | ✓ |
| withRouter-HASH.js gzip | 781 B | 781 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.6 kB | 15.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-259-images-with-fill-and-blurdataurl-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 481 B | ✓ |
| Overall change | 481 B | 481 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-259-images-with-fill-and-blurdataurl-props | Change |
| - | - | - | - |
| index.html gzip | 490 B | 490 B | ✓ |
| link.html gzip | 505 B | 505 B | ✓ |
| withRouter.html gzip | 485 B | 485 B | ✓ |
| Overall change | 1.48 kB | 1.48 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-259-images-with-fill-and-blurdataurl-props | Change |
| - | - | - | - |
| edge-ssr.js gzip | 110 kB | 110 kB | ✓ |
| page.js gzip | 98.4 kB | 98.4 kB | ✓ |
| Overall change | 209 kB | 209 kB | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-259-images-with-fill-and-blurdataurl-props | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 585 B | 585 B | ✓ |
| middleware-r..fest.js gzip | 145 B | 145 B | ✓ |
| middleware.js gzip | 27 kB | 27 kB | ✓ |
| edge-runtime..pack.js gzip | 1.83 kB | 1.83 kB | ✓ |
| Overall change | 29.6 kB | 29.6 kB | ✓ |

</details>

</details>
Commit: c5c1e2b4fda58868244739a46bb37ed98b4c9fd7

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 466635197e53b4ebdc8ead1822ade5e386685f37

`pnpm testheadless test/integration/next-image-new/default/test/static.test.ts` 
- Static Image Component Tests > dev mode > should add placeholder with blurDataURL and fill
- Static Image Component Tests > production mode > should add placeholder with blurDataURL and fill

<details>
<summary>Expand output</summary>

  ● Static Image Component Tests › production mode › should add placeholder with blurDataURL and fill

    expect(received).toBe(expected) // Object.is equality

    Expected: "position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg'%3E%3Cimage style='filter:blur(20px)' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNM/s/wBwAFjwJgf8HDLgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E\")"
    Received: "position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg'%3E%3Cimage style='filter:blur(20px)' preserveAspectRatio='none' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNM/s/wBwAFjwJgf8HDLgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E\")"

      132 |   it('should add placeholder with blurDataURL and fill', async () => {
      133 |     const style = $('#blurdataurl-fill').attr('style')
    > 134 |     expect(style).toBe(
          |                   ^
      135 |       `position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg'%3E%3Cimage style='filter:blur(20px)' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNM/s/wBwAFjwJgf8HDLgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E")`
      136 |     )
      137 |   })

      at Object.<anonymous> (integration/next-image-new/default/test/static.test.ts:134:19)

  ● Static Image Component Tests › dev mode › should add placeholder with blurDataURL and fill

    expect(received).toBe(expected) // Object.is equality

    Expected: "position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg'%3E%3Cimage style='filter:blur(20px)' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNM/s/wBwAFjwJgf8HDLgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E\")"
    Received: "position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg'%3E%3Cimage style='filter:blur(20px)' preserveAspectRatio='none' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNM/s/wBwAFjwJgf8HDLgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E\")"

      132 |   it('should add placeholder with blurDataURL and fill', async () => {
      133 |     const style = $('#blurdataurl-fill').attr('style')
    > 134 |     expect(style).toBe(
          |                   ^
      135 |       `position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg'%3E%3Cimage style='filter:blur(20px)' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNM/s/wBwAFjwJgf8HDLgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E")`
      136 |     )
      137 |   })

      at Object.<anonymous> (integration/next-image-new/default/test/static.test.ts:134:19)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by jankaifer — DISMISSED** [review]
LGTM

**Review by shuding — DISMISSED** [review]
Looks good!

**Review by shuding — APPROVED** [review]

**Comment by topaxi** [comment]
Thank you for this fix! 🥳 ❤️

**Comment by Ojay** [comment]
Is there any way to get this into V12 `next/future/image` at all?? Thanks!

**Comment by styfle** [comment]
@Ojay We don't patch old majors unless there is a security vulnerability.

That being said, upgrading from 12 to 13 should be as easy as running a few codemods.

https://nextjs.org/docs/upgrading
