### PR TITLE
fix(create-next-app): add default version

### LINKED ISSUE #32713: `yarn create next-app` fails when directory is a workspace
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next export

### Describe the Bug

With the following project structure:

```
.
├── node_modules
├── package.json
├── sites # this is a workspace
└── yarn.lock
```

And with the following `package.json`:
```json
{
  "name": "workspace-test",
  "version": "1.0.0",
  "private": true,
  "license": "MIT",
  "workspaces": [
    "sites/*"
  ]
}
```

Running this command fails:
```bash
yarn create next-app sites/hello-world
```

With this following output:
```
yarn create v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-next-app@12.0.7" with binaries:
      - create-next-app
[##] 2/2Creating a new Next.js app in /Users/karbi/dev/workspace-test/sites/hello-world.

Using yarn.

Installing dependencies:
- react
- react-dom
- next

yarn add v1.22.17
warning Missing version in workspace at "/Users/karbi/dev/workspace-test/sites/asd", ignoring.
warning Missing version in workspace at "/Users/karbi/dev/workspace-test/sites/hello-world", ignoring.
error An unexpected error occurred: "Cannot read properties of undefined (reading 'manifest')".
info If you think this is a bug, please open a bug report with the information provided in "/Users/karbi/dev/workspace-test/sites/hello-world/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Expected Behavior

I would expect that following command would produce a successful boilerplate without error:
```bash
yarn create next-app sites/hello-world
```

Additionally, running the following command works successfully when not targeting a workspace:
```bash
yarn create next-app hello-world
```

To note, using `npx` works successfully:
```bash
npx create-next-app sites/hello-world
```

### To Reproduce

Clone [this repository](https://github.com/karbica/workspace-test) and run the following command in the project root:
```bash
yarn create next-app sites/hello-world
```
Screen Shot 2021-12-21 at 1 20 09 PM

### PR DESCRIPTION
**Pull request by balazsorban44**
Fixes #32713

`version` was removed in https://github.com/vercel/next.js/pull/30357/commits/6daadcb5b81eaf63dc4275ab80df3988cb7423c0 "to be consistent" with the examples (#27121), but in my opinion, creating an app with the CLI has nothing to do with our examples.

This is seemingly related to a bug in Yarn v1 (fixed in v2, probably won't be in v1). More context here: https://github.com/vercel/next.js/issues/32713#issuecomment-1000945764

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| buildDuration | 16s | 15.9s | -30ms |
| buildDurationCached | 3.6s | 3.6s | -6ms |
| nodeModulesSize | 348 MB | 348 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.282 | 3.312 | ⚠️ +0.03 |
| / avg req/sec | 761.72 | 754.92 | ⚠️ -6.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.495 | 1.494 | 0 |
| /error-in-render avg req/sec | 1672.73 | 1673.69 | +0.96 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.1 kB | 27.1 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 70.9 kB | 70.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.74 kB | 4.74 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.13 kB | 2.13 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| buildDuration | 17.8s | 17.7s | -61ms |
| buildDurationCached | 3.6s | 3.5s | -132ms |
| nodeModulesSize | 348 MB | 348 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.321 | 3.282 | -0.04 |
| / avg req/sec | 752.69 | 761.64 | +8.95 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.521 | 1.521 | ✓ |
| /error-in-render avg req/sec | 1643.81 | 1644.16 | +0.35 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.1 kB | 71.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 906 B | 906 B | ✓ |
| image-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/cna-in-yarn-workspace | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 6742e3e23ef07a8e87b451f63cde70a9a580dc87

File: packages/create-next-app/create-app.ts [hunk 1]
```diff
@@ -203,6 +203,7 @@ export async function createApp({
      */
     const packageJson = {
       name: appName,
+      version: '0.1.0',
```
Comment (kachkaev) [inline packages/create-next-app/create-app.ts:206]: How about `0.0.0-dev` or something else that does not look like a releaseable version? If a bug only exists in old Yarn versions, what about adding this line only in some cases?

**Review by ijjk — APPROVED** [review]
