### PR TITLE
Check if esmodules is supported before enabling useESModules

### LINKED ISSUE #6273: 8.0.0 - babel not compiling properly
I am getting the following issue which I presume is related to babel.

```
node_modules/@babel/runtime-corejs2/helpers/esm/asyncToGenerator.js:1
(function (exports, require, module, __filename, __dirname) { import _Promise from "../../core-js/promise";

SyntaxError: Unexpected token import
```
It seems that `@babel/runtime-corejs2/helpers/esm` is being used instead of just`@babel/runtime-corejs2/helpers` where the compiled files seem to be.

I didn't notice this in `dev` with the following config

```
"presets": [
   ["next/babel", {"preset-env": {
      "modules": "commonjs"
    }}]
 ],
```

The issue is when I try and run the production build. Here is the relevant config

```
{
  "env": {
    "production": {
      "presets": [
        ["next/babel", {
          "preset-env": {
            "targets": {
              "browsers": ["> 1%"]
            }
          }
        }]
      ],
      "plugins": [
        [ "babel-plugin-styled-components", { "displayName": false } ],
        "transform-react-constant-elements",
        "@babel/plugin-transform-react-inline-elements"
      ]
    },
  },
  "plugins": [
    [
      "transform-imports",
      {
        "lodash": {
          "transform": "lodash/${member}",
          "preventFullImport": true
        },
        "validator": {
          "transform": "validator/lib/${member}",
          "preventFullImport": true
        },
        "recompose": {
          "transform": "recompose/${member}",
          "preventFullImport": true
        },
      }
    ], 
    "date-fns",
    "transform-modern-regexp",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-optional-catch-binding",
    [ 
      "module-resolver", { 
        "root": [ "./src" ]
      } 
    ],
    [
      "inline-import", {
        "extensions": [ ".css" ]
      }
    ]
  ]
}

```

### PR DESCRIPTION
**Pull request by timneutkens**
Fixes #6273

This checks if esmodules is supported using the same detection login that @babel/preset-env uses. babel-loader sets the esmodule support flag automatically. This way it will still work with jest etc, but this will allow compilation using the `babel` cli etc that uses next/babel to work.

### CODE REVIEW

File: packages/next/build/babel/preset.ts [hunk 1]
```diff
@@ -47,11 +47,18 @@ type BabelPreset = {
...
 
-module.exports = (context: any, options: NextBabelPresetOptions = {}): BabelPreset => {
+// Taken from https://github.com/babel/babel/commit/d60c5e1736543a6eac4b549553e107a9ba967051#diff-b4beead8ad9195361b4537601cc22532R158
+function supportsStaticESM(caller: any) {
+  return !!(caller && caller.supportsStaticESM);
+}
+
+module.exports = (api: any, options: NextBabelPresetOptions = {}): BabelPreset => {
+  const supportsESM = api.caller(supportsStaticESM)
+  console.log({supportsESM})
```
Comment (Timer) [inline packages/next/build/babel/preset.ts]:
```suggestion
```

**Review by Timer — APPROVED** [review]

File: packages/next/build/babel/preset.ts [hunk 2]
```diff
@@ -74,7 +80,7 @@ module.exports = (context: any, options: NextBabelPresetOptions = {}): BabelPres
         corejs: 2,
         helpers: true,
         regenerator: true,
-        useESModules: !isTest && presetEnvConfig.modules !== 'commonjs',
+        useESModules: supportsESM && presetEnvConfig.modules !== 'commonjs',
```
Comment (loganfsmyth) [inline packages/next/build/babel/preset.ts]: Would it be worth exposing an option to disable this check for users? Since people could still manually enable the commonjs plugin directly, this `presetEnvConfig.modules !== 'commonjs'` check isn't guaranteed to catch all cases where CommonJS is used.

Comment (timneutkens) [reply packages/next/build/babel/preset.ts]: Users can already override the options because of `...options['transform-runtime']`

Comment (loganfsmyth) [reply packages/next/build/babel/preset.ts]: Ahhh good call.
