### PR TITLE
Fix sendGAEvent function (for real?)

### LINKED ISSUE #61703: @nextjs/third-party/google Custom Events Don't Register When Using `sendGAEvent()`
### Link to the code that reproduces this issue

https://github.com/AbdelrahmanSadat/ga-issue

### To Reproduce

1. Use `<GoogleAnalytics>` component in the app's layout.
2. Use `sendGAEvent({event: "custom_event", value: 'value'})` on any client component.
3. Add the `custom_event` in [GA](https://support.google.com/analytics/answer/14239696?sjid=1720473978381836552-EU#zippy=%2Canalyze-the-custom-dimension-in-a-report%2Canalyze-the-custom-dimension-in-an-exploration%2Cbuild-an-audience-using-the-dimension)
4. Check Google Analytics [realtime](https://support.google.com/analytics/answer/9271392) dashboard. No event is reported.

### Current vs. Expected behavior

Expected the `custom_event` to be reported in GA.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Script optimization (next/script)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Not really sure how I can provide a reproduction for this since it would also require access to a Google Analytics dashboard. But long story short, I tried `@nextjs/third-parties/google` instead of using a `<Script>`, and while that part works and normal events fire, manually firing custom events (or predefined events) using the library's `SendGAEvent()` doesn't register on the dashboard.

I removed any use of `SendGAEvent()` and instead used `(window as any).gtag("event", "custome_event", {value: "value"})`, and my custom_event was firing and showing on the dashboard, so that rules out any issue in my GA setup.

### PR DESCRIPTION
**Pull request by asobirov**
The recently merged PR - https://github.com/vercel/next.js/pull/62065, doesn't seem to fix the issue. As per the comment this seems to be related to `dataLayer` that does not like working with Arrays, but works with [arguments object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments). Also, when using window.gtag(...) an Arguments() is pushed instead of Array().

Fixes #61703

### CODE REVIEW

File: packages/third-parties/src/google/ga.tsx [hunk 1]
```diff
@@ -54,14 +54,14 @@ export function GoogleAnalytics(props: GAParams) {
   )
 }
 
-export const sendGAEvent = (...args: Object[]) => {
+export function sendGAEvent(..._args: Object[]) {
```
Comment (asobirov) [inline packages/third-parties/src/google/ga.tsx:57]: Converted to a `function` so that `arguments` would be available. 

Wasn't entirely sure of any other way to turn the `args` into `Arguments()` instead of `Array()`, so I just prefixed it with `_` to have the types at least. Not sure though.

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 995f0155e38095e3007ebf727856f6aecc2258f8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by ijjk — APPROVED** [review]
Looking at [the gtag docs](https://developers.google.com/tag-platform/gtagjs/configure) it does seem to not handle Array values specifically so using arguments seems good to me

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | asobirov/next.js fix-issue-61703 | Change |
| - | - | - | - |
| buildDuration | 20.1s | 19.8s | N/A |
| buildDurationCached | 8.5s | 6.9s | N/A |
| nodeModulesSize | 196 MB | 196 MB | ✓ |
| nextStartRea..uration (ms) | 428ms | 417ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | asobirov/next.js fix-issue-61703 | Change |
| - | - | - | - |
| 1068-HASH.js gzip | 30.3 kB | 30.3 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.5 kB | 53.5 kB | N/A |
| 4944-HASH.js gzip | 5.04 kB | 5.03 kB | N/A |
| 8423.HASH.js gzip | 181 B | 181 B | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 242 B | N/A |
| main-HASH.js gzip | 32.1 kB | 32.1 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 47.1 kB | 47.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | asobirov/next.js fix-issue-61703 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | asobirov/next.js fix-issue-61703 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 196 B | ✓ |
| _error-HASH.js gzip | 184 B | 183 B | N/A |
| amp-HASH.js gzip | 503 B | 504 B | N/A |
| css-HASH.js gzip | 323 B | 324 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.51 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 353 B | 351 B | N/A |
| hooks-HASH.js gzip | 370 B | 370 B | ✓ |
| image-HASH.js gzip | 4.21 kB | 4.2 kB | N/A |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.68 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 313 B | 314 B | N/A |
| script-HASH.js gzip | 386 B | 385 B | N/A |
| withRouter-HASH.js gzip | 309 B | 311 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 931 B | 931 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | asobirov/next.js fix-issue-61703 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | asobirov/next.js fix-issue-61703 | Change |
| - | - | - | - |
| index.html gzip | 528 B | 528 B | ✓ |
| link.html gzip | 540 B | 541 B | N/A |
| withRouter.html gzip | 524 B | 523 B | N/A |
| Overall change | 528 B | 528 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | asobirov/next.js fix-issue-61703 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94.5 kB | 94.5 kB | N/A |
| page.js gzip | 151 kB | 151 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | asobirov/next.js fix-issue-61703 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 626 B | 625 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 44.6 kB | 44.6 kB | N/A |
| edge-runtime..pack.js gzip | 1.94 kB | 1.94 kB | ✓ |
| Overall change | 2.1 kB | 2.1 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | asobirov/next.js fix-issue-61703 | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 166 kB | 166 kB | ✓ |
| app-page-exp..prod.js gzip | 95.9 kB | 95.9 kB | ✓ |
| app-page-tur..prod.js gzip | 97.6 kB | 97.6 kB | ✓ |
| app-page-tur..prod.js gzip | 92 kB | 92 kB | ✓ |
| app-page.run...dev.js gzip | 136 kB | 136 kB | ✓ |
| app-page.run..prod.js gzip | 90.6 kB | 90.6 kB | ✓ |
| app-route-ex...dev.js gzip | 22 kB | 22 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.47 kB | 9.47 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.74 kB | 9.74 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.47 kB | 9.47 kB | ✓ |
| pages-turbo...prod.js gzip | 22.1 kB | 22.1 kB | ✓ |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | ✓ |
| pages.runtim..prod.js gzip | 22.1 kB | 22.1 kB | ✓ |
| server.runti..prod.js gzip | 50.1 kB | 50.1 kB | ✓ |
| Overall change | 927 kB | 927 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | asobirov/next.js fix-issue-61703 | Change |
| - | - | - | - |
| 0.pack gzip | 1.55 MB | 1.55 MB | N/A |
| index.pack gzip | 103 kB | 104 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

</details>
Commit: 995f0155e38095e3007ebf727856f6aecc2258f8

**Comment by felix-mittermeier** [comment]
Hi guys, can you confirm that this really solves the issue? I built my app using the 14.1.1-canary.61 version but the events still don't show up in Google Analytics. Also not in the real time view.
