### PR TITLE
Fix #5674 Append crossOrigin on the client side too, add config option for crossOrigin

### LINKED ISSUE #5674: CrossOrigin attribute not added to scripts loaded by PageLoader
# Bug report

## Describe the bug

When I add the `crossOrigin` prop to my `Head` and `NextScript` components, I expect all scripts to have a `crossOrigin` attribute on them. This appears to be the case, except for scripts created by [`PageLoader`](https://github.com/zeit/next.js/blob/0d77dda28c8b0eaed38bb203de737ffc1235d42a/packages/next/lib/page-loader.js#L71).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Add a `crossOrigin` prop to `Head` and `NextScript`
2. View attributes of any script created by the `PageLoader` class.

## Expected behavior

A `crossOrigin` attribute is present on scripts created by `PageLoader`.

## Additional context

This was solved in the [original `crossOrigin` PR](https://github.com/zeit/next.js/pull/5150/files#diff-c7ddf3ad46bcb0938d6043ea0393d554R75), but not in [the one that was merged](https://github.com/zeit/next.js/pull/5646).

### PR DESCRIPTION
**Pull request by dav-is**
# Fixes https://github.com/zeit/next.js/issues/5674

This adds config option
```js
// next.config.js
module.exports = {
  crossOrigin: 'anonymous'
}
```
This config option is defined in the webpack Define Plugin at build.
`Head` and `NextScript` now use the config option, if it's not explicitly set on the element.
This value is now passed to Webpack so it can add it to scripts that it loads.
The value is now used in `PageLoader` (on the client) so it can add it to the scripts and links that it loads.
Using `<Head crossOrigin>` or `<NextScript crossOrigin>` is now deprecated.

### CODE REVIEW

File: packages/next-server/server/next-server.ts [hunk 1]
```diff
@@ -38,6 +38,7 @@ export default class Server {
     buildId: string,
     generateEtags: boolean,
     runtimeConfig?: {[key: string]: any},
+    crossOrigin?: string,
```
Comment (timneutkens) [inline packages/next-server/server/next-server.ts]: Instead of passing it all the way through the app (and increasing html size) let's instead use `webpack.DefinePlugin` to inline the value, this also makes the changes needed less code and more reliable in the future 😌

Comment (dav-is) [reply packages/next-server/server/next-server.ts]: Very true... didn't think about that :+1:

File: packages/next/pages/_document.js [hunk 2]
```diff
@@ -117,14 +117,15 @@ export class Head extends Component {
         }
         return child
       })
+      if (this.props.crossOrigin) console.warn('<Head crossOrigin=""> is deprecated, use next.config.js option: crossOrigin')
```
Comment (timneutkens) [inline packages/next/pages/_document.js]: Let's add an err.sh link here. Which basically works like `err.sh/zeit/next.js/head-crossorigin-deprecated` which will be redirected to this repo's `errors/head-crossorigin-deprecated.md` file

File: packages/next-server/server/next-server.ts (hunk 1 above)
Comment (timneutkens) [reply packages/next-server/server/next-server.ts]: Really good way of thinking: Compile time is better than runtime

File: packages/next/pages/_document.js [hunk 3]
```diff
@@ -117,14 +117,15 @@ export class Head extends Component {
         }
         return child
       })
+      if (this.props.crossOrigin) console.warn('Warning: `Head` attribute `crossOrigin` is deprecated. https://err.sh/next.js/doc-crossorigin-deprecated')
```
Comment (timneutkens) [inline packages/next/pages/_document.js]: Below there is a `NODE_ENV` check, let's add it here too 💯

File: packages/next-server/server/next-server.ts (hunk 1 above)
Comment (dav-is) [reply packages/next-server/server/next-server.ts]: I was just worried about breaking dynamic asset paths as if someone might be able to change crossOrigin on demand but I don't think there's really a case for it.

File: packages/next/pages/_document.js (hunk 3 above)
Comment (dav-is) [reply packages/next/pages/_document.js]: It's in one :smile:

File: packages/next-server/server/next-server.ts (hunk 1 above)
Comment (timneutkens) [reply packages/next-server/server/next-server.ts]: Yeah agreed, basically keeping this issue in mind: https://github.com/zeit/next.js/issues/5846

File: packages/next/pages/_document.js (hunk 3 above)
Comment (timneutkens) [reply packages/next/pages/_document.js]: Oh, doh 🤦‍♂️ the diff only showed part of the code lol

**Review by timneutkens — APPROVED** [review]
💯 perfect PR

**Comment by timneutkens** [comment]
Will ship to canary in the morning 👍
