### PR TITLE
Alias nextjs api entry to esm version for app router

### LINKED ISSUE #54777: next/image not working when using in esm projects
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.17.1
      npm: 9.6.7
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.12
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/yanush/nextjs_issue_20230830

### To Reproduce

- Create a new nextjs app:
`npx create-next-app@latest`

Using the following options: 
- TypeScript: No
- EsLint: Yes
- Tailwind CSS: No
- src/ directory: No
- App Router: Yes
- import Alias: No

- Edit package.json and add:
`"type": "module",`

Edit next.config.js file to match esm:
```
/** @type {import('next').NextConfig} */
const nextConfig = {}

export default nextConfig;
```

- try to run project using npm run dev

### Describe the Bug

I get these errors:
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check your code at page.js:19.
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

The errors referring to lines that contain _Image_ Tags

Notice:

- Using the legacy Image works fine (Changing page.js import to: `import Image from 'next/legacy/image'`)

- Changing the project to commonjs also seems to solve the issue

Both of these fixes are not ideal for me

### Expected Behavior

Should be working fine with the new image and don't throw errors

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

<sub>[NEXT-1774](https://linear.app/vercel/issue/NEXT-1774/nextimage-not-working-when-using-in-esm-projects)</sub>

### PR DESCRIPTION
**Pull request by huozhi**
## What

When users specify `"type": "module"` in Next.js app, especially with `create-next-app`, `Image` component is not working. An error `Unsupported Server Component type: {...}` is thrown.

## Why

`next/image` API is mixing with a client component as default export and a named export as server component. But the entry file of the API is still CJS file, which will import the module as the object. So you'll get `{ default, unstable_getImageProps }` when you do `import Image from 'next/image'` instead of `Image` component itself, where the CJS module load all the exports as an object. This is expected behavior for ESM but breaks the usage.

It only errors when you're using js extensions, if you're using typescript, it still works. If you're using turbopack, it works in dev mode.

This is also because webpack can't analyze the exports from CJS module of that `next/image` entry file. Usually we can assign the default export to the module itself, then attach other named exports onto it, so the default export equals the `module.exports` itself. But for `next/image` since the default export is an client component, doing that will error with React as you cannot modify the react client reference.
Turbopack doesn't use the same way to analyze the default export, so it doesn't have this problem.

## How

We create few ESM version of entry files of nextjs APIs, then pick up them to let app router for bundling, instead of using the `next/<api name>.js` CJS files. Those ESM entries still point to the `next/dist/..` CJS files. In this way webpack and directly gets the exports from the `next/dist/...` files and be aware of the module exports. No more CJS module wrapping the ESM module, the default and named exports can preserve correctly.

Fixes #54777
Closes NEXT-1774
Closes NEXT-1879
Closes NEXT-1923

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: fb669e9418904c9946f3de6660f3df239e19897e

`pnpm test-dev test/e2e/app-dir/app-edge/app-edge.test.ts` 
- app-dir edge SSR > should handle edge only routes
- app-dir edge SSR > should retrieve cookies in a server component in the edge runtime
- app-dir edge SSR > should resolve client component without error

<details>
<summary>Expand output</summary>

  ● app-dir edge SSR › should handle edge only routes

    expect(received).toContain(expected) // indexOf

    Expected substring: "<p>Edge!</p>"
    Received string:    "<!DOCTYPE html><html id=\"__next_error__\"><head><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/><link rel=\"preload\" as=\"script\" fetchPriority=\"low\" href=\"/_next/static/chunks/webpack.js\"/><script src=\"/_next/static/chunks/main-app.js\" async=\"\"></script><script src=\"/_next/static/chunks/app-pages-internals.js\" async=\"\"></script><meta name=\"robots\" content=\"noindex\"/><meta name=\"next-error\" content=\"not-found\"/><script src=\"/_next/static/chunks/polyfills.js\" noModule=\"\"></script></head><body><script src=\"/_next/static/chunks/webpack.js\" async=\"\"></script><script>(self.__next_f=self.__next_f||[]).push([0]);self.__next_f.push([2,null])</script><script>self.__next_f.push([1,\"0:\\\"$L1\\\"\\n\"])</script><script>self.__next_f.push([1,\"2:I[\\\"(app-pages-browser)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/client/components/app-router.js\\\",[\\\"app-pages-internals\\\",\\\"static/chunks/app-pages-internals.js\\\"],\\\"\\\"]\\n4:I[\\\"(app-pages-browser)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/client/components/layout-router.\"])</script><script>self.__next_f.push([1,\"js\\\",[\\\"app-pages-internals\\\",\\\"static/chunks/app-pages-internals.js\\\"],\\\"\\\"]\\n5:I[\\\"(app-pages-browser)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/client/components/render-from-template-context.js\\\",[\\\"app-pages-internals\\\",\\\"static/chunks/app-pages-internals.js\\\"],\\\"\\\"]\\n6:I[\\\"(app-pages-browser)/./app/edge/layout.tsx\\\",[\\\"app/edge/layout\\\",\\\"static/chunks/app/edge/layout.js\\\"],\\\"\\\"]\\n8:I[\\\"(app-pages-browser)/.\"])</script><script>self.__next_f.push([1,\"/node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/client/components/error-boundary.js\\\",[\\\"app-pages-internals\\\",\\\"static/chunks/app-pages-internals.js\\\"],\\\"\\\"]\\n\"])</script><script>self.__next_f.push([1,\"1:[null,[\\\"$\\\",\\\"$L2\\\",null,{\\\"buildId\\\":\\\"development\\\",\\\"assetPrefix\\\":\\\"\\\",\\\"initialCanonicalUrl\\\":\\\"/edge/basic\\\",\\\"initialTree\\\":[\\\"\\\",{\\\"children\\\":[\\\"edge\\\",{\\\"children\\\":[\\\"basic\\\",{\\\"children\\\":[\\\"__PAGE__\\\",{}]}]}]},\\\"$undefined\\\",\\\"$undefined\\\",true],\\\"initialSeedData\\\":[\\\"\\\",{\\\"children\\\":[\\\"edge\\\",{\\\"children\\\":[\\\"basic\\\",{\\\"children\\\":[\\\"__PAGE__\\\",{},[\\\"$L3\\\",[\\\"$\\\",\\\"p\\\",null,{\\\"children\\\":\\\"Edge!\\\"}],null]]},[\\\"$\\\",\\\"$L4\\\",null,{\\\"parallelRouterKey\\\":\\\"children\\\",\\\"segmentPath\\\":[\\\"children\\\",\\\"edge\\\",\\\"children\\\",\\\"basic\\\",\\\"children\\\"],\\\"loading\\\":\\\"$undefined\\\",\\\"loadingStyles\\\":\\\"$undefined\\\",\\\"loadingScripts\\\":\\\"$undefined\\\",\\\"hasLoading\\\":false,\\\"error\\\":\\\"$undefined\\\",\\\"errorStyles\\\":\\\"$undefined\\\",\\\"errorScripts\\\":\\\"$undefined\\\",\\\"template\\\":[\\\"$\\\",\\\"$L5\\\",null,{}],\\\"templateStyles\\\":\\\"$undefined\\\",\\\"templateScripts\\\":\\\"$undefined\\\",\\\"notFound\\\":\\\"$undefined\\\",\\\"notFoundStyles\\\":\\\"$undefined\\\",\\\"styles\\\":null}]]},[null,[\\\"$\\\",\\\"$L6\\\",null,{\\\"children\\\":[\\\"$\\\",\\\"$L4\\\",null,{\\\"parallelRouterKey\\\":\\\"children\\\",\\\"segmentPath\\\":[\\\"children\\\",\\\"edge\\\",\\\"children\\\"],\\\"loading\\\":\\\"$undefined\\\",\\\"loadingStyles\\\":\\\"$undefined\\\",\\\"loadingScripts\\\":\\\"$undefined\\\",\\\"hasLoading\\\":false,\\\"error\\\":\\\"$undefined\\\",\\\"errorStyles\\\":\\\"$undefined\\\",\\\"errorScripts\\\":\\\"$undefined\\\",\\\"template\\\":[\\\"$\\\",\\\"$L5\\\",null,{}],\\\"templateStyles\\\":\\\"$undefined\\\",\\\"templateScripts\\\":\\\"$undefined\\\",\\\"notFound\\\":\\\"$undefined\\\",\\\"notFoundStyles\\\":\\\"$undefined\\\",\\\"styles\\\":null}],\\\"params\\\":{}}],null]]},[null,[\\\"$\\\",\\\"html\\\",null,{\\\"children\\\":[[\\\"$\\\",\\\"head\\\",null,{}],[\\\"$\\\",\\\"body\\\",null,{\\\"children\\\":[\\\"$\\\",\\\"$L4\\\",null,{\\\"parallelRouterKey\\\":\\\"children\\\",\\\"segmentPath\\\":[\\\"children\\\"],\\\"loading\\\":\\\"$undefined\\\",\\\"loadingStyles\\\":\\\"$undefined\\\",\\\"loadingScripts\\\":\\\"$undefined\\\",\\\"hasLoading\\\":false,\\\"error\\\":\\\"$undefined\\\",\\\"errorStyles\\\":\\\"$undefined\\\",\\\"errorScripts\\\":\\\"$undefined\\\",\\\"template\\\":[\\\"$\\\",\\\"$L5\\\",null,{}],\\\"templateStyles\\\":\\\"$undefined\\\",\\\"templateScripts\\\":\\\"$undefined\\\",\\\"notFound\\\":[[\\\"$\\\",\\\"title\\\",null,{\\\"children\\\":\\\"404: This page could not be found.\\\"}],[\\\"$\\\",\\\"div\\\",null,{\\\"style\\\":{\\\"fontFamily\\\":\\\"system-ui,\\\\\\\"Segoe UI\\\\\\\",Roboto,Helvetica,Arial,sans-serif,\\\\\\\"Apple Color Emoji\\\\\\\",\\\\\\\"Segoe UI Emoji\\\\\\\"\\\",\\\"height\\\":\\\"100vh\\\",\\\"textAlign\\\":\\\"center\\\",\\\"display\\\":\\\"flex\\\",\\\"flexDirection\\\":\\\"column\\\",\\\"alignItems\\\":\\\"center\\\",\\\"justifyContent\\\":\\\"center\\\"},\\\"children\\\":[\\\"$\\\",\\\"div\\\",null,{\\\"children\\\":[[\\\"$\\\",\\\"style\\\",null,{\\\"dangerouslySetInnerHTML\\\":{\\\"__html\\\":\\\"body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}\\\"}}],[\\\"$\\\",\\\"h1\\\",null,{\\\"className\\\":\\\"next-error-h1\\\",\\\"style\\\":{\\\"display\\\":\\\"inline-block\\\",\\\"margin\\\":\\\"0 20px 0 0\\\",\\\"padding\\\":\\\"0 23px 0 0\\\",\\\"fontSize\\\":24,\\\"fontWeight\\\":500,\\\"verticalAlign\\\":\\\"top\\\",\\\"lineHeight\\\":\\\"49px\\\"},\\\"children\\\":\\\"404\\\"}],[\\\"$\\\",\\\"div\\\",null,{\\\"style\\\":{\\\"display\\\":\\\"inline-block\\\"},\\\"children\\\":[\\\"$\\\",\\\"h2\\\",null,{\\\"style\\\":{\\\"fontSize\\\":14,\\\"fontWeight\\\":400,\\\"lineHeight\\\":\\\"49px\\\",\\\"margin\\\":0},\\\"children\\\":\\\"This page could not be found.\\\"}]}]]}]}]],\\\"notFoundStyles\\\":[],\\\"styles\\\":null}]}]]}],null]],\\\"initialHead\\\":[false,\\\"$L7\\\"],\\\"globalErrorComponent\\\":\\\"$8\\\"}]]\\n\"])</script><script>self.__next_f.push([1,\"7:[[\\\"$\\\",\\\"meta\\\",\\\"0\\\",{\\\"name\\\":\\\"viewport\\\",\\\"content\\\":\\\"width=device-width, initial-scale=1\\\"}],[\\\"$\\\",\\\"meta\\\",\\\"1\\\",{\\\"charSet\\\":\\\"utf-8\\\"}]]\\n3:null\\n\"])</script><script>self.__next_f.push([1,\"\"])</script></body></html>"

      11 |     it('should handle edge only routes', async () => {
      12 |       const appHtml = await next.render('/edge/basic')
    > 13 |       expect(appHtml).toContain('<p>Edge!</p>')
         |                       ^
      14 |
      15 |       const pageHtml = await next.render('/pages-edge')
      16 |       expect(pageHtml).toContain('<p>pages-edge-ssr</p>')

      at Object.toContain (e2e/app-dir/app-edge/app-edge.test.ts:13:23)

  ● app-dir edge SSR › should retrieve cookies in a server component in the edge runtime

    expect(received).toInclude(expected)

    Expected string to include:
      "Hello"
    Received:
      "<!DOCTYPE html><html id=\"__next_error__\"><head><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/><link rel=\"preload\" as=\"script\" fetchPriority=\"low\" href=\"/_next/static/chunks/webpack.js\"/><script src=\"/_next/static/chunks/main-app.js\" async=\"\"></script><script src=\"/_next/static/chunks/app-pages-internals.js\" async=\"\"></script><meta name=\"robots\" content=\"noindex\"/><meta name=\"next-error\" content=\"not-found\"/><script src=\"/_next/static/chunks/polyfills.js\" noModule=\"\"></script></head><body><script src=\"/_next/static/chunks/webpack.js\" async=\"\"></script><script>(self.__next_f=self.__next_f||[]).push([0]);self.__next_f.push([2,null])</script><script>self.__next_f.push([1,\"0:\\\"$L1\\\"\\n\"])</script><script>self.__next_f.push([1,\"2:I[\\\"(app-pages-browser)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/client/components/app-router.js\\\",[\\\"app-pages-internals\\\",\\\"static/chunks/app-pages-internals.js\\\"],\\\"\\\"]\\n5:I[\\\"(app-pages-browser)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/client/components/layout-router.\"])</script><script>self.__next_f.push([1,\"js\\\",[\\\"app-pages-internals\\\",\\\"static/chunks/app-pages-internals.js\\\"],\\\"\\\"]\\n6:I[\\\"(app-pages-browser)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/client/components/render-from-template-context.js\\\",[\\\"app-pages-internals\\\",\\\"static/chunks/app-pages-internals.js\\\"],\\\"\\\"]\\n8:I[\\\"(app-pages-browser)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+pack\"])</script><script>self.__next_f.push([1,\"ages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/client/components/error-boundary.js\\\",[\\\"app-pages-internals\\\",\\\"static/chunks/app-pages-internals.js\\\"],\\\"\\\"]\\n\"])</script><script>self.__next_f.push([1,\"1:[null,[\\\"$\\\",\\\"$L2\\\",null,{\\\"buildId\\\":\\\"development\\\",\\\"assetPrefix\\\":\\\"\\\",\\\"initialCanonicalUrl\\\":\\\"/edge-apis/cookies\\\",\\\"initialTree\\\":[\\\"\\\",{\\\"children\\\":[\\\"edge-apis\\\",{\\\"children\\\":[\\\"cookies\\\",{\\\"children\\\":[\\\"__PAGE__\\\",{}]}]}]},\\\"$undefined\\\",\\\"$undefined\\\",true],\\\"initialSeedData\\\":[\\\"\\\",{\\\"children\\\":[\\\"edge-apis\\\",{\\\"children\\\":[\\\"cookies\\\",{\\\"children\\\":[\\\"__PAGE__\\\",{},[\\\"$L3\\\",\\\"$L4\\\",null]]},[\\\"$\\\",\\\"$L5\\\",null,{\\\"parallelRouterKey\\\":\\\"children\\\",\\\"segmentPath\\\":[\\\"children\\\",\\\"edge-apis\\\",\\\"children\\\",\\\"cookies\\\",\\\"children\\\"],\\\"loading\\\":\\\"$undefined\\\",\\\"loadingStyles\\\":\\\"$undefined\\\",\\\"loadingScripts\\\":\\\"$undefined\\\",\\\"hasLoading\\\":false,\\\"error\\\":\\\"$undefined\\\",\\\"errorStyles\\\":\\\"$undefined\\\",\\\"errorScripts\\\":\\\"$undefined\\\",\\\"template\\\":[\\\"$\\\",\\\"$L6\\\",null,{}],\\\"templateStyles\\\":\\\"$undefined\\\",\\\"templateScripts\\\":\\\"$undefined\\\",\\\"notFound\\\":\\\"$undefined\\\",\\\"notFoundStyles\\\":\\\"$undefined\\\",\\\"styles\\\":null}]]},[\\\"$\\\",\\\"$L5\\\",null,{\\\"parallelRouterKey\\\":\\\"children\\\",\\\"segmentPath\\\":[\\\"children\\\",\\\"edge-apis\\\",\\\"children\\\"],\\\"loading\\\":\\\"$undefined\\\",\\\"loadingStyles\\\":\\\"$undefined\\\",\\\"loadingScripts\\\":\\\"$undefined\\\",\\\"hasLoading\\\":false,\\\"error\\\":\\\"$undefined\\\",\\\"errorStyles\\\":\\\"$undefined\\\",\\\"errorScripts\\\":\\\"$undefined\\\",\\\"template\\\":[\\\"$\\\",\\\"$L6\\\",null,{}],\\\"templateStyles\\\":\\\"$undefined\\\",\\\"templateScripts\\\":\\\"$undefined\\\",\\\"notFound\\\":\\\"$undefined\\\",\\\"notFoundStyles\\\":\\\"$undefined\\\",\\\"styles\\\":null}]]},[null,[\\\"$\\\",\\\"html\\\",null,{\\\"children\\\":[[\\\"$\\\",\\\"head\\\",null,{}],[\\\"$\\\",\\\"body\\\",null,{\\\"children\\\":[\\\"$\\\",\\\"$L5\\\",null,{\\\"parallelRouterKey\\\":\\\"children\\\",\\\"segmentPath\\\":[\\\"children\\\"],\\\"loading\\\":\\\"$undefined\\\",\\\"loadingStyles\\\":\\\"$undefined\\\",\\\"loadingScripts\\\":\\\"$undefined\\\",\\\"hasLoading\\\":false,\\\"error\\\":\\\"$undefined\\\",\\\"errorStyles\\\":\\\"$undefined\\\",\\\"errorScripts\\\":\\\"$undefined\\\",\\\"template\\\":[\\\"$\\\",\\\"$L6\\\",null,{}],\\\"templateStyles\\\":\\\"$undefined\\\",\\\"templateScripts\\\":\\\"$undefined\\\",\\\"notFound\\\":[[\\\"$\\\",\\\"title\\\",null,{\\\"children\\\":\\\"404: This page could not be found.\\\"}],[\\\"$\\\",\\\"div\\\",null,{\\\"style\\\":{\\\"fontFamily\\\":\\\"system-ui,\\\\\\\"Segoe UI\\\\\\\",Roboto,Helvetica,Arial,sans-serif,\\\\\\\"Apple Color Emoji\\\\\\\",\\\\\\\"Segoe UI Emoji\\\\\\\"\\\",\\\"height\\\":\\\"100vh\\\",\\\"textAlign\\\":\\\"center\\\",\\\"display\\\":\\\"flex\\\",\\\"flexDirection\\\":\\\"column\\\",\\\"alignItems\\\":\\\"center\\\",\\\"justifyContent\\\":\\\"center\\\"},\\\"children\\\":[\\\"$\\\",\\\"div\\\",null,{\\\"children\\\":[[\\\"$\\\",\\\"style\\\",null,{\\\"dangerouslySetInnerHTML\\\":{\\\"__html\\\":\\\"body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}\\\"}}],[\\\"$\\\",\\\"h1\\\",null,{\\\"className\\\":\\\"next-error-h1\\\",\\\"style\\\":{\\\"display\\\":\\\"inline-block\\\",\\\"margin\\\":\\\"0 20px 0 0\\\",\\\"padding\\\":\\\"0 23px 0 0\\\",\\\"fontSize\\\":24,\\\"fontWeight\\\":500,\\\"verticalAlign\\\":\\\"top\\\",\\\"lineHeight\\\":\\\"49px\\\"},\\\"children\\\":\\\"404\\\"}],[\\\"$\\\",\\\"div\\\",null,{\\\"style\\\":{\\\"display\\\":\\\"inline-block\\\"},\\\"children\\\":[\\\"$\\\",\\\"h2\\\",null,{\\\"style\\\":{\\\"fontSize\\\":14,\\\"fontWeight\\\":400,\\\"lineHeight\\\":\\\"49px\\\",\\\"margin\\\":0},\\\"children\\\":\\\"This page could not be found.\\\"}]}]]}]}]],\\\"notFoundStyles\\\":[],\\\"styles\\\":null}]}]]}],null]],\\\"initialHead\\\":[false,\\\"$L7\\\"],\\\"globalErrorComponent\\\":\\\"$8\\\"}]]\\n\"])</script><script>self.__next_f.push([1,\"4:E{\\\"digest\\\":\\\"4188676482\\\",\\\"message\\\":\\\"Invariant: cookies() expects to have requestAsyncStorage, none available.\\\",\\\"stack\\\":\\\"Error: Invariant: cookies() expects to have requestAsyncStorage, none available.\\\\n    at cookies (webpack-internal:///(rsc)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/client/components/headers.js:50:15)\\\\n    at Page (webpack-internal:///(rsc)/./app/edge-apis/cookies/page.tsx:12:58)\\\\n    at attemptResolveElement (webpack-internal:///(rsc)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js:1592:30)\\\\n    at resolveModelToJSON (webpack-internal:///(rsc)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js:1961:41)\\\\n    at Array.toJSON (webpack-internal:///(rsc)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js:1423:28)\\\\n    at stringify (\\u003canonymous\\u003e)\\\\n    at emitModelChunk (webpack-internal:///(rsc)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js:2341:24)\\\\n    at retryTask (webpack-internal:///(rsc)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js:2377:17)\\\\n    at performWork (webpack-internal:///(rsc)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js:2420:21)\\\\n    at Timeout.eval [as _onTimeout] (webpack-internal:///(rsc)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/compiled/react-server-dom-webpack-experimental/cjs/react-server-dom-webpack-server.edge.development.js:1692:28)\\\"}\\n\"])</script><script>self.__next_f.push([1,\"7:[[\\\"$\\\",\\\"meta\\\",\\\"0\\\",{\\\"name\\\":\\\"viewport\\\",\\\"content\\\":\\\"width=device-width, initial-scale=1\\\"}],[\\\"$\\\",\\\"meta\\\",\\\"1\\\",{\\\"charSet\\\":\\\"utf-8\\\"}]]\\n3:null\\n\"])</script><script>self.__next_f.push([1,\"\"])</script></body></html>"

      19 |     it('should retrieve cookies in a server component in the edge runtime', async () => {
      20 |       const res = await next.fetch('/edge-apis/cookies')
    > 21 |       expect(await res.text()).toInclude('Hello')
         |                                ^
      22 |     })
      23 |
      24 |     it('should handle /index routes correctly', async () => {

      at Object.toInclude (e2e/app-dir/app-edge/app-edge.test.ts:21:32)

  ● app-dir edge SSR › should resolve client component without error

    expect(received).toContain(expected) // indexOf

    Expected substring: "My Button"
    Received string:    "<!DOCTYPE html><html id=\"__next_error__\"><head><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/><link rel=\"preload\" as=\"script\" fetchPriority=\"low\" href=\"/_next/static/chunks/webpack.js\"/><script src=\"/_next/static/chunks/main-app.js\" async=\"\"></script><script src=\"/_next/static/chunks/app-pages-internals.js\" async=\"\"></script><meta name=\"robots\" content=\"noindex\"/><meta name=\"next-error\" content=\"not-found\"/><script src=\"/_next/static/chunks/polyfills.js\" noModule=\"\"></script></head><body><script src=\"/_next/static/chunks/webpack.js\" async=\"\"></script><script>(self.__next_f=self.__next_f||[]).push([0]);self.__next_f.push([2,null])</script><script>self.__next_f.push([1,\"0:\\\"$L1\\\"\\n\"])</script><script>self.__next_f.push([1,\"2:I[\\\"(app-pages-browser)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/client/components/app-router.js\\\",[\\\"app-pages-internals\\\",\\\"static/chunks/app-pages-internals.js\\\"],\\\"\\\"]\\n4:I[\\\"(app-pages-browser)/./components/button.tsx\\\",[\\\"app/with-client/page\\\",\\\"static/chunks/app/with-client/page.js\\\"],\\\"\\\"]\\n5:I[\\\"(app-pages-browser)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3\"])</script><script>self.__next_f.push([1,\"813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/client/components/layout-router.js\\\",[\\\"app-pages-internals\\\",\\\"static/chunks/app-pages-internals.js\\\"],\\\"\\\"]\\n6:I[\\\"(app-pages-browser)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/client/components/render-from-template-context.js\\\",[\\\"app-pages-internals\\\",\\\"static/chunks/app-pages-internals.js\\\"],\\\"\\\"]\\n8:I[\\\"(app-page\"])</script><script>self.__next_f.push([1,\"s-browser)/./node_modules/.pnpm/file+..+next-repo-a767c380a1e154bc7683a0cf2bfb31992e0dcb3813a3db5ada666f7e139510c2+packages+n_zazqydgrn775dvjv45zdlkapei/node_modules/next/dist/client/components/error-boundary.js\\\",[\\\"app-pages-internals\\\",\\\"static/chunks/app-pages-internals.js\\\"],\\\"\\\"]\\n\"])</script><script>self.__next_f.push([1,\"1:[null,[\\\"$\\\",\\\"$L2\\\",null,{\\\"buildId\\\":\\\"development\\\",\\\"assetPrefix\\\":\\\"\\\",\\\"initialCanonicalUrl\\\":\\\"/with-client\\\",\\\"initialTree\\\":[\\\"\\\",{\\\"children\\\":[\\\"with-client\\\",{\\\"children\\\":[\\\"__PAGE__\\\",{}]}]},\\\"$undefined\\\",\\\"$undefined\\\",true],\\\"initialSeedData\\\":[\\\"\\\",{\\\"children\\\":[\\\"with-client\\\",{\\\"children\\\":[\\\"__PAGE__\\\",{},[\\\"$L3\\\",[[\\\"$\\\",\\\"h1\\\",null,{\\\"children\\\":\\\"Import a client component\\\"}],[\\\"$\\\",\\\"$L4\\\",null,{}]],null]]},[\\\"$\\\",\\\"$L5\\\",null,{\\\"parallelRouterKey\\\":\\\"children\\\",\\\"segmentPath\\\":[\\\"children\\\",\\\"with-client\\\",\\\"children\\\"],\\\"loading\\\":\\\"$undefined\\\",\\\"loadingStyles\\\":\\\"$undefined\\\",\\\"loadingScripts\\\":\\\"$undefined\\\",\\\"hasLoading\\\":false,\\\"error\\\":\\\"$undefined\\\",\\\"errorStyles\\\":\\\"$undefined\\\",\\\"errorScripts\\\":\\\"$undefined\\\",\\\"template\\\":[\\\"$\\\",\\\"$L6\\\",null,{}],\\\"templateStyles\\\":\\\"$undefined\\\",\\\"templateScripts\\\":\\\"$undefined\\\",\\\"notFound\\\":\\\"$undefined\\\",\\\"notFoundStyles\\\":\\\"$undefined\\\",\\\"styles\\\":null}]]},[null,[\\\"$\\\",\\\"html\\\",null,{\\\"children\\\":[[\\\"$\\\",\\\"head\\\",null,{}],[\\\"$\\\",\\\"body\\\",null,{\\\"children\\\":[\\\"$\\\",\\\"$L5\\\",null,{\\\"parallelRouterKey\\\":\\\"children\\\",\\\"segmentPath\\\":[\\\"children\\\"],\\\"loading\\\":\\\"$undefined\\\",\\\"loadingStyles\\\":\\\"$undefined\\\",\\\"loadingScripts\\\":\\\"$undefined\\\",\\\"hasLoading\\\":false,\\\"error\\\":\\\"$undefined\\\",\\\"errorStyles\\\":\\\"$undefined\\\",\\\"errorScripts\\\":\\\"$undefined\\\",\\\"template\\\":[\\\"$\\\",\\\"$L6\\\",null,{}],\\\"templateStyles\\\":\\\"$undefined\\\",\\\"templateScripts\\\":\\\"$undefined\\\",\\\"notFound\\\":[[\\\"$\\\",\\\"title\\\",null,{\\\"children\\\":\\\"404: This page could not be found.\\\"}],[\\\"$\\\",\\\"div\\\",null,{\\\"style\\\":{\\\"fontFamily\\\":\\\"system-ui,\\\\\\\"Segoe UI\\\\\\\",Roboto,Helvetica,Arial,sans-serif,\\\\\\\"Apple Color Emoji\\\\\\\",\\\\\\\"Segoe UI Emoji\\\\\\\"\\\",\\\"height\\\":\\\"100vh\\\",\\\"textAlign\\\":\\\"center\\\",\\\"display\\\":\\\"flex\\\",\\\"flexDirection\\\":\\\"column\\\",\\\"alignItems\\\":\\\"center\\\",\\\"justifyContent\\\":\\\"center\\\"},\\\"children\\\":[\\\"$\\\",\\\"div\\\",null,{\\\"children\\\":[[\\\"$\\\",\\\"style\\\",null,{\\\"dangerouslySetInnerHTML\\\":{\\\"__html\\\":\\\"body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}\\\"}}],[\\\"$\\\",\\\"h1\\\",null,{\\\"className\\\":\\\"next-error-h1\\\",\\\"style\\\":{\\\"display\\\":\\\"inline-block\\\",\\\"margin\\\":\\\"0 20px 0 0\\\",\\\"padding\\\":\\\"0 23px 0 0\\\",\\\"fontSize\\\":24,\\\"fontWeight\\\":500,\\\"verticalAlign\\\":\\\"top\\\",\\\"lineHeight\\\":\\\"49px\\\"},\\\"children\\\":\\\"404\\\"}],[\\\"$\\\",\\\"div\\\",null,{\\\"style\\\":{\\\"display\\\":\\\"inline-block\\\"},\\\"children\\\":[\\\"$\\\",\\\"h2\\\",null,{\\\"style\\\":{\\\"fontSize\\\":14,\\\"fontWeight\\\":400,\\\"lineHeight\\\":\\\"49px\\\",\\\"margin\\\":0},\\\"children\\\":\\\"This page could not be found.\\\"}]}]]}]}]],\\\"notFoundStyles\\\":[],\\\"styles\\\":null}]}]]}],null]],\\\"initialHead\\\":[false,\\\"$L7\\\"],\\\"globalErrorComponent\\\":\\\"$8\\\"}]]\\n\"])</script><script>self.__next_f.push([1,\"7:[[\\\"$\\\",\\\"meta\\\",\\\"0\\\",{\\\"name\\\":\\\"viewport\\\",\\\"content\\\":\\\"width=device-width, initial-scale=1\\\"}],[\\\"$\\\",\\\"meta\\\",\\\"1\\\",{\\\"charSet\\\":\\\"utf-8\\\"}]]\\n3:null\\n\"])</script><script>self.__next_f.push([1,\"\"])</script></body></html>"

      68 |         })
      69 |         const html = await next.render('/with-client')
    > 70 |         expect(html).toContain('My Button')
         |                      ^
      71 |         expect(logs).toEqual([])
      72 |       })
      73 |

      at Object.toContain (e2e/app-dir/app-edge/app-edge.test.ts:70:22)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js feat/esm-api | Change |
| - | - | - | - |
| buildDuration | 12.9s | 12.7s | N/A |
| buildDurationCached | 7s | 6.1s | N/A |
| nodeModulesSize | 202 MB | 202 MB | ⚠️ +6.75 kB |
| nextStartRea..uration (ms) | 424ms | 425ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/esm-api | Change |
| - | - | - | - |
| 193.HASH.js gzip | 181 B | 184 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 433-HASH.js gzip | 28.2 kB | 28.3 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 239 B | 239 B | ✓ |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.7 kB | 98.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/esm-api | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/esm-api | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 194 B | ✓ |
| _error-HASH.js gzip | 183 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 502 B | N/A |
| css-HASH.js gzip | 321 B | 322 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 256 B | N/A |
| head-HASH.js gzip | 350 B | 348 B | N/A |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.28 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | N/A |
| routerDirect..HASH.js gzip | 312 B | 310 B | N/A |
| script-HASH.js gzip | 385 B | 382 B | N/A |
| withRouter-HASH.js gzip | 307 B | 307 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 976 B | 976 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/esm-api | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 485 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/esm-api | Change |
| - | - | - | - |
| index.html gzip | 528 B | 529 B | N/A |
| link.html gzip | 540 B | 541 B | N/A |
| withRouter.html gzip | 523 B | 524 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/esm-api | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.7 kB | 93.7 kB | N/A |
| page.js gzip | 147 kB | 147 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/esm-api | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 624 B | ✓ |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.7 kB | 2.7 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/esm-api | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 94.2 kB | 94.2 kB | ✓ |
| app-page-tur..prod.js gzip | 94.9 kB | 94.9 kB | ✓ |
| app-page-tur..prod.js gzip | 89.4 kB | 89.4 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.7 kB | 88.7 kB | ✓ |
| app-route-ex...dev.js gzip | 24.1 kB | 24.1 kB | ✓ |
| app-route-ex..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| app-route.ru...dev.js gzip | 23.5 kB | 23.5 kB | ✓ |
| app-route.ru..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| Overall change | 932 kB | 932 kB | ✓ |

</details>

</details>
Commit: fb669e9418904c9946f3de6660f3df239e19897e

File: packages/next/src/build/create-compiler-aliases.ts [hunk 1]
```diff
@@ -233,6 +193,46 @@ export function createServerOnlyClientOnlyAliases(
...
+    router: 'next/dist/api/router',
+    dynamic: 'next/dist/api/dynamic',
+    script: 'next/dist/api/script',
+    link: 'next/dist/api/link',
+    navigation: 'next/dist/api/navigation',
+    headers: 'next/dist/api/headers',
+    og: 'next/dist/api/og',
+    // pages api
+    document: 'next/dist/api/document',
+    app: 'next/dist/api/app',
```
Comment (ztanner) [inline packages/next/src/build/create-compiler-aliases.ts:210]: Probably a silly question, but can you clarify why it's ok for this to be `app` and `document` if previously`dist/esm/_app` and `dist/esm/_document`?

Comment (huozhi) [reply packages/next/src/build/create-compiler-aliases.ts:210]: previously we were locating the page `dist/esm/_app|_document`, now with the new `api/` folder, they're re-exporting everything from `dist/(esm/)?pages/_app|_document`. So we were mapping file path to another file path

In this way, it will be easier to maintain as we only need to care about the api path `next/app` instead of the file path `next/dist/pages/_app`. The esm mapping takes effect with above folder mapping

**Review by ztanner — APPROVED** [review]
