### PR TITLE
Bug fix: dynamic page should not be interpreted as predefined page

### LINKED ISSUE #17096: dynamic routes param value is not defined for server side render when literal dynamic route value is provided as the pathname
# Bug report

## Describe the bug

When using [dynamic routes](https://nextjs.org/docs/routing/dynamic-routes) the `param` value is not defined when navigating to a page whose pathname is the string literal value for the dynamic route. 

From the dynamic routes example:

Given a page defined as `pages/post/[pid].js`, navigating to `/post/[pid]` will _not_ set the `pid` param value for the server side render _if_ `getInitialProps` is defined for the page.

If `getInitialProps` is not provided, then the router correctly extracts the `pid` `param`. When `getInitialProps` is provided, the router does not extract the `pid` param, and the `context` argument for `getInitialProps` will not include `pid` in the `query` attribute. 

Note: This only occurs for the server side render. When navigating client side, everything works as expected.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://3q2nu.sse.codesandbox.io/
2. Click on the `[day]` link
3. Observe the values for `router` and `gIP` (both are `[day]` as expected)
4. Reload the page (https://3q2nu.sse.codesandbox.io/days/[day])
5. Observe the values for `router` and `gIP` (both are `undefined`)

codesandbox: https://codesandbox.io/s/romantic-raman-3q2nu

Note:
Removing `DayPage.getInitialProps` from the sandbox above will cause the `router` value to be correct both when navigating on the client and on the sever side render.

## Expected behavior

The query param value should always be set.

Given a page defined as `pages/post/[pid].js`, navigating to `/post/[pid]` should set the `pid` param value to `[pid]` in both server and client side contexts.

## System information

- OS: [macOs]
- Browser [N/A]
- Version of Next.js: [9.5.3, present on latest]
- Version of Node.js: [12.x]

### LINKED ISSUE #23824: Dynamic API routes : explicilty requesting url with dynamic slug as [slug]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

v12.16.3

### What browser are you using?

Firefox

### What operating system are you using?

Ubuntu

### How are you deploying your application?

next dev

### Describe the Bug

When requesting a url with a dynamic segment (ex : `/my/path/[slug]`) with that slug not being replaced by anything (ex : `https://mysite.web/my/path/[slug]`), I got the following error : 
`The provided `href` (/my/path/[slug]?) value is missing query values (slug) to be interpolated properly. Read more: https://nextjs.org/docs/messages/href-interpolation-failed`

### Expected Behavior

To behave as if the slug was wrong (ex : `/my/path/foo` or  `/my/path/[bar]`).

### To Reproduce

https://codesandbox.io/s/dynamic-routes-slug-k7jui

### PR DESCRIPTION
**Pull request by jameshfisher**
Fixes: https://github.com/vercel/next.js/issues/17096
Fixes: https://github.com/vercel/next.js/issues/23824
Closes: https://github.com/vercel/next.js/pull/33765

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added in https://github.com/vercel/next.js/pull/33765
- [x] Errors have helpful link attached (N/A)

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.8s | ⚠️ +9ms |
| buildDurationCached | 3.3s | 3.2s | -65ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +539 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.994 | 2.961 | -0.03 |
| / avg req/sec | 835.01 | 844.18 | +9.17 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.392 | 1.401 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1796.6 | 1783.89 | ⚠️ -12.71 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71 kB | 71 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.93 kB | 4.93 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| buildDuration | 16.1s | 16.2s | ⚠️ +94ms |
| buildDurationCached | 3.2s | 3.2s | -26ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +539 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.914 | 2.983 | ⚠️ +0.07 |
| / avg req/sec | 858.02 | 838.22 | ⚠️ -19.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.384 | 1.362 | -0.02 |
| /error-in-render avg req/sec | 1806.73 | 1835.01 | +28.28 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.97 kB | 4.97 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 2f1dac642e79d92afa50634d17815712cc84046e

File: packages/next/server/base-server.ts [hunk 1]
```diff
@@ -1532,15 +1532,20 @@ export default abstract class Server {
...
     try {
-      const result = await this.findPageComponents(pathname, query)
-      if (result) {
-        try {
-          return await this.renderToResponseWithComponents(ctx, result)
-        } catch (err) {
-          const isNoFallbackError = err instanceof NoFallbackError
+      // The following guard is necessary to safely cast the URL pathname to a potential predefined page path.
+      // Without the guard, a request to the URL /accounts/[id] will find pages/accounts/[id].js
+      // and interpret it as a predefined route.
```
Comment (ijjk) [inline packages/next/server/base-server.ts:1537]:
```suggestion
      // Ensure a request to the URL /accounts/[id] will be treated as a dynamic
      // route correctly and not loaded immediately without parsing params.
```
Looks like we also need to handle this case for API routes here https://github.com/vercel/next.js/blob/3bac02e032792b07726ba795e5b07b502185667a/packages/next/server/base-server.ts#L882

**Comment by ijjk** [comment]
## Failing test suites 
Commit: a2640880d68d88e356b1c82a113423f0a763886b

**test/e2e/dynamic-route-interpolation/index.test.ts** 
- Dynamic Route Interpolation > should work with parameter itself in API routes
- Dynamic Route Interpolation > should work with brackets in API routes

<details>
<summary>Expand output</summary>

  ● Dynamic Route Interpolation › should work with parameter itself in API routes

    expect(received).toBe(expected) // Object.is equality

    Expected: "[slug]"
    Received: ""

      54 |   it('should work with parameter itself in API routes', async () => {
      55 |     const html = await renderViaHTTP(next.url, '/api/dynamic/[slug]')
    > 56 |     const $ = cheerio.load(html)
         |                                 ^
      57 |     expect($('#slug').text()).toBe('[slug]')
      58 |   })
      59 |

      at Object.<anonymous> (e2e/dynamic-route-interpolation/index.test.ts:56:35)

  ● Dynamic Route Interpolation › should work with brackets in API routes

    expect(received).toBe(expected) // Object.is equality

    Expected: "[abc]"
    Received: ""

      59 |
      60 |   it('should work with brackets in API routes', async () => {
    > 61 |     const html = await renderViaHTTP(next.url, '/api/dynamic/[abc]')
         |                                   ^
      62 |     const $ = cheerio.load(html)
      63 |     expect($('#slug').text()).toBe('[abc]')
      64 |   })

      at Object.<anonymous> (e2e/dynamic-route-interpolation/index.test.ts:61:35)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| buildDuration | 12.6s | 13.3s | ⚠️ +651ms |
| buildDurationCached | 3.3s | 3.2s | -156ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +529 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.919 | 2.991 | ⚠️ +0.07 |
| / avg req/sec | 856.38 | 835.77 | ⚠️ -20.61 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.373 | 1.38 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1821.32 | 1810.94 | ⚠️ -10.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71 kB | 71 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.93 kB | 4.93 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| buildDuration | 16.7s | 15.9s | -798ms |
| buildDurationCached | 3.3s | 3.3s | ⚠️ +62ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +529 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.002 | 2.929 | -0.07 |
| / avg req/sec | 832.74 | 853.44 | +20.7 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.465 | 1.394 | -0.07 |
| /error-in-render avg req/sec | 1706.08 | 1793.94 | +87.86 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.97 kB | 4.97 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: a2640880d68d88e356b1c82a113423f0a763886b

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 5d5ebe5cf45e422b829eedf328319a627828ee13

**test/e2e/dynamic-route-interpolation/index.test.ts** 
- Dynamic Route Interpolation > should work with parameter itself in API routes
- Dynamic Route Interpolation > should work with brackets in API routes

<details>
<summary>Expand output</summary>

  ● Dynamic Route Interpolation › should work with parameter itself in API routes

    expect(received).toBe(expected) // Object.is equality

    Expected: "[slug]"
    Received: ""

      54 |   it('should work with parameter itself in API routes', async () => {
      55 |     const html = await renderViaHTTP(next.url, '/api/dynamic/[slug]')
    > 56 |     const $ = cheerio.load(html)
         |                                 ^
      57 |     expect($('#slug').text()).toBe('[slug]')
      58 |   })
      59 |

      at Object.<anonymous> (e2e/dynamic-route-interpolation/index.test.ts:56:35)

  ● Dynamic Route Interpolation › should work with brackets in API routes

    expect(received).toBe(expected) // Object.is equality

    Expected: "[abc]"
    Received: ""

      59 |
      60 |   it('should work with brackets in API routes', async () => {
    > 61 |     const html = await renderViaHTTP(next.url, '/api/dynamic/[abc]')
         |                                   ^
      62 |     const $ = cheerio.load(html)
      63 |     expect($('#slug').text()).toBe('[abc]')
      64 |   })

      at Object.<anonymous> (e2e/dynamic-route-interpolation/index.test.ts:61:35)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.4s | -185ms |
| buildDurationCached | 3.1s | 3.2s | ⚠️ +32ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +375 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.957 | 2.902 | -0.05 |
| / avg req/sec | 845.4 | 861.53 | +16.13 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.353 | 1.369 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1848.37 | 1826.15 | ⚠️ -22.22 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71 kB | 71 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.93 kB | 4.93 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| buildDuration | 15.8s | 15.8s | ⚠️ +50ms |
| buildDurationCached | 3.1s | 3.1s | ⚠️ +21ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +375 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.93 | 2.911 | -0.02 |
| / avg req/sec | 853.23 | 858.85 | +5.62 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.375 | 1.384 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1818.04 | 1806.31 | ⚠️ -11.73 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.97 kB | 4.97 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 5d5ebe5cf45e422b829eedf328319a627828ee13

**Comment by ijjk** [comment]
## Failing test suites 
Commit: b8eaf8864e0f7678da5b472280d8eaec6adc147f

**test/e2e/dynamic-route-interpolation/index.test.ts** 
- Dynamic Route Interpolation > should work with parameter itself in API routes
- Dynamic Route Interpolation > should work with brackets in API routes

<details>
<summary>Expand output</summary>

  ● Dynamic Route Interpolation › should work with parameter itself in API routes

    expect(received).toBe(expected) // Object.is equality

    Expected: "[slug]"
    Received: ""

      54 |   it('should work with parameter itself in API routes', async () => {
      55 |     const html = await renderViaHTTP(next.url, '/api/dynamic/[slug]')
    > 56 |     const $ = cheerio.load(html)
         |                                 ^
      57 |     expect($('#slug').text()).toBe('[slug]')
      58 |   })
      59 |

      at Object.<anonymous> (e2e/dynamic-route-interpolation/index.test.ts:56:35)

  ● Dynamic Route Interpolation › should work with brackets in API routes

    expect(received).toBe(expected) // Object.is equality

    Expected: "[abc]"
    Received: ""

      59 |
      60 |   it('should work with brackets in API routes', async () => {
    > 61 |     const html = await renderViaHTTP(next.url, '/api/dynamic/[abc]')
         |                                   ^
      62 |     const $ = cheerio.load(html)
      63 |     expect($('#slug').text()).toBe('[abc]')
      64 |   })

      at Object.<anonymous> (e2e/dynamic-route-interpolation/index.test.ts:61:35)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| buildDuration | 16.7s | 15.8s | -912ms |
| buildDurationCached | 3.9s | 4s | ⚠️ +64ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +391 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.024 | 4.024 | ✓ |
| / avg req/sec | 621.2 | 621.34 | +0.14 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.104 | 2.051 | -0.05 |
| /error-in-render avg req/sec | 1188.19 | 1219.18 | +30.99 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71 kB | 71 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.4 kB | 14.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 543 B | 543 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| buildDuration | 22.5s | 19.6s | -3s |
| buildDurationCached | 4.2s | 4.1s | -125ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +391 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.069 | 3.763 | -0.31 |
| / avg req/sec | 614.43 | 664.39 | +49.96 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.078 | 1.956 | -0.12 |
| /error-in-render avg req/sec | 1203.08 | 1277.91 | +74.83 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.98 kB | 4.98 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 543 B | 543 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: b8eaf8864e0f7678da5b472280d8eaec6adc147f

**Comment by ijjk** [comment]
## Failing test suites 
Commit: ce00fcb7f4481d3c27b47c0777dfe95541e00301

**test/e2e/dynamic-route-interpolation/index.test.ts** 
- Dynamic Route Interpolation > should work with parameter itself in API routes
- Dynamic Route Interpolation > should work with brackets in API routes

<details>
<summary>Expand output</summary>

  ● Dynamic Route Interpolation › should work with parameter itself in API routes

    expect(received).toBe(expected) // Object.is equality

    Expected: "[slug]"
    Received: ""

      54 |   it('should work with parameter itself in API routes', async () => {
      55 |     const html = await renderViaHTTP(next.url, '/api/dynamic/[slug]')
    > 56 |     const $ = cheerio.load(html)
         |                                 ^
      57 |     expect($('#slug').text()).toBe('[slug]')
      58 |   })
      59 |

      at Object.<anonymous> (e2e/dynamic-route-interpolation/index.test.ts:56:35)

  ● Dynamic Route Interpolation › should work with brackets in API routes

    expect(received).toBe(expected) // Object.is equality

    Expected: "[abc]"
    Received: ""

      59 |
      60 |   it('should work with brackets in API routes', async () => {
    > 61 |     const html = await renderViaHTTP(next.url, '/api/dynamic/[abc]')
         |                                   ^
      62 |     const $ = cheerio.load(html)
      63 |     expect($('#slug').text()).toBe('[abc]')
      64 |   })

      at Object.<anonymous> (e2e/dynamic-route-interpolation/index.test.ts:61:35)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.5s | ⚠️ +52ms |
| buildDurationCached | 3.2s | 3.2s | -50ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +459 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.919 | 2.95 | ⚠️ +0.03 |
| / avg req/sec | 856.51 | 847.35 | ⚠️ -9.16 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.373 | 1.364 | -0.01 |
| /error-in-render avg req/sec | 1820.85 | 1833.43 | +12.58 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71 kB | 71 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.4 kB | 14.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 543 B | 543 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| buildDuration | 16s | 16.1s | ⚠️ +76ms |
| buildDurationCached | 3.2s | 3.2s | ⚠️ +20ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +459 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.912 | 2.961 | ⚠️ +0.05 |
| / avg req/sec | 858.52 | 844.31 | ⚠️ -14.21 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.392 | 1.39 | 0 |
| /error-in-render avg req/sec | 1796.58 | 1799.09 | +2.51 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.98 kB | 4.98 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 543 B | 543 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: ce00fcb7f4481d3c27b47c0777dfe95541e00301

**Comment by jameshfisher** [comment]
@timneutkens it looks like the API tests are expecting HTML, but the API routes are returning plaintext? (Or am I misreading it)

**Comment by ijjk** [comment]
@jameshfisher right, I went ahead and updated those cases and looks good now

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| buildDuration | 14.6s | 14.4s | -192ms |
| buildDurationCached | 3.7s | 3.8s | ⚠️ +144ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +460 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.377 | 3.444 | ⚠️ +0.07 |
| / avg req/sec | 740.25 | 725.8 | ⚠️ -14.45 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.498 | 1.536 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1668.43 | 1627.61 | ⚠️ -40.82 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.1 kB | 71.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| buildDuration | 18.3s | 18.1s | -220ms |
| buildDurationCached | 3.7s | 3.7s | ⚠️ +27ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +460 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.453 | 3.457 | 0 |
| / avg req/sec | 724.09 | 723.13 | ⚠️ -0.96 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.546 | 1.565 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1617.43 | 1597.44 | ⚠️ -19.99 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.4 kB | 27.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.98 kB | 4.98 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jameshfisher/next.js url-should-not-be-used-as-page-path | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 94084be5fb804bc531edf82e8dd41b324d807409

**Review by ijjk — APPROVED** [review]
Thanks for the PR!
