### PR TITLE
Safely retrieve router, improve page reload logic

### LINKED ISSUE #71974: Page Router - Turbopack HMR Warning: window.next.router undefined during appIsrManifest event
### Link to the code that reproduces this issue

https://github.com/gurkerl83/next-turbo-dynamic-import

### To Reproduce

The following reproducer was create for another ticket. The HMR problem is observable even in this demonstrator, so I hope this is OK for reuse.

1. Clone the reproduction repository: 
   
```bash
git clone https://github.com/gurkerl83/next-turbo-dynamic-import.git
```

2. The reproduction case was originally created to address a different issue. To use it for this problem, please comment out both the import and render of the ComponentNamedImportWithIssue component.

3. Install dependencies using pnpm:

```bash
pnpm install
```

4. Run the development server with Turbopack:

```bash
pnpm dev:turbo
```

5. Go to the browser, Open Dev Tools, Observe the console warnings and errors upon startup:

```text
[HMR] Invalid message: {"action":"appIsrManifest","data":{}}
TypeError: Cannot read properties of undefined (reading 'pathname')
    at http://localhost:3000/_next/static/chunks/...
```

### Current vs. Expected behavior

Current behavior: When starting the application with Turbopack in development mode, a TypeError occurs due to window.next.router being undefined during HMR events, specifically during the appIsrManifest action. This results in console warnings and may disrupt the development workflow.

Expected behavior: The application should start without any TypeError or HMR warnings. Hot Module Replacement (HMR) events should not cause errors even if window.next.router is not yet initialized.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031
  Available memory (MB): 65536
  Available CPU cores: 16
Binaries:
  Node: 22.6.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: 9.11.0
Relevant Packages:
  next: 15.0.2-canary.9 // Latest available version.
  react: 19.0.0-rc-cae764ce-20241025
  react-dom: 19.0.0-rc-cae764ce-20241025
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Pages Router, Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

In the Next.js source code, there are two distinct hot-reloader-client implementations: one for the Page Router and another for the App Router.

The Page Router variant includes a custom event handler, `customHmrEventHandler`, which is responsible for handling specific hot-reload events. This functionality is implemented in the following code snippet to address the issue effectively.

[packages/next/src/client/dev/hot-middleware-client.ts](https://github.com/vercel/next.js/blob/a3918569c79d7a7fe1a8b080b42f39586e3daa8a/packages/next/src/client/dev/hot-middleware-client.ts)

Note:
This issue may not be detectable in the App Router because the event handler in question is not utilized there. The reproduction case specifically relies on the Page Router.

```ts
import type {
  NextRouter,
  PrivateRouteInfo,
} from '../../shared/lib/router/router'
import connect from '../components/react-dev-overlay/pages/hot-reloader-client'
import { sendMessage } from '../components/react-dev-overlay/pages/websocket'

// Define a local type for the window.next object
interface NextWindow {
  next?: {
    router?: NextRouter & {
      components: { [pathname: string]: PrivateRouteInfo }
    }
  }
  __nextDevClientId?: string
  location: Location
}

declare const window: NextWindow

let reloading = false

export default (mode: 'webpack' | 'turbopack') => {
  const devClient = connect(mode)

  devClient.subscribeToHmrEvent((obj) => {
    if (reloading) return

    // Retrieve the router if it's available
    const router = window.next?.router

    // Determine if we're on an error page or the router is not initialized
    const isOnErrorPage =
      !router || router.pathname === '/404' || router.pathname === '/_error'

    switch (obj.action) {
      case 'reloadPage': {
        sendMessage(
          JSON.stringify({
            event: 'client-reload-page',
            clientId: window.__nextDevClientId,
          })
        )
        reloading = true
        return window.location.reload()
      }
      case 'removedPage': {
        const [page] = obj.data

        // Check if the removed page is the current page
        const isCurrentPage = page === router?.pathname

        if (isCurrentPage || isOnErrorPage) {
          sendMessage(
            JSON.stringify({
              event: 'client-removed-page',
              clientId: window.__nextDevClientId,
              page,
            })
          )
          return window.location.reload()
        }
        return
      }
      case 'addedPage': {
        const [page] = obj.data

        // Check if the added page is the current page
        const isCurrentPage = page === router?.pathname

        // Check if the page component is not yet loaded
        const isPageNotLoaded =
          typeof router?.components?.[page] === 'undefined'

        if ((isCurrentPage && isPageNotLoaded) || isOnErrorPage) {
          sendMessage(
            JSON.stringify({
              event: 'client-added-page',
              clientId: window.__nextDevClientId,
              page,
            })
          )
          return window.location.reload()
        }
        return
      }
      case 'serverError':
      case 'devPagesManifestUpdate':
      case 'appIsrManifest':
      case 'building':
      case 'finishBuilding': {
        return
      }
      default: {
        throw new Error('Unexpected action ' + obj.action)
      }
    }
  })

  return devClient
}
```

### PR DESCRIPTION
**Pull request by gurkerl83**
This PR improves the hot module reloading (HMR) logic in the dev client by:

- Safe Router Retrieval: Uses optional chaining (window.next?.router) to prevent errors if the router is uninitialized.
- Enhanced Error Page Handling: Ensures the client reloads when on /404 or /_error pages, addressing cases where page additions/removals can't be reliably matched to the current path.
- Improved Reload Logic: Checks if the current page is added or removed and triggers a reload accordingly to keep the client state up-to-date.
- Updated Comments: Clarifies the conditions under which reloads occur, especially when on error pages.

These changes make the HMR process more robust and prevent potential runtime issues.

Closes #71974

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 8c6bdf90540d1d6c050cf4103c98ed53e6ec47d5

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

File: packages/next/src/client/dev/hot-middleware-client.ts [hunk 1]
```diff
@@ -1,18 +1,37 @@
...
-    // matches the current path. In that case, assume any added/removed entries should trigger a reload of the current page
+
+    // Retrieve the router if it's available
+    const router = window.next?.router
+
+    // Determine if we're on an error page or the router is not initialized
     const isOnErrorPage =
-      window.next.router.pathname === '/404' ||
-      window.next.router.pathname === '/_error'
+      !router || router.pathname === '/404' || router.pathname === '/_error'
```
Comment (7alip) [inline packages/next/src/client/dev/hot-middleware-client.ts:34]: @gurkerl83 Probably missing optional chaining here

```suggestion
      !router || router?.pathname === '/404' || router?.pathname === '/_error'
```

Comment (gurkerl83) [reply packages/next/src/client/dev/hot-middleware-client.ts:34]: Where optional chaining makes sense and where it does not.

1. Correctly uses optional chaining to safely access router, preventing errors if window.next is undefined.

```window.next?.router```

2. Access of the mandatory field `router.pathname`

The following type is defined for Router

```
export type BaseRouter = {
  route: string
  pathname: string
...
}
```

- The original PR is **safe** without using ?. on router.pathname because !router ensures router is defined before accessing pathname.
- The suggested change adding ?. to router.pathname is **redundant**; once router is confirmed truthy, pathname is guaranteed to exist.

**Keep Original Code:** 
The existing use of optional chaining on window.next?.router is necessary. Adding it to router.pathname is unnecessary and clutters the code.

Thx!

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | gurkerl83/next.js Fix-HMR-Warning | Change |
| - | - | - | - |
| buildDuration | 31s | 24.3s | N/A |
| buildDurationCached | 24s | 24.4s | ⚠️ +396ms |
| nodeModulesSize | 416 MB | 416 MB | ⚠️ +7.68 kB |
| nextStartRea..uration (ms) | 802ms | 791ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | gurkerl83/next.js Fix-HMR-Warning | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 52.4 kB | 52.4 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.36 kB | 5.36 kB | N/A |
| bccd1874-HASH.js gzip | 52.8 kB | 52.8 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 231 B | 235 B | N/A |
| main-HASH.js gzip | 34.1 kB | 34.1 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | gurkerl83/next.js Fix-HMR-Warning | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | gurkerl83/next.js Fix-HMR-Warning | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | gurkerl83/next.js Fix-HMR-Warning | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 746 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | gurkerl83/next.js Fix-HMR-Warning | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 538 B | 537 B | N/A |
| withRouter.html gzip | 520 B | 520 B | ✓ |
| Overall change | 1.04 kB | 1.04 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | gurkerl83/next.js Fix-HMR-Warning | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 206 kB | 206 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | gurkerl83/next.js Fix-HMR-Warning | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 670 B | 666 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.2 kB | 31.2 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | gurkerl83/next.js Fix-HMR-Warning | Change |
| - | - | - | - |
| 274-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 274.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 359 kB | 359 kB | ✓ |
| app-page-exp..prod.js gzip | 129 kB | 129 kB | ✓ |
| app-page-tur..prod.js gzip | 142 kB | 142 kB | ✓ |
| app-page-tur..prod.js gzip | 137 kB | 137 kB | ✓ |
| app-page.run...dev.js gzip | 348 kB | 348 kB | ✓ |
| app-page.run..prod.js gzip | 125 kB | 125 kB | ✓ |
| app-route-ex...dev.js gzip | 37.5 kB | 37.5 kB | ✓ |
| app-route-ex..prod.js gzip | 25.5 kB | 25.5 kB | ✓ |
| app-route-tu..prod.js gzip | 25.5 kB | 25.5 kB | ✓ |
| app-route-tu..prod.js gzip | 25.4 kB | 25.4 kB | ✓ |
| app-route.ru...dev.js gzip | 39.2 kB | 39.2 kB | ✓ |
| app-route.ru..prod.js gzip | 25.4 kB | 25.4 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.69 kB | 9.69 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.6 kB | 11.6 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.68 kB | 9.68 kB | ✓ |
| pages-turbo...prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| pages.runtim...dev.js gzip | 27.5 kB | 27.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| server.runti..prod.js gzip | 916 kB | 916 kB | ✓ |
| Overall change | 2.44 MB | 2.44 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | gurkerl83/next.js Fix-HMR-Warning | Change |
| - | - | - | - |
| 0.pack gzip | 2.08 MB | 2.08 MB | ⚠️ +1.28 kB |
| index.pack gzip | 74.8 kB | 74.6 kB | N/A |
| Overall change | 2.08 MB | 2.08 MB | ⚠️ +1.28 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: b2c518855faa4ae1daeb3433e3a055287e69bb83

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: b2c518855faa4ae1daeb3433e3a055287e69bb83

`pnpm test-start test/production/graceful-shutdown/index.test.ts`
- Graceful Shutdown > production (standalone mode) > should not accept new requests during shutdown cleanup > when there is no activity

<details>
<summary>Expand output</summary>

  ● Graceful Shutdown › production (standalone mode) › should not accept new requests during shutdown cleanup › when there is no activity

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Array [
    -   0,
        null,
    +   "SIGTERM",
      ]

      233 |
      234 |         // App finally shuts down
    > 235 |         expect(await appKilledPromise).toEqual([0, null])
          |                                        ^
      236 |         expect(app.exitCode).toBe(0)
      237 |       })
      238 |     })

      at Object.toEqual (production/graceful-shutdown/index.test.ts:235:40)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).
