### PR TITLE
Remove passing of NODE_OPTIONS='--inspect' to subprocesses

### LINKED ISSUE #11030: Cannot start node inspector: "address already in use"
# Bug report

After upgrading from Next 9.2.2 -> 9.3.0 the node inspector fails to start (crashing the Next process) with the error "Starting inspector on 0.0.0.0:9229 failed: address already in use".

None of the suggestions offered in https://github.com/zeit/next.js/issues/10610 or https://github.com/zeit/next.js/issues/9027 have helped. Have also tested with Next 9.3.1-canary.3 and noted the same issue occurs.

## To Reproduce

1. Run `npx create-next-app`
2. Add `"dev": "NODE_OPTIONS='--inspect' next"` to scripts
3. Run `npm run dev`

## Expected behavior

The node inspector starts normally without crashing the Next process.

## System information

- OS: macOS 10.15.3
- Version of Next.js: 9.3.0+

### PR DESCRIPTION
**Pull request by vvo**
fixes #11030

To test:

```json
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "NODE_OPTIONS='--inspect' next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "9.3.0",
    "react": "16.13.0",
    "react-dom": "16.13.0"
  }
}
```

```bash
yarn dev
```

This will also solve #10807

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 11.1s | 11.3s | ⚠️ +160ms |
| nodeModulesSize | 56.6 MB | 56.6 MB | ⚠️ +778 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.2 kB | 26.2 kB | ✓ |
| Overall change | 26.2 kB | 26.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.96 kB | 2.96 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.06 kB | 2.06 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| index.html gzip | 914 B | 914 B | ✓ |
| link.html gzip | 922 B | 922 B | ✓ |
| withRouter.html gzip | 910 B | 910 B | ✓ |
| Overall change | 2.75 kB | 2.75 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.2s | -152ms |
| nodeModulesSize | 56.6 MB | 56.6 MB | ⚠️ +778 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.2 kB | 26.2 kB | ✓ |
| Overall change | 26.2 kB | 26.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.96 kB | 2.96 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.06 kB | 2.06 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _error.js gzip | 293 kB | 293 kB | -3 B |
| 404.html gzip | 1.32 kB | 1.32 kB | ✓ |
| hooks.html gzip | 954 B | 954 B | ✓ |
| index.js gzip | 293 kB | 293 kB | -61 B |
| link.js gzip | 301 kB | 301 kB | ⚠️ +547 B |
| routerDirect.js gzip | 300 kB | 300 kB | -50 B |
| withRouter.js gzip | 300 kB | 299 kB | -49 B |
| Overall change | 1.49 MB | 1.49 MB | ⚠️ +384 B |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 9.6s | 10s | ⚠️ +356ms |
| nodeModulesSize | 56.6 MB | 56.6 MB | ⚠️ +778 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.2 kB | 26.2 kB | ✓ |
| Overall change | 26.2 kB | 26.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.96 kB | 2.96 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.06 kB | 2.06 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| index.html gzip | 914 B | 914 B | ✓ |
| link.html gzip | 922 B | 922 B | ✓ |
| withRouter.html gzip | 910 B | 910 B | ✓ |
| Overall change | 2.75 kB | 2.75 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.5s | -19ms |
| nodeModulesSize | 56.6 MB | 56.6 MB | ⚠️ +778 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.2 kB | 26.2 kB | ✓ |
| Overall change | 26.2 kB | 26.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.96 kB | 2.96 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.06 kB | 2.06 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _error.js gzip | 293 kB | 294 kB | ⚠️ +707 B |
| 404.html gzip | 1.32 kB | 1.32 kB | ✓ |
| hooks.html gzip | 954 B | 954 B | ✓ |
| index.js gzip | 294 kB | 293 kB | -189 B |
| link.js gzip | 301 kB | 301 kB | -425 B |
| routerDirect.js gzip | 300 kB | 300 kB | -4 B |
| withRouter.js gzip | 300 kB | 300 kB | ⚠️ +309 B |
| Overall change | 1.49 MB | 1.49 MB | ⚠️ +398 B |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 9.4s | 9.6s | ⚠️ +180ms |
| nodeModulesSize | 56.6 MB | 56.6 MB | ⚠️ +778 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.2 kB | 26.2 kB | ✓ |
| Overall change | 26.2 kB | 26.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.96 kB | 2.96 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.06 kB | 2.06 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| index.html gzip | 916 B | 916 B | ✓ |
| link.html gzip | 925 B | 925 B | ✓ |
| withRouter.html gzip | 913 B | 913 B | ✓ |
| Overall change | 2.75 kB | 2.75 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.2s | -95ms |
| nodeModulesSize | 56.6 MB | 56.6 MB | ⚠️ +778 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.2 kB | 26.2 kB | ✓ |
| Overall change | 26.2 kB | 26.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.96 kB | 2.96 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.06 kB | 2.06 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _error.js gzip | 293 kB | 294 kB | ⚠️ +763 B |
| 404.html gzip | 1.32 kB | 1.32 kB | ✓ |
| hooks.html gzip | 957 B | 957 B | ✓ |
| index.js gzip | 294 kB | 294 kB | ⚠️ +390 B |
| link.js gzip | 301 kB | 301 kB | ⚠️ +502 B |
| routerDirect.js gzip | 300 kB | 300 kB | -101 B |
| withRouter.js gzip | 300 kB | 300 kB | ⚠️ +268 B |
| Overall change | 1.49 MB | 1.49 MB | ⚠️ +1.82 kB |

</details>

</details>

**Comment by GabrielDelepine** [comment]
For instance :
Screenshot 2020-03-13 at 18 34 41

`process.env.NODE_OPTIONS.replace('--inspect', '')` does not remove the option totally. I think we will have to use a regex (Using a package specialise to manipulate parameters would be preferable)

**Comment by vvo** [comment]
> `process.env.NODE_OPTIONS.replace('--inspect', '')` does not remove the option totally. I think we will have to use a regex (Using a package specialise to manipulate parameters would be preferable)

Definitely right, I'll give it another take later. At least we know where the bug lies now.

> Removing it totally fix the issue for me, but the warning `Starting inspector on 127.0.0.1:9876 failed: address already in use` is still displayed once

I do not get the warning, maybe you have other processes running or some phamtom processes too?

see:

image

Try on a fresh new project maybe?

**Comment by GabrielDelepine** [comment]
> I do not get the warning, maybe you have other processes running or some phamtom processes too?

You are right!
I had to close VSCODE, no more warning now. Everything is fine

**Review by aleclarson — APPROVED** [review]

File: packages/next/server/next-dev-server.ts [hunk 1]
```diff
@@ -85,6 +85,16 @@ export default class DevServer extends Server {
       {
         maxRetries: 0,
         numWorkers: this.nextConfig.experimental.cpus,
+        forkOptions: {
+          env: {
+            ...process.env,
+            // discard process.env.NODE_OPTIONS --inspect flag otherwise two debuggers are started in inspect
+            // mode when users will try to debug their Next.js application with NODE_OPTIONS='--inspect' next dev
+            NODE_OPTIONS: process.env.NODE_OPTIONS
+              ? process.env.NODE_OPTIONS.replace('--inspect', '')
```
Comment (aleclarson) [inline packages/next/server/next-dev-server.ts]:
```suggestion
              ? process.env.NODE_OPTIONS.replace(/--inspect(=\S+)? ?/, '')
```

Comment (aleclarson) [inline packages/next/server/next-dev-server.ts]: Fixed here: https://github.com/vvo/next.js/pull/1

Comment (aleclarson) [reply packages/next/server/next-dev-server.ts]: Note: Downgrading to v8.1.0 fixed the issue

Comment (aleclarson) [reply packages/next/server/next-dev-server.ts]: Overriding `process.env.NODE_OPTIONS` seems to do the job:
https://github.com/aleclarson/next.js/commit/0248a44e620f499271e8ccb43c69138f8d010422

Apart from "purity", is there any reason this approach should be avoided?

Comment (vvo) [reply packages/next/server/next-dev-server.ts]: > Apart from "purity", is there any reason this approach should be avoided?

I think its fine, the feature of debugging a Next.js application for end users outweights the "purity" question for me. Sorry I have no time left to properly fix this but we know where the bug is at least, if someone from Next.js jumps in we'll see

Comment (aleclarson) [reply packages/next/server/next-dev-server.ts]: Even with my fix, I'm still unable to set breakpoints in my `pages/api` functions. :(

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 11.2s | 11.8s | ⚠️ +523ms |
| nodeModulesSize | 53.2 MB | 53.2 MB | ⚠️ +778 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.39 kB | 7.39 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| index.html gzip | 916 B | 916 B | ✓ |
| link.html gzip | 924 B | 924 B | ✓ |
| withRouter.html gzip | 913 B | 913 B | ✓ |
| Overall change | 2.75 kB | 2.75 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.2s | -268ms |
| nodeModulesSize | 53.2 MB | 53.2 MB | ⚠️ +778 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.39 kB | 7.39 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _error.js gzip | 293 kB | 293 kB | ⚠️ +313 B |
| 404.html gzip | 1.32 kB | 1.32 kB | ✓ |
| hooks.html gzip | 957 B | 957 B | ✓ |
| index.js gzip | 293 kB | 293 kB | -4 B |
| link.js gzip | 301 kB | 301 kB | ⚠️ +50 B |
| routerDirect.js gzip | 300 kB | 300 kB | -334 B |
| withRouter.js gzip | 299 kB | 300 kB | ⚠️ +483 B |
| Overall change | 1.49 MB | 1.49 MB | ⚠️ +508 B |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 9.8s | 10s | ⚠️ +244ms |
| nodeModulesSize | 53.2 MB | 53.2 MB | ⚠️ +1.52 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.39 kB | 7.39 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| index.html gzip | 916 B | 916 B | ✓ |
| link.html gzip | 924 B | 924 B | ✓ |
| withRouter.html gzip | 913 B | 913 B | ✓ |
| Overall change | 2.75 kB | 2.75 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.6s | ⚠️ +138ms |
| nodeModulesSize | 53.2 MB | 53.2 MB | ⚠️ +1.52 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.39 kB | 7.39 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _error.js gzip | 294 kB | 293 kB | -385 B |
| 404.html gzip | 1.32 kB | 1.32 kB | ✓ |
| hooks.html gzip | 957 B | 957 B | ✓ |
| index.js gzip | 294 kB | 294 kB | -100 B |
| link.js gzip | 301 kB | 301 kB | -665 B |
| routerDirect.js gzip | 300 kB | 300 kB | -181 B |
| withRouter.js gzip | 300 kB | 300 kB | -222 B |
| Overall change | 1.49 MB | 1.49 MB | -1.55 kB |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 7.7s | 7.8s | ⚠️ +127ms |
| nodeModulesSize | 53.2 MB | 53.2 MB | ⚠️ +1.52 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.39 kB | 7.39 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| index.html gzip | 916 B | 916 B | ✓ |
| link.html gzip | 924 B | 924 B | ✓ |
| withRouter.html gzip | 913 B | 913 B | ✓ |
| Overall change | 2.75 kB | 2.75 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 8.3s | 8.3s | ⚠️ +54ms |
| nodeModulesSize | 53.2 MB | 53.2 MB | ⚠️ +1.52 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.39 kB | 7.39 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _error.js gzip | 293 kB | 293 kB | ⚠️ +57 B |
| 404.html gzip | 1.32 kB | 1.32 kB | ✓ |
| hooks.html gzip | 957 B | 957 B | ✓ |
| index.js gzip | 293 kB | 294 kB | ⚠️ +438 B |
| link.js gzip | 301 kB | 301 kB | ⚠️ +331 B |
| routerDirect.js gzip | 300 kB | 299 kB | -555 B |
| withRouter.js gzip | 300 kB | 300 kB | -54 B |
| Overall change | 1.49 MB | 1.49 MB | ⚠️ +217 B |

</details>

</details>

**Comment by vvo** [comment]
ok @timneutkens I've fixed the code here and added a test as for --inspect.

cc @aleclarson this uses your regex commit too.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 10.9s | 11s | ⚠️ +94ms |
| nodeModulesSize | 53.2 MB | 53.2 MB | ⚠️ +1.52 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.39 kB | 7.39 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| index.html gzip | 916 B | 916 B | ✓ |
| link.html gzip | 924 B | 924 B | ✓ |
| withRouter.html gzip | 913 B | 913 B | ✓ |
| Overall change | 2.75 kB | 2.75 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 12s | 11.9s | -57ms |
| nodeModulesSize | 53.2 MB | 53.2 MB | ⚠️ +1.52 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.39 kB | 7.39 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _error.js gzip | 294 kB | 293 kB | -679 B |
| 404.html gzip | 1.32 kB | 1.32 kB | ✓ |
| hooks.html gzip | 957 B | 957 B | ✓ |
| index.js gzip | 294 kB | 293 kB | -187 B |
| link.js gzip | 301 kB | 301 kB | -113 B |
| routerDirect.js gzip | 299 kB | 299 kB | -20 B |
| withRouter.js gzip | 300 kB | 300 kB | ⚠️ +304 B |
| Overall change | 1.49 MB | 1.49 MB | -695 B |

</details>

</details>

**Comment by vvo** [comment]
Side note: I wonder if we should maybe re-introduce the --inspect flag or better like a --debug flag that would then start the debugger internally. So we would not even have to fiddle with NODE_OPTIONS internally. Not sure this is doable though.

Also, I did try to go using https://github.com/zeit/arg but:
- no easy way to handle --inspect --inspect=value (it's either one or the other)
- no way to turn the args back into a string (NODE_OPTIONS: String => arg => remove --inspect => NODE_OPTIONS: String)

So I went for the regex even if I am allergic (read: bad) to them :D. But @aleclarson did a good one

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 9.5s | 9.7s | ⚠️ +206ms |
| nodeModulesSize | 53.2 MB | 53.2 MB | ⚠️ +1.52 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.39 kB | 7.39 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| index.html gzip | 916 B | 916 B | ✓ |
| link.html gzip | 924 B | 924 B | ✓ |
| withRouter.html gzip | 913 B | 913 B | ✓ |
| Overall change | 2.75 kB | 2.75 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.6s | ⚠️ +399ms |
| nodeModulesSize | 53.2 MB | 53.2 MB | ⚠️ +1.52 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.39 kB | 7.39 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _error.js gzip | 293 kB | 294 kB | ⚠️ +263 B |
| 404.html gzip | 1.32 kB | 1.32 kB | ✓ |
| hooks.html gzip | 957 B | 957 B | ✓ |
| index.js gzip | 293 kB | 294 kB | ⚠️ +276 B |
| link.js gzip | 301 kB | 301 kB | -336 B |
| routerDirect.js gzip | 299 kB | 300 kB | ⚠️ +420 B |
| withRouter.js gzip | 300 kB | 300 kB | -23 B |
| Overall change | 1.49 MB | 1.49 MB | ⚠️ +600 B |

</details>

</details>

**Comment by GuillaumeDesforges** [comment]
Looking forward for this fix, thank you so much.
Any idea for a release date ?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 11.7s | 11.4s | -275ms |
| nodeModulesSize | 47.7 MB | 47.7 MB | ⚠️ +1.52 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.25 kB | 6.25 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c6c1.js gzip | 10.1 kB | 10.1 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.3 kB | 56.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.24 kB | 1.24 kB | ✓ |
| _error.js gzip | 3.15 kB | 3.15 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.03 kB | 2.03 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.86 kB | 7.86 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| index.html gzip | 919 B | 919 B | ✓ |
| link.html gzip | 927 B | 927 B | ✓ |
| withRouter.html gzip | 917 B | 917 B | ✓ |
| Overall change | 2.76 kB | 2.76 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.5s | ⚠️ +76ms |
| nodeModulesSize | 47.7 MB | 47.7 MB | ⚠️ +1.52 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.25 kB | 6.25 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c6c1.js gzip | 10.1 kB | 10.1 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.3 kB | 56.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.js gzip | 1.24 kB | 1.24 kB | ✓ |
| _error.js gzip | 3.15 kB | 3.15 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.03 kB | 2.03 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.86 kB | 7.86 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js fix/next-dev-server-inspect | Change |
| - | - | - | - |
| _error.js gzip | 233 kB | 232 kB | -415 B |
| 404.html gzip | 1.33 kB | 1.33 kB | ✓ |
| hooks.html gzip | 960 B | 960 B | ✓ |
| index.js gzip | 232 kB | 233 kB | ⚠️ +130 B |
| link.js gzip | 242 kB | 243 kB | ⚠️ +285 B |
| routerDirect.js gzip | 241 kB | 241 kB | -66 B |
| withRouter.js gzip | 240 kB | 241 kB | ⚠️ +280 B |
| Overall change | 1.19 MB | 1.19 MB | ⚠️ +214 B |

</details>

</details>

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
Thanks @vvo @aleclarson! I think you could bring back the `--inspect` flag if you want to spend time on it 👍

**Comment by Hainesy** [comment]
I have just tested this on the latest 9.3.5-canary.3, and I still get loads of 'address already in use' errors.

```
$ npm run dev

> pickle-ui@1.0.0 dev /some-folder
> NODE_OPTIONS='--inspect' next dev

Debugger listening on ws://127.0.0.1:9229/e84f4f75-3874-4628-b6eb-707be02f0bfe
For help, see: https://nodejs.org/en/docs/inspector
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
Defining routes from exportPathMap
Starting inspector on 127.0.0.1:9229 failed: address already in use
[ info ]  bundled successfully, waiting for typecheck results...
[ wait ]  compiling ...
Starting inspector on 127.0.0.1:9229 failed: address already in use
[ info ]  bundled successfully, waiting for typecheck results...
[ event ] build page: /next/dist/pages/_error
[ wait ]  compiling ...
Starting inspector on 127.0.0.1:9229 failed: address already in use
[ info ]  bundled successfully, waiting for typecheck results...
[ event ] build page: /
[ wait ]  compiling ...
Starting inspector on 127.0.0.1:9229 failed: address already in use
[ info ]  bundled successfully, waiting for typecheck results...
Starting inspector on 127.0.0.1:9229 failed: address already in use
```

**Comment by GabrielDelepine** [comment]
As @Hainesy, I keep having the warning in `9.3.5-canary.6`

Screenshot 2020-04-10 at 18 39 43

Here is my VSCODE debug config
```json
{
    "type": "node",
    "request": "launch",
    "name": "Next: npm dev",
    "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/next",
    "env": {
        "NODE_OPTIONS": "--inspect=9669"
    },
    "port": 9669,
    "console": "integratedTerminal"
},
```
