### PR TITLE
Fix index.js for API routes

### LINKED ISSUE #8111: 500 on /pages/api/index.js on Zeit Now
# Bug report

## Describe the bug

You get a 500 with code in `/pages/api/index.js` but not if you put the same code in `/pages/api/foo.js`

## To Reproduce

Put the following code in `/pages/api/index.js`:
```js
export default (req, res) => {
  res.setHeader('Content-Type', 'application/json');
  res.statusCode = 200;
  res.end(JSON.stringify({ name: 'Nextjs' }));
};
```

Deploy to Now, and go to `deployment.endpoint/api`, you'll get a 500 (complaining that res.setHeader is not a function).

Hope I'm not missing something. Cheers!

### PR DESCRIPTION
**Pull request by huv1k**
This fixes the problem with `/pages/api/index.js` not creating serverless function. Fixes #8111

### CODE REVIEW

File: packages/next/lib/constants.ts [hunk 1]
```diff
@@ -15,6 +15,9 @@ export const NEXT_PROJECT_ROOT_DIST_SERVER = join(
   'server'
 )
 
+// Regex for API routes
+export const API_ROUTE = /^\/api(?:\/.*)?$/
```
Comment (Timer) [inline packages/next/lib/constants.ts]:
```suggestion
export const API_ROUTE = /^\/api(?:\/|$)/
```

Nit, but I think this regex is more clear.

**Review by Timer — CHANGES_REQUESTED** [review]

File: packages/next/lib/constants.ts (hunk 1 above)
Comment (huv1k) [reply packages/next/lib/constants.ts]: This is not going to work for `/api/users`.

**Review by Timer — APPROVED** [review]
