### PR TITLE
fixing observing paint types in safari bug

### LINKED ISSUE #10075: PerformanceObserver code is broken on canary only
see title

Safari:
>TypeError: entryTypes contained only unsupported types

QQ:
image

### PR DESCRIPTION
**Pull request by prateekbh**
- checks for supported entry type before observing them

fixes #10075

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| buildDuration | 13.5s | 13.3s | -145ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +222 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.14 kB | ⚠️ +25 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +25 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.2 kB | ⚠️ +23 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +23 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ✓ |
| link.html gzip | 1.03 kB | 1.03 kB | ⚠️ +1 B |
| withRouter.html gzip | 1.01 kB | 1.01 kB | ✓ |
| Overall change | 3.06 kB | 3.06 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -874,11 +874,11 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!('PerformanceObserver' in window)) {
-            window.addEventListener('load', function() {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
+          if (
+            'PerformanceObserver' in window &&
+            PerformanceObserver.supportedEntryTypes &&
+            PerformanceObserver.supportedEntryTypes.includes('paint')
+          ) {
             performance.getEntriesByType('paint').forEach(onPerfEntry) // Start an observer to catch any paint metrics which may fire _after_
             // the load event is fired on the window
 
@@ -888,6 +888,10 @@
             observer.observe({
               entryTypes: ['paint'],
             })
+          } else {
+            window.addEventListener('load', function() {
+              performance.getEntriesByType('paint').forEach(onPerfEntry)
+            })
           }
         }
       }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -588,11 +588,11 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!('PerformanceObserver' in window)) {
-            window.addEventListener('load', () => {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
+          if (
+            'PerformanceObserver' in window &&
+            PerformanceObserver.supportedEntryTypes &&
+            PerformanceObserver.supportedEntryTypes.includes('paint')
+          ) {
             performance.getEntriesByType('paint').forEach(onPerfEntry) // Start an observer to catch any paint metrics which may fire _after_
             // the load event is fired on the window
 
@@ -602,6 +602,10 @@
             observer.observe({
               entryTypes: ['paint'],
             })
+          } else {
+            window.addEventListener('load', () => {
+              performance.getEntriesByType('paint').forEach(onPerfEntry)
+            })
           }
         }
       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-ab7e878f086add3e9a36.module.js"
+      href="/_next/static/runtime/main-79999fdb009776ea8589.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-c9f0aaf2812fb05b1b82.js"
+      src="/_next/static/runtime/main-7629b784c28350870c30.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-ab7e878f086add3e9a36.module.js"
+      src="/_next/static/runtime/main-79999fdb009776ea8589.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-ab7e878f086add3e9a36.module.js"
+      href="/_next/static/runtime/main-79999fdb009776ea8589.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-c9f0aaf2812fb05b1b82.js"
+      src="/_next/static/runtime/main-7629b784c28350870c30.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-ab7e878f086add3e9a36.module.js"
+      src="/_next/static/runtime/main-79999fdb009776ea8589.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-ab7e878f086add3e9a36.module.js"
+      href="/_next/static/runtime/main-79999fdb009776ea8589.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-c9f0aaf2812fb05b1b82.js"
+      src="/_next/static/runtime/main-7629b784c28350870c30.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-ab7e878f086add3e9a36.module.js"
+      src="/_next/static/runtime/main-79999fdb009776ea8589.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| buildDuration | 14s | 14s | ⚠️ +58ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +222 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.14 kB | ⚠️ +25 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +25 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.2 kB | ⚠️ +23 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +23 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +3 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | ✓ |
| index.js gzip | 78 kB | 78 kB | ⚠️ +3 B |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +3 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +3 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +3 B |
| Overall change | 393 kB | 393 kB | ⚠️ +15 B |

</details>

</details>


Commit: 3f40b11558b8fbff2311a8b675bd07c0fb830138

File: packages/next/client/index.js [hunk 1]
```diff
@@ -307,6 +307,10 @@ function renderReactElement(reactEl, domEl) {
         list.getEntries().forEach(onPerfEntry)
       })
       observer.observe({ entryTypes: ['paint'] })
+    } else {
+      window.addEventListener('load', () => {
```
Comment (philipwalton) [inline packages/next/client/index.js]: If you use the `buffered: true` flag with `PerformanceObserver`, then you shouldn't need to wait until load, nor should you need to use the performance timeline at all (i.e. `performance.getEntriesByType()`).

And since Chrome/Chromium is the only browser to support paint timing, then you maybe as well just use the buffered flag (supported since M77) as shown in this example: https://web.dev/fcp/#measure-fcp-in-javascript

Also, as per our conversation, you'll probably want to wrap this in a try/catch to prevent an error in Safari ([this issue](https://github.com/GoogleChrome/web.dev/issues/2078) tracks updating the web.dev examples to account for the Safari error issue).

**Review by philipwalton — CHANGES_REQUESTED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| buildDuration | 13.5s | 13.3s | -142ms |
| nodeModulesSize | 49 MB | 49 MB | -303 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.11 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.17 kB | -10 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -10 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | -2 B |
| withRouter.html gzip | 1.01 kB | 1.01 kB | -1 B |
| Overall change | 3.07 kB | 3.06 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -873,19 +873,18 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!('PerformanceObserver' in window)) {
-            window.addEventListener('load', function() {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
-            performance.getEntriesByType('paint').forEach(onPerfEntry) // Start an observer to catch any paint metrics which may fire _after_
-            // the load event is fired on the window
-
+          try {
             var observer = new PerformanceObserver(function(list) {
               list.getEntries().forEach(onPerfEntry)
-            })
+            }) // Start observing paint entry types.
+
             observer.observe({
-              entryTypes: ['paint'],
+              type: 'paint',
+              buffered: true,
+            })
+          } catch (e) {
+            window.addEventListener('load', function() {
+              performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
           }
         }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -587,19 +587,18 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!('PerformanceObserver' in window)) {
-            window.addEventListener('load', () => {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
-            performance.getEntriesByType('paint').forEach(onPerfEntry) // Start an observer to catch any paint metrics which may fire _after_
-            // the load event is fired on the window
-
+          try {
             var observer = new PerformanceObserver(list => {
               list.getEntries().forEach(onPerfEntry)
-            })
+            }) // Start observing paint entry types.
+
             observer.observe({
-              entryTypes: ['paint'],
+              type: 'paint',
+              buffered: true,
+            })
+          } catch (e) {
+            window.addEventListener('load', () => {
+              performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
           }
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-99b0cb5e34f4c0acb752.module.js"
+      href="/_next/static/runtime/main-d13073a1c41c3110ea33.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-f1eb419eab6ba464f0e4.js"
+      src="/_next/static/runtime/main-92d7db062de553082ab9.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-99b0cb5e34f4c0acb752.module.js"
+      src="/_next/static/runtime/main-d13073a1c41c3110ea33.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-99b0cb5e34f4c0acb752.module.js"
+      href="/_next/static/runtime/main-d13073a1c41c3110ea33.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-f1eb419eab6ba464f0e4.js"
+      src="/_next/static/runtime/main-92d7db062de553082ab9.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-99b0cb5e34f4c0acb752.module.js"
+      src="/_next/static/runtime/main-d13073a1c41c3110ea33.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-99b0cb5e34f4c0acb752.module.js"
+      href="/_next/static/runtime/main-d13073a1c41c3110ea33.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-f1eb419eab6ba464f0e4.js"
+      src="/_next/static/runtime/main-92d7db062de553082ab9.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-99b0cb5e34f4c0acb752.module.js"
+      src="/_next/static/runtime/main-d13073a1c41c3110ea33.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.9s | ⚠️ +160ms |
| nodeModulesSize | 49 MB | 49 MB | -303 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.11 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.17 kB | -10 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -10 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +4 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | -1 B |
| index.js gzip | 78 kB | 78 kB | ⚠️ +3 B |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +5 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +4 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +4 B |
| Overall change | 393 kB | 393 kB | ⚠️ +19 B |

</details>

</details>


Commit: 21fcfc354d1c592597d8c7d3494eee46a5ecb79d

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.5s | -163ms |
| nodeModulesSize | 49 MB | 49 MB | -303 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.11 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.17 kB | -10 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -10 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | -2 B |
| withRouter.html gzip | 1.01 kB | 1.01 kB | -1 B |
| Overall change | 3.07 kB | 3.06 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -873,19 +873,18 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!('PerformanceObserver' in window)) {
-            window.addEventListener('load', function() {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
-            performance.getEntriesByType('paint').forEach(onPerfEntry) // Start an observer to catch any paint metrics which may fire _after_
-            // the load event is fired on the window
-
+          try {
             var observer = new PerformanceObserver(function(list) {
               list.getEntries().forEach(onPerfEntry)
-            })
+            }) // Start observing paint entry types.
+
             observer.observe({
-              entryTypes: ['paint'],
+              type: 'paint',
+              buffered: true,
+            })
+          } catch (e) {
+            window.addEventListener('load', function() {
+              performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
           }
         }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -587,19 +587,18 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!('PerformanceObserver' in window)) {
-            window.addEventListener('load', () => {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
-            performance.getEntriesByType('paint').forEach(onPerfEntry) // Start an observer to catch any paint metrics which may fire _after_
-            // the load event is fired on the window
-
+          try {
             var observer = new PerformanceObserver(list => {
               list.getEntries().forEach(onPerfEntry)
-            })
+            }) // Start observing paint entry types.
+
             observer.observe({
-              entryTypes: ['paint'],
+              type: 'paint',
+              buffered: true,
+            })
+          } catch (e) {
+            window.addEventListener('load', () => {
+              performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
           }
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-99b0cb5e34f4c0acb752.module.js"
+      href="/_next/static/runtime/main-d13073a1c41c3110ea33.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-f1eb419eab6ba464f0e4.js"
+      src="/_next/static/runtime/main-92d7db062de553082ab9.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-99b0cb5e34f4c0acb752.module.js"
+      src="/_next/static/runtime/main-d13073a1c41c3110ea33.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-99b0cb5e34f4c0acb752.module.js"
+      href="/_next/static/runtime/main-d13073a1c41c3110ea33.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-f1eb419eab6ba464f0e4.js"
+      src="/_next/static/runtime/main-92d7db062de553082ab9.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-99b0cb5e34f4c0acb752.module.js"
+      src="/_next/static/runtime/main-d13073a1c41c3110ea33.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-99b0cb5e34f4c0acb752.module.js"
+      href="/_next/static/runtime/main-d13073a1c41c3110ea33.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-f1eb419eab6ba464f0e4.js"
+      src="/_next/static/runtime/main-92d7db062de553082ab9.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-99b0cb5e34f4c0acb752.module.js"
+      src="/_next/static/runtime/main-d13073a1c41c3110ea33.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| buildDuration | 13.1s | 13.1s | -2ms |
| nodeModulesSize | 49 MB | 49 MB | -303 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.11 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.17 kB | -10 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -10 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +4 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | -1 B |
| index.js gzip | 78 kB | 78 kB | ⚠️ +3 B |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +5 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +4 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +4 B |
| Overall change | 393 kB | 393 kB | ⚠️ +19 B |

</details>

</details>


Commit: cdb7463560f5676f88eb226e65b02e97b346599b

**Comment by prateekbh** [comment]
@Timer not sure why this has failed

**Review by Timer — APPROVED** [review]
This looks great. Should pass on re-run. Thanks!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.3s | -38ms |
| nodeModulesSize | 49 MB | 49 MB | -303 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.11 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.17 kB | -10 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -10 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ⚠️ +1 B |
| link.html gzip | 1.03 kB | 1.03 kB | ✓ |
| withRouter.html gzip | 1.02 kB | 1.02 kB | ⚠️ +1 B |
| Overall change | 3.07 kB | 3.07 kB | ⚠️ +2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -873,19 +873,18 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!('PerformanceObserver' in window)) {
-            window.addEventListener('load', function() {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
-            performance.getEntriesByType('paint').forEach(onPerfEntry) // Start an observer to catch any paint metrics which may fire _after_
-            // the load event is fired on the window
-
+          try {
             var observer = new PerformanceObserver(function(list) {
               list.getEntries().forEach(onPerfEntry)
-            })
+            }) // Start observing paint entry types.
+
             observer.observe({
-              entryTypes: ['paint'],
+              type: 'paint',
+              buffered: true,
+            })
+          } catch (e) {
+            window.addEventListener('load', function() {
+              performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
           }
         }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -587,19 +587,18 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!('PerformanceObserver' in window)) {
-            window.addEventListener('load', () => {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
-            performance.getEntriesByType('paint').forEach(onPerfEntry) // Start an observer to catch any paint metrics which may fire _after_
-            // the load event is fired on the window
-
+          try {
             var observer = new PerformanceObserver(list => {
               list.getEntries().forEach(onPerfEntry)
-            })
+            }) // Start observing paint entry types.
+
             observer.observe({
-              entryTypes: ['paint'],
+              type: 'paint',
+              buffered: true,
+            })
+          } catch (e) {
+            window.addEventListener('load', () => {
+              performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
           }
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-53129cb44048f8bf9b4a.module.js"
+      href="/_next/static/runtime/main-f2232532cc1c81bbfde1.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-bff58951632f207cd6dd.js"
+      src="/_next/static/runtime/main-bc401d4e0254cc2783d0.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-53129cb44048f8bf9b4a.module.js"
+      src="/_next/static/runtime/main-f2232532cc1c81bbfde1.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-53129cb44048f8bf9b4a.module.js"
+      href="/_next/static/runtime/main-f2232532cc1c81bbfde1.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-bff58951632f207cd6dd.js"
+      src="/_next/static/runtime/main-bc401d4e0254cc2783d0.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-53129cb44048f8bf9b4a.module.js"
+      src="/_next/static/runtime/main-f2232532cc1c81bbfde1.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-53129cb44048f8bf9b4a.module.js"
+      href="/_next/static/runtime/main-f2232532cc1c81bbfde1.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-bff58951632f207cd6dd.js"
+      src="/_next/static/runtime/main-bc401d4e0254cc2783d0.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-53129cb44048f8bf9b4a.module.js"
+      src="/_next/static/runtime/main-f2232532cc1c81bbfde1.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| buildDuration | 13.5s | 13.6s | ⚠️ +94ms |
| nodeModulesSize | 49 MB | 49 MB | -303 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.11 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.17 kB | -10 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -10 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js perf-entry-safari-bug-fix | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +1 B |
| hooks.html gzip | 1.05 kB | 1.06 kB | ⚠️ +2 B |
| index.js gzip | 78 kB | 78 kB | ⚠️ +1 B |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +1 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ✓ |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ✓ |
| Overall change | 393 kB | 393 kB | ⚠️ +5 B |

</details>

</details>


Commit: 12047afd77cb8d937c63c9c4853f3952049ba905
