### PR TITLE
Turbopack: fix `sideEffects` matching for non-relative globs

### LINKED ISSUE #66348: Refractor languages missing when Turbopack is enabled
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/serene-napier-go8s7s

### To Reproduce

1. Install `react-markdown` and `rehype-prism-plus`.
2. Set up a page that renders some Markdown with `<ReactMarkdown rehypePlugins={[rehypePrism]}>{markdown}</ReactMarkdown>`, where `markdown` is a string containing code with `json` as the specified language.
3. Run the dev server with the `--turbo` flag.

### Current vs. Expected behavior

If you run the dev server without the `--turbo` flag, the JSON renders as expected.

With the `--turbo` flag, the page fails to render, and instead you get this error:

```
Error: Unknown language: `json` is not registered

Call stack:

Refractor.highlight
node_modules/.pnpm/refractor@4.8.1/node_modules/refractor/lib/core.js (99:13)
highlight
node_modules/.pnpm/rehype-prism-plus@2.0.0/node_modules/rehype-prism-plus/src/generator.js (224:37)
...
```

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 15.0.0-canary.0 // Latest available version is detected (15.0.0-canary.0).
  eslint-config-next: N/A
  react: 19.0.0-rc-6f23540c7d-20240528
  react-dom: 19.0.0-rc-6f23540c7d-20240528
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

According to the [rehype-prism-plus README](https://github.com/timlrx/rehype-prism-plus), the default export of `rehype-prism-plus` works with all languages supported by refractor. I suspect that what's happening here is some overly aggressive tree-shaking on Turbopack's part, where it's removing the refractor language imports that Webpack preserves.

### PR DESCRIPTION
**Pull request by mischnic**
Previously, `"sideEffects": ["lib/common.js"]` never matched.

Closes #66348
Closes PACK-4241

### CODE REVIEW

**Comment by mischnic** [comment]
* **#77693** <a href="https://app.graphite.dev/github/pr/vercel/next.js/77693?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/vercel/next.js/77693?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js mischnic/side-effects-dot-slash | Change |
| - | - | - | - |
| buildDuration | 18.8s | 17.4s | N/A |
| buildDurationCached | 16.2s | 13.7s | N/A |
| nodeModulesSize | 392 MB | 392 MB | ✓ |
| nextStartRea..uration (ms) | 436ms | 460ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js mischnic/side-effects-dot-slash | Change |
| - | - | - | - |
| 1733-HASH.js gzip | 45.9 kB | 46.5 kB | ⚠️ +579 B |
| 194b18f3-HASH.js gzip | 53.1 kB | 53.1 kB | N/A |
| 2192.HASH.js gzip | 169 B | 171 B | N/A |
| 4719-HASH.js gzip | 5.47 kB | 5.44 kB | N/A |
| framework-HASH.js gzip | 57.4 kB | 57.4 kB | N/A |
| main-app-HASH.js gzip | 248 B | 250 B | N/A |
| main-HASH.js gzip | 33.7 kB | 33.7 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 45.9 kB | 46.5 kB | ⚠️ +579 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js mischnic/side-effects-dot-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js mischnic/side-effects-dot-slash | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 510 B | 510 B | ✓ |
| css-HASH.js gzip | 344 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | N/A |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 364 B | N/A |
| hooks-HASH.js gzip | 392 B | 391 B | N/A |
| image-HASH.js gzip | 4.69 kB | 4.67 kB | N/A |
| index-HASH.js gzip | 267 B | 267 B | ✓ |
| link-HASH.js gzip | 2.53 kB | 2.53 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 325 B | N/A |
| script-HASH.js gzip | 396 B | 396 B | ✓ |
| withRouter-HASH.js gzip | 325 B | 325 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 2.25 kB | 2.25 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js mischnic/side-effects-dot-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 750 B | 750 B | ✓ |
| Overall change | 750 B | 750 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js mischnic/side-effects-dot-slash | Change |
| - | - | - | - |
| index.html gzip | 524 B | 523 B | N/A |
| link.html gzip | 536 B | 539 B | N/A |
| withRouter.html gzip | 519 B | 521 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js mischnic/side-effects-dot-slash | Change |
| - | - | - | - |
| edge-ssr.js gzip | 135 kB | 135 kB | N/A |
| page.js gzip | 216 kB | 211 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js mischnic/side-effects-dot-slash | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 676 B | 673 B | N/A |
| middleware-r..fest.js gzip | 155 B | 157 B | N/A |
| middleware.js gzip | 32 kB | 32.2 kB | ⚠️ +214 B |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 32.9 kB | 33.1 kB | ⚠️ +214 B |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js mischnic/side-effects-dot-slash | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 375 kB | 375 kB | ✓ |
| app-page-exp..prod.js gzip | 143 kB | 143 kB | ✓ |
| app-page-tur..prod.js gzip | 156 kB | 156 kB | ✓ |
| app-page-tur..prod.js gzip | 152 kB | 152 kB | ✓ |
| app-page.run...dev.js gzip | 364 kB | 364 kB | ✓ |
| app-page.run..prod.js gzip | 139 kB | 139 kB | ✓ |
| app-route-ex...dev.js gzip | 40 kB | 40 kB | ✓ |
| app-route-ex..prod.js gzip | 26.1 kB | 26.1 kB | ✓ |
| app-route-tu..prod.js gzip | 26.1 kB | 26.1 kB | ✓ |
| app-route-tu..prod.js gzip | 25.9 kB | 25.9 kB | ✓ |
| app-route.ru...dev.js gzip | 39.7 kB | 39.7 kB | ✓ |
| app-route.ru..prod.js gzip | 25.9 kB | 25.9 kB | ✓ |
| dist_client_...dev.js gzip | 356 B | 356 B | ✓ |
| dist_client_...dev.js gzip | 349 B | 349 B | ✓ |
| pages-api-tu..prod.js gzip | 9.76 kB | 9.76 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.9 kB | 11.9 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.75 kB | 9.75 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 31.6 kB | 31.6 kB | ✓ |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | ✓ |
| server.runti..prod.js gzip | 62.5 kB | 62.5 kB | ✓ |
| Overall change | 1.68 MB | 1.68 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js mischnic/side-effects-dot-slash | Change |
| - | - | - | - |
| 0.pack gzip | 2.16 MB | 2.16 MB | ⚠️ +221 B |
| index.pack gzip | 77 kB | 77.6 kB | ⚠️ +579 B |
| Overall change | 2.24 MB | 2.24 MB | ⚠️ +800 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>css-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [9813],
   {
-    /***/ 1586: /***/ (
+    /***/ 2628: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/css",
         function () {
-          return __webpack_require__(4362);
+          return __webpack_require__(8707);
         },
       ]);
       if (false) {
@@ -18,14 +18,7 @@
       /***/
     },
 
-    /***/ 4350: /***/ (module) => {
-      // extracted by mini-css-extract-plugin
-      module.exports = { helloWorld: "css_helloWorld__aUdUq" };
-
-      /***/
-    },
-
-    /***/ 4362: /***/ (
+    /***/ 8707: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -39,7 +32,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(5640);
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(4350);
+        __webpack_require__(9080);
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           _css_module_css__WEBPACK_IMPORTED_MODULE_1__
@@ -58,13 +51,20 @@
 
       /***/
     },
+
+    /***/ 9080: /***/ (module) => {
+      // extracted by mini-css-extract-plugin
+      module.exports = { helloWorld: "css_helloWorld__aUdUq" };
+
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(1586)
+      __webpack_exec__(2628)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -1,17 +1,117 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [2291],
   {
-    /***/ 283: /***/ (
+    /***/ 2001: /***/ (
+      __unused_webpack_module,
+      __webpack_exports__,
+      __webpack_require__
+    ) => {
+      "use strict";
+      __webpack_require__.r(__webpack_exports__);
+      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
+        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
+        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
+        /* harmony export */
+      });
+      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
+        __webpack_require__(5640);
+      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ =
+        __webpack_require__(9553);
+      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default =
+        /*#__PURE__*/ __webpack_require__.n(
+          next_dynamic__WEBPACK_IMPORTED_MODULE_1__
+        );
+
+      const DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
+        () =>
+          __webpack_require__
+            .e(/* import() */ 8042)
+            .then(__webpack_require__.bind(__webpack_require__, 5661))
+            .then((mod) => mod.Hello),
+        {
+          loadableGenerated: {
+            webpack: () => [/*require.resolve*/ 5661],
+          },
+        }
+      );
+      const Page = () =>
+        /*#__PURE__*/ (0, react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)(
+          react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.Fragment,
+          {
+            children: [
+              /*#__PURE__*/ (0,
+              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("p", {
+                children: "testing next/dynamic size",
+              }),
+              /*#__PURE__*/ (0,
+              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
+                DynamicHello,
+                {}
+              ),
+            ],
+          }
+        );
+      var __N_SSP = true;
+      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = Page;
+
+      /***/
+    },
+
+    /***/ 2976: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/dynamic",
+        function () {
+          return __webpack_require__(2001);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 7807: /***/ (
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) => {
+      "use strict";
+      /* __next_internal_client_entry_do_not_use__  cjs */
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "LoadableContext", {
+        enumerable: true,
+        get: function () {
+          return LoadableContext;
+        },
+      });
+      const _interop_require_default = __webpack_require__(1532);
+      const _react = /*#__PURE__*/ _interop_require_default._(
+        __webpack_require__(148)
+      );
+      const LoadableContext = _react.default.createContext(null);
+      if (false) {
+      } //# sourceMappingURL=loadable-context.shared-runtime.js.map
+
+      /***/
+    },
+
+    /***/ 9553: /***/ (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) => {
-      module.exports = __webpack_require__(6990);
+      module.exports = __webpack_require__(9986);
 
       /***/
     },
 
-    /***/ 505: /***/ (
+    /***/ 9829: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -53,7 +153,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       const _react = /*#__PURE__*/ _interop_require_default._(
         __webpack_require__(148)
       );
-      const _loadablecontextsharedruntime = __webpack_require__(6179);
+      const _loadablecontextsharedruntime = __webpack_require__(7807);
       function resolve(obj) {
         return obj && obj.default ? obj.default : obj;
       }
@@ -288,90 +388,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       /***/
     },
 
-    /***/ 5703: /***/ (
-      __unused_webpack_module,
-      __webpack_exports__,
-      __webpack_require__
-    ) => {
-      "use strict";
-      __webpack_require__.r(__webpack_exports__);
-      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
-        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
-        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
-        /* harmony export */
-      });
-      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(5640);
-      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(283);
-      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default =
-        /*#__PURE__*/ __webpack_require__.n(
-          next_dynamic__WEBPACK_IMPORTED_MODULE_1__
-        );
-
-      const DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
-        () =>
-          __webpack_require__
-            .e(/* import() */ 2192)
-            .then(__webpack_require__.bind(__webpack_require__, 2192))
-            .then((mod) => mod.Hello),
-        {
-          loadableGenerated: {
-            webpack: () => [/*require.resolve*/ 2192],
-          },
-        }
-      );
-      const Page = () =>
-        /*#__PURE__*/ (0, react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)(
-          react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.Fragment,
-          {
-            children: [
-              /*#__PURE__*/ (0,
-              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("p", {
-                children: "testing next/dynamic size",
-              }),
-              /*#__PURE__*/ (0,
-              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
-                DynamicHello,
-                {}
-              ),
-            ],
-          }
-        );
-      var __N_SSP = true;
-      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = Page;
-
-      /***/
-    },
-
-    /***/ 6179: /***/ (
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) => {
-      "use strict";
-      /* __next_internal_client_entry_do_not_use__  cjs */
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "LoadableContext", {
-        enumerable: true,
-        get: function () {
-          return LoadableContext;
-        },
-      });
-      const _interop_require_default = __webpack_require__(1532);
-      const _react = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(148)
-      );
-      const LoadableContext = _react.default.createContext(null);
-      if (false) {
-      } //# sourceMappingURL=loadable-context.shared-runtime.js.map
-
-      /***/
-    },
-
-    /***/ 6990: /***/ (module, exports, __webpack_require__) => {
+    /***/ 9986: /***/ (module, exports, __webpack_require__) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -404,7 +421,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
         __webpack_require__(148)
       );
       const _loadablesharedruntime = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(505)
+        __webpack_require__(9829)
       );
       const isServerSide = "object" === "undefined";
       // Normalize loader to return the module as form { default: Component } for `React.lazy`.
@@ -504,30 +521,13 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
 
       /***/
     },
-
-    /***/ 9254: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/dynamic",
-        function () {
-          return __webpack_require__(5703);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(9254)
+      __webpack_exec__(2976)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>hooks-HASH.js</strong></summary>

```diff
@@ -1,24 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [9804],
   {
-    /***/ 1664: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/hooks",
-        function () {
-          return __webpack_require__(6130);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 6130: /***/ (
+    /***/ 4756: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -76,13 +59,30 @@
 
       /***/
     },
+
+    /***/ 5426: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/hooks",
+        function () {
+          return __webpack_require__(4756);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(1664)
+      __webpack_exec__(5426)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [2983],
   {
-    /***/ 2198: /***/ (
+    /***/ 264: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function () {
-          return __webpack_require__(3444);
+          return __webpack_require__(3594);
         },
       ]);
       if (false) {
@@ -18,7 +18,190 @@
       /***/
     },
 
-    /***/ 2514: /***/ (
+    /***/ 1206: /***/ (__unused_webpack_module, exports) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "default", {
+        enumerable: true,
+        get: function () {
+          return _default;
+        },
+      });
+      const DEFAULT_Q = 75;
+      function defaultLoader(param) {
+        let { config, src, width, quality } = param;
+        var _config_qualities;
+        if (false) {
+        }
+        const q =
+          quality ||
+          ((_config_qualities = config.qualities) == null
+            ? void 0
+            : _config_qualities.reduce((prev, cur) =>
+                Math.abs(cur - DEFAULT_Q) < Math.abs(prev - DEFAULT_Q)
+                  ? cur
+                  : prev
+              )) ||
+          DEFAULT_Q;
+        return (
+          config.path +
+          "?url=" +
+          encodeURIComponent(src) +
+          "&w=" +
+          width +
+          "&q=" +
+          q +
+          (src.startsWith("/_next/static/media/") && false ? 0 : "")
+        );
+      }
+      // We use this to determine if the import is the default loader
+      // or a custom loader defined by the user in next.config.js
+      defaultLoader.__next_img_default = true;
+      const _default = defaultLoader; //# sourceMappingURL=image-loader.js.map
+
+      /***/
+    },
+
+    /***/ 1765: /***/ (module, exports, __webpack_require__) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "useMergedRef", {
+        enumerable: true,
+        get: function () {
+          return useMergedRef;
+        },
+      });
+      const _react = __webpack_require__(148);
+      function useMergedRef(refA, refB) {
+        const cleanupA = (0, _react.useRef)(null);
+        const cleanupB = (0, _react.useRef)(null);
+        // NOTE: In theory, we could skip the wrapping if only one of the refs is non-null.
+        // (this happens often if the user doesn't pass a ref to Link/Form/Image)
+        // But this can cause us to leak a cleanup-ref into user code (e.g. via `<Link legacyBehavior>`),
+        // and the user might pass that ref into ref-merging library that doesn't support cleanup refs
+        // (because it hasn't been updated for React 19)
+        // which can then cause things to blow up, because a cleanup-returning ref gets called with `null`.
+        // So in practice, it's safer to be defensive and always wrap the ref, even on React 19.
+        return (0, _react.useCallback)(
+          (current) => {
+            if (current === null) {
+              const cleanupFnA = cleanupA.current;
+              if (cleanupFnA) {
+                cleanupA.current = null;
+                cleanupFnA();
+              }
+              const cleanupFnB = cleanupB.current;
+              if (cleanupFnB) {
+                cleanupB.current = null;
+                cleanupFnB();
+              }
+            } else {
+              if (refA) {
+                cleanupA.current = applyRef(refA, current);
+              }
+              if (refB) {
+                cleanupB.current = applyRef(refB, current);
+              }
+            }
+          },
+          [refA, refB]
+        );
+      }
+      function applyRef(refA, current) {
+        if (typeof refA === "function") {
+          const cleanup = refA(current);
+          if (typeof cleanup === "function") {
+            return cleanup;
+          } else {
+            return () => refA(null);
+          }
+        } else {
+          refA.current = current;
+          return () => {
+            refA.current = null;
+          };
+        }
+      }
+      if (
+        (typeof exports.default === "function" ||
+          (typeof exports.default === "object" && exports.default !== null)) &&
+        typeof exports.default.__esModule === "undefined"
+      ) {
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true,
+        });
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
+      } //# sourceMappingURL=use-merged-ref.js.map
+
+      /***/
+    },
+
+    /***/ 3353: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(5526);
+
+      /***/
+    },
+
+    /***/ 3594: /***/ (
+      __unused_webpack_module,
+      __webpack_exports__,
+      __webpack_require__
+    ) => {
+      "use strict";
+      // ESM COMPAT FLAG
+      __webpack_require__.r(__webpack_exports__);
+
+      // EXPORTS
+      __webpack_require__.d(__webpack_exports__, {
+        __N_SSP: () => /* binding */ __N_SSP,
+        default: () => /* binding */ pages_image,
+      });
+
+      // EXTERNAL MODULE: ./node_modules/.pnpm/react@19.1.0/node_modules/react/jsx-runtime.js
+      var jsx_runtime = __webpack_require__(5640);
+      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.1.0_react@19.1.0__react@19.1.0/node_modules/next/image.js
+      var next_image = __webpack_require__(3353);
+      var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // ./pages/nextjs.png
+      /* harmony default export */ const nextjs = {
+        src: "/_next/static/media/nextjs.cae0b805.png",
+        height: 1347,
+        width: 1626,
+        blurDataURL:
+          "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAHCAMAAAACh/xsAAAAD1BMVEX////x8fH6+vrb29vo6Oh8o70bAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAH0lEQVR4nGNgwARMjIyMjCAGCzMzMwsTRISJCcRABwAEcAAkLCQfgAAAAABJRU5ErkJggg==",
+        blurWidth: 8,
+        blurHeight: 7,
+      }; // ./pages/image.js
+      function ImagePage(props) {
+        return /*#__PURE__*/ (0, jsx_runtime.jsxs)(jsx_runtime.Fragment, {
+          children: [
+            /*#__PURE__*/ (0, jsx_runtime.jsx)("h1", {
+              children: "next/image example",
+            }),
+            /*#__PURE__*/ (0, jsx_runtime.jsx)(image_default(), {
+              src: nextjs,
+              placeholder: "blur",
+            }),
+          ],
+        });
+      }
+      var __N_SSP = true;
+      /* harmony default export */ const pages_image = ImagePage;
+
+      /***/
+    },
+
+    /***/ 3854: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -34,9 +217,9 @@
           return getImgProps;
         },
       });
-      const _warnonce = __webpack_require__(5127);
-      const _imageblursvg = __webpack_require__(4287);
-      const _imageconfig = __webpack_require__(2795);
+      const _warnonce = __webpack_require__(3603);
+      const _imageblursvg = __webpack_require__(7835);
+      const _imageconfig = __webpack_require__(6799);
       const VALID_LOADING_VALUES =
         /* unused pure expression or super */ null && [
           "lazy",
@@ -463,55 +646,69 @@
       /***/
     },
 
-    /***/ 3444: /***/ (
+    /***/ 5526: /***/ (
       __unused_webpack_module,
-      __webpack_exports__,
+      exports,
       __webpack_require__
     ) => {
       "use strict";
-      // ESM COMPAT FLAG
-      __webpack_require__.r(__webpack_exports__);
 
-      // EXPORTS
-      __webpack_require__.d(__webpack_exports__, {
-        __N_SSP: () => /* binding */ __N_SSP,
-        default: () => /* binding */ pages_image,
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
       });
-
-      // EXTERNAL MODULE: ./node_modules/.pnpm/react@19.1.0/node_modules/react/jsx-runtime.js
-      var jsx_runtime = __webpack_require__(5640);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.1.0_react@19.1.0__react@19.1.0/node_modules/next/image.js
-      var next_image = __webpack_require__(6359);
-      var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // ./pages/nextjs.png
-      /* harmony default export */ const nextjs = {
-        src: "/_next/static/media/nextjs.cae0b805.png",
-        height: 1347,
-        width: 1626,
-        blurDataURL:
-          "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAHCAMAAAACh/xsAAAAD1BMVEX////x8fH6+vrb29vo6Oh8o70bAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAH0lEQVR4nGNgwARMjIyMjCAGCzMzMwsTRISJCcRABwAEcAAkLCQfgAAAAABJRU5ErkJggg==",
-        blurWidth: 8,
-        blurHeight: 7,
-      }; // ./pages/image.js
-      function ImagePage(props) {
-        return /*#__PURE__*/ (0, jsx_runtime.jsxs)(jsx_runtime.Fragment, {
-          children: [
-            /*#__PURE__*/ (0, jsx_runtime.jsx)("h1", {
-              children: "next/image example",
-            }),
-            /*#__PURE__*/ (0, jsx_runtime.jsx)(image_default(), {
-              src: nextjs,
-              placeholder: "blur",
-            }),
-          ],
+      0 && 0;
+      function _export(target, all) {
+        for (var name in all)
+          Object.defineProperty(target, name, {
+            enumerable: true,
+            get: all[name],
+          });
+      }
+      _export(exports, {
+        default: function () {
+          return _default;
+        },
+        getImageProps: function () {
+          return getImageProps;
+        },
+      });
+      const _interop_require_default = __webpack_require__(1532);
+      const _getimgprops = __webpack_require__(3854);
+      const _imagecomponent = __webpack_require__(8350);
+      const _imageloader = /*#__PURE__*/ _interop_require_default._(
+        __webpack_require__(1206)
+      );
+      function getImageProps(imgProps) {
+        const { props } = (0, _getimgprops.getImgProps)(imgProps, {
+          defaultLoader: _imageloader.default,
+          // This is replaced by webpack define plugin
+          imgConf: {
+            deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
+            imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
+            path: "/_next/image",
+            loader: "default",
+            dangerouslyAllowSVG: false,
+            unoptimized: false,
+          },
         });
+        // Normally we don't care about undefined props because we pass to JSX,
+        // but this exported function could be used by the end user for anything
+        // so we delete undefined props to clean it up a little.
+        for (const [key, value] of Object.entries(props)) {
+          if (value === undefined) {
+            delete props[key];
+          }
+        }
+        return {
+          props,
+        };
       }
-      var __N_SSP = true;
-      /* harmony default export */ const pages_image = ImagePage;
+      const _default = _imagecomponent.Image; //# sourceMappingURL=image-external.js.map
 
       /***/
     },
 
-    /***/ 4287: /***/ (__unused_webpack_module, exports) => {
+    /***/ 7835: /***/ (__unused_webpack_module, exports) => {
       "use strict";
       /**
        * A shared function, used on both client and server, to generate a SVG blur placeholder.
@@ -566,85 +763,7 @@
       /***/
     },
 
-    /***/ 4985: /***/ (module, exports, __webpack_require__) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "useMergedRef", {
-        enumerable: true,
-        get: function () {
-          return useMergedRef;
-        },
-      });
-      const _react = __webpack_require__(148);
-      function useMergedRef(refA, refB) {
-        const cleanupA = (0, _react.useRef)(null);
-        const cleanupB = (0, _react.useRef)(null);
-        // NOTE: In theory, we could skip the wrapping if only one of the refs is non-null.
-        // (this happens often if the user doesn't pass a ref to Link/Form/Image)
-        // But this can cause us to leak a cleanup-ref into user code (e.g. via `<Link legacyBehavior>`),
-        // and the user might pass that ref into ref-merging library that doesn't support cleanup refs
-        // (because it hasn't been updated for React 19)
-        // which can then cause things to blow up, because a cleanup-returning ref gets called with `null`.
-        // So in practice, it's safer to be defensive and always wrap the ref, even on React 19.
-        return (0, _react.useCallback)(
-          (current) => {
-            if (current === null) {
-              const cleanupFnA = cleanupA.current;
-              if (cleanupFnA) {
-                cleanupA.current = null;
-                cleanupFnA();
-              }
-              const cleanupFnB = cleanupB.current;
-              if (cleanupFnB) {
-                cleanupB.current = null;
-                cleanupFnB();
-              }
-            } else {
-              if (refA) {
-                cleanupA.current = applyRef(refA, current);
-              }
-              if (refB) {
-                cleanupB.current = applyRef(refB, current);
-              }
-            }
-          },
-          [refA, refB]
-        );
-      }
-      function applyRef(refA, current) {
-        if (typeof refA === "function") {
-          const cleanup = refA(current);
-          if (typeof cleanup === "function") {
-            return cleanup;
-          } else {
-            return () => refA(null);
-          }
-        } else {
-          refA.current = current;
-          return () => {
-            refA.current = null;
-          };
-        }
-      }
-      if (
-        (typeof exports.default === "function" ||
-          (typeof exports.default === "object" && exports.default !== null)) &&
-        typeof exports.default.__esModule === "undefined"
-      ) {
-        Object.defineProperty(exports.default, "__esModule", {
-          value: true,
-        });
-        Object.assign(exports.default, exports);
-        module.exports = exports.default;
-      } //# sourceMappingURL=use-merged-ref.js.map
-
-      /***/
-    },
-
-    /***/ 5898: /***/ (module, exports, __webpack_require__) => {
+    /***/ 8350: /***/ (module, exports, __webpack_require__) => {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -666,17 +785,17 @@
         __webpack_require__(7897)
       );
       const _head = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(5207)
+        __webpack_require__(8843)
       );
-      const _getimgprops = __webpack_require__(2514);
-      const _imageconfig = __webpack_require__(2795);
-      const _imageconfigcontextsharedruntime = __webpack_require__(2349);
-      const _warnonce = __webpack_require__(5127);
-      const _routercontextsharedruntime = __webpack_require__(3556);
+      const _getimgprops = __webpack_require__(3854);
+      const _imageconfig = __webpack_require__(6799);
+      const _imageconfigcontextsharedruntime = __webpack_require__(3905);
+      const _warnonce = __webpack_require__(3603);
+      const _routercontextsharedruntime = __webpack_require__(6712);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(5970)
+        __webpack_require__(1206)
       );
-      const _usemergedref = __webpack_require__(4985);
+      const _usemergedref = __webpack_require__(1765);
       // This is replaced by webpack define plugin
       const configEnv = {
         deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
@@ -1002,132 +1121,13 @@
 
       /***/
     },
-
-    /***/ 5970: /***/ (__unused_webpack_module, exports) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "default", {
-        enumerable: true,
-        get: function () {
-          return _default;
-        },
-      });
-      const DEFAULT_Q = 75;
-      function defaultLoader(param) {
-        let { config, src, width, quality } = param;
-        var _config_qualities;
-        if (false) {
-        }
-        const q =
-          quality ||
-          ((_config_qualities = config.qualities) == null
-            ? void 0
-            : _config_qualities.reduce((prev, cur) =>
-                Math.abs(cur - DEFAULT_Q) < Math.abs(prev - DEFAULT_Q)
-                  ? cur
-                  : prev
-              )) ||
-          DEFAULT_Q;
-        return (
-          config.path +
-          "?url=" +
-          encodeURIComponent(src) +
-          "&w=" +
-          width +
-          "&q=" +
-          q +
-          (src.startsWith("/_next/static/media/") && false ? 0 : "")
-        );
-      }
-      // We use this to determine if the import is the default loader
-      // or a custom loader defined by the user in next.config.js
-      defaultLoader.__next_img_default = true;
-      const _default = defaultLoader; //# sourceMappingURL=image-loader.js.map
-
-      /***/
-    },
-
-    /***/ 6359: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(8986);
-
-      /***/
-    },
-
-    /***/ 8986: /***/ (
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      0 && 0;
-      function _export(target, all) {
-        for (var name in all)
-          Object.defineProperty(target, name, {
-            enumerable: true,
-            get: all[name],
-          });
-      }
-      _export(exports, {
-        default: function () {
-          return _default;
-        },
-        getImageProps: function () {
-          return getImageProps;
-        },
-      });
-      const _interop_require_default = __webpack_require__(1532);
-      const _getimgprops = __webpack_require__(2514);
-      const _imagecomponent = __webpack_require__(5898);
-      const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(5970)
-      );
-      function getImageProps(imgProps) {
-        const { props } = (0, _getimgprops.getImgProps)(imgProps, {
-          defaultLoader: _imageloader.default,
-          // This is replaced by webpack define plugin
-          imgConf: {
-            deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
-            imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
-            path: "/_next/image",
-            loader: "default",
-            dangerouslyAllowSVG: false,
-            unoptimized: false,
-          },
-        });
-        // Normally we don't care about undefined props because we pass to JSX,
-        // but this exported function could be used by the end user for anything
-        // so we delete undefined props to clean it up a little.
-        for (const [key, value] of Object.entries(props)) {
-          if (value === undefined) {
-            delete props[key];
-          }
-        }
-        return {
-          props,
-        };
-      }
-      const _default = _imagecomponent.Image; //# sourceMappingURL=image-external.js.map
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(2198)
+      __webpack_exec__(264)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>index-HASH.js</strong></summary>

```diff
@@ -1,7 +1,24 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [3332],
   {
-    /***/ 9418: /***/ (
+    /***/ 8230: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/",
+        function () {
+          return __webpack_require__(8696);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 8696: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -19,30 +36,13 @@
 
       /***/
     },
-
-    /***/ 9532: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/",
-        function () {
-          return __webpack_require__(9418);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(9532)
+      __webpack_exec__(8230)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -1,125 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [4672],
   {
-    /***/ 1854: /***/ (
-      __unused_webpack_module,
-      __webpack_exports__,
-      __webpack_require__
-    ) => {
-      "use strict";
-      __webpack_require__.r(__webpack_exports__);
-      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
-        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
-        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
-        /* harmony export */
-      });
-      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(5640);
-      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(8770);
-      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default =
-        /*#__PURE__*/ __webpack_require__.n(
-          next_link__WEBPACK_IMPORTED_MODULE_1__
-        );
-
-      function aLink(props) {
-        return /*#__PURE__*/ (0,
-        react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)("div", {
-          children: [
-            /*#__PURE__*/ (0,
-            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("h3", {
-              children: "A Link page!",
-            }),
-            /*#__PURE__*/ (0,
-            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
-              next_link__WEBPACK_IMPORTED_MODULE_1___default(),
-              {
-                href: "/",
-                children: "Go to /",
-              }
-            ),
-          ],
-        });
-      }
-      var __N_SSP = true;
-      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = aLink;
-
-      /***/
-    },
-
-    /***/ 3199: /***/ (__unused_webpack_module, exports) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "errorOnce", {
-        enumerable: true,
-        get: function () {
-          return errorOnce;
-        },
-      });
-      let errorOnce = (_) => {};
-      if (false) {
-      } //# sourceMappingURL=error-once.js.map
-
-      /***/
-    },
-
-    /***/ 3568: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/link",
-        function () {
-          return __webpack_require__(1854);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 3857: /***/ (module, exports, __webpack_require__) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "getDomainLocale", {
-        enumerable: true,
-        get: function () {
-          return getDomainLocale;
-        },
-      });
-      const _normalizetrailingslash = __webpack_require__(4869);
-      const basePath =
-        /* unused pure expression or super */ null && (false || "");
-      function getDomainLocale(path, locale, locales, domainLocales) {
-        if (false) {
-        } else {
-          return false;
-        }
-      }
-      if (
-        (typeof exports.default === "function" ||
-          (typeof exports.default === "object" && exports.default !== null)) &&
-        typeof exports.default.__esModule === "undefined"
-      ) {
-        Object.defineProperty(exports.default, "__esModule", {
-          value: true,
-        });
-        Object.assign(exports.default, exports);
-        module.exports = exports.default;
-      } //# sourceMappingURL=get-domain-locale.js.map
-
-      /***/
-    },
-
-    /***/ 3947: /***/ (module, exports, __webpack_require__) => {
+    /***/ 591: /***/ (module, exports, __webpack_require__) => {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -146,17 +28,17 @@
       const _react = /*#__PURE__*/ _interop_require_wildcard._(
         __webpack_require__(148)
       );
-      const _resolvehref = __webpack_require__(3161);
-      const _islocalurl = __webpack_require__(2309);
-      const _formaturl = __webpack_require__(3768);
-      const _utils = __webpack_require__(5554);
-      const _addlocale = __webpack_require__(7591);
-      const _routercontextsharedruntime = __webpack_require__(3556);
-      const _useintersection = __webpack_require__(5624);
-      const _getdomainlocale = __webpack_require__(3857);
-      const _addbasepath = __webpack_require__(4356);
-      const _usemergedref = __webpack_require__(4985);
-      const _erroronce = __webpack_require__(3199);
+      const _resolvehref = __webpack_require__(5837);
+      const _islocalurl = __webpack_require__(5953);
+      const _formaturl = __webpack_require__(6212);
+      const _utils = __webpack_require__(6950);
+      const _addlocale = __webpack_require__(6467);
+      const _routercontextsharedruntime = __webpack_require__(6712);
+      const _useintersection = __webpack_require__(9692);
+      const _getdomainlocale = __webpack_require__(6850);
+      const _addbasepath = __webpack_require__(4928);
+      const _usemergedref = __webpack_require__(1765);
+      const _erroronce = __webpack_require__(8659);
       const prefetched = new Set();
       function prefetch(router, href, as, options) {
         if (false) {
@@ -545,7 +427,17 @@
       /***/
     },
 
-    /***/ 4985: /***/ (module, exports, __webpack_require__) => {
+    /***/ 1148: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(591);
+
+      /***/
+    },
+
+    /***/ 1765: /***/ (module, exports, __webpack_require__) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -623,7 +515,125 @@
       /***/
     },
 
-    /***/ 5624: /***/ (module, exports, __webpack_require__) => {
+    /***/ 5436: /***/ (
+      __unused_webpack_module,
+      __webpack_exports__,
+      __webpack_require__
+    ) => {
+      "use strict";
+      __webpack_require__.r(__webpack_exports__);
+      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
+        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
+        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
+        /* harmony export */
+      });
+      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
+        __webpack_require__(5640);
+      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ =
+        __webpack_require__(1148);
+      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default =
+        /*#__PURE__*/ __webpack_require__.n(
+          next_link__WEBPACK_IMPORTED_MODULE_1__
+        );
+
+      function aLink(props) {
+        return /*#__PURE__*/ (0,
+        react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)("div", {
+          children: [
+            /*#__PURE__*/ (0,
+            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("h3", {
+              children: "A Link page!",
+            }),
+            /*#__PURE__*/ (0,
+            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
+              next_link__WEBPACK_IMPORTED_MODULE_1___default(),
+              {
+                href: "/",
+                children: "Go to /",
+              }
+            ),
+          ],
+        });
+      }
+      var __N_SSP = true;
+      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = aLink;
+
+      /***/
+    },
+
+    /***/ 6850: /***/ (module, exports, __webpack_require__) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "getDomainLocale", {
+        enumerable: true,
+        get: function () {
+          return getDomainLocale;
+        },
+      });
+      const _normalizetrailingslash = __webpack_require__(6457);
+      const basePath =
+        /* unused pure expression or super */ null && (false || "");
+      function getDomainLocale(path, locale, locales, domainLocales) {
+        if (false) {
+        } else {
+          return false;
+        }
+      }
+      if (
+        (typeof exports.default === "function" ||
+          (typeof exports.default === "object" && exports.default !== null)) &&
+        typeof exports.default.__esModule === "undefined"
+      ) {
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true,
+        });
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
+      } //# sourceMappingURL=get-domain-locale.js.map
+
+      /***/
+    },
+
+    /***/ 8659: /***/ (__unused_webpack_module, exports) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "errorOnce", {
+        enumerable: true,
+        get: function () {
+          return errorOnce;
+        },
+      });
+      let errorOnce = (_) => {};
+      if (false) {
+      } //# sourceMappingURL=error-once.js.map
+
+      /***/
+    },
+
+    /***/ 9666: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/link",
+        function () {
+          return __webpack_require__(5436);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 9692: /***/ (module, exports, __webpack_require__) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -636,7 +646,7 @@
         },
       });
       const _react = __webpack_require__(148);
-      const _requestidlecallback = __webpack_require__(3543);
+      const _requestidlecallback = __webpack_require__(315);
       const hasIntersectionObserver =
         typeof IntersectionObserver === "function";
       const observers = new Map();
@@ -748,23 +758,13 @@
 
       /***/
     },
-
-    /***/ 8770: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(3947);
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(3568)
+      __webpack_exec__(9666)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>routerDirect-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [188],
   {
-    /***/ 3618: /***/ (
+    /***/ 76: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -16,7 +16,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(5640);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(4631);
+        __webpack_require__(9413);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_router__WEBPACK_IMPORTED_MODULE_1__
@@ -36,17 +36,7 @@
       /***/
     },
 
-    /***/ 4631: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(7086);
-
-      /***/
-    },
-
-    /***/ 7824: /***/ (
+    /***/ 1810: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -54,7 +44,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/routerDirect",
         function () {
-          return __webpack_require__(3618);
+          return __webpack_require__(76);
         },
       ]);
       if (false) {
@@ -62,13 +52,23 @@
 
       /***/
     },
+
+    /***/ 9413: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(5282);
+
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(7824)
+      __webpack_exec__(1810)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>script-HASH.js</strong></summary>

```diff
@@ -1,24 +1,17 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [1209],
   {
-    /***/ 1984: /***/ (
-      __unused_webpack_module,
+    /***/ 2227: /***/ (
+      module,
       __unused_webpack_exports,
       __webpack_require__
     ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/script",
-        function () {
-          return __webpack_require__(5769);
-        },
-      ]);
-      if (false) {
-      }
+      module.exports = __webpack_require__(5984);
 
       /***/
     },
 
-    /***/ 5769: /***/ (
+    /***/ 3043: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -33,7 +26,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(5640);
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(8293);
+        __webpack_require__(2227);
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_script__WEBPACK_IMPORTED_MODULE_1__
@@ -66,12 +59,19 @@
       /***/
     },
 
-    /***/ 8293: /***/ (
-      module,
+    /***/ 3642: /***/ (
+      __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
     ) => {
-      module.exports = __webpack_require__(900);
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/script",
+        function () {
+          return __webpack_require__(3043);
+        },
+      ]);
+      if (false) {
+      }
 
       /***/
     },
@@ -81,7 +81,7 @@
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(1984)
+      __webpack_exec__(3642)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>withRouter-HASH.js</strong></summary>

```diff
@@ -1,34 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [3263],
   {
-    /***/ 4631: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(7086);
-
-      /***/
-    },
-
-    /***/ 9216: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/withRouter",
-        function () {
-          return __webpack_require__(9803);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 9803: /***/ (
+    /***/ 1089: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -43,7 +16,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(5640);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(4631);
+        __webpack_require__(9413);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_router__WEBPACK_IMPORTED_MODULE_1__
@@ -61,13 +34,40 @@
 
       /***/
     },
+
+    /***/ 3962: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/withRouter",
+        function () {
+          return __webpack_require__(1089);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 9413: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(5282);
+
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(9216)
+      __webpack_exec__(3962)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>1733-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>4719-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-app-HASH.js</strong></summary>

```diff
@@ -1,61 +1,61 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [4977],
   {
-    /***/ 3505: /***/ () => {
-      /* (ignored) */
-      /***/
-    },
-
-    /***/ 8089: /***/ (
+    /***/ 903: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
     ) => {
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 8790, 23)
+        __webpack_require__.t.bind(__webpack_require__, 5356, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 7382, 23)
+        __webpack_require__.t.bind(__webpack_require__, 4304, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 9442, 23)
+        __webpack_require__.t.bind(__webpack_require__, 8390, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 94, 23)
+        __webpack_require__.t.bind(__webpack_require__, 9464, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 2439, 23)
+        __webpack_require__.t.bind(__webpack_require__, 7601, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 5083, 23)
+        __webpack_require__.t.bind(__webpack_require__, 2553, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 8103, 23)
+        __webpack_require__.t.bind(__webpack_require__, 1925, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 5625, 23)
+        __webpack_require__.t.bind(__webpack_require__, 959, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 4247, 23)
+        __webpack_require__.t.bind(__webpack_require__, 9389, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 5602, 23)
+        __webpack_require__.t.bind(__webpack_require__, 8628, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 227, 23)
+        __webpack_require__.t.bind(__webpack_require__, 3077, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 6734, 23)
+        __webpack_require__.t.bind(__webpack_require__, 7812, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 4120, 23)
+        __webpack_require__.t.bind(__webpack_require__, 5774, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.bind(__webpack_require__, 6104)
+        __webpack_require__.bind(__webpack_require__, 750)
       );
 
       /***/
     },
+
+    /***/ 3579: /***/ () => {
+      /* (ignored) */
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
@@ -63,8 +63,8 @@
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(
       0,
-      [1305, 1733],
-      () => (__webpack_exec__(9679), __webpack_exec__(8089))
+      [9910, 965],
+      () => (__webpack_exec__(1389), __webpack_exec__(903))
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>

</details>

</details>
Commit: 3b6f0ab05780dc1ecad92d2f9a296688056858d8

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 3b6f0ab05780dc1ecad92d2f9a296688056858d8

`pnpm test-dev-turbo test/e2e/app-dir/logging/fetch-logging.test.ts` (turbopack)
- app-dir - logging > with default logging > should not contain metadata internal segments for dynamic metadata routes
- app-dir - logging > with fetches default logging > should not contain metadata internal segments for dynamic metadata routes
- app-dir - logging > with fetches verbose logging > should not contain metadata internal segments for dynamic metadata routes
- app-dir - logging > with verbose logging for edge runtime > should not contain trailing word page for app router routes
- app-dir - logging > with verbose logging for edge runtime > should not contain metadata internal segments for dynamic metadata routes

<details>
<summary>Expand output</summary>

  ● app-dir - logging › with fetches verbose logging › should not contain metadata internal segments for dynamic metadata routes

    expect(received).not.toContain(expected) // indexOf

    Expected substring: not "/route"
    Received string:        " GET / 200 in 706ms
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-modules/app-route/module.compiled.js\"
    is_marked_as_side_effect_free flase \"[project]/app/dynamic/[slug]/icon.jsx\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/server.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/og.js\"
     ✓ Compiled /dynamic/[slug]/icon in 249ms
     GET /dynamic/big/icon 200 in 600ms
    "

      348 |           expect(output).not.toContain('/(group)')
      349 |           expect(output).not.toContain('[__metadata_id__]')
    > 350 |           expect(output).not.toContain('/route')
          |                              ^
      351 |         })
      352 |       })
      353 |     }

      at toContain (e2e/app-dir/logging/fetch-logging.test.ts:350:30)
      at fn (lib/next-test-utils.ts:810:20)
      at Object.<anonymous> (e2e/app-dir/logging/fetch-logging.test.ts:345:9)

  ● app-dir - logging › with fetches default logging › should not contain metadata internal segments for dynamic metadata routes

    expect(received).not.toContain(expected) // indexOf

    Expected substring: not "/route"
    Received string:        " GET / 200 in 713ms
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-modules/app-route/module.compiled.js\"
    is_marked_as_side_effect_free flase \"[project]/app/dynamic/[slug]/icon.jsx\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/server.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/og.js\"
     ✓ Compiled /dynamic/[slug]/icon in 233ms
     GET /dynamic/big/icon 200 in 586ms
    "

      348 |           expect(output).not.toContain('/(group)')
      349 |           expect(output).not.toContain('[__metadata_id__]')
    > 350 |           expect(output).not.toContain('/route')
          |                              ^
      351 |         })
      352 |       })
      353 |     }

      at toContain (e2e/app-dir/logging/fetch-logging.test.ts:350:30)
      at fn (lib/next-test-utils.ts:810:20)
      at Object.<anonymous> (e2e/app-dir/logging/fetch-logging.test.ts:345:9)

  ● app-dir - logging › with verbose logging for edge runtime › should not contain trailing word page for app router routes

    expect(received).not.toContain(expected) // indexOf

    Expected substring: not "/page"
    Received string:        "is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/encryption-utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/page-types.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/app-render.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/action-utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/incremental-cache/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/build/webpack/loaders/next-edge-ssr-loader/render.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/entry-base.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/error-boundary.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-kind.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/get-short-dynamic-param-type.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/get-asset-query-string.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/postponed-state.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/create-component-tree.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/server-inserted-html.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/to-route.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/render-result.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/static-generation-bailout.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/format-server-error.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-modules/app-page/module.compiled.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/incremental-cache/shared-cache-controls.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/page-path/normalize-page-path.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/react/jsx-runtime.react-server.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/create-initial-router-state.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/incremental-cache/file-system-cache.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/required-scripts.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/resume-data-cache/resume-data-cache.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/stream-utils/node-web-streams-helper.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/build/output/log.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/make-get-server-inserted-html.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/get-segment-param.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/action-handler.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/react/react.react-server.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/server-utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/walk-tree-with-flight-router-state.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/metadata-context.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/use-flight-response.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/dynamic-rendering.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/get-script-nonce-from-header.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/metadata-insertion/create-server-inserted-metadata.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/instrumentation/utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/lazy-dynamic/bailout-to-csr.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/route-regex.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/create-error-handler.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/app-router.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/parse-relative-url.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/client-component-renderer-logger.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/web-server.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/parse-loader-tree.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/implicit-tags.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/create-flight-router-state-from-loader-tree.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/use-cache/use-cache-errors.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/web/internal-edge-wait-until.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/hooks-server-context.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/base-http/web.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/base-http/helpers.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/app-router-instance.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/clean-async-snapshot.external.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/create-component-styles-and-scripts.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/is-error.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/app-render-prerender-utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/prospective-render-utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/app-render-render-utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/scheduler.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/server-action-request-meta.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/cache-signal.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/trace/utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/response-cache/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/redirect.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/parse-and-validate-flight-router-state.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/flight-render-result.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/detached-promise.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/base-http/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/api-utils/web.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/base-server.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/build-custom-route.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/etag.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/api/constants.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/escape-regexp.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/types.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/csrf-protection.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/request-meta.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/response-cache/web.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/route-matcher.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/has-loading-component-in-tree.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/get-preloadable-fonts.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/server-ipc/utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/error-telemetry-utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/response-cache/types.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/render-css-resource.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/htmlescape.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/pipe-readable.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/querystring.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/clean-async-snapshot-instance.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/interop-default.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/encode-uri-path.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/multi-file-writer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/response-cache/utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/stream-utils/uint8array-helpers.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/batcher.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/react-dom/react-dom.react-server.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/get-layer-assets.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/errors/constants.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/react-dom/server.edge.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/parallel-route-default.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/reducers/prefetch-reducer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/path-match.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/stream-utils/encodedTags.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/get-css-inlined-link-tags.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/is-plain-object.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/client-and-server-references.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/app-dir-module.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/links.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/match-segments.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/patch-fetch.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-modules/route-module.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/resume-data-cache/cache-store.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/shared/lib/server-inserted-metadata.shared-runtime.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/picocolors.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/use-action-queue.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/add-base-path.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-modules/app-page/vendored/contexts/entrypoints.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/render-to-string.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/interception-routes.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/string-hash/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/segment-cache.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/router-reducer-types.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/shared/lib/server-inserted-html.shared-runtime.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/dynamic-rendering-utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/flight-data-helpers.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/prepare-destination.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/metadata-constants.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/router-reducer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/refetch-inactive-parallel-segments.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/prefetch-cache-utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/compute-changed-path.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/fill-lazy-items-till-leaf-with-head.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/create-href-from-url.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/native-url/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/constants.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/is-dynamic.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/isomorphic/path.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/sorted-routes.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/api-utils/get-cookie-parser.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/action-async-storage-instance.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/superstruct/index.cjs\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/server-reference-info.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/web/spec-extension/adapters/next-request.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/promise-queue.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/reducers/navigate-reducer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/reducers/server-patch-reducer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/fetch-server-response.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/not-found.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/apply-flight-data.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/parse-url.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/reducers/refresh-reducer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/reducers/hmr-refresh-reducer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/create-router-cache-key.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/reducers/server-action-reducer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/path-to-regexp/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/normalize-trailing-slash.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/reducers/restore-reducer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/shared/lib/head-manager-context.shared-runtime.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/fallback.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/clone-response.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/dedupe-fetch.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/streaming-metadata.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-modules/checks.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/strip-flight-headers.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/shared/lib/app-router-context.shared-runtime.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/shared/lib/hooks-client-context.shared-runtime.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/patch-set-header.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/shared/lib/router-context.shared-runtime.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/shared/lib/amp-context.shared-runtime.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/shared/lib/image-config-context.shared-runtime.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/decode-query-path-parameter.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/router-utils/decode-path-params.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/is-bot.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/match-next-data-pathname.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/redirect-status.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/experimental/ppr.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matcher-managers/default-route-matcher-manager.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/load-custom-routes.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/react/jsx-runtime.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/get-route-from-asset-path.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matcher-providers/pages-route-matcher-provider.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/react/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matcher-providers/pages-api-route-matcher-provider.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matcher-providers/app-page-route-matcher-provider.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/modern-browserslist-target.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matcher-providers/app-route-route-matcher-provider.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/page-path/denormalize-page-path.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/request/prefetch-rsc.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/request/next-data.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/is-edge-runtime.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/request/segment-prefix-rsc.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/request/rsc.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/runtime-config.external.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/locale-route-normalizer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/format-hostname.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/cache-control.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matcher-providers/helpers/manifest-loaders/server-manifest-loader.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/request/fallback-params.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/has-base-path.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/send-response.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/apply-router-state-patch-to-tree.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/is-navigating-to-new-root-layout.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/i18n-provider.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/handle-mutable.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/fill-cache-with-new-subtree-data.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/app-find-source-map-url.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/app-call-server.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/aliased-prefetch-navigations.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/handle-segment-mismatch.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/clear-cache-node-data-for-segment-path.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/try-to-parse-path.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/reducers/has-interception-route-in-current-tree.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/ppr-navigations.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/assign-location.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/url.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/remove-base-path.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/utils/dev-indicator/dev-render-indicator.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/invalidate-cache-below-flight-segmentpath.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/should-hard-navigate.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/html-bots.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/is-ipv6.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/request/suffix.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/page-path/normalize-path-sep.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/escape-path-delimiters.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/http-access-fallback/error-boundary.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matchers/locale-route-matcher.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/react-dom/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/is-api-route.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/is-app-route-route.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/is-app-page-route.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/invalidate-cache-by-router-state.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/request/prefix.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/built/app/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matcher-providers/manifest-route-matcher-provider.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matchers/app-page-route-matcher.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matchers/pages-api-route-matcher.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matchers/pages-route-matcher.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/app-router-announcer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/redirect-boundary.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/reducers/find-head-in-cache.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/built/pages/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/unresolved-thenable.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matchers/app-route-route-matcher.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/navigation-untracked.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/nav-failure-handler.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/utils/warn-once.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matchers/route-matcher.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/built/app/app-page-normalizer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/built/app/app-bundle-path-normalizer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/built/app/app-filename-normalizer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/built/app/app-pathname-normalizer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/built/pages/pages-page-normalizer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/built/pages/pages-pathname-normalizer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/set-cache-busting-search-param.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/app-build-id.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/built/pages/pages-filename-normalizer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/built/pages/pages-bundle-path-normalizer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-matcher-providers/helpers/cached-route-matcher-provider.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/prefixing-normalizer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/wrap-normalizer-fn.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/underscore-normalizer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/normalizers.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/normalizers/absolute-filename-normalizer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/navigation.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/hash.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/app/app-dev-overlay.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/utils/parse-stack.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/dev/hot-reloader-types.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/utils/turbopack-hot-reloader-common.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/utils/parse-component-stack.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/utils/report-hmr-latency.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/shared.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/dev/dev-build-indicator/internal/handle-dev-build-indicator-hmr-events.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/errors/runtime-error-handler.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/errors/stitched-error.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/utils/format-webpack-messages.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/errors/use-error-handler.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/page-path/absolute-path-to-page.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/utils/use-websocket.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/strip-ansi/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/navigation.react-server.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/router-reducer/reducers/get-segment-value.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/get-metadata-route.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/page-path/remove-page-path-tail.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/dev/dev-build-indicator/internal/dev-build-indicator.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/errors/enqueue-client-error.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/errors/console-error.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/utils/get-socket-url.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/is-hydration-error.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/app/app-dev-overlay-error-boundary.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/errors/hydration-error-info.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/dev-overlay.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/errors/attach-hydration-error-state.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/font/font-styles.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/lib/console.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/unauthorized.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/forbidden.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/unstable-rethrow.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/stacktrace-parser/stack-trace-parser.cjs.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/dev/dev-build-indicator/internal/initialize.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/is-metadata-route.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/utils/css.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/container/runtime-error/render-error.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/styles/dark-theme.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/shadow-portal.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/styles/component-styles.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/styles/base.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/styles/colors.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/dev-tools-indicator/dev-tools-indicator.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/dev-tools-indicator/dev-tools-info/preferences.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/styles/css-reset.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/error-overlay/error-overlay.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/normalized-asset-prefix.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/lib/router-utils/is-postpone.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/container/build-error.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/container/errors.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/hooks/use-delayed-render.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/utils/get-error-by-type.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/dev-tools-indicator/next-logo.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/call-stack-frame/call-stack-frame.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/error-overlay-footer/error-overlay-footer.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/code-frame/code-frame.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/version-staleness-info/version-staleness-info.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/dev-tools-indicator/dev-tools-info/dev-tools-info.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/overlay/styles.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/error-overlay-bottom-stack/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/dev-tools-indicator/dev-tools-info/route-info.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/terminal/terminal.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/toast/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/dev-tools-indicator/dev-tools-info/turbopack-info.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/dialog/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/fader/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/dev-tools-indicator/dev-tools-info/user-preferences.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/dev-tools-indicator/utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/container/runtime-error/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/error-overlay-layout/error-overlay-layout.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/terminal/editor-link.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/error-overlay-pagination/error-overlay-pagination.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/error-source.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/copy-button/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/icons/gear-icon.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/utils/stack-frame.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/environment-name-label/environment-name-label.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/dialog/styles.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/terminal/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/container/runtime-error/component-stack-pseudo-html.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/overlay/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/hot-linked-text/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/utils/webpack-module-path.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/toast/toast.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/toast/styles.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/icons/file.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/utils/use-open-in-editor.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/icons/external.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/overlay/overlay.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/hydration-diff/diff-view.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/error-type-label/error-type-label.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/error-overlay-toolbar/error-overlay-toolbar.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/overlay/overlay.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/dialog/header.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/dialog/dialog-content.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/anser/index.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/error-overlay-nav/error-overlay-nav.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/utils/merge-refs.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/dev-tools-indicator/use-minimum-loading-time-multiple.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/dialog/dialog.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/dialog/body.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/error-overlay-footer/error-feedback/error-feedback.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/icons/system-icon.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/dialog/dialog-header.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/error-message/error-message.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/icons/eye-icon.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/dialog/dialog-body.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/utils/cx.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/icons/light-icon.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/dialog/dialog.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/magic-identifier.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/icons/dark-icon.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/code-frame/parse-code-frame.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/icons/collapse-icon.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/icons/left-arrow.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/icons/right-arrow.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/overlay/body-locker.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/call-stack/call-stack.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/icons/thumbs/thumbs-down.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/hooks/use-measure-height.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/icons/thumbs/thumbs-up.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/hooks/use-on-click-outside.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/error-overlay-toolbar/docs-link-button.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/error-overlay-toolbar/copy-stack-trace-button.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/components/errors/error-overlay-toolbar/nodejs-inspector-button.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/react-dev-overlay/ui/utils/parse-url-from-text.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/request/params.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/layout-router.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/action-async-storage.external.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/render-from-template-context.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/react-server-dom-turbopack/static.edge.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/client-segment.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/collect-segment-data.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/client-page.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/metadata.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/react-server-dom-turbopack/server.edge.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/request/search-params.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/rsc/postpone.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/rsc/preloads.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/app-render/rsc/taint.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/metadata/metadata-boundary.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/build/polyfills/process.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/utils/reflect-utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/create-deduped-by-callsite-server-error-logger.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/request/utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/components/metadata/async-metadata.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/segment-cache/segment-value-encoding.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/resolve-metadata.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/generate/meta.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/generate/alternate.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/react-server-dom-turbopack/client.edge.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/generate/basic.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/generate/opengraph.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/generate/icons.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/constants.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/non-nullable.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/generate/utils.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/interop-default.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/default-metadata.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/server-only/empty.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/resolvers/resolve-basics.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/resolvers/resolve-title.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/resolvers/resolve-icons.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/resolvers/resolve-opengraph.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/handle-smooth-scroll.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/lib/metadata/resolvers/resolve-url.js\"
     ○ Compiling / ...
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/compiled/react/jsx-dev-runtime.react-server.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/app-dir/link.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/format-url.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/utils/error-once.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/client/use-merged-ref.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/shared/lib/router/utils/is-local-url.js\"
     ✓ Compiled / in 912ms
     GET / 200 in 1106ms
    "

      335 |           const output = stripAnsi(next.cliOutput.slice(logLength))
      336 |           expect(output).toContain('/')
    > 337 |           expect(output).not.toContain('/page')
          |                              ^
      338 |         })
      339 |       })
      340 |

      at toContain (e2e/app-dir/logging/fetch-logging.test.ts:337:30)
      at fn (lib/next-test-utils.ts:810:20)
      at Object.<anonymous> (e2e/app-dir/logging/fetch-logging.test.ts:334:9)

  ● app-dir - logging › with verbose logging for edge runtime › should not contain metadata internal segments for dynamic metadata routes

    expect(received).not.toContain(expected) // indexOf

    Expected substring: not "/route"
    Received string:        "is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-modules/app-route/module.compiled.js\"
    is_marked_as_side_effect_free flase \"[project]/app/dynamic/[slug]/icon.jsx\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/server.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/og.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react.js\"
     ✓ Compiled /dynamic/[slug]/icon in 251ms
     GET /dynamic/big/icon 200 in 646ms
    "

      348 |           expect(output).not.toContain('/(group)')
      349 |           expect(output).not.toContain('[__metadata_id__]')
    > 350 |           expect(output).not.toContain('/route')
          |                              ^
      351 |         })
      352 |       })
      353 |     }

      at toContain (e2e/app-dir/logging/fetch-logging.test.ts:350:30)
      at fn (lib/next-test-utils.ts:810:20)
      at Object.<anonymous> (e2e/app-dir/logging/fetch-logging.test.ts:345:9)

  ● app-dir - logging › with default logging › should not contain metadata internal segments for dynamic metadata routes

    expect(received).not.toContain(expected) // indexOf

    Expected substring: not "/route"
    Received string:        " GET / 200 in 714ms
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/esm/server/route-modules/app-route/module.compiled.js\"
    is_marked_as_side_effect_free flase \"[project]/app/dynamic/[slug]/icon.jsx\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/server.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/og.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js\"
    is_marked_as_side_effect_free flase \"[project]/node_modules/.pnpm/next@file+..+next-repo-4a523cf45beb13772e3007b19759abc917f1e18dbb80de51649e37e6f1904316+packa_pmyjdjsmiktdlgkmyk4xwj2b6y/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react.js\"
     ✓ Compiled /dynamic/[slug]/icon in 249ms
     GET /dynamic/big/icon 200 in 650ms
    "

      348 |           expect(output).not.toContain('/(group)')
      349 |           expect(output).not.toContain('[__metadata_id__]')
    > 350 |           expect(output).not.toContain('/route')
          |                              ^
      351 |         })
      352 |       })
      353 |     }

      at toContain (e2e/app-dir/logging/fetch-logging.test.ts:350:30)
      at fn (lib/next-test-utils.ts:810:20)
      at Object.<anonymous> (e2e/app-dir/logging/fetch-logging.test.ts:345:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: turbopack/crates/turbopack-ecmascript/src/chunk/placeable.rs [hunk 1]
```diff
@@ -179,12 +181,17 @@ pub async fn is_marked_as_side_effect_free(
...
+                    return Ok(Vc::cell(!glob.await?.execute(rel_path)));
                 }
             }
         }
     }
 
+    println!(
+        "is_marked_as_side_effect_free flase {:?}",
+        path.to_string().await?
+    );
```
Comment (sokra) [inline turbopack/crates/turbopack-ecmascript/src/chunk/placeable.rs:194]:
```suggestion
```

**Review by sokra — APPROVED** [review]
ok

**Comment by sokra** [comment]
### Merge activity

* **Apr 3, 9:02 PM EDT**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/77693).
