### PR TITLE
Check if _document.js returns a react element before using

### LINKED ISSUE #1996: Empty _document.js causes next to crash
If you have a `_document.js` file that is empty, react throws an invariant error which is not really meaningful:

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.`

This can be tricky to catch and take some time to figure out. (ex: forgot to save the content of _document)

### PR DESCRIPTION
**Pull request by xuezhma**
Fixes #1996 
Throws an error if _document.js is not returning a react element

### CODE REVIEW

File: server/render.js [hunk 1]
```diff
@@ -90,6 +90,7 @@ async function doRender (req, res, pathname, query, {
 
   if (res.finished) return
 
+  if (!Document.prototype || !Document.prototype.isReactComponent) throw new Error('_document.js is not exporting a react element')
```
Comment (timneutkens) [inline server/render.js]: Minor, but: `React element` (capital `R`)

**Comment by timneutkens** [comment]
Fixes #1996

File: server/render.js (hunk 1 above)
Comment (xuezhma) [inline server/render.js]: Changed to capital R

**Review by timneutkens — APPROVED** [review]
Great! Thank you so much 👌

**Comment by arunoda** [comment]
Nice.

File: server/render.js (hunk 1 above)
Comment (kirill-konshin) [inline server/render.js]: If a functional component is returned then this check fails.
