### PR TITLE
Apply workaround for Firefox bug

### LINKED ISSUE #3817: Firefox loses query string after a Router.replace shallow
We have a very strange edge case only happening in Firefox but its def causing some problems.

This is whats happening is I navigate to the root http://localhost:3000, get redirected on the server to /about2

I click I button which Router.replace shallow:true which replaces the url to /about2?key=value

I refresh the browser at the current state, url is /about2, I expect it to be /about2=key=value

Here a video recording of the scenario.
https://drive.google.com/file/d/1c0oN-UZIVuG5lt6oZiJOlwZSzAM98gSX/view?usp=sharing

To be a friendly guest here's the repro repo, examples/hello-world
npm install && npm run dev

https://github.com/ptomasroos/next.js/tree/firefox-loses-querystrings

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

Firefox 58 (latest)

### PR DESCRIPTION
**Pull request by ijjk**
There's a weird bug in current versions of Firefox that causes a URL's query to be lost after refreshing the page. This applies a workaround to prevent this behavior.

Fixes: #3817

### CODE REVIEW

**Comment by Timer** [comment]
Should we add a truthy check on `window.location.search` to skip this if there's no query param?

Also, how do you feel about restricting this to Firefox? i.e. `(navigator.userAgent && navigator.userAgent.match(/firefox/i))`

File: packages/next-server/lib/router/router.js [hunk 1]
```diff
@@ -40,6 +40,15 @@ export default class Router {
       this.changeState('replaceState', formatWithValidation({ pathname, query }), as)
 
       window.addEventListener('popstate', this.onPopState)
+
+      // Workaround for weird Firefox bug, see below links
+      // https://github.com/zeit/next.js/issues/3817
+      // https://bugzilla.mozilla.org/show_bug.cgi?id=1422334
```
Comment (Timer) [inline packages/next-server/lib/router/router.js]:
```suggestion
      // https://bugzilla.mozilla.org/show_bug.cgi?id=1422334
      // TODO: let's remove this once the Firefox bug is resolved
```

**Review by Timer — APPROVED** [review]
