### PR TITLE
fix revalidation/refresh behavior with parallel routes

### LINKED ISSUE #51711: router.push("/") broken when intercepting routes as modal with parallel routes
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.6.7
      Yarn: N/A
      pnpm: 8.6.1
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3


```

### Which area(s) of Next.js are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/fast-bush-qlpdwm?file=%2Fapp%2Fhome%2Fpage.tsx

### To Reproduce

use push("/") in a modal

### Describe the Bug

This is what I get
image

### Expected Behavior

I expect it to actually redirect me to the path I telling it to redirect

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### LINKED ISSUE #51714: Refreshing an intercepted parallel route `(modal)` breaks router
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.6.7
      Yarn: N/A
      pnpm: 8.6.1
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/goofy-williamson-myrykt

### To Reproduce

Steps to reproduce: 
1. Click `Go to Login Page` Button
2. Click `Refresh` Button
3. Click `Go Back` Button

### Describe the Bug

When refreshing an intercepted parallel route the router stops working and then you can't go to any other route because the intercepted route doesn't disappear.

### Expected Behavior

I expect the intercepted parallel route to disappear and take me to the correct route

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

<sub>[NEXT-2030](https://linear.app/vercel/issue/NEXT-2030/refreshing-an-intercepted-parallel-route-modal-breaks-router)</sub>

### LINKED ISSUE #58715: Since v14.0.2, using revalidatePath in nested Parallel Routes prevents router.back from functioning
### Link to the code that reproduces this issue

https://github.com/zaru/nested-parallel-routes

### To Reproduce

1. Click the "Open drawer" button.
2. Click the "Open modal" button.
3. Click the "Revalidate submit" button.
4. The modal is expected to close but does not close.

### Current vs. Expected behavior

Executing router.back() is expected to clear the Slot of Parallel Routes and close the modal, but in reality, the modal does not close. However, the URL and History do go back one step.

This unexpected behavior occurs when revalidatePath() is executed within ServerActions.

https://github.com/zaru/nested-parallel-routes/blob/c459d5d2b7425b5cc9b7c44cada8e001de02c5f4/src/app/%40modal/modal/action.ts#L7

I can close the modal when I don't execute revalidatePath(), but I'm having trouble updating the screen to the latest version without it.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.12.1
  npm: 9.6.6
  Yarn: 3.6.3
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.6
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

This was working correctly in Next.js versions prior to v14.0.1.

### LINKED ISSUE #60815: RevalidateTag from Server Action changes default slot in parallel route
### Link to the code that reproduces this issue

https://github.com/swa-legste/next-reproduction

### To Reproduce

1. Start the application in development (next dev)
2. Open applicaiton over http://localhost:3000/
3. click on the  "Open basket" link at the top
4. wait until basket opens
5. Click on any "Fake Cart Update" button
6. wait until action completes

### Current vs. Expected behavior

**expected**
As we're updating the cart using a server action I'm expecting the modal to change and not the page:
image

**actual**
After executing the action the main slot is empty:
image

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Mon Jan  1 18:15:01 PST 2024
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: 8.14.0
Relevant Packages:
  next: 14.0.5-canary.65
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

I've reported a similar bug using `redirect` instead of `revalidateTag`: https://github.com/vercel/next.js/issues/60814

This might be related to https://github.com/vercel/next.js/issues/54173 and partially fixed (at least redirects executes) by https://github.com/vercel/next.js/pull/59585.

Root cause being the `revalidateTag('cart')` in the server action.

### LINKED ISSUE #60948: Parallel + Intercepted route causes 404 when setting cookie in Server Action
### Link to the code that reproduces this issue

https://github.com/mordechaim/intercepted-not-found

### To Reproduce

1. Check out deployment at https://intercepted-not-found.vercel.app/
2. Hard navigate to login page https://intercepted-not-found.vercel.app/login
3. Set cookie action: works perfectly.
4. Soft navigate to login page from home via link
5. Set cookie action in intercepted form: 404

### Current vs. Expected behavior

When setting cookie, or any other server action that clear the client-side router cache, there's an error in the console:

```
No default component was found for a parallel route rendered on this page. Falling back to nearest NotFound boundary.
Learn more: https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#defaultjs
```

The main page then changes to a 404, while the intercepted page is still present all the way at the bottom.

I would expect the form to behave exactly the same regardless if the router cache is cleared or not.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
Binaries:
  Node: 20.5.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.4 // Latest available version is detected (14.1.1-canary.4).
  eslint-config-next: 14.1.1-canary.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed)

### Additional context

_No response_

### LINKED ISSUE #60950: Calling revalidatePath() or revalidateTag() in Server Actions triggered by Intercepting Routes breaks routing
### Link to the code that reproduces this issue

https://github.com/flsilva/next-v14-revalidate-issue-2

### To Reproduce

Steps to reproduce bugs 1 and 2:

1. Visit https://next-v14-revalidate-issue-2.vercel.app

2. Fill in the **name** input text at **Default children slot box**.

3. Click the **Submit** button below the input field.

4. It works as expected. The **Submit** button changes to **Submitting...** and after 3 seconds it changes back to **Submit**, and we can see the Server Action's response.

5. Click **Nav to /foo** to visit the Intercepting Route **/foo**. Navigating to it works as expected, i.e., you'll see **/src/app/@intercept/(.)foo/page.tsx** content at the **intercept slot box**.

6. Fill in the **name** input text in the form at **intercept slot box**.

7. Click the **Submit** button in below the input text.

8. The form submission works as expected, but we have a bug here. The content at **Default children slot box** goes away, but it shouldn't. This is **bug 1**.

9. Do it again (second time), i.e., fill in the **name** input text in the form at **intercept slot box**, without refreshing the browser. **It does work**.

10. Do it again (third time), i.e., fill in the **name** input text in the form at **intercept slot box**, without refreshing the browser. **It does NOT work**.

11. We have another bug. We get a behavior equivalent to a hard reload. The page at **intercept slot box** goes away, and **/src/app/foo/page.tsx** is rendered at **Default children slot box**, exactly as if we did a manual hard reload. This is **bug 2**.

### Current vs. Expected behavior

Current behavior is described in the steps to reproduce above.

Expected behavior:

For **bug 1**: The content at **Default children slot box** shouldn't go away.

For **bug 2**:

a. The content at **intercept slot box** shouldn't go away.
b. The **/src/app/foo/page.tsx** shouldn't get rendered at **Default children slot box**.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.4 // Latest available version is detected (14.1.1-canary.4).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), Vercel (Deployed)

### Additional context

I can reproduce the issue in v14.1.1-canary.4 on localhost and Vercel.

Code changes that results in the same behavior:

1. Changing revalidatePath('/') to revalidatePath('/', 'page').
2. Changing revalidatePath('/') to revalidatePath('/', 'layout').
3. Changing revalidatePath('/') to revalidatePath('/foo').
4. Changing revalidatePath('/') to revalidatePath('/foo', 'page').
5. Changing revalidatePath('/') to revalidatePath('/foo', 'layout').
6. Replacing revalidatePath() with revalidateTag('anything').

Code changes that results in the expected behavior:

1. If we comment out the **revalidatePath('/')** line of code in **action.ts** everything works as expected **because we're not relying on cached data in this app**, showing that the bug only happens when we use that function.

Routing structure:

```
app
├── @intercept
│   ├── (.)foo
│   │   └── page.tsx
│   └── default.tsx
├── foo
│   └── page.tsx
├── layout.tsx
└── page.tsx
```

Relevant code:

app/action.ts

```ts
"use server";

import { revalidatePath } from "next/cache";

export const action = async (
  previousState: string | undefined,
  formData: FormData
) => {
  const name = formData.get("name");
  await new Promise((resolve) => setTimeout(resolve, 3000));
  revalidatePath("/");
  return `name: ${name} | Math.random(): ${(Math.random() * 100).toFixed(2)}`;
};
```

Replay:

next-v14-revalidate-issue-2

<sub>[NEXT-2852](https://linear.app/vercel/issue/NEXT-2852/calling-revalidatepath-or-revalidatetag-in-server-actions-triggered-by)</sub>

### LINKED ISSUE #61341: Calling redirect from a React Server Component to an intercepted route causes infinite rerendering loop
### Link to the code that reproduces this issue

https://github.com/denexapp/redirect-from-rsc-to-intercepted-route-bug

### To Reproduce

1. Start the dev server
2. Open the main page and click on the Link
3. Wait for 30 seconds
4. Watch the terminal and the browser console for a list of errors / rerender messages

### Current vs. Expected behavior

Expected behaviour: 
- A component from the intercepted route renders once

Current behaviour:
- Component gets rerendered in a loop
- Navigation works _incorrectly_, causing weird errors and sometimes crashing the app

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #18~22.04.1-Ubuntu SMP Tue Nov 21 19:25:02 UTC 2023
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.14.1
Relevant Packages:
  next: 14.1.1-canary.20 // Latest available version is detected (14.1.1-canary.20).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed)

### Additional context

The issue occurs with:
- with babel / without babel
- on mac os / on github codespaces
- with turbopack / without turbopack
- on canary (14.1.1-canary.20) / on stable (14.1.0)
- with bun / with node
- locally / on Vercel

### LINKED ISSUE #62213: 404 error occurs after refreshing from intercepted parallel route.
### Link to the code that reproduces this issue

https://github.com/aramikuto/nextjs-intercepted-parallel-route-refresh-problem

### To Reproduce

1. Navigate to the intercepted parallel route.
2. Press the `Refresh` button.

### Current vs. Expected behavior

I expected the `router.refresh` function to update the content of the displayed components without altering which components are being displayed. However, upon refreshing, the content of the root page (`/`) is replaced with a 404 error page.

https://github.com/vercel/next.js/assets/116561995/681d0f5f-eb62-434b-a3eb-eeb2e021ee98

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 8.14.3
Relevant Packages:
  next: 14.1.1-canary.59 // Latest available version is detected (14.1.1-canary.59).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

In version 14.0.1, refreshing does not trigger a 'not found' error and successfully updates the displayed components as expected.

### PR DESCRIPTION
**Pull request by ztanner**
(Original PR #63608 was erroneously merged into this branch. As a result, I've copied the notes from it below.)

### What
When a parallel segment in the current router tree is no longer "active" during a soft navigation (ie, no longer matches a page component on the particular route), it remains on-screen until the page is refreshed, at which point it would switch to rendering the default.tsx component. However, when revalidating the router cache via router.refresh, or when a server action finishes & refreshes the router cache, this would trigger the "hard refresh" behavior. This would have the unintended consequence of a 404 being triggered (which is the default behavior of default.tsx) or inactive segments disappearing unexpectedly.

### Why
When the router cache is refreshed, it currently fetches new data for the page by fetching from the current URL the user is on. This means that the server will never respond with the data it needs if the segment wasn't "activated" via the URL we're fetching from, as it came from someplace else. Instead, the server will give us data for the default.tsx component, which we don't want to render when doing a soft refresh.

### How
This updates the FlightRouterState to encode information about the URL that caused the segment to become active. That way, when some sort of revalidation event takes place, we can both refresh the data for the current URL (existing handling), and recursively refetch segment data for anything that was still present in the tree but requires fetching from a different URL. We patch this new data into the tree before committing the final CacheNode to the router.

Note: I re-used the existing refresh and url arguments in FlightRouterState to avoid introducing more options to this data structure that is already a bit tricky to work with. Initially I was going to re-use "refetch" as-is, which seemed to work ok, but I'm worried about potential implications of this considering they have different semantics. In an abundance of caution, I added a new marker type ("refresh", alternative suggestions welcome).

This has some trade-offs: namely, if there are a lot of different segments that are in this stale state that require data from different URLs, the refresh is going to be blocked while we fetch all of these segments. Having to do a separate round-trip for each of these segments could be expensive. In an ideal world, we'd be able to enumerate the segments we'd want to refetch and where they came from, so it could be handled in a single round-trip. There are some ideas on how to improve per-segment fetching which are out of scope of this PR. However, due to the implicit contract that middleware.ts creates with URLs, we still need to identify these resources by URLs.

### Other Notes:
`applyRouterStatePatchToTree` had been refactored to support the case of not skipping the `__DEFAULT__` segment, so that `router.refresh` or revalidating in a server action wouldn't break the router. (More details in this #59585)

This was a stop-gap and not an ideal solution, as this behavior means `router.refresh()` would effectively behave like reloading the page, where "stale" segments (ones that went from `__PAGE__` -> `__DEFAULT__`) would disappear.

Fixes #60815
Fixes #60950
Fixes #51711
Fixes #51714
Fixes #58715
Fixes #60948
Fixes #62213
Fixes #61341

Closes [NEXT-1845](https://linear.app/vercel/issue/NEXT-1845)
Closes [NEXT-2030](https://linear.app/vercel/issue/NEXT-2030)

Closes NEXT-2903

### CODE REVIEW

**Comment by ztanner** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vercel/next.js/63607?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#63607** <a href="https://app.graphite.dev/github/pr/vercel/next.js/63607?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#63606** <a href="https://app.graphite.dev/github/pr/vercel/next.js/63606?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ztanner and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c158aaf8668f66c7441745d0870fddc6ad087dd0

`pnpm test-start test/e2e/app-dir/parallel-routes-revalidation/parallel-routes-revalidation.test.ts`
- parallel-routes-revalidation > should submit the action and revalidate the page data
- parallel-routes-revalidation > should handle a redirect action when called in a slot

<details>
<summary>Expand output</summary>

  ● parallel-routes-revalidation › should submit the action and revalidate the page data

    TIMED OUT: 1

    0

    undefined

      636 |
      637 |   if (hardError) {
    > 638 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      639 |   }
      640 |   return false
      641 | }

      at check (lib/next-test-utils.ts:638:11)
      at Object.<anonymous> (e2e/app-dir/parallel-routes-revalidation/parallel-routes-revalidation.test.ts:24:7)

  ● parallel-routes-revalidation › should handle a redirect action when called in a slot

    TIMED OUT: false

    true

    undefined

      636 |
      637 |   if (hardError) {
    > 638 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      639 |   }
      640 |   return false
      641 | }

      at check (lib/next-test-utils.ts:638:11)
      at Object.<anonymous> (e2e/app-dir/parallel-routes-revalidation/parallel-routes-revalidation.test.ts:79:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-21-simply_applyRouterStatePatchToTree_handling | Change |
| - | - | - | - |
| buildDuration | 13.7s | 13.7s | N/A |
| buildDurationCached | 7.4s | 6.1s | N/A |
| nodeModulesSize | 198 MB | 198 MB | N/A |
| nextStartRea..uration (ms) | 435ms | 444ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-21-simply_applyRouterStatePatchToTree_handling | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 30.8 kB | 30.8 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | ✓ |
| 8299-HASH.js gzip | 5.04 kB | 5.04 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 242 B | 242 B | ✓ |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 99.3 kB | 99.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-21-simply_applyRouterStatePatchToTree_handling | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-21-simply_applyRouterStatePatchToTree_handling | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.21 kB | 4.21 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.57 kB | 6.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-21-simply_applyRouterStatePatchToTree_handling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-21-simply_applyRouterStatePatchToTree_handling | Change |
| - | - | - | - |
| index.html gzip | 530 B | 527 B | N/A |
| link.html gzip | 542 B | 540 B | N/A |
| withRouter.html gzip | 524 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-21-simply_applyRouterStatePatchToTree_handling | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.3 kB | 95.3 kB | N/A |
| page.js gzip | 3.04 kB | 3.04 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-21-simply_applyRouterStatePatchToTree_handling | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 625 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-21-simply_applyRouterStatePatchToTree_handling | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | ✓ |
| app-page-exp..prod.js gzip | 96.9 kB | 96.9 kB | ✓ |
| app-page-tur..prod.js gzip | 98.6 kB | 98.6 kB | ✓ |
| app-page-tur..prod.js gzip | 93.1 kB | 93.1 kB | ✓ |
| app-page.run...dev.js gzip | 144 kB | 144 kB | ✓ |
| app-page.run..prod.js gzip | 91.6 kB | 91.6 kB | ✓ |
| app-route-ex...dev.js gzip | 21.4 kB | 21.4 kB | ✓ |
| app-route-ex..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| app-route.ru...dev.js gzip | 21 kB | 21 kB | ✓ |
| app-route.ru..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim...dev.js gzip | 23.1 kB | 23.1 kB | ✓ |
| pages.runtim..prod.js gzip | 22.4 kB | 22.4 kB | ✓ |
| server.runti..prod.js gzip | 50.9 kB | 50.9 kB | ✓ |
| Overall change | 945 kB | 945 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 03-21-simply_applyRouterStatePatchToTree_handling | Change |
| - | - | - | - |
| 0.pack gzip | 1.57 MB | 1.57 MB | N/A |
| index.pack gzip | 106 kB | 106 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>2453-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: c158aaf8668f66c7441745d0870fddc6ad087dd0

File: packages/next/src/client/components/router-reducer/reducers/fast-refresh-reducer.ts [hunk 1]
```diff
@@ -69,11 +69,12 @@ function fastRefreshReducerImpl(
...
         // Given the path can only have two items the items are only the router state and rsc for the root.
         const [treePatch] = flightDataPath
-        const newTree = applyRouterStatePatchToTreeSkipDefault(
+        const newTree = applyRouterStatePatchToTree(
           // TODO-APP: remove ''
           [''],
           currentTree,
-          treePatch
+          treePatch,
+          location.pathname
```
Comment (lubieowoce) [inline packages/next/src/client/components/router-reducer/reducers/fast-refresh-reducer.ts:77]: can using the global `window.location` cause any weird bugs here? like race conditions with pending navigations or something?

Comment (ztanner) [reply packages/next/src/client/components/router-reducer/reducers/fast-refresh-reducer.ts:77]: Good question -- I don't think so since actions are processed sequentially - a navigation would have had to occur before this reducer would have had a chance to run.

But it might be safer to use `state.canonicalUrl` instead since that's meant to be the same value. The only reason I didn't is because it includes `location.search`, and I want to store only the `pathname` for these references. So I could probably do something like `new URL(state.canonicalUrl, location.origin).pathname` -- or maybe just `state.canonicalUrl.split('?')[0]`. Just felt kinda ugly either way 😆

**Review by timneutkens — APPROVED** [review]
