### PR TITLE
Unify Node and Edge externals list

### LINKED ISSUE #90765: Turbopack does not support imports from stream/consumers
### Link to the code that reproduces this issue

https://github.com/paulbrimicombe/nextjs-stream-consumers-bug

### To Reproduce

1. Install dependencies: `npm install`
2. Attempt to build the code using Turbopack: `npm run build` — the error `Module not found: Can't resolve 'stream/consumers'` will be displayed
3. Attempt to build the code using Webpack: `npm run build -- --webpack` — no errors will be shown
4. Update the code in `page.tsx` to add the `node:` prefix to the `stream/consumers` import
5. Attempt to build the code using Turbopack: `npm run build` — the error `Cannot find module 'node:stream/consumers': Unsupported external type Url for commonjs reference` will be displayed

### Current vs. Expected behavior

- [Utility consumer functions](https://nodejs.org/api/webstreams.html#utility-consumers) should be able to be imported without the `node:` prefix (like other Node.js libraries).
- These functions should be able to be imported in CommonJS code

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.6.0: Wed Nov  5 21:30:44 PST 2025; root:xnu-11417.140.69.705.2~1/RELEASE_ARM64_T6041
  Available memory (MB): 24576
  Available CPU cores: 14
Binaries:
  Node: 22.21.1
  npm: 11.10.0
  Yarn: 1.22.22
  pnpm: 10.28.0
Relevant Packages:
  next: 16.1.6 // Latest available version is detected (16.1.6).
  eslint-config-next: N/A
  react: 19.2.4
  react-dom: 19.2.4
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

A quick search of the Turbopack codebase for similar Node.js libraries such as `stream/promises` or `stream/web` indicates that there is some missing handling for `stream/consumers`.

### PR DESCRIPTION
**Pull request by mischnic**
Unify the list of Node/Edge iexternals.
Turns out `readline/promises` and `stream/consumers` was missing in some places.

Closes https://github.com/vercel/next.js/issues/90765

### CODE REVIEW

**Comment by mischnic** [comment]
* **#90819** <a href="https://app.graphite.com/github/pr/vercel/next.js/90819?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/vercel/next.js/90819?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/next-taskless/src/constants.rs [hunk 1]
```diff
@@ -50,28 +68,48 @@ pub const NODE_EXTERNALS: [&str; 64] = [
...
+// SAFETY: This has to be sorted alphabetically since we are doing binary search on it
+pub const EDGE_NODE_EXTERNALS: [&str; 7] = [
+    "assert",
+    "assert/strict",
+    "async_hooks",
+    "buffer",
+    "events",
+    "util",
+    "util/types",
+];
```
Comment (bgw) [inline crates/next-taskless/src/constants.rs:86]: Yep, this is better, listing the thing that are supported instead of the things that aren't.

**Review by bgw — APPROVED** [review]

**Comment by mischnic** [comment]
### Merge activity

* **Mar 4, 5:36 PM UTC**: @mischnic merged this pull request with [Graphite](https://app.graphite.com/github/pr/vercel/next.js/90819).
