### PR TITLE
Turbopack: lazy require metadata and handle TLA

### LINKED ISSUE #91676: Turbopack: dynamic metadata images (opengraph-image.tsx) fail with async module dependencies
### Link to the code that reproduces this issue

https://github.com/franky47/next-16.2.0-canary.0-repro

### To Reproduce

```bash
git clone https://github.com/franky47/next-16.2.0-canary.0-repro
cd next-16.2.0-canary.0-repro
pnpm install
pnpm build            # Fails with Turbopack (default)
pnpm build --webpack  # Works
```

A dynamic route `app/blog/[slug]` has an `opengraph-image.tsx` that imports from `app/data.ts`, which uses top-level `await` (making it an async module). Any module that transitively depends on async modules (content collections, MDX processing, etc.) will trigger this.

### Current vs. Expected behavior

**Current:** Build fails during static page generation with:

```
Error occurred prerendering page "/blog/some-slug"
TypeError: Cannot read properties of undefined (reading 'default')
    at collectStaticImagesFiles (resolve-metadata.ts)
```

**Expected:** Build succeeds, as it does with `next build --webpack` or on Next.js 16.1.7.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.6.0: Mon Jan 19 22:01:58 PST 2026; root:xnu-11417.140.69.708.3~1/RELEASE_ARM64_T6041
  Available memory (MB): 131072
  Available CPU cores: 16
Binaries:
  Node: 24.11.0
  npm: 11.6.2
  Yarn: 1.22.22
  pnpm: 10.27.0
Relevant Packages:
  next: 16.2.1-canary.1 // Latest available version is detected (16.2.1-canary.1).
  eslint-config-next: N/A
  react: 19.2.4
  react-dom: 19.2.4
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

I detected this issue when upgrading to next@16.2.0 in the [nuqs](https://github.com/47ng/nuqs) docs app.

### Root cause

Bisected to [PR #88487](https://github.com/vercel/next.js/pull/88487) ("Turbopack: retain loader tree order for metadata"), which shipped in 16.2.0-canary.0.

That PR changed how Turbopack references dynamic metadata image modules in the app-page template (`crates/next-core/src/app_page_loader_tree.rs`):

**Before (16.1.7, working):**
```js
import __TURBOPACK__openGraph__5__ from "METADATA_5";
// ...
metadata: { openGraph: [__TURBOPACK__openGraph__5__] }
```

**After (16.2.0, broken):**
```js
const __TURBOPACK__openGraph__5__ = require("METADATA_5");
// ...
metadata: { openGraph: [__TURBOPACK__openGraph__5__.default] }
```

The `require()` is synchronous, but the metadata module can be async when `opengraph-image.tsx` transitively depends on async modules (top-level await, async module initialization from libraries like fumadocs-mdx, content collections, etc.). The synchronous `require()` returns before async initialization completes, so `.default` is `undefined`. The route tree is then constructed with `[undefined]` in the metadata arrays.

Later, `collectStaticImagesFiles` in `resolve-metadata.ts` iterates the array and calls `interopDefault(undefined)` → `undefined.default` → TypeError.

**Why webpack is unaffected:** The webpack code path in `metadata/discover.ts` wraps dynamic metadata images in async factory functions:
```js
(async (props) => (await import(/* webpackMode: "eager" */ "...")).default(props))
```
The `.default` access is deferred until the async import resolves.

**Why static images are unaffected in Turbopack:** `write_static_metadata_item` in the same Rust file already wraps static images in async factory functions. Only `write_metadata_item` for `MetadataWithAltItem::Dynamic` uses the broken synchronous pattern.

<details>
<summary>

Suggested fix (from Opus 4.6)

</summary>

Wrap dynamic metadata items in async factory functions (matching both the webpack behavior and the existing Turbopack `write_static_metadata_item` behavior), so `.default` is accessed after async initialization completes:

```js
// Instead of:
const mod = require("METADATA_5");
metadata: { openGraph: [mod.default] }

// Wrap in an async factory:
metadata: { openGraph: [async (props) => {
  const mod = await import("METADATA_5");
  return mod.default(props);
}] }
```

</details>

### Bisect results

| Version | Result |
|---------|--------|
| 16.1.7 | pass |
| 16.2.0-canary.0 | **fail** |
| 16.2.0 | fail |

### Additional context

- PR #88487 was fixing [#87322](https://github.com/vercel/next.js/issues/87322) (infinite compilation loop caused by ESM import hoisting breaking loader tree order). The fix is correct for that issue, but the switch to synchronous `require()` + immediate `.default` doesn't account for async metadata modules.
- Any project using content layer tools (fumadocs-mdx, Contentlayer, etc.) that compile MDX at build time will likely hit this, since the compiled MDX modules are async under Turbopack.

### PR DESCRIPTION
**Pull request by mischnic**
A regression from #88487

1. Make metadata import lazy with `() => require()`, just like for the layout segments
2. Properly await the return value to better handle TLA modules

This align with Webpack which does this:

Bildschirmfoto 2026-03-20 um 11 58 00

Closes PACK-6927
Closes #91700
Closes https://github.com/vercel/next.js/issues/91676

### CODE REVIEW

**Comment by mischnic** [comment]
* **#91705** <a href="https://app.graphite.com/github/pr/vercel/next.js/91705?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/vercel/next.js/91705?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/next-core/src/app_page_loader_tree.rs [hunk 1]
```diff
@@ -255,8 +258,51 @@ impl AppPageLoaderTreeBuilder {
...
+        } else {
+            None
+        };
+
         let s = "      ";
-        writeln!(self.loader_tree_code, "{s}(async (props) => [{{")?;
+        writeln!(self.loader_tree_code, "{s}(async (props) => {{")?;
+        writeln!(
+            self.loader_tree_code,
+            "const mod = interopDefault(await {identifier}());"
```
Comment (sokra) [inline crates/next-core/src/app_page_loader_tree.rs]:
```suggestion
            "{s}  const mod = interopDefault(await {identifier}());"
```

File: crates/next-core/src/app_page_loader_tree.rs [hunk 2]
```diff
@@ -255,8 +258,51 @@ impl AppPageLoaderTreeBuilder {
...
+        )?;
+        if let Some(alt) = &alt {
+            writeln!(
+                self.loader_tree_code,
+                "const alt = interopDefault(await {alt}());"
```
Comment (sokra) [inline crates/next-core/src/app_page_loader_tree.rs]:
```suggestion
                "{s}  const alt = interopDefault(await {alt}());"
```

File: crates/next-core/src/app_page_loader_tree.rs [hunk 3]
```diff
@@ -255,8 +258,51 @@ impl AppPageLoaderTreeBuilder {
...
+            )?;
+        }
+        writeln!(self.loader_tree_code, "return [{{")?;
```
Comment (sokra) [inline crates/next-core/src/app_page_loader_tree.rs]:
```suggestion
        writeln!(self.loader_tree_code, "{s}  return [{{")?;
```

File: crates/next-core/src/app_page_loader_tree.rs [hunk 4]
```diff
@@ -266,67 +312,35 @@ impl AppPageLoaderTreeBuilder {
         writeln!(
             self.loader_tree_code,
             "{s}  url: fillMetadataSegment({}, await props.params, {}, true) + \
```
Comment (sokra) [inline crates/next-core/src/app_page_loader_tree.rs]:
```suggestion
            "{s}    url: fillMetadataSegment({}, await props.params, {}, true) + \
```

File: crates/next-core/src/app_page_loader_tree.rs [hunk 5]
```diff
@@ -266,67 +312,35 @@ impl AppPageLoaderTreeBuilder {
...
-             `?${{{identifier}.default.src.split(\"/\").splice(-1)[0]}}`,",
+             `?${{mod.src.split(\"/\").splice(-1)[0]}}`,",
```
Comment (sokra) [inline crates/next-core/src/app_page_loader_tree.rs:314]: Preexisting, but this `src.split(\"/\").splice(-1)[0]` feels weird

File: crates/next-core/src/app_page_loader_tree.rs [hunk 6]
```diff
@@ -266,67 +312,35 @@ impl AppPageLoaderTreeBuilder {
...
-            writeln!(
-                self.loader_tree_code,
-                "{s}  width: {identifier}.default.width,"
-            )?;
-            writeln!(
-                self.loader_tree_code,
-                "{s}  height: {identifier}.default.height,"
-            )?;
+            writeln!(self.loader_tree_code, "{s}  width: mod.width,")?;
+            writeln!(self.loader_tree_code, "{s}  height: mod.height,")?;
```
Comment (sokra) [inline crates/next-core/src/app_page_loader_tree.rs]:
```suggestion
            writeln!(self.loader_tree_code, "{s}    width: mod.width,")?;
            writeln!(self.loader_tree_code, "{s}    height: mod.height,")?;
```

File: crates/next-core/src/app_page_loader_tree.rs [hunk 7]
```diff
@@ -266,67 +312,35 @@ impl AppPageLoaderTreeBuilder {
...
-                .to_resolved()
-                .await?;
-
-            self.base
-                .inner_assets
-                .insert(inner_module_id.into(), module);
-
-            writeln!(self.loader_tree_code, "{s}  alt: {identifier}.default,")?;
+        if alt.is_some() {
+            writeln!(self.loader_tree_code, "{s}  alt,")?;
```
Comment (sokra) [inline crates/next-core/src/app_page_loader_tree.rs]:
```suggestion
            writeln!(self.loader_tree_code, "{s}    alt,")?;
```

File: crates/next-core/src/app_page_loader_tree.rs [hunk 8]
```diff
@@ -266,67 +312,35 @@ impl AppPageLoaderTreeBuilder {
...
+                "any"
             } else {
-                format!("${{{identifier}.default.width}}x${{{identifier}.default.height}}")
+                "${mod.width}x${mod.height}"
             };
             writeln!(self.loader_tree_code, "{s}  sizes: `{sizes}`,")?;
         }
 
         let content_type = get_content_type(path).await?;
         writeln!(self.loader_tree_code, "{s}  type: `{content_type}`,")?;
```
Comment (sokra) [inline crates/next-core/src/app_page_loader_tree.rs]:
```suggestion
        writeln!(self.loader_tree_code, "{s}    type: `{content_type}`,")?;
```

File: crates/next-core/src/app_page_loader_tree.rs [hunk 9]
```diff
@@ -266,67 +312,35 @@ impl AppPageLoaderTreeBuilder {
...
             // For the images doesn't provide the size properly, use "any" as well.
             // If the size is presented, use the actual size for the image.
             let sizes = if path.has_extension(".svg") {
-                "any".to_string()
+                "any"
             } else {
-                format!("${{{identifier}.default.width}}x${{{identifier}.default.height}}")
+                "${mod.width}x${mod.height}"
             };
             writeln!(self.loader_tree_code, "{s}  sizes: `{sizes}`,")?;
```
Comment (sokra) [inline crates/next-core/src/app_page_loader_tree.rs]:
```suggestion
            writeln!(self.loader_tree_code, "{s}    sizes: `{sizes}`,")?;
```

File: crates/next-core/src/app_page_loader_tree.rs [hunk 10]
```diff
@@ -266,67 +312,35 @@ impl AppPageLoaderTreeBuilder {
...
-                .inner_assets
-                .insert(inner_module_id.into(), module);
-
-            writeln!(self.loader_tree_code, "{s}  alt: {identifier}.default,")?;
+        if alt.is_some() {
+            writeln!(self.loader_tree_code, "{s}  alt,")?;
         }
 
-        writeln!(self.loader_tree_code, "{s}}}]),")?;
+        writeln!(self.loader_tree_code, "{s}}}];}}),")?;
```
Comment (sokra) [inline crates/next-core/src/app_page_loader_tree.rs]: Should be two lines

**Review by sokra — APPROVED** [review]
