### PR TITLE
fix: deprecated util._extend

### LINKED ISSUE #74460: DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
### Link to the code that reproduces this issue

https://github.com/kuanjiahong/deprecation-warning-app

### To Reproduce

**Development mode**
1. Start the application in development `npm run dev`
2. Go to `http://localhost:3000`
3. Click the button to rewrite the url
4. Check the console for the deprecation warning

**Deployment - Node.js Server**
1. Build the application `npm run build`
2. Run the application `npm run start`
3. Go to `http://localhost:3000`
4. Click the button to rewrite the url
5. Check the console for the deprecation warning

**Deployment - Docker image"
1. Build container `docker build -t nextjs-docker .`
2. Run container: `docker run -p 3000:3000 nextjs-docker`
3. Go to `http://localhost:3000`
4. Click the button to rewrite the url
5. Check the console for the deprecation warning

### Current vs. Expected behavior

Current behaviour:

A deprecation warning is shown:

```bash
[DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
When used node --trace-deprecation to show where the warning was created:
```
(node:1) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
    at ProxyServer.<anonymous> (/app/node_modules/next/dist/compiled/http-proxy/index.js:13:2607)
    at proxyRequest (/app/node_modules/next/dist/server/lib/router-utils/proxy-request.js:108:15)
    at handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:332:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async requestHandlerImpl (/app/node_modules/next/dist/server/lib/router-server.js:441:13)
    at async Server.requestListener (/app/node_modules/next/dist/server/lib/start-server.js:155:13)
```

Expected behaviour:
No deprecation warning.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Enterprise
  Available memory (MB): 32562
  Available CPU cores: 8
Binaries:
  Node: 22.12.0
  npm: 10.9.2
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.1.1-canary.23 // Latest available version is detected (15.1.1-canary.23).
  eslint-config-next: N/A
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.3.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Runtime

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Other (Deployed)

### Additional context

I found these related issue: #72220 #71374

### PR DESCRIPTION
**Pull request by Netail**
### What?

Fix deprecated warning: "Use Object.assign instead of deprecated util._extend" from http-proxy (which hasn't been updated for 5 years)

### How?

Fixes #74460
In favour of https://github.com/vercel/next.js/pull/81544 (which didn't use a patch, but manually updated the compiled version)

### CODE REVIEW

File: packages/next/src/compiled/http-proxy/index.js [hunk 1]
```diff
@@ -10,25 +10,25 @@
...
...te(createHttpHeader("HTTP/1.1 101 Switching Protocols",e.headers));r.pipe(t).pipe(r);a.emit("open",r);a.emit("proxySocket",r)}));return u.end();function onOutgoingError(r){if(c){c(r,e,t)}else{a.emit("error",r,e,t)}t.end()}}}},85:e=>{"use strict";e.exports=function required(e,t){t=t.split(":")[0];e=+e;if(!e)return false;switch(t){case"http":case"ws":return e!==80;case"https":case"wss":return e!==443;case"ftp":return e!==21;case"gopher":return e!==70;case"file":return false}return e!==0}},491:e=>{"use strict";e.exports=require("assert")},685:e=>{"use strict";e.exports=require("http")},687:e=>{"use strict";e.exports=require("https")},937:e=>{"use strict";e.exports=require("next/dist/compiled/debug")},781:e=>{"use strict";e.exports=require("stream")},310:e=>{"use strict";e.exports=require("url")},837:e=>{"use strict";e.exports=require("util")}};var t={};function __nccwpck_require__(r){var o=t[r];if(o!==undefined){return o.exports}var s=t[r]={exports:{}};var n=true;try{e[r](s,s.exports,__nccwpck_require__);n=false}finally{if(n)delete t[r]}return s.exports}if(typeof __nccwpck_require__!=="undefined")__nccwpck_require__.ab=__dirname+"/";var r=__nccwpck_require__(768);module.exports=r})();
```
Comment (ijjk) [inline packages/next/src/compiled/http-proxy/index.js:34]: I'm still seeing util be pulled in here, is there somewhere else that needs to be updated in the patch?

Comment (Netail) [reply packages/next/src/compiled/http-proxy/index.js:34]: That seems to be the line `require('util').inherits(ProxyServer, EE3);` in http-proxy, but nodejs didn't deprecated the whole "util" module, just `_extend`. Which, with this patch, doesn't get used anymore. `inherits` has not been deprecated

Comment (ijjk) [reply packages/next/src/compiled/http-proxy/index.js:34]: Ah gotcha seems alright then, thanks for confirming

**Review by ijjk — APPROVED** [review]
