### PR TITLE
graceful shutdown

### LINKED ISSUE #53661: Close http server in cleanup
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.3.1
      npm: 9.6.7
      Yarn: 1.22.18
      pnpm: 7.29.3
    Relevant Packages:
      next: 13.4.13-canary.18
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Standalone mode (output: "standalone")

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Meemaw/next-server-shutdown-reproducer

### To Reproduce

1. yarn build
2. yarn start
3. Visit http://localhost:3000
4. Close the server before the page renders
5. Get a "This site can’t be reached" error

### Describe the Bug

NextJS doesn't gracefully handle inflight HTTP server connections. There is a cleanup code
https://github.com/vercel/next.js/blob/498692b69812a096178eaabfea766f4d8fa82413/packages/next/src/server/lib/start-server.ts#L262

, but it doesn't call `server.cleanup()`.

There also seems to be a `teardown` function defined https://github.com/vercel/next.js/blob/498692b69812a096178eaabfea766f4d8fa82413/packages/next/src/server/lib/start-server.ts#L500)

, which does the correct thing, but is never called?

### Expected Behavior

`server.cleanup()` should be called & awaited so any inflight requests are gracefully handled.

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

<sub>[NEXT-1961](https://linear.app/vercel/issue/NEXT-1961/close-http-server-in-cleanup)</sub>

### PR DESCRIPTION
**Pull request by redbmk**
- Both the standalone server and the `startServer` function it calls attempt to stop the server on `SIGINT` and `SIGTERM` in different ways. This lets `server.js` yield to `startServer`
- The cleanup function in `startServer` was not waiting for the server to close before calling `process.exit`. This lets it wait for any in-flight requests to finish processing before exiting the process
- Sends `SIGKILL` to the child process in `next dev`, which should have the same effect of immediately shutting down the server on `SIGTERM` or `SIGINT`

fixes: #53661
refs: #59551

------

Previously #59551 attempted to fix #53661, but had broken some tests in the process. It looks like the final commit was also missing an intended change to `utils.ts`. This should fix those issues as well as introduce a new set of tests for the graceful shutdown feature.

In the last PR I was squashing and force-pushing updates along the way but it made it difficult to track the changes. This time I'm pushing quite a few commits to make it easier to track the changes and refactors I've made, with the idea that this should be squashed before being merged.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 4f74aee9987c5a82d498dfebed9be2365a1e7a6b

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 4f74aee9987c5a82d498dfebed9be2365a1e7a6b

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

File: packages/next/src/bin/next.ts [hunk 1]
```diff
@@ -108,12 +108,6 @@ if (process.env.NODE_ENV) {
 ;(process.env as any).NODE_ENV = process.env.NODE_ENV || defaultEnv
 ;(process.env as any).NEXT_RUNTIME = 'nodejs'
 
-// Make sure commands gracefully respect termination signals (e.g. from Docker)
-// Allow the graceful termination to be manually configurable
-if (!process.env.NEXT_MANUAL_SIG_HANDLE && command !== 'dev') {
```
Comment (redbmk) [inline packages/next/src/bin/next.ts:113]: removing this one is necessary for `next dev` and `next start` to gracefully shutdown. The env is still in `start-server`

File: packages/next/src/build/utils.ts [hunk 2]
```diff
@@ -2049,13 +2049,6 @@ const dir = path.join(__dirname)
 process.env.NODE_ENV = 'production'
 process.chdir(__dirname)
 
-// Make sure commands gracefully respect termination signals (e.g. from Docker)
-// Allow the graceful termination to be manually configurable
-if (!process.env.NEXT_MANUAL_SIG_HANDLE) {
```
Comment (redbmk) [inline packages/next/src/build/utils.ts:2054]: removing this one is necessary for standalone mode to gracefully shutdown. The env is still in `start-server`

File: test/lib/next-modes/base.ts [hunk 3]
```diff
@@ -342,14 +343,8 @@ export class NextInstance {
...
-    if (this.childProcess) {
-      let exitResolve
-      const exitPromise = new Promise((resolve) => {
-        exitResolve = resolve
-      })
-      this.childProcess.addListener('exit', () => {
-        exitResolve()
-      })
+    if (this.childProcess && !this.isStopping) {
+      const exitPromise = once(this.childProcess, 'exit')
```
Comment (redbmk) [inline test/lib/next-modes/base.ts:347]: I had started making changes here and turned out they weren't needed, but I thought I'd keep this refactor since `once` seemed a little cleaner when I learned about it.

File: test/lib/next-test-utils.ts [hunk 4]
```diff
@@ -523,10 +524,24 @@ export async function killProcess(
...
+    return true
+  } catch {
+    return false
+  }
+}
+
 // Kill a launched app
 export async function killApp(instance: ChildProcess) {
-  if (instance && instance.pid) {
+  if (instance?.pid && isAppRunning(instance)) {
```
Comment (redbmk) [inline test/lib/next-test-utils.ts:541]: no need to kill the app if it's already running.

File: test/production/graceful-shutdown/index.test.ts [hunk 5]
```diff
@@ -0,0 +1,236 @@
...
+      })
+
+      it('when there is no activity', async () => {
+        const appKilledPromise = once(app, 'exit')
+
+        process.kill(app.pid, 'SIGTERM')
+        expect(isAppRunning(app)).toBe(true)
+
+        // yield event loop to allow server to start the shutdown process
+        await waitFor(20)
```
Comment (redbmk) [inline test/production/graceful-shutdown/index.test.ts:226]: I was running into some issues with these tests. Waiting 20 ms seems to be the sweet spot but I'm a little worried there could be race conditions causing this to sometimes fail.

File: test/production/graceful-shutdown/pages/api/long-running.ts [hunk 6]
```diff
@@ -0,0 +1,6 @@
+export const LONG_RUNNING_MS = 400
```
Comment (redbmk) [inline test/production/graceful-shutdown/pages/api/long-running.ts]: I had lowered this to `100` but seemed to run into less race conditions bumping it up higher. In practice, `400ms` wouldn't really be a "long running" request but should be enough to simulate the issue in tests.

**Comment by redbmk** [comment]
@huozhi, pinging you since you reviewed the last PR recently. One thing I noticed was that one of the tests that had failed in the previous PR I was able to get to fail randomly on the latest (as of a week or so ago) `canary`. https://github.com/vercel/next.js/pull/59551#pullrequestreview-1782132150

If I ran it locally a few times it would sometimes pass and sometimes fail. Not sure if it's been fixed since then.

The other tests that were failing though I think I've fixed

**Comment by redbmk** [comment]
Just marked as a draft because I want to run a couple more manual tests:

- [ ] make sure the previously failing tests from the last PR are passing
- [ ] apply these changes locally and run the dev and prod servers to make sure the behavior feels correct
- [ ] run the new tests a decent number of times to make sure they aren't occasionally failing (eg due to race conditions)

File: packages/next/src/cli/next-dev.ts [hunk 7]
```diff
@@ -108,8 +119,11 @@ const handleSessionStop = async (signal: string | null) => {
   process.exit(0)
 }
 
-process.on('SIGINT', () => handleSessionStop('SIGINT'))
-process.on('SIGTERM', () => handleSessionStop('SIGTERM'))
+process.on('SIGINT', () => handleSessionStop('SIGKILL'))
+process.on('SIGTERM', () => handleSessionStop('SIGKILL'))
```
Comment (redbmk) [inline packages/next/src/cli/next-dev.ts:123]: a little unsure about switching this to SIGKILL because it could potentially mess with someone using a custom signal but it looks like that was never supported in `next dev` anyway, at least officially:

https://nextjs.org/docs/pages/building-your-application/deploying

> **Good to know**: Manual signal handling is not available in `next dev`.

Also because of the block in `packages/next/src/bin/next.ts` that's removed in this MR, it has the extra check `command !== 'dev'`, so behavior should effectively be the same (exit the child immediately when the dev server receives SIGINT or SIGTERM)

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f3c875def3f53847a18ba1aada0eb750dbfa3aee

`pnpm test-dev test/development/app-dir/basic/basic.test.ts` 
- basic app-dir tests > should reload app pages without error

<details>
<summary>Expand output</summary>

  ● basic app-dir tests › should reload app pages without error

    stop() must be called before cleaning

      319 |   public async clean() {
      320 |     if (this.childProcess) {
    > 321 |       throw new Error(`stop() must be called before cleaning`)
          |             ^
      322 |     }
      323 |
      324 |     const keptFiles = [

      at NextDevInstance.clean (lib/next-modes/base.ts:321:13)
      at clean (lib/development-sandbox.ts:34:14)
      at Object.<anonymous> (development/app-dir/basic/basic.test.ts:11:43)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js graceful-shutdown | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.8s | ⚠️ +126ms |
| buildDurationCached | 7.1s | 6s | N/A |
| nodeModulesSize | 202 MB | 202 MB | N/A |
| nextStartRea..uration (ms) | 427ms | 420ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js graceful-shutdown | Change |
| - | - | - | - |
| 193.HASH.js gzip | 181 B | 182 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 433-HASH.js gzip | 28.4 kB | 28.4 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 240 B | 242 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js graceful-shutdown | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js graceful-shutdown | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 183 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 502 B | N/A |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 253 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.28 kB | 4.28 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | ✓ |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.4 kB | 3.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js graceful-shutdown | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js graceful-shutdown | Change |
| - | - | - | - |
| index.html gzip | 528 B | 526 B | N/A |
| link.html gzip | 541 B | 538 B | N/A |
| withRouter.html gzip | 524 B | 521 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js graceful-shutdown | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.7 kB | 93.7 kB | N/A |
| page.js gzip | 147 kB | 147 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js graceful-shutdown | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 625 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | ✓ |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 39.5 kB | 39.5 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js graceful-shutdown | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 94.2 kB | 94.2 kB | ✓ |
| app-page-tur..prod.js gzip | 94.9 kB | 94.9 kB | ✓ |
| app-page-tur..prod.js gzip | 89.4 kB | 89.4 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.7 kB | 88.7 kB | ✓ |
| app-route-ex...dev.js gzip | 24.1 kB | 24.1 kB | ✓ |
| app-route-ex..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| app-route.ru...dev.js gzip | 23.5 kB | 23.5 kB | ✓ |
| app-route.ru..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.38 kB | 9.38 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.65 kB | 9.65 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.4 kB | 49.4 kB | N/A |
| Overall change | 882 kB | 882 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>433-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: f3c875def3f53847a18ba1aada0eb750dbfa3aee

**Comment by redbmk** [comment]
That's a lot of failing tests. I have a feeling most are related to the change in `test/lib/next-modes/base.ts`. I'll mark it as a draft again until I can get these squared away

File: packages/next/src/bin/next.ts [hunk 8]
```diff
@@ -108,12 +108,11 @@ if (process.env.NODE_ENV) {
...
+if (command === 'build') {
```
Comment (redbmk) [inline packages/next/src/bin/next.ts:111]: we still want to stop the CLI immediately if SIGTERM or SIGINT is used for building. There's also a test for this already that was breaking if we remove these handlers for all commands.

File: test/integration/css-client-nav/test/index.test.js [hunk 9]
```diff
@@ -180,6 +181,8 @@ describe('CSS Module client-side navigation', () => {
     })
     afterAll(async () => {
       proxyServer.close()
+      // something is hanging onto the process, so we need to SIGKILL
+      await killProcess(app.pid, 'SIGKILL')
```
Comment (redbmk) [inline test/integration/css-client-nav/test/index.test.js:185]: I wasn't able to track down why the app wouldn't close. I tried closing `proxyServer` as well as `proxy` in different orders, but both of them would hang if I waited for the `close` callback. I tried killing both of those with `killApp` which seemed to shut them down, but `killApp(app)` would still hang.

Using `SIGKILL` was the only way I found to work. Before this change, it would have been calling `process.exit(0)` immediately on receiving SIGTERM, so the end result should be the same.

**Comment by redbmk** [comment]
These tests are now failing in the pipeline, but they work for me locally

```
test/development/acceptance-app/rsc-runtime-errors.test.ts
test/development/basic/barrel-optimization/barrel-optimization.test.ts 
```

These are the errors in the pipeline, which seem to have something to do with a cache. Is it possible there's an issue with the test runners? I'm not sure how my changes would have affected a `yarn install`.

```
error Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, open '/usr/local/share/.cache/yarn/v6/.tmp/7327f839ffa162ea7d5801d9101b1c89/dist/build/polyfills/process.js'"

error Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, stat '/usr/local/share/.cache/yarn/v6/.tmp/7327f839ffa162ea7d5801d9101b1c89/dist/compiled/react-dom/cjs/react-dom.production.js'"
  
error Extracting tar content of undefined failed, the file appears to be corrupt: "EEXIST: file already exists, mkdir '/usr/local/share/.cache/yarn/v6/.tmp/7327f839ffa162ea7d5801d9101b1c89/dist/build/templates'"
```

**Comment by redbmk** [comment]
@huozhi This now seems to be the only failing test (when I updated the branch earlier the other failing tests went away)

```
✕ should render the 404 page when the file is removed, and restore the page when re-added (32898 ms)
```

However, I had noticed that this same test failed in the `canary` branch and passed after the test suite was reran. So I don't think it's related to my changes.

I'll try updating again since there have been more merges, and see if the new run makes that one go away (or brings in any new ones)

**Comment by huozhi** [comment]
Previous was flaky, `pnpm test test/integration/api-support/test/index.test.js` seems failing after re-run the CI

File: packages/next/src/server/lib/start-server.ts [hunk 10]
```diff
@@ -279,11 +278,11 @@ export async function startServer(
           // This is the render worker, we keep the process alive
           console.error(err)
         }
-        process.on('exit', (code) => cleanup(code))
```
Comment (huozhi) [inline packages/next/src/server/lib/start-server.ts:282]: Why we don't need to handle `'exit'` anymore?

Comment (redbmk) [reply packages/next/src/server/lib/start-server.ts:282]: The `exit` event is sent right before the process exits and it can only execute synchronous code. I suppose we could capture it if we wanted to force the exit code to be `0`, but I was thinking letting it send the code it got made sense. 
https://nodejs.org/api/process.html#event-exit

> There is no way to prevent the exiting of the event loop at this point, and once all `'exit'` listeners have finished running the Node.js process will terminate.

> Listener functions **must** only perform **synchronous** operations. The Node.js process will exit immediately after calling the `'exit'` event listeners causing any additional work still queued in the event loop to be abandoned.

Since `server.close` is asychronous, I don't think calling it on the `'exit'` event would do anything useful

https://nodejs.org/api/net.html#serverclosecallback

> This function is asynchronous

I could see there maybe being a couple things that `server.close` does synchronously, but it definitely would exit without calling the callback.

**Comment by redbmk** [comment]
> Previous was flaky, `pnpm test test/integration/api-support/test/index.test.js` seems failing after re-run the CI

I'm starting to think we have the `killApp` test util send a `SIGKILL` by default just to ensure the app is killed right away, and then if any tests want to test another signal like `SIGINT` (e.g. the new tests or some of the CLI tests) they can just pass that as an extra param to `killApp`. Kinda feels like there are some cases where it doesn't quite catch the exit signal for some reason and then it times out.

**Comment by redbmk** [comment]
I'm trying to figure out why [test prod (3/5) / build](https://github.com/vercel/next.js/actions/runs/7514231305/job/20456884756?pr=60059) would have failed in [e49fb6d](https://github.com/vercel/next.js/pull/60059/commits/e49fb6d0b7c2a810e4989f251e0ce47a2e1b2a29), since it seems unrelated to the stuff I did.


<details>
<summary>When I re-ran the failed test locally, both in my branch and on `canary`, it fails the same way both times.</summary>

```
test/production/prerender-prefetch/index.test.ts

❯ pnpm testheadless test/production/prerender-prefetch/index.test.ts -t "unstable_skip"

 FAIL  test/production/prerender-prefetch/index.test.ts (133.785 s)
  Prerender prefetch
    with optimisticClientCache enabled
      ✓ should update cache using prefetch with unstable_skipClientCache (3556 ms)
      ✓ should update cache using router.push with unstable_skipClientCache (2268 ms)
      ○ skipped should not revalidate during prefetching
      ○ skipped should trigger revalidation after navigation
      ○ skipped should attempt cache update on link hover/touch start
      ○ skipped should handle failed data fetch and empty cache correctly
    with optimisticClientCache disabled
      ✓ should update cache using prefetch with unstable_skipClientCache (2391 ms)
      ✕ should update cache using router.push with unstable_skipClientCache (2276 ms)
      ○ skipped should not revalidate during prefetching
      ○ skipped should trigger revalidation after navigation
      ○ skipped should not attempt client cache update on link hover/touch start
      ○ skipped should handle failed data fetch and empty cache correctly

  ● Prerender prefetch › with optimisticClientCache disabled › should update cache using router.push with unstable_skipClientCache

    expect(received).not.toBe(expected) // Object.is equality

    Expected: not 1705179893593

      154 |         await browser.elementByCss('#props').text()
      155 |       ).now
    > 156 |       expect(newTime).not.toBe(startTime)
          |                           ^
      157 |       expect(isNaN(newTime)).toBe(false)
      158 |     })
      159 |

      at Object.toBe (production/prerender-prefetch/index.test.ts:156:27)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 8 skipped, 3 passed, 12 total
Snapshots:   0 total
Time:        133.827 s, estimated 158 s
Ran all test suites matching /test\/production\/prerender-prefetch\/index.test.ts/i with tests matching "unstable_skip".
```
</details>

Is this a known flaky test? It looks like when I updated to the latest canary the tests are now passing, but that only included two extra commits.

I tried running that test locally on the latest `canary` 10 times in a row and of those 10, `should update cache using router.push with unstable_skipClientCache` failed every time with `optimisticClientCache` disabled, and 8/10 times for the tests where it's enabled.

**Comment by redbmk** [comment]
I'm not sure this PR would affect that code, but I just want to be sure I'm not breaking anything. Once bitten, twice shy 😂 

I'll try keeping this PR up to date with `canary` as new commits come in to see if any other failures start cropping up.

File: packages/next/src/server/lib/start-server.ts (hunk 10 above)
Comment (redbmk) [reply packages/next/src/server/lib/start-server.ts:282]: Also just realized it was already using the original exit code and just defaulting to 0, so the behavior should still be the same without listening for the event

**Review by huozhi — APPROVED** [review]
Looks good, thanks!
