### PR TITLE
fix(#53190): add missing crossOrigin to assetsPrefix resources

### LINKED ISSUE #53190: app dir next.config.js option `crossOrigin: 'anonymous'` not working
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: 8.6.2
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: standalone
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/boring-dust-mjv4ps

### To Reproduce

1. open above codesandbox link
2. see next.config.js exises `crossOrigin: 'anonymous'` option
3. open browser console, see script is not exises `crossOrigin: 'anonymous'`

### Describe the Bug

nextjs v13, app dir,  next.config.js exises `crossOrigin: 'anonymous'` option but not working

### Expected Behavior

how to add crossOrigin='anonymous' to script ?

### Which browser are you using? (if relevant)

Chrome 114.0.0.0

### How are you deploying your application? (if relevant)

next start

<sub>[NEXT-1475](https://linear.app/vercel/issue/NEXT-1475/app-dir-nextconfigjs-option-crossorigin-anonymous-not-working)</sub>

### PR DESCRIPTION
**Pull request by SukkaW**
Fixes #53190.

Next.js App Router comprises two categories of resources, same-origin ones (RSC payload, in the form of inline `<script />`) and possibly third-party ones (chunks that respect the `assetPrefix`). The latter should also respect the `crossOrigin` option from `next.config.js`.

### CODE REVIEW

File: packages/next/src/server/app-render/app-render.tsx [hunk 1]
```diff
@@ -1446,21 +1448,26 @@ export const renderToHTMLOrFlight: AppPageRender = (
...
+            )
+            .map((polyfill) => ({
+              src: `${assetPrefix}/_next/${polyfill}${getAssetQueryString(
+                false
+              )}`,
+              integrity: subresourceIntegrityManifest?.[polyfill],
+              crossOrigin: renderOpts.crossOrigin,
+              noModule: true,
+              nonce,
+            }))
```
Comment (SukkaW) [inline packages/next/src/server/app-render/app-render.tsx:1465]: Here I simplify the `polyfills` by making its type as `JSX.IntrinsicElements['script'][]`, so it can be spread (`{...polyfill}`) on the JSX later.

File: packages/next/src/server/app-render/required-scripts.tsx [hunk 2]
```diff
@@ -5,24 +5,35 @@ import ReactDOM from 'react-dom'
...
   let preinitScriptCommands: string[] = []
-  let bootstrapScript: string | { src: string; integrity: string } = ''
+  const bootstrapScript: {
+    src: string
+    integrity?: string
+    crossOrigin?: string | undefined
+  } = {
+    src: '',
+    crossOrigin,
+  }
```
Comment (SukkaW) [inline packages/next/src/server/app-render/required-scripts.tsx:25]: Although the `bootstrapScripts` option of `ReactDOMServer.renderToReadableStream` supports both string and object type, here I enforce the use of object type so we won't forget other attributes in the future.

File: packages/next/src/server/app-render/types.ts [hunk 3]
```diff
@@ -111,6 +111,7 @@ export type RenderOptsPartial = {
   runtime?: ServerRuntime
   serverComponents?: boolean
   assetPrefix?: string
+  crossOrigin?: '' | 'anonymous' | 'use-credentials' | undefined
```
Comment (SukkaW) [inline packages/next/src/server/app-render/types.ts:114]: `renderOpt.crossOrigin` exists on `PagesRenderOptsPartial` but it is missing on `AppRenderOptsPartial` here.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8ebab8f139cacf484db6183ddd3bdc654f3acca8

`pnpm test-start test/e2e/app-dir/app-config-crossorigin/test/index.test.ts` 
- app dir - crossOrigin config > should render correctly with assetPrefix: "/"

<details>
<summary>Expand output</summary>

  ● app dir - crossOrigin config › should render correctly with assetPrefix: "/"

    TypeError: Invalid URL

      160 | ): Promise<Response> {
      161 |   const url = query ? withQuery(pathname, query) : pathname
    > 162 |   return fetch(getFullUrl(appPort, url), opts)
          |               ^
      163 | }
      164 |
      165 | export function renderViaHTTP(

      at parseURL (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1164:12)
      at new Request (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1210:17)
      at ../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1439:19
      at fetch (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1437:9)
      at fetchViaHTTP (lib/next-test-utils.ts:162:15)
      at renderViaHTTP (lib/next-test-utils.ts:171:10)
      at NextStartInstance.render$ (lib/next-modes/base.ts:512:37)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by huozhi — APPROVED** [review]
