### PR TITLE
fix(turbopack): Enable `explicit_resource_management` transform

### LINKED ISSUE #73739: Can't compile "using" keyword in Turbopack Dev
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/inspiring-liskov-r72y29

### To Reproduce

Write some code with the `using` keyword ([ECMAScript Explicit Resource Management](https://tc39.es/proposal-explicit-resource-management/)), run dev server with `--turbo` option

e.g.

```tsx
class Disposer {
  [Symbol.dispose]() {
    console.log("Disposed")
  }
}

export default function Page({ children }) {
  useEffect(() => {
    using disposer = new Disposer()
  }, [])
  
  return null
}
```

### Current vs. Expected behavior

> > @ dev /project/workspace
> > next dev --turbo
> 
>    ▲ Next.js 15.0.4-canary.49 (Turbopack)
>    - Local:        http://localhost:3000
>    - Network:      http://192.168.241.2:3000
> 
>  ✓ Starting...
>  ✓ Ready in 1205ms
>  ○ Compiling / ...
>  ✓ Compiled / in 2.7s
> [Error: Failed to load chunk server/chunks/ssr/[root of the server]__64ec1c._.js from parent module [project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { METADATA_0 => "[project]/app/favicon.ico.mjs { IMAGE => \"[project]/app/favicon.ico [app-rsc] (static)\" } [app-rsc] (structured image object, ecmascript, Next.js server component)", MODULE_1 => "[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)", MODULE_2 => "[project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_3 => "[project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/client/components/forbidden-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_4 => "[project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/client/components/unauthorized-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_5 => "[project]/app/page.tsx [app-rsc] (ecmascript, Next.js server component)" } [app-rsc] (ecmascript) <locals>] {
>   [cause]: SyntaxError: Unexpected identifier 'disposer'
>       at eval (<anonymous>)
> }
>  ⨯ unhandledRejection: [Error: Failed to load chunk server/chunks/ssr/[root of the server]__64ec1c._.js from parent module [project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { METADATA_0 => "[project]/app/favicon.ico.mjs { IMAGE => \"[project]/app/favicon.ico [app-rsc] (static)\" } [app-rsc] (structured image object, ecmascript, Next.js server component)", MODULE_1 => "[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)", MODULE_2 => "[project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_3 => "[project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/client/components/forbidden-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_4 => "[project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/client/components/unauthorized-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_5 => "[project]/app/page.tsx [app-rsc] (ecmascript, Next.js server component)" } [app-rsc] (ecmascript) <locals>] {
>   [cause]: SyntaxError: Unexpected identifier 'disposer'
>       at eval (<anonymous>)
> }
>  ⨯ unhandledRejection:  [Error: Failed to load chunk server/chunks/ssr/[root of the server]__64ec1c._.js from parent module [project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { METADATA_0 => "[project]/app/favicon.ico.mjs { IMAGE => \"[project]/app/favicon.ico [app-rsc] (static)\" } [app-rsc] (structured image object, ecmascript, Next.js server component)", MODULE_1 => "[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)", MODULE_2 => "[project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_3 => "[project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/client/components/forbidden-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_4 => "[project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/client/components/unauthorized-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_5 => "[project]/app/page.tsx [app-rsc] (ecmascript, Next.js server component)" } [app-rsc] (ecmascript) <locals>] {
>   [cause]: SyntaxError: Unexpected identifier 'disposer'
>       at eval (<anonymous>)
> }
>  ⨯ [Error: Failed to load chunk server/chunks/ssr/[root of the server]__64ec1c._.js from parent module [project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { METADATA_0 => "[project]/app/favicon.ico.mjs { IMAGE => \"[project]/app/favicon.ico [app-rsc] (static)\" } [app-rsc] (structured image object, ecmascript, Next.js server component)", MODULE_1 => "[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)", MODULE_2 => "[project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_3 => "[project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/client/components/forbidden-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_4 => "[project]/node_modules/.pnpm/next@15.0.4-canary.49_react-dom@19.0.0_react@19.0.0/node_modules/next/dist/client/components/unauthorized-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_5 => "[project]/app/page.tsx [app-rsc] (ecmascript, Next.js server component)" } [app-rsc] (ecmascript) <locals>] {
>   digest: '2118425113',
>   [cause]: SyntaxError: Unexpected identifier 'disposer'
>       at eval (<anonymous>)
> }
>  GET / 500 in 3134ms

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 15.0.4-canary.49 // Latest available version is detected (15.0.4-canary.49).
  eslint-config-next: N/A
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience, Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

`next dev --turbo` does not even transplie the syntax even with [`explicit_resource_management: true` enabled in swc](https://github.com/vercel/next.js/blob/b6b5ab88acdce8fbea623402d3fe97b5d5333d20/turbopack/crates/turbopack-ecmascript/src/parse.rs#L300)

CleanShot 2024-11-19 at 22 07 39@2x

### PR DESCRIPTION
**Pull request by kdy1**
### What?

Enable ERM transform unconditionally, to avoid creating non-standard code.

### Why?

It's nearly standard (stage 3) and supported by TypeScript with default config. But as it's stage 3, runtimes cannot support it  right now. So we workaround it using SWC transform.

### How?

 - Closes PACK-3637
 - Closes https://github.com/vercel/next.js/issues/73739

### CODE REVIEW

File: turbopack/crates/turbopack-ecmascript/src/parse.rs [hunk 1]
```diff
@@ -385,6 +385,8 @@ async fn parse_file_content(
             parsed_program.mutate(swc_core::ecma::lints::rules::lint_to_fold(rules));
             drop(span);
 
+            parsed_program.mutate(swc_core::ecma::transforms::proposal::explicit_resource_management::explicit_resource_management());
```
Comment (kdy1) [inline turbopack/crates/turbopack-ecmascript/src/parse.rs:388]: I'll add a next.js test for this

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 4b11aef964e9e52172b36cd0ea4d6a6df376a88b

`pnpm test-dev test/e2e/app-dir/ecmascript-features/ecmascript-features.test.ts`
- ecmascript-features > should work with fetch

<details>
<summary>Expand output</summary>

  ● ecmascript-features › should work with fetch

    expect(received).toContain(expected) // indexOf

    Expected substring: "hello world"
    Received string:    "<!DOCTYPE html><html><head><meta charSet=\"utf-8\" data-next-head=\"\"/><meta name=\"viewport\" content=\"width=device-width\" data-next-head=\"\"/><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><noscript data-n-css=\"\"></noscript><script defer=\"\" noModule=\"\" src=\"/_next/static/chunks/polyfills.js\"></script><script src=\"/_next/static/chunks/fallback/webpack.js\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/main.js\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_app.js\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_error.js\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"></div><script src=\"/_next/static/chunks/fallback/react-refresh.js\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"ModuleBuildError\",\"source\":\"server\",\"message\":\"Module build failed (from ./node_modules/.pnpm/next@file+..+next-repo-45812e78dc562e4ce15a10d7a7111f92619bb71fa089e3def518b8891f445b90+packa_uyp2hlyhozf5i75bufnbg36qle/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js):\\nError:   x You're importing a component that needs `useEffect`. This React hook only works in a client component. To fix, mark the file (or its parent) with the `\\\"use client\\\"` directive.\\n  | \\n  |  Learn more: https://nextjs.org/docs/app/api-reference/directives/use-client\\n  | \\n  | \\n   ,-[1:1]\\n 1 | import { useEffect } from 'react'\\n   :          ^^^^^^^^^\\n 2 | \\n 3 | class Disposer {\\n 4 |   [Symbol.dispose]() {\\n   `----\\n\",\"stack\":\"ModuleBuildError: Module build failed (from ./node_modules/.pnpm/next@file+..+next-repo-45812e78dc562e4ce15a10d7a7111f92619bb71fa089e3def518b8891f445b90+packa_uyp2hlyhozf5i75bufnbg36qle/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js):\\nError:   \\u001b[31mx\\u001b[0m You're importing a component that needs `useEffect`. This React hook only works in a client component. To fix, mark the file (or its parent) with the `\\\"use client\\\"` directive.\\n  \\u001b[31m|\\u001b[0m \\n  \\u001b[31m|\\u001b[0m  Learn more: https://nextjs.org/docs/app/api-reference/directives/use-client\\n  \\u001b[31m|\\u001b[0m \\n  \\u001b[31m|\\u001b[0m \\n   ,-[1:1]\\n \\u001b[2m1\\u001b[0m | import { useEffect } from 'react'\\n   : \\u001b[35;1m         ^^^^^^^^^\\u001b[0m\\n \\u001b[2m2\\u001b[0m | \\n \\u001b[2m3\\u001b[0m | class Disposer {\\n \\u001b[2m4\\u001b[0m |   [Symbol.dispose]() {\\n   `----\\n\\n    at processResult (/tmp/next-install-a9c6915716421cedab4786c4adc7dcefebfd26cb4affba59939e6a1489546e32/node_modules/.pnpm/next@file+..+next-repo-45812e78dc562e4ce15a10d7a7111f92619bb71fa089e3def518b8891f445b90+packa_uyp2hlyhozf5i75bufnbg36qle/node_modules/next/dist/compiled/webpack/bundle5.js:28:405677)\\n    at /tmp/next-install-a9c6915716421cedab4786c4adc7dcefebfd26cb4affba59939e6a1489546e32/node_modules/.pnpm/next@file+..+next-repo-45812e78dc562e4ce15a10d7a7111f92619bb71fa089e3def518b8891f445b90+packa_uyp2hlyhozf5i75bufnbg36qle/node_modules/next/dist/compiled/webpack/bundle5.js:28:407465\\n    at /tmp/next-install-a9c6915716421cedab4786c4adc7dcefebfd26cb4affba59939e6a1489546e32/node_modules/.pnpm/next@file+..+next-repo-45812e78dc562e4ce15a10d7a7111f92619bb71fa089e3def518b8891f445b90+packa_uyp2hlyhozf5i75bufnbg36qle/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:8645\\n    at /tmp/next-install-a9c6915716421cedab4786c4adc7dcefebfd26cb4affba59939e6a1489546e32/node_modules/.pnpm/next@file+..+next-repo-45812e78dc562e4ce15a10d7a7111f92619bb71fa089e3def518b8891f445b90+packa_uyp2hlyhozf5i75bufnbg36qle/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5019\\n    at r.callback (/tmp/next-install-a9c6915716421cedab4786c4adc7dcefebfd26cb4affba59939e6a1489546e32/node_modules/.pnpm/next@file+..+next-repo-45812e78dc562e4ce15a10d7a7111f92619bb71fa089e3def518b8891f445b90+packa_uyp2hlyhozf5i75bufnbg36qle/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4039)\"},\"gip\":true,\"scriptLoader\":[]}</script></body></html>"

      10 |     const res = await next.fetch('/')
      11 |     const html = await res.text()
    > 12 |     expect(html).toContain('hello world')
         |                  ^
      13 |   })
      14 | })
      15 |

      at Object.toContain (e2e/app-dir/ecmascript-features/ecmascript-features.test.ts:12:18)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by mischnic — APPROVED** [review]
