### PR TITLE
Fix conflict between defaultPathMap and default 404.html export

### LINKED ISSUE #8364: Error static HTML export for pages/404.js
# Bug report

## Describe the bug

When you have a page `pages/404.js`, static HTML export will not export the page you write, instead of the default 404 page by next.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```bash
# create a blank project
npx create-next-app next-export-404
cd next-export-404
# crate a page that cause bug
echo "export default () => { return '404' }" > pages/404.js
# do static export
npx next build && npx next export
# check output
cat out/404.html
```

The content of `out/404.html` is not the page we've created, it's the default 404 page by next.js

## Expected behavior

The content of `out/404.html` is '404'.

## Screenshots

Screen Shot 2019-08-14 at 12 59 02 PM

## System information

- Version of Next.js: 9.0.3

### PR DESCRIPTION
**Pull request by undirectlookable**
Fix conflict between defaultPathMap and default 404.html export，if have a page named pages/404.js.

Fixes: #8364 
Related PR GH-6912

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| buildDuration | 23.1s | 22.9s | -296ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -20 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 286 B | 287 B | ⚠️ +1 B |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ⚠️ +1 B |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 849 B | 845 B | -4 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 844 B | 841 B | -3 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 833 B | 830 B | -3 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| buildDuration | 23.8s | 24.3s | ⚠️ +440ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -20 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.2 kB | 66.2 kB | ✓ |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | ✓ |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.7 kB | 68.7 kB | -1 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | ✓ |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | -1 B |
| Overall change |  |  | ✓ |

</details>

</details>

**Comment by huv1k** [comment]
Hey @undirectlookable, could you write a test for it?

**Comment by undirectlookable** [comment]
> Hey @undirectlookable, could you write a test for it?

I can't figure out how to test with/without a `404.js` file in `test/integration/export/pages/`

Most project does not have such a situation, so I can't simply add a `404.js` in test folder.

File: packages/next/export/index.js [hunk 1]
```diff
@@ -140,7 +140,7 @@ export default async function (dir, options, configuration) {
     distDir,
     buildId
   })
-  exportPathMap['/404.html'] = exportPathMap['/404.html'] || { page: '/_error' }
+  exportPathMap['/404'] = exportPathMap['/404'] || { page: '/_error' }
```
Comment (ijjk) [inline packages/next/export/index.js]:
```suggestion
  if (!exportPathMap['/404']) {
    exportPathMap['/404.html'] = exportPathMap['/404.html'] || { page: '/_error' }
  }
```

It looks like the `export` test suite is failing, we can just check if there is already a `/404` page and not add the `/404.html` when there is

**Comment by ijjk** [comment]
Hi, thanks for the PR! To add a test for this you can add a `404` page to `test/integration/production/pages/404.js` and then check to make sure that it returns the correct contents

**Comment by undirectlookable** [comment]
Test suits will stuck if connect internet via proxy. I'll fix that and add test for my PR.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| buildDuration | 24.9s | 24.8s | -37ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -20 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | ✓ |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.2 kB | 16.2 kB | ✓ |
| main-HASH.module.js gzip | 6.28 kB | 6.28 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | ✓ |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 600 B | 600 B | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 290 B | 290 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| link | 2.8 kB | 2.8 kB | ✓ |
| link gzip | 851 B | 849 B | -2 B |
| index | 2.75 kB | 2.75 kB | ✓ |
| index gzip | 842 B | 841 B | -1 B |
| withRouter | 2.81 kB | 2.81 kB | ✓ |
| withRouter gzip | 839 B | 836 B | -3 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| buildDuration | 26.8s | 26.3s | -510ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -20 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | ✓ |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.2 kB | 16.2 kB | ✓ |
| main-HASH.module.js gzip | 6.28 kB | 6.28 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | ✓ |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 600 B | 600 B | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 290 B | 290 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.3 kB | 66.3 kB | -2 B |
| hooks.html | 2.87 kB | 2.87 kB | ✓ |
| hooks.html gzip | 865 B | 864 B | -1 B |
| index.js | 248 kB | 248 kB | ✓ |
| index.js gzip | 66.6 kB | 66.6 kB | -1 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.8 kB | 68.8 kB | -1 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.5 kB | 66.5 kB | -2 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.6 kB | 66.6 kB | -1 B |
| Overall change |  |  | ✓ |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| buildDuration | 24.4s | 25.5s | ⚠️ +1.1s |
| nodeModulesSize | 41.3 MB | 41.3 MB | ⚠️ +66 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | ✓ |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.2 kB | 16.2 kB | ✓ |
| main-HASH.module.js gzip | 6.28 kB | 6.28 kB | ⚠️ +1 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | ✓ |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 601 B | 600 B | -1 B |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ⚠️ +1 B |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 289 B | 290 B | ⚠️ +1 B |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| link | 2.8 kB | 2.8 kB | ✓ |
| link gzip | 851 B | 849 B | -2 B |
| index | 2.75 kB | 2.75 kB | ✓ |
| index gzip | 844 B | 841 B | -3 B |
| withRouter | 2.81 kB | 2.81 kB | ✓ |
| withRouter gzip | 839 B | 836 B | -3 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| buildDuration | 25.9s | 26.4s | ⚠️ +548ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | ⚠️ +66 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | ✓ |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.2 kB | 16.2 kB | ✓ |
| main-HASH.module.js gzip | 6.28 kB | 6.28 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | ✓ |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 600 B | 600 B | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 290 B | 290 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.3 kB | 66.3 kB | -1 B |
| hooks.html | 2.87 kB | 2.87 kB | ✓ |
| hooks.html gzip | 866 B | 865 B | -1 B |
| index.js | 248 kB | 248 kB | ✓ |
| index.js gzip | 66.6 kB | 66.6 kB | -1 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.8 kB | 68.8 kB | -1 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.5 kB | 66.5 kB | -1 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.6 kB | 66.6 kB | -1 B |
| Overall change |  |  | ✓ |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| buildDuration | 22.7s | 22.5s | -148ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | ⚠️ +66 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | ✓ |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.2 kB | 16.2 kB | ✓ |
| main-HASH.module.js gzip | 6.28 kB | 6.28 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | ✓ |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 600 B | 600 B | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 290 B | 290 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| link | 2.8 kB | 2.8 kB | ✓ |
| link gzip | 850 B | 847 B | -3 B |
| index | 2.75 kB | 2.75 kB | ✓ |
| index gzip | 842 B | 839 B | -3 B |
| withRouter | 2.81 kB | 2.81 kB | ✓ |
| withRouter gzip | 838 B | 835 B | -3 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| buildDuration | 23.9s | 23.3s | -557ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | ⚠️ +66 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | ✓ |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.2 kB | 16.2 kB | ✓ |
| main-HASH.module.js gzip | 6.28 kB | 6.28 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | ✓ |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 600 B | 600 B | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 290 B | 290 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.3 kB | 66.3 kB | ✓ |
| hooks.html | 2.87 kB | 2.87 kB | ✓ |
| hooks.html gzip | 866 B | 864 B | -2 B |
| index.js | 248 kB | 248 kB | ✓ |
| index.js gzip | 66.6 kB | 66.6 kB | ✓ |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.8 kB | 68.8 kB | ✓ |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.5 kB | 66.5 kB | ✓ |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.6 kB | 66.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| buildDuration | 24.9s | 24s | -936ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | ⚠️ +66 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | ✓ |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.2 kB | 16.2 kB | ✓ |
| main-HASH.module.js gzip | 6.28 kB | 6.28 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | ✓ |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 600 B | 600 B | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 290 B | 290 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| link | 2.8 kB | 2.8 kB | ✓ |
| link gzip | 849 B | 850 B | ⚠️ +1 B |
| index | 2.75 kB | 2.75 kB | ✓ |
| index gzip | 840 B | 843 B | ⚠️ +3 B |
| withRouter | 2.81 kB | 2.81 kB | ✓ |
| withRouter gzip | 836 B | 839 B | ⚠️ +3 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| buildDuration | 25.4s | 25.5s | ⚠️ +111ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | ⚠️ +66 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | ✓ |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.2 kB | 16.2 kB | ✓ |
| main-HASH.module.js gzip | 6.28 kB | 6.28 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | ✓ |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 600 B | 600 B | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 290 B | 290 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | undirectlookable/next.js export-404-fix | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.3 kB | 66.3 kB | -2 B |
| hooks.html | 2.87 kB | 2.87 kB | ✓ |
| hooks.html gzip | 865 B | 864 B | -1 B |
| index.js | 248 kB | 248 kB | ✓ |
| index.js gzip | 66.6 kB | 66.6 kB | -1 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.8 kB | 68.8 kB | -2 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.5 kB | 66.5 kB | -1 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.6 kB | 66.6 kB | -1 B |
| Overall change |  |  | ✓ |

</details>

</details>

**Review by ijjk — APPROVED** [review]
Looks good, thanks again for the PR!

**Comment by Timer** [comment]
This change has been released as `next@9.0.4`. You may upgrade your application(s)!
