### PR TITLE
Fixes `beforeInteractive` scripts failing in custom document

### LINKED ISSUE #31275: Unable to use `dangerouslySetInnerHTML` and `beforeInteractive` strategy in Script component
### What version of Next.js are you using?

14.17.1

### What version of Node.js are you using?

12.0.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

npm run dev

### Describe the Bug

Setting `dangerouslySetInnerHtml` in next Script component while also specifying `beforeInteractive` strategy will result in the Script component doing nothing. Since there is no `src` specified, the src will simply be `(unknown)`.
script

```
<Script
  id="test"
  strategy="beforeInteractive"
  dangerouslySetInnerHTML={{
    // will not run
    __html: `console.log('hello!')`,
  }}
/>
```

### Expected Behavior

Script component can be used with no `src` while using `dangerouslySetInnerHtml` property. 

### To Reproduce

Try to render Script component using `beforeInteractive` while having no `url` and specifying `dangerouslySetInnerHtml` property.

```
<Script
  id="test"
  strategy="beforeInteractive"
  dangerouslySetInnerHTML={{
    // will not run
    __html: `console.log('hello!')`,
  }}
/>
```
This piece of code of next Script will result in the following script tag being added
script

### LINKED ISSUE #36997: next/script `beforeInteractive` not working in `_document.js`
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    Binaries:
      Node: 14.17.6
      npm: 7.24.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.7
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

Script fails to load when using `<Script src="beforeInteractive"/>` in `_document.js` as specified in the documentation. 

Complete `_document.js` file as written:

```jsx
import { Html, Head, Main, NextScript } from "next/document";
import Script from "next/script";

export default function Document() {
  return (
    <Html>
      <Head>
        <Script
          src="https://unpkg.com/css-paint-polyfill@3.4.0/dist/css-paint-polyfill.js"
          strategy="beforeInteractive"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
```

There are also no console or browsers warning. Things fail silently.

### Expected Behavior

Script loads.

### To Reproduce

Import `next/script` in `_document.js` and load any third-party, or inline, script. Run the application and take a look at your network requests or DOM and you'll notice that no script tag has been inserted.

### PR DESCRIPTION
**Pull request by housseindjirdeh**
- Fixes #36997
- Fixes #31275

@janicklas-ralph Any idea why tests were passing while this check was failing? Can we add a stronger test for this?

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| buildDuration | 17.4s | 18s | ⚠️ +597ms |
| buildDurationCached | 7.2s | 6.9s | -288ms |
| nodeModulesSize | 478 MB | 478 MB | -7 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 5.141 | 4.873 | -0.27 |
| / avg req/sec | 486.26 | 513.02 | +26.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.992 | 1.854 | -0.14 |
| /error-in-render avg req/sec | 1254.85 | 1348.48 | +93.63 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.7 kB | 28.7 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.4 kB | 72.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 308 B | 308 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.7 kB | 2.7 kB | ✓ |
| head-HASH.js gzip | 359 B | 359 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.71 kB | 5.71 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.65 kB | 2.65 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 391 B | 391 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| buildDuration | 20.4s | 23.2s | ⚠️ +2.8s |
| buildDurationCached | 7.8s | 7.3s | -535ms |
| nodeModulesSize | 478 MB | 478 MB | -7 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.968 | 5.47 | ⚠️ +0.5 |
| / avg req/sec | 503.25 | 457.03 | ⚠️ -46.22 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.816 | 2.015 | ⚠️ +0.2 |
| /error-in-render avg req/sec | 1376.53 | 1240.85 | ⚠️ -135.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.7 kB | 42.7 kB | ✓ |
| main-HASH.js gzip | 29.2 kB | 29.2 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 73.5 kB | 73.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 311 B | 311 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.89 kB | 2.89 kB | ✓ |
| head-HASH.js gzip | 357 B | 357 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.8 kB | 5.8 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.77 kB | 2.77 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.3 kB | 16.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 457 B | 457 B | ✓ |
| Overall change | 457 B | 457 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/#36997 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 9813e11d5475c306fb0f2eb9513bd9ae264b75d6

**Review by janicklas-ralph — DISMISSED** [review]

**Comment by janicklas-ralph** [comment]
This was passing. Our tests would have failed otherwise, since none of the Script tags would have rendered

File: packages/next/pages/_document.tsx [hunk 1]
```diff
@@ -605,7 +605,7 @@ export class Head extends Component<
     const filteredChildren: ReactNode[] = []
 
     React.Children.forEach(children, (child: any) => {
-      if (child.type === Script) {
+      if (typeof child.type === 'function' && child.type.name === 'Script') {
```
Comment (ijjk) [inline packages/next/pages/_document.tsx:608]: I think the previous check of `child.type === Script` was correct as that ensures it is the `next/script` component and not a custom component named `Script` 

The issue seemed to be from the import for `next/script` in `_document` being local `../client/script` and the other being non-local causing different instances to be loaded. The tests passed because the monorepo version of Next.js is being used and webpack treated both instances the same.

We should be able to add a regression test for this by adding it to an isolated test (`test/e2e` or `test/production`)

We can also fix the different instances being loaded by updating this line:
https://github.com/vercel/next.js/blob/4a86a8ffb1ed9db223c05509844b39a2d8661cfc/packages/next/build/webpack-config.ts#L819

to: `/^(?:private-next-pages\/|next\/(?:dist\/pages\/|(?:app|document|link|image|constants|dynamic|script)$)|string-hash$)/`

Comment (housseindjirdeh) [reply packages/next/pages/_document.tsx]: Thanks so much clarifying, I wasn't aware that different instances of the same import could have been the issue. 

Just fixed it and added a regression test 👍

**Review by ijjk — APPROVED** [review]
Thanks!
