### PR TITLE
Fix Show error when user put wrong values in width or height

### LINKED ISSUE #26135: Wrong message that Image with src "/test.jpg" is smaller than 40x40. Consider removing the "placeholder='blur'" property to improve performance.
### What version of Next.js are you using?

11

### What version of Node.js are you using?

15.12.0

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### How are you deploying your application?

yarn dev

### Describe the Bug

Terminal says `Image with src "/test.jpg" is smaller than 40x40. Consider removing the "placeholder='blur'" property to improve performance.`

but `test.jpg` is 14669 × 5000. file is below.
https://commons.wikimedia.org/w/index.php?title=Category:Large_images#/media/File:'Matijevic_Hill'_Panorama_for_Rover's_Ninth_Anniversary_(Stereo).jpg

### Expected Behavior

No message with that.

### To Reproduce

put that image in public folder and use below code.
```
<Image
  src='/test.jpg'
  width='fill'
  height='fill'
  layout='responsive'
  placeholder='blur'
  blurDataURL='/test.jpg'
/>
```

### PR DESCRIPTION
**Pull request by jthcast**
## Bug

- [x] Related issues linked using `fixes #26135 `
- [x] Integration tests added

fixes #26135

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #26135 `
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.

## Documentation / Examples

- [ ] Make sure the linting passes

### CODE REVIEW

**Review by timneutkens — CHANGES_REQUESTED** [review]
Can you add a integration test to `test/integration/image-component`

**Review by atcastle — DISMISSED** [review]
Thanks, this is an error case that was missing.  With an integration test, this looks good to me.

**Comment by jthcast** [comment]
a... am I doing right? I'm new to this test 😅

File: packages/next/client/image.tsx [hunk 1]
```diff
@@ -353,6 +353,9 @@ export default function Image({
         )}`
       )
     }
+    if (Number.isNaN(widthInt) || Number.isNaN(heightInt)){
```
Comment (timneutkens) [inline packages/next/client/image.tsx:356]: `width` and `height` are not required when `layout="fill'` right? That seems like it would throw here

Comment (jthcast) [reply packages/next/client/image.tsx:356]: You are right. it only can handling with `layout='responsive'`
should change 
```
if (layout === 'responsive' && (Number.isNaN(widthInt) || Number.isNaN(heightInt))) {
  throw new Error(`Image with src "${src}" has invalid "width" or "height" property. These should be numeric values.`);
}
```

when `layout='fill'` it doesn't need width and height. so don't know that value.
so, there is another process like below.

```
if (layout !== 'fill' && ((widthInt || 0) * (heightInt || 0) < 1600)) {
  console.warn(`Image with src "${src}" is smaller than 40x40. Consider removing the "placeholder='blur'" property to improve performance.`);
}
```

But, I don't like that, because that is not abstract enough I think.
I tried getting real width from image, but failed. 😂

File: test/integration/image-component/default/pages/invalid-weight-or-height.js [hunk 2]
```diff
@@ -0,0 +1,19 @@
+import React from 'react'
+import Image from 'next/image'
+
+export default function Page() {
+  return (
+    <div>
+      <p>Invalid weight or height</p>
```
Comment (styfle) [inline test/integration/image-component/default/pages/invalid-weight-or-height.js:7]:
```suggestion
      <p>Invalid width or height</p>
```

File: test/integration/image-component/default/pages/invalid-weight-or-height.js [hunk 3]
```diff
@@ -0,0 +1,19 @@
+import React from 'react'
```
Comment (styfle) [inline test/integration/image-component/default/pages/invalid-weight-or-height.js:1]: Also the file name has the same typo (should be `width`)

File: packages/next/client/image.tsx [hunk 4]
```diff
@@ -360,6 +360,14 @@ export default function Image({
         ).join(',')}.`
       )
     }
+    if (
+      layout !== 'fill' &&
+      (Number.isNaN(widthInt) || Number.isNaN(heightInt))
```
Comment (styfle) [inline packages/next/client/image.tsx:365]:
```suggestion
      (isNaN(widthInt) || isNaN(heightInt))
```

Seems like Number.isNaN() isn't supported in IE.

File: test/integration/image-component/default/test/index.test.js [hunk 5]
```diff
@@ -494,6 +494,15 @@ function runTests(mode) {
       )
     })
 
+    it('should show error when not numeric string width or height', async () => {
+      const browser = await webdriver(appPort, '/invalid-weight-or-height')
```
Comment (styfle) [inline test/integration/image-component/default/test/index.test.js:498]:
```suggestion
      const browser = await webdriver(appPort, '/invalid-width-or-height')
```

After renaming the file, update here too 👍

File: test/integration/image-component/default/pages/invalid-weight-or-height.js (hunk 3 above)
Comment (jthcast) [reply test/integration/image-component/default/pages/invalid-weight-or-height.js:1]: Yeah. there was many mistake on me 😅 Thank you! i will rename it.

Comment (styfle) [reply test/integration/image-component/default/pages/invalid-weight-or-height.js:1]: No worries, we are always happy to get PRs 👍

**Review by styfle — DISMISSED** [review]
Great work, thanks! 🎉

**Review by ijjk — DISMISSED** [review]

**Review by timneutkens — DISMISSED** [review]
Thanks @jthcast! Amazing first contribution!

**Comment by jthcast** [comment]
> Thanks @jthcast! Amazing first contribution!

Thanks everyone for your help! 😊

**Review by ijjk — DISMISSED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.9s | ⚠️ +272ms |
| buildDurationCached | 2.9s | 2.8s | -66ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.119 | 2.097 | -0.02 |
| / avg req/sec | 1179.96 | 1192.02 | +12.06 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.277 | 1.244 | -0.03 |
| /error-in-render avg req/sec | 1957.29 | 2009.64 | +52.35 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 13.9s | 13.6s | -284ms |
| buildDurationCached | 3.9s | 3.8s | -68ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | -2 B |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 10.1s | 10.3s | ⚠️ +182ms |
| buildDurationCached | 4.1s | 4.1s | -49ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.027 | 2.679 | ⚠️ +0.65 |
| / avg req/sec | 1233.29 | 933.3 | ⚠️ -299.99 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.222 | 1.202 | -0.02 |
| /error-in-render avg req/sec | 2045.36 | 2080.06 | +34.7 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 63.8 kB | 63.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.28 kB | 9.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 568 B | 568 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 561 B | 561 B | ✓ |
| Overall change | 1.71 kB | 1.71 kB | ✓ |

</details>

</details>
Commit: 9fe959f574743d8cee088c75759059aa060da80e

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 9fe959f574743d8cee088c75759059aa060da80e

**test/integration/image-component/typescript/test/index.test.js** 
- TypeScript Image Component > next dev > should print error when invalid Image usage

<details>
<summary>Expand output</summary>

  ● TypeScript Image Component › next dev › should print error when invalid Image usage

    expect(received).toMatch(expected)

    Expected pattern: /must use "width" and "height" properties or "layout='fill'" property/
    Received string:  "ready - started server on 0.0.0.0:45101, url: http://localhost:45101
    info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
    warn  - Minimum recommended TypeScript version is v4.3.2, older versions can potentially be incompatible with Next.js. Detected: 4.3.0-beta
    event - compiled successfully
    event - build page: /valid
    wait  - compiling...
    event - compiled successfully
    event - build page: /invalid
    wait  - compiling...
    event - compiled successfully
    event - build page: /next/dist/pages/_error
    wait  - compiling...
    event - compiled successfully
    Error: Image with src \"https://via.placeholder.com/500\" has invalid \"width\" or \"height\" property. These should be numeric values.

      345 |
      346 |     if (layout !== 'fill' && (isNaN(widthInt) || isNaN(heightInt))) {
    > 347 |       throw new Error(`Image with src "${src}" has invalid "width" or "height" property. These should be numeric values.`);
          |             ^
      348 |     }
      349 |
      350 |     if (!VALID_LOADING_VALUES.includes(loading)) {

      at Image (integration/image-component/typescript/.next/server/pages/invalid.js:347:13)
      at processChild (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
      at resolve (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
      at ReactDOMServerRenderer.render (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
      at ReactDOMServerRenderer.read (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
      at renderToString (../node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
      at Object.renderPage (../packages/next/dist/next-server/server/render.js:53:854)
      at Function.getInitialProps (integration/image-component/typescript/.next/server/pages/_document.js:625:19)
      at loadGetInitialProps (../packages/next/dist/next-server/lib/utils.js:5:101)
      at renderToHTML (../packages/next/dist/next-server/server/render.js:53:1145)
      "
      at Object.<anonymous> (integration/image-component/typescript/test/index.test.js:52:22)

</details>

File: packages/next/client/image.tsx (hunk 1 above)
Comment (atcastle) [reply packages/next/client/image.tsx]: Are we sure this would have thrown on an empty image with layout fill? I believe widthInt is undefined if nothing is provided, and Number.isNaN(undefined) is false

**Comment by jthcast** [comment]
**test/integration/image-component/default/test/index.test.js**
- The test code written first was wrong. so, i edited.

**test/integration/image-component/typescript/test/index.test.js**
- The test is duplicated with mine. what should i do?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 10.9s | 11.1s | ⚠️ +152ms |
| buildDurationCached | 2.7s | 2.7s | -35ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.009 | 2.015 | ⚠️ +0.01 |
| / avg req/sec | 1244.12 | 1240.58 | ⚠️ -3.54 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.113 | 1.107 | -0.01 |
| /error-in-render avg req/sec | 2247.18 | 2258.86 | +11.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.5s | ⚠️ +25ms |
| buildDurationCached | 3.6s | 3.6s | -16ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 9.7s | 9.8s | ⚠️ +53ms |
| buildDurationCached | 3.9s | 3.9s | -43ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.031 | 2.022 | -0.01 |
| / avg req/sec | 1230.78 | 1236.14 | +5.36 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.13 | 1.119 | -0.01 |
| /error-in-render avg req/sec | 2211.7 | 2233.44 | +21.74 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 63.8 kB | 63.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.28 kB | 9.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 568 B | 568 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 561 B | 561 B | ✓ |
| Overall change | 1.71 kB | 1.71 kB | ✓ |

</details>

</details>
Commit: 9c84023de83a76d4c033eedc848440d0ee4b766f

File: packages/next/client/image.tsx (hunk 1 above)
Comment (jthcast) [reply packages/next/client/image.tsx]: Yes, Number.isNaN(undefined) return false. but isNaN(undefined) return true.
It changed Number.isNaN to isNaN

Comment (jthcast) [reply packages/next/client/image.tsx]: No. as i said, this PR can't handle when `layout='fill`. when `layout='fill` it doesn't need width and height. and don't know it's real size.

And, as you said Number.isNaN(undefined) return false. but It changed  to isNaN.
isNaN(undefined) return true.

File: test/integration/image-component/default/pages/invalid-placeholder-blur-static.js [hunk 6]
```diff
@@ -9,6 +9,8 @@ const Page = () => {
         id="invalid-placeholder-blur-static"
         src={testBMP}
         placeholder="blur"
+        width={200}
+        height={200}
```
Comment (styfle) [inline test/integration/image-component/default/pages/invalid-placeholder-blur-static.js:13]: @jthcast This test should not be modified because you don't need width/height on a static import

File: test/integration/image-component/default/pages/invalid-placeholder-blur.js [hunk 7]
```diff
@@ -4,7 +4,13 @@ import Image from 'next/image'
 const Page = () => {
   return (
     <div>
-      <Image id="invalid-placeholder-blur" src="/test.png" placeholder="blur" />
+      <Image 
+        id="invalid-placeholder-blur"
+        src="/test.png"
+        placeholder="blur"
+        width={200}
+        height={200}
```
Comment (styfle) [inline test/integration/image-component/default/pages/invalid-placeholder-blur.js:12]: @jthcast Same here. This test should not be modified because you don't need width/height on a static import

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 13.1s | 13.3s | ⚠️ +172ms |
| buildDurationCached | 3.1s | 3.3s | ⚠️ +151ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.271 | 2.341 | ⚠️ +0.07 |
| / avg req/sec | 1100.79 | 1068.14 | ⚠️ -32.65 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.26 | 1.315 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1983.81 | 1901.81 | ⚠️ -82 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.5s | ⚠️ +64ms |
| buildDurationCached | 4.1s | 4.3s | ⚠️ +131ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | -2 B |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 11.3s | 11.7s | ⚠️ +315ms |
| buildDurationCached | 4.6s | 4.6s | ⚠️ +4ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.319 | 2.396 | ⚠️ +0.08 |
| / avg req/sec | 1077.83 | 1043.58 | ⚠️ -34.25 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.303 | 1.272 | -0.03 |
| /error-in-render avg req/sec | 1918.15 | 1965.8 | +47.65 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 63.8 kB | 63.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.28 kB | 9.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 567 B | 567 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 561 B | 561 B | ✓ |
| Overall change | 1.71 kB | 1.71 kB | ✓ |

</details>

</details>
Commit: 6ce4b62c1198518752bd535406d9c99eb3d252a4

File: test/integration/image-component/default/pages/invalid-placeholder-blur-static.js (hunk 6 above)
Comment (jthcast) [reply test/integration/image-component/default/pages/invalid-placeholder-blur-static.js]: You are right. fixed!

**Review by styfle — DISMISSED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.5s | -350ms |
| buildDurationCached | 3.1s | 3.1s | ⚠️ +25ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.314 | 2.312 | 0 |
| / avg req/sec | 1080.47 | 1081.5 | +1.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.31 | 1.265 | -0.05 |
| /error-in-render avg req/sec | 1907.89 | 1976.79 | +68.9 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 14.6s | 14.4s | -226ms |
| buildDurationCached | 4.1s | 4.6s | ⚠️ +480ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 11.2s | 11.3s | ⚠️ +27ms |
| buildDurationCached | 4.7s | 4.5s | -193ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.342 | 2.337 | 0 |
| / avg req/sec | 1067.49 | 1069.67 | +2.18 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.338 | 1.278 | -0.06 |
| /error-in-render avg req/sec | 1868 | 1956.61 | +88.61 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 63.8 kB | 63.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.28 kB | 9.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 567 B | 567 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 561 B | 561 B | ✓ |
| Overall change | 1.71 kB | 1.71 kB | ✓ |

</details>

</details>
Commit: 168597d198cf07b824ba0d719fa9659d5c52419a

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 168597d198cf07b824ba0d719fa9659d5c52419a

**test/integration/image-component/typescript/test/index.test.js** 
- TypeScript Image Component > next dev > should print error when invalid Image usage

<details>
<summary>Expand output</summary>

  ● TypeScript Image Component › next dev › should print error when invalid Image usage

    expect(received).toMatch(expected)

    Expected pattern: /must use "width" and "height" properties or "layout='fill'" property/
    Received string:  "ready - started server on 0.0.0.0:40719, url: http://localhost:40719
    info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
    warn  - Minimum recommended TypeScript version is v4.3.2, older versions can potentially be incompatible with Next.js. Detected: 4.3.0-beta
    event - compiled successfully
    event - build page: /valid
    wait  - compiling...
    event - compiled successfully
    event - build page: /invalid
    wait  - compiling...
    event - compiled successfully
    event - build page: /next/dist/pages/_error
    wait  - compiling...
    event - compiled successfully
    Error: Image with src \"https://via.placeholder.com/500\" has invalid \"width\" or \"height\" property. These should be numeric values.

      345 |
      346 |     if (layout !== 'fill' && (isNaN(widthInt) || isNaN(heightInt))) {
    > 347 |       throw new Error(`Image with src "${src}" has invalid "width" or "height" property. These should be numeric values.`);
          |             ^
      348 |     }
      349 |
      350 |     if (!VALID_LOADING_VALUES.includes(loading)) {

      at Image (integration/image-component/typescript/.next/server/pages/invalid.js:347:13)
      at processChild (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
      at resolve (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
      at ReactDOMServerRenderer.render (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
      at ReactDOMServerRenderer.read (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
      at renderToString (../node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
      at Object.renderPage (../packages/next/dist/next-server/server/render.js:53:854)
      at Function.getInitialProps (integration/image-component/typescript/.next/server/pages/_document.js:625:19)
      at loadGetInitialProps (../packages/next/dist/next-server/lib/utils.js:5:101)
      at renderToHTML (../packages/next/dist/next-server/server/render.js:53:1145)
      "
      at Object.<anonymous> (integration/image-component/typescript/test/index.test.js:52:22)

</details>

File: packages/next/client/image.tsx [hunk 8]
```diff
@@ -360,6 +360,11 @@ export default function Image({
         ).join(',')}.`
       )
     }
+    if (layout !== 'fill' && (isNaN(widthInt!) || isNaN(heightInt!))) {
+      throw new Error(
+        `Image with src "${src}" has invalid "width" or "height" property. These should be numeric values.`
+      )
+    }
```
Comment (styfle) [inline packages/next/client/image.tsx:367]:
```suggestion
    if (
      (typeof widthInt !== 'undefined' && isNaN(widthInt)) ||
      (typeof heightInt !== 'undefined' && isNaN(heightInt))
    ) {
      throw new Error(
        `Image with src "${src}" has invalid "width" or "height" property. These should be numeric values.`
      )
    }
```

**Review by styfle — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 11s | 11s | -5ms |
| buildDurationCached | 2.7s | 2.6s | -4ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +782 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.009 | 2.01 | 0 |
| / avg req/sec | 1244.32 | 1244.02 | ⚠️ -0.3 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.135 | 1.086 | -0.05 |
| /error-in-render avg req/sec | 2202.13 | 2302.32 | +100.19 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.4s | -141ms |
| buildDurationCached | 3.6s | 3.6s | ⚠️ +13ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +782 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | -2 B |
| Overall change | 105 kB | 105 kB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| buildDuration | 9.7s | 9.8s | ⚠️ +167ms |
| buildDurationCached | 3.9s | 3.9s | -55ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +782 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.021 | 2.022 | 0 |
| / avg req/sec | 1236.75 | 1236.18 | ⚠️ -0.57 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.126 | 1.157 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2220.72 | 2159.89 | ⚠️ -60.83 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 63.8 kB | 63.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.28 kB | 9.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jthcast/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 567 B | 567 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 561 B | 561 B | ✓ |
| Overall change | 1.71 kB | 1.71 kB | ✓ |

</details>

</details>
Commit: 10f70605103675a265a4c54c2c35ed9f9684fb90

File: packages/next/client/image.tsx (hunk 8 above)
Comment (jthcast) [reply packages/next/client/image.tsx]: You are really good! Thanks for your help!

**Review by ijjk — APPROVED** [review]
