### PR TITLE
Provide AppTree to getInitialProps for getDataFromTree

### LINKED ISSUE #6042: Router context breaking change in v8.0.0-canary.6
# Bug report

## Describe the bug

The `next/router` migration to `React.createContext` in https://github.com/zeit/next.js/pull/6030 (Next.js v8.0.0-canary.6) is a breaking change for the GraphQL SSR related examples such as [`with-graphql-react`](https://github.com/zeit/next.js/tree/canary/examples/with-graphql-react) and probably [`with-apollo`](https://github.com/zeit/next.js/tree/canary/examples/with-apollo).

## To Reproduce

In the [`with-graphql-react`](https://github.com/zeit/next.js/tree/canary/examples/with-graphql-react) example, update the `next` dependency to `8.0.0-canary.6` and replace the contents of `pages/index.js` with:

```jsx
import { Query } from 'graphql-react'
import { RouterContext } from 'next/router'

export default () => (
  <RouterContext.Consumer>
    {router => {
      console.log(router)
      return null
    }}
  </RouterContext.Consumer>
)
```

With `npm run dev`, in terminal you will see first `undefined` (bad) for the GraphQL preload render and then a router instance when the final SSR happens:

screen shot 2019-01-13 at 9 50 03 am

I imagine this reproduction would work for the [`with-apollo`](https://github.com/zeit/next.js/tree/canary/examples/with-apollo) examples too:

https://github.com/zeit/next.js/blob/v8.0.0-canary.6/examples/with-apollo/lib/with-apollo-client.js#L27

## Expected behavior

Perhaps the API would be non-breaking from Next.js v7 if `<RouterContext.Consumer>` was used inside of `<App>` instead of immediately outside.

## System information
 - Version of Next.js: v8.0.0-canary.6

## Additional context

Is this breaking change intentional? If so, I can work it in to [`next-graphql-react`](https://github.com/jaydenseric/next-graphql-react) and cut a new release for Next.js v8 compatibility.

The Apollo examples will also need updating.

### LINKED ISSUE #7731: with-apollo-auth: getDataFromTree returns an error during SSR with useRouter hook
# Error while running `getDataFromTree` TypeError: Cannot read property 'query' of null

## Describe the bug

I tried to use latest dynamic router functionality next to apollo client (just updated next version in `with-apollo-auth` example). When I use `useRouter` hook and trying to load page via visiting dynamic page directly from browser (not via client routing) I get an error `Error while running `getDataFromTree` TypeError: Cannot read property 'query' of null`. If I use `withRouter` hoc - everything is ok!

## To Reproduce

```ts
// Route like: /users/[user].tsx
import React from 'react';
import { useRouter } from 'next/router';

const UserInfo = (props) => {
  const router = useRouter();

  return <div>Hello {router.query.user}!</div>;
};

export default UserInfo;
```

## Screenshots
image

## System information

- OS: macOS
- Browser: Chrome
- Version of Next.js: [e.g. 8.1.1-canary.64]

### PR DESCRIPTION
**Pull request by ijjk**
This allows using `useRouter` when calling `getDataFromTree` by providing an `AppContainer` that provides the context in the render tree. 

Fixes: #7731 
Fixes #6042

### CODE REVIEW

File: packages/next/client/index.js [hunk 1]
```diff
@@ -257,6 +263,7 @@ async function doRender ({ App, Component, props, err }) {
   ) {
     const { pathname, query, asPath } = router
     props = await loadGetInitialProps(App, {
+      AppContainer,
```
Comment (Timer) [inline packages/next/client/index.js]: This would have to be the same as above, right? `AppTree` -- maybe you should pull this out to a `const` var.

File: packages/next-server/server/render.tsx [hunk 2]
```diff
@@ -344,7 +344,16 @@ export async function renderToHTML(
   )
 
   try {
-    props = await loadGetInitialProps(App, { Component, router, ctx })
+    props = await loadGetInitialProps(App, {
+      Component,
+      AppTree: (props: any) => (
+        <AppContainer>
+          <App {...props} />
```
Comment (Timer) [inline packages/next-server/server/render.tsx]: Why does the other reference need `<App Component={Component} router={router} {...props} />` but this one only need `props`? Seems like a bug.

File: packages/next-server/lib/utils.ts [hunk 3]
```diff
@@ -1,6 +1,6 @@
 import { format, UrlObject, URLFormatOptions } from 'url'
 import { ServerResponse, IncomingMessage } from 'http'
-import { ComponentType } from 'react'
+import { ComponentType, Component, FunctionComponent } from 'react'
```
Comment (Timer) [inline packages/next-server/lib/utils.ts]:
```suggestion
import { ComponentType } from 'react'
```

seem unneeded

**Review by Timer — DISMISSED** [review]

File: packages/next-server/lib/utils.ts (hunk 3 above)
Comment (ijjk) [reply packages/next-server/lib/utils.ts]: yup, auto import

File: packages/next-server/server/render.tsx (hunk 2 above)
Comment (ijjk) [reply packages/next-server/server/render.tsx]: updated

File: packages/next/client/index.js (hunk 1 above)
Comment (ijjk) [reply packages/next/client/index.js]: updated

File: examples/with-apollo-auth/lib/withApollo.js [hunk 4]
```diff
@@ -49,7 +50,7 @@ export default App => {
         try {
           // Run all GraphQL queries
           await getDataFromTree(
-            <App
+            <AppTree
               {...appProps}
               Component={Component}
               router={router}
```
Comment (timneutkens) [inline examples/with-apollo-auth/lib/withApollo.js]: This can be removed

File: examples/with-apollo-auth/lib/withApollo.js [hunk 5]
```diff
@@ -49,7 +50,7 @@ export default App => {
         try {
           // Run all GraphQL queries
           await getDataFromTree(
-            <App
+            <AppTree
               {...appProps}
               Component={Component}
```
Comment (timneutkens) [inline examples/with-apollo-auth/lib/withApollo.js]: This can be removed

File: packages/next-server/server/render.tsx [hunk 6]
```diff
@@ -344,7 +344,19 @@ export async function renderToHTML(
   )
 
   try {
-    props = await loadGetInitialProps(App, { Component, router, ctx })
+    props = await loadGetInitialProps(App, {
+      Component,
+      AppTree: (props: any) => {
+        const appProps = { Component, router, ...props }
```
Comment (timneutkens) [inline packages/next-server/server/render.tsx]: Reason you can remove them is that you're providing them here. Also it should be move the other way around:

```suggestion
        const appProps = { ...props, Component, router }
```

Otherwise users can override Component and router which is something we do not want.

Comment (ijjk) [reply packages/next-server/server/render.tsx]: Yup, missed a commit

**Comment by jesstelford** [comment]
@ijjk looks like there's a merge conflict with this PR against `canary`. Is there anything I can do to help here?

**Comment by ijjk** [comment]
@jesstelford Thanks for offering to help move this along! After @timneutkens gets a chance to review it should be good to go

**Review by timneutkens — CHANGES_REQUESTED** [review]
Bundle size increased quite a bit.

**Comment by ijjk** [comment]
Lowered the bundle size increase by making some of the `AppTree` related code opt-in through an experimental config. WDYT @timneutkens ?

**Comment by timneutkens** [comment]
I just don't think it should increase by the amount specified in your earlier commits even when enabled 🤔

**Comment by jaydenseric** [comment]
It would be unfortunate if this was behind a flag; it will introduce more complexity to setting up GraphQL implementations like [Apollo](https://github.com/zeit/next.js/tree/canary/examples/with-apollo) or [graphql-react](https://github.com/zeit/next.js/tree/canary/examples/with-graphql-react). The less config the better.

Also, I object to a fix being flagged as "experimental". IMO what is experimental are all the changes to context, hooks, etc. that shipped without addressing https://github.com/zeit/next.js/issues/6042.

Surely this fix can be achieved with negligible bundlesize impact, considering that an app already has bundled the ability to render its whole tree.

Exciting to see progress though.

**Comment by timneutkens** [comment]
> Surely this fix can be achieved with negligible bundlesize impact, considering that an app already has bundled the ability to render its whole tree.

An app being an app that uses Apollo, which is by far not all apps.

> Also, I object to a fix being flagged as "experimental". IMO what is experimental are all the changes to context, hooks, etc. that shipped without addressing #6042.

I want to reiterate that Apollo's implementation of tree rendering is the reason it does not work. Next.js works fine with everything else, hence not experimental. Furthermore this only affects this one specific feature (useRouter).

Also want to reiterate that what I'm saying is that this change does not have to increase bundle size at all so it shouldn't.

**Comment by jaydenseric** [comment]
> An app being an app that uses Apollo, which is by far not all apps.

This unfairly trivialises the many serious apps built with Next.js and GraphQL,  https://www.chromaticqa.com being one example.

> I want to reiterate that Apollo's implementation of tree rendering is the reason it does not work.

Apollo != GraphQL. I have put months of work into `graphql-react`, which is a completely different implementation to Apollo and it injures me every time someone refers to it as "Apollo".  I only bring up Apollo myself to draw attention to the fact that several other libraries are affected by the issues this PR attempts to address.

I'm not just some naive or impatient user, SSR like in the official examples used to work without caveats using legitimate, documented Next.js APIs and now it doesn't, and as a library author I need an elegant way to get it all working again.

> Furthermore this only affects this one specific feature (useRouter).

Anything using context with providers wrapping app is affected. I would like to be able to access `RequestContext` in components to make it easier to isomorphically retrieve the cookie in components:

https://github.com/zeit/next.js/blob/9609fe453d8ce3e67ab89733f52643fc85c16b72/packages/next-server/server/render.tsx#L328

Using `getInitialProps` to get the cookie and populate it in a context provider within a custom app leaves a lot to be desired (unnecessary serialization and hydration):

Screen Shot 2019-07-18 at 2 06 28 am

Screen Shot 2019-07-18 at 2 06 43 am

**Comment by timneutkens** [comment]
> This unfairly trivialises the many serious apps built with Next.js and GraphQL, chromaticqa.com being one example.

Note that I did not imply anything about the seriousness of apps built with Next.js or GraphQL. I was just noting it's not all users, so we shouldn't increase bundle size.

> I would like to be able to access RequestContext in components to make it easier to isomorphically retrieve the cookie in components

This is not stable and not documented so I would highly discourage using it, as we're very likely to remove this specific one. It's a good point though, we should have removed that one before the release. Potentially this clears up quite a bit of bundle size for that we can fit in this change.

Like I said it's only useRouter, there's an alternative, withRouter which everyone can still use. That uses the old context, hence it's backwards compatible.

Anyway there's an open PR as you can see so I'm not sure what the problem is. Again all I'm saying is it should not increase bundle size which is entirely possible.

**Comment by jesstelford** [comment]
@timneutkens To clarify, is it this line which you're concerned about?

Build Dir Size | 757 kB | 760 kB | ⚠️ +2.9 kB
-- | -- | -- | --

Are you able to provide some direction on what might cause such an increase? It looks like it's now including those Context providers into the bundle sent to the client (so that any custom `_app.js` has the same tree as what's provided on the server).

Perhaps removing the `RequestContext` provider is one step toward lowering the bundle increase, but wouldn't the client need all these context providers anyway? If the hooks are to be official APIs of next, then they will always need their `Provider`s, so the bundle size increase would be necessary, no?

I'm not sure if it's possible to dead-code eliminate any `Providers` which are never consumed?

**Comment by timneutkens** [comment]
I'm saying the code can be written in a way that doesn't increase bundle size, as we're literally passing an already existing thing to a function.

**Comment by jesstelford** [comment]
@timneutkens looks like @ijjk may have solved the bundle size increase 🎉

Is this ready for review now?

File: examples/with-apollo/lib/with-apollo-client.js [hunk 7]
```diff
@@ -20,14 +20,7 @@ export default App => {
...
           // Run all GraphQL queries
-          await getDataFromTree(
-            <App
-              {...appProps}
-              Component={Component}
-              router={router}
-              apolloClient={apollo}
-            />
-          )
+          await getDataFromTree(<AppTree apolloClient={apollo} {...appProps} />)
```
Comment (timneutkens) [inline examples/with-apollo/lib/with-apollo-client.js]: I think we should update the examples after it's on stable otherwise it'll break.

Comment (ijjk) [reply examples/with-apollo/lib/with-apollo-client.js]: 👌 removed for now

**Review by Timer — CHANGES_REQUESTED** [review]
One test per slack and I'll be 👍.

**Review by Timer — APPROVED** [review]
