### PR TITLE
[turbopack] Respect `{eval:true}` in worker_threads constructors

### LINKED ISSUE #91642: Build failing after 16.1.2 to 16.2 upgrade
### Link to the code that reproduces this issue

https://github.com/yukosgiti/next-js-16-2-0-bug

### To Reproduce

The reproduction has 2 commits. 
1st commit - pdfjs working normally in a server action.
2nd commit - ran npx next upgrade

- checkout the 1st commi
 - npm install
- npm run dev
- click on button at /
- pdf created.
- then run: npx next upgrade
- the dev server errors

### Current vs. Expected behavior

the website should work as it did before the upgrade

The build and the dev server gives the following error:

```ts
GET / 500 in 32ms (next.js: 19ms, application-code: 13ms)
[browser] Uncaught Error: ./node_modules/fflate/lib/node.cjs:22:13
Module not found: Can't resolve <dynamic>
  20 | node_worker_1["default"] = Worker ? function (c, _, msg, transfer, cb) {
  21 |     var done = false;
> 22 |     var w = new Worker(c + workerAdd, { eval: true })
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  23 |         .on('error', function (e) { return cb(e, null); })
  24 |         .on('message', function (m) { return cb(null, m); })
  25 |         .on('exit', function (c) {



Import trace:
  Server Component:
    ./node_modules/fflate/lib/node.cjs
    ./node_modules/jspdf/dist/jspdf.node.min.js
    ./app/create-pdf-action.ts
    ./app/page.tsx

https://nextjs.org/docs/messages/module-not-found


    at <unknown> (Error: ./node_modules/fflate/lib/node.cjs:22:13)
    at <unknown> (https://nextjs.org/docs/messages/module-not-found)
    at <unknown> (https://nextjs.org/docs/messages/module-not-found)
[browser] ./node_modules/fflate/lib/node.cjs:22:13
Module not found: Can't resolve <dynamic>
  20 | node_worker_1["default"] = Worker ? function (c, _, msg, transfer, cb) {
  21 |     var done = false;
> 22 |     var w = new Worker(c + workerAdd, { eval: true })
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  23 |         .on('error', function (e) { return cb(e, null); })
  24 |         .on('message', function (m) { return cb(null, m); })
  25 |         .on('exit', function (c) {

Import trace:
  Server Component:
    ./node_modules/fflate/lib/node.cjs
    ./node_modules/jspdf/dist/jspdf.node.min.js
    ./app/create-pdf-action.ts
    ./app/page.tsx

https://nextjs.org/docs/messages/module-not-found 
    at console.overrideMethod [as error] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/installHook.js:1:174822) (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/installHook.js:1:174822)
[browser] ./node_modules/fflate/lib/node.cjs:22:13
Module not found: Can't resolve <dynamic>
  20 | node_worker_1["default"] = Worker ? function (c, _, msg, transfer, cb) {
  21 |     var done = false;
> 22 |     var w = new Worker(c + workerAdd, { eval: true })
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  23 |         .on('error', function (e) { return cb(e, null); })
  24 |         .on('message', function (m) { return cb(null, m); })
  25 |         .on('exit', function (c) {

Import trace:
  Server Component:
    ./node_modules/fflate/lib/node.cjs
    ./node_modules/jspdf/dist/jspdf.node.min.js
    ./app/create-pdf-action.ts
    ./app/page.tsx

https://nextjs.org/docs/messages/module-not-found 
    at console.overrideMethod [as error] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/installHook.js:1:174822) (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/installHook.js:1:174822)
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 25.3.0: Wed Jan 28 20:56:42 PST 2026; root:xnu-12377.91.3~2/RELEASE_ARM64_T8142
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 22.21.1
  npm: 11.6.4
  Yarn: 1.22.22
  pnpm: 10.26.0
Relevant Packages:
  next: 16.2.0 // Latest available version is detected (16.2.0).
  eslint-config-next: N/A
  react: 19.2.4
  react-dom: 19.2.4
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

React, Server Actions

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

It might be an issue with react as well.

### PR DESCRIPTION
**Pull request by lukesandberg**
### What?

Fixed Turbopack incorrectly trying to resolve inline JavaScript code as module references when `new Worker()` is called with `{ eval: true }` option.

Now we skip creating a reference when `eval:true`, and report warnings if we cannot tell what the value is

### Why?

Libraries like jsPDF create Worker threads by passing inline JavaScript code as the first argument along with `{ eval: true }` as the second argument. Turbopack was incorrectly treating this inline code as a file path and attempting to resolve it as a module reference, causing build failures.

### How?

Added logic to detect when the `eval: true` option is passed to the Worker constructor. When this option is present, Turbopack now skips creating a worker reference since the first argument contains executable code rather than a file path. Added comprehensive test coverage using jsPDF to verify the fix works correctly.

Fixes #91642

### CODE REVIEW

**Comment by lukesandberg** [comment]
* **#91666** <a href="https://app.graphite.com/github/pr/vercel/next.js/91666?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/vercel/next.js/91666?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: turbopack/crates/turbopack-ecmascript/src/references/mod.rs [hunk 1]
```diff
@@ -2167,6 +2167,50 @@ where
...
+                                JsValue::Constant(JsConstantValue::False) => {}
+                                // eval is set but not a literal boolean — we
+                                // can't know if it's code or a path at compile
+                                // time
+                                _ => {
+                                    let (args, hints) = explain_args(args);
+                                    handler.span_warn_with_code(
+                                        span,
+                                        &format!(
+                                            "new Worker({args}) has a dynamic `eval` option{hints}",
```
Comment (mischnic) [inline turbopack/crates/turbopack-ecmascript/src/references/mod.rs]: and if the whole `args.get(1)` is dynamic? should that also warn and early return?

Comment (lukesandberg) [reply turbopack/crates/turbopack-ecmascript/src/references/mod.rs]: yup, done

**Review by mischnic — APPROVED** [review]

**Comment by lukesandberg** [comment]
### Merge activity

* **Mar 19, 8:58 PM UTC**: @lukesandberg merged this pull request with [Graphite](https://app.graphite.com/github/pr/vercel/next.js/91666).
