### PR TITLE
misc: remove vendored node-fetch usages

### LINKED ISSUE #75313: Deprecation warning of "punycode" module in freshly created next js app in Windows 11
### Link to the code that reproduces this issue

https://github.com/vickvey/next-imdb/

### To Reproduce

1. Create a fresh next app with `npm create-next-app@latest` in windows 11 from powershell terminal.
2. Run the developement server using `npm run dev`.
3. You will see the warning there about some punycode module is expired.

PS: I dont't know but I think its just dont feels right that, although I have just created a new fresh next app using "npx create-next-app@latest" and nothing else but yet I get this punycode deprecation warning, this means that the create-next-app@latest has some flaws which needs to fixed maybe there is need to update the dependecies.

### Current vs. Expected behavior

Image

See here the `punycode` deprecation warning in freshly created next app using `npm create-next-app@latest`.
Please resolve this issue, as I have OCD of using deprecated software.

### Provide environment information

```bash
Operating system:
Windows 11
Architecture:
x64
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Nothing, Please fix this. The biggest reason for me creating this issue is I mean i just used the latest version of next-js to create a fresh next app but still got a deprecation warning of some punycode module. Please resolve this.

### PR DESCRIPTION
**Pull request by feedthejim**
## What

This PR replaces the usage of node-fetch in the next/font/google loader code, which runs as part of every next build. `node-fetch` relies on `punycode`, which shows a deprecration warning from Node.js 22, affecting every users on Next.js and Node 22.

This PR also removes any other references to the vendored node-fetch used in other parts of the codebase.

~~Unfortunately, we can't remove it because other next.js dependencies like the amp optimiser actually use node-fetch, so they would need to be updated separately.~~

not a problem anymore because of @wowczarczyk suggestion of also rewriting the external in the dependencies to point to the correct one

This PR does not remove the node-fetch usage in tests.

## How

This replaces the node-fetch call with a call to the native fetch exposed in Node.js. However, this fetch does not support proxies without tapping into Undici, so I've had to "polyfill" a usage because I did not want to add a dependency to Undici for a minor use case.

Fixes #66289
Fixes #75313
Closes NDX-730

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 352961eaded029146d42ba12d24f5cfcbc293446

`__NEXT_EXPERIMENTAL_PPR=true pnpm test-dev test/e2e/next-font/with-proxy.test.ts` (PPR)
- next/font/google with proxy > should use a proxy agent when proxy environment variable is set

<details>
<summary>Expand output</summary>

  ● next/font/google with proxy › should use a proxy agent when proxy environment variable is set

    expect(received).toContain(expected) // indexOf

    Expected value: "/css2?family=Oswald:wght@200..700&display=swap"
    Received array: []

      50 |       )
      51 |       // eslint-disable-next-line jest/no-standalone-expect
    > 52 |       expect(proxiedRequests).toContain(
         |                               ^
      53 |         '/css2?family=Oswald:wght@200..700&display=swap'
      54 |       )
      55 |       // eslint-disable-next-line jest/no-standalone-expect

      at Object.toContain (e2e/next-font/with-proxy.test.ts:52:31)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by eps1lon — COMMENTED** [review]
Edit: Didn't see this was a draft. Graphite has too much grey 🙈 

To fix all the deprecation warnings, shouldn't we get rid of node-fetch entirely? There's still usage in `packages/next/src/trace/trace-uploader.ts`. After that we can stop vendoring it as well.

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/remove-node-fetch-from-google-loader | Change |
| - | - | - | - |
| buildDuration | 29s | 24.7s | N/A |
| buildDurationCached | 22.4s | 20s | N/A |
| nodeModulesSize | 392 MB | 392 MB | N/A |
| nextStartRea..uration (ms) | 707ms | 762ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/remove-node-fetch-from-google-loader | Change |
| - | - | - | - |
| 5306-HASH.js gzip | 54.2 kB | 54.2 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.46 kB | 5.46 kB | N/A |
| bccd1874-HASH.js gzip | 52.9 kB | 52.9 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 241 B | 242 B | N/A |
| main-HASH.js gzip | 34.5 kB | 34.5 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/remove-node-fetch-from-google-loader | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/remove-node-fetch-from-google-loader | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.59 kB | 4.58 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.35 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/remove-node-fetch-from-google-loader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 748 B | 747 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/remove-node-fetch-from-google-loader | Change |
| - | - | - | - |
| index.html gzip | 524 B | 523 B | N/A |
| link.html gzip | 539 B | 538 B | N/A |
| withRouter.html gzip | 520 B | 520 B | ✓ |
| Overall change | 520 B | 520 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/remove-node-fetch-from-google-loader | Change |
| - | - | - | - |
| edge-ssr.js gzip | 130 kB | 130 kB | N/A |
| page.js gzip | 211 kB | 210 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/remove-node-fetch-from-google-loader | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 675 B | 672 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.3 kB | 31.3 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/remove-node-fetch-from-google-loader | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 393 kB | 393 kB | ✓ |
| app-page-exp..prod.js gzip | 132 kB | 132 kB | ✓ |
| app-page-tur..prod.js gzip | 145 kB | 145 kB | ✓ |
| app-page-tur..prod.js gzip | 141 kB | 141 kB | ✓ |
| app-page.run...dev.js gzip | 381 kB | 381 kB | ✓ |
| app-page.run..prod.js gzip | 128 kB | 128 kB | ✓ |
| app-route-ex...dev.js gzip | 39.3 kB | 39.3 kB | ✓ |
| app-route-ex..prod.js gzip | 25.6 kB | 25.6 kB | ✓ |
| app-route-tu..prod.js gzip | 25.6 kB | 25.6 kB | ✓ |
| app-route-tu..prod.js gzip | 25.4 kB | 25.4 kB | ✓ |
| app-route.ru...dev.js gzip | 40.9 kB | 40.9 kB | ✓ |
| app-route.ru..prod.js gzip | 25.4 kB | 25.4 kB | ✓ |
| dist_client_...dev.js gzip | 356 B | 356 B | ✓ |
| dist_client_...dev.js gzip | 349 B | 349 B | ✓ |
| pages-api-tu..prod.js gzip | 9.69 kB | 9.69 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.8 kB | 11.8 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.68 kB | 9.68 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 31.5 kB | 31.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 60.5 kB | 60.5 kB | ✓ |
| Overall change | 1.67 MB | 1.67 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/remove-node-fetch-from-google-loader | Change |
| - | - | - | - |
| 0.pack gzip | 2.11 MB | 2.11 MB | ⚠️ +439 B |
| index.pack gzip | 74.4 kB | 75.1 kB | ⚠️ +654 B |
| Overall change | 2.18 MB | 2.18 MB | ⚠️ +1.09 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 6fa0960c8676b8b48e212adb89d029d090e5abaf

File: packages/next/taskfile.js [hunk 1]
```diff
@@ -77,6 +77,7 @@ const externals = {
   'terser-webpack-plugin':
     'next/dist/build/webpack/plugins/terser-webpack-plugin/src',
 
+  punycode: 'punycode/',
```
Comment (ztanner) [inline packages/next/taskfile.js:80]: how come this is the only one with a trailing slash?

File: packages/font/src/google/fetch-resource.ts [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+    const { protocol } = new URL(url)
+    const client = protocol === 'https:' ? https : http
+    const timeout = isDev ? 3000 : undefined
+
+    const req = client.request(
+      url,
+      {
+        agent: getProxyAgent(),
+        headers: {
+          'User-Agent':
```
Comment (ztanner) [inline packages/font/src/google/fetch-resource.ts:25]: maybe worth preserving the previous comment about why a user agent is specified here

**Review by ztanner — APPROVED** [review]

File: packages/next/taskfile.js (hunk 1 above)
Comment (wowczarczyk) [reply packages/next/taskfile.js:80]: trailing slash enforces the use of external [punycode](https://github.com/mathiasbynens/punycode.js) library, instead of the node-embedded one

**Review by ijjk — APPROVED** [review]

**Review by eps1lon — COMMENTED** [review]
Can we remove the vendored `node-fetch` entirely now?

**Comment by ijjk** [comment]
Yes, removing in https://github.com/vercel/next.js/pull/76241

**Comment by feedthejim** [comment]
nope node fetch is still being used by one of the other vendored deps so it's still valuable for us to vendor it and modify it, so that we can hide the log warning

**Comment by ijjk** [comment]
@feedthejim we don't need to vendor separately it gets bundled in with that single vendored dep
