### PR TITLE
Apply optimization to middleware when using babel

### LINKED ISSUE #50492: Using a `babel.config.js` file gives error when having a middleware containing `NextResponse.redirect()`
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/athoteldev/vercel-function-test/tree/middleware-issue

### To Reproduce

1. create a new Next.js project.
2. add a `babel.config.js` file:
```js
const plugins = []

module.exports = {
    presets: ['next/babel'],
    plugins,
}

```
3. add a middleware.ts in the root of the project:
```ts
import { NextRequest, NextResponse } from 'next/server'

export async function middleware(request: NextRequest) {
	if (false) { // just for demo purposes
		return NextResponse.redirect(new URL('/some-page', request.url))
	}
}

```
4. push the changes and the Vercel build and deploy.
5. notice the error message:
```


Error: The Edge Function "middleware" is referencing unsupported modules:
--
16:01:31.675 | - index.js: ./resvg.wasm?module, ./yoga.wasm?module
16:01:33.773 | NOW_SANDBOX_WORKER_EDGE_FUNCTION_UNSUPPORTED_MODULES: The Edge Function "middleware" is referencing unsupported modules:	- index.js: ./resvg.wasm?module, ./yoga.wasm?module


```

image

### Describe the Bug

I am getting an error when Vercel is trying to build the project.

To notice that removing any of these two files: `babel.config.js` or `middleware.ts`, will make the project build successfully. 

The project also build successfully if I remove the ".redirect()" from the `middleware.ts` file.

But I can't do that with my real project because I have specific configuration.

### Expected Behavior

To not get any errors in Vercel when it's building the project

### Which browser are you using? (if relevant)

-

### How are you deploying your application? (if relevant)

Vercel

### PR DESCRIPTION
**Pull request by huozhi**
Like how we handled RSC loader transform before, we also apply swc loader to middleware to make sure the imports optimization is applied so og package won't be bundled

Fixes #50492

### CODE REVIEW

**Review by ijjk — APPROVED** [review]

File: packages/next/src/build/webpack-config.ts [hunk 1]
```diff
@@ -899,7 +899,14 @@ export default async function getBaseWebpackConfig(
     : []
   const swcLoaderForMiddlewareLayer = useSWCLoader
     ? getSwcLoader({ hasServerComponents: false })
-    : getBabelLoader()
+    : // When using Babel, we will have to use SWC to do the optimization
+      // for middleware to tree shake the unused default optimized imports like "next/server".
+      // This will cause some performance overhead but
+      // acceptable as Babel will not be recommended.
+      [
+        getSwcLoader({ hasServerComponents: false, isServerLayer: false }),
```
Comment (shuding) [inline packages/next/src/build/webpack-config.ts:907]:
```suggestion
        getSwcLoader({ hasServerComponents: false }),
```

`isServerLayer: false` is not necessary here.
