### PR TITLE
Tree shake the unused exports in direct relative imported client component module

### LINKED ISSUE #60246: Tree-shaking/Code splitting doesn't with react-aria-components
### Discussed in https://github.com/vercel/next.js/discussions/60206

<div type='discussions-op-text'>

<sup>Originally posted by **IonelLupu** January  4, 2024</sup>
### Summary

We started to use [react-aria-components](https://react-spectrum.adobe.com/react-aria/) in our NextJS project and we encountered something strange: when using just a simple `<Button>` from **_react-aria-components_**, the entire  140kb+ **_react-aria-components_** package is imported in the app as seen in the [next-bundle-analyzer](https://github.com/vercel/next.js/tree/canary/packages/next-bundle-analyzer) report below:

image

At first, I thought this is a problem with how the files are exported from **_react-aria-components_**. 

I don't think this is the case, because a [Vite](https://vitejs.dev/) React project shows it only imports under 40kb of react-aria-components packages as seen in the [vite-bundle-visualizer](https://www.npmjs.com/package/vite-bundle-visualizer) report below:

image

Is [next-bundle-analyzer](https://github.com/vercel/next.js/tree/canary/packages/next-bundle-analyzer) outputting wrong data or is there a problem with the NextJS builder?

Following this issue, I came across other two opened issues:
- https://github.com/vercel/next.js/issues/12557
- which points to https://github.com/vercel/next.js/issues/44039

Reading these I noticed that using 'use client' in every page does bring the react-aria-components package size down to ~40kb:
image

image

You might thing the issue is solved, but nooo. 

As you will notice in the NextJS repos I created to replicate the issue and I listed below, the "/" page is using a simple `<Button>` and the "/other-page" is using a more complex `<Select>` component. Still, the "/" page that is using only a `<Button>` contains all of the modules for the `<Select>` component EVEN IF the "/" page is not using the `<Select>` component at all. 🤯 

Here is another example where I have a page with a `<Table>` from react-aria-components (I didn't add this page in the repo, but you get the idea). The bundle size goes crazy to around ~140kb:
image

In order to see this yourself, clone the NextJS repo linked below. From there, check these scenarios:

**Scenario 1**: run `npm run build`. In the "client" bundle analyzer browser tab, after you select the "app/page" file, you will see the bundle have around 36kb. This contains both the Button and Select modules:
image

**Scenario 2**: delete the entire "other-page" folder and run `npm run build` again. In the "client" bundle analyzer  opened tab, after you select the "app/page" file. Notice the bundle size for react-aria going down to around ~15kb. It contains only the modules for <Button>. Below are some screenshots for both the "app/page" page and "app/other-page/page" page:

image

image

**Scenario 3**: remove the 'use client' from the "app/page.tsx" file and run `npm run build` again. In the "client" bundle analyzer  opened tab, after you select the "app/page" file. Notice the bundle size going up to ~140kb for react-aria. It contains the ENTIRE "react-aria-components" library
image

Using `modularizeImports` doesn't work for react-aria-components, but I think this is a react-aria-components issue:
image

Also, using `"sideEffect": false` doesn't do anything either.

---

I don't know what happens, but it seems NextJS is summing up all the used imports and uses that FOR EVERY SINGLE PAGE that uses react-aria-components. 

It should split the react-aria-component library based on every component used for that particular page.

Here are the repos you can use to see the difference:
- NextJS repo: https://github.com/IonelLupu/react-aria-button-bundle-size-nextjs
- Vite repo: https://github.com/IonelLupu/react-aria-button-bundle-size-vite
 

### Additional information

```js
$ next info  

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Fri Dec  1 03:17:00 PST 2023; root:xnu-10002.80.11~58/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 14.0.5-canary.37
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Example

https://github.com/IonelLupu/react-aria-button-bundle-size-nextjs</div>

### PR DESCRIPTION
**Pull request by huozhi**
### What & Why

This PR helps fixes a long time tree-shaking issue that if you're import some identifiers from client components, the whole client component is being included in the client chunk. Because we're using import eager mode in webpack to include all the client component modules that make sure they're present in SSR entry and browser entry when they're transformed to client reference on RSC layer.

But the way we collect client components is a bit "aggressive" where contains some spaces to optimize.

### How

We change the collected client components from simpliy collecting it resolved module request, into collecting both the imported identifiers (by server components) and the module request. And when we inserted the used client components imports into the SSR and Client entry, leverage webpack magic comments `"webpackExports"` to only contain the used exports in the bundle. Thank you webpack for this nice feature : )

Along the way we also fixed an issue that when you only used default export, the `default` export itself should also be proxied when the bundle is in ESM.

#### Notice

There's a limitation yet that it can't work with barrel file, if you have a shared component `index.js` to re-export the changes several client components there and you only partially import few from `index.js` it won't work. For the cases that the node_modules package contain a barrel file importing multiple client components, please use [optimizePackageImports](https://nextjs.org/docs/app/api-reference/next-config-js/optimizePackageImports) config for now. We'll have follow up optimizations

### Testing Result

If we compare the `react-aria-components` the reproduction from #60246, you'll see the result being optimized a lot:

#### After vs Before

134KB being tree-shaked out 🤯 
```
Route (app)                              Size     First Load JS
┌ ○ /                                    324 B           127 kB
├ ○ /_not-found                          872 B          86.5 kB
└ ○ /other-page                          174 B           127 kB
```

```
Route (app)                              Size     First Load JS
┌ ○ /                                    325 B           261 kB
├ ○ /_not-found                          870 B          86.5 kB
└ ○ /other-page                          176 B           261 kB
```

Fixes #60246
Related report: https://github.com/adobe/react-spectrum/issues/5639
Closes NEXT-2527
phase 1 of NEXT-1799

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js client-components-opt | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.4s | N/A |
| buildDurationCached | 7.5s | 8.1s | ⚠️ +587ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +15.4 kB |
| nextStartRea..uration (ms) | 424ms | 437ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js client-components-opt | Change |
| - | - | - | - |
| 1068-HASH.js gzip | 30.3 kB | 30.3 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.5 kB | 53.5 kB | N/A |
| 4944-HASH.js gzip | 5.04 kB | 5.03 kB | N/A |
| 8423.HASH.js gzip | 181 B | 181 B | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 242 B | N/A |
| main-HASH.js gzip | 32.1 kB | 32.1 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 47.1 kB | 47.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js client-components-opt | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js client-components-opt | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 196 B | ✓ |
| _error-HASH.js gzip | 184 B | 183 B | N/A |
| amp-HASH.js gzip | 503 B | 504 B | N/A |
| css-HASH.js gzip | 323 B | 324 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.51 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 353 B | 351 B | N/A |
| hooks-HASH.js gzip | 370 B | 370 B | ✓ |
| image-HASH.js gzip | 4.21 kB | 4.2 kB | N/A |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.68 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 313 B | 314 B | N/A |
| script-HASH.js gzip | 386 B | 385 B | N/A |
| withRouter-HASH.js gzip | 309 B | 311 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 931 B | 931 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js client-components-opt | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js client-components-opt | Change |
| - | - | - | - |
| index.html gzip | 529 B | 529 B | ✓ |
| link.html gzip | 541 B | 541 B | ✓ |
| withRouter.html gzip | 524 B | 523 B | N/A |
| Overall change | 1.07 kB | 1.07 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js client-components-opt | Change |
| - | - | - | - |
| edge-ssr.js gzip | 2.29 kB | 2.29 kB | N/A |
| page.js gzip | 2.98 kB | 2.98 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js client-components-opt | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 625 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 466 B | 465 B | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js client-components-opt | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 166 kB | 166 kB | ✓ |
| app-page-exp..prod.js gzip | 95.9 kB | 95.9 kB | ✓ |
| app-page-tur..prod.js gzip | 97.6 kB | 97.6 kB | ✓ |
| app-page-tur..prod.js gzip | 92 kB | 92 kB | ✓ |
| app-page.run...dev.js gzip | 136 kB | 136 kB | ✓ |
| app-page.run..prod.js gzip | 90.6 kB | 90.6 kB | ✓ |
| app-route-ex...dev.js gzip | 22 kB | 22 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.47 kB | 9.47 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.74 kB | 9.74 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.47 kB | 9.47 kB | ✓ |
| pages-turbo...prod.js gzip | 22.1 kB | 22.1 kB | ✓ |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | ✓ |
| pages.runtim..prod.js gzip | 22.1 kB | 22.1 kB | ✓ |
| server.runti..prod.js gzip | 50.1 kB | 50.1 kB | ✓ |
| Overall change | 927 kB | 927 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js client-components-opt | Change |
| - | - | - | - |
| 0.pack gzip | 1.49 MB | 1.49 MB | N/A |
| index.pack gzip | 104 kB | 104 kB | ⚠️ +258 B |
| Overall change | 104 kB | 104 kB | ⚠️ +258 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>1068-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 9fa375469a55811d4f54047de7a5a8fee214e2fe

**Comment by ijjk** [comment]
## Failing test suites 
Commit: cfb34b4fa7bfd1e91a35b37a2e5985009fbc1e53

`pnpm test-start test/e2e/app-dir/app/standalone.test.ts` (PPR)
- output: standalone with app dir > should work correctly with output standalone

<details>
<summary>Expand output</summary>

  ● output: standalone with app dir › should work correctly with output standalone

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 500

      93 |           ]) {
      94 |             const res = await fetchViaHTTP(appPort, testPath)
    > 95 |             expect(res.status).toBe(200)
         |                                ^
      96 |           }
      97 |         } finally {
      98 |           if (server) await killApp(server)

      at Object.toBe (e2e/app-dir/app/standalone.test.ts:95:32)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: packages/next/src/build/webpack/loaders/next-flight-client-entry-loader.ts [hunk 1]
```diff
@@ -1,43 +1,64 @@
...
+          ? request.replace(':', '!=!')
+          : request
+      )
+
+      // When we cannot determine the export names, we use eager mode to include the whole module.
+      // Otherwise, we use eager mode with webpackExports to only include the necessary exports.
+      if (ids.length === 0) {
+        return `import(/* webpackMode: "eager" */ ${importPath});\n`
+      } else {
+        return `import(/* webpackMode: "eager" */ /* webpackExports: ${JSON.stringify(
```
Comment (shuding) [inline packages/next/src/build/webpack/loaders/next-flight-client-entry-loader.ts:54]:
```suggestion
        return `import(/* webpackMode: "eager", webpackExports: ${JSON.stringify(
```

File: packages/next/src/build/webpack/plugins/flight-client-entry-plugin.ts [hunk 2]
```diff
@@ -460,7 +469,8 @@ export class FlightClientEntryPlugin {
         }
       }
 
-      return Promise.all(addedClientActionEntryList)
+      await Promise.all(addedClientActionEntryList)
+      return
     })
```
Comment (shuding) [inline packages/next/src/build/webpack/plugins/flight-client-entry-plugin.ts:474]: Unnecessary change?

**Review by shuding — APPROVED** [review]

File: packages/next/src/build/webpack/plugins/flight-client-entry-plugin.ts (hunk 2 above)
Comment (huozhi) [reply packages/next/src/build/webpack/plugins/flight-client-entry-plugin.ts:474]: This was changed related to typing updates, it needs to return `Promise<void>`. I tried tapAsync it will hang so I switched to a new line
