### PR TITLE
Fix react-refresh for transpiled packages

### LINKED ISSUE #56487: transpilePackages causes use of 'import.meta' outside a module, breaking dev mode
### Link to the code that reproduces this issue

https://github.com/sawyerh/nextjs-pino-transpilePackages-bug

### To Reproduce

This bug happens when [`pino`](https://github.com/pinojs/pino) is in the `transpilePackages` config array.

Using the linked repo:

To reproduce the bug, run the application in dev mode:

```
npm run dev
```

You will see the following error:

```
 ⨯ ./node_modules/pino/browser.js
Module parse failed: Cannot use 'import.meta' outside a module (437:16)
|                 // still a Refresh Boundary later.
|                 // @ts-ignore importMeta is replaced in the loader
>                 import.meta.webpackHot.accept();
|                 // This field is set when the previous version of this module was a
|                 // Refresh Boundary, letting us know we need to check for invalidation or
```

To resolve the issue, remove `transpilePackages` from `next.config.js` and restart the server.

### Current vs. Expected behavior

`next dev` fails to run successfully when [`pino`](https://github.com/pinojs/pino) is in the `transpilePackages` config, but `next build && next start` works as expected. I expected `next dev` to also run successfully. 

I am transpiling `pino` in order to support Firefox versions prior to 71.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:30 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T8103
Binaries:
  Node: 18.12.1
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 8.4.0
Relevant Packages:
  next: 13.5.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

SWC transpilation

### Additional context

A similar `import.meta` error message was reported in https://github.com/vercel/next.js/issues/35110 however it's not caused by usage of `transpilePackages`.

<sub>[NEXT-2061](https://linear.app/vercel/issue/NEXT-2061/transpilepackages-causes-use-of-importmeta-outside-a-module-breaking)</sub>

### PR DESCRIPTION
**Pull request by huozhi**
### What

We're applying react-refresh to browser layer and inject ESM or CJS helper based on file type. Some package from `trasnpilePackages` might contain CJS browser bundle. And injecting ESM helper breaks them. Actually they don't need to have fast refresh ability since they're in `node_modules`.

### How
Skip react-refresh for transpiled packages as they're in node_modules and won't change. 

Fixes #56487 
Closes NEXT-2061

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/transpiled-react-refresh | Change |
| - | - | - | - |
| buildDuration | 13s | 13s | N/A |
| buildDurationCached | 7.3s | 6.1s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +3.78 kB |
| nextStartRea..uration (ms) | 431ms | 432ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/transpiled-react-refresh | Change |
| - | - | - | - |
| 193.HASH.js gzip | 181 B | 182 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | N/A |
| 433-HASH.js gzip | 28.6 kB | 28.6 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 239 B | 242 B | N/A |
| main-HASH.js gzip | 31.8 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 45.2 kB | 45.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/transpiled-react-refresh | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/transpiled-react-refresh | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 183 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 502 B | N/A |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 253 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.28 kB | 4.28 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | ✓ |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.4 kB | 3.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/transpiled-react-refresh | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/transpiled-react-refresh | Change |
| - | - | - | - |
| index.html gzip | 529 B | 527 B | N/A |
| link.html gzip | 541 B | 540 B | N/A |
| withRouter.html gzip | 524 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/transpiled-react-refresh | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.8 kB | 93.8 kB | N/A |
| page.js gzip | 148 kB | 148 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/transpiled-react-refresh | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 624 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.5 kB | 37.5 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/transpiled-react-refresh | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 169 kB | 169 kB | ✓ |
| app-page-exp..prod.js gzip | 95.2 kB | 95.2 kB | ✓ |
| app-page-tur..prod.js gzip | 95.9 kB | 95.9 kB | ✓ |
| app-page-tur..prod.js gzip | 90.5 kB | 90.5 kB | ✓ |
| app-page.run...dev.js gzip | 142 kB | 142 kB | ✓ |
| app-page.run..prod.js gzip | 89.8 kB | 89.8 kB | ✓ |
| app-route-ex...dev.js gzip | 24.1 kB | 24.1 kB | ✓ |
| app-route-ex..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| app-route.ru...dev.js gzip | 23.5 kB | 23.5 kB | ✓ |
| app-route.ru..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.38 kB | 9.38 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.65 kB | 9.65 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.6 kB | 49.6 kB | ✓ |
| Overall change | 940 kB | 940 kB | ✓ |

</details>

</details>
Commit: 5411c41419a6f9da978aab6cf05d64a9f88c163b

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 5411c41419a6f9da978aab6cf05d64a9f88c163b

`pnpm test-dev test/e2e/app-dir/app-external/app-external.test.ts` 
- app dir - external dependency > should handle external async module libraries correctly
- app dir - external dependency > should transpile specific external packages with the `transpilePackages` option
- app dir - external dependency > should resolve the subset react in server components based on the react-server condition
- app dir - external dependency > should resolve 3rd party package exports based on the react-server condition
- app dir - external dependency > should correctly collect global css imports and mark them as side effects
- app dir - external dependency > should handle external css modules
- app dir - external dependency > should use the same export type for packages in both ssr and client
- app dir - external dependency > should handle external css modules in pages
- app dir - external dependency > should handle external next/font
- app dir - external dependency > should emit cjs helpers for external cjs modules when compiled
- app dir - external dependency > should export client module references in esm
- app dir - external dependency > should support exporting multiple star re-exports
- app dir - external dependency > should use the same async storages if imported directly
- app dir - external dependency > mixed syntax external modules > should handle mixed module with next/dynamic
- app dir - external dependency > mixed syntax external modules > should handle mixed module in server and client components
- app dir - external dependency > react in external esm packages > should use the same react in client app
- app dir - external dependency > react in external esm packages > should use the same react in server app
- app dir - external dependency > react in external esm packages > should use the same react in edge server app
- app dir - external dependency > react in external esm packages > should use the same react in pages
- app dir - external dependency > server actions > should not prefer to resolve esm over cjs for bundling optout packages
- app dir - external dependency > server actions > should compile server actions from node_modules in client components

<details>
<summary>Expand output</summary>

  ● app dir - external dependency › should handle external async module libraries correctly

    page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('#content')
    ============================================================

      417 |     return this.chain(() => {
      418 |       return page
    > 419 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      420 |         .then(async (el) => {
      421 |           // it seems selenium waits longer and tests rely on this behavior
      422 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:419:10)

  ● app dir - external dependency › should transpile specific external packages with the `transpilePackages` option

    expect(received).toContain(expected) // indexOf

    Expected substring: "transpilePackages:5"
    Received string:    "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1705064848617\"></script><script src=\"/_next/static/chunks/fallback/webpack.js?ts=1705064848617\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/main.js?ts=1705064848617\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_app.js?ts=1705064848617\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_error.js?ts=1705064848617\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"></div><script src=\"/_next/static/chunks/fallback/react-refresh.js?ts=1705064848617\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Error\",\"source\":\"server\",\"message\":\"Module not found: Can't resolve 'untranspiled-module'\\n  3 | import getType, { named, value, array, obj } from 'non-isomorphic-text'\\n  4 |\\n\\u003e 5 | import add from 'untranspiled-module'\\n  6 |\\n  7 | // ESM externals has react has a peer dependency\\n  8 | import useSWR from 'swr'\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\",\"stack\":\"Error: Module not found: Can't resolve 'untranspiled-module'\\n\\u001b[0m \\u001b[90m 3 |\\u001b[39m \\u001b[36mimport\\u001b[39m getType\\u001b[33m,\\u001b[39m { named\\u001b[33m,\\u001b[39m value\\u001b[33m,\\u001b[39m array\\u001b[33m,\\u001b[39m obj } \\u001b[36mfrom\\u001b[39m \\u001b[32m'non-isomorphic-text'\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 4 |\\u001b[39m\\u001b[0m\\n\\u001b[0m\\u001b[31m\\u001b[1m\\u003e\\u001b[22m\\u001b[39m\\u001b[90m 5 |\\u001b[39m \\u001b[36mimport\\u001b[39m add \\u001b[36mfrom\\u001b[39m \\u001b[32m'untranspiled-module'\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 6 |\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 7 |\\u001b[39m \\u001b[90m// ESM externals has react has a peer dependency\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 8 |\\u001b[39m \\u001b[36mimport\\u001b[39m useSWR \\u001b[36mfrom\\u001b[39m \\u001b[32m'swr'\\u001b[39m\\u001b[0m\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\\n    at getNotFoundError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:120:16)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async getModuleBuildError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:102:27)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:29:49\\n    at async Promise.all (index 0)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:27:21\"},\"gip\":true,\"scriptLoader\":[]}</script></body></html>"

      79 |     it('should transpile specific external packages with the `transpilePackages` option', async () => {
      80 |       const clientHtml = await next.render('/external-imports/client')
    > 81 |       expect(clientHtml).toContain('transpilePackages:5')
         |                          ^
      82 |     })
      83 |
      84 |     it('should resolve the subset react in server components based on the react-server condition', async () => {

      at Object.toContain (e2e/app-dir/app-external/app-external.test.ts:81:26)

  ● app dir - external dependency › should resolve the subset react in server components based on the react-server condition

    expect(received).toContain(expected) // indexOf

    Expected substring: "Server: subset"
    Received string:    "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1705064848995\"></script><script src=\"/_next/static/chunks/fallback/webpack.js?ts=1705064848995\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/main.js?ts=1705064848995\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_app.js?ts=1705064848995\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_error.js?ts=1705064848995\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"></div><script src=\"/_next/static/chunks/fallback/react-refresh.js?ts=1705064848995\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Error\",\"source\":\"server\",\"message\":\"Module not found: Can't resolve 'untranspiled-module'\\n  3 | import getType, { named, value, array, obj } from 'non-isomorphic-text'\\n  4 |\\n\\u003e 5 | import add from 'untranspiled-module'\\n  6 |\\n  7 | // ESM externals has react has a peer dependency\\n  8 | import useSWR from 'swr'\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\",\"stack\":\"Error: Module not found: Can't resolve 'untranspiled-module'\\n\\u001b[0m \\u001b[90m 3 |\\u001b[39m \\u001b[36mimport\\u001b[39m getType\\u001b[33m,\\u001b[39m { named\\u001b[33m,\\u001b[39m value\\u001b[33m,\\u001b[39m array\\u001b[33m,\\u001b[39m obj } \\u001b[36mfrom\\u001b[39m \\u001b[32m'non-isomorphic-text'\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 4 |\\u001b[39m\\u001b[0m\\n\\u001b[0m\\u001b[31m\\u001b[1m\\u003e\\u001b[22m\\u001b[39m\\u001b[90m 5 |\\u001b[39m \\u001b[36mimport\\u001b[39m add \\u001b[36mfrom\\u001b[39m \\u001b[32m'untranspiled-module'\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 6 |\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 7 |\\u001b[39m \\u001b[90m// ESM externals has react has a peer dependency\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 8 |\\u001b[39m \\u001b[36mimport\\u001b[39m useSWR \\u001b[36mfrom\\u001b[39m \\u001b[32m'swr'\\u001b[39m\\u001b[0m\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\\n    at getNotFoundError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:120:16)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async getModuleBuildError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:102:27)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:29:49\\n    at async Promise.all (index 0)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:27:21\"},\"gip\":true,\"scriptLoader\":[]}</script></body></html>"

      85 |       await next.fetch('/react-server').then(async (response) => {
      86 |         const result = await resolveStreamResponse(response)
    > 87 |         expect(result).toContain('Server: subset')
         |                        ^
      88 |         expect(result).toContain('Client: full')
      89 |       })
      90 |     })

      at toContain (e2e/app-dir/app-external/app-external.test.ts:87:24)
      at Object.<anonymous> (e2e/app-dir/app-external/app-external.test.ts:85:7)

  ● app dir - external dependency › should resolve 3rd party package exports based on the react-server condition

    expect(received).toContain(expected) // indexOf

    Expected substring: "Server: index.react-server:react.subset:dep.server"
    Received string:    "{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Error\",\"source\":\"server\",\"message\":\"Module not found: Can't resolve 'untranspiled-module'\\n  3 | import getType, { named, value, array, obj } from 'non-isomorphic-text'\\n  4 |\\n\\u003e 5 | import add from 'untranspiled-module'\\n  6 |\\n  7 | // ESM externals has react has a peer dependency\\n  8 | import useSWR from 'swr'\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\",\"stack\":\"Error: Module not found: Can't resolve 'untranspiled-module'\\n\\u001b[0m \\u001b[90m 3 |\\u001b[39m \\u001b[36mimport\\u001b[39m getType\\u001b[33m,\\u001b[39m { named\\u001b[33m,\\u001b[39m value\\u001b[33m,\\u001b[39m array\\u001b[33m,\\u001b[39m obj } \\u001b[36mfrom\\u001b[39m \\u001b[32m'non-isomorphic-text'\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 4 |\\u001b[39m\\u001b[0m\\n\\u001b[0m\\u001b[31m\\u001b[1m\\u003e\\u001b[22m\\u001b[39m\\u001b[90m 5 |\\u001b[39m \\u001b[36mimport\\u001b[39m add \\u001b[36mfrom\\u001b[39m \\u001b[32m'untranspiled-module'\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 6 |\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 7 |\\u001b[39m \\u001b[90m// ESM externals has react has a peer dependency\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 8 |\\u001b[39m \\u001b[36mimport\\u001b[39m useSWR \\u001b[36mfrom\\u001b[39m \\u001b[32m'swr'\\u001b[39m\\u001b[0m\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\\n    at getNotFoundError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:120:16)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async getModuleBuildError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:102:27)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:29:49\\n    at async Promise.all (index 0)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:27:21\"},\"gip\":true,\"scriptLoader\":[]}"

       97 |       // Package should be resolved based on the react-server condition,
       98 |       // as well as package's internal & external dependencies.
    >  99 |       expect(result).toContain(
          |                      ^
      100 |         'Server: index.react-server:react.subset:dep.server'
      101 |       )
      102 |       expect(result).toContain('Client: index.default:react.full:dep.default')

      at Object.toContain (e2e/app-dir/app-external/app-external.test.ts:99:22)

  ● app dir - external dependency › should correctly collect global css imports and mark them as side effects

    expect(received).toMatch(expected)

    Expected pattern: /\.css/
    Received string:  "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1705064849492\"></script><script src=\"/_next/static/chunks/fallback/webpack.js?ts=1705064849492\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/main.js?ts=1705064849492\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_app.js?ts=1705064849492\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_error.js?ts=1705064849492\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"></div><script src=\"/_next/static/chunks/fallback/react-refresh.js?ts=1705064849492\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Error\",\"source\":\"server\",\"message\":\"Module not found: Can't resolve 'untranspiled-module'\\n  3 | import getType, { named, value, array, obj } from 'non-isomorphic-text'\\n  4 |\\n\\u003e 5 | import add from 'untranspiled-module'\\n  6 |\\n  7 | // ESM externals has react has a peer dependency\\n  8 | import useSWR from 'swr'\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\",\"stack\":\"Error: Module not found: Can't resolve 'untranspiled-module'\\n\\u001b[0m \\u001b[90m 3 |\\u001b[39m \\u001b[36mimport\\u001b[39m getType\\u001b[33m,\\u001b[39m { named\\u001b[33m,\\u001b[39m value\\u001b[33m,\\u001b[39m array\\u001b[33m,\\u001b[39m obj } \\u001b[36mfrom\\u001b[39m \\u001b[32m'non-isomorphic-text'\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 4 |\\u001b[39m\\u001b[0m\\n\\u001b[0m\\u001b[31m\\u001b[1m\\u003e\\u001b[22m\\u001b[39m\\u001b[90m 5 |\\u001b[39m \\u001b[36mimport\\u001b[39m add \\u001b[36mfrom\\u001b[39m \\u001b[32m'untranspiled-module'\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 6 |\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 7 |\\u001b[39m \\u001b[90m// ESM externals has react has a peer dependency\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 8 |\\u001b[39m \\u001b[36mimport\\u001b[39m useSWR \\u001b[36mfrom\\u001b[39m \\u001b[32m'swr'\\u001b[39m\\u001b[0m\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\\n    at getNotFoundError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:120:16)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async getModuleBuildError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:102:27)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:29:49\\n    at async Promise.all (index 0)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:27:21\"},\"gip\":true,\"scriptLoader\":[]}</script></body></html>"

      115 |
      116 |         // It should include the global CSS import
    > 117 |         expect(result).toMatch(/\.css/)
          |                        ^
      118 |       })
      119 |     })
      120 |

      at toMatch (e2e/app-dir/app-external/app-external.test.ts:117:24)
      at Object.<anonymous> (e2e/app-dir/app-external/app-external.test.ts:113:7)

  ● app dir - external dependency › should handle external css modules

    expect(received).toBe(expected) // Object.is equality

    Expected: "rgb(255, 0, 0)"
    Received: null

      126 |           `window.getComputedStyle(document.querySelector('h1')).color`
      127 |         )
    > 128 |       ).toBe('rgb(255, 0, 0)')
          |         ^
      129 |     })
      130 |
      131 |     it('should use the same export type for packages in both ssr and client', async () => {

      at Object.toBe (e2e/app-dir/app-external/app-external.test.ts:128:9)

  ● app dir - external dependency › should use the same export type for packages in both ssr and client

    expect(received).toBe(expected) // Object.is equality

    Expected: "hello"
    Received: ""

      131 |     it('should use the same export type for packages in both ssr and client', async () => {
      132 |       const browser = await next.browser('/client-dep')
    > 133 |       expect(await browser.eval(`window.document.body.innerText`)).toBe('hello')
          |                                                                    ^
      134 |     })
      135 |
      136 |     it('should handle external css modules in pages', async () => {

      at Object.toBe (e2e/app-dir/app-external/app-external.test.ts:133:68)

  ● app dir - external dependency › should handle external css modules in pages

    expect(received).toBe(expected) // Object.is equality

    Expected: "rgb(255, 0, 0)"
    Received: null

      141 |           `window.getComputedStyle(document.querySelector('h1')).color`
      142 |         )
    > 143 |       ).toBe('rgb(255, 0, 0)')
          |         ^
      144 |     })
      145 |
      146 |     it('should handle external next/font', async () => {

      at Object.toBe (e2e/app-dir/app-external/app-external.test.ts:143:9)

  ● app dir - external dependency › should handle external next/font

    expect(received).toMatch(expected)

    Expected pattern: /^__myFont_.{6}, __myFont_Fallback_.{6}$/
    Received string:  "\"Times New Roman\""

      151 |           `window.getComputedStyle(document.querySelector('p')).fontFamily`
      152 |         )
    > 153 |       ).toMatch(/^__myFont_.{6}, __myFont_Fallback_.{6}$/)
          |         ^
      154 |     })
      155 |
      156 |     describe('react in external esm packages', () => {

      at Object.toMatch (e2e/app-dir/app-external/app-external.test.ts:153:9)

  ● app dir - external dependency › react in external esm packages › should use the same react in client app

    TypeError: Cannot read properties of null (reading '1')

      158 |         const html = await next.render('/esm/client')
      159 |
    > 160 |         const v1 = html.match(/App React Version: ([^<]+)</)[1]
          |                                                             ^
      161 |         const v2 = html.match(/External React Version: ([^<]+)</)[1]
      162 |         expect(v1).toBe(v2)
      163 |

      at Object.<anonymous> (e2e/app-dir/app-external/app-external.test.ts:160:61)

  ● app dir - external dependency › react in external esm packages › should use the same react in server app

    TypeError: Cannot read properties of null (reading '1')

      175 |         const html = await next.render('/esm/server')
      176 |
    > 177 |         const v1 = html.match(/App React Version: ([^<]+)</)[1]
          |                                                             ^
      178 |         const v2 = html.match(/External React Version: ([^<]+)</)[1]
      179 |         expect(v1).toBe(v2)
      180 |

      at Object.<anonymous> (e2e/app-dir/app-external/app-external.test.ts:177:61)

  ● app dir - external dependency › react in external esm packages › should use the same react in edge server app

    TypeError: Cannot read properties of null (reading '1')

      189 |         const html = await next.render('/esm/edge-server')
      190 |
    > 191 |         const v1 = html.match(/App React Version: ([^<]+)</)[1]
          |                                                             ^
      192 |         const v2 = html.match(/External React Version: ([^<]+)</)[1]
      193 |         expect(v1).toBe(v2)
      194 |

      at Object.<anonymous> (e2e/app-dir/app-external/app-external.test.ts:191:61)

  ● app dir - external dependency › react in external esm packages › should use the same react in pages

    TypeError: Cannot read properties of null (reading '1')

      203 |         const html = await next.render('/test-pages-esm')
      204 |
    > 205 |         const v1 = html.match(/App React Version: ([^<]+)</)[1]
          |                                                             ^
      206 |         const v2 = html.match(/External React Version: ([^<]+)</)[1]
      207 |         expect(v1).toBe(v2)
      208 |       })

      at Object.<anonymous> (e2e/app-dir/app-external/app-external.test.ts:205:61)

  ● app dir - external dependency › mixed syntax external modules › should handle mixed module with next/dynamic

    page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('#component')
    ============================================================

      417 |     return this.chain(() => {
      418 |       return page
    > 419 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      420 |         .then(async (el) => {
      421 |           // it seems selenium waits longer and tests rely on this behavior
      422 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:419:10)

  ● app dir - external dependency › mixed syntax external modules › should handle mixed module in server and client components

    expect(received).toContain(expected) // indexOf

    Expected substring: "server:mixed-syntax-esm"
    Received string:    ""

      219 |       it('should handle mixed module in server and client components', async () => {
      220 |         const $ = await next.render$('/mixed/import')
    > 221 |         expect(await $('#server').text()).toContain('server:mixed-syntax-esm')
          |                                           ^
      222 |         expect(await $('#client').text()).toContain('client:mixed-syntax-esm')
      223 |         expect(await $('#relative-mixed').text()).toContain(
      224 |           'relative-mixed-syntax-esm'

      at Object.toContain (e2e/app-dir/app-external/app-external.test.ts:221:43)

  ● app dir - external dependency › should emit cjs helpers for external cjs modules when compiled

    expect(received).toBe(expected) // Object.is equality

    Expected: "prop"
    Received: ""

      229 |     it('should emit cjs helpers for external cjs modules when compiled', async () => {
      230 |       const $ = await next.render$('/cjs/client')
    > 231 |       expect($('#private-prop').text()).toBe('prop')
          |                                         ^
      232 |       expect($('#transpile-cjs-lib').text()).toBe('transpile-cjs-lib')
      233 |
      234 |       const browser = await next.browser('/cjs/client')

      at Object.toBe (e2e/app-dir/app-external/app-external.test.ts:231:41)

  ● app dir - external dependency › should export client module references in esm

    expect(received).toContain(expected) // indexOf

    Expected substring: "hello"
    Received string:    "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1705064914273\"></script><script src=\"/_next/static/chunks/fallback/webpack.js?ts=1705064914273\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/main.js?ts=1705064914273\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_app.js?ts=1705064914273\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_error.js?ts=1705064914273\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"></div><script src=\"/_next/static/chunks/fallback/react-refresh.js?ts=1705064914273\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Error\",\"source\":\"server\",\"message\":\"Module not found: Can't resolve 'test/e2e/app-dir/app-external/node_modules_bak/transpile-cjs-lib'\\n  2 |\\n  3 | import { instance } from 'cjs-modern-syntax'\\n\\u003e 4 | import { packageName } from 'test/e2e/app-dir/app-external/node_modules_bak/transpile-cjs-lib'\\n  5 | export default function Page() {\\n  6 |   return (\\n  7 |     \\u003c\\u003e\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\",\"stack\":\"Error: Module not found: Can't resolve 'test/e2e/app-dir/app-external/node_modules_bak/transpile-cjs-lib'\\n\\u001b[0m \\u001b[90m 2 |\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 3 |\\u001b[39m \\u001b[36mimport\\u001b[39m { instance } \\u001b[36mfrom\\u001b[39m \\u001b[32m'cjs-modern-syntax'\\u001b[39m\\u001b[0m\\n\\u001b[0m\\u001b[31m\\u001b[1m\\u003e\\u001b[22m\\u001b[39m\\u001b[90m 4 |\\u001b[39m \\u001b[36mimport\\u001b[39m { packageName } \\u001b[36mfrom\\u001b[39m \\u001b[32m'test/e2e/app-dir/app-external/node_modules_bak/transpile-cjs-lib'\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 5 |\\u001b[39m \\u001b[36mexport\\u001b[39m \\u001b[36mdefault\\u001b[39m \\u001b[36mfunction\\u001b[39m \\u001b[33mPage\\u001b[39m() {\\u001b[0m\\n\\u001b[0m \\u001b[90m 6 |\\u001b[39m   \\u001b[36mreturn\\u001b[39m (\\u001b[0m\\n\\u001b[0m \\u001b[90m 7 |\\u001b[39m     \\u001b[33m\\u003c\\u001b[39m\\u001b[33m\\u003e\\u001b[39m\\u001b[0m\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\\n    at getNotFoundError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:120:16)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async getModuleBuildError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:102:27)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:29:49\\n    at async Promise.all (index 0)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:27:21\"},\"gip\":true,\"scriptLoader\":[]}</script></body></html>"

      238 |     it('should export client module references in esm', async () => {
      239 |       const html = await next.render('/esm-client-ref')
    > 240 |       expect(html).toContain('hello')
          |                    ^
      241 |     })
      242 |
      243 |     it('should support exporting multiple star re-exports', async () => {

      at Object.toContain (e2e/app-dir/app-external/app-external.test.ts:240:20)

  ● app dir - external dependency › should support exporting multiple star re-exports

    expect(received).toContain(expected) // indexOf

    Expected substring: "Foo"
    Received string:    "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1705064914455\"></script><script src=\"/_next/static/chunks/fallback/webpack.js?ts=1705064914455\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/main.js?ts=1705064914455\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_app.js?ts=1705064914455\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_error.js?ts=1705064914455\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"></div><script src=\"/_next/static/chunks/fallback/react-refresh.js?ts=1705064914455\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Error\",\"source\":\"server\",\"message\":\"Module not found: Can't resolve 'test/e2e/app-dir/app-external/node_modules_bak/transpile-cjs-lib'\\n  2 |\\n  3 | import { instance } from 'cjs-modern-syntax'\\n\\u003e 4 | import { packageName } from 'test/e2e/app-dir/app-external/node_modules_bak/transpile-cjs-lib'\\n  5 | export default function Page() {\\n  6 |   return (\\n  7 |     \\u003c\\u003e\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\",\"stack\":\"Error: Module not found: Can't resolve 'test/e2e/app-dir/app-external/node_modules_bak/transpile-cjs-lib'\\n\\u001b[0m \\u001b[90m 2 |\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 3 |\\u001b[39m \\u001b[36mimport\\u001b[39m { instance } \\u001b[36mfrom\\u001b[39m \\u001b[32m'cjs-modern-syntax'\\u001b[39m\\u001b[0m\\n\\u001b[0m\\u001b[31m\\u001b[1m\\u003e\\u001b[22m\\u001b[39m\\u001b[90m 4 |\\u001b[39m \\u001b[36mimport\\u001b[39m { packageName } \\u001b[36mfrom\\u001b[39m \\u001b[32m'test/e2e/app-dir/app-external/node_modules_bak/transpile-cjs-lib'\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 5 |\\u001b[39m \\u001b[36mexport\\u001b[39m \\u001b[36mdefault\\u001b[39m \\u001b[36mfunction\\u001b[39m \\u001b[33mPage\\u001b[39m() {\\u001b[0m\\n\\u001b[0m \\u001b[90m 6 |\\u001b[39m   \\u001b[36mreturn\\u001b[39m (\\u001b[0m\\n\\u001b[0m \\u001b[90m 7 |\\u001b[39m     \\u001b[33m\\u003c\\u001b[39m\\u001b[33m\\u003e\\u001b[39m\\u001b[0m\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\\n    at getNotFoundError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:120:16)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async getModuleBuildError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:102:27)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:29:49\\n    at async Promise.all (index 0)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:27:21\"},\"gip\":true,\"scriptLoader\":[]}</script></body></html>"

      243 |     it('should support exporting multiple star re-exports', async () => {
      244 |       const html = await next.render('/wildcard')
    > 245 |       expect(html).toContain('Foo')
          |                    ^
      246 |     })
      247 |
      248 |     it('should have proper tree-shaking for known modules in CJS', async () => {

      at Object.toContain (e2e/app-dir/app-external/app-external.test.ts:245:20)

  ● app dir - external dependency › should use the same async storages if imported directly

    expect(received).toContain(expected) // indexOf

    Expected substring: "success"
    Received string:    "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1705064914682\"></script><script src=\"/_next/static/chunks/fallback/webpack.js?ts=1705064914682\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/main.js?ts=1705064914682\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_app.js?ts=1705064914682\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_error.js?ts=1705064914682\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"></div><script src=\"/_next/static/chunks/fallback/react-refresh.js?ts=1705064914682\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Error\",\"source\":\"server\",\"message\":\"Module not found: Can't resolve 'test/e2e/app-dir/app-external/node_modules_bak/transpile-cjs-lib'\\n  2 |\\n  3 | import { instance } from 'cjs-modern-syntax'\\n\\u003e 4 | import { packageName } from 'test/e2e/app-dir/app-external/node_modules_bak/transpile-cjs-lib'\\n  5 | export default function Page() {\\n  6 |   return (\\n  7 |     \\u003c\\u003e\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\",\"stack\":\"Error: Module not found: Can't resolve 'test/e2e/app-dir/app-external/node_modules_bak/transpile-cjs-lib'\\n\\u001b[0m \\u001b[90m 2 |\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 3 |\\u001b[39m \\u001b[36mimport\\u001b[39m { instance } \\u001b[36mfrom\\u001b[39m \\u001b[32m'cjs-modern-syntax'\\u001b[39m\\u001b[0m\\n\\u001b[0m\\u001b[31m\\u001b[1m\\u003e\\u001b[22m\\u001b[39m\\u001b[90m 4 |\\u001b[39m \\u001b[36mimport\\u001b[39m { packageName } \\u001b[36mfrom\\u001b[39m \\u001b[32m'test/e2e/app-dir/app-external/node_modules_bak/transpile-cjs-lib'\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 5 |\\u001b[39m \\u001b[36mexport\\u001b[39m \\u001b[36mdefault\\u001b[39m \\u001b[36mfunction\\u001b[39m \\u001b[33mPage\\u001b[39m() {\\u001b[0m\\n\\u001b[0m \\u001b[90m 6 |\\u001b[39m   \\u001b[36mreturn\\u001b[39m (\\u001b[0m\\n\\u001b[0m \\u001b[90m 7 |\\u001b[39m     \\u001b[33m\\u003c\\u001b[39m\\u001b[33m\\u003e\\u001b[39m\\u001b[0m\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\\n    at getNotFoundError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:120:16)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async getModuleBuildError (/tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:102:27)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:29:49\\n    at async Promise.all (index 0)\\n    at async /tmp/next-install-f11c4a1897df1d6f9bf042d41ec3c9c2c4014b269e70ec6f290b73d051c04e3c/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:27:21\"},\"gip\":true,\"scriptLoader\":[]}</script></body></html>"

      256 |     it('should use the same async storages if imported directly', async () => {
      257 |       const html = await next.render('/async-storage')
    > 258 |       expect(html).toContain('success')
          |                    ^
      259 |     })
      260 |
      261 |     describe('server actions', () => {

      at Object.toContain (e2e/app-dir/app-external/app-external.test.ts:258:20)

  ● app dir - external dependency › server actions › should not prefer to resolve esm over cjs for bundling optout packages

    page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('#dual-pkg-outout p')
    ============================================================

      417 |     return this.chain(() => {
      418 |       return page
    > 419 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      420 |         .then(async (el) => {
      421 |           // it seems selenium waits longer and tests rely on this behavior
      422 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:419:10)

  ● app dir - external dependency › server actions › should compile server actions from node_modules in client components

    page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('#action')
    ============================================================

      417 |     return this.chain(() => {
      418 |       return page
    > 419 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      420 |         .then(async (el) => {
      421 |           // it seems selenium waits longer and tests rely on this behavior
      422 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:419:10)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: packages/next/src/build/webpack-config.ts [hunk 1]
```diff
@@ -1397,8 +1403,16 @@ export default async function getBaseWebpackConfig(
...
+                test: {
+                  and: [
+                    codeCondition.test,
+                    {
+                      not: [transpilePackagesRegex],
+                    },
+                  ],
+                },
+
+                exclude: [codeCondition.exclude],
```
Comment (shuding) [inline packages/next/src/build/webpack-config.ts:1415]: Simpler maybe?

```suggestion
                test: codeCondition.test,
                exclude: [codeCondition.exclude, transpilePackagesRegex],
```

**Review by shuding — APPROVED** [review]

**Review by ztanner — APPROVED** [review]
