### PR TITLE
Ensure next/dynamic transpiles for tests

### LINKED ISSUE #24566: Jest tests failing when testing components with dynamic import in Next 10.2.0
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14

### What browser are you using?

N/A (but JSDOM in the test runner)

### What operating system are you using?

macos linux

### How are you deploying your application?

Pre deploy failure

### Describe the Bug

~~I'm still putting together a minimal reproduction case (will post shortly), but~~(added) My jest tests that test rendering of components that make use of `next/dynamic` began failing on next 10.2.0.

The error:

```console
project % npx jest components/header/header.test.jsx
 FAIL  components/header/header.test.jsx
  ● Test suite failed to run

    /project/components/header/header.jsx: The "from" argument must be of type string. Received undefined

      at Import (node_modules/next/build/babel/plugins/react-loadable-plugin.ts:154:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:55:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:42:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:92:31)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:116:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:85:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:144:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.54 s
Ran all test suites matching /components\/header\/header.test.jsx/i.
```

The simplified component in question:

```jsx
import dynamic from 'next/dynamic'

const SomeDynamicComp = dynamic(() =>
  import('./some-dynamic-comp').then((mod) => mod.SomeDynamicComp),
{ ssr: false })

export function SomeComp () {
  return (
    <div>
      Hello world
      <SomeDynamicComp />
    </div>
    )
}
```

This is the code that causes the test to fail with the above error:

```jsx
const SomeDynamicComp = dynamic(() =>
  import('./some-dynamic-comp').then((mod) => mod.SomeDynamicComp),
{ ssr: false })
```

The test that fails:

```jsx
import React from 'react'
import { render } from '@testing-library/react'

import { SomeComp } from './some-comp'

it('renders without error', () => {
  render(<SomeComp />)
})
```

When those were removed, the tests passed again on 10.2.0.  Leaving them in and pinning next to 10.1.3, things worked again. 

### Expected Behavior

That I can test react components in jest that utilize `next/dynamic`.

### To Reproduce

~~Reproducible gist incoming.   I need to extract out a simplified example.  Hang tight.~~

Failing example: https://github.com/ballpit/dynamic-10.2-bug/tree/master/components
Passing workaround: https://github.com/ballpit/dynamic-10.2-bug/compare/workaround

To run, just clone and run npm run test.  Jest is configured to use the following babel config:

```json
{
  "presets": ["next/babel"],
  "plugins": []
}
```

### PR DESCRIPTION
**Pull request by ijjk**
This ensures the `react-loadable` babel plugin used for `next/dynamic` works correctly when the `pagesDir` info is not provided. 

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added

Fixes: https://github.com/vercel/next.js/issues/24566

### CODE REVIEW

File: packages/next/build/babel/plugins/react-loadable-plugin.ts [hunk 1]
```diff
@@ -151,10 +151,12 @@ export default function ({
...
-                    relativePath(
-                      state.file.opts.caller.pagesDir,
-                      state.file.opts.filename
-                    ) + ' -> '
+                    (state.file.opts.caller.pagesDir
+                      ? relativePath(
+                          state.file.opts.caller.pagesDir,
+                          state.file.opts.filename
+                        )
+                      : state.file.opts.filename) + ' -> '
```
Comment (sokra) [inline packages/next/build/babel/plugins/react-loadable-plugin.ts:159]: This is not enough. The key is also used on the other side.

**Review by sokra — CHANGES_REQUESTED** [review]

File: packages/next/build/babel/plugins/react-loadable-plugin.ts (hunk 1 above)
Comment (sokra) [reply packages/next/build/babel/plugins/react-loadable-plugin.ts:159]: https://github.com/vercel/next.js/blob/1d643eb6e1cc57faaecf02e6c3c5e1bb463b2027/packages/next/build/webpack/plugins/react-loadable-plugin.ts#L108-L110

Comment (ijjk) [reply packages/next/build/babel/plugins/react-loadable-plugin.ts:159]: These files aren't loaded client-side, they are only being tested in the jest environment so this allows the babel transpile to complete and the tests to run, tested against the provided failing repo https://github.com/ballpit/dynamic-10.2-bug

Comment (ijjk) [reply packages/next/build/babel/plugins/react-loadable-plugin.ts:159]: We could only allow this if the `NODE_ENV` is set to test 🤔

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 13.8s | 14s | ⚠️ +190ms |
| buildDurationCached | 4.5s | 4.3s | -208ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.283 | 2.306 | ⚠️ +0.02 |
| / avg req/sec | 1094.88 | 1083.99 | ⚠️ -10.89 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.216 | 1.239 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2055.23 | 2017.37 | ⚠️ -37.86 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.51 kB | 8.51 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 393 B | 393 B | ✓ |
| Overall change | 393 B | 393 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| index.html gzip | 561 B | 561 B | ✓ |
| link.html gzip | 570 B | 570 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 17.1s | 17s | -82ms |
| buildDurationCached | 6.5s | 6.5s | ⚠️ +17ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.51 kB | 8.51 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 393 B | 393 B | ✓ |
| Overall change | 393 B | 393 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | ✓ |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.34 MB | 1.34 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.39 MB | 1.39 MB | ✓ |
| withRouter.js | 1.39 MB | 1.39 MB | ✓ |
| Overall change | 6.9 MB | 6.9 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 12s | 11.7s | -251ms |
| buildDurationCached | 5.1s | 4.8s | -256ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.335 | 2.394 | ⚠️ +0.06 |
| / avg req/sec | 1070.52 | 1044.41 | ⚠️ -26.11 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.213 | 1.226 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2061.7 | 2038.92 | ⚠️ -22.78 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.36 kB | 9.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: bd0a0704e1ddf63c2744e7ed16c2c44946d63a2b

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 14s | 14.4s | ⚠️ +377ms |
| buildDurationCached | 4.8s | 4.4s | -428ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.387 | 2.317 | -0.07 |
| / avg req/sec | 1047.14 | 1078.94 | +31.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.216 | 1.257 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2055.53 | 1988.34 | ⚠️ -67.19 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.51 kB | 8.51 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 393 B | 393 B | ✓ |
| Overall change | 393 B | 393 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| index.html gzip | 561 B | 561 B | ✓ |
| link.html gzip | 570 B | 570 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 17.7s | 17.4s | -324ms |
| buildDurationCached | 6.6s | 6.7s | ⚠️ +29ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.51 kB | 8.51 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 393 B | 393 B | ✓ |
| Overall change | 393 B | 393 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | ✓ |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.34 MB | 1.34 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.39 MB | 1.39 MB | ✓ |
| withRouter.js | 1.39 MB | 1.39 MB | ✓ |
| Overall change | 6.9 MB | 6.9 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12.2s | ⚠️ +64ms |
| buildDurationCached | 4.9s | 5s | ⚠️ +21ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.359 | 2.478 | ⚠️ +0.12 |
| / avg req/sec | 1059.77 | 1009.04 | ⚠️ -50.73 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.308 | 1.276 | -0.03 |
| /error-in-render avg req/sec | 1911.15 | 1959.25 | +48.1 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.36 kB | 9.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: c358bfe586bb431e784e86b3f6ebf8f7333f3ac2

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 17.4s | 17.5s | ⚠️ +106ms |
| buildDurationCached | 5.7s | 5.4s | -208ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.851 | 2.945 | ⚠️ +0.09 |
| / avg req/sec | 876.8 | 849.01 | ⚠️ -27.79 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.768 | 1.711 | -0.06 |
| /error-in-render avg req/sec | 1414.38 | 1461.55 | +47.17 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.51 kB | 8.51 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 393 B | 393 B | ✓ |
| Overall change | 393 B | 393 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| index.html gzip | 561 B | 561 B | ✓ |
| link.html gzip | 570 B | 570 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 21.5s | 20.9s | -577ms |
| buildDurationCached | 7.8s | 7.8s | ⚠️ +15ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.51 kB | 8.51 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 393 B | 393 B | ✓ |
| Overall change | 393 B | 393 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | ✓ |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.34 MB | 1.34 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.39 MB | 1.39 MB | ✓ |
| withRouter.js | 1.39 MB | 1.39 MB | ✓ |
| Overall change | 6.9 MB | 6.9 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 14.3s | 14.4s | ⚠️ +119ms |
| buildDurationCached | 6s | 6.1s | ⚠️ +72ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.864 | 3 | ⚠️ +0.14 |
| / avg req/sec | 872.82 | 833.42 | ⚠️ -39.4 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.729 | 1.736 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1445.73 | 1440.29 | ⚠️ -5.44 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.36 kB | 9.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: 4c89b9de0927289dca89d4b214863ec9accbb348

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 15.8s | 15.6s | -226ms |
| buildDurationCached | 5.3s | 4.8s | -481ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.674 | 2.689 | ⚠️ +0.02 |
| / avg req/sec | 935.09 | 929.74 | ⚠️ -5.35 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.489 | 1.572 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1678.64 | 1590.56 | ⚠️ -88.08 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.51 kB | 8.51 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 393 B | 393 B | ✓ |
| Overall change | 393 B | 393 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| index.html gzip | 561 B | 561 B | ✓ |
| link.html gzip | 570 B | 570 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 19.7s | 19.2s | -528ms |
| buildDurationCached | 7.2s | 7.2s | ⚠️ +22ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.51 kB | 8.51 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 393 B | 393 B | ✓ |
| Overall change | 393 B | 393 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | ✓ |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.34 MB | 1.34 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.39 MB | 1.39 MB | ✓ |
| withRouter.js | 1.39 MB | 1.39 MB | ✓ |
| Overall change | 6.9 MB | 6.9 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 13.1s | 13.3s | ⚠️ +270ms |
| buildDurationCached | 5.6s | 5.5s | -81ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.807 | 2.74 | -0.07 |
| / avg req/sec | 890.58 | 912.56 | +21.98 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.595 | 1.567 | -0.03 |
| /error-in-render avg req/sec | 1567.66 | 1595.41 | +27.75 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.36 kB | 9.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: abf7637ce2132886d54dcd4813c36d046cb4b995

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 15.8s | 15.6s | -226ms |
| buildDurationCached | 5.3s | 4.8s | -481ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.674 | 2.689 | ⚠️ +0.02 |
| / avg req/sec | 935.09 | 929.74 | ⚠️ -5.35 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.489 | 1.572 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1678.64 | 1590.56 | ⚠️ -88.08 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.51 kB | 8.51 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 393 B | 393 B | ✓ |
| Overall change | 393 B | 393 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| index.html gzip | 561 B | 561 B | ✓ |
| link.html gzip | 570 B | 570 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 19.7s | 19.2s | -528ms |
| buildDurationCached | 7.2s | 7.2s | ⚠️ +22ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.51 kB | 8.51 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 393 B | 393 B | ✓ |
| Overall change | 393 B | 393 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | ✓ |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.34 MB | 1.34 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.39 MB | 1.39 MB | ✓ |
| withRouter.js | 1.39 MB | 1.39 MB | ✓ |
| Overall change | 6.9 MB | 6.9 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 13.1s | 13.3s | ⚠️ +270ms |
| buildDurationCached | 5.6s | 5.5s | -81ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.807 | 2.74 | -0.07 |
| / avg req/sec | 890.58 | 912.56 | +21.98 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.595 | 1.567 | -0.03 |
| /error-in-render avg req/sec | 1567.66 | 1595.41 | +27.75 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.36 kB | 9.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: abf7637ce2132886d54dcd4813c36d046cb4b995

File: packages/next/build/babel/plugins/react-loadable-plugin.ts (hunk 1 above)
Comment (travisbloom) [reply packages/next/build/babel/plugins/react-loadable-plugin.ts:159]: This same issue occurs when running next@10.2 with the latest storybook so I'm unsure if NODE_ENV will cover all the breaking cases :(

**Review by sokra — APPROVED** [review]
Seems like this problem happens when the babel config resp the next.js preset is used outside of next.js, so it doesn't really matter what the key is.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 14.3s | 14.9s | ⚠️ +665ms |
| buildDurationCached | 4.7s | 4.5s | -155ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.371 | 2.518 | ⚠️ +0.15 |
| / avg req/sec | 1054.28 | 992.95 | ⚠️ -61.33 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.432 | 1.45 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1745.98 | 1723.79 | ⚠️ -22.19 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| index.html gzip | 560 B | 560 B | ✓ |
| link.html gzip | 569 B | 569 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 18.1s | 17.9s | -199ms |
| buildDurationCached | 6.7s | 6.6s | -59ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | ✓ |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.35 MB | 1.35 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | -2 B |
| routerDirect.js | 1.39 MB | 1.39 MB | ✓ |
| withRouter.js | 1.39 MB | 1.39 MB | ✓ |
| Overall change | 6.9 MB | 6.9 MB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.2s | -80ms |
| buildDurationCached | 5.2s | 5s | -218ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +301 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.488 | 2.504 | ⚠️ +0.02 |
| / avg req/sec | 1004.86 | 998.24 | ⚠️ -6.62 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.463 | 1.589 | ⚠️ +0.13 |
| /error-in-render avg req/sec | 1708.73 | 1573.66 | ⚠️ -135.07 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.72 kB | 3.72 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.37 kB | 9.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/next-dynamic-plugin | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: 05578e40100f43839f5447ae0a0c729678cd2222
