### PR TITLE
Fix TypeScript error in with-mongodb example

### LINKED ISSUE #50084: Typescript error in the with-mongodb example
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.6.3
```

### Which example does this report relate to?

with-mongodb

### What browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

n/a

### Describe the Bug

When I try to build the with-mongodb example using `npm run build`, the build fails with this typescript error:

```
./pages/index.tsx:5:42
Type error: Parameter 'context' implicitly has an 'any' type.

  3 | import { InferGetServerSidePropsType } from 'next'
  4 |
> 5 | export async function getServerSideProps(context) {
    |                                          ^
  6 |   try {
  7 |     await clientPromise
  8 |     // `await clientPromise` will use the default database passed in the MONGODB_URI
```

### Expected Behavior

The example should build successfully.

### To Reproduce

The issue can be reproduced with these three commands:

```
npx create-next-app --example with-mongodb myapp
cd myapp
npm run build
```

### PR DESCRIPTION
**Pull request by ibrahemid**
- Resolves #50084

The context parameter in the getServerSideProps function lacked a type, which led to a compile-time error. To resolve this, the GetServerSidePropsContext type from next was used to properly type the context parameter. This ensures type safety and allows TypeScript to catch potential errors at compile time.

### CODE REVIEW

File: examples/with-mongodb/pages/index.tsx [hunk 1]
```diff
@@ -1,8 +1,8 @@
 import Head from 'next/head'
 import clientPromise from '../lib/mongodb'
-import { InferGetServerSidePropsType } from 'next'
+import { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next'
 
-export async function getServerSideProps(context) {
+export async function getServerSideProps(context: GetServerSidePropsContext) {
```
Comment (styfle) [inline examples/with-mongodb/pages/index.tsx:5]: How about using the same pattern from the docs here:

https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props

Comment (ibrahemid) [reply examples/with-mongodb/pages/index.tsx]: Sure, i made another commit following the same pattern. let me know your feedback.

File: examples/with-mongodb/pages/index.tsx [hunk 2]
```diff
@@ -1,8 +1,13 @@
 import Head from 'next/head'
 import clientPromise from '../lib/mongodb'
-import { InferGetServerSidePropsType } from 'next'
+import type { InferGetServerSidePropsType, GetServerSideProps } from 'next'
 
-export async function getServerSideProps(context) {
+
+type ConnectionStatus = {
+  isConnected: boolean;
```
Comment (styfle) [inline examples/with-mongodb/pages/index.tsx:7]:
```suggestion
  isConnected: boolean
```

**Review by styfle — DISMISSED** [review]

**Review by styfle — APPROVED** [review]
