### PR TITLE
Turbopack: Create junction points instead of symlinks on Windows

### LINKED ISSUE #69858: Standalone Output doesn't work with PNPM
### Link to the code that reproduces this issue

https://github.com/Charismara/nextjs-output-pnpm-issue

### To Reproduce

1. Create a new Project
2. Install dependencies with pnpm
3. Add `output: "standalone"` to your nextjs config file
4. Build Project with pnpm
5. --> Run into the following error:
``` 
Failed to copy traced files for C:\Users\****\IdeaProjects\pnpm-issue\.next\server\pages\_document.js Error: EPERM: operation not permitted, symlink 'C:\Users\****\IdeaProjects\pnpm-issue\node_modules\.pnpm\next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next' -> 'C:\Users\****\IdeaProjects\pnpm-issue\.next\standalone\node_modules\next'
```

### Current vs. Expected behavior

An error occurs which prevents the project from building.

The Project builds just fine without the output: `standalone` option set.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32548
  Available CPU cores: 32
Binaries:
  Node: 20.14.0
  npm: N/A
  Yarn: N/A
  pnpm: 9.7.0
Relevant Packages:
  next: 14.2.8 // Latest available version is detected (14.2.8).
  eslint-config-next: 14.2.8
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Output (export/standalone)

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bgw**
Next 16.1 changed Turbopack's external packaging to use symlinks.

Symlinks require elevated privileges on Windows if "Developer Mode" is not enabled. We can work around this by using junction points, which are mostly equivalent, but:

- They only work with directories.
- They can only point to absolute paths, not relative paths.

Fixes #87334
Fixes #87607
Fixes #87603
Fixes #87605
Fixes #87559
Fixes #87604
Fixes #87601
Fixes #87599
Fixes #87598
Fixes #87596
Fixes #87595
Fixes #87592
Fixes #87590
Fixes #87589
Fixes #87473
Fixes #87586
Fixes #87585
Fixes #87584
Fixes #87583
Fixes #87582
Fixes #87576
Fixes #87575
Fixes #87574
Fixes #87573
Fixes #87572
Fixes #87571
Fixes #87568
... and many more

Also:
Fixes #69858 (related issue about `output: 'standalone'` on Windows.

## Testing

- Disable Developer Mode on Windows, reboot, and then verify that symlink creation fails.
- Make a payload app with `pnpx create-payload-app` (just pick sqlite for the database when prompted), and then update the app with `pnpx @next/codemod upgrade 16.1.0`.
- Add `output: 'standalone'` to the `next.config.js`.
- Try running `pnpm build`

### CODE REVIEW

**Comment by bgw** [comment]
* **#87606** <a href="https://app.graphite.com/github/pr/vercel/next.js/87606?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/vercel/next.js/87606?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: turbopack/crates/turbo-tasks-fs/src/lib.rs [hunk 1]
```diff
@@ -1080,8 +1101,17 @@ impl FileSystem for DiskFileSystem {
...
             let is_equal = match (&*content, &old_content) {
+                // TODO(bgw): Is this logic correct? This might give us `is_equal = false` when it
+                // shouldn't, and cause us to do extra work.
+                // - `old_content` may have windows path separators, but `LinkContent` normalizes
+                //   them.
+                // - Windows junction points are always transformed to absolute before being stored.
+                // - `LinkContent`'s target field stores absolute paths as relative to the project
+                //   root, but `old_target` is relative to the real filesystem's root.
+                // We should compute the final target `Path` first, and then it with that value, not
+                // the normalized format stored in
```
Comment (sokra) [inline turbopack/crates/turbo-tasks-fs/src/lib.rs:1096]: Yes, sounds like your concerns are valid here.

File: turbopack/crates/turbo-tasks-fs/src/lib.rs [hunk 2]
```diff
@@ -2859,7 +2946,7 @@ mod tests {
             target: RcStr,
         ) -> anyhow::Result<()> {
             let write_file = |f| {
-                fs.write_link(
+                fs.write_symbolic_link_dir(
                     f,
                     LinkContent::Link {
                         target: format!("{target}/data.txt").into(),
```
Comment (sokra) [inline turbopack/crates/turbo-tasks-fs/src/lib.rs:2950]: That doesn't look like a directory

File: turbopack/crates/turbo-tasks-fs/src/lib.rs [hunk 3]
```diff
@@ -1042,9 +1054,18 @@ impl FileSystem for DiskFileSystem {
...
 
         let content = target.await?;
+        if let LinkContent::Link { link_type, .. } = &*content
+            && !link_type.contains(LinkType::DIRECTORY)
+        {
+            bail!(
+                "Only symbolic links to directories are supported, to ensure cross-platform \
+                 compatibility with Windows junction points"
+            )
+        }
```
Comment (sokra) [inline turbopack/crates/turbo-tasks-fs/src/lib.rs]: Only allowing directory links is a bit too restrictive. When using nft in build mode, we want to copy over existing symlinks, but that would fail here...

**Review by sokra — APPROVED** [review]

File: turbopack/crates/turbo-tasks-fs/src/lib.rs (hunk 1 above)
Comment (sokra) [reply turbopack/crates/turbo-tasks-fs/src/lib.rs:1096]: I'll make a follow-up PR for that
