### PR TITLE
Fix build type error of page params

### LINKED ISSUE #41884: Next 13: Missing Types for generateStaticParams
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
Binaries:
  Node: 16.18.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 7.13.4
Relevant packages:
  next: 13.0.0
  eslint-config-next: 13.0.0
  react: 18.2.0
  react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

A next 13 app with typescript and `generateStaticParams` can not be build. The following code works in dev mode, but fails on build:

```tsx
import { use } from "react";
import { fetchPeople, fetchPeoples } from "../../../lib/people";

type Params = {
  id: string;
};

type Props = {
  params: Params;
};

const People = ({ params }: Props) => {
  const people = use(fetchPeople(params.id));
  return (
    <>
      <h1>{people.name}</h1>
    </>
  );
};

export const generateStaticParams = async (): Promise<Params[]> => {
  const peoples = await fetchPeoples();

  const result = peoples.map((people) => ({
    id: people.id,
  }));

  return result;
}

export default People;
```

The build fails with the following error:

```
Type error: Page "app/people/[id]/page.tsx" does not match the required types of a Next.js Page.
  Invalid configuration:
    The exported page component isn't correctly typed.
        Expected "Props", got "PageProps".
          Invalid configuration:
            Expected "Params", got "PageParams | undefined".
              Expected "Params", got "undefined".
```

Sadly i was not able to find the mentioned types of the error.

Have a look at the following discussions for more informations:
* https://github.com/vercel/next.js/discussions/41826#discussioncomment-3966869
* https://github.com/vercel/next.js/discussions/41745#discussioncomment-3971314

### Expected Behavior

The example above can be build or the required types are exported.

### Link to reproduction

https://github.com/sdorra/next-13-missing-types

### To Reproduce

Run `pnpm build` in the example repository

### PR DESCRIPTION
**Pull request by shuding**
This PR temporarily fixes #41884 by loosing the type check rules. I will work on a follow up PR to type params better with tests.

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have a helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have a helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm build && pnpm lint`
- [ ] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

### CODE REVIEW

**Review by huozhi — DISMISSED** [review]

File: packages/next/build/webpack/plugins/flight-types-plugin.ts [hunk 1]
```diff
@@ -27,12 +27,12 @@ check<IEntry, TEntry>(entry)
 
 type PageParams = Record<string, string>
 interface PageProps {
-  params?: PageParams
-  searchParams?: Record<string, string | string[]>
+  params: any
+  searchParams: any
```
Comment (huozhi) [inline packages/next/build/webpack/plugins/flight-types-plugin.ts:31]: those props should still be optional?
```suggestion
  searchParams?: any
```

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f3b6ecd002aeddc4d3e0847619abb027e2812ad6

`pnpm testheadless test/unit/web-runtime/next-response.test.ts` 
-  > can be cloned

<details>
<summary>Expand output</summary>

  ● can be cloned

    TypeError: fetch failed

      at Object.processResponse (../evalmachine.<anonymous>:7941:27)
      at ../evalmachine.<anonymous>:8271:42

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: packages/next/build/webpack/plugins/flight-types-plugin.ts (hunk 1 above)
Comment (shuding) [reply packages/next/build/webpack/plugins/flight-types-plugin.ts]: No these shouldn't...
