### PR TITLE
Correctly fetch data for root route

### LINKED ISSUE #14923: Canary.29: Unexpected error in root path with optional catch all
# Bug report

## Describe the bug

Production build fails to render root path page when using optional catch all in canary.29 with fallback and empty static paths.

## To Reproduce

1. Install `next@9.4.5-canary.29`
2. Create page `pages/[[...slug]].js`
3. Add following code:
```javascript
const CatchAllPages = () => {
  return <div>Test</div>
}
export const getStaticPaths = async () => {
  return {
    paths: [],
    fallback: true,
  }
}
export const getStaticProps = async (ctx) => {
  return {
    props: {},
  }
}

export default CatchAllPages
```
4. Run `next build && next start`
5. Go to `http://localhost:3000/`
6. See error

## Expected behavior

It should render

## Screenshots

In Chrome & Firefox same error:
Screen Shot 2020-07-07 at 10 12 53 PM
In Safari, quite different error:
Screen Shot 2020-07-07 at 10 13 53 PM

## System information

- OS: MacOS; Vercel as well
- Version of Next.js: 9.4.5-canary.29
- Version of Node.js: v12.16.3
- Browsers: All

## Additional context

If it helps, adding a breakpoint in the bundle code shows that this fails here (prettyfied bundle slice of code):
```javascript
fetch(t, {
  credentials: "same-origin",
}).then(function (t) {
  if (!t.ok) {
    if (--n > 0 && t.status >= 500) return e();
    throw new Error("Failed to load static props");
  }
  return t.json();
});
```
Logging here `t` (argument passed to `fetch`) when root path `localhost:3000/`, displays `t` as an empty string while other routes (e.g: `/de/` & `/fr/`) display, for example:
```markdown
/_next/data/77xPdya_xyQSG_SoVaE0m/de.json
/_next/data/77xPdya_xyQSG_SoVaE0m/fr.json
```
Since `fetch('').then(t => t.json())` would get the homepage fallback html code `t.json()` would fail with error shown in screenshots.

### PR DESCRIPTION
**Pull request by Timer**
This PR corrects the data fetching behavior for optional root routes.

---

Fixes #14923

### CODE REVIEW

**Review by Janpot — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| buildDuration | 13.1s | 12.7s | -364ms |
| nodeModulesSize | 66.5 MB | 66.5 MB | ⚠️ +481 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.197 | 2.081 | -0.12 |
| / avg req/sec | 1138.12 | 1201.22 | +63.1 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.417 | 1.329 | -0.09 |
| /error-in-render avg req/sec | 1764.09 | 1881.53 | +117.44 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.72 kB | 6.72 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..cead.js gzip | 9.77 kB | 9.77 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.4 kB | 56.4 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.79 kB | 5.8 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.9 kB | 51.9 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| _buildManifest.js gzip | 267 B | 267 B | ✓ |
| _buildManife..dule.js gzip | 273 B | 273 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| index.html gzip | 955 B | 954 B | -1 B |
| link.html gzip | 962 B | 961 B | -1 B |
| withRouter.html gzip | 947 B | 946 B | -1 B |
| Overall change | 2.86 kB | 2.86 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1687,14 +1687,15 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
                     if (repeat && !Array.isArray(value)) value = [value];
                     return (
                       (optional || param in dynamicMatches) && // Interpolate group into data URL if present
-                      (interpolatedRoute = interpolatedRoute.replace(
-                        replaced,
-                        repeat
-                          ? value
-                              .map(_escapePathDelimiters["default"])
-                              .join("/")
-                          : (0, _escapePathDelimiters["default"])(value)
-                      ))
+                      (interpolatedRoute =
+                        interpolatedRoute.replace(
+                          replaced,
+                          repeat
+                            ? value
+                                .map(_escapePathDelimiters["default"])
+                                .join("/")
+                            : (0, _escapePathDelimiters["default"])(value)
+                        ) || "/")
                     );
                   })
                 ) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1301,12 +1301,13 @@
                 if (repeat && !Array.isArray(value)) value = [value];
                 return (
                   (optional || param in dynamicMatches) && // Interpolate group into data URL if present
-                  (interpolatedRoute = interpolatedRoute.replace(
-                    replaced,
-                    repeat
-                      ? value.map(_escapePathDelimiters.default).join("/")
-                      : (0, _escapePathDelimiters.default)(value)
-                  ))
+                  (interpolatedRoute =
+                    interpolatedRoute.replace(
+                      replaced,
+                      repeat
+                        ? value.map(_escapePathDelimiters.default).join("/")
+                        : (0, _escapePathDelimiters.default)(value)
+                    ) || "/")
                 );
               })
             ) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -6,7 +6,7 @@
     <meta name="next-head-count" content="2" />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-52742ec6c0d4de4de49f.module.js"
+      href="/_next/static/runtime/main-1fe0425f6363a9bb77b5.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -81,13 +81,13 @@
       src="/_next/static/runtime/polyfills-fa968511391ff096b874.js"
     ></script>
     <script
-      src="/_next/static/runtime/main-319a371e481bbb280956.js"
+      src="/_next/static/runtime/main-ab7d683543bf7f75b30e.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-52742ec6c0d4de4de49f.module.js"
+      src="/_next/static/runtime/main-1fe0425f6363a9bb77b5.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -6,7 +6,7 @@
     <meta name="next-head-count" content="2" />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-52742ec6c0d4de4de49f.module.js"
+      href="/_next/static/runtime/main-1fe0425f6363a9bb77b5.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -86,13 +86,13 @@
       src="/_next/static/runtime/polyfills-fa968511391ff096b874.js"
     ></script>
     <script
-      src="/_next/static/runtime/main-319a371e481bbb280956.js"
+      src="/_next/static/runtime/main-ab7d683543bf7f75b30e.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-52742ec6c0d4de4de49f.module.js"
+      src="/_next/static/runtime/main-1fe0425f6363a9bb77b5.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -6,7 +6,7 @@
     <meta name="next-head-count" content="2" />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-52742ec6c0d4de4de49f.module.js"
+      href="/_next/static/runtime/main-1fe0425f6363a9bb77b5.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -81,13 +81,13 @@
       src="/_next/static/runtime/polyfills-fa968511391ff096b874.js"
     ></script>
     <script
-      src="/_next/static/runtime/main-319a371e481bbb280956.js"
+      src="/_next/static/runtime/main-ab7d683543bf7f75b30e.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-52742ec6c0d4de4de49f.module.js"
+      src="/_next/static/runtime/main-1fe0425f6363a9bb77b5.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| buildDuration | 14.1s | 13.8s | -260ms |
| nodeModulesSize | 66.5 MB | 66.5 MB | ⚠️ +481 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.72 kB | 6.72 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..cead.js gzip | 9.77 kB | 9.77 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.4 kB | 56.4 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.79 kB | 5.8 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.9 kB | 51.9 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| _buildManifest.js gzip | 267 B | 267 B | ✓ |
| _buildManife..dule.js gzip | 273 B | 273 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| _error.js | 881 kB | 882 kB | ⚠️ +859 B |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 881 kB | 882 kB | ⚠️ +859 B |
| link.js | 923 kB | 924 kB | ⚠️ +859 B |
| routerDirect.js | 917 kB | 918 kB | ⚠️ +859 B |
| withRouter.js | 917 kB | 918 kB | ⚠️ +859 B |
| Overall change | 4.53 MB | 4.53 MB | ⚠️ +4.29 kB |

</details>

</details>
Commit: e002cd7a9b445c817e01b48a41a93226fac5f835

File: packages/next/client/page-loader.js [hunk 1]
```diff
@@ -155,12 +155,13 @@ export default class PageLoader {
...
-                ? value.map(escapePathDelimiters).join('/')
-                : escapePathDelimiters(value)
-            ))
+            (interpolatedRoute =
+              interpolatedRoute.replace(
+                replaced,
+                repeat
+                  ? value.map(escapePathDelimiters).join('/')
+                  : escapePathDelimiters(value)
+              ) || '/')
```
Comment (Janpot) [inline packages/next/client/page-loader.js:164]: @Timer Haven't investigated but it's kind of suspicious to me to have `|| '/'` here and not needing it [there](https://github.com/vercel/next.js/blob/cb96da13a0085577820855b71b7894ed607e6f1d/packages/next/build/utils.ts#L631) because most of the other logic around there is exactly the same, and I've fixed several issues before where the logic had drifted. (We should probably also look into whether it can share a bit more code)

Comment (Timer) [reply packages/next/client/page-loader.js:164]: In this specific case, what happens is when we do `interpolatedRoute.replace('replaced', ...)`, we replace `/[[...root]]` with nothing (because it's optional) which results in an empty string, thus the necessity to do `|| '/'`.

Comment (Timer) [reply packages/next/client/page-loader.js:164]: In the code you linked, we only replace `[[...root]]` and not `/[[...root]` (note the leading slash).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.9s | ⚠️ +142ms |
| nodeModulesSize | 66.5 MB | 66.5 MB | ⚠️ +481 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.019 | 2.095 | ⚠️ +0.08 |
| / avg req/sec | 1237.94 | 1193.05 | ⚠️ -44.89 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.238 | 1.327 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 2019.41 | 1884.44 | ⚠️ -134.97 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.72 kB | 6.72 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..cead.js gzip | 9.77 kB | 9.77 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.4 kB | 56.4 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.79 kB | 5.8 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.9 kB | 51.9 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| _buildManifest.js gzip | 267 B | 267 B | ✓ |
| _buildManife..dule.js gzip | 273 B | 273 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| index.html gzip | 955 B | 954 B | -1 B |
| link.html gzip | 962 B | 961 B | -1 B |
| withRouter.html gzip | 947 B | 946 B | -1 B |
| Overall change | 2.86 kB | 2.86 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1687,14 +1687,15 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
                     if (repeat && !Array.isArray(value)) value = [value];
                     return (
                       (optional || param in dynamicMatches) && // Interpolate group into data URL if present
-                      (interpolatedRoute = interpolatedRoute.replace(
-                        replaced,
-                        repeat
-                          ? value
-                              .map(_escapePathDelimiters["default"])
-                              .join("/")
-                          : (0, _escapePathDelimiters["default"])(value)
-                      ))
+                      (interpolatedRoute =
+                        interpolatedRoute.replace(
+                          replaced,
+                          repeat
+                            ? value
+                                .map(_escapePathDelimiters["default"])
+                                .join("/")
+                            : (0, _escapePathDelimiters["default"])(value)
+                        ) || "/")
                     );
                   })
                 ) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1301,12 +1301,13 @@
                 if (repeat && !Array.isArray(value)) value = [value];
                 return (
                   (optional || param in dynamicMatches) && // Interpolate group into data URL if present
-                  (interpolatedRoute = interpolatedRoute.replace(
-                    replaced,
-                    repeat
-                      ? value.map(_escapePathDelimiters.default).join("/")
-                      : (0, _escapePathDelimiters.default)(value)
-                  ))
+                  (interpolatedRoute =
+                    interpolatedRoute.replace(
+                      replaced,
+                      repeat
+                        ? value.map(_escapePathDelimiters.default).join("/")
+                        : (0, _escapePathDelimiters.default)(value)
+                    ) || "/")
                 );
               })
             ) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -6,7 +6,7 @@
     <meta name="next-head-count" content="2" />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-52742ec6c0d4de4de49f.module.js"
+      href="/_next/static/runtime/main-1fe0425f6363a9bb77b5.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -81,13 +81,13 @@
       src="/_next/static/runtime/polyfills-fa968511391ff096b874.js"
     ></script>
     <script
-      src="/_next/static/runtime/main-319a371e481bbb280956.js"
+      src="/_next/static/runtime/main-ab7d683543bf7f75b30e.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-52742ec6c0d4de4de49f.module.js"
+      src="/_next/static/runtime/main-1fe0425f6363a9bb77b5.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -6,7 +6,7 @@
     <meta name="next-head-count" content="2" />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-52742ec6c0d4de4de49f.module.js"
+      href="/_next/static/runtime/main-1fe0425f6363a9bb77b5.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -86,13 +86,13 @@
       src="/_next/static/runtime/polyfills-fa968511391ff096b874.js"
     ></script>
     <script
-      src="/_next/static/runtime/main-319a371e481bbb280956.js"
+      src="/_next/static/runtime/main-ab7d683543bf7f75b30e.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-52742ec6c0d4de4de49f.module.js"
+      src="/_next/static/runtime/main-1fe0425f6363a9bb77b5.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -6,7 +6,7 @@
     <meta name="next-head-count" content="2" />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-52742ec6c0d4de4de49f.module.js"
+      href="/_next/static/runtime/main-1fe0425f6363a9bb77b5.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -81,13 +81,13 @@
       src="/_next/static/runtime/polyfills-fa968511391ff096b874.js"
     ></script>
     <script
-      src="/_next/static/runtime/main-319a371e481bbb280956.js"
+      src="/_next/static/runtime/main-ab7d683543bf7f75b30e.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-52742ec6c0d4de4de49f.module.js"
+      src="/_next/static/runtime/main-1fe0425f6363a9bb77b5.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.7s | -118ms |
| nodeModulesSize | 66.5 MB | 66.5 MB | ⚠️ +481 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.72 kB | 6.72 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..cead.js gzip | 9.77 kB | 9.77 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.4 kB | 56.4 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.79 kB | 5.8 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.9 kB | 51.9 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| _buildManifest.js gzip | 267 B | 267 B | ✓ |
| _buildManife..dule.js gzip | 273 B | 273 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/fix-data-fetch | Change |
| - | - | - | - |
| _error.js | 881 kB | 882 kB | ⚠️ +859 B |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 881 kB | 882 kB | ⚠️ +859 B |
| link.js | 923 kB | 924 kB | ⚠️ +859 B |
| routerDirect.js | 917 kB | 918 kB | ⚠️ +859 B |
| withRouter.js | 917 kB | 918 kB | ⚠️ +859 B |
| Overall change | 4.53 MB | 4.53 MB | ⚠️ +4.29 kB |

</details>

</details>
Commit: ae90770753b1562f980266d11be433ba6efdd5ed

**Review by ijjk — APPROVED** [review]
