### PR TITLE
Don't add locale to client side redirects from data fetching

### LINKED ISSUE #36169: redirection to default locale doesn't work from getStaticProps(fallback) when we're in another locale currently
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Other platform

### Describe the Bug

let's say you entered /es/xyz/[slug] on chrome and since this page wasn't statically generated before, getStaticProps runs and since there is not Spanish content for this page, I want to redirect the user to /xyz/[slug]. but the below doesn't work.

```
 return {
      redirect: {
        destination: '/xyz/abc',
        permanent: false,
      },
    };
```

I even tried doing 
```
 return {
      redirect: {
        destination: '/en/xyz/abc',
        permanent: false,
      },
    };
```

but that doesn't work either.

So my question is how to change the current locale to the default one inside of getStaticProps?

### Expected Behavior

redirects to default locale inside of getStaticProps when you're in a different locale currently should happen.

### To Reproduce

I think whatever I wrote above kinda explains it. Thanks a lot!

### PR DESCRIPTION
**Pull request by hanneslund**
## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

Fixes #36169

### CODE REVIEW

File: test/e2e/i18n-data-fetching-redirect/app/pages/gsp-fallback-redirect/[param].js [hunk 1]
```diff
@@ -0,0 +1,16 @@
+export async function getStaticProps() {
+  return {
+    redirect: {
+      destination: '/en/home',
```
Comment (ijjk) [inline test/e2e/i18n-data-fetching-redirect/app/pages/gsp-fallback-redirect/[param].js:4]:
```suggestion
export async function getStaticProps({ locale }) {
  return {
    redirect: {
      destination: `/${locale}/home`,
```
Can we add a test case that ensures the locale passed down matches what we expect and it redirects correctly and then another test case that ensures redirecting from defaultLocale `en` -> `sv` works alright?

File: test/e2e/i18n-data-fetching-redirect/index.test.ts [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+  })
+  afterAll(() => next.destroy())
+
+  describe('Redirect to another locale', () => {
+    test.each([
+      ['getServerSideProps', '/sv/gssp-redirect'],
+      ['getStaticProps blocking', '/sv/gsp-blocking-redirect/1'],
+      ['getStaticProps fallback', '/sv/gsp-fallback-redirect/1'],
+    ])('%s', async (_, path) => {
+      const browser = await webdriver(next.url, path)
```
Comment (ijjk) [inline test/e2e/i18n-data-fetching-redirect/index.test.ts:27]: Can we also test client-side transitions with `next/link` and ensure a full navigation doesn't occur?

**Review by ijjk — APPROVED** [review]
Change and added tests look good, thanks!
