### PR TITLE
[middleware] avoid fetching a chunk for api endpoints on middleware redirect

### LINKED ISSUE #37783: [NEXT-835] Next.js attempts to fetch API route proxy as regular page
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.40
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

When proxying a page using an API route, Next.js will attempt to request the page's JavaScript at the rewrite destination instead of the source page. For example, with the following rewrite setup, a request to `http://localhost:3000?proxy=true` will return the correct HTML but then Next.js will send a request to `http://localhost:3000/_next/static/chunks/pages/api/proxy.js`. That request will 404, resulting in a full page reload, which then results in the same behavior, again and again in an infinite loop.

```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async rewrites() {
    return {
      beforeFiles: [
        {
          source: '/:path(.*)',
          has: [{ type: 'query', key: 'proxy', value: 'true' }],
          destination: '/api/proxy?path=:path',
        },
      ],
    }
  },
}

module.exports = nextConfig
```

### Expected Behavior

The expected behavior is for Next.js to request the page's JS and not to use the rewrite source to determine the URL.

### Link to reproduction

https://github.com/migueloller/next-proxy-rewrite-bug

### To Reproduce

```bash
git clone https://github.com/migueloller/next-proxy-rewrite-bug
cd next-proxy-rewrite-bug
yarn install
yarn dev
open http://localhost:3000?proxy=true
```

<sub>[NEXT-835](https://linear.app/vercel/issue/NEXT-835/nextjs-attempts-to-fetch-api-route-proxy-as-regular-page)</sub>

### LINKED ISSUE #37944: [middleware] Redirecting to an API route leads to trying fetching a static chunk for it
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.18
      pnpm: 7.3.0
    Relevant packages:
      next: 12.1.7-canary.45
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

-

### How are you deploying your application? (if relevant)

-

### Describe the Bug

When a Middleware redirects to an API route on a client navigation, the router tries to download its static chunk (which does not exist), and therefore we get a 404 network request & an error in the log.

The following test contains these errors in the log: https://github.com/vercel/next.js/blob/b0533635ab318ab88350033fa6a8571b0f5a5434/test/e2e/middleware-redirects/test/index.test.ts#L145-L150

that say:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
Error: Failed to lookup route: /api/ok
  at http://localhost:52023/_next/static/chunks/main-bd08724fa7c4e7ed.js:1:3522
```

### Expected Behavior

Redirecting into an API route shouldn't trigger fetching a missing static chunk

### Link to reproduction

pnpx next test/e2e/middleware-redirects/app

### To Reproduce

* Open the browser (http://localhost:3000)
* Open the dev tools (alt+cmd+i, or F12) and move to the Network tab (to capture the network)
* Click on "Redirect me to api with locale"
* witness the error in the Network tab & in the console

### PR DESCRIPTION
**Pull request by Schniz**
avoid fetching a chunk for api endpoints on middleware redirect.
This still makes a request to the data endpoint, not sure if this is a good idea,
but a rewrite _can_ happen from that data request.

## Related

- Fixes #37944
- Fixes https://github.com/vercel/next.js/issues/37783

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm lint`
- [ ] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

### CODE REVIEW

File: packages/next/server/base-server.ts [hunk 1]
```diff
@@ -779,7 +779,7 @@ export default abstract class Server<ServerOptions extends Options = Options> {
             _parsedUrl.query.__nextDefaultLocale =
               defaultLocale || this.nextConfig.i18n.defaultLocale
 
-            if (!detectedLocale) {
+            if (!detectedLocale && !pathname.startsWith('/api/')) {
```
Comment (ijjk) [inline packages/next/server/base-server.ts:782]:
```suggestion
            if (!detectedLocale && !(pathname === '/api' || pathname.startsWith('/api/'))) {
```

File: packages/next/shared/lib/router/router.ts [hunk 2]
```diff
@@ -1710,6 +1710,11 @@ export default class Router implements BaseRouter {
             : undefined
       }
 
+      if (route.startsWith('/api/')) {
```
Comment (ijjk) [inline packages/next/shared/lib/router/router.ts:1713]:
```suggestion
      if (route === '/api' || route.startsWith('/api/')) {
```

**Review by ijjk — APPROVED** [review]
Thanks!
