### PR TITLE
Polyfill missing std lib fns for module browsers

### LINKED ISSUE #11173: Microsoft Edge 16-18 missing "flat" polyfill
# Bug report

## Describe the bug

When loading out Next site with Edge 18, there is a critical `TypeError` stating `Object doesn't support property or method 'flat'`

## To Reproduce

1. Go to https://epdev123.org/wiki/lang_en/magnus-dunn in Edge 18
2. Notice the full-screen critical error

* View our public sentry issue here: https://sentry.io/share/issue/cc2dd3b7d40b44a4ae69806e81a63c46/

## Expected behavior

This page should load properly like all other browsers were able to 

## Screenshots

image

## System information

- OS: Windows
- Browser: Edge 18, Edge 17, Edge 16 (see [Sentry Issue](https://sentry.io/share/issue/cc2dd3b7d40b44a4ae69806e81a63c46/) for browser breakdown)
- Version of Next.js: 9.3.1

## Additional context

This issue may relate to the recent changes in Next's polyfilling partially described in https://github.com/zeit/next.js/issues/7993

* I looked into adding this flat polyfill manually, but it's [already included in `next-polyfill-nomodule`](https://github.com/zeit/next.js/blob/canary/packages/next-polyfill-nomodule/src/index.js) as `import 'core-js/features/array/flat'`

* We have zero polyfilling in our application currently, we're fully relying on Next's included polyfills. We have not changed the included version of `core-js`

* This is a private project, we can email a zip to anyone at Zeit, just let me know if this looks like a valid bug to you all

### PR DESCRIPTION
**Pull request by Timer**
This pull request creates a new `@next/polyfill-module` that fills in the missing gaps between various `nomodule` browsers.

It supports:

- `String#trimStart` / `String#trimEnd`
- `Symbol#description`
- `Array#flat` / `Array#flatMap`
- `Promise#finally` (**previously polyfilled, now relocated**)

---

Fixes #11173

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 19d13965f27285d435c4c63fffaae0158dcd61f3

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 0
    Received:    0.20000000000000284

       96 | 
       97 |       // should be no bigger than 60.2 kb
    >  98 |       expect(parseFloat(indexFirstLoad) - 60.5).toBeLessThanOrEqual(0)
          |                                                 ^
       99 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      100 | 
      101 |       expect(parseFloat(err404Size) - 3.5).toBeLessThanOrEqual(0)

      at Object.<anonymous> (integration/build-output/test/index.test.js:98:49)

</details>

**Review by ijjk — APPROVED** [review]

File: packages/next-polyfill-module/src/index.js [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+ *
+ * https://caniuse.com/mdn-javascript_builtins_symbol_description
+ */
+if (!('description' in Symbol.prototype)) {
+  Object.defineProperty(Symbol.prototype, 'description', {
+    get: function get() {
+      return /\((.+)\)/.exec(this)[1]
+    },
+  })
+}
```
Comment (minhtule) [inline packages/next-polyfill-module/src/index.js:38]: @ijjk This polyfill doesn't work properly on Edge 44 (https://github.com/vercel/next.js/issues/18213) and Safari 11 (https://github.com/vercel/next.js/issues/17825). We can't upgrade to 9.5.4 to fix the security alert and also 10.0 today... Does Next.js need this polyfill internally? If not, could we remove it for now?

Comment (Timer) [reply packages/next-polyfill-module/src/index.js:38]: Can you send a PR to fix it?

Comment (minhtule) [reply packages/next-polyfill-module/src/index.js:38]: Yes, I can open a PR to fix the issue on Edge 44 with a small change
```js
Object.defineProperty(Symbol.prototype, 'description', {
  get: function get() {
    const result = /\((.+)\)/.exec(this)[1];
    return result ? result[1] : undefined;
  },
})
```
However, this still doesn't handle the other issue with Safari 11 (https://github.com/vercel/next.js/issues/17825). Core-js [`es.symbol.description`](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.symbol.description.js) polyfill seems to be more complete (handling all browser) but I'm not sure if we want to bring all that code into Next.js. I would suggest that we remove this problematic polyfill from Next.js. Whoever needs it can polyfill it manually.

@Timer WDYT?

Comment (developit) [reply packages/next-polyfill-module/src/index.js:38]: Core-js does not polyfill symbol.description, it polyfills Symbols themselves (in their entirety). This works:

```js
if (!('description' in Symbol.prototype)) {
  Object.defineProperty(Symbol.prototype, 'description', {
    get: function get() {
      return /\((.+)\)/.exec(this.toString())[1]
    },
  })
}
```
