### PR TITLE
fix(turbopack): Stop analyzer if IIFE is recursive

### LINKED ISSUE #74190: In Next.js 15 with Turbopack mode, the IIFE is not executing as expected, resulting in a strange bug.
### Link to the code that reproduces this issue

https://github.com/listen936/nextjs_15_turbopack_bug_demo

### To Reproduce

1. npm install
2. npm run dev

### Current vs. Expected behavior

``` js
(function _(namespace, path) {
  // The expected output is "", "wrapper", "wrapper.data", "wrapper.data.key"
  // The actual output is "", "wrapper", "data", "key"
  console.debug("####", path)

  for (var i = 0, keys = Object.keys(namespace); i < keys.length; i++) {
    var key = keys[i];
    // --------------------------------------------------------------------------
    console.debug("####", path ? true : false) // always true? why?
    // --------------------------------------------------------------------------
    parent[key] = _(namespace[key], path ? `${path}.${key}` : key, parent[key] || {});
    // --- If the line below is replaced, it will meet the expectations.
    // parent[key] = _(namespace[key], Boolean(path) ? `${path}.${key}` : key, parent[key] || {});
  }
  return parent;
})({
  wrapper: {
    data: {
      key: {}
    },
  }
}, '');
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:27 PDT 2024; root:xnu-11215.41.3~2/RELEASE_X86_64
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 18.20.1
  npm: 8.19.4
  Yarn: 1.22.10
  pnpm: 8.14.1
Relevant Packages:
  next: 15.1.2 // Latest available version is detected (15.1.2).
  eslint-config-next: 15.1.1
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kdy1**
### What?

Add a check for recursive IIFE.

### Why?

Turbopack miscompiles recursive IIFEs because it does not check if IIFE recurses.

### How?

Closes https://github.com/vercel/next.js/issues/74190

Closes PACK-3694

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-74190 | Change |
| - | - | - | - |
| buildDuration | 29.1s | 26.4s | N/A |
| buildDurationCached | 25.7s | 21s | N/A |
| nodeModulesSize | 417 MB | 417 MB | ✓ |
| nextStartRea..uration (ms) | 851ms | 778ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-74190 | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 52.6 kB | 52.6 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.44 kB | 5.44 kB | N/A |
| bccd1874-HASH.js gzip | 53 kB | 53 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 232 B | 235 B | N/A |
| main-HASH.js gzip | 34.1 kB | 34.1 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-74190 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-74190 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.57 kB | 4.57 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-74190 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 747 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-74190 | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 539 B | 538 B | N/A |
| withRouter.html gzip | 520 B | 521 B | N/A |
| Overall change | 524 B | 524 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-74190 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 206 kB | 206 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-74190 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 670 B | 668 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.2 kB | 31.2 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-74190 | Change |
| - | - | - | - |
| 274-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 274.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 364 kB | 364 kB | ✓ |
| app-page-exp..prod.js gzip | 129 kB | 129 kB | ✓ |
| app-page-tur..prod.js gzip | 142 kB | 142 kB | ✓ |
| app-page-tur..prod.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run...dev.js gzip | 352 kB | 352 kB | ✓ |
| app-page.run..prod.js gzip | 125 kB | 125 kB | ✓ |
| app-route-ex...dev.js gzip | 37.5 kB | 37.5 kB | ✓ |
| app-route-ex..prod.js gzip | 25.6 kB | 25.6 kB | ✓ |
| app-route-tu..prod.js gzip | 25.6 kB | 25.6 kB | ✓ |
| app-route-tu..prod.js gzip | 25.4 kB | 25.4 kB | ✓ |
| app-route.ru...dev.js gzip | 39.2 kB | 39.2 kB | ✓ |
| app-route.ru..prod.js gzip | 25.4 kB | 25.4 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.69 kB | 9.69 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.6 kB | 11.6 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.68 kB | 9.68 kB | ✓ |
| pages-turbo...prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| pages.runtim...dev.js gzip | 27.5 kB | 27.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| server.runti..prod.js gzip | 916 kB | 916 kB | ✓ |
| Overall change | 2.45 MB | 2.45 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-74190 | Change |
| - | - | - | - |
| 0.pack gzip | 2.08 MB | 2.09 MB | ⚠️ +4.77 kB |
| index.pack gzip | 74 kB | 74 kB | N/A |
| Overall change | 2.08 MB | 2.09 MB | ⚠️ +4.77 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: e14447b4c6170d535158aafaf3267847cf15b97a

**Comment by ijjk** [comment]
## Failing test suites 
Commit: e14447b4c6170d535158aafaf3267847cf15b97a

`pnpm test-start test/production/app-dir/worker-restart/worker-restart.test.ts`
- worker-restart > should properly exhaust all restart attempts and not fail with any worker errors

<details>
<summary>Expand output</summary>

  ● worker-restart › should properly exhaust all restart attempts and not fail with any worker errors

    thrown: "Exceeded timeout of 60000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      2 |
      3 | describe('worker-restart', () => {
    > 4 |   it('should properly exhaust all restart attempts and not fail with any worker errors', async () => {
        |   ^
      5 |     const { stdout, stderr } = await nextBuild(
      6 |       __dirname + '/fixtures/timeout',
      7 |       [],

      at it (production/app-dir/worker-restart/worker-restart.test.ts:4:3)
      at Object.describe (production/app-dir/worker-restart/worker-restart.test.ts:3:1)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: turbopack/crates/turbopack-tests/tests/snapshot/next-issues/74190/input/index.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+var root = {};
```
Comment (mischnic) [inline turbopack/crates/turbopack-tests/tests/snapshot/next-issues/74190/input/index.js:1]: Could this be an execution test instead?

File: turbopack/crates/turbopack-ecmascript/tests/analyzer/graph/iife-2/input.js [hunk 2]
```diff
@@ -0,0 +1,15 @@
+var root = {};
```
Comment (mischnic) [inline turbopack/crates/turbopack-ecmascript/tests/analyzer/graph/iife-2/input.js:1]: Can you make this test case smaller? The snapshots can easily change and are hard to check for correctness if there are so many statements

File: turbopack/crates/turbopack-tests/tests/snapshot/next-issues/74190/input/index.js (hunk 1 above)
Comment (kdy1) [reply turbopack/crates/turbopack-tests/tests/snapshot/next-issues/74190/input/index.js]: I converted this into an execution test

**Review by mischnic — APPROVED** [review]
