### PR TITLE
fix(turbopack): Use correct `SyntaxContext` for `__turbopack_esm__`

### LINKED ISSUE #72232: ReferenceError: e is not defined error occurs when running next dev --turbo
### Link to the code that reproduces this issue

https://github.com/y-hsgw/with-urql

### To Reproduce

When using` next dev --turbo` with a Next.js application, the following error message appears:
```sh
ReferenceError: e is not defined
    at Module.Kind (/path/to/.next/server/chunks/ssr/node_modules_xyz.js:1376:18)
    at Kind (turbopack://[project]/node_modules/@urql/core/src/gql.ts:84:30)
    ...
```

The application works without issues when running the `next dev` command.

### Current vs. Expected behavior

bug screenshot: 

スクリーンショット 2024-11-03 12 36 54

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:26 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8103
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 22.10.0
  npm: 10.9.0
  Yarn: 4.5.1
  pnpm: N/A
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I also submitted an issue to urql, but they responded that it was an issue on the Next.js side.

https://github.com/urql-graphql/urql/issues/3704

### LINKED ISSUE #73383: Bug: Mangling of Constants Causing Runtime Errors in GraphQL-based Packages with Turbopack
### Link to the code that reproduces this issue

https://github.com/0no-co/graphql.web/pull/43

### To Reproduce

1. Install and configure Next.js 15 with Turbopack and a GraphQL-based package (e.g., `gql.tada`).
2. Start the application using Turbopack in development mode.
3. Encounter runtime errors where exported constants (e.g., `Kind`) are incorrectly referenced (e.g., as `e` instead of `e1`).

### Current vs. Expected behavior

**Current behavior**: Some exported constants in `graphql.web`, such as `Kind` as `e`, are incorrectly referenced during the bundling process in Turbopack, leading to references like `e` instead of the intended `e1`. This causes runtime errors because the application expects the correct constant name (e.g., `e1` for `Kind`), but Turbopack provides an incorrect reference.

**Expected behavior**: The exported constants should be preserved with their correct names during bundling. For example, `Kind` should not be mangled to `e` or any other incorrect name, and it should maintain its correct reference throughout the build and runtime.

Example Code:
https://github.com/0no-co/graphql.web/pull/43

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.5.0
  npm: 9.8.0
  Yarn: N/A
  pnpm: 9.7.1
Relevant Packages:
  next: 15.0.3 // Latest available version is detected (15.0.3).
  react: 19.0.0-rc-66855b96-20241106
  react-dom: 19.0.0-rc-66855b96-20241106
  gql.tada: 1.8.10
  graphql: 16.9.0
  urql: 4.2.1
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kdy1**
### Why?

For description about the `resolver`/`hygiene` system, please see https://rustdoc.swc.rs/swc_core/ecma/transforms/base/fn.resolver.html

### How?

 - Closes https://github.com/vercel/next.js/issues/72232
 - Closes PACK-3372

<br>

 - Closes https://github.com/vercel/next.js/issues/73383
 - Closes PACK-3586

### CODE REVIEW

**Comment by Iamknownasfesal** [comment]
when is this gonna get merged

This is a huge bug where we cannot even use graphql anymore

**Comment by arielweinberger** [comment]
Please, any news?

**Comment by KyBerry** [comment]
@arielweinberger 
> Please, any news? To not implement ESM standards correctly with Turbopack and essentially block users from using various GraphQL packages with over 500k weekly downloads isn't cool.

@Iamknownasfesal 
> when is this gonna get merged
> 
> This is a huge bug where we cannot even use graphql anymore

I'm not sure if you have a strict need to use turbopack, but removing `--turbopack` from the dev script so you just have `"dev": "next dev"` worked for me  🤷‍♂️

**Comment by Iamknownasfesal** [comment]
> @arielweinberger
> 
> > Please, any news? To not implement ESM standards correctly with Turbopack and essentially block users from using various GraphQL packages with over 500k weekly downloads isn't cool.
> 
> @Iamknownasfesal
> 
> > when is this gonna get merged
> > This is a huge bug where we cannot even use graphql anymore
> 
> I'm not sure if you have a strict need to use turbopack, but removing `--turbopack` from the dev script so you just have `"dev": "next dev"` worked for me 🤷‍♂️

yea but any new nextjs developer will try to use turbopack, and look what they will see after they use qpl

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 2bdd050ba668ae6794beba5c4772632e889a12ba

`pnpm test test/integration/bigint/test/index.test.js` (turbopack)
- bigint API route support > production mode > should return 200
- bigint API route support > production mode > should return the BigInt result text

<details>
<summary>Expand output</summary>

  ● bigint API route support › production mode › should return 200

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       No config file found
       No config file found
       ▲ Next.js 15.2.0-canary.40 (Turbopack)

       Checking validity of types ...
       Creating an optimized production build ...
       No config file found
       No config file found
       Building (0/2) ...
    FATAL: An unexpected Turbopack error occurred:
    Panic: panicked at turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:540:29:
    Failed to find export context for hoist
    Backtrace:    0: next_swc_napi::init::{closure#0}
       1: std::panicking::rust_panic_with_hook
       2: std::panicking::begin_panic_handler::{{closure}}
       3: std::sys::backtrace::__rust_end_short_backtrace
       4: rust_begin_unwind
       5: core::panicking::panic_fmt
       6: <turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline::{closure#0}
       7: <<turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline as turbo_tasks::task::function::TaskFnInputFunctionWithThis<turbo_tasks::task::function::AsyncFunctionMode, turbopack_ecmascript::references::esm::export::EsmExports, (turbo_tasks::vc::Vc<turbopack_core::module_graph::ModuleGraph>, turbo_tasks::vc::Vc<alloc::boxed::Box<dyn turbopack_core::chunk::chunking_context::ChunkingContext>>)>>::functor::{closure#0}
       8: <turbo_tasks::capture_future::CaptureFuture<core::result::Result<core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>, futures_util::future::future::catch_unwind::CatchUnwind<core::panic::unwind_safe::AssertUnwindSafe<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>> + core::marker::Send>>>>> as core::future::future::Future>::poll
       9: <tracing::instrument::Instrumented<<turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}::{closure#0}> as core::future::future::Future>::poll
      10: <tokio::task::task_local::LocalKey<turbo_tasks::manager::CurrentLocalTaskState>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      11: <tokio::task::task_local::LocalKey<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>, tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}>> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      12: <tokio::task::task_local::LocalKey<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>>>
      13: <tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>> as core::future::future::Future>::poll
      14: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread_alt::handle::Handle>>>::poll
      15: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
      16: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll_inner
      17: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
      18: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task
      19: <tokio::runtime::scheduler::multi_thread::worker::Context>::run
      20: <tokio::runtime::context::scoped::Scoped<tokio::runtime::scheduler::Context>>::set::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure#0}, ()>
      21: tokio::runtime::context::runtime::enter_runtime::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}, ()>
      22: tokio::runtime::scheduler::multi_thread::worker::run
      23: <tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}> as core::future::future::Future>::poll
      24: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
      25: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      26: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
      27: tokio::runtime::task::raw::poll::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      28: <tokio::runtime::blocking::pool::Inner>::run
      29: std::sys::backtrace::__rust_begin_short_backtrace::<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>
      30: <<std::thread::Builder>::spawn_unchecked_<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
      31: std::sys::pal::unix::thread::Thread::new::thread_start
      32: <unknown>
      33: <unknown>

    FATAL: An unexpected Turbopack error occurred:
    Panic: panicked at turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:540:29:
    Failed to find export context for __TURBOPACK__default__export__
    Backtrace:    0: next_swc_napi::init::{closure#0}
       1: std::panicking::rust_panic_with_hook
       2: std::panicking::begin_panic_handler::{{closure}}
       3: std::sys::backtrace::__rust_end_short_backtrace
       4: rust_begin_unwind
       5: core::panicking::panic_fmt
       6: <turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline::{closure#0}
       7: <<turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline as turbo_tasks::task::function::TaskFnInputFunctionWithThis<turbo_tasks::task::function::AsyncFunctionMode, turbopack_ecmascript::references::esm::export::EsmExports, (turbo_tasks::vc::Vc<turbopack_core::module_graph::ModuleGraph>, turbo_tasks::vc::Vc<alloc::boxed::Box<dyn turbopack_core::chunk::chunking_context::ChunkingContext>>)>>::functor::{closure#0}
       8: <turbo_tasks::capture_future::CaptureFuture<core::result::Result<core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>, futures_util::future::future::catch_unwind::CatchUnwind<core::panic::unwind_safe::AssertUnwindSafe<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>> + core::marker::Send>>>>> as core::future::future::Future>::poll
       9: <tracing::instrument::Instrumented<<turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}::{closure#0}> as core::future::future::Future>::poll
      10: <tokio::task::task_local::LocalKey<turbo_tasks::manager::CurrentLocalTaskState>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      11: <tokio::task::task_local::LocalKey<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>, tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}>> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      12: <tokio::task::task_local::LocalKey<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>>>
      13: <tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>> as core::future::future::Future>::poll
      14: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread_alt::handle::Handle>>>::poll
      15: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
      16: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll_inner
      17: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
      18: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task
      19: <tokio::runtime::scheduler::multi_thread::worker::Context>::run
      20: <tokio::runtime::context::scoped::Scoped<tokio::runtime::scheduler::Context>>::set::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure#0}, ()>
      21: tokio::runtime::context::runtime::enter_runtime::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}, ()>
      22: tokio::runtime::scheduler::multi_thread::worker::run
      23: <tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}> as core::future::future::Future>::poll
      24: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
      25: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      26: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
      27: tokio::runtime::task::raw::poll::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      28: <tokio::runtime::blocking::pool::Inner>::run
      29: std::sys::backtrace::__rust_begin_short_backtrace::<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>
      30: <<std::thread::Builder>::spawn_unchecked_<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
      31: std::sys::pal::unix::thread::Thread::new::thread_start
      32: <unknown>
      33: <unknown>

    FATAL: An unexpected Turbopack error occurred:
    Panic: panicked at turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:540:29:
    Failed to find export context for config
    Backtrace:    0: next_swc_napi::init::{closure#0}
       1: std::panicking::rust_panic_with_hook
       2: std::panicking::begin_panic_handler::{{closure}}
       3: std::sys::backtrace::__rust_end_short_backtrace
       4: rust_begin_unwind
       5: core::panicking::panic_fmt
       6: <turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline::{closure#0}
       7: <<turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline as turbo_tasks::task::function::TaskFnInputFunctionWithThis<turbo_tasks::task::function::AsyncFunctionMode, turbopack_ecmascript::references::esm::export::EsmExports, (turbo_tasks::vc::Vc<turbopack_core::module_graph::ModuleGraph>, turbo_tasks::vc::Vc<alloc::boxed::Box<dyn turbopack_core::chunk::chunking_context::ChunkingContext>>)>>::functor::{closure#0}
       8: <turbo_tasks::capture_future::CaptureFuture<core::result::Result<core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>, futures_util::future::future::catch_unwind::CatchUnwind<core::panic::unwind_safe::AssertUnwindSafe<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>> + core::marker::Send>>>>> as core::future::future::Future>::poll
       9: <tracing::instrument::Instrumented<<turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}::{closure#0}> as core::future::future::Future>::poll
      10: <tokio::task::task_local::LocalKey<turbo_tasks::manager::CurrentLocalTaskState>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      11: <tokio::task::task_local::LocalKey<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>, tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}>> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      12: <tokio::task::task_local::LocalKey<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>>>
      13: <tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>> as core::future::future::Future>::poll
      14: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread_alt::handle::Handle>>>::poll
      15: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
      16: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll_inner
      17: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
      18: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task
      19: <tokio::runtime::scheduler::multi_thread::worker::Context>::run
      20: <tokio::runtime::context::scoped::Scoped<tokio::runtime::scheduler::Context>>::set::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure#0}, ()>
      21: tokio::runtime::context::runtime::enter_runtime::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}, ()>
      22: tokio::runtime::scheduler::multi_thread::worker::run
      23: <tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}> as core::future::future::Future>::poll
      24: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
      25: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      26: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
      27: tokio::runtime::task::raw::poll::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      28: <tokio::runtime::blocking::pool::Inner>::run
      29: std::sys::backtrace::__rust_begin_short_backtrace::<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>
      30: <<std::thread::Builder>::spawn_unchecked_<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
      31: std::sys::pal::unix::thread::Thread::new::thread_start
      32: <unknown>
      33: <unknown>

    FATAL: An unexpected Turbopack error occurred:
    Panic: panicked at turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:540:29:
    Failed to find export context for RouteKind
    Backtrace:    0: next_swc_napi::init::{closure#0}
       1: std::panicking::rust_panic_with_hook
       2: std::panicking::begin_panic_handler::{{closure}}
       3: std::sys::backtrace::__rust_end_short_backtrace
       4: rust_begin_unwind
       5: core::panicking::panic_fmt
       6: <turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline::{closure#0}
       7: <<turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline as turbo_tasks::task::function::TaskFnInputFunctionWithThis<turbo_tasks::task::function::AsyncFunctionMode, turbopack_ecmascript::references::esm::export::EsmExports, (turbo_tasks::vc::Vc<turbopack_core::module_graph::ModuleGraph>, turbo_tasks::vc::Vc<alloc::boxed::Box<dyn turbopack_core::chunk::chunking_context::ChunkingContext>>)>>::functor::{closure#0}
       8: <turbo_tasks::capture_future::CaptureFuture<core::result::Result<core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>, futures_util::future::future::catch_unwind::CatchUnwind<core::panic::unwind_safe::AssertUnwindSafe<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>> + core::marker::Send>>>>> as core::future::future::Future>::poll
       9: <tracing::instrument::Instrumented<<turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}::{closure#0}> as core::future::future::Future>::poll
      10: <tokio::task::task_local::LocalKey<turbo_tasks::manager::CurrentLocalTaskState>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      11: <tokio::task::task_local::LocalKey<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>, tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}>> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      12: <tokio::task::task_local::LocalKey<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>>>
      13: <tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>> as core::future::future::Future>::poll
      14: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread_alt::handle::Handle>>>::poll
      15: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
      16: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll_inner
      17: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
      18: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task
      19: <tokio::runtime::scheduler::multi_thread::worker::Context>::run
      20: <tokio::runtime::context::scoped::Scoped<tokio::runtime::scheduler::Context>>::set::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure#0}, ()>
      21: tokio::runtime::context::runtime::enter_runtime::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}, ()>
      22: tokio::runtime::scheduler::multi_thread::worker::run
      23: <tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}> as core::future::future::Future>::poll
      24: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
      25: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      26: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
      27: tokio::runtime::task::raw::poll::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      28: <tokio::runtime::blocking::pool::Inner>::run
      29: std::sys::backtrace::__rust_begin_short_backtrace::<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>
      30: <<std::thread::Builder>::spawn_unchecked_<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
      31: std::sys::pal::unix::thread::Thread::new::thread_start
      32: <unknown>
      33: <unknown>


    > Build error occurred
    Error [ModuleBuildError]: ./packages/next/dist/esm/build/templates/helpers.js
    Code generation for chunk item errored
    An error occurred while generating the chunk item 6753

    Caused by:
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for hoist")

    Debug info:
    - An error occurred while generating the chunk item 6753
    - Execution of <ModuleChunkItem as EcmascriptChunkItem>::content_with_async_module_info failed
    - Execution of EcmascriptModuleContent::new failed
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for hoist")



    ./packages/next/dist/esm/build/templates/pages-api.js
    Code generation for chunk item errored
    An error occurred while generating the chunk item 4153

    Caused by:
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for config")

    Debug info:
    - An error occurred while generating the chunk item 4153
    - Execution of <ModuleChunkItem as EcmascriptChunkItem>::content_with_async_module_info failed
    - Execution of EcmascriptModuleContent::new failed
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for config")



    ./packages/next/dist/esm/server/route-kind.js
    Code generation for chunk item errored
    An error occurred while generating the chunk item 4624

    Caused by:
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for RouteKind")

    Debug info:
    - An error occurred while generating the chunk item 4624
    - Execution of <ModuleChunkItem as EcmascriptChunkItem>::content_with_async_module_info failed
    - Execution of EcmascriptModuleContent::new failed
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for RouteKind")



    ./test/integration/bigint/pages/api/bigint.js
    Code generation for chunk item errored
    An error occurred while generating the chunk item 1942

    Caused by:
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for {default export}")

    Debug info:
    - An error occurred while generating the chunk item 1942
    - Execution of <ModuleChunkItem as EcmascriptChunkItem>::content_with_async_module_info failed
    - Execution of EcmascriptModuleContent::new failed
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for {default export}")

      at processIssues (../dist/shared/lib/turbopack/utils.js:110:37)
      at handleRouteType (../dist/build/handle-entrypoints.js:228:42)
      at async (../dist/build/turbopack-build/impl.js:220:17)
      at async turbopackBuild (../dist/build/turbopack-build/impl.js:262:5)
      at async Object.workerMain (../dist/build/turbopack-build/impl.js:325:20) {
        type: 'ModuleBuildError'
      }
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:314:11)

  ● bigint API route support › production mode › should return the BigInt result text

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       No config file found
       No config file found
       ▲ Next.js 15.2.0-canary.40 (Turbopack)

       Checking validity of types ...
       Creating an optimized production build ...
       No config file found
       No config file found
       Building (0/2) ...
    FATAL: An unexpected Turbopack error occurred:
    Panic: panicked at turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:540:29:
    Failed to find export context for hoist
    Backtrace:    0: next_swc_napi::init::{closure#0}
       1: std::panicking::rust_panic_with_hook
       2: std::panicking::begin_panic_handler::{{closure}}
       3: std::sys::backtrace::__rust_end_short_backtrace
       4: rust_begin_unwind
       5: core::panicking::panic_fmt
       6: <turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline::{closure#0}
       7: <<turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline as turbo_tasks::task::function::TaskFnInputFunctionWithThis<turbo_tasks::task::function::AsyncFunctionMode, turbopack_ecmascript::references::esm::export::EsmExports, (turbo_tasks::vc::Vc<turbopack_core::module_graph::ModuleGraph>, turbo_tasks::vc::Vc<alloc::boxed::Box<dyn turbopack_core::chunk::chunking_context::ChunkingContext>>)>>::functor::{closure#0}
       8: <turbo_tasks::capture_future::CaptureFuture<core::result::Result<core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>, futures_util::future::future::catch_unwind::CatchUnwind<core::panic::unwind_safe::AssertUnwindSafe<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>> + core::marker::Send>>>>> as core::future::future::Future>::poll
       9: <tracing::instrument::Instrumented<<turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}::{closure#0}> as core::future::future::Future>::poll
      10: <tokio::task::task_local::LocalKey<turbo_tasks::manager::CurrentLocalTaskState>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      11: <tokio::task::task_local::LocalKey<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>, tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}>> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      12: <tokio::task::task_local::LocalKey<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>>>
      13: <tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>> as core::future::future::Future>::poll
      14: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread_alt::handle::Handle>>>::poll
      15: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
      16: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll_inner
      17: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
      18: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task
      19: <tokio::runtime::scheduler::multi_thread::worker::Context>::run
      20: <tokio::runtime::context::scoped::Scoped<tokio::runtime::scheduler::Context>>::set::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure#0}, ()>
      21: tokio::runtime::context::runtime::enter_runtime::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}, ()>
      22: tokio::runtime::scheduler::multi_thread::worker::run
      23: <tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}> as core::future::future::Future>::poll
      24: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
      25: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      26: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
      27: tokio::runtime::task::raw::poll::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      28: <tokio::runtime::blocking::pool::Inner>::run
      29: std::sys::backtrace::__rust_begin_short_backtrace::<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>
      30: <<std::thread::Builder>::spawn_unchecked_<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
      31: std::sys::pal::unix::thread::Thread::new::thread_start
      32: <unknown>
      33: <unknown>

    FATAL: An unexpected Turbopack error occurred:
    Panic: panicked at turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:540:29:
    Failed to find export context for __TURBOPACK__default__export__
    Backtrace:    0: next_swc_napi::init::{closure#0}
       1: std::panicking::rust_panic_with_hook
       2: std::panicking::begin_panic_handler::{{closure}}
       3: std::sys::backtrace::__rust_end_short_backtrace
       4: rust_begin_unwind
       5: core::panicking::panic_fmt
       6: <turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline::{closure#0}
       7: <<turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline as turbo_tasks::task::function::TaskFnInputFunctionWithThis<turbo_tasks::task::function::AsyncFunctionMode, turbopack_ecmascript::references::esm::export::EsmExports, (turbo_tasks::vc::Vc<turbopack_core::module_graph::ModuleGraph>, turbo_tasks::vc::Vc<alloc::boxed::Box<dyn turbopack_core::chunk::chunking_context::ChunkingContext>>)>>::functor::{closure#0}
       8: <turbo_tasks::capture_future::CaptureFuture<core::result::Result<core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>, futures_util::future::future::catch_unwind::CatchUnwind<core::panic::unwind_safe::AssertUnwindSafe<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>> + core::marker::Send>>>>> as core::future::future::Future>::poll
       9: <tracing::instrument::Instrumented<<turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}::{closure#0}> as core::future::future::Future>::poll
      10: <tokio::task::task_local::LocalKey<turbo_tasks::manager::CurrentLocalTaskState>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      11: <tokio::task::task_local::LocalKey<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>, tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}>> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      12: <tokio::task::task_local::LocalKey<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>>>
      13: <tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>> as core::future::future::Future>::poll
      14: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread_alt::handle::Handle>>>::poll
      15: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
      16: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll_inner
      17: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
      18: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task
      19: <tokio::runtime::scheduler::multi_thread::worker::Context>::run
      20: <tokio::runtime::context::scoped::Scoped<tokio::runtime::scheduler::Context>>::set::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure#0}, ()>
      21: tokio::runtime::context::runtime::enter_runtime::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}, ()>
      22: tokio::runtime::scheduler::multi_thread::worker::run
      23: <tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}> as core::future::future::Future>::poll
      24: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
      25: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      26: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
      27: tokio::runtime::task::raw::poll::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      28: <tokio::runtime::blocking::pool::Inner>::run
      29: std::sys::backtrace::__rust_begin_short_backtrace::<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>
      30: <<std::thread::Builder>::spawn_unchecked_<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
      31: std::sys::pal::unix::thread::Thread::new::thread_start
      32: <unknown>
      33: <unknown>

    FATAL: An unexpected Turbopack error occurred:
    Panic: panicked at turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:540:29:
    Failed to find export context for config
    Backtrace:    0: next_swc_napi::init::{closure#0}
       1: std::panicking::rust_panic_with_hook
       2: std::panicking::begin_panic_handler::{{closure}}
       3: std::sys::backtrace::__rust_end_short_backtrace
       4: rust_begin_unwind
       5: core::panicking::panic_fmt
       6: <turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline::{closure#0}
       7: <<turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline as turbo_tasks::task::function::TaskFnInputFunctionWithThis<turbo_tasks::task::function::AsyncFunctionMode, turbopack_ecmascript::references::esm::export::EsmExports, (turbo_tasks::vc::Vc<turbopack_core::module_graph::ModuleGraph>, turbo_tasks::vc::Vc<alloc::boxed::Box<dyn turbopack_core::chunk::chunking_context::ChunkingContext>>)>>::functor::{closure#0}
       8: <turbo_tasks::capture_future::CaptureFuture<core::result::Result<core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>, futures_util::future::future::catch_unwind::CatchUnwind<core::panic::unwind_safe::AssertUnwindSafe<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>> + core::marker::Send>>>>> as core::future::future::Future>::poll
       9: <tracing::instrument::Instrumented<<turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}::{closure#0}> as core::future::future::Future>::poll
      10: <tokio::task::task_local::LocalKey<turbo_tasks::manager::CurrentLocalTaskState>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      11: <tokio::task::task_local::LocalKey<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>, tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}>> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      12: <tokio::task::task_local::LocalKey<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>>>
      13: <tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>> as core::future::future::Future>::poll
      14: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread_alt::handle::Handle>>>::poll
      15: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
      16: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll_inner
      17: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
      18: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task
      19: <tokio::runtime::scheduler::multi_thread::worker::Context>::run
      20: <tokio::runtime::context::scoped::Scoped<tokio::runtime::scheduler::Context>>::set::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure#0}, ()>
      21: tokio::runtime::context::runtime::enter_runtime::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}, ()>
      22: tokio::runtime::scheduler::multi_thread::worker::run
      23: <tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}> as core::future::future::Future>::poll
      24: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
      25: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      26: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
      27: tokio::runtime::task::raw::poll::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      28: <tokio::runtime::blocking::pool::Inner>::run
      29: std::sys::backtrace::__rust_begin_short_backtrace::<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>
      30: <<std::thread::Builder>::spawn_unchecked_<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
      31: std::sys::pal::unix::thread::Thread::new::thread_start
      32: <unknown>
      33: <unknown>

    FATAL: An unexpected Turbopack error occurred:
    Panic: panicked at turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:540:29:
    Failed to find export context for RouteKind
    Backtrace:    0: next_swc_napi::init::{closure#0}
       1: std::panicking::rust_panic_with_hook
       2: std::panicking::begin_panic_handler::{{closure}}
       3: std::sys::backtrace::__rust_end_short_backtrace
       4: rust_begin_unwind
       5: core::panicking::panic_fmt
       6: <turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline::{closure#0}
       7: <<turbopack_ecmascript::references::esm::export::EsmExports as turbopack_ecmascript::references::esm::export::EsmExports_CodeGenerateable_code_generation_inline>::code_generation_turbo_tasks_function_inline as turbo_tasks::task::function::TaskFnInputFunctionWithThis<turbo_tasks::task::function::AsyncFunctionMode, turbopack_ecmascript::references::esm::export::EsmExports, (turbo_tasks::vc::Vc<turbopack_core::module_graph::ModuleGraph>, turbo_tasks::vc::Vc<alloc::boxed::Box<dyn turbopack_core::chunk::chunking_context::ChunkingContext>>)>>::functor::{closure#0}
       8: <turbo_tasks::capture_future::CaptureFuture<core::result::Result<core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>, futures_util::future::future::catch_unwind::CatchUnwind<core::panic::unwind_safe::AssertUnwindSafe<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<turbo_tasks::raw_vc::RawVc, anyhow::Error>> + core::marker::Send>>>>> as core::future::future::Future>::poll
       9: <tracing::instrument::Instrumented<<turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}::{closure#0}> as core::future::future::Future>::poll
      10: <tokio::task::task_local::LocalKey<turbo_tasks::manager::CurrentLocalTaskState>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      11: <tokio::task::task_local::LocalKey<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<std::sync::rwlock::RwLock<turbo_tasks::manager::CurrentGlobalTaskState>>, tokio::task::task_local::TaskLocalFuture<turbo_tasks::manager::CurrentLocalTaskState, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}::{closure#1}>> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<bool>>>
      12: <tokio::task::task_local::LocalKey<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>>>::scope_inner::<<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}> as core::future::future::Future>::poll::{closure#0}, core::option::Option<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>>>
      13: <tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>> as core::future::future::Future>::poll
      14: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread_alt::handle::Handle>>>::poll
      15: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
      16: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll_inner
      17: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::task::task_local::TaskLocalFuture<alloc::sync::Arc<dyn turbo_tasks::manager::TurboTasksApi>, <turbo_tasks::manager::TurboTasks<turbo_tasks_backend::backend::TurboTasksBackend<turbo_tasks_backend::kv_backing_storage::KeyValueDatabaseBackingStorage<turbo_tasks_backend::database::noop_kv::NoopKvDb>>>>::schedule::{closure#0}>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
      18: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task
      19: <tokio::runtime::scheduler::multi_thread::worker::Context>::run
      20: <tokio::runtime::context::scoped::Scoped<tokio::runtime::scheduler::Context>>::set::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure#0}, ()>
      21: tokio::runtime::context::runtime::enter_runtime::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}, ()>
      22: tokio::runtime::scheduler::multi_thread::worker::run
      23: <tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}> as core::future::future::Future>::poll
      24: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
      25: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      26: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
      27: tokio::runtime::task::raw::poll::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
      28: <tokio::runtime::blocking::pool::Inner>::run
      29: std::sys::backtrace::__rust_begin_short_backtrace::<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>
      30: <<std::thread::Builder>::spawn_unchecked_<<tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
      31: std::sys::pal::unix::thread::Thread::new::thread_start
      32: <unknown>
      33: <unknown>


    > Build error occurred
    Error [ModuleBuildError]: ./packages/next/dist/esm/build/templates/helpers.js
    Code generation for chunk item errored
    An error occurred while generating the chunk item 6753

    Caused by:
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for hoist")

    Debug info:
    - An error occurred while generating the chunk item 6753
    - Execution of <ModuleChunkItem as EcmascriptChunkItem>::content_with_async_module_info failed
    - Execution of EcmascriptModuleContent::new failed
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for hoist")



    ./packages/next/dist/esm/build/templates/pages-api.js
    Code generation for chunk item errored
    An error occurred while generating the chunk item 4153

    Caused by:
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for config")

    Debug info:
    - An error occurred while generating the chunk item 4153
    - Execution of <ModuleChunkItem as EcmascriptChunkItem>::content_with_async_module_info failed
    - Execution of EcmascriptModuleContent::new failed
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for config")



    ./packages/next/dist/esm/server/route-kind.js
    Code generation for chunk item errored
    An error occurred while generating the chunk item 4624

    Caused by:
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for RouteKind")

    Debug info:
    - An error occurred while generating the chunk item 4624
    - Execution of <ModuleChunkItem as EcmascriptChunkItem>::content_with_async_module_info failed
    - Execution of EcmascriptModuleContent::new failed
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for RouteKind")



    ./test/integration/bigint/pages/api/bigint.js
    Code generation for chunk item errored
    An error occurred while generating the chunk item 1942

    Caused by:
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for {default export}")

    Debug info:
    - An error occurred while generating the chunk item 1942
    - Execution of <ModuleChunkItem as EcmascriptChunkItem>::content_with_async_module_info failed
    - Execution of EcmascriptModuleContent::new failed
    - Panic in <EsmExports as CodeGenerateable>::code_generation: Some("Failed to find export context for {default export}")

      at processIssues (../dist/shared/lib/turbopack/utils.js:110:37)
      at handleRouteType (../dist/build/handle-entrypoints.js:228:42)
      at async (../dist/build/turbopack-build/impl.js:220:17)
      at async turbopackBuild (../dist/build/turbopack-build/impl.js:262:5)
      at async Object.workerMain (../dist/build/turbopack-build/impl.js:325:20) {
        type: 'ModuleBuildError'
      }
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:314:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-72232 | Change |
| - | - | - | - |
| buildDuration | 18.1s | 15.4s | N/A |
| buildDurationCached | 14.6s | 12.1s | N/A |
| nodeModulesSize | 392 MB | 392 MB | ✓ |
| nextStartRea..uration (ms) | 415ms | 418ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-72232 | Change |
| - | - | - | - |
| 5306-HASH.js gzip | 54 kB | 54 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.46 kB | 5.46 kB | N/A |
| bccd1874-HASH.js gzip | 52.9 kB | 52.9 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 239 B | 242 B | N/A |
| main-HASH.js gzip | 34.5 kB | 34.5 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-72232 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-72232 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.59 kB | 4.58 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.35 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-72232 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 748 B | 747 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-72232 | Change |
| - | - | - | - |
| index.html gzip | 525 B | 524 B | N/A |
| link.html gzip | 539 B | 538 B | N/A |
| withRouter.html gzip | 520 B | 520 B | ✓ |
| Overall change | 520 B | 520 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-72232 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 130 kB | 130 kB | N/A |
| page.js gzip | 210 kB | 210 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-72232 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 676 B | 671 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.3 kB | 31.3 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-72232 | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 385 kB | 385 kB | ✓ |
| app-page-exp..prod.js gzip | 132 kB | 132 kB | ✓ |
| app-page-tur..prod.js gzip | 145 kB | 145 kB | ✓ |
| app-page-tur..prod.js gzip | 141 kB | 141 kB | ✓ |
| app-page.run...dev.js gzip | 372 kB | 372 kB | ✓ |
| app-page.run..prod.js gzip | 128 kB | 128 kB | ✓ |
| app-route-ex...dev.js gzip | 39.3 kB | 39.3 kB | ✓ |
| app-route-ex..prod.js gzip | 25.6 kB | 25.6 kB | ✓ |
| app-route-tu..prod.js gzip | 25.6 kB | 25.6 kB | ✓ |
| app-route-tu..prod.js gzip | 25.4 kB | 25.4 kB | ✓ |
| app-route.ru...dev.js gzip | 40.8 kB | 40.8 kB | ✓ |
| app-route.ru..prod.js gzip | 25.4 kB | 25.4 kB | ✓ |
| dist_client_...dev.js gzip | 356 B | 356 B | ✓ |
| dist_client_...dev.js gzip | 349 B | 349 B | ✓ |
| pages-api-tu..prod.js gzip | 9.69 kB | 9.69 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.8 kB | 11.8 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.68 kB | 9.68 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 31.5 kB | 31.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 60.5 kB | 60.5 kB | ✓ |
| Overall change | 1.65 MB | 1.65 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-72232 | Change |
| - | - | - | - |
| 0.pack gzip | 2.1 MB | 2.1 MB | N/A |
| index.pack gzip | 75.5 kB | 75 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 2bdd050ba668ae6794beba5c4772632e889a12ba

File: turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs [hunk 1]
```diff
@@ -527,20 +534,23 @@ impl CodeGenerateable for EsmExports {
                     } else {
                         Cow::Borrowed(name.as_str())
                     };
+                    let ctxt = export_ctxts
+                        .get(name)
+                        .unwrap_or_else(|| {
+                            panic!("Failed to find export context for {}", name);
```
Comment (sokra) [inline turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:540]:
```suggestion
                            bail!("Failed to find export context for {}", name);
```

File: turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs [hunk 2]
```diff
@@ -592,10 +602,17 @@ impl CodeGenerateable for EsmExports {
                     referenced_asset
                         .get_ident(module_graph, chunking_context)
                         .await?
-                        .map(|ident| {
+                        .map(|name| {
+                            let ctxt = export_ctxts
+                                .get(&*name)
+                                .unwrap_or_else(|| {
+                                    panic!("Failed to find export context for {}", name);
```
Comment (sokra) [inline turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:609]:
```suggestion
                                    bail!("Failed to find export context for {}", name);
```

File: turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs [hunk 3]
```diff
@@ -429,6 +430,7 @@ async fn emit_star_exports_issue(source_ident: Vc<AssetIdent>, message: RcStr) -
 #[turbo_tasks::value(shared)]
 #[derive(Hash, Debug)]
 pub struct EsmExports {
+    pub parsed: ResolvedVc<ParseResult>,
```
Comment (sokra) [inline turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:433]: Instead of storing that here, we should instead pass the `ParseResult` to `code_generation`

File: turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs [hunk 4]
```diff
@@ -494,8 +495,12 @@ impl EsmExports {
         self: Vc<Self>,
         _module_graph: Vc<ModuleGraph>,
         chunking_context: Vc<Box<dyn ChunkingContext>>,
+        parsed: Vc<ParseResult>,
     ) -> Result<CodeGeneration> {
         let expanded = self.expand_exports().await?;
+        let ParseResult::Ok { eval_context, .. } = &*parsed.await? else {
+            return Err(anyhow::anyhow!("failed to get eval context"));
```
Comment (bgw) [inline turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:502]:
```suggestion
            anyhow::bail!("failed to get eval context");
```

File: turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs [hunk 5]
```diff
@@ -522,20 +527,23 @@ impl EsmExports {
                     } else {
                         Cow::Borrowed(name.as_str())
                     };
+                    let ctxt = eval_context
+                        .imports
+                        .exports
+                        .get(name)
+                        .map(|id| id.1)
+                        .expect("failed to get the correct SyntaxContext");
```
Comment (bgw) [inline turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:535]: It would seem like `self` (where `name` comes from) and `parsed` (where `eval_context` comes from) must refer to the same code, and therefore `name` should always be in `eval_context`, but turbo-tasks is eventually consistent, so they might not!

Turbo-tasks does not suppress panics (maybe it should when they're a result of eventual consistency...), so we must handle it as a `Result`.

```suggestion
                        .context("failed to get the correct SyntaxContext")?;
```

**Review by bgw — APPROVED** [review]

File: turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs (hunk 5 above)
Comment (kdy1) [reply turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs:535]: Good to know, thank you!

File: turbopack/crates/turbopack-ecmascript/src/side_effect_optimization/facade/chunk_item.rs [hunk 6]
```diff
@@ -23,13 +23,15 @@ use crate::{
...
     },
+    parse::ParseResult,
     process_content_with_code_gens,
 };
 
 /// The chunk item for [EcmascriptModuleFacadeModule].
 #[turbo_tasks::value(shared)]
 pub struct EcmascriptModuleFacadeChunkItem {
     pub(crate) module: ResolvedVc<EcmascriptModuleFacadeModule>,
+    pub(crate) parsed: ResolvedVc<ParseResult>,
```
Comment (sokra) [inline turbopack/crates/turbopack-ecmascript/src/side_effect_optimization/facade/chunk_item.rs:34]:
```suggestion
```

You can get that from `module.parsed`

**Review by sokra — APPROVED** [review]
