### PR TITLE
fix(next-swc/styled-jsx): Fix interpolation in media query

### LINKED ISSUE #31562: @media query interpolation broken in 12.0.4
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

v16.11.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next dev

### Describe the Bug

PR #31407 fixed #30480 but introduced a new issue where interpolated strings in media queries are sometimes unnecessarily parenthesized.

Consider this, which used to work in 12.0.3 and before:

```ts
/// theme.ts

// Media Queries
export const Target: { [size in ScreenSizeQuery]: string } &
  { [prop in OtherQueries]: string } = {
  smallOnly: "screen and (max-width: 580px)",
  smallPlus: "screen and (min-width: 580px)",
  mediumPlus: "screen and (min-width: 700px)",
  largePlus: "screen and (min-width: 900px)",
  xlPlus: "screen and (min-width: 1200px)",
  touchScreen: "(hover: none), (pointer: coarse)",
};
```

And elsewhere in JSX:

```tsx
/// _app.tsx

// ...
      <style jsx global>{`
        html {
          font-size: ${Typography.base.size.default};
          line-height: ${Typography.base.lineHeight};
        }
        @media ${Target.mediumPlus} {
          html {
            font-size: ${Typography.base.size.mediumPlus};
          }
        }
        @media ${Target.largePlus} {
          html {
            font-size: ${Typography.base.size.largePlus};
          }
        }
      `}</style>
// ...
```

### Expected Behavior

This should compile into:

```css
            html {
                font-size: 16px;
                line-height: 1.75;
            }

            @media screen and (min-width: 700px) {
                html {
                    font-size:18px;
                }
            }

            @media screen and (min-width: 900px) {
                html {
                    font-size:21px;
                }
            }
```

### To Reproduce

Instead, in 12.0.4, it compiles into:

```css
html {font-size:16px; line-height:1.75}
@media (screen and (min-width: 700px)) {html {font-size:18px}}
@media (screen and (min-width: 900px)) {html {font-size:21px}}
```

Notably, this should be `@media screen and (min-width: 700px) {}` rather than `@media (screen and (min-width: 700px)) {}`.

### PR DESCRIPTION
**Pull request by kdy1**
## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

Fixes https://github.com/vercel/next.js/issues/31562

### CODE REVIEW

File: packages/next-swc/crates/core/tests/fixture.rs [hunk 1]
```diff
@@ -112,13 +99,20 @@ fn styled_jsx_span_should_not_affect_hash(input: PathBuf) {
                 let _mark = Mark::fresh(Mark::root());
             }
 
-            chain!(as_folder(DropSpan), resolver(), styled_jsx())
+            chain!(resolver(), styled_jsx(t.cm.clone()))
```
Comment (kdy1) [inline packages/next-swc/crates/core/tests/fixture.rs:102]: I removed `DropSpan` because `styled-jsx` depends on span.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| buildDuration | 18.1s | 17.9s | -213ms |
| buildDurationCached | 3.4s | 3.3s | -75ms |
| nodeModulesSize | 351 MB | 351 MB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.806 | 2.905 | ⚠️ +0.1 |
| / avg req/sec | 890.88 | 860.52 | ⚠️ -30.36 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.35 | 1.315 | -0.04 |
| /error-in-render avg req/sec | 1852.16 | 1900.51 | +48.35 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 30.2 kB | 30.2 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 74 kB | 74 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.73 kB | 4.73 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.13 kB | 2.13 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| buildDuration | 19.3s | 19.7s | ⚠️ +430ms |
| buildDurationCached | 3.2s | 3.5s | ⚠️ +270ms |
| nodeModulesSize | 351 MB | 351 MB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.889 | 2.911 | ⚠️ +0.02 |
| / avg req/sec | 865.22 | 858.71 | ⚠️ -6.51 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.403 | 1.338 | -0.06 |
| /error-in-render avg req/sec | 1781.79 | 1869.02 | +87.23 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 30.3 kB | 30.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 74.2 kB | 74.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 906 B | 906 B | ✓ |
| image-HASH.js gzip | 4.75 kB | 4.75 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | kdy1/next.js styled-jsx-31562 | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: d7c2f5629601b1df1c751b2665921330f1538001

**Review by timneutkens — APPROVED** [review]
