### PR TITLE
Fix: Non-writable pages/_app breaks build 

### LINKED ISSUE #24772: Non-writable pages/_app breaks build
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.15

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Other

### Describe the Bug

In environments that make files non-writable like Bazel, builds break with

```
Failed to compile.

./src/<file>.css
Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: src/pages/_app.tsx
```

This is due to checking if pages/_app `isWritable`: https://github.com/vercel/next.js/blob/0af3b526408bae26d6b3f8cab75c4229998bf7cb/packages/next/server/lib/find-page-file.ts#L34

Is there a reason to check if file is writable and not just if it exists?

### Expected Behavior

Expected build not to fail even if pages/_app is not writable

### To Reproduce

Remove write permission on `pages/_app`:

```
chmod -w pages/_app.js
```

### PR DESCRIPTION
**Pull request by darshkpatel**
Fixes #24772

Added `isReadable` function and switched to using `isReadable` instead of `isWriteable` 
Not sure if the function is placed in the correct place, let me know if I should move it somewhere else. 

Also, nitpick: `import {promises} from 'fs'` hinders readability should I change it to something like `import {promises as fsPromises} from 'fs'` ?

**Update:** 
Came across an edge case where ENAMETOOLONG wasn't handled which was causing some tests to fail. 
Updated behavior to respond with status code 400 when ENAMETOOLONG is encountered. 
Not entirely sure if it's the best way to handle this, let me know if I should use a different approach.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12.2s | ⚠️ +122ms |
| buildDurationCached | 4.1s | 3.8s | -252ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +470 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.019 | 2.021 | 0 |
| / avg req/sec | 1238.15 | 1237.06 | ⚠️ -1.09 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.062 | 1.095 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2353.68 | 2283.41 | ⚠️ -70.27 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| index.html gzip | 560 B | 560 B | ✓ |
| link.html gzip | 569 B | 569 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 15s | 15s | -26ms |
| buildDurationCached | 5.7s | 5.7s | ⚠️ +26ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +470 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | ⚠️ +2 B |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.35 MB | 1.35 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.39 MB | 1.39 MB | ✓ |
| withRouter.js | 1.39 MB | 1.39 MB | ⚠️ +2 B |
| Overall change | 6.9 MB | 6.9 MB | ⚠️ +4 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.3s | -166ms |
| buildDurationCached | 4.3s | 4.3s | -30ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +470 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.064 | 2.084 | ⚠️ +0.02 |
| / avg req/sec | 1211.18 | 1199.7 | ⚠️ -11.48 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.106 | 1.059 | -0.05 |
| /error-in-render avg req/sec | 2259.66 | 2360.24 | +100.58 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.72 kB | 3.72 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.37 kB | 9.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: 20ea370ba36edfca76b14e39bb52fd1976fcc6e4

**Comment by dpolugic** [comment]
> Also, nitpick: `import {promises} from 'fs'` hinders readability should I change it to something like `import {promises as fsPromises} from 'fs'` ?

I'm not a Next.js maintainer, but that seems like a great suggestion without any downsides. :)

File: packages/next/server/lib/find-page-file.ts [hunk 1]
```diff
@@ -17,6 +16,15 @@ async function isTrueCasePagePath(pagePath: string, pagesDir: string) {
   return (await Promise.all(segmentExistsPromises)).every(Boolean)
 }
 
+async function isReadable(directory: string): Promise<boolean> {
```
Comment (timneutkens) [inline packages/next/server/lib/find-page-file.ts:19]: You can use the `fileExists` function from `packages/next/lib/file-exists.ts` instead which does the same only checking for `ENOENT` to ensure filesystem errors are throwing:

```
await fileExists(directory)
```

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.3s | ⚠️ +229ms |
| buildDurationCached | 4.7s | 4s | -666ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -14 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.384 | 2.371 | -0.01 |
| / avg req/sec | 1048.84 | 1054.54 | +5.7 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.267 | 1.313 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1973.89 | 1903.53 | ⚠️ -70.36 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| index.html gzip | 560 B | 560 B | ✓ |
| link.html gzip | 569 B | 569 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 15.3s | 15.1s | -255ms |
| buildDurationCached | 5.8s | 5.7s | -88ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -14 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | ⚠️ +2 B |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.35 MB | 1.35 MB | ⚠️ +2 B |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.39 MB | 1.39 MB | ✓ |
| withRouter.js | 1.39 MB | 1.39 MB | ✓ |
| Overall change | 6.9 MB | 6.9 MB | ⚠️ +4 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 10.7s | 10.6s | -138ms |
| buildDurationCached | 4.5s | 4.8s | ⚠️ +304ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -14 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.156 | 2.199 | ⚠️ +0.04 |
| / avg req/sec | 1159.42 | 1136.73 | ⚠️ -22.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.078 | 1.098 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2318.64 | 2277.07 | ⚠️ -41.57 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.72 kB | 3.72 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.37 kB | 9.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: e795cd78e7509f16637b5fcb83eb9cd762afee87

**Review by timneutkens — DISMISSED** [review]

**Comment by darshkpatel** [comment]
Weirdly one of the required integration tests is failing on the CI with the recent switch to `fileExists`
Seems to pass locally with node `14.16.1` and node `16.1.0` 
Screenshot 2021-05-06 at 5 07 03 PM

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 11.9s | 12.4s | ⚠️ +482ms |
| buildDurationCached | 4.2s | 4.3s | ⚠️ +62ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -14 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.022 | 2.092 | ⚠️ +0.07 |
| / avg req/sec | 1236.52 | 1195.03 | ⚠️ -41.49 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.054 | 1.152 | ⚠️ +0.1 |
| /error-in-render avg req/sec | 2371.85 | 2169.73 | ⚠️ -202.12 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| index.html gzip | 560 B | 560 B | ✓ |
| link.html gzip | 569 B | 569 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 16.7s | 17s | ⚠️ +350ms |
| buildDurationCached | 6.4s | 6.3s | -91ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -14 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | -2 B |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.35 MB | 1.35 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.39 MB | 1.39 MB | ✓ |
| withRouter.js | 1.39 MB | 1.39 MB | ✓ |
| Overall change | 6.9 MB | 6.9 MB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 11.9s | 11.6s | -335ms |
| buildDurationCached | 4.9s | 4.1s | -793ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -14 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.384 | 2.323 | -0.06 |
| / avg req/sec | 1048.76 | 1076.3 | +27.54 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.215 | 1.204 | -0.01 |
| /error-in-render avg req/sec | 2057.56 | 2075.57 | +18.01 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.72 kB | 3.72 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.37 kB | 9.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: d928b2c24465c149f6965a786eaf2aadcd43f174

**Comment by ijjk** [comment]
## Failing test suites 
Commit: d928b2c24465c149f6965a786eaf2aadcd43f174

**test/integration/amphtml/test/index.test.js** 
- AMP Usage > AMP dev mode > should detect changes and refresh an AMP page
- AMP Usage > AMP dev mode > should not reload unless the page is edited for an AMP page

<details>
<summary>Expand output</summary>

  ● AMP Usage › AMP dev mode › should detect changes and refresh an AMP page

    expect(received).toBe(expected) // Object.is equality

    Expected: "I'm an AMP page!"
    Received: "replaced it!"

      361 |         browser = await webdriver(dynamicAppPort, '/hmr/amp')
      362 |         const text = await browser.elementByCss('p').text()
    > 363 |         expect(text).toBe(`I'm an AMP page!`)
          |                      ^
      364 |
      365 |         const hmrTestPagePath = join(__dirname, '../', 'pages', 'hmr', 'amp.js')
      366 |

      at Object.<anonymous> (integration/amphtml/test/index.test.js:363:22)

  ● AMP Usage › AMP dev mode › should not reload unless the page is edited for an AMP page

    TIMED OUT: /I'm an AMP page!/

    replaced it!

      394 |
      395 |   if (hardError) {
    > 396 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      397 |   }
      398 |   return false
      399 | }

      at check (lib/next-test-utils.js:396:11)
      at Object.<anonymous> (integration/amphtml/test/index.test.js:409:9)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.7s | ⚠️ +513ms |
| buildDurationCached | 4.3s | 4.2s | -122ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -14 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.375 | 2.593 | ⚠️ +0.22 |
| / avg req/sec | 1052.52 | 963.98 | ⚠️ -88.54 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.393 | 1.536 | ⚠️ +0.14 |
| /error-in-render avg req/sec | 1794.43 | 1627.5 | ⚠️ -166.93 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| index.html gzip | 560 B | 560 B | ✓ |
| link.html gzip | 569 B | 569 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 16.9s | 17s | ⚠️ +74ms |
| buildDurationCached | 6.1s | 6.2s | ⚠️ +146ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -14 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | ✓ |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.35 MB | 1.35 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.39 MB | 1.39 MB | ⚠️ +2 B |
| withRouter.js | 1.39 MB | 1.39 MB | ✓ |
| Overall change | 6.9 MB | 6.9 MB | ⚠️ +2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 11.4s | 11.2s | -178ms |
| buildDurationCached | 4.8s | 4.7s | -92ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -14 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.438 | 2.475 | ⚠️ +0.04 |
| / avg req/sec | 1025.44 | 1010.25 | ⚠️ -15.19 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.422 | 1.401 | -0.02 |
| /error-in-render avg req/sec | 1758.38 | 1785.06 | +26.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.72 kB | 3.72 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.37 kB | 9.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: c00363b335d7b014f6e7d68796b1fedd046fa20a

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c00363b335d7b014f6e7d68796b1fedd046fa20a

**test/integration/file-serving/test/index.test.js** 
- File Serving > dev mode > should prevent traversing with /%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25aftest-file.txt
- File Serving > dev mode > should prevent traversing with /%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259ctest-file.txt

<details>
<summary>Expand output</summary>

  ● File Serving › dev mode › should prevent traversing with /%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25aftest-file.txt

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      24 |   // test base mount point `public/`
      25 |   const res = await fetchViaHTTP(appPort, path)
    > 26 |   expect(res.status === 400 || res.status === 404).toBe(true)
         |                                                    ^
      27 |   expect(await res.text()).toMatch(containRegex)
      28 |
      29 |   // test `/_next` mount point

      at expectStatus (integration/file-serving/test/index.test.js:26:52)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (integration/file-serving/test/index.test.js:837:5)

  ● File Serving › dev mode › should prevent traversing with /%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259ctest-file.txt

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      24 |   // test base mount point `public/`
      25 |   const res = await fetchViaHTTP(appPort, path)
    > 26 |   expect(res.status === 400 || res.status === 404).toBe(true)
         |                                                    ^
      27 |   expect(await res.text()).toMatch(containRegex)
      28 |
      29 |   // test `/_next` mount point

      at expectStatus (integration/file-serving/test/index.test.js:26:52)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (integration/file-serving/test/index.test.js:1097:5)

</details>

**Comment by darshkpatel** [comment]
I believe it's a CI issue, random groups of integration tests fail after each commit :/

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 15.1s | 15.3s | ⚠️ +239ms |
| buildDurationCached | 4.9s | 4.6s | -318ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -14 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.567 | 2.577 | ⚠️ +0.01 |
| / avg req/sec | 973.84 | 970.3 | ⚠️ -3.54 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.494 | 1.503 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1673.36 | 1663.36 | ⚠️ -10 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| index.html gzip | 560 B | 560 B | ✓ |
| link.html gzip | 569 B | 569 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 18.7s | 18.6s | -11ms |
| buildDurationCached | 7s | 7s | -21ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -14 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | ⚠️ +4 B |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.35 MB | 1.35 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.39 MB | 1.39 MB | ✓ |
| withRouter.js | 1.39 MB | 1.39 MB | ✓ |
| Overall change | 6.9 MB | 6.9 MB | ⚠️ +4 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 12.9s | 13.1s | ⚠️ +127ms |
| buildDurationCached | 5.4s | 5.3s | -63ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -14 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.606 | 2.592 | -0.01 |
| / avg req/sec | 959.26 | 964.34 | +5.08 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.539 | 1.487 | -0.05 |
| /error-in-render avg req/sec | 1624.36 | 1681.09 | +56.73 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.72 kB | 3.72 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.37 kB | 9.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: 83a962013dec747dda626bf6160b4e54d414019b

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 83a962013dec747dda626bf6160b4e54d414019b

**test/integration/file-serving/test/index.test.js** 
- File Serving > dev mode > should prevent traversing with /%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25aftest-file.txt
- File Serving > dev mode > should prevent traversing with /%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259ctest-file.txt

<details>
<summary>Expand output</summary>

  ● File Serving › dev mode › should prevent traversing with /%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25af%25c0%25ae%25c0%25ae%25c0%25aftest-file.txt

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      24 |   // test base mount point `public/`
      25 |   const res = await fetchViaHTTP(appPort, path)
    > 26 |   expect(res.status === 400 || res.status === 404).toBe(true)
         |                                                    ^
      27 |   expect(await res.text()).toMatch(containRegex)
      28 |
      29 |   // test `/_next` mount point

      at expectStatus (integration/file-serving/test/index.test.js:26:52)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (integration/file-serving/test/index.test.js:837:5)

  ● File Serving › dev mode › should prevent traversing with /%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259c%25c0%25ae%25c0%25ae%25c1%259ctest-file.txt

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      24 |   // test base mount point `public/`
      25 |   const res = await fetchViaHTTP(appPort, path)
    > 26 |   expect(res.status === 400 || res.status === 404).toBe(true)
         |                                                    ^
      27 |   expect(await res.text()).toMatch(containRegex)
      28 |
      29 |   // test `/_next` mount point

      at expectStatus (integration/file-serving/test/index.test.js:26:52)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (integration/file-serving/test/index.test.js:1097:5)

</details>

**Comment by darshkpatel** [comment]
Should I fallback to `20ea370` or update `fileExists` to check readability? I believe the latter might have impact on performance

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 12s | 11.7s | -264ms |
| buildDurationCached | 4s | 3.8s | -194ms |
| nodeModulesSize | 46.5 MB | 46.5 MB | ⚠️ +642 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.934 | 1.934 | ✓ |
| / avg req/sec | 1292.65 | 1292.97 | +0.32 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.021 | 0.973 | -0.05 |
| /error-in-render avg req/sec | 2447.71 | 2568.59 | +120.88 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| index.html gzip | 560 B | 560 B | ✓ |
| link.html gzip | 569 B | 569 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 14.3s | 14.7s | ⚠️ +440ms |
| buildDurationCached | 5.5s | 5.6s | ⚠️ +157ms |
| nodeModulesSize | 46.5 MB | 46.5 MB | ⚠️ +642 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | -2 B |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.35 MB | 1.35 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.39 MB | 1.39 MB | ✓ |
| withRouter.js | 1.39 MB | 1.39 MB | ✓ |
| Overall change | 6.9 MB | 6.9 MB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| buildDuration | 10s | 9.8s | -196ms |
| buildDurationCached | 4.2s | 4.3s | ⚠️ +139ms |
| nodeModulesSize | 46.5 MB | 46.5 MB | ⚠️ +642 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.975 | 2.049 | ⚠️ +0.07 |
| / avg req/sec | 1265.84 | 1220.08 | ⚠️ -45.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.05 | 1.162 | ⚠️ +0.11 |
| /error-in-render avg req/sec | 2382.03 | 2152.01 | ⚠️ -230.02 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.72 kB | 3.72 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.37 kB | 9.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | darshkpatel/next.js fix/24772 | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: 3a63eff7f43ee104f267e27f06c9ed080ac950c3

**Comment by darshkpatel** [comment]
Found the culprit! The test fails because the response is 500 instead of 404.My mistake, Apologies. 
Screenshot 2021-05-08 at 10 45 46 AM

File: packages/next/server/lib/find-page-file.ts (hunk 1 above)
Comment (darshkpatel) [reply packages/next/server/lib/find-page-file.ts]: Done!

**Review by timneutkens — APPROVED** [review]
