### PR TITLE
[dynamicIO] cache tracking for import()

### LINKED ISSUE #72589: Bug/inconsistency with `dynamicIO` and dynamic imports
### Link to the code that reproduces this issue

https://github.com/amannn/nextjs-bug-repro-json-import-turbo/commit/011dc47eddfb59aaea7e5461dcde85139b908c2c

### To Reproduce

1. Clone https://github.com/amannn/nextjs-bug-repro-json-import-turbo/
2. `pnpm i`
3. `pnpm dev --turbo`

### Current vs. Expected behavior

When running with Turbo, this error message is printed:

Screenshot 2024-11-11 at 20 07 56

When running with webpack, there's no error.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64
  Available memory (MB): 16384
  Available CPU cores: 12
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.22
  pnpm: 9.12.3
Relevant Packages:
  next: 15.0.4-canary.5 // Latest available version is detected (15.0.4-canary.5).
  eslint-config-next: 15.0.4-canary.5
  react: 19.0.0-rc-66855b96-20241106
  react-dom: 19.0.0-rc-66855b96-20241106
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

dynamicIO

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lubieowoce**
This PR introduces some extra tracking which makes us treat `import(...)` like a call to a cached function. Thanks to this, `await import(...)` will no longer cause dynamicity errors in `dynamicIO`.
The motivation is the same as allowing `fs.readFileSync` -- if something is available on the server at prerender time, we don't consider it IO.

Fixes #72589
Closes #75132

### Implementation notes

The tracking is implemented via an SWC transform (`track_dynamic_imports.ts`) that turns `import(...)` into `trackDynamicImport(import(...))`.

`trackDynamicImport(promise)` tracks the promise globally, without using `workUnitStore.cacheSignal`. The prospective render subscribes to pending modules using `trackPendingModules(cacheSignal)`, which causes the prospective  render to wait for all `import()`s to finish before proceeding to the final render. The mechanism is analogous to `'use cache'`, but the "result" of an `import()` is stored *in the module cache* instead; when we invoke the `import()` again in the actual prerender, it will resolve at microtask-speed, like we need it to.

The transform is enabled for all modules that run server-side, both RSC and SSR, because the prerender runs both. This also includes route handlers, because we also use a `cacheSignal` when prerendering those.
Notably, we also instrument `import()` in `node_modules` to account for libraries that do lazy initialization.

I've also had to adjust the prospective client render in PPR mode to wait for `cacheSignal.cacheReady()` - otherwise, it wouldn't wait for `import()`s to resolve before doing the final client render, which'd subsequently cause a dynamicity error.
(we didn't need to wait for `cacheSignal` before, because all cached promises would've already been awaited in the server prerender)

Finally, we no longer need `warmFlightResponse`, because `trackPendingModules` already makes the `cacheSignal` wait for all loading chunks to finish, so we don't need to do it ahead of time.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 38a55f7d11165c243368b1a8d62862266e6d1ac9

`pnpm test-dev test/e2e/app-dir/non-root-project-monorepo/non-root-project-monorepo.test.ts`
- non-root-project-monorepo > source-maps > should work on RSC
- non-root-project-monorepo > source-maps > should work on SSR
- non-root-project-monorepo > source-maps > should work on client-side

<details>
<summary>Expand output</summary>

  ● non-root-project-monorepo › source-maps › should work on RSC

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `non-root-project-monorepo source-maps should work on RSC 1`

    - Snapshot  - 1
    + Received  + 1

    - app/separate-file.ts (1:11) @ Error
    + app/separate-file.ts (1:11) @ eval

      > 1 | throw new Error('Expected error')
          |           ^
        2 |

      89 |         } else {
      90 |           // TODO the function name is incorrect
    > 91 |           expect(await getRedboxSource(browser)).toMatchInlineSnapshot(`
         |                                                  ^
      92 |             "app/separate-file.ts (1:11) @ Error
      93 |
      94 |             > 1 | throw new Error('Expected error')

      at Object.toMatchInlineSnapshot (e2e/app-dir/non-root-project-monorepo/non-root-project-monorepo.test.ts:91:50)

  ● non-root-project-monorepo › source-maps › should work on RSC

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `non-root-project-monorepo source-maps should work on RSC 2`

    - Snapshot  - 3
    + Received  + 3

      <unknown>
      rsc)/./app/separate-file.ts (rsc://React/Server/file://<full-path>/apps/web/.next/server/app/source-maps-rsc/page.js
      __webpack_require__
      file://<full-path>/apps/web/.next/server/webpack-runtime.js
    - require
    + innerArrowFunction
      app/source-maps-rsc/page.tsx (14:3)
    - innerArrowFunction
    + innerFunction
      app/source-maps-rsc/page.tsx (10:3)
    - innerFunction
    + Page
      app/source-maps-rsc/page.tsx (4:5)

       98 |           // TODO webpack runtime code shouldn't be included in stack trace
       99 |           expect(normalizeStackTrace(await getRedboxCallStack(browser)))
    > 100 |             .toMatchInlineSnapshot(`
          |              ^
      101 |            "<unknown>
      102 |            rsc)/./app/separate-file.ts (rsc://React/Server/file://<full-path>/apps/web/.next/server/app/source-maps-rsc/page.js
      103 |            __webpack_require__

      at Object.toMatchInlineSnapshot (e2e/app-dir/non-root-project-monorepo/non-root-project-monorepo.test.ts:100:14)

  ● non-root-project-monorepo › source-maps › should work on SSR

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `non-root-project-monorepo source-maps should work on SSR 2`

    - Snapshot  - 3
    + Received  + 3

    @@ -4,11 +4,11 @@
      file://<full-path>/apps/web/.next/static/chunks/webpack.js (700:31)
      __webpack_require__
      file://<full-path>/apps/web/.next/static/chunks/webpack.js (37:33)
      fn
      file://<full-path>/apps/web/.next/static/chunks/webpack.js (357:21)
    - require
    + innerArrowFunction
      app/source-maps-ssr/page.tsx (16:3)
    - innerArrowFunction
    + innerFunction
      app/source-maps-ssr/page.tsx (12:3)
    - innerFunction
    + Page
      app/source-maps-ssr/page.tsx (6:5)

      147 |           // TODO webpack runtime code shouldn't be included in stack trace
      148 |           expect(normalizeStackTrace(await getRedboxCallStack(browser)))
    > 149 |             .toMatchInlineSnapshot(`
          |              ^
      150 |            "./app/separate-file.ts
      151 |            file://<full-path>/apps/web/.next/static/chunks/app/source-maps-ssr/page.js (27:1)
      152 |            options.factory

      at Object.toMatchInlineSnapshot (e2e/app-dir/non-root-project-monorepo/non-root-project-monorepo.test.ts:149:14)

  ● non-root-project-monorepo › source-maps › should work on client-side

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `non-root-project-monorepo source-maps should work on client-side 2`

    - Snapshot  - 3
    + Received  + 3

    @@ -4,11 +4,11 @@
      file://<full-path>/apps/web/.next/static/chunks/webpack.js (712:31)
      __webpack_require__
      file://<full-path>/apps/web/.next/static/chunks/webpack.js (37:33)
      fn
      file://<full-path>/apps/web/.next/static/chunks/webpack.js (369:21)
    - require
    + innerArrowFunction
      app/source-maps-client/page.tsx (17:3)
    - innerArrowFunction
    + innerFunction
      app/source-maps-client/page.tsx (13:3)
    - innerFunction
    + effectCallback
      app/source-maps-client/page.tsx (7:5)

      200 |           // TODO webpack runtime code shouldn't be included in stack trace
      201 |           expect(normalizeStackTrace(await getRedboxCallStack(browser)))
    > 202 |             .toMatchInlineSnapshot(`
          |              ^
      203 |             "./app/separate-file.ts
      204 |             file://<full-path>/apps/web/.next/static/chunks/app/source-maps-client/page.js (27:1)
      205 |             options.factory

      at Object.toMatchInlineSnapshot (e2e/app-dir/non-root-project-monorepo/non-root-project-monorepo.test.ts:202:14)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by lubieowoce** [comment]
* **#75397** <a href="https://app.graphite.dev/github/pr/vercel/next.js/75397?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#74152** <a href="https://app.graphite.dev/github/pr/vercel/next.js/74152?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/vercel/next.js/74152?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/next/src/lib/scheduler.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ export type SchedulerFn<T = void> = (cb: ScheduledFn<T>) => void
  *
  * @param cb the function to schedule
  */
-export const scheduleOnNextTick = <T = void>(cb: ScheduledFn<T>): void => {
+export const scheduleOnNextTick = (cb: ScheduledFn<void>) => {
```
Comment (lubieowoce) [inline packages/next/src/lib/scheduler.ts:10]: just some drive-by cleanups, the `T` param is unnecessary because it doesn't ever make sense to return a value here

File: .gitignore [hunk 2]
```diff
@@ -28,7 +28,7 @@ pids
 coverage
 
 # test output
-test/**/out*
+test/**/out/*
```
Comment (lubieowoce) [inline .gitignore:31]: the previous pattern matched `outside-of-render` which is a folder name i used in one of the tests

File: test/e2e/app-dir/dynamic-io-dynamic-imports/dynamic-io-dynamic-imports.test.ts [hunk 3]
```diff
@@ -0,0 +1,161 @@
...
+      it('import of module with top-level-await', async () => {
+        await testPage('/outside-of-render/client/async-module')
+      })
+    })
+  })
+
+  // TODO:
+  // - imports inside an external
+  // likely to fail:
+  // - unawaited import with a tasky delay (and nothing else to delay `cacheSignal`)
```
Comment (unstubbable) [inline test/e2e/app-dir/dynamic-io-dynamic-imports/dynamic-io-dynamic-imports.test.ts:160]: second TODO is obsolete, right? what about the first one?

**Review by unstubbable — COMMENTED** [review]
Looks good overall! Just added a couple of minor nits and questions.

File: test/e2e/app-dir/dynamic-io-dynamic-imports/dynamic-io-dynamic-imports.test.ts (hunk 3 above)
Comment (lubieowoce) [reply test/e2e/app-dir/dynamic-io-dynamic-imports/dynamic-io-dynamic-imports.test.ts:160]: yeah the latter is just dynamic behavior so no need to test it again here

not 100% sure what to do re: imports in an external. we won't transform them (they're in an external) so i suppose it'd just have to be a failing test?

Comment (lubieowoce) [reply test/e2e/app-dir/dynamic-io-dynamic-imports/dynamic-io-dynamic-imports.test.ts]: added a test that expects `import()` in an external to fail in DIO, i guess that makes sense for now.

File: crates/next-custom-transforms/src/transforms/track_dynamic_imports.rs [hunk 4]
```diff
@@ -0,0 +1,143 @@
...
+            wrapper_function_local_ident: private_ident!("$$trackDynamicImport__"),
+        }
+    }
+}
+
+impl<C> VisitMut for ImportReplacer<C>
+where
+    C: Comments,
+{
+    noop_visit_mut_type!(); // TODO: what does this do?
```
[the remark this answers is not in the document]
Comment (unstubbable) [reply crates/next-custom-transforms/src/transforms/track_dynamic_imports.rs:32]: As discussed offline, it's apparently used to short-circuit visiting any TypeScript AST nodes. I think we can just remove the TODO comment.

**Review by unstubbable — APPROVED** [review]
