### PR TITLE
Expose manifest.js.map during development

### LINKED ISSUE #3748: Error 404 SourceMap Next5
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (i don't know if bugs)

1. Upgrade to version 5 of next
2. In dev mode the terminal tells me the 404 error of the js source map
3. Keep running my application, but the message bothers me, I do not know if it's ok

## Context

My big mental problem, is not knowing if this is a normal behavior or I have something wrong with my next application configuration or in the browser.
Terminal:

DONE  Compiled successfully in 3408ms
"GET /_next/-/manifest.js.map HTTP/1.1" 404 Chrome/63.0.3239.132 Safari/537.36
"GET /_next/-/commons.js.map HTTP/1.1" 404 Chrome/63.0.3239.132 Safari/537.36
"GET /_next/-/main.js.map HTTP/1.1" 404 Chrome/63.0.3239.132 Safari/537.36

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     v5.0.0    |
| node    |    v8.9.4     |
| OS      |   macos sierra      |
| browser |     google chrome    |

### PR DESCRIPTION
**Pull request by ptomasroos**
Closes #3748

### CODE REVIEW

File: server/index.js [hunk 1]
```diff
@@ -166,6 +166,14 @@ export default class Server {
         await this.serveStatic(req, res, p)
       },
 
+      '/_next/:buildId/manifest.js.map': async (req, res, params) => {
+        if (!this.dev) return this.send404(res)
```
Comment (timneutkens) [inline server/index.js]: I don't think this is needed 🤔

Comment (timneutkens) [reply server/index.js]: Actually makes sense since it's dev only 👍

**Review by timneutkens — APPROVED** [review]

**Review by timneutkens — APPROVED** [review]

File: server/index.js [hunk 2]
```diff
@@ -166,6 +166,14 @@ export default class Server {
...
+
+        this.handleBuildId(params.buildId, res)
+        const p = join(this.dir, this.dist, 'manifest.js.map')
```
Comment (albinekb) [inline server/index.js]: I would just spell it out `const path = ...`, `p` is hard to understand :)
