### PR TITLE
Fix image related link prop warning with react 18 beta

### LINKED ISSUE #31892: Warning: Invalid DOM property `imagesizes`. Did you mean `imageSizes`?
### What version of Next.js are you using?

12.0.5-canary.10

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Screenshot 2021-11-29 at 00 15 36

### Expected Behavior

No Warning should be there

### To Reproduce

Create a new nextjs project

my next.config.js
```
const moduleExports = {
  images: {
    deviceSizes: [640],
    domains: ["avatars.dicebear.com"],
    formats: ["image/avif", "image/webp"],
  },
  createRoot: true,
  swcMinify: false,
  experimental: {
    reactRoot: true,
    // concurrentFeatures: true,
    // serverComponents: true,
  },
};

module.exports = moduleExports;
```

### PR DESCRIPTION
**Pull request by huozhi**
## Bug

Fixes #31892 

react 18: requires camelcase for those props 
```
Warning: Invalid DOM property `imagesrcset`. Did you mean `imageSrcSet`
```
react 17: requires lowercase for those props

```
Warning: React does not recognize the `imageSrcSet` prop on a DOM element.
```

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

### Utils

* Add command `yarn next-react-18 test/integration/any-react-18-app/`
* Add util `withReact18`

```js
const withReact18 = require('../../react-18/test/with-react-18')

module.exports = withReact18({
  experimental: {
    concurrentFeatures: true,
  },
})
```

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| buildDuration | 20.6s | 20.7s | ⚠️ +59ms |
| buildDurationCached | 3.8s | 3.9s | ⚠️ +87ms |
| nodeModulesSize | 346 MB | 346 MB | ⚠️ +651 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.359 | 3.427 | ⚠️ +0.07 |
| / avg req/sec | 744.26 | 729.57 | ⚠️ -14.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.551 | 1.583 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1612.05 | 1579.05 | ⚠️ -33 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.45 kB | 4.52 kB | ⚠️ +71 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ⚠️ +71 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 459 B | -1 B |
| Overall change | 460 B | 459 B | -1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-a63607dde045e008.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-678af336607f5345.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -37,6 +37,19 @@
           return arr2;
         }
       }
+      function _defineProperty(obj, key, value) {
+        if (key in obj) {
+          Object.defineProperty(obj, key, {
+            value: value,
+            enumerable: true,
+            configurable: true,
+            writable: true
+          });
+        } else {
+          obj[key] = value;
+        }
+        return obj;
+      }
       function _iterableToArray(iter) {
         if (
           Symbol.iterator in Object(iter) ||
@@ -101,7 +114,7 @@
       var _toBase64 = __webpack_require__(6978);
       var _imageConfig = __webpack_require__(5809);
       var _useIntersection = __webpack_require__(7190);
-      function _defineProperty(obj, key, value) {
+      function _defineProperty1(obj, key, value) {
         if (key in obj) {
           Object.defineProperty(obj, key, {
             value: value,
@@ -137,7 +150,7 @@
               );
             }
             ownKeys.forEach(function(key) {
-              _defineProperty(target, key, source[key]);
+              _defineProperty1(target, key, source[key]);
             });
           };
         for (var i = 1; i < arguments.length; i++) _loop(i);
@@ -403,6 +416,7 @@
           img.onload = handleLoad;
         }
       }
+      var _obj;
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -624,6 +638,17 @@
         if (false) {
           var fullUrl;
         }
+        var imageSrcSetPropName = "imageSrcSet";
+        var imageSizesPropName = "imageSizes";
+        if (true) {
+          imageSrcSetPropName = imageSrcSetPropName.toLowerCase();
+          imageSizesPropName = imageSizesPropName.toLowerCase();
+        }
+        var linkProps =
+          ((_obj = {}), // @ts-ignore: imagesrcset is not yet in the link element type.
+          _defineProperty(_obj, imageSrcSetPropName, imgAttributes.srcSet), // @ts-ignore: imagesizes is not yet in the link element type.
+          _defineProperty(_obj, imageSizesPropName, imgAttributes.sizes),
+          _obj);
         return /*#__PURE__*/ _react.default.createElement(
           "span",
           {
@@ -711,20 +736,22 @@
               /*#__PURE__*/ _react.default.createElement(
                 _head.default,
                 null,
-                /*#__PURE__*/ _react.default.createElement("link", {
-                  key:
-                    "__nimg-" +
-                    imgAttributes.src +
-                    imgAttributes.srcSet +
-                    imgAttributes.sizes,
-                  rel: "preload",
-                  as: "image",
-                  href: imgAttributes.srcSet ? undefined : imgAttributes.src,
-                  // @ts-ignore: imagesrcset is not yet in the link element type.
-                  imagesrcset: imgAttributes.srcSet,
-                  // @ts-ignore: imagesizes is not yet in the link element type.
-                  imagesizes: imgAttributes.sizes
-                })
+                /*#__PURE__*/ _react.default.createElement(
+                  "link",
+                  Object.assign(
+                    {
+                      key:
+                        "__nimg-" +
+                        imgAttributes.src +
+                        imgAttributes.srcSet +
+                        imgAttributes.sizes,
+                      rel: "preload",
+                      as: "image",
+                      href: imgAttributes.srcSet ? undefined : imgAttributes.src
+                    },
+                    linkProps
+                  )
+                )
               )
             : null
         );
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| buildDuration | 22.5s | 23.1s | ⚠️ +601ms |
| buildDurationCached | 3.9s | 3.9s | ⚠️ +72ms |
| nodeModulesSize | 346 MB | 346 MB | ⚠️ +651 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.381 | 3.567 | ⚠️ +0.19 |
| / avg req/sec | 739.49 | 700.8 | ⚠️ -38.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.551 | 1.734 | ⚠️ +0.18 |
| /error-in-render avg req/sec | 1611.5 | 1441.89 | ⚠️ -169.61 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.47 kB | 4.55 kB | ⚠️ +86 B |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.3 kB | ⚠️ +86 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-a63607dde045e008.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-678af336607f5345.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -37,6 +37,19 @@
           return arr2;
         }
       }
+      function _defineProperty(obj, key, value) {
+        if (key in obj) {
+          Object.defineProperty(obj, key, {
+            value: value,
+            enumerable: true,
+            configurable: true,
+            writable: true
+          });
+        } else {
+          obj[key] = value;
+        }
+        return obj;
+      }
       function _iterableToArray(iter) {
         if (
           Symbol.iterator in Object(iter) ||
@@ -101,7 +114,7 @@
       var _toBase64 = __webpack_require__(6978);
       var _imageConfig = __webpack_require__(5809);
       var _useIntersection = __webpack_require__(7190);
-      function _defineProperty(obj, key, value) {
+      function _defineProperty1(obj, key, value) {
         if (key in obj) {
           Object.defineProperty(obj, key, {
             value: value,
@@ -137,7 +150,7 @@
               );
             }
             ownKeys.forEach(function(key) {
-              _defineProperty(target, key, source[key]);
+              _defineProperty1(target, key, source[key]);
             });
           };
         for (var i = 1; i < arguments.length; i++) _loop(i);
@@ -403,6 +416,7 @@
           img.onload = handleLoad;
         }
       }
+      var _obj;
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -624,6 +638,17 @@
         if (false) {
           var fullUrl;
         }
+        var imageSrcSetPropName = "imageSrcSet";
+        var imageSizesPropName = "imageSizes";
+        if (true) {
+          imageSrcSetPropName = imageSrcSetPropName.toLowerCase();
+          imageSizesPropName = imageSizesPropName.toLowerCase();
+        }
+        var linkProps =
+          ((_obj = {}), // @ts-ignore: imagesrcset is not yet in the link element type.
+          _defineProperty(_obj, imageSrcSetPropName, imgAttributes.srcSet), // @ts-ignore: imagesizes is not yet in the link element type.
+          _defineProperty(_obj, imageSizesPropName, imgAttributes.sizes),
+          _obj);
         return /*#__PURE__*/ _react.default.createElement(
           "span",
           {
@@ -711,20 +736,22 @@
               /*#__PURE__*/ _react.default.createElement(
                 _head.default,
                 null,
-                /*#__PURE__*/ _react.default.createElement("link", {
-                  key:
-                    "__nimg-" +
-                    imgAttributes.src +
-                    imgAttributes.srcSet +
-                    imgAttributes.sizes,
-                  rel: "preload",
-                  as: "image",
-                  href: imgAttributes.srcSet ? undefined : imgAttributes.src,
-                  // @ts-ignore: imagesrcset is not yet in the link element type.
-                  imagesrcset: imgAttributes.srcSet,
-                  // @ts-ignore: imagesizes is not yet in the link element type.
-                  imagesizes: imgAttributes.sizes
-                })
+                /*#__PURE__*/ _react.default.createElement(
+                  "link",
+                  Object.assign(
+                    {
+                      key:
+                        "__nimg-" +
+                        imgAttributes.src +
+                        imgAttributes.srcSet +
+                        imgAttributes.sizes,
+                      rel: "preload",
+                      as: "image",
+                      href: imgAttributes.srcSet ? undefined : imgAttributes.src
+                    },
+                    linkProps
+                  )
+                )
               )
             : null
         );
```
</details>
</details>
Commit: 1b98afcdc23707c550a9bd42475824823691b610

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| buildDuration | 21.1s | 21s | -88ms |
| buildDurationCached | 3.9s | 3.9s | ⚠️ +9ms |
| nodeModulesSize | 346 MB | 346 MB | ⚠️ +592 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.395 | 3.356 | -0.04 |
| / avg req/sec | 736.4 | 744.83 | +8.43 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.523 | 1.612 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 1641.72 | 1550.75 | ⚠️ -90.97 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.45 kB | 4.52 kB | ⚠️ +71 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ⚠️ +71 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 459 B | -1 B |
| Overall change | 460 B | 459 B | -1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-d57ede3ffd4e5f8b.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-678af336607f5345.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -37,6 +37,19 @@
           return arr2;
         }
       }
+      function _defineProperty(obj, key, value) {
+        if (key in obj) {
+          Object.defineProperty(obj, key, {
+            value: value,
+            enumerable: true,
+            configurable: true,
+            writable: true
+          });
+        } else {
+          obj[key] = value;
+        }
+        return obj;
+      }
       function _iterableToArray(iter) {
         if (
           Symbol.iterator in Object(iter) ||
@@ -101,7 +114,7 @@
       var _toBase64 = __webpack_require__(6978);
       var _imageConfig = __webpack_require__(5809);
       var _useIntersection = __webpack_require__(7190);
-      function _defineProperty(obj, key, value) {
+      function _defineProperty1(obj, key, value) {
         if (key in obj) {
           Object.defineProperty(obj, key, {
             value: value,
@@ -137,7 +150,7 @@
               );
             }
             ownKeys.forEach(function(key) {
-              _defineProperty(target, key, source[key]);
+              _defineProperty1(target, key, source[key]);
             });
           };
         for (var i = 1; i < arguments.length; i++) _loop(i);
@@ -403,6 +416,7 @@
           img.onload = handleLoad;
         }
       }
+      var _obj;
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -624,6 +638,17 @@
         if (false) {
           var fullUrl;
         }
+        var imageSrcSetPropName = "imageSrcSet";
+        var imageSizesPropName = "imageSizes";
+        if (true) {
+          imageSrcSetPropName = imageSrcSetPropName.toLowerCase();
+          imageSizesPropName = imageSizesPropName.toLowerCase();
+        }
+        var linkProps =
+          ((_obj = {}), // Note: imagesrcset and imagesizes are not in the link element type with react 17.
+          _defineProperty(_obj, imageSrcSetPropName, imgAttributes.srcSet),
+          _defineProperty(_obj, imageSizesPropName, imgAttributes.sizes),
+          _obj);
         return /*#__PURE__*/ _react.default.createElement(
           "span",
           {
@@ -711,20 +736,22 @@
               /*#__PURE__*/ _react.default.createElement(
                 _head.default,
                 null,
-                /*#__PURE__*/ _react.default.createElement("link", {
-                  key:
-                    "__nimg-" +
-                    imgAttributes.src +
-                    imgAttributes.srcSet +
-                    imgAttributes.sizes,
-                  rel: "preload",
-                  as: "image",
-                  href: imgAttributes.srcSet ? undefined : imgAttributes.src,
-                  // @ts-ignore: imagesrcset is not yet in the link element type.
-                  imagesrcset: imgAttributes.srcSet,
-                  // @ts-ignore: imagesizes is not yet in the link element type.
-                  imagesizes: imgAttributes.sizes
-                })
+                /*#__PURE__*/ _react.default.createElement(
+                  "link",
+                  Object.assign(
+                    {
+                      key:
+                        "__nimg-" +
+                        imgAttributes.src +
+                        imgAttributes.srcSet +
+                        imgAttributes.sizes,
+                      rel: "preload",
+                      as: "image",
+                      href: imgAttributes.srcSet ? undefined : imgAttributes.src
+                    },
+                    linkProps
+                  )
+                )
               )
             : null
         );
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| buildDuration | 23s | 22.7s | -229ms |
| buildDurationCached | 4s | 3.9s | -118ms |
| nodeModulesSize | 346 MB | 346 MB | ⚠️ +592 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.409 | 3.378 | -0.03 |
| / avg req/sec | 733.39 | 739.98 | +6.59 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.568 | 1.614 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1594.21 | 1549.05 | ⚠️ -45.16 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.47 kB | 4.55 kB | ⚠️ +86 B |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.3 kB | ⚠️ +86 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-d57ede3ffd4e5f8b.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-678af336607f5345.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -37,6 +37,19 @@
           return arr2;
         }
       }
+      function _defineProperty(obj, key, value) {
+        if (key in obj) {
+          Object.defineProperty(obj, key, {
+            value: value,
+            enumerable: true,
+            configurable: true,
+            writable: true
+          });
+        } else {
+          obj[key] = value;
+        }
+        return obj;
+      }
       function _iterableToArray(iter) {
         if (
           Symbol.iterator in Object(iter) ||
@@ -101,7 +114,7 @@
       var _toBase64 = __webpack_require__(6978);
       var _imageConfig = __webpack_require__(5809);
       var _useIntersection = __webpack_require__(7190);
-      function _defineProperty(obj, key, value) {
+      function _defineProperty1(obj, key, value) {
         if (key in obj) {
           Object.defineProperty(obj, key, {
             value: value,
@@ -137,7 +150,7 @@
               );
             }
             ownKeys.forEach(function(key) {
-              _defineProperty(target, key, source[key]);
+              _defineProperty1(target, key, source[key]);
             });
           };
         for (var i = 1; i < arguments.length; i++) _loop(i);
@@ -403,6 +416,7 @@
           img.onload = handleLoad;
         }
       }
+      var _obj;
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -624,6 +638,17 @@
         if (false) {
           var fullUrl;
         }
+        var imageSrcSetPropName = "imageSrcSet";
+        var imageSizesPropName = "imageSizes";
+        if (true) {
+          imageSrcSetPropName = imageSrcSetPropName.toLowerCase();
+          imageSizesPropName = imageSizesPropName.toLowerCase();
+        }
+        var linkProps =
+          ((_obj = {}), // Note: imagesrcset and imagesizes are not in the link element type with react 17.
+          _defineProperty(_obj, imageSrcSetPropName, imgAttributes.srcSet),
+          _defineProperty(_obj, imageSizesPropName, imgAttributes.sizes),
+          _obj);
         return /*#__PURE__*/ _react.default.createElement(
           "span",
           {
@@ -711,20 +736,22 @@
               /*#__PURE__*/ _react.default.createElement(
                 _head.default,
                 null,
-                /*#__PURE__*/ _react.default.createElement("link", {
-                  key:
-                    "__nimg-" +
-                    imgAttributes.src +
-                    imgAttributes.srcSet +
-                    imgAttributes.sizes,
-                  rel: "preload",
-                  as: "image",
-                  href: imgAttributes.srcSet ? undefined : imgAttributes.src,
-                  // @ts-ignore: imagesrcset is not yet in the link element type.
-                  imagesrcset: imgAttributes.srcSet,
-                  // @ts-ignore: imagesizes is not yet in the link element type.
-                  imagesizes: imgAttributes.sizes
-                })
+                /*#__PURE__*/ _react.default.createElement(
+                  "link",
+                  Object.assign(
+                    {
+                      key:
+                        "__nimg-" +
+                        imgAttributes.src +
+                        imgAttributes.srcSet +
+                        imgAttributes.sizes,
+                      rel: "preload",
+                      as: "image",
+                      href: imgAttributes.srcSet ? undefined : imgAttributes.src
+                    },
+                    linkProps
+                  )
+                )
               )
             : null
         );
```
</details>
</details>
Commit: f90fd222a4e485c425d1285c92d7ca9311cdc901

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f90fd222a4e485c425d1285c92d7ca9311cdc901

**test/integration/react-18/test/index.test.js** 
- React 18 Support > Use legacy render > supported version of react in dev
- React 18 Support > Use legacy render > supported version of react in build
- React 18 Support > Use legacy render > suspense is not allowed in blocking rendering mode (prod)

<details>
<summary>Expand output</summary>

  ● React 18 Support › Use legacy render › supported version of react in dev

    expect(received).not.toMatch(expected)

    Expected substring: not "Using the createRoot API for React"
    Received string:        "ready - started server on 0.0.0.0:35311, url: http://localhost:35311
    info  - Using the createRoot API for React
    event - compiled client and server successfully in 3.7s (168 modules)
    warn  - You have enabled experimental feature(s).
    warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

    warn  - You have to use React 18 to use `experimental.reactRoot`.
    "

      59 |
      60 | describe('React 18 Support', () => {
    > 61 |   describe('Use legacy render', () => {
         |                                ^
      62 |     beforeAll(async () => {
      63 |       await fs.remove(join(appDir, 'node_modules'))
      64 |       nextConfig.replace('reactRoot: true', '// reactRoot: true')

      at Object.<anonymous> (integration/react-18/test/index.test.js:61:32)

  ● React 18 Support › Use legacy render › supported version of react in build

    expect(received).not.toMatch(expected)

    Expected substring: not "Using the createRoot API for React"
    Received string:        "info  - Checking validity of types...
    info  - Creating an optimized production build...
    info  - Using the createRoot API for React
    info  - Compiled successfully
    info  - Collecting page data...
    info  - Generating static pages (0/9)
    info  - Generating static pages (2/9)
    info  - Generating static pages (4/9)
    info  - Generating static pages (6/9)
    info  - Generating static pages (9/9)
    info  - Finalizing page optimization...

    Page                                       Size     First Load JS
    ┌ ○ /                                      4.39 kB        79.3 kB
    ├   /_app                                  0 B            74.9 kB
    ├ ○ /404                                   195 B          75.1 kB
    ├ λ /ssr                                   255 B          75.1 kB
    ├ λ /suspense/backpressure                 411 B          75.3 kB
    ├ ○ /suspense/no-preload                   2.34 kB        77.2 kB
    ├ ○ /suspense/no-thrown                    2.37 kB        77.2 kB
    ├ ○ /suspense/thrown                       2.37 kB        77.2 kB
    ├ ○ /suspense/typing                       2.29 kB        77.2 kB
    ├ ○ /suspense/unwrapped                    2.3 kB         77.2 kB
    └ ○ /use-id                                286 B          75.2 kB
    + First Load JS shared by all              74.9 kB
      ├ chunks/framework-09b6cbaf12e61211.js   1.89 kB
      ├ chunks/main-c899a3485de782d1.js        70.5 kB
      ├ chunks/pages/_app-b03ed3ebdb6f4317.js  1.03 kB
      └ chunks/webpack-fabc6d93ba0613c1.js     1.46 kB

    λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
    ○  (Static)  automatically rendered as static HTML (uses no initial props)

    warn  - You have enabled experimental feature(s).
    warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

    warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
    warn  - You have to use React 18 to use `experimental.reactRoot`.
    "

      64 |       nextConfig.replace('reactRoot: true', '// reactRoot: true')
      65 |     })
    > 66 |     afterAll(() => {
         |                     ^
      67 |       nextConfig.replace('// reactRoot: true', 'reactRoot: true')
      68 |     })
      69 |

      at Object.<anonymous> (integration/react-18/test/index.test.js:66:32)

  ● React 18 Support › Use legacy render › suspense is not allowed in blocking rendering mode (prod)

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      72 |       expect(output).not.toMatch(USING_CREATE_ROOT)
      73 |       expect(output).not.toMatch(UNSUPPORTED_PRERELEASE)
    > 74 |     })
         |       ^
      75 |
      76 |     test('supported version of react in build', async () => {
      77 |       const output = await getBuildOutput(appDir)

      at Object.<anonymous> (integration/react-18/test/index.test.js:74:26)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| buildDuration | 17.5s | 17.5s | -25ms |
| buildDurationCached | 3.3s | 3.2s | -44ms |
| nodeModulesSize | 346 MB | 346 MB | ⚠️ +580 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.745 | 2.726 | -0.02 |
| / avg req/sec | 910.91 | 917.22 | +6.31 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.161 | 1.155 | -0.01 |
| /error-in-render avg req/sec | 2152.66 | 2164.38 | +11.72 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.45 kB | 4.52 kB | ⚠️ +71 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ⚠️ +71 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 459 B | -1 B |
| Overall change | 460 B | 459 B | -1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-d57ede3ffd4e5f8b.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-678af336607f5345.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -37,6 +37,19 @@
           return arr2;
         }
       }
+      function _defineProperty(obj, key, value) {
+        if (key in obj) {
+          Object.defineProperty(obj, key, {
+            value: value,
+            enumerable: true,
+            configurable: true,
+            writable: true
+          });
+        } else {
+          obj[key] = value;
+        }
+        return obj;
+      }
       function _iterableToArray(iter) {
         if (
           Symbol.iterator in Object(iter) ||
@@ -101,7 +114,7 @@
       var _toBase64 = __webpack_require__(6978);
       var _imageConfig = __webpack_require__(5809);
       var _useIntersection = __webpack_require__(7190);
-      function _defineProperty(obj, key, value) {
+      function _defineProperty1(obj, key, value) {
         if (key in obj) {
           Object.defineProperty(obj, key, {
             value: value,
@@ -137,7 +150,7 @@
               );
             }
             ownKeys.forEach(function(key) {
-              _defineProperty(target, key, source[key]);
+              _defineProperty1(target, key, source[key]);
             });
           };
         for (var i = 1; i < arguments.length; i++) _loop(i);
@@ -403,6 +416,7 @@
           img.onload = handleLoad;
         }
       }
+      var _obj;
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -624,6 +638,17 @@
         if (false) {
           var fullUrl;
         }
+        var imageSrcSetPropName = "imageSrcSet";
+        var imageSizesPropName = "imageSizes";
+        if (true) {
+          imageSrcSetPropName = imageSrcSetPropName.toLowerCase();
+          imageSizesPropName = imageSizesPropName.toLowerCase();
+        }
+        var linkProps =
+          ((_obj = {}), // Note: imagesrcset and imagesizes are not in the link element type with react 17.
+          _defineProperty(_obj, imageSrcSetPropName, imgAttributes.srcSet),
+          _defineProperty(_obj, imageSizesPropName, imgAttributes.sizes),
+          _obj);
         return /*#__PURE__*/ _react.default.createElement(
           "span",
           {
@@ -711,20 +736,22 @@
               /*#__PURE__*/ _react.default.createElement(
                 _head.default,
                 null,
-                /*#__PURE__*/ _react.default.createElement("link", {
-                  key:
-                    "__nimg-" +
-                    imgAttributes.src +
-                    imgAttributes.srcSet +
-                    imgAttributes.sizes,
-                  rel: "preload",
-                  as: "image",
-                  href: imgAttributes.srcSet ? undefined : imgAttributes.src,
-                  // @ts-ignore: imagesrcset is not yet in the link element type.
-                  imagesrcset: imgAttributes.srcSet,
-                  // @ts-ignore: imagesizes is not yet in the link element type.
-                  imagesizes: imgAttributes.sizes
-                })
+                /*#__PURE__*/ _react.default.createElement(
+                  "link",
+                  Object.assign(
+                    {
+                      key:
+                        "__nimg-" +
+                        imgAttributes.src +
+                        imgAttributes.srcSet +
+                        imgAttributes.sizes,
+                      rel: "preload",
+                      as: "image",
+                      href: imgAttributes.srcSet ? undefined : imgAttributes.src
+                    },
+                    linkProps
+                  )
+                )
               )
             : null
         );
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| buildDuration | 19.7s | 19.3s | -407ms |
| buildDurationCached | 3.2s | 3.2s | -9ms |
| nodeModulesSize | 346 MB | 346 MB | ⚠️ +580 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.74 | 2.757 | ⚠️ +0.02 |
| / avg req/sec | 912.38 | 906.93 | ⚠️ -5.45 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.164 | 1.161 | 0 |
| /error-in-render avg req/sec | 2147.15 | 2154.24 | +7.09 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.47 kB | 4.55 kB | ⚠️ +86 B |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.3 kB | ⚠️ +86 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-d57ede3ffd4e5f8b.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-678af336607f5345.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -37,6 +37,19 @@
           return arr2;
         }
       }
+      function _defineProperty(obj, key, value) {
+        if (key in obj) {
+          Object.defineProperty(obj, key, {
+            value: value,
+            enumerable: true,
+            configurable: true,
+            writable: true
+          });
+        } else {
+          obj[key] = value;
+        }
+        return obj;
+      }
       function _iterableToArray(iter) {
         if (
           Symbol.iterator in Object(iter) ||
@@ -101,7 +114,7 @@
       var _toBase64 = __webpack_require__(6978);
       var _imageConfig = __webpack_require__(5809);
       var _useIntersection = __webpack_require__(7190);
-      function _defineProperty(obj, key, value) {
+      function _defineProperty1(obj, key, value) {
         if (key in obj) {
           Object.defineProperty(obj, key, {
             value: value,
@@ -137,7 +150,7 @@
               );
             }
             ownKeys.forEach(function(key) {
-              _defineProperty(target, key, source[key]);
+              _defineProperty1(target, key, source[key]);
             });
           };
         for (var i = 1; i < arguments.length; i++) _loop(i);
@@ -403,6 +416,7 @@
           img.onload = handleLoad;
         }
       }
+      var _obj;
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -624,6 +638,17 @@
         if (false) {
           var fullUrl;
         }
+        var imageSrcSetPropName = "imageSrcSet";
+        var imageSizesPropName = "imageSizes";
+        if (true) {
+          imageSrcSetPropName = imageSrcSetPropName.toLowerCase();
+          imageSizesPropName = imageSizesPropName.toLowerCase();
+        }
+        var linkProps =
+          ((_obj = {}), // Note: imagesrcset and imagesizes are not in the link element type with react 17.
+          _defineProperty(_obj, imageSrcSetPropName, imgAttributes.srcSet),
+          _defineProperty(_obj, imageSizesPropName, imgAttributes.sizes),
+          _obj);
         return /*#__PURE__*/ _react.default.createElement(
           "span",
           {
@@ -711,20 +736,22 @@
               /*#__PURE__*/ _react.default.createElement(
                 _head.default,
                 null,
-                /*#__PURE__*/ _react.default.createElement("link", {
-                  key:
-                    "__nimg-" +
-                    imgAttributes.src +
-                    imgAttributes.srcSet +
-                    imgAttributes.sizes,
-                  rel: "preload",
-                  as: "image",
-                  href: imgAttributes.srcSet ? undefined : imgAttributes.src,
-                  // @ts-ignore: imagesrcset is not yet in the link element type.
-                  imagesrcset: imgAttributes.srcSet,
-                  // @ts-ignore: imagesizes is not yet in the link element type.
-                  imagesizes: imgAttributes.sizes
-                })
+                /*#__PURE__*/ _react.default.createElement(
+                  "link",
+                  Object.assign(
+                    {
+                      key:
+                        "__nimg-" +
+                        imgAttributes.src +
+                        imgAttributes.srcSet +
+                        imgAttributes.sizes,
+                      rel: "preload",
+                      as: "image",
+                      href: imgAttributes.srcSet ? undefined : imgAttributes.src
+                    },
+                    linkProps
+                  )
+                )
               )
             : null
         );
```
</details>
</details>
Commit: ca39e38f55d629d86a378190ded70c5a72f2a132

File: packages/next/client/image.tsx [hunk 1]
```diff
@@ -642,6 +642,18 @@ export default function Image({
     }
   }
 
+  let imageSrcSetPropName = 'imageSrcSet'
+  let imageSizesPropName = 'imageSizes'
+  if (!process.env.__NEXT_REACT_ROOT) {
```
Comment (ijjk) [inline packages/next/client/image.tsx:647]: Should we inverse this so that we don't include `if (true) { ... }` for all non-react root projects?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| buildDuration | 17.7s | 17.6s | -82ms |
| buildDurationCached | 3.2s | 3.3s | ⚠️ +62ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +503 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.808 | 2.808 | ✓ |
| / avg req/sec | 890.2 | 890.17 | ⚠️ -0.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.161 | 1.162 | 0 |
| /error-in-render avg req/sec | 2152.78 | 2151.27 | ⚠️ -1.51 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.45 kB | 4.49 kB | ⚠️ +45 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ⚠️ +45 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f207079640969086.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-678af336607f5345.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -37,6 +37,19 @@
           return arr2;
         }
       }
+      function _defineProperty(obj, key, value) {
+        if (key in obj) {
+          Object.defineProperty(obj, key, {
+            value: value,
+            enumerable: true,
+            configurable: true,
+            writable: true
+          });
+        } else {
+          obj[key] = value;
+        }
+        return obj;
+      }
       function _iterableToArray(iter) {
         if (
           Symbol.iterator in Object(iter) ||
@@ -101,7 +114,7 @@
       var _toBase64 = __webpack_require__(6978);
       var _imageConfig = __webpack_require__(5809);
       var _useIntersection = __webpack_require__(7190);
-      function _defineProperty(obj, key, value) {
+      function _defineProperty1(obj, key, value) {
         if (key in obj) {
           Object.defineProperty(obj, key, {
             value: value,
@@ -137,7 +150,7 @@
               );
             }
             ownKeys.forEach(function(key) {
-              _defineProperty(target, key, source[key]);
+              _defineProperty1(target, key, source[key]);
             });
           };
         for (var i = 1; i < arguments.length; i++) _loop(i);
@@ -403,6 +416,7 @@
           img.onload = handleLoad;
         }
       }
+      var _obj;
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -624,6 +638,15 @@
         if (false) {
           var fullUrl;
         }
+        var imageSrcSetPropName = "imagesrcset";
+        var imageSizesPropName = "imagesizes";
+        if (false) {
+        }
+        var linkProps =
+          ((_obj = {}), // Note: imagesrcset and imagesizes are not in the link element type with react 17.
+          _defineProperty(_obj, imageSrcSetPropName, imgAttributes.srcSet),
+          _defineProperty(_obj, imageSizesPropName, imgAttributes.sizes),
+          _obj);
         return /*#__PURE__*/ _react.default.createElement(
           "span",
           {
@@ -711,20 +734,22 @@
               /*#__PURE__*/ _react.default.createElement(
                 _head.default,
                 null,
-                /*#__PURE__*/ _react.default.createElement("link", {
-                  key:
-                    "__nimg-" +
-                    imgAttributes.src +
-                    imgAttributes.srcSet +
-                    imgAttributes.sizes,
-                  rel: "preload",
-                  as: "image",
-                  href: imgAttributes.srcSet ? undefined : imgAttributes.src,
-                  // @ts-ignore: imagesrcset is not yet in the link element type.
-                  imagesrcset: imgAttributes.srcSet,
-                  // @ts-ignore: imagesizes is not yet in the link element type.
-                  imagesizes: imgAttributes.sizes
-                })
+                /*#__PURE__*/ _react.default.createElement(
+                  "link",
+                  Object.assign(
+                    {
+                      key:
+                        "__nimg-" +
+                        imgAttributes.src +
+                        imgAttributes.srcSet +
+                        imgAttributes.sizes,
+                      rel: "preload",
+                      as: "image",
+                      href: imgAttributes.srcSet ? undefined : imgAttributes.src
+                    },
+                    linkProps
+                  )
+                )
               )
             : null
         );
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| buildDuration | 19s | 19.2s | ⚠️ +176ms |
| buildDurationCached | 3.3s | 3.3s | ⚠️ +1ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +503 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.736 | 2.795 | ⚠️ +0.06 |
| / avg req/sec | 913.84 | 894.52 | ⚠️ -19.32 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.18 | 1.142 | -0.04 |
| /error-in-render avg req/sec | 2118.99 | 2188.65 | +69.66 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.47 kB | 4.53 kB | ⚠️ +62 B |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.3 kB | ⚠️ +62 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 458 B | -1 B |
| Overall change | 459 B | 458 B | -1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f207079640969086.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-678af336607f5345.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -37,6 +37,19 @@
           return arr2;
         }
       }
+      function _defineProperty(obj, key, value) {
+        if (key in obj) {
+          Object.defineProperty(obj, key, {
+            value: value,
+            enumerable: true,
+            configurable: true,
+            writable: true
+          });
+        } else {
+          obj[key] = value;
+        }
+        return obj;
+      }
       function _iterableToArray(iter) {
         if (
           Symbol.iterator in Object(iter) ||
@@ -101,7 +114,7 @@
       var _toBase64 = __webpack_require__(6978);
       var _imageConfig = __webpack_require__(5809);
       var _useIntersection = __webpack_require__(7190);
-      function _defineProperty(obj, key, value) {
+      function _defineProperty1(obj, key, value) {
         if (key in obj) {
           Object.defineProperty(obj, key, {
             value: value,
@@ -137,7 +150,7 @@
               );
             }
             ownKeys.forEach(function(key) {
-              _defineProperty(target, key, source[key]);
+              _defineProperty1(target, key, source[key]);
             });
           };
         for (var i = 1; i < arguments.length; i++) _loop(i);
@@ -403,6 +416,7 @@
           img.onload = handleLoad;
         }
       }
+      var _obj;
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -624,6 +638,15 @@
         if (false) {
           var fullUrl;
         }
+        var imageSrcSetPropName = "imagesrcset";
+        var imageSizesPropName = "imagesizes";
+        if (false) {
+        }
+        var linkProps =
+          ((_obj = {}), // Note: imagesrcset and imagesizes are not in the link element type with react 17.
+          _defineProperty(_obj, imageSrcSetPropName, imgAttributes.srcSet),
+          _defineProperty(_obj, imageSizesPropName, imgAttributes.sizes),
+          _obj);
         return /*#__PURE__*/ _react.default.createElement(
           "span",
           {
@@ -711,20 +734,22 @@
               /*#__PURE__*/ _react.default.createElement(
                 _head.default,
                 null,
-                /*#__PURE__*/ _react.default.createElement("link", {
-                  key:
-                    "__nimg-" +
-                    imgAttributes.src +
-                    imgAttributes.srcSet +
-                    imgAttributes.sizes,
-                  rel: "preload",
-                  as: "image",
-                  href: imgAttributes.srcSet ? undefined : imgAttributes.src,
-                  // @ts-ignore: imagesrcset is not yet in the link element type.
-                  imagesrcset: imgAttributes.srcSet,
-                  // @ts-ignore: imagesizes is not yet in the link element type.
-                  imagesizes: imgAttributes.sizes
-                })
+                /*#__PURE__*/ _react.default.createElement(
+                  "link",
+                  Object.assign(
+                    {
+                      key:
+                        "__nimg-" +
+                        imgAttributes.src +
+                        imgAttributes.srcSet +
+                        imgAttributes.sizes,
+                      rel: "preload",
+                      as: "image",
+                      href: imgAttributes.srcSet ? undefined : imgAttributes.src
+                    },
+                    linkProps
+                  )
+                )
               )
             : null
         );
```
</details>
</details>
Commit: d0e407ca27265469c67bb37d92aa2283bb07e3c0

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| buildDuration | 20.7s | 21.3s | ⚠️ +644ms |
| buildDurationCached | 3.9s | 3.9s | ⚠️ +71ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +503 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.394 | 3.42 | ⚠️ +0.03 |
| / avg req/sec | 736.58 | 730.91 | ⚠️ -5.67 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.574 | 1.602 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1588.31 | 1560.07 | ⚠️ -28.24 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.45 kB | 4.49 kB | ⚠️ +45 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ⚠️ +45 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f207079640969086.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-678af336607f5345.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -37,6 +37,19 @@
           return arr2;
         }
       }
+      function _defineProperty(obj, key, value) {
+        if (key in obj) {
+          Object.defineProperty(obj, key, {
+            value: value,
+            enumerable: true,
+            configurable: true,
+            writable: true
+          });
+        } else {
+          obj[key] = value;
+        }
+        return obj;
+      }
       function _iterableToArray(iter) {
         if (
           Symbol.iterator in Object(iter) ||
@@ -101,7 +114,7 @@
       var _toBase64 = __webpack_require__(6978);
       var _imageConfig = __webpack_require__(5809);
       var _useIntersection = __webpack_require__(7190);
-      function _defineProperty(obj, key, value) {
+      function _defineProperty1(obj, key, value) {
         if (key in obj) {
           Object.defineProperty(obj, key, {
             value: value,
@@ -137,7 +150,7 @@
               );
             }
             ownKeys.forEach(function(key) {
-              _defineProperty(target, key, source[key]);
+              _defineProperty1(target, key, source[key]);
             });
           };
         for (var i = 1; i < arguments.length; i++) _loop(i);
@@ -403,6 +416,7 @@
           img.onload = handleLoad;
         }
       }
+      var _obj;
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -624,6 +638,15 @@
         if (false) {
           var fullUrl;
         }
+        var imageSrcSetPropName = "imagesrcset";
+        var imageSizesPropName = "imagesizes";
+        if (false) {
+        }
+        var linkProps =
+          ((_obj = {}), // Note: imagesrcset and imagesizes are not in the link element type with react 17.
+          _defineProperty(_obj, imageSrcSetPropName, imgAttributes.srcSet),
+          _defineProperty(_obj, imageSizesPropName, imgAttributes.sizes),
+          _obj);
         return /*#__PURE__*/ _react.default.createElement(
           "span",
           {
@@ -711,20 +734,22 @@
               /*#__PURE__*/ _react.default.createElement(
                 _head.default,
                 null,
-                /*#__PURE__*/ _react.default.createElement("link", {
-                  key:
-                    "__nimg-" +
-                    imgAttributes.src +
-                    imgAttributes.srcSet +
-                    imgAttributes.sizes,
-                  rel: "preload",
-                  as: "image",
-                  href: imgAttributes.srcSet ? undefined : imgAttributes.src,
-                  // @ts-ignore: imagesrcset is not yet in the link element type.
-                  imagesrcset: imgAttributes.srcSet,
-                  // @ts-ignore: imagesizes is not yet in the link element type.
-                  imagesizes: imgAttributes.sizes
-                })
+                /*#__PURE__*/ _react.default.createElement(
+                  "link",
+                  Object.assign(
+                    {
+                      key:
+                        "__nimg-" +
+                        imgAttributes.src +
+                        imgAttributes.srcSet +
+                        imgAttributes.sizes,
+                      rel: "preload",
+                      as: "image",
+                      href: imgAttributes.srcSet ? undefined : imgAttributes.src
+                    },
+                    linkProps
+                  )
+                )
               )
             : null
         );
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| buildDuration | 23.4s | 23.9s | ⚠️ +456ms |
| buildDurationCached | 4s | 3.9s | -131ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +503 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.552 | 3.529 | -0.02 |
| / avg req/sec | 703.84 | 708.42 | +4.58 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.606 | 1.693 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 1556.57 | 1476.28 | ⚠️ -80.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.47 kB | 4.53 kB | ⚠️ +62 B |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.3 kB | ⚠️ +62 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 458 B | -1 B |
| Overall change | 459 B | 458 B | -1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/camel-case-prop | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f207079640969086.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-678af336607f5345.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -37,6 +37,19 @@
           return arr2;
         }
       }
+      function _defineProperty(obj, key, value) {
+        if (key in obj) {
+          Object.defineProperty(obj, key, {
+            value: value,
+            enumerable: true,
+            configurable: true,
+            writable: true
+          });
+        } else {
+          obj[key] = value;
+        }
+        return obj;
+      }
       function _iterableToArray(iter) {
         if (
           Symbol.iterator in Object(iter) ||
@@ -101,7 +114,7 @@
       var _toBase64 = __webpack_require__(6978);
       var _imageConfig = __webpack_require__(5809);
       var _useIntersection = __webpack_require__(7190);
-      function _defineProperty(obj, key, value) {
+      function _defineProperty1(obj, key, value) {
         if (key in obj) {
           Object.defineProperty(obj, key, {
             value: value,
@@ -137,7 +150,7 @@
               );
             }
             ownKeys.forEach(function(key) {
-              _defineProperty(target, key, source[key]);
+              _defineProperty1(target, key, source[key]);
             });
           };
         for (var i = 1; i < arguments.length; i++) _loop(i);
@@ -403,6 +416,7 @@
           img.onload = handleLoad;
         }
       }
+      var _obj;
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -624,6 +638,15 @@
         if (false) {
           var fullUrl;
         }
+        var imageSrcSetPropName = "imagesrcset";
+        var imageSizesPropName = "imagesizes";
+        if (false) {
+        }
+        var linkProps =
+          ((_obj = {}), // Note: imagesrcset and imagesizes are not in the link element type with react 17.
+          _defineProperty(_obj, imageSrcSetPropName, imgAttributes.srcSet),
+          _defineProperty(_obj, imageSizesPropName, imgAttributes.sizes),
+          _obj);
         return /*#__PURE__*/ _react.default.createElement(
           "span",
           {
@@ -711,20 +734,22 @@
               /*#__PURE__*/ _react.default.createElement(
                 _head.default,
                 null,
-                /*#__PURE__*/ _react.default.createElement("link", {
-                  key:
-                    "__nimg-" +
-                    imgAttributes.src +
-                    imgAttributes.srcSet +
-                    imgAttributes.sizes,
-                  rel: "preload",
-                  as: "image",
-                  href: imgAttributes.srcSet ? undefined : imgAttributes.src,
-                  // @ts-ignore: imagesrcset is not yet in the link element type.
-                  imagesrcset: imgAttributes.srcSet,
-                  // @ts-ignore: imagesizes is not yet in the link element type.
-                  imagesizes: imgAttributes.sizes
-                })
+                /*#__PURE__*/ _react.default.createElement(
+                  "link",
+                  Object.assign(
+                    {
+                      key:
+                        "__nimg-" +
+                        imgAttributes.src +
+                        imgAttributes.srcSet +
+                        imgAttributes.sizes,
+                      rel: "preload",
+                      as: "image",
+                      href: imgAttributes.srcSet ? undefined : imgAttributes.src
+                    },
+                    linkProps
+                  )
+                )
               )
             : null
         );
```
</details>
</details>
Commit: 2948af9816480e28445561ab18616713601e5775
