### PR TITLE
Merge url query with exportPathMap

### LINKED ISSUE #4615: ctx.query undefined during dev and using exportPathMap
# Bug report

## Description of the bug

The `query` object `undefined`  missing from the `ctx` in `getInitialProps` during development. This causes exceptions to be thrown when expecting an object (rather than undefined).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://next6-queries-kvyvgbrmae.now.sh/?a=b
2. See that the `query` is missing from props.

Note: if the URL shows a 5xx error, it's because Next is running in dev mode on Now, which it doesn't really like! Here's the source for local testing: https://gist.github.com/remy/391923f938629436d671456d3e1234b7

[Source](https://zeit.co/rem/next6-queries/kvyvgbrmae/source) of `pages/index.js`:

```js
const Page = props => <pre>{JSON.stringify(props, '', 2)}</pre>;
export default Page;
```

## Expected behavior

I'd expect to see the page render:

```json
{
  "query": {
    "a": "b"
  },
  "url": {
    "pathname": "/",
    "asPath": "/?a=b"
  }
}
```

## System information
 - OS: macOS
 - Version of Next.js: 6.0.3

## Additional context

I've debugged through the compiled code and I _think_ it's due to the `exportPathMap` being used during development: https://github.com/zeit/next.js/blob/canary/server/index.js#L252-L258

I'm not quite sure how to work out which should win, but if I were to suggest, I'd expect the exportMap.query to merge with the URL query, giving priority to the URL query.

At the very least, it shouldn't be undefined, and I can see in the original server/index.js it tries to default to an empty object, but that isn't getting passed through - see screenshot of generated code:

screen shot 2018-06-16 at 10 43 56

### PR DESCRIPTION
**Pull request by lucleray**
This PR fixes #4615

From the issue :
> One thing we might consider is merging and showing a warning for keys not defined in exportPathMap

The behaviour after this PR is the following :

```js
// next.config.js
module.exports = {
  exportPathMap: () => ({
    '/': { page: '/', query: { a: 'blue' } }
  })
}
```

| url called | `ctx.query` | warning ? |
|-|-|-|
| `/` | `{ a: 'blue' }` | |
| `/?a=red` | `{ a: 'blue' }` | |
| `/?b=green` | `{ a: 'blue', b: 'green' }` | `... parameter 'b' missing in exportPathMap` |

Is that the expected behaviour ? If not, I'll update the PR to shape the expected behavior.

### CODE REVIEW

File: server/index.js [hunk 1]
```diff
@@ -254,7 +254,15 @@ export default class Server {
...
           const {page, query = {}} = exportPathMap[path]
           routes[path] = async (req, res, params, parsedUrl) => {
-            await this.render(req, res, page, query, parsedUrl)
+            const { query: urlQuery } = parsedUrl
+
+            Object.keys(urlQuery)
+              .filter(key => query[key] === undefined)
+              .forEach(key => console.warn(`Url defines a query parameter '${key}' that is missing in exportPathMap`))
+
+            const mergedQuery = Object.assign({}, urlQuery, query)
```
Comment (timneutkens) [inline server/index.js]: Lets do `{...urlQuery, ...query}` instead of `Object.assign`

**Review by timneutkens — APPROVED** [review]
Let's add a test for this new behavior 👍 can be added in test/integration/export

**Review by timneutkens — CHANGES_REQUESTED** [review]
My review was actually a request changes

**Comment by timneutkens** [comment]
I actually gave the wrong directory, `static` already has tests for `next export`.

**Comment by lucleray** [comment]
@timneutkens I added the tests for the 3 scenario in the PR's description.

I ran into the following problems while writing the tests :

### 1. `launchApp` / `killApp`
If I used `launchApp` from the `next-test-utils`, it was harder to catch `console.warn` call and the app wouldn't shut down properly.

`killApp` does kill the PID of the spawned process, here :
https://github.com/zeit/next.js/blob/7fcfb8bde91af096af6905ec8c426934f667f0b6/test/lib/next-test-utils.js#L102-L104

But it does not kill the PID of the "subprocess" spawned by the spawned process 💣 
Basically, `launchApp` spawn a new process : `next`, which spawns another new process : `next-dev`
They get PID and PID+1 (for example 44013 and 44014).
`killApp` only kills PID, but not PID+1. They would need to be both killed for `killApp` to work properly.

### 2. `startApp` / `stopApp` 
There is a bug in `stopApp`, I think.

More precisely here :

https://github.com/zeit/next.js/blob/7fcfb8bde91af096af6905ec8c426934f667f0b6/test/lib/next-test-utils.js#L116-L121

`app` is never touched.

### What I did

So I ended up simply using `start` and `stop` from `server/next`. Not sure it's the best thing to do for integration test. Let me know 🙂

**Comment by lucleray** [comment]
@timneutkens 
Oh, ok, I can move the tests to `static`

**Comment by timneutkens** [comment]
You actually don't have to test the console.log calls, just check loading the page with a querystring and `query` defined and see if it works. We don't test console.log side effects as they will most likely change in the future and can't break anything.

**Comment by lucleray** [comment]
I fixed the tests, I removed the test for console.log.

**Review by timneutkens — APPROVED** [review]
Looks great 👍
