### PR TITLE
Match data fetch and busting cache key when path URI encodes

### LINKED ISSUE #38581: Page was incorrectly cached when Route parameter contains `:`
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.4.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.3-canary.3
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Google Chrome Version 103.0.5060.114 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

```
npm run build
npm run start
```

### Describe the Bug

When the Route parameter contains the `:` character, page uses getServerSideProps will be incorrectly cached in the browser by next.js.

This is because an encoding error in `cacheKey` causing next.js unable to `delete _this.sdc[cacheKey]` (Server Data Cache)

https://github.com/vercel/next.js/blob/13557eac6fb599bb9b29c076c59c7117498ad0c5/packages/next/shared/lib/router/router.ts#L1841-L1847

### Expected Behavior

Even if Router parameter contains the `:` character, page uses getServerSideProps should not be cached.

### Link to reproduction

https://next-cache-test-fawn.vercel.app/

### To Reproduce

Click the second & fourth link repeatedly, the server generated content will not change because it's cached in browser.

**This is only reproducible in `production` build.**

I've disabled the minimize (`config.optimization.minimize = false`) to make it easy to debug.

Demo: https://next-cache-test-fawn.vercel.app/
Demo source: https://github.com/Coxxs/next-cache-test/commit/fe30c1abf8e713b601634fda3e1016d7ad02d77b

### PR DESCRIPTION
**Pull request by visnup**
Fixes #38581

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm lint`
- [ ] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

### CODE REVIEW

File: packages/next/shared/lib/router/router.ts [hunk 1]
```diff
@@ -1812,6 +1812,7 @@ export default class Router implements BaseRouter {
             : await fetchNextData({
                 dataHref: this.pageLoader.getDataHref({
                   href: formatWithValidation({ pathname, query }),
+                  skipInterpolation: true,
```
Comment (visnup) [inline packages/next/shared/lib/router/router.ts:1815]: This seemed like the most minimal change in order to match the generated cacheKey from https://github.com/vercel/next.js/blob/2633c1ef7a0de8b4b40d3f19aae5aae4f1a5d7cc/packages/next/shared/lib/router/router.ts#L1716-L1721

I'm unsure why this `fetchNextData` doesn't just outright use the `fetchNextDataParams` defined previously though? The key differences between the two currently are this `skipInterpolation` and `hasMiddleware: true`.

**Comment by visnup** [comment]
Anything I can do to make this easier to review or explain better?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| buildDuration | 22.4s | 22.8s | ⚠️ +358ms |
| buildDurationCached | 7.8s | 7.8s | -58ms |
| nodeModulesSize | 1.96 GB | 1.96 GB | ⚠️ +620 B |
| nextStartRea..uration (ms) | 324ms | 291ms | -33ms |
| nextDevReadyDuration | 316ms | 321ms | ⚠️ +5ms |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 9.055 | 9.095 | ⚠️ +0.04 |
| / avg req/sec | 276.08 | 274.89 | ⚠️ -1.19 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 5.957 | 6.091 | ⚠️ +0.13 |
| /error-in-render avg req/sec | 419.68 | 410.45 | ⚠️ -9.23 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| 900.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 45.3 kB | 45.3 kB | ✓ |
| main-HASH.js gzip | 31 kB | 31 kB | ⚠️ +21 B |
| webpack-HASH.js gzip | 1.54 kB | 1.54 kB | ✓ |
| Overall change | 78 kB | 78 kB | ⚠️ +21 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| _app-HASH.js gzip | 201 B | 202 B | ⚠️ +1 B |
| _error-HASH.js gzip | 195 B | 195 B | ✓ |
| amp-HASH.js gzip | 492 B | 493 B | ⚠️ +1 B |
| css-HASH.js gzip | 327 B | 329 B | ⚠️ +2 B |
| dynamic-HASH.js gzip | 2.01 kB | 2.01 kB | -1 B |
| edge-ssr-HASH.js gzip | 288 B | 287 B | -1 B |
| head-HASH.js gzip | 356 B | 355 B | -1 B |
| hooks-HASH.js gzip | 800 B | 800 B | ✓ |
| image-HASH.js gzip | 4.87 kB | 4.87 kB | -5 B |
| index-HASH.js gzip | 261 B | 263 B | ⚠️ +2 B |
| link-HASH.js gzip | 2.36 kB | 2.35 kB | -1 B |
| routerDirect..HASH.js gzip | 322 B | 321 B | -1 B |
| script-HASH.js gzip | 392 B | 391 B | -1 B |
| withRouter-HASH.js gzip | 320 B | 321 B | ⚠️ +1 B |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | -4 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 484 B | ⚠️ +3 B |
| Overall change | 481 B | 484 B | ⚠️ +3 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| index.html gzip | 511 B | 512 B | ⚠️ +1 B |
| link.html gzip | 525 B | 527 B | ⚠️ +2 B |
| withRouter.html gzip | 505 B | 507 B | ⚠️ +2 B |
| Overall change | 1.54 kB | 1.55 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Edge SSR Page bundle Size</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| edge-ssr.js gzip | 114 kB | 114 kB | -11 B |
| Overall change | 114 kB | 114 kB | -11 B |

</details>

<details>
<summary><strong>Middleware size</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 573 B | 575 B | ⚠️ +2 B |
| middleware-r..fest.js gzip | 145 B | 145 B | ✓ |
| middleware.js gzip | 17.9 kB | 17.9 kB | -6 B |
| edge-runtime..pack.js gzip | 1.83 kB | 1.83 kB | ✓ |
| Overall change | 20.4 kB | 20.4 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>middleware-b..-manifest.js</strong></summary>

```diff
@@ -9,89 +9,89 @@ self.__BUILD_MANIFEST = {
   rootMainFiles: [],
   pages: {
     "/": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
-      "static/chunks/pages/index-eff379b6d5b9bb68.js"
+      "static/chunks/main-0d1bfa95bad2d347.js",
+      "static/chunks/pages/index-2d083d34263a3ab6.js"
     ],
     "/_app": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
-      "static/chunks/pages/_app-92c368fd6cf3735d.js"
+      "static/chunks/main-0d1bfa95bad2d347.js",
+      "static/chunks/pages/_app-dfaef6942d774f42.js"
     ],
     "/_error": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
-      "static/chunks/pages/_error-178a994c6aae5c09.js"
+      "static/chunks/main-0d1bfa95bad2d347.js",
+      "static/chunks/pages/_error-d3adcea7db63be0b.js"
     ],
     "/amp": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
-      "static/chunks/pages/amp-5371e17dca0f96e2.js"
+      "static/chunks/main-0d1bfa95bad2d347.js",
+      "static/chunks/pages/amp-73798c31aeaffbc0.js"
     ],
     "/css": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
+      "static/chunks/main-0d1bfa95bad2d347.js",
       "static/css/94fdbc56eafa2039.css",
-      "static/chunks/pages/css-10d4fc9f36e1f8a8.js"
+      "static/chunks/pages/css-544d2f643bb52307.js"
     ],
     "/dynamic": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
-      "static/chunks/pages/dynamic-ed542e6de09f4f6d.js"
+      "static/chunks/main-0d1bfa95bad2d347.js",
+      "static/chunks/pages/dynamic-8cc413d9b0b7d51c.js"
     ],
     "/edge-ssr": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
-      "static/chunks/pages/edge-ssr-bd097e7f94bdaf6d.js"
+      "static/chunks/main-0d1bfa95bad2d347.js",
+      "static/chunks/pages/edge-ssr-5c29739b02b7e442.js"
     ],
     "/head": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
-      "static/chunks/pages/head-d124b5fb804544eb.js"
+      "static/chunks/main-0d1bfa95bad2d347.js",
+      "static/chunks/pages/head-06e10ac8d6cd67db.js"
     ],
     "/hooks": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
-      "static/chunks/pages/hooks-71978b92cd657738.js"
+      "static/chunks/main-0d1bfa95bad2d347.js",
+      "static/chunks/pages/hooks-215fac25fbffd827.js"
     ],
     "/image": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
-      "static/chunks/pages/image-b9ed2c7590f64461.js"
+      "static/chunks/main-0d1bfa95bad2d347.js",
+      "static/chunks/pages/image-1fb57d78b17238b0.js"
     ],
     "/link": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
-      "static/chunks/pages/link-d74217d3651ac70d.js"
+      "static/chunks/main-0d1bfa95bad2d347.js",
+      "static/chunks/pages/link-509250f01ccca9e0.js"
     ],
     "/routerDirect": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
-      "static/chunks/pages/routerDirect-6f8978da85fef5eb.js"
+      "static/chunks/main-0d1bfa95bad2d347.js",
+      "static/chunks/pages/routerDirect-1ea8459dd75e3757.js"
     ],
     "/script": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
-      "static/chunks/pages/script-cd3b8fa3518c83c8.js"
+      "static/chunks/main-0d1bfa95bad2d347.js",
+      "static/chunks/pages/script-178c2ac994fe2199.js"
     ],
     "/withRouter": [
-      "static/chunks/webpack-596ddb9e5090dbce.js",
+      "static/chunks/webpack-752e2e86747c1b07.js",
       "static/chunks/framework-0249bf7bc1c3f377.js",
-      "static/chunks/main-a29cb935e8307bda.js",
-      "static/chunks/pages/withRouter-394e599a32dcd7a4.js"
+      "static/chunks/main-0d1bfa95bad2d347.js",
+      "static/chunks/pages/withRouter-27de9f24be6003e9.js"
     ]
   },
   ampFirstPages: []
```
</details>
<details>
<summary>Diff for <strong>middleware-r..-manifest.js</strong></summary>

```diff
@@ -1,6 +1,6 @@
 self.__REACT_LOADABLE_MANIFEST = {
   "dynamic.js -> ../components/hello": {
-    id: 3900,
-    files: ["static/chunks/900.f01fcc2109adde55.js"]
+    id: 5886,
+    files: ["static/chunks/886.b879335d00f271d1.js"]
   }
 };
```
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [826],
   {
-    /***/ 3957: /***/ (
+    /***/ 6460: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -14,13 +14,13 @@
         /* harmony export */
       });
       /* harmony import */ var next_dist_server_web_adapter__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
-        674
+        9107
       );
 
       (0,
       next_dist_server_web_adapter__WEBPACK_IMPORTED_MODULE_0__ /* .enhanceGlobals */.gL)();
 
-      var mod = __webpack_require__(7352);
+      var mod = __webpack_require__(5250);
       var handler = mod.middleware || mod.default;
 
       if (typeof handler !== "function") {
@@ -46,7 +46,7 @@
       /***/
     },
 
-    /***/ 7352: /***/ (
+    /***/ 5250: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -58,7 +58,7 @@
         /* harmony export */
       });
       /* harmony import */ var next_server__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
-        8352
+        9541
       );
       /* harmony import */ var next_server__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/ __webpack_require__.n(
         next_server__WEBPACK_IMPORTED_MODULE_0__
@@ -71,7 +71,7 @@
       /***/
     },
 
-    /***/ 5195: /***/ (__unused_webpack_module, exports) => {
+    /***/ 3239: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -91,7 +91,7 @@
       /***/
     },
 
-    /***/ 9923: /***/ (__unused_webpack_module, exports) => {
+    /***/ 7793: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -129,7 +129,7 @@
       /***/
     },
 
-    /***/ 5401: /***/ (__unused_webpack_module, exports) => {
+    /***/ 7432: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -161,7 +161,7 @@
       /***/
     },
 
-    /***/ 5316: /***/ (
+    /***/ 5154: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -172,8 +172,8 @@
         value: true
       });
       exports.addLocale = addLocale;
-      var _addPathPrefix = __webpack_require__(8976);
-      var _pathHasPrefix = __webpack_require__(9882);
+      var _addPathPrefix = __webpack_require__(4632);
+      var _pathHasPrefix = __webpack_require__(387);
       function addLocale(path, locale, defaultLocale, ignorePrefix) {
         if (
           locale &&
@@ -193,7 +193,7 @@
       /***/
     },
 
-    /***/ 8976: /***/ (
+    /***/ 4632: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -204,7 +204,7 @@
         value: true
       });
       exports.addPathPrefix = addPathPrefix;
-      var _parsePath = __webpack_require__(5606);
+      var _parsePath = __webpack_require__(386);
       function addPathPrefix(path, prefix) {
         if (!path.startsWith("/") || !prefix) {
           return path;
@@ -216,7 +216,7 @@
       /***/
     },
 
-    /***/ 3009: /***/ (
+    /***/ 5045: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -227,7 +227,7 @@
         value: true
       });
       exports.addPathSuffix = addPathSuffix;
-      var _parsePath = __webpack_require__(5606);
+      var _parsePath = __webpack_require__(386);
       function addPathSuffix(path, suffix) {
         if (!path.startsWith("/") || !suffix) {
           return path;
@@ -239,7 +239,7 @@
       /***/
     },
 
-    /***/ 4234: /***/ (
+    /***/ 7100: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -250,10 +250,10 @@
         value: true
       });
       exports.formatNextPathnameInfo = formatNextPathnameInfo;
-      var _removeTrailingSlash = __webpack_require__(8336);
-      var _addPathPrefix = __webpack_require__(8976);
-      var _addPathSuffix = __webpack_require__(3009);
-      var _addLocale = __webpack_require__(5316);
+      var _removeTrailingSlash = __webpack_require__(8833);
+      var _addPathPrefix = __webpack_require__(4632);
+      var _addPathSuffix = __webpack_require__(5045);
+      var _addLocale = __webpack_require__(5154);
       function formatNextPathnameInfo(info) {
         let pathname = (0, _addLocale).addLocale(
           info.pathname,
@@ -281,7 +281,7 @@
       /***/
     },
 
-    /***/ 3633: /***/ (
+    /***/ 7139: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -292,9 +292,9 @@
         value: true
       });
       exports.getNextPathnameInfo = getNextPathnameInfo;
-      var _normalizeLocalePath = __webpack_require__(5401);
-      var _removePathPrefix = __webpack_require__(2811);
-      var _pathHasPrefix = __webpack_require__(9882);
+      var _normalizeLocalePath = __webpack_require__(7432);
+      var _removePathPrefix = __webpack_require__(3776);
+      var _pathHasPrefix = __webpack_require__(387);
       function getNextPathnameInfo(pathname, options) {
         var _nextConfig;
         const { basePath, i18n, trailingSlash } =
@@ -344,7 +344,7 @@
       /***/
     },
 
-    /***/ 5606: /***/ (__unused_webpack_module, exports) => {
+    /***/ 386: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -378,7 +378,7 @@
       /***/
     },
 
-    /***/ 9882: /***/ (
+    /***/ 387: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -389,7 +389,7 @@
         value: true
       });
       exports.pathHasPrefix = pathHasPrefix;
-      var _parsePath = __webpack_require__(5606);
+      var _parsePath = __webpack_require__(386);
       function pathHasPrefix(path, prefix) {
         if (typeof path !== "string") {
           return false;
@@ -401,7 +401,7 @@
       /***/
     },
 
-    /***/ 4258: /***/ (__unused_webpack_module, exports) => {
+    /***/ 1142: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -420,7 +420,7 @@
       /***/
     },
 
-    /***/ 2811: /***/ (
+    /***/ 3776: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -431,7 +431,7 @@
         value: true
       });
       exports.removePathPrefix = removePathPrefix;
-      var _pathHasPrefix = __webpack_require__(9882);
+      var _pathHasPrefix = __webpack_require__(387);
       function removePathPrefix(path, prefix) {
         if ((0, _pathHasPrefix).pathHasPrefix(path, prefix)) {
           const withoutPrefix = path.slice(prefix.length);
@@ -445,7 +445,7 @@
       /***/
     },
 
-    /***/ 8336: /***/ (__unused_webpack_module, exports) => {
+    /***/ 8833: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -459,7 +459,7 @@
       /***/
     },
 
-    /***/ 5682: /***/ module => {
+    /***/ 4202: /***/ module => {
       var __dirname = "/";
       (() => {
         "use strict";
@@ -587,7 +587,7 @@
       /***/
     },
 
-    /***/ 6166: /***/ (module, exports, __webpack_require__) => {
+    /***/ 6204: /***/ (module, exports, __webpack_require__) => {
       var __dirname = "/";
       var __WEBPACK_AMD_DEFINE_RESULT__;
       (() => {
@@ -1429,7 +1429,7 @@
       /***/
     },
 
-    /***/ 674: /***/ (
+    /***/ 9107: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1443,13 +1443,13 @@
       exports.VL = adapter;
       exports.OT = blockUnallowedResponse;
       exports.gL = enhanceGlobals;
-      var _error = __webpack_require__(4524);
-      var _utils = __webpack_require__(88);
-      var _fetchEvent = __webpack_require__(8852);
-      var _request = __webpack_require__(5829);
-      var _response = __webpack_require__(5277);
-      var _relativizeUrl = __webpack_require__(4258);
-      var _nextUrl = __webpack_require__(3062);
+      var _error = __webpack_require__(8666);
+      var _utils = __webpack_require__(30);
+      var _fetchEvent = __webpack_require__(9833);
+      var _request = __webpack_require__(5985);
+      var _response = __webpack_require__(5165);
+      var _relativizeUrl = __webpack_require__(1142);
+      var _nextUrl = __webpack_require__(4901);
       class NextRequestHint extends _request.NextRequest {
         constructor(params) {
           super(params.input, params.init);
@@ -1660,7 +1660,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 4524: /***/ (__unused_webpack_module, exports) => {
+    /***/ 8666: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -1701,7 +1701,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 3062: /***/ (
+    /***/ 4901: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1711,10 +1711,10 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
-      var _detectDomainLocale = __webpack_require__(9923);
-      var _formatNextPathnameInfo = __webpack_require__(4234);
-      var _getHostname = __webpack_require__(5195);
-      var _getNextPathnameInfo = __webpack_require__(3633);
+      var _detectDomainLocale = __webpack_require__(7793);
+      var _formatNextPathnameInfo = __webpack_require__(7100);
+      var _getHostname = __webpack_require__(3239);
+      var _getNextPathnameInfo = __webpack_require__(7139);
       const REGEX_LOCALHOST_HOSTNAME = /(?!^https?:\/\/)(127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}|::1|localhost)/;
       function parseURL(url, base) {
         return new URL(
@@ -1935,7 +1935,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 3868: /***/ (
+    /***/ 4570: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1945,7 +1945,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
-      var _cookie = _interopRequireDefault(__webpack_require__(5682));
+      var _cookie = _interopRequireDefault(__webpack_require__(4202));
       function _interopRequireDefault(obj) {
         return obj && obj.__esModule
           ? obj
@@ -2080,7 +2080,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 8852: /***/ (
+    /***/ 9833: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -2091,7 +2091,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         value: true
       });
       exports.waitUntilSymbol = void 0;
-      var _error = __webpack_require__(4524);
+      var _error = __webpack_require__(8666);
       const responseSymbol = Symbol("response");
       const passThroughSymbol = Symbol("passThrough");
       const waitUntilSymbol = Symbol("waitUntil");
@@ -2144,7 +2144,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 5829: /***/ (
+    /***/ 5985: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -2155,10 +2155,10 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         value: true
       });
       exports.INTERNALS = void 0;
-      var _nextUrl = __webpack_require__(3062);
-      var _utils = __webpack_require__(88);
-      var _error = __webpack_require__(4524);
-      var _cookies = __webpack_require__(3868);
+      var _nextUrl = __webpack_require__(4901);
+      var _utils = __webpack_require__(30);
+      var _error = __webpack_require__(8666);
+      var _cookies = __webpack_require__(4570);
       const INTERNALS = Symbol("internal request");
       exports.INTERNALS = INTERNALS;
       class NextRequest extends Request {
@@ -2239,7 +2239,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 5277: /***/ (
+    /***/ 5165: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -2249,9 +2249,9 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
-      var _nextUrl = __webpack_require__(3062);
-      var _utils = __webpack_require__(88);
-      var _cookies = __webpack_require__(3868);
+      var _nextUrl = __webpack_require__(4901);
+      var _utils = __webpack_require__(30);
+      var _cookies = __webpack_require__(4570);
       const INTERNALS = Symbol("internal response");
       const REDIRECTS = new Set([301, 302, 303, 307, 308]);
       class NextResponse extends Response {
@@ -2341,7 +2341,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 7873: /***/ (
+    /***/ 9132: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -2355,7 +2355,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       __webpack_unused_export__ = isBot;
       exports.Nf = userAgentFromString;
       exports.WE = userAgent;
-      var _uaParserJs = _interopRequireDefault(__webpack_require__(6166));
+      var _uaParserJs = _interopRequireDefault(__webpack_require__(6204));
       function _interopRequireDefault(obj) {
         return obj && obj.__esModule
           ? obj
@@ -2383,7 +2383,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 88: /***/ (__unused_webpack_module, exports) => {
+    /***/ 30: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -2498,14 +2498,14 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 8352: /***/ (module, exports, __webpack_require__) => {
+    /***/ 9541: /***/ (module, exports, __webpack_require__) => {
       const serverExports = {
-        NextRequest: __webpack_require__(5829).NextRequest,
-        NextResponse: __webpack_require__(5277).NextResponse,
+        NextRequest: __webpack_require__(5985).NextRequest,
+        NextResponse: __webpack_require__(5165).NextResponse,
         userAgentFromString: __webpack_require__(
-          7873
+          9132
         ) /* .userAgentFromString */.Nf,
-        userAgent: __webpack_require__(7873) /* .userAgent */.WE
+        userAgent: __webpack_require__(9132) /* .userAgent */.WE
       };
 
       if (typeof URLPattern !== "undefined") {
@@ -2531,7 +2531,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = moduleId =>
       __webpack_require__((__webpack_require__.s = moduleId));
-    /******/ var __webpack_exports__ = __webpack_exec__(3957);
+    /******/ var __webpack_exports__ = __webpack_exec__(6460);
     /******/ (_ENTRIES =
       typeof _ENTRIES === "undefined"
         ? {}
```
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,28 +1,28 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-eff379b6d5b9bb68.js"],
-  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-178a994c6aae5c09.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-5371e17dca0f96e2.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-2d083d34263a3ab6.js"],
+  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-d3adcea7db63be0b.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-73798c31aeaffbc0.js"],
   "/css": [
     "static\u002Fcss\u002F94fdbc56eafa2039.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-10d4fc9f36e1f8a8.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-544d2f643bb52307.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-ed542e6de09f4f6d.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-8cc413d9b0b7d51c.js"
   ],
   "/edge-ssr": [
-    "static\u002Fchunks\u002Fpages\u002Fedge-ssr-bd097e7f94bdaf6d.js"
+    "static\u002Fchunks\u002Fpages\u002Fedge-ssr-5c29739b02b7e442.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-d124b5fb804544eb.js"],
-  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-71978b92cd657738.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-b9ed2c7590f64461.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-d74217d3651ac70d.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-06e10ac8d6cd67db.js"],
+  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-215fac25fbffd827.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-1fb57d78b17238b0.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-509250f01ccca9e0.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-6f8978da85fef5eb.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-1ea8459dd75e3757.js"
   ],
-  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-cd3b8fa3518c83c8.js"],
+  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-178c2ac994fe2199.js"],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-394e599a32dcd7a4.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-27de9f24be6003e9.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 3115: /***/ function(
+    /***/ 1113: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_app",
         function() {
-          return __webpack_require__(2501);
+          return __webpack_require__(4802);
         }
       ]);
       if (false) {
@@ -24,7 +24,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 179], function() {
-      return __webpack_exec__(3115), __webpack_exec__(6401);
+      return __webpack_exec__(1113), __webpack_exec__(2385);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [820],
   {
-    /***/ 5374: /***/ function(
+    /***/ 3363: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_error",
         function() {
-          return __webpack_require__(7969);
+          return __webpack_require__(3273);
         }
       ]);
       if (false) {
@@ -24,7 +24,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function() {
-      return __webpack_exec__(5374);
+      return __webpack_exec__(3363);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>amp-HASH.js</strong></summary>

```diff
@@ -1,17 +1,17 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [216],
   {
-    /***/ 8510: /***/ function(
+    /***/ 8753: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(6464);
+      module.exports = __webpack_require__(9709);
 
       /***/
     },
 
-    /***/ 7010: /***/ function(
+    /***/ 5348: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -19,7 +19,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/amp",
         function() {
-          return __webpack_require__(2461);
+          return __webpack_require__(7503);
         }
       ]);
       if (false) {
@@ -28,7 +28,7 @@
       /***/
     },
 
-    /***/ 6464: /***/ function(module, exports, __webpack_require__) {
+    /***/ 9709: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -38,8 +38,8 @@
       var _interop_require_default = __webpack_require__(4507) /* ["default"] */
         .Z;
       var _react = _interop_require_default(__webpack_require__(959));
-      var _ampContext = __webpack_require__(1258);
-      var _ampMode = __webpack_require__(5976);
+      var _ampContext = __webpack_require__(8373);
+      var _ampMode = __webpack_require__(7380);
       function useAmp() {
         // Don't assign the context value to a variable to save bytes
         return (0, _ampMode).isInAmpMode(
@@ -61,7 +61,7 @@
       /***/
     },
 
-    /***/ 2461: /***/ function(
+    /***/ 7503: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -78,7 +78,7 @@
         /* harmony export */
       });
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
-        8510
+        8753
       );
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/ __webpack_require__.n(
         next_amp__WEBPACK_IMPORTED_MODULE_0__
@@ -102,7 +102,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function() {
-      return __webpack_exec__(7010);
+      return __webpack_exec__(5348);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>css-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [706],
   {
-    /***/ 860: /***/ function(
+    /***/ 6437: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/css",
         function() {
-          return __webpack_require__(7832);
+          return __webpack_require__(7135);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 7832: /***/ function(
+    /***/ 7135: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -29,7 +29,7 @@
         1527
       );
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        2707
+        3934
       );
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         _css_module_css__WEBPACK_IMPORTED_MODULE_1__
@@ -48,7 +48,7 @@
       /***/
     },
 
-    /***/ 2707: /***/ function(module) {
+    /***/ 3934: /***/ function(module) {
       // extracted by mini-css-extract-plugin
       module.exports = { helloWorld: "css_helloWorld__qqNwY" };
 
@@ -61,7 +61,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(860);
+      return __webpack_exec__(6437);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [739],
   {
-    /***/ 3995: /***/ function(
+    /***/ 7753: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/dynamic",
         function() {
-          return __webpack_require__(2523);
+          return __webpack_require__(4683);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 2627: /***/ function(module, exports, __webpack_require__) {
+    /***/ 5434: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -34,7 +34,7 @@
       var _interop_require_default = __webpack_require__(4507) /* ["default"] */
         .Z;
       var _react = _interop_require_default(__webpack_require__(959));
-      var _loadable = _interop_require_default(__webpack_require__(2132));
+      var _loadable = _interop_require_default(__webpack_require__(5682));
       function dynamic(dynamicOptions, options) {
         var loadableFn = _loadable.default;
         var loadableOptions = {
@@ -129,7 +129,7 @@
       /***/
     },
 
-    /***/ 1685: /***/ function(
+    /***/ 9106: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -151,7 +151,7 @@
       /***/
     },
 
-    /***/ 2132: /***/ function(
+    /***/ 5682: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -171,7 +171,7 @@
       var _interop_require_default = __webpack_require__(4507) /* ["default"] */
         .Z;
       var _react = _interop_require_default(__webpack_require__(959));
-      var _loadableContext = __webpack_require__(1685);
+      var _loadableContext = __webpack_require__(9106);
       var useSyncExternalStore = (true ? __webpack_require__(959) : 0)
         .useSyncExternalStore;
       var ALL_INITIALIZERS = [];
@@ -485,7 +485,7 @@
       /***/
     },
 
-    /***/ 2523: /***/ function(
+    /***/ 4683: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -502,7 +502,7 @@
         1527
       );
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        6113
+        2677
       );
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_dynamic__WEBPACK_IMPORTED_MODULE_1__
@@ -511,13 +511,13 @@
       var DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
         function() {
           return __webpack_require__
-            .e(/* import() */ 900)
-            .then(__webpack_require__.bind(__webpack_require__, 3900));
+            .e(/* import() */ 886)
+            .then(__webpack_require__.bind(__webpack_require__, 5886));
         },
         {
           loadableGenerated: {
             webpack: function() {
-              return [/*require.resolve*/ 3900];
+              return [/*require.resolve*/ 5886];
             }
           }
         }
@@ -547,12 +547,12 @@
       /***/
     },
 
-    /***/ 6113: /***/ function(
+    /***/ 2677: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(2627);
+      module.exports = __webpack_require__(5434);
 
       /***/
     }
@@ -563,7 +563,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(3995);
+      return __webpack_exec__(7753);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>edge-ssr-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [800],
   {
-    /***/ 6219: /***/ function(
+    /***/ 6027: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/edge-ssr",
         function() {
-          return __webpack_require__(7692);
+          return __webpack_require__(3789);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 7692: /***/ function(
+    /***/ 3789: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -54,7 +54,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function() {
-      return __webpack_exec__(6219);
+      return __webpack_exec__(6027);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>head-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [645],
   {
-    /***/ 2899: /***/ function(
+    /***/ 6955: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/head",
         function() {
-          return __webpack_require__(6820);
+          return __webpack_require__(4489);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 6820: /***/ function(
+    /***/ 4489: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -35,7 +35,7 @@
         1527
       );
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        8412
+        9046
       );
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_head__WEBPACK_IMPORTED_MODULE_1__
@@ -71,12 +71,12 @@
       /***/
     },
 
-    /***/ 8412: /***/ function(
+    /***/ 9046: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(8684);
+      module.exports = __webpack_require__(1453);
 
       /***/
     }
@@ -87,7 +87,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(2899);
+      return __webpack_exec__(6955);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>hooks-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [757],
   {
-    /***/ 2304: /***/ function(
+    /***/ 7819: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/hooks",
         function() {
-          return __webpack_require__(1903);
+          return __webpack_require__(7520);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 1903: /***/ function(
+    /***/ 7520: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -132,7 +132,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(2304);
+      return __webpack_exec__(7819);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -26,7 +26,7 @@
       /***/
     },
 
-    /***/ 5885: /***/ function(
+    /***/ 801: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -34,7 +34,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function() {
-          return __webpack_require__(7547);
+          return __webpack_require__(6913);
         }
       ]);
       if (false) {
@@ -43,7 +43,7 @@
       /***/
     },
 
-    /***/ 3200: /***/ function(module, exports, __webpack_require__) {
+    /***/ 206: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -66,12 +66,12 @@
         4719
       ) /* ["default"] */.Z;
       var _react = _interop_require_wildcard(__webpack_require__(959));
-      var _head = _interop_require_default(__webpack_require__(8684));
-      var _imageConfig = __webpack_require__(5732);
-      var _useIntersection = __webpack_require__(157);
-      var _imageConfigContext = __webpack_require__(891);
-      var _utils = __webpack_require__(7944);
-      var _normalizeTrailingSlash = __webpack_require__(3912);
+      var _head = _interop_require_default(__webpack_require__(1453));
+      var _imageConfig = __webpack_require__(4188);
+      var _useIntersection = __webpack_require__(4422);
+      var _imageConfigContext = __webpack_require__(7971);
+      var _utils = __webpack_require__(8858);
+      var _normalizeTrailingSlash = __webpack_require__(5289);
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -927,7 +927,7 @@
       /***/
     },
 
-    /***/ 157: /***/ function(module, exports, __webpack_require__) {
+    /***/ 4422: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -939,7 +939,7 @@
       });
       exports.useIntersection = useIntersection;
       var _react = __webpack_require__(959);
-      var _requestIdleCallback = __webpack_require__(9186);
+      var _requestIdleCallback = __webpack_require__(2398);
       var hasIntersectionObserver = typeof IntersectionObserver === "function";
       var observers = new Map();
       var idList = [];
@@ -1064,7 +1064,7 @@
       /***/
     },
 
-    /***/ 7547: /***/ function(
+    /***/ 6913: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -1085,8 +1085,8 @@
 
       // EXTERNAL MODULE: ./node_modules/.pnpm/react@18.2.0/node_modules/react/jsx-runtime.js
       var jsx_runtime = __webpack_require__(1527);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/image.js
-      var next_image = __webpack_require__(3960);
+      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/image.js
+      var next_image = __webpack_require__(8249);
       var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // CONCATENATED MODULE: ./pages/nextjs.png
       /* harmony default export */ var nextjs = {
         src: "/_next/static/media/nextjs.cae0b805.png",
@@ -1116,12 +1116,12 @@
       /***/
     },
 
-    /***/ 3960: /***/ function(
+    /***/ 8249: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(3200);
+      module.exports = __webpack_require__(206);
 
       /***/
     }
@@ -1132,7 +1132,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(5885);
+      return __webpack_exec__(801);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>index-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [405],
   {
-    /***/ 3558: /***/ function(
+    /***/ 6481: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/",
         function() {
-          return __webpack_require__(80);
+          return __webpack_require__(5376);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 80: /***/ function(
+    /***/ 5376: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -46,7 +46,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function() {
-      return __webpack_exec__(3558);
+      return __webpack_exec__(6481);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [644],
   {
-    /***/ 8662: /***/ function(
+    /***/ 7014: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/link",
         function() {
-          return __webpack_require__(1269);
+          return __webpack_require__(1226);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 6999: /***/ function(module, exports) {
+    /***/ 7173: /***/ function(module, exports) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -54,7 +54,7 @@
       /***/
     },
 
-    /***/ 8036: /***/ function(module, exports, __webpack_require__) {
+    /***/ 404: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -72,13 +72,13 @@
         4719
       ) /* ["default"] */.Z;
       var _react = _interop_require_default(__webpack_require__(959));
-      var _router = __webpack_require__(319);
-      var _addLocale = __webpack_require__(2421);
-      var _routerContext = __webpack_require__(3977);
-      var _appRouterContext = __webpack_require__(8766);
-      var _useIntersection = __webpack_require__(157);
-      var _getDomainLocale = __webpack_require__(6999);
-      var _addBasePath = __webpack_require__(6526);
+      var _router = __webpack_require__(8107);
+      var _addLocale = __webpack_require__(7543);
+      var _routerContext = __webpack_require__(9303);
+      var _appRouterContext = __webpack_require__(7500);
+      var _useIntersection = __webpack_require__(4422);
+      var _getDomainLocale = __webpack_require__(7173);
+      var _addBasePath = __webpack_require__(2851);
       // @ts-ignore useTransition exist
       var hasUseTransition =
         typeof _react.default.useTransition !== "undefined";
@@ -433,7 +433,7 @@
       /***/
     },
 
-    /***/ 157: /***/ function(module, exports, __webpack_require__) {
+    /***/ 4422: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -445,7 +445,7 @@
       });
       exports.useIntersection = useIntersection;
       var _react = __webpack_require__(959);
-      var _requestIdleCallback = __webpack_require__(9186);
+      var _requestIdleCallback = __webpack_require__(2398);
       var hasIntersectionObserver = typeof IntersectionObserver === "function";
       var observers = new Map();
       var idList = [];
@@ -570,7 +570,7 @@
       /***/
     },
 
-    /***/ 8766: /***/ function(
+    /***/ 7500: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -596,7 +596,7 @@
       /***/
     },
 
-    /***/ 1269: /***/ function(
+    /***/ 1226: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -613,7 +613,7 @@
         1527
       );
       /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        4595
+        9495
       );
       /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_link__WEBPACK_IMPORTED_MODULE_1__
@@ -644,12 +644,12 @@
       /***/
     },
 
-    /***/ 4595: /***/ function(
+    /***/ 9495: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(8036);
+      module.exports = __webpack_require__(404);
 
       /***/
     }
@@ -660,7 +660,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(8662);
+      return __webpack_exec__(7014);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>routerDirect-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [58],
   {
-    /***/ 2188: /***/ function(
+    /***/ 7288: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/routerDirect",
         function() {
-          return __webpack_require__(6938);
+          return __webpack_require__(6018);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 6938: /***/ function(
+    /***/ 6018: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -35,7 +35,7 @@
         1527
       );
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        5866
+        5664
       );
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_router__WEBPACK_IMPORTED_MODULE_1__
@@ -56,12 +56,12 @@
       /***/
     },
 
-    /***/ 5866: /***/ function(
+    /***/ 5664: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(6401);
+      module.exports = __webpack_require__(2385);
 
       /***/
     }
@@ -72,7 +72,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(2188);
+      return __webpack_exec__(7288);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>script-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [797],
   {
-    /***/ 1136: /***/ function(
+    /***/ 6695: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/script",
         function() {
-          return __webpack_require__(3560);
+          return __webpack_require__(4237);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 3560: /***/ function(
+    /***/ 4237: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -35,7 +35,7 @@
         1527
       );
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        9096
+        6071
       );
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_script__WEBPACK_IMPORTED_MODULE_1__
@@ -70,12 +70,12 @@
       /***/
     },
 
-    /***/ 9096: /***/ function(
+    /***/ 6071: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(5506);
+      module.exports = __webpack_require__(1149);
 
       /***/
     }
@@ -86,7 +86,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(1136);
+      return __webpack_exec__(6695);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>withRouter-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [807],
   {
-    /***/ 3551: /***/ function(
+    /***/ 8118: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/withRouter",
         function() {
-          return __webpack_require__(6216);
+          return __webpack_require__(3622);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 6216: /***/ function(
+    /***/ 3622: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -35,7 +35,7 @@
         1527
       );
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        5866
+        5664
       );
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_router__WEBPACK_IMPORTED_MODULE_1__
@@ -54,12 +54,12 @@
       /***/
     },
 
-    /***/ 5866: /***/ function(
+    /***/ 5664: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(6401);
+      module.exports = __webpack_require__(2385);
 
       /***/
     }
@@ -70,7 +70,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function() {
-      return __webpack_exec__(3551);
+      return __webpack_exec__(8118);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>900.HASH.js</strong></summary>

```diff
@@ -1,8 +1,8 @@
 "use strict";
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
-  [900],
+  [886],
   {
-    /***/ 3900: /***/ function(
+    /***/ 5886: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
@@ -159,7 +159,7 @@
     /******/ __webpack_require__.u = function(chunkId) {
       /******/ // return url for filenames based on template
       /******/ return (
-        "static/chunks/" + chunkId + "." + "f01fcc2109adde55" + ".js"
+        "static/chunks/" + chunkId + "." + "b879335d00f271d1" + ".js"
       );
       /******/
     };
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-596ddb9e5090dbce.js"
+      src="/_next/static/chunks/webpack-752e2e86747c1b07.js"
       defer=""
     ></script>
     <script
@@ -19,15 +19,15 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a29cb935e8307bda.js"
+      src="/_next/static/chunks/main-0d1bfa95bad2d347.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-92c368fd6cf3735d.js"
+      src="/_next/static/chunks/pages/_app-dfaef6942d774f42.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/index-eff379b6d5b9bb68.js"
+      src="/_next/static/chunks/pages/index-2d083d34263a3ab6.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-596ddb9e5090dbce.js"
+      src="/_next/static/chunks/webpack-752e2e86747c1b07.js"
       defer=""
     ></script>
     <script
@@ -19,15 +19,15 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a29cb935e8307bda.js"
+      src="/_next/static/chunks/main-0d1bfa95bad2d347.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-92c368fd6cf3735d.js"
+      src="/_next/static/chunks/pages/_app-dfaef6942d774f42.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-d74217d3651ac70d.js"
+      src="/_next/static/chunks/pages/link-509250f01ccca9e0.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-596ddb9e5090dbce.js"
+      src="/_next/static/chunks/webpack-752e2e86747c1b07.js"
       defer=""
     ></script>
     <script
@@ -19,15 +19,15 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a29cb935e8307bda.js"
+      src="/_next/static/chunks/main-0d1bfa95bad2d347.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-92c368fd6cf3735d.js"
+      src="/_next/static/chunks/pages/_app-dfaef6942d774f42.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/withRouter-394e599a32dcd7a4.js"
+      src="/_next/static/chunks/pages/withRouter-27de9f24be6003e9.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| buildDuration | 24.8s | 24.9s | ⚠️ +117ms |
| buildDurationCached | 7.9s | 7.7s | -149ms |
| nodeModulesSize | 1.96 GB | 1.96 GB | ⚠️ +620 B |
| nextStartRea..uration (ms) | 292ms | 293ms | ⚠️ +1ms |
| nextDevReadyDuration | 313ms | 314ms | ⚠️ +1ms |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 8.969 | 9.049 | ⚠️ +0.08 |
| / avg req/sec | 278.73 | 276.26 | ⚠️ -2.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 6.01 | 6.107 | ⚠️ +0.1 |
| /error-in-render avg req/sec | 415.97 | 409.36 | ⚠️ -6.61 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| 900.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 45.5 kB | 45.5 kB | ✓ |
| main-HASH.js gzip | 31 kB | 31 kB | ⚠️ +17 B |
| webpack-HASH.js gzip | 1.52 kB | 1.52 kB | ⚠️ +1 B |
| Overall change | 78.3 kB | 78.3 kB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 194 B | ✓ |
| _error-HASH.js gzip | 181 B | 181 B | ✓ |
| amp-HASH.js gzip | 481 B | 482 B | ⚠️ +1 B |
| css-HASH.js gzip | 322 B | 324 B | ⚠️ +2 B |
| dynamic-HASH.js gzip | 2 kB | 1.99 kB | -2 B |
| edge-ssr-HASH.js gzip | 279 B | 279 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 776 B | 778 B | ⚠️ +2 B |
| image-HASH.js gzip | 4.82 kB | 4.81 kB | -4 B |
| index-HASH.js gzip | 257 B | 258 B | ⚠️ +1 B |
| link-HASH.js gzip | 2.34 kB | 2.34 kB | -2 B |
| routerDirect..HASH.js gzip | 313 B | 313 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 310 B | 310 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | -2 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 483 B | ✓ |
| Overall change | 483 B | 483 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| index.html gzip | 513 B | 514 B | ⚠️ +1 B |
| link.html gzip | 527 B | 528 B | ⚠️ +1 B |
| withRouter.html gzip | 508 B | 508 B | ✓ |
| Overall change | 1.55 kB | 1.55 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Edge SSR Page bundle Size</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | visnup/next.js fix/ssr-data-cache-key-encoding | Change |
| - | - | - | - |
| edge-ssr.js gzip | 114 kB | 114 kB | -10 B |
| Overall change | 114 kB | 114 kB | -10 B |

</details>

<details>
<summary><strong>Middleware size</strong> Overal
Post job cleanup.
[command]/usr/bin/git version
git version 2.37.2
Temporarily overriding HOME='/home/runner/work/_temp/e903f366-5f52-4a9e-b4c7-04e1bb67df4c' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
[command]/usr/bin/git config --global --add safe.directory /home/runner/work/next.js/next.js
[command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
[command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
[command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
[command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
[command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
Cleaning up orphan processes
Commit: ddbdcbdfa2d7ba13f2b0d7043ce682fe7dfab8ab

**Review by ijjk — APPROVED** [review]
Thanks for the PR!
