### PR TITLE
Fix conflict dev entry key between app and pages

### LINKED ISSUE #45651: [NEXT-472] appdir causes `pages/page.tsx` throws 404 in dev and 500 in prod
reproduction: [https://github.com/JanKaifer/next-repro-45651.git](https://github.com/JanKaifer/next-repro-45651.git)

visit: [http://localhost:3000/page](http://localhost:3000/page)

* [ ] It will throw 404 in dev
* [X]  It will throw 500 in production when loading

To reproduce it in `dev` first navigate to `/` load it and then navigate to `/page`.
(navigating to `/page` first and then to `/` also reproduces the issue)

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-472](https://linear.app/vercel/issue/NEXT-472/appdir-causes-pagespagetsx-throws-404-in-dev-and-500-in-prod)</sub>

### PR DESCRIPTION
**Pull request by huozhi**
Add unique identifier `@app@` / `@pages@` / `@root@` for entry key of on demand entries, so that they'll be unique for each path when the page key is similar bewteen app and pages like (`"app/page"` and `"pages/page"` will both end up with `/page`)

## Bug

Follow up for #46736
Closes NEXT-472

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have a helpful link attached, see [`contributing.md`](https://github.com/vercel/next.js/blob/canary/contributing.md)

fix #45651

### CODE REVIEW

File: packages/next/src/server/dev/on-demand-entry-handler.ts [hunk 1]
```diff
@@ -80,6 +80,33 @@ function convertDynamicParamTypeToSyntax(
...
+ *
+ * This guarantees the uniqueness for each page, to avoid conflicts between app/ and pages/
+ */
+
+export function getEntryKey(
+  compilerType: CompilerNameValues,
+  pageBundleType: 'app' | 'pages' | 'root',
+  page: string
+) {
+  return `${compilerType}@${pageBundleType}@${page}`
```
Comment (JanKaifer) [inline packages/next/src/server/dev/on-demand-entry-handler.ts:96]: Maybe it's better to just use `JSON.stringify([compilerType, pageBundleType, page])`?
It's easier to parse & handle.

Comment (huozhi) [reply packages/next/src/server/dev/on-demand-entry-handler.ts:96]: we need to extract the values from format in hot-reload, I believe this will be easier for now. We could change once entry key become complicated but seems enough for current case

**Review by ijjk — APPROVED** [review]
