### PR TITLE
hotfix(next):`next lint` installs `eslint@9` which includes breaking changes

### LINKED ISSUE #64136: `next lint` installs incompatible `eslint@9`
### Link to the code that reproduces this issue

https://github.com/devjiwonchoi/repro-next-64114

### To Reproduce

1. Run `pnpm next lint`
2. To start over, run `pnpm remove eslint eslint-config-next`, delete `.eslintrc.json`, and run `pnpm next lint`

### Current vs. Expected behavior

Multiple unmeet peer dependencies:

Screenshot 2024-04-06 at 11 59 41 AM

Invalid Options:

Screenshot 2024-04-06 at 12 00 10 PM

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:32:11 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 11
Binaries:
  Node: 18.20.0
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.0-canary.60 // Latest available version is detected (14.2.0-canary.60).
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app), ESLint (eslint-config-next)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

x-ref: #64114

### PR DESCRIPTION
**Pull request by devjiwonchoi**
This is a hotfix since it breaks `next lint`, I'll start to implement eslint v9 for canary.

x-ref: #64114
x-ref: [eslint v9 release](https://github.com/eslint/eslint/releases/tag/v9.0.0)
Fixes #64136

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 25da86a4aa62e32734f66fb0573efeadcfac6bea

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 25da86a4aa62e32734f66fb0573efeadcfac6bea

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 25da86a4aa62e32734f66fb0573efeadcfac6bea

`TURBOPACK=1 pnpm test test/integration/eslint/test/next-lint.test.js` (turbopack)
- Next Lint > First Time Setup  > installs eslint and eslint-config-next as devDependencies if missing with yarn
- Next Lint > First Time Setup  > creates .eslintrc.json file with a default configuration
- Next Lint > First Time Setup  > shows a successful message when completed

<details>
<summary>Expand output</summary>

  ● Next Lint › First Time Setup  › installs eslint and eslint-config-next as devDependencies if missing with yarn

    ENOENT: no such file or directory, open '/tmp/ln4ene7y4i9/package.json'



  ● Next Lint › First Time Setup  › creates .eslintrc.json file with a default configuration

    ENOENT: no such file or directory, open '/tmp/65klanrry8v/package.json'



  ● Next Lint › First Time Setup  › shows a successful message when completed

    ENOENT: no such file or directory, open '/tmp/x0h4xade39d/package.json'



</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js eslint-9 | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.8s | N/A |
| buildDurationCached | 7.5s | 6.7s | N/A |
| nodeModulesSize | 199 MB | 199 MB | ⚠️ +2.13 kB |
| nextStartRea..uration (ms) | 410ms | 398ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js eslint-9 | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 31.4 kB | 31.4 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | ✓ |
| 8299-HASH.js gzip | 5.04 kB | 5.04 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 242 B | 242 B | ✓ |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 99.3 kB | 99.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js eslint-9 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js eslint-9 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.21 kB | 4.21 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.57 kB | 6.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js eslint-9 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js eslint-9 | Change |
| - | - | - | - |
| index.html gzip | 529 B | 529 B | ✓ |
| link.html gzip | 541 B | 541 B | ✓ |
| withRouter.html gzip | 523 B | 524 B | N/A |
| Overall change | 1.07 kB | 1.07 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js eslint-9 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.4 kB | 95.4 kB | N/A |
| page.js gzip | 3.06 kB | 3.06 kB | ✓ |
| Overall change | 3.06 kB | 3.06 kB | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js eslint-9 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 624 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js eslint-9 | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | ✓ |
| app-page-exp..prod.js gzip | 97 kB | 97 kB | ✓ |
| app-page-tur..prod.js gzip | 98.8 kB | 98.8 kB | ✓ |
| app-page-tur..prod.js gzip | 93 kB | 93 kB | ✓ |
| app-page.run...dev.js gzip | 144 kB | 144 kB | ✓ |
| app-page.run..prod.js gzip | 91.5 kB | 91.5 kB | ✓ |
| app-route-ex...dev.js gzip | 21.4 kB | 21.4 kB | ✓ |
| app-route-ex..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route.ru...dev.js gzip | 21.1 kB | 21.1 kB | ✓ |
| app-route.ru..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim...dev.js gzip | 23.1 kB | 23.1 kB | ✓ |
| pages.runtim..prod.js gzip | 22.4 kB | 22.4 kB | ✓ |
| server.runti..prod.js gzip | 51.1 kB | 51.1 kB | ✓ |
| Overall change | 945 kB | 945 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js eslint-9 | Change |
| - | - | - | - |
| 0.pack gzip | 1.58 MB | 1.58 MB | N/A |
| index.pack gzip | 106 kB | 107 kB | ⚠️ +802 B |
| Overall change | 106 kB | 107 kB | ⚠️ +802 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 25da86a4aa62e32734f66fb0573efeadcfac6bea

**Comment by devjiwonchoi** [comment]
hmm, works locally for `TURBOPACK=1 pnpm test test/integration/eslint/test/next-lint.test.js`

**Comment by darthmaim** [comment]
> RFC: is it all good for me to start implementing v9 on create-next-app, next lint, eslint-config-next, etc.?

You can check #56181 which was a PR that tried to implement support for the new flat config format.

File: packages/next/src/lib/eslint/runLintCheck.ts [hunk 1]
```diff
@@ -369,8 +369,16 @@ export async function runLintCheck(
...
           // Check if necessary deps installed, and install any that are missing
           deps = await hasNecessaryDependencies(baseDir, requiredPackages)
-          if (deps.missing.length > 0)
+          if (deps.missing.length > 0) {
+            deps.missing.forEach(({ pkg }) => {
+              if (pkg === 'eslint') {
+                // eslint v9 has breaking changes, so lock to 8 until dependency plugins fully support v9.
+                pkg = 'eslint@^8'
+              }
+            })
```
Comment (ztanner) [inline packages/next/src/lib/eslint/runLintCheck.ts:378]: This is performing a local mutation and not actually updating the `pkg` property of the dependency. I think you maybe meant to do something like this
```suggestion
          if (deps.missing.length > 0) {
            deps.missing.forEach((dep) => {
              if (dep.pkg === 'eslint') {
                // eslint v9 has breaking changes, so lock to 8 until dependency plugins fully support v9.
                dep.pkg = 'eslint@^8'
              }
            })
```

Comment (devjiwonchoi) [reply packages/next/src/lib/eslint/runLintCheck.ts]: Thanks for catching that!

**Review by ztanner — APPROVED** [review]
Thank you for the quick hotfix!

**Comment by devjiwonchoi** [comment]
Thank you for reviewing, I hope you have a great weekend!

**Comment by ztanner** [comment]
You as well! We could probably have optimized this a bit more to exit the loop once we find `eslint`, but probably doesn't matter that much since the missing list is likely fairly small 😆

**Comment by devjiwonchoi** [comment]
Thanks for your insight. I totally agree that it is a much better practice. Yes, honestly, since the list is limited to lint, the length is short so didn't optimize it. I'll do better next time. Thank you again!

**Comment by KieraDOG** [comment]
Hey @devjiwonchoi , thanks for your hard work. By the way, do you have an active PR or issue that links to the implementation of ESLint v9? I'd like to have it for tracking purposes.

**Comment by devjiwonchoi** [comment]
@KieraDOG I'm not working on it since https://github.com/vercel/next.js/pull/64251 is opened already!
