### PR TITLE
Wait for shell resolve with gIP is customized in react 18

### LINKED ISSUE #36675: 12.1.6 CSS generation regression
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.5.0
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.1
      react: 18.1.0
      react-dom: 18.1.0
```

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

I'm seeing a CSS generation regression in my setup starting from `12.1.6` and persisting with current `12.1.7-canary.1`.

I'm using React 18 with emotion based UI kit. I see a huge FOUC that gets resolved a moment after load, see dev lighthouse screenshots:

`12.1.5`
Screen Shot 2022-05-04 at 2 38 08 PM

`12.1.6+`
Screen Shot 2022-05-04 at 2 37 20 PM

Any idea if this is an issue with React 18 or how to mitigate? I locked my packages to 12.1.5 for now.

### Expected Behavior

No FOUC like in 12.1.5

### To Reproduce

1. use React 18
2. use css-in-js library like emotion or ui kit like http://mantine.dev
3. use next version 12.1.6 or later
4. Run lighthouse test or watch content jump around during load

### PR DESCRIPTION
**Pull request by huozhi**
When getInitialProps is customized with react 18, since gIP requires to return `html` as doc property which could be used by  user-land customization, we do blocking-rendering there and passdown the `html` to document

Fixes #36675
Closes #36419

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 49b652d303b01b718724a429b418bfafc724fccc

`yarn testheadless test/integration/app-document/test/index.test.js` 
- Document and App > Client side > should detect the changes to pages/_app.js and display it
- Document and App > Client side > should detect the changes to pages/_document.js and display it
- Document and App > Client side > should keep state between page navigations
- Document and App > Client side > It should share module state with pages
- Document and App > Rendering via HTTP > _app > It shows a custom tag
- Document and App > Rendering via HTTP > _app > It should share module state with pages
- Document and App > Rendering via HTTP > _app > It should show valid error when thrown in _app getInitialProps
- Document and App > Rendering via HTTP > _document > It has a custom html class
- Document and App > Rendering via HTTP > _document > It has a custom body class
- Document and App > Rendering via HTTP > _document > It injects custom head tags
- Document and App > Rendering via HTTP > _document > It passes props from Document.getInitialProps to Document
- Document and App > Rendering via HTTP > _document > It adds nonces to all scripts and preload links
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhancer correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceComponent correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceApp correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceApp and enhanceComponent correctly

<details>
<summary>Expand output</summary>

  ● Document and App › Rendering via HTTP › _document › It has a custom html class

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      15 |       test('It has a custom html class', async () => {
      16 |         const $ = await get$('/')
    > 17 |         expect($('html').hasClass('test-html-props')).toBe(true)
         |                                                       ^
      18 |       })
      19 |
      20 |       test('It has a custom body class', async () => {

      at Object.<anonymous> (integration/app-document/test/rendering.js:17:55)

  ● Document and App › Rendering via HTTP › _document › It has a custom body class

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      20 |       test('It has a custom body class', async () => {
      21 |         const $ = await get$('/')
    > 22 |         expect($('body').hasClass('custom_class')).toBe(true)
         |                                                    ^
      23 |       })
      24 |
      25 |       test('It injects custom head tags', async () => {

      at Object.<anonymous> (integration/app-document/test/rendering.js:22:52)

  ● Document and App › Rendering via HTTP › _document › It injects custom head tags

    expect(received).toMatch(expected)

    Expected substring: "body { margin: 0 }"
    Received string:    "body{display:none}body{display:block}"

      25 |       test('It injects custom head tags', async () => {
      26 |         const $ = await get$('/')
    > 27 |         expect($('head').text()).toMatch('body { margin: 0 }')
         |                                  ^
      28 |       })
      29 |
      30 |       test('It passes props from Document.getInitialProps to Document', async () => {

      at Object.<anonymous> (integration/app-document/test/rendering.js:27:34)

  ● Document and App › Rendering via HTTP › _document › It passes props from Document.getInitialProps to Document

    expect(received).toBe(expected) // Object.is equality

    Expected: "Hello Document"
    Received: ""

      30 |       test('It passes props from Document.getInitialProps to Document', async () => {
      31 |         const $ = await get$('/')
    > 32 |         expect($('#custom-property').text()).toBe('Hello Document')
         |                                              ^
      33 |       })
      34 |
      35 |       test('It adds nonces to all scripts and preload links', async () => {

      at Object.<anonymous> (integration/app-document/test/rendering.js:32:46)

  ● Document and App › Rendering via HTTP › _document › It adds nonces to all scripts and preload links

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      40 |           if ($(element).attr('nonce') !== nonce) noncesAdded = false
      41 |         })
    > 42 |         expect(noncesAdded).toBe(true)
         |                             ^
      43 |       })
      44 |
      45 |       test('It adds crossOrigin to all scripts and preload links', async () => {

      at Object.<anonymous> (integration/app-document/test/rendering.js:42:29)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhancer correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      54 |         const $ = await get$('/?withEnhancer=true')
      55 |         const nonce = 'RENDERED'
    > 56 |         expect($('#render-page-enhance-component').text().includes(nonce)).toBe(
         |                                                                            ^
      57 |           true
      58 |         )
      59 |       })

      at Object.<anonymous> (integration/app-document/test/rendering.js:56:76)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceComponent correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      62 |         const $ = await get$('/?withEnhanceComponent=true')
      63 |         const nonce = 'RENDERED'
    > 64 |         expect($('#render-page-enhance-component').text().includes(nonce)).toBe(
         |                                                                            ^
      65 |           true
      66 |         )
      67 |       })

      at Object.<anonymous> (integration/app-document/test/rendering.js:64:76)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceApp correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      70 |         const $ = await get$('/?withEnhanceApp=true')
      71 |         const nonce = 'RENDERED'
    > 72 |         expect($('#render-page-enhance-app').text().includes(nonce)).toBe(true)
         |                                                                      ^
      73 |       })
      74 |
      75 |       test('It renders ctx.renderPage with enhanceApp and enhanceComponent correctly', async () => {

      at Object.<anonymous> (integration/app-document/test/rendering.js:72:70)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceApp and enhanceComponent correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      76 |         const $ = await get$('/?withEnhanceComponent=true&withEnhanceApp=true')
      77 |         const nonce = 'RENDERED'
    > 78 |         expect($('#render-page-enhance-app').text().includes(nonce)).toBe(true)
         |                                                                      ^
      79 |         expect($('#render-page-enhance-component').text().includes(nonce)).toBe(
      80 |           true
      81 |         )

      at Object.<anonymous> (integration/app-document/test/rendering.js:78:70)

  ● Document and App › Rendering via HTTP › _app › It shows a custom tag

    expect(received).toBe(expected) // Object.is equality

    Expected: "Hello App"
    Received: ""

      102 |       test('It shows a custom tag', async () => {
      103 |         const $ = await get$('/')
    > 104 |         expect($('#hello-app').text()).toBe('Hello App')
          |                                        ^
      105 |       })
      106 |
      107 |       // For example react context uses shared module state

      at Object.<anonymous> (integration/app-document/test/rendering.js:104:40)

  ● Document and App › Rendering via HTTP › _app › It should share module state with pages

    expect(received).toBe(expected) // Object.is equality

    Expected: "UPDATED"
    Received: ""

      109 |       test('It should share module state with pages', async () => {
      110 |         const $ = await get$('/shared')
    > 111 |         expect($('#currentstate').text()).toBe('UPDATED')
          |                                           ^
      112 |       })
      113 |
      114 |       test('It should show valid error when thrown in _app getInitialProps', async () => {

      at Object.<anonymous> (integration/app-document/test/rendering.js:111:43)

  ● Document and App › Rendering via HTTP › _app › It should show valid error when thrown in _app getInitialProps

    expect(received).toMatch(expected)

    Expected substring: "page-index"
    Received string:    "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" crossorigin=\"anonymous\" nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1652142170870\"></script><script src=\"/_next/static/chunks/fallback/webpack.js?ts=1652142170870\" defer=\"\" crossorigin=\"anonymous\"></script><script src=\"/_next/static/chunks/fallback/main.js?ts=1652142170870\" defer=\"\" crossorigin=\"anonymous\"></script><script src=\"/_next/static/chunks/fallback/pages/_app.js?ts=1652142170870\" defer=\"\" crossorigin=\"anonymous\"></script><script src=\"/_next/static/chunks/fallback/pages/_error.js?ts=1652142170870\" defer=\"\" crossorigin=\"anonymous\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\" data-reactroot=\"\"></div><script src=\"/_next/static/chunks/fallback/react-refresh.js?ts=1652142170870\" crossorigin=\"anonymous\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\" crossorigin=\"anonymous\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{\"__NEXT_PAGE\":\"/\"},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Error\",\"message\":\"\\\"MyDocument.getInitialProps()\\\" should resolve to an object with a \\\"html\\\" prop set with a valid html string\",\"stack\":\"Error: \\\"MyDocument.getInitialProps()\\\" should resolve to an object with a \\\"html\\\" prop set with a valid html string\\n    at documentInitialProps (/home/runner/work/next.js/next.js/packages/next/dist/server/render.js:821:23)\\n    at async renderDocument (/home/runner/work/next.js/next.js/packages/next/dist/server/render.js:842:49)\\n    at async Object.renderToHTML (/home/runner/work/next.js/next.js/packages/next/dist/server/render.js:981:28)\\n    at async doRender (/home/runner/work/next.js/next.js/packages/next/dist/server/base-server.js:921:38)\\n    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/home/runner/work/next.js/next.js/packages/next/dist/server/base-server.js:1026:28)\\n    at async /home/runner/work/next.js/next.js/packages/next/dist/server/response-cache.js:74:36\"},\"gip\":true,\"scriptLoader\":[]}</script></body></html>"

      117 |
      118 |         let foundErr = false
    > 119 |         expect(await render('/')).toMatch('page-index')
          |                                   ^
      120 |         _app.replace(
      121 |           '// throw _app GIP err here',
      122 |           `throw new Error("${errMsg}")`

      at Object.<anonymous> (integration/app-document/test/rendering.js:119:35)

  ● Document and App › Client side › should detect the changes to pages/_app.js and display it

    page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "#hello-hmr"
    ============================================================

      304 |     return this.chain(() => {
      305 |       return page
    > 306 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      307 |         .then(async (el) => {
      308 |           // it seems selenium waits longer and tests rely on this behavior
      309 |           // so we wait for the load event fire before returning

      at lib/browsers/playwright.ts:306:10

  ● Document and App › Client side › should detect the changes to pages/_document.js and display it

    page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "#hello-hmr"
    ============================================================

      304 |     return this.chain(() => {
      305 |       return page
    > 306 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      307 |         .then(async (el) => {
      308 |           // it seems selenium waits longer and tests rely on this behavior
      309 |           // so we wait for the load event fire before returning

      at lib/browsers/playwright.ts:306:10

  ● Document and App › Client side › should keep state between page navigations

    page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "#random-number"
    ============================================================

      304 |     return this.chain(() => {
      305 |       return page
    > 306 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      307 |         .then(async (el) => {
      308 |           // it seems selenium waits longer and tests rely on this behavior
      309 |           // so we wait for the load event fire before returning

      at lib/browsers/playwright.ts:306:10

  ● Document and App › Client side › It should share module state with pages

    page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "#currentstate"
    ============================================================

      304 |     return this.chain(() => {
      305 |       return page
    > 306 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      307 |         .then(async (el) => {
      308 |           // it seems selenium waits longer and tests rely on this behavior
      309 |           // so we wait for the load event fire before returning

      at lib/browsers/playwright.ts:306:10

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| buildDuration | 15.4s | 15.3s | -130ms |
| buildDurationCached | 6.2s | 6.1s | -111ms |
| nodeModulesSize | 475 MB | 475 MB | ⚠️ +472 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.788 | 3.783 | 0 |
| / avg req/sec | 659.98 | 660.78 | +0.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.172 | 1.149 | -0.02 |
| /error-in-render avg req/sec | 2132.4 | 2176.43 | +44.03 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 308 B | 308 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.69 kB | 2.69 kB | ✓ |
| head-HASH.js gzip | 359 B | 359 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.7 kB | 5.7 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.64 kB | 2.64 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 391 B | 391 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| buildDuration | 17.4s | 17.3s | -27ms |
| buildDurationCached | 6.1s | 6.1s | ⚠️ +35ms |
| nodeModulesSize | 475 MB | 475 MB | ⚠️ +472 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.775 | 3.786 | ⚠️ +0.01 |
| / avg req/sec | 662.27 | 660.38 | ⚠️ -1.89 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.165 | 1.157 | -0.01 |
| /error-in-render avg req/sec | 2146.43 | 2160.47 | +14.04 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 29.2 kB | 29.2 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 73.1 kB | 73.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.71 kB | 2.71 kB | ✓ |
| head-HASH.js gzip | 357 B | 357 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.79 kB | 5.79 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.76 kB | 2.76 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.1 kB | 16.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| _buildManifest.js gzip | 456 B | 456 B | ✓ |
| Overall change | 456 B | 456 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js streaming/initial-shell | Change |
| - | - | - | - |
| index.html gzip | 529 B | 529 B | ✓ |
| link.html gzip | 543 B | 543 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 49b652d303b01b718724a429b418bfafc724fccc

**Review by shuding — COMMENTED** [review]
Can we have a test for this?

File: packages/next/server/render.tsx [hunk 1]
```diff
@@ -1373,11 +1374,13 @@ export async function renderToHTML(
...
-          return renderShell(EnhancedApp, EnhancedComponent).then(() => {
-            // When using concurrent features, we don't have or need the full
-            // html so it's fine to return nothing here.
-            return { html: '', head }
-          })
+          return renderShell(EnhancedApp, EnhancedComponent).then(
+            async (stream) => {
+              await stream.allReady
+              const html = await streamToString(stream)
+              return { html, head }
```
Comment (shuding) [inline packages/next/server/render.tsx:1381]: This means that we won't have streaming. Can we just return the shell as html here instead of the full stream?

**Review by shuding — APPROVED** [review]
