### PR TITLE
Ensure request specific caches for revalidate are reset

### LINKED ISSUE #60680: On Vercel only: unstable_cache serves stale data when revalidated twice in succession, Router Cache doesn't update
### Link to the code that reproduces this issue

https://github.com/mordechaim/vercel-revalidate

### To Reproduce

1. Navigate to the deployment on https://vercel-revalidate-three.vercel.app/
2. Check the date, it should be the date of the last time someone pressed the "Revalidate" button
3. Press once: The date properly updates
4. Press again: nothing happens

Another issue I noticed with this reproduction: Refreshing the page will show the old data until a 2nd refresh is done.

### Current vs. Expected behavior

`unstable_cache` serves stale data when revalidating more than once in a short period.

When running `next build && next start` and trying locally, everything works flawlessly.

The expected behavior is to always show the latest date.

The other issue is that even when the router cache does update (after a single revalidation), refreshing will show stale data until a second refresh is done.
I'm not sure if the 2nd issue is related or if I should open another issue.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64      
  Version: Windows 10 Home
Binaries:
  Node: 20.5.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.5-canary.58
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ijjk**
This ensures our in memory cache leveraged for the `fetch-cache` interface is reset per-request instead of using an arbitrary timeout so that we are always pulling the revalidate state from upstream correctly on new requests. 

Before: https://vercel-revalidate-3zi8wpexo-vtest314-ijjk-testing.vercel.app/
After: https://vercel-revalidate-70y5a8dbh-vtest314-ijjk-testing.vercel.app/

Closes: https://github.com/vercel/next.js/issues/60680

Closes NEXT-2144

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/cache-revalidate-delay | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.8s | N/A |
| buildDurationCached | 7.1s | 6.1s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +4.77 kB |
| nextStartRea..uration (ms) | 420ms | 425ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/cache-revalidate-delay | Change |
| - | - | - | - |
| 193.HASH.js gzip | 181 B | 182 B | N/A |
| 3f784ff6-HASH.js gzip | 53.4 kB | 53.4 kB | ✓ |
| 433-HASH.js gzip | 29 kB | 29 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 242 B | N/A |
| main-HASH.js gzip | 31.8 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.6 kB | 98.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/cache-revalidate-delay | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/cache-revalidate-delay | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 183 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 502 B | N/A |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 253 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.18 kB | 4.18 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | ✓ |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.4 kB | 3.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/cache-revalidate-delay | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 485 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/cache-revalidate-delay | Change |
| - | - | - | - |
| index.html gzip | 529 B | 528 B | N/A |
| link.html gzip | 541 B | 541 B | ✓ |
| withRouter.html gzip | 524 B | 523 B | N/A |
| Overall change | 541 B | 541 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/cache-revalidate-delay | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.9 kB | 94 kB | N/A |
| page.js gzip | 148 kB | 149 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/cache-revalidate-delay | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 626 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.5 kB | 37.5 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/cache-revalidate-delay | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 169 kB | 169 kB | ✓ |
| app-page-exp..prod.js gzip | 95.6 kB | 95.6 kB | ✓ |
| app-page-tur..prod.js gzip | 96.3 kB | 96.3 kB | ✓ |
| app-page-tur..prod.js gzip | 90.8 kB | 90.8 kB | ✓ |
| app-page.run...dev.js gzip | 142 kB | 142 kB | ✓ |
| app-page.run..prod.js gzip | 90.2 kB | 90.2 kB | ✓ |
| app-route-ex...dev.js gzip | 24.2 kB | 24.2 kB | ✓ |
| app-route-ex..prod.js gzip | 16.8 kB | 16.8 kB | ✓ |
| app-route-tu..prod.js gzip | 16.8 kB | 16.8 kB | ✓ |
| app-route-tu..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route.ru...dev.js gzip | 23.6 kB | 23.6 kB | ✓ |
| app-route.ru..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.39 kB | 9.39 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.67 kB | 9.67 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.39 kB | 9.39 kB | ✓ |
| pages-turbo...prod.js gzip | 22 kB | 22 kB | ✓ |
| pages.runtim...dev.js gzip | 22.6 kB | 22.6 kB | ✓ |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | ✓ |
| server.runti..prod.js gzip | 49.7 kB | 49.7 kB | N/A |
| Overall change | 894 kB | 894 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 258e02a7afda09f9d7670e31345cb676f42ce4b6

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 258e02a7afda09f9d7670e31345cb676f42ce4b6

`pnpm test-dev test/e2e/app-dir/app-custom-cache-handler/index.test.ts` (PPR)
- app-dir - custom-cache-handler - cjs > cjs module exports > should have logs from cache-handler
- app-dir - custom-cache-handler - cjs-default-export > cjs default export > should have logs from cache-handler
- app-dir - custom-cache-handler - esm > esm default export > should have logs from cache-handler

<details>
<summary>Expand output</summary>

  ● app-dir - custom-cache-handler - cjs › cjs module exports › should have logs from cache-handler

    TIMED OUT: success

    undefined

    Error: expect(received).toContain(expected) // indexOf

    Expected substring: "cache-handler get"
    Received string:    "yarn run v1.22.19
    $ /tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.bin/next
     ⚠ `experimental.ppr` has been defaulted to `true` because `__NEXT_EXPERIMENTAL_PPR` was set to `true` during testing.
     ⚠ `experimental.ppr` has been defaulted to `true` because `__NEXT_EXPERIMENTAL_PPR` was set to `true` during testing.
       ▲ Next.js 14.0.5-canary.65
       - Local:        http://localhost:39625·
     ⚠ `experimental.ppr` has been defaulted to `true` because `__NEXT_EXPERIMENTAL_PPR` was set to `true` during testing.
     ⚠ `experimental.ppr` has been defaulted to `true` because `__NEXT_EXPERIMENTAL_PPR` was set to `true` during testing.
     ✓ Ready in 2s
    initialized custom cache-handler
    cache handler - cjs module exports
    TypeError: _this_cacheHandler.resetRequestCache is not a function

      636 |
      637 |   if (hardError) {
    > 638 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      639 |   }
      640 |   return false
      641 | }

      at IncrementalCache.resetRequestCache (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/incremental-cache/index.js:125:88)
      at DevServer.handleRequestImpl (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/base-server.js:755:34)
      at ../async /tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/dev/next-dev-server.js:331:20
      at async Span.traceAsyncFn (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/trace/trace.js:151:20)
      at async DevServer.handleRequest (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
      at async invokeRender (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:163:21)
      at async handleRequest (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:342:24)
      at async requestHandlerImpl (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:366:13)
      at async Server.requestListener (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/start-server.js:140:13)
      initialized custom cache-handler
      cache handler - cjs module exports
      TypeError: _this_cacheHandler.resetRequestCache is not a function
      at IncrementalCache.resetRequestCache (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/incremental-cache/index.js:125:88)
      at DevServer.handleRequestImpl (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/base-server.js:755:34)
      at ../async /tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/dev/next-dev-server.js:331:20
      at async Span.traceAsyncFn (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/trace/trace.js:151:20)
      at async DevServer.handleRequest (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
      at async invokeRender (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:163:21)
      at async requestHandlerImpl (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:378:24)
      at async Server.requestListener (../../../../../../tmp/next-install-e2c440aa16932f4bf81bac09dd51ef4b2bc3012794dea828a77ccfda9df374b8/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/start-server.js:140:13)
      "
      at check (lib/next-test-utils.ts:638:11)
      at Object.<anonymous> (e2e/app-dir/app-custom-cache-handler/index.test.ts:19:7)

  ● app-dir - custom-cache-handler - cjs-default-export › cjs default export › should have logs from cache-handler

    TIMED OUT: success

    undefined

    Error: expect(received).toContain(expected) // indexOf

    Expected substring: "cache-handler get"
    Received string:    "yarn run v1.22.19
    $ /tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.bin/next
     ⚠ `experimental.ppr` has been defaulted to `true` because `__NEXT_EXPERIMENTAL_PPR` was set to `true` during testing.
     ⚠ `experimental.ppr` has been defaulted to `true` because `__NEXT_EXPERIMENTAL_PPR` was set to `true` during testing.
       ▲ Next.js 14.0.5-canary.65
       - Local:        http://localhost:35431·
     ⚠ `experimental.ppr` has been defaulted to `true` because `__NEXT_EXPERIMENTAL_PPR` was set to `true` during testing.
     ⚠ `experimental.ppr` has been defaulted to `true` because `__NEXT_EXPERIMENTAL_PPR` was set to `true` during testing.
     ✓ Ready in 1836ms
    initialized custom cache-handler
    cache handler - cjs default export
    TypeError: _this_cacheHandler.resetRequestCache is not a function

      636 |
      637 |   if (hardError) {
    > 638 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      639 |   }
      640 |   return false
      641 | }

      at IncrementalCache.resetRequestCache (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/incremental-cache/index.js:125:88)
      at DevServer.handleRequestImpl (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/base-server.js:755:34)
      at ../async /tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/dev/next-dev-server.js:331:20
      at async Span.traceAsyncFn (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/trace/trace.js:151:20)
      at async DevServer.handleRequest (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
      at async invokeRender (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:163:21)
      at async handleRequest (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:342:24)
      at async requestHandlerImpl (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:366:13)
      at async Server.requestListener (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/start-server.js:140:13)
      initialized custom cache-handler
      cache handler - cjs default export
      TypeError: _this_cacheHandler.resetRequestCache is not a function
      at IncrementalCache.resetRequestCache (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/incremental-cache/index.js:125:88)
      at DevServer.handleRequestImpl (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/base-server.js:755:34)
      at ../async /tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/dev/next-dev-server.js:331:20
      at async Span.traceAsyncFn (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/trace/trace.js:151:20)
      at async DevServer.handleRequest (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
      at async invokeRender (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:163:21)
      at async requestHandlerImpl (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:378:24)
      at async Server.requestListener (../../../../../../tmp/next-install-beb6a1e975546b110c82dcc7c6ffa3700434482414604dcb19aa4c3bcdbab982/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/start-server.js:140:13)
      "
      at check (lib/next-test-utils.ts:638:11)
      at Object.<anonymous> (e2e/app-dir/app-custom-cache-handler/index.test.ts:19:7)

  ● app-dir - custom-cache-handler - esm › esm default export › should have logs from cache-handler

    TIMED OUT: success

    undefined

    Error: expect(received).toContain(expected) // indexOf

    Expected substring: "cache-handler get"
    Received string:    "yarn run v1.22.19
    $ /tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.bin/next
     ⚠ `experimental.ppr` has been defaulted to `true` because `__NEXT_EXPERIMENTAL_PPR` was set to `true` during testing.
     ⚠ `experimental.ppr` has been defaulted to `true` because `__NEXT_EXPERIMENTAL_PPR` was set to `true` during testing.
       ▲ Next.js 14.0.5-canary.65
       - Local:        http://localhost:32921·
     ⚠ `experimental.ppr` has been defaulted to `true` because `__NEXT_EXPERIMENTAL_PPR` was set to `true` during testing.
     ⚠ `experimental.ppr` has been defaulted to `true` because `__NEXT_EXPERIMENTAL_PPR` was set to `true` during testing.
     ✓ Ready in 1077ms
    initialized custom cache-handler
    cache handler - esm default export
    TypeError: _this_cacheHandler.resetRequestCache is not a function

      636 |
      637 |   if (hardError) {
    > 638 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      639 |   }
      640 |   return false
      641 | }

      at IncrementalCache.resetRequestCache (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/incremental-cache/index.js:125:88)
      at DevServer.handleRequestImpl (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/base-server.js:755:34)
      at ../async /tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/dev/next-dev-server.js:331:20
      at async Span.traceAsyncFn (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/trace/trace.js:151:20)
      at async DevServer.handleRequest (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
      at async invokeRender (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:163:21)
      at async handleRequest (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:342:24)
      at async requestHandlerImpl (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:366:13)
      at async Server.requestListener (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/start-server.js:140:13)
      initialized custom cache-handler
      cache handler - esm default export
      TypeError: _this_cacheHandler.resetRequestCache is not a function
      at IncrementalCache.resetRequestCache (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/incremental-cache/index.js:125:88)
      at DevServer.handleRequestImpl (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/base-server.js:755:34)
      at ../async /tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/dev/next-dev-server.js:331:20
      at async Span.traceAsyncFn (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/trace/trace.js:151:20)
      at async DevServer.handleRequest (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
      at async invokeRender (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:163:21)
      at async requestHandlerImpl (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/router-server.js:378:24)
      at async Server.requestListener (../../../../../../tmp/next-install-9e37ef4205b8063fa7e83dc12747439d974f508d02eb93608a81c113e3c600a4/node_modules/.pnpm/file+..+next-repo-d9440d083658d41cacededc4859e6ed5dc8934adb688a3f7378670c30aad2fc2+packages+n_afo6qei7znet6lktswf6umxppe/node_modules/next/dist/server/lib/start-server.js:140:13)
      "
      at check (lib/next-test-utils.ts:638:11)
      at Object.<anonymous> (e2e/app-dir/app-custom-cache-handler/index.test.ts:19:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: packages/next/src/server/lib/incremental-cache/index.ts [hunk 1]
```diff
@@ -213,6 +215,10 @@ export class IncrementalCache implements IncrementalCacheType {
     return fetchCache ? pathname : normalizePagePath(pathname)
   }
 
+  resetRequestCache() {
+    this.cacheHandler?.resetRequestCache()
```
Comment (ijjk) [inline packages/next/src/server/lib/incremental-cache/index.ts:219]:
```suggestion
    this.cacheHandler?.resetRequestCache?.()
```

**Comment by ijjk** [comment]
## Failing test suites 
Commit: b05eef2e04fdeec32cbc063743799b8a0d739130

`pnpm test-start test/e2e/prerender.test.ts`
- Prerender > should on-demand revalidate for fallback: blocking with onlyGenerated if generated

<details>
<summary>Expand output</summary>

  ● Prerender › should on-demand revalidate for fallback: blocking with onlyGenerated if generated

    expect(received).toMatch(expected)

    Expected pattern: /(HIT|STALE)/
    Received string:  "MISS"

      2294 |
      2295 |         expect(initialTime).toBe($2('#time').text())
    > 2296 |         expect(res2.headers.get('x-nextjs-cache')).toMatch(/(HIT|STALE)/)
           |                                                    ^
      2297 |
      2298 |         const res3 = await fetchViaHTTP(
      2299 |           next.url,

      at Object.toMatch (e2e/prerender.test.ts:2296:52)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by huozhi — APPROVED** [review]

File: packages/next/src/server/lib/incremental-cache/fetch-cache.ts [hunk 2]
```diff
@@ -7,7 +7,7 @@ import {
 } from '../../../lib/constants'
 
 let rateLimitedUntil = 0
-let memoryCache: LRUCache<string, CacheHandlerValue> | undefined
+export let memoryCache: LRUCache<string, CacheHandlerValue> | undefined
```
Comment (huozhi) [inline packages/next/src/server/lib/incremental-cache/fetch-cache.ts:10]: is this going to be imported somewhere?

Comment (ijjk) [reply packages/next/src/server/lib/incremental-cache/fetch-cache.ts:10]: Oh not anymore, leftover from previous approach

Comment (ijjk) [inline packages/next/src/server/lib/incremental-cache/fetch-cache.ts:10]:
```suggestion
let memoryCache: LRUCache<string, CacheHandlerValue> | undefined
```
