### PR TITLE
Fix interception/detail routes being triggered by router refreshes

### LINKED ISSUE #60844: router.refresh() causes intercepted route to switch to the intercepting route/modal
### Link to the code that reproduces this issue

https://github.com/vercel/nextgram

### To Reproduce

1. Add code to `router.refresh()` on the intercepted route:

```diff
diff --git a/app/photos/[id]/page.tsx b/app/photos/[id]/page.tsx
index 4085ee7..45b6027 100644
--- a/app/photos/[id]/page.tsx
+++ b/app/photos/[id]/page.tsx
@@ -1,7 +1,18 @@
+'use client';
+
+import { useRouter } from 'next/navigation';
+
 export default function PhotoPage({
   params: { id },
 }: {
   params: { id: string };
 }) {
-  return <div className="card">{id}</div>;
+  const router = useRouter();
+
+  return (
+    <div className="card">
+      {id}
+      <button onClick={router.refresh}>Refresh</button>
+    </div>
+  );
 }
```

2. Click the refresh button.

### Current vs. Expected behavior

I expect the route to stay the same on `router.refresh()`.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
Binaries:
  Node: 21.6.0
  npm: 10.2.4
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.5-canary.67
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

https://github.com/vercel/next.js/assets/2367158/ee3300c2-662d-4aa8-8c42-0baa9264e516

<sub>[NEXT-2737](https://linear.app/vercel/issue/NEXT-2737/routerrefresh-causes-intercepted-route-to-switch-to-the-intercepting)</sub>

### LINKED ISSUE #62470: Issues with intercepting routes in dev mode
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/dev-mode-route-intercept-bug-6rxwz9

### To Reproduce

Note that there's no styling in order to simplify the example, so calling it a "modal" is a bit of a stretch. This is a simplification of https://github.com/vercel/nextgram, where I also experience the issue.

1. Start application: `next dev`
image

2. Click "Open Modal" to open the "photos modal". Works as expected.
image

3. Refresh the page to see the photos page (no modal). Works as expected.
image

4. Edit any page, ex: in `app/page.tsx` add "!" to the "Open Modal" text.
image

6. Allow the photos page to reload automatically. The photos page now shows the modal rendering with the photos page as the "background"
image

### Current vs. Expected behavior

I would expect the hotreload to have no visible effect, but instead it seems to cause the route to be suddenly intercepted. I'm not sure if this is a bug in the implementation (this repros on https://github.com/vercel/nextgram as well) or in the route interception logic during dev mode.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I've tested this on latest canary (14.1.1-canary.70), 14.1.0 and 14.0.0 and all exhibit the same issue.
I first ran into it in a project I was developing in Windows, so I tried the running the nextgram repo locally (on canary) to see if it was a problem with my code. When that had the same bug, I tried in WSL with the same result. In making this issue I verified that it also happened in the codesandbox env.

Thanks! <3

### PR DESCRIPTION
**Pull request by ztanner**
### What
Actions that revalidate the router state by kicking off a refetch (such as `router.refresh()` or dev fast refresh) would incorrectly trigger an interception route if one matched the current URL, or in the case of already being on an intercepted route, would trigger the full detail page instead.

### Why
Interception rewrites use the `nextUrl` header to determine if the requested path should be rewritten to a different path. We currently forward that header indiscriminately, which means that if you were on a non-intercepted route and called `router.refresh()`, the UI would change to the intercepted content instead (since it would treat it the same as a soft-navigation).

### How
This updates various reducers to only forward the `nextUrl` header if there's an interception route present in the tree. If there is, we want to refresh its data, rather than the data for the underlying page. The reverse is also true: if we were on the "full" page, and triggered a `router.refresh()`, we won't forward `nextUrl` meaning it won't fetch the interception data. 

In order to determine if an interception route is present in the tree, I had to add a new segment type for dynamic interception routes, as by the time they reach the client they are stripped of their interception marker.

**Note: There are a series of bugs related to `router.refresh` with parallel/interception routes, such as the previous page/slot content disappearing when triggering a refresh. This does not address all of those cases, but I'm working through them!**

Fixes #60844
Fixes #62470
Closes NEXT-2737

### CODE REVIEW

**Comment by ztanner** [comment]
* **#63263** <a href="https://app.graphite.dev/github/pr/vercel/next.js/63263?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ztanner and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: packages/next/src/client/components/router-reducer/reducers/server-action-reducer.ts [hunk 1]
```diff
@@ -57,12 +57,12 @@ async function fetchServerAction(
...
-  // if it's different from the current `nextUrl`. This indicates the route has already been intercepted,
-  // and so the action should be as well. Otherwise the server action might be intercepted
-  // with the wrong action id (ie, one that corresponds with the intercepted route)
-  const includeNextUrl = state.nextUrl && state.nextUrl !== newNextUrl
+  // only pass along the `nextUrl` param (used for interception routes) if the current route was intercepted.
+  // If the route has been intercepted, the action should be as well.
+  // Otherwise the server action might be intercepted with the wrong action id
+  // (ie, one that corresponds with the intercepted route)
+  const includeNextUrl =
+    state.nextUrl && hasInterceptionRouteInCurrentTree(state.tree)
```
Comment (ztanner) [inline packages/next/src/client/components/router-reducer/reducers/server-action-reducer.ts:65]: The previous implementation here solved a similar problem, but it relied on an incorrect assumption about `nextUrl`. This more accurately determines if an interception marker is present in the tree. 

Confirmed that the previous test that was added for this case still passes ([test ref](https://github.com/vercel/next.js/blob/6687634ab849477855e5130859ccb60edcf291a3/test/e2e/app-dir/actions/app-action.test.ts#L1011-L1049))

**Review by feedthejim — APPROVED** [review]
