### PR TITLE
Export URLPattern from next/server

### LINKED ISSUE #38131: Cannot find name 'URLPattern'
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.9.0
      Yarn: 1.22.10
      pnpm: 4.14.4
    Relevant packages:
      next: 12.2.0
      eslint-config-next: 12.2.0
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

vercel

### Describe the Bug

I am trying to upgrade to the GA Middlware. I previously had used logic such as 
```
const { page }  = req
...
const isActualPage = !!page.name
```
to test against the URL in my middleware so i could be sure that I was only affecting urls that corresponded to my `pages` directory. Since this was removed in next `12.2` I had begun following the guide found [here](https://nextjs.org/docs/messages/middleware-request-page) to upgrade my application to use `URLPattern` instead. I am, however, having trouble using that as VSCode and TS are telling that name doesn't exist. I am having a hard time finding any information on `URLPattern` at all in other applications, so debugging as been tough.

Screen Shot 2022-06-28 at 6 26 47 PM

If there's something I need to add my global namespaces or otherwise, this just doesn't seem to work with the default Next.js TS config.

### Expected Behavior

`new URLPattern()` should be available in VSCode/TS globals

### Link to reproduction

https://codesandbox.io/s/ecstatic-marco-s3lo6n?file=/middleware.ts

### To Reproduce

1. Create a `middleware.ts` in your src or root folder
2. Try and use `new URLPattern()`

### PR DESCRIPTION
**Pull request by Schniz**
This commit allows the users to import URLPattern from `next/server`,
by defining a key that uses `global.URLPattern`.

Why is this any good? or: why don't we add URLPattern to the global namespace?

URLPattern is exposed as global on Edge Runtime _only_. This means that if we define a
constructor in global namespace in our TypeScript definitions, people might
have runtime errors in their Node.js functions.

Importing from `next/server` enables users to get the constructor without
risking in runtime errors and wrong type definitions.

Keep in mind, that with the current implementation, we do not check if the
constructor actually exists, but `next/server` shouldn't be imported in
Node.js functions, AFAIK.

## Related

- Fixes #38131

## Bug

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

### CODE REVIEW

File: test/e2e/middleware-general/app/middleware.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
-/* global globalThis, URLPattern */
-import { NextRequest, NextResponse } from 'next/server'
+/* global globalThis */
+import { NextRequest, NextResponse, URLPattern } from 'next/server'
```
Comment (ijjk) [inline test/e2e/middleware-general/app/middleware.js:2]: Can we add this in TypeScript middleware test suite to ensure the types are correct as well? https://github.com/vercel/next.js/blob/canary/test/production/middleware-typescript/app/middleware.ts

**Review by ijjk — APPROVED** [review]
Thanks!
