### PR TITLE
Expose app.js

### LINKED ISSUE #88: Top-level app component and animated route transitions
Having animated route transitions would be nice, as this is one of the many benefits through client-side routing. Doing so should be left up to the user in my opinion (some people prefer CSS transitions over more fine-grained control with `react-motion` etc). As I understand it, one would need to modify the top-level App component.

The [client entry file](https://github.com/zeit/next.js/blob/master/client/next.js#L13) seems to look for a globally assigned `__NEXT_DATA__.app` variable but I can't find any documentation on that.

### LINKED ISSUE #4029: Can't restrict pages routed through next-router with next/link.
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

I am building a wrapper middleware in express to restrict an entire next application from the public without a password and a username. It should catch every get request that's coming through, check for a logged-in boolean on a session found with an id from a session-cookie.
## Current Behavior

It works as expected for every normal browser http get request, however it does not work for pages served through the next-router. I noticed this because I had reused a logo component on the restriction page which simply linked to '/' and even though the request went through the middleware and the correct code was run (basic if else with a logged-in boolean) it did serve the homepage.
## Steps to Reproduce (for bugs)

```JavaScript
const express = require('express')
const next = require('next')

const app = next({
    dir: '.',
    dev: process.env.NODE_ENV !== 'PRODUCTION'
})

const handle = app.getRequestHandler()
const server = express()

/* HARDCODED VALIDATE BOOLEAN */
const authenticated = false

app.prepare()

.then(() => {
    /*
        Page restriction middleware
    */
    server.get('*', (req, res) => {
        console.log(req.path)
        if (!authenticated) {
            console.log('Not authenticated.')
            return app.render(req, res, '/restriction')
        } else {
            console.log('Authenticated.')
            return handle(req, res)
        }

    })

    const PORT = process.env.PORT || process.env.port || 3000
    server.listen(PORT)

})
```

This code should never log 'Authenticated' much less actually serve the requested resource right?
Here's the thing, it never logs 'Authenticated' but it does serve any page you want if it was requested with next/link.

Front-end to reproduce:

index.js
```JavaScript
export default () =>
  <div>Restricted page. You cant see this without bypassing the express routing middleware.</div>
```

restriction.js
```JavaScript
import Link from 'next/link'
export default () =>
    <Link href="/"><button>I am the magic resctriction bypasser.</button></Link>
```

What's sort of funny about this is that you can click on that Link in the restriction page and then refresh the page and the middleware will render the restriction page again.

### PR DESCRIPTION
**Pull request by timneutkens**
Fixes #88
Fixes #4029 

Examples will be added when this PR lands, since this PR involves a lot of changes I didn't want to mess up the diff with unrelated files

- Is rendered on both client and server side
- Markup can be persisted between page changes
- `this.state` should not be overwritten. Instead create a new component to handle the state ([layout example](./examples/layout-component))
- Handles calling `getInitialProps` of the **page** `Component`
- Implements `componentDidCatch` on the client side, and renders the error page accordingly. ([overriding `componentDidCatch` example](./examples/componentdidcatch))
- The `Container` implements React Hot Loader when in development mode.
- The `Container` implements scrolling to a hash when using `<Link href="/about#example-hash">`

To override the default `_app.js` behaviour you can create a file `./pages/_app.js`, where you can extend the `App` class:

```js
import App, {Container} from 'next/app'
import React from 'react'

export default class MyApp extends App {
  static async getInitialProps ({ Component, ctx }) {
    let pageProps = {}

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx)
    }

    return {pageProps}
  }

  render () {
    const {Component, pageProps} = this.props
    return <Container>
      <Component {...pageProps} />
    </Container>
  }
}
```

### CODE REVIEW

File: lib/app.js [hunk 1]
```diff
@@ -1,24 +1,34 @@
...
 import { makePublicRouterInstance } from './router'
 
 export default class App extends Component {
   state = {
     hasError: null
   }
 
+  static displayName = 'App'
+
+  static async getInitialProps ({ Component, router, ctx }) {
```
Comment (arunoda) [inline lib/app.js]: If user didn't override `getInitialProps` in his/her sub class, is this going to execute?

File: test/integration/app-document/pages/_document.js [hunk 2]
```diff
@@ -0,0 +1,31 @@
+// _document is only rendered on the server side and not on the client side
+// Event handlers like onClick can't be added to this file
+
+// ./pages/_document.js
+import Document, { Head, Main, NextScript } from 'next/document'
+import flush from 'styled-jsx/server'
+
+export default class MyDocument extends Document {
+  static getInitialProps ({ renderPage }) {
+    const { html, head, errorHtml, chunks } = renderPage()
```
Comment (arunoda) [inline test/integration/app-document/pages/_document.js]: Shall we get these from the `Document`. Like this:

```
static getInitialProps(info) {
  const initialProps = Document.getInitialProps(info);
  return {
    ...initialProps,
    customProperty: 'Hello World'
  } 
}
```

Then it's very simple and we don't need expose internal things like `renderPage`. And let's make sure we update this for `_app.js` and inside README as well.

**Comment by arunoda** [comment]
Looks pretty nice to me.

**Comment by corysimmons** [comment]
Just confirming this is the PR to watch for page transition support?

File: lib/app.js [hunk 3]
```diff
@@ -83,39 +96,48 @@ class Container extends Component {
...
 }
 
-function createUrl (router) {
+export function createUrl (router) {
   return {
-    query: router.query,
-    pathname: router.pathname,
-    asPath: router.asPath,
+    get query () {
+      warn(`Warning: 'url.query' is deprecated. https://err.sh/next.js/url-deprecated`)
```
[the remark this answers is not in the document]
Comment (timneutkens) [reply lib/app.js]: Done 👍

File: server/build/webpack/utils.js [hunk 4]
```diff
@@ -17,7 +17,7 @@ export async function getPagePaths (dir, {dev, isServer, pageExtensions}) {
 
   if (dev) {
```
[the remark this answers is not in the document]
Comment (timneutkens) [reply server/build/webpack/utils.js]: Done 🔑

**Comment by timneutkens** [comment]
@corysimmons among other things, yeah it's one of the possible ways to apply this 👍

File: lib/app.js [hunk 5]
```diff
@@ -83,39 +96,50 @@ class Container extends Component {
...
+      warnUrl()
+      return router.pathname
+    },
+    get asPath () {
+      warnUrl()
+      return router.asPath
+    },
     back: () => {
-      warn(`Warning: 'url.back()' is deprecated. Use "window.history.back()"`)
+      warn(`Warning: 'url.back()' is deprecated. Use "window.history.back()" https://err.sh/next.js/url-deprecated`)
```
Comment (arunoda) [inline lib/app.js]: Don't we use something like `warnOnce` or something.

File: readme.md [hunk 6]
```diff
@@ -923,6 +923,47 @@ const HelloBundle = dynamic({
...
+### Custom `<App>`
+
+<p><details>
+  <summary><b>Examples</b></summary>
+  <ul><li><a href="./examples/layout-component">Using `_app.js` for layout</a></li></ul>
+  <ul><li><a href="./examples/componentdidcatch">Using `_app.js` to override `componentDidCatch`</a></li></ul>
+</details></p>
+
+- Is rendered on both client and server side
+- `this.state` should not be overwritten. Instead create a new component to handle the state ([layout example](./examples/layout-component))
```
Comment (arunoda) [inline readme.md]: This is not clear. What are we going to say.

File: readme.md [hunk 7]
```diff
@@ -923,6 +923,47 @@ const HelloBundle = dynamic({
...
+- Handles calling `getInitialProps` of the **page** `Component`
+- Implements `componentDidCatch` on the client side, and renders the error page accordingly. ([overriding `componentDidCatch` example](./examples/componentdidcatch))
```
Comment (arunoda) [inline readme.md]: Let's try not say what've inside `app.js`. But what the user can do with this. Here's a sample:

Next.js has a App layout which initialize pages in your app. You can override it with `pages/_app.js` and implement:

* Layouts works across pages
* Animations in between pages
* Keep the DOM state when navigating page
* Provide additional properties to initial props of pages
* Custom error messages by catching errors
...

File: lib/app.js (hunk 5 above)
Comment (timneutkens) [reply lib/app.js]: I believe this was deprecated in v2 or v3. That's what I didn't want to touch it too much, just adding the url to the message. In theory we could use the same message though. Will update it.

File: readme.md (hunk 7 above)
Comment (timneutkens) [reply readme.md]: Updated

File: readme.md (hunk 6 above)
Comment (timneutkens) [reply readme.md]: Added a clearer example.

File: readme.md [hunk 8]
```diff
@@ -923,6 +923,77 @@ const HelloBundle = dynamic({
...
+</details></p>
+
+Next.js uses the `App` component to initialize pages. This can be used for:
+
+- Persisting layout between page changes
+- Keeping state when navigating pages
+- Custom error handling using `componentDidCatch`
+- Handling of calling **page** `Component`s `getInitialProps`
+
+To override the default `_app.js` behaviour you can create a file `./pages/_app.js`, where you can extend the `App` class:
```
Comment (arunoda) [inline readme.md]: To override, create a file in `./pages/_app.js` and override the `App` class as shown below:

**Review by arunoda — COMMENTED** [review]
Added some suggestions for docs.
May contain grammar errors :D

**Comment by PetrSnobelt** [comment]
Is it possible to have multiple layouts using this feature? 
It looks like the only way is to use if statement in `_app.js` which can be difficult. 
Will be fine if a page can specify which app/layout would like to use.

**Comment by timneutkens** [comment]
> It looks like the only way is to use if statement in _app.js which can be difficult.

This is definitely not the way to go. What you could do however is this:

@tz5514 made a PR implementing a custom `renderPage` api. The change he made actually involved only 1 change in the `App` component. So his idea can be implemented by the community based on this pull request. The specific PR is: https://github.com/zeit/next.js/pull/3552

**Comment by arunoda** [comment]
@PetrSnobelt 

> It looks like the only way is to use if statement in _app.js which can be difficult.

I don't find using `if` is difficult. Usually, that's the way you can show different content in React apps.
I am not just talking about `if`, but all the basic JS control structures.

> Will be fine if a page can specify which app/layout would like to use.

Yes you can do that.  You can mention the layout name in your page like this.

```
const MyPage = () => (
  <div>This is my page</div>
)

MyPage.layout = "main-layout"

export default MyPage
```

Then you can read the `layout` field inside the render function of `_app.js` and use the correct layout.
You can even use our `dynamic` import support to avoid loading all the layouts at once.

**Review by arunoda — APPROVED** [review]
This is looks great.

**Comment by tz5514** [comment]
@timneutkens There is a missing item `Custom <App>` in `readme.md`, 
beween `Dynamic Import` and `Custom <Document>`:
image

**Comment by timneutkens** [comment]
@tz5514 great catch, I believe the table of contents hasn't been updated for a while, I'll udpate it right now 👍

**Comment by timneutkens** [comment]
Fixed the table of contents ✅

**Comment by PetrSnobelt** [comment]
@timneutkens @aronuda That makes sense, thanks

**Comment by timneutkens** [comment]
@PetrSnobelt As you can see here: https://github.com/zeit/next.js/pull/3461/files#diff-c39f41208533f29db9e4150b6efd2b68

The change involves changing app.js, so yeah, definitely possible 😄

**Review by rauchg — APPROVED** [review]

**Comment by tz5514** [comment]
Finally! Huge thanks for @timneutkens and core team. Now I can release next-layouts in fews days. Great work, thanks!

**Comment by willmeierart** [comment]
So, will we have to wait for 6 to use this feature? Thank you soooo much for opening this door for us!

**Comment by timneutkens** [comment]
It'll be out on canary when another PR I'm working on right now gets merged 👍

**Comment by tim-phillips** [comment]
[6.0.0-canary.4](https://github.com/zeit/next.js/releases/tag/6.0.0-canary.4) is released
