### PR TITLE
fix: show the error message if `images.loaderFile` doesn't export a default function

### LINKED ISSUE #63803: TypeError: Cannot use 'in' operator to search for '__next_img_default' in undefined
### Link to the code that reproduces this issue

https://github.com/ojj1123/next-custom-loader-issue-repro

### To Reproduce

1. pnpm install
2. pnpm dev
3. and then you can see the issue below:

## Expected behavior
I want to configure the image loader globally.
[Nextjs docs](https://nextjs.org/docs/pages/api-reference/components/image#loaderfile) describes that I can configure the image loader at `next.config.js`:
```js
const nextConfig = {
  images: {
    loader: 'custom',
    loaderFile: '/custom-loader.ts',
  },
};

export default nextConfig;
```

## Current
But currently, nextjs occurs this error:
It is shown at either App router or Page router
```
TypeError: Cannot use 'in' operator to search for '__next_img_default' in undefined
```

스크린샷 2024-03-28 16 10 53

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 8.15.4
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Image optimization (next/image, next/legacy/image)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

This error occurs at `getImgProps`

https://github.com/vercel/next.js/blob/0c21ff7df6f3cfc4b494bb78a354b68d7117ac96/packages/next/src/shared/lib/get-img-props.ts#L286-L294

`rest.loader` is what the user pass `loader` function at Image's `loader` prop. **But I didn't pass the custom loader at `Image` component so then the value of `loader` variable above would be `defaultLoader`.** `__next_img_default` property is only in `defaultLoader` for [checking whether or not the user pass the custom `loader`](https://github.com/vercel/next.js/blob/0c21ff7df6f3cfc4b494bb78a354b68d7117ac96/packages/next/src/shared/lib/image-loader.ts#L69-L71). I don't know why the value is `undefined`

#### Update
**If setting `images.loaderFile` at `next.config.js`, `defaultLoader` module is resolved as `config.images.loaderFile` during build. So we have to export loader function as default.** https://github.com/vercel/next.js/issues/63803#issuecomment-2026850654
https://github.com/vercel/next.js/blob/b434ea401cf2b12fca35e2ad7543f284b273254f/packages/next/src/build/create-compiler-aliases.ts#L112-L119

Nextjs internally import/export `defaultLoader` as a default function
https://github.com/vercel/next.js/blob/29d53c87ea53336cf1e436119975d8e53bc28827/packages/next/src/shared/lib/image-external.tsx#L7-L8

After build, the build assets is like:
```ts
// next.config.js
const nextConfig = {
  images: {
    loader: 'custom',
    loaderFile: '/custom-loader.js'
  }
}

// custom-loader.js
// ⚠️ named export
export function customLoader({ src }) {
  return src
}
```
**Since custom loader is exported as a named, `defaultLoader.default` is `undefined`**
```ts
// build asset for getImgProps.js
 import defaultLoader from '/custom-loader.js' // Resolve through webpack alias

...
 let loader: ImageLoaderWithConfig = rest.loader || defaultLoader.default // ⚠️ defaultLoader.default is undefined
  
 // Remove property so it's not spread on <img> element 
 delete rest.loader 
 delete (rest as any).srcSet 
  
 // This special value indicates that the user 
 // didn't define a "loader" prop or "loader" config. 
 const isDefaultLoader = '__next_img_default' in loader 
...
```

### PR DESCRIPTION
**Pull request by ojj1123**
fixes #63803 

## What I do?

- If the loader file export the function as `named`, Next.js throws the error.
- But this error is a bit confusing for the developers.
- So I open this PR for showing the accurate error message.

### AS-IS

```
TypeError: Cannot use 'in' operator to search for '__next_img_default' in undefined
```
스크린샷 2024-03-28 16 10 53

### TO-BE

```
Error: The loader file must export a default function that returns a string.
See more info here: https://nextjs.org/docs/messages/invalid-images-config
```
스크린샷 2024-03-28 16 10 53

### CODE REVIEW

**Comment by ojj1123** [comment]
## Question
Should I write the test code?

**Comment by styfle** [comment]
> Should I write the test code?

Yes, please add a test to confirm this works as expected

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ojj1123/next.js fix/custom-loader-config | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.8s | N/A |
| buildDurationCached | 7.4s | 6.1s | N/A |
| nodeModulesSize | 199 MB | 199 MB | ⚠️ +3.38 kB |
| nextStartRea..uration (ms) | 403ms | 400ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | ojj1123/next.js fix/custom-loader-config | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 31.4 kB | 31.4 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | ✓ |
| 8299-HASH.js gzip | 5.04 kB | 5.11 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 242 B | 241 B | N/A |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 99 kB | 99 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ojj1123/next.js fix/custom-loader-config | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ojj1123/next.js fix/custom-loader-config | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.21 kB | 4.3 kB | N/A |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 2.36 kB | 2.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ojj1123/next.js fix/custom-loader-config | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ojj1123/next.js fix/custom-loader-config | Change |
| - | - | - | - |
| index.html gzip | 528 B | 528 B | ✓ |
| link.html gzip | 540 B | 541 B | N/A |
| withRouter.html gzip | 523 B | 522 B | N/A |
| Overall change | 528 B | 528 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | ojj1123/next.js fix/custom-loader-config | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.4 kB | 95.4 kB | N/A |
| page.js gzip | 3.06 kB | 3.06 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | ojj1123/next.js fix/custom-loader-config | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 625 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | ojj1123/next.js fix/custom-loader-config | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | ✓ |
| app-page-exp..prod.js gzip | 97 kB | 97 kB | ✓ |
| app-page-tur..prod.js gzip | 98.8 kB | 98.8 kB | ✓ |
| app-page-tur..prod.js gzip | 93 kB | 93 kB | ✓ |
| app-page.run...dev.js gzip | 144 kB | 144 kB | ✓ |
| app-page.run..prod.js gzip | 91.5 kB | 91.5 kB | ✓ |
| app-route-ex...dev.js gzip | 21.4 kB | 21.4 kB | ✓ |
| app-route-ex..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route.ru...dev.js gzip | 21.1 kB | 21.1 kB | ✓ |
| app-route.ru..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim...dev.js gzip | 23.1 kB | 23.1 kB | ✓ |
| pages.runtim..prod.js gzip | 22.4 kB | 22.4 kB | ✓ |
| server.runti..prod.js gzip | 51 kB | 51 kB | ✓ |
| Overall change | 945 kB | 945 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ojj1123/next.js fix/custom-loader-config | Change |
| - | - | - | - |
| 0.pack gzip | 1.58 MB | 1.58 MB | N/A |
| index.pack gzip | 106 kB | 106 kB | ⚠️ +323 B |
| Overall change | 106 kB | 106 kB | ⚠️ +323 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [8358],
   {
-    /***/ 1552: /***/ function (
+    /***/ 4070: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function () {
-          return __webpack_require__(5237);
+          return __webpack_require__(396);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 2016: /***/ function (module, exports, __webpack_require__) {
+    /***/ 8490: /***/ function (module, exports, __webpack_require__) {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -40,15 +40,15 @@
         __webpack_require__(422)
       );
       const _head = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(6074)
+        __webpack_require__(2457)
       );
-      const _getimgprops = __webpack_require__(9571);
-      const _imageconfig = __webpack_require__(6567);
-      const _imageconfigcontextsharedruntime = __webpack_require__(419);
-      const _warnonce = __webpack_require__(4486);
-      const _routercontextsharedruntime = __webpack_require__(162);
+      const _getimgprops = __webpack_require__(7932);
+      const _imageconfig = __webpack_require__(5706);
+      const _imageconfigcontextsharedruntime = __webpack_require__(9483);
+      const _warnonce = __webpack_require__(9035);
+      const _routercontextsharedruntime = __webpack_require__(4829);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(6996)
+        __webpack_require__(7240)
       );
       // This is replaced by webpack define plugin
       const configEnv = {
@@ -56,6 +56,7 @@
         imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
         path: "/_next/image",
         loader: "default",
+        loaderFile: "",
         dangerouslyAllowSVG: false,
         unoptimized: false,
       };
@@ -333,6 +334,14 @@
           }, [onLoadingComplete]);
           const [blurComplete, setBlurComplete] = (0, _react.useState)(false);
           const [showAltText, setShowAltText] = (0, _react.useState)(false);
+          if (
+            config.loaderFile &&
+            typeof _imageloader.default === "undefined"
+          ) {
+            throw new Error(
+              "The loader file must export a default function that returns a string.\nSee more info here: https://nextjs.org/docs/messages/invalid-images-config"
+            );
+          }
           const { props: imgAttributes, meta: imgMeta } = (0,
           _getimgprops.getImgProps)(props, {
             defaultLoader: _imageloader.default,
@@ -379,7 +388,7 @@
       /***/
     },
 
-    /***/ 9571: /***/ function (
+    /***/ 7932: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -395,9 +404,9 @@
           return getImgProps;
         },
       });
-      const _warnonce = __webpack_require__(4486);
-      const _imageblursvg = __webpack_require__(133);
-      const _imageconfig = __webpack_require__(6567);
+      const _warnonce = __webpack_require__(9035);
+      const _imageblursvg = __webpack_require__(2642);
+      const _imageconfig = __webpack_require__(5706);
       const VALID_LOADING_VALUES =
         /* unused pure expression or super */ null && [
           "lazy",
@@ -766,7 +775,7 @@
       /***/
     },
 
-    /***/ 133: /***/ function (__unused_webpack_module, exports) {
+    /***/ 2642: /***/ function (__unused_webpack_module, exports) {
       "use strict";
       /**
        * A shared function, used on both client and server, to generate a SVG blur placeholder.
@@ -821,7 +830,7 @@
       /***/
     },
 
-    /***/ 4085: /***/ function (
+    /***/ 503: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -848,23 +857,30 @@
         },
       });
       const _interop_require_default = __webpack_require__(2430);
-      const _getimgprops = __webpack_require__(9571);
-      const _imagecomponent = __webpack_require__(2016);
+      const _getimgprops = __webpack_require__(7932);
+      const _imagecomponent = __webpack_require__(8490);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(6996)
+        __webpack_require__(7240)
       );
       function getImageProps(imgProps) {
+        // This is replaced by webpack define plugin
+        const config = {
+          deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
+          imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
+          path: "/_next/image",
+          loader: "default",
+          loaderFile: "",
+          dangerouslyAllowSVG: false,
+          unoptimized: false,
+        };
+        if (config.loaderFile && typeof _imageloader.default === "undefined") {
+          throw new Error(
+            "The loader file must export a default function that returns a string.\nSee more info here: https://nextjs.org/docs/messages/invalid-images-config"
+          );
+        }
         const { props } = (0, _getimgprops.getImgProps)(imgProps, {
           defaultLoader: _imageloader.default,
-          // This is replaced by webpack define plugin
-          imgConf: {
-            deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
-            imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
-            path: "/_next/image",
-            loader: "default",
-            dangerouslyAllowSVG: false,
-            unoptimized: false,
-          },
+          imgConf: config,
         });
         // Normally we don't care about undefined props because we pass to JSX,
         // but this exported function could be used by the end user for anything
@@ -883,7 +899,7 @@
       /***/
     },
 
-    /***/ 6996: /***/ function (__unused_webpack_module, exports) {
+    /***/ 7240: /***/ function (__unused_webpack_module, exports) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -918,7 +934,7 @@
       /***/
     },
 
-    /***/ 5237: /***/ function (
+    /***/ 396: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -939,8 +955,8 @@
 
       // EXTERNAL MODULE: ./node_modules/.pnpm/react@18.2.0/node_modules/react/jsx-runtime.js
       var jsx_runtime = __webpack_require__(1527);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/image.js
-      var next_image = __webpack_require__(1577);
+      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/image.js
+      var next_image = __webpack_require__(73);
       var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // CONCATENATED MODULE: ./pages/nextjs.png
       /* harmony default export */ var nextjs = {
         src: "/_next/static/media/nextjs.cae0b805.png",
@@ -970,12 +986,12 @@
       /***/
     },
 
-    /***/ 1577: /***/ function (
+    /***/ 73: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(4085);
+      module.exports = __webpack_require__(503);
 
       /***/
     },
@@ -986,7 +1002,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [2888, 9774, 179], function () {
-      return __webpack_exec__(1552);
+      return __webpack_exec__(4070);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>8299-HASH.js</strong></summary>

```diff
@@ -1,8 +1,8 @@
 "use strict";
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
-  [8299],
+  [2764],
   {
-    /***/ 8299: /***/ function (module, exports, __webpack_require__) {
+    /***/ 2764: /***/ function (module, exports, __webpack_require__) {
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
         value: true,
@@ -13,25 +13,25 @@
           return Image;
         },
       });
-      const _interop_require_default = __webpack_require__(4777);
-      const _interop_require_wildcard = __webpack_require__(353);
-      const _jsxruntime = __webpack_require__(6435);
+      const _interop_require_default = __webpack_require__(9380);
+      const _interop_require_wildcard = __webpack_require__(2077);
+      const _jsxruntime = __webpack_require__(2260);
       const _react = /*#__PURE__*/ _interop_require_wildcard._(
-        __webpack_require__(8288)
+        __webpack_require__(4978)
       );
       const _reactdom = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(4364)
+        __webpack_require__(7)
       );
       const _head = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(9369)
+        __webpack_require__(5175)
       );
-      const _getimgprops = __webpack_require__(2564);
-      const _imageconfig = __webpack_require__(578);
-      const _imageconfigcontextsharedruntime = __webpack_require__(8589);
-      const _warnonce = __webpack_require__(2528);
-      const _routercontextsharedruntime = __webpack_require__(2339);
+      const _getimgprops = __webpack_require__(7253);
+      const _imageconfig = __webpack_require__(6491);
+      const _imageconfigcontextsharedruntime = __webpack_require__(9382);
+      const _warnonce = __webpack_require__(3848);
+      const _routercontextsharedruntime = __webpack_require__(7897);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(1300)
+        __webpack_require__(3366)
       );
       // This is replaced by webpack define plugin
       const configEnv = {
@@ -39,6 +39,7 @@
         imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
         path: "/_next/image",
         loader: "default",
+        loaderFile: "",
         dangerouslyAllowSVG: false,
         unoptimized: false,
       };
@@ -317,6 +318,14 @@
           }, [onLoadingComplete]);
           const [blurComplete, setBlurComplete] = (0, _react.useState)(false);
           const [showAltText, setShowAltText] = (0, _react.useState)(false);
+          if (
+            config.loaderFile &&
+            typeof _imageloader.default === "undefined"
+          ) {
+            throw new Error(
+              "The loader file must export a default function that returns a string.\nSee more info here: https://nextjs.org/docs/messages/invalid-images-config"
+            );
+          }
           const { props: imgAttributes, meta: imgMeta } = (0,
           _getimgprops.getImgProps)(props, {
             defaultLoader: _imageloader.default,
@@ -363,7 +372,7 @@
       /***/
     },
 
-    /***/ 5416: /***/ function (
+    /***/ 7121: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -377,9 +386,9 @@
           return AmpStateContext;
         },
       });
-      const _interop_require_default = __webpack_require__(4777);
+      const _interop_require_default = __webpack_require__(9380);
       const _react = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(8288)
+        __webpack_require__(4978)
       );
       const AmpStateContext = _react.default.createContext({});
       if (false) {
@@ -388,7 +397,7 @@
       /***/
     },
 
-    /***/ 9392: /***/ function (__unused_webpack_module, exports) {
+    /***/ 7960: /***/ function (__unused_webpack_module, exports) {
       Object.defineProperty(exports, "__esModule", {
         value: true,
       });
@@ -410,7 +419,7 @@
       /***/
     },
 
-    /***/ 2564: /***/ function (
+    /***/ 7253: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -424,9 +433,9 @@
           return getImgProps;
         },
       });
-      const _warnonce = __webpack_require__(2528);
-      const _imageblursvg = __webpack_require__(7910);
-      const _imageconfig = __webpack_require__(578);
+      const _warnonce = __webpack_require__(3848);
+      const _imageblursvg = __webpack_require__(558);
+      const _imageconfig = __webpack_require__(6491);
       const VALID_LOADING_VALUES =
         /* unused pure expression or super */ null && [
           "lazy",
@@ -795,7 +804,7 @@
       /***/
     },
 
-    /***/ 9369: /***/ function (module, exports, __webpack_require__) {
+    /***/ 5175: /***/ function (module, exports, __webpack_require__) {
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
         value: true,
@@ -816,19 +825,19 @@
           return defaultHead;
         },
       });
-      const _interop_require_default = __webpack_require__(4777);
-      const _interop_require_wildcard = __webpack_require__(353);
-      const _jsxruntime = __webpack_require__(6435);
+      const _interop_require_default = __webpack_require__(9380);
+      const _interop_require_wildcard = __webpack_require__(2077);
+      const _jsxruntime = __webpack_require__(2260);
       const _react = /*#__PURE__*/ _interop_require_wildcard._(
-        __webpack_require__(8288)
+        __webpack_require__(4978)
       );
       const _sideeffect = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(1620)
+        __webpack_require__(5894)
       );
-      const _ampcontextsharedruntime = __webpack_require__(5416);
-      const _headmanagercontextsharedruntime = __webpack_require__(7662);
-      const _ampmode = __webpack_require__(9392);
-      const _warnonce = __webpack_require__(2528);
+      const _ampcontextsharedruntime = __webpack_require__(7121);
+      const _headmanagercontextsharedruntime = __webpack_require__(5237);
+      const _ampmode = __webpack_require__(7960);
+      const _warnonce = __webpack_require__(3848);
       function defaultHead(inAmpMode) {
         if (inAmpMode === void 0) inAmpMode = false;
         const head = [
@@ -1004,7 +1013,7 @@
       /***/
     },
 
-    /***/ 7910: /***/ function (__unused_webpack_module, exports) {
+    /***/ 558: /***/ function (__unused_webpack_module, exports) {
       /**
        * A shared function, used on both client and server, to generate a SVG blur placeholder.
        */
@@ -1058,7 +1067,7 @@
       /***/
     },
 
-    /***/ 8589: /***/ function (
+    /***/ 9382: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1072,11 +1081,11 @@
           return ImageConfigContext;
         },
       });
-      const _interop_require_default = __webpack_require__(4777);
+      const _interop_require_default = __webpack_require__(9380);
       const _react = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(8288)
+        __webpack_require__(4978)
       );
-      const _imageconfig = __webpack_require__(578);
+      const _imageconfig = __webpack_require__(6491);
       const ImageConfigContext = _react.default.createContext(
         _imageconfig.imageConfigDefault
       );
@@ -1086,7 +1095,7 @@
       /***/
     },
 
-    /***/ 578: /***/ function (__unused_webpack_module, exports) {
+    /***/ 6491: /***/ function (__unused_webpack_module, exports) {
       Object.defineProperty(exports, "__esModule", {
         value: true,
       });
@@ -1133,7 +1142,7 @@
       /***/
     },
 
-    /***/ 1300: /***/ function (__unused_webpack_module, exports) {
+    /***/ 3366: /***/ function (__unused_webpack_module, exports) {
       Object.defineProperty(exports, "__esModule", {
         value: true,
       });
@@ -1166,7 +1175,7 @@
       /***/
     },
 
-    /***/ 2339: /***/ function (
+    /***/ 7897: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1180,9 +1189,9 @@
           return RouterContext;
         },
       });
-      const _interop_require_default = __webpack_require__(4777);
+      const _interop_require_default = __webpack_require__(9380);
       const _react = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(8288)
+        __webpack_require__(4978)
       );
       const RouterContext = _react.default.createContext(null);
       if (false) {
@@ -1191,7 +1200,7 @@
       /***/
     },
 
-    /***/ 1620: /***/ function (
+    /***/ 5894: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1205,7 +1214,7 @@
           return SideEffect;
         },
       });
-      const _react = __webpack_require__(8288);
+      const _react = __webpack_require__(4978);
       const isServer = typeof window === "undefined";
       const useClientOnlyLayoutEffect = isServer
         ? () => {}
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 732940d8836e3575862cd79942f901f4a8812cc5

File: packages/next/src/build/webpack/plugins/define-env-plugin.ts [hunk 1]
```diff
@@ -110,6 +110,7 @@ function getImageConfig(
       imageSizes: config.images.imageSizes,
       path: config.images.path,
       loader: config.images.loader,
+      loaderFile: config.images.loaderFile,
```
[the remark this answers is not in the document]
Comment (ojj1123) [reply packages/next/src/build/webpack/plugins/define-env-plugin.ts:113]: > since __NEXT_IMAGE_OPTS is still being used below

what's the mean?

[the remark this answers is not in the document]
Comment (styfle) [reply packages/next/src/build/webpack/plugins/define-env-plugin.ts:113]: No its not, the import is replaced by webpack/turbopack

File: packages/next/src/shared/lib/get-img-props.ts [hunk 2]
```diff
@@ -283,6 +283,11 @@ export function getImgProps(
     config = { ...c, allSizes, deviceSizes }
   }
 
+  if (config.loaderFile && typeof defaultLoader === 'undefined') {
```
Comment (styfle) [inline packages/next/src/shared/lib/get-img-props.ts:286]:
```suggestion
  if (!isDefaultLoader) {
```

Use the existing variable on line 299 below

Comment (styfle) [reply packages/next/src/shared/lib/get-img-props.ts:286]: Actually, move this if statement into the `else` block on line 309

File: packages/next/src/build/webpack/plugins/define-env-plugin.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (ojj1123) [reply packages/next/src/build/webpack/plugins/define-env-plugin.ts:113]: Sorry for my misunderstanding. but I didn't get it.
Why didn't Next.js add `config.images.loaderFile` in `__NEXT_IMAGE_OPTS`?

> No its not, the import is replaced by webpack/turbopack

you mean that `defaultLoader` is replaced with `loaderFile` by webpack/turbopack?

File: packages/next/src/shared/lib/get-img-props.ts (hunk 2 above)
Comment (ojj1123) [reply packages/next/src/shared/lib/get-img-props.ts:286]: `isDefaultLoader` flag is just used to check whether or not the user pass loader function to `loader` props or `config.images.loaderFile`.

```ts
// get-img-props.ts

let loader: ImageLoaderWithConfig = rest.loader || defaultLoader // undefined
...
const isDefaultLoader = '__next_img_default' in loader
```

But If the loader file export a named function and the user do not pass `loader` props, the value of `loader` above is `undefined` so the error occurs like this 👉
```
TypeError: Cannot use 'in' operator to search for '__next_img_default' in undefined
```

So `defaultLoader` should be some value: `defaultLoader` or `config.images.loaderFile`

File: packages/next/src/build/webpack/plugins/define-env-plugin.ts [hunk 3]
```diff
@@ -110,7 +110,6 @@ function getImageConfig(
       imageSizes: config.images.imageSizes,
       path: config.images.path,
       loader: config.images.loader,
-      loaderFile: config.images.loaderFile,
```
Comment (ojj1123) [inline packages/next/src/build/webpack/plugins/define-env-plugin.ts]: @styfle 

I reverted it !

**Comment by ojj1123** [comment]
I added the test. Please review this PR!

**Comment by ojj1123** [comment]
@styfle
Sorry for mentioning you but I was wondering if anyone could review this PR?

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: fc1a35ed28623db8f39222050bb5a80a6502ed11

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ojj1123** [comment]
https://github.com/vercel/next.js/pull/64036/commits/82eeab493d48d62f4bd6ceefa18dc9844cb014c7

@styfle 
I fixed the test suite.

File: packages/next/src/shared/lib/get-img-props.ts [hunk 4]
```diff
@@ -285,6 +285,11 @@ export function getImgProps(
     config = { ...c, allSizes, deviceSizes }
   }
 
+  if (typeof defaultLoader === 'undefined') {
+    throw new Error(
+      'The loader file must export a default function that returns a string.\nSee more info here: https://nextjs.org/docs/messages/invalid-images-config'
```
Comment (styfle) [inline packages/next/src/shared/lib/get-img-props.ts:290]:
```suggestion
      'images.loaderFile detected but the file is missing export default.\nRead more: https://nextjs.org/docs/messages/invalid-images-config'
```

File: test/e2e/app-dir/loader-file-named-export-custom-loader-error/loader-file-named-export-custom-loader-error.test.ts [hunk 5]
```diff
@@ -0,0 +1,53 @@
+import { nextTestSetup } from 'e2e-utils'
+import { getRedboxHeader, hasRedbox } from 'next-test-utils'
+
+const errorMessage =
+  'The loader file must export a default function that returns a string.\nSee more info here: https://nextjs.org/docs/messages/invalid-images-config'
```
Comment (styfle) [inline test/e2e/app-dir/loader-file-named-export-custom-loader-error/loader-file-named-export-custom-loader-error.test.ts:5]:
```suggestion
  'images.loaderFile detected but the file is missing default export.\nRead more: https://nextjs.org/docs/messages/invalid-images-config'
```

File: packages/next/src/shared/lib/get-img-props.ts [hunk 6]
```diff
@@ -285,6 +285,11 @@ export function getImgProps(
     config = { ...c, allSizes, deviceSizes }
   }
 
+  if (typeof defaultLoader === 'undefined') {
+    throw new Error(
+      'images.loaderFile detected but the file is missing export default.\nRead more: https://nextjs.org/docs/messages/invalid-images-config'
```
Comment (styfle) [inline packages/next/src/shared/lib/get-img-props.ts:290]:
```suggestion
      'images.loaderFile detected but the file is missing default export.\nRead more: https://nextjs.org/docs/messages/invalid-images-config'
```

**Review by styfle — APPROVED** [review]
Great work, thanks! 🎉
