### PR TITLE
fix: should allow optional properties for `images` option

### LINKED ISSUE #28708: type `images?: ImageOption` on next.config.js does not allow optional properties.
### What version of Next.js are you using?

v11.1.2

### What version of Node.js are you using?

v15.8.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

On next.config.js, setting single property to `images` option  cause a TypeError.

```
Type '{ disableStaticImages: true; }' is missing the following properties
from type 'ImageConfig': deviceSizes, imageSizes, loader, path
```

スクリーンショット 2021-09-01 23 05 23

This happens because `deviceSizes`, `imageSizes`, `loader` and `path` are required in `ImageConfig`.

```ts
// https://github.com/vercel/next.js/blob/8151a7e0dc9a029a9c4261901d333f67d23f718f/packages/next/server/image-config.ts
type ImageConfig = {
    deviceSizes: number[];
    imageSizes: number[];
    loader: LoaderValue;
    path: string;
    domains?: string[];
    disableStaticImages?: boolean;
    minimumCacheTTL?: number;
};
```

### Expected Behavior

Should allow single property as written in [document](https://nextjs.org/docs/basic-features/image-optimization#disable-static-imports)

```js
module.exports = {
  images: {
    disableStaticImages: true,
  },
}
```

### To Reproduce

Paste below code into your next.config.js

```js
// @ts-check

/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  images: {
    disableStaticImages: true,
  },
};

module.exports = nextConfig;
```

### PR DESCRIPTION
**Pull request by catnose99**
## Bug
- Fixes #28708

- [x] Related issues linked using `fixes #number`

### CODE REVIEW

**Review by styfle — DISMISSED** [review]
Thanks!

**Review by ijjk — DISMISSED** [review]

File: packages/next/server/config-shared.ts [hunk 1]
```diff
@@ -81,7 +81,7 @@ export type NextConfig = { [key: string]: any } & {
   pageExtensions?: string[]
   compress?: boolean
   poweredByHeader?: boolean
-  images?: ImageConfig
+  images?: Partial<ImageConfig>
```
Comment (ijjk) [inline packages/next/server/config-shared.ts:84]: It looks like we need to update the `NextConfigComplete` type to not treat this as a partial since these values should be defined after being normalized.

**Comment by catnose99** [comment]
@ijjk @styfle 

I made some changes to `NextConfigComplete` and `ImageConfig`.

To solve type errors caused by difference in required props between `next.config.js` and `NextConfigComplete`, 
I newly defined `ImageConfigComplete`.

Feel free to close this PR if these changes are not following the project convention.
Thanks.

File: packages/next/server/config-shared.ts [hunk 2]
```diff
@@ -1,13 +1,15 @@
...
 import { Header, Redirect, Rewrite } from '../lib/load-custom-routes'
-import { ImageConfig, imageConfigDefault } from './image-config'
+import {
+  ImageConfig,
+  ImageConfigComplete,
+  imageConfigDefault,
+} from './image-config'
 
-type NoOptionals<T> = {
-  [P in keyof T]-?: T[P]
```
Comment (catnose99) [inline packages/next/server/config-shared.ts:6]: Equals to [`Required<Type>
`](https://www.typescriptlang.org/docs/handbook/utility-types.html).

File: packages/next/server/config-shared.ts [hunk 3]
```diff
@@ -1,13 +1,15 @@
...
+export interface NextConfigComplete extends Required<NextConfig> {
+  images: ImageConfigComplete
```
Comment (catnose99) [inline packages/next/server/config-shared.ts:10]: Need to override `images` type since the object have been normalized.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.5s | ⚠️ +102ms |
| buildDurationCached | 3.8s | 3.6s | -106ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ⚠️ +166 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.823 | 2.792 | -0.03 |
| / avg req/sec | 885.5 | 895.38 | +9.88 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.598 | 1.589 | -0.01 |
| /error-in-render avg req/sec | 1564.94 | 1573.61 | +8.67 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 11.8s | 12.1s | ⚠️ +315ms |
| buildDurationCached | 4.9s | 4.9s | -7ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ⚠️ +166 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.873 | 2.773 | -0.1 |
| / avg req/sec | 870.17 | 901.68 | +31.51 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.6 | 1.597 | 0 |
| /error-in-render avg req/sec | 1562.32 | 1565.13 | +2.81 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 584 B | 584 B | ✓ |
| link.html gzip | 597 B | 597 B | ✓ |
| withRouter.html gzip | 579 B | 579 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: cf3348312045c78f89085931217323c5e86318a5

File: packages/next/server/config-shared.ts [hunk 4]
```diff
@@ -1,13 +1,15 @@
...
 }
```
Comment (styfle) [inline packages/next/server/config-shared.ts:11]:
```suggestion
export type NextConfigComplete = Required<NextConfig> & {
  images: ImageConfigComplete
}
```

We should probably use `export type` instead of `export interface` here since thats what it was exporting before.

Comment (catnose99) [reply packages/next/server/config-shared.ts]: Thanks!

**Review by styfle — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13s | -563ms |
| buildDurationCached | 3.5s | 3.2s | -258ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +157 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.524 | 2.544 | ⚠️ +0.02 |
| / avg req/sec | 990.67 | 982.68 | ⚠️ -7.99 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.351 | 1.348 | 0 |
| /error-in-render avg req/sec | 1850.31 | 1854.88 | +4.57 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 553 B | 553 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.63 kB | 1.63 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.5s | ⚠️ +52ms |
| buildDurationCached | 4.4s | 4.3s | -56ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +157 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.555 | 2.689 | ⚠️ +0.13 |
| / avg req/sec | 978.57 | 929.76 | ⚠️ -48.81 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.38 | 1.406 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1811.29 | 1778.59 | ⚠️ -32.7 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 584 B | 584 B | ✓ |
| link.html gzip | 597 B | 597 B | ✓ |
| withRouter.html gzip | 577 B | 577 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: d5b717fae1084bcb203705781f7f491326e41edd

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 16.2s | 16.1s | -86ms |
| buildDurationCached | 4s | 4.2s | ⚠️ +125ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +154 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.186 | 3.291 | ⚠️ +0.1 |
| / avg req/sec | 784.68 | 759.63 | ⚠️ -25.05 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.916 | 1.905 | -0.01 |
| /error-in-render avg req/sec | 1304.55 | 1312.18 | +7.63 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 540 B | 540 B | ✓ |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.63 kB | 1.63 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 13.5s | 13.7s | ⚠️ +262ms |
| buildDurationCached | 5.4s | 5.5s | ⚠️ +63ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +154 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.234 | 3.415 | ⚠️ +0.18 |
| / avg req/sec | 773.12 | 732.14 | ⚠️ -40.98 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.87 | 2.084 | ⚠️ +0.21 |
| /error-in-render avg req/sec | 1336.95 | 1199.73 | ⚠️ -137.22 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 584 B | 584 B | ✓ |
| link.html gzip | 596 B | 596 B | ✓ |
| withRouter.html gzip | 577 B | 577 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: 7f3ddea14e2ff7d8a6336d7bfba7d4ce8465efc6

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 7f3ddea14e2ff7d8a6336d7bfba7d4ce8465efc6

**test/integration/required-server-files/test/index.test.js** 
- Required Server Files > should output required-server-files manifest correctly
- Required Server Files > should render SSR page correctly
- Required Server Files > should render dynamic SSR page correctly
- Required Server Files > should render fallback page correctly
- Required Server Files > should render SSR page correctly with x-matched-path
- Required Server Files > should render dynamic SSR page correctly with x-matched-path
- Required Server Files > should render fallback page correctly with x-matched-path and routes-matches
- Required Server Files > should return data correctly with x-matched-path
- Required Server Files > should render fallback optional catch-all route correctly with x-matched-path and routes-matches
- Required Server Files > should return data correctly with x-matched-path for optional catch-all route
- Required Server Files > should not apply trailingSlash redirect
- Required Server Files > should normalize catch-all rewrite query values correctly
- Required Server Files > should bubble error correctly for gip page
- Required Server Files > should bubble error correctly for gssp page
- Required Server Files > should bubble error correctly for gsp page
- Required Server Files > should bubble error correctly for API page
- Required Server Files > should normalize optional values correctly for SSP page
- Required Server Files > should normalize optional values correctly for SSG page
- Required Server Files > should normalize optional values correctly for SSG page with encoded slash
- Required Server Files > should normalize optional values correctly for API page
- Required Server Files > should match the index page correctly
- Required Server Files > should match the root dyanmic page correctly

<details>
<summary>Expand output</summary>

  ● Required Server Files › should output required-server-files manifest correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render SSR page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render dynamic SSR page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render fallback page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render SSR page correctly with x-matched-path

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render dynamic SSR page correctly with x-matched-path

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render fallback page correctly with x-matched-path and routes-matches

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should return data correctly with x-matched-path

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render fallback optional catch-all route correctly with x-matched-path and routes-matches

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should return data correctly with x-matched-path for optional catch-all route

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should not apply trailingSlash redirect

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize catch-all rewrite query values correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for gip page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for gssp page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for gsp page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for API page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for SSP page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for SSG page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for SSG page with encoded slash

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for API page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should match the index page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should match the root dyanmic page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 15.4s | 15.3s | -85ms |
| buildDurationCached | 4s | 3.9s | -100ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +152 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.114 | 3 | -0.11 |
| / avg req/sec | 802.8 | 833.36 | +30.56 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.891 | 1.855 | -0.04 |
| /error-in-render avg req/sec | 1321.86 | 1347.61 | +25.75 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 540 B | 540 B | ✓ |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.63 kB | 1.63 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 12.2s | 12.4s | ⚠️ +167ms |
| buildDurationCached | 5.1s | 5.1s | -28ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +152 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.147 | 3.122 | -0.02 |
| / avg req/sec | 794.5 | 800.77 | +6.27 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.935 | 1.9 | -0.04 |
| /error-in-render avg req/sec | 1291.73 | 1315.59 | +23.86 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 584 B | 584 B | ✓ |
| link.html gzip | 596 B | 596 B | ✓ |
| withRouter.html gzip | 577 B | 577 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: 745b6f53286d8cb03d139b5fa459c226f1dc507f

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 745b6f53286d8cb03d139b5fa459c226f1dc507f

**test/acceptance/ReactRefreshLogBox.dev.test.js** 
-  > logbox: can recover from a syntax error without losing state

<details>
<summary>Expand output</summary>

  ● logbox: can recover from a syntax error without losing state

    expect(received).toBe(expected) // Object.is equality

    Expected: "Count: 1"
    Received: "1"

      46 |       import { useCallback, useState } from 'react'
      47 |
    > 48 |       export default function Index() {
         |        ^
      49 |         const [count, setCount] = useState(0)
      50 |         const increment = useCallback(() => setCount(c => c + 1), [setCount])
      51 |         return (

      at Object.<anonymous> (acceptance/ReactRefreshLogBox.dev.test.js:48:8)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.6s | ⚠️ +489ms |
| buildDurationCached | 3.3s | 3.3s | -7ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ⚠️ +154 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.71 | 2.766 | ⚠️ +0.06 |
| / avg req/sec | 922.47 | 903.8 | ⚠️ -18.67 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.615 | 1.619 | 0 |
| /error-in-render avg req/sec | 1548.23 | 1543.81 | ⚠️ -4.42 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 553 B | 553 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.63 kB | 1.63 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.8s | ⚠️ +246ms |
| buildDurationCached | 4.4s | 4.8s | ⚠️ +354ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ⚠️ +154 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.79 | 2.991 | ⚠️ +0.2 |
| / avg req/sec | 895.99 | 835.87 | ⚠️ -60.12 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.618 | 1.832 | ⚠️ +0.21 |
| /error-in-render avg req/sec | 1545.02 | 1364.67 | ⚠️ -180.35 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 586 B | 586 B | ✓ |
| link.html gzip | 598 B | 598 B | ✓ |
| withRouter.html gzip | 578 B | 578 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: 0e96e442a22d486e638169dd7e68315d87144038

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 0e96e442a22d486e638169dd7e68315d87144038

**test/integration/required-server-files/test/index.test.js** 
- Required Server Files > should output required-server-files manifest correctly
- Required Server Files > should render SSR page correctly
- Required Server Files > should render dynamic SSR page correctly
- Required Server Files > should render fallback page correctly
- Required Server Files > should render SSR page correctly with x-matched-path
- Required Server Files > should render dynamic SSR page correctly with x-matched-path
- Required Server Files > should render fallback page correctly with x-matched-path and routes-matches
- Required Server Files > should return data correctly with x-matched-path
- Required Server Files > should render fallback optional catch-all route correctly with x-matched-path and routes-matches
- Required Server Files > should return data correctly with x-matched-path for optional catch-all route
- Required Server Files > should not apply trailingSlash redirect
- Required Server Files > should normalize catch-all rewrite query values correctly
- Required Server Files > should bubble error correctly for gip page
- Required Server Files > should bubble error correctly for gssp page
- Required Server Files > should bubble error correctly for gsp page
- Required Server Files > should bubble error correctly for API page
- Required Server Files > should normalize optional values correctly for SSP page
- Required Server Files > should normalize optional values correctly for SSG page
- Required Server Files > should normalize optional values correctly for SSG page with encoded slash
- Required Server Files > should normalize optional values correctly for API page
- Required Server Files > should match the index page correctly
- Required Server Files > should match the root dyanmic page correctly

<details>
<summary>Expand output</summary>

  ● Required Server Files › should output required-server-files manifest correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render SSR page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render dynamic SSR page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render fallback page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render SSR page correctly with x-matched-path

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render dynamic SSR page correctly with x-matched-path

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render fallback page correctly with x-matched-path and routes-matches

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should return data correctly with x-matched-path

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render fallback optional catch-all route correctly with x-matched-path and routes-matches

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should return data correctly with x-matched-path for optional catch-all route

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should not apply trailingSlash redirect

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize catch-all rewrite query values correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for gip page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for gssp page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for gsp page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for API page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for SSP page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for SSG page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for SSG page with encoded slash

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for API page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should match the index page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should match the root dyanmic page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 16.3s | 16.6s | ⚠️ +314ms |
| buildDurationCached | 4.1s | 4.1s | ⚠️ +55ms |
| nodeModulesSize | 48.2 MB | 48.2 MB | ⚠️ +154 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.274 | 3.375 | ⚠️ +0.1 |
| / avg req/sec | 763.48 | 740.74 | ⚠️ -22.74 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.952 | 1.983 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1281 | 1260.87 | ⚠️ -20.13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 13.1s | 13s | -54ms |
| buildDurationCached | 5.4s | 5.2s | -156ms |
| nodeModulesSize | 48.2 MB | 48.2 MB | ⚠️ +154 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.474 | 3.278 | -0.2 |
| / avg req/sec | 719.73 | 762.69 | +42.96 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.038 | 1.964 | -0.07 |
| /error-in-render avg req/sec | 1226.82 | 1273.17 | +46.35 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 597 B | 597 B | ✓ |
| withRouter.html gzip | 578 B | 578 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: ba2352b13539081724fc3ae0bd72189c66318664

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 11.9s | 11.9s | ⚠️ +22ms |
| buildDurationCached | 3.1s | 3s | -92ms |
| nodeModulesSize | 48.2 MB | 48.2 MB | ⚠️ +154 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.348 | 2.358 | ⚠️ +0.01 |
| / avg req/sec | 1064.9 | 1060.32 | ⚠️ -4.58 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.255 | 1.283 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1992.16 | 1949.21 | ⚠️ -42.95 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| buildDuration | 9.6s | 9.6s | -12ms |
| buildDurationCached | 4s | 4s | -38ms |
| nodeModulesSize | 48.2 MB | 48.2 MB | ⚠️ +154 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.353 | 2.342 | -0.01 |
| / avg req/sec | 1062.58 | 1067.6 | +5.02 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.28 | 1.254 | -0.03 |
| /error-in-render avg req/sec | 1952.8 | 1993.21 | +40.41 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | catnose99/next.js fix-images-type | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 597 B | 597 B | ✓ |
| withRouter.html gzip | 578 B | 578 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: 399e301e4b6d7ff1c150946edbc633171c147fcb
