### PR TITLE
Fix server output bundling packages module resolving

### LINKED ISSUE #57622: 14.0.0 Server Actions webpack issues
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/practical-silence-zgrvzc

### To Reproduce

1. Go to https://codesandbox.io/p/sandbox/practical-silence-zgrvzc
2. Open the /app/page.tsx file and see instructions
3. Click "Click me" button on the app to see the pop up, everything is fine.
4. Comment out the Scenario1 (happy path) and uncomment the Scenario2 block, save file and wait for app to reload
5. Click "Click me" and see error in the terminal
6. Comment out the Scenario2 and uncomment the Scenario1 block, save file and wait for app to reload
7. Click "Click me" and see new error in the terminal

### Current vs. Expected behavior

In Next 13.5.6, server actions did not have any issues with webpack.
In Next 14.0.0 is broken with webpack importing certain libraries

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.5.1
  npm: 9.8.0
  Yarn: 1.22.19
  pnpm: 8.10.0
Relevant Packages:
  next: 14.0.0
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

[v14.0.1-canary.0](https://github.com/vercel/next.js/releases/tag/v14.0.1-canary.0 only contains a docs change.

### LINKED ISSUE #58428: [Next:^14] Server Action: Unexpected identifier "(action-browser)/..."
### Link to the code that reproduces this issue

https://github.com/liquiFruit/libsql-action-test

### To Reproduce

1. Install deps and run app in dev mode.
2. Visit `http://localhost:3000/`.
3. Click the "create user" button.
4. Take note of the error that appears.

### Current vs. Expected behavior

Currently, this runtime error prevents calling the `tryCreateUser` action. 

The expected behavior would be for the action to be successfully called -- as it does when downgrading to `next: ^13` and enabling experimental server actions. This was the functionality when I had the `"use server"` in `@/server/db/index.ts` and had not created `@/server/actions.ts`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
OS: Windows 11, 64bit.
Next.js version: 14.0.3-canary.7
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I tested the same code on nextjs version `^13` and all works as expected.

### PR DESCRIPTION
**Pull request by huozhi**
We removed the forced resolving cjs package for app router when releasing v14 in #56960, which will resolve the ESM if possible since we're trying to bundle all packages for app router in RSC and Server Actions. There're cases that packages can't be bundled that we're providing a `serverComponentsExternalPackages` experimental flag which is widly used for packages that can't be bundled, they're remained as external.

In webpack it will output the module based on if they're cjs or esm external, where cjs external pkg output will be `require('external-pkg')` and esm one will be `import('external-pkg')`. This could change `external-pkg` to an async module if we resolve them as ESM, since dynamic `import()` will return a Promise. This causes few apps especially the ones with datdabase usage couldn't properly imports the APIs from externaled packages.

### Solution

We'll not enable prefer esm resolving strategy for `serverComponentsExternalPackages` while resolving externals. 

Fixes #57622 
Fixes #58428

In turbopack we don't have this problem in dev mode, so I skipped it for now as turbopack also uses different strategy to bundle.

Closes NEXT-1822

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/not-prefer-esm-for-external-pkg | Change |
| - | - | - | - |
| buildDuration | 10.7s | 10.8s | N/A |
| buildDurationCached | 6s | 6.1s | ⚠️ +124ms |
| nodeModulesSize | 199 MB | 199 MB | ⚠️ +5.03 kB |
| nextStartRea..uration (ms) | 423ms | 429ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/not-prefer-esm-for-external-pkg | Change |
| - | - | - | - |
| 170-HASH.js gzip | 26.7 kB | 26.7 kB | N/A |
| 199.HASH.js gzip | 181 B | 185 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 240 B | 243 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/not-prefer-esm-for-external-pkg | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/not-prefer-esm-for-external-pkg | Change |
| - | - | - | - |
| _app-HASH.js gzip | 195 B | 194 B | N/A |
| _error-HASH.js gzip | 183 B | 182 B | N/A |
| amp-HASH.js gzip | 501 B | 501 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 255 B | ✓ |
| head-HASH.js gzip | 349 B | 350 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.6 kB | 2.6 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 309 B | N/A |
| script-HASH.js gzip | 384 B | 384 B | ✓ |
| withRouter-HASH.js gzip | 307 B | 306 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/not-prefer-esm-for-external-pkg | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 483 B | ✓ |
| Overall change | 483 B | 483 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/not-prefer-esm-for-external-pkg | Change |
| - | - | - | - |
| index.html gzip | 527 B | 530 B | N/A |
| link.html gzip | 541 B | 542 B | N/A |
| withRouter.html gzip | 523 B | 525 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/not-prefer-esm-for-external-pkg | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.5 kB | 93.5 kB | N/A |
| page.js gzip | 146 kB | 146 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/not-prefer-esm-for-external-pkg | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 623 B | 625 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/not-prefer-esm-for-external-pkg | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 93.9 kB | 93.9 kB | ✓ |
| app-page-tur..prod.js gzip | 94.7 kB | 94.7 kB | ✓ |
| app-page-tur..prod.js gzip | 89.2 kB | 89.2 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.6 kB | 88.6 kB | ✓ |
| app-route-ex...dev.js gzip | 24 kB | 24 kB | ✓ |
| app-route-ex..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| app-route.ru...dev.js gzip | 23.4 kB | 23.4 kB | ✓ |
| app-route.ru..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.6 kB | 22.6 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| Overall change | 930 kB | 930 kB | ✓ |

</details>

</details>
Commit: 423e5a7064c024d3f770bec25275d268134afbf6

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 423e5a7064c024d3f770bec25275d268134afbf6

`pnpm test-dev test/e2e/app-dir/app-external/app-external.test.ts` 
- app dir - external dependency > should not prefer to resolve esm over cjs for bundling optout packages

<details>
<summary>Expand output</summary>

  ● app dir - external dependency › should not prefer to resolve esm over cjs for bundling optout packages

    TIMED OUT: /success/

    undefined

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "dual-pkg-optout:cjs"
    Received: "dual-pkg-optout:mjs"

      626 |
      627 |   if (hardError) {
    > 628 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      629 |   }
      630 |   return false
      631 | }

      at check (lib/next-test-utils.ts:628:11)
      at Object.<anonymous> (e2e/app-dir/app-external/app-external.test.ts:259:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: packages/next/src/build/handle-externals.ts [hunk 1]
```diff
@@ -62,12 +63,22 @@ export async function resolveExternal(
...
-    esmExternals && isEsmRequested ? [true, false] : [false]
+  const preferEsmOptions =
+    esmExternals &&
+    isEsmRequested &&
+    // For package that marked as externals that should be not bundled,
+    // we don't resolve them as ESM since it could be resolved as async module,
+    // such as `import(external package)` in the bundle, valued as a `Promise`.
+    !isPackageExcludedFromBundling
+      ? [true, false]
+      : [false]
```
Comment (shuding) [inline packages/next/src/build/handle-externals.ts:81]: Nit: if we inline `!isPackageExcludedFromBundling` directly as `!optOutBundlingPackages.some((optOut) => request.startsWith(optOut))` below, it will be faster as the `.some` is linear and doesn't have to run if `esmExternals && isEsmRequested &&` is already `false`.

**Review by shuding — APPROVED** [review]
