### PR TITLE
fix: do not add suffix for sitemap under group routes

### LINKED ISSUE #72787: Nested sitemaps seem to 404 in Next.js 15
### Link to the code that reproduces this issue

https://github.com/JamesSingleton/sitemap-issue

### To Reproduce

1. Start the app running `pnpm dev`
2. Go to `http://localhost:3000/resources/sitemap.xml/0` since in dev mode that's where it is supposed to live according to the [docs](https://nextjs.org/docs/app/api-reference/functions/generate-sitemaps)
3. You will get a 404
4. You can also do `pnpm build && pnpm start` and then go to `http://localhost:3000/resources/sitemap/0.xml` and you will get a 404 as well.

Screenshot 2024-11-13 at 19 10 24

### Current vs. Expected behavior

In Next 14 this worked just fine. However, after upgrading to Next 15 this no longer works.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 20.15.0
  npm: 10.7.0
  Yarn: 1.22.22
  pnpm: 9.13.0
Relevant Packages:
  next: 15.0.4-canary.11 // Latest available version is detected (15.0.4-canary.11).
  eslint-config-next: 15.0.3
  react: 19.0.0-rc-66855b96-20241106
  react-dom: 19.0.0-rc-66855b96-20241106
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), Vercel (Deployed)

### Additional context

If you go to `localhost:3000/sitemap.xml` it will load that sitemap just fine
Screenshot 2024-11-13 at 19 14 33

I even tried moving the `sitemap.ts` to just `app/resources/sitemap.ts` and going to `http://localhost:3000/resources/sitemap.xml/0` still does not load anything

### PR DESCRIPTION
**Pull request by huozhi**
### What

Do not add hash suffix for the metadata `/sitemap.xml` routes under the routes group.

### Why

We previously added the suffix to all the metadata routes where they're under the routes group. This was intentional for cases like having both `/(group)/og image` and `/og image` so they can be different og images inlined into different group routes. But for sitemap it's different since sitemap usually wasn't intended to have duplicates. Each sitemap contains all the urls of sub routes, we don't have the case `/(group)/sitemap.[ext]` and `/sitemap.[ext]` exist at the same time. So we always normalize the urls for sitemap and do not append hash suffix. 

This was already the case in v14, it's regressed in #66477 

Fixes #72787
Closes NEXT-3909

### CODE REVIEW

**Comment by huozhi** [comment]
* **#73570** <a href="https://app.graphite.dev/github/pr/vercel/next.js/73570?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/vercel/next.js/73570?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 167674aff3d99f8c18ecc64f3590a4153d742e42

`pnpm test-dev test/e2e/app-dir/sitemap-group/sitemap-group.test.ts`
- sitemap-group > should not add suffix to sitemap under group routes

<details>
<summary>Expand output</summary>

  ● sitemap-group › should not add suffix to sitemap under group routes

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `sitemap-group should not add suffix to sitemap under group routes 1`

    - Snapshot  - 1
    + Received  + 1

      "<?xml version="1.0" encoding="UTF-8"?>
      <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      <url>
      <loc>https://www.vercel.com</loc>
    - <lastmod>2024-12-05T23:45:13.405Z</lastmod>
    + <lastmod>2024-12-05T23:50:52.190Z</lastmod>
      <changefreq>monthly</changefreq>
      </url>
      </urlset>
      "

      11 |     expect(res.headers.get('content-type')).toBe('application/xml')
      12 |     const text = await res.text()
    > 13 |     expect(text).toMatchInlineSnapshot(`
         |                  ^
      14 |       "<?xml version="1.0" encoding="UTF-8"?>
      15 |       <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      16 |       <url>

      at Object.toMatchInlineSnapshot (e2e/app-dir/sitemap-group/sitemap-group.test.ts:13:18)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 12-05-fix_always_normalize_sitemap_urls | Change |
| - | - | - | - |
| buildDuration | 37.4s | 35.5s | N/A |
| buildDurationCached | 34.2s | 30s | N/A |
| nodeModulesSize | 409 MB | 409 MB | ⚠️ +6.6 kB |
| nextStartRea..uration (ms) | 846ms | 843ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-05-fix_always_normalize_sitemap_urls | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 49.2 kB | 49.2 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.3 kB | 5.3 kB | N/A |
| bccd1874-HASH.js gzip | 53 kB | 53 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 233 B | 235 B | N/A |
| main-HASH.js gzip | 33.7 kB | 33.7 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-05-fix_always_normalize_sitemap_urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-05-fix_always_normalize_sitemap_urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 513 B | 511 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | N/A |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.44 kB | 4.43 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.75 kB | 1.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-05-fix_always_normalize_sitemap_urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 746 B | 747 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-05-fix_always_normalize_sitemap_urls | Change |
| - | - | - | - |
| index.html gzip | 523 B | 524 B | N/A |
| link.html gzip | 537 B | 537 B | ✓ |
| withRouter.html gzip | 519 B | 521 B | N/A |
| Overall change | 537 B | 537 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-05-fix_always_normalize_sitemap_urls | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 200 kB | 200 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-05-fix_always_normalize_sitemap_urls | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 665 B | 664 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.1 kB | 31.1 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-05-fix_always_normalize_sitemap_urls | Change |
| - | - | - | - |
| 797-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 797.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 321 kB | 321 kB | ✓ |
| app-page-exp..prod.js gzip | 126 kB | 126 kB | ✓ |
| app-page-tur..prod.js gzip | 139 kB | 139 kB | ✓ |
| app-page-tur..prod.js gzip | 134 kB | 134 kB | ✓ |
| app-page.run...dev.js gzip | 311 kB | 311 kB | ✓ |
| app-page.run..prod.js gzip | 122 kB | 122 kB | ✓ |
| app-route-ex...dev.js gzip | 36.8 kB | 36.8 kB | ✓ |
| app-route-ex..prod.js gzip | 25 kB | 25 kB | ✓ |
| app-route-tu..prod.js gzip | 25 kB | 25 kB | ✓ |
| app-route-tu..prod.js gzip | 24.8 kB | 24.8 kB | ✓ |
| app-route.ru...dev.js gzip | 38.5 kB | 38.5 kB | ✓ |
| app-route.ru..prod.js gzip | 24.8 kB | 24.8 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.56 kB | 9.56 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.4 kB | 11.4 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.56 kB | 9.56 kB | ✓ |
| pages-turbo...prod.js gzip | 21.3 kB | 21.3 kB | ✓ |
| pages.runtim...dev.js gzip | 27 kB | 27 kB | ✓ |
| pages.runtim..prod.js gzip | 21.3 kB | 21.3 kB | ✓ |
| server.runti..prod.js gzip | 916 kB | 916 kB | ✓ |
| Overall change | 2.34 MB | 2.34 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 12-05-fix_always_normalize_sitemap_urls | Change |
| - | - | - | - |
| 0.pack gzip | 2.03 MB | 2.04 MB | ⚠️ +1.18 kB |
| index.pack gzip | 146 kB | 147 kB | ⚠️ +914 B |
| Overall change | 2.18 MB | 2.18 MB | ⚠️ +2.1 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 167674aff3d99f8c18ecc64f3590a4153d742e42

File: packages/next/src/lib/metadata/get-metadata-route.ts [hunk 1]
```diff
@@ -66,11 +85,7 @@ export function normalizeMetadataRoute(page: string) {
   } else if (page === '/manifest') {
     route += '.webmanifest'
   } else {
-    // Remove the file extension,
```
Comment (huozhi) [inline packages/next/src/lib/metadata/get-metadata-route.ts:69]: The previous comment was wrong, updated in the new places

File: packages/next/src/lib/metadata/get-metadata-route.ts [hunk 2]
```diff
@@ -11,14 +11,33 @@ import { normalizePathSep } from '../../shared/lib/page-path/normalize-path-sep'
...
+  if (page.endsWith('/sitemap')) {
+    return ''
+  }
 
-  if ((page.includes('(') && page.includes(')')) || page.includes('@')) {
-    suffix = djb2Hash(page).toString(36).slice(0, 6)
+  // Calculate the hash suffix based on the parent path
+  let suffix = ''
+  if (
+    (parentPathname.includes('(') && parentPathname.includes(')')) ||
```
Comment (ztanner) [inline packages/next/src/lib/metadata/get-metadata-route.ts:37]: This should probably be using the [`isGroupSegment`](https://github.com/vercel/next.js/blob/canary/packages/next/src/shared/lib/segment.ts#L3-L6) util

File: packages/next/src/lib/metadata/get-metadata-route.ts [hunk 3]
```diff
@@ -11,14 +11,33 @@ import { normalizePathSep } from '../../shared/lib/page-path/normalize-path-sep'
  * Give it a unique hash suffix to avoid conflicts
  *
  * e.g.
- * /app/opengraph-image.tsx -> /opengraph-image
- * /app/(post)/opengraph-image.tsx -> /opengraph-image-[0-9a-z]{6}
+ * /opengraph-image -> /opengraph-image
+ * /(post)/opengraph-image.tsx -> /opengraph-image-[0-9a-z]{6}
+ *
+ * Sitemap is an exception, it should not have a suffix.
+ * As the generated urls are for indexer and usually one sitemap contains all the urls of the sub routes.
```
Comment (ztanner) [inline packages/next/src/lib/metadata/get-metadata-route.ts:18]: I'm having a hard time following this sentence -- I think we can just clarify that the sitemap has to be accessible at a predictable URL so that crawlers can find it.

File: packages/next/src/lib/metadata/get-metadata-route.ts [hunk 4]
```diff
@@ -11,14 +11,33 @@ import { normalizePathSep } from '../../shared/lib/page-path/normalize-path-sep'
...
+ * The sitemap should be unique in each level and not have a suffix.
+ *
+ * /sitemap -> /sitemap
+ * /(post)/sitemap -> /sitemap
  */
 function getMetadataRouteSuffix(page: string) {
-  let suffix = ''
+  // Remove the last segment and get the parent pathname
+  // e.g. /parent/a/b/c -> /parent
```
Comment (ztanner) [inline packages/next/src/lib/metadata/get-metadata-route.ts:26]: wouldn't this be: 
```suggestion
  // e.g. /parent/a/b/c -> /parent/a/b
```

File: packages/next/src/lib/metadata/get-metadata-route.ts [hunk 5]
```diff
@@ -11,14 +11,33 @@ import { normalizePathSep } from '../../shared/lib/page-path/normalize-path-sep'
...
+  // e.g. /parent/opengraph-image.tsx -> /parent
+  const parentPathname = page.slice(0, -(path.basename(page).length + 1))
```
Comment (ztanner) [inline packages/next/src/lib/metadata/get-metadata-route.ts:28]: would it make more sense to use `path.dirname` here? 

```suggestion
  const parentPathname = path.dirname(page)
```

File: packages/next/src/lib/metadata/get-metadata-route.ts [hunk 6]
```diff
@@ -11,14 +11,33 @@ import { normalizePathSep } from '../../shared/lib/page-path/normalize-path-sep'
...
+    return ''
+  }
 
-  if ((page.includes('(') && page.includes(')')) || page.includes('@')) {
-    suffix = djb2Hash(page).toString(36).slice(0, 6)
+  // Calculate the hash suffix based on the parent path
+  let suffix = ''
+  if (
+    (parentPathname.includes('(') && parentPathname.includes(')')) ||
+    parentPathname.includes('@')
```
Comment (ztanner) [inline packages/next/src/lib/metadata/get-metadata-route.ts:38]: This is looking for parallel routes right? I think this should probably be `startsWith`, since it's technically possible to have a route with `@` that doesn't correspond with a parallel route. 

```suggestion
    parentPathname.startsWith('@')
```

File: packages/next/src/lib/metadata/get-metadata-route.ts (hunk 2 above)
Comment (huozhi) [reply packages/next/src/lib/metadata/get-metadata-route.ts:37]: This is bit different from `isGroupSegment` but more like `hasGroupSegment` since we're asserting on the whole pathname. `isGroupSegment` only checks if the 1st letter has `(`

File: packages/next/src/lib/metadata/get-metadata-route.ts (hunk 6 above)
Comment (huozhi) [reply packages/next/src/lib/metadata/get-metadata-route.ts:38]: This is similar as the group segment one, we check if any special char exists in the pathname

File: packages/next/src/lib/metadata/get-metadata-route.ts (hunk 3 above)
Comment (huozhi) [reply packages/next/src/lib/metadata/get-metadata-route.ts]: Updated the comments a bit

File: packages/next/src/lib/metadata/get-metadata-route.ts (hunk 6 above)
Comment (ztanner) [reply packages/next/src/lib/metadata/get-metadata-route.ts:41]: Is that correct though? It’s only considered special if it’s at the start of the dirname. It’s valid to have a directory called “foo@“ that has nothing to do with parallel routes.

**Review by ztanner — APPROVED** [review]
