### PR TITLE
Sourcemap and Breakpoint Fixes

### LINKED ISSUE #2990: Sourcemaps broken in simplest example
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

I'd expect sourcemaps of a basic module to enable breakpoint selection on all lines, except those clearly represented differently through transpilation.

## Current Behavior

A basic component is not debuggable with sourcemaps: clicking on a line to set a breakpoint does not set a breakpoint at that line.

## Steps to Reproduce (for bugs)

1. Example: https://github.com/tmcw/next-sourcemap-breakage-example

Single page with the source:

```js
import {Component} from "react";
export default class Button extends Component {
  render() {
    function foo() {
      console.log(1);
    }
    return <button onClick={foo}>hi</button>
  }
};
```

Setting a breakpoint on the line

```js
      console.log(1);
```

Is not possible:

next-bug

## Context

This makes debugging applications quite difficult.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    3.2.2     |
| node    |      8.4.0   |
| OS      |    macOS 10.12.6     |
| browser |      Google Chrome 61.0.3163.100   |

### PR DESCRIPTION
**Pull request by kpdecker**
Fixes source maps so they work properly when run in concat chunks, pages, or dynamic chunks.
Updates files names in dev mode to be constant so breakpoints will persist across page refreshes.

Fixes #2990

### CODE REVIEW

File: server/render.js [hunk 1]
```diff
@@ -93,11 +93,9 @@ async function doRender (req, res, pathname, query, {
...
 
   const docProps = await loadGetInitialProps(Document, { ...ctx, renderPage })
-  // While developing, we should not cache any assets.
-  // So, we use a different buildId for each page load.
-  // With that we can ensure, we have unique URL for assets per every page load.
-  // So, it'll prevent issues like this: https://git.io/vHLtb
-  const devBuildId = Date.now()
+  // Hard coding build id to development to allow for breakpoints to be set across
+  // page reloads.
+  const devBuildId = 'development'
```
Comment (frol) [inline server/render.js]: Won't this bring the mentioned issue #2014 back?

**Comment by kpdecker** [comment]
The disable cache feature in dev tools is on by default. Also cache
management in dev mode is something devs should be aware of. It was one of
the first things I learned back in the “old days” :)

**Comment by kpdecker** [comment]
But headers also provide better fixes that allow both to live together.

**Comment by kpdecker** [comment]
@frol pulled in the explicit no-cache headers from #2680 to help avoid any issues if not using dev tools, etc.

**Review by timneutkens — APPROVED** [review]
This is great @kpdecker, just tried and seems to work pretty well. One thing I noticed is that hot updates that contain errors (throw etc) don't get sourcemaps client side. Example:

```jsx
export default class extends React.Component {
    render() {
        if(typeof window !== 'undefined') {
            throw new Error('Error')                   
        }
        return null
    }
}
```

screen shot 2017-10-18 at 21 53 16

**Comment by timneutkens** [comment]
Had to revert the PR:
https://github.com/zeit/next.js/issues/3134
https://github.com/zeit/next.js/issues/3135

**Comment by kpdecker** [comment]
I can reproduce #3134. Appears to be timing issue between the combine assets plugin and the uglify plugin. Investigating fix there.

I have not been able to reproduce #3135, but have subscribed and will note if the reporter provides more information.

**Comment by timneutkens** [comment]
Thanks @kpdecker ❤️
