### PR TITLE
Fix draft mode invariant

### LINKED ISSUE #61377: Enabling draft mode causes "Invariant: expected pageData to be a string, got undefined"
### Link to the code that reproduces this issue

https://github.com/benmerckx/next-debug
Live: https://next-debug-blush.vercel.app/

### To Reproduce

1. Host it on Vercel
2. Click the button

### Current vs. Expected behavior

When hosted on Vercel enabling draft mode and then requesting a previously static page dynamically via RSC payload (in this example by `router.refresh`) results in a 500 error response with the following error shown in the logs:

````Error: Invariant: expected pageData to be a string, got undefined````

<details>
  <summary>Stack trace</summary>

````
Error: Invariant: expected pageData to be a string, got undefined
    at r3.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:3521)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async r3.renderPageComponent (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:4780)
    at async r3.renderToResponseImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:5363)
    at async r3.pipeImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:17297)
    at async r3.handleCatchallRenderRequest (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:36510)
    at async r3.runImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:17030)
    at async r3.handleRequestImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:16123)
    at async Server.<anonymous> (/var/task/___next_launcher.cjs:25:5)
    at async Server.<anonymous> (/opt/node-bridge/bridge-server-YN63DHRI.js:1:8857)
````

</details>

<details>
  <summary>HTTP request (some headers stripped)</summary>

````http
GET https://next-debug-blush.vercel.app/?_rsc=1xuj0
Cache-Control: no-cache
Cookie: __prerender_bypass=xxx
Next-Router-State-Tree: %5B%22%22%2C%7B%22children%22%3A%5B%22__PAGE__%22%2C%7B%7D%5D%7D%2Cnull%2C%22refetch%22%5D
Next-Url: /
Pragma: no-cache
Rsc: 1

HTTP/1.1 500 Internal Server Error
Cache-Control: public, max-age=0, must-revalidate
Content-Disposition: inline; filename="500"
Content-Length: 2130
Content-Type: text/html; charset=utf-8
Server: Vercel
Vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url
X-Matched-Path: /500
X-Vercel-Cache: HIT
X-Vercel-Id: cdg1::7csb7-1706614439461-d4fd6a4ceb4c
````

</details>

<details>
  <summary>Minimal reproduction</summary>

````tsx
import {Toggles} from './toggles'
import {draftMode} from 'next/headers'

export default async function SomeRSC() {
  const {isEnabled} = draftMode()
  return <Toggles isEnabled={isEnabled} />
}

// toggles.jsx

'use client'

import {useRouter} from 'next/navigation'
import {setDraftMode} from './actions'

export function Toggles({isEnabled}) {
  const router = useRouter()
  return (
    <div>
      <p>
        Draft mode is {isEnabled ? 'enabled' : 'disabled'}
      </p>
      <button onClick={async () => {
        await setDraftMode(!isEnabled)
        router.refresh()
      }}>Enable draft Mode</button>
    </div>
  );
}

// actions.js

'use server'

import {draftMode} from 'next/headers'

export async function setDraftMode(isEnabled) {
  if (isEnabled) draftMode().enable()
  else draftMode().disable()
}
````

</details>

This points to a possible issue with a cached version being expected:

https://github.com/vercel/next.js/blob/b8a7efcf1361da29994247f7d2dd6b58912b6a9e/packages/next/src/server/base-server.ts#L2836-L2840

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.17.0
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.21 // Latest available version is detected (14.1.1-canary.21).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
### What?

In today's implementation, requests that don't end in `.rsc` are getting the data request query. We need to remove this toggle to prevent them from 500'ing.

### Why?

The invariant triggered was:

https://github.com/vercel/next.js/blob/212553958c671ea1f71d96fbc97ea4b9e5019bf3/packages/next/src/server/base-server.ts#L2838-L2842

Crawling up the code, the conditional:

https://github.com/vercel/next.js/blob/212553958c671ea1f71d96fbc97ea4b9e5019bf3/packages/next/src/server/base-server.ts#L2815 

must be `true`.

The variable `isDataReq` is set here:

https://github.com/vercel/next.js/blob/212553958c671ea1f71d96fbc97ea4b9e5019bf3/packages/next/src/server/base-server.ts#L1833-L1839

This conditional expression is a bit complex, but it simplifies down to: 
- `isDataReq` is `true` when (TODO)
- `isDataReq` is `false` when (TODO)

### How?

Closes NEXT-2341
Fixes #61377

Tested manually by:
- Building and packaging this branch locally
- Deploying tarball and then depending on it as the Next.js version for an example app similar to the one reported by #61377 
- Inspecting console for 500 errors.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: a009b26b611e7ac29918923fef17ff0afb9dc069

`pnpm test-start test/production/standalone-mode/response-cache/index.test.ts`
- minimal-mode-response-cache > app router revalidate should work with previous response cache dynamic
- minimal-mode-response-cache > app router revalidate should work with previous response cache

<details>
<summary>Expand output</summary>

  ● minimal-mode-response-cache › app router revalidate should work with previous response cache dynamic

    expect(received).not.toContain(expected) // indexOf

    Expected substring: not "<html"
    Received string:        "<!DOCTYPE html><html><head><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/><link rel=\"preload\" as=\"script\" fetchPriority=\"low\" href=\"/_next/static/chunks/webpack-d847bab83eed1cbf.js\"/><script src=\"/_next/static/chunks/1dfdc540-d7f5ead044991419.js\" async=\"\"></script><script src=\"/_next/static/chunks/197-9444edac4b1bf320.js\" async=\"\"></script><script src=\"/_next/static/chunks/main-app-b6540faea8b3ff00.js\" async=\"\"></script><script src=\"/_next/static/chunks/polyfills-78c92fac7aa8fdd8.js\" noModule=\"\"></script></head><body><p>/app-blog</p><p>slug [&quot;compare&quot;]</p><p>Date: 1708038709186</p><script src=\"/_next/static/chunks/webpack-d847bab83eed1cbf.js\" async=\"\"></script><script>(self.__next_f=self.__next_f||[]).push([0]);self.__next_f.push([2,null])</script><script>self.__next_f.push([1,\"1:I[57,[],\\\"\\\"]\\n3:I[1002,[],\\\"\\\"]\\n5:I[5589,[],\\\"\\\"]\\n7:I[2805,[],\\\"\\\"]\\n4:[\\\"slug\\\",\\\"compare\\\",\\\"c\\\"]\\n8:[]\\n\"])</script><script>self.__next_f.push([1,\"0:[null,[\\\"$\\\",\\\"$L1\\\",null,{\\\"buildId\\\":\\\"bRnYfVGzg-ETvdKCPWewC\\\",\\\"assetPrefix\\\":\\\"\\\",\\\"initialCanonicalUrl\\\":\\\"/app-blog/compare\\\",\\\"initialTree\\\":[\\\"\\\",{\\\"children\\\":[\\\"app-blog\\\",{\\\"children\\\":[[\\\"slug\\\",\\\"compare\\\",\\\"c\\\"],{\\\"children\\\":[\\\"__PAGE__\\\",{}]}]}]},\\\"$undefined\\\",\\\"$undefined\\\",true],\\\"initialSeedData\\\":[\\\"\\\",{\\\"children\\\":[\\\"app-blog\\\",{\\\"children\\\":[[\\\"slug\\\",\\\"compare\\\",\\\"c\\\"],{\\\"children\\\":[\\\"__PAGE__\\\",{},[[\\\"$L2\\\",[[\\\"$\\\",\\\"p\\\",null,{\\\"children\\\":\\\"/app-blog\\\"}],[\\\"$\\\",\\\"p\\\",null,{\\\"children\\\":[\\\"slug \\\",\\\"[\\\\\\\"compare\\\\\\\"]\\\"]}],[\\\"$\\\",\\\"p\\\",null,{\\\"children\\\":[\\\"Date: \\\",1708038709186]}]]],null]]},[\\\"$\\\",\\\"$L3\\\",null,{\\\"parallelRouterKey\\\":\\\"children\\\",\\\"segmentPath\\\":[\\\"children\\\",\\\"app-blog\\\",\\\"children\\\",\\\"$4\\\",\\\"children\\\"],\\\"loading\\\":\\\"$undefined\\\",\\\"loadingStyles\\\":\\\"$undefined\\\",\\\"loadingScripts\\\":\\\"$undefined\\\",\\\"hasLoading\\\":false,\\\"error\\\":\\\"$undefined\\\",\\\"errorStyles\\\":\\\"$undefined\\\",\\\"errorScripts\\\":\\\"$undefined\\\",\\\"template\\\":[\\\"$\\\",\\\"$L5\\\",null,{}],\\\"templateStyles\\\":\\\"$undefined\\\",\\\"templateScripts\\\":\\\"$undefined\\\",\\\"notFound\\\":\\\"$undefined\\\",\\\"notFoundStyles\\\":\\\"$undefined\\\",\\\"styles\\\":null}]]},[\\\"$\\\",\\\"$L3\\\",null,{\\\"parallelRouterKey\\\":\\\"children\\\",\\\"segmentPath\\\":[\\\"children\\\",\\\"app-blog\\\",\\\"children\\\"],\\\"loading\\\":\\\"$undefined\\\",\\\"loadingStyles\\\":\\\"$undefined\\\",\\\"loadingScripts\\\":\\\"$undefined\\\",\\\"hasLoading\\\":false,\\\"error\\\":\\\"$undefined\\\",\\\"errorStyles\\\":\\\"$undefined\\\",\\\"errorScripts\\\":\\\"$undefined\\\",\\\"template\\\":[\\\"$\\\",\\\"$L5\\\",null,{}],\\\"templateStyles\\\":\\\"$undefined\\\",\\\"templateScripts\\\":\\\"$undefined\\\",\\\"notFound\\\":\\\"$undefined\\\",\\\"notFoundStyles\\\":\\\"$undefined\\\",\\\"styles\\\":null}]]},[[\\\"$\\\",\\\"html\\\",null,{\\\"children\\\":[[\\\"$\\\",\\\"head\\\",null,{}],[\\\"$\\\",\\\"body\\\",null,{\\\"children\\\":[\\\"$\\\",\\\"$L3\\\",null,{\\\"parallelRouterKey\\\":\\\"children\\\",\\\"segmentPath\\\":[\\\"children\\\"],\\\"loading\\\":\\\"$undefined\\\",\\\"loadingStyles\\\":\\\"$undefined\\\",\\\"loadingScripts\\\":\\\"$undefined\\\",\\\"hasLoading\\\":false,\\\"error\\\":\\\"$undefined\\\",\\\"errorStyles\\\":\\\"$undefined\\\",\\\"errorScripts\\\":\\\"$undefined\\\",\\\"template\\\":[\\\"$\\\",\\\"$L5\\\",null,{}],\\\"templateStyles\\\":\\\"$undefined\\\",\\\"templateScripts\\\":\\\"$undefined\\\",\\\"notFound\\\":[[\\\"$\\\",\\\"title\\\",null,{\\\"children\\\":\\\"404: This page could not be found.\\\"}],[\\\"$\\\",\\\"div\\\",null,{\\\"style\\\":{\\\"fontFamily\\\":\\\"system-ui,\\\\\\\"Segoe UI\\\\\\\",Roboto,Helvetica,Arial,sans-serif,\\\\\\\"Apple Color Emoji\\\\\\\",\\\\\\\"Segoe UI Emoji\\\\\\\"\\\",\\\"height\\\":\\\"100vh\\\",\\\"textAlign\\\":\\\"center\\\",\\\"display\\\":\\\"flex\\\",\\\"flexDirection\\\":\\\"column\\\",\\\"alignItems\\\":\\\"center\\\",\\\"justifyContent\\\":\\\"center\\\"},\\\"children\\\":[\\\"$\\\",\\\"div\\\",null,{\\\"children\\\":[[\\\"$\\\",\\\"style\\\",null,{\\\"dangerouslySetInnerHTML\\\":{\\\"__html\\\":\\\"body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}\\\"}}],[\\\"$\\\",\\\"h1\\\",null,{\\\"className\\\":\\\"next-error-h1\\\",\\\"style\\\":{\\\"display\\\":\\\"inline-block\\\",\\\"margin\\\":\\\"0 20px 0 0\\\",\\\"padding\\\":\\\"0 23px 0 0\\\",\\\"fontSize\\\":24,\\\"fontWeight\\\":500,\\\"verticalAlign\\\":\\\"top\\\",\\\"lineHeight\\\":\\\"49px\\\"},\\\"children\\\":\\\"404\\\"}],[\\\"$\\\",\\\"div\\\",null,{\\\"style\\\":{\\\"display\\\":\\\"inline-block\\\"},\\\"children\\\":[\\\"$\\\",\\\"h2\\\",null,{\\\"style\\\":{\\\"fontSize\\\":14,\\\"fontWeight\\\":400,\\\"lineHeight\\\":\\\"49px\\\",\\\"margin\\\":0},\\\"children\\\":\\\"This page could not be found.\\\"}]}]]}]}]],\\\"notFoundStyles\\\":[],\\\"styles\\\":null}]}]]}],null]],\\\"couldBeIntercepted\\\":false,\\\"initialHead\\\":[false,\\\"$L6\\\"],\\\"globalErrorComponent\\\":\\\"$7\\\",\\\"missingSlots\\\":\\\"$W8\\\"}]]\\n\"])</script><script>self.__next_f.push([1,\"6:[[\\\"$\\\",\\\"meta\\\",\\\"0\\\",{\\\"name\\\":\\\"viewport\\\",\\\"content\\\":\\\"width=device-width, initial-scale=1\\\"}],[\\\"$\\\",\\\"meta\\\",\\\"1\\\",{\\\"charSet\\\":\\\"utf-8\\\"}]]\\n2:null\\n\"])</script></body></html>"

      106 |     )
      107 |     const content1 = await res1.text()
    > 108 |     expect(content1).not.toContain('<html')
          |                          ^
      109 |     expect(content1).toContain('app-blog')
      110 |     expect(res1.headers.get('content-type')).toContain('text/x-component')
      111 |

      at Object.toContain (production/standalone-mode/response-cache/index.test.ts:108:26)

  ● minimal-mode-response-cache › app router revalidate should work with previous response cache

    expect(received).toContain(expected) // indexOf

    Expected substring: "text/x-component"
    Received string:    "text/html; charset=utf-8"

      131 |     })
      132 |     const content1 = await res1.text()
    > 133 |     expect(res1.headers.get('content-type')).toContain('text/x-component')
          |                                              ^
      134 |     expect(content1).not.toContain('<html')
      135 |     expect(content1).toContain('app-another')
      136 |

      at Object.toContain (production/standalone-mode/response-cache/index.test.ts:133:46)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ijjk — APPROVED** [review]

File: packages/next/src/server/base-server.ts [hunk 1]
```diff
@@ -2831,7 +2831,11 @@ export default abstract class Server<ServerOptions extends Options = Options> {
         res.setHeader(NEXT_DID_POSTPONE_HEADER, '1')
       }
 
-      if (isDataReq) {
+      // we don't go through this block when preview mode is true
+      // as preview mode is a dynamic request (bypasses cache) and doesn't data
```
Comment (ztanner) [inline packages/next/src/server/base-server.ts:2835]:
```suggestion
      // as preview mode is a dynamic request (bypasses cache) and doesn't
```

**Review by ztanner — APPROVED** [review]
