### PR TITLE
Fix blurred image position when using objectPosition

### LINKED ISSUE #26309: Blurred image not positioned correctly when using object-position
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.13.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Blurred images are not respecting the objectPosition property in Image component

Full image: [Example Image](https://i.schoen.world/cVAqU.png)

**What I see:** 

### Expected Behavior

The blurred placeholder should have the save position as the the later loaded full image.

**What I expect:**

An easy fix for this would be to mirror the `object-position` value to the `background-position` value while loading.

### To Reproduce

Setup:

```jsx
import Image from 'next/image'

import exampleImg from '../data/example.png'

const Page = () => (
  <Image
    src={exampleImg}
    width={1024}
    height={700}
    layout="responsive"
    objectFit="cover"
    objectPosition="center"
    placeholder="blur"
  />
)

export default Page
```

Deployed example: [schoenwaldnils.vercel.app/objectPositionIssue](https://schoen-world-8793xnvzh-schoenwaldnils.vercel.app/objectPositionIssue)

### PR DESCRIPTION
**Pull request by schoenwaldnils**
## Bug

fixes #26309

## Documentation / Examples

see #26309

- [ ] Make sure the linting passes

### CODE REVIEW

**Review by styfle — DISMISSED** [review]
Looks great, just needs a test 👍

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| buildDuration | 13.1s | 13s | -51ms |
| buildDurationCached | 3.2s | 3.2s | ⚠️ +10ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.302 | 2.321 | ⚠️ +0.02 |
| / avg req/sec | 1085.93 | 1077.24 | ⚠️ -8.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.276 | 1.313 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1958.76 | 1903.47 | ⚠️ -55.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 810 B | 810 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 534 B | 534 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| buildDuration | 14.7s | 14.5s | -240ms |
| buildDurationCached | 4.2s | 4.2s | -6ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 810 B | 810 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.8s | ⚠️ +232ms |
| buildDurationCached | 4.6s | 4.5s | -141ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.354 | 2.369 | ⚠️ +0.02 |
| / avg req/sec | 1062 | 1055.11 | ⚠️ -6.89 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.305 | 1.305 | ✓ |
| /error-in-render avg req/sec | 1916.27 | 1915.55 | ⚠️ -0.72 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 757 B | 757 B | ✓ |
| Overall change | 63.9 kB | 63.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.28 kB | 9.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| index.html gzip | 566 B | 566 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 559 B | 559 B | ✓ |
| Overall change | 1.7 kB | 1.7 kB | ✓ |

</details>

</details>
Commit: 7266cd4ccb41765abe74fcf017c4b55f1d4cf7c5

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 7266cd4ccb41765abe74fcf017c4b55f1d4cf7c5

**test/integration/image-component/default/test/static.test.js** 
- Static Image Component Tests > Should add a blurry placeholder to statically imported jpg
- Static Image Component Tests > Should add a blurry placeholder to statically imported png

<details>
<summary>Expand output</summary>

  ● Static Image Component Tests › Should add a blurry placeholder to statically imported jpg

    expect(received).toContain(expected) // indexOf

    Expected substring: "style=\"position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;filter:blur(20px);background-size:cover;background-image:url(&quot;data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/sBCgoKCgoKCwwMCw8QDhAPFhQTExQWIhgaGBoYIjMgJSAgJSAzLTcsKSw3LVFAODhAUV5PSk9ecWVlcY+Ij7u7+//CABEIAAgACAMBIgACEQEDEQH/xAAUAAEAAAAAAAAAAAAAAAAAAAAH/9oACAEBAAAAADX/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/9oACAECEAAAAH//xAAUAQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDEAAAAH//xAAdEAABAgcAAAAAAAAAAAAAAAATEhUAAwUUIzLS/9oACAEBAAE/AB0ZlUac43GqMYuo/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAgEBPwB//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAwEBPwB//9k=&quot;)\""
    Received string:    "<!DOCTYPE html><html><head><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills-086def5afcb77f2bdcdf.js\"></script><script src=\"/_next/static/chunks/webpack-61095c13c5984b221292.js\" defer=\"\"></script><script src=\"/_next/static/chunks/framework-de4918242e5470340566.js\" defer=\"\"></script><script src=\"/_next/static/chunks/main-39a50bd6f3670f7efa97.js\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/_app-0c8d78f1cb652f1f4d22.js\" defer=\"\"></script><script src=\"/_next/static/chunks/528-d2258d67de479983375e.js\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/static-d3414810803819812c6b.js\" defer=\"\"></script><script src=\"/_next/static/HG9NE6_AmYeX2JeR6zpUZ/_buildManifest.js\" defer=\"\"></script><script src=\"/_next/static/HG9NE6_AmYeX2JeR6zpUZ/_ssgManifest.js\" defer=\"\"></script></head><body><div id=\"__next\"><div><h1 id=\"page-header\">Static Image</h1><div style=\"overflow:hidden;box-sizing:border-box;display:inline-block;position:relative;width:400px;height:300px\"><noscript></noscript></div><div><h1 id=\"page-header\">Static Image</h1><div style=\"overflow:hidden;box-sizing:border-box;display:inline-block;position:relative;width:160px;height:394px\"><noscript></noscript></div></div><div style=\"overflow:hidden;box-sizing:border-box;display:inline-block;position:relative;width:200px;height:200px\"><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><br/><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div></div></div><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{}},\"page\":\"/static\",\"query\":{},\"buildId\":\"HG9NE6_AmYeX2JeR6zpUZ\",\"nextExport\":true,\"autoExport\":true,\"isFallback\":false,\"scriptLoader\":[]}</script></body></html>"

      38 |   })
      39 |   it('Should add a blurry placeholder to statically imported jpg', async () => {
    > 40 |     expect(html).toContain(
         |                  ^
      41 |       `style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;filter:blur(20px);background-size:cover;background-image:url(&quot;data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/sBCgoKCgoKCwwMCw8QDhAPFhQTExQWIhgaGBoYIjMgJSAgJSAzLTcsKSw3LVFAODhAUV5PSk9ecWVlcY+Ij7u7+//CABEIAAgACAMBIgACEQEDEQH/xAAUAAEAAAAAAAAAAAAAAAAAAAAH/9oACAEBAAAAADX/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/9oACAECEAAAAH//xAAUAQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDEAAAAH//xAAdEAABAgcAAAAAAAAAAAAAAAATEhUAAwUUIzLS/9oACAEBAAE/AB0ZlUac43GqMYuo/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAgEBPwB//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAwEBPwB//9k=&quot;)"`
      42 |     )
      43 |   })

      at Object.<anonymous> (integration/image-component/default/test/static.test.js:40:18)

  ● Static Image Component Tests › Should add a blurry placeholder to statically imported png

    expect(received).toContain(expected) // indexOf

    Expected substring: "style=\"position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;filter:blur(20px);background-size:cover;background-image:url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAQAAABuBnYAAAAATklEQVR42i2I0QmAMBQD869Q9K+IsxU6RkfoiA6T55VXDpJLJC9uUJIzcx+XFd2dXMbx8n+QpoeYDpgY66RaDA83jCUfVpK2pER1dcEUP+KfSBtXK+BpAAAAAElFTkSuQmCC&quot;)\""
    Received string:    "<!DOCTYPE html><html><head><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills-086def5afcb77f2bdcdf.js\"></script><script src=\"/_next/static/chunks/webpack-61095c13c5984b221292.js\" defer=\"\"></script><script src=\"/_next/static/chunks/framework-de4918242e5470340566.js\" defer=\"\"></script><script src=\"/_next/static/chunks/main-39a50bd6f3670f7efa97.js\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/_app-0c8d78f1cb652f1f4d22.js\" defer=\"\"></script><script src=\"/_next/static/chunks/528-d2258d67de479983375e.js\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/static-d3414810803819812c6b.js\" defer=\"\"></script><script src=\"/_next/static/HG9NE6_AmYeX2JeR6zpUZ/_buildManifest.js\" defer=\"\"></script><script src=\"/_next/static/HG9NE6_AmYeX2JeR6zpUZ/_ssgManifest.js\" defer=\"\"></script></head><body><div id=\"__next\"><div><h1 id=\"page-header\">Static Image</h1><div style=\"overflow:hidden;box-sizing:border-box;display:inline-block;position:relative;width:400px;height:300px\"><noscript></noscript></div><div><h1 id=\"page-header\">Static Image</h1><div style=\"overflow:hidden;box-sizing:border-box;display:inline-block;position:relative;width:160px;height:394px\"><noscript></noscript></div></div><div style=\"overflow:hidden;box-sizing:border-box;display:inline-block;position:relative;width:200px;height:200px\"><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><br/><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div><div style=\"display:inline-block;max-width:100%;overflow:hidden;position:relative;box-sizing:border-box;margin:0\"><div style=\"box-sizing:border-box;display:block;max-width:100%\"></div><noscript></noscript></div></div></div><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{}},\"page\":\"/static\",\"query\":{},\"buildId\":\"HG9NE6_AmYeX2JeR6zpUZ\",\"nextExport\":true,\"autoExport\":true,\"isFallback\":false,\"scriptLoader\":[]}</script></body></html>"

      43 |   })
      44 |   it('Should add a blurry placeholder to statically imported png', async () => {
    > 45 |     expect(html).toContain(
         |                  ^
      46 |       `style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;filter:blur(20px);background-size:cover;background-image:url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAQAAABuBnYAAAAATklEQVR42i2I0QmAMBQD869Q9K+IsxU6RkfoiA6T55VXDpJLJC9uUJIzcx+XFd2dXMbx8n+QpoeYDpgY66RaDA83jCUfVpK2pER1dcEUP+KfSBtXK+BpAAAAAElFTkSuQmCC&quot;)"`
      47 |     )
      48 |   })

      at Object.<anonymous> (integration/image-component/default/test/static.test.js:45:18)

</details>

**Comment by schoenwaldnils** [comment]
I have a question regarding the blurring. 
the `blurDataURL` should be a small image (approximately 10-15px wide) and data encoded, right?
Does the blurring of this small image happens afterwards in the Image component?

If yes, why is the provided `blurDataURL` in the test an encoded svg with a blur filter in it? 🤔
[test/integration/image-component/default/pages/blurry-placeholder.js#L15](https://github.com/vercel/next.js/blob/canary/test/integration/image-component/default/pages/blurry-placeholder.js#L15)

**Comment by schoenwaldnils** [comment]
Not sure why the test are still failing 🤔
Also can't test locally because yarn and npm install are not running 🤷‍♂️

File: test/integration/image-component/default/components/TallImage.js [hunk 1]
```diff
@@ -1,20 +0,0 @@
...
-        id="basic-static"
-        src={testTall}
-        layout="fixed"
-        placeholder="blur"
-      />
-    </div>
-  )
-}
-
-export default Page
```
Comment (styfle) [inline test/integration/image-component/default/components/TallImage.js:20]: Why was this test deleted?

**Comment by styfle** [comment]
@schoenwaldnils You might need to use Node.js 14

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.6s | ⚠️ +149ms |
| buildDurationCached | 2.8s | 2.9s | ⚠️ +51ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.069 | 2.062 | -0.01 |
| / avg req/sec | 1208.28 | 1212.34 | +4.06 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.149 | 1.211 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 2175.42 | 2064.03 | ⚠️ -111.39 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 810 B | 810 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 534 B | 534 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.2s | -175ms |
| buildDurationCached | 3.9s | 3.9s | -27ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 810 B | 810 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ⚠️ +2 B |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | ⚠️ +2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.4s | -126ms |
| buildDurationCached | 4.2s | 4.2s | ⚠️ +17ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.099 | 2.134 | ⚠️ +0.03 |
| / avg req/sec | 1191.22 | 1171.38 | ⚠️ -19.84 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.191 | 1.227 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2099.94 | 2037 | ⚠️ -62.94 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 757 B | 757 B | ✓ |
| Overall change | 63.9 kB | 63.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.28 kB | 9.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| index.html gzip | 566 B | 566 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 559 B | 559 B | ✓ |
| Overall change | 1.7 kB | 1.7 kB | ✓ |

</details>

</details>
Commit: 7dabb20c51787a26ecfbd88cf0ad50ad14134265

File: test/integration/image-component/default/components/TallImage.js (hunk 1 above)
Comment (schoenwaldnils) [reply test/integration/image-component/default/components/TallImage.js:20]: Ah, thats why it was a seperate component 🤔 will revert

**Comment by schoenwaldnils** [comment]
> @schoenwaldnils You might need to use Node.js 14 to test locally

node 14.15.5 works. A `.nvmrc` in the project would be nice ^^

Tests of the image-component are passing locally ✅

**Review by styfle — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.8s | ⚠️ +6ms |
| buildDurationCached | 3.2s | 3.1s | -117ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.313 | 2.321 | ⚠️ +0.01 |
| / avg req/sec | 1080.91 | 1077.15 | ⚠️ -3.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.262 | 1.279 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1980.39 | 1954.19 | ⚠️ -26.2 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 810 B | 810 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.42 kB | 8.42 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| index.html gzip | 525 B | 525 B | ✓ |
| link.html gzip | 537 B | 537 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.4s | -289ms |
| buildDurationCached | 4.7s | 4.6s | -124ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.308 | 2.335 | ⚠️ +0.03 |
| / avg req/sec | 1083.19 | 1070.88 | ⚠️ -12.31 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.28 | 1.296 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1952.51 | 1928.95 | ⚠️ -23.56 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 757 B | 757 B | ✓ |
| Overall change | 63.9 kB | 63.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.26 kB | 9.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _buildManifest.js gzip | 422 B | 422 B | ✓ |
| Overall change | 422 B | 422 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| index.html gzip | 567 B | 567 B | ✓ |
| link.html gzip | 580 B | 580 B | ✓ |
| withRouter.html gzip | 561 B | 561 B | ✓ |
| Overall change | 1.71 kB | 1.71 kB | ✓ |

</details>

</details>
Commit: 7d055cef3722a70fd870a120e2069269aa4ed11e

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 7d055cef3722a70fd870a120e2069269aa4ed11e

**test/integration/size-limit/test/index.test.js** 
- Production response size > should not increase the overall response size of default build

<details>
<summary>Expand output</summary>

  ● Production response size › should not increase the overall response size of default build

    expect(received).toBeCloseTo(expected, precision)

    Expected: 286.8
    Received: 286.2998046875

    Expected precision:    0
    Expected difference: < 0.5
    Received difference:   0.5001953125000114

      86 |
      87 |     // Expected difference: < 0.5
    > 88 |     expect(delta).toBeCloseTo(286.8, 0)
         |                   ^
      89 |   })
      90 | })
      91 |

      at Object.<anonymous> (integration/size-limit/test/index.test.js:88:19)

</details>

**Review by styfle — APPROVED** [review]
I tried it out locally and it works perfectly!

Great work, thanks! 🎉

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| buildDuration | 12.9s | 13s | ⚠️ +61ms |
| buildDurationCached | 3.3s | 3.3s | ⚠️ +61ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.297 | 2.323 | ⚠️ +0.03 |
| / avg req/sec | 1088.53 | 1076.3 | ⚠️ -12.23 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.304 | 1.287 | -0.02 |
| /error-in-render avg req/sec | 1917.65 | 1942.55 | +24.9 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 810 B | 810 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.42 kB | 8.42 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| index.html gzip | 525 B | 525 B | ✓ |
| link.html gzip | 537 B | 537 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| buildDuration | 11.9s | 11.9s | -36ms |
| buildDurationCached | 4.8s | 4.7s | -82ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.39 | 2.405 | ⚠️ +0.01 |
| / avg req/sec | 1046.16 | 1039.59 | ⚠️ -6.57 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.34 | 1.299 | -0.04 |
| /error-in-render avg req/sec | 1865.54 | 1924.24 | +58.7 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 757 B | 757 B | ✓ |
| Overall change | 63.9 kB | 63.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.26 kB | 9.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| _buildManifest.js gzip | 422 B | 422 B | ✓ |
| Overall change | 422 B | 422 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | schoenwaldnils/next.js feat/fix-blur-image-position | Change |
| - | - | - | - |
| index.html gzip | 567 B | 567 B | ✓ |
| link.html gzip | 580 B | 580 B | ✓ |
| withRouter.html gzip | 561 B | 561 B | ✓ |
| Overall change | 1.71 kB | 1.71 kB | ✓ |

</details>

</details>
Commit: af602c78c2c332f0c78394fc01b978e74037609a
