### PR TITLE
Make esm default interpolation work with jest mock

### LINKED ISSUE #36794: router client file is transpiled incorrectly
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64
    Binaries:
      Node: 16.11.1
      npm: 8.0.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

n/a

### Describe the Bug

The dist/client/router.js file had this code added in version 12.1.5

```js
if (typeof exports.default === 'function' || (typeof exports.default === 'object' && exports.default !== null)) {
  Object.assign(exports.default, exports);
  module.exports = exports.default;
}
```

This essentially erases all named exports from the CJS exports object, and instead hangs them all on the default export. This breaks Jest code that's mocking the useRouter hook.

```ts
import * as routerModule from 'next/router';

// ...

jest.spyOn(routerModule, 'useRouter').mockReturnValue(({
  pathname: '/foo/bar',
  push: pushMockFn,
} as unknown) as useRouter.NextRouter);
```

now breaks, requiring instead 

```ts
import routerModule from 'next/router';
```

This fixes the test, but is wrong. useRouter is not a property on the default export (or shouldn't be) be is rather a named export in that module. 

### Expected Behavior

CJS exports should match ESM.

### To Reproduce

See above

### PR DESCRIPTION
**Pull request by Brooooooklyn**
fixes https://github.com/vercel/next.js/issues/36794

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| buildDuration | 19.5s | 19.7s | ⚠️ +267ms |
| buildDurationCached | 7.5s | 7.7s | ⚠️ +290ms |
| nodeModulesSize | 475 MB | 475 MB | ⚠️ +19.7 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 5.454 | 5.555 | ⚠️ +0.1 |
| / avg req/sec | 458.35 | 450.08 | ⚠️ -8.27 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.16 | 2.125 | -0.04 |
| /error-in-render avg req/sec | 1157.58 | 1176.62 | +19.04 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 29.2 kB | ⚠️ +430 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.9 kB | ⚠️ +430 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 308 B | 308 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.69 kB | 2.75 kB | ⚠️ +62 B |
| head-HASH.js gzip | 359 B | 359 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.7 kB | 5.78 kB | ⚠️ +82 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.64 kB | 2.74 kB | ⚠️ +96 B |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 391 B | 391 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 16.1 kB | ⚠️ +240 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 460 B | ⚠️ +1 B |
| Overall change | 459 B | 460 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 544 B | -1 B |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -8,12 +8,12 @@ self.__BUILD_MANIFEST = {
     "static\u002Fchunks\u002Fpages\u002Fcss-436fa6bb26fc4120.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-8e11b4c2953d70e9.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-ad7ec8c1d663fa93.js"
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-544bb68363445a0e.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-c1372eeb4916d32c.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-550ed853173c68fb.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-ca5e63d57db66cd2.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-c65cf55625d93512.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-1a07bcd8ed18283f.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-113a7082ae16fbcb.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -160,7 +160,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=dynamic.js.map
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1108,7 +1108,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=image.js.map
 
@@ -1319,7 +1339,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=use-intersection.js.map
```
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -408,7 +408,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=link.js.map
 
@@ -619,7 +639,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=use-intersection.js.map
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -244,7 +244,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=head-manager.js.map
 
@@ -1537,7 +1557,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=index.js.map
 
@@ -1566,7 +1606,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=next.js.map
 
@@ -1590,7 +1650,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=normalize-trailing-slash.js.map
 
@@ -1778,7 +1858,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=page-loader.js.map
 
@@ -1828,7 +1928,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=performance-relayer.js.map
 
@@ -1943,7 +2063,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=index.js.map
 
@@ -1985,7 +2125,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=request-idle-callback.js.map
 
@@ -2137,7 +2297,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=route-announcer.js.map
 
@@ -2541,7 +2721,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=route-loader.js.map
 
@@ -2864,7 +3064,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=router.js.map
 
@@ -3259,7 +3479,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=script.js.map
 
@@ -3284,7 +3524,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=refresh.js.map
 
@@ -3346,7 +3606,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=vitals.js.map
 
@@ -3399,7 +3679,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=trusted-types.js.map
 
@@ -3446,7 +3746,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=with-router.js.map
 
@@ -3777,7 +4097,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=amp.js.map
 
@@ -4082,7 +4422,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=head.js.map
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-58d7883f661d58fa.js"
+      src="/_next/static/chunks/main-71ed64602d7b3afc.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-58d7883f661d58fa.js"
+      src="/_next/static/chunks/main-71ed64602d7b3afc.js"
       defer=""
     ></script>
     <script
@@ -27,7 +27,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-ca5e63d57db66cd2.js"
+      src="/_next/static/chunks/pages/link-1a07bcd8ed18283f.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-58d7883f661d58fa.js"
+      src="/_next/static/chunks/main-71ed64602d7b3afc.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| buildDuration | 22.5s | 22.6s | ⚠️ +78ms |
| buildDurationCached | 7.5s | 7.7s | ⚠️ +246ms |
| nodeModulesSize | 475 MB | 475 MB | ⚠️ +19.7 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 5.378 | 5.401 | ⚠️ +0.02 |
| / avg req/sec | 464.89 | 462.91 | ⚠️ -1.98 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.077 | 2.074 | 0 |
| /error-in-render avg req/sec | 1203.54 | 1205.17 | +1.63 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 29.2 kB | 29.7 kB | ⚠️ +436 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 73.1 kB | 73.5 kB | ⚠️ +436 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.71 kB | 2.77 kB | ⚠️ +52 B |
| head-HASH.js gzip | 357 B | 357 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.79 kB | 5.86 kB | ⚠️ +72 B |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.76 kB | 2.85 kB | ⚠️ +91 B |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.1 kB | 16.3 kB | ⚠️ +215 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| _buildManifest.js gzip | 456 B | 455 B | -1 B |
| Overall change | 456 B | 455 B | -1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js interpolate-getter-setter | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 543 B | 544 B | ⚠️ +1 B |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -8,12 +8,12 @@ self.__BUILD_MANIFEST = {
     "static\u002Fchunks\u002Fpages\u002Fcss-436fa6bb26fc4120.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-8e11b4c2953d70e9.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-ad7ec8c1d663fa93.js"
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-544bb68363445a0e.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-c1372eeb4916d32c.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-550ed853173c68fb.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-ca5e63d57db66cd2.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-c65cf55625d93512.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-1a07bcd8ed18283f.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-113a7082ae16fbcb.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -160,7 +160,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=dynamic.js.map
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1108,7 +1108,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=image.js.map
 
@@ -1319,7 +1339,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=use-intersection.js.map
```
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -408,7 +408,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=link.js.map
 
@@ -619,7 +639,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=use-intersection.js.map
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -244,7 +244,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=head-manager.js.map
 
@@ -1537,7 +1557,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=index.js.map
 
@@ -1566,7 +1606,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=next.js.map
 
@@ -1590,7 +1650,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=normalize-trailing-slash.js.map
 
@@ -1778,7 +1858,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=page-loader.js.map
 
@@ -1828,7 +1928,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=performance-relayer.js.map
 
@@ -1943,7 +2063,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=index.js.map
 
@@ -1985,7 +2125,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=request-idle-callback.js.map
 
@@ -2137,7 +2297,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=route-announcer.js.map
 
@@ -2541,7 +2721,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=route-loader.js.map
 
@@ -2864,7 +3064,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=router.js.map
 
@@ -3259,7 +3479,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=script.js.map
 
@@ -3284,7 +3524,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=refresh.js.map
 
@@ -3346,7 +3606,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=vitals.js.map
 
@@ -3399,7 +3679,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=trusted-types.js.map
 
@@ -3446,7 +3746,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=with-router.js.map
 
@@ -3777,7 +4097,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=amp.js.map
 
@@ -4082,7 +4422,27 @@
         typeof exports.default === "function" ||
         (typeof exports.default === "object" && exports.default !== null)
       ) {
-        Object.assign(exports.default, exports);
+        for (var exp1 in exports) {
+          if (Object.prototype.hasOwnProperty.call(exports, exp1)) {
+            Object.defineProperty(exports.default, exp1, {
+              enumerable: true,
+              configurable: true,
+              get: (function(exp2) {
+                return function() {
+                  return exports[exp2];
+                };
+              })(exp1),
+              set: (function(exp) {
+                return function(newValue) {
+                  exports[exp] = newValue;
+                };
+              })(exp1)
+            });
+          }
+        }
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true
+        });
         module.exports = exports.default;
       } //# sourceMappingURL=head.js.map
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-58d7883f661d58fa.js"
+      src="/_next/static/chunks/main-71ed64602d7b3afc.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-58d7883f661d58fa.js"
+      src="/_next/static/chunks/main-71ed64602d7b3afc.js"
       defer=""
     ></script>
     <script
@@ -27,7 +27,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-ca5e63d57db66cd2.js"
+      src="/_next/static/chunks/pages/link-1a07bcd8ed18283f.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-58d7883f661d58fa.js"
+      src="/_next/static/chunks/main-71ed64602d7b3afc.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 973f12011ceb56be564f945902da31b9c795ef43

File: packages/next/taskfile-swc.js [hunk 1]
```diff
@@ -118,7 +118,25 @@ module.exports = function (task) {
...
+        })(exp),
+        set: (function (exp) {
+          return function(newValue) {
+            exports[exp] = newValue;
+          }
+        })(exp)
+      });
+    }
+  }
+  Object.defineProperty(exports.default, '__esModule', { value: true });
```
Comment (SukkaW) [inline packages/next/taskfile-swc.js:139]: IMHO:

```js
module.exports = exports = Object.assign(exports.default, exports);
```

This should be able to retain reference between `module.exports`, `exports` and `exports.default`?

**Review by ijjk — APPROVED** [review]
