### PR TITLE
Fix sendGAEvent function 

### LINKED ISSUE #61703: @nextjs/third-party/google Custom Events Don't Register When Using `sendGAEvent()`
### Link to the code that reproduces this issue

https://github.com/AbdelrahmanSadat/ga-issue

### To Reproduce

1. Use `<GoogleAnalytics>` component in the app's layout.
2. Use `sendGAEvent({event: "custom_event", value: 'value'})` on any client component.
3. Add the `custom_event` in [GA](https://support.google.com/analytics/answer/14239696?sjid=1720473978381836552-EU#zippy=%2Canalyze-the-custom-dimension-in-a-report%2Canalyze-the-custom-dimension-in-an-exploration%2Cbuild-an-audience-using-the-dimension)
4. Check Google Analytics [realtime](https://support.google.com/analytics/answer/9271392) dashboard. No event is reported.

### Current vs. Expected behavior

Expected the `custom_event` to be reported in GA.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Script optimization (next/script)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Not really sure how I can provide a reproduction for this since it would also require access to a Google Analytics dashboard. But long story short, I tried `@nextjs/third-parties/google` instead of using a `<Script>`, and while that part works and normal events fire, manually firing custom events (or predefined events) using the library's `SendGAEvent()` doesn't register on the dashboard.

I removed any use of `SendGAEvent()` and instead used `(window as any).gtag("event", "custome_event", {value: "value"})`, and my custom_event was firing and showing on the dashboard, so that rules out any issue in my GA setup.

### PR DESCRIPTION
**Pull request by willashe**
Previous implementation of `sendGAEvent` was pushing arguments to `dataLayer` via rest parameter syntax, resulting in an actual array, which GA doesn't seem to process correctly (resulting in the event not showing up in GA reports).  This PR refactors it to a vanilla JS function passing data via the `arguments` array-like object, which is able to be processed correctly and results in the event showing up as expected.

fixes [61703](https://github.com/vercel/next.js/issues/61703)

### CODE REVIEW

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 520b6973a572abb1678c2aa19d98c0a39c164bde

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c0724b82cd8f90372006c0dfbbdd622a7b5b6b4a

`TURBOPACK=1 pnpm test test/integration/cli/test/index.test.js` (turbopack)
- CLI Usage > dev > NODE_OPTIONS='--inspect'

<details>
<summary>Expand output</summary>

  ● CLI Usage › dev › NODE_OPTIONS='--inspect'

    TIMED OUT: /Debugger listening on/

    Starting inspector on 127.0.0.1:9229 failed: address already in use
    Starting inspector on 127.0.0.1:9230 failed: address already in use


    undefined

      636 |
      637 |   if (hardError) {
    > 638 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      639 |   }
      640 |   return false
      641 | }

      at check (lib/next-test-utils.ts:638:11)
      at Object.<anonymous> (integration/cli/test/index.test.js:549:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | willashe/next.js send-ga-event-fix | Change |
| - | - | - | - |
| buildDuration | 20.4s | 20.4s | N/A |
| buildDurationCached | 8s | 7.2s | N/A |
| nodeModulesSize | 196 MB | 196 MB | ✓ |
| nextStartRea..uration (ms) | 407ms | 409ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | willashe/next.js send-ga-event-fix | Change |
| - | - | - | - |
| 1068-HASH.js gzip | 30.2 kB | 30.2 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.5 kB | 53.5 kB | N/A |
| 4944-HASH.js gzip | 5.04 kB | 5.03 kB | N/A |
| 8423.HASH.js gzip | 181 B | 181 B | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 242 B | N/A |
| main-HASH.js gzip | 32.1 kB | 32.1 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 47.1 kB | 47.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | willashe/next.js send-ga-event-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | willashe/next.js send-ga-event-fix | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 196 B | ✓ |
| _error-HASH.js gzip | 184 B | 183 B | N/A |
| amp-HASH.js gzip | 503 B | 504 B | N/A |
| css-HASH.js gzip | 323 B | 324 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.51 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 353 B | 351 B | N/A |
| hooks-HASH.js gzip | 370 B | 370 B | ✓ |
| image-HASH.js gzip | 4.21 kB | 4.2 kB | N/A |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.68 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 313 B | 314 B | N/A |
| script-HASH.js gzip | 386 B | 385 B | N/A |
| withRouter-HASH.js gzip | 309 B | 311 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 931 B | 931 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | willashe/next.js send-ga-event-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | willashe/next.js send-ga-event-fix | Change |
| - | - | - | - |
| index.html gzip | 528 B | 527 B | N/A |
| link.html gzip | 540 B | 540 B | ✓ |
| withRouter.html gzip | 524 B | 522 B | N/A |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | willashe/next.js send-ga-event-fix | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94.4 kB | 94.4 kB | N/A |
| page.js gzip | 151 kB | 151 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | willashe/next.js send-ga-event-fix | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 627 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 44.4 kB | 44.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.94 kB | 1.94 kB | ✓ |
| Overall change | 2.1 kB | 2.1 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | willashe/next.js send-ga-event-fix | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 166 kB | 166 kB | ✓ |
| app-page-exp..prod.js gzip | 95.5 kB | 95.5 kB | ✓ |
| app-page-tur..prod.js gzip | 97.3 kB | 97.3 kB | ✓ |
| app-page-tur..prod.js gzip | 91.7 kB | 91.7 kB | ✓ |
| app-page.run...dev.js gzip | 136 kB | 136 kB | ✓ |
| app-page.run..prod.js gzip | 90.3 kB | 90.3 kB | ✓ |
| app-route-ex...dev.js gzip | 22 kB | 22 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.7 kB | 9.7 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-turbo...prod.js gzip | 22 kB | 22 kB | ✓ |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | ✓ |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | ✓ |
| server.runti..prod.js gzip | 50 kB | 50 kB | ✓ |
| Overall change | 925 kB | 925 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | willashe/next.js send-ga-event-fix | Change |
| - | - | - | - |
| 0.pack gzip | 1.55 MB | 1.55 MB | N/A |
| index.pack gzip | 104 kB | 103 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

</details>
Commit: c0724b82cd8f90372006c0dfbbdd622a7b5b6b4a

**Comment by willashe** [comment]
Looks like TS isn't happy. Working on a fix.

**Comment by darthmaim** [comment]
Wouldn't it be enough to change the `...args` to just `args` (so instead of passing each element of `args` as a parameter, pass all `args` as array). I don't think the change to the method signature is required.

**Comment by hesselbom** [comment]
Can confirm that this solution solved the issue for me.

This approach of using `arguments` more closely mimics the `gtag()` that Google Analytics creates, meaning the example in the [docs](https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries#sending-events-1) would be `sendGAEvent('event', 'buttonClicked', { value: 'xyz' })` instead of `sendGAEvent({ event: 'buttonClicked', value: 'xyz' })`

At least that's what seemed to work for me when testing. And could be a good thing, because then any `gtag` documentation is more directly translatable to `sendGAEvent`.

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 4572a3bbd70c5c42fcf0c70bc90b7d936605a702

`pnpm test-dev test/e2e/app-dir/interception-route-prefetch-cache/interception-route-prefetch-cache.test.ts` (PPR)
- interception-route-prefetch-cache > runtime = edge > should render the correct interception when two distinct layouts share the same path structure

<details>
<summary>Expand output</summary>

  ● interception-route-prefetch-cache › runtime = edge › should render the correct interception when two distinct layouts share the same path structure

    thrown: "Exceeded timeout of 120000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

       6 | describe('interception-route-prefetch-cache', () => {
       7 |   function runTests({ next }: ReturnType<typeof nextTestSetup>) {
    >  8 |     it('should render the correct interception when two distinct layouts share the same path structure', async () => {
         |     ^
       9 |       const browser = await next.browser('/')
      10 |
      11 |       await browser.elementByCss('[href="/foo"]').click()

      at it (e2e/app-dir/interception-route-prefetch-cache/interception-route-prefetch-cache.test.ts:8:5)
      at runTests (e2e/app-dir/interception-route-prefetch-cache/interception-route-prefetch-cache.test.ts:91:5)
      at describe (e2e/app-dir/interception-route-prefetch-cache/interception-route-prefetch-cache.test.ts:90:3)
      at Object.describe (e2e/app-dir/interception-route-prefetch-cache/interception-route-prefetch-cache.test.ts:6:1)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: packages/third-parties/src/google/ga.tsx [hunk 1]
```diff
@@ -54,14 +54,14 @@ export function GoogleAnalytics(props: GAParams) {
...
-export function sendGAEvent() {
+export const sendGAEvent = (...args: Object[]) => {
   if (currDataLayerName === undefined) {
     console.warn(`@next/third-parties: GA has not been initialized`)
     return
   }
 
   if (window[currDataLayerName]) {
-    window[currDataLayerName].push(arguments)
+    window[currDataLayerName].push(args)
```
Comment (asobirov) [inline packages/third-parties/src/google/ga.tsx:64]: We might want to leave this one as `arguements`. It seems like this does not work with Arrays, but works with [arguments object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments). Additionally, when using `window.gtag(...)` an `Arguments()` is pushed instead of `Array()`.

Might be related, see: https://stackoverflow.com/questions/60400130/google-analytics-datalayer-push-not-working-with-array-of-variables#60410151

Comment (asobirov) [reply packages/third-parties/src/google/ga.tsx:64]: Not sure if TS will like it:
```suggestion
    window[currDataLayerName].push(arguements)
```

Comment (willashe) [reply packages/third-parties/src/google/ga.tsx:64]: Yes, this should not have been changed from `arguments`...

**Comment by daynejones** [comment]
This doesn't seem to work for me, maybe I've got the usage wrong.

I'm using next/third-parties v14.1.1 and I'm calling `sendGAEvent` like so:

```
sendGAEvent('event', 'testEvent', { 'param1': 'val1' });
```

I'm seeing weird stuff in the DataLayer and I do NOT see /collect endpoint hits.

image

**Comment by asobirov** [comment]
Hey @daynejones, just to double check:
- are you trying to use GTM or GA
- There should be a `GET` request to `https://www.googletagmanager.com/gtag/js?id=G-<YOUR_GA_ID>`. Make sure that it is 200, otherwise you may not see the `/collect`

The usage seems to be ok

**Comment by daynejones** [comment]
Thanks for the response @asobirov 

Maybe that's the problem. I've got GTM and GA running (it's a third party's requirement). 

I see a 200 for gtm itself and I see `/collect` hits for the default events like pageview and scroll.

**Comment by asobirov** [comment]
I think the issue might just be the package version. Tried out the `v14.1.1` and saw the same issue. So you may want to use the canary for now. A lil clue from release notes for v14.1.1:
> Note: this is a backport release for critical bug fixes -- this does not include all pending features/changes on canary

So you should be good using the pre-release version - [v14.1.1-canary.82](https://github.com/vercel/next.js/releases/tag/v14.1.1-canary.82)

**Comment by daynejones** [comment]
Got it. Will try that and report back.

**Comment by daynejones** [comment]
Yep, works now. Thanks for the help!

**Comment by luknl** [comment]
Using 14.1.2 and it's still not working for me. What version are you in exactly?

**Comment by hjick** [comment]
What about this PR? I'd love to get feedback!
https://github.com/vercel/next.js/pull/63226#issue-2183211909

**Comment by comp615** [comment]
For those following, this is still not fixed nor the docs corrected in main (unsure why it wasn't backported since it's a regression/bug?). You must use `v14.2.0-canary.34` and `sendGAEvent("event", "custom_name", { value });`

**Comment by craigRSA** [comment]
> For those following, this is still not fixed nor the docs corrected in main (unsure why it wasn't backported since it's a regression/bug?). You must use `v14.2.0-canary.34` and `sendGAEvent("event", "custom_name", { value });`

Is this working for anyone in v14.2.0-canary.34?

**Comment by dariuscosden** [comment]
@craigRSA yeah, works for me!

**Comment by dariuscosden** [comment]
@craigRSA yes exactly. However I'm sending it using `setTimeout` of 500ms, since in some cases the `dataLayer` wasn't available (saw logs in console and didn't want to deal with it)

**Comment by craigRSA** [comment]
it works when running from my local but once its build in prod on Vercel it stops working. Other events work fine, just not the custom ones. It's a client component. Annoying..

**Comment by m1dok** [comment]
@craigRSA 

Same for me! it run inlocal but non in prod, but not on Vercel.

**Comment by craigRSA** [comment]
@m1dok we used GTM to forward the requests to GA via a trigger and event parameters to send through all the fields we wanted
