### PR TITLE
fix: use absolute paths

### LINKED ISSUE #21679: Error: Cannot find module 'webpack'
**What version of Next.js are you using?**

10.0.6

**What version of Node.js are you using?**

14.15.4

**What browser are you using?**

Safari

**What operating system are you using?**

macOS

**How are you deploying your application?**

yarn build locally

**Describe the Bug**

I just updated to 10.0.6 version from 10.0.5 and im getting the next error: Error: Cannot find module 'webpack'.

I found out that if I remove next-pwa it works, and the terminal output while building all of the errors came form next-pwa.

**Expected Behavior**

If I downgrade to 10.0.5 my project builds in dev and prod.

**To Reproduce**

Install the latest version of next and install next-pwa.

`
yarn install v1.22.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning next-pwa > workbox-webpack-plugin > workbox-build > rollup > fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
warning next-pwa > workbox-webpack-plugin > workbox-build > @hapi/joi@16.1.8: Switch to 'npm install joi'
warning next-pwa > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning next-pwa > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
warning next-pwa > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
warning next-pwa > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
warning next-pwa > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning next-pwa > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > next-pwa@5.0.4" has unmet peer dependency "webpack@>=4.0.0".
warning "next-pwa > babel-loader@8.2.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "next-pwa > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
warning "next-pwa > workbox-webpack-plugin@6.1.0" has unmet peer dependency "webpack@^4.4.0 || ^5.9.0".
warning "next-pwa > clean-webpack-plugin@3.0.0" has unmet peer dependency "webpack@*".
warning " > tailwindcss-font-inter@2.0.0" has incorrect peer dependency "tailwindcss@^1.9.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 23.34s.
jcgm@JoseloG-Macbook-Pro landing-site % yarn build          
yarn run v1.22.10
$ next build
Loaded env from /Users/jcgm/Dev/Kapital/landing-site/.env.local

> Build error occurred
Error: Cannot find module 'webpack'
Require stack:
- /Users/jcgm/Dev/Kapital/landing-site/node_modules/workbox-webpack-plugin/build/generate-sw.js
- /Users/jcgm/Dev/Kapital/landing-site/node_modules/workbox-webpack-plugin/build/index.js
- /Users/jcgm/Dev/Kapital/landing-site/node_modules/next-pwa/index.js
- /Users/jcgm/Dev/Kapital/landing-site/next.config.js
- /Users/jcgm/Dev/Kapital/landing-site/node_modules/next/dist/next-server/server/config.js
- /Users/jcgm/Dev/Kapital/landing-site/node_modules/next/dist/build/index.js
- /Users/jcgm/Dev/Kapital/landing-site/node_modules/next/dist/cli/next-build.js
- /Users/jcgm/Dev/Kapital/landing-site/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/jcgm/Dev/Kapital/landing-site/node_modules/workbox-webpack-plugin/build/generate-sw.js:18:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/jcgm/Dev/Kapital/landing-site/node_modules/workbox-webpack-plugin/build/index.js:10:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jcgm/Dev/Kapital/landing-site/node_modules/workbox-webpack-plugin/build/generate-sw.js',
    '/Users/jcgm/Dev/Kapital/landing-site/node_modules/workbox-webpack-plugin/build/index.js',
    '/Users/jcgm/Dev/Kapital/landing-site/node_modules/next-pwa/index.js',
    '/Users/jcgm/Dev/Kapital/landing-site/next.config.js',
    '/Users/jcgm/Dev/Kapital/landing-site/node_modules/next/dist/next-server/server/config.js',
    '/Users/jcgm/Dev/Kapital/landing-site/node_modules/next/dist/build/index.js',
    '/Users/jcgm/Dev/Kapital/landing-site/node_modules/next/dist/cli/next-build.js',
    '/Users/jcgm/Dev/Kapital/landing-site/node_modules/next/dist/bin/next'
  ]
}
error Command failed with exit code 1.
`

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

The hook added in https://github.com/vercel/next.js/pull/21802 doesn't use absolute paths so it doesn't work correctly

**How did you fix it?**

Use absolute paths

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 8.9s | 8.8s | -166ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.73 | 1.759 | ⚠️ +0.03 |
| / avg req/sec | 1445.14 | 1421.24 | ⚠️ -23.9 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.126 | 1.105 | -0.02 |
| /error-in-render avg req/sec | 2219.97 | 2262.47 | +42.5 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.8s | ⚠️ +276ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.06 MB | 1.06 MB | ✓ |
| withRouter.js | 1.06 MB | 1.06 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 10.6s | 10.8s | ⚠️ +212ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.769 | 1.763 | -0.01 |
| / avg req/sec | 1412.91 | 1417.67 | +4.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.09 | 1.083 | -0.01 |
| /error-in-render avg req/sec | 2293.1 | 2308.06 | +14.96 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 580 B | 580 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "yWJClqOds7_RUOUqAgkCh",
+        "buildId": "tyHt7TpVwEj1nMJFU8icP",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/yWJClqOds7_RUOUqAgkCh/_buildManifest.js"
+      src="/_next/static/tyHt7TpVwEj1nMJFU8icP/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/yWJClqOds7_RUOUqAgkCh/_ssgManifest.js"
+      src="/_next/static/tyHt7TpVwEj1nMJFU8icP/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "yWJClqOds7_RUOUqAgkCh",
+        "buildId": "tyHt7TpVwEj1nMJFU8icP",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/yWJClqOds7_RUOUqAgkCh/_buildManifest.js"
+      src="/_next/static/tyHt7TpVwEj1nMJFU8icP/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/yWJClqOds7_RUOUqAgkCh/_ssgManifest.js"
+      src="/_next/static/tyHt7TpVwEj1nMJFU8icP/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "yWJClqOds7_RUOUqAgkCh",
+        "buildId": "tyHt7TpVwEj1nMJFU8icP",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/yWJClqOds7_RUOUqAgkCh/_buildManifest.js"
+      src="/_next/static/tyHt7TpVwEj1nMJFU8icP/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/yWJClqOds7_RUOUqAgkCh/_ssgManifest.js"
+      src="/_next/static/tyHt7TpVwEj1nMJFU8icP/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 7a57437eccfd58cdcfcde7c73f7df1bac9758a72

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 9s | 8.9s | -98ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.767 | 1.781 | ⚠️ +0.01 |
| / avg req/sec | 1414.96 | 1403.99 | ⚠️ -10.97 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.119 | 1.069 | -0.05 |
| /error-in-render avg req/sec | 2234.88 | 2337.58 | +102.7 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 10.8s | 10.8s | -57ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.06 MB | 1.06 MB | ✓ |
| withRouter.js | 1.06 MB | 1.06 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 10.7s | 10.9s | ⚠️ +186ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.78 | 1.755 | -0.03 |
| / avg req/sec | 1404.27 | 1424.64 | +20.37 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.109 | 1.151 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2255.1 | 2172.59 | ⚠️ -82.51 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 580 B | 580 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "9vhE_VY-tXRRwMSZNYndD",
+        "buildId": "_XheALXnYPxfqAhgE0KkF",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/9vhE_VY-tXRRwMSZNYndD/_buildManifest.js"
+      src="/_next/static/_XheALXnYPxfqAhgE0KkF/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/9vhE_VY-tXRRwMSZNYndD/_ssgManifest.js"
+      src="/_next/static/_XheALXnYPxfqAhgE0KkF/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "9vhE_VY-tXRRwMSZNYndD",
+        "buildId": "_XheALXnYPxfqAhgE0KkF",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/9vhE_VY-tXRRwMSZNYndD/_buildManifest.js"
+      src="/_next/static/_XheALXnYPxfqAhgE0KkF/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/9vhE_VY-tXRRwMSZNYndD/_ssgManifest.js"
+      src="/_next/static/_XheALXnYPxfqAhgE0KkF/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "9vhE_VY-tXRRwMSZNYndD",
+        "buildId": "_XheALXnYPxfqAhgE0KkF",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/9vhE_VY-tXRRwMSZNYndD/_buildManifest.js"
+      src="/_next/static/_XheALXnYPxfqAhgE0KkF/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/9vhE_VY-tXRRwMSZNYndD/_ssgManifest.js"
+      src="/_next/static/_XheALXnYPxfqAhgE0KkF/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 6567cfc3410d298a0715742541c409a8849e053a

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.2s | -113ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.066 | 2.195 | ⚠️ +0.13 |
| / avg req/sec | 1210.02 | 1139.11 | ⚠️ -70.91 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.437 | 1.515 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1739.72 | 1650.43 | ⚠️ -89.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12s | -21ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.06 MB | 1.06 MB | ✓ |
| withRouter.js | 1.06 MB | 1.06 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 12.5s | 13.2s | ⚠️ +714ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.17 | 2.05 | -0.12 |
| / avg req/sec | 1151.87 | 1219.68 | +67.81 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.522 | 1.432 | -0.09 |
| /error-in-render avg req/sec | 1642.63 | 1746.29 | +103.66 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 580 B | 580 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "fGk_Z3T9MCXZTdCz2dWJP",
+        "buildId": "xzLVJBYLMdIjO7-DEalJ8",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/fGk_Z3T9MCXZTdCz2dWJP/_buildManifest.js"
+      src="/_next/static/xzLVJBYLMdIjO7-DEalJ8/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/fGk_Z3T9MCXZTdCz2dWJP/_ssgManifest.js"
+      src="/_next/static/xzLVJBYLMdIjO7-DEalJ8/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "fGk_Z3T9MCXZTdCz2dWJP",
+        "buildId": "xzLVJBYLMdIjO7-DEalJ8",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/fGk_Z3T9MCXZTdCz2dWJP/_buildManifest.js"
+      src="/_next/static/xzLVJBYLMdIjO7-DEalJ8/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/fGk_Z3T9MCXZTdCz2dWJP/_ssgManifest.js"
+      src="/_next/static/xzLVJBYLMdIjO7-DEalJ8/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "fGk_Z3T9MCXZTdCz2dWJP",
+        "buildId": "xzLVJBYLMdIjO7-DEalJ8",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/fGk_Z3T9MCXZTdCz2dWJP/_buildManifest.js"
+      src="/_next/static/xzLVJBYLMdIjO7-DEalJ8/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/fGk_Z3T9MCXZTdCz2dWJP/_ssgManifest.js"
+      src="/_next/static/xzLVJBYLMdIjO7-DEalJ8/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 262fa3cc6a8be7585e72044237e4d95256a7ca54

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 10.8s | 11.1s | ⚠️ +313ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.177 | 2.216 | ⚠️ +0.04 |
| / avg req/sec | 1148.47 | 1128.23 | ⚠️ -20.24 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.426 | 1.403 | -0.02 |
| /error-in-render avg req/sec | 1753.75 | 1782.06 | +28.31 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 12.9s | 12.8s | -42ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.06 MB | 1.06 MB | ✓ |
| withRouter.js | 1.06 MB | 1.06 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.1s | -116ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.175 | 2.126 | -0.05 |
| / avg req/sec | 1149.18 | 1175.9 | +26.72 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.279 | 1.399 | ⚠️ +0.12 |
| /error-in-render avg req/sec | 1954.89 | 1786.51 | ⚠️ -168.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 580 B | 580 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "TmP-fgw5E_E4xvWANPVdv",
+        "buildId": "HKkDwnCcYAIOEd_QkDYZk",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/TmP-fgw5E_E4xvWANPVdv/_buildManifest.js"
+      src="/_next/static/HKkDwnCcYAIOEd_QkDYZk/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/TmP-fgw5E_E4xvWANPVdv/_ssgManifest.js"
+      src="/_next/static/HKkDwnCcYAIOEd_QkDYZk/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "TmP-fgw5E_E4xvWANPVdv",
+        "buildId": "HKkDwnCcYAIOEd_QkDYZk",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/TmP-fgw5E_E4xvWANPVdv/_buildManifest.js"
+      src="/_next/static/HKkDwnCcYAIOEd_QkDYZk/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/TmP-fgw5E_E4xvWANPVdv/_ssgManifest.js"
+      src="/_next/static/HKkDwnCcYAIOEd_QkDYZk/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "TmP-fgw5E_E4xvWANPVdv",
+        "buildId": "HKkDwnCcYAIOEd_QkDYZk",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/TmP-fgw5E_E4xvWANPVdv/_buildManifest.js"
+      src="/_next/static/HKkDwnCcYAIOEd_QkDYZk/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/TmP-fgw5E_E4xvWANPVdv/_ssgManifest.js"
+      src="/_next/static/HKkDwnCcYAIOEd_QkDYZk/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 755ee797f7ef3d351755d5cf81f66dd50c03dad9

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 2a07c7549e17d708de8ebeb8c5b2db2080282832

**test/integration/config/test/index.test.js** 
- Configuration > should disable X-Powered-By header support
- Configuration > renders css imports
- Configuration > renders non-js imports from node_modules
- Configuration > renders server config on the server only
- Configuration > renders public config on the server only
- Configuration > renders the build id in development mode
- Configuration > correctly imports a package that defines `module` but no `main` in package.json
- Configuration > should have config available on the client
- Configuration > should update css styles using hmr
- Configuration > should update sass styles using hmr

<details>
<summary>Expand output</summary>

  ● Configuration › should disable X-Powered-By header support

    FetchError: request to http://localhost:40299/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:40299

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders css imports

    FetchError: request to http://localhost:40299/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:40299

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders non-js imports from node_modules

    FetchError: request to http://localhost:40299/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:40299

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders server config on the server only

    FetchError: request to http://localhost:40299/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:40299

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders public config on the server only

    FetchError: request to http://localhost:40299/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:40299

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders the build id in development mode

    FetchError: request to http://localhost:40299/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:40299

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › correctly imports a package that defines `module` but no `main` in package.json

    FetchError: request to http://localhost:40299/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:40299

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › should have config available on the client

    FetchError: request to http://localhost:40299/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:40299

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › should update css styles using hmr

    FetchError: request to http://localhost:40299/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:40299

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › should update sass styles using hmr

    FetchError: request to http://localhost:40299/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:40299

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 10.4s | 9.6s | -831ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +338 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.164 | 2.314 | ⚠️ +0.15 |
| / avg req/sec | 1155.33 | 1080.34 | ⚠️ -74.99 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.452 | 1.47 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1721.52 | 1700.28 | ⚠️ -21.24 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 12s | 12s | ⚠️ +57ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +338 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.06 MB | 1.06 MB | ✓ |
| withRouter.js | 1.06 MB | 1.06 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 12.8s | 14.4s | ⚠️ +1.7s |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +338 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.132 | 2.297 | ⚠️ +0.17 |
| / avg req/sec | 1172.53 | 1088.32 | ⚠️ -84.21 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.493 | 1.579 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 1674.49 | 1583.24 | ⚠️ -91.25 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 580 B | 580 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "AI9N_qw-U361sc3MSB5na",
+        "buildId": "Hl8bETal6BLB2EtqnET-Y",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/AI9N_qw-U361sc3MSB5na/_buildManifest.js"
+      src="/_next/static/Hl8bETal6BLB2EtqnET-Y/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/AI9N_qw-U361sc3MSB5na/_ssgManifest.js"
+      src="/_next/static/Hl8bETal6BLB2EtqnET-Y/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "AI9N_qw-U361sc3MSB5na",
+        "buildId": "Hl8bETal6BLB2EtqnET-Y",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/AI9N_qw-U361sc3MSB5na/_buildManifest.js"
+      src="/_next/static/Hl8bETal6BLB2EtqnET-Y/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/AI9N_qw-U361sc3MSB5na/_ssgManifest.js"
+      src="/_next/static/Hl8bETal6BLB2EtqnET-Y/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "AI9N_qw-U361sc3MSB5na",
+        "buildId": "Hl8bETal6BLB2EtqnET-Y",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/AI9N_qw-U361sc3MSB5na/_buildManifest.js"
+      src="/_next/static/Hl8bETal6BLB2EtqnET-Y/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/AI9N_qw-U361sc3MSB5na/_ssgManifest.js"
+      src="/_next/static/Hl8bETal6BLB2EtqnET-Y/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 2a07c7549e17d708de8ebeb8c5b2db2080282832

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 429f2defbb2171155f282324099caad11425ce2b

**test/integration/config/test/index.test.js** 
- Configuration > should disable X-Powered-By header support
- Configuration > renders css imports
- Configuration > renders non-js imports from node_modules
- Configuration > renders server config on the server only
- Configuration > renders public config on the server only
- Configuration > renders the build id in development mode
- Configuration > correctly imports a package that defines `module` but no `main` in package.json
- Configuration > should have config available on the client
- Configuration > should update css styles using hmr
- Configuration > should update sass styles using hmr

<details>
<summary>Expand output</summary>

  ● Configuration › should disable X-Powered-By header support

    FetchError: request to http://localhost:41829/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:41829

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders css imports

    FetchError: request to http://localhost:41829/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:41829

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders non-js imports from node_modules

    FetchError: request to http://localhost:41829/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:41829

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders server config on the server only

    FetchError: request to http://localhost:41829/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:41829

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders public config on the server only

    FetchError: request to http://localhost:41829/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:41829

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders the build id in development mode

    FetchError: request to http://localhost:41829/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:41829

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › correctly imports a package that defines `module` but no `main` in package.json

    FetchError: request to http://localhost:41829/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:41829

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › should have config available on the client

    FetchError: request to http://localhost:41829/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:41829

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › should update css styles using hmr

    FetchError: request to http://localhost:41829/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:41829

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › should update sass styles using hmr

    FetchError: request to http://localhost:41829/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:41829

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 10.8s | 10.6s | -108ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +683 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.208 | 2.191 | -0.02 |
| / avg req/sec | 1132.33 | 1141.02 | +8.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.563 | 1.592 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1599.24 | 1570.34 | ⚠️ -28.9 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.6s | ⚠️ +111ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +683 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.06 MB | 1.06 MB | ✓ |
| withRouter.js | 1.06 MB | 1.06 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.3s | ⚠️ +139ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +683 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.236 | 2.289 | ⚠️ +0.05 |
| / avg req/sec | 1117.86 | 1092.4 | ⚠️ -25.46 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.634 | 1.61 | -0.02 |
| /error-in-render avg req/sec | 1530.02 | 1553.15 | +23.13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 580 B | 580 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "xveaJAGGG1y6O8NjqYiS6",
+        "buildId": "T6wsprK53EqcAedUfSisf",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/xveaJAGGG1y6O8NjqYiS6/_buildManifest.js"
+      src="/_next/static/T6wsprK53EqcAedUfSisf/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/xveaJAGGG1y6O8NjqYiS6/_ssgManifest.js"
+      src="/_next/static/T6wsprK53EqcAedUfSisf/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "xveaJAGGG1y6O8NjqYiS6",
+        "buildId": "T6wsprK53EqcAedUfSisf",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/xveaJAGGG1y6O8NjqYiS6/_buildManifest.js"
+      src="/_next/static/T6wsprK53EqcAedUfSisf/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/xveaJAGGG1y6O8NjqYiS6/_ssgManifest.js"
+      src="/_next/static/T6wsprK53EqcAedUfSisf/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "xveaJAGGG1y6O8NjqYiS6",
+        "buildId": "T6wsprK53EqcAedUfSisf",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/xveaJAGGG1y6O8NjqYiS6/_buildManifest.js"
+      src="/_next/static/T6wsprK53EqcAedUfSisf/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/xveaJAGGG1y6O8NjqYiS6/_ssgManifest.js"
+      src="/_next/static/T6wsprK53EqcAedUfSisf/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 429f2defbb2171155f282324099caad11425ce2b

**Review by guybedford — DISMISSED** [review]
Looks good to me, thanks for following up on this.

**Comment by merceyz** [comment]
I'm not sure what to do about all those failing tests though, so if someone wants to take a look at that I would appreciate it

File: test-pnp.sh [hunk 1]
```diff
@@ -1,4 +1,7 @@
 declare -a testCases=(
+  # Tests the webpack require hook
+  "progressive-web-app"
```
Comment (guybedford) [inline test-pnp.sh:3]: Are the failures due to this addition? Can we at least test that.

Comment (merceyz) [reply test-pnp.sh:3]: That shouldn't affect the `Build, test, and deploy / Test Integration (5) (pull_request)` family of tests

File: packages/next/next-server/server/config.ts [hunk 2]
```diff
@@ -501,6 +501,10 @@ export default function loadConfig(
 
   // If config file was found
   if (path?.length) {
+    // hook the Node.js require so that webpack requires are
+    // routed to the bundled webpack version
+    require('../../build/webpack/require-hook')
```
Comment (guybedford) [inline packages/next/next-server/server/config.ts:506]: The issue is most likely here then? Can we at least bisect by reverting this change only, to be sure?

Comment (guybedford) [reply packages/next/next-server/server/config.ts:506]: Ping @merceyz would be great to see this adjusted to see if that changes the results here. I won't be able to follow up on this personally until next month.

Comment (merceyz) [reply packages/next/next-server/server/config.ts]: Reverted, lets see

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 11.1s | 10.9s | -228ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +345 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.334 | 2.306 | -0.03 |
| / avg req/sec | 1071.14 | 1083.92 | +12.78 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.647 | 1.603 | -0.04 |
| /error-in-render avg req/sec | 1517.7 | 1559.83 | +42.13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13s | -142ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +345 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.06 MB | 1.06 MB | ✓ |
| withRouter.js | 1.06 MB | 1.06 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| buildDuration | 13.3s | 13.5s | ⚠️ +192ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +345 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.228 | 2.222 | -0.01 |
| / avg req/sec | 1122.29 | 1125.03 | +2.74 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.567 | 1.563 | 0 |
| /error-in-render avg req/sec | 1595.68 | 1599.95 | +4.27 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | merceyz/next.js merceyz/webpack-hook | Change |
| - | - | - | - |
| index.html gzip | 584 B | 584 B | ✓ |
| link.html gzip | 591 B | 591 B | ✓ |
| withRouter.html gzip | 578 B | 578 B | ✓ |
| Overall change | 1.75 kB | 1.75 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "avcJsqAOxpXF6YmjcZQwc",
+        "buildId": "gLEXtZ22dYZc6bnSMm4ZT",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/avcJsqAOxpXF6YmjcZQwc/_buildManifest.js"
+      src="/_next/static/gLEXtZ22dYZc6bnSMm4ZT/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/avcJsqAOxpXF6YmjcZQwc/_ssgManifest.js"
+      src="/_next/static/gLEXtZ22dYZc6bnSMm4ZT/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "avcJsqAOxpXF6YmjcZQwc",
+        "buildId": "gLEXtZ22dYZc6bnSMm4ZT",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/avcJsqAOxpXF6YmjcZQwc/_buildManifest.js"
+      src="/_next/static/gLEXtZ22dYZc6bnSMm4ZT/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/avcJsqAOxpXF6YmjcZQwc/_ssgManifest.js"
+      src="/_next/static/gLEXtZ22dYZc6bnSMm4ZT/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "avcJsqAOxpXF6YmjcZQwc",
+        "buildId": "gLEXtZ22dYZc6bnSMm4ZT",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/avcJsqAOxpXF6YmjcZQwc/_buildManifest.js"
+      src="/_next/static/gLEXtZ22dYZc6bnSMm4ZT/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/avcJsqAOxpXF6YmjcZQwc/_ssgManifest.js"
+      src="/_next/static/gLEXtZ22dYZc6bnSMm4ZT/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: e849c561243db61097331febbc2d00b73ad72884

**Comment by timneutkens** [comment]
> Error: workbox-webpack-plugin tried to access webpack (a peer dependency) but it isn't provided by your application; this makes the require call ambiguous and unsound.

Seems like the PnP test highlights that the yarn require hook runs earlier than the webpack require hook causing the test to fail 🤔 This PR does solve the issue for all other cases though so I'm fine with landing it given that it's currently broken with PnP anyway.

**Comment by merceyz** [comment]
It highlights that the webpack hook isn't run early enough but [when I fixed that](https://github.com/vercel/next.js/pull/21877/commits/2a07c7549e17d708de8ebeb8c5b2db2080282832) I broke all of your tests  which I don't know how to fix

**Comment by timneutkens** [comment]
I'll have a look into it 👍
