### PR TITLE
Fix parallel routes with server actions / revalidating router cache

### LINKED ISSUE #54173: revalidatePath() not working as expected for Parallel Routes, or for Parallel + Intercepting Routes (modal)
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Thu Jun  8 23:57:12 PDT 2023; root:xnu-8020.240.18.701.6~1/RELEASE_X86_64
    Binaries:
      Node: 20.5.1
      npm: 9.8.0
      Yarn: 1.22.19
      pnpm: 8.6.12
    Relevant Packages:
      next: 13.4.17
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/magoz/revalidatepath-parallel-routes-bug

### To Reproduce

Click on [Parallel+Intercepting Modal](https://revalidatepath-parallel-routes-bug.vercel.app/parallel-intercepting).

### Describe the Bug

When clicking on the `Trigger Server Action` button, the server action is triggered just by fetching a new random number and passing it to a client component.

It works perfectly for the [Home Page](https://revalidatepath-parallel-routes-bug.vercel.app/), and a [Leaf Page](https://revalidatepath-parallel-routes-bug.vercel.app/leaf).

But for a Page that uses Parallel + Intercepting Routes (modal), `revalidatePath('/parallel-intercepting')` seems to fetch the new data, and the component appears to receive the new props (see client console), but it doesn't re-render.

For a page that uses Parallel Routes (modal without Intercepting), works as expected on hard navigation, but on soft navigation we get the same issue than the Parallel + Intercepting Routes case.

### Expected Behavior

`revalidatePath()` to work as expected for Parallel Routes, and for Parallel + Intercepting Routes.

### Which browser are you using? (if relevant)

Chrome 115.0.5790.170

### How are you deploying your application? (if relevant)

pnpm dev

<sub>[NEXT-1706](https://linear.app/vercel/issue/NEXT-1706/revalidatepath-not-working-as-expected-for-parallel-routes-or-for)</sub>

### LINKED ISSUE #54723: calling router.refresh in a parallel route breaks routing without any error messages
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.20-canary.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/wild-browser-3yjcn4

### To Reproduce

- Open the sandbox. 
- Navigate using the links on the page.
- goto /create
- click the "break" button
- try goto /

### Describe the Bug

Routing stops working, both router and Link after router.refresh().

### Expected Behavior

Routing should work.

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### LINKED ISSUE #57665: Server Actions Inside Slots Do not work as expected
### Link to the code that reproduces this issue

https://github.com/joelrozen/nextgram

### To Reproduce

1. Install dependencies and start application (`npm i && npm run dev`)
2. Click a photo so it opens in the Modal
3. Click "Redirect Me" Button
4. Observe in server console "action triggered" gets logged, however the page never redirects back to '/'. Inspecting the form element of the modal also reveals that the form action is `javascript:throw new Error('A React form was unexpectedly submitted...` and none of the hidden nextjs form inputs are injected.
5. Hard refresh the photo route so that the image loads in the page instead of the Modal slot.
6. Observe HTML of form looks correct, click the "Redirect Me" button
7. Observer "action triggered" gets logged to server console and 1 second later, the page is redirected back to "/"

### Current vs. Expected behavior

Expect server actions inside forms to work consistently no matter where they're rendered (page, slots, intercepted/parallel routes etc).

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
Binaries:
  Node: 18.18.1
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 7.13.4
Relevant Packages:
  next: 14.0.1-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

same behaviour observed when using useFormState

<sub>[NEXT-1812](https://linear.app/vercel/issue/NEXT-1812/server-actions-inside-slots-do-not-work-as-expected)</sub>

### LINKED ISSUE #58772: Calling revalidatePath() or revalidateTag() in Server Actions that are triggered from Intercepting Routes breaks useFormStatus() and useFormState()
### Link to the code that reproduces this issue

https://github.com/flsilva/next-v14-revalidate-issue-1

### To Reproduce

1. Visit https://next-v14-revalidate-issue-1.vercel.app
2. Scroll down and fill in the **name** input text.
3.  Click the **Submit** button in the **/src/app/page.tsx** box.
4. It works as expected. The **Submit** button changes to **Submitting...** and after 3 seconds it changes back to **Submit**, and you can see the Server Action's response.
5. Click **Nav to /foo** to visit the Intercepting Route **/foo**.
6. Fill in the **name** input text in either form.
7. Click the **Submit** button in either form.
8.  It doesn't work as expected. The **Submit** button changes to **Submitting...** but never changes back to **Submit**, and we never get the Server Action's response. Client Components never re-render.

### Current vs. Expected behavior

When we're at the **/foo** Intercepting Route we should see the same behavior we see when we're at the root route **/**, i.e., after clicking the **Submit** button it should change to **Submitting...** and after 3 seconds it should change back to **Submit**, and we should see the Server Action's response.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.9
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I can reproduce the issue in **v14.0.4-canary.9** on localhost and Vercel.

Code changes that results in the same behavior:

1. Changing **revalidatePath('/')** to **revalidatePath('/', 'page')**.
2. Changing **revalidatePath('/')** to **revalidatePath('/', 'layout')**.
3. Changing **revalidatePath('/')** to **revalidatePath('/foo')**.
4. Changing **revalidatePath('/')** to **revalidatePath('/foo', 'page')**.
5. Changing **revalidatePath('/')** to **revalidatePath('/foo', 'layout')**.
6. Replacing **revalidatePath()** with **revalidateTag('anything')**.

Code changes that results in the expected behavior:

1. If we comment out the **revalidatePath('/')** line of code in **action.ts** everything works as expected because we're not relying on cached data in this app.

Routing structure:

```
app
├── @intercept
│   ├── (.)foo
│   │   └── page.tsx
│   ├── [...catchAll]
│   │   └── default.tsx
│   └── default.tsx
│   └── page.tsx
├── foo
│   └── page.tsx
├── layout.tsx
└── page.tsx
```

Relevant code:

app/action.ts

```typescript
"use server";

import { revalidatePath } from "next/cache";

export const action = async (
  previousState: string | undefined,
  formData: FormData
) => {
  const name = formData.get("name");
  await new Promise((resolve) => setTimeout(resolve, 3000));
  revalidatePath("/");
  return `name: ${name} | Math.random(): ${(Math.random() * 100).toFixed(2)}`;
};
```

app/MyForm.tsx

```typescript
"use client";

import { useFormState } from "react-dom";
import { SubmitButton } from "./SubmitButton";
import { action } from "./action";

export const MyForm = () => {
  const [result, formAction] = useFormState(action, undefined);

  return (
    <form action={formAction}>
      <input type="text" name="name" placeholder="Name" autoComplete="off" />
      <SubmitButton />
      <p>Response: {result}</p>
    </form>
  );
};
```

app/SubmitButton.tsx

```typescript
"use client";

import { useFormStatus } from "react-dom";

export const SubmitButton = () => {
  const { pending } = useFormStatus();
  return (
    <button type="submit" disabled={pending}>
      {pending ? "Submitting..." : "Submit"}
    </button>
  );
};
```

Replay:

next-v14-revalidate-issue-1

<sub>[NEXT-1815](https://linear.app/vercel/issue/NEXT-1815/calling-revalidatepath-or-revalidatetag-in-server-actions-that-are)</sub>

### PR DESCRIPTION
**Pull request by ztanner**
### What?
There are a bunch of different bugs caused by the same underlying issue, but the common thread is that performing any sort of router cache update (either through `router.refresh()`, `revalidatePath()`, or `redirect()`) inside of a parallel route would break the router preventing subsequent actions, and not resolve any pending state such as from `useFormState`. 

### Why?
`applyPatch` is responsible for taking an update response from the server and merging it into the client router cache. However, there's specific bailout logic to skip over applying the patch to a `__DEFAULT__` segment (which corresponds with a `default.tsx` page). When the router detects a cache node that is expected to be rendered on the page but contains no data, the router will trigger a lazy fetch to retrieve the data that's expected to be there ([ref](https://github.com/vercel/next.js/blob/5adacb69126e0fd7dff7ebd45278c0dfd42f6116/packages/next/src/client/components/layout-router.tsx#L359-L370)) and then update the router cache once the data resolves ([ref](https://github.com/vercel/next.js/blob/5adacb69126e0fd7dff7ebd45278c0dfd42f6116/packages/next/src/client/components/layout-router.tsx#L399-L404)).

This is causing the router to get stuck in a loop: it'll fetch the data for the cache node, send the data to the router reducer to merge it into the existing cache nodes, skip merging that data in for `__DEFAULT__` segments, and repeat.

### How?
We currently assign `__DEFAULT__` to have `notFound()` behavior when there isn't a `default.tsx` component for a particular segment. This makes it so that when loading a page that renders a slot without slot content / a `default`, it 404s. But when performing a client-side navigation, the intended behavior is different: we keep whatever was in the `default` slots place, until the user refreshes the page, which would then 404. 

However, this logic is incorrect when triggering any of the above mentioned cache node revalidation strategies: if we always skip applying to the `__DEFAULT__` segment, slots will never properly handle reducer actions that rely on making changes to their cache nodes. 

This splits these different `applyPatch` functions: one that will apply to the full tree, and another that'll apply to everything except the default segments with the existing bailout condition. 

Fixes #54173
Fixes #58772
Fixes #54723
Fixes #57665

Closes NEXT-1706
Closes NEXT-1815
Closes NEXT-1812

### CODE REVIEW

**Comment by ztanner** [comment]
Current dependencies on/for this PR:
* `canary`
  * **PR #59585** <a href="https://app.graphite.dev/github/pr/vercel/next.js/59585?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/59585?utm_source=stack-comment).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 12-13-fix_action_revalidation_within_a_parallel_slot | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.7s | N/A |
| buildDurationCached | 7.2s | 5.9s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +3.16 kB |
| nextStartRea..uration (ms) | 422ms | 423ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-13-fix_action_revalidation_within_a_parallel_slot | Change |
| - | - | - | - |
| 170-HASH.js gzip | 28.6 kB | 28.7 kB | N/A |
| 199.HASH.js gzip | 181 B | 185 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 240 B | 241 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-13-fix_action_revalidation_within_a_parallel_slot | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-13-fix_action_revalidation_within_a_parallel_slot | Change |
| - | - | - | - |
| _app-HASH.js gzip | 195 B | 194 B | N/A |
| _error-HASH.js gzip | 183 B | 182 B | N/A |
| amp-HASH.js gzip | 501 B | 501 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 255 B | ✓ |
| head-HASH.js gzip | 349 B | 350 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.6 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 309 B | N/A |
| script-HASH.js gzip | 384 B | 384 B | ✓ |
| withRouter-HASH.js gzip | 307 B | 306 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-13-fix_action_revalidation_within_a_parallel_slot | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-13-fix_action_revalidation_within_a_parallel_slot | Change |
| - | - | - | - |
| index.html gzip | 529 B | 526 B | N/A |
| link.html gzip | 543 B | 539 B | N/A |
| withRouter.html gzip | 524 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-13-fix_action_revalidation_within_a_parallel_slot | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.7 kB | 93.7 kB | N/A |
| page.js gzip | 146 kB | 146 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-13-fix_action_revalidation_within_a_parallel_slot | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 626 B | 622 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-13-fix_action_revalidation_within_a_parallel_slot | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 94.1 kB | 94.1 kB | ✓ |
| app-page-tur..prod.js gzip | 94.8 kB | 94.8 kB | ✓ |
| app-page-tur..prod.js gzip | 89.4 kB | 89.4 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.7 kB | 88.7 kB | ✓ |
| app-route-ex...dev.js gzip | 24 kB | 24 kB | ✓ |
| app-route-ex..prod.js gzip | 16.6 kB | 16.6 kB | ✓ |
| app-route-tu..prod.js gzip | 16.6 kB | 16.6 kB | ✓ |
| app-route-tu..prod.js gzip | 16.2 kB | 16.2 kB | ✓ |
| app-route.ru...dev.js gzip | 23.4 kB | 23.4 kB | ✓ |
| app-route.ru..prod.js gzip | 16.2 kB | 16.2 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| Overall change | 930 kB | 930 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>170-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 800cc79ab194edb0ba357f7f27d939135cb12ab2

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 800cc79ab194edb0ba357f7f27d939135cb12ab2

`pnpm test-dev test/e2e/app-dir/error-boundary-navigation/index.test.ts` 
- app dir - not found navigation > should be able to navigate to other page from root not-found page

<details>
<summary>Expand output</summary>

  ● app dir - not found navigation › should be able to navigate to other page from root not-found page

    page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('#homepage')
    ============================================================

      417 |     return this.chain(() => {
      418 |       return page
    > 419 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      420 |         .then(async (el) => {
      421 |           // it seems selenium waits longer and tests rely on this behavior
      422 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:419:10)
      at Object.<anonymous> (e2e/app-dir/error-boundary-navigation/index.test.ts:121:5)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: packages/next/src/client/components/router-reducer/reducers/server-action-reducer.ts [hunk 1]
```diff
@@ -220,7 +220,8 @@ export function serverActionReducer(
           // TODO-APP: remove ''
           [''],
           currentTree,
-          treePatch
+          treePatch,
+          true
```
Comment (damian-balas) [inline packages/next/src/client/components/router-reducer/reducers/server-action-reducer.ts:224]: What is `true`? Doesn't this function only take 3 arguments?

File: packages/next/src/client/components/router-reducer/apply-router-state-patch-to-tree.ts [hunk 2]
```diff
@@ -95,12 +105,17 @@ export function applyRouterStatePatchToTree(
...
+      treePatch,
+      applyPatchDefaultSegment
+    )
   } else {
     parallelRoutePatch = applyRouterStatePatchToTree(
       flightSegmentPath.slice(2),
       parallelRoutes[parallelRouteKey],
-      treePatch
+      treePatch,
+      applyPatchDefaultSegment
```
Comment (damian-balas) [inline packages/next/src/client/components/router-reducer/apply-router-state-patch-to-tree.ts:118]: Doesn't this function only take 3 args?

File: packages/next/src/client/components/router-reducer/create-router-cache-key.ts [hunk 3]
```diff
@@ -5,9 +5,17 @@ export function createRouterCacheKey(
   segment: Segment,
   withoutSearchParameters: boolean = false
 ) {
-  return Array.isArray(segment)
-    ? `${segment[0]}|${segment[1]}|${segment[2]}`.toLowerCase()
-    : withoutSearchParameters && segment.startsWith(PAGE_SEGMENT_KEY)
-    ? PAGE_SEGMENT_KEY
-    : segment
+  // if the segment is an array, it means it's a dynamic segment
```
Comment (ztanner) [inline packages/next/src/client/components/router-reducer/create-router-cache-key.ts:8]: No change in behavior to this file, just split it out of a ternary to better annotate with comments

File: packages/next/src/client/components/router-reducer/reducers/server-action-reducer.ts (hunk 1 above)
Comment (feedthejim) [inline packages/next/src/client/components/router-reducer/reducers/server-action-reducer.ts:224]: optional, instead of a boolean param, could we perhaps just split the function into two so that it's more explicit? 

something like eapplyRouterStateRevalidationPatchToTree (but not this)

**Review by feedthejim — APPROVED** [review]
optional nit, otherwise lgtm
