### PR TITLE
fix(31013): add base path to preflight request url

### LINKED ISSUE #31013: HEAD prefetch requests caused by middleware do not respect basePath
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying your application?

next start

### Describe the Bug

When having a basePath in next-config and some middleware then next.js fires HEAD request for link prefetching.
These HEAD request do not respect basePath.

### Expected Behavior

HEAD request respects basePath.

### To Reproduce

repository to reproduce: 
https://github.com/alfrescian/next-middleware-base-path-issue
next-config:`module.exports = {
  basePath: "/my-base"
};`
You'll notice HEAD request go to http://localhost:3000/blend9709 instead of expected http://localhost:3000/my-base/blend9709

### PR DESCRIPTION
**Pull request by hi-ogawa**
Fixes https://github.com/vercel/next.js/issues/31013

My understanding is that there are currently two functions `Router.change` and `Router.prefetch` leading to `Router._preflightRequest` and they pass `options.as` URL differently regarding base path.
In this PR, such difference will be handled in `Router._preflightRequest` to add base path before actually fetching.
Thanks for the review!

P.S.
Since middleware feature is a relatively new, official maintainers might not want external contributions around this area at this stage.
I totally understand such situation, so please let me know if that's the case. I can look for other issues to investigate instead.

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

File: packages/next/shared/lib/router/router.ts [hunk 1]
```diff
@@ -1829,7 +1829,9 @@ export default class Router implements BaseRouter {
     }
 
     const preflight = await this._getPreflightData({
-      preflightHref: options.as,
+      preflightHref: hasBasePath(options.as)
```
Comment (ijjk) [inline packages/next/shared/lib/router/router.ts:1832]: Can we move this to the [prefetch call](https://github.com/vercel/next.js/blob/9fe0fda5b47f690a7d1b40169b0a5a9c58d9c53d/packages/next/shared/lib/router/router.ts#L1700) instead of checking if the basePath was already added?

Comment (hi-ogawa) [reply packages/next/shared/lib/router/router.ts]: Thanks for the suggestion! Now I'm looking it again, indeed that makes more sense.
In the last commit https://github.com/vercel/next.js/pull/31101/commits/3b923bf0a527afae3aec3de4ad4e7c875de14c8d, I updated the code as you suggested.

**Review by ijjk — APPROVED** [review]
Change and added test look good, thanks!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| buildDuration | 22s | 22.5s | ⚠️ +501ms |
| buildDurationCached | 4.5s | 4.5s | -17ms |
| nodeModulesSize | 333 MB | 333 MB | ⚠️ +17 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.956 | 3.843 | -0.11 |
| / avg req/sec | 632 | 650.47 | +18.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.052 | 2.057 | 0 |
| /error-in-render avg req/sec | 1218.39 | 1215.21 | ⚠️ -3.18 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.1 kB | 28.1 kB | ⚠️ +5 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 536 B | 535 B | -1 B |
| withRouter.html gzip | 517 B | 518 B | ⚠️ +1 B |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -5656,7 +5656,7 @@
                             case 24:
                               _ctx.next = 26;
                               return this._preflightRequest({
-                                as: asPath,
+                                as: addBasePath(asPath),
                                 cache: true,
                                 pages: pages,
                                 pathname: pathname,
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f78d3bf7c627c9d4.js"
+      src="/_next/static/chunks/main-10789f4ca49986c9.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f78d3bf7c627c9d4.js"
+      src="/_next/static/chunks/main-10789f4ca49986c9.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f78d3bf7c627c9d4.js"
+      src="/_next/static/chunks/main-10789f4ca49986c9.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| buildDuration | 24s | 23.9s | -101ms |
| buildDurationCached | 4.3s | 4.5s | ⚠️ +189ms |
| nodeModulesSize | 333 MB | 333 MB | ⚠️ +17 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.874 | 3.88 | ⚠️ +0.01 |
| / avg req/sec | 645.4 | 644.41 | ⚠️ -0.99 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.078 | 2.003 | -0.07 |
| /error-in-render avg req/sec | 1202.85 | 1248.22 | +45.37 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ⚠️ +1 B |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| index.html gzip | 524 B | 523 B | -1 B |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 517 B | 516 B | -1 B |
| Overall change | 1.58 kB | 1.57 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -5656,7 +5656,7 @@
                             case 24:
                               _ctx.next = 26;
                               return this._preflightRequest({
-                                as: asPath,
+                                as: addBasePath(asPath),
                                 cache: true,
                                 pages: pages,
                                 pathname: pathname,
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f78d3bf7c627c9d4.js"
+      src="/_next/static/chunks/main-10789f4ca49986c9.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f78d3bf7c627c9d4.js"
+      src="/_next/static/chunks/main-10789f4ca49986c9.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f78d3bf7c627c9d4.js"
+      src="/_next/static/chunks/main-10789f4ca49986c9.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 4c90caace4fd8329875c60aa10a11e894da0d2d9

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| buildDuration | 25.4s | 25s | -317ms |
| buildDurationCached | 5.1s | 4.9s | -115ms |
| nodeModulesSize | 333 MB | 333 MB | ⚠️ +21 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.186 | 4.155 | -0.03 |
| / avg req/sec | 597.28 | 601.68 | +4.4 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.175 | 2.101 | -0.07 |
| /error-in-render avg req/sec | 1149.32 | 1189.93 | +40.61 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.1 kB | 28.1 kB | ⚠️ +5 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 536 B | 535 B | -1 B |
| withRouter.html gzip | 517 B | 518 B | ⚠️ +1 B |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -5656,7 +5656,7 @@
                             case 24:
                               _ctx.next = 26;
                               return this._preflightRequest({
-                                as: asPath,
+                                as: addBasePath(asPath),
                                 cache: true,
                                 pages: pages,
                                 pathname: pathname,
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f78d3bf7c627c9d4.js"
+      src="/_next/static/chunks/main-10789f4ca49986c9.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f78d3bf7c627c9d4.js"
+      src="/_next/static/chunks/main-10789f4ca49986c9.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f78d3bf7c627c9d4.js"
+      src="/_next/static/chunks/main-10789f4ca49986c9.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| buildDuration | 26.9s | 27.1s | ⚠️ +145ms |
| buildDurationCached | 5s | 5s | -73ms |
| nodeModulesSize | 333 MB | 333 MB | ⚠️ +21 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.271 | 4.211 | -0.06 |
| / avg req/sec | 585.41 | 593.68 | +8.27 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.117 | 2.191 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1180.65 | 1141.09 | ⚠️ -39.56 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ⚠️ +1 B |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 31013-add-base-path-to-preflight-middleware-request | Change |
| - | - | - | - |
| index.html gzip | 524 B | 523 B | -1 B |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 517 B | 516 B | -1 B |
| Overall change | 1.58 kB | 1.57 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -5656,7 +5656,7 @@
                             case 24:
                               _ctx.next = 26;
                               return this._preflightRequest({
-                                as: asPath,
+                                as: addBasePath(asPath),
                                 cache: true,
                                 pages: pages,
                                 pathname: pathname,
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f78d3bf7c627c9d4.js"
+      src="/_next/static/chunks/main-10789f4ca49986c9.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f78d3bf7c627c9d4.js"
+      src="/_next/static/chunks/main-10789f4ca49986c9.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f78d3bf7c627c9d4.js"
+      src="/_next/static/chunks/main-10789f4ca49986c9.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 15db3aac3641e9fd6929071c12e6e96a035f9ce4
