### PR TITLE
chore(examples): Fix for destroy is not a function error

### LINKED ISSUE #47393: Stripe checkout  return generates an error - destroy is not a function
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

with-stripe-typescript

### What browser are you using? (if relevant)

FireFox 111.0

### How are you deploying your application? (if relevant)

Running on local MacBook

### Describe the Bug

On completing the stripe test payment using the checkout form, the page returns the error .
Unhandled Runtime Error

TypeError: destroy is not a function

The browser log has:
`Uncaught TypeError: destroy is not a function
    React 15
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    EventHandlerNonNull* scheduler.development.js:571
    <anonymous> scheduler.development.js:633
    NextJS 4
    <anonymous> index.js:6
    NextJS 4
    React 2
    NextJS 4
    <anonymous> React
    NextJS 4
    <anonymous> React
    NextJS 4
    <anonymous> index.js:14
    NextJS 4
    <anonymous> next-dev.js:3
    NextJS 7
[react-dom.development.js:22932](webpack://_N_E/node_modules/react-dom/cjs/react-dom.development.js?ac89)
The above error occurred in the <ClearCart> component:`

### Expected Behavior

I would expect the page to  confirm payments and clear any cart

### To Reproduce

Download  the example and setup as per the ReadMe document and  then run with `npm run dev`.
Select the checkout example with the default payment of $1000 and complete the card information.
On press the pay button, the error is returned

### PR DESCRIPTION
**Pull request by heyitsuzair**
Fixes #47393

### CODE REVIEW

**Review by balazsorban44 — DISMISSED** [review]

**Review by styfle — DISMISSED** [review]
Thanks!

File: examples/with-stripe-typescript/components/ClearCart.tsx [hunk 1]
```diff
@@ -4,7 +4,10 @@ import { useShoppingCart } from 'use-shopping-cart'
 export default function ClearCart() {
   const { clearCart } = useShoppingCart()
 
-  useEffect(() => clearCart(), [clearCart])
+  useEffect(() => {
+    clearCart()
+    return () => {}
```
Comment (styfle) [inline examples/with-stripe-typescript/components/ClearCart.tsx:9]: You shouldn't need to return anything

Comment (heyitsuzair) [reply examples/with-stripe-typescript/components/ClearCart.tsx:9]: Without return it was throwing an error "destroy is not a function".

**Review by styfle — APPROVED** [review]

**Review by balazsorban44 — APPROVED** [review]
