### PR TITLE
fix: update broken links in config-shared.d.ts

### LINKED ISSUE #74121: Docs: broken links in config-shared.d.ts
### What is the documentation issue?

Links beginning with `"https://nextjs.org/docs/api-reference/next.config.js"` are broken in https://github.com/vercel/next.js/blob/canary/packages/next/src/server/config-shared.ts#L616.

### Is there any context that might help us understand?

Here's an example link from the file (https://github.com/vercel/next.js/blob/canary/packages/next/src/server/config-shared.ts#L616):
https://nextjs.org/docs/api-reference/next.config.js/introduction

image

### Does the docs page already exist? Please link to it.

_No response_

### PR DESCRIPTION
**Pull request by yongholeeme**
Links beginning with `"https://nextjs.org/docs/api-reference/next.config.js"` are broken in https://github.com/vercel/next.js/blob/canary/packages/next/src/server/config-shared.ts#L616. 

And I found other broken links with same problems and fixed those. [09ff492](https://github.com/vercel/next.js/pull/74122/commits/09ff49228beae98107e2da1e7eb40aa4cfcebde1)

close https://github.com/vercel/next.js/issues/74121

### CODE REVIEW

**Comment by yongholeeme** [comment]
@ijjk , could you review this pr?

**Review by ijjk — APPROVED** [review]

**Comment by yongholeeme** [comment]
@ijjk Thank you

File: packages/next/src/server/config-shared.ts [hunk 1]
```diff
@@ -703,22 +703,22 @@ export interface NextConfig extends Record<string, any> {
   /**
```
Comment (jophy-ye) [inline packages/next/src/server/config-shared.ts:703]: @yongholeeme Wow thank you. I spotted this error several weeks ago and always intended to fix it in a PR, but you got it in earlier haha! The URL on Moment.js on line 699 still appears to be incorrect, although not broken.🤔
