### PR TITLE
Fixes #32338 missing Document components trigger an error for production builds

### LINKED ISSUE #32278: Unable to build intentional Dirty AMP page
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### How are you deploying your application?

next

### Describe the Bug

The following fixes have been made in 12.0.5.

https://github.com/vercel/next.js/pull/31505

This changed the warning to an error if the required components does not exist in `_document.tsx`.

Next.js supports AMP.
AMP also supports Invalid (dirty) AMP, like AMP Bento.

Even with Invalid AMP, we want to apply AMP validation and AMP optimization.

This could easily be achieved by changing `Html` to` html`.
This method is also introduced here (https://youtu.be/S_UttIYzKtM?t=736).

However, v12.0.5 causes an error.

Would you please take one of the following measures?

- Change error to warning (revert PR)
- Exclude `Html` from the target (https://github.com/vercel/next.js/blob/9bcf678e646fea8340a8d9c72094c6c624d71668/packages/next/server/render.tsx#L1311)
- Allows us to overwrite customized props for `Html` later (https://github.com/vercel/next.js/blob/canary/packages/next/pages/_document.tsx#L198)

### Expected Behavior

It should be able to build the next project even if Html is html.

### To Reproduce

To use html instead of Html in amp valid page (`export const config = {amp: true}`).

### LINKED ISSUE #32338: Make missing Document components trigger an error for production builds
### What version of Next.js are you using?

12.05 and above

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Other platform

### Describe the Bug

When the user is a bot we only want to serve a plain version of the page without any javascript, but since version 12.05 if we do not include NextScript it triggers a 500 Server error.

### Expected Behavior

If we do not include NextScript it should render a version without javascripts, since [this PR](https://github.com/vercel/next.js/pull/31505) was merged we can not do it anymore. As far as I knew, requiring NextScripts for dev environments made total sense because it could not work without javascript in the client side, but in production we have cases where we do not want to send any javascript to the user and the page should be a plain html. 
In the mentioned PR, the production check was removed.

### To Reproduce

- Remove NextScript from a custom _document.js
- Requesting any page will trigger a 500 error NextScript must be present.

### PR DESCRIPTION
**Pull request by oriolcp**
Fixes #32338

## Bug

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

File: packages/next/server/render.tsx [hunk 1]
```diff
@@ -1307,25 +1307,27 @@ export async function renderToHTML(
...
-      `Your custom Document (pages/_document) did not render all the required subcomponent${plural}.\n` +
-        `Missing component${plural}: ${missingComponentList}\n` +
-        'Read how to fix here: https://nextjs.org/docs/messages/missing-document-component'
-    )
+    if (nonRenderedComponents.length) {
+      const missingComponentList = nonRenderedComponents
+        .map((e) => `<${e} />`)
+        .join(', ')
+      const plural = nonRenderedComponents.length !== 1 ? 's' : ''
+      throw new Error(
```
Comment (balazsorban44) [inline packages/next/server/render.tsx:1325]: We should use `warn` instead of throwing an `Error`. It would crash in development but would be fine in production. That might be confusing.

**Review by balazsorban44 — DISMISSED** [review]

**Comment by balazsorban44** [comment]
Fixes #32278

**Review by devknoll — APPROVED** [review]

File: packages/next/server/render.tsx (hunk 1 above)
Comment (oriolcp) [reply packages/next/server/render.tsx]: @balazsorban44 I've already fixed what you mentioned, let me know if it's ok and I will proceed with the PR.

thanks in advance.

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| buildDuration | 23.8s | 22.3s | -1.5s |
| buildDurationCached | 4.1s | 4.2s | ⚠️ +68ms |
| nodeModulesSize | 350 MB | 350 MB | ⚠️ +192 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.899 | 3.92 | ⚠️ +0.02 |
| / avg req/sec | 641.27 | 637.75 | ⚠️ -3.52 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.95 | 2.01 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1281.86 | 1244.09 | ⚠️ -37.77 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 30.2 kB | 30.2 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 74 kB | 74 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.39 kB | 2.39 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.73 kB | 4.73 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.13 kB | 2.13 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| buildDuration | 23.7s | 24.9s | ⚠️ +1.2s |
| buildDurationCached | 3.9s | 4.2s | ⚠️ +345ms |
| nodeModulesSize | 350 MB | 350 MB | ⚠️ +192 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.649 | 3.586 | -0.06 |
| / avg req/sec | 685.03 | 697.12 | +12.09 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.965 | 1.861 | -0.1 |
| /error-in-render avg req/sec | 1272.02 | 1343.68 | +71.66 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 30.3 kB | 30.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 74.2 kB | 74.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.39 kB | 2.39 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 906 B | 906 B | ✓ |
| image-HASH.js gzip | 4.75 kB | 4.75 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | oriolcp/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 7e1f3f438f1136fa50a76194b2209b9f889df35f
