### PR TITLE
Fix leaking internal config to user-defined `loader` prop in `next/image`

### LINKED ISSUE #35115: The `config` arg should not be passed to user-defined `loader` function in `next/image
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:        
      Platform: win32        
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 14.17.6
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:       
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2    

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

The bug for next.config.js not considered for node_modeles was discussed here: [https://github.com/vercel/next.js/issues/31065](url)

**Fixed in PR**:[https://github.com/vercel/next.js/pull/33559](url)

After the above fix when trying to build the next app the `config` argument passed in the custom loader function resolves to the default next variables.

### Expected Behavior

The config argument in the loader function should return the variables configured in the next.config.js coming from the node_modules when trying to build the app statically.

### To Reproduce

1) Create the next app
2) The app should use a next.config.js for the 3rd party packages inside node_modules that import next/image(which uses a custom loader function).
3) Build the app `next build`

The config argument in the loader function returns default next.config variables set by vercel.

### PR DESCRIPTION
**Pull request by styfle**
The `config` was changed from a global variable to a function parameter of the `loader()` function in PR https://github.com/vercel/next.js/pull/33559 as an implementation detail, not as a public API. It was not meant to be used by the end user which is why it was [undocumented](https://nextjs.org/docs/api-reference/next/image#loader).

This config is meant for the default Image Optimization API. Since the `loader` prop bypasses the default Image Optimization API in favor of a custom function, that config is no longer be relevant because the function can implement the optimization url however it desires.

- Fixes #35115

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: e46a97ba4299f8b37fcdb2b3608f5ab5056f0996

`yarn testheadless test/integration/image-component/basic/test/index.test.js` 
- Image Component Tests > SSR Image Component Tests > should automatically load images if observer does not exist

<details>
<summary>Expand output</summary>

  ● Image Component Tests › SSR Image Component Tests › should automatically load images if observer does not exist

    expect(received).toBe(expected) // Object.is equality

    Expected: "https://example.vercel.sh/success/foo.jpg?width=300"
    Received: "https://example.vercel.sh/error-unexpected-config"

      322 |       expect(
      323 |         await browser.elementById('loader-prop-img').getAttribute('src')
    > 324 |       ).toBe('https://example.vercel.sh/success/foo.jpg?width=300')
          |         ^
      325 |       expect(
      326 |         await browser.elementById('lazy-no-observer').getAttribute('srcset')
      327 |       ).toBe(

      at Object.<anonymous> (integration/image-component/basic/test/index.test.js:324:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| buildDuration | 15.8s | 15.6s | -149ms |
| buildDurationCached | 6.2s | 6.1s | -70ms |
| nodeModulesSize | 478 MB | 478 MB | ⚠️ +779 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.234 | 3.236 | 0 |
| / avg req/sec | 773.01 | 772.59 | ⚠️ -0.42 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.358 | 1.377 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1840.84 | 1815.11 | ⚠️ -25.73 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.7 kB | 71.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.64 kB | 5.67 kB | ⚠️ +27 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ⚠️ +27 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-96a5d6ed07cf5a83.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-9dfe734f583d4926.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f39504b2095f9b7d.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-131c82cedf7dda3b.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-a72b8ab130103a8f.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-cb15c8ac2322bf32.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -155,8 +155,6 @@
           objectPosition = _param.objectPosition,
           onLoadingComplete = _param.onLoadingComplete,
           onError = _param.onError,
-          _loader = _param.loader,
-          loader = _loader === void 0 ? defaultImageLoader : _loader,
           _placeholder = _param.placeholder,
           placeholder = _placeholder === void 0 ? "empty" : _placeholder,
           blurDataURL = _param.blurDataURL,
@@ -177,7 +175,6 @@
             "objectPosition",
             "onLoadingComplete",
             "onError",
-            "loader",
             "placeholder",
             "blurDataURL"
           ]);
@@ -208,8 +205,20 @@
         if ("layout" in rest) {
           // Override default layout if the user specified one:
           if (rest.layout) layout = rest.layout;
-          // Remove property so it's not spread into image:
-          delete rest["layout"];
+          // Remove property so it's not spread on <img>:
+          delete rest.layout;
+        }
+        var loader = defaultImageLoader;
+        if ("loader" in rest && rest.loader) {
+          var customImageLoader = rest.loader;
+          loader = function(obj) {
+            // The config object is internal only so we must
+            // delete before invoking the user-defined loader()
+            delete obj.config;
+            return customImageLoader(obj);
+          };
+          // Remove property so it's not spread on <img>
+          delete rest.loader;
         }
         var staticSrc = "";
         if (isStaticImport(src)) {
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| buildDuration | 18.7s | 18.5s | -186ms |
| buildDurationCached | 6.2s | 6.1s | -39ms |
| nodeModulesSize | 478 MB | 478 MB | ⚠️ +779 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.244 | 3.235 | -0.01 |
| / avg req/sec | 770.54 | 772.9 | +2.36 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.407 | 1.376 | -0.03 |
| /error-in-render avg req/sec | 1777.09 | 1816.88 | +39.79 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.7 kB | 5.73 kB | ⚠️ +29 B |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 16 kB | ⚠️ +29 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-96a5d6ed07cf5a83.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-9dfe734f583d4926.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f39504b2095f9b7d.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-131c82cedf7dda3b.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-a72b8ab130103a8f.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-cb15c8ac2322bf32.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -155,8 +155,6 @@
           objectPosition = _param.objectPosition,
           onLoadingComplete = _param.onLoadingComplete,
           onError = _param.onError,
-          _loader = _param.loader,
-          loader = _loader === void 0 ? defaultImageLoader : _loader,
           _placeholder = _param.placeholder,
           placeholder = _placeholder === void 0 ? "empty" : _placeholder,
           blurDataURL = _param.blurDataURL,
@@ -177,7 +175,6 @@
             "objectPosition",
             "onLoadingComplete",
             "onError",
-            "loader",
             "placeholder",
             "blurDataURL"
           ]);
@@ -208,8 +205,20 @@
         if ("layout" in rest) {
           // Override default layout if the user specified one:
           if (rest.layout) layout = rest.layout;
-          // Remove property so it's not spread into image:
-          delete rest["layout"];
+          // Remove property so it's not spread on <img>:
+          delete rest.layout;
+        }
+        var loader = defaultImageLoader;
+        if ("loader" in rest && rest.loader) {
+          var customImageLoader = rest.loader;
+          loader = function(obj) {
+            // The config object is internal only so we must
+            // delete before invoking the user-defined loader()
+            delete obj.config;
+            return customImageLoader(obj);
+          };
+          // Remove property so it's not spread on <img>
+          delete rest.loader;
         }
         var staticSrc = "";
         if (isStaticImport(src)) {
```
</details>
</details>
Commit: e46a97ba4299f8b37fcdb2b3608f5ab5056f0996

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 37f8f178567ebf237cc14de24fcc6fbec3b6a7f5

`yarn testheadless test/integration/export-image-loader/test/index.test.js` 
- Export with cloudinary loader next/image component > should build successfully
- Export with cloudinary loader next/image component > should export successfully
- Export with cloudinary loader next/image component > should contain img element in html output

<details>
<summary>Expand output</summary>

  ● Export with cloudinary loader next/image component › should build successfully

    command failed with code 1
    warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
    info  - Checking validity of types...
    warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
    info  - Creating an optimized production build...
    info  - Using locally built binary of @next/swc
    info  - Compiled successfully
    info  - Collecting page data...
    info  - Generating static pages (0/3)
    TypeError: loader is not a function

      at integration/export-image-loader/.next/server/pages/index.js:501:39
          at Array.map (<anonymous>)
      at generateImgAttrs (integration/export-image-loader/.next/server/pages/index.js:501:24)
      at ImageElement (integration/export-image-loader/.next/server/pages/index.js:630:183)
      at Hc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:64:191)
      at Kc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:253)
      at Z (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
      at Lc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
      at Nc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:72:306)
      at Z (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:217)
      Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
      TypeError: loader is not a function
      at integration/export-image-loader/.next/server/pages/index.js:501:39
          at Array.map (<anonymous>)
      at generateImgAttrs (integration/export-image-loader/.next/server/pages/index.js:501:24)
      at ImageElement (integration/export-image-loader/.next/server/pages/index.js:630:183)
      at Hc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:64:191)
      at Kc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:253)
      at Z (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
      at Lc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
      at Nc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:72:306)
      at Z (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:217)
      info  - Generating static pages (3/3)
      > Build error occurred
      Error: Export encountered errors on following paths:
      	/
      at ../packages/next/dist/export/index.js:397:19
          at runMicrotasks (<anonymous>)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:79:20)
      at ../async /home/runner/work/next.js/next.js/packages/next/dist/build/index.js:1010:17
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:79:20)
      at ../async /home/runner/work/next.js/next.js/packages/next/dist/build/index.js:886:13
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:79:20)
      at async Object.build [as default] (../packages/next/dist/build/index.js:55:25)
      at ChildProcess.<anonymous> (lib/next-test-utils.js:205:11)

  ● Export with cloudinary loader next/image component › should export successfully

    command failed with code 1
    info  - using build directory: /home/runner/work/next.js/next.js/test/integration/export-image-loader/.next
    info  - Copying "static build" directory
    info  - No "exportPathMap" found in "/home/runner/work/next.js/next.js/test/integration/export-image-loader/next.config.js". Generating map from "./pages"
    info  - Launching 1 workers
    info  - Exporting (0/3)
    TypeError: loader is not a function

      at integration/export-image-loader/.next/server/pages/index.js:501:39
          at Array.map (<anonymous>)
      at generateImgAttrs (integration/export-image-loader/.next/server/pages/index.js:501:24)
      at ImageElement (integration/export-image-loader/.next/server/pages/index.js:630:183)
      at Hc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:64:191)
      at Kc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:253)
      at Z (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
      at Lc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
      at Nc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:72:306)
      at Z (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:217)
      Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
      TypeError: loader is not a function
      at integration/export-image-loader/.next/server/pages/index.js:501:39
          at Array.map (<anonymous>)
      at generateImgAttrs (integration/export-image-loader/.next/server/pages/index.js:501:24)
      at ImageElement (integration/export-image-loader/.next/server/pages/index.js:630:183)
      at Hc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:64:191)
      at Kc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:253)
      at Z (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
      at Lc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
      at Nc (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:72:306)
      at Z (../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:217)
      info  - Exporting (3/3)
      Error: Export encountered errors on following paths:
      	/
      at ../packages/next/dist/export/index.js:397:19
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:79:20)
      at ChildProcess.<anonymous> (lib/next-test-utils.js:205:11)

  ● Export with cloudinary loader next/image component › should contain img element in html output

    ENOENT: no such file or directory, open '/home/runner/work/next.js/next.js/test/integration/export-image-loader/out/index.html'



</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| buildDuration | 15.9s | 16.1s | ⚠️ +227ms |
| buildDurationCached | 6.2s | 6.2s | ⚠️ +4ms |
| nodeModulesSize | 478 MB | 478 MB | ⚠️ +779 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.302 | 3.269 | -0.03 |
| / avg req/sec | 757.21 | 764.76 | +7.55 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.398 | 1.378 | -0.02 |
| /error-in-render avg req/sec | 1788.73 | 1814.17 | +25.44 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.7 kB | 71.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.64 kB | 5.67 kB | ⚠️ +27 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ⚠️ +27 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-96a5d6ed07cf5a83.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-9dfe734f583d4926.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f39504b2095f9b7d.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-131c82cedf7dda3b.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-a72b8ab130103a8f.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-cb15c8ac2322bf32.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -155,8 +155,6 @@
           objectPosition = _param.objectPosition,
           onLoadingComplete = _param.onLoadingComplete,
           onError = _param.onError,
-          _loader = _param.loader,
-          loader = _loader === void 0 ? defaultImageLoader : _loader,
           _placeholder = _param.placeholder,
           placeholder = _placeholder === void 0 ? "empty" : _placeholder,
           blurDataURL = _param.blurDataURL,
@@ -177,7 +175,6 @@
             "objectPosition",
             "onLoadingComplete",
             "onError",
-            "loader",
             "placeholder",
             "blurDataURL"
           ]);
@@ -208,8 +205,20 @@
         if ("layout" in rest) {
           // Override default layout if the user specified one:
           if (rest.layout) layout = rest.layout;
-          // Remove property so it's not spread into image:
-          delete rest["layout"];
+          // Remove property so it's not spread on <img>:
+          delete rest.layout;
+        }
+        var loader = defaultImageLoader;
+        if ("loader" in rest && rest.loader) {
+          var customImageLoader = rest.loader;
+          loader = function(obj) {
+            // The config object is internal only so we must
+            // delete before invoking the user-defined loader()
+            delete obj.config;
+            return customImageLoader(obj);
+          };
+          // Remove property so it's not spread on <img>
+          delete rest.loader;
         }
         var staticSrc = "";
         if (isStaticImport(src)) {
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| buildDuration | 18.1s | 18.7s | ⚠️ +616ms |
| buildDurationCached | 6.2s | 5.8s | -346ms |
| nodeModulesSize | 478 MB | 478 MB | ⚠️ +779 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.231 | 3.301 | ⚠️ +0.07 |
| / avg req/sec | 773.73 | 757.31 | ⚠️ -16.42 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.369 | 1.391 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1825.89 | 1796.88 | ⚠️ -29.01 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.7 kB | 5.73 kB | ⚠️ +29 B |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 16 kB | ⚠️ +29 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-96a5d6ed07cf5a83.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-9dfe734f583d4926.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f39504b2095f9b7d.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-131c82cedf7dda3b.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-a72b8ab130103a8f.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-cb15c8ac2322bf32.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -155,8 +155,6 @@
           objectPosition = _param.objectPosition,
           onLoadingComplete = _param.onLoadingComplete,
           onError = _param.onError,
-          _loader = _param.loader,
-          loader = _loader === void 0 ? defaultImageLoader : _loader,
           _placeholder = _param.placeholder,
           placeholder = _placeholder === void 0 ? "empty" : _placeholder,
           blurDataURL = _param.blurDataURL,
@@ -177,7 +175,6 @@
             "objectPosition",
             "onLoadingComplete",
             "onError",
-            "loader",
             "placeholder",
             "blurDataURL"
           ]);
@@ -208,8 +205,20 @@
         if ("layout" in rest) {
           // Override default layout if the user specified one:
           if (rest.layout) layout = rest.layout;
-          // Remove property so it's not spread into image:
-          delete rest["layout"];
+          // Remove property so it's not spread on <img>:
+          delete rest.layout;
+        }
+        var loader = defaultImageLoader;
+        if ("loader" in rest && rest.loader) {
+          var customImageLoader = rest.loader;
+          loader = function(obj) {
+            // The config object is internal only so we must
+            // delete before invoking the user-defined loader()
+            delete obj.config;
+            return customImageLoader(obj);
+          };
+          // Remove property so it's not spread on <img>
+          delete rest.loader;
         }
         var staticSrc = "";
         if (isStaticImport(src)) {
```
</details>
</details>
Commit: 37f8f178567ebf237cc14de24fcc6fbec3b6a7f5

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 998b3af49d72813425fe3036f046cac7ceab8338

`yarn testheadless test/integration/image-component/basic/test/index.test.js` 
- Image Component Tests > SSR Image Component Tests > should automatically load images if observer does not exist

<details>
<summary>Expand output</summary>

  ● Image Component Tests › SSR Image Component Tests › should automatically load images if observer does not exist

    expect(received).toBe(expected) // Object.is equality

    Expected: "https://example.vercel.sh/success/foo.jpg?width=300"
    Received: "https://example.vercel.sh/success/foo.jpg?width=1024"

      322 |       expect(
      323 |         await browser.elementById('loader-prop-img').getAttribute('src')
    > 324 |       ).toBe('https://example.vercel.sh/success/foo.jpg?width=300')
          |         ^
      325 |       expect(
      326 |         await browser.elementById('lazy-no-observer').getAttribute('srcset')
      327 |       ).toBe(

      at Object.<anonymous> (integration/image-component/basic/test/index.test.js:324:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| buildDuration | 15.3s | 15.1s | -174ms |
| buildDurationCached | 6.1s | 6s | -62ms |
| nodeModulesSize | 478 MB | 478 MB | ⚠️ +864 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.987 | 3.004 | ⚠️ +0.02 |
| / avg req/sec | 836.84 | 832.22 | ⚠️ -4.62 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.152 | 1.139 | -0.01 |
| /error-in-render avg req/sec | 2170.9 | 2195.33 | +24.43 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.7 kB | 71.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.64 kB | 5.67 kB | ⚠️ +30 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ⚠️ +30 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-96a5d6ed07cf5a83.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-9dfe734f583d4926.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f39504b2095f9b7d.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-9a9ba258e19d2cd4.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-a72b8ab130103a8f.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-cb15c8ac2322bf32.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -155,8 +155,6 @@
           objectPosition = _param.objectPosition,
           onLoadingComplete = _param.onLoadingComplete,
           onError = _param.onError,
-          _loader = _param.loader,
-          loader = _loader === void 0 ? defaultImageLoader : _loader,
           _placeholder = _param.placeholder,
           placeholder = _placeholder === void 0 ? "empty" : _placeholder,
           blurDataURL = _param.blurDataURL,
@@ -177,7 +175,6 @@
             "objectPosition",
             "onLoadingComplete",
             "onError",
-            "loader",
             "placeholder",
             "blurDataURL"
           ]);
@@ -208,8 +205,22 @@
         if ("layout" in rest) {
           // Override default layout if the user specified one:
           if (rest.layout) layout = rest.layout;
-          // Remove property so it's not spread into image:
-          delete rest["layout"];
+          // Remove property so it's not spread on <img>:
+          delete rest.layout;
+        }
+        var loader = defaultImageLoader;
+        if ("loader" in rest) {
+          if (rest.loader) {
+            var customImageLoader = rest.loader;
+            loader = function(obj) {
+              // The config object is internal only so we must
+              // delete before invoking the user-defined loader()
+              delete obj.config;
+              return customImageLoader(obj);
+            };
+          }
+          // Remove property so it's not spread on <img>
+          delete rest.loader;
         }
         var staticSrc = "";
         if (isStaticImport(src)) {
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| buildDuration | 17.8s | 17.8s | -16ms |
| buildDurationCached | 6.1s | 6s | -190ms |
| nodeModulesSize | 478 MB | 478 MB | ⚠️ +864 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.989 | 3.026 | ⚠️ +0.04 |
| / avg req/sec | 836.33 | 826.09 | ⚠️ -10.24 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.175 | 1.159 | -0.02 |
| /error-in-render avg req/sec | 2128.47 | 2157.44 | +28.97 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.7 kB | 5.73 kB | ⚠️ +31 B |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 16 kB | ⚠️ +31 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-96a5d6ed07cf5a83.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-9dfe734f583d4926.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f39504b2095f9b7d.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-9a9ba258e19d2cd4.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-a72b8ab130103a8f.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-cb15c8ac2322bf32.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -155,8 +155,6 @@
           objectPosition = _param.objectPosition,
           onLoadingComplete = _param.onLoadingComplete,
           onError = _param.onError,
-          _loader = _param.loader,
-          loader = _loader === void 0 ? defaultImageLoader : _loader,
           _placeholder = _param.placeholder,
           placeholder = _placeholder === void 0 ? "empty" : _placeholder,
           blurDataURL = _param.blurDataURL,
@@ -177,7 +175,6 @@
             "objectPosition",
             "onLoadingComplete",
             "onError",
-            "loader",
             "placeholder",
             "blurDataURL"
           ]);
@@ -208,8 +205,22 @@
         if ("layout" in rest) {
           // Override default layout if the user specified one:
           if (rest.layout) layout = rest.layout;
-          // Remove property so it's not spread into image:
-          delete rest["layout"];
+          // Remove property so it's not spread on <img>:
+          delete rest.layout;
+        }
+        var loader = defaultImageLoader;
+        if ("loader" in rest) {
+          if (rest.loader) {
+            var customImageLoader = rest.loader;
+            loader = function(obj) {
+              // The config object is internal only so we must
+              // delete before invoking the user-defined loader()
+              delete obj.config;
+              return customImageLoader(obj);
+            };
+          }
+          // Remove property so it's not spread on <img>
+          delete rest.loader;
         }
         var staticSrc = "";
         if (isStaticImport(src)) {
```
</details>
</details>
Commit: 998b3af49d72813425fe3036f046cac7ceab8338

File: packages/next/client/image.tsx [hunk 1]
```diff
@@ -40,13 +40,23 @@ type ImageConfig = ImageConfigComplete & { allSizes: number[] }
 export type ImageLoader = (resolverProps: ImageLoaderProps) => string
 
 export type ImageLoaderProps = {
-  config: Readonly<ImageConfig>
+  config?: Readonly<ImageConfig>
```
Comment (ijjk) [inline packages/next/client/image.tsx:43]: Should this be included on the type if it's being exported, would it be better to exclude here and have a separate internal type that has `config`?

Comment (styfle) [reply packages/next/client/image.tsx]: @ijjk Good point! I updated the types in b41388d so this won't be exported 👍

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| buildDuration | 15.2s | 15.1s | -83ms |
| buildDurationCached | 6s | 6s | ⚠️ +76ms |
| nodeModulesSize | 478 MB | 478 MB | ⚠️ +946 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.035 | 3.053 | ⚠️ +0.02 |
| / avg req/sec | 823.74 | 818.91 | ⚠️ -4.83 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.155 | 1.149 | -0.01 |
| /error-in-render avg req/sec | 2165.19 | 2175.89 | +10.7 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.7 kB | 71.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.64 kB | 5.68 kB | ⚠️ +41 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ⚠️ +41 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 460 B | ⚠️ +1 B |
| Overall change | 459 B | 460 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-96a5d6ed07cf5a83.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-9dfe734f583d4926.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f39504b2095f9b7d.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-0e5a6c840e535a1d.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-a72b8ab130103a8f.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-cb15c8ac2322bf32.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -155,8 +155,6 @@
           objectPosition = _param.objectPosition,
           onLoadingComplete = _param.onLoadingComplete,
           onError = _param.onError,
-          _loader = _param.loader,
-          loader = _loader === void 0 ? defaultImageLoader : _loader,
           _placeholder = _param.placeholder,
           placeholder = _placeholder === void 0 ? "empty" : _placeholder,
           blurDataURL = _param.blurDataURL,
@@ -177,7 +175,6 @@
             "objectPosition",
             "onLoadingComplete",
             "onError",
-            "loader",
             "placeholder",
             "blurDataURL"
           ]);
@@ -208,8 +205,26 @@
         if ("layout" in rest) {
           // Override default layout if the user specified one:
           if (rest.layout) layout = rest.layout;
-          // Remove property so it's not spread into image:
-          delete rest["layout"];
+          // Remove property so it's not spread on <img>:
+          delete rest.layout;
+        }
+        var loader = defaultImageLoader;
+        if ("loader" in rest) {
+          if (rest.loader) {
+            var customImageLoader = rest.loader;
+            var _tmp;
+            (_tmp = function(obj) {
+              var _ = obj.config,
+                opts = _objectWithoutProperties(obj, ["config"]);
+              // The config object is internal only so we must
+              // not pass it to the user-defined loader()
+              return customImageLoader(opts);
+            }),
+              (loader = _tmp),
+              _tmp;
+          }
+          // Remove property so it's not spread on <img>
+          delete rest.loader;
         }
         var staticSrc = "";
         if (isStaticImport(src)) {
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| buildDuration | 17.9s | 17.9s | ⚠️ +17ms |
| buildDurationCached | 6s | 6s | ⚠️ +7ms |
| nodeModulesSize | 478 MB | 478 MB | ⚠️ +946 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.024 | 3.035 | ⚠️ +0.01 |
| / avg req/sec | 826.73 | 823.83 | ⚠️ -2.9 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.148 | 1.168 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2178.25 | 2140.71 | ⚠️ -37.54 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.7 kB | 5.74 kB | ⚠️ +35 B |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 16 kB | ⚠️ +35 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-custom-loader-prop-remove-config | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-96a5d6ed07cf5a83.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-9dfe734f583d4926.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f39504b2095f9b7d.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-0e5a6c840e535a1d.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-a72b8ab130103a8f.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-cb15c8ac2322bf32.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -155,8 +155,6 @@
           objectPosition = _param.objectPosition,
           onLoadingComplete = _param.onLoadingComplete,
           onError = _param.onError,
-          _loader = _param.loader,
-          loader = _loader === void 0 ? defaultImageLoader : _loader,
           _placeholder = _param.placeholder,
           placeholder = _placeholder === void 0 ? "empty" : _placeholder,
           blurDataURL = _param.blurDataURL,
@@ -177,7 +175,6 @@
             "objectPosition",
             "onLoadingComplete",
             "onError",
-            "loader",
             "placeholder",
             "blurDataURL"
           ]);
@@ -208,8 +205,26 @@
         if ("layout" in rest) {
           // Override default layout if the user specified one:
           if (rest.layout) layout = rest.layout;
-          // Remove property so it's not spread into image:
-          delete rest["layout"];
+          // Remove property so it's not spread on <img>:
+          delete rest.layout;
+        }
+        var loader = defaultImageLoader;
+        if ("loader" in rest) {
+          if (rest.loader) {
+            var customImageLoader = rest.loader;
+            var _tmp;
+            (_tmp = function(obj) {
+              var _ = obj.config,
+                opts = _objectWithoutProperties(obj, ["config"]);
+              // The config object is internal only so we must
+              // not pass it to the user-defined loader()
+              return customImageLoader(opts);
+            }),
+              (loader = _tmp),
+              _tmp;
+          }
+          // Remove property so it's not spread on <img>
+          delete rest.loader;
         }
         var staticSrc = "";
         if (isStaticImport(src)) {
```
</details>
</details>
Commit: b41388d0662d772575768648d602ab73725f1f7b

**Comment by TheThirdRace** [comment]
This decision costed me 1 hour of refactoring...

**The values in `next.config.js` definitely can be used with a custom loader.**

NextJs image solution consist of 2 distinct parts:

1. the `server` part, which is in charge of optimizing the images and acts as a `SERVICE`
2. the `client` part is in charge of asking the `server` part what it needs and display the image efficiently

There are tons of problems with the `client` part. Problems the community is asking fixes for more than a year...

While a lot of improvements have been done with the `client` part, it still has glaring issues that can warrant a complete replacement of `next/image` as a display solution.

By making `next.config.js` image values private to NextJs, it only makes it more difficult for people to replace `next/image` as a display solution.

It's like NextJs never anticipated that we could use NextJs image optimization service, the `server` part, with a better fitting display solution for our specific needs...

In any case, I just wanted to point out these kind of decisions are not improving flexibility, it just makes it frustrating to work with NextJs Image solution.

**Comment by LZL0** [comment]
next/image desperately lacks out-of-the-box support for modern CSS frameworks like TailwindCSS. We need to use workarounds and define static widths and heights. I feel that instead of assisting the developer, it's just a chore to work with it most of the time.

**Comment by styfle** [comment]
Thanks for the feedback!

Please see my comment https://github.com/vercel/next.js/issues/35115#issuecomment-1086405262 as well as https://github.com/vercel/next.js/issues/35115#issuecomment-1086429207.
