### PR TITLE
Include `AggregateError.errors` in terminal output

### LINKED ISSUE #84464: Logging an `AggregateError` doesn't include the `[errors]` section.
### Link to the code that reproduces this issue

https://github.com/bencmbrook/next-aggregateerror-repro

### To Reproduce

**To reproduce:**

1. Build the app (`next build` / `npm run build`)
2. Start the app (`next start` / `npm run start`)
3. Open [http://localhost:3000/api/log](http://localhost:3000/api/log). 

This will:
- Log to the server logs: `console.error(myAggregateError)` 
- Display on the webpage, the result of `util.inspect(myAggregateError)`

The log and the text on the webpage will both show that the formatted `AggregateError` omits the `[errors]` section of the string.

--------

**To confirm that this is inconsistent with Node's behavior:**

1. In a terminal, open the Node REPL (`node`)
2. Paste this code:

    ```ts   
    const error1 = new Error("Error 1");
    const error2 = new TypeError("Error 2");

    // `AggregateError` doesn't include the `errors` property in the log, even in production. It does in an unpatched Node runtime.
    const myAggregateError = new AggregateError([error1, error2], "Multiple errors:");
    console.error(myAggregateError);

    // This is because the Node's util.inspect is likely patched:
    const formattedAggregateError = util.inspect(myAggregateError);
    const stringified = `This is the formatted AggregateError from util.inspect, missing the \`[errors]\` section:\n\n${formattedAggregateError}`;
    console.log(stringified);
    ```
3. Hit enter, and observe that both `console.error(myAggregateError)` and `console.log(stringified)` produce a string containing the `[errors]` section.

### Current vs. Expected behavior

**Current Behavior:**

`console.error(myAggregateError)` produces:

```
AggregateError: Multiple errors:
    at x (.next/server/app/api/log/route.js:1:1569)
```

**Expected Behavior:**

`console.error(myAggregateError)` should include the `[errors]` section:

```
AggregateError: Multiple errors:
    at x (.next/server/app/api/log/route.js:1:1569) {
  [errors]: [
    Error: Error 1
        at x (.next/server/app/api/log/route.js:1:1569)
    TypeError: Error 2
        at x (.next/server/app/api/log/route.js:1:1588)
  ]
}
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.6.0: Mon Jul 14 11:28:30 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6030
  Available memory (MB): 36864
  Available CPU cores: 12
Binaries:
  Node: 22.18.0
  npm: 10.9.3
  Yarn: 1.22.22
  pnpm: 9.15.4
Relevant Packages:
  next: 15.6.0-canary.39 // Latest available version is detected (15.6.0-canary.39).
  eslint-config-next: N/A
  react: 19.1.1
  react-dom: 19.1.1
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Route Handlers, Error Handling

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed), next start (local)

### Additional context

- It looks like `util.inspect` [is indeed patched by Next.js](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/patch-error-inspect.ts). This is the function that Node uses to serialize Error objects inside `console.log`
- MDN reference on the [`errors` property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError/errors).
- In development (`next dev`), this property is also not shown, but in development it is significantly different already (where it shows the code snippet), so it's already less comparable to expected Node behavior.
- I've tried this in Node 24, 22, 20 and the behavior is the same in each
- In case it's helpful, I've [added](https://github.com/bencmbrook/next-aggregateerror-repro/commit/0e5cc6d5423caa353dc445c6618e29a40a31bc4e) a second test case to confirm that the `cause` property serializes correctly—it appears that it does work, and this bug is isolated to the `errors` property.
  - Same steps as repro, but navigate to [http://localhost:3000/api/with-cause](http://localhost:3000/api/with-cause). This will log:
    ```
    AggregateError: Multiple errors:
        at x (.next/server/app/api/with-cause/route.js:1:671) {
      [cause]: Error: Root error
          at x (.next/server/app/api/with-cause/route.js:1:649)
    }
    ```

    So the `cause` property does serialize correctly, it's just `.errors` that is being omitted.

### PR DESCRIPTION
**Pull request by bencmbrook**
- Fixes https://github.com/vercel/next.js/issues/84464

## Summary

This fixes a bug where Next.js overrides Node's `util.inspect` (to rewrite the stack trace), but that override accidentally omits the `errors` property of an `AggregateError`.

`console.error(myAggregateError)` now includes `[errors]`, matching Node's behavior.

### Changes

1. Special-cased `AggregateError` in the `util.inspect` patch to maintain the `errors` property.
2. Fixed a miscalculation on `depth` in the `util.inspect` patch which caused nested errors in `Error.cause` and `AggregateError.errors` to truncate in weird ways and at the wrong depth.
3. Added unit tests which demonstrate these are now aligned to Node's `util.inspect` behavior.

## Background

When logging an `AggregateError`, it should print an `[errors]` object.

```ts
const error1 = new Error("Error 1");
const error2 = new TypeError("Error 2");
const myAggregateError = new AggregateError([error1, error2], "Multiple errors:");

console.error(myAggregateError);
```

```
AggregateError: Multiple errors:
    at x (.next/server/app/api/log/route.js:1:1569) {
  [errors]: [
    Error: Error 1
        at x (.next/server/app/api/log/route.js:1:1569)
    TypeError: Error 2
        at x (.next/server/app/api/log/route.js:1:1588)
  ]
}
```

However, the `[errors]` object is totally omitted in Next.js production backends today:

```
AggregateError: Multiple errors:
    at x (.next/server/app/api/log/route.js:1:1569)
```

This PR ensures `console.error(myAggregateError)` now includes `[errors]`, matching Node's behavior.

## Are there other omissions like this?

No:

1. `Error.cause` is already special-cased in the patch function.
2. Only `AggregateError` needs this special treatment (and e.g., `TypeError` does not), because `AggregateError` is the only built-in error object that has [its own instance property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError/errors). That property is non-enumerable, so it is not handled by this logic:
    https://github.com/vercel/next.js/blob/f51e3acf961c9bbcab68aab6078c9267d230db21/packages/next/src/server/patch-error-inspect.ts#L465-L471

## Tests

Added unit tests to test for consistency between `util.inspect` and the patched `util.inspect`. The test suite runs twice: once against the original `util.inspect`, and then again for the patched version of `util.inspect`, demonstrating they are consistent (stack trace aside).

<details>

<summary>Unit test results before the bugfix (note that "Original util.inspect" tests pass, meaning the tests are aligned to default Node behavior, and the patch was breaking that behavior)</summary>

```console
$ pnpm jest patch-error-inspect

 FAIL   Turbopack  packages/next/src/server/patch-error-inspect.test.ts
  patch-error-inspect
    Original `util.inspect`
      Regular Error
        ✓ should preserve message formatting for regular Error objects (3 ms)
        ✓ should preserve cause property for regular Error objects (1 ms)
      TypeError
        ✓ should preserve name for TypeError
      Deep Error
        ✓ should collapse deeply nested errors (1 ms)
      AggregateError
        ✓ should preserve errors property when formatting AggregateError with cause (1 ms)
        ✓ should preserve errors property when formatting empty AggregateError
    Patched `util.inspect`
      Regular Error
        ✓ should preserve message formatting for regular Error objects (2 ms)
        ✓ should preserve cause property for regular Error objects (1 ms)
      TypeError
        ✓ should preserve name for TypeError
      Deep Error
        ✕ should collapse deeply nested errors (2 ms)
      AggregateError
        ✕ should preserve errors property when formatting AggregateError with cause (1 ms)
        ✕ should preserve errors property when formatting empty AggregateError

  ● patch-error-inspect › Patched `util.inspect` › Deep Error › should collapse deeply nested errors

    expect(received).toContain(expected) // indexOf

    Expected substring: "[cause]: [Error]"
    Received string:    "Error: Depth 0 error
        at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:101:32)
        at new Promise (<anonymous>) {
      [cause]: Error: Depth 1 error
          at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:98:32)
          at new Promise (<anonymous>) {
        [cause]: Error: Depth 2 error
            at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:95:32)
            at new Promise (<anonymous>) {
          [cause]: Error: Depth 3 error
              at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:92:32)
              at new Promise (<anonymous>) {
            [cause]: Error: Depth 4 error
                at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:91:32)
                at new Promise (<anonymous>)
          }
        }
      }
    }"

    

      at Object.<anonymous> (../packages/next/src/server/patch-error-inspect.test.ts:111:35)

  ● patch-error-inspect › Patched `util.inspect` › AggregateError › should preserve errors property when formatting AggregateError with cause

    expect(received).toContain(expected) // indexOf

    Expected substring: "[errors]:"
    Received string:    "AggregateError: Multiple errors:
        at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:121:40)
        at new Promise (<anonymous>) {
      [cause]: Error: Root error
          at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:120:35)
          at new Promise (<anonymous>)
    }"

    

      at Object.<anonymous> (../packages/next/src/server/patch-error-inspect.test.ts:129:35)

  ● patch-error-inspect › Patched `util.inspect` › AggregateError › should preserve errors property when formatting empty AggregateError

    expect(received).toContain(expected) // indexOf

    Expected substring: "[errors]:"
    Received string:    "AggregateError: No errors
        at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:136:40)
        at new Promise (<anonymous>)"

    

      at Object.<anonymous> (../packages/next/src/server/patch-error-inspect.test.ts:139:35)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 9 passed, 12 total
Snapshots:   0 total
Time:        0.131 s, estimated 1 s
Ran all test suites matching /patch-error-inspect/i.
```

</details>

Closes https://linear.app/vercel/issue/NAR-752/

### CODE REVIEW

File: packages/next/src/server/patch-error-inspect.ts [hunk 1]
```diff
@@ -501,10 +506,7 @@ export function patchErrorInspectNodeJS(
       try {
         return inspect(newError, {
           ...inspectOptions,
-          depth:
-            (inspectOptions.depth ??
-              // Default in Node.js
-              2) - depth,
```
Comment (bencmbrook) [inline packages/next/src/server/patch-error-inspect.ts]: This is another bug affecting both `AggregateError.errors` as well as `Error.cause`. `util.inspect` has a `depth` property which [defaults](https://nodejs.org/api/util.html#utilinspectobject-showhidden-depth-colors) to `2`, but it was being unnecessarily transformed here.

## `Error.cause`

```ts
const depth4 = new Error('Depth 4 error')
const depth3 = new Error('Depth 3 error', { cause: depth4 })
const depth2 = new Error('Depth 2 error', { cause: depth3 })
const depth1 = new Error('Depth 1 error', { cause: depth2 })
const depth0 = new Error('Depth 0 error', { cause: depth1 })
const formatted = util.inspect(depth0)
console.log(formatted);
```

Should print:

```
Error: Depth 0 error
    at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:101:32)
    at new Promise (<anonymous>) {
  [cause]: Error: Depth 1 error
      at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:98:32)
      at new Promise (<anonymous>) {
    [cause]: Error: Depth 2 error
        at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:95:32)
        at new Promise (<anonymous>) {
      [cause]: [Error]
    }
  }
}
```

Note the truncation to `[cause]: [Error]` after depth 2. Instead, it would not respect the `depth: 2` argument for nested `cause` errors:

```
Error: Depth 0 error
    at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:101:32)
    at new Promise (<anonymous>) {
  [cause]: Error: Depth 1 error
      at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:98:32)
      at new Promise (<anonymous>) {
    [cause]: Error: Depth 2 error
        at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:95:32)
        at new Promise (<anonymous>) {
      [cause]: Error: Depth 3 error
          at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:92:32)
          at new Promise (<anonymous>) {
        [cause]: Error: Depth 4 error
            at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:91:32)
            at new Promise (<anonymous>)
      }
    }
  }
}
```

## `AggregateError.errors`

```ts
const error1 = new Error('Error 1')
const error2 = new TypeError('Error 2')
const rootError = new Error('Root error')
const aggregateError = new AggregateError(
  [error1, error2],
  'Multiple errors:',
  { cause: rootError }
)
const formatted = util.inspect(aggregateError)
console.log(formatted)
```

Should print:

```
AggregateError: Multiple errors:
    at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:121:40)
    at new Promise (<anonymous>) {
    [cause]: Error: Root error
        at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:120:35)
        at new Promise (<anonymous>),
    [errors]: [
    Error: Error 1
        at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:118:32)
        at new Promise (<anonymous>),
    TypeError: Error 2
        at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:119:32)
        at new Promise (<anonymous>)
    ]
}
```

But in actuality, it would immediately truncate:

```
AggregateError: Multiple errors:
    at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:121:40)
    at new Promise (<anonymous>) {
  [cause]: Error: Root error
      at Object.<anonymous> (packages/next/src/server/patch-error-inspect.test.ts:120:35)
      at new Promise (<anonymous>),
  [errors]: [Array]
}
```

This fix resolves both cases to match the expected behaviors.

File: packages/next/src/server/patch-error-inspect.test.ts
Comment (eps1lon) [inline packages/next/src/server/patch-error-inspect.test.ts:1]: @cursor This should be moved to an e2e test in `test/e2e/app-dir/server-source-maps/server-source-maps.test.ts`

File: packages/next/src/server/patch-error-inspect.ts (hunk 1 above)
Comment (eps1lon) [reply packages/next/src/server/patch-error-inspect.ts]: Please file a separate PR for this.

**Review by eps1lon — COMMENTED** [review]
Appreciate the work. Let's make sure we don't multiple fixes into a single PR. Hopefully cursor can move the unit test into an e2e test. If it fails, could you take care of that?

File: packages/next/src/server/patch-error-inspect.ts (hunk 1 above)
Comment (eps1lon) [reply packages/next/src/server/patch-error-inspect.ts]: @cursor extract this into a separate PR

Comment (eps1lon) [reply packages/next/src/server/patch-error-inspect.ts]: @cursor rebase the PR

File: test/e2e/app-dir/server-source-maps/server-source-maps.test.ts [hunk 2]
```diff
@@ -126,6 +126,57 @@ describe('app-dir - server source maps', () => {
...
+          '\n  [cause]: Error: Root error' +
+          '\n      at logError (app/rsc-error-log-aggregate/page.js:5:21)' +
+          '\n      at Page (app/rsc-error-log-aggregate/page.js:15:3)' +
+          "\n    3 |   const error1 = new Error('Error 1')" +
+          "\n    4 |   const error2 = new TypeError('Error 2')" +
+          "\n  > 5 |   const rootError = new Error('Root error')" +
+          '\n      |                     ^' +
+          '\n    6 |   const aggregateError = new AggregateError(' +
+          '\n    7 |     [error1, error2],' +
+          "\n    8 |     'rsc-error-log-aggregate',," +
```
[the remark this answers is not in the document]
Comment (eps1lon) [reply test/e2e/app-dir/server-source-maps/server-source-maps.test.ts:232]: Double comma is from Node.js' `inspect`

**Review by eps1lon — APPROVED** [review]
Thank you!
