### PR TITLE
fix: Ensure ergonomic handling of non-page in `./pages/`

### LINKED ISSUE #7836: Ensure ergonomic handling of non-page in `./pages/`
We need to make sure there's a sufficiently informative error displayed.

### PR DESCRIPTION
**Pull request by nataliemarleny**
This PR adds a sufficiently informative error when a non-page is added to the `./pages` directory when `target: severless`

--------

8e8bb0e 
- Update `autoExport failed` to `automatic static optimization failed` as discussed in issue comments: see https://github.com/zeit/next.js/issues/7836#issuecomment-510238273

cb21fe7 
- Update test for `autoExport` error message to reflect rename to `automatic static optimization` 

73203ec 
- Update the outputted error message for handling a non-page in `./pages` when `target: serverless'`

097d5e89 
- Add test for changes made in 73203ec

---------
#### Error Message after fix:
```
$ next build
Creating an optimized production build ...

Failed to compile.

> Build error occurred
Error: webpack build failed: found page without a React Component as default export in pages/abc.tsx

See https://err.sh/zeit/next.js page-without-valid-component for more info.
    at build (/Users/nataliemarleny/nextjs-sandbox/node_modules/next/dist/build/index.js:14:418)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### Error Message prior to fix:
```
$ next build
Creating an optimized production build ...

> Using external babel configuration
> Location: "/Users/timneutkens/projects/something/.babelrc"
Failed to compile.

./node_modules/next/dist/build/webpack/loaders/next-serverless-loader.js?page=%2Fhome%2Fstyles&absolutePagePath=private-next-pages%2Fhome%2Fstyles.js&absoluteAppPath=next%2Fdist%2Fpages%2F_app&absoluteDocumentPath=private-next-pages%2F_document.js&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&distDir=private-dot-next&assetPrefix=&generateEtags=true&ampBindInitData=false&canonicalBase=&dynamicBuildId=false
Attempted import error: 'private-next-pages/home/styles.js' does not contain a default export (imported as 'ComponentInfo').

> Build error occurred
Error: > webpack config.resolve.alias was incorrectly overriden. https://err.sh/zeit/next.js/invalid-resolve-alias
    at build (/Users/timneutkens/projects/something/node_modules/next/dist/build/index.js:6:235)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
error Command failed with exit code 1.
```

fixes: #7836

### CODE REVIEW

File: packages/next/build/index.ts [hunk 1]
```diff
@@ -240,6 +240,19 @@ export default async function build(dir: string, conf = null): Promise<void> {
...
+
+    if (
+      error.indexOf('private-next-pages') > -1 &&
+      error.indexOf('does not contain a default export') > -1
+    ) {
+      const page_name_regex = /\'private-next-pages\/(?<page_name>[^\']*)\'/
+      const parsed = page_name_regex.exec(error)
+      const page_name = parsed.groups.page_name
+      throw new Error(
+        `webpack build failed: found page without a React Component as default export in pages/${page_name}\n\nSee https://err.sh/zeit/next.js page-without-valid-component for more info.`
```
Comment (huv1k) [inline packages/next/build/index.ts]: `
```suggestion
        `webpack build failed: found page without a React Component as default export in pages/${page_name}\n\nSee https://err.sh/zeit/next.js/page-without-valid-component for more info.`
```

**Review by timneutkens — APPROVED** [review]
Looks good to me 💯
