### PR TITLE
Flush buffered vitals metrics on page mount

### LINKED ISSUE #32631: Small memory leak inside trackWebVitalMetric
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.4.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

In `next/client/vitals.ts` there's a function `trackWebVitalMetric` which gets called on each navigation that will push a metric object onto the `metrics`-array. This causes a small memory leak, especially since this array is only used by an experimental hook `useExperimentalWebVitalsReport`.

### Expected Behavior

A) That the application doesn't contain any sudden memory leak
B) It would be good with an option that doesn't include experimental features

### To Reproduce

1. Have an example with at least a start page and a linked page
2. Navigate between the pages by using e.g., NextLink or use the browser back button
3. Note how the variable `metrics` will grow for each navigation

### PR DESCRIPTION
**Pull request by huozhi**
## Bug

fixes #32631

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [x] Errors have helpful link attached, see `contributing.md`

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| buildDuration | 11.8s | 11.2s | -557ms |
| buildDurationCached | 2.9s | 2.9s | ⚠️ +49ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +570 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.645 | 2.702 | ⚠️ +0.06 |
| / avg req/sec | 945.12 | 925.41 | ⚠️ -19.71 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.27 | 1.312 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1968.52 | 1905.76 | ⚠️ -62.76 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ⚠️ +37 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71 kB | 71.1 kB | ⚠️ +37 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.4 kB | 14.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| index.html gzip | 530 B | 532 B | ⚠️ +2 B |
| link.html gzip | 543 B | 546 B | ⚠️ +3 B |
| withRouter.html gzip | 525 B | 527 B | ⚠️ +2 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +7 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -3158,13 +3158,14 @@
       });
       exports.trackWebVitalMetric = trackWebVitalMetric;
       exports.useWebVitalsReport = useWebVitalsReport;
-      exports.webVitalsCallbacks = void 0;
+      exports.bufferedVitalsMetrics = exports.webVitalsCallbacks = void 0;
       var _react = __webpack_require__(7294);
       var webVitalsCallbacks = new Set();
       exports.webVitalsCallbacks = webVitalsCallbacks;
-      var metrics = [];
+      var bufferedVitalsMetrics = [];
+      exports.bufferedVitalsMetrics = bufferedVitalsMetrics;
       function trackWebVitalMetric(metric) {
-        metrics.push(metric);
+        bufferedVitalsMetrics.push(metric);
         webVitalsCallbacks.forEach(function(callback) {
           return callback(metric);
         });
@@ -3176,10 +3177,14 @@
             // Flush calculated metrics
             var reportMetric = function(metric) {
               callback(metric);
-              metricIndexRef.current = metrics.length;
+              metricIndexRef.current = bufferedVitalsMetrics.length;
             };
-            for (var i = metricIndexRef.current; i < metrics.length; i++) {
-              reportMetric(metrics[i]);
+            for (
+              var i = metricIndexRef.current;
+              i < bufferedVitalsMetrics.length;
+              i++
+            ) {
+              reportMetric(bufferedVitalsMetrics[i]);
             }
             webVitalsCallbacks.add(reportMetric);
             return function() {
@@ -3188,6 +3193,11 @@
           },
           [callback]
         );
+        // Flush buffer on mount
+        (0, _react).useEffect(function() {
+          bufferedVitalsMetrics.length = 0;
+          metricIndexRef.current = 0;
+        }, []);
       } //# sourceMappingURL=vitals.js.map
 
       /***/
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-767fc6542b5c4eaf.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-767fc6542b5c4eaf.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-767fc6542b5c4eaf.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14s | -174ms |
| buildDurationCached | 2.9s | 2.9s | -10ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +570 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.644 | 2.689 | ⚠️ +0.04 |
| / avg req/sec | 945.58 | 929.86 | ⚠️ -15.72 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.262 | 1.235 | -0.03 |
| /error-in-render avg req/sec | 1980.49 | 2023.48 | +42.99 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.4 kB | ⚠️ +32 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.98 kB | 4.98 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| index.html gzip | 530 B | 528 B | -2 B |
| link.html gzip | 543 B | 542 B | -1 B |
| withRouter.html gzip | 525 B | 523 B | -2 B |
| Overall change | 1.6 kB | 1.59 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -3158,13 +3158,14 @@
       });
       exports.trackWebVitalMetric = trackWebVitalMetric;
       exports.useWebVitalsReport = useWebVitalsReport;
-      exports.webVitalsCallbacks = void 0;
+      exports.bufferedVitalsMetrics = exports.webVitalsCallbacks = void 0;
       var _react = __webpack_require__(7294);
       var webVitalsCallbacks = new Set();
       exports.webVitalsCallbacks = webVitalsCallbacks;
-      var metrics = [];
+      var bufferedVitalsMetrics = [];
+      exports.bufferedVitalsMetrics = bufferedVitalsMetrics;
       function trackWebVitalMetric(metric) {
-        metrics.push(metric);
+        bufferedVitalsMetrics.push(metric);
         webVitalsCallbacks.forEach(function(callback) {
           return callback(metric);
         });
@@ -3176,10 +3177,14 @@
             // Flush calculated metrics
             var reportMetric = function(metric) {
               callback(metric);
-              metricIndexRef.current = metrics.length;
+              metricIndexRef.current = bufferedVitalsMetrics.length;
             };
-            for (var i = metricIndexRef.current; i < metrics.length; i++) {
-              reportMetric(metrics[i]);
+            for (
+              var i = metricIndexRef.current;
+              i < bufferedVitalsMetrics.length;
+              i++
+            ) {
+              reportMetric(bufferedVitalsMetrics[i]);
             }
             webVitalsCallbacks.add(reportMetric);
             return function() {
@@ -3188,6 +3193,11 @@
           },
           [callback]
         );
+        // Flush buffer on mount
+        (0, _react).useEffect(function() {
+          bufferedVitalsMetrics.length = 0;
+          metricIndexRef.current = 0;
+        }, []);
       } //# sourceMappingURL=vitals.js.map
 
       /***/
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-767fc6542b5c4eaf.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-767fc6542b5c4eaf.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-767fc6542b5c4eaf.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 44b62791a45ee249b9519d50801b91772df03bde

**Comment by devknoll** [comment]
Doesn't this still cause a leak if `useWebVitalsReport` isn't actually used? I think you probably want a separate (private) hook that you can add to `next/client/index.tsx` to clear the buffer regardless?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| buildDuration | 13s | 12.6s | -403ms |
| buildDurationCached | 3.2s | 3.2s | -2ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +1.37 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.942 | 2.947 | 0 |
| / avg req/sec | 849.73 | 848.45 | ⚠️ -1.28 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.366 | 1.368 | 0 |
| /error-in-render avg req/sec | 1830.68 | 1827.57 | ⚠️ -3.11 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ⚠️ +53 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71 kB | 71.1 kB | ⚠️ +53 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.4 kB | 14.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 543 B | 545 B | ⚠️ +2 B |
| withRouter.html gzip | 525 B | 524 B | -1 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1465,6 +1465,10 @@
         _react.default.useEffect(function() {
           (0, _performanceRelayer).default(onPerfEntry);
         }, []);
+        // Flush buffer on mount
+        _react.default.useEffect(function() {
+          (0, _vitals).flushBufferedVitalsMetrics();
+        }, []);
         return children;
       }
       // Dummy component that we render as a child of Root so that we can
@@ -3156,30 +3160,43 @@
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
+      exports.flushBufferedVitalsMetrics = flushBufferedVitalsMetrics;
       exports.trackWebVitalMetric = trackWebVitalMetric;
       exports.useWebVitalsReport = useWebVitalsReport;
-      exports.webVitalsCallbacks = void 0;
+      exports.bufferedVitalsMetrics = exports.webVitalsCallbacks = void 0;
       var _react = __webpack_require__(7294);
       var webVitalsCallbacks = new Set();
       exports.webVitalsCallbacks = webVitalsCallbacks;
-      var metrics = [];
+      var flushed = false;
+      var bufferedVitalsMetrics = [];
+      exports.bufferedVitalsMetrics = bufferedVitalsMetrics;
+      function flushBufferedVitalsMetrics() {
+        flushed = true;
+        bufferedVitalsMetrics.length = 0;
+      }
       function trackWebVitalMetric(metric) {
-        metrics.push(metric);
+        bufferedVitalsMetrics.push(metric);
         webVitalsCallbacks.forEach(function(callback) {
           return callback(metric);
         });
       }
       function useWebVitalsReport(callback) {
         var metricIndexRef = (0, _react).useRef(0);
+        if (false) {
+        }
         (0, _react).useEffect(
           function() {
             // Flush calculated metrics
             var reportMetric = function(metric) {
               callback(metric);
-              metricIndexRef.current = metrics.length;
+              metricIndexRef.current = bufferedVitalsMetrics.length;
             };
-            for (var i = metricIndexRef.current; i < metrics.length; i++) {
-              reportMetric(metrics[i]);
+            for (
+              var i = metricIndexRef.current;
+              i < bufferedVitalsMetrics.length;
+              i++
+            ) {
+              reportMetric(bufferedVitalsMetrics[i]);
             }
             webVitalsCallbacks.add(reportMetric);
             return function() {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-dbe9186259f8eb09.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-dbe9186259f8eb09.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-dbe9186259f8eb09.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| buildDuration | 16.2s | 16.1s | -148ms |
| buildDurationCached | 3.2s | 3.2s | -21ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +1.37 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.957 | 2.962 | ⚠️ +0.01 |
| / avg req/sec | 845.43 | 844.05 | ⚠️ -1.38 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.398 | 1.37 | -0.03 |
| /error-in-render avg req/sec | 1787.89 | 1824.5 | +36.61 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.4 kB | ⚠️ +55 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ⚠️ +55 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.98 kB | 4.98 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| index.html gzip | 530 B | 531 B | ⚠️ +1 B |
| link.html gzip | 543 B | 544 B | ⚠️ +1 B |
| withRouter.html gzip | 525 B | 526 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1465,6 +1465,10 @@
         _react.default.useEffect(function() {
           (0, _performanceRelayer).default(onPerfEntry);
         }, []);
+        // Flush buffer on mount
+        _react.default.useEffect(function() {
+          (0, _vitals).flushBufferedVitalsMetrics();
+        }, []);
         return children;
       }
       // Dummy component that we render as a child of Root so that we can
@@ -3156,30 +3160,43 @@
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
+      exports.flushBufferedVitalsMetrics = flushBufferedVitalsMetrics;
       exports.trackWebVitalMetric = trackWebVitalMetric;
       exports.useWebVitalsReport = useWebVitalsReport;
-      exports.webVitalsCallbacks = void 0;
+      exports.bufferedVitalsMetrics = exports.webVitalsCallbacks = void 0;
       var _react = __webpack_require__(7294);
       var webVitalsCallbacks = new Set();
       exports.webVitalsCallbacks = webVitalsCallbacks;
-      var metrics = [];
+      var flushed = false;
+      var bufferedVitalsMetrics = [];
+      exports.bufferedVitalsMetrics = bufferedVitalsMetrics;
+      function flushBufferedVitalsMetrics() {
+        flushed = true;
+        bufferedVitalsMetrics.length = 0;
+      }
       function trackWebVitalMetric(metric) {
-        metrics.push(metric);
+        bufferedVitalsMetrics.push(metric);
         webVitalsCallbacks.forEach(function(callback) {
           return callback(metric);
         });
       }
       function useWebVitalsReport(callback) {
         var metricIndexRef = (0, _react).useRef(0);
+        if (false) {
+        }
         (0, _react).useEffect(
           function() {
             // Flush calculated metrics
             var reportMetric = function(metric) {
               callback(metric);
-              metricIndexRef.current = metrics.length;
+              metricIndexRef.current = bufferedVitalsMetrics.length;
             };
-            for (var i = metricIndexRef.current; i < metrics.length; i++) {
-              reportMetric(metrics[i]);
+            for (
+              var i = metricIndexRef.current;
+              i < bufferedVitalsMetrics.length;
+              i++
+            ) {
+              reportMetric(bufferedVitalsMetrics[i]);
             }
             webVitalsCallbacks.add(reportMetric);
             return function() {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-dbe9186259f8eb09.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-dbe9186259f8eb09.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-dbe9186259f8eb09.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 21c579944c640b3fe393c50f0fb7c341e34ee37f

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 21c579944c640b3fe393c50f0fb7c341e34ee37f

**test/integration/ondemand/test/index.test.js** 
- On Demand Entries > should navigate to pages with dynamic imports

<details>
<summary>Expand output</summary>

  ● On Demand Entries › should navigate to pages with dynamic imports

    TIMED OUT: /Hello/

    /nav/dynamic

      479 | }
      480 |
    > 481 | export class File {
          |               ^
      482 |   constructor(path) {
      483 |     this.path = path
      484 |     this.originalContent = existsSync(this.path)

      at Object.check (lib/next-test-utils.js:481:15)
      at Object.<anonymous> (integration/ondemand/test/index.test.js:102:13)

</details>

File: packages/next/client/vitals.ts [hunk 1]
```diff
@@ -3,24 +3,43 @@ import { NextWebVitalsMetric } from '../pages/_app'
...
   webVitalsCallbacks.forEach((callback) => callback(metric))
 }
 
 export function useWebVitalsReport(callback: ReportWebVitalsCallback) {
   const metricIndexRef = useRef(0)
 
+  if (process.env.NODE_ENV === 'development') {
+    if (flushed) {
+      console.error(
+        `Web vitals reporting callback is attached too late, please attach it before page is mounted.`
```
Comment (devknoll) [inline packages/next/client/vitals.ts:26]: nit, maybe:

```
The `useWebVitalsReport` hook was called too late -- did you use it inside of a <Suspense> boundary?
```

File: packages/next/client/vitals.ts [hunk 2]
```diff
@@ -5,15 +5,19 @@ type ReportWebVitalsCallback = (webVitals: NextWebVitalsMetric) => any
 export const webVitalsCallbacks = new Set<ReportWebVitalsCallback>()
 
 let flushed = false
-export const bufferedVitalsMetrics: NextWebVitalsMetric[] = []
+const metrics: NextWebVitalsMetric[] = []
+
+export function getBufferedVitalsMetrics() {
+  return metrics
+}
```
Comment (devknoll) [inline packages/next/client/vitals.ts:12]: Do we need to expose the metrics themselves or can we just expose the length?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.6s | ⚠️ +18ms |
| buildDurationCached | 3.1s | 3.2s | ⚠️ +15ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +1.39 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.891 | 2.941 | ⚠️ +0.05 |
| / avg req/sec | 864.74 | 850.17 | ⚠️ -14.57 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.368 | 1.371 | 0 |
| /error-in-render avg req/sec | 1827.64 | 1823.05 | ⚠️ -4.59 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ⚠️ +53 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71 kB | 71.1 kB | ⚠️ +53 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.4 kB | 14.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| index.html gzip | 530 B | 532 B | ⚠️ +2 B |
| link.html gzip | 543 B | 545 B | ⚠️ +2 B |
| withRouter.html gzip | 525 B | 527 B | ⚠️ +2 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +6 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1465,6 +1465,10 @@
         _react.default.useEffect(function() {
           (0, _performanceRelayer).default(onPerfEntry);
         }, []);
+        // Flush buffer on mount
+        _react.default.useEffect(function() {
+          (0, _vitals).flushBufferedVitalsMetrics();
+        }, []);
         return children;
       }
       // Dummy component that we render as a child of Root so that we can
@@ -3156,13 +3160,23 @@
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
+      exports.getBufferedVitalsMetrics = getBufferedVitalsMetrics;
+      exports.flushBufferedVitalsMetrics = flushBufferedVitalsMetrics;
       exports.trackWebVitalMetric = trackWebVitalMetric;
       exports.useWebVitalsReport = useWebVitalsReport;
       exports.webVitalsCallbacks = void 0;
       var _react = __webpack_require__(7294);
       var webVitalsCallbacks = new Set();
       exports.webVitalsCallbacks = webVitalsCallbacks;
+      var flushed = false;
       var metrics = [];
+      function getBufferedVitalsMetrics() {
+        return metrics;
+      }
+      function flushBufferedVitalsMetrics() {
+        flushed = true;
+        metrics.length = 0;
+      }
       function trackWebVitalMetric(metric) {
         metrics.push(metric);
         webVitalsCallbacks.forEach(function(callback) {
@@ -3171,6 +3185,8 @@
       }
       function useWebVitalsReport(callback) {
         var metricIndexRef = (0, _react).useRef(0);
+        if (false) {
+        }
         (0, _react).useEffect(
           function() {
             // Flush calculated metrics
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-40389b4c813c0c20.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-40389b4c813c0c20.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-40389b4c813c0c20.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| buildDuration | 15.8s | 15.9s | ⚠️ +127ms |
| buildDurationCached | 3.2s | 3.2s | ⚠️ +24ms |
| nodeModulesSize | 358 MB | 358 MB | ⚠️ +1.39 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.902 | 2.875 | -0.03 |
| / avg req/sec | 861.33 | 869.65 | +8.32 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.396 | 1.296 | -0.1 |
| /error-in-render avg req/sec | 1790.37 | 1929.09 | +138.72 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.4 kB | ⚠️ +55 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ⚠️ +55 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.98 kB | 4.98 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 543 B | 543 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1465,6 +1465,10 @@
         _react.default.useEffect(function() {
           (0, _performanceRelayer).default(onPerfEntry);
         }, []);
+        // Flush buffer on mount
+        _react.default.useEffect(function() {
+          (0, _vitals).flushBufferedVitalsMetrics();
+        }, []);
         return children;
       }
       // Dummy component that we render as a child of Root so that we can
@@ -3156,13 +3160,23 @@
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
+      exports.getBufferedVitalsMetrics = getBufferedVitalsMetrics;
+      exports.flushBufferedVitalsMetrics = flushBufferedVitalsMetrics;
       exports.trackWebVitalMetric = trackWebVitalMetric;
       exports.useWebVitalsReport = useWebVitalsReport;
       exports.webVitalsCallbacks = void 0;
       var _react = __webpack_require__(7294);
       var webVitalsCallbacks = new Set();
       exports.webVitalsCallbacks = webVitalsCallbacks;
+      var flushed = false;
       var metrics = [];
+      function getBufferedVitalsMetrics() {
+        return metrics;
+      }
+      function flushBufferedVitalsMetrics() {
+        flushed = true;
+        metrics.length = 0;
+      }
       function trackWebVitalMetric(metric) {
         metrics.push(metric);
         webVitalsCallbacks.forEach(function(callback) {
@@ -3171,6 +3185,8 @@
       }
       function useWebVitalsReport(callback) {
         var metricIndexRef = (0, _react).useRef(0);
+        if (false) {
+        }
         (0, _react).useEffect(
           function() {
             // Flush calculated metrics
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-40389b4c813c0c20.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-40389b4c813c0c20.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-40389b4c813c0c20.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 265381e283a15e92fa884a24867a13413866912a

File: packages/next/client/vitals.ts (hunk 2 above)
Comment (huozhi) [reply packages/next/client/vitals.ts:12]: I think it's fine to keep like this for internal usage? it's not exposed in `next/vitals` but only the hook.

Comment (devknoll) [reply packages/next/client/vitals.ts:12]: Ah, didn't realize that. Yeah that's fine then.

**Review by devknoll — DISMISSED** [review]

File: packages/next/client/index.tsx [hunk 3]
```diff
@@ -1011,6 +1011,11 @@ function Root({
   React.useEffect(() => {
     measureWebVitals(onPerfEntry)
   }, [])
+
+  // Flush buffer on mount
+  React.useEffect(() => {
+    flushBufferedVitalsMetrics()
+  }, [])
```
Comment (shuding) [inline packages/next/client/index.tsx:1018]: Why not merging these two effects?

**Review by shuding — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.3s | -321ms |
| buildDurationCached | 3.1s | 3.1s | -9ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +1.24 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.911 | 2.877 | -0.03 |
| / avg req/sec | 858.76 | 868.97 | +10.21 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.362 | 1.351 | -0.01 |
| /error-in-render avg req/sec | 1835.59 | 1850.88 | +15.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ⚠️ +50 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71 kB | 71.1 kB | ⚠️ +50 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.4 kB | 14.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| index.html gzip | 530 B | 532 B | ⚠️ +2 B |
| link.html gzip | 543 B | 546 B | ⚠️ +3 B |
| withRouter.html gzip | 525 B | 527 B | ⚠️ +2 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +7 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1464,6 +1464,7 @@
         // don't cause any hydration delay:
         _react.default.useEffect(function() {
           (0, _performanceRelayer).default(onPerfEntry);
+          (0, _vitals).flushBufferedVitalsMetrics();
         }, []);
         return children;
       }
@@ -3156,13 +3157,23 @@
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
+      exports.getBufferedVitalsMetrics = getBufferedVitalsMetrics;
+      exports.flushBufferedVitalsMetrics = flushBufferedVitalsMetrics;
       exports.trackWebVitalMetric = trackWebVitalMetric;
       exports.useWebVitalsReport = useWebVitalsReport;
       exports.webVitalsCallbacks = void 0;
       var _react = __webpack_require__(7294);
       var webVitalsCallbacks = new Set();
       exports.webVitalsCallbacks = webVitalsCallbacks;
+      var flushed = false;
       var metrics = [];
+      function getBufferedVitalsMetrics() {
+        return metrics;
+      }
+      function flushBufferedVitalsMetrics() {
+        flushed = true;
+        metrics.length = 0;
+      }
       function trackWebVitalMetric(metric) {
         metrics.push(metric);
         webVitalsCallbacks.forEach(function(callback) {
@@ -3171,6 +3182,8 @@
       }
       function useWebVitalsReport(callback) {
         var metricIndexRef = (0, _react).useRef(0);
+        if (false) {
+        }
         (0, _react).useEffect(
           function() {
             // Flush calculated metrics
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-8167ff53b7a6317e.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-8167ff53b7a6317e.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-8167ff53b7a6317e.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| buildDuration | 15.6s | 15.9s | ⚠️ +279ms |
| buildDurationCached | 3.1s | 3.2s | ⚠️ +107ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +1.24 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.899 | 2.976 | ⚠️ +0.08 |
| / avg req/sec | 862.24 | 840.04 | ⚠️ -22.2 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.337 | 1.375 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1869.39 | 1818.63 | ⚠️ -50.76 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.4 kB | ⚠️ +56 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ⚠️ +56 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.98 kB | 4.98 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 543 B | 543 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1464,6 +1464,7 @@
         // don't cause any hydration delay:
         _react.default.useEffect(function() {
           (0, _performanceRelayer).default(onPerfEntry);
+          (0, _vitals).flushBufferedVitalsMetrics();
         }, []);
         return children;
       }
@@ -3156,13 +3157,23 @@
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
+      exports.getBufferedVitalsMetrics = getBufferedVitalsMetrics;
+      exports.flushBufferedVitalsMetrics = flushBufferedVitalsMetrics;
       exports.trackWebVitalMetric = trackWebVitalMetric;
       exports.useWebVitalsReport = useWebVitalsReport;
       exports.webVitalsCallbacks = void 0;
       var _react = __webpack_require__(7294);
       var webVitalsCallbacks = new Set();
       exports.webVitalsCallbacks = webVitalsCallbacks;
+      var flushed = false;
       var metrics = [];
+      function getBufferedVitalsMetrics() {
+        return metrics;
+      }
+      function flushBufferedVitalsMetrics() {
+        flushed = true;
+        metrics.length = 0;
+      }
       function trackWebVitalMetric(metric) {
         metrics.push(metric);
         webVitalsCallbacks.forEach(function(callback) {
@@ -3171,6 +3182,8 @@
       }
       function useWebVitalsReport(callback) {
         var metricIndexRef = (0, _react).useRef(0);
+        if (false) {
+        }
         (0, _react).useEffect(
           function() {
             // Flush calculated metrics
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-8167ff53b7a6317e.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-8167ff53b7a6317e.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-c6fc133fe313f8ea.js"
+      src="/_next/static/chunks/main-8167ff53b7a6317e.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 75bb71042675d91b853c6cb065975c966113cacd

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.3s | -55ms |
| buildDurationCached | 3.1s | 3.1s | ⚠️ +9ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +1.22 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.89 | 2.908 | ⚠️ +0.02 |
| / avg req/sec | 864.99 | 859.55 | ⚠️ -5.44 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.316 | 1.34 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1899.36 | 1866.09 | ⚠️ -33.27 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ⚠️ +50 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71 kB | 71.1 kB | ⚠️ +50 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.4 kB | 14.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| index.html gzip | 530 B | 529 B | -1 B |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1464,6 +1464,7 @@
         // don't cause any hydration delay:
         _react.default.useEffect(function() {
           (0, _performanceRelayer).default(onPerfEntry);
+          (0, _vitals).flushBufferedVitalsMetrics();
         }, []);
         return children;
       }
@@ -3156,13 +3157,23 @@
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
+      exports.getBufferedVitalsMetrics = getBufferedVitalsMetrics;
+      exports.flushBufferedVitalsMetrics = flushBufferedVitalsMetrics;
       exports.trackWebVitalMetric = trackWebVitalMetric;
       exports.useWebVitalsReport = useWebVitalsReport;
       exports.webVitalsCallbacks = void 0;
       var _react = __webpack_require__(7294);
       var webVitalsCallbacks = new Set();
       exports.webVitalsCallbacks = webVitalsCallbacks;
+      var flushed = false;
       var metrics = [];
+      function getBufferedVitalsMetrics() {
+        return metrics;
+      }
+      function flushBufferedVitalsMetrics() {
+        flushed = true;
+        metrics.length = 0;
+      }
       function trackWebVitalMetric(metric) {
         metrics.push(metric);
         webVitalsCallbacks.forEach(function(callback) {
@@ -3171,6 +3182,8 @@
       }
       function useWebVitalsReport(callback) {
         var metricIndexRef = (0, _react).useRef(0);
+        if (false) {
+        }
         (0, _react).useEffect(
           function() {
             // Flush calculated metrics
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-9e509be81242c9cb.js"
+      src="/_next/static/chunks/main-7381bf85898cb56a.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-9e509be81242c9cb.js"
+      src="/_next/static/chunks/main-7381bf85898cb56a.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-9e509be81242c9cb.js"
+      src="/_next/static/chunks/main-7381bf85898cb56a.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| buildDuration | 15.7s | 15.9s | ⚠️ +145ms |
| buildDurationCached | 3.2s | 3.1s | -35ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +1.22 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.905 | 2.935 | ⚠️ +0.03 |
| / avg req/sec | 860.57 | 851.71 | ⚠️ -8.86 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.328 | 1.354 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1883.11 | 1845.82 | ⚠️ -37.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.4 kB | ⚠️ +56 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ⚠️ +56 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.98 kB | 4.98 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js vitals/clear-buffer | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 543 B | 543 B | ✓ |
| withRouter.html gzip | 524 B | 525 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1464,6 +1464,7 @@
         // don't cause any hydration delay:
         _react.default.useEffect(function() {
           (0, _performanceRelayer).default(onPerfEntry);
+          (0, _vitals).flushBufferedVitalsMetrics();
         }, []);
         return children;
       }
@@ -3156,13 +3157,23 @@
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
+      exports.getBufferedVitalsMetrics = getBufferedVitalsMetrics;
+      exports.flushBufferedVitalsMetrics = flushBufferedVitalsMetrics;
       exports.trackWebVitalMetric = trackWebVitalMetric;
       exports.useWebVitalsReport = useWebVitalsReport;
       exports.webVitalsCallbacks = void 0;
       var _react = __webpack_require__(7294);
       var webVitalsCallbacks = new Set();
       exports.webVitalsCallbacks = webVitalsCallbacks;
+      var flushed = false;
       var metrics = [];
+      function getBufferedVitalsMetrics() {
+        return metrics;
+      }
+      function flushBufferedVitalsMetrics() {
+        flushed = true;
+        metrics.length = 0;
+      }
       function trackWebVitalMetric(metric) {
         metrics.push(metric);
         webVitalsCallbacks.forEach(function(callback) {
@@ -3171,6 +3182,8 @@
       }
       function useWebVitalsReport(callback) {
         var metricIndexRef = (0, _react).useRef(0);
+        if (false) {
+        }
         (0, _react).useEffect(
           function() {
             // Flush calculated metrics
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-9e509be81242c9cb.js"
+      src="/_next/static/chunks/main-7381bf85898cb56a.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-9e509be81242c9cb.js"
+      src="/_next/static/chunks/main-7381bf85898cb56a.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-9e509be81242c9cb.js"
+      src="/_next/static/chunks/main-7381bf85898cb56a.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 053f08376f59c3b8bf437c5e125f8e02cbbab3a9
