### PR TITLE
Fix missing quotes around `in` operator check for PerformanceObserver

### LINKED ISSUE #10016: unstable_onPerformanceData breaking hydration in IE11
# Bug report

## Describe the bug

As of `9.1.5`, When using `unstable_onPerformanceData` API, IE11 throws an exception when hydrating the application.`Unhandled promise rejection ReferenceError: 'PerformanceObserver' is undefined`:

It's triggered with a custom `_app.js` containing:

```jsx
function MyApp({ Component, pageProps }) {
    return <Component {...pageProps} />
}
  
export const unstable_onPerformanceData = data => { };
  
export default MyApp
```
## To Reproduce

```bash
$ git clone https://github.com/KB1RMA/nextjs-performance-ie-bug-reproduction.git
$ cd nextjs-performance-ie-bug-reproduction
$ yarn 
$ yarn build && NODE_ENV=production yarn start
```
Visit http://localhost:3000 in IE11

## Expected behavior

Example NextJS application should load and hydrate in the browser.

## Screenshots

image

## System information

- OS: Windows
- Browser: IE11
- Version of Next.js: 9.1.5

### PR DESCRIPTION
**Pull request by KB1RMA**
Closes #10016 by fixing missing quotes around the object property name in the support check for `PerformanceObserver`.

I can take a look at adding a test for this, but might take me a bit to familiarize myself with the suite.

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14s | -117ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +1 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | -1 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ⚠️ +1 B |
| link.html gzip | 1.03 kB | 1.03 kB | ⚠️ +2 B |
| withRouter.html gzip | 1.01 kB | 1.01 kB | ⚠️ +1 B |
| Overall change | 3.06 kB | 3.06 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -874,7 +874,7 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
+          if (!('PerformanceObserver' in window)) {
             window.addEventListener('load', function() {
               performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -588,7 +588,7 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
+          if (!('PerformanceObserver' in window)) {
             window.addEventListener('load', () => {
               performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      href="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-fe84dab9e48c3d7c3265.js"
+      src="/_next/static/runtime/main-e43d049cc1f6d0b61ef6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      src="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      href="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-fe84dab9e48c3d7c3265.js"
+      src="/_next/static/runtime/main-e43d049cc1f6d0b61ef6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      src="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      href="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-fe84dab9e48c3d7c3265.js"
+      src="/_next/static/runtime/main-e43d049cc1f6d0b61ef6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      src="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 14.7s | 14.7s | -7ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +1 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | -1 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.7 kB | -2 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | ⚠️ +1 B |
| index.js gzip | 78 kB | 78 kB | ✓ |
| link.js gzip | 80.4 kB | 80.4 kB | -1 B |
| routerDirect.js gzip | 78 kB | 78 kB | -2 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | -1 B |
| Overall change | 393 kB | 393 kB | -5 B |

</details>

</details>


Commit: afe8ce1a56776f850982295e852b3c8b2aeb4eb0

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 12.4s | 11.8s | -637ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +1 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | -1 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ⚠️ +1 B |
| link.html gzip | 1.03 kB | 1.03 kB | ⚠️ +2 B |
| withRouter.html gzip | 1.02 kB | 1.02 kB | ✓ |
| Overall change | 3.06 kB | 3.07 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -874,7 +874,7 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
+          if (!('PerformanceObserver' in window)) {
             window.addEventListener('load', function() {
               performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -588,7 +588,7 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
+          if (!('PerformanceObserver' in window)) {
             window.addEventListener('load', () => {
               performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      href="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-fe84dab9e48c3d7c3265.js"
+      src="/_next/static/runtime/main-e43d049cc1f6d0b61ef6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      src="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      href="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-fe84dab9e48c3d7c3265.js"
+      src="/_next/static/runtime/main-e43d049cc1f6d0b61ef6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      src="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      href="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-fe84dab9e48c3d7c3265.js"
+      src="/_next/static/runtime/main-e43d049cc1f6d0b61ef6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      src="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 13s | 12.4s | -619ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +1 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | -1 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | -1 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | ✓ |
| index.js gzip | 78 kB | 78 kB | -2 B |
| link.js gzip | 80.4 kB | 80.4 kB | -1 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | -2 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | -1 B |
| Overall change | 393 kB | 393 kB | -7 B |

</details>

</details>


Commit: e4f49909839c49bbf3cc218a6de8c2b9d841ccb7

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.4s | -243ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +1 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | -1 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ⚠️ +1 B |
| link.html gzip | 1.03 kB | 1.03 kB | ⚠️ +2 B |
| withRouter.html gzip | 1.02 kB | 1.02 kB | ✓ |
| Overall change | 3.06 kB | 3.07 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -874,7 +874,7 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
+          if (!('PerformanceObserver' in window)) {
             window.addEventListener('load', function() {
               performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -588,7 +588,7 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
+          if (!('PerformanceObserver' in window)) {
             window.addEventListener('load', () => {
               performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      href="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-fe84dab9e48c3d7c3265.js"
+      src="/_next/static/runtime/main-e43d049cc1f6d0b61ef6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      src="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      href="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-fe84dab9e48c3d7c3265.js"
+      src="/_next/static/runtime/main-e43d049cc1f6d0b61ef6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      src="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      href="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-fe84dab9e48c3d7c3265.js"
+      src="/_next/static/runtime/main-e43d049cc1f6d0b61ef6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-31eec21cac2e127e1241.module.js"
+      src="/_next/static/runtime/main-4239b13467e4e5a0bb1f.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 13.1s | 12.7s | -398ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +1 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | -1 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | -1 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | ✓ |
| index.js gzip | 78 kB | 78 kB | -2 B |
| link.js gzip | 80.4 kB | 80.4 kB | -1 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | -2 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | -1 B |
| Overall change | 393 kB | 393 kB | -7 B |

</details>

</details>


Commit: 92a4f7b15568d00e6b5cd936d2b2369ca80aaa12

**Comment by KB1RMA** [comment]
Looks like the paint metrics from `PerformanceObserver` aren't calling the exported function in some of the integration tests. I can keep taking a look tomorrow, but I'm not entirely familiar with how you guys want this API to behave

**Comment by Timer** [comment]
cc @prateekbh any insights?

**Comment by prateekbh** [comment]
just for sanity, does removing the `''` fixes it?
can we try that once

**Comment by KB1RMA** [comment]
Can't we just take a look at any of the other test runs on another branch? It looks like those tests are passing on other branches. Although I'm still trying to get myself up to speed on the integration suite and where all it runs so I could be misunderstanding what you're asking.

But just from a purely theoretical standpoint, this code will never make it to the else block which actually uses `PerformanceObserver`. So I think the behavior just needs to be adjusted. Perhaps by calling the method on the load event?

**Comment by prateekbh** [comment]
@KB1RMA if the browser in tests has `PerformanceObserver` shouldn't it reach there?

**Comment by KB1RMA** [comment]
It does now that I've fixed the check for it existing on `window`. But I don't think it's behaving as it was designed too. It almost looks like the observer is being registered too late in the lifecycle and the callback is never actually executed for paint metrics. At least from my brief amount of time debugging and reading docs on `PerformanceObserver`

**Comment by KB1RMA** [comment]
I pull the `PerformanceObserver` out of this. I don't see how it could stream `first-paint` to the component this late in the lifecycle. It needs to be pulled retroactively from the performance api.

Unless there's a way to get fancy and stream it to local storage before hydration, then read it in later? But that seems pretty complex

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.5s | ⚠️ +32ms |
| nodeModulesSize | 49 MB | 49 MB | -403 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.06 kB | -47 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | -47 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.13 kB | -46 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62 kB | -46 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | -2 B |
| withRouter.html gzip | 1.02 kB | 1.01 kB | -1 B |
| Overall change | 3.07 kB | 3.06 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -874,18 +874,9 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
-            window.addEventListener('load', function() {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
-            var observer = new PerformanceObserver(function(list) {
-              list.getEntries().forEach(onPerfEntry)
-            })
-            observer.observe({
-              entryTypes: ['paint'],
-            })
-          }
+          window.addEventListener('load', function() {
+            performance.getEntriesByType('paint').forEach(onPerfEntry)
+          })
         }
       }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -588,18 +588,9 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
-            window.addEventListener('load', () => {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
-            var observer = new PerformanceObserver(list => {
-              list.getEntries().forEach(onPerfEntry)
-            })
-            observer.observe({
-              entryTypes: ['paint'],
-            })
-          }
+          window.addEventListener('load', () => {
+            performance.getEntriesByType('paint').forEach(onPerfEntry)
+          })
         }
       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-e50b1f9de6a9a8158e33.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-f37d3c2d18db653676b9.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-e50b1f9de6a9a8158e33.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-e50b1f9de6a9a8158e33.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-f37d3c2d18db653676b9.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-e50b1f9de6a9a8158e33.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-e50b1f9de6a9a8158e33.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-f37d3c2d18db653676b9.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-e50b1f9de6a9a8158e33.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 12s | 11.9s | -52ms |
| nodeModulesSize | 49 MB | 49 MB | -403 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.06 kB | -47 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | -47 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.13 kB | -46 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62 kB | -46 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +1 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | -1 B |
| index.js gzip | 78 kB | 78 kB | ⚠️ +1 B |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +1 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +1 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +1 B |
| Overall change | 393 kB | 393 kB | ⚠️ +4 B |

</details>

</details>


Commit: 6a2c9d9b08e86c9bbad0c956de2e9914daead5e1

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.1s | -76ms |
| nodeModulesSize | 49 MB | 49 MB | -403 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.06 kB | -47 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | -47 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.13 kB | -46 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62 kB | -46 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | -2 B |
| withRouter.html gzip | 1.02 kB | 1.01 kB | -1 B |
| Overall change | 3.07 kB | 3.06 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -874,18 +874,9 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
-            window.addEventListener('load', function() {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
-            var observer = new PerformanceObserver(function(list) {
-              list.getEntries().forEach(onPerfEntry)
-            })
-            observer.observe({
-              entryTypes: ['paint'],
-            })
-          }
+          window.addEventListener('load', function() {
+            performance.getEntriesByType('paint').forEach(onPerfEntry)
+          })
         }
       }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -588,18 +588,9 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
-            window.addEventListener('load', () => {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
-            var observer = new PerformanceObserver(list => {
-              list.getEntries().forEach(onPerfEntry)
-            })
-            observer.observe({
-              entryTypes: ['paint'],
-            })
-          }
+          window.addEventListener('load', () => {
+            performance.getEntriesByType('paint').forEach(onPerfEntry)
+          })
         }
       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-e50b1f9de6a9a8158e33.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-f37d3c2d18db653676b9.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-e50b1f9de6a9a8158e33.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-e50b1f9de6a9a8158e33.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-f37d3c2d18db653676b9.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-e50b1f9de6a9a8158e33.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-e50b1f9de6a9a8158e33.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-f37d3c2d18db653676b9.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-e50b1f9de6a9a8158e33.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.9s | ⚠️ +119ms |
| nodeModulesSize | 49 MB | 49 MB | -403 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.06 kB | -47 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | -47 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.13 kB | -46 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62 kB | -46 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +1 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | -1 B |
| index.js gzip | 78 kB | 78 kB | ⚠️ +1 B |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +1 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +1 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +1 B |
| Overall change | 393 kB | 393 kB | ⚠️ +4 B |

</details>

</details>


Commit: 6bea842c693a056fba46c001635e57960fdd4c81

**Comment by prateekbh** [comment]
There can be times where a script execution is keeping a body blank by the time `load` event happens. Thus `PerformanceObserver` is used to make this time independent.

a small addition to top of PerformanceObserver can fix this.
// collect already occurred paint timings
performance.getEntriesByType('paint').forEach(onPerfEntry)
// another observer for future paint events
const observer = new PerformanceObserver(list => {
  list.getEntries().forEach(onPerfEntry)
})
observer.observe({ entryTypes: ['paint'] })


Sidenote, after this we can re-enable this test to run in `dev` mode.

**Comment by KB1RMA** [comment]
Ah fair enough. Makes sense to be thorough - I'll add that back in

**Review by prateekbh — CHANGES_REQUESTED** [review]
just marking it `request for changes`. For awareness purposes

**Comment by KB1RMA** [comment]
Is it worth creating an integration test to hang paint until after load?

File: packages/next/client/index.js [hunk 1]
```diff
@@ -294,11 +294,13 @@ function renderReactElement(reactEl, domEl) {
...
   if (onPerfEntry && ST) {
-    if (!(PerformanceObserver in window)) {
-      window.addEventListener('load', () => {
-        performance.getEntriesByType('paint').forEach(onPerfEntry)
-      })
-    } else {
+    window.addEventListener('load', () => {
+      performance.getEntriesByType('paint').forEach(onPerfEntry)
+    })
+
```
Comment (prateekbh) [inline packages/next/client/index.js]: without an `else` this might relay twice.
once when through the observer and second on load.
thus the whole else thing is needed.

`window.addEventListener('load', () => {` is only to cover you when PerformanceObserver is not available

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.8s | -29ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +205 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | -3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | -3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | -2 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ✓ |
| link.html gzip | 1.03 kB | 1.03 kB | ✓ |
| withRouter.html gzip | 1.02 kB | 1.02 kB | ✓ |
| Overall change | 3.07 kB | 3.07 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -874,11 +874,12 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
-            window.addEventListener('load', function() {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
+          window.addEventListener('load', function() {
+            performance.getEntriesByType('paint').forEach(onPerfEntry)
+          }) // Start an observer to catch any paint metrics which may fire _after_
+          // the load event is fired on the window
+
+          if ('PerformanceObserver' in window) {
             var observer = new PerformanceObserver(function(list) {
               list.getEntries().forEach(onPerfEntry)
             })
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -588,11 +588,12 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
-            window.addEventListener('load', () => {
-              performance.getEntriesByType('paint').forEach(onPerfEntry)
-            })
-          } else {
+          window.addEventListener('load', () => {
+            performance.getEntriesByType('paint').forEach(onPerfEntry)
+          }) // Start an observer to catch any paint metrics which may fire _after_
+          // the load event is fired on the window
+
+          if ('PerformanceObserver' in window) {
             var observer = new PerformanceObserver(list => {
               list.getEntries().forEach(onPerfEntry)
             })
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-1ce1471a35159418eabf.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-89a9a183aa600c330d28.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-1ce1471a35159418eabf.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-1ce1471a35159418eabf.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-89a9a183aa600c330d28.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-1ce1471a35159418eabf.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-1ce1471a35159418eabf.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-89a9a183aa600c330d28.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-1ce1471a35159418eabf.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.2s | -225ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +205 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | -3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | -3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | -2 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +3 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | ✓ |
| index.js gzip | 78 kB | 78 kB | ⚠️ +4 B |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +4 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +4 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +3 B |
| Overall change | 393 kB | 393 kB | ⚠️ +18 B |

</details>

</details>


Commit: 19e04a997032d6491ddee5761869a8498a4a1914

File: packages/next/client/index.js (hunk 1 above)
Comment (KB1RMA) [reply packages/next/client/index.js]: Yep didn't think of that. Too enthralled with making it pretty :). Thanks

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 12.7s | 13s | ⚠️ +202ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +364 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +5 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.5 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.18 kB | ⚠️ +4 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | -2 B |
| withRouter.html gzip | 1.02 kB | 1.01 kB | -1 B |
| Overall change | 3.07 kB | 3.06 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -874,11 +874,14 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
+          if (!('PerformanceObserver' in window)) {
             window.addEventListener('load', function() {
               performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
           } else {
+            performance.getEntriesByType('paint').forEach(onPerfEntry) // Start an observer to catch any paint metrics which may fire _after_
+            // the load event is fired on the window
+
             var observer = new PerformanceObserver(function(list) {
               list.getEntries().forEach(onPerfEntry)
             })
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -588,11 +588,14 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
+          if (!('PerformanceObserver' in window)) {
             window.addEventListener('load', () => {
               performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
           } else {
+            performance.getEntriesByType('paint').forEach(onPerfEntry) // Start an observer to catch any paint metrics which may fire _after_
+            // the load event is fired on the window
+
             var observer = new PerformanceObserver(list => {
               list.getEntries().forEach(onPerfEntry)
             })
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-31d1966b6e8450d91898.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-5cd5f40aa28eba9c2462.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-31d1966b6e8450d91898.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-31d1966b6e8450d91898.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-5cd5f40aa28eba9c2462.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-31d1966b6e8450d91898.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-31d1966b6e8450d91898.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-5cd5f40aa28eba9c2462.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-31d1966b6e8450d91898.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 13.1s | 13.3s | ⚠️ +221ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +364 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +5 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.5 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.18 kB | ⚠️ +4 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +2 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | -1 B |
| index.js gzip | 78 kB | 78 kB | ⚠️ +3 B |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +1 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +1 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +2 B |
| Overall change | 393 kB | 393 kB | ⚠️ +8 B |

</details>

</details>


Commit: 48e94890577aae4c5fcc4136df411969b7629275

**Review by prateekbh — APPROVED** [review]

**Review by Timer — APPROVED** [review]
Great, thank you!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 13.5s | 13.6s | ⚠️ +154ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +364 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +5 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.5 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.18 kB | ⚠️ +4 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ⚠️ +2 B |
| link.html gzip | 1.03 kB | 1.03 kB | ⚠️ +2 B |
| withRouter.html gzip | 1.02 kB | 1.02 kB | ⚠️ +1 B |
| Overall change | 3.06 kB | 3.07 kB | ⚠️ +5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -874,11 +874,14 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
+          if (!('PerformanceObserver' in window)) {
             window.addEventListener('load', function() {
               performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
           } else {
+            performance.getEntriesByType('paint').forEach(onPerfEntry) // Start an observer to catch any paint metrics which may fire _after_
+            // the load event is fired on the window
+
             var observer = new PerformanceObserver(function(list) {
               list.getEntries().forEach(onPerfEntry)
             })
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -588,11 +588,14 @@
         }
 
         if (onPerfEntry && _utils.ST) {
-          if (!(PerformanceObserver in window)) {
+          if (!('PerformanceObserver' in window)) {
             window.addEventListener('load', () => {
               performance.getEntriesByType('paint').forEach(onPerfEntry)
             })
           } else {
+            performance.getEntriesByType('paint').forEach(onPerfEntry) // Start an observer to catch any paint metrics which may fire _after_
+            // the load event is fired on the window
+
             var observer = new PerformanceObserver(list => {
               list.getEntries().forEach(onPerfEntry)
             })
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-b5bff3d9b3863c261b07.module.js"
+      href="/_next/static/runtime/main-897db3c959bbfb77cb36.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-879abd608df79480d50a.js"
+      src="/_next/static/runtime/main-1a5ad0bc4973fa5d751b.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-b5bff3d9b3863c261b07.module.js"
+      src="/_next/static/runtime/main-897db3c959bbfb77cb36.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-b5bff3d9b3863c261b07.module.js"
+      href="/_next/static/runtime/main-897db3c959bbfb77cb36.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-879abd608df79480d50a.js"
+      src="/_next/static/runtime/main-1a5ad0bc4973fa5d751b.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-b5bff3d9b3863c261b07.module.js"
+      src="/_next/static/runtime/main-897db3c959bbfb77cb36.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-b5bff3d9b3863c261b07.module.js"
+      href="/_next/static/runtime/main-897db3c959bbfb77cb36.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-879abd608df79480d50a.js"
+      src="/_next/static/runtime/main-1a5ad0bc4973fa5d751b.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-b5bff3d9b3863c261b07.module.js"
+      src="/_next/static/runtime/main-897db3c959bbfb77cb36.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| buildDuration | 14.3s | 14.4s | ⚠️ +88ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +364 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +5 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.5 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.18 kB | ⚠️ +4 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | KB1RMA/next.js perf-api-ie11-compat-check | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +1 B |
| hooks.html gzip | 1.05 kB | 1.06 kB | ⚠️ +2 B |
| index.js gzip | 78 kB | 78 kB | ⚠️ +1 B |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +1 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +1 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +2 B |
| Overall change | 393 kB | 393 kB | ⚠️ +8 B |

</details>

</details>


Commit: 1023682decfe3cb799a13a069f6e642ec3fc3e1e

**Comment by Timer** [comment]
Released in 9.1.8-canary.13.

**Comment by KB1RMA** [comment]
You guys rock.

**Comment by Timer** [comment]
Thanks for sending this fix, we really appreciate it!
