### PR TITLE
fixes #30604 - Cannot read properties of null (reading 'tagName')

### LINKED ISSUE #30604: TypeError: Cannot read properties of null (reading 'tagName')
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

14.15.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS Big Sur

### How are you deploying your application?

Vercel

### Describe the Bug

During development, each refresh I get this error:
`TypeError: Cannot read properties of null (reading 'tagName')`

image

It comes from this component:
image
In this case `<Picture />` is just a next/image, where the first image is loaded eagerly with priority

Full error stack:
image

### Expected Behavior

Doesn't show the error

### To Reproduce

Run component

### PR DESCRIPTION
**Pull request by furcan**
TypeError: Cannot read properties of null (reading 'tagName') #30604

- Fixes https://github.com/vercel/next.js/issues/30604

### CODE REVIEW

File: packages/next/client/head-manager.ts [hunk 1]
```diff
@@ -62,7 +62,7 @@ function updateElements(type: string, components: JSX.Element[]): void {
     i < headCount;
     i++, j = j!.previousElementSibling
   ) {
-    if (j!.tagName.toLowerCase() === type) {
+    if (j!.tagName?.toLowerCase() === type) {
```
Comment (styfle) [inline packages/next/client/head-manager.ts:65]:
```suggestion
    if (j?.tagName.toLowerCase() === type) {
```
I think you have this in the wrong place since `previousElementSibling` can be null

Comment (furcan) [reply packages/next/client/head-manager.ts]: Thank you.

**Review by styfle — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 20.2s | 20.8s | ⚠️ +661ms |
| buildDurationCached | 4.2s | 4.3s | ⚠️ +80ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.459 | 3.595 | ⚠️ +0.14 |
| / avg req/sec | 722.77 | 695.39 | ⚠️ -27.38 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.915 | 1.956 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1305.7 | 1278.13 | ⚠️ -27.57 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ⚠️ +14 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ⚠️ +14 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 534 B | 535 B | ⚠️ +1 B |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -118,7 +118,14 @@
           i < headCount;
           i++, j = j.previousElementSibling
         ) {
-          if (j.tagName.toLowerCase() === type) {
+          var ref;
+          if (
+            (j === null || j === void 0
+              ? void 0
+              : (ref = j.tagName) === null || ref === void 0
+              ? void 0
+              : ref.toLowerCase()) === type
+          ) {
             oldTags.push(j);
           }
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ab67a6af98bf1f43.js"
+      src="/_next/static/chunks/main-022dee77aa48ff79.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ab67a6af98bf1f43.js"
+      src="/_next/static/chunks/main-022dee77aa48ff79.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ab67a6af98bf1f43.js"
+      src="/_next/static/chunks/main-022dee77aa48ff79.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 22.4s | 22.5s | ⚠️ +153ms |
| buildDurationCached | 4.1s | 4.5s | ⚠️ +397ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.529 | 3.557 | ⚠️ +0.03 |
| / avg req/sec | 708.43 | 702.8 | ⚠️ -5.63 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.875 | 1.849 | -0.03 |
| /error-in-render avg req/sec | 1333.3 | 1351.96 | +18.66 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ⚠️ +9 B |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +9 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 522 B | 521 B | -1 B |
| link.html gzip | 536 B | 534 B | -2 B |
| withRouter.html gzip | 516 B | 515 B | -1 B |
| Overall change | 1.57 kB | 1.57 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -118,7 +118,14 @@
           i < headCount;
           i++, j = j.previousElementSibling
         ) {
-          if (j.tagName.toLowerCase() === type) {
+          var ref;
+          if (
+            (j === null || j === void 0
+              ? void 0
+              : (ref = j.tagName) === null || ref === void 0
+              ? void 0
+              : ref.toLowerCase()) === type
+          ) {
             oldTags.push(j);
           }
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ab67a6af98bf1f43.js"
+      src="/_next/static/chunks/main-022dee77aa48ff79.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ab67a6af98bf1f43.js"
+      src="/_next/static/chunks/main-022dee77aa48ff79.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ab67a6af98bf1f43.js"
+      src="/_next/static/chunks/main-022dee77aa48ff79.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: a2e22013e801ad47031f40f6e620eaec209e8fdc

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 21.8s | 22s | ⚠️ +239ms |
| buildDurationCached | 4.4s | 4.7s | ⚠️ +258ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +245 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.692 | 3.796 | ⚠️ +0.1 |
| / avg req/sec | 677.21 | 658.52 | ⚠️ -18.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.884 | 1.877 | -0.01 |
| /error-in-render avg req/sec | 1327.02 | 1332.14 | +5.12 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ⚠️ +14 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ⚠️ +14 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 534 B | 535 B | ⚠️ +1 B |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -118,7 +118,14 @@
           i < headCount;
           i++, j = j.previousElementSibling
         ) {
-          if (j.tagName.toLowerCase() === type) {
+          var ref;
+          if (
+            (j === null || j === void 0
+              ? void 0
+              : (ref = j.tagName) === null || ref === void 0
+              ? void 0
+              : ref.toLowerCase()) === type
+          ) {
             oldTags.push(j);
           }
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ab67a6af98bf1f43.js"
+      src="/_next/static/chunks/main-022dee77aa48ff79.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ab67a6af98bf1f43.js"
+      src="/_next/static/chunks/main-022dee77aa48ff79.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ab67a6af98bf1f43.js"
+      src="/_next/static/chunks/main-022dee77aa48ff79.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 24.3s | 24.2s | -134ms |
| buildDurationCached | 4.7s | 4.6s | -56ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +245 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.83 | 3.705 | -0.12 |
| / avg req/sec | 652.82 | 674.77 | +21.95 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.09 | 1.924 | -0.17 |
| /error-in-render avg req/sec | 1195.99 | 1299.49 | +103.5 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ⚠️ +9 B |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +9 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | furcan/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 522 B | 521 B | -1 B |
| link.html gzip | 536 B | 534 B | -2 B |
| withRouter.html gzip | 516 B | 515 B | -1 B |
| Overall change | 1.57 kB | 1.57 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -118,7 +118,14 @@
           i < headCount;
           i++, j = j.previousElementSibling
         ) {
-          if (j.tagName.toLowerCase() === type) {
+          var ref;
+          if (
+            (j === null || j === void 0
+              ? void 0
+              : (ref = j.tagName) === null || ref === void 0
+              ? void 0
+              : ref.toLowerCase()) === type
+          ) {
             oldTags.push(j);
           }
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ab67a6af98bf1f43.js"
+      src="/_next/static/chunks/main-022dee77aa48ff79.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ab67a6af98bf1f43.js"
+      src="/_next/static/chunks/main-022dee77aa48ff79.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ab67a6af98bf1f43.js"
+      src="/_next/static/chunks/main-022dee77aa48ff79.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: a672d8fdb23f6ba2eace14a881fa40035909124d
