### PR TITLE
Fix #3900 return 404 on asset hash mismatch in prod

### LINKED ISSUE #3900: Asset URLs with old hash 500 when you visit them instead of 404 in production
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

If a user happens to request an old bundle resource with an old hash, the response should 404, not 500.

## Current Behavior

I'm currently running a Next.js app at https://www.tenable.com/plugins and I'm getting quite a few 500 errors in my logs after I deploy a new version that has a new hash from the build (I'm using sticky sessions to minimize the disruption, but still see some errors long after the deploy).

## Steps to Reproduce (for bugs)

**200** -> https://custom-server-koa-wxksegmzhf.now.sh/_next/7c048a193f99703d6180e88866b6e06b/app.js

**500 Internal server error** -> https://custom-server-koa-wxksegmzhf.now.sh/_next/OLD_HASH_VALUE/app.js

Source code area of interest: https://github.com/zeit/next.js/blob/1aade36f13e03db13d23f86dc52a459f9a29e03d/server/index.js#L467
## Context

Just trying to minimize the number of unneeded 500 errors 😄 

Appreciate all your work and effort!

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     canary    |
| node    |     8.9    |
| OS      |     macOS, node docker    |
| browser |         |
| etc     |         |

### PR DESCRIPTION
**Pull request by timteeling**
Per #3900 I'm looking to have Next.js respond with a 404 when someone requests a hash from an asset that doesn't exist in production instead of what it currently does which is 500 Internal server error.

Currently, `handleBuildHash` in `server/index.js` throws an error regardless of environment, so I'm looking at tweaking it to send a 404 in production.

**Example:**
200 -> https://custom-server-koa-wxksegmzhf.now.sh/_next/7c048a193f99703d6180e88866b6e06b/app.js

500 Internal server error -> https://custom-server-koa-wxksegmzhf.now.sh/_next/OLD_HASH_VALUE/app.js

Thanks for your time!

### CODE REVIEW

File: server/index.js [hunk 1]
```diff
@@ -467,7 +467,11 @@ export default class Server {
     }
 
     if (hash !== this.buildStats[filename].hash) {
-      throw new Error(`Invalid Build File Hash(${hash}) for chunk: ${filename}`)
```
Comment (arunoda) [inline server/index.js]: Here's console.log the ^^ message and do `return this.send404(res)`.
In the dev mode, there's no buildId and it's been handled in few lines before.

Comment (arunoda) [inline server/index.js]: Here's console.log the ^^ message and do return this.send404(res).
In the dev mode, there's no buildId and it's been handled in few lines before.

**Review by arunoda — CHANGES_REQUESTED** [review]
This is a good one and we need to do 404 instead 500. But I'm looking for a different implementation.

**Comment by timteeling** [comment]
Thanks @arunoda 

It looks like https://github.com/zeit/next.js/pull/3793 changed how this is handled pretty significantly: https://github.com/zeit/next.js/blob/canary/server/index.js#L177

I tweaked `renderScriptError` now instead to return a 404 instead of 500 when `INVALID_BUILD_ID` is the error message

**Comment by omaksi** [comment]
I'd like to +1 this, is there something that still needs to be improved to get this released?

**Review by timneutkens — APPROVED** [review]
Awesome, just verified the code 👍 thanks Tim 🙏

**Comment by omaksi** [comment]
Thanks guys, any estimate on when could this be released on npm?
