### PR TITLE
make getStaticPaths work with optional catch-all routes

### LINKED ISSUE #13524: Experimental optional catch all routes getStaticProps receive stringified array instead of array
# Bug report

## Describe the bug

With optional catch all routes `getStaticProps` receive stringified array instead of array.

## To Reproduce

1. With this `getStaticPaths` :
```typescript
// [[...slug]].tsx
export const getStaticPaths: GetStaticPaths<PagePathParams> = async () => {
  return {
    paths: [
      {
        params: {
          slug: ['p1', 'p2'],
        },
      },
      {
        params: {
          slug: ['p3', 'p4'],
        },
      },
    ],
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps<any, PagePathParams> = async ({ params }) => {
  console.log('getStaticProps', { params })
  return {
    props: {},
  }
}
```
2. Output is:
```
getStaticProps { params: { slug: [ '[p3', 'p4]' ] } }
getStaticProps { params: { slug: [ '[p1', 'p2]' ] } }
```

## Expected behavior

Output should be the same like with normal catch all `[...slug].tsx`:
```
getStaticProps { params: { slug: [ 'p1', 'p2' ] } }
getStaticProps { params: { slug: [ 'p3', 'p4' ] } }
```

## Environment
"next": "9.4.4",

### PR DESCRIPTION
**Pull request by Janpot**
Fixes https://github.com/vercel/next.js/issues/13524

To do:
- [x] fix dev mode
- [x] there's a ~route ordering or~ trailing slash issue with top level catch-all (current tests reflect that)
- [x] in this test `/get-static-paths/whatever` should fall back to `/[[...optionalName]].js` since `fallback` is `false` in its `getStaticPaths` method. ~Currently seems to 500~ must have been a glitch
- [x] add tests for `null`, `undefined` ~and `false`~ behavior as well (if decided these are valid)
- [x] ~add tests for string params as well~ this is not allowed for catch-all routes
- [x] test behavior when fallback is enabled and a top level catch-all exists

### CODE REVIEW

File: packages/next/build/utils.ts [hunk 1]
```diff
@@ -648,9 +648,12 @@ export async function buildStaticPaths(
             } in getStaticPaths for ${page}`
           )
         }
-
+        let replaced = `[${repeat ? '...' : ''}${validParamKey}]`
+        if (optional) {
+          replaced = `[${replaced}]`
```
Comment (Janpot) [inline packages/next/build/utils.ts:653]: @Timer having `optional` on the regexp group makes this quite straightforward, but this should be possible as well by constructing a regex.

File: test/integration/dynamic-optional-routing/pages/get-static-paths-undefined/[[...slug]].js [hunk 2]
```diff
@@ -0,0 +1,25 @@
+export async function getStaticPaths() {
+  return {
+    paths: [
+      {
+        params: {},
```
Comment (Timer) [inline test/integration/dynamic-optional-routing/pages/get-static-paths-undefined/[[...slug]].js:5]: Should this be allowed? IMO it'd be better to require the field be set to `false` or `null`.

File: packages/next/build/utils.ts [hunk 3]
```diff
@@ -648,13 +651,18 @@ export async function buildStaticPaths(
...
+        }
+        builtPage = builtPage
+          .replace(
+            replaced,
+            repeat
+              ? (paramValue as string[]).map(encodeURIComponent).join('/')
+              : encodeURIComponent(paramValue as string)
+          )
+          .replace(/(?!^)\/$/, '')
```
Comment (Timer) [inline packages/next/build/utils.ts:665]: What's the purpose of this regex?

File: packages/next/next-server/server/next-server.ts [hunk 4]
```diff
@@ -978,6 +978,9 @@ export default class Server {
       ? (req as any)._nextRewroteUrl
       : `${parseUrl(req.url || '').pathname!}`
 
+    // remove trailing slash
+    urlPathname = urlPathname.replace(/(?!^)\/$/, '')
```
Comment (Timer) [inline packages/next/next-server/server/next-server.ts:982]: Is this change out of scope re: your future PR fixing trailing slash behaviors? Or is it easier to just do this now?

I don't see adequate test coverage for this behavior.

**Review by Timer — CHANGES_REQUESTED** [review]

File: packages/next/next-server/server/next-server.ts (hunk 4 above)
Comment (Janpot) [reply packages/next/next-server/server/next-server.ts:982]: This is needed by both PRs for different purposes, and covered by two different tests, one in each PR.
tested here: https://github.com/vercel/next.js/pull/13559/files#diff-6a1ab8ce5323e3179038754e716d22baR98
and here: https://github.com/vercel/next.js/pull/13333/files#diff-4f5701207fbffaffe78cae6aa30571a4R56

File: test/integration/dynamic-optional-routing/pages/get-static-paths-undefined/[[...slug]].js (hunk 2 above)
Comment (Janpot) [reply test/integration/dynamic-optional-routing/pages/get-static-paths-undefined/[[...slug]].js:5]: sure, I just thought it would match nicely with what is passed to `getStaticProps `

File: packages/next/build/utils.ts (hunk 3 above)
Comment (Janpot) [reply packages/next/build/utils.ts:665]: It removes that trailing slash in case `paramValue` is empty. There may be a cleaner way.

```js
        builtPage
          .replace(
            '/get-static-paths/[[...slug]]',
            [].map(encodeURIComponent).join('/')
          )
        //  '/get-static-paths/'
```

File: packages/next/next-server/server/next-server.ts (hunk 4 above)
Comment (Timer) [reply packages/next/next-server/server/next-server.ts:982]: Please extend this test:
https://github.com/vercel/next.js/pull/13559/files#diff-6a1ab8ce5323e3179038754e716d22baR98

To include a subpath as well.

File: packages/next/build/utils.ts (hunk 3 above)
Comment (Timer) [reply packages/next/build/utils.ts:665]: Could we also filter the above array?
```js
(paramValue as string[]).filter(Boolean).map(encodeURIComponent).join('/')
```

Comment (Janpot) [reply packages/next/build/utils.ts:665]: the array is already empty, it's the slash between `/get-static-paths` and `[[...slug]]`.

File: packages/next/next-server/server/next-server.ts (hunk 4 above)
Comment (Janpot) [reply packages/next/next-server/server/next-server.ts:982]: like this test? https://github.com/vercel/next.js/pull/13559/files#diff-6a1ab8ce5323e3179038754e716d22baR104

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| buildDuration | 12.2s | 12.1s | -69ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ⚠️ +1.42 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.972 | 2.11 | ⚠️ +0.14 |
| / avg req/sec | 1267.99 | 1184.66 | -83.33 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.258 | 1.213 | -0.04 |
| /error-in-render avg req/sec | 1987.72 | 2060.33 | ⚠️ +72.61 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8679.js gzip | 10.5 kB | 10.5 kB | ⚠️ +10 B |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.93 kB | ⚠️ +7 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| index.html gzip | 927 B | 926 B | -1 B |
| link.html gzip | 937 B | 935 B | -2 B |
| withRouter.html gzip | 923 B | 923 B | ✓ |
| Overall change | 2.79 kB | 2.78 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..a18624191.js</strong></summary>

```diff
@@ -548,7 +548,8 @@
                 .replace(/\\([|\\{}()[\]^$+*?.-])/g, "$1") // eslint-disable-next-line no-sequences
             ] = {
               pos: groupIndex++,
-              repeat: isCatchAll
+              repeat: isCatchAll,
+              optional: isOptional
             };
             return isCatchAll
               ? isOptional
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..08.module.js</strong></summary>

```diff
@@ -470,7 +470,8 @@
                 .replace(/\\([|\\{}()[\]^$+*?.-])/g, "$1") // eslint-disable-next-line no-sequences
             ] = {
               pos: groupIndex++,
-              repeat: isCatchAll
+              repeat: isCatchAll,
+              optional: isOptional
             };
             return isCatchAll
               ? isOptional
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -30,7 +30,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -133,13 +133,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.3db71069b12a18624191.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.af1e06cc201c9a513ccb.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -30,7 +30,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -138,13 +138,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.3db71069b12a18624191.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.af1e06cc201c9a513ccb.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -30,7 +30,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -133,13 +133,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.3db71069b12a18624191.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.af1e06cc201c9a513ccb.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| buildDuration | 13.3s | 13.4s | ⚠️ +85ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ⚠️ +1.42 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8679.js gzip | 10.5 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..21ef.js gzip | N/A | 10.5 kB | N/A |
| Overall change | 57 kB | 57 kB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | N/A | 6.93 kB | N/A |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _error.js | 877 kB | 877 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 877 kB | 877 kB | ✓ |
| link.js | 915 kB | 915 kB | ⚠️ +28 B |
| routerDirect.js | 907 kB | 907 kB | ⚠️ +28 B |
| withRouter.js | 907 kB | 907 kB | ⚠️ +28 B |
| Overall change | 4.49 MB | 4.49 MB | ⚠️ +84 B |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| buildDuration | 12s | 11.9s | -87ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ⚠️ +1.42 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.096 | 2.075 | -0.02 |
| / avg req/sec | 1192.62 | 1204.8 | ⚠️ +12.18 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.197 | 1.266 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 2088.57 | 1975.21 | -113.36 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8679.js gzip | 10.5 kB | 10.5 kB | ⚠️ +10 B |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.93 kB | ⚠️ +7 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| index.html gzip | 927 B | 926 B | -1 B |
| link.html gzip | 937 B | 935 B | -2 B |
| withRouter.html gzip | 923 B | 923 B | ✓ |
| Overall change | 2.79 kB | 2.78 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..a18624191.js</strong></summary>

```diff
@@ -548,7 +548,8 @@
                 .replace(/\\([|\\{}()[\]^$+*?.-])/g, "$1") // eslint-disable-next-line no-sequences
             ] = {
               pos: groupIndex++,
-              repeat: isCatchAll
+              repeat: isCatchAll,
+              optional: isOptional
             };
             return isCatchAll
               ? isOptional
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..08.module.js</strong></summary>

```diff
@@ -470,7 +470,8 @@
                 .replace(/\\([|\\{}()[\]^$+*?.-])/g, "$1") // eslint-disable-next-line no-sequences
             ] = {
               pos: groupIndex++,
-              repeat: isCatchAll
+              repeat: isCatchAll,
+              optional: isOptional
             };
             return isCatchAll
               ? isOptional
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -30,7 +30,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -133,13 +133,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.3db71069b12a18624191.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.af1e06cc201c9a513ccb.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -30,7 +30,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -138,13 +138,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.3db71069b12a18624191.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.af1e06cc201c9a513ccb.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -30,7 +30,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -133,13 +133,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.3db71069b12a18624191.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.af1e06cc201c9a513ccb.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| buildDuration | 13s | 13.3s | ⚠️ +262ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ⚠️ +1.42 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8679.js gzip | 10.5 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..21ef.js gzip | N/A | 10.5 kB | N/A |
| Overall change | 57 kB | 57 kB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | N/A | 6.93 kB | N/A |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _error.js | 877 kB | 877 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 877 kB | 877 kB | ✓ |
| link.js | 915 kB | 915 kB | ⚠️ +28 B |
| routerDirect.js | 907 kB | 907 kB | ⚠️ +28 B |
| withRouter.js | 907 kB | 907 kB | ⚠️ +28 B |
| Overall change | 4.49 MB | 4.49 MB | ⚠️ +84 B |

</details>

</details>

**Review by Timer — APPROVED** [review]
Excellent work, thank you!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| buildDuration | 12s | 12.3s | ⚠️ +362ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ⚠️ +1.42 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.1 | 2.108 | ⚠️ +0.01 |
| / avg req/sec | 1190.45 | 1185.89 | -4.56 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.219 | 1.2 | -0.02 |
| /error-in-render avg req/sec | 2050.28 | 2083.76 | ⚠️ +33.48 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8679.js gzip | 10.5 kB | 10.5 kB | ⚠️ +10 B |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.93 kB | ⚠️ +7 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| index.html gzip | 927 B | 926 B | -1 B |
| link.html gzip | 937 B | 935 B | -2 B |
| withRouter.html gzip | 923 B | 923 B | ✓ |
| Overall change | 2.79 kB | 2.78 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..a18624191.js</strong></summary>

```diff
@@ -548,7 +548,8 @@
                 .replace(/\\([|\\{}()[\]^$+*?.-])/g, "$1") // eslint-disable-next-line no-sequences
             ] = {
               pos: groupIndex++,
-              repeat: isCatchAll
+              repeat: isCatchAll,
+              optional: isOptional
             };
             return isCatchAll
               ? isOptional
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..08.module.js</strong></summary>

```diff
@@ -470,7 +470,8 @@
                 .replace(/\\([|\\{}()[\]^$+*?.-])/g, "$1") // eslint-disable-next-line no-sequences
             ] = {
               pos: groupIndex++,
-              repeat: isCatchAll
+              repeat: isCatchAll,
+              optional: isOptional
             };
             return isCatchAll
               ? isOptional
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -30,7 +30,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -133,13 +133,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.3db71069b12a18624191.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.af1e06cc201c9a513ccb.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -30,7 +30,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -138,13 +138,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.3db71069b12a18624191.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.af1e06cc201c9a513ccb.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -30,7 +30,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -133,13 +133,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.3db71069b12a18624191.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.af1e06cc201c9a513ccb.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.98d04be1fd209669b708.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.41641d95dc96d5d4377a.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.3s | -337ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ⚠️ +1.42 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8679.js gzip | 10.5 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..21ef.js gzip | N/A | 10.5 kB | N/A |
| Overall change | 57 kB | 57 kB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | N/A | 6.93 kB | N/A |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js optional-static-paths | Change |
| - | - | - | - |
| _error.js | 877 kB | 877 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 877 kB | 877 kB | ✓ |
| link.js | 915 kB | 915 kB | ⚠️ +28 B |
| routerDirect.js | 907 kB | 907 kB | ⚠️ +28 B |
| withRouter.js | 907 kB | 907 kB | ⚠️ +28 B |
| Overall change | 4.49 MB | 4.49 MB | ⚠️ +84 B |

</details>

</details>
