### PR TITLE
Turbopack: allow resolving TS files in tailwind config

### LINKED ISSUE #87898: Tailwind config throws `Module not found` on Next.js 16.1.1 (works on 16.0)
Hello! I have some custom Tailwind v3 plugins that I import in my `tailwind.config.ts` file. After upgrading to version 16.1, I began encountering `Module not found` errors. I have created a reproduction below.

### Link to the code that reproduces this issue

https://github.com/carloitaben/test-repro-next-16-tw

### To Reproduce

1. `pnpm i`
2. `pnpm dev`
3. Open http://localhost:3000

### Current vs. Expected behavior

With Next.js 16.1.1:
```
⚠ ./tailwind.config.ts:2:1
Module not found: Can't resolve './src/lib/tailwind'
  1 | import type { Config } from "tailwindcss";
> 2 | import { someCustomPlugin } from "./src/lib/tailwind";
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  3 |
  4 | export default {
  5 |   content: ["./src/**/*.{ts,tsx}"],
```
Image

Downgrading to 16.0.10 or adding the `--webpack` flag removes the errors:
Image

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: 9.15.9
Relevant Packages:
  next: 16.1.1 // Latest available version is detected (16.1.1).
  eslint-config-next: N/A
  react: 19.2.3
  react-dom: 19.2.3
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

The error does not seem to break the build, and the code continues to function. I believe this is a Turbopack issue introduced in this minor version as running the scripts with the `--webpack` flags removes the error.

I've also tested this on the latest canary version (currently `16.1.1-canary.8`), which exhibits the same behavior.

### PR DESCRIPTION
**Pull request by mischnic**
A regression from https://github.com/vercel/next.js/issues/86576

Closes https://github.com/vercel/next.js/issues/87898
Closes PACK-6421

### CODE REVIEW

**Comment by mischnic** [comment]
* **#90046** <a href="https://app.graphite.com/github/pr/vercel/next.js/90046?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/vercel/next.js/90046?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: turbopack/crates/turbopack/src/lib.rs [hunk 1]
```diff
@@ -920,9 +920,15 @@ async fn process_default_internal(
...
+    resolve_typescript: bool,
 ) -> Result<Vc<ModuleAssetContext>> {
+    let mut extensions = vec![rcstr!(".js"), rcstr!(".node"), rcstr!(".json")];
+    if resolve_typescript {
+        extensions.insert(0, rcstr!(".ts"));
+    }
+
     let resolve_options = ResolveOptionsContext {
-        enable_node_native_modules: true,
+        custom_extensions: Some(extensions),
```
Comment (lukesandberg) [inline turbopack/crates/turbopack/src/lib.rs:904]: why disable node_native_modules?

**Review by lukesandberg — APPROVED** [review]

File: turbopack/crates/turbopack/src/lib.rs (hunk 1 above)
Comment (mischnic) [reply turbopack/crates/turbopack/src/lib.rs:904]: it's ignored anyway when providing `custom_extensions`
