### PR TITLE
Example for GraphQL server with API routes

### LINKED ISSUE #7777: [Next 9.0.0] GraphQL endpoint with apollo-server-micro doesn't work
# Bug report

## Describe the bug

Unable to load GraphQL Playground / endpoints in `/pages/api` with a lambda using `apollo-server-micro`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [https://github.com/yoongfook/nextjs9-apollo](https://github.com/yoongfook/nextjs9-apollo)
2. Install and run yarn dev
3. Go to /api/basic - `works!`
4. Go to /api/micro - `works!`
5. Go to /api/apollo-server-micro - unable to load schema, unable to make query, mutation

## Expected behavior

Go to /api/apollo-server-micro - able to load schema, make query, mutation

## Screenshots

image

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of Next.js: 9.0.0

### PR DESCRIPTION
**Pull request by huv1k**
Closes #7777

### CODE REVIEW

File: examples/api-routes-graphql/pages/index.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+  </div>
+)
+
+Index.getInitialProps = async () => {
+  const response = await fetch('http://localhost:3000/api/graphql', {
+    method: 'POST',
+    headers: {
+      'Content-type': 'application/json'
+    },
+    body: JSON.stringify({ query: '{users{name}}' })
```
Comment (lfades) [inline examples/api-routes-graphql/pages/index.js]:
```suggestion
    body: JSON.stringify({ query: '{ users { name } }' })
```
is less confusing this way.

**Review by lfades — APPROVED** [review]

**Comment by Prabhakar-17** [comment]
@lfades @huv1k how does the nextjs server handles the api route in this case because we are creating a new apollo server and a handler that maps to the api/graphql route?
