### PR TITLE
bug: Fields truncated when submitting form using Server Actions

### LINKED ISSUE #59277: bug: serverActions.bodySizeLimit is ignored
### Link to the code that reproduces this issue

https://github.com/TryingToImprove/next-app-router-body-size-issue

### To Reproduce

1. Start the application
2. Click submit button
3. It should not throw a error because the data posted is not the same size as what is expected

### Current vs. Expected behavior

Should not fail - `bodySizeLimit` should work

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.17.0
  npm: N/A
  Yarn: N/A
  pnpm: 8.11.0
Relevant Packages:
  next: 14.0.4-canary.40
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

Relevant code is here: https://github.com/TryingToImprove/next-app-router-body-size-issue/commit/6efd384f55d30fcdb26bc72a2252689c0f44e562

### PR DESCRIPTION
**Pull request by TryingToImprove**
When using Server Actions with a form the fields are getting truncated at 1MB because of `busboy`'s default `fieldSize` limit of 1MB.

This PR tries to solve https://github.com/vercel/next.js/issues/59277 however there is a mismatch about `fieldSize` and `bodySize`. I have tried creating a PR for `busboy` https://github.com/mscdex/busboy/pull/351 to allow configuring a max size for the entire body.

### TODO:

- [ ] Figure out if this is acceptable
- [ ] Throw error when `bodySizeLimit` is hit.

Fixes #59277, closes #61462.

### CODE REVIEW

File: packages/next/src/server/app-render/action-handler.ts [hunk 1]
```diff
@@ -463,8 +463,15 @@ export async function handleAction({
...
           if (isFetchAction) {
+            const readableLimit = serverActions?.bodySizeLimit ?? '1 MB'
+            const limit = require('next/dist/compiled/bytes').parse(
+              readableLimit
+            )
             const busboy = require('busboy')
-            const bb = busboy({ headers: req.headers })
+            const bb = busboy({
+              headers: req.headers,
+              limits: { fieldSize: limit },
```
Comment (TryingToImprove) [inline packages/next/src/server/app-render/action-handler.ts:473]: Unsure what to do here since `busboy` is pr. field whereas `next` is for the whole body.

File: test/e2e/app-dir/actions/app-action-size-limit-invalid.test.ts [hunk 2]
```diff
@@ -117,6 +117,42 @@ createNextDescribe(
...
+        await browser.elementByCss('#size-1mb').click()
+
+        await check(() => {
+          return logs.some((log) => log.includes('size = 1048576')) ? 'yes' : ''
+        }, 'yes')
+
+        await browser.elementByCss('#size-2mb').click()
+        await check(() => {
+          return logs.some((log) => log.includes('size = 2097152')) ? 'yes' : ''
+        }, 'yes')
```
Comment (shuding) [inline test/e2e/app-dir/actions/app-action-size-limit-invalid.test.ts:154]: How about the 3mb one?

Comment (TryingToImprove) [reply test/e2e/app-dir/actions/app-action-size-limit-invalid.test.ts:154]: When clicking the 3mb I think it said `size = 2097152` since it is truncating the payload.. 

I guess it should throw instead, but busboy does not support that.

**Review by shuding — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | TryingToImprove/next.js fields-truncated-when-submitting-form | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.6s | N/A |
| buildDurationCached | 7.3s | 6.1s | N/A |
| nodeModulesSize | 198 MB | 198 MB | ⚠️ +8.77 kB |
| nextStartRea..uration (ms) | 429ms | 434ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | TryingToImprove/next.js fields-truncated-when-submitting-form | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 30.5 kB | 30.5 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | N/A |
| 8299-HASH.js gzip | 5.04 kB | 5.04 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 242 B | 241 B | N/A |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 45.4 kB | 45.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | TryingToImprove/next.js fields-truncated-when-submitting-form | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | TryingToImprove/next.js fields-truncated-when-submitting-form | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.21 kB | 4.21 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.57 kB | 6.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | TryingToImprove/next.js fields-truncated-when-submitting-form | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | TryingToImprove/next.js fields-truncated-when-submitting-form | Change |
| - | - | - | - |
| index.html gzip | 529 B | 528 B | N/A |
| link.html gzip | 540 B | 541 B | N/A |
| withRouter.html gzip | 523 B | 523 B | ✓ |
| Overall change | 523 B | 523 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | TryingToImprove/next.js fields-truncated-when-submitting-form | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.1 kB | 95.1 kB | N/A |
| page.js gzip | 3.05 kB | 3.05 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | TryingToImprove/next.js fields-truncated-when-submitting-form | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 625 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | TryingToImprove/next.js fields-truncated-when-submitting-form | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | N/A |
| app-page-exp..prod.js gzip | 96.6 kB | 96.6 kB | N/A |
| app-page-tur..prod.js gzip | 98.3 kB | 98.3 kB | N/A |
| app-page-tur..prod.js gzip | 92.8 kB | 92.8 kB | N/A |
| app-page.run...dev.js gzip | 149 kB | 149 kB | N/A |
| app-page.run..prod.js gzip | 91.3 kB | 91.3 kB | N/A |
| app-route-ex...dev.js gzip | 21.3 kB | 21.3 kB | ✓ |
| app-route-ex..prod.js gzip | 15 kB | 15 kB | ✓ |
| app-route-tu..prod.js gzip | 15 kB | 15 kB | ✓ |
| app-route-tu..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| app-route.ru...dev.js gzip | 21 kB | 21 kB | ✓ |
| app-route.ru..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.52 kB | 9.52 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.8 kB | 9.8 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.52 kB | 9.52 kB | ✓ |
| pages-turbo...prod.js gzip | 22.3 kB | 22.3 kB | ✓ |
| pages.runtim...dev.js gzip | 22.9 kB | 22.9 kB | ✓ |
| pages.runtim..prod.js gzip | 22.3 kB | 22.3 kB | ✓ |
| server.runti..prod.js gzip | 50.6 kB | 50.6 kB | ✓ |
| Overall change | 249 kB | 249 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | TryingToImprove/next.js fields-truncated-when-submitting-form | Change |
| - | - | - | - |
| 0.pack gzip | 1.56 MB | 1.56 MB | N/A |
| index.pack gzip | 105 kB | 105 kB | ⚠️ +109 B |
| Overall change | 105 kB | 105 kB | ⚠️ +109 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: b8f2c11677e87f9877dd527d841aa7a60ab09375
