### PR TITLE
Fix external check for non-local next import

### LINKED ISSUE #25303: Imported next-server modules are duplicated, causing duplicate react contexts
### What version of Next.js are you using?

10.2.1

### What version of Node.js are you using?

16.1.0

### What browser are you using?

Chrome and Safari

### What operating system are you using?

macOS

### How are you deploying your application?

None

### Describe the Bug

We use `@apollo/client` to execute some graphQL queries during SSR: we do this in getServerSideProps, and most importantly by rendering the component tree before nextjs actually renders it on the server. A simplified example of how this looks is below:

```typescript
export function getServerSideProps(ctx) {
  // ....
     await renderToStringWithData(
        <RouterContext.Provider value={router}>
          <ApolloProvider client={apolloClient}>
             <Page {...props} />
          </ApolloProvider>
        </RouterContext.Provider >
      )
  // ...
}
```

Most importantly, because we use `useRouter` and render different components based on `query`, we create a dummy next router and pass it into the router provider:

```typescript
  const router = {
    query: ctx.query
  }
```

The router context itself is imported like so:
```typescript
import { RouterContext } from 'next/dist/next-server/lib/router-context'
```

This worked fine up until 10.2.1, where now calls on the server to `useRouter` return `null`.
After doing some debugging it turns out this is caused by the two different `router-context` modules being imported: One in our app, and one in `next/router`.
So whenever `useRouter` calls `useContext`, it looks up a different `RouterContext` than the `RouterContext` we imported, and thus returns null.

Previously in 10.2.0 these imported modules were the same, and we believe the PR that caused this new behaviour is https://github.com/vercel/next.js/pull/24603

The difference between the generated webpack imports is that on 10.2.0, they look like this:

```javascript
/* harmony import */ var next_dist_next_server_lib_router_context__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! next/dist/next-server/lib/router-context */ "next/dist/next-server/lib/router-context");
```

But on 10.2.1 it now becomes:

```javascript
/* harmony import */
var next_dist_next_server_lib_router_context__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! next/dist/next-server/lib/router-context */
"./node_modules/next/dist/next-server/lib/router-context.js");
```
`./node_modules` has been prefixed

`next/dist/client/router.js` imports the module as `require("../next-server/lib/router-context")`, so understandably webpack gives back two different modules, with two different contexts

### Expected Behavior

Importing modules from `next/dist/next-server/` should resolve to the same module as the modules used by next itself

### To Reproduce

https://github.com/bubba/next-webpack-import-bug.git

### PR DESCRIPTION
**Pull request by ijjk**
This is a follow-up to https://github.com/vercel/next.js/pull/24603 ensuring we maintain the previous behavior to correctly externalize non-local `next/dist/next-server` imports, an added test case has been added to ensure we prevent regressing on this behavior. 

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added

Fixes: https://github.com/vercel/next.js/issues/25303

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| buildDuration | 13.9s | 14s | ⚠️ +84ms |
| buildDurationCached | 3.9s | 3.8s | -34ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +386 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.534 | 2.457 | -0.08 |
| / avg req/sec | 986.61 | 1017.64 | +31.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.348 | 1.354 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1854.43 | 1846.45 | ⚠️ -7.98 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.4 kB | 19.4 kB | ✓ |
| webpack-HASH.js gzip | 994 B | 994 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.54 kB | 8.54 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| index.html gzip | 560 B | 560 B | ✓ |
| link.html gzip | 568 B | 568 B | ✓ |
| withRouter.html gzip | 556 B | 556 B | ✓ |
| Overall change | 1.68 kB | 1.68 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| buildDuration | 16.1s | 15.9s | -208ms |
| buildDurationCached | 4.9s | 4.9s | -22ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +386 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.4 kB | 19.4 kB | ✓ |
| webpack-HASH.js gzip | 994 B | 994 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.54 kB | 8.54 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.4 kB | 17.4 kB | ✓ |
| routerDirect.js | 17.4 kB | 17.4 kB | -2 B |
| withRouter.js | 17.4 kB | 17.4 kB | ✓ |
| Overall change | 107 kB | 107 kB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.6s | ⚠️ +79ms |
| buildDurationCached | 5.4s | 5.2s | -141ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +386 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.577 | 2.555 | -0.02 |
| / avg req/sec | 970.21 | 978.44 | +8.23 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.428 | 1.356 | -0.07 |
| /error-in-render avg req/sec | 1751.11 | 1844.11 | +93 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.25 kB | 7.25 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.74 kB | 3.74 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.38 kB | 9.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: 71e987a6a6089c909545a336f094f83ae09f457a

File: packages/next/build/webpack-config.ts [hunk 1]
```diff
@@ -738,12 +739,14 @@ export default async function getBaseWebpackConfig(
     if (baseRes !== res) {
       return
     }
+    const isNextExternal = res.match(/next[/\\]dist[/\\]next-server[/\\]/)
```
Comment (sokra) [inline packages/next/build/webpack-config.ts:742]:
```suggestion
    if (res.match(/next[/\\]dist[/\\]next-server[/\\]/)) {
      return `commonjs ${request}`
    }
```

I think this could be simplified to directly early exit here

Comment (sokra) [reply packages/next/build/webpack-config.ts:742]: Further above this regex is used `/next[/\\]dist[/\\]next-server[/\\](?!lib[/\\]router[/\\]router)/`. Does this make sense here to or is that unrelated?

Comment (ijjk) [reply packages/next/build/webpack-config.ts]: Yeah looks like we can just return right away if this matches here and we should exclude `lib/router/router` here too since that relies on `process.env` values being injected by webpack currently

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| buildDuration | 13s | 12.2s | -878ms |
| buildDurationCached | 3.4s | 3.3s | -140ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +422 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.481 | 2.25 | -0.23 |
| / avg req/sec | 1007.77 | 1111.11 | +103.34 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.332 | 1.294 | -0.04 |
| /error-in-render avg req/sec | 1877.13 | 1931.9 | +54.77 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.4 kB | 19.4 kB | ✓ |
| webpack-HASH.js gzip | 994 B | 994 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.54 kB | 8.54 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| index.html gzip | 560 B | 560 B | ✓ |
| link.html gzip | 568 B | 568 B | ✓ |
| withRouter.html gzip | 556 B | 556 B | ✓ |
| Overall change | 1.68 kB | 1.68 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| buildDuration | 13.9s | 13.8s | -132ms |
| buildDurationCached | 4s | 4.1s | ⚠️ +41ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +422 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.4 kB | 19.4 kB | ✓ |
| webpack-HASH.js gzip | 994 B | 994 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.54 kB | 8.54 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.4 kB | 17.4 kB | ✓ |
| routerDirect.js | 17.4 kB | 17.4 kB | ✓ |
| withRouter.js | 17.4 kB | 17.4 kB | ✓ |
| Overall change | 107 kB | 107 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| buildDuration | 10.7s | 11s | ⚠️ +259ms |
| buildDurationCached | 5.2s | 5s | -184ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +422 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.301 | 2.273 | -0.03 |
| / avg req/sec | 1086.7 | 1099.71 | +13.01 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.316 | 1.26 | -0.06 |
| /error-in-render avg req/sec | 1900.25 | 1984.74 | +84.49 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.25 kB | 7.25 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.74 kB | 3.74 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.38 kB | 9.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/next-external-check | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: 0a9d7e3d6bace585a722a5cc60ed8a83bbc3a92e

**Review by sokra — APPROVED** [review]
