### PR TITLE
[metadata] re-insert icons to head for streamed metadata

### LINKED ISSUE #76810: Streaming Metadata: Favicon Not Applied on Initial Load
### Link to the code that reproduces this issue

https://github.com/ryanburns23/nextjs-streaming-metadata-bug

### To Reproduce

1. Open the deployed [reproduction example](https://nextjs-streaming-metadata-bug.vercel.app/) in Chrome.
2. Wait approximately 1.5 seconds for the metadata to stream in. Observe that the favicon does not update.

Additional context:

- Clicking the button to navigate to "page2" correctly updates the favicon.
- This issue only occurs on the initial page load.

### Current vs. Expected behavior

Current behavior:

Next.js 15.2 introduced [Streaming Metadata](https://nextjs.org/blog/next-15-2#streaming-metadata). When using streaming metadata in a project with dynamic routes and dynamic favicons, Chrome doesn't apply the favicon upon initial load. While the metadata and tags are correctly streamed and appended to the end of the <body> tag once generated, Chrome fails to recognize and display the favicon initially.

Expected behavior:

The favicon should correctly update and display immediately after streaming metadata loads, even on initial page load.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020
  Available memory (MB): 98304
  Available CPU cores: 12
Binaries:
  Node: 22.13.0
  npm: 10.9.2
  Yarn: N/A
  pnpm: 10.2.0
Relevant Packages:
  next: 15.2.2-canary.0 // Latest available version is detected (15.2.2-canary.0).
  eslint-config-next: N/A
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.8.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Metadata

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

- Tested with Chrome 133.0.6943.142
- This appears to be specifically related to Chrome's handling of dynamically streamed favicons.
- Subsequent navigations to other routes with dynamic metadata correctly update the favicon, confirming that this issue is isolated to the initial page load scenario. Notably, the key difference during subsequent navigations is that metadata tags are appended directly to the `<head>`, rather than the `<body>` as seen on initial load. A potential solution could involve ensuring that initially streamed metadata tags are also appended to the `<head>` instead of the `<body>`.
- While potentially a browser-level issue, it may be valuable for Next.js to investigate possible workarounds or mitigations.

### PR DESCRIPTION
**Pull request by huozhi**
### What

Re-insert the metadata icons under body tag into head tag to ensure they can be proper displayed.

### Why

* For chromium based browsers (Chrome, Edge, etc.) and Safari, icons need to stay under `<head>` to be picked up by the browser. Firefox doesn't have this requirement.
* Firefox will always render svg > icon > png, so it doesn't matter to it.

Made a test in https://icons-order-test.vercel.app/, you can play with the test cases here. These links can see the comparsion of the approach in the this PR.

During deployment it's very hard to verify Safari as it's pretty broken. But deploymet works well.
After we re-insert the icon from body into head, they can be properly displayed across all the browsers.

Note: We insert the script during streaming rather than using a jsx element right after metadata to avoid the hydration errors

Closes #76810
Closes NDX-951

### CODE REVIEW

**Comment by huozhi** [comment]
* **#76915** <a href="https://app.graphite.dev/github/pr/vercel/next.js/76915?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/vercel/next.js/76915?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8cf478f3054df550dc5e7ef3f47c25b361261ba6

`pnpm test-dev test/e2e/app-dir/metadata-icons/metadata-icons.test.ts`
- app-dir - metadata-icons > should re-insert the apple icons into the head after navigation

<details>
<summary>Expand output</summary>

  ● app-dir - metadata-icons › should re-insert the apple icons into the head after navigation

    expect(received).toEqual(expected) // deep equality

    - Expected  - 4
    + Received  + 1

    - Array [
    -   "/favicon.ico",
    -   "/star.png",
    - ]
    + Array []

      60 |     // In non-headless mode, the icons are deduped;
      61 |     // In headless mode, the icons are not deduped
    > 62 |     expect(iconUrls.slice(2)).toEqual(['/favicon.ico', '/star.png'])
         |                               ^
      63 |
      64 |     // navigate back
      65 |     await browser.elementByCss('#custom-icon-link').click()

      at Object.toEqual (e2e/app-dir/metadata-icons/metadata-icons.test.ts:62:31)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: packages/next/src/server/stream-utils/node-web-streams-helper.ts [hunk 1]
```diff
@@ -378,6 +389,22 @@ function createMergedTransformStream(
...
+ * to be picked up by the browser. Firefox doesn't have this requirement.
+ *
+ * Firefox won't work if we insert those icons into head, it will still pick up default favicon.ico.
+ * Because of this limitation, we just don't insert for firefox and leave the default behavior for it.
+ *
+ */
+const createReinsertIconScript = (nonce: string | undefined) => {
+  return `\
+<script ${typeof nonce === 'string' ? `nonce="${nonce}"` : ''}>\
+!/firefox/i.test(navigator.userAgent) && \
```
Comment (gnoff) [inline packages/next/src/server/stream-utils/node-web-streams-helper.ts:403]: feel like we can just do this in FF too and not encode the browser test. it works fine in FF too

File: packages/next/src/server/stream-utils/node-web-streams-helper.ts [hunk 2]
```diff
@@ -648,17 +704,26 @@ export async function continueDynamicHTMLResume(
...
+          reinsertIcons: false,
+        })
+      )
       // Insert generated metadata to body
       .pipeThrough(
-        createHeadInsertionTransformStream(getServerInsertedMetadata)
+        createHeadInsertionTransformStream(getServerInsertedMetadata, {
+          nonce,
+          reinsertIcons: true,
+        })
```
Comment (gnoff) [inline packages/next/src/server/stream-utils/node-web-streams-helper.ts:726]: why can't `getServerInsertedMetadata` just return the script as part of the html it produces. I wasn't expecting that any new config here in the stream handler would actually be necessary. Ideally it's a black box and the fact we have this insertion instruction is just part of what the server inserted metadata chooses to encode

File: packages/next/src/server/stream-utils/node-web-streams-helper.ts (hunk 1 above)
Comment (huozhi) [reply packages/next/src/server/stream-utils/node-web-streams-helper.ts:403]: firefox will still show the favicon if we do that. example case: navigate from home page to https://icons-order-test.vercel.app/insert-icon-with-script.html

File: packages/next/src/server/app-render/metadata-insertion/create-server-inserted-metadata.tsx [hunk 3]
```diff
@@ -34,7 +42,18 @@ export function createServerInsertedMetadata() {
       metadataToFlush = metadataResolver()
       const html = await renderToString({
         renderToReadableStream,
-        element: <>{metadataToFlush}</>,
+        element: (
+          <>
+            {metadataToFlush}
+            <script
+              defer
```
Comment (gnoff) [inline packages/next/src/server/app-render/metadata-insertion/create-server-inserted-metadata.tsx:49]: why defer? this won't run until the document has completely loaded. But all of the icons we want to hoist are know to be in the document already. this can just be a sync function.

File: packages/next/src/server/app-render/metadata-insertion/create-server-inserted-metadata.tsx [hunk 4]
```diff
@@ -34,7 +42,18 @@ export function createServerInsertedMetadata() {
...
+              nonce={nonce}
+              dangerouslySetInnerHTML={{
+                __html: REINSERT_ICON_SCRIPT,
+              }}
```
Comment (gnoff) [inline packages/next/src/server/app-render/metadata-insertion/create-server-inserted-metadata.tsx:53]: can you double check if this is actually needed? we changed React to allow a lot more stuff to be encoded properly as just string children of things like scripts and style tags. This is less safe in that we do zero escaping of the content. I know we control the script so it's only risky if we put something dangerous in the script src itself but still best maybe to avoid it if we can

File: packages/next/src/server/stream-utils/node-web-streams-helper.ts [hunk 5]
```diff
@@ -609,6 +610,7 @@ type ContinueStaticPrerenderOptions = {
   inlinedDataStream: ReadableStream<Uint8Array>
   getServerInsertedHTML: () => Promise<string>
   getServerInsertedMetadata: () => Promise<string>
+  nonce: string | undefined
```
Comment (gnoff) [inline packages/next/src/server/stream-utils/node-web-streams-helper.ts:613]: aren't all these nonce arguments unecessary now?

File: packages/next/src/server/app-render/metadata-insertion/create-server-inserted-metadata.tsx [hunk 6]
```diff
@@ -6,7 +6,15 @@ import {
...
 import { renderToString } from '../render-to-string'
 
-export function createServerInsertedMetadata() {
+/**
+ * For chromium based browsers (Chrome, Edge, etc.) and Safari,
+ * icons need to stay under <head> to be picked up by the browser.
+ *
+ */
+const REINSERT_ICON_SCRIPT = `\
+document.querySelectorAll('body link[rel="icon"], body link[rel="apple-touch-icon"]').forEach(el => document.head.appendChild(el.cloneNode()))`
```
Comment (gnoff) [inline packages/next/src/server/app-render/metadata-insertion/create-server-inserted-metadata.tsx:15]: still cloning

**Review by gnoff — CHANGES_REQUESTED** [review]

File: packages/next/src/server/app-render/metadata-insertion/create-server-inserted-metadata.tsx [hunk 7]
```diff
@@ -6,7 +6,15 @@ import {
 } from '../../../shared/lib/server-inserted-metadata.shared-runtime'
 import { renderToString } from '../render-to-string'
 
-export function createServerInsertedMetadata() {
+/**
+ * For chromium based browsers (Chrome, Edge, etc.) and Safari,
+ * icons need to stay under <head> to be picked up by the browser.
+ *
+ */
+const REINSERT_ICON_SCRIPT = `\
```
Comment (gnoff) [inline packages/next/src/server/app-render/metadata-insertion/create-server-inserted-metadata.tsx:14]: what's the point of this slash?

Comment (huozhi) [reply packages/next/src/server/app-render/metadata-insertion/create-server-inserted-metadata.tsx:14]: it's nothing but just be able to let you start the string in the new line for appearance 😂
image

Comment (gnoff) [reply packages/next/src/server/app-render/metadata-insertion/create-server-inserted-metadata.tsx:14]: TIL

**Review by gnoff — APPROVED** [review]
