### PR TITLE
fix(navigation): allow `useSelectedLayoutSegment(s)` in Pages Router

### LINKED ISSUE #61464: useSelectedLayoutSegments fails in Pages router
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/pedantic-perlman-msccx8

### To Reproduce

Call the hook anywhere in a pages router rendering tree.

In the codesandbox, visit `/test` in the preview browser to see the error

### Current vs. Expected behavior

Given that almost every method from the `next/navigation` package works in pages router with a compatibility layer, and this seems to be the only equivalent for getting the value returned by the old router's `router.pathname` property, I would expect this to work in pages router as well. Otherwise incremental migration is hard because you can't replace uses of `next/router` that need the `pathname` property, except by passing it down via custom context (which I have done)

If this hook is not intended to work in pages router, then it should provide a better error stating that.

Currently the error you receive is 
```
TypeError: Cannot destructure property 'tree' of '(0 , _react.useContext)(...)' as it is null.
```
which is unhelpful.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.1.1-canary.25 // Latest available version is detected (14.1.1-canary.25).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

_No response_

<sub>[NEXT-2506](https://linear.app/vercel/issue/NEXT-2506/useselectedlayoutsegments-fails-in-pages-router)</sub>

### PR DESCRIPTION
**Pull request by balazsorban44**
### What?

Do not fail when `useSelectedLayoutSegment` or `useSelectedLayoutSegments` APIs are called in the Pages Router.

### Why?

This makes migration easier and creates consistency with our other App Router-specific APIs that inherit the same behavior.

### How?

Similar to #47490, we return `null` if there is no Layout context (indicating being in Pages Router)

Types are also overridden in the navigation compact module declaration which kicks in during start to correct the types if we detect a `pages/` directory.

Note to reviewer: #47490 didn't add a test, so I added one top-level, let me know if you have a better suggestion for placing.

Closes NEXT-2506
Fixes #61464

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8a45bdcf0a2a3c20ec5e0f3369bd05c4a2851f5f

`pnpm test-dev test/e2e/useselectedlayoutsegment-s-in-pages-router/useselectedlayoutsegment-s-in-pages-router.test.ts` (PPR)
- useSelectedLayoutSegment(s) in Pages Router > should work using browser

<details>
<summary>Expand output</summary>

  ● useSelectedLayoutSegment(s) in Pages Router › should work using browser

    expect(received).toBe(expected) // Object.is equality

    Expected: "Hello World"
    Received: ""

       6 |   it('should work using browser', async () => {
       7 |     const browser = await next.browser('/')
    >  8 |     expect(await browser.elementByCss('body').text()).toBe('Hello World')
         |                                                       ^
       9 |   })
      10 | })
      11 |

      at Object.toBe (e2e/useselectedlayoutsegment-s-in-pages-router/useselectedlayoutsegment-s-in-pages-router.test.ts:8:55)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/use-selected-layout-segment-s-pages | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.8s | N/A |
| buildDurationCached | 7.7s | 6.4s | N/A |
| nodeModulesSize | 197 MB | 197 MB | ⚠️ +2.32 kB |
| nextStartRea..uration (ms) | 406ms | 403ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/use-selected-layout-segment-s-pages | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 30.5 kB | 30.5 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | N/A |
| 8299-HASH.js gzip | 5.04 kB | 5.04 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 242 B | 242 B | ✓ |
| main-HASH.js gzip | 32.1 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 45.6 kB | 45.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/use-selected-layout-segment-s-pages | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/use-selected-layout-segment-s-pages | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.2 kB | 4.2 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.56 kB | 6.56 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/use-selected-layout-segment-s-pages | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 485 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/use-selected-layout-segment-s-pages | Change |
| - | - | - | - |
| index.html gzip | 527 B | 527 B | ✓ |
| link.html gzip | 540 B | 540 B | ✓ |
| withRouter.html gzip | 523 B | 522 B | N/A |
| Overall change | 1.07 kB | 1.07 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/use-selected-layout-segment-s-pages | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95 kB | 95 kB | N/A |
| page.js gzip | 3.05 kB | 3.06 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/use-selected-layout-segment-s-pages | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 626 B | 622 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/use-selected-layout-segment-s-pages | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | ✓ |
| app-page-exp..prod.js gzip | 96.7 kB | 96.7 kB | ✓ |
| app-page-tur..prod.js gzip | 98.5 kB | 98.5 kB | ✓ |
| app-page-tur..prod.js gzip | 92.9 kB | 92.9 kB | ✓ |
| app-page.run...dev.js gzip | 150 kB | 150 kB | ✓ |
| app-page.run..prod.js gzip | 91.4 kB | 91.4 kB | ✓ |
| app-route-ex...dev.js gzip | 21.3 kB | 21.3 kB | ✓ |
| app-route-ex..prod.js gzip | 15 kB | 15 kB | ✓ |
| app-route-tu..prod.js gzip | 15 kB | 15 kB | ✓ |
| app-route-tu..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| app-route.ru...dev.js gzip | 20.9 kB | 20.9 kB | ✓ |
| app-route.ru..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.51 kB | 9.51 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.79 kB | 9.79 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.51 kB | 9.51 kB | ✓ |
| pages-turbo...prod.js gzip | 22.3 kB | 22.3 kB | ✓ |
| pages.runtim...dev.js gzip | 23 kB | 23 kB | ✓ |
| pages.runtim..prod.js gzip | 22.3 kB | 22.3 kB | ✓ |
| server.runti..prod.js gzip | 50.6 kB | 50.6 kB | ✓ |
| Overall change | 950 kB | 950 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/use-selected-layout-segment-s-pages | Change |
| - | - | - | - |
| 0.pack gzip | 1.56 MB | 1.56 MB | N/A |
| index.pack gzip | 105 kB | 105 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>2453-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 8a45bdcf0a2a3c20ec5e0f3369bd05c4a2851f5f

File: packages/next/src/client/components/navigation.ts [hunk 1]
```diff
@@ -211,7 +211,10 @@ function useSelectedLayoutSegments(
   parallelRouteKey: string = 'children'
 ): string[] {
```
Comment (huozhi) [inline packages/next/src/client/components/navigation.ts:212]:
```suggestion
): string[] | null {
```

File: packages/next/src/client/components/navigation.ts [hunk 2]
```diff
@@ -211,7 +211,10 @@ function useSelectedLayoutSegments(
...
   clientHookInServerComponentError('useSelectedLayoutSegments')
-  const { tree } = useContext(LayoutRouterContext)
+  const tree = useContext(LayoutRouterContext)?.tree
+  // @ts-expect-error This only happens in `pages`. Type is overwritten in navigation.d.ts
```
Comment (huozhi) [inline packages/next/src/client/components/navigation.ts:215]:
```suggestion
  // This only happens in `pages`. Type is overwritten in navigation.d.ts
```

File: packages/next/src/client/components/navigation.ts (hunk 1 above)
Comment (balazsorban44) [reply packages/next/src/client/components/navigation.ts:212]: This is not the correct place for this type change. We don't want to override the type if you only use App Router, hence we only do it in the compat types file

File: packages/next/src/client/components/navigation.ts (hunk 2 above)
Comment (balazsorban44) [reply packages/next/src/client/components/navigation.ts:215]: See https://github.com/vercel/next.js/pull/62584#discussion_r1507239370

Comment (huozhi) [reply packages/next/src/client/components/navigation.ts:215]: we can make `LayoutRouterContext` 's value could also return null, like what we did for `SearchParamsContext` and `AppRouterContext`. 

```ts
export const LayoutRouterContext = React.createContext<{
  childNodes: CacheNode['parallelRoutes']
  tree: FlightRouterState
  url: string
} | null>(null as any)
```

then we can return null when context is null


```ts
function useSelectedLayoutSegments(
  parallelRouteKey: string = 'children'
): string[] {
  clientHookInServerComponentError('useSelectedLayoutSegments')
  const layoutRouterContext = useContext(LayoutRouterContext)
  
  if (!layoutRouterContext) {
    // for pages router
    return null as unknown as string[]
  }

  return getSelectedLayoutSegmentPath(layoutRouterContext.tree, parallelRouteKey)
}
```

**Review by huozhi — APPROVED** [review]
