### PR TITLE
Uses the PnP API when available

### LINKED ISSUE #8659: PnP breaks the `externals` detection
# Bug report

## Describe the bug (tl;dr)

Using `resolve` through a prebuilt binary instead of the regular one prevents it from resolving files through PnP, causing it to bake all the third-party files into the SSR bundle:

https://github.com/zeit/next.js/blob/canary/packages/next/build/webpack-config.ts#L9

A derived bug is that contexts & hooks don't work in SSR mode, because they expect the React instance to be unique across the Node resolution and the Webpack resolution (which isn't the case since `react` and `react-dom` aren't `externals` anymore).

## Describe the bug

I noticed that when operating under PnP, Next causes React to crash when using hooks (with [this error](https://reactjs.org/warnings/invalid-hook-call-warning.html)). The problems stems from the following line:

https://github.com/zeit/next.js/blob/e9ffb41462beff7bed9e27717e9558d42f48d17b/packages/next/build/webpack-config.ts#L317-L323

What should have happened is this. This assumes the SSR mode, please feel free to correct me:

- Next (the Node process) generates a Webpack bundle for all/some of the routes.
- Then it requires `react-dom/server`, which requires `react`. So far so good.
- Then it requires the Webpack bundle, and triggers a build for the routes it contains.
- Then Webpack page requires `react`. Since it got marked as being stored within a `node_modules` directory, it should have been marked as external, and thus would have been required through the Node resolution, at runtime, hence sharing the same instance as the rest of the server.

So what prevents this from working?

- In order to support PnP, `resolve` uses a "pseudo-hook". It's a specific file that, when required, a resolver wrapper is allowed to replace by whatever it wants (with the idea that it will change the default options depending on the context). The PR that introduced it is here: https://github.com/browserify/resolve/pull/174

- For some reason, Next [is compiling `resolve` through `ncc`](https://github.com/zeit/next.js/blob/canary/packages/next/build/webpack-config.ts#L9). This causes the file I referenced to disappear entirely, and thus PnP cannot hook itself into it without help.

## Potential fixes

From the best to the less practical:

- Next could maybe stop precompiling `resolve`? I'm not sure why it works that way (cc @timneutkens, https://github.com/zeit/next.js/pull/6771)

- Next could just use [`createRequire`](https://nodejs.org/api/modules.html#modules_module_createrequire_filename) to get an handle on `require.resolve` from the perspective of a particular location on the disk, which would work in both contexts (maybe there isn't a need for `resolve` after all?).

- Next could just call directly the PnP API when operating under PnP (`if (process.versions.pnp) require('pnpapi').resolveRequest(request).includes('node_modules')` or similar).

- Next could explicitly pass the PnP options to `resolve` to compensate for Yarn not being able to inject the right settings. They are defined [here](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-pnp/sources/loader/applyPatch.ts#L34-L71).

- Next could use `enhanced-resolve` with the actual Webpack resolution configuration used by Webpack (which would then include `PnpWebpackPlugin`). But frankly it might require a hefty refactoring, probably not the most practical solution in the lot.

- `resolve` could just detect PnP by default without us having to hook into it. I'll open an issue to discuss it, but it might take a while before a consensus is reached.

## Screenshots

image

### PR DESCRIPTION
**Pull request by arcanis**
Fix #8659 

When available, the PnP API is used instead of the `resolve` package to find out if the specified package is resolvable from the top-level application (similar to what the regular codepath does).

Speaking of which, I'm not sure this logic is 100% correct - if the app depends on `next` and `Foo`, and if `next` depends on `Foo` and uses it in the generated documents, it won't be bundled into the app (which will then use the top-level version instead of the original one) because it will be resolvable from the basedir. Not entirely sure what's the right fix given Next's architecture. Not relevant to this diff anyway 😊

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| buildDuration | 22.5s | 21.5s | -1s |
| nodeModulesSize | 42.4 MB | 42.4 MB | -20.1 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.2 kB | -1 B |
| main-HASH.js gzip | 6.64 kB | 6.64 kB | -1 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b2b5f78d65..2b8407376.js | 21.9 kB | N/A | N/A |
| 16b2b5f78d65..7376.js gzip | 7.81 kB | N/A | N/A |
| 427650be2c1b..799a4e38e.js | 43.1 kB | N/A | N/A |
| 427650be2c1b..e38e.js gzip | 15.4 kB | N/A | N/A |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 817ef1005ebf..2b8407376.js | N/A | 21.9 kB | N/A |
| 817ef1005ebf..7376.js gzip | N/A | 7.81 kB | N/A |
| c498350d8f10..799a4e38e.js | N/A | 43.1 kB | N/A |
| c498350d8f10..e38e.js gzip | N/A | 15.4 kB | N/A |
| Overall change | 210 kB | 210 kB | -1 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | -1 B |
| main-HASH.module.js gzip | 6.38 kB | 6.38 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 427650be2c1b..f0.module.js | 45.5 kB | N/A | N/A |
| 427650be2c1b..dule.js gzip | 16.5 kB | N/A | N/A |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| c498350d8f10..f0.module.js | N/A | 45.5 kB | N/A |
| c498350d8f10..dule.js gzip | N/A | 16.5 kB | N/A |
| Overall change | 189 kB | 189 kB | -1 B |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ⚠️ +1 B |
| routerDirect.js | 433 B | 434 B | ⚠️ +1 B |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 840 B | -1 B |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 805 B | ⚠️ +1 B |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 430 B | ⚠️ +1 B |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| index.html | 3.75 kB | 3.75 kB | ✓ |
| index.html gzip | 959 B | 961 B | ⚠️ +2 B |
| link.html | 3.79 kB | 3.79 kB | ✓ |
| link.html gzip | 968 B | 970 B | ⚠️ +2 B |
| withRouter.html | 3.8 kB | 3.8 kB | ✓ |
| withRouter.html gzip | 955 B | 957 B | ⚠️ +2 B |
| Overall change | 11.3 kB | 11.3 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -6,9 +6,9 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/index.module.js"
+        <link rel="preload" href="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/index.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
@@ -16,9 +16,9 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/538929eb098d29bd8795a8d91b62f85c2cd70180.85e4c18b9e4b400e5496.module.js"
+        <link rel="preload" href="/_next/static/chunks/9c55f52966eec015ca752d895b72be32ded85f1c.85e4c18b9e4b400e5496.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/V57Inh7FhDPLqpT5fIT1V/_buildManifest.module.js"
+        <link rel="preload" href="/_next/static/6cm3GMFkQmlpYbATXnDRE/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -26,18 +26,18 @@
         <div id="__next">Hello world 👋</div>
         <script id="__NEXT_DATA__" type="application/json"
         crossorigin="anonymous">
-            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"V57Inh7FhDPLqpT5fIT1V"}
+            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"6cm3GMFkQmlpYbATXnDRE"}
         </script>
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script async="" data-next-page="/" src="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/index.js"
+        <script async="" data-next-page="/" src="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/index.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/" src="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/index.module.js"
+        <script async="" data-next-page="/" src="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/index.module.js"
         crossorigin="anonymous" type="module"></script>
-        <script async="" data-next-page="/_app" src="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/_app.js"
+        <script async="" data-next-page="/_app" src="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/_app.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/_app" src="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/_app.module.js"
+        <script async="" data-next-page="/_app" src="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/_app.module.js"
         crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
         async="" crossorigin="anonymous" nomodule=""></script>
@@ -51,15 +51,15 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/chunks/8c874e6432cc280a7a4f4bb5c9a34ab58459d223.155621535702fe040780.js"
+        <script src="/_next/static/chunks/228e1f4e893fa3baf19d35d232c5645368446558.155621535702fe040780.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/538929eb098d29bd8795a8d91b62f85c2cd70180.b3f63bf01308f3d17f5c.js"
+        <script src="/_next/static/chunks/9c55f52966eec015ca752d895b72be32ded85f1c.b3f63bf01308f3d17f5c.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/538929eb098d29bd8795a8d91b62f85c2cd70180.85e4c18b9e4b400e5496.module.js"
+        <script src="/_next/static/chunks/9c55f52966eec015ca752d895b72be32ded85f1c.85e4c18b9e4b400e5496.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/V57Inh7FhDPLqpT5fIT1V/_buildManifest.js"
+        <script src="/_next/static/6cm3GMFkQmlpYbATXnDRE/_buildManifest.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/V57Inh7FhDPLqpT5fIT1V/_buildManifest.module.js"
+        <script src="/_next/static/6cm3GMFkQmlpYbATXnDRE/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
     </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -6,19 +6,19 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/link.module.js"
+        <link rel="preload" href="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/link.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/538929eb098d29bd8795a8d91b62f85c2cd70180.85e4c18b9e4b400e5496.module.js"
+        <link rel="preload" href="/_next/static/chunks/9c55f52966eec015ca752d895b72be32ded85f1c.85e4c18b9e4b400e5496.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/main-e3367c6cc0a826287f74.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/V57Inh7FhDPLqpT5fIT1V/_buildManifest.module.js"
+        <link rel="preload" href="/_next/static/6cm3GMFkQmlpYbATXnDRE/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -29,18 +29,18 @@
             </div>
         </div>
         <script id="__NEXT_DATA__" type="application/json" crossorigin="anonymous">
-            {"dataManager":"[]","props":{"pageProps":{}},"page":"/link","query":{},"buildId":"V57Inh7FhDPLqpT5fIT1V"}
+            {"dataManager":"[]","props":{"pageProps":{}},"page":"/link","query":{},"buildId":"6cm3GMFkQmlpYbATXnDRE"}
         </script>
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script async="" data-next-page="/link" src="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/link.js"
+        <script async="" data-next-page="/link" src="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/link.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/link" src="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/link.module.js"
+        <script async="" data-next-page="/link" src="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/link.module.js"
         crossorigin="anonymous" type="module"></script>
-        <script async="" data-next-page="/_app" src="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/_app.js"
+        <script async="" data-next-page="/_app" src="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/_app.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/_app" src="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/_app.module.js"
+        <script async="" data-next-page="/_app" src="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/_app.module.js"
         crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
         async="" crossorigin="anonymous" nomodule=""></script>
@@ -50,19 +50,19 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/chunks/8c874e6432cc280a7a4f4bb5c9a34ab58459d223.155621535702fe040780.js"
+        <script src="/_next/static/chunks/228e1f4e893fa3baf19d35d232c5645368446558.155621535702fe040780.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/538929eb098d29bd8795a8d91b62f85c2cd70180.b3f63bf01308f3d17f5c.js"
+        <script src="/_next/static/chunks/9c55f52966eec015ca752d895b72be32ded85f1c.b3f63bf01308f3d17f5c.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/538929eb098d29bd8795a8d91b62f85c2cd70180.85e4c18b9e4b400e5496.module.js"
+        <script src="/_next/static/chunks/9c55f52966eec015ca752d895b72be32ded85f1c.85e4c18b9e4b400e5496.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/runtime/main-26e9253859bbcb659328.js"
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/main-e3367c6cc0a826287f74.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/V57Inh7FhDPLqpT5fIT1V/_buildManifest.js"
+        <script src="/_next/static/6cm3GMFkQmlpYbATXnDRE/_buildManifest.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/V57Inh7FhDPLqpT5fIT1V/_buildManifest.module.js"
+        <script src="/_next/static/6cm3GMFkQmlpYbATXnDRE/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
     </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -6,19 +6,19 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/withRouter.module.js"
+        <link rel="preload" href="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/withRouter.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/538929eb098d29bd8795a8d91b62f85c2cd70180.85e4c18b9e4b400e5496.module.js"
+        <link rel="preload" href="/_next/static/chunks/9c55f52966eec015ca752d895b72be32ded85f1c.85e4c18b9e4b400e5496.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/main-e3367c6cc0a826287f74.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/V57Inh7FhDPLqpT5fIT1V/_buildManifest.module.js"
+        <link rel="preload" href="/_next/static/6cm3GMFkQmlpYbATXnDRE/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -27,18 +27,18 @@
             <div>I use withRouter</div>
         </div>
         <script id="__NEXT_DATA__" type="application/json" crossorigin="anonymous">
-            {"dataManager":"[]","props":{"pageProps":{}},"page":"/withRouter","query":{},"buildId":"V57Inh7FhDPLqpT5fIT1V"}
+            {"dataManager":"[]","props":{"pageProps":{}},"page":"/withRouter","query":{},"buildId":"6cm3GMFkQmlpYbATXnDRE"}
         </script>
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script async="" data-next-page="/withRouter" src="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/withRouter.js"
+        <script async="" data-next-page="/withRouter" src="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/withRouter.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/withRouter" src="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/withRouter.module.js"
+        <script async="" data-next-page="/withRouter" src="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/withRouter.module.js"
         crossorigin="anonymous" type="module"></script>
-        <script async="" data-next-page="/_app" src="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/_app.js"
+        <script async="" data-next-page="/_app" src="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/_app.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/_app" src="/_next/static/V57Inh7FhDPLqpT5fIT1V/pages/_app.module.js"
+        <script async="" data-next-page="/_app" src="/_next/static/6cm3GMFkQmlpYbATXnDRE/pages/_app.module.js"
         crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
         async="" crossorigin="anonymous" nomodule=""></script>
@@ -48,19 +48,19 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/chunks/8c874e6432cc280a7a4f4bb5c9a34ab58459d223.155621535702fe040780.js"
+        <script src="/_next/static/chunks/228e1f4e893fa3baf19d35d232c5645368446558.155621535702fe040780.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/538929eb098d29bd8795a8d91b62f85c2cd70180.b3f63bf01308f3d17f5c.js"
+        <script src="/_next/static/chunks/9c55f52966eec015ca752d895b72be32ded85f1c.b3f63bf01308f3d17f5c.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/538929eb098d29bd8795a8d91b62f85c2cd70180.85e4c18b9e4b400e5496.module.js"
+        <script src="/_next/static/chunks/9c55f52966eec015ca752d895b72be32ded85f1c.85e4c18b9e4b400e5496.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/runtime/main-26e9253859bbcb659328.js"
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/main-e3367c6cc0a826287f74.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/V57Inh7FhDPLqpT5fIT1V/_buildManifest.js"
+        <script src="/_next/static/6cm3GMFkQmlpYbATXnDRE/_buildManifest.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/V57Inh7FhDPLqpT5fIT1V/_buildManifest.module.js"
+        <script src="/_next/static/6cm3GMFkQmlpYbATXnDRE/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
     </body>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| buildDuration | 23s | 22.5s | -581ms |
| nodeModulesSize | 42.4 MB | 42.4 MB | -20.1 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.2 kB | ✓ |
| main-HASH.js gzip | 6.64 kB | 6.64 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 611facb4dc25..799a4e38e.js | 43.1 kB | N/A | N/A |
| 611facb4dc25..e38e.js gzip | 15.4 kB | N/A | N/A |
| c5165a51f6af..2b8407376.js | 21.9 kB | N/A | N/A |
| c5165a51f6af..7376.js gzip | 7.81 kB | N/A | N/A |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 37abfcf6d75f..799a4e38e.js | N/A | 43.1 kB | N/A |
| 37abfcf6d75f..e38e.js gzip | N/A | 15.4 kB | N/A |
| 930e107a26d2..2b8407376.js | N/A | 21.9 kB | N/A |
| 930e107a26d2..7376.js gzip | N/A | 7.81 kB | N/A |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.38 kB | 6.38 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 611facb4dc25..f0.module.js | 45.5 kB | N/A | N/A |
| 611facb4dc25..dule.js gzip | 16.5 kB | N/A | N/A |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 37abfcf6d75f..f0.module.js | N/A | 45.5 kB | N/A |
| 37abfcf6d75f..dule.js gzip | N/A | 16.5 kB | N/A |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | arcanis/next.js mael/pnp-externals | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.2 kB | 66.1 kB | -7 B |
| hooks.html | 3.86 kB | 3.86 kB | ✓ |
| hooks.html gzip | 986 B | 985 B | -1 B |
| index.js | 248 kB | 248 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | ✓ |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.6 kB | 68.6 kB | ⚠️ +13 B |
| routerDirect.js | 249 kB | 249 kB | ✓ |
| routerDirect.js gzip | 66.5 kB | 66.5 kB | -33 B |
| withRouter.js | 249 kB | 249 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | ⚠️ +10 B |
| Overall change | 1.25 MB | 1.25 MB | ✓ |

</details>

</details>

**Comment by Timer** [comment]
> because it will be resolvable from the basedir

I'm not sure this was intentional, it's probably meant to use webpack's passed `context`.

**Comment by Timer** [comment]
Let's see what happens: https://github.com/zeit/next.js/pull/8669

**Review by Timer — COMMENTED** [review]
I'm guessing this needs fixed everywhere we use the `resolve` module, e.g. `verifyTypeScriptSetup.ts`. Maybe we should export `resolveFn` as a generic helper so we can use it in both places?

**Comment by arcanis** [comment]
Sounds a good idea - I've put it in `next/lib/resolve-request` and updated `verifyTypeScriptSetup` to use it 👍

File: packages/next/lib/resolve-request.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+export function resolveRequest(req: string, issuer: string) {
+  // The `resolve` package is prebuilt through ncc, which prevents
+  // PnP from being able to inject itself into it. To circumvent
+  // this, we simply use PnP directly when available.
+  // @ts-ignore
+  if (process.versions.pnp) {
+    const { resolveRequest } = require(`pnpapi`)
+    return resolveRequest(req, issuer, { considerBuiltins: false })
+  } else {
+    const basedir = issuer.endsWith(`/`) ? issuer : path.dirname(issuer)
```
Comment (Timer) [inline packages/next/lib/resolve-request.ts]: This probably needs to handle both types of path ends:
```suggestion
    const basedir = issuer.endsWith(path.posix.sep) || issuer.endsWith(path.win32.sep) ? issuer : path.dirname(issuer)
```

**Review by Timer — CHANGES_REQUESTED** [review]

File: packages/next/lib/resolve-request.ts (hunk 1 above)
Comment (arcanis) [reply packages/next/lib/resolve-request.ts]: LGTM 👍

**Review by Timer — APPROVED** [review]
Awesome, thanks! As normal with these, we'll rely on Yarn's tests for PnP compat but will add our own shortly.
