### PR TITLE
Fix streaming SSR with multi-byte characters

### LINKED ISSUE #35720: Server response is broken with multi-byte characters and React 18.0.0
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.3-canary.0
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

Firefox 98.0.2

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

The sever response with multi-byte characters seems to be broken.

image

This causes the following hydration error:

```
Warning: Text content did not match. Server: "アイウエオアイウエオアイウエオアイウオ" Client: "アイウエオアイウエオアイウエオアイウエオ"
p
main
div
Home
MyApp@webpack-internal:///./pages/_app.tsx:34:21
ErrorBoundary@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20638
ReactDevOverlay@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23177
Container@webpack-internal:///./node_modules/next/dist/client/index.js:323:24
AppContainer@webpack-internal:///./node_modules/next/dist/client/index.js:822:20
Root@webpack-internal:///./node_modules/next/dist/client/index.js:946:21 

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

### Expected Behavior

The hydration error should not be occurred. The server response should not contain garbage characters.

### To Reproduce

https://github.com/3c1u/nextjs-mb-error-test

### PR DESCRIPTION
**Pull request by martinnabhan**
Fixes #35720 

When using streaming SSR decodeText is called repeatedly with incoming chunks of data.
In that case a multi-byte character may occasionally split between chunks, causing corruption.
By setting the TextDecoder option 'stream' to true, and reusing the same TextDecoder instance,
TextDecoder will memorise “unfinished” characters and decode them when the next chunk comes.

I found out about the stream option here: https://javascript.info/text-decoder

### CODE REVIEW

File: packages/next/server/node-web-streams-helper.ts [hunk 1]
```diff
@@ -111,8 +111,8 @@ export function encodeText(input: string) {
   return new TextEncoder().encode(input)
 }
 
-export function decodeText(input?: Uint8Array) {
-  return new TextDecoder().decode(input)
+export function decodeText(input?: Uint8Array, textDecoder?: TextDecoder) {
+  return textDecoder ? textDecoder.decode(input, { stream: true } ) : new TextDecoder().decode(input)
```
Comment (martinnabhan) [inline packages/next/server/node-web-streams-helper.ts:115]: Since decodeText is being exported I didn't want to mess with the code signature, so I just added the textDecoder argument.

File: packages/next/server/node-web-streams-helper.ts [hunk 2]
```diff
@@ -207,9 +207,11 @@ export function createBufferedTransformStream(): TransformStream<
     return pendingFlush
   }
 
+  const textDecoder = new TextDecoder();
```
Comment (martinnabhan) [inline packages/next/server/node-web-streams-helper.ts:210]: We need to keep the same TextEncoder instance until the stream ends, or else the steam option won't work.

**Review by shuding — DISMISSED** [review]
Thanks!

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 0f0e126f878411cfe30250e4e706ce3f582d1e69

`yarn testheadless test/development/acceptance/ReactRefresh.test.ts` 
- ReactRefresh > can edit a component without losing state
- ReactRefresh > cyclic dependencies

<details>
<summary>Expand output</summary>

  ● ReactRefresh › can edit a component without losing state

    expect(received).toBe(expected) // Object.is equality

    Expected: "Count: 1"
    Received: "1"

      61 |     expect(
      62 |       await session.evaluate(() => document.querySelector('p').textContent)
    > 63 |     ).toBe('Count: 1')
         |       ^
      64 |     await session.evaluate(() => document.querySelector('button').click())
      65 |     expect(
      66 |       await session.evaluate(() => document.querySelector('p').textContent)

      at Object.<anonymous> (development/acceptance/ReactRefresh.test.ts:63:7)

  ● ReactRefresh › cyclic dependencies

    expect(received).toBe(expected) // Object.is equality

    Expected: "Hello. 200"
    Received: "Hello. 100"

      187 |     expect(
      188 |       await session.evaluate(() => document.querySelector('p').textContent)
    > 189 |     ).toBe('Hello. 200')
          |       ^
      190 |     expect(didFullRefresh).toBe(false)
      191 |
      192 |     didFullRefresh = !(await session.patch(

      at Object.<anonymous> (development/acceptance/ReactRefresh.test.ts:189:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| buildDuration | 19.7s | 19s | -740ms |
| buildDurationCached | 7.6s | 7.5s | -158ms |
| nodeModulesSize | 467 MB | 467 MB | ⚠️ +335 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.988 | 3.937 | -0.05 |
| / avg req/sec | 626.93 | 635.05 | +8.12 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.68 | 1.731 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1488.45 | 1444.18 | ⚠️ -44.27 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.48 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.2 kB | 15.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| buildDuration | 23.1s | 23.5s | ⚠️ +368ms |
| buildDurationCached | 7.7s | 7.5s | -205ms |
| nodeModulesSize | 467 MB | 467 MB | ⚠️ +335 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.845 | 3.954 | ⚠️ +0.11 |
| / avg req/sec | 650.2 | 632.34 | ⚠️ -17.86 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.797 | 1.769 | -0.03 |
| /error-in-render avg req/sec | 1391.28 | 1412.96 | +21.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.59 kB | 5.59 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.3 kB | 15.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 0f0e126f878411cfe30250e4e706ce3f582d1e69

**Review by huozhi — APPROVED** [review]

**Review by huozhi — CHANGES_REQUESTED** [review]
pause for incoming patch, will re-approve later. would be nice to have a test during this period

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| buildDuration | 15.1s | 15s | -149ms |
| buildDurationCached | 6s | 6s | ⚠️ +26ms |
| nodeModulesSize | 467 MB | 467 MB | ⚠️ +335 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.937 | 2.925 | -0.01 |
| / avg req/sec | 851.22 | 854.81 | +3.59 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.186 | 1.177 | -0.01 |
| /error-in-render avg req/sec | 2107.25 | 2124.71 | +17.46 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.48 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.2 kB | 15.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| buildDuration | 18.5s | 18.6s | ⚠️ +24ms |
| buildDurationCached | 6s | 6s | ⚠️ +8ms |
| nodeModulesSize | 467 MB | 467 MB | ⚠️ +335 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.939 | 2.934 | 0 |
| / avg req/sec | 850.74 | 852.1 | +1.36 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.202 | 1.199 | 0 |
| /error-in-render avg req/sec | 2079.79 | 2084.29 | +4.5 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.59 kB | 5.59 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.3 kB | 15.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 55c78bc4a06d10730251a18497e90dde5fb2b0a3

File: test/production/react-18-streaming-ssr/index.test.ts [hunk 3]
```diff
@@ -61,6 +61,15 @@ describe('react 18 streaming SSR with custom next configs', () => {
             return <p>hello nextjs</p>
           }
         `,
+        'pages/multi-byte.js': `
+          export default function Page() {
+            return (
+              <div>
+                <p>{"マルチバイト".repeat(28)}</p>
```
Comment (martinnabhan) [inline test/production/react-18-streaming-ssr/index.test.ts:68]: マルチバイト is multi-byte in Japanese. Repeating this word exactly 28 times results in corrupted text in the response.

**Comment by martinnabhan** [comment]
I've added a test. Thank you so much for the work you do on Next.js!

**Comment by shuding** [comment]
Thanks for adding the test!

**Review by huozhi — DISMISSED** [review]
Thanks! 🙏

**Comment by shuding** [comment]
It seems that there's a lint error in packages/next/server/node-web-streams-helper.ts.

**Comment by martinnabhan** [comment]
I'm sorry, my bad! I ran lint-fix and pushed the changes.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 04cf4c974f1f759934506c58f0ae98835b75ba17

`yarn testheadless test/integration/cli/test/index.test.js` 
- CLI Usage > info > should print output

<details>
<summary>Expand output</summary>

  ● CLI Usage › info › should print output

    expect(received).toBe(expected) // Object.is equality

    Expected: ""
    Received: "warn  - Latest canary version not detected, detected: \"12.1.3-canary.2\", newest: \"12.1.3-canary.3\".
            Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
            Read more - https://nextjs.org/docs/messages/opening-an-issue
    "

      496 |       // warning will show so skip this check for the stable release
      497 |       if (pkg.version.includes('-canary')) {
    > 498 |         expect(info.stderr || '').toBe('')
          |                                   ^
      499 |       }
      500 |       expect(info.stdout).toMatch(
      501 |         new RegExp(`

      at Object.<anonymous> (integration/cli/test/index.test.js:498:35)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| buildDuration | 16.5s | 16.1s | -394ms |
| buildDurationCached | 6.3s | 6.4s | ⚠️ +124ms |
| nodeModulesSize | 467 MB | 467 MB | ⚠️ +336 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.349 | 3.289 | -0.06 |
| / avg req/sec | 746.49 | 760.04 | +13.55 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.501 | 1.484 | -0.02 |
| /error-in-render avg req/sec | 1665.26 | 1684.63 | +19.37 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.48 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.2 kB | 15.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| buildDuration | 19.8s | 19.8s | ⚠️ +21ms |
| buildDurationCached | 6.3s | 6.4s | ⚠️ +64ms |
| nodeModulesSize | 467 MB | 467 MB | ⚠️ +336 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.32 | 3.294 | -0.03 |
| / avg req/sec | 752.97 | 758.94 | +5.97 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.525 | 1.459 | -0.07 |
| /error-in-render avg req/sec | 1639.27 | 1713.5 | +74.23 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.59 kB | 5.59 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.3 kB | 15.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | martinnabhan/next.js fix/multi-byte-streaming-ssr | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 04cf4c974f1f759934506c58f0ae98835b75ba17

**Review by huozhi — APPROVED** [review]
