### PR TITLE
Do not remove placeholder for data URL

### LINKED ISSUE #24703: Placeholder are always blank during lazy loading.
### What version of Next.js are you using?

10.2.1-canary.2

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome, Firefox, Mobile Safari

### What operating system are you using?

Windows, iOS

### How are you deploying your application?

Vercel

### Describe the Bug

The placeholders introduced in #24153 are always blank during lazy loading.

### Expected Behavior

Placeholder are displayed until loading is complete.

### To Reproduce

```tsx
<Image
  src="/test.jpg"
  alt="photo"
  width="1920"
  height="1080"
  layout="responsive"
  placeholder="blur"
  blurDataURL={dataURL}
/>
```

### PR DESCRIPTION
**Pull request by ykzts**
Follow-up #24153
Fixes #24703

## Bug

- [x] Related issues linked using `fixes #24703`
- [x] Integration tests added

## ~~Feature~~

- ~~Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.~~
- ~~Related issues linked using `fixes #number`~~
- ~~Integration tests added~~
- ~~Documentation added~~
- ~~Telemetry added. In case of a feature if it's used or not.~~

## ~~Documentation / Examples~~

- ~~Make sure the linting passes~~

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| buildDuration | 14.9s | 14.8s | -83ms |
| buildDurationCached | 5s | 4.5s | -502ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +302 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.586 | 2.632 | ⚠️ +0.05 |
| / avg req/sec | 966.69 | 949.68 | ⚠️ -17.01 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.496 | 1.527 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1671.68 | 1636.88 | ⚠️ -34.8 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.2 kB | 13.2 kB | ✓ |
| 778-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| css-HASH.js gzip | 363 B | 363 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.52 kB | 9.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 395 B | 395 B | ✓ |
| Overall change | 395 B | 395 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| index.html gzip | 607 B | 607 B | ✓ |
| link.html gzip | 614 B | 614 B | ✓ |
| withRouter.html gzip | 602 B | 602 B | ✓ |
| Overall change | 1.82 kB | 1.82 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| buildDuration | 18.1s | 18.2s | ⚠️ +93ms |
| buildDurationCached | 6.8s | 6.6s | -194ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +302 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.2 kB | 13.2 kB | ✓ |
| 778-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| css-HASH.js gzip | 363 B | 363 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.52 kB | 9.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 395 B | 395 B | ✓ |
| Overall change | 395 B | 395 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _error.js | 1.35 MB | 1.35 MB | ✓ |
| 404.html | 2.76 kB | 2.76 kB | ✓ |
| 500.html | 2.75 kB | 2.75 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.96 kB | 1.96 kB | ✓ |
| css.html | 2.13 kB | 2.13 kB | ✓ |
| hooks.html | 2.01 kB | 2.01 kB | ✓ |
| index.js | 1.35 MB | 1.35 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.4 MB | 1.4 MB | ✓ |
| withRouter.js | 1.4 MB | 1.4 MB | ✓ |
| Overall change | 6.91 MB | 6.91 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.4s | -247ms |
| buildDurationCached | 5.4s | 5.1s | -386ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +302 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.732 | 2.506 | -0.23 |
| / avg req/sec | 915.07 | 997.68 | +82.61 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.629 | 1.492 | -0.14 |
| /error-in-render avg req/sec | 1534.58 | 1675.57 | +140.99 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.36 kB | 9.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: c7a5edfaca08d5b1282a5be00747dc47450a9b8a

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.2s | -125ms |
| buildDurationCached | 4.3s | 4s | -276ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +302 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.272 | 2.262 | -0.01 |
| / avg req/sec | 1100.41 | 1105.3 | +4.89 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.216 | 1.179 | -0.04 |
| /error-in-render avg req/sec | 2055.73 | 2121.34 | +65.61 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| index.html gzip | 560 B | 560 B | ✓ |
| link.html gzip | 569 B | 569 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| buildDuration | 16.3s | 16.8s | ⚠️ +549ms |
| buildDurationCached | 6.1s | 6.1s | -17ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +302 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | ✓ |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.35 MB | 1.35 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | ⚠️ +2 B |
| routerDirect.js | 1.39 MB | 1.39 MB | ✓ |
| withRouter.js | 1.39 MB | 1.39 MB | ✓ |
| Overall change | 6.9 MB | 6.9 MB | ⚠️ +2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| buildDuration | 11.1s | 11.3s | ⚠️ +176ms |
| buildDurationCached | 4.6s | 4.5s | -137ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +302 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.333 | 2.282 | -0.05 |
| / avg req/sec | 1071.58 | 1095.3 | +23.72 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.215 | 1.188 | -0.03 |
| /error-in-render avg req/sec | 2056.91 | 2104.37 | +47.46 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.72 kB | 3.72 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.37 kB | 9.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: 6244211c6303070a91676dc46bff5c90df4c3475

File: packages/next/client/image.tsx [hunk 1]
```diff
@@ -228,14 +228,16 @@ function removePlaceholder(
   placeholder: PlaceholderValue
 ) {
   if (placeholder === 'blur' && element) {
-    if (element.complete) {
+    if (element.complete && !element.src.startsWith('data:')) {
```
Comment (Joonpark13) [inline packages/next/client/image.tsx:231]: Can you explain a bit more about your reasoning behind checking the src?

**Review by Joonpark13 — COMMENTED** [review]
I'm currently looking into #24703 but I also wanted to clarify that the `priority` attribute in the existing integration test case shouldn't make a difference since that callout was left in there by mistake.

File: packages/next/client/image.tsx (hunk 1 above)
Comment (ykzts) [reply packages/next/client/image.tsx:231]: When `isVisible === false`, the value of `src` always starts with `data:`.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| buildDuration | 13.7s | 14.5s | ⚠️ +835ms |
| buildDurationCached | 4.1s | 3.8s | -371ms |
| nodeModulesSize | 46.7 MB | 46.8 MB | ⚠️ +302 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.407 | 2.238 | -0.17 |
| / avg req/sec | 1038.73 | 1117.1 | +78.37 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.415 | 1.217 | -0.2 |
| /error-in-render avg req/sec | 1766.6 | 2053.63 | +287.03 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| index.html gzip | 573 B | 573 B | ✓ |
| link.html gzip | 580 B | 580 B | ✓ |
| withRouter.html gzip | 568 B | 568 B | ✓ |
| Overall change | 1.72 kB | 1.72 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| buildDuration | 15.5s | 15.9s | ⚠️ +467ms |
| buildDurationCached | 4.9s | 4.9s | ⚠️ +11ms |
| nodeModulesSize | 46.7 MB | 46.8 MB | ⚠️ +302 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 2.44 kB | 2.44 kB | ✓ |
| 500.html | 2.43 kB | 2.43 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.63 kB | 1.63 kB | ✓ |
| css.html | 1.81 kB | 1.81 kB | ✓ |
| hooks.html | 1.69 kB | 1.69 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | -2 B |
| link.js | 17.4 kB | 17.4 kB | ✓ |
| routerDirect.js | 17.4 kB | 17.4 kB | ⚠️ +2 B |
| withRouter.js | 17.4 kB | 17.4 kB | -2 B |
| Overall change | 107 kB | 107 kB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.9s | ⚠️ +346ms |
| buildDurationCached | 5.6s | 5.6s | -27ms |
| nodeModulesSize | 46.7 MB | 46.8 MB | ⚠️ +302 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.359 | 2.574 | ⚠️ +0.21 |
| / avg req/sec | 1059.67 | 971.12 | ⚠️ -88.55 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.139 | 1.403 | ⚠️ +0.26 |
| /error-in-render avg req/sec | 2195.78 | 1781.93 | ⚠️ -413.85 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 61.1 kB | 61.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.74 kB | 3.74 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.16 kB | 9.16 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ykzts/next.js data-url | Change |
| - | - | - | - |
| index.html gzip | 626 B | 626 B | ✓ |
| link.html gzip | 632 B | 632 B | ✓ |
| withRouter.html gzip | 620 B | 620 B | ✓ |
| Overall change | 1.88 kB | 1.88 kB | ✓ |

</details>

</details>
Commit: 767a66d3a00de75b7da8aa7db03598b8738f4402

**Review by atcastle — APPROVED** [review]
This change makes sense to me. Thanks @ykzts
