### PR TITLE
fix(ts): re-export `PageComponent` and `LayoutComponent` types

### LINKED ISSUE #41901: Type error: PageComponent/LayoutComponent is declared but never used
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

When adding `"noUnusedLocals": true` to tsconfig.json and running a type-check with `npx tsc` (or `next build`), it fails due to declared but unused types:

```
.next/types/app/layout.ts:17:6 - error TS6196: 'PageComponent' is declared but never used.

17 type PageComponent = (props: PageProps) => React.ReactNode | Promise<React.ReactNode>
        ~~~~~~~~~~~~~

.next/types/app/page.ts:18:6 - error TS6196: 'LayoutComponent' is declared but never used.

18 type LayoutComponent = (props: LayoutProps) => React.ReactNode | Promise<React.ReactNode>
        ~~~~~~~~~~~~~~~
```

### Expected Behavior

No type errors.

### Link to reproduction

https://github.com/richardkall/next-bug-repro

### To Reproduce

1. Clone repo.
2. Run `npm install`
3. Run `npm run build`

### LINKED ISSUE #42042: next app typings aren't compatible with `noUnusedLocals`
I'm using typescript with `"noUnusedLocals": true,` and I'm getting this error at build time

image

_Originally posted by @imranbarbhuiya in https://github.com/vercel/next.js/discussions/41745#discussioncomment-3972703_

### LINKED ISSUE #43195: Type error: 'PageComponent' is declared but never used
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information
```
 ⚡nekodex ❯❯ pnpm exec next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Nov 2 19:50:29 UTC 2022
    Binaries:
      Node: 18.11.0
      npm: 8.19.2
      Yarn: 3.2.4
      pnpm: 7.13.5
    Relevant packages:
      next: 13.0.5-canary.3
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Microsoft Edge 107.0.1418.52

### How are you deploying your application? (if relevant)

next build

### Describe the Bug

When I try to compile my application with "next build", eslint complains about "PageComponent" being declared but never used.

I looked where that declaration was because I didn't have any variable with that name, then I see that in the "types" folder inside the "next" folder that is autogenerated by next.

image

image

image

### Expected Behavior

A successful compilation with no slint errors.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

None.

### To Reproduce

1. Create a nextjs project
2. Run `next build`

### PR DESCRIPTION
**Pull request by balazsorban44**
Fixes #43195, fixes #41901, fixes #42042
## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have a helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have a helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm build && pnpm lint`
- [ ] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: d1cf6efb31fe15a35c86106216bcf4cfdec39248

`pnpm testheadless test/development/acceptance-app/ReactRefreshLogBox.test.ts` 
- ReactRefreshLogBox app > logbox: can recover from a syntax error without losing state
- ReactRefreshLogBox app > render error not shown right after syntax error

<details>
<summary>Expand output</summary>

  ● ReactRefreshLogBox app › logbox: can recover from a syntax error without losing state

    TIMED OUT: /Count: 1/

    Count: 0

      532 |
      533 |   if (hardError) {
    > 534 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      535 |   }
      536 |   return false
      537 | }

      at check (lib/next-test-utils.js:534:11)
      at Object.<anonymous> (development/acceptance-app/ReactRefreshLogBox.test.ts:107:5)

  ● ReactRefreshLogBox app › render error not shown right after syntax error

    expect(received).toMatchSnapshot()

    Snapshot name: `ReactRefreshLogBox app render error not shown right after syntax error 1`

    Snapshot: "index.js (6:18) @ ClassDefault.render

      4 | class ClassDefault extends React.Component {
      5 |   render() {
    > 6 |     throw new Error('nooo');
        |          ^
      7 |     return <h1>Default Export</h1>;
      8 |   }
      9 | }"
    Received: null

      327 |     )
      328 |     expect(await session.hasRedbox(true)).toBe(true)
    > 329 |     expect(await session.getRedboxSource()).toMatchSnapshot()
          |                                             ^
      330 |
      331 |     await cleanup()
      332 |   })

      at Object.<anonymous> (development/acceptance-app/ReactRefreshLogBox.test.ts:329:45)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by shuding — APPROVED** [review]

**Comment by imranbarbhuiya** [comment]
This also fixes #41901 and #42042

File: packages/next/build/webpack/plugins/flight-types-plugin.ts [hunk 1]
```diff
@@ -35,8 +35,8 @@ interface LayoutProps {
   params: any
 }
 
-type PageComponent = (props: PageProps) => React.ReactNode | Promise<React.ReactNode>
-type LayoutComponent = (props: LayoutProps) => React.ReactNode | Promise<React.ReactNode>
+export type PageComponent = (props: PageProps) => React.ReactNode | Promise<React.ReactNode>
+export type LayoutComponent = (props: LayoutProps) => React.ReactNode | Promise<React.ReactNode>
```
Comment (imranbarbhuiya) [inline packages/next/build/webpack/plugins/flight-types-plugin.ts:39]: Instead of exporting can't you declare these types based on `options.type === 'layout'`?

**Review by imranbarbhuiya — CHANGES_REQUESTED** [review]

File: packages/next/build/webpack/plugins/flight-types-plugin.ts (hunk 1 above)
Comment (balazsorban44) [reply packages/next/build/webpack/plugins/flight-types-plugin.ts:39]: These types _might_ be useful for lib authors so I think exporting is fine, but we can always iterate on it in the future. `app/` is not yet stable, but thanks for the feedback!
