### PR TITLE
Restore `--no-mangling` CLI option for `next build`

### LINKED ISSUE #50208: `__NEXT_MANGLING_DEBUG` resp. `--no-mangling` do not work with `swcMinify: true` (per next config)
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.4-canary.2
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC minifier (swcMinify: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/tree/canary/examples/basic-export

### To Reproduce

1. Create plain boilerplate via `yarn create next-app`
2. Run `yarn next build --no-mangling`
3. Inspect output in `.next`
4. Modify `next.config.js` to use `swcMinify: true`
5. Run `yarn next build --no-mangling`
6. Inspect output in `.next`, see e.g. class names are preserved.

### Describe the Bug

Currently disabling terser mangling (`__NEXT_MANGLING_DEBUG` resp. `--no-mangling`) do not work with `swcMinify: true` (i.e. default).

### Expected Behavior

`__NEXT_MANGLING_DEBUG` resp. `--no-mangling` should work regardless of `swcMinify`.

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### LINKED ISSUE #67037: next build --no-mangling keeps mangling
### Link to the code that reproduces this issue

https://github.com/inside/no-mangling-option

### To Reproduce

1. `npm install`
2. `npm run build -- --profile --no-mangling`
3. `npm start`
4. Open your browser to `http://localhost:3000`
5. Open the devtools
6. If installed, go to the React Developer Tools profiler tab
7. Click on "Reload and start profiling"
8. After a few seconds, click stop on the red circle

### Expected behavior versus Current

Following the previous section, a flamegraph with no mangled names should appear like shown in the screenshot below:

image

Instead a flamegraph with mangled names appears like shown in the screenshot below:

image

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2
  Available memory (MB): 15747
  Available CPU cores: 8
Binaries:
  Node: 20.12.1
  npm: 10.5.1
  Yarn: 1.22.21
  pnpm: 7.11.0
Relevant Packages:
  next: 15.0.0-canary.37 // Latest available version is detected (15.0.0-canary.37).
  eslint-config-next: N/A
  react: 19.0.0-rc.0
  react-dom: 19.0.0-rc.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

SWC

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by unstubbable**
The `--no-mangling` CLI option for `next build` was originally introduced in #42633. However, we lost this feature during our migration from Terser to SWC. As part of broader improvements for debugging dynamic accesses with Dynamic I/O enabled, I needed this functionality back, so I restored it for Webpack and also added it to Turbopack.

fixes #67037
fixes #50208

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 3bf69a164cae8656faf2266061dce00c7863b70c

`pnpm test-dev-turbo test/development/basic/next-rs-api.test.ts` (turbopack)
- next.rs api > should detect the correct routes
- next.rs api > should allow to write root page to disk
- next.rs api > should allow to write pages edge api to disk
- next.rs api > should allow to write pages Node.js api to disk
- next.rs api > should allow to write app edge page to disk
- next.rs api > should allow to write app Node.js page to disk
- next.rs api > should allow to write pages edge page to disk
- next.rs api > should allow to write pages Node.js page to disk
- next.rs api > should allow to write app edge route to disk
- next.rs api > should allow to write app Node.js route to disk
- next.rs api > should have working HMR on client-side change on a page 0
- next.rs api > should have working HMR on client-side change on a page 1
- next.rs api > should have working HMR on client-side change on a page 2
- next.rs api > should have working HMR on server-side change on a page 0
- next.rs api > should have working HMR on server-side change on a page 1
- next.rs api > should have working HMR on server-side change on a page 2
- next.rs api > should have working HMR on client and server-side change on a page 0
- next.rs api > should have working HMR on client and server-side change on a page 1
- next.rs api > should have working HMR on client and server-side change on a page 2
- next.rs api > should have working HMR on client-side change on a app page 0
- next.rs api > should have working HMR on client-side change on a app page 1
- next.rs api > should have working HMR on client-side change on a app page 2
- next.rs api > should have working HMR on server-side change on a app page 0
- next.rs api > should have working HMR on server-side change on a app page 1
- next.rs api > should have working HMR on server-side change on a app page 2

<details>
<summary>Expand output</summary>

  ● next.rs api › should detect the correct routes

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should allow to write root page to disk

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should allow to write pages edge api to disk

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should allow to write pages Node.js api to disk

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should allow to write app edge page to disk

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should allow to write app Node.js page to disk

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should allow to write pages edge page to disk

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should allow to write pages Node.js page to disk

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should allow to write app edge route to disk

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should allow to write app Node.js route to disk

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on client-side change on a page 0

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on client-side change on a page 1

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on client-side change on a page 2

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on server-side change on a page 0

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on server-side change on a page 1

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on server-side change on a page 2

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on client and server-side change on a page 0

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on client and server-side change on a page 1

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on client and server-side change on a page 2

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on client-side change on a app page 0

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on client-side change on a app page 1

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on client-side change on a app page 2

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on server-side change on a app page 0

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on server-side change on a app page 1

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should have working HMR on server-side change on a app page 2

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

  ● next.rs api › should allow to make many HMR updates

    Missing field `noMangling`

      987 |   ) {
      988 |     return new ProjectImpl(
    > 989 |       await binding.projectNew(
          |                     ^
      990 |         await rustifyProjectOptions(options),
      991 |         turboEngineOptions || {}
      992 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:989:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:199:15)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: crates/napi/src/minify.rs [hunk 1]
```diff
@@ -118,10 +118,19 @@ fn patch_opts(opts: &mut JsMinifyOptions) {
...
+            reserved: vec!["AbortSignal".into()],
+            ..Default::default()
+        });
+    } else if opts.mangle.is_obj() {
+        let mangle = std::mem::take(&mut opts.mangle);
+        opts.mangle = mangle.map(|mut mangle_opts| {
+            mangle_opts.reserved.push("AbortSignal".into());
+            mangle_opts
+        });
+    }
```
Comment (bgw) [inline crates/napi/src/minify.rs:133]: As this is not a hot codepath, I'd personally prefer something that minimizes branching/duplication like:

```suggestion
    if opts.mangle.is_true() {
        opts.mangle = BoolOrDataConfig::from_obj(MangleOptions::default());
    }
    let mangle = std::mem::take(&mut opts.mangle);
    opts.mangle = mangle.map(|mut mangle_opts| {
        mangle_opts.reserved.push("AbortSignal".into());
        mangle_opts
    });
```

File: crates/napi/src/next_api/project.rs [hunk 2]
```diff
@@ -144,6 +144,9 @@ pub struct NapiProjectOptions {
 
     /// The browserslist query to use for targeting browsers.
     pub browserslist_query: String,
+
+    /// Whether mangling should be disabled
```
Comment (bgw) [inline crates/napi/src/next_api/project.rs:148]: This comment isn't useful. Either remove it, or add a better comment explaining what mangling is (shortening/renaming of local variable and function names).

File: packages/next/src/build/webpack/plugins/minify-webpack-plugin/src/index.ts [hunk 3]
```diff
@@ -18,27 +21,44 @@ function buildError(error: any, file: string) {
...
+    cache: CacheFacade,
+    {
+      SourceMapSource,
+      RawSource,
+    }: {
+      SourceMapSource: typeof sources.SourceMapSource
+      RawSource: typeof sources.RawSource
+    }
   ) {
+    const mangle = this.options.noMangling ? false : true
```
Comment (bgw) [inline packages/next/src/build/webpack/plugins/minify-webpack-plugin/src/index.ts:50]: Huh? I assume there's a better idiom for boolean coercion in the nextjs codebase?

**Review by bgw — APPROVED** [review]
