### PR TITLE
Fix AMP HTML content emit

### LINKED ISSUE #9467: AMP: Dollars followed by single quote in AMP document attributes turned into __NEXT_AMP_RENDER_TARGET__#x27;
# Bug report

## Describe the bug

The character sequence dollars single-quote (`$'`) in attributes is being replaced with `__NEXT_AMP_RENDER_TARGET__#x27;`, corrupting the attribute value.

## To Reproduce

1. Load the following page into pages/dollars.js (note this page does not work because it does not load the amp-bind component, but that is not required to illustrate the problem).
```
export const config = {amp: true};

export default () => (
  <div data-amp-bind-text="fields_maxPrice_live < 801 ? '$' + round(fields_maxPrice_live) : '$800+'">
    $800+
  </div>
);
```
2. Load the page in a web browser and view the source code. Where the `$'` characters should be instead you will see `__NEXT_AMP_RENDER_TARGET__#x27;`.
```
<div data-amp-bind-text="fields_maxPrice_live < 801 ? '__NEXT_AMP_RENDER_TARGET__#x27; + round(fields_maxPrice_live) : '$800+'">$800+</div>
```
3. Insert a space between the `$` and `'` and it will work correctly. So it appears to be `$'` (dollars followed by quote) that is triggering the problem.

## Expected behavior

The `$'` should not be modified.

## System information

- OS: macOS
- Browser: Chrome
- Version of Next.js: 9.1.4

### PR DESCRIPTION
**Pull request by ijjk**
This fixes `$` not being escaped before replacing the `__NEXT_AMP_RENDER_TARGET__`. Since React escapes attribute values automatically `? '$'` becomes `? &#x27;$&#x27;` and `$&` is a reference to the match in RegEx so the `__NEXT_AMP_RENDER_TARGET__` gets inserted

Fixes: #9467

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12.2s | ⚠️ +175ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.8 kB | ✓ |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0f1a45b52.js | 19.9 kB | 19.9 kB | ✓ |
| 16b1a7225520..5b52.js gzip | 7.34 kB | 7.34 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..99.module.js | 16.1 kB | 16.1 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 205 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.01 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ✓ |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.08 kB | 1.08 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.6s | ⚠️ +43ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.8 kB | ✓ |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0f1a45b52.js | 19.9 kB | 19.9 kB | ✓ |
| 16b1a7225520..5b52.js gzip | 7.34 kB | 7.34 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..99.module.js | 16.1 kB | 16.1 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 205 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _error.js | 241 kB | 241 kB | ⚠️ +127 B |
| _error.js gzip | 64.5 kB | 64.5 kB | ⚠️ +57 B |
| hooks.html | 4.04 kB | 4.04 kB | ✓ |
| hooks.html gzip | 1.05 kB | 1.05 kB | ✓ |
| index.js | 242 kB | 242 kB | ⚠️ +127 B |
| index.js gzip | 64.6 kB | 64.6 kB | ⚠️ +60 B |
| link.js | 274 kB | 274 kB | ⚠️ +127 B |
| link.js gzip | 73.6 kB | 73.6 kB | ⚠️ +59 B |
| routerDirect.js | 267 kB | 267 kB | ⚠️ +127 B |
| routerDirect.js gzip | 71.6 kB | 71.7 kB | ⚠️ +61 B |
| withRouter.js | 267 kB | 267 kB | ⚠️ +127 B |
| withRouter.js gzip | 71.7 kB | 71.8 kB | ⚠️ +61 B |
| Overall change | 1.29 MB | 1.3 MB | ⚠️ +635 B |

</details>

</details>


Commit: 10f360241c8e83ded9e51e0a259a64e84ad5d44f

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 14s | 14.3s | ⚠️ +302ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.8 kB | ✓ |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0f1a45b52.js | 19.9 kB | 19.9 kB | ✓ |
| 16b1a7225520..5b52.js gzip | 7.34 kB | 7.34 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..99.module.js | 16.1 kB | 16.1 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 205 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.01 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ✓ |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.08 kB | 1.08 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 15.1s | 14.9s | -209ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.8 kB | ✓ |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0f1a45b52.js | 19.9 kB | 19.9 kB | ✓ |
| 16b1a7225520..5b52.js gzip | 7.34 kB | 7.34 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..99.module.js | 16.1 kB | 16.1 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 205 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _error.js | 241 kB | 241 kB | ⚠️ +127 B |
| _error.js gzip | 64.5 kB | 64.5 kB | ⚠️ +57 B |
| hooks.html | 4.04 kB | 4.04 kB | ✓ |
| hooks.html gzip | 1.05 kB | 1.05 kB | ✓ |
| index.js | 242 kB | 242 kB | ⚠️ +127 B |
| index.js gzip | 64.6 kB | 64.6 kB | ⚠️ +60 B |
| link.js | 274 kB | 274 kB | ⚠️ +127 B |
| link.js gzip | 73.6 kB | 73.6 kB | ⚠️ +59 B |
| routerDirect.js | 267 kB | 267 kB | ⚠️ +127 B |
| routerDirect.js gzip | 71.6 kB | 71.7 kB | ⚠️ +61 B |
| withRouter.js | 267 kB | 267 kB | ⚠️ +127 B |
| withRouter.js gzip | 71.7 kB | 71.8 kB | ⚠️ +61 B |
| Overall change | 1.29 MB | 1.3 MB | ⚠️ +635 B |

</details>

</details>


Commit: 5ae807acd7ca82a2c698529385b1cc95111a7aee

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 14s | 14s | ⚠️ +29ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.8 kB | ✓ |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0f1a45b52.js | 19.9 kB | 19.9 kB | ✓ |
| 16b1a7225520..5b52.js gzip | 7.34 kB | 7.34 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..99.module.js | 16.1 kB | 16.1 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 205 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.01 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ✓ |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.09 kB | 1.09 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.4s | ⚠️ +29ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.8 kB | ✓ |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0f1a45b52.js | 19.9 kB | 19.9 kB | ✓ |
| 16b1a7225520..5b52.js gzip | 7.34 kB | 7.34 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..99.module.js | 16.1 kB | 16.1 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 205 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _error.js | 241 kB | 241 kB | ⚠️ +127 B |
| _error.js gzip | 64.5 kB | 64.5 kB | ⚠️ +57 B |
| hooks.html | 4.04 kB | 4.04 kB | ✓ |
| hooks.html gzip | 1.05 kB | 1.05 kB | ✓ |
| index.js | 242 kB | 242 kB | ⚠️ +127 B |
| index.js gzip | 64.6 kB | 64.6 kB | ⚠️ +58 B |
| link.js | 274 kB | 274 kB | ⚠️ +127 B |
| link.js gzip | 73.6 kB | 73.6 kB | ⚠️ +60 B |
| routerDirect.js | 267 kB | 267 kB | ⚠️ +127 B |
| routerDirect.js gzip | 71.6 kB | 71.7 kB | ⚠️ +62 B |
| withRouter.js | 267 kB | 267 kB | ⚠️ +127 B |
| withRouter.js gzip | 71.7 kB | 71.8 kB | ⚠️ +61 B |
| Overall change | 1.29 MB | 1.3 MB | ⚠️ +635 B |

</details>

</details>


Commit: a3c96be6b7002fdaa654c6326e5cb339753c8a6c

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.6s | ⚠️ +322ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.8 kB | ✓ |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0f1a45b52.js | 19.9 kB | 19.9 kB | ✓ |
| 16b1a7225520..5b52.js gzip | 7.34 kB | 7.34 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..99.module.js | 16.1 kB | 16.1 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 205 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.01 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ✓ |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.09 kB | 1.09 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 14.7s | 14.9s | ⚠️ +175ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.8 kB | ✓ |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0f1a45b52.js | 19.9 kB | 19.9 kB | ✓ |
| 16b1a7225520..5b52.js gzip | 7.34 kB | 7.34 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..99.module.js | 16.1 kB | 16.1 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 205 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _error.js | 241 kB | 241 kB | ⚠️ +127 B |
| _error.js gzip | 64.5 kB | 64.5 kB | ⚠️ +57 B |
| hooks.html | 4.04 kB | 4.04 kB | ✓ |
| hooks.html gzip | 1.05 kB | 1.05 kB | ✓ |
| index.js | 242 kB | 242 kB | ⚠️ +127 B |
| index.js gzip | 64.6 kB | 64.6 kB | ⚠️ +58 B |
| link.js | 274 kB | 274 kB | ⚠️ +127 B |
| link.js gzip | 73.6 kB | 73.6 kB | ⚠️ +60 B |
| routerDirect.js | 267 kB | 267 kB | ⚠️ +127 B |
| routerDirect.js gzip | 71.6 kB | 71.7 kB | ⚠️ +62 B |
| withRouter.js | 267 kB | 267 kB | ⚠️ +127 B |
| withRouter.js gzip | 71.7 kB | 71.8 kB | ⚠️ +61 B |
| Overall change | 1.29 MB | 1.3 MB | ⚠️ +635 B |

</details>

</details>


Commit: efc3cfc380cabde03e248f3d42996f3299710f25

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 13.3s | 13.4s | ⚠️ +68ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..ebc17c08d.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..c08d.js gzip | 7.35 kB | 7.35 kB | ✓ |
| 4952ddcd88e7..49d7903c2.js | 9.6 kB | 9.6 kB | ✓ |
| 4952ddcd88e7..03c2.js gzip | 3.76 kB | 3.76 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..a824c82eb.js | 28.3 kB | 28.3 kB | ✓ |
| de003c3a9d30..82eb.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..9a.module.js | 21.3 kB | 21.3 kB | ✓ |
| 16b1a7225520..dule.js gzip | 8.14 kB | 8.14 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 196 kB | 196 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 2.92 kB | 2.92 kB | ✓ |
| _app.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error.js | 13.2 kB | 13.2 kB | ✓ |
| _error.js gzip | 5.1 kB | 5.1 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.76 kB | 6.76 kB | ✓ |
| link.js gzip | 2.88 kB | 2.88 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 26 kB | 26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 208 B | 208 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.04 kB | 1.04 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.12 kB | 1.12 kB | ✓ |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.1 kB | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 14s | 14.1s | ⚠️ +108ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..ebc17c08d.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..c08d.js gzip | 7.35 kB | 7.35 kB | ✓ |
| 4952ddcd88e7..49d7903c2.js | 9.6 kB | 9.6 kB | ✓ |
| 4952ddcd88e7..03c2.js gzip | 3.76 kB | 3.76 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..a824c82eb.js | 28.3 kB | 28.3 kB | ✓ |
| de003c3a9d30..82eb.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..9a.module.js | 21.3 kB | 21.3 kB | ✓ |
| 16b1a7225520..dule.js gzip | 8.14 kB | 8.14 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 196 kB | 196 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 2.92 kB | 2.92 kB | ✓ |
| _app.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error.js | 13.2 kB | 13.2 kB | ✓ |
| _error.js gzip | 5.1 kB | 5.1 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.76 kB | 6.76 kB | ✓ |
| link.js gzip | 2.88 kB | 2.88 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 26 kB | 26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 208 B | 208 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _error.js | 255 kB | 256 kB | ⚠️ +127 B |
| _error.js gzip | 67.9 kB | 67.9 kB | ⚠️ +59 B |
| hooks.html | 4.19 kB | 4.19 kB | ✓ |
| hooks.html gzip | 1.07 kB | 1.07 kB | ✓ |
| index.js | 256 kB | 256 kB | ⚠️ +127 B |
| index.js gzip | 68 kB | 68.1 kB | ⚠️ +61 B |
| link.js | 288 kB | 288 kB | ⚠️ +127 B |
| link.js gzip | 77.1 kB | 77.1 kB | ⚠️ +65 B |
| routerDirect.js | 281 kB | 281 kB | ⚠️ +127 B |
| routerDirect.js gzip | 75.1 kB | 75.2 kB | ⚠️ +66 B |
| withRouter.js | 281 kB | 281 kB | ⚠️ +127 B |
| withRouter.js gzip | 75.2 kB | 75.3 kB | ⚠️ +64 B |
| Overall change | 1.37 MB | 1.37 MB | ⚠️ +635 B |

</details>

</details>


Commit: ef6aaa9b8fa3730dd86be09e54e4c2b99977b1f4

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 13.5s | 13.4s | -65ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..ebc17c08d.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..c08d.js gzip | 7.35 kB | 7.35 kB | ✓ |
| 4952ddcd88e7..49d7903c2.js | 9.6 kB | 9.6 kB | ✓ |
| 4952ddcd88e7..03c2.js gzip | 3.76 kB | 3.76 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..a824c82eb.js | 28.3 kB | 28.3 kB | ✓ |
| de003c3a9d30..82eb.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..9a.module.js | 21.3 kB | 21.3 kB | ✓ |
| 16b1a7225520..dule.js gzip | 8.14 kB | 8.14 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 196 kB | 196 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 2.92 kB | 2.92 kB | ✓ |
| _app.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error.js | 13.2 kB | 13.2 kB | ✓ |
| _error.js gzip | 5.1 kB | 5.1 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.76 kB | 6.76 kB | ✓ |
| link.js gzip | 2.88 kB | 2.88 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 26 kB | 26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 208 B | 208 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.04 kB | 1.04 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.12 kB | 1.12 kB | ✓ |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.1 kB | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 13.9s | 14s | ⚠️ +75ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..ebc17c08d.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..c08d.js gzip | 7.35 kB | 7.35 kB | ✓ |
| 4952ddcd88e7..49d7903c2.js | 9.6 kB | 9.6 kB | ✓ |
| 4952ddcd88e7..03c2.js gzip | 3.76 kB | 3.76 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..a824c82eb.js | 28.3 kB | 28.3 kB | ✓ |
| de003c3a9d30..82eb.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..9a.module.js | 21.3 kB | 21.3 kB | ✓ |
| 16b1a7225520..dule.js gzip | 8.14 kB | 8.14 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 196 kB | 196 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 2.92 kB | 2.92 kB | ✓ |
| _app.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error.js | 13.2 kB | 13.2 kB | ✓ |
| _error.js gzip | 5.1 kB | 5.1 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.76 kB | 6.76 kB | ✓ |
| link.js gzip | 2.88 kB | 2.88 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 26 kB | 26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 208 B | 208 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _error.js | 255 kB | 256 kB | ⚠️ +127 B |
| _error.js gzip | 67.9 kB | 67.9 kB | ⚠️ +59 B |
| hooks.html | 4.19 kB | 4.19 kB | ✓ |
| hooks.html gzip | 1.07 kB | 1.07 kB | ✓ |
| index.js | 256 kB | 256 kB | ⚠️ +127 B |
| index.js gzip | 68 kB | 68.1 kB | ⚠️ +59 B |
| link.js | 288 kB | 288 kB | ⚠️ +127 B |
| link.js gzip | 77.1 kB | 77.1 kB | ⚠️ +65 B |
| routerDirect.js | 281 kB | 281 kB | ⚠️ +127 B |
| routerDirect.js gzip | 75.1 kB | 75.2 kB | ⚠️ +66 B |
| withRouter.js | 281 kB | 281 kB | ⚠️ +127 B |
| withRouter.js gzip | 75.2 kB | 75.3 kB | ⚠️ +65 B |
| Overall change | 1.37 MB | 1.37 MB | ⚠️ +635 B |

</details>

</details>


Commit: 984a519c517a78373d28c4a6e1187ee719966fb1

File: packages/next/next-server/server/render.tsx [hunk 1]
```diff
@@ -651,7 +651,9 @@ export async function renderToHTML(
     // use replace to allow rendering directly to body in AMP mode
     html = html.replace(
```
Comment (Timer) [inline packages/next/next-server/server/render.tsx]: Would it be better to just not use replace? I think the dollar sign inception is confusing.

Something like this, but with a hoisted constant and maybe re-used index:
```js
html.substring(0, html.indexOf("__NEXT_AMP_RENDER_TARGET__")) +
  `<!-- __NEXT_DATA__ -->${docProps.html}` +
  html.substring(
    html.indexOf("__NEXT_AMP_RENDER_TARGET__") +
      "__NEXT_AMP_RENDER_TARGET__".length
  );
```

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 15.1s | 15.2s | ⚠️ +138ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +659 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..ebc17c08d.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..c08d.js gzip | 7.35 kB | 7.35 kB | ✓ |
| 4952ddcd88e7..49d7903c2.js | 9.6 kB | 9.6 kB | ✓ |
| 4952ddcd88e7..03c2.js gzip | 3.76 kB | 3.76 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..a824c82eb.js | 28.3 kB | 28.3 kB | ✓ |
| de003c3a9d30..82eb.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..9a.module.js | 21.3 kB | 21.3 kB | ✓ |
| 16b1a7225520..dule.js gzip | 8.14 kB | 8.14 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 196 kB | 196 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 2.92 kB | 2.92 kB | ✓ |
| _app.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error.js | 13.2 kB | 13.2 kB | ✓ |
| _error.js gzip | 5.1 kB | 5.1 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.76 kB | 6.76 kB | ✓ |
| link.js gzip | 2.88 kB | 2.88 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 26 kB | 26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 208 B | 208 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.04 kB | 1.04 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.12 kB | 1.12 kB | ✓ |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.1 kB | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| buildDuration | 15.5s | 15.4s | -99ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +659 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..ebc17c08d.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..c08d.js gzip | 7.35 kB | 7.35 kB | ✓ |
| 4952ddcd88e7..49d7903c2.js | 9.6 kB | 9.6 kB | ✓ |
| 4952ddcd88e7..03c2.js gzip | 3.76 kB | 3.76 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..a824c82eb.js | 28.3 kB | 28.3 kB | ✓ |
| de003c3a9d30..82eb.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..9a.module.js | 21.3 kB | 21.3 kB | ✓ |
| 16b1a7225520..dule.js gzip | 8.14 kB | 8.14 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 196 kB | 196 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.js | 2.92 kB | 2.92 kB | ✓ |
| _app.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error.js | 13.2 kB | 13.2 kB | ✓ |
| _error.js gzip | 5.1 kB | 5.1 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.76 kB | 6.76 kB | ✓ |
| link.js gzip | 2.88 kB | 2.88 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 26 kB | 26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 208 B | 208 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/amp-render-target | Change |
| - | - | - | - |
| _error.js | 255 kB | 256 kB | ⚠️ +323 B |
| _error.js gzip | 67.9 kB | 67.9 kB | ⚠️ +85 B |
| hooks.html | 4.19 kB | 4.19 kB | ✓ |
| hooks.html gzip | 1.07 kB | 1.07 kB | ✓ |
| index.js | 256 kB | 256 kB | ⚠️ +323 B |
| index.js gzip | 68 kB | 68.1 kB | ⚠️ +85 B |
| link.js | 288 kB | 288 kB | ⚠️ +323 B |
| link.js gzip | 77.1 kB | 77.1 kB | ⚠️ +85 B |
| routerDirect.js | 281 kB | 281 kB | ⚠️ +323 B |
| routerDirect.js gzip | 75.1 kB | 75.2 kB | ⚠️ +87 B |
| withRouter.js | 281 kB | 281 kB | ⚠️ +323 B |
| withRouter.js gzip | 75.2 kB | 75.3 kB | ⚠️ +87 B |
| Overall change | 1.37 MB | 1.37 MB | ⚠️ +1.61 kB |

</details>

</details>


Commit: 916569bc58525346cdcf58d0edde862c602c3de4

File: packages/next/next-server/server/render.tsx (hunk 1 above)
Comment (ijjk) [reply packages/next/next-server/server/render.tsx]: Updated

**Review by Timer — APPROVED** [review]
