### PR TITLE
Fix re-rendering on client after navigating back from external

### LINKED ISSUE #5648: Safari renders twice while coming back from external page
# Bug report

## Describe the bug

On Safari11, if one leave the nextjs app by going to an external url and hits the back button of the browser, getInitialProps of the last visited page is called twice, once on the server and once on the client side.

## To Reproduce

1) Create an empty project directory. Create the following package.json file inside.

package.json:
```
{
  "name": "nextsafarireprod",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "next": "7.0.2",
    "react": "16.6.1",
    "react-dom": "16.6.1"
  }
}
```

2) Initiate `npm install`
3) Create a `/pages` directory inside the project directory
4) Create `index.js` and `about.js` files in the `/pages` directory with the following content, in the respective order:

```
//index.js

import Link from 'next/link';
export default class Index extends React.Component {
    static async getInitialProps({req}) {
        if (req) {
            return {txt: 'server'}
        }
        else {
            return {txt: 'client'}
        }
    }

    render() {
        return (
            <div>
                <p>Hello Next.JS!</p>
                <p>
                    <Link href="/about" passHref prefetch>
                        <a>Go to About</a>
                    </Link>
                </p>
                <p>{this.props.txt}</p>
            </div>
        )
    }
}
```

```
//about.js

export default class About extends React.Component {
    static async getInitialProps({req}){
        await new Promise((resolve, reject)=>{
            setTimeout(()=>{
                resolve(true);
            },1500)
        });

        if(req){
            console.log('initialProps: server');
            return {txt: 'server'}
        }
        else{
            console.log('initialProps: client');
            return {txt: 'client'}
        }
    }

    render(){
        console.log(this.props.txt, new Date().toISOString());
        return (
            <div>
                <p>
                    <a href="http://www.google.com">Go to Google!</a>
                </p>
                <p>{this.props.txt}</p>
            </div>
        )
    }
}
```

5) Run `npm run build; npm start` for starting a local production server
6) Go to localhost:3000 and open your browser's console
7) Navigate to /about page by the link on the index page (this uses next's Link component)
8) Navigate to google by the link on the about page (this is old-school anchor tag)
9) Hit the back button of the browser, Safari will clear the console while moving back to the nextJS app.
10) Observe the new outputs on the console

## Expected behavior
I would expect a server refresh only, as it happens successfully on Opera and Chrome.

## Screenshots
Screenshot of the Safari Dev Console after coming back from the external page:

screen shot 2018-11-10 at 02 57 58

## System information
 - OS: macOS High Sierra 10.13.6 - macbook pro 2017
 - Browser: Safari 11.1.2
 - Version of Next.js: 7.0.2

## Additional context

Delete the `.next` folder, rebuild and restart the server and open a new private window from scratch every time you retry this, as both browser and the nextjs server tend to cache the pages

### Addendum:
Additionally, Firefox on macOS does neither server nor client refresh in such a case. Normally (if user do not leave the app), going back inside the app always triggers server ssr refresh in any browsers that i have tested so far. but when leaving occurs, safari and firefox behaves strangely in two different ways :/

### PR DESCRIPTION
**Pull request by ijjk**
Some older browser fire a `popState` event on navigating back from an external site. This causes Next.js to re-render on the client side when it doesn't need to. To fix this we tag the history on `unload` so we know to ignore the initial `popState` event.

Fixes: #5648, #6887

### CODE REVIEW

File: packages/next-server/lib/router/router.ts [hunk 1]
```diff
@@ -73,15 +73,20 @@ export default class Router implements IRouterInterface {
...
+      window.addEventListener('unload', () => {
+        // Workaround for weird Firefox bug, see below links
+        // https://github.com/zeit/next.js/issues/3817
+        // https://bugzilla.mozilla.org/show_bug.cgi?id=1422334
+        // TODO: let's remove this once the Firefox bug is resolved
+        if (window.location.search && navigator.userAgent &&
+          navigator.userAgent.match(/firefox/i)) {
+          window.location.replace(window.location.toString())
+        }
+        // Workaround for popstate firing on initial page load when
```
Comment (timneutkens) [inline packages/next-server/lib/router/router.ts]: Just so that I understand this correctly, does this mean that coming back from an external site  re-requests the page and **then** fire popstate? Because in that case it would be easy to detect using `constructor` right 🤔

Comment (ijjk) [reply packages/next-server/lib/router/router.ts]: So the problem occurs when first navigating to one pages e.g. `/` then navigating with `Link` to another `/about` and then clicking an external link `google.com` and then clicking the back button. 

When you click the back button it loads the page from the server and then in some browsers like safari it fires a `popState` event with the state from before navigating to the external site.

The most simple way I've found to detect this is to tag the history state on `unload` so that we know to ignore that `popState` event.

**Comment by gustavoteodoro** [comment]
Thanks for this PR, @ijjk . Currently, the Next.js isn't compatible with Safari so also all iPhone browsers because of this bug #5648

File: packages/next-server/lib/router/router.ts [hunk 2]
```diff
@@ -75,16 +75,20 @@ export default class Router implements IRouterInterface {
...
+        // navigating back from an external site
+        const { url, as, options }: any = history.state || {}
```
Comment (Timer) [inline packages/next-server/lib/router/router.ts]:
```suggestion
        if (history.state) {
          const { url, as, options }: any = history.state
```

File: packages/next-server/lib/router/router.ts [hunk 3]
```diff
@@ -75,16 +75,20 @@ export default class Router implements IRouterInterface {
...
+        this.changeState('replaceState', url, as, { ...options, fromExternal: true })
```
Comment (Timer) [inline packages/next-server/lib/router/router.ts]:
```suggestion
          this.changeState('replaceState', url, as, { ...options, fromExternal: true })
        }
```

File: packages/next-server/lib/router/router.ts [hunk 4]
```diff
@@ -116,6 +122,12 @@ export default class Router implements IRouterInterface {
       return
     }
 
+    // Make sure we don't re-render on initial load,
+    // can be caused by navigating back from an external site
+    if (e.state.options.fromExternal) {
```
Comment (Timer) [inline packages/next-server/lib/router/router.ts]:
```suggestion
    if (e.state.options && e.state.options.fromExternal) {
```

**Review by Timer — APPROVED** [review]
