### PR TITLE
fix(examples): invalid `with-apollo` and `with-graphql-hooks`

### LINKED ISSUE #9865: Example "with-graphql-hooks" is not working with server side rendering
# Bug report

## Describe the bug

When i build the with-graphql-hooks example and run check the server side rendered html output, the grpahql data is not part of the response.

## To Reproduce

Inside the examples/with-graphql-hooks folder

```
npm install
npm run dev
curl http://localhost:3000
```

## Expected behavior

I expect (based on the code) that the graphql examples renders the result of the graphql response inside the server side generated html.

During my debugging i figure out that the graphql client is created multiple times and because of that, different threads working with different graphql clients. This result into an empty ssrPromises attribute and an empty state: https://github.com/zeit/next.js/blob/canary/examples/with-graphql-hooks/lib/with-graphql-client.js#L24

https://github.com/zeit/next.js/blob/canary/examples/with-graphql-hooks/lib/init-graphql.js#L20

I'm not sure why it's called multiple times, but this line above will create (and this is correct) every time a new client.

I found a similar issue here with apollo: https://github.com/zeit/next.js/pull/8917

### PR DESCRIPTION
**Pull request by devjiwonchoi**
### Why?

The examples `with-apollo` and `with-graphql-hooks` included outdated API endpoints and packages.
This resulted in the **failed Vercel Deployment** of the examples.

<details><summary>Screenshot of failed deployments</summary>
<p>

#### with-graphql-hooks

Screenshot 2024-04-08 at 3 04 05 PM

#### with-apollo

Screenshot 2024-04-08 at 3 05 26 PM

</p>
</details> 

### How?

- Migrated examples from `pages` to `app` router and removed invalid API endpoints.
- Refactored the example to a minimal template as possible with essential features.

Closes #9865 #10253 #36112

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 0dff32db2ebe8358eaccf0d4ae3b8cb7ef74bdba

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 0dff32db2ebe8358eaccf0d4ae3b8cb7ef74bdba

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

File: examples/with-apollo/src/client-components/apollo-client-provider.tsx [hunk 1]
```diff
@@ -0,0 +1,16 @@
+import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client";
+
+export const client = new ApolloClient({
+  // URL retrieved from official apollo graphql blog
+  // See https://www.apollographql.com/blog/using-apollo-client-with-next-js-13-releasing-an-official-library-to-support-the-app-router
+  uri: "https://main--spacex-l4uc6p.apollographos.net/graphql",
```
Comment (devjiwonchoi) [inline examples/with-apollo/src/client-components/apollo-client-provider.tsx:6]: Proposal: It'd be nice if we open a graphql API endpoint like the [ones already used on tests](https://next-data-api-endpoint.vercel.app/api/random).

Comment (samcx) [reply examples/with-apollo/src/client-components/apollo-client-provider.tsx:6]: @devjiwonchoi Definitely a nice-to-have! But not strictly required for `/examples`.

**Review by samcx — APPROVED** [review]
<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

File: examples/with-apollo/src/client-components/apollo-client-provider.tsx (hunk 1 above)
Comment (devjiwonchoi) [reply examples/with-apollo/src/client-components/apollo-client-provider.tsx:6]: Yeah, IMO it'd be great to prevent issues like: https://github.com/vercel/next.js/issues/36112#issuecomment-1098849154

Thanks for reviewing!!

**Comment by devjiwonchoi** [comment]
@samcx it'd be great if you link https://github.com/vercel/next.js/issues/10253 https://github.com/vercel/next.js/issues/36112 as closed too!

**Comment by samcx** [comment]
@devjiwonchoi Curious why those didn't automatically close

**Comment by devjiwonchoi** [comment]
@samcx hmm, just realized I had to repeat `closes` three times like:

```
Resolves #10, resolves #123, resolves octo-org/octo-repo#100
```

x-ref: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
