### PR TITLE
Fix next/link can't jump to non-latin anchors

### LINKED ISSUE #11109: Jump link anchors dont work
# Bug report

## Describe the bug

When clicking an anchor tag in a different page with a jump to id tag, it raises an error and doesnt go.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

` <a
                  className='nav-link'
                  href='https://github.com/zeit/next.js/#documentation'
                >
                  Docs
                </a>
`
## Expected behavior

should redirect to github and scroll to documentation tag

## Screenshots

Screenshot 2020-03-16 at 15 13 05

## System information

- Browser (if applies): Chrome
- Nextjs version: 9.1.6

## Additional context

I've tried this in another project without nextjs and it works fine i also tried in a random 
place like

https://jsfiddle.net/uqxck4jv/

### PR DESCRIPTION
**Pull request by hulufei**
fixes #11109 

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by hulufei** [comment]
I have made it works for anchors in the same page, but got stuck with links from another page. I need someone to help me to work it out. Thanks.

**Comment by hulufei** [comment]
I think I figure it out.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| buildDuration | 15.2s | 15.2s | ✓ |
| buildDurationCached | 6.1s | 6.1s | -1ms |
| nodeModulesSize | 481 MB | 481 MB | ⚠️ +499 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.978 | 3.009 | ⚠️ +0.03 |
| / avg req/sec | 839.55 | 830.74 | ⚠️ -8.81 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.173 | 1.16 | -0.01 |
| /error-in-render avg req/sec | 2130.84 | 2154.53 | +23.69 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.7 kB | ⚠️ +16 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ⚠️ +16 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.73 kB | 5.73 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16 kB | 16 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 461 B | 461 B | ✓ |
| Overall change | 461 B | 461 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 530 B | -1 B |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -5134,6 +5134,11 @@
                             window.location.href = url;
                             return _ctx.abrupt("return", false);
                           case 3:
+                            // Decode hash to make non-latin anchor works.
+                            // A hash mark # is the optional last part of a URL
+                            as = as.replace(/#.+$/, function(m) {
+                              return decodeURIComponent(m);
+                            });
                             shouldResolveHref =
                               options._h ||
                               options._shouldResolveHref ||
@@ -5146,7 +5151,7 @@
                             }
                             prevLocale = nextState.locale;
                             if (true) {
-                              _ctx.next = 19;
+                              _ctx.next = 20;
                               break;
                             }
                             nextState.locale =
@@ -5195,14 +5200,14 @@
                             if (false) {
                             }
                             if (!didNavigate) {
-                              _ctx.next = 19;
+                              _ctx.next = 20;
                               break;
                             }
                             return _ctx.abrupt(
                               "return",
                               new Promise(function() {})
                             );
-                          case 19:
+                          case 20:
                             if (!options._h) {
                               _this.isSsr = false;
                             }
@@ -5244,7 +5249,7 @@
                                 !localeChange
                               )
                             ) {
-                              _ctx.next = 36;
+                              _ctx.next = 37;
                               break;
                             }
                             nextState.asPath = cleanedAs;
@@ -5276,21 +5281,21 @@
                               routeProps
                             );
                             return _ctx.abrupt("return", true);
-                          case 36:
+                          case 37:
                             parsed = (0, _parseRelativeUrl).parseRelativeUrl(
                               url
                             );
                             (pathname = parsed.pathname),
                               (query = parsed.query);
-                            _ctx.prev = 39;
+                            _ctx.prev = 40;
                             _ctx.t0 = _slicedToArray;
-                            _ctx.next = 44;
+                            _ctx.next = 45;
                             return Promise.all([
                               _this.pageLoader.getPageList(),
                               (0, _routeLoader).getClientBuildManifest(),
                               _this.pageLoader.getMiddlewareList()
                             ]);
-                          case 44:
+                          case 45:
                             _ctx.t1 = _ctx.sent;
                             ref1 = (0, _ctx.t0)(_ctx.t1, 2);
                             pages = ref1[0];
@@ -5298,16 +5303,16 @@
                               (rewrites = ref2.__rewrites),
                               ref2;
                             ref1;
-                            _ctx.next = 55;
+                            _ctx.next = 56;
                             break;
-                          case 51:
-                            _ctx.prev = 51;
-                            _ctx.t2 = _ctx["catch"](39);
+                          case 52:
+                            _ctx.prev = 52;
+                            _ctx.t2 = _ctx["catch"](40);
                             // If we fail to resolve the page list or client-build manifest, we must
                             // do a server-side transition:
                             window.location.href = as;
                             return _ctx.abrupt("return", false);
-                          case 55:
+                          case 56:
                             // If asked to change the current URL we should reload the current page
                             // (not location.reload() but reload getInitialProps and other Next.js stuffs)
                             // We also need to set the method = replaceState always
@@ -5329,12 +5334,12 @@
                             if (
                               !(shouldResolveHref && pathname !== "/_error")
                             ) {
-                              _ctx.next = 70;
+                              _ctx.next = 71;
                               break;
                             }
                             options._shouldResolveHref = true;
                             if (true) {
-                              _ctx.next = 69;
+                              _ctx.next = 70;
                               break;
                             }
                             rewritesResult = (0, _resolveRewrites).default(
@@ -5350,12 +5355,12 @@
                               _this.locales
                             );
                             if (!rewritesResult.externalDest) {
-                              _ctx.next = 65;
+                              _ctx.next = 66;
                               break;
                             }
                             location.href = as;
                             return _ctx.abrupt("return", true);
-                          case 65:
+                          case 66:
                             resolvedAs = rewritesResult.asPath;
                             if (
                               rewritesResult.matchedPage &&
@@ -5369,9 +5374,9 @@
                                 parsed
                               );
                             }
-                            _ctx.next = 70;
+                            _ctx.next = 71;
                             break;
-                          case 69: {
+                          case 70: {
                             parsed.pathname = resolveDynamicRoute(
                               pathname,
                               pages
@@ -5384,13 +5389,13 @@
                               );
                             }
                           }
-                          case 70:
+                          case 71:
                             if (isLocalURL(as)) {
-                              _ctx.next = 75;
+                              _ctx.next = 76;
                               break;
                             }
                             if (true) {
-                              _ctx.next = 73;
+                              _ctx.next = 74;
                               break;
                             }
                             throw new Error(
@@ -5402,10 +5407,10 @@
                                 ) +
                                 "\nSee more info: https://nextjs.org/docs/messages/invalid-relative-url-external-as"
                             );
-                          case 73:
+                          case 74:
                             window.location.href = as;
                             return _ctx.abrupt("return", false);
-                          case 75:
+                          case 76:
                             resolvedAs = delLocale(
                               delBasePath(resolvedAs),
                               nextState.locale
@@ -5422,10 +5427,10 @@
                                   ))
                               )
                             ) {
-                              _ctx.next = 96;
+                              _ctx.next = 97;
                               break;
                             }
-                            _ctx.next = 79;
+                            _ctx.next = 80;
                             return _this._preflightRequest({
                               as: as,
                               cache: "production" === "production",
@@ -5435,10 +5440,10 @@
                               locale: nextState.locale,
                               isPreview: nextState.isPreview
                             });
-                          case 79:
+                          case 80:
                             effect = _ctx.sent;
                             if (!(effect.type === "rewrite")) {
-                              _ctx.next = 84;
+                              _ctx.next = 85;
                               break;
                             }
                             {
@@ -5454,11 +5459,11 @@
                                 parsed
                               );
                             }
-                            _ctx.next = 96;
+                            _ctx.next = 97;
                             break;
-                          case 84:
+                          case 85:
                             if (!(effect.type === "redirect" && effect.newAs)) {
-                              _ctx.next = 88;
+                              _ctx.next = 89;
                               break;
                             }
                             return _ctx.abrupt(
@@ -5470,13 +5475,13 @@
                                 options
                               )
                             );
-                          case 88:
+                          case 89:
                             if (
                               !(
                                 effect.type === "redirect" && effect.destination
                               )
                             ) {
-                              _ctx.next = 93;
+                              _ctx.next = 94;
                               break;
                             }
                             window.location.href = effect.destination;
@@ -5484,14 +5489,14 @@
                               "return",
                               new Promise(function() {})
                             );
-                          case 93:
+                          case 94:
                             if (
                               !(
                                 effect.type === "refresh" &&
                                 as !== window.location.pathname
                               )
                             ) {
-                              _ctx.next = 96;
+                              _ctx.next = 97;
                               break;
                             }
                             window.location.href = as;
@@ -5499,13 +5504,13 @@
                               "return",
                               new Promise(function() {})
                             );
-                          case 96:
+                          case 97:
                             route = (0,
                             _normalizeTrailingSlash).removePathTrailingSlash(
                               pathname
                             );
                             if (!(0, _isDynamic).isDynamicRoute(route)) {
-                              _ctx.next = 112;
+                              _ctx.next = 113;
                               break;
                             }
                             parsedAs1 = (0, _parseRelativeUrl).parseRelativeUrl(
@@ -5526,7 +5531,7 @@
                                 (shouldInterpolate && !interpolatedAs.result)
                               )
                             ) {
-                              _ctx.next = 111;
+                              _ctx.next = 112;
                               break;
                             }
                             missingParams = Object.keys(
@@ -5535,7 +5540,7 @@
                               return !query[param];
                             });
                             if (!(missingParams.length > 0)) {
-                              _ctx.next = 109;
+                              _ctx.next = 110;
                               break;
                             }
                             if (false) {
@@ -5563,10 +5568,10 @@
                                     : "incompatible-href-as"
                                 )
                             );
-                          case 109:
-                            _ctx.next = 112;
+                          case 110:
+                            _ctx.next = 113;
                             break;
-                          case 111:
+                          case 112:
                             if (shouldInterpolate) {
                               as = (0, _formatUrl).formatWithValidation(
                                 Object.assign({}, parsedAs1, {
@@ -5581,14 +5586,14 @@
                               // Merge params into `query`, overwriting any specified in search
                               Object.assign(query, routeMatch);
                             }
-                          case 112:
+                          case 113:
                             Router.events.emit(
                               "routeChangeStart",
                               as,
                               routeProps
                             );
-                            _ctx.prev = 113;
-                            _ctx.next = 117;
+                            _ctx.prev = 114;
+                            _ctx.next = 118;
                             return _this.getRouteInfo(
                               route,
                               pathname,
@@ -5599,7 +5604,7 @@
                               nextState.locale,
                               nextState.isPreview
                             );
-                          case 117:
+                          case 118:
                             routeInfo = _ctx.sent;
                             (error = routeInfo.error),
                               (props = routeInfo.props),
@@ -5617,13 +5622,13 @@
                               });
                             }
                             if (!((__N_SSG || __N_SSP) && props)) {
-                              _ctx.next = 146;
+                              _ctx.next = 147;
                               break;
                             }
                             if (
                               !(props.pageProps && props.pageProps.__N_REDIRECT)
                             ) {
-                              _ctx.next = 131;
+                              _ctx.next = 132;
                               break;
                             }
                             destination = props.pageProps.__N_REDIRECT;
@@ -5633,7 +5638,7 @@
                                 props.pageProps.__N_REDIRECT_BASE_PATH !== false
                               )
                             ) {
-                              _ctx.next = 129;
+                              _ctx.next = 130;
                               break;
                             }
                             parsedHref = (0,
@@ -5653,31 +5658,31 @@
                               "return",
                               _this.change(method, newUrl, newAs, options)
                             );
-                          case 129:
+                          case 130:
                             window.location.href = destination;
                             return _ctx.abrupt(
                               "return",
                               new Promise(function() {})
                             );
-                          case 131:
+                          case 132:
                             nextState.isPreview = !!props.__N_PREVIEW;
                             if (!(props.notFound === SSG_DATA_NOT_FOUND)) {
-                              _ctx.next = 146;
+                              _ctx.next = 147;
                               break;
                             }
-                            _ctx.prev = 134;
-                            _ctx.next = 137;
+                            _ctx.prev = 135;
+                            _ctx.next = 138;
                             return _this.fetchComponent("/404");
-                          case 137:
+                          case 138:
                             notFoundRoute = "/404";
-                            _ctx.next = 143;
+                            _ctx.next = 144;
                             break;
-                          case 140:
-                            _ctx.prev = 140;
-                            _ctx.t3 = _ctx["catch"](134);
+                          case 141:
+                            _ctx.prev = 141;
+                            _ctx.t3 = _ctx["catch"](135);
                             notFoundRoute = "/_error";
-                          case 143:
-                            _ctx.next = 145;
+                          case 144:
+                            _ctx.next = 146;
                             return _this.getRouteInfo(
                               notFoundRoute,
                               notFoundRoute,
@@ -5690,9 +5695,9 @@
                               nextState.locale,
                               nextState.isPreview
                             );
-                          case 145:
-                            routeInfo = _ctx.sent;
                           case 146:
+                            routeInfo = _ctx.sent;
+                          case 147:
                             Router.events.emit(
                               "beforeHistoryChange",
                               as,
@@ -5730,7 +5735,7 @@
                                   y: 0
                                 }
                               : null;
-                            _ctx.next = 155;
+                            _ctx.next = 156;
                             return _this
                               .set(
                                 _objectSpread({}, nextState, {
@@ -5749,9 +5754,9 @@
                                 if (e.cancelled) error = error || e;
                                 else throw e;
                               });
-                          case 155:
+                          case 156:
                             if (!error) {
-                              _ctx.next = 158;
+                              _ctx.next = 159;
                               break;
                             }
                             Router.events.emit(
@@ -5761,7 +5766,7 @@
                               routeProps
                             );
                             throw error;
-                          case 158:
+                          case 159:
                             if (false) {
                             }
                             Router.events.emit(
@@ -5769,23 +5774,26 @@
                               as,
                               routeProps
                             );
+                            if (shouldScroll) {
+                              _this.scrollToHash(as);
+                            }
                             return _ctx.abrupt("return", true);
-                          case 163:
-                            _ctx.prev = 163;
-                            _ctx.t4 = _ctx["catch"](113);
+                          case 165:
+                            _ctx.prev = 165;
+                            _ctx.t4 = _ctx["catch"](114);
                             if (
                               !(
                                 (0, _isError).default(_ctx.t4) &&
                                 _ctx.t4.cancelled
                               )
                             ) {
-                              _ctx.next = 167;
+                              _ctx.next = 169;
                               break;
                             }
                             return _ctx.abrupt("return", false);
-                          case 167:
+                          case 169:
                             throw _ctx.t4;
-                          case 168:
+                          case 170:
                           case "end":
                             return _ctx.stop();
                         }
@@ -5793,9 +5801,9 @@
                     _callee,
                     null,
                     [
-                      [39, 51],
-                      [113, 163],
-                      [134, 140]
+                      [40, 52],
+                      [114, 165],
+                      [135, 141]
                     ]
                   );
                 })
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ae64527b37d6c65e.js"
+      src="/_next/static/chunks/main-61b899d9e1ad08d8.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ae64527b37d6c65e.js"
+      src="/_next/static/chunks/main-61b899d9e1ad08d8.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ae64527b37d6c65e.js"
+      src="/_next/static/chunks/main-61b899d9e1ad08d8.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| buildDuration | 17.3s | 17.8s | ⚠️ +416ms |
| buildDurationCached | 6s | 6s | -25ms |
| nodeModulesSize | 481 MB | 481 MB | ⚠️ +499 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.981 | 2.983 | 0 |
| / avg req/sec | 838.69 | 838.11 | ⚠️ -0.58 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.161 | 1.153 | -0.01 |
| /error-in-render avg req/sec | 2153.17 | 2169.13 | +15.96 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 29.1 kB | 29.1 kB | ⚠️ +22 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.9 kB | 72.9 kB | ⚠️ +22 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.02 kB | 3.02 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.78 kB | 5.78 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.44 kB | 2.44 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.1 kB | 16.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 457 B | 457 B | ✓ |
| Overall change | 457 B | 457 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | hulufei/next.js fix-11109 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 529 B | -2 B |
| link.html gzip | 544 B | 543 B | -1 B |
| withRouter.html gzip | 526 B | 525 B | -1 B |
| Overall change | 1.6 kB | 1.6 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -5134,6 +5134,11 @@
                             window.location.href = url;
                             return _ctx.abrupt("return", false);
                           case 3:
+                            // Decode hash to make non-latin anchor works.
+                            // A hash mark # is the optional last part of a URL
+                            as = as.replace(/#.+$/, function(m) {
+                              return decodeURIComponent(m);
+                            });
                             shouldResolveHref =
                               options._h ||
                               options._shouldResolveHref ||
@@ -5146,7 +5151,7 @@
                             }
                             prevLocale = nextState.locale;
                             if (true) {
-                              _ctx.next = 19;
+                              _ctx.next = 20;
                               break;
                             }
                             nextState.locale =
@@ -5195,14 +5200,14 @@
                             if (false) {
                             }
                             if (!didNavigate) {
-                              _ctx.next = 19;
+                              _ctx.next = 20;
                               break;
                             }
                             return _ctx.abrupt(
                               "return",
                               new Promise(function() {})
                             );
-                          case 19:
+                          case 20:
                             if (!options._h) {
                               _this.isSsr = false;
                             }
@@ -5244,7 +5249,7 @@
                                 !localeChange
                               )
                             ) {
-                              _ctx.next = 36;
+                              _ctx.next = 37;
                               break;
                             }
                             nextState.asPath = cleanedAs;
@@ -5276,21 +5281,21 @@
                               routeProps
                             );
                             return _ctx.abrupt("return", true);
-                          case 36:
+                          case 37:
                             parsed = (0, _parseRelativeUrl).parseRelativeUrl(
                               url
                             );
                             (pathname = parsed.pathname),
                               (query = parsed.query);
-                            _ctx.prev = 39;
+                            _ctx.prev = 40;
                             _ctx.t0 = _slicedToArray;
-                            _ctx.next = 44;
+                            _ctx.next = 45;
                             return Promise.all([
                               _this.pageLoader.getPageList(),
                               (0, _routeLoader).getClientBuildManifest(),
                               _this.pageLoader.getMiddlewareList()
                             ]);
-                          case 44:
+                          case 45:
                             _ctx.t1 = _ctx.sent;
                             ref1 = (0, _ctx.t0)(_ctx.t1, 2);
                             pages = ref1[0];
@@ -5298,16 +5303,16 @@
                               (rewrites = ref2.__rewrites),
                               ref2;
                             ref1;
-                            _ctx.next = 55;
+                            _ctx.next = 56;
                             break;
-                          case 51:
-                            _ctx.prev = 51;
-                            _ctx.t2 = _ctx["catch"](39);
+                          case 52:
+                            _ctx.prev = 52;
+                            _ctx.t2 = _ctx["catch"](40);
                             // If we fail to resolve the page list or client-build manifest, we must
                             // do a server-side transition:
                             window.location.href = as;
                             return _ctx.abrupt("return", false);
-                          case 55:
+                          case 56:
                             // If asked to change the current URL we should reload the current page
                             // (not location.reload() but reload getInitialProps and other Next.js stuffs)
                             // We also need to set the method = replaceState always
@@ -5329,12 +5334,12 @@
                             if (
                               !(shouldResolveHref && pathname !== "/_error")
                             ) {
-                              _ctx.next = 70;
+                              _ctx.next = 71;
                               break;
                             }
                             options._shouldResolveHref = true;
                             if (true) {
-                              _ctx.next = 69;
+                              _ctx.next = 70;
                               break;
                             }
                             rewritesResult = (0, _resolveRewrites).default(
@@ -5350,12 +5355,12 @@
                               _this.locales
                             );
                             if (!rewritesResult.externalDest) {
-                              _ctx.next = 65;
+                              _ctx.next = 66;
                               break;
                             }
                             location.href = as;
                             return _ctx.abrupt("return", true);
-                          case 65:
+                          case 66:
                             resolvedAs = rewritesResult.asPath;
                             if (
                               rewritesResult.matchedPage &&
@@ -5369,9 +5374,9 @@
                                 parsed
                               );
                             }
-                            _ctx.next = 70;
+                            _ctx.next = 71;
                             break;
-                          case 69: {
+                          case 70: {
                             parsed.pathname = resolveDynamicRoute(
                               pathname,
                               pages
@@ -5384,13 +5389,13 @@
                               );
                             }
                           }
-                          case 70:
+                          case 71:
                             if (isLocalURL(as)) {
-                              _ctx.next = 75;
+                              _ctx.next = 76;
                               break;
                             }
                             if (true) {
-                              _ctx.next = 73;
+                              _ctx.next = 74;
                               break;
                             }
                             throw new Error(
@@ -5402,10 +5407,10 @@
                                 ) +
                                 "\nSee more info: https://nextjs.org/docs/messages/invalid-relative-url-external-as"
                             );
-                          case 73:
+                          case 74:
                             window.location.href = as;
                             return _ctx.abrupt("return", false);
-                          case 75:
+                          case 76:
                             resolvedAs = delLocale(
                               delBasePath(resolvedAs),
                               nextState.locale
@@ -5422,10 +5427,10 @@
                                   ))
                               )
                             ) {
-                              _ctx.next = 96;
+                              _ctx.next = 97;
                               break;
                             }
-                            _ctx.next = 79;
+                            _ctx.next = 80;
                             return _this._preflightRequest({
                               as: as,
                               cache: "production" === "production",
@@ -5435,10 +5440,10 @@
                               locale: nextState.locale,
                               isPreview: nextState.isPreview
                             });
-                          case 79:
+                          case 80:
                             effect = _ctx.sent;
                             if (!(effect.type === "rewrite")) {
-                              _ctx.next = 84;
+                              _ctx.next = 85;
                               break;
                             }
                             {
@@ -5454,11 +5459,11 @@
                                 parsed
                               );
                             }
-                            _ctx.next = 96;
+                            _ctx.next = 97;
                             break;
-                          case 84:
+                          case 85:
                             if (!(effect.type === "redirect" && effect.newAs)) {
-                              _ctx.next = 88;
+                              _ctx.next = 89;
                               break;
                             }
                             return _ctx.abrupt(
@@ -5470,13 +5475,13 @@
                                 options
                               )
                             );
-                          case 88:
+                          case 89:
                             if (
                               !(
                                 effect.type === "redirect" && effect.destination
                               )
                             ) {
-                              _ctx.next = 93;
+                              _ctx.next = 94;
                               break;
                             }
                             window.location.href = effect.destination;
@@ -5484,14 +5489,14 @@
                               "return",
                               new Promise(function() {})
                             );
-                          case 93:
+                          case 94:
                             if (
                               !(
                                 effect.type === "refresh" &&
                                 as !== window.location.pathname
                               )
                             ) {
-                              _ctx.next = 96;
+                              _ctx.next = 97;
                               break;
                             }
                             window.location.href = as;
@@ -5499,13 +5504,13 @@
                               "return",
                               new Promise(function() {})
                             );
-                          case 96:
+                          case 97:
                             route = (0,
                             _normalizeTrailingSlash).removePathTrailingSlash(
                               pathname
                             );
                             if (!(0, _isDynamic).isDynamicRoute(route)) {
-                              _ctx.next = 112;
+                              _ctx.next = 113;
                               break;
                             }
                             parsedAs1 = (0, _parseRelativeUrl).parseRelativeUrl(
@@ -5526,7 +5531,7 @@
                                 (shouldInterpolate && !interpolatedAs.result)
                               )
                             ) {
-                              _ctx.next = 111;
+                              _ctx.next = 112;
                               break;
                             }
                             missingParams = Object.keys(
@@ -5535,7 +5540,7 @@
                               return !query[param];
                             });
                             if (!(missingParams.length > 0)) {
-                              _ctx.next = 109;
+                              _ctx.next = 110;
                               break;
                             }
                             if (false) {
@@ -5563,10 +5568,10 @@
                                     : "incompatible-href-as"
                                 )
                             );
-                          case 109:
-                            _ctx.next = 112;
+                          case 110:
+                            _ctx.next = 113;
                             break;
-                          case 111:
+                          case 112:
                             if (shouldInterpolate) {
                               as = (0, _formatUrl).formatWithValidation(
                                 Object.assign({}, parsedAs1, {
@@ -5581,14 +5586,14 @@
                               // Merge params into `query`, overwriting any specified in search
                               Object.assign(query, routeMatch);
                             }
-                          case 112:
+                          case 113:
                             Router.events.emit(
                               "routeChangeStart",
                               as,
                               routeProps
                             );
-                            _ctx.prev = 113;
-                            _ctx.next = 117;
+                            _ctx.prev = 114;
+                            _ctx.next = 118;
                             return _this.getRouteInfo(
                               route,
                               pathname,
@@ -5599,7 +5604,7 @@
                               nextState.locale,
                               nextState.isPreview
                             );
-                          case 117:
+                          case 118:
                             routeInfo = _ctx.sent;
                             (error = routeInfo.error),
                               (props = routeInfo.props),
@@ -5617,13 +5622,13 @@
                               });
                             }
                             if (!((__N_SSG || __N_SSP) && props)) {
-                              _ctx.next = 146;
+                              _ctx.next = 147;
                               break;
                             }
                             if (
                               !(props.pageProps && props.pageProps.__N_REDIRECT)
                             ) {
-                              _ctx.next = 131;
+                              _ctx.next = 132;
                               break;
                             }
                             destination = props.pageProps.__N_REDIRECT;
@@ -5633,7 +5638,7 @@
                                 props.pageProps.__N_REDIRECT_BASE_PATH !== false
                               )
                             ) {
-                              _ctx.next = 129;
+                              _ctx.next = 130;
                               break;
                             }
                             parsedHref = (0,
@@ -5653,31 +5658,31 @@
                               "return",
                               _this.change(method, newUrl, newAs, options)
                             );
-                          case 129:
+                          case 130:
                             window.location.href = destination;
                             return _ctx.abrupt(
                               "return",
                               new Promise(function() {})
                             );
-                          case 131:
+                          case 132:
                             nextState.isPreview = !!props.__N_PREVIEW;
                             if (!(props.notFound === SSG_DATA_NOT_FOUND)) {
-                              _ctx.next = 146;
+                              _ctx.next = 147;
                               break;
                             }
-                            _ctx.prev = 134;
-                            _ctx.next = 137;
+                            _ctx.prev = 135;
+                            _ctx.next = 138;
                             return _this.fetchComponent("/404");
-                          case 137:
+                          case 138:
                             notFoundRoute = "/404";
-                            _ctx.next = 143;
+                            _ctx.next = 144;
                             break;
-                          case 140:
-                            _ctx.prev = 140;
-                            _ctx.t3 = _ctx["catch"](134);
+                          case 141:
+                            _ctx.prev = 141;
+                            _ctx.t3 = _ctx["catch"](135);
                             notFoundRoute = "/_error";
-                          case 143:
-                            _ctx.next = 145;
+                          case 144:
+                            _ctx.next = 146;
                             return _this.getRouteInfo(
                               notFoundRoute,
                               notFoundRoute,
@@ -5690,9 +5695,9 @@
                               nextState.locale,
                               nextState.isPreview
                             );
-                          case 145:
-                            routeInfo = _ctx.sent;
                           case 146:
+                            routeInfo = _ctx.sent;
+                          case 147:
                             Router.events.emit(
                               "beforeHistoryChange",
                               as,
@@ -5730,7 +5735,7 @@
                                   y: 0
                                 }
                               : null;
-                            _ctx.next = 155;
+                            _ctx.next = 156;
                             return _this
                               .set(
                                 _objectSpread({}, nextState, {
@@ -5749,9 +5754,9 @@
                                 if (e.cancelled) error = error || e;
                                 else throw e;
                               });
-                          case 155:
+                          case 156:
                             if (!error) {
-                              _ctx.next = 158;
+                              _ctx.next = 159;
                               break;
                             }
                             Router.events.emit(
@@ -5761,7 +5766,7 @@
                               routeProps
                             );
                             throw error;
-                          case 158:
+                          case 159:
                             if (false) {
                             }
                             Router.events.emit(
@@ -5769,23 +5774,26 @@
                               as,
                               routeProps
                             );
+                            if (shouldScroll) {
+                              _this.scrollToHash(as);
+                            }
                             return _ctx.abrupt("return", true);
-                          case 163:
-                            _ctx.prev = 163;
-                            _ctx.t4 = _ctx["catch"](113);
+                          case 165:
+                            _ctx.prev = 165;
+                            _ctx.t4 = _ctx["catch"](114);
                             if (
                               !(
                                 (0, _isError).default(_ctx.t4) &&
                                 _ctx.t4.cancelled
                               )
                             ) {
-                              _ctx.next = 167;
+                              _ctx.next = 169;
                               break;
                             }
                             return _ctx.abrupt("return", false);
-                          case 167:
+                          case 169:
                             throw _ctx.t4;
-                          case 168:
+                          case 170:
                           case "end":
                             return _ctx.stop();
                         }
@@ -5793,9 +5801,9 @@
                     _callee,
                     null,
                     [
-                      [39, 51],
-                      [113, 163],
-                      [134, 140]
+                      [40, 52],
+                      [114, 165],
+                      [135, 141]
                     ]
                   );
                 })
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ae64527b37d6c65e.js"
+      src="/_next/static/chunks/main-61b899d9e1ad08d8.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ae64527b37d6c65e.js"
+      src="/_next/static/chunks/main-61b899d9e1ad08d8.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ae64527b37d6c65e.js"
+      src="/_next/static/chunks/main-61b899d9e1ad08d8.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 25acbed0d207e01002c58e4b7cf79e5a28260b2d

**Comment by hulufei** [comment]
@ijjk Could you check it again? Thanks.

**Comment by hulufei** [comment]
It's weird, I checked the failing log, and didn't find any assert failures. I had run `yarn testheadless --testPathPattern "client-navigation" -t 'Client Navigation'` on local with [2900d7e](https://github.com/vercel/next.js/pull/36430/commits/2900d7ed1faf35a627bdb1ba0b1fc9c5397c45b9), all tests passed. 

Anything I can do to continue?

File: packages/next/shared/lib/router/router.ts [hunk 1]
```diff
@@ -922,6 +922,11 @@ export default class Router implements BaseRouter {
       window.location.href = url
       return false
     }
+    // Decode hash to make non-latin anchor works.
+    // A hash mark # is the optional last part of a URL
+    const hashRegex = /#.+$/
+    as = as.replace(hashRegex, (m) => decodeURIComponent(m))
```
Comment (ijjk) [inline packages/next/shared/lib/router/router.ts:928]: Can we move the hash decoding directly to `scrollToHash` and make sure to only decode the `hash` value being used for `getElementById`? I don't think we want to modify the `asPath` and store it in the decoded format.

Comment (hulufei) [reply packages/next/shared/lib/router/router.ts:928]: Good point.

File: packages/next/shared/lib/router/router.ts [hunk 2]
```diff
@@ -1389,6 +1389,12 @@ export default class Router implements BaseRouter {
       }
       Router.events.emit('routeChangeComplete', as, routeProps)
 
+      // A hash mark # is the optional last part of a URL
+      const hashRegex = /#.+$/
+      if (shouldScroll && hashRegex.test(as)) {
+        this.scrollToHash(as)
```
Comment (ijjk) [inline packages/next/shared/lib/router/router.ts:1395]: Why is this extra `scrollToHash` call needed?

Comment (hulufei) [reply packages/next/shared/lib/router/router.ts:1395]: When navigate to another page with non-latin anchors, the browser won't scroll to that anchor. We have to call `scrollToHash` manually after router change completed.

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
Thanks for the PR!
