### PR TITLE
[next] Fix to not call middleware with shallow push, fix middleware call wit…

### LINKED ISSUE #32655: shallow: true calls the middleware when using middlewares
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

v16.6.1

### What browser are you using?

Crhome, Firefox

### What operating system are you using?

Ubuntu 

### How are you deploying your application?

vercel

### Describe the Bug

`Shallow: true` does not work, when

```js
// pages/some/path.js
  router.push('/some/path', as, { shallow: true })
```
```js
// /pages/_middleware.js
export function middleware(req) {
  return NextResponse.next()
}
```

`the middleware` is executed.

### Expected Behavior

The documentation says nothing about middleware. 

https://nextjs.org/docs/routing/shallow-routing

I excepted shallow-routing to be pure client-side. Calling the middleware slows down the UX.

If calling the middleware is the right behavior, I think the documentation should be updated, and also a new option might be needed, like ` {clientOnly: true}` to prevent the middleware to be called, when you want a pure client-side interaction.

### To Reproduce

https://codesandbox.io/s/happy-shannon-1dd78?file=/pages/index.js

### LINKED ISSUE #35006: Middleware is not called on client when url is for index.js and contains query parameter
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.6.0: Thu Jan 13 01:26:33 PST 2022; root:xnu-6153.141.51~3/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.6
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

Middleware is not called at all on the following case:

```sh
# file structure
pages/test/index.js
pages/test/_middleware.js
```

```js
<Link href="/test?something=1">...</Link>
```

It's correctly called If there are other middleware like on the top level.

### Expected Behavior

Middleware is called

### To Reproduce

Create files

```
pages/test/index.js
pages/test/_middleware.js
```

On a page, create a navigation like `<Link href="/test?something=1"><a>click me</a></Link>`

Ensure there is no other middleware and add query to the url to navigate.

### PR DESCRIPTION
**Pull request by nkzawa**
…h query parameter

Fixes https://github.com/vercel/next.js/issues/32655 and fixes https://github.com/vercel/next.js/issues/35006

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

### CODE REVIEW

File: packages/next/shared/lib/router/router.ts [hunk 1]
```diff
@@ -1864,8 +1866,9 @@ export default class Router implements BaseRouter {
     locale: string | undefined
     isPreview: boolean
   }): Promise<PreflightEffect> {
+    const asPathname = parseUrl(options.as).pathname
     const cleanedAs = delLocale(
-      hasBasePath(options.as) ? delBasePath(options.as) : options.as,
+      hasBasePath(asPathname) ? delBasePath(asPathname) : asPathname,
```
Comment (nkzawa) [inline packages/next/shared/lib/router/router.ts:1871]: this is the fix for https://github.com/vercel/next.js/issues/35006

**Review by javivelasco — DISMISSED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 49c06bdf17f75ad5f0f9b733fdf7a4e08b55434f

`yarn testheadless test/integration/router-prefetch/test/index.test.js` 
- Router prefetch > production mode > should resolve prefetch promise with invalid href

<details>
<summary>Expand output</summary>

  ● Router prefetch › production mode › should resolve prefetch promise with invalid href

    page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "#hidden-until-click"
    ============================================================

      304 |     return this.chain(() => {
      305 |       return page
    > 306 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      307 |         .then(async (el) => {
      308 |           // it seems selenium waits longer and tests rely on this behavior
      309 |           // so we wait for the load event fire before returning

      at lib/browsers/playwright.ts:306:10
      at didResolveAfterPrefetch (integration/router-prefetch/test/index.test.js:19:16)
      at Object.<anonymous> (integration/router-prefetch/test/index.test.js:61:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: packages/next/shared/lib/router/router.ts [hunk 2]
```diff
@@ -1864,8 +1866,9 @@ export default class Router implements BaseRouter {
     locale: string | undefined
     isPreview: boolean
   }): Promise<PreflightEffect> {
+    const asPathname = parseUrl(options.as).pathname
```
Comment (ijjk) [inline packages/next/shared/lib/router/router.ts:1869]: Are we only stripping the query and hash values here if so can we use the `pathNoQueryHash` method?

Comment (nkzawa) [reply packages/next/shared/lib/router/router.ts:1869]: done

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| buildDuration | 15.8s | 16.2s | ⚠️ +367ms |
| buildDurationCached | 5.8s | 6.3s | ⚠️ +473ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +179 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.107 | 3.206 | ⚠️ +0.1 |
| / avg req/sec | 804.61 | 779.75 | ⚠️ -24.86 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.448 | 1.407 | -0.04 |
| /error-in-render avg req/sec | 1726.42 | 1776.32 | +49.9 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ⚠️ +9 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.5 kB | 71.5 kB | ⚠️ +9 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.06 kB | 5.06 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.8 kB | 14.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -5269,13 +5269,14 @@
                             );
                             if (
                               !(
-                                options._h !== 1 ||
-                                (0, _isDynamic).isDynamicRoute(
-                                  (0,
-                                  _normalizeTrailingSlash).removePathTrailingSlash(
-                                    pathname
-                                  )
-                                )
+                                (!options.shallow || options._h === 1) &&
+                                (options._h !== 1 ||
+                                  (0, _isDynamic).isDynamicRoute(
+                                    (0,
+                                    _normalizeTrailingSlash).removePathTrailingSlash(
+                                      pathname
+                                    )
+                                  ))
                               )
                             ) {
                               _ctx.next = 96;
@@ -6338,7 +6339,8 @@
               var _this = this;
               return _asyncToGenerator(
                 _runtimeJs.default.mark(function _callee() {
-                  var cleanedAs,
+                  var asPathname,
+                    cleanedAs,
                     fns,
                     requiresPreflight,
                     preflight,
@@ -6354,15 +6356,16 @@
                     while (1)
                       switch ((_ctx.prev = _ctx.next)) {
                         case 0:
+                          asPathname = pathNoQueryHash(options.as);
                           cleanedAs = delLocale(
-                            hasBasePath(options.as)
-                              ? delBasePath(options.as)
-                              : options.as,
+                            hasBasePath(asPathname)
+                              ? delBasePath(asPathname)
+                              : asPathname,
                             options.locale
                           );
-                          _ctx.next = 3;
+                          _ctx.next = 4;
                           return _this.pageLoader.getMiddlewareList();
-                        case 3:
+                        case 4:
                           fns = _ctx.sent;
                           requiresPreflight = fns.some(function(param) {
                             var _param = _slicedToArray(param, 2),
@@ -6376,34 +6379,34 @@
                             )(cleanedAs);
                           });
                           if (requiresPreflight) {
-                            _ctx.next = 7;
+                            _ctx.next = 8;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "next"
                           });
-                        case 7:
-                          _ctx.next = 9;
+                        case 8:
+                          _ctx.next = 10;
                           return _this._getPreflightData({
                             preflightHref: options.as,
                             shouldCache: options.cache,
                             isPreview: options.isPreview
                           });
-                        case 9:
+                        case 10:
                           preflight = _ctx.sent;
                           if (!preflight.rewrite) {
-                            _ctx.next = 19;
+                            _ctx.next = 20;
                             break;
                           }
                           if (preflight.rewrite.startsWith("/")) {
-                            _ctx.next = 13;
+                            _ctx.next = 14;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "redirect",
                             destination: options.as
                           });
-                        case 13:
+                        case 14:
                           parsed = (0, _parseRelativeUrl).parseRelativeUrl(
                             (0, _normalizeLocalePath).normalizeLocalePath(
                               hasBasePath(preflight.rewrite)
@@ -6438,13 +6441,13 @@
                             matchedPage: matchedPage,
                             resolvedHref: resolvedHref
                           });
-                        case 19:
+                        case 20:
                           if (!preflight.redirect) {
-                            _ctx.next = 25;
+                            _ctx.next = 26;
                             break;
                           }
                           if (!preflight.redirect.startsWith("/")) {
-                            _ctx.next = 24;
+                            _ctx.next = 25;
                             break;
                           }
                           cleanRedirect = (0,
@@ -6468,24 +6471,24 @@
                             newUrl: newUrl,
                             newAs: newAs
                           });
-                        case 24:
+                        case 25:
                           return _ctx.abrupt("return", {
                             type: "redirect",
                             destination: preflight.redirect
                           });
-                        case 25:
+                        case 26:
                           if (!(preflight.refresh && !preflight.ssr)) {
-                            _ctx.next = 27;
+                            _ctx.next = 28;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "refresh"
                           });
-                        case 27:
+                        case 28:
                           return _ctx.abrupt("return", {
                             type: "next"
                           });
-                        case 28:
+                        case 29:
                         case "end":
                           return _ctx.stop();
                       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-33a5431a1debc260.js"
+      src="/_next/static/chunks/main-ec16309c57240cfb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-33a5431a1debc260.js"
+      src="/_next/static/chunks/main-ec16309c57240cfb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-33a5431a1debc260.js"
+      src="/_next/static/chunks/main-ec16309c57240cfb.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| buildDuration | 19.4s | 19.1s | -214ms |
| buildDurationCached | 6.2s | 6.4s | ⚠️ +141ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +179 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.212 | 3.245 | ⚠️ +0.03 |
| / avg req/sec | 778.37 | 770.53 | ⚠️ -7.84 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.419 | 1.441 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1762.26 | 1735.24 | ⚠️ -27.02 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ⚠️ +19 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +19 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.2 kB | 5.2 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.9 kB | 14.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -5269,13 +5269,14 @@
                             );
                             if (
                               !(
-                                options._h !== 1 ||
-                                (0, _isDynamic).isDynamicRoute(
-                                  (0,
-                                  _normalizeTrailingSlash).removePathTrailingSlash(
-                                    pathname
-                                  )
-                                )
+                                (!options.shallow || options._h === 1) &&
+                                (options._h !== 1 ||
+                                  (0, _isDynamic).isDynamicRoute(
+                                    (0,
+                                    _normalizeTrailingSlash).removePathTrailingSlash(
+                                      pathname
+                                    )
+                                  ))
                               )
                             ) {
                               _ctx.next = 96;
@@ -6338,7 +6339,8 @@
               var _this = this;
               return _asyncToGenerator(
                 _runtimeJs.default.mark(function _callee() {
-                  var cleanedAs,
+                  var asPathname,
+                    cleanedAs,
                     fns,
                     requiresPreflight,
                     preflight,
@@ -6354,15 +6356,16 @@
                     while (1)
                       switch ((_ctx.prev = _ctx.next)) {
                         case 0:
+                          asPathname = pathNoQueryHash(options.as);
                           cleanedAs = delLocale(
-                            hasBasePath(options.as)
-                              ? delBasePath(options.as)
-                              : options.as,
+                            hasBasePath(asPathname)
+                              ? delBasePath(asPathname)
+                              : asPathname,
                             options.locale
                           );
-                          _ctx.next = 3;
+                          _ctx.next = 4;
                           return _this.pageLoader.getMiddlewareList();
-                        case 3:
+                        case 4:
                           fns = _ctx.sent;
                           requiresPreflight = fns.some(function(param) {
                             var _param = _slicedToArray(param, 2),
@@ -6376,34 +6379,34 @@
                             )(cleanedAs);
                           });
                           if (requiresPreflight) {
-                            _ctx.next = 7;
+                            _ctx.next = 8;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "next"
                           });
-                        case 7:
-                          _ctx.next = 9;
+                        case 8:
+                          _ctx.next = 10;
                           return _this._getPreflightData({
                             preflightHref: options.as,
                             shouldCache: options.cache,
                             isPreview: options.isPreview
                           });
-                        case 9:
+                        case 10:
                           preflight = _ctx.sent;
                           if (!preflight.rewrite) {
-                            _ctx.next = 19;
+                            _ctx.next = 20;
                             break;
                           }
                           if (preflight.rewrite.startsWith("/")) {
-                            _ctx.next = 13;
+                            _ctx.next = 14;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "redirect",
                             destination: options.as
                           });
-                        case 13:
+                        case 14:
                           parsed = (0, _parseRelativeUrl).parseRelativeUrl(
                             (0, _normalizeLocalePath).normalizeLocalePath(
                               hasBasePath(preflight.rewrite)
@@ -6438,13 +6441,13 @@
                             matchedPage: matchedPage,
                             resolvedHref: resolvedHref
                           });
-                        case 19:
+                        case 20:
                           if (!preflight.redirect) {
-                            _ctx.next = 25;
+                            _ctx.next = 26;
                             break;
                           }
                           if (!preflight.redirect.startsWith("/")) {
-                            _ctx.next = 24;
+                            _ctx.next = 25;
                             break;
                           }
                           cleanRedirect = (0,
@@ -6468,24 +6471,24 @@
                             newUrl: newUrl,
                             newAs: newAs
                           });
-                        case 24:
+                        case 25:
                           return _ctx.abrupt("return", {
                             type: "redirect",
                             destination: preflight.redirect
                           });
-                        case 25:
+                        case 26:
                           if (!(preflight.refresh && !preflight.ssr)) {
-                            _ctx.next = 27;
+                            _ctx.next = 28;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "refresh"
                           });
-                        case 27:
+                        case 28:
                           return _ctx.abrupt("return", {
                             type: "next"
                           });
-                        case 28:
+                        case 29:
                         case "end":
                           return _ctx.stop();
                       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-33a5431a1debc260.js"
+      src="/_next/static/chunks/main-ec16309c57240cfb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-33a5431a1debc260.js"
+      src="/_next/static/chunks/main-ec16309c57240cfb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-33a5431a1debc260.js"
+      src="/_next/static/chunks/main-ec16309c57240cfb.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: cd299b420c310d7587e30dd0c9770ce741850d21

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| buildDuration | 15s | 15.2s | ⚠️ +207ms |
| buildDurationCached | 6.1s | 6.2s | ⚠️ +127ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +179 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.008 | 3.071 | ⚠️ +0.06 |
| / avg req/sec | 831.01 | 813.97 | ⚠️ -17.04 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.388 | 1.355 | -0.03 |
| /error-in-render avg req/sec | 1801.24 | 1845.07 | +43.83 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ⚠️ +8 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.5 kB | 71.5 kB | ⚠️ +8 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.09 kB | 5.09 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.8 kB | 14.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| index.html gzip | 531 B | 530 B | -1 B |
| link.html gzip | 545 B | 544 B | -1 B |
| withRouter.html gzip | 526 B | 524 B | -2 B |
| Overall change | 1.6 kB | 1.6 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -5302,13 +5302,14 @@
                             );
                             if (
                               !(
-                                options._h !== 1 ||
-                                (0, _isDynamic).isDynamicRoute(
-                                  (0,
-                                  _normalizeTrailingSlash).removePathTrailingSlash(
-                                    pathname
-                                  )
-                                )
+                                (!options.shallow || options._h === 1) &&
+                                (options._h !== 1 ||
+                                  (0, _isDynamic).isDynamicRoute(
+                                    (0,
+                                    _normalizeTrailingSlash).removePathTrailingSlash(
+                                      pathname
+                                    )
+                                  ))
                               )
                             ) {
                               _ctx.next = 96;
@@ -6371,7 +6372,8 @@
               var _this = this;
               return _asyncToGenerator(
                 _runtimeJs.default.mark(function _callee() {
-                  var cleanedAs,
+                  var asPathname,
+                    cleanedAs,
                     fns,
                     requiresPreflight,
                     preflight,
@@ -6387,15 +6389,16 @@
                     while (1)
                       switch ((_ctx.prev = _ctx.next)) {
                         case 0:
+                          asPathname = pathNoQueryHash(options.as);
                           cleanedAs = delLocale(
-                            hasBasePath(options.as)
-                              ? delBasePath(options.as)
-                              : options.as,
+                            hasBasePath(asPathname)
+                              ? delBasePath(asPathname)
+                              : asPathname,
                             options.locale
                           );
-                          _ctx.next = 3;
+                          _ctx.next = 4;
                           return _this.pageLoader.getMiddlewareList();
-                        case 3:
+                        case 4:
                           fns = _ctx.sent;
                           requiresPreflight = fns.some(function(param) {
                             var _param = _slicedToArray(param, 2),
@@ -6409,34 +6412,34 @@
                             )(cleanedAs);
                           });
                           if (requiresPreflight) {
-                            _ctx.next = 7;
+                            _ctx.next = 8;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "next"
                           });
-                        case 7:
-                          _ctx.next = 9;
+                        case 8:
+                          _ctx.next = 10;
                           return _this._getPreflightData({
                             preflightHref: options.as,
                             shouldCache: options.cache,
                             isPreview: options.isPreview
                           });
-                        case 9:
+                        case 10:
                           preflight = _ctx.sent;
                           if (!preflight.rewrite) {
-                            _ctx.next = 19;
+                            _ctx.next = 20;
                             break;
                           }
                           if (preflight.rewrite.startsWith("/")) {
-                            _ctx.next = 13;
+                            _ctx.next = 14;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "redirect",
                             destination: options.as
                           });
-                        case 13:
+                        case 14:
                           parsed = (0, _parseRelativeUrl).parseRelativeUrl(
                             (0, _normalizeLocalePath).normalizeLocalePath(
                               hasBasePath(preflight.rewrite)
@@ -6471,13 +6474,13 @@
                             matchedPage: matchedPage,
                             resolvedHref: resolvedHref
                           });
-                        case 19:
+                        case 20:
                           if (!preflight.redirect) {
-                            _ctx.next = 25;
+                            _ctx.next = 26;
                             break;
                           }
                           if (!preflight.redirect.startsWith("/")) {
-                            _ctx.next = 24;
+                            _ctx.next = 25;
                             break;
                           }
                           cleanRedirect = (0,
@@ -6501,24 +6504,24 @@
                             newUrl: newUrl,
                             newAs: newAs
                           });
-                        case 24:
+                        case 25:
                           return _ctx.abrupt("return", {
                             type: "redirect",
                             destination: preflight.redirect
                           });
-                        case 25:
+                        case 26:
                           if (!(preflight.refresh && !preflight.ssr)) {
-                            _ctx.next = 27;
+                            _ctx.next = 28;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "refresh"
                           });
-                        case 27:
+                        case 28:
                           return _ctx.abrupt("return", {
                             type: "next"
                           });
-                        case 28:
+                        case 29:
                         case "end":
                           return _ctx.stop();
                       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a9622e10c1f28000.js"
+      src="/_next/static/chunks/main-5ef02dfc5c89364b.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a9622e10c1f28000.js"
+      src="/_next/static/chunks/main-5ef02dfc5c89364b.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a9622e10c1f28000.js"
+      src="/_next/static/chunks/main-5ef02dfc5c89364b.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| buildDuration | 19.2s | 19.3s | ⚠️ +106ms |
| buildDurationCached | 6.2s | 6.1s | -95ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +179 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.186 | 3.206 | ⚠️ +0.02 |
| / avg req/sec | 784.64 | 779.88 | ⚠️ -4.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.385 | 1.384 | 0 |
| /error-in-render avg req/sec | 1805.29 | 1806.24 | +0.95 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ⚠️ +17 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +17 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.23 kB | 5.23 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15 kB | 15 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| index.html gzip | 530 B | 532 B | ⚠️ +2 B |
| link.html gzip | 544 B | 546 B | ⚠️ +2 B |
| withRouter.html gzip | 525 B | 527 B | ⚠️ +2 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +6 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -5302,13 +5302,14 @@
                             );
                             if (
                               !(
-                                options._h !== 1 ||
-                                (0, _isDynamic).isDynamicRoute(
-                                  (0,
-                                  _normalizeTrailingSlash).removePathTrailingSlash(
-                                    pathname
-                                  )
-                                )
+                                (!options.shallow || options._h === 1) &&
+                                (options._h !== 1 ||
+                                  (0, _isDynamic).isDynamicRoute(
+                                    (0,
+                                    _normalizeTrailingSlash).removePathTrailingSlash(
+                                      pathname
+                                    )
+                                  ))
                               )
                             ) {
                               _ctx.next = 96;
@@ -6371,7 +6372,8 @@
               var _this = this;
               return _asyncToGenerator(
                 _runtimeJs.default.mark(function _callee() {
-                  var cleanedAs,
+                  var asPathname,
+                    cleanedAs,
                     fns,
                     requiresPreflight,
                     preflight,
@@ -6387,15 +6389,16 @@
                     while (1)
                       switch ((_ctx.prev = _ctx.next)) {
                         case 0:
+                          asPathname = pathNoQueryHash(options.as);
                           cleanedAs = delLocale(
-                            hasBasePath(options.as)
-                              ? delBasePath(options.as)
-                              : options.as,
+                            hasBasePath(asPathname)
+                              ? delBasePath(asPathname)
+                              : asPathname,
                             options.locale
                           );
-                          _ctx.next = 3;
+                          _ctx.next = 4;
                           return _this.pageLoader.getMiddlewareList();
-                        case 3:
+                        case 4:
                           fns = _ctx.sent;
                           requiresPreflight = fns.some(function(param) {
                             var _param = _slicedToArray(param, 2),
@@ -6409,34 +6412,34 @@
                             )(cleanedAs);
                           });
                           if (requiresPreflight) {
-                            _ctx.next = 7;
+                            _ctx.next = 8;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "next"
                           });
-                        case 7:
-                          _ctx.next = 9;
+                        case 8:
+                          _ctx.next = 10;
                           return _this._getPreflightData({
                             preflightHref: options.as,
                             shouldCache: options.cache,
                             isPreview: options.isPreview
                           });
-                        case 9:
+                        case 10:
                           preflight = _ctx.sent;
                           if (!preflight.rewrite) {
-                            _ctx.next = 19;
+                            _ctx.next = 20;
                             break;
                           }
                           if (preflight.rewrite.startsWith("/")) {
-                            _ctx.next = 13;
+                            _ctx.next = 14;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "redirect",
                             destination: options.as
                           });
-                        case 13:
+                        case 14:
                           parsed = (0, _parseRelativeUrl).parseRelativeUrl(
                             (0, _normalizeLocalePath).normalizeLocalePath(
                               hasBasePath(preflight.rewrite)
@@ -6471,13 +6474,13 @@
                             matchedPage: matchedPage,
                             resolvedHref: resolvedHref
                           });
-                        case 19:
+                        case 20:
                           if (!preflight.redirect) {
-                            _ctx.next = 25;
+                            _ctx.next = 26;
                             break;
                           }
                           if (!preflight.redirect.startsWith("/")) {
-                            _ctx.next = 24;
+                            _ctx.next = 25;
                             break;
                           }
                           cleanRedirect = (0,
@@ -6501,24 +6504,24 @@
                             newUrl: newUrl,
                             newAs: newAs
                           });
-                        case 24:
+                        case 25:
                           return _ctx.abrupt("return", {
                             type: "redirect",
                             destination: preflight.redirect
                           });
-                        case 25:
+                        case 26:
                           if (!(preflight.refresh && !preflight.ssr)) {
-                            _ctx.next = 27;
+                            _ctx.next = 28;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "refresh"
                           });
-                        case 27:
+                        case 28:
                           return _ctx.abrupt("return", {
                             type: "next"
                           });
-                        case 28:
+                        case 29:
                         case "end":
                           return _ctx.stop();
                       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a9622e10c1f28000.js"
+      src="/_next/static/chunks/main-5ef02dfc5c89364b.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a9622e10c1f28000.js"
+      src="/_next/static/chunks/main-5ef02dfc5c89364b.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a9622e10c1f28000.js"
+      src="/_next/static/chunks/main-5ef02dfc5c89364b.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 0385bfc1608a4be2c5440f2118289ab59b29987b

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| buildDuration | 15.1s | 15.1s | -35ms |
| buildDurationCached | 6s | 6.1s | ⚠️ +38ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +179 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.914 | 2.94 | ⚠️ +0.03 |
| / avg req/sec | 857.82 | 850.3 | ⚠️ -7.52 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.16 | 1.175 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2155.67 | 2127.4 | ⚠️ -28.27 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ⚠️ +8 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.5 kB | 71.5 kB | ⚠️ +8 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.09 kB | 5.09 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.8 kB | 14.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| index.html gzip | 531 B | 530 B | -1 B |
| link.html gzip | 545 B | 544 B | -1 B |
| withRouter.html gzip | 526 B | 524 B | -2 B |
| Overall change | 1.6 kB | 1.6 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -5302,13 +5302,14 @@
                             );
                             if (
                               !(
-                                options._h !== 1 ||
-                                (0, _isDynamic).isDynamicRoute(
-                                  (0,
-                                  _normalizeTrailingSlash).removePathTrailingSlash(
-                                    pathname
-                                  )
-                                )
+                                (!options.shallow || options._h === 1) &&
+                                (options._h !== 1 ||
+                                  (0, _isDynamic).isDynamicRoute(
+                                    (0,
+                                    _normalizeTrailingSlash).removePathTrailingSlash(
+                                      pathname
+                                    )
+                                  ))
                               )
                             ) {
                               _ctx.next = 96;
@@ -6371,7 +6372,8 @@
               var _this = this;
               return _asyncToGenerator(
                 _runtimeJs.default.mark(function _callee() {
-                  var cleanedAs,
+                  var asPathname,
+                    cleanedAs,
                     fns,
                     requiresPreflight,
                     preflight,
@@ -6387,15 +6389,16 @@
                     while (1)
                       switch ((_ctx.prev = _ctx.next)) {
                         case 0:
+                          asPathname = pathNoQueryHash(options.as);
                           cleanedAs = delLocale(
-                            hasBasePath(options.as)
-                              ? delBasePath(options.as)
-                              : options.as,
+                            hasBasePath(asPathname)
+                              ? delBasePath(asPathname)
+                              : asPathname,
                             options.locale
                           );
-                          _ctx.next = 3;
+                          _ctx.next = 4;
                           return _this.pageLoader.getMiddlewareList();
-                        case 3:
+                        case 4:
                           fns = _ctx.sent;
                           requiresPreflight = fns.some(function(param) {
                             var _param = _slicedToArray(param, 2),
@@ -6409,34 +6412,34 @@
                             )(cleanedAs);
                           });
                           if (requiresPreflight) {
-                            _ctx.next = 7;
+                            _ctx.next = 8;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "next"
                           });
-                        case 7:
-                          _ctx.next = 9;
+                        case 8:
+                          _ctx.next = 10;
                           return _this._getPreflightData({
                             preflightHref: options.as,
                             shouldCache: options.cache,
                             isPreview: options.isPreview
                           });
-                        case 9:
+                        case 10:
                           preflight = _ctx.sent;
                           if (!preflight.rewrite) {
-                            _ctx.next = 19;
+                            _ctx.next = 20;
                             break;
                           }
                           if (preflight.rewrite.startsWith("/")) {
-                            _ctx.next = 13;
+                            _ctx.next = 14;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "redirect",
                             destination: options.as
                           });
-                        case 13:
+                        case 14:
                           parsed = (0, _parseRelativeUrl).parseRelativeUrl(
                             (0, _normalizeLocalePath).normalizeLocalePath(
                               hasBasePath(preflight.rewrite)
@@ -6471,13 +6474,13 @@
                             matchedPage: matchedPage,
                             resolvedHref: resolvedHref
                           });
-                        case 19:
+                        case 20:
                           if (!preflight.redirect) {
-                            _ctx.next = 25;
+                            _ctx.next = 26;
                             break;
                           }
                           if (!preflight.redirect.startsWith("/")) {
-                            _ctx.next = 24;
+                            _ctx.next = 25;
                             break;
                           }
                           cleanRedirect = (0,
@@ -6501,24 +6504,24 @@
                             newUrl: newUrl,
                             newAs: newAs
                           });
-                        case 24:
+                        case 25:
                           return _ctx.abrupt("return", {
                             type: "redirect",
                             destination: preflight.redirect
                           });
-                        case 25:
+                        case 26:
                           if (!(preflight.refresh && !preflight.ssr)) {
-                            _ctx.next = 27;
+                            _ctx.next = 28;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "refresh"
                           });
-                        case 27:
+                        case 28:
                           return _ctx.abrupt("return", {
                             type: "next"
                           });
-                        case 28:
+                        case 29:
                         case "end":
                           return _ctx.stop();
                       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a9622e10c1f28000.js"
+      src="/_next/static/chunks/main-5ef02dfc5c89364b.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a9622e10c1f28000.js"
+      src="/_next/static/chunks/main-5ef02dfc5c89364b.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a9622e10c1f28000.js"
+      src="/_next/static/chunks/main-5ef02dfc5c89364b.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| buildDuration | 18.4s | 18.5s | ⚠️ +86ms |
| buildDurationCached | 6s | 6s | ⚠️ +8ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +179 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.924 | 2.921 | 0 |
| / avg req/sec | 854.95 | 855.91 | +0.96 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.2 | 1.199 | 0 |
| /error-in-render avg req/sec | 2082.97 | 2085.43 | +2.46 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ⚠️ +17 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +17 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.23 kB | 5.23 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15 kB | 15 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-do-not-call-middleware-with-shallow-push | Change |
| - | - | - | - |
| index.html gzip | 530 B | 532 B | ⚠️ +2 B |
| link.html gzip | 544 B | 546 B | ⚠️ +2 B |
| withRouter.html gzip | 525 B | 527 B | ⚠️ +2 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +6 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -5302,13 +5302,14 @@
                             );
                             if (
                               !(
-                                options._h !== 1 ||
-                                (0, _isDynamic).isDynamicRoute(
-                                  (0,
-                                  _normalizeTrailingSlash).removePathTrailingSlash(
-                                    pathname
-                                  )
-                                )
+                                (!options.shallow || options._h === 1) &&
+                                (options._h !== 1 ||
+                                  (0, _isDynamic).isDynamicRoute(
+                                    (0,
+                                    _normalizeTrailingSlash).removePathTrailingSlash(
+                                      pathname
+                                    )
+                                  ))
                               )
                             ) {
                               _ctx.next = 96;
@@ -6371,7 +6372,8 @@
               var _this = this;
               return _asyncToGenerator(
                 _runtimeJs.default.mark(function _callee() {
-                  var cleanedAs,
+                  var asPathname,
+                    cleanedAs,
                     fns,
                     requiresPreflight,
                     preflight,
@@ -6387,15 +6389,16 @@
                     while (1)
                       switch ((_ctx.prev = _ctx.next)) {
                         case 0:
+                          asPathname = pathNoQueryHash(options.as);
                           cleanedAs = delLocale(
-                            hasBasePath(options.as)
-                              ? delBasePath(options.as)
-                              : options.as,
+                            hasBasePath(asPathname)
+                              ? delBasePath(asPathname)
+                              : asPathname,
                             options.locale
                           );
-                          _ctx.next = 3;
+                          _ctx.next = 4;
                           return _this.pageLoader.getMiddlewareList();
-                        case 3:
+                        case 4:
                           fns = _ctx.sent;
                           requiresPreflight = fns.some(function(param) {
                             var _param = _slicedToArray(param, 2),
@@ -6409,34 +6412,34 @@
                             )(cleanedAs);
                           });
                           if (requiresPreflight) {
-                            _ctx.next = 7;
+                            _ctx.next = 8;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "next"
                           });
-                        case 7:
-                          _ctx.next = 9;
+                        case 8:
+                          _ctx.next = 10;
                           return _this._getPreflightData({
                             preflightHref: options.as,
                             shouldCache: options.cache,
                             isPreview: options.isPreview
                           });
-                        case 9:
+                        case 10:
                           preflight = _ctx.sent;
                           if (!preflight.rewrite) {
-                            _ctx.next = 19;
+                            _ctx.next = 20;
                             break;
                           }
                           if (preflight.rewrite.startsWith("/")) {
-                            _ctx.next = 13;
+                            _ctx.next = 14;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "redirect",
                             destination: options.as
                           });
-                        case 13:
+                        case 14:
                           parsed = (0, _parseRelativeUrl).parseRelativeUrl(
                             (0, _normalizeLocalePath).normalizeLocalePath(
                               hasBasePath(preflight.rewrite)
@@ -6471,13 +6474,13 @@
                             matchedPage: matchedPage,
                             resolvedHref: resolvedHref
                           });
-                        case 19:
+                        case 20:
                           if (!preflight.redirect) {
-                            _ctx.next = 25;
+                            _ctx.next = 26;
                             break;
                           }
                           if (!preflight.redirect.startsWith("/")) {
-                            _ctx.next = 24;
+                            _ctx.next = 25;
                             break;
                           }
                           cleanRedirect = (0,
@@ -6501,24 +6504,24 @@
                             newUrl: newUrl,
                             newAs: newAs
                           });
-                        case 24:
+                        case 25:
                           return _ctx.abrupt("return", {
                             type: "redirect",
                             destination: preflight.redirect
                           });
-                        case 25:
+                        case 26:
                           if (!(preflight.refresh && !preflight.ssr)) {
-                            _ctx.next = 27;
+                            _ctx.next = 28;
                             break;
                           }
                           return _ctx.abrupt("return", {
                             type: "refresh"
                           });
-                        case 27:
+                        case 28:
                           return _ctx.abrupt("return", {
                             type: "next"
                           });
-                        case 28:
+                        case 29:
                         case "end":
                           return _ctx.stop();
                       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a9622e10c1f28000.js"
+      src="/_next/static/chunks/main-5ef02dfc5c89364b.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a9622e10c1f28000.js"
+      src="/_next/static/chunks/main-5ef02dfc5c89364b.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-a9622e10c1f28000.js"
+      src="/_next/static/chunks/main-5ef02dfc5c89364b.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 1f270b1005afdc671fe5e14648f2c06bd0902505
