### PR TITLE
Remove React Suspense from Client Runtime

### LINKED ISSUE #8886: "Unexpected fiber popped" / "An unexpected error has occurred"
# Bug report

## Describe the bug

At least two of the NextJS examples do not work when run "out of the box".

## To Reproduce

1. Follow the steps in either of these two READMEs:
    - [nextjs-with-typescript](https://github.com/mui-org/material-ui/blob/master/examples/nextjs-with-typescript/README.md)
    - [hello-world](https://github.com/zeit/next.js/blob/canary/examples/hello-world/README.md)
2. Run `npm install && npm run dev`.
    - React will report "Unexpected fiber popped" and "Unexpected pop" in the console.
    - In the Material UI example, buttons will not demonstrate the ripple effect when clicked. In my application, the effects are more severe, leading to loss of interactivity.
3. Deploy using `npx now`. Resulting application will report errors.
    - [nextjs-with-typescript](https://nextjs-with-typescript.ryaninvents.now.sh/) deployment
    - [hello-world](https://hello-world.ryaninvents.now.sh/) deployment

## Expected behavior

Given examples work when deployed and run.

## System information

- OS
    - Development: Ubuntu 18.04 LTS
    - Deployment: Zeit Now platform
- Browser: Reproducible in Chrome and Firefox
- Version of Next.js: 9.0.6 (current `latest`)

### PR DESCRIPTION
**Pull request by Timer**
This removes the `<Suspense>` component from Next.js' client-side runtime to deal with a breaking change released in a React minor version.

---

Closes https://github.com/zeit/next.js/issues/8886

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]

File: test/integration/data/pages/_app.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import React, { Suspense } from 'react'
```
Comment (Kristonitas) [inline test/integration/data/pages/_app.js]: What is this test covering, isn't `Suspense` failing?

P. S. I'm completely new to next.js, let alone its development.

Comment (timneutkens) [reply test/integration/data/pages/_app.js]: The data folder covers an experimental feature we've been developing, it's unrelated to anything else.

**Comment by timneutkens** [comment]
@devknoll FYI on these changes.
