### PR TITLE
Prevent timeout when loading routes in development

### LINKED ISSUE #25675: Error: Route did not complete loading: /some-page
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

12.16.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

custom-server-express

### Describe the Bug

While running the dev server, when I click through a couple of `pages/`, linked by the `<Link>` component, a full page load happens very often and randomly. This has been reported before: https://github.com/vercel/next.js/issues/21543, but in connection with debugging with DevTools.

It works as expected on a production build.

### Expected Behavior

Client-side navigation to work without full page loads, except for expected situations, which Fast Refresh warns about and are listed here: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works.

### To Reproduce

Unfortunately, this is very hard to reproduce (meaning create a reproduction). I still can't pinpoint the cause of this behaviour. However, you can add this event listener to your `_app.js` after mount, preserve log in DevTools console, and look for this error right before the full page load.

```js
Router.events.on('routeChangeError', (...yaaarghz) => {
  console.log(...yaaarghz)
})
```

(optional) You can also add this debugger statement to look through the callstack.

```js
window.addEventListener('beforeunload', () => {
  debugger
})
```

### PR DESCRIPTION
**Pull request by stovmascript**
@Timer The new route loader (https://github.com/vercel/next.js/pull/19006) will timeout loading routes after 3.8s [`MS_MAX_IDLE_DELAY`](https://github.com/vercel/next.js/blob/canary/packages/next/client/route-loader.ts#L6-L10), but this can easily happen when running dev on a large app.

Fixes https://github.com/vercel/next.js/issues/25675

## Bug

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.

## Documentation / Examples

- [ ] Make sure the linting passes

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| buildDuration | 13.1s | 13.1s | ⚠️ +36ms |
| buildDurationCached | 3.7s | 3.7s | -54ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +179 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.281 | 2.286 | 0 |
| / avg req/sec | 1095.87 | 1093.79 | ⚠️ -2.08 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.19 | 1.153 | -0.04 |
| /error-in-render avg req/sec | 2101.36 | 2168.21 | +66.85 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| index.html gzip | 573 B | 573 B | ✓ |
| link.html gzip | 580 B | 580 B | ✓ |
| withRouter.html gzip | 567 B | 567 B | ✓ |
| Overall change | 1.72 kB | 1.72 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -2375,13 +2375,16 @@
             cancelled = true;
             resolve(r);
           })["catch"](reject);
-          (0, _requestIdleCallback.requestIdleCallback)(function() {
-            return setTimeout(function() {
-              if (!cancelled) {
-                reject(err);
-              }
-            }, ms);
-          });
+
+          if (true) {
+            (0, _requestIdleCallback.requestIdleCallback)(function() {
+              return setTimeout(function() {
+                if (!cancelled) {
+                  reject(err);
+                }
+              }, ms);
+            });
+          }
         });
       } // TODO: stop exporting or cache the failure
       // It'd be best to stop exporting this. It's an implementation detail. We're
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -17,7 +17,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/main-38bab3b1dd44eb32312e.js"
+      href="/_next/static/chunks/main-bb007c84d603cd0361b6.js"
       as="script"
     />
     <link
@@ -57,7 +57,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/main-38bab3b1dd44eb32312e.js"
+      src="/_next/static/chunks/main-bb007c84d603cd0361b6.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -17,7 +17,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/main-38bab3b1dd44eb32312e.js"
+      href="/_next/static/chunks/main-bb007c84d603cd0361b6.js"
       as="script"
     />
     <link
@@ -62,7 +62,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/main-38bab3b1dd44eb32312e.js"
+      src="/_next/static/chunks/main-bb007c84d603cd0361b6.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -17,7 +17,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/main-38bab3b1dd44eb32312e.js"
+      href="/_next/static/chunks/main-bb007c84d603cd0361b6.js"
       as="script"
     />
     <link
@@ -57,7 +57,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/main-38bab3b1dd44eb32312e.js"
+      src="/_next/static/chunks/main-bb007c84d603cd0361b6.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| buildDuration | 14.9s | 14.7s | -220ms |
| buildDurationCached | 4.7s | 4.6s | -87ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +179 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 2.44 kB | 2.44 kB | ✓ |
| 500.html | 2.43 kB | 2.43 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.63 kB | 1.63 kB | ✓ |
| css.html | 1.81 kB | 1.81 kB | ✓ |
| hooks.html | 1.69 kB | 1.69 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ⚠️ +2 B |
| link.js | 17.4 kB | 17.4 kB | ✓ |
| routerDirect.js | 17.4 kB | 17.4 kB | ✓ |
| withRouter.js | 17.4 kB | 17.4 kB | ✓ |
| Overall change | 107 kB | 107 kB | ⚠️ +2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| buildDuration | 11.7s | 11.9s | ⚠️ +168ms |
| buildDurationCached | 5.2s | 5.1s | -129ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +179 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.408 | 2.383 | -0.02 |
| / avg req/sec | 1038.05 | 1048.96 | +10.91 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.215 | 1.244 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2058.35 | 2010.36 | ⚠️ -47.99 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 61.1 kB | 61.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.74 kB | 3.74 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.16 kB | 9.16 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| index.html gzip | 626 B | 626 B | ✓ |
| link.html gzip | 632 B | 633 B | ⚠️ +1 B |
| withRouter.html gzip | 620 B | 620 B | ✓ |
| Overall change | 1.88 kB | 1.88 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..c4df.HASH.js</strong></summary>

```diff
@@ -593,13 +593,16 @@
             cancelled = true;
             resolve(r);
           })["catch"](reject);
-          (0, _requestIdleCallback.requestIdleCallback)(function() {
-            return setTimeout(function() {
-              if (!cancelled) {
-                reject(err);
-              }
-            }, ms);
-          });
+
+          if (true) {
+            (0, _requestIdleCallback.requestIdleCallback)(function() {
+              return setTimeout(function() {
+                if (!cancelled) {
+                  reject(err);
+                }
+              }, ms);
+            });
+          }
         });
       } // TODO: stop exporting or cache the failure
       // It'd be best to stop exporting this. It's an implementation detail. We're
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -17,7 +17,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ce858a7353648dcbd41d.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.88559539f337d117373f.js"
       as="script"
     />
     <link
@@ -62,7 +62,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ce858a7353648dcbd41d.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.88559539f337d117373f.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -17,7 +17,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ce858a7353648dcbd41d.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.88559539f337d117373f.js"
       as="script"
     />
     <link
@@ -67,7 +67,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ce858a7353648dcbd41d.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.88559539f337d117373f.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -17,7 +17,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ce858a7353648dcbd41d.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.88559539f337d117373f.js"
       as="script"
     />
     <link
@@ -62,7 +62,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ce858a7353648dcbd41d.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.88559539f337d117373f.js"
       async=""
     ></script>
     <script
```
</details>
</details>
Commit: 49ad5f6ef54497855a54b84a4aabb61992f7f686

**Comment by tonytoth** [comment]
I agree with @stovmascript but I am not sure why (for me) it does take > 3.8 only in docker. On my local machine it works nice.

File: packages/next/client/route-loader.ts [hunk 1]
```diff
@@ -164,13 +164,15 @@ function resolvePromiseWithTimeout<T>(
...
     }).catch(reject)
 
-    requestIdleCallback(() =>
-      setTimeout(() => {
-        if (!cancelled) {
-          reject(err)
-        }
-      }, ms)
-    )
+    if (process.env.NODE_ENV !== 'development') {
```
Comment (ijjk) [inline packages/next/client/route-loader.ts:167]: Instead of not timing out in development when a page is being compiled we could check the [HMR events](https://github.com/vercel/next.js/blob/402f0360cece821b9e0017f6ecb499d129993600/packages/next/client/dev/error-overlay/hot-dev-client.js#L203-L208) and delay the timeout until after the compilation is complete. 

This should allow the full-page transition timeout to trigger correctly in development when data-fetching or other requests take a while so that you don't have to wait until a production build to notice the timeout is being hit on transition.

File: packages/next/client/route-loader.ts [hunk 2]
```diff
@@ -164,13 +197,15 @@ function resolvePromiseWithTimeout<T>(
...
     }).catch(reject)
 
-    requestIdleCallback(() =>
-      setTimeout(() => {
-        if (!cancelled) {
-          reject(err)
-        }
-      }, ms)
-    )
+    onBuildCallback(() => {
```
Comment (stovmascript) [inline packages/next/client/route-loader.ts:200]: @ijjk How about this? I'm wondering if this should be integrated into `requestIdleCallback`...

File: packages/next/client/route-loader.ts [hunk 3]
```diff
@@ -149,6 +150,38 @@ function appendScript(
...
 
+function onBuildCallback(cb) {
+  if (process.env.NODE_ENV !== 'development') {
+    cb()
+    return
+  }
+
+  let isComplete = false
+
+  addMessageListener((event) => {
```
Comment (stovmascript) [inline packages/next/client/route-loader.ts:161]: Is this the best way to subscribe to HMR events? I didn't find a way to unsubscribe, so atm the handler returns if "`isComplete`".

Comment (ijjk) [reply packages/next/client/route-loader.ts:161]: Yeah we use `addMessageListener` for the [build indicator here](https://github.com/vercel/next.js/blob/8066e423a7c51e8c670e8328beac91e80da2fc0a/packages/next/client/dev/dev-build-watcher.js#L43-L52) as well.

Let's not move this out into a separate function and keep it inside of `resolvePromiseWithTimeout` and make sure to wrap all dev related code in a `if (process.env.NODE_ENV === 'development') {}` check so that it can be dead-code eliminated to prevent impacting production bundle sizes. We can use `require` to load the `addMessageListener` inside of the `if` check as well.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.7s | ⚠️ +100ms |
| buildDurationCached | 2.9s | 2.9s | -79ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +1.86 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.044 | 2.097 | ⚠️ +0.05 |
| / avg req/sec | 1223.37 | 1192.17 | ⚠️ -31.2 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.15 | 1.137 | -0.01 |
| /error-in-render avg req/sec | 2174.66 | 2198.24 | +23.58 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| 359.HASH.js gzip | 3.09 kB | 3.09 kB | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.6 kB | 20.6 kB | ⚠️ +13 B |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ⚠️ +13 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.18 kB | 3.18 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.42 kB | 8.42 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| index.html gzip | 530 B | 531 B | ⚠️ +1 B |
| link.html gzip | 545 B | 544 B | -1 B |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -2469,13 +2469,23 @@
             cancelled = true;
             resolve(r);
           })["catch"](reject);
-          (0, _requestIdleCallback.requestIdleCallback)(function() {
-            return setTimeout(function() {
-              if (!cancelled) {
-                reject(err);
-              }
-            }, ms);
-          });
+          new Promise(function(res) {
+            if (false) {
+              var _require, addMessageListener;
+            } else {
+              res();
+            }
+          })
+            .then(function() {
+              (0, _requestIdleCallback.requestIdleCallback)(function() {
+                return setTimeout(function() {
+                  if (!cancelled) {
+                    reject(err);
+                  }
+                }, ms);
+              });
+            })
+            ["catch"](reject);
         });
       } // TODO: stop exporting or cache the failure
       // It'd be best to stop exporting this. It's an implementation detail. We're
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-892ee2944821256aa3b7.js"
+      src="/_next/static/chunks/main-2eb61f4ea715412ccaaa.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-892ee2944821256aa3b7.js"
+      src="/_next/static/chunks/main-2eb61f4ea715412ccaaa.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-892ee2944821256aa3b7.js"
+      src="/_next/static/chunks/main-2eb61f4ea715412ccaaa.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| buildDuration | 10.1s | 9.8s | -248ms |
| buildDurationCached | 4s | 4s | -21ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +1.86 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.052 | 2.076 | ⚠️ +0.02 |
| / avg req/sec | 1218.1 | 1204.25 | ⚠️ -13.85 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.155 | 1.156 | 0 |
| /error-in-render avg req/sec | 2163.96 | 2162.81 | ⚠️ -1.15 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| 14.HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.9 kB | 13.9 kB | ⚠️ +8 B |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.81 kB | 7.81 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 67.8 kB | 67.8 kB | ⚠️ +8 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 230 B | 230 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 297 B | 297 B | ✓ |
| withRouter-HASH.js gzip | 293 B | 293 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.98 kB | 8.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _buildManifest.js gzip | 418 B | 418 B | ✓ |
| Overall change | 418 B | 418 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| index.html gzip | 577 B | 574 B | -3 B |
| link.html gzip | 588 B | 586 B | -2 B |
| withRouter.html gzip | 569 B | 567 B | -2 B |
| Overall change | 1.73 kB | 1.73 kB | -7 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..c4df.HASH.js</strong></summary>

```diff
@@ -990,13 +990,23 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
             cancelled = true;
             resolve(r);
           })["catch"](reject);
-          (0, _requestIdleCallback.requestIdleCallback)(function() {
-            return setTimeout(function() {
-              if (!cancelled) {
-                reject(err);
-              }
-            }, ms);
-          });
+          new Promise(function(res) {
+            if (false) {
+              var _require, addMessageListener;
+            } else {
+              res();
+            }
+          })
+            .then(function() {
+              (0, _requestIdleCallback.requestIdleCallback)(function() {
+                return setTimeout(function() {
+                  if (!cancelled) {
+                    reject(err);
+                  }
+                }, ms);
+              });
+            })
+            ["catch"](reject);
         });
       } // TODO: stop exporting or cache the failure
       // It'd be best to stop exporting this. It's an implementation detail. We're
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.743faf44f9b7c645e1e6.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7262db8bd9d48883c143.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.743faf44f9b7c645e1e6.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7262db8bd9d48883c143.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.743faf44f9b7c645e1e6.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7262db8bd9d48883c143.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 5070f8df7aed16b3a2b3a35689121e15acb08cc2

**Review by stovmascript — COMMENTED** [review]
Do these changes look good then? Happy to improve something if need be :)

**Review by ijjk — CHANGES_REQUESTED** [review]
It looks like we can tweak this a bit more to prevent adding any changes to the production code, I attached a diff here as I'm not able to update this PR directly since contributions from maintainers is disabled for this PR. 

```diff
diff --git a/packages/next/client/route-loader.ts b/packages/next/client/route-loader.ts
index 14cb8bef3..7d09f0414 100644
--- a/packages/next/client/route-loader.ts
+++ b/packages/next/client/route-loader.ts
@@ -149,6 +149,38 @@ function appendScript(
   })
 }
 
+// we wait for pages to be built in dev before we start
+// the route transition timeout to prevent an un-necessary
+// hard navigation in development
+let devBuildPromise: Promise<void> | undefined
+let devBuildResolve: (() => void) | undefined
+
+if (process.env.NODE_ENV === 'development') {
+  const { addMessageListener } = require('./dev/error-overlay/eventsource')
+
+  addMessageListener((event: any) => {
+    // This is the heartbeat event
+    if (event.data === '\uD83D\uDC93') {
+      return
+    }
+
+    const obj =
+      typeof event === 'string' ? { action: event } : JSON.parse(event.data)
+
+    switch (obj.action) {
+      case 'built':
+      case 'sync':
+        if (devBuildResolve) {
+          devBuildResolve()
+          devBuildResolve = undefined
+        }
+        break
+      default:
+        break
+    }
+  })
+}
+
 // Resolve a promise that times out after given amount of milliseconds.
 function resolvePromiseWithTimeout<T>(
   p: Promise<T>,
@@ -164,13 +196,29 @@ function resolvePromiseWithTimeout<T>(
       resolve(r)
     }).catch(reject)
 
-    requestIdleCallback(() =>
-      setTimeout(() => {
-        if (!cancelled) {
-          reject(err)
-        }
-      }, ms)
-    )
+    // we wrap these checks separately for better dead-code elimination
+    // in production bundles
+    if (process.env.NODE_ENV === 'development') {
+      ;(devBuildPromise || Promise.resolve()).then(() => {
+        requestIdleCallback(() =>
+          setTimeout(() => {
+            if (!cancelled) {
+              reject(err)
+            }
+          }, ms)
+        )
+      })
+    }
+
+    if (process.env.NODE_ENV !== 'development') {
+      requestIdleCallback(() =>
+        setTimeout(() => {
+          if (!cancelled) {
+            reject(err)
+          }
+        }, ms)
+      )
+    }
   })
 }
 
@@ -307,6 +355,12 @@ function createRouteLoader(assetPrefix: string): RouteLoader {
     },
     loadRoute(route: string, prefetch?: boolean) {
       return withFuture<RouteLoaderEntry>(route, routes, () => {
+        if (process.env.NODE_ENV === 'development') {
+          devBuildPromise = new Promise<void>((resolve) => {
+            devBuildResolve = resolve
+          })
+        }
+
         return resolvePromiseWithTimeout(
           getFilesForRoute(assetPrefix, route)
             .then(({ scripts, css }) => {
```

**Comment by stovmascript** [comment]
@ijjk Done

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| buildDuration | 13.7s | 13.9s | ⚠️ +193ms |
| buildDurationCached | 3.5s | 3.4s | -132ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +3.75 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.403 | 2.428 | ⚠️ +0.02 |
| / avg req/sec | 1040.4 | 1029.76 | ⚠️ -10.64 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.369 | 1.387 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1826.58 | 1801.87 | ⚠️ -24.71 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| 359.HASH.js gzip | 3.09 kB | 3.09 kB | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.6 kB | 20.6 kB | ✓ |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.18 kB | 3.18 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.42 kB | 8.42 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -2459,6 +2459,14 @@
           script.src = src;
           document.body.appendChild(script);
         });
+      } // We wait for pages to be built in dev before we start the route transition
+      // timeout to prevent an un-necessary hard navigation in development.
+
+      var devBuildPromise;
+      var devBuildResolve;
+
+      if (false) {
+        var _require, addMessageListener;
       } // Resolve a promise that times out after given amount of milliseconds.
 
       function resolvePromiseWithTimeout(p, ms, err) {
@@ -2468,14 +2476,21 @@
             // Resolved, cancel the timeout
             cancelled = true;
             resolve(r);
-          })["catch"](reject);
-          (0, _requestIdleCallback.requestIdleCallback)(function() {
-            return setTimeout(function() {
-              if (!cancelled) {
-                reject(err);
-              }
-            }, ms);
-          });
+          })["catch"](reject); // We wrap these checks separately for better dead-code elimination in
+          // production bundles.
+
+          if (false) {
+          }
+
+          if (true) {
+            (0, _requestIdleCallback.requestIdleCallback)(function() {
+              return setTimeout(function() {
+                if (!cancelled) {
+                  reject(err);
+                }
+              }, ms);
+            });
+          }
         });
       } // TODO: stop exporting or cache the failure
       // It'd be best to stop exporting this. It's an implementation detail. We're
@@ -2612,6 +2627,9 @@
             var _this = this;
 
             return withFuture(route, routes, function() {
+              if (false) {
+              }
+
               return resolvePromiseWithTimeout(
                 getFilesForRoute(assetPrefix, route)
                   .then(function(_ref) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-4f15dc261f5ce5c05417.js"
+      src="/_next/static/chunks/main-ae652afd74f33a5448c1.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-4f15dc261f5ce5c05417.js"
+      src="/_next/static/chunks/main-ae652afd74f33a5448c1.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-4f15dc261f5ce5c05417.js"
+      src="/_next/static/chunks/main-ae652afd74f33a5448c1.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| buildDuration | 11.8s | 12.4s | ⚠️ +615ms |
| buildDurationCached | 4.9s | 4.6s | -304ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +3.75 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.425 | 2.436 | ⚠️ +0.01 |
| / avg req/sec | 1030.9 | 1026.35 | ⚠️ -4.55 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.349 | 1.388 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1852.71 | 1801.18 | ⚠️ -51.53 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| 14.HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.81 kB | 7.81 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 67.8 kB | 67.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 230 B | 230 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 297 B | 297 B | ✓ |
| withRouter-HASH.js gzip | 293 B | 293 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.98 kB | 8.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| _buildManifest.js gzip | 418 B | 418 B | ✓ |
| Overall change | 418 B | 418 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | monitora-media/next.js fix-route-loader-dev | Change |
| - | - | - | - |
| index.html gzip | 576 B | 575 B | -1 B |
| link.html gzip | 587 B | 586 B | -1 B |
| withRouter.html gzip | 570 B | 569 B | -1 B |
| Overall change | 1.73 kB | 1.73 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..c4df.HASH.js</strong></summary>

```diff
@@ -980,6 +980,14 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
           script.src = src;
           document.body.appendChild(script);
         });
+      } // We wait for pages to be built in dev before we start the route transition
+      // timeout to prevent an un-necessary hard navigation in development.
+
+      var devBuildPromise;
+      var devBuildResolve;
+
+      if (false) {
+        var _require, addMessageListener;
       } // Resolve a promise that times out after given amount of milliseconds.
 
       function resolvePromiseWithTimeout(p, ms, err) {
@@ -989,14 +997,21 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
             // Resolved, cancel the timeout
             cancelled = true;
             resolve(r);
-          })["catch"](reject);
-          (0, _requestIdleCallback.requestIdleCallback)(function() {
-            return setTimeout(function() {
-              if (!cancelled) {
-                reject(err);
-              }
-            }, ms);
-          });
+          })["catch"](reject); // We wrap these checks separately for better dead-code elimination in
+          // production bundles.
+
+          if (false) {
+          }
+
+          if (true) {
+            (0, _requestIdleCallback.requestIdleCallback)(function() {
+              return setTimeout(function() {
+                if (!cancelled) {
+                  reject(err);
+                }
+              }, ms);
+            });
+          }
         });
       } // TODO: stop exporting or cache the failure
       // It'd be best to stop exporting this. It's an implementation detail. We're
@@ -1133,6 +1148,9 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
             var _this = this;
 
             return withFuture(route, routes, function() {
+              if (false) {
+              }
+
               return resolvePromiseWithTimeout(
                 getFilesForRoute(assetPrefix, route)
                   .then(function(_ref) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.743faf44f9b7c645e1e6.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7ea47bba50cd89db0708.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.743faf44f9b7c645e1e6.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7ea47bba50cd89db0708.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.743faf44f9b7c645e1e6.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7ea47bba50cd89db0708.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 2af1953d6ec81f6f2a91899d07b67c721735cd37

**Review by ijjk — APPROVED** [review]
Thanks for the PR!

**Comment by tonytoth** [comment]
I am not sure that this solution covers all cases. I still have few pages that are reload.

**Comment by stovmascript** [comment]
Same here. There will have to be another source of the `routeChangeError` though.

**Comment by ijjk** [comment]
Can you provide more information on the case you're seeing reloading in development after upgrading past `v11.0.2-canary.12` of Next.js?

A screen recording of the console during the reload or a repo with steps to reproduce consistently can help.

**Comment by tonytoth** [comment]
This is the most I can get at the moment (I will try to create a reproduction repo but a bit later) https://streamable.com/1uq88y

**Comment by jarvelov** [comment]
Just wanted to chime in to say that we're experiencing the same thing with `v11.0.2-canary.19`. Even with the fix in this PR we're still seeing `routeChangeError` and the page gets reloaded.

I have tracked down why the `routeChangeError` still pops up and written a patch which fixes the page reloads. See PR #27395
