### PR TITLE
fix(turbopack): don't emit issues for deleted pages

### LINKED ISSUE #61384: Deleting page directory blocks dev server with "module-not-found"
### Link to the code that reproduces this issue

https://github.com/tmota900/reproduction-app

### To Reproduce

1 - Create an empty project
`npx create-next-app --example reproduction-template reproduction-app && cd reproduction-app`
2 - Add an .css file
`touch app/global.css`
3 - Import the global.css in the page.tsx
`echo -e "import './global.css';\n$(cat app/page.tsx)" > app/page.tsx`
4 - Create a nested page to to test the error
`mkdir app/page && cp -R app/*.* app/page`
5 - Run the server with turbo
`pnpm dev`
6 - Open the dev server page in browser:
[http://localhost:3000/page](http://localhost:3000/page)
7 - Delete the page in folder:
`rm -rf app/page`

Screenshot 2024-01-30 at 11 26 25

I was able to reproduce this consistently when there are css imports, without them it's harder to hit the issue. Once this error appears it seems to be cached and only restores restarting the server.

### Current vs. Expected behavior

The page does not exist and seems to be persisted in cache even tho the is not import anymore for the required module.
I would expect to receive an 404 when this case happens, as if the page does not include `.css` files happens.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: N/A
  pnpm: 7.33.6
Relevant Packages:
  next: 14.1.1-canary.21 // Latest available version is detected (14.1.1-canary.21).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

_No response_

<sub>[PACK-2366](https://linear.app/vercel/issue/PACK-2366/deleting-page-directory-blocks-dev-server-with-module-not-found)</sub>

### PR DESCRIPTION
**Pull request by ForsakenHarmony**
### What?

We now keep track of all client assets emitted for each route in `ClientAssetMapper` and remove all issues associated with them when a route get deleted.

Fixes #61384  
Closes PACK-2487

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vercel/next.js/62012?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* `canary`
  * **#61778** <a href="https://app.graphite.dev/github/pr/vercel/next.js/61778?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **#62012** <a href="https://app.graphite.dev/github/pr/vercel/next.js/62012?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ForsakenHarmony and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/filter-ws-issues | Change |
| - | - | - | - |
| buildDuration | 11.8s | 11.9s | ⚠️ +102ms |
| buildDurationCached | 6s | 5s | N/A |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +27.7 kB |
| nextStartRea..uration (ms) | 425ms | 430ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/filter-ws-issues | Change |
| - | - | - | - |
| 3f784ff6-HASH.js gzip | 53.5 kB | 53.5 kB | N/A |
| 423.HASH.js gzip | 185 B | 181 B | N/A |
| 68-HASH.js gzip | 30 kB | 30 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 238 B | 239 B | N/A |
| main-HASH.js gzip | 31.9 kB | 31.9 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 46.9 kB | 46.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/filter-ws-issues | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/filter-ws-issues | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 502 B | 501 B | N/A |
| css-HASH.js gzip | 320 B | 322 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 256 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.2 kB | 4.2 kB | N/A |
| index-HASH.js gzip | 257 B | 256 B | N/A |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 310 B | 311 B | N/A |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 306 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 106 B | 106 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/filter-ws-issues | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/filter-ws-issues | Change |
| - | - | - | - |
| index.html gzip | 527 B | 527 B | ✓ |
| link.html gzip | 541 B | 539 B | N/A |
| withRouter.html gzip | 523 B | 522 B | N/A |
| Overall change | 527 B | 527 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/filter-ws-issues | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94.4 kB | 94.4 kB | N/A |
| page.js gzip | 150 kB | 150 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/filter-ws-issues | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 621 B | 623 B | N/A |
| middleware-r..fest.js gzip | 151 B | 149 B | N/A |
| middleware.js gzip | 47.4 kB | 47.4 kB | ✓ |
| edge-runtime..pack.js gzip | 1.94 kB | 1.94 kB | ✓ |
| Overall change | 49.3 kB | 49.3 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/filter-ws-issues | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 166 kB | 166 kB | ✓ |
| app-page-exp..prod.js gzip | 95.5 kB | 95.5 kB | ✓ |
| app-page-tur..prod.js gzip | 97.2 kB | 97.2 kB | ✓ |
| app-page-tur..prod.js gzip | 91.7 kB | 91.7 kB | ✓ |
| app-page.run...dev.js gzip | 136 kB | 136 kB | ✓ |
| app-page.run..prod.js gzip | 90.2 kB | 90.2 kB | ✓ |
| app-route-ex...dev.js gzip | 22 kB | 22 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.7 kB | 9.7 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-turbo...prod.js gzip | 22.1 kB | 22.1 kB | ✓ |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | ✓ |
| pages.runtim..prod.js gzip | 22.1 kB | 22.1 kB | ✓ |
| server.runti..prod.js gzip | 49.9 kB | 49.9 kB | ✓ |
| Overall change | 925 kB | 925 kB | ✓ |

</details>

</details>
Commit: b0d698566c9e92bef2e2a29103424bd4a881806c

File: packages/next-swc/crates/next-api/src/middleware.rs [hunk 1]
```diff
@@ -198,7 +198,11 @@ impl Endpoint for MiddlewareEndpoint {
                 .await?
                 .clone_value();
 
-            Ok(WrittenEndpoint::Edge { server_paths }.cell())
+            Ok(WrittenEndpoint::Edge {
+                server_paths,
+                client_paths: vec![],
```
Comment (sokra) [inline packages/next-swc/crates/next-api/src/middleware.rs:203]: middleware might have client path. e.g. if you use `new URL` to include an image. The image would be on client side

**Comment by sokra** [comment]
A test case would be great

File: packages/next-swc/crates/next-core/src/next_app/mod.rs [hunk 2]
```diff
@@ -371,6 +423,21 @@ impl Display for AppPath {
     }
 }
 
+impl Ord for AppPath {
```
Comment (kdy1) [inline packages/next-swc/crates/next-core/src/next_app/mod.rs:426]: Why are there two implementations?

**Comment by sokra** [comment]
This needs a rebase/merge and there are also some test failures

File: packages/next/src/server/dev/hot-reloader-turbopack.ts [hunk 3]
```diff
@@ -579,18 +601,17 @@ export async function createHotReloaderTurbopack(
...
+
+        for (const entryIssues of currentEntryIssues.values()) {
           for (const issue of entryIssues.values()) {
             errors.push({
               message: formatIssue(issue),
             })
           }
         }
-        clientIssues.forEach(addIssues)
-        currentEntryIssues.forEach(addIssues)
```
Comment (sokra) [inline packages/next/src/server/dev/hot-reloader-turbopack.ts:615]: I think that was an incorrect rebase. It should also add issues from `clientIssues`

Comment (ForsakenHarmony) [reply packages/next/src/server/dev/hot-reloader-turbopack.ts:615]: `clientIssues` can't have any entries at this point?

File: packages/next/src/server/dev/turbopack-utils.ts [hunk 4]
```diff
@@ -499,33 +628,51 @@ export async function handleEntrypoints({
...
     }
   }
 
+  if (clients && clientStates) {
+    for (const client of clients) {
+      const state = clientStates.get(client)
+      if (!state) {
+        continue
+      }
+
```
Comment (sokra) [inline packages/next/src/server/dev/turbopack-utils.ts:661]:
```js
  for (const [key] of state.clientIssues) {
    if (!hasEntrypointForKey(currentEntrypoints, key, assetMapper)) {
      state.clientIssues.delete(key)
    }
  }
```

File: packages/next/src/server/dev/turbopack-utils.ts [hunk 5]
```diff
@@ -460,7 +586,10 @@ export async function handleEntrypoints({
   nextConfig: NextConfigComplete
   rewrites: SetupOpts['fsChecker']['rewrites']
 
+  assetMapper?: AssetMapper // dev
   changeSubscriptions?: ChangeSubscriptions // dev
+  clients?: Set<ws> // dev
+  clientStates?: ClientStateMap // dev
   serverFields?: ServerFields // dev
 
   hooks?: HandleEntrypointsHooks //dev
```
Comment (sokra) [inline packages/next/src/server/dev/turbopack-utils.ts:595]: maybe this should be in a single `dev` sub object. Could be a separate PR.

```suggestion
  dev?: {
    assetMapper: AssetMapper
    changeSubscriptions: ChangeSubscriptions
    clients: Set<ws>
    clientStates: ClientStateMap
    serverFields: ServerFields

    hooks: HandleEntrypointsHooks
  }
```

**Review by sokra — APPROVED** [review]

File: packages/next/src/server/dev/hot-reloader-turbopack.ts (hunk 3 above)
Comment (sokra) [reply packages/next/src/server/dev/hot-reloader-turbopack.ts:615]: entries?

`clientIssues` are issues from subscriptions of that connection/client. They should also be send via websocket.

Comment (ForsakenHarmony) [reply packages/next/src/server/dev/hot-reloader-turbopack.ts:615]: Yes, the map can't have any entries at this point, it's empty because the client just connected

File: packages/next/src/server/dev/turbopack-utils.ts (hunk 4 above)
Comment (ForsakenHarmony) [reply packages/next/src/server/dev/turbopack-utils.ts:661]: done

File: packages/next/src/server/dev/turbopack-utils.ts (hunk 5 above)
Comment (ForsakenHarmony) [reply packages/next/src/server/dev/turbopack-utils.ts]: done, missed the separate PR thing 🙃
