### PR TITLE
fix router prefetch cache key to work with route interception

### LINKED ISSUE #49878: Modal intercept/parallel routes clash when intercepting from different routes
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.3-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/nextjs-clashing-intercept-routes-7fb9i9?file=/app/page.tsx:1,1

### To Reproduce

Do the following within the root URL of the sandbox (aka `/` route). This is also accessible by the **Home** link.
1. Click **foo** link.
2. Click **Post 1** link (within the Foo Page). Note that it says `[Intercepted on Foo Page]`. 
3. Click outside the modal to go back and close it.
4. Click **home** link.
5. Click **bar** link.
6. Click **Post** link (within the Bar page). Note that it **incorrectly** says `[Intercepted on Foo Page]`.

### Describe the Bug

When intercepting the _same_ route from within _different_ routes, the intercepting clashes and the wrong pages/slots are rendered. 

The behavior seems to change depending on the order of the intercepting. 

### Expected Behavior

Being able to intercept the same route from within different routes and rendering the correct content.

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

<sub>[NEXT-1818](https://linear.app/vercel/issue/NEXT-1818/modal-interceptparallel-routes-clash-when-intercepting-from-different)</sub>

### LINKED ISSUE #52748: Intercepting routes not work depending on the first page displayed
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
$ next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 8.3.1
    Relevant Packages:
      next: 13.4.10-canary.8
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A

```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/AkifumiSato/http-vary-has-not-next-url
I discovered this while investigating another bug.

#### Operate normally

1. `http://localhost:3000/feed`(full load)
2. `http://localhost:3000/photo` 

#### Not operate normally

1. `http://localhost:3000/`(full load)
2. `http://localhost:3000/feed`
3. `http://localhost:3000/photo` 

### Describe the Bug

Depending on the first page displayed, the intercepting routes not work properly, and the transition will be as if the intercept directory did not exist.

### Expected Behavior

Wherever the first page is, intercepting routes should work.

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ztanner**
### What?
When handling route interception in two different segments but handled by the same interception route, the first interception will show the correct component but attempting the same interception on another segment will return elements from the first request, not the second.

### Why?
Prefetch cache entries are created from the browser URL. However, route interception makes use of `nextUrl` to mask the underlying components that are being fetched from the server to handle the request

Consider the following scenario:

```
app
   foo
     @modal
       (...)post
         [id]
   bar
     @modal
       (...post)
         [id]
   post
     [id]
     
```
If you trigger an interception on `/foo`, your URL is going to be masked to `/post/1` and keyed as such in the prefetch cache. However, the cache entry is actually associated with `app/foo/@modal/(...post)/[id]`. That means when you trigger the same interception on `/bar`, it will return the tree from `/foo`.

### How?
This PR will prefix the prefetch cache key with `state.nextUrl` when necessary.

Fixes #49878
Fixes #52748
Closes NEXT-1818

### CODE REVIEW

**Comment by ztanner** [comment]
Current dependencies on/for this PR:
* `canary`
  * **PR #59861** <a href="https://app.graphite.dev/github/pr/vercel/next.js/59861?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/59861?utm_source=stack-comment).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 6e0b9dfd0898e691732ad2e1c635df3e5c6172cc

`pnpm test packages/next/src/client/components/router-reducer/reducers/prefetch-reducer.test.tsx` 
- prefetchReducer > should apply navigation
- prefetchReducer > should apply navigation (concurrent)

<details>
<summary>Expand output</summary>

  ● prefetchReducer › should apply navigation

    expect(received).toMatchObject(expected)

    - Expected  - 2
    + Received  + 2

    @@ -40,15 +40,15 @@
          "onlyHashChange": false,
          "segmentPaths": Array [],
        },
        "nextUrl": "/linking",
        "prefetchCache": Map {
    -     "/linking/about" => Object {
    +     "/linking/linking/about" => Object {
            "data": Promise {},
            "kind": "auto",
            "lastUsedTime": null,
    -       "prefetchTime": Any<Number>,
    +       "prefetchTime": 1703196815272,
            "treeAtTimeOfPrefetch": Array [
              "",
              Object {
                "children": Array [
                  "linking",

      210 |     }
      211 |
    > 212 |     expect(newState).toMatchObject(expectedState)
          |                      ^
      213 |   })
      214 |
      215 |   it('should apply navigation (concurrent)', async () => {

      at Object.toMatchObject (../packages/next/src/client/components/router-reducer/reducers/prefetch-reducer.test.tsx:212:22)

  ● prefetchReducer › should apply navigation (concurrent)

    expect(received).toMatchObject(expected)

    - Expected  - 2
    + Received  + 2

    @@ -40,15 +40,15 @@
          "onlyHashChange": false,
          "segmentPaths": Array [],
        },
        "nextUrl": "/linking",
        "prefetchCache": Map {
    -     "/linking/about" => Object {
    +     "/linking/linking/about" => Object {
            "data": Promise {},
            "kind": "auto",
            "lastUsedTime": null,
    -       "prefetchTime": Any<Number>,
    +       "prefetchTime": 1703196815293,
            "treeAtTimeOfPrefetch": Array [
              "",
              Object {
                "children": Array [
                  "linking",

      366 |     }
      367 |
    > 368 |     expect(newState).toMatchObject(expectedState)
          |                      ^
      369 |   })
      370 | })
      371 |

      at Object.toMatchObject (../packages/next/src/client/components/router-reducer/reducers/prefetch-reducer.test.tsx:368:22)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 6e0b9dfd0898e691732ad2e1c635df3e5c6172cc

`pnpm test packages/next/src/client/components/router-reducer/reducers/navigate-reducer.test.tsx` 
- navigateReducer > should apply navigation
- navigateReducer > should apply navigation when called twice (concurrent)
- navigateReducer > should apply navigation for scroll
- navigateReducer > should apply navigation with prefetched data
- navigateReducer > should apply parallel routes navigation (concurrent)
- navigateReducer > should apply navigation for hash fragments within a different tree

<details>
<summary>Expand output</summary>

  ● navigateReducer › should apply navigation

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `navigateReducer should apply navigation 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -71,11 +71,11 @@
            ],
          ],
        },
        "nextUrl": "/linking/about",
        "prefetchCache": Map {
    -     "/linking/about" => {
    +     "/linking/linking/about" => {
            "data": Promise {},
            "kind": "temporary",
            "lastUsedTime": 1690329600000,
            "prefetchTime": 1690329600000,
            "treeAtTimeOfPrefetch": [

      179 |     const newState = await navigateReducer(state, action)
      180 |
    > 181 |     expect(newState).toMatchInlineSnapshot(`
          |                      ^
      182 |       {
      183 |         "buildId": "development",
      184 |         "cache": {

      at Object.toMatchInlineSnapshot (../packages/next/src/client/components/router-reducer/reducers/navigate-reducer.test.tsx:181:22)

  ● navigateReducer › should apply navigation when called twice (concurrent)

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `navigateReducer should apply navigation when called twice (concurrent) 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -71,11 +71,11 @@
            ],
          ],
        },
        "nextUrl": "/linking/about",
        "prefetchCache": Map {
    -     "/linking/about" => {
    +     "/linking/linking/about" => {
            "data": Promise {},
            "kind": "temporary",
            "lastUsedTime": 1690329600000,
            "prefetchTime": 1690329600000,
            "treeAtTimeOfPrefetch": [

      373 |     const newState = await navigateReducer(state, action)
      374 |
    > 375 |     expect(newState).toMatchInlineSnapshot(`
          |                      ^
      376 |       {
      377 |         "buildId": "development",
      378 |         "cache": {

      at Object.toMatchInlineSnapshot (../packages/next/src/client/components/router-reducer/reducers/navigate-reducer.test.tsx:375:22)

  ● navigateReducer › should apply navigation for scroll

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `navigateReducer should apply navigation for scroll 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -40,11 +40,11 @@
          "onlyHashChange": false,
          "segmentPaths": [],
        },
        "nextUrl": "/linking",
        "prefetchCache": Map {
    -     "/linking" => {
    +     "/linking/linking" => {
            "data": Promise {},
            "kind": "temporary",
            "lastUsedTime": 1690329600000,
            "prefetchTime": 1690329600000,
            "treeAtTimeOfPrefetch": [

      841 |     const newState = await navigateReducer(state, action)
      842 |
    > 843 |     expect(newState).toMatchInlineSnapshot(`
          |                      ^
      844 |       {
      845 |         "buildId": "development",
      846 |         "cache": {

      at Object.toMatchInlineSnapshot (../packages/next/src/client/components/router-reducer/reducers/navigate-reducer.test.tsx:843:22)

  ● navigateReducer › should apply navigation with prefetched data

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `navigateReducer should apply navigation with prefetched data 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -71,11 +71,11 @@
            ],
          ],
        },
        "nextUrl": "/linking/about",
        "prefetchCache": Map {
    -     "/linking/about" => {
    +     "/linking/linking/about" => {
            "data": Promise {},
            "kind": "auto",
            "lastUsedTime": 1690329600000,
            "prefetchTime": 1690329600000,
            "treeAtTimeOfPrefetch": [

      1036 |     await prom
      1037 |
    > 1038 |     expect(newState).toMatchInlineSnapshot(`
           |                      ^
      1039 |       {
      1040 |         "buildId": "development",
      1041 |         "cache": {

      at Object.toMatchInlineSnapshot (../packages/next/src/client/components/router-reducer/reducers/navigate-reducer.test.tsx:1038:22)

  ● navigateReducer › should apply parallel routes navigation (concurrent)

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `navigateReducer should apply parallel routes navigation (concurrent) 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -87,11 +87,11 @@
            ],
          ],
        },
        "nextUrl": "/parallel-tab-bar/demographics",
        "prefetchCache": Map {
    -     "/parallel-tab-bar/demographics" => {
    +     "/parallel-tab-bar/parallel-tab-bar/demographics" => {
            "data": Promise {},
            "kind": "temporary",
            "lastUsedTime": 1690329600000,
            "prefetchTime": 1690329600000,
            "treeAtTimeOfPrefetch": [

      1274 |     const newState = await navigateReducer(state, action)
      1275 |
    > 1276 |     expect(newState).toMatchInlineSnapshot(`
           |                      ^
      1277 |       {
      1278 |         "buildId": "development",
      1279 |         "cache": {

      at Object.toMatchInlineSnapshot (../packages/next/src/client/components/router-reducer/reducers/navigate-reducer.test.tsx:1276:22)

  ● navigateReducer › should apply navigation for hash fragments within a different tree

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `navigateReducer should apply navigation for hash fragments within a different tree 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -71,11 +71,11 @@
            ],
          ],
        },
        "nextUrl": "/linking/about",
        "prefetchCache": Map {
    -     "/linking/about" => {
    +     "/linking/linking/about" => {
            "data": Promise {},
            "kind": "temporary",
            "lastUsedTime": 1690329600000,
            "prefetchTime": 1690329600000,
            "treeAtTimeOfPrefetch": [

      1633 |     const newState = await navigateReducer(state, action)
      1634 |
    > 1635 |     expect(newState).toMatchInlineSnapshot(`
           |                      ^
      1636 |       {
      1637 |         "buildId": "development",
      1638 |         "cache": {

      at Object.toMatchInlineSnapshot (../packages/next/src/client/components/router-reducer/reducers/navigate-reducer.test.tsx:1635:22)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 12-21-fix_router_prefetch_cache_key_to_work_with_route_interception | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.9s | ⚠️ +142ms |
| buildDurationCached | 7.2s | 6.1s | N/A |
| nodeModulesSize | 202 MB | 202 MB | ⚠️ +7.55 kB |
| nextStartRea..uration (ms) | 421ms | 433ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-21-fix_router_prefetch_cache_key_to_work_with_route_interception | Change |
| - | - | - | - |
| 193.HASH.js gzip | 181 B | 182 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 433-HASH.js gzip | 28.2 kB | 28.3 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 239 B | 242 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-21-fix_router_prefetch_cache_key_to_work_with_route_interception | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-21-fix_router_prefetch_cache_key_to_work_with_route_interception | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 183 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 502 B | N/A |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 253 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.28 kB | 4.28 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | ✓ |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.4 kB | 3.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-21-fix_router_prefetch_cache_key_to_work_with_route_interception | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-21-fix_router_prefetch_cache_key_to_work_with_route_interception | Change |
| - | - | - | - |
| index.html gzip | 529 B | 526 B | N/A |
| link.html gzip | 541 B | 539 B | N/A |
| withRouter.html gzip | 525 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-21-fix_router_prefetch_cache_key_to_work_with_route_interception | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.7 kB | 93.7 kB | N/A |
| page.js gzip | 147 kB | 147 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-21-fix_router_prefetch_cache_key_to_work_with_route_interception | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 626 B | 623 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-21-fix_router_prefetch_cache_key_to_work_with_route_interception | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 94.2 kB | 94.2 kB | ✓ |
| app-page-tur..prod.js gzip | 94.9 kB | 94.9 kB | ✓ |
| app-page-tur..prod.js gzip | 89.4 kB | 89.4 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.7 kB | 88.7 kB | ✓ |
| app-route-ex...dev.js gzip | 24.1 kB | 24.1 kB | ✓ |
| app-route-ex..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| app-route.ru...dev.js gzip | 23.5 kB | 23.5 kB | ✓ |
| app-route.ru..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| Overall change | 932 kB | 932 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>433-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 6e0b9dfd0898e691732ad2e1c635df3e5c6172cc

**Comment by AkifumiSato** [comment]
The same is true for this issue.
#52748

File: packages/next/src/client/components/router-reducer/reducers/create-prefetch-cache-key.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+    url,
+    // Ensures the hash is not part of the cache key as it does not impact the server fetch
+    false
+  )
+
+  // Route interception depends on `nextUrl` values which aren't a 1:1 mapping to a URL
+  // The cache key that we store needs to use `nextUrl` to properly distinguish cache entries
+  if (nextUrl && !pathHasPrefix(pathnameFromUrl, nextUrl)) {
+    return addPathPrefix(nextUrl, pathnameFromUrl)
+  }
```
Comment (wyattjoh) [inline packages/next/src/client/components/router-reducer/reducers/create-prefetch-cache-key.ts:23]: As this cache key doesn't reflect the real URL, maybe joining it via a method that wouldn't conflict would be more reliable?

For example, if the `pathname` is `/bar`, and the `nextUrl` is `/foo`, but there's a route for `/foo/bar`, then this would cause them to clash right? Perhaps if you did something like `%` so the cache key could be `/foo%/bar` which by itself isn't a valid path, but would allow the interception route to match.

**Review by wyattjoh — APPROVED** [review]

**Review by huozhi — APPROVED** [review]

**Comment by kachkaev** [comment]
👋 @ztanner! Would this PR close https://github.com/vercel/next.js/issues/52748 too? Just curious if it has the same underlying cause or there’s something else going on there.
