### PR TITLE
Ensure path encoding is handled consistently for prerendered pages

### LINKED ISSUE #17582: fallback: 'unstable_blocking' is not encoding dynamic params properly
# Bug report

## Describe the bug

In the following page called `pages/post/[slug].tsx`:

```jsx
import { useRouter } from 'next/router'

export async function getStaticPaths() {
  return {
    paths: [{ params: { slug: '/my-post/' } }],
    fallback: 'unstable_blocking',
  }
}

export async function getStaticProps({ params }: any) {
  console.log('SLUG', params.slug)
  return { props: {} }
}

export default function Page() {
  const router = useRouter()
  return <h1>Hello World {router.query.slug}</h1>
}
```

The value of `slug` is `my-post` on development, and `%2Fmy-post%2F` on production.

Using `fallback: 'unstable_blocking'` the page will match `/post/my-post` on development but it won't on production, and using `fallback: false` the page will encode the param properly and it will never match `/post/my-post`.

## Expected behavior

The encoded param should be consistent in development and production, and while using different values for `fallback`

## System information

- Version of Next.js: 9.5.4-canary.23

### LINKED ISSUE #17642: getStaticPaths with fallback: false, return 404 page for non-ASCII/non-Latin url
# Bug report

## Describe the bug

In the following page called `pages/a/[slug]/index.js`

```javascript
export async function getStaticPaths() {
  return {
    paths: [{ params: { slug: 'Synonyms' } }, { params: { slug: 'อักษรย่อ' } }],
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const res = await fetch(getApplicationDetailBySlug(params.slug));
  const app = await res.json();

  return {
    props: { app },
  };
}
```
The value of `slug` is dynamic value that can be ASCII or Non-ASCII characters, So, When navigate to url of ASCII `(Synonyms)`, Page rendered correctly but for Non-ASCII `(อักษรย่อ)`, I got 404 page.

**List of urls:**

- อักษรย่อ
Url: `/a/อักษรย่อ`
encodeURIComponent: `/a/%E0%B8%AD%E0%B8%B1%E0%B8%81%E0%B8%A9%E0%B8%A3%E0%B8%A2%E0%B9%88%E0%B8%AD`

- Synonyms
Url: `/a/Synonyms`
encodeURIComponent: `/a/Synonyms`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. in getStaticPaths(), Use url param with non-ascii characters, I think for all non-latin language will face this issue, e.g. Thai, Chinese, Japanese.
2. fallback: false
3. browse the url in browser.
4. See 404 error page.

## Expected behavior

Should return correctly of url path and param for all encoding in `fallback: false` mode.

## Screenshots

Page of non-ascii url:
image

Page of ascii url:
image

Result from `build` command
image

Files from `build` command in `.next` folder:
image

## System information

- OS: Windows 10 Pro (WSL Bash shell)
- Version of Next.js: 9.5.3
- Version of Node.js: v12.18.4

## Additional context

OSX is got same behavior and 404 page. So, Path syntax is not root cause for this case for sure.

### PR DESCRIPTION
**Pull request by ijjk**
This ensures we handle encoding/decoding for SSG prerendered/fallback pages correctly. Since we only encode path delimiters when outputting to the disk we need to match this encoding when building the `ssgCacheKey` to look-up the prerendered pages. This also fixes non-ascii prerendered paths (e.g. 商業日語) not matching correctly. 

This does not resolve 👉  https://github.com/vercel/next.js/issues/10084 and further investigation will be needed before addressing non-ascii paths for non-SSG pages. 

The encoding output was tested against https://tst-encoding-l7amu5b9c.vercel.app/ to ensure the values will match correctly on Vercel. 

Closes: https://github.com/vercel/next.js/issues/17582
Closes: https://github.com/vercel/next.js/issues/17642
x-ref: https://github.com/vercel/next.js/pull/14717

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c916ac9edf70a3cd9994dfc1e8dda9895fb5955a

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 0
    Received:    0.10000000000000142

      105 |       expect(err404FirstLoad.endsWith('kB')).toBe(true)
      106 | 
    > 107 |       expect(parseFloat(sharedByAll) - 61.5).toBeLessThanOrEqual(0)
          |                                              ^
      108 |       expect(sharedByAll.endsWith('kB')).toBe(true)
      109 | 
      110 |       if (_appSize.endsWith('kB')) {

      at Object.<anonymous> (integration/build-output/test/index.test.js:107:46)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 12.2s | 13.4s | ⚠️ +1.2s |
| nodeModulesSize | 84.9 MB | 84.9 MB | ⚠️ +3.31 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.545 | 2.509 | -0.04 |
| / avg req/sec | 982.18 | 996.33 | +14.15 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.476 | 1.522 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1693.94 | 1642.29 | ⚠️ -51.65 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..d9fb.js gzip | 12.7 kB | 12.7 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-b0b971f..64a5.js gzip | 6.5 kB | 6.53 kB | ⚠️ +32 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.9 kB | 58.9 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 8.23 kB | 8.23 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-22cb0cf..dule.js gzip | 5.61 kB | 5.63 kB | ⚠️ +25 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.6 kB | 53.6 kB | ⚠️ +25 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d9a15a0..130a.js gzip | 1.57 kB | 1.57 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.98 kB | 7.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-973cce3..dule.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.6 kB | 5.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| index.html gzip | 971 B | 971 B | ✓ |
| link.html gzip | 978 B | 978 B | ✓ |
| withRouter.html gzip | 965 B | 964 B | -1 B |
| Overall change | 2.91 kB | 2.91 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-288e71c..7e8ff798f.js</strong></summary>

```diff
@@ -360,7 +360,8 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         runtimeConfig = data.runtimeConfig,
         dynamicIds = data.dynamicIds,
         isFallback = data.isFallback,
-        locales = data.locales;
+        locales = data.locales,
+        gsp = data.gsp;
       var locale = data.locale,
         defaultLocale = data.defaultLocale;
       var prefix = assetPrefix || ""; // With dynamic assetPrefix it's no longer possible to set assetPrefix at the build time
@@ -373,7 +374,18 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         serverRuntimeConfig: {},
         publicRuntimeConfig: runtimeConfig || {}
       });
-      var asPath = (0, _utils.getURL)(); // make sure not to attempt stripping basePath for 404s
+      var asPath = (0, _utils.getURL)();
+
+      if (gsp) {
+        // this does not decode query values only the path
+        // ensuring non-ascii values are the proper encoding
+        // and matches SSR/prerender
+        try {
+          asPath = decodeURI(asPath);
+        } catch (_) {
+          // non-fatal
+        }
+      } // make sure not to attempt stripping basePath for 404s
 
       if ((0, _router.hasBasePath)(asPath)) {
         asPath = (0, _router.delBasePath)(asPath);
```
</details>
<details>
<summary>Diff for <strong>main-b5494d9..2e.module.js</strong></summary>

```diff
@@ -275,7 +275,8 @@
         runtimeConfig,
         dynamicIds,
         isFallback,
-        locales
+        locales,
+        gsp
       } = data;
       var { locale, defaultLocale } = data;
       var prefix = assetPrefix || ""; // With dynamic assetPrefix it's no longer possible to set assetPrefix at the build time
@@ -288,7 +289,18 @@
         serverRuntimeConfig: {},
         publicRuntimeConfig: runtimeConfig || {}
       });
-      var asPath = (0, _utils.getURL)(); // make sure not to attempt stripping basePath for 404s
+      var asPath = (0, _utils.getURL)();
+
+      if (gsp) {
+        // this does not decode query values only the path
+        // ensuring non-ascii values are the proper encoding
+        // and matches SSR/prerender
+        try {
+          asPath = decodeURI(asPath);
+        } catch (_) {
+          // non-fatal
+        }
+      } // make sure not to attempt stripping basePath for 404s
 
       if ((0, _router.hasBasePath)(asPath)) {
         asPath = (0, _router.delBasePath)(asPath);
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css="true"></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-b5494d90160de3f12c2e.module.js"
+      href="/_next/static/chunks/main-b833247e0048e447ad01.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -82,13 +82,13 @@
       src="/_next/static/chunks/polyfills-f73ba3fc145972ef83e9.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-288e71cf56f7e8ff798f.js"
+      src="/_next/static/chunks/main-405eb69c8ffb11ece957.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/main-b5494d90160de3f12c2e.module.js"
+      src="/_next/static/chunks/main-b833247e0048e447ad01.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css="true"></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-b5494d90160de3f12c2e.module.js"
+      href="/_next/static/chunks/main-b833247e0048e447ad01.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -87,13 +87,13 @@
       src="/_next/static/chunks/polyfills-f73ba3fc145972ef83e9.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-288e71cf56f7e8ff798f.js"
+      src="/_next/static/chunks/main-405eb69c8ffb11ece957.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/main-b5494d90160de3f12c2e.module.js"
+      src="/_next/static/chunks/main-b833247e0048e447ad01.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css="true"></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-b5494d90160de3f12c2e.module.js"
+      href="/_next/static/chunks/main-b833247e0048e447ad01.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -82,13 +82,13 @@
       src="/_next/static/chunks/polyfills-f73ba3fc145972ef83e9.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-288e71cf56f7e8ff798f.js"
+      src="/_next/static/chunks/main-405eb69c8ffb11ece957.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/main-b5494d90160de3f12c2e.module.js"
+      src="/_next/static/chunks/main-b833247e0048e447ad01.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.7s | ⚠️ +523ms |
| nodeModulesSize | 84.9 MB | 84.9 MB | ⚠️ +3.31 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..d9fb.js gzip | 12.7 kB | 12.7 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-b0b971f..64a5.js gzip | 6.5 kB | N/A | N/A |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| main-eeb40c9..1817.js gzip | N/A | 6.53 kB | N/A |
| Overall change | 58.9 kB | 58.9 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 8.23 kB | 8.23 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-22cb0cf..dule.js gzip | 5.61 kB | N/A | N/A |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| main-e62d0f4..dule.js gzip | N/A | 5.63 kB | N/A |
| Overall change | 53.6 kB | 53.6 kB | ⚠️ +25 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d9a15a0..130a.js gzip | 1.57 kB | 1.57 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.98 kB | 7.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-973cce3..dule.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.6 kB | 5.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _error.js | 916 kB | 916 kB | ⚠️ +247 B |
| 404.html | 4.61 kB | 4.61 kB | ✓ |
| hooks.html | 3.86 kB | 3.86 kB | ✓ |
| index.js | 916 kB | 916 kB | ⚠️ +247 B |
| link.js | 974 kB | 975 kB | ⚠️ +247 B |
| routerDirect.js | 967 kB | 967 kB | ⚠️ +247 B |
| withRouter.js | 967 kB | 967 kB | ⚠️ +247 B |
| Overall change | 4.75 MB | 4.75 MB | ⚠️ +1.24 kB |

</details>

</details>
Commit: c916ac9edf70a3cd9994dfc1e8dda9895fb5955a

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.9s | ⚠️ +206ms |
| nodeModulesSize | 84.9 MB | 84.9 MB | ⚠️ +3.31 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.286 | 2.269 | -0.02 |
| / avg req/sec | 1093.76 | 1101.66 | +7.9 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.246 | 1.202 | -0.04 |
| /error-in-render avg req/sec | 2007.04 | 2079.9 | +72.86 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..d9fb.js gzip | 12.7 kB | 12.7 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-b0b971f..64a5.js gzip | 6.5 kB | 6.53 kB | ⚠️ +32 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.9 kB | 58.9 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 8.23 kB | 8.23 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-22cb0cf..dule.js gzip | 5.61 kB | 5.63 kB | ⚠️ +25 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.6 kB | 53.6 kB | ⚠️ +25 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d9a15a0..130a.js gzip | 1.57 kB | 1.57 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.98 kB | 7.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-973cce3..dule.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.6 kB | 5.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| index.html gzip | 971 B | 971 B | ✓ |
| link.html gzip | 978 B | 978 B | ✓ |
| withRouter.html gzip | 965 B | 964 B | -1 B |
| Overall change | 2.91 kB | 2.91 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-288e71c..7e8ff798f.js</strong></summary>

```diff
@@ -360,7 +360,8 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         runtimeConfig = data.runtimeConfig,
         dynamicIds = data.dynamicIds,
         isFallback = data.isFallback,
-        locales = data.locales;
+        locales = data.locales,
+        gsp = data.gsp;
       var locale = data.locale,
         defaultLocale = data.defaultLocale;
       var prefix = assetPrefix || ""; // With dynamic assetPrefix it's no longer possible to set assetPrefix at the build time
@@ -373,7 +374,18 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         serverRuntimeConfig: {},
         publicRuntimeConfig: runtimeConfig || {}
       });
-      var asPath = (0, _utils.getURL)(); // make sure not to attempt stripping basePath for 404s
+      var asPath = (0, _utils.getURL)();
+
+      if (gsp) {
+        // this does not decode query values only the path
+        // ensuring non-ascii values are the proper encoding
+        // and matches SSR/prerender
+        try {
+          asPath = decodeURI(asPath);
+        } catch (_) {
+          // non-fatal
+        }
+      } // make sure not to attempt stripping basePath for 404s
 
       if ((0, _router.hasBasePath)(asPath)) {
         asPath = (0, _router.delBasePath)(asPath);
```
</details>
<details>
<summary>Diff for <strong>main-b5494d9..2e.module.js</strong></summary>

```diff
@@ -275,7 +275,8 @@
         runtimeConfig,
         dynamicIds,
         isFallback,
-        locales
+        locales,
+        gsp
       } = data;
       var { locale, defaultLocale } = data;
       var prefix = assetPrefix || ""; // With dynamic assetPrefix it's no longer possible to set assetPrefix at the build time
@@ -288,7 +289,18 @@
         serverRuntimeConfig: {},
         publicRuntimeConfig: runtimeConfig || {}
       });
-      var asPath = (0, _utils.getURL)(); // make sure not to attempt stripping basePath for 404s
+      var asPath = (0, _utils.getURL)();
+
+      if (gsp) {
+        // this does not decode query values only the path
+        // ensuring non-ascii values are the proper encoding
+        // and matches SSR/prerender
+        try {
+          asPath = decodeURI(asPath);
+        } catch (_) {
+          // non-fatal
+        }
+      } // make sure not to attempt stripping basePath for 404s
 
       if ((0, _router.hasBasePath)(asPath)) {
         asPath = (0, _router.delBasePath)(asPath);
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css="true"></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-b5494d90160de3f12c2e.module.js"
+      href="/_next/static/chunks/main-b833247e0048e447ad01.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -82,13 +82,13 @@
       src="/_next/static/chunks/polyfills-f73ba3fc145972ef83e9.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-288e71cf56f7e8ff798f.js"
+      src="/_next/static/chunks/main-405eb69c8ffb11ece957.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/main-b5494d90160de3f12c2e.module.js"
+      src="/_next/static/chunks/main-b833247e0048e447ad01.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css="true"></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-b5494d90160de3f12c2e.module.js"
+      href="/_next/static/chunks/main-b833247e0048e447ad01.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -87,13 +87,13 @@
       src="/_next/static/chunks/polyfills-f73ba3fc145972ef83e9.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-288e71cf56f7e8ff798f.js"
+      src="/_next/static/chunks/main-405eb69c8ffb11ece957.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/main-b5494d90160de3f12c2e.module.js"
+      src="/_next/static/chunks/main-b833247e0048e447ad01.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css="true"></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-b5494d90160de3f12c2e.module.js"
+      href="/_next/static/chunks/main-b833247e0048e447ad01.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -82,13 +82,13 @@
       src="/_next/static/chunks/polyfills-f73ba3fc145972ef83e9.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-288e71cf56f7e8ff798f.js"
+      src="/_next/static/chunks/main-405eb69c8ffb11ece957.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/main-b5494d90160de3f12c2e.module.js"
+      src="/_next/static/chunks/main-b833247e0048e447ad01.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.6s | ⚠️ +397ms |
| nodeModulesSize | 84.9 MB | 84.9 MB | ⚠️ +3.31 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..d9fb.js gzip | 12.7 kB | 12.7 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-b0b971f..64a5.js gzip | 6.5 kB | N/A | N/A |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| main-eeb40c9..1817.js gzip | N/A | 6.53 kB | N/A |
| Overall change | 58.9 kB | 58.9 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 8.23 kB | 8.23 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-22cb0cf..dule.js gzip | 5.61 kB | N/A | N/A |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| main-e62d0f4..dule.js gzip | N/A | 5.63 kB | N/A |
| Overall change | 53.6 kB | 53.6 kB | ⚠️ +25 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d9a15a0..130a.js gzip | 1.57 kB | 1.57 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.98 kB | 7.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-973cce3..dule.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.6 kB | 5.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _error.js | 916 kB | 916 kB | ⚠️ +247 B |
| 404.html | 4.61 kB | 4.61 kB | ✓ |
| hooks.html | 3.86 kB | 3.86 kB | ✓ |
| index.js | 916 kB | 916 kB | ⚠️ +247 B |
| link.js | 974 kB | 975 kB | ⚠️ +247 B |
| routerDirect.js | 967 kB | 967 kB | ⚠️ +247 B |
| withRouter.js | 967 kB | 967 kB | ⚠️ +247 B |
| Overall change | 4.75 MB | 4.75 MB | ⚠️ +1.24 kB |

</details>

</details>
Commit: 2ff6f0ddb3c0273cfdad89bde2e5e9bf79668649

File: packages/next/client/index.tsx [hunk 1]
```diff
@@ -79,6 +80,17 @@ envConfig.setConfig({
...
+if (gsp) {
+  // this does not decode query values only the path
+  // ensuring non-ascii values are the proper encoding
+  // and matches SSR/prerender
+  try {
+    asPath = decodeURI(asPath)
+  } catch (_) {
+    // non-fatal
+  }
+}
```
Comment (Timer) [inline packages/next/client/index.tsx:92]: How does this handle routes that are intentionally double encoded by the user when visiting?

File: packages/next/next-server/server/render.tsx [hunk 2]
```diff
@@ -507,7 +507,19 @@ export async function renderToHTML(
...
+
+  if (!renderOpts.nextExport && isSSG) {
+    // this does not decode query values only the path
+    // ensuring non-ascii values are the proper encoding
+    // and ensures we match prerender asPath values
+    try {
+      asPath = decodeURI(asPath)
+    } catch (_) {
+      // non-fatal continue
+    }
```
Comment (Timer) [inline packages/next/next-server/server/render.tsx:520]: Swallowing this concerns me.

Comment (ijjk) [reply packages/next/next-server/server/render.tsx:520]: Was going back and fourth on whether this should be a 400 error if it fails to decode to match the dynamic-route decode error handling, do you think that would be more correct here?

File: packages/next/client/index.tsx (hunk 1 above)
Comment (ijjk) [reply packages/next/client/index.tsx:92]: What would be a case you intentionally double encode the path? This aims to have the `asPath` match the same level of decoding as we do when generating the paths at build time as otherwise we can have a hydration mis-match

Comment (Timer) [reply packages/next/client/index.tsx:92]: When would this ever error? We control the gsp asPath so it should always be properly encoded, right?

BTW a hydration mismatch *is* fatal, so we can't swallow this.

File: packages/next/next-server/server/render.tsx (hunk 2 above)
Comment (Timer) [reply packages/next/next-server/server/render.tsx:520]: Considering that something should always be in an encoded or decoded state already, this should probably 400.

**Review by Timer — CHANGES_REQUESTED** [review]
I'm very hesitant on the "optional" decoding behavior. We shouldn't be relying on any `try { } catch { }` to implement this support.

File: packages/next/client/index.tsx (hunk 1 above)
Comment (ijjk) [reply packages/next/client/index.tsx]: This is now updated to ensure we use the fully encoded variant while prerendering and still output the path delimiter escaped version to the filesystem. This should prevent hydration mismatch from a properly encoded URL being visited on the client but the prerendered version not being properly encoded.

File: packages/next/next-server/server/render.tsx (hunk 2 above)
Comment (ijjk) [reply packages/next/next-server/server/render.tsx]: This is now removed and when decoding fails while normalizing the `ssgCacheKey` in `next-server` we now throw a `DECODE_ERROR` which triggers a 400 response.

**Comment by ijjk** [comment]
Updated to address the optional decoding in favor of requiring the URL be properly encoded, this also removes the conditional decoding on the client and fixes the prerendered `asPath` to be encoded correctly.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.5s | ⚠️ +167ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +7.48 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.088 | 2.036 | -0.05 |
| / avg req/sec | 1197.26 | 1227.73 | +30.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.256 | 1.263 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1989.7 | 1979 | ⚠️ -10.7 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ⚠️ +31 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59.1 kB | ⚠️ +31 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| index.html gzip | 612 B | 613 B | ⚠️ +1 B |
| link.html gzip | 620 B | 619 B | -1 B |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..a0be5398c.js</strong></summary>

```diff
@@ -1325,7 +1325,18 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                 interpolatedRoute.replace(
                   replaced,
                   repeat
-                    ? value.map(_escapePathDelimiters["default"]).join("/")
+                    ? value
+                        .map(
+                          // TODO: should these values be encoded since they are decoded
+                          // in dynamicMatches and we are expecting encoded segments in
+                          // the URL
+                          function(segment) {
+                            return (0, _escapePathDelimiters["default"])(
+                              segment
+                            );
+                          }
+                        )
+                        .join("/")
                     : (0, _escapePathDelimiters["default"])(value)
                 ) || "/")
             );
@@ -3044,10 +3055,16 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       exports.__esModule = true;
       exports["default"] = escapePathDelimiters; // escape delimiters used by path-to-regexp
 
-      function escapePathDelimiters(segment) {
-        return segment.replace(/[/#?]/g, function(_char) {
-          return encodeURIComponent(_char);
-        });
+      function escapePathDelimiters(segment, escapeEncoded) {
+        return segment.replace(
+          new RegExp(
+            "([/#?]".concat(escapeEncoded ? "|%(2f|23|3f)" : "", ")"),
+            "gi"
+          ),
+          function(_char) {
+            return encodeURIComponent(_char);
+          }
+        );
       }
 
       /***/
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.b5bce6917aaa0be5398c.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.22e86bd654551b416200.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.b5bce6917aaa0be5398c.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.22e86bd654551b416200.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.b5bce6917aaa0be5398c.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.22e86bd654551b416200.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.b5bce6917aaa0be5398c.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.22e86bd654551b416200.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.b5bce6917aaa0be5398c.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.22e86bd654551b416200.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.b5bce6917aaa0be5398c.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.22e86bd654551b416200.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.3s | -81ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +7.48 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..60a5.js gzip | N/A | 12.8 kB | N/A |
| Overall change | 59 kB | 59.1 kB | ⚠️ +31 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +246 B |
| routerDirect.js | 1.05 MB | 1.05 MB | ⚠️ +246 B |
| withRouter.js | 1.05 MB | 1.05 MB | ⚠️ +246 B |
| Overall change | 5.16 MB | 5.16 MB | ⚠️ +738 B |

</details>

</details>
Commit: 3691d520fd28b752bd99ec33662915004537ed55

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.4s | -74ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +7.66 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.039 | 2.063 | ⚠️ +0.02 |
| / avg req/sec | 1225.82 | 1211.97 | ⚠️ -13.85 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.321 | 1.305 | -0.02 |
| /error-in-render avg req/sec | 1892.37 | 1915.39 | +23.02 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.7 kB | -40 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | -40 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| index.html gzip | 612 B | 614 B | ⚠️ +2 B |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 608 B | ⚠️ +1 B |
| Overall change | 1.84 kB | 1.84 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..a0be5398c.js</strong></summary>

```diff
@@ -1167,8 +1167,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
     /***/ elyg: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
-      var _slicedToArray = __webpack_require__("J4zp");
-
       var _regeneratorRuntime = __webpack_require__("o0o1");
 
       var _asyncToGenerator = __webpack_require__("yXPU");
@@ -1177,6 +1175,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
       var _createClass = __webpack_require__("W8MJ");
 
+      var _slicedToArray = __webpack_require__("J4zp");
+
       exports.__esModule = true;
       exports.addLocale = addLocale;
       exports.delLocale = delLocale;
@@ -1200,10 +1200,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
       var _utils = __webpack_require__("g/15");
 
-      var _escapePathDelimiters = _interopRequireDefault(
-        __webpack_require__("fcRV")
-      );
-
       var _isDynamic = __webpack_require__("/jkW");
 
       var _parseRelativeUrl = __webpack_require__("hS4m");
@@ -1325,8 +1321,18 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                 interpolatedRoute.replace(
                   replaced,
                   repeat
-                    ? value.map(_escapePathDelimiters["default"]).join("/")
-                    : (0, _escapePathDelimiters["default"])(value)
+                    ? value
+                        .map(
+                          // these values should be fully encoded instead of just
+                          // path delimiter escaped since they are being inserted
+                          // into the URL and we expect URL encoded segments
+                          // when parsing dynamic route params
+                          function(segment) {
+                            return encodeURIComponent(segment);
+                          }
+                        )
+                        .join("/")
+                    : encodeURIComponent(value)
                 ) || "/")
             );
           })
@@ -1417,9 +1423,16 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       function prepareUrlAs(router, url, as) {
         // If url and as provided as an object representation,
         // we'll format them into the string version here.
+        var _resolveHref = resolveHref(router.pathname, url, true),
+          _resolveHref2 = _slicedToArray(_resolveHref, 2),
+          resolvedHref = _resolveHref2[0],
+          resolvedAs = _resolveHref2[1];
+
         return {
-          url: addBasePath(resolveHref(router.pathname, url)),
-          as: as ? addBasePath(resolveHref(router.pathname, as)) : as
+          url: addBasePath(resolvedHref),
+          as: addBasePath(
+            as ? resolveHref(router.pathname, as) : resolvedAs || resolvedHref
+          )
         };
       }
 
@@ -1683,11 +1696,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
           },
           {
             key: "push",
-            value: function push(url) {
-              var as =
-                arguments.length > 1 && arguments[1] !== undefined
-                  ? arguments[1]
-                  : url;
+            value: function push(url, as) {
               var options =
                 arguments.length > 2 && arguments[2] !== undefined
                   ? arguments[2]
@@ -1707,11 +1716,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
           },
           {
             key: "replace",
-            value: function replace(url) {
-              var as =
-                arguments.length > 1 && arguments[1] !== undefined
-                  ? arguments[1]
-                  : url;
+            value: function replace(url, as) {
               var options =
                 arguments.length > 2 && arguments[2] !== undefined
                   ? arguments[2]
@@ -3038,21 +3043,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       /***/
     },
 
-    /***/ fcRV: /***/ function(module, exports, __webpack_require__) {
-      "use strict";
-
-      exports.__esModule = true;
-      exports["default"] = escapePathDelimiters; // escape delimiters used by path-to-regexp
-
-      function escapePathDelimiters(segment) {
-        return segment.replace(/[/#?]/g, function(_char) {
-          return encodeURIComponent(_char);
-        });
-      }
-
-      /***/
-    },
-
     /***/ "g/15": /***/ function(module, exports, __webpack_require__) {
       "use strict";
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.b5bce6917aaa0be5398c.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.750c7a14a7407aaee518.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.b5bce6917aaa0be5398c.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.750c7a14a7407aaee518.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.b5bce6917aaa0be5398c.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.750c7a14a7407aaee518.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.b5bce6917aaa0be5398c.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.750c7a14a7407aaee518.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.b5bce6917aaa0be5398c.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.750c7a14a7407aaee518.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.b5bce6917aaa0be5398c.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.750c7a14a7407aaee518.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.2s | -63ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +7.66 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..4114.js gzip | N/A | 12.7 kB | N/A |
| Overall change | 59 kB | 59 kB | -40 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | -127 B |
| routerDirect.js | 1.05 MB | 1.05 MB | -127 B |
| withRouter.js | 1.05 MB | 1.05 MB | -127 B |
| Overall change | 5.16 MB | 5.16 MB | -381 B |

</details>

</details>
Commit: 1ec95c8a93e82db808ac645348d155b61ad34b0f

**Review by Timer — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 10.9s | 10.7s | -197ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +7.66 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.052 | 2.136 | ⚠️ +0.08 |
| / avg req/sec | 1218.55 | 1170.41 | ⚠️ -48.14 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.351 | 1.353 | 0 |
| /error-in-render avg req/sec | 1849.99 | 1847.92 | ⚠️ -2.07 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..1e91.js gzip | 12.8 kB | 12.7 kB | -40 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | -40 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 620 B | -1 B |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..513eb1106.js</strong></summary>

```diff
@@ -1167,8 +1167,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
     /***/ elyg: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
-      var _slicedToArray = __webpack_require__("J4zp");
-
       var _regeneratorRuntime = __webpack_require__("o0o1");
 
       var _asyncToGenerator = __webpack_require__("yXPU");
@@ -1177,6 +1175,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
       var _createClass = __webpack_require__("W8MJ");
 
+      var _slicedToArray = __webpack_require__("J4zp");
+
       exports.__esModule = true;
       exports.addLocale = addLocale;
       exports.delLocale = delLocale;
@@ -1200,10 +1200,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
       var _utils = __webpack_require__("g/15");
 
-      var _escapePathDelimiters = _interopRequireDefault(
-        __webpack_require__("fcRV")
-      );
-
       var _isDynamic = __webpack_require__("/jkW");
 
       var _parseRelativeUrl = __webpack_require__("hS4m");
@@ -1325,8 +1321,18 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                 interpolatedRoute.replace(
                   replaced,
                   repeat
-                    ? value.map(_escapePathDelimiters["default"]).join("/")
-                    : (0, _escapePathDelimiters["default"])(value)
+                    ? value
+                        .map(
+                          // these values should be fully encoded instead of just
+                          // path delimiter escaped since they are being inserted
+                          // into the URL and we expect URL encoded segments
+                          // when parsing dynamic route params
+                          function(segment) {
+                            return encodeURIComponent(segment);
+                          }
+                        )
+                        .join("/")
+                    : encodeURIComponent(value)
                 ) || "/")
             );
           })
@@ -1417,9 +1423,16 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       function prepareUrlAs(router, url, as) {
         // If url and as provided as an object representation,
         // we'll format them into the string version here.
+        var _resolveHref = resolveHref(router.pathname, url, true),
+          _resolveHref2 = _slicedToArray(_resolveHref, 2),
+          resolvedHref = _resolveHref2[0],
+          resolvedAs = _resolveHref2[1];
+
         return {
-          url: addBasePath(resolveHref(router.pathname, url)),
-          as: as ? addBasePath(resolveHref(router.pathname, as)) : as
+          url: addBasePath(resolvedHref),
+          as: addBasePath(
+            as ? resolveHref(router.pathname, as) : resolvedAs || resolvedHref
+          )
         };
       }
 
@@ -1683,11 +1696,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
           },
           {
             key: "push",
-            value: function push(url) {
-              var as =
-                arguments.length > 1 && arguments[1] !== undefined
-                  ? arguments[1]
-                  : url;
+            value: function push(url, as) {
               var options =
                 arguments.length > 2 && arguments[2] !== undefined
                   ? arguments[2]
@@ -1707,11 +1716,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
           },
           {
             key: "replace",
-            value: function replace(url) {
-              var as =
-                arguments.length > 1 && arguments[1] !== undefined
-                  ? arguments[1]
-                  : url;
+            value: function replace(url, as) {
               var options =
                 arguments.length > 2 && arguments[2] !== undefined
                   ? arguments[2]
@@ -3047,21 +3052,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       /***/
     },
 
-    /***/ fcRV: /***/ function(module, exports, __webpack_require__) {
-      "use strict";
-
-      exports.__esModule = true;
-      exports["default"] = escapePathDelimiters; // escape delimiters used by path-to-regexp
-
-      function escapePathDelimiters(segment) {
-        return segment.replace(/[/#?]/g, function(_char) {
-          return encodeURIComponent(_char);
-        });
-      }
-
-      /***/
-    },
-
     /***/ "g/15": /***/ function(module, exports, __webpack_require__) {
       "use strict";
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.8s | ⚠️ +102ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +7.66 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..1e91.js gzip | 12.8 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..68d0.js gzip | N/A | 12.7 kB | N/A |
| Overall change | 59 kB | 59 kB | -40 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | -127 B |
| routerDirect.js | 1.05 MB | 1.05 MB | -127 B |
| withRouter.js | 1.05 MB | 1.05 MB | -127 B |
| Overall change | 5.16 MB | 5.16 MB | -381 B |

</details>

</details>
Commit: 9a5122222c18a36277b3c5e78a0a8ad5837a6ed9

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 9a5122222c18a36277b3c5e78a0a8ad5837a6ed9

**test/integration/i18n-support-base-path/test/index.test.js** 
- i18n Support basePath > serverless mode > should navigate through history with query correctly

<details>
<summary>Expand output</summary>

  ● i18n Support basePath › serverless mode › should navigate through history with query correctly

    thrown: "Exceeded timeout of 120000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      28 | 
      29 | export function runTests(ctx) {
    > 30 |   it('should navigate through history with query correctly', async () => {
         |   ^
      31 |     const browser = await webdriver(ctx.appPort, `${ctx.basePath || '/'}`)
      32 | 
      33 |     await browser.eval(`(function() {

      at runTests (integration/i18n-support/test/shared.js:30:3)
      at integration/i18n-support-base-path/test/index.test.js:191:5
      at integration/i18n-support-base-path/test/index.test.js:77:3
      at Object.<anonymous> (integration/i18n-support-base-path/test/index.test.js:24:1)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 9.9s | 10.2s | ⚠️ +293ms |
| nodeModulesSize | 82.6 MB | 82.7 MB | ⚠️ +7.66 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.035 | 1.984 | -0.05 |
| / avg req/sec | 1228.37 | 1260.02 | +31.65 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.237 | 1.248 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2021.04 | 2003.58 | ⚠️ -17.46 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..1e91.js gzip | 12.8 kB | 12.7 kB | -40 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | -40 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 620 B | -1 B |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..513eb1106.js</strong></summary>

```diff
@@ -1167,8 +1167,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
     /***/ elyg: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
-      var _slicedToArray = __webpack_require__("J4zp");
-
       var _regeneratorRuntime = __webpack_require__("o0o1");
 
       var _asyncToGenerator = __webpack_require__("yXPU");
@@ -1177,6 +1175,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
       var _createClass = __webpack_require__("W8MJ");
 
+      var _slicedToArray = __webpack_require__("J4zp");
+
       exports.__esModule = true;
       exports.addLocale = addLocale;
       exports.delLocale = delLocale;
@@ -1200,10 +1200,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
       var _utils = __webpack_require__("g/15");
 
-      var _escapePathDelimiters = _interopRequireDefault(
-        __webpack_require__("fcRV")
-      );
-
       var _isDynamic = __webpack_require__("/jkW");
 
       var _parseRelativeUrl = __webpack_require__("hS4m");
@@ -1325,8 +1321,18 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                 interpolatedRoute.replace(
                   replaced,
                   repeat
-                    ? value.map(_escapePathDelimiters["default"]).join("/")
-                    : (0, _escapePathDelimiters["default"])(value)
+                    ? value
+                        .map(
+                          // these values should be fully encoded instead of just
+                          // path delimiter escaped since they are being inserted
+                          // into the URL and we expect URL encoded segments
+                          // when parsing dynamic route params
+                          function(segment) {
+                            return encodeURIComponent(segment);
+                          }
+                        )
+                        .join("/")
+                    : encodeURIComponent(value)
                 ) || "/")
             );
           })
@@ -1417,9 +1423,16 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       function prepareUrlAs(router, url, as) {
         // If url and as provided as an object representation,
         // we'll format them into the string version here.
+        var _resolveHref = resolveHref(router.pathname, url, true),
+          _resolveHref2 = _slicedToArray(_resolveHref, 2),
+          resolvedHref = _resolveHref2[0],
+          resolvedAs = _resolveHref2[1];
+
         return {
-          url: addBasePath(resolveHref(router.pathname, url)),
-          as: as ? addBasePath(resolveHref(router.pathname, as)) : as
+          url: addBasePath(resolvedHref),
+          as: addBasePath(
+            as ? resolveHref(router.pathname, as) : resolvedAs || resolvedHref
+          )
         };
       }
 
@@ -1683,11 +1696,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
           },
           {
             key: "push",
-            value: function push(url) {
-              var as =
-                arguments.length > 1 && arguments[1] !== undefined
-                  ? arguments[1]
-                  : url;
+            value: function push(url, as) {
               var options =
                 arguments.length > 2 && arguments[2] !== undefined
                   ? arguments[2]
@@ -1707,11 +1716,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
           },
           {
             key: "replace",
-            value: function replace(url) {
-              var as =
-                arguments.length > 1 && arguments[1] !== undefined
-                  ? arguments[1]
-                  : url;
+            value: function replace(url, as) {
               var options =
                 arguments.length > 2 && arguments[2] !== undefined
                   ? arguments[2]
@@ -3047,21 +3052,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       /***/
     },
 
-    /***/ fcRV: /***/ function(module, exports, __webpack_require__) {
-      "use strict";
-
-      exports.__esModule = true;
-      exports["default"] = escapePathDelimiters; // escape delimiters used by path-to-regexp
-
-      function escapePathDelimiters(segment) {
-        return segment.replace(/[/#?]/g, function(_char) {
-          return encodeURIComponent(_char);
-        });
-      }
-
-      /***/
-    },
-
     /***/ "g/15": /***/ function(module, exports, __webpack_require__) {
       "use strict";
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.1s | -227ms |
| nodeModulesSize | 82.6 MB | 82.7 MB | ⚠️ +7.66 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..1e91.js gzip | 12.8 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..68d0.js gzip | N/A | 12.7 kB | N/A |
| Overall change | 59 kB | 59 kB | -40 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | -127 B |
| routerDirect.js | 1.05 MB | 1.05 MB | -127 B |
| withRouter.js | 1.05 MB | 1.05 MB | -127 B |
| Overall change | 5.16 MB | 5.16 MB | -381 B |

</details>

</details>
Commit: 63bcca12bc1b21ef8fcc2911b3bb9e9ccb59fcf7

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 8.4s | 8.5s | ⚠️ +19ms |
| nodeModulesSize | 82.6 MB | 82.7 MB | ⚠️ +7.66 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.649 | 1.69 | ⚠️ +0.04 |
| / avg req/sec | 1516.35 | 1479.09 | ⚠️ -37.26 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.058 | 1.099 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2362.82 | 2275.14 | ⚠️ -87.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..1e91.js gzip | 12.8 kB | 12.7 kB | -40 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | -40 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 620 B | -1 B |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..513eb1106.js</strong></summary>

```diff
@@ -1167,8 +1167,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
     /***/ elyg: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
-      var _slicedToArray = __webpack_require__("J4zp");
-
       var _regeneratorRuntime = __webpack_require__("o0o1");
 
       var _asyncToGenerator = __webpack_require__("yXPU");
@@ -1177,6 +1175,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
       var _createClass = __webpack_require__("W8MJ");
 
+      var _slicedToArray = __webpack_require__("J4zp");
+
       exports.__esModule = true;
       exports.addLocale = addLocale;
       exports.delLocale = delLocale;
@@ -1200,10 +1200,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
       var _utils = __webpack_require__("g/15");
 
-      var _escapePathDelimiters = _interopRequireDefault(
-        __webpack_require__("fcRV")
-      );
-
       var _isDynamic = __webpack_require__("/jkW");
 
       var _parseRelativeUrl = __webpack_require__("hS4m");
@@ -1325,8 +1321,18 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                 interpolatedRoute.replace(
                   replaced,
                   repeat
-                    ? value.map(_escapePathDelimiters["default"]).join("/")
-                    : (0, _escapePathDelimiters["default"])(value)
+                    ? value
+                        .map(
+                          // these values should be fully encoded instead of just
+                          // path delimiter escaped since they are being inserted
+                          // into the URL and we expect URL encoded segments
+                          // when parsing dynamic route params
+                          function(segment) {
+                            return encodeURIComponent(segment);
+                          }
+                        )
+                        .join("/")
+                    : encodeURIComponent(value)
                 ) || "/")
             );
           })
@@ -1417,9 +1423,16 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       function prepareUrlAs(router, url, as) {
         // If url and as provided as an object representation,
         // we'll format them into the string version here.
+        var _resolveHref = resolveHref(router.pathname, url, true),
+          _resolveHref2 = _slicedToArray(_resolveHref, 2),
+          resolvedHref = _resolveHref2[0],
+          resolvedAs = _resolveHref2[1];
+
         return {
-          url: addBasePath(resolveHref(router.pathname, url)),
-          as: as ? addBasePath(resolveHref(router.pathname, as)) : as
+          url: addBasePath(resolvedHref),
+          as: addBasePath(
+            as ? resolveHref(router.pathname, as) : resolvedAs || resolvedHref
+          )
         };
       }
 
@@ -1683,11 +1696,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
           },
           {
             key: "push",
-            value: function push(url) {
-              var as =
-                arguments.length > 1 && arguments[1] !== undefined
-                  ? arguments[1]
-                  : url;
+            value: function push(url, as) {
               var options =
                 arguments.length > 2 && arguments[2] !== undefined
                   ? arguments[2]
@@ -1707,11 +1716,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
           },
           {
             key: "replace",
-            value: function replace(url) {
-              var as =
-                arguments.length > 1 && arguments[1] !== undefined
-                  ? arguments[1]
-                  : url;
+            value: function replace(url, as) {
               var options =
                 arguments.length > 2 && arguments[2] !== undefined
                   ? arguments[2]
@@ -3047,21 +3052,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       /***/
     },
 
-    /***/ fcRV: /***/ function(module, exports, __webpack_require__) {
-      "use strict";
-
-      exports.__esModule = true;
-      exports["default"] = escapePathDelimiters; // escape delimiters used by path-to-regexp
-
-      function escapePathDelimiters(segment) {
-        return segment.replace(/[/#?]/g, function(_char) {
-          return encodeURIComponent(_char);
-        });
-      }
-
-      /***/
-    },
-
     /***/ "g/15": /***/ function(module, exports, __webpack_require__) {
       "use strict";
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0415ba721b6513eb1106.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.98cd454f84e413dc7645.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| buildDuration | 10s | 10s | -6ms |
| nodeModulesSize | 82.6 MB | 82.7 MB | ⚠️ +7.66 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| 677f882d2ed8..1e91.js gzip | 12.8 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..68d0.js gzip | N/A | 12.7 kB | N/A |
| Overall change | 59 kB | 59 kB | -40 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js ssg/path-encoding | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | -127 B |
| routerDirect.js | 1.05 MB | 1.05 MB | -127 B |
| withRouter.js | 1.05 MB | 1.05 MB | -127 B |
| Overall change | 5.16 MB | 5.16 MB | -381 B |

</details>

</details>
Commit: 7ef74886be586cb0fdd42ee2f941531390c47d1b
