### PR TITLE
parallel routes: support multi-slot layouts

### LINKED ISSUE #58506: Layouts of root level parallel routes do not render properly
### Link to the code that reproduces this issue

https://github.com/jfangrad/parallel-routes-issue/

### To Reproduce

1. Start the application in development
2. Notice the UI shows only 
Screenshot 2023-11-15 at 2 09 35 PM

3. Change the value of `isRoute1` in `src/app/layout.tsx` to `false` and save
4. Notice the UI now shows 
Screenshot 2023-11-15 at 2 10 29 PM

### Current vs. Expected behavior

Following the steps above, at **step 2** I expected to see output of
```
Test route 1 layout
Page 1 content
```

But instead only saw output of
```
Page 1 content
```

For some reason the layout for `route1` parallel route is being ignored but the layout for `route2` is not.

A bandaid solution that allowed both layouts to render properly was to put a `(default)` (or any group name) route group as the direct child of each parallel route and then place all files inside that route group. For some reason this change allows the layout for both parallel routes to work.

**Note:** Ran with both `14.0.2` and `^14.0.3-canary.9` but saw the same output.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.17.0
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.3-canary.9
  eslint-config-next: 14.0.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I tried recreating in a sandbox but the I could not reproduce in that enviroment.

However I was able to produce this bug in more than one next project (one on v13 and and clean slate v14)

### LINKED ISSUE #59463: Inconsistent behaviour between dev and build in parallel routing.
### Link to the code that reproduces this issue

https://github.com/jainmohit2001/nextjs-features

### To Reproduce

1. Clone the mentioned project
2. `npm install`
3. `npm run dev` (for development)
4. `npm run build` followed by `npm run start` (for production server) 

### Current vs. Expected behavior

The [src/app/routing/parallel-routing/@slot1/layout.tsx](https://github.com/jainmohit2001/nextjs-features/blob/58e9256befc54d8de3394a4395af479fe24f104e/src/app/routing/parallel-routing/%40slot1/layout.tsx) should be visible for the `@slot1`. In dev mode, this works as expected, but in build mode, the layout seems to be missing. 

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Wed Aug 25 23:20:18 UTC 2021
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Additional context

I tested the build with next canary release with the following info output:

```
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Wed Aug 25 23:20:18 UTC 2021
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.5-canary.5
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### PR DESCRIPTION
**Pull request by ztanner**
### What?
When using layouts in multiple parallel route slots, only 1 of the layouts would render.

### Why?
The `resolveParallelSegments` logic responsible for populating the loader tree was incorrectly bailing if it found another parallel route that matched a page component. 

### How?
I did my best to update this loader code with some more comments to make it a bit easier to reason about, and also made some slight refactors. But the gist of the fix is just ensuring that each parallel route (that isn't a direct match on the `children` slot) is resolved as an array, so that when the subtree is created, it doesn't skip over the slot.

Fixes #58506
Fixes #59463

Closes NEXT-2222

### CODE REVIEW

**Comment by ztanner** [comment]
* `canary`
  * **#61115** <a href="https://app.graphite.dev/github/pr/vercel/next.js/61115?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ztanner and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: packages/next/src/build/webpack/loaders/next-app-loader.ts [hunk 1]
```diff
@@ -293,27 +295,38 @@ async function createTreeCodeFromPath(
...
+      const normalizedParallelSegment = Array.isArray(parallelSegment)
+        ? parallelSegment[0]
+        : parallelSegment
 
-      subSegmentPath.push(
-        ...normalizedParallelSegments.filter(
-          (segment) =>
-            segment !== PAGE_SEGMENT && segment !== PARALLEL_CHILDREN_SEGMENT
-        )
-      )
```
Comment (ztanner) [inline packages/next/src/build/webpack/loaders/next-app-loader.ts]: This was always operating on a single element and I'm not sure why it was being normalized into an array, so I refactored this.

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 01-24-parallel_routes_support_multi-slot_layouts | Change |
| - | - | - | - |
| buildDuration | 11.7s | 11.6s | N/A |
| buildDurationCached | 5.9s | 5s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +7.23 kB |
| nextStartRea..uration (ms) | 425ms | 428ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 01-24-parallel_routes_support_multi-slot_layouts | Change |
| - | - | - | - |
| 3f784ff6-HASH.js gzip | 53.4 kB | 53.4 kB | ✓ |
| 423.HASH.js gzip | 185 B | 181 B | N/A |
| 68-HASH.js gzip | 29.8 kB | 29.8 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 238 B | 240 B | N/A |
| main-HASH.js gzip | 31.8 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 100 kB | 100 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 01-24-parallel_routes_support_multi-slot_layouts | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 01-24-parallel_routes_support_multi-slot_layouts | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 502 B | 502 B | ✓ |
| css-HASH.js gzip | 320 B | 322 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 256 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.18 kB | 4.18 kB | N/A |
| index-HASH.js gzip | 257 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | N/A |
| routerDirect..HASH.js gzip | 310 B | 311 B | N/A |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 306 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 608 B | 608 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 01-24-parallel_routes_support_multi-slot_layouts | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 484 B | ✓ |
| Overall change | 484 B | 484 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 01-24-parallel_routes_support_multi-slot_layouts | Change |
| - | - | - | - |
| index.html gzip | 527 B | 529 B | N/A |
| link.html gzip | 539 B | 541 B | N/A |
| withRouter.html gzip | 521 B | 524 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 01-24-parallel_routes_support_multi-slot_layouts | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94 kB | 94 kB | N/A |
| page.js gzip | 149 kB | 149 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 01-24-parallel_routes_support_multi-slot_layouts | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 622 B | N/A |
| middleware-r..fest.js gzip | 151 B | 149 B | N/A |
| middleware.js gzip | 37.6 kB | 37.6 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 01-24-parallel_routes_support_multi-slot_layouts | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | ✓ |
| app-page-exp..prod.js gzip | 95.7 kB | 95.7 kB | ✓ |
| app-page-tur..prod.js gzip | 96.3 kB | 96.3 kB | ✓ |
| app-page-tur..prod.js gzip | 90.9 kB | 90.9 kB | ✓ |
| app-page.run...dev.js gzip | 142 kB | 142 kB | ✓ |
| app-page.run..prod.js gzip | 90.2 kB | 90.2 kB | ✓ |
| app-route-ex...dev.js gzip | 22.2 kB | 22.2 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.5 kB | 14.5 kB | ✓ |
| app-route.ru...dev.js gzip | 21.6 kB | 21.6 kB | ✓ |
| app-route.ru..prod.js gzip | 14.5 kB | 14.5 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.42 kB | 9.42 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.69 kB | 9.69 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.42 kB | 9.42 kB | ✓ |
| pages-turbo...prod.js gzip | 22 kB | 22 kB | ✓ |
| pages.runtim...dev.js gzip | 22.6 kB | 22.6 kB | ✓ |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | ✓ |
| server.runti..prod.js gzip | 49.7 kB | 49.7 kB | ✓ |
| Overall change | 932 kB | 932 kB | ✓ |

</details>

</details>
Commit: e1aa924a30a68075765b88dc8ad323374919e1b6

File: test/e2e/app-dir/parallel-routes-layouts/parallel-routes-layouts.test.ts [hunk 2]
```diff
@@ -0,0 +1,84 @@
+import { createNextDescribe } from 'e2e-utils'
+import { retry } from 'next-test-utils'
+
+createNextDescribe(
+  'parallel-routes-layouts',
+  {
+    files: __dirname,
+  },
+  ({ next }) => {
```
Comment (ForsakenHarmony) [inline test/e2e/app-dir/parallel-routes-layouts/parallel-routes-layouts.test.ts:9]:
```suggestion
describe('parallel-routes-layouts', () => {
  const { next } = nextTestSetup({
    files: __dirname,
  })
```

File: test/e2e/app-dir/parallel-routes-layouts/parallel-routes-layouts.test.ts [hunk 3]
```diff
@@ -0,0 +1,84 @@
+import { createNextDescribe } from 'e2e-utils'
```
Comment (ForsakenHarmony) [inline test/e2e/app-dir/parallel-routes-layouts/parallel-routes-layouts.test.ts:1]: does this PR need changes from turbopack?

new tests should in theory run by default and it seems like everything is passing, so it might be fine?

Comment (ztanner) [reply test/e2e/app-dir/parallel-routes-layouts/parallel-routes-layouts.test.ts:1]: It looks like this is behaving properly in Turbopack 👍

File: test/e2e/app-dir/parallel-routes-layouts/parallel-routes-layouts.test.ts (hunk 2 above)
Comment (ztanner) [reply test/e2e/app-dir/parallel-routes-layouts/parallel-routes-layouts.test.ts:9]: sgtm, but we should probably discuss with the rest of the team as well since I think most tests are written this way currently. It seems marginally useful for things like `skipStart` and `skipDeployment` but honestly doesn't save that much time so 🤷

Comment (ForsakenHarmony) [reply test/e2e/app-dir/parallel-routes-layouts/parallel-routes-layouts.test.ts:9]: those are also included in `nextTestSetup` if you look at the implementation `createNextDescribe` is just a wrapper (I changed that a while back after talking to the team)

Comment (ztanner) [reply test/e2e/app-dir/parallel-routes-layouts/parallel-routes-layouts.test.ts:9]: Oh nice! Ok I can update this.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 99ac6677ec1d0849b08a8dabb0d36becb97ae6ee

`pnpm test-start test/e2e/app-dir/app-client-cache/client-cache.test.ts` (PPR)
- app dir client cache semantics > prefetch={true} > should prefetch again after 5 mins if the link is visible again

<details>
<summary>Expand output</summary>

  ● app dir client cache semantics › prefetch={true} › should prefetch again after 5 mins if the link is visible again

    TIMED OUT: success

    fail

    undefined

      636 |
      637 |   if (hardError) {
    > 638 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      639 |   }
      640 |   return false
      641 | }

      at check (lib/next-test-utils.ts:638:11)
      at Object.<anonymous> (e2e/app-dir/app-client-cache/client-cache.test.ts:176:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by acdlite — APPROVED** [review]
