### PR TITLE
fix: set swr delta

### LINKED ISSUE #51823: stale-while-revalidate header used without delta-seconds
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/blob/913b365d85011473c0ec595791afa6d924a988c4/packages/next/src/server/send-payload/revalidate-headers.ts#L25C53-L25C53

### To Reproduce

Render a page using `getStaticProps` in production. According to [the docs](https://nextjs.org/docs/pages/building-your-application/deploying/production-checklist#caching) and consistent with [the source code](https://github.com/vercel/next.js/blob/913b365d85011473c0ec595791afa6d924a988c4/packages/next/src/server/send-payload/revalidate-headers.ts#L25C53-L25C53) this will serve a `Cache-Control` header in the form of:

```
Cache-Control: s-maxage=REVALIDATE_SECONDS, stale-while-revalidate
```

### Describe the Bug

`stale-while-revalidate` does not specify a delta-seconds value describing for how long the shared cache (e.g. CDN) is allowed to serve stale responses while revalidating the cache.

### Expected Behavior

`stale-while-revalidate` must specify a delta-seconds for how long a shared cache is allowed to serve stale responses while revalidating. E.g. a valid header would be:

```
Cache-Control: s-maxage=60, stale-while-revalidate=60
```

I cross-read the informal resources at MDN and AWS CloudFront docs, none of them mentioned leaving out the delta:
* [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control)
* [CloudFront](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html#stale-content)
* [An article linked from next.js docs](https://web.dev/stale-while-revalidate/)

Thus I also checked [RFC 5861](https://httpwg.org/specs/rfc5861.html#n-the-stale-while-revalidate-cache-control-extension), which is specifying the header. The ABNF for the header is defined as

```
stale-while-revalidate = "stale-while-revalidate" "=" delta-seconds
```

As you can see none of the parts is marked as optional, also the text does not refer to a default behaviour to assume if the value is left out. So I am pretty sure that according to the specification it is not allowed to leave out the time.

This _might_ cause our CDN (CloudFront) to ignore the header entirely, resulting in poor page performance every 60 seconds (when periodically reloading the page).

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

AWS Amplify

### PR DESCRIPTION
**Pull request by adrianha**
Closes: https://github.com/vercel/next.js/pull/52251
Closes: https://github.com/vercel/next.js/issues/51823

### Adding a feature

Added `stale-while-revalidate` delta amount to indicate that the cache could reuse a stale response while it revalidates, [reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control). It's also already supported by [CloudFront](https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-cloudfront-stale-while-revalidate-stale-if-error-cache-control-directives/).

### CODE REVIEW

**Comment by adrianha** [comment]
hi @wyattjoh, could you please help to review this PR? let me know what you think 🙏

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 6e9fe22dbc20dccf4dd05d8d7b24b3ebb112acea

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by shuding — COMMENTED** [review]
LGTM but cc @ijjk for confirmation 🙏

File: packages/next/src/server/lib/revalidate.ts [hunk 1]
```diff
@@ -13,8 +13,8 @@ export function formatRevalidate(revalidate: Revalidate): string {
   if (revalidate === 0) {
     return 'private, no-cache, no-store, max-age=0, must-revalidate'
   } else if (typeof revalidate === 'number') {
-    return `s-maxage=${revalidate}, stale-while-revalidate`
+    return `s-maxage=${revalidate}, stale-while-revalidate=${revalidate}`
```
Comment (ijjk) [inline packages/next/src/server/lib/revalidate.ts:16]:
```suggestion
    return `s-maxage=${revalidate}, stale-while-revalidate=${CACHE_ONE_YEAR}`
```
I believe we want the stale-while-revalidate delta to always be at least a year as this is the amount of time a cache is allowed to keep the stale value and if a resource is failing to revalidate we don't want to evict the stale content just as fast as we want to revalidate the content.

**Comment by adrianha** [comment]
got it, updated the swr value for ISR to 1 year, cc @shuding @ijjk

**Review by ijjk — DISMISSED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 40bdcca0825458ae3272c9dba90662ab070ba63b

`pnpm test test/integration/not-found-revalidate/test/index.test.js`
- SSG notFound revalidate > production mode > should revalidate after notFound is returned for fallback: blocking
- SSG notFound revalidate > production mode > should revalidate after notFound is returned for fallback: true

<details>
<summary>Expand output</summary>

  ● SSG notFound revalidate › production mode › should revalidate after notFound is returned for fallback: blocking

    expect(received).toBe(expected) // Object.is equality

    Expected: "s-maxage=1, stale-while-revalidate"
    Received: "s-maxage=1, stale-while-revalidate=31536000"

      101 |
      102 |     const props = JSON.parse($('#props').text())
    > 103 |     expect(res.headers.get('cache-control')).toBe(
          |                                              ^
      104 |       's-maxage=1, stale-while-revalidate'
      105 |     )
      106 |     expect(res.status).toBe(200)

      at Object.toBe (integration/not-found-revalidate/test/index.test.js:103:46)

  ● SSG notFound revalidate › production mode › should revalidate after notFound is returned for fallback: true

    expect(received).toBe(expected) // Object.is equality

    Expected: "s-maxage=1, stale-while-revalidate"
    Received: "s-maxage=1, stale-while-revalidate=31536000"

      157 |
      158 |     const props = JSON.parse($('#props').text())
    > 159 |     expect(res.headers.get('cache-control')).toBe(
          |                                              ^
      160 |       's-maxage=1, stale-while-revalidate'
      161 |     )
      162 |     expect(res.status).toBe(200)

      at Object.toBe (integration/not-found-revalidate/test/index.test.js:159:46)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrianha/next.js set-swr-delta | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.5s | N/A |
| buildDurationCached | 6.1s | 5.1s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +972 B |
| nextStartRea..uration (ms) | 422ms | 433ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | adrianha/next.js set-swr-delta | Change |
| - | - | - | - |
| 3f784ff6-HASH.js gzip | 53.4 kB | 53.4 kB | ✓ |
| 423.HASH.js gzip | 185 B | 181 B | N/A |
| 68-HASH.js gzip | 29.8 kB | 29.8 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 238 B | 240 B | N/A |
| main-HASH.js gzip | 31.8 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 100 kB | 100 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrianha/next.js set-swr-delta | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrianha/next.js set-swr-delta | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 502 B | 502 B | ✓ |
| css-HASH.js gzip | 320 B | 322 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 256 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.18 kB | 4.18 kB | N/A |
| index-HASH.js gzip | 257 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | N/A |
| routerDirect..HASH.js gzip | 310 B | 311 B | N/A |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 306 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 608 B | 608 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrianha/next.js set-swr-delta | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 484 B | ✓ |
| Overall change | 484 B | 484 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrianha/next.js set-swr-delta | Change |
| - | - | - | - |
| index.html gzip | 529 B | 525 B | N/A |
| link.html gzip | 541 B | 539 B | N/A |
| withRouter.html gzip | 523 B | 518 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | adrianha/next.js set-swr-delta | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94 kB | 94.1 kB | N/A |
| page.js gzip | 150 kB | 150 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | adrianha/next.js set-swr-delta | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 622 B | N/A |
| middleware-r..fest.js gzip | 151 B | 149 B | N/A |
| middleware.js gzip | 37.6 kB | 37.6 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | adrianha/next.js set-swr-delta | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | ✓ |
| app-page-exp..prod.js gzip | 95.8 kB | 95.8 kB | ✓ |
| app-page-tur..prod.js gzip | 96.4 kB | 96.4 kB | ✓ |
| app-page-tur..prod.js gzip | 91 kB | 91 kB | ✓ |
| app-page.run...dev.js gzip | 142 kB | 142 kB | ✓ |
| app-page.run..prod.js gzip | 90.3 kB | 90.3 kB | ✓ |
| app-route-ex...dev.js gzip | 22.2 kB | 22.2 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.5 kB | 14.5 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.5 kB | 14.5 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.7 kB | 9.7 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-turbo...prod.js gzip | 22 kB | 22 kB | N/A |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | N/A |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | N/A |
| server.runti..prod.js gzip | 49.7 kB | 49.7 kB | N/A |
| Overall change | 817 kB | 817 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-turbo...time.prod.js</strong></summary>

```diff
@@ -20,7 +20,7 @@ Reason: ${n}`)}}function z(e,t,r){if(!D(r))throw new H(e,t,"",`Props must be ret
 Keys that need to be moved: ${t.join(", ")}.
 Read more: https://nextjs.org/docs/messages/${r}`};function e9(e,t,r){let{destination:n,permanent:o,statusCode:s,basePath:a}=e,i=[],l=void 0!==s,d=void 0!==o;d&&l?i.push("`permanent` and `statusCode` can not both be provided"):d&&"boolean"!=typeof o?i.push("`permanent` must be `true` or `false`"):l&&!eh.has(s)&&i.push(`\`statusCode\` must undefined or one of ${[...eh].join(", ")}`);let u=typeof n;"string"!==u&&i.push(`\`destination\` should be string but received ${u}`);let c=typeof a;if("undefined"!==c&&"boolean"!==c&&i.push(`\`basePath\` should be undefined or a false, received ${c}`),i.length>0)throw Error(`Invalid redirect object returned from ${r} for ${t.url}
 `+i.join(" and ")+"\nSee more info here: https://nextjs.org/docs/messages/invalid-redirect-gssp")}async function e6(n,s,a,i,l,d){var u,h;let f,m,g;(0,$.gk)({req:n},"cookies",(h=n.headers,function(){let{cookie:e}=h;if(!e)return{};let{parse:t}=r("./dist/compiled/cookie/index.js");return t(Array.isArray(e)?e.join("; "):e)}));let v={};if(v.assetQueryString=l.dev&&l.assetQueryString||"",l.dev&&!v.assetQueryString){let e=(n.headers["user-agent"]||"").toLowerCase();e.includes("safari")&&!e.includes("chrome")&&(v.assetQueryString=`?ts=${Date.now()}`)}l.deploymentId&&(v.assetQueryString+=`${v.assetQueryString?"&":"?"}dpl=${l.deploymentId}`),i=Object.assign({},i);let{err:y,dev:x=!1,ampPath:b="",pageConfig:w={},buildManifest:S,reactLoadableManifest:P,ErrorDebug:_,getStaticProps:R,getStaticPaths:j,getServerSideProps:C,isDataReq:T,params:N,previewProps:A,basePath:L,images:q,runtime:D,isExperimentalCompile:F}=l,{App:H}=d,J=v.assetQueryString,G=d.Document,V=l.Component,Q=!!i.__nextFallback,Z=i.__nextNotFoundSrcPage;!function(e){for(let t of eF)delete e[t]}(i);let Y=!!R,er=Y&&l.nextExport,ei=H.getInitialProps===H.origGetInitialProps,eu=!!(null==V?void 0:V.getInitialProps),ec=null==V?void 0:V.unstable_scriptLoader,eh=en(a),eg="/_error"===a&&V.getInitialProps===V.origGetInitialProps;l.nextExport&&eu&&!eg&&t(`Detected getInitialProps on page '${a}' while running export. It's recommended to use getStaticProps which has a more correct behavior for static exporting.
-Read more: https://nextjs.org/docs/messages/get-initial-props-export`);let ev=!eu&&ei&&!Y&&!C;if(ev&&!x&&F&&(s.setHeader("Cache-Control","number"==typeof!1?"s-maxage=false, stale-while-revalidate":`s-maxage=${k.BR}, stale-while-revalidate`),ev=!1),eu&&Y)throw Error(k.wh+` ${a}`);if(eu&&C)throw Error(k.Wo+` ${a}`);if(C&&Y)throw Error(k.oL+` ${a}`);if(C&&"export"===l.nextConfigOutput)throw Error('getServerSideProps cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export');if(j&&!eh)throw Error(`getStaticPaths is only allowed for dynamic SSG pages and was found on '${a}'.
+Read more: https://nextjs.org/docs/messages/get-initial-props-export`);let ev=!eu&&ei&&!Y&&!C;if(ev&&!x&&F&&(s.setHeader("Cache-Control","number"==typeof!1?`s-maxage=false, stale-while-revalidate=${k.BR}`:`s-maxage=${k.BR}, stale-while-revalidate=${k.BR}`),ev=!1),eu&&Y)throw Error(k.wh+` ${a}`);if(eu&&C)throw Error(k.Wo+` ${a}`);if(C&&Y)throw Error(k.oL+` ${a}`);if(C&&"export"===l.nextConfigOutput)throw Error('getServerSideProps cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export');if(j&&!eh)throw Error(`getStaticPaths is only allowed for dynamic SSG pages and was found on '${a}'.
 Read more: https://nextjs.org/docs/messages/non-dynamic-getstaticpaths-usage`);if(j&&!Y)throw Error(`getStaticPaths was added without a getStaticProps in ${a}. Without getStaticProps, getStaticPaths does nothing`);if(Y&&eh&&!j)throw Error(`getStaticPaths is required for dynamic SSG pages and is missing for '${a}'.
 Read more: https://nextjs.org/docs/messages/invalid-getstaticpaths-value`);let eP=l.resolvedAsPath||n.url;if(x){let{isValidElementType:e}=r("./dist/compiled/react-is/index.js");if(!e(V))throw Error(`The default export is not a React Component in page: "${a}"`);if(!e(H))throw Error('The default export is not a React Component in page: "/_app"');if(!e(G))throw Error('The default export is not a React Component in page: "/_document"');if((ev||Q)&&(i={...i.amp?{amp:i.amp}:{}},eP=`${a}${n.url.endsWith("/")&&"/"!==a&&!eh?"/":""}`,n.url=a),"/404"===a&&(eu||C))throw Error(`\`pages/404\` ${k.Ei}`);if(M.Er.includes(a)&&(eu||C))throw Error(`\`pages${a}\` ${k.Ei}`)}for(let e of["getStaticProps","getServerSideProps","getStaticPaths"])if(null==V?void 0:V[e])throw Error(`page ${a} ${e} ${k.lk}`);await X.preloadAll(),(Y||C)&&!Q&&A&&(g=!1!==(f=e(n,s,A)));let e_=!!(C||eu||!ei&&!Y||F),eR=new e3(a,i,eP,{isFallback:Q},e_,L,l.locale,l.locales,l.defaultLocale,l.domainLocales,g,ep(n,"isLocaleDomain")),ej={back(){eR.back()},forward(){eR.forward()},refresh(){eR.reload()},push(e,t){let{scroll:r}=void 0===t?{}:t;eR.push(e,void 0,{scroll:r})},replace(e,t){let{scroll:r}=void 0===t?{}:t;eR.replace(e,void 0,{scroll:r})},prefetch(e){eR.prefetch(e)}},eC={},eT=(0,I.createStyleRegistry)(),eE={ampFirst:!0===w.amp,hasQuery:!!i.amp,hybrid:"hybrid"===w.amp},e$=function(e){let{ampFirst:t=!1,hybrid:r=!1,hasQuery:n=!1}=void 0===e?{}:e;return t||r&&n}(eE),eN=function(e){void 0===e&&(e=!1);let t=[(0,E.jsx)("meta",{charSet:"utf-8"})];return e||t.push((0,E.jsx)("meta",{name:"viewport",content:"width=device-width"})),t}(e$),eA=[],eL={};ec&&(eL.beforeInteractive=[].concat(ec()).filter(e=>"beforeInteractive"===e.props.strategy).map(e=>e.props));let eO=({children:e})=>{var t;return(0,E.jsx)(eQ.Provider,{value:ej,children:(0,E.jsx)(eH.Provider,{value:eR.isReady&&eR.query?(t=eR.asPath,new URL(t,"http://n").searchParams):new URLSearchParams,children:(0,E.jsx)(eV,{router:eR,isAutoExport:ev,children:(0,E.jsx)(eB.Provider,{value:function(e){if(!e.isReady||!e.query)return null;let t={},r=function(e){let{parameterizedRoute:t,groups:r}=function(e){let t=eS(e).slice(1).split("/"),r={},n=1;return{parameterizedRoute:t.map(e=>{let t=et.find(t=>e.startsWith(t)),o=e.match(/\[((?:\[.*\])|.+)\]/);if(t&&o){let{key:e,optional:s,repeat:a}=eG(o[1]);return r[e]={pos:n++,repeat:a,optional:s},"/"+eJ(t)+"([^/]+?)"}if(!o)return"/"+eJ(e);{let{key:e,repeat:t,optional:s}=eG(o[1]);return r[e]={pos:n++,repeat:t,optional:s},t?s?"(?:/(.+?))?":"/(.+?)":"/([^/]+?)"}}).join(""),groups:r}}(e);return{re:RegExp("^"+t+"(?:/)?$"),groups:r}}(e.pathname),n=Object.keys(r.groups);for(let r of n)t[r]=e.query[r];return t}(eR),children:(0,E.jsx)(K.Provider,{value:eR,children:(0,E.jsx)(B.Provider,{value:eE,children:(0,E.jsx)(U.Provider,{value:{updateHead:e=>{eN=e},updateScripts:e=>{eC=e},scripts:eL,mountedInstances:new Set},children:(0,E.jsx)(W.Provider,{value:e=>eA.push(e),children:(0,E.jsx)(I.StyleRegistry,{registry:eT,children:(0,E.jsx)(eM.Provider,{value:q,children:e})})})})})})})})})})},eI=()=>null,eq=({children:e})=>(0,E.jsxs)(E.Fragment,{children:[(0,E.jsx)(eI,{}),(0,E.jsx)(eO,{children:(0,E.jsxs)(E.Fragment,{children:[x?(0,E.jsxs)(E.Fragment,{children:[e,(0,E.jsx)(eI,{})]}):e,(0,E.jsx)(eI,{})]})})]}),ez={err:y,req:ev?void 0:n,res:ev?void 0:s,pathname:a,query:i,asPath:eP,locale:l.locale,locales:l.locales,defaultLocale:l.defaultLocale,AppTree:e=>(0,E.jsx)(eq,{children:e2(H,V,{...e,router:eR})}),defaultGetInitialProps:async(e,t={})=>{let{html:r,head:n}=await e.renderPage({enhanceApp:e=>t=>(0,E.jsx)(e,{...t})}),o=eT.styles({nonce:t.nonce});return eT.flush(),{html:r,head:n,styles:o}}},eU=!Y&&(l.nextExport||x&&(ev||Q)),eW=()=>{let e=eT.styles();return eT.flush(),(0,E.jsx)(E.Fragment,{children:e})};if(m=await ea(H,{AppTree:ez.AppTree,Component:V,router:eR,ctx:ez}),(Y||C)&&g&&(m.__N_PREVIEW=!0),Y&&(m[M.NO]=!0),Y&&!Q){let e,t;try{e=await (0,em.getTracer)().trace(c.getStaticProps,{spanName:`getStaticProps ${a}`,attributes:{"next.route":a}},()=>R({...eh?{params:i}:void 0,...g?{draftMode:!0,preview:!0,previewData:f}:void 0,locales:l.locales,locale:l.locale,defaultLocale:l.defaultLocale}))}catch(e){throw e&&"ENOENT"===e.code&&delete e.code,e}if(null==e)throw Error(k.q6);let r=Object.keys(e).filter(e=>"revalidate"!==e&&"props"!==e&&"redirect"!==e&&"notFound"!==e);if(r.includes("unstable_revalidate"))throw Error(k.Eo);if(r.length)throw Error(e8("getStaticProps",r));if("notFound"in e&&e.notFound){if("/404"===a)throw Error('The /404 page can not return notFound in "getStaticProps", please remove it to continue!');v.isNotFound=!0}if("redirect"in e&&e.redirect&&"object"==typeof e.redirect){if(e9(e.redirect,n,"getStaticProps"),er)throw Error(`\`redirect\` can not be returned from getStaticProps during prerendering (${n.url})
 See more info here: https://nextjs.org/docs/messages/gsp-redirect-during-prerender`);e.props={__N_REDIRECT:e.redirect.destination,__N_REDIRECT_STATUS:ef(e.redirect)},void 0!==e.redirect.basePath&&(e.props.__N_REDIRECT_BASE_PATH=e.redirect.basePath),v.isRedirect=!0}if((x||er)&&!v.isNotFound&&!z(a,"getStaticProps",e.props))throw Error("invariant: getStaticProps did not return valid props. Please report this.");if("revalidate"in e){if(e.revalidate&&"export"===l.nextConfigOutput)throw Error('ISR cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export');if("number"==typeof e.revalidate){if(Number.isInteger(e.revalidate)){if(e.revalidate<=0)throw Error(`A page's revalidate option can not be less than or equal to zero for ${n.url}. A revalidate option of zero means to revalidate after _every_ request, and implies stale data cannot be tolerated.
```
</details>
<details>
<summary>Diff for <strong>pages.runtime.dev.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ Reason: ${n}`)}}function z(e,t,r){if(!D(r))throw new H(e,t,"",`Props must be ret
 Keys that need to be moved: ${t.join(", ")}.
 Read more: https://nextjs.org/docs/messages/${r}`};function e6(e,t,r){let{destination:n,permanent:o,statusCode:s,basePath:a}=e,i=[],l=void 0!==s,d=void 0!==o;d&&l?i.push("`permanent` and `statusCode` can not both be provided"):d&&"boolean"!=typeof o?i.push("`permanent` must be `true` or `false`"):l&&!eh.has(s)&&i.push(`\`statusCode\` must undefined or one of ${[...eh].join(", ")}`);let u=typeof n;"string"!==u&&i.push(`\`destination\` should be string but received ${u}`);let c=typeof a;if("undefined"!==c&&"boolean"!==c&&i.push(`\`basePath\` should be undefined or a false, received ${c}`),i.length>0)throw Error(`Invalid redirect object returned from ${r} for ${t.url}
 `+i.join(" and ")+"\nSee more info here: https://nextjs.org/docs/messages/invalid-redirect-gssp")}async function e5(n,s,a,i,l,d){var u,h;let m,f,g;(0,$.gk)({req:n},"cookies",(h=n.headers,function(){let{cookie:e}=h;if(!e)return{};let{parse:t}=r("./dist/compiled/cookie/index.js");return t(Array.isArray(e)?e.join("; "):e)}));let v={};if(v.assetQueryString=l.dev&&l.assetQueryString||"",l.dev&&!v.assetQueryString){let e=(n.headers["user-agent"]||"").toLowerCase();e.includes("safari")&&!e.includes("chrome")&&(v.assetQueryString=`?ts=${Date.now()}`)}l.deploymentId&&(v.assetQueryString+=`${v.assetQueryString?"&":"?"}dpl=${l.deploymentId}`),i=Object.assign({},i);let{err:y,dev:x=!1,ampPath:b="",pageConfig:w={},buildManifest:S,reactLoadableManifest:P,ErrorDebug:_,getStaticProps:C,getStaticPaths:j,getServerSideProps:R,isDataReq:T,params:N,previewProps:A,basePath:L,images:q,runtime:D,isExperimentalCompile:F}=l,{App:H}=d,J=v.assetQueryString,G=d.Document,V=l.Component,Q=!!i.__nextFallback,Z=i.__nextNotFoundSrcPage;!function(e){for(let t of eF)delete e[t]}(i);let Y=!!C,er=Y&&l.nextExport,ei=H.getInitialProps===H.origGetInitialProps,eu=!!(null==V?void 0:V.getInitialProps),ec=null==V?void 0:V.unstable_scriptLoader,eh=en(a),eg="/_error"===a&&V.getInitialProps===V.origGetInitialProps;l.nextExport&&eu&&!eg&&t(`Detected getInitialProps on page '${a}' while running export. It's recommended to use getStaticProps which has a more correct behavior for static exporting.
-Read more: https://nextjs.org/docs/messages/get-initial-props-export`);let ev=!eu&&ei&&!Y&&!R;if(ev&&!x&&F&&(s.setHeader("Cache-Control","number"==typeof!1?"s-maxage=false, stale-while-revalidate":`s-maxage=${k.BR}, stale-while-revalidate`),ev=!1),eu&&Y)throw Error(k.wh+` ${a}`);if(eu&&R)throw Error(k.Wo+` ${a}`);if(R&&Y)throw Error(k.oL+` ${a}`);if(R&&"export"===l.nextConfigOutput)throw Error('getServerSideProps cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export');if(j&&!eh)throw Error(`getStaticPaths is only allowed for dynamic SSG pages and was found on '${a}'.
+Read more: https://nextjs.org/docs/messages/get-initial-props-export`);let ev=!eu&&ei&&!Y&&!R;if(ev&&!x&&F&&(s.setHeader("Cache-Control","number"==typeof!1?`s-maxage=false, stale-while-revalidate=${k.BR}`:`s-maxage=${k.BR}, stale-while-revalidate=${k.BR}`),ev=!1),eu&&Y)throw Error(k.wh+` ${a}`);if(eu&&R)throw Error(k.Wo+` ${a}`);if(R&&Y)throw Error(k.oL+` ${a}`);if(R&&"export"===l.nextConfigOutput)throw Error('getServerSideProps cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export');if(j&&!eh)throw Error(`getStaticPaths is only allowed for dynamic SSG pages and was found on '${a}'.
 Read more: https://nextjs.org/docs/messages/non-dynamic-getstaticpaths-usage`);if(j&&!Y)throw Error(`getStaticPaths was added without a getStaticProps in ${a}. Without getStaticProps, getStaticPaths does nothing`);if(Y&&eh&&!j)throw Error(`getStaticPaths is required for dynamic SSG pages and is missing for '${a}'.
 Read more: https://nextjs.org/docs/messages/invalid-getstaticpaths-value`);let eP=l.resolvedAsPath||n.url;if(x){let{isValidElementType:e}=r("./dist/compiled/react-is/index.js");if(!e(V))throw Error(`The default export is not a React Component in page: "${a}"`);if(!e(H))throw Error('The default export is not a React Component in page: "/_app"');if(!e(G))throw Error('The default export is not a React Component in page: "/_document"');if((ev||Q)&&(i={...i.amp?{amp:i.amp}:{}},eP=`${a}${n.url.endsWith("/")&&"/"!==a&&!eh?"/":""}`,n.url=a),"/404"===a&&(eu||R))throw Error(`\`pages/404\` ${k.Ei}`);if(M.Er.includes(a)&&(eu||R))throw Error(`\`pages${a}\` ${k.Ei}`)}for(let e of["getStaticProps","getServerSideProps","getStaticPaths"])if(null==V?void 0:V[e])throw Error(`page ${a} ${e} ${k.lk}`);await X.preloadAll(),(Y||R)&&!Q&&A&&(g=!1!==(m=e(n,s,A)));let e_=!!(R||eu||!ei&&!Y||F),eC=new e2(a,i,eP,{isFallback:Q},e_,L,l.locale,l.locales,l.defaultLocale,l.domainLocales,g,ep(n,"isLocaleDomain")),ej={back(){eC.back()},forward(){eC.forward()},refresh(){eC.reload()},push(e,t){let{scroll:r}=void 0===t?{}:t;eC.push(e,void 0,{scroll:r})},replace(e,t){let{scroll:r}=void 0===t?{}:t;eC.replace(e,void 0,{scroll:r})},prefetch(e){eC.prefetch(e)}},eR={},eT=(0,I.createStyleRegistry)(),eE={ampFirst:!0===w.amp,hasQuery:!!i.amp,hybrid:"hybrid"===w.amp},e$=function(e){let{ampFirst:t=!1,hybrid:r=!1,hasQuery:n=!1}=void 0===e?{}:e;return t||r&&n}(eE),eN=function(e){void 0===e&&(e=!1);let t=[(0,E.jsx)("meta",{charSet:"utf-8"})];return e||t.push((0,E.jsx)("meta",{name:"viewport",content:"width=device-width"})),t}(e$),eA=[],eL={};ec&&(eL.beforeInteractive=[].concat(ec()).filter(e=>"beforeInteractive"===e.props.strategy).map(e=>e.props));let eO=({children:e})=>{var t;return(0,E.jsx)(eQ.Provider,{value:ej,children:(0,E.jsx)(eH.Provider,{value:eC.isReady&&eC.query?(t=eC.asPath,new URL(t,"http://n").searchParams):new URLSearchParams,children:(0,E.jsx)(eV,{router:eC,isAutoExport:ev,children:(0,E.jsx)(eB.Provider,{value:function(e){if(!e.isReady||!e.query)return null;let t={},r=function(e){let{parameterizedRoute:t,groups:r}=function(e){let t=eS(e).slice(1).split("/"),r={},n=1;return{parameterizedRoute:t.map(e=>{let t=et.find(t=>e.startsWith(t)),o=e.match(/\[((?:\[.*\])|.+)\]/);if(t&&o){let{key:e,optional:s,repeat:a}=eG(o[1]);return r[e]={pos:n++,repeat:a,optional:s},"/"+eJ(t)+"([^/]+?)"}if(!o)return"/"+eJ(e);{let{key:e,repeat:t,optional:s}=eG(o[1]);return r[e]={pos:n++,repeat:t,optional:s},t?s?"(?:/(.+?))?":"/(.+?)":"/([^/]+?)"}}).join(""),groups:r}}(e);return{re:RegExp("^"+t+"(?:/)?$"),groups:r}}(e.pathname),n=Object.keys(r.groups);for(let r of n)t[r]=e.query[r];return t}(eC),children:(0,E.jsx)(K.Provider,{value:eC,children:(0,E.jsx)(B.Provider,{value:eE,children:(0,E.jsx)(U.Provider,{value:{updateHead:e=>{eN=e},updateScripts:e=>{eR=e},scripts:eL,mountedInstances:new Set},children:(0,E.jsx)(W.Provider,{value:e=>eA.push(e),children:(0,E.jsx)(I.StyleRegistry,{registry:eT,children:(0,E.jsx)(eM.Provider,{value:q,children:e})})})})})})})})})})},eI=()=>null,eq=({children:e})=>(0,E.jsxs)(E.Fragment,{children:[(0,E.jsx)(eI,{}),(0,E.jsx)(eO,{children:(0,E.jsxs)(E.Fragment,{children:[x?(0,E.jsxs)(E.Fragment,{children:[e,(0,E.jsx)(eI,{})]}):e,(0,E.jsx)(eI,{})]})})]}),ez={err:y,req:ev?void 0:n,res:ev?void 0:s,pathname:a,query:i,asPath:eP,locale:l.locale,locales:l.locales,defaultLocale:l.defaultLocale,AppTree:e=>(0,E.jsx)(eq,{children:e8(H,V,{...e,router:eC})}),defaultGetInitialProps:async(e,t={})=>{let{html:r,head:n}=await e.renderPage({enhanceApp:e=>t=>(0,E.jsx)(e,{...t})}),o=eT.styles({nonce:t.nonce});return eT.flush(),{html:r,head:n,styles:o}}},eU=!Y&&(l.nextExport||x&&(ev||Q)),eW=()=>{let e=eT.styles();return eT.flush(),(0,E.jsx)(E.Fragment,{children:e})};if(f=await ea(H,{AppTree:ez.AppTree,Component:V,router:eC,ctx:ez}),(Y||R)&&g&&(f.__N_PREVIEW=!0),Y&&(f[M.NO]=!0),Y&&!Q){let e,t;try{e=await (0,ef.getTracer)().trace(c.getStaticProps,{spanName:`getStaticProps ${a}`,attributes:{"next.route":a}},()=>C({...eh?{params:i}:void 0,...g?{draftMode:!0,preview:!0,previewData:m}:void 0,locales:l.locales,locale:l.locale,defaultLocale:l.defaultLocale}))}catch(e){throw e&&"ENOENT"===e.code&&delete e.code,e}if(null==e)throw Error(k.q6);let r=Object.keys(e).filter(e=>"revalidate"!==e&&"props"!==e&&"redirect"!==e&&"notFound"!==e);if(r.includes("unstable_revalidate"))throw Error(k.Eo);if(r.length)throw Error(e9("getStaticProps",r));if(void 0!==e.notFound&&void 0!==e.redirect)throw Error(`\`redirect\` and \`notFound\` can not both be returned from ${Y?"getStaticProps":"getServerSideProps"} at the same time. Page: ${a}
 See more info here: https://nextjs.org/docs/messages/gssp-mixed-not-found-redirect`);if("notFound"in e&&e.notFound){if("/404"===a)throw Error('The /404 page can not return notFound in "getStaticProps", please remove it to continue!');v.isNotFound=!0}if("redirect"in e&&e.redirect&&"object"==typeof e.redirect){if(e6(e.redirect,n,"getStaticProps"),er)throw Error(`\`redirect\` can not be returned from getStaticProps during prerendering (${n.url})
```
</details>
<details>
<summary>Diff for <strong>pages.runtime.prod.js</strong></summary>

```diff
@@ -20,7 +20,7 @@ Reason: ${n}`)}}function z(e,t,r){if(!D(r))throw new H(e,t,"",`Props must be ret
 Keys that need to be moved: ${t.join(", ")}.
 Read more: https://nextjs.org/docs/messages/${r}`};function e9(e,t,r){let{destination:n,permanent:o,statusCode:s,basePath:a}=e,i=[],l=void 0!==s,d=void 0!==o;d&&l?i.push("`permanent` and `statusCode` can not both be provided"):d&&"boolean"!=typeof o?i.push("`permanent` must be `true` or `false`"):l&&!eh.has(s)&&i.push(`\`statusCode\` must undefined or one of ${[...eh].join(", ")}`);let u=typeof n;"string"!==u&&i.push(`\`destination\` should be string but received ${u}`);let c=typeof a;if("undefined"!==c&&"boolean"!==c&&i.push(`\`basePath\` should be undefined or a false, received ${c}`),i.length>0)throw Error(`Invalid redirect object returned from ${r} for ${t.url}
 `+i.join(" and ")+"\nSee more info here: https://nextjs.org/docs/messages/invalid-redirect-gssp")}async function e6(n,s,a,i,l,d){var u,h;let f,m,g;(0,$.gk)({req:n},"cookies",(h=n.headers,function(){let{cookie:e}=h;if(!e)return{};let{parse:t}=r("./dist/compiled/cookie/index.js");return t(Array.isArray(e)?e.join("; "):e)}));let v={};if(v.assetQueryString=l.dev&&l.assetQueryString||"",l.dev&&!v.assetQueryString){let e=(n.headers["user-agent"]||"").toLowerCase();e.includes("safari")&&!e.includes("chrome")&&(v.assetQueryString=`?ts=${Date.now()}`)}l.deploymentId&&(v.assetQueryString+=`${v.assetQueryString?"&":"?"}dpl=${l.deploymentId}`),i=Object.assign({},i);let{err:y,dev:x=!1,ampPath:b="",pageConfig:w={},buildManifest:S,reactLoadableManifest:P,ErrorDebug:_,getStaticProps:R,getStaticPaths:j,getServerSideProps:C,isDataReq:T,params:N,previewProps:A,basePath:L,images:q,runtime:D,isExperimentalCompile:F}=l,{App:H}=d,J=v.assetQueryString,G=d.Document,V=l.Component,Q=!!i.__nextFallback,Z=i.__nextNotFoundSrcPage;!function(e){for(let t of eF)delete e[t]}(i);let Y=!!R,er=Y&&l.nextExport,ei=H.getInitialProps===H.origGetInitialProps,eu=!!(null==V?void 0:V.getInitialProps),ec=null==V?void 0:V.unstable_scriptLoader,eh=en(a),eg="/_error"===a&&V.getInitialProps===V.origGetInitialProps;l.nextExport&&eu&&!eg&&t(`Detected getInitialProps on page '${a}' while running export. It's recommended to use getStaticProps which has a more correct behavior for static exporting.
-Read more: https://nextjs.org/docs/messages/get-initial-props-export`);let ev=!eu&&ei&&!Y&&!C;if(ev&&!x&&F&&(s.setHeader("Cache-Control","number"==typeof!1?"s-maxage=false, stale-while-revalidate":`s-maxage=${k.BR}, stale-while-revalidate`),ev=!1),eu&&Y)throw Error(k.wh+` ${a}`);if(eu&&C)throw Error(k.Wo+` ${a}`);if(C&&Y)throw Error(k.oL+` ${a}`);if(C&&"export"===l.nextConfigOutput)throw Error('getServerSideProps cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export');if(j&&!eh)throw Error(`getStaticPaths is only allowed for dynamic SSG pages and was found on '${a}'.
+Read more: https://nextjs.org/docs/messages/get-initial-props-export`);let ev=!eu&&ei&&!Y&&!C;if(ev&&!x&&F&&(s.setHeader("Cache-Control","number"==typeof!1?`s-maxage=false, stale-while-revalidate=${k.BR}`:`s-maxage=${k.BR}, stale-while-revalidate=${k.BR}`),ev=!1),eu&&Y)throw Error(k.wh+` ${a}`);if(eu&&C)throw Error(k.Wo+` ${a}`);if(C&&Y)throw Error(k.oL+` ${a}`);if(C&&"export"===l.nextConfigOutput)throw Error('getServerSideProps cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export');if(j&&!eh)throw Error(`getStaticPaths is only allowed for dynamic SSG pages and was found on '${a}'.
 Read more: https://nextjs.org/docs/messages/non-dynamic-getstaticpaths-usage`);if(j&&!Y)throw Error(`getStaticPaths was added without a getStaticProps in ${a}. Without getStaticProps, getStaticPaths does nothing`);if(Y&&eh&&!j)throw Error(`getStaticPaths is required for dynamic SSG pages and is missing for '${a}'.
 Read more: https://nextjs.org/docs/messages/invalid-getstaticpaths-value`);let eP=l.resolvedAsPath||n.url;if(x){let{isValidElementType:e}=r("./dist/compiled/react-is/index.js");if(!e(V))throw Error(`The default export is not a React Component in page: "${a}"`);if(!e(H))throw Error('The default export is not a React Component in page: "/_app"');if(!e(G))throw Error('The default export is not a React Component in page: "/_document"');if((ev||Q)&&(i={...i.amp?{amp:i.amp}:{}},eP=`${a}${n.url.endsWith("/")&&"/"!==a&&!eh?"/":""}`,n.url=a),"/404"===a&&(eu||C))throw Error(`\`pages/404\` ${k.Ei}`);if(M.Er.includes(a)&&(eu||C))throw Error(`\`pages${a}\` ${k.Ei}`)}for(let e of["getStaticProps","getServerSideProps","getStaticPaths"])if(null==V?void 0:V[e])throw Error(`page ${a} ${e} ${k.lk}`);await X.preloadAll(),(Y||C)&&!Q&&A&&(g=!1!==(f=e(n,s,A)));let e_=!!(C||eu||!ei&&!Y||F),eR=new e3(a,i,eP,{isFallback:Q},e_,L,l.locale,l.locales,l.defaultLocale,l.domainLocales,g,ep(n,"isLocaleDomain")),ej={back(){eR.back()},forward(){eR.forward()},refresh(){eR.reload()},push(e,t){let{scroll:r}=void 0===t?{}:t;eR.push(e,void 0,{scroll:r})},replace(e,t){let{scroll:r}=void 0===t?{}:t;eR.replace(e,void 0,{scroll:r})},prefetch(e){eR.prefetch(e)}},eC={},eT=(0,I.createStyleRegistry)(),eE={ampFirst:!0===w.amp,hasQuery:!!i.amp,hybrid:"hybrid"===w.amp},e$=function(e){let{ampFirst:t=!1,hybrid:r=!1,hasQuery:n=!1}=void 0===e?{}:e;return t||r&&n}(eE),eN=function(e){void 0===e&&(e=!1);let t=[(0,E.jsx)("meta",{charSet:"utf-8"})];return e||t.push((0,E.jsx)("meta",{name:"viewport",content:"width=device-width"})),t}(e$),eA=[],eL={};ec&&(eL.beforeInteractive=[].concat(ec()).filter(e=>"beforeInteractive"===e.props.strategy).map(e=>e.props));let eO=({children:e})=>{var t;return(0,E.jsx)(eQ.Provider,{value:ej,children:(0,E.jsx)(eH.Provider,{value:eR.isReady&&eR.query?(t=eR.asPath,new URL(t,"http://n").searchParams):new URLSearchParams,children:(0,E.jsx)(eV,{router:eR,isAutoExport:ev,children:(0,E.jsx)(eB.Provider,{value:function(e){if(!e.isReady||!e.query)return null;let t={},r=function(e){let{parameterizedRoute:t,groups:r}=function(e){let t=eS(e).slice(1).split("/"),r={},n=1;return{parameterizedRoute:t.map(e=>{let t=et.find(t=>e.startsWith(t)),o=e.match(/\[((?:\[.*\])|.+)\]/);if(t&&o){let{key:e,optional:s,repeat:a}=eG(o[1]);return r[e]={pos:n++,repeat:a,optional:s},"/"+eJ(t)+"([^/]+?)"}if(!o)return"/"+eJ(e);{let{key:e,repeat:t,optional:s}=eG(o[1]);return r[e]={pos:n++,repeat:t,optional:s},t?s?"(?:/(.+?))?":"/(.+?)":"/([^/]+?)"}}).join(""),groups:r}}(e);return{re:RegExp("^"+t+"(?:/)?$"),groups:r}}(e.pathname),n=Object.keys(r.groups);for(let r of n)t[r]=e.query[r];return t}(eR),children:(0,E.jsx)(K.Provider,{value:eR,children:(0,E.jsx)(B.Provider,{value:eE,children:(0,E.jsx)(U.Provider,{value:{updateHead:e=>{eN=e},updateScripts:e=>{eC=e},scripts:eL,mountedInstances:new Set},children:(0,E.jsx)(W.Provider,{value:e=>eA.push(e),children:(0,E.jsx)(I.StyleRegistry,{registry:eT,children:(0,E.jsx)(eM.Provider,{value:q,children:e})})})})})})})})})})},eI=()=>null,eq=({children:e})=>(0,E.jsxs)(E.Fragment,{children:[(0,E.jsx)(eI,{}),(0,E.jsx)(eO,{children:(0,E.jsxs)(E.Fragment,{children:[x?(0,E.jsxs)(E.Fragment,{children:[e,(0,E.jsx)(eI,{})]}):e,(0,E.jsx)(eI,{})]})})]}),ez={err:y,req:ev?void 0:n,res:ev?void 0:s,pathname:a,query:i,asPath:eP,locale:l.locale,locales:l.locales,defaultLocale:l.defaultLocale,AppTree:e=>(0,E.jsx)(eq,{children:e2(H,V,{...e,router:eR})}),defaultGetInitialProps:async(e,t={})=>{let{html:r,head:n}=await e.renderPage({enhanceApp:e=>t=>(0,E.jsx)(e,{...t})}),o=eT.styles({nonce:t.nonce});return eT.flush(),{html:r,head:n,styles:o}}},eU=!Y&&(l.nextExport||x&&(ev||Q)),eW=()=>{let e=eT.styles();return eT.flush(),(0,E.jsx)(E.Fragment,{children:e})};if(m=await ea(H,{AppTree:ez.AppTree,Component:V,router:eR,ctx:ez}),(Y||C)&&g&&(m.__N_PREVIEW=!0),Y&&(m[M.NO]=!0),Y&&!Q){let e,t;try{e=await (0,em.getTracer)().trace(c.getStaticProps,{spanName:`getStaticProps ${a}`,attributes:{"next.route":a}},()=>R({...eh?{params:i}:void 0,...g?{draftMode:!0,preview:!0,previewData:f}:void 0,locales:l.locales,locale:l.locale,defaultLocale:l.defaultLocale}))}catch(e){throw e&&"ENOENT"===e.code&&delete e.code,e}if(null==e)throw Error(k.q6);let r=Object.keys(e).filter(e=>"revalidate"!==e&&"props"!==e&&"redirect"!==e&&"notFound"!==e);if(r.includes("unstable_revalidate"))throw Error(k.Eo);if(r.length)throw Error(e8("getStaticProps",r));if("notFound"in e&&e.notFound){if("/404"===a)throw Error('The /404 page can not return notFound in "getStaticProps", please remove it to continue!');v.isNotFound=!0}if("redirect"in e&&e.redirect&&"object"==typeof e.redirect){if(e9(e.redirect,n,"getStaticProps"),er)throw Error(`\`redirect\` can not be returned from getStaticProps during prerendering (${n.url})
 See more info here: https://nextjs.org/docs/messages/gsp-redirect-during-prerender`);e.props={__N_REDIRECT:e.redirect.destination,__N_REDIRECT_STATUS:ef(e.redirect)},void 0!==e.redirect.basePath&&(e.props.__N_REDIRECT_BASE_PATH=e.redirect.basePath),v.isRedirect=!0}if((x||er)&&!v.isNotFound&&!z(a,"getStaticProps",e.props))throw Error("invariant: getStaticProps did not return valid props. Please report this.");if("revalidate"in e){if(e.revalidate&&"export"===l.nextConfigOutput)throw Error('ISR cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export');if("number"==typeof e.revalidate){if(Number.isInteger(e.revalidate)){if(e.revalidate<=0)throw Error(`A page's revalidate option can not be less than or equal to zero for ${n.url}. A revalidate option of zero means to revalidate after _every_ request, and implies stale data cannot be tolerated.
```
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 40bdcca0825458ae3272c9dba90662ab070ba63b

**Comment by ijjk** [comment]
Actually I'm not sure this change is safe, since if a CDN isn't present in front of Next.js then the client may unexpectedly consume this header instead causing unexpected behavior.

**Comment by adrianha** [comment]
@ijjk do you have suggestion how to test it? was checked running production build locally, there seems no difference. as for case with CDN, tested in Cloudfront, it allows Cloudfront to serve `STALE` content while it revalidated in the background thus response `RefreshHit`, previously the response were only `Hit` or `Miss`

**Comment by ijjk** [comment]
Was just double checking through https://datatracker.ietf.org/doc/html/rfc5861#section-3.1 and this may be fine. If a user does have a CDN in front of Next.js (most likely) then their CDN will dictate the behavior and then if there isn't a CDN then `s-maxage` will be ignored and then the client will be able to fallback to `stale-while-revalidate` behavior if supported which should match most CDN's handling

Also was reminded a previous PR we decided this was acceptable that failed to land https://github.com/vercel/next.js/pull/52251

**Comment by adrianha** [comment]
thanks for the confirmation @ijjk !

**Comment by adrianha** [comment]
reverted `/gssp` test value as `swr` is not defined https://github.com/vercel/next.js/blob/canary/test/production/standalone-mode/required-server-files/pages/gssp.js#L8 @ijjk

**Comment by adrianha** [comment]
could you help to re-run the CI checks @ijjk ? also not sure why its failing on prefetch test

**Comment by ijjk** [comment]
Yeah triggered run, I think the prefetch failure is due to the browser having the additional caching now which the test assumes it doesn't

**Comment by adrianha** [comment]
its failed to set up the runner now

**Comment by adrianha** [comment]
hi @ijjk, just adjusted some tests on prefetching, could you help to re-run the tests? changes on #61794 looks like related with `rsc` payload that impacting the tests

and also could you help to run tests on #61944? I found the tests also failed with current cache config, wondering if its failed only on my machine

**Comment by adrianha** [comment]
hi @ijjk , just adjusted some tests on prefetching, could you help to re-run the tests? changes on #61794 looks like related with rsc payload that impacting the tests

and also could you help to run tests on #61944? I found the tests also failed with current cache config, wondering if its failed only on my machine

**Comment by adrianha** [comment]
hi @ijjk,

- just removed `rsc` test case on this [commit](https://github.com/vercel/next.js/pull/61330/commits/570ec4952b692e3564251b3b98b8d8bedd014fc6), due to changes on #61794 and #61235 that removes `next-url` changes that was added on #52746, kindly help to confirm if this removal is expected
- also want to confirm if https://github.com/vercel/next.js/blob/canary/packages/next/src/client/components/router-reducer/fetch-server-response.ts#L86 should be removed? referring to `NEXT_URL` removal on https://github.com/vercel/next.js/pull/61794/files#diff-90d1d5f446bdf243be25cc4ea2295a9c91508859d655e51d5ec4a3562d3a24d9R1105

**Review by ijjk — COMMENTED** [review]
@adrianha what do you think about putting this change behind an experimental flag and leaving the default to `false` so that we avoid any breaking/test changes being needed by default and those who need it can opt-in?

**Comment by adrianha** [comment]
do you mean adding new option to define swr on ISR pages @ijjk ?

ex:
{
  revalidate: 600,
  staleWhileRevalidate: 6000,
}

**Comment by ijjk** [comment]
No I mean an experimental config in `next.config.js` like `exposeSwrDelta`, that toggles it being set or not and it's defaulted to `false` which is the current behavior.

**Comment by adrianha** [comment]
hi @ijjk, just added `swrDelta` option to `next.config.js` for specifying `stale-while-revalidate` delta amount

File: packages/next/src/export/index.ts [hunk 2]
```diff
@@ -507,6 +507,7 @@ export async function exportAppImpl(
       : {}),
     strictNextHead: !!nextConfig.experimental.strictNextHead,
     deploymentId: nextConfig.experimental.deploymentId,
+    swrDelta: nextConfig.swrDelta,
```
Comment (ijjk) [inline packages/next/src/export/index.ts:510]: Let's keep this in experimental to start, then we can stabilize after some testing/validating

Comment (adrianha) [reply packages/next/src/export/index.ts]: noted, adjusted to `experimental`

**Review by ijjk — APPROVED** [review]
