### PR TITLE
Fix: Cleaner error message when importing sass without it being installed in dev

### LINKED ISSUE #13975: Bad error message when importing sass without it being installed in dev
The require stack should not be present when importing sass without it installed in dev.
This message should be short & sweet.

image

```
error - ./pages/test.module.scss
To use Next.js' built-in Sass support, you first need to install `sass`.
Run `npm i sass` or `yarn add sass` inside your workspace.

Learn more: https://err.sh/next.js/install-sass
Require stack:
- /Users/joe/Desktop/scratch2/test/node_modules/sass-loader/dist/getDefaultSassImplementation.js
- /Users/joe/Desktop/scratch2/test/node_modules/sass-loader/dist/getSassImplementation.js
- /Users/joe/Desktop/scratch2/test/node_modules/sass-loader/dist/index.js
- /Users/joe/Desktop/scratch2/test/node_modules/sass-loader/dist/cjs.js
- /Users/joe/Desktop/scratch2/test/node_modules/loader-runner/lib/loadLoader.js
- /Users/joe/Desktop/scratch2/test/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/joe/Desktop/scratch2/test/node_modules/webpack/lib/NormalModule.js
- /Users/joe/Desktop/scratch2/test/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/joe/Desktop/scratch2/test/node_modules/webpack/lib/Compiler.js
- /Users/joe/Desktop/scratch2/test/node_modules/webpack/lib/webpack.js
- /Users/joe/Desktop/scratch2/test/node_modules/next/dist/server/hot-reloader.js
- /Users/joe/Desktop/scratch2/test/node_modules/next/dist/server/next-dev-server.js
- /Users/joe/Desktop/scratch2/test/node_modules/next/dist/server/next.js
- /Users/joe/Desktop/scratch2/test/node_modules/next/dist/server/lib/start-server.js
- /Users/joe/Desktop/scratch2/test/node_modules/next/dist/cli/next-dev.js
- /Users/joe/Desktop/scratch2/test/node_modules/next/dist/bin/next
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Cannot find module 'node-sass'
Require stack:
- /Users/joe/Desktop/scratch2/test/node_modules/sass-loader/dist/getDefaultSassImplementation.js
- /Users/joe/Desktop/scratch2/test/node_modules/sass-loader/dist/getSassImplementation.js
- /Users/joe/Desktop/scratch2/test/node_modules/sass-loader/dist/index.js
- /Users/joe/Desktop/scratch2/test/node_modules/sass-loader/dist/cjs.js
- /Users/joe/Desktop/scratch2/test/node_modules/loader-runner/lib/loadLoader.js
- /Users/joe/Desktop/scratch2/test/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/joe/Desktop/scratch2/test/node_modules/webpack/lib/NormalModule.js
- /Users/joe/Desktop/scratch2/test/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/joe/Desktop/scratch2/test/node_modules/webpack/lib/Compiler.js
- /Users/joe/Desktop/scratch2/test/node_modules/webpack/lib/webpack.js
- /Users/joe/Desktop/scratch2/test/node_modules/next/dist/server/hot-reloader.js
- /Users/joe/Desktop/scratch2/test/node_modules/next/dist/server/next-dev-server.js
- /Users/joe/Desktop/scratch2/test/node_modules/next/dist/server/next.js
- /Users/joe/Desktop/scratch2/test/node_modules/next/dist/server/lib/start-server.js
- /Users/joe/Desktop/scratch2/test/node_modules/next/dist/cli/next-dev.js
- /Users/joe/Desktop/scratch2/test/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at getDefaultSassImplementation (/Users/joe/Desktop/scratch2/test/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/Users/joe/Desktop/scratch2/test/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/Users/joe/Desktop/scratch2/test/node_modules/sass-loader/dist/index.js:40:61)
    at /Users/joe/Desktop/scratch2/test/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/joe/Desktop/scratch2/test/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/joe/Desktop/scratch2/test/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/joe/Desktop/scratch2/test/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/joe/Desktop/scratch2/test/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /Users/joe/Desktop/scratch2/test/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /Users/joe/Desktop/scratch2/test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

### PR DESCRIPTION
**Pull request by baruchadi**
This PR removes the not-very-helpful stack trace when sass is being used but the npm package is not installed. Fixes #13975

- Fix behavior to show the modified error message if either node-sass OR sass is missing
- dispose of stack trace if the condition above passes
- update the error link to [err.sh](https://err.sh/next.js/install-sass) equivalent 
- update the relevant test to verify the stack trace is omitted and to account for the new link

## Bug

- [x] Related issues linked using `fixes #13975`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| buildDuration | 15.4s | 15.3s | -118ms |
| buildDurationCached | 6s | 6s | ⚠️ +21ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +146 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.088 | 3.112 | ⚠️ +0.02 |
| / avg req/sec | 809.52 | 803.35 | ⚠️ -6.17 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.347 | 1.326 | -0.02 |
| /error-in-render avg req/sec | 1855.46 | 1885.5 | +30.04 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.5 kB | 71.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.06 kB | 5.06 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.8 kB | 14.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| buildDuration | 18.5s | 18.9s | ⚠️ +371ms |
| buildDurationCached | 6s | 6s | -21ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +146 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.093 | 3.064 | -0.03 |
| / avg req/sec | 808.4 | 815.93 | +7.53 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.345 | 1.356 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1859.05 | 1843.92 | ⚠️ -15.13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.2 kB | 5.2 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.9 kB | 14.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 352a131ded6ef446aedf9cfe1e8cfacd2f225fe6

**Comment by balazsorban44** [comment]
Using this change, I'm seeing the following on a global Sass import:
 
image

Similar to the CSS module, I think we should also clean up the stack trace before the custom error message.

File: packages/next/client/dev/error-overlay/format-webpack-messages.js [hunk 1]
```diff
@@ -111,14 +111,17 @@ function formatMessage(message, verbose) {
   }
 
   // Add helpful message for users trying to use Sass for the first time
-  if (lines[1] && lines[1].match(/Cannot find module.+node-sass/)) {
+  if (lines[1] && lines[1].match(/Cannot find module.+sass/)) {
     // ./file.module.scss (<<loader info>>) => ./file.module.scss
     lines[0] = lines[0].replace(/(.+) \(.+?(?=\?\?).+?\)/, '$1')
```
Comment (balazsorban44) [inline packages/next/client/dev/error-overlay/format-webpack-messages.js:116]:
```suggestion
    const firstLine = lines[0].split('!')
    lines[0] = firstLine[firstLine.length-1]
```

This seems to correctly print both global and module CSS file names without anything else.

File: test/integration/scss/test/index.test.js [hunk 2]
```diff
@@ -43,8 +43,9 @@ describe('SCSS Support', () => {
         'Run `npm i sass` or `yarn add sass` inside your workspace.'
       )
       expect(stderr).toContain(
-        'Learn more: https://nextjs.org/docs/messages/install-sass'
+        'Learn more: https://err.sh/next.js/install-sass'
       )
+      expect(stderr).not.toContain('Require stack:')
```
Comment (balazsorban44) [inline test/integration/scss/test/index.test.js:48]:
```suggestion
      expect(stderr).not.toContain('Require stack:')
      expect(stderr).not.toContain('css-loader/src/index.js??')
```

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
I'm seeing the following on a global Sass import:
 
image

Similar to the CSS module, let's make sure to clean up the stack trace before the custom error message.

**Comment by baruchadi** [comment]
@balazsorban44 
> Similar to the CSS module, let's make sure to clean up the stack trace before the custom error message.

Sounds good, I'll get on it! 
To get some more clarity before I make this modification:

Below is the `stderr` string on which the tests are performed, it seems like there are a lot of subsequent errors besides the one I'm working on which have the `ruleset` substring. That would cause the new test assertion you recommended to fail, regardless of if I use the approach you mentioned above to clean up the trace before the custom error message. 

> expect(stderr).not.toContain('ruleSet')

- Should these other error messages be cleaned up as well, as part the scope of this issue/PR? 
- If not, and the rest of the errors are behaving as expected - I'll have to apply these tests to a part of the `stderr` string for the tests to pass correctly while keeping the new assertion. 
  - the new string on which I'll test will be the first 9 lines, or in other words until a second `./styles/...` is found. 

Let me know what you think!


    warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic- features/eslint#migrating-existing-config
    Failed to compile.
    
    ./styles/global.scss
    To use Next.js' built-in Sass support, you first need to install `sass`.
    Run `npm i sass` or `yarn add sass` inside your workspace.
    
    Learn more: https://err.sh/next.js/install-sass
    
    ./styles/global.scss.webpack[javascript/auto]!=!../../../../packages/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!../../../../packages/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!../../../../packages/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[3].oneOf[9].use[3]!../../../../packages/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[3].oneOf[9].use[4]!./styles/global.scss
    Error: resolve-url-loader: CSS error
      PostCSS received undefined instead of CSS string
      at new Input (/Users/baruchadi/projects/next/next.js/packages/next/node_modules/postcss/lib/input.js:24:13)
        at encodeError (/Users/baruchadi/projects/next/next.js/packages/next/dist/build/webpack/loaders/resolve-url-loader/index.js:52:16)
        at onFailure (/Users/baruchadi/projects/next/next.js/packages/next/dist/build/webpack/loaders/resolve-url-loader/index.js:38:18)
    
    Import trace for requested module:
    ./styles/global.scss
    ./pages/_app.js
    
    ./styles/global.scss
    Error: resolve-url-loader: CSS error
      PostCSS received undefined instead of CSS string
      at new Input (/Users/baruchadi/projects/next/next.js/packages/next/node_modules/postcss/lib/input.js:24:13)
        at encodeError (/Users/baruchadi/projects/next/next.js/packages/next/dist/build/webpack/loaders/resolve-url-loader/index.js:52:16)
        at onFailure (/Users/baruchadi/projects/next/next.js/packages/next/dist/build/webpack/loaders/resolve-url-loader/index.js:38:18)
        at tryRunOrWebpackError (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:41704:9)
        at __webpack_require_module__ (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:27321:12)
        at __nested_webpack_require_152432__ (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:27278:18)
        at /Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:27349:20
        at symbolIterator (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/neo-async/async.js:1:14443)
        at done (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/neo-async/async.js:1:14823)
        at Hook.eval [as callAsync] (eval at create (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:140346:10), <anonymous>:13:1)
        at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:140148:14)
        at /Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:27256:43
        at symbolIterator (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/neo-async/async.js:1:14401)
    -- inner error --
    Error: resolve-url-loader: CSS error
      PostCSS received undefined instead of CSS string
      at new Input (/Users/baruchadi/projects/next/next.js/packages/next/node_modules/postcss/lib/input.js:24:13)
        at encodeError (/Users/baruchadi/projects/next/next.js/packages/next/dist/build/webpack/loaders/resolve-url-loader/index.js:52:16)
        at onFailure (/Users/baruchadi/projects/next/next.js/packages/next/dist/build/webpack/loaders/resolve-url-loader/index.js:38:18)
        at Object.<anonymous> (/Users/baruchadi/projects/next/next.js/packages/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!/Users/baruchadi/projects/next/next.js/packages/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!/Users/baruchadi/projects/next/next.js/packages/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[3].oneOf[9].use[3]!/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[3].oneOf[9].use[4]!/Users/baruchadi/projects/next/next.js/test/integration/scss-fixtures/webpack-error/styles/global.scss:1:7)
        at /Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:90227:11
        at Hook.eval [as call] (eval at create (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:140332:10), <anonymous>:5:1)
        at Hook.CALL_DELEGATE [as _call] (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:140144:14)
        at /Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:27323:39
        at tryRunOrWebpackError (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:41699:7)
        at __webpack_require_module__ (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:27321:12)
        at __nested_webpack_require_152432__ (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:27278:18)
        at /Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/webpack/bundle5.js:27349:20
        at symbolIterator (/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/neo-async/async.js:1:14443)
    
    Generated code for /Users/baruchadi/projects/next/next.js/packages/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!/Users/baruchadi/projects/next/next.js/packages/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!/Users/baruchadi/projects/next/next.js/packages/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[3].oneOf[9].use[3]!/Users/baruchadi/projects/next/next.js/packages/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[3].oneOf[9].use[4]!/Users/baruchadi/projects/next/next.js/test/integration/scss-fixtures/webpack-error/styles/global.scss
    
    Import trace for requested module:
    ./pages/_app.js
    
    
    > Build failed because of webpack errors`

**Comment by balazsorban44** [comment]
> Should these other error messages be cleaned up as well, as part of the scope of this issue/PR?

No, let's focus on the original issue.

A better approach to the `expect` assertion would be to do `expect(stderr).toBe("...")` with an exact match of the result. :+1:

File: test/integration/scss/test/index.test.js (hunk 2 above)
Comment (balazsorban44) [reply test/integration/scss/test/index.test.js:48]: See https://github.com/vercel/next.js/pull/35051#issuecomment-1060835592

File: test/integration/scss/test/index.test.js [hunk 3]
```diff
@@ -34,17 +34,20 @@ describe('SCSS Support', () => {
...
-      )
-      expect(stderr).toContain(
-        'Run `npm i sass` or `yarn add sass` inside your workspace.'
-      )
-      expect(stderr).toContain(
-        'Learn more: https://nextjs.org/docs/messages/install-sass'
-      )
+      expect(stderr).toContain(cleanScssErrMsg)
+
+      expect(stderr).not.toContain('Require stack:')
```
Comment (balazsorban44) [inline test/integration/scss/test/index.test.js:50]:
```suggestion
```

This is not necessary anymore.

**Comment by baruchadi** [comment]
I went with 
`expect(stderr).toContain(cleanScssErrMsg)`
Because the stderr is just so large (check my previous comment above) and I wanted to avoid snapshotting.

by adding two linebreaks `\n\n` both before and after the expected "clean message", we can assert that there is no trace prepended or appended to our "clean message"

update: remove the unnecessary test assertion for "Require stack"

File: test/integration/scss/test/index.test.js (hunk 3 above)
Comment (baruchadi) [reply test/integration/scss/test/index.test.js]: resolved in commit [7086fa0](https://github.com/vercel/next.js/pull/35051/commits/7086fa04cd5d83afc8bb38dd6949292b546a3312)

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| buildDuration | 19.3s | 19.3s | ⚠️ +18ms |
| buildDurationCached | 7.5s | 7.7s | ⚠️ +225ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +251 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.828 | 3.845 | ⚠️ +0.02 |
| / avg req/sec | 653.03 | 650.26 | ⚠️ -2.77 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.684 | 1.685 | 0 |
| /error-in-render avg req/sec | 1484.53 | 1484.05 | ⚠️ -0.48 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.5 kB | 71.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.06 kB | 5.06 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.8 kB | 14.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| buildDuration | 23.3s | 22.9s | -472ms |
| buildDurationCached | 7.7s | 7.4s | -265ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +251 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.777 | 3.964 | ⚠️ +0.19 |
| / avg req/sec | 661.88 | 630.63 | ⚠️ -31.25 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.667 | 1.701 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1499.48 | 1470.06 | ⚠️ -29.42 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.2 kB | 5.2 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.9 kB | 14.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | baruchadi/next.js feature/friendly-sass-err-msg | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 9515deb88976eea4614669f363b6177f36b5b2f5

File: test/integration/scss/test/index.test.js [hunk 4]
```diff
@@ -34,17 +34,18 @@ describe('SCSS Support', () => {
...
-      expect(stderr).toContain(
-        "To use Next.js' built-in Sass support, you first need to install `sass`."
-      )
-      expect(stderr).toContain(
-        'Run `npm i sass` or `yarn add sass` inside your workspace.'
-      )
-      expect(stderr).toContain(
-        'Learn more: https://nextjs.org/docs/messages/install-sass'
-      )
+      expect(stderr).toContain(cleanScssErrMsg)
```
Comment (balazsorban44) [inline test/integration/scss/test/index.test.js:48]: This should probably still use `toMatch` for an exact match, not `toContain`.

Or a better alternative is `toMatchInlineSnapshot` so you can drop the extra variable.  https://jestjs.io/docs/snapshot-testing#inline-snapshots

**Review by balazsorban44 — DISMISSED** [review]
Let's make the assertion exact since we are trying to verify that there is no leftover in the output.

File: test/integration/scss/test/index.test.js (hunk 4 above)
Comment (baruchadi) [reply test/integration/scss/test/index.test.js:48]: I don't think that either`toMatchInlineSnapshot` or `toMatch` would be the right choice here, since the `stderr` string contains a lot of machine specific information such as absolute paths
i.e. 
`at new Input (/Users/baruchadi/projects/next/next.js/packages/next/node_modules/postcss/lib/input.js:24:13)`

and given that the string is about 60 lines long and has more than than 6500 characters (see example value here: https://gist.github.com/baruchadi/81be9d5b4d1f45d6f1f22b2195777a9a), I believe that `.toContain` would be our best bet at the moment. 
We can do `.toMatch` with some regex, but that would require us to make a lot of assumptions and the result would be very similar to `.toContain`.

**Note** that in the code, i'm checking for two new lines before and after our clean message. this should guarantee that the stack was removed from above and below our message.

see the diff between our error message and the original unedited one 
image

Comment (balazsorban44) [reply test/integration/scss/test/index.test.js:48]: Wasn't the point of this PR to only have https://gist.github.com/baruchadi/81be9d5b4d1f45d6f1f22b2195777a9a#file-stderr-output-L4-L8 ? That should always be the same.

**Review by ijjk — APPROVED** [review]
Thanks for the PR!
