### PR TITLE
Fix basePath replacing server-side and `normalizeLocalePath()` when path is empty string

### LINKED ISSUE #22429: TypeError: Cannot read property 'toLowerCase' of undefined
**What version of Next.js are you using?**

10.0.7

**What version of Node.js are you using?**

14.15.5-buster

**What browser are you using?**

Chrome

**What operating system are you using?**

Docker image node:14.15.5-buster

**How are you deploying your application?**

Docker image on Google Cloud Platform using Cloud Run

**Describe the Bug**

I get the following errors and the page will not load:

```
$ next start -p $PORT
Loaded env from /app/.env.local
ready - started server on 0.0.0.0:8080, url: http://localhost:8080
(node:24) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
 at /app/node_modules/next/dist/next-server/lib/i18n/normalize-locale-path.js:2:89
 at Array.some (<anonymous>)
 at normalizeLocalePath (/app/node_modules/next/dist/next-server/lib/i18n/normalize-locale-path.js:2:55)
 at Server.handleRequest (/app/node_modules/next/dist/next-server/server/next-server.js:21:274)
 at Server.emit (events.js:315:20)
 at parserOnIncoming (_http_server.js:874:12)
 at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:24) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:24) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
 at /app/node_modules/next/dist/next-server/lib/i18n/normalize-locale-path.js:2:89
 at Array.some (<anonymous>)
 at normalizeLocalePath (/app/node_modules/next/dist/next-server/lib/i18n/normalize-locale-path.js:2:55)
 at Server.handleRequest (/app/node_modules/next/dist/next-server/server/next-server.js:21:274)
 at Server.emit (events.js:315:20)
 at parserOnIncoming (_http_server.js:874:12)
 at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:24) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
...
```

**Expected Behavior**

I expect the page to be loaded.

**To Reproduce**

I can't provide a github repo as it is a private project, but see below some relevant files that could help.

Relevant files that could help:

```js
// package.json

{
  "name": "---",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start -p $PORT"
  },
  "dependencies": {
    "@chakra-ui/react": "^1.3.3",
    "@emotion/react": "^11.1.5",
    "@emotion/styled": "^11.1.5",
    "easy-peasy": "^4.0.1",
    "emotion-theming": "^11.0.0",
    "firebase": "^8.2.7",
    "firebase-admin": "^9.5.0",
    "formik": "^2.2.6",
    "framer-motion": "^3.3.0",
    "next": "^10.0.7",
    "next-firebase-auth": "^0.13.0-alpha.0",
    "next-translate": "^1.0.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-firebaseui": "^4.1.0",
    "react-icons": "^4.2.0",
    "react-redux": "^7.2.2",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@types/node": "^14.14.27",
    "@types/react": "^17.0.2",
    "typescript": "^4.1.5"
  }
}
```
```js
// next.config.js

const nextTranslate = require('next-translate')

module.exports = nextTranslate()
```
```js
// .Dockerfile

# base image
FROM node:14.15.5-buster

# working directory
WORKDIR /app

# add binaries to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/
COPY yarn.lock /app/
RUN yarn install

# copy app files and build
COPY . /app
RUN yarn build

# start app
CMD [ "yarn", "start" ]
```

### LINKED ISSUE #31423: i18n: Next node server crashes when using a basePath in the URL with a string appended to it
### What version of Next.js are you using?

12.0.3, canary

### What version of Node.js are you using?

16.11.0

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

next start

### Describe the Bug

We noticed our server kept restarting, and found this in our logs:

```
/app/node_modules/next/dist/shared/lib/i18n/normalize-locale-path.js:11
        if (pathnameParts[1].toLowerCase() === locale.toLowerCase()) {
                             ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at /app/node_modules/next/dist/shared/lib/i18n/normalize-locale-path.js:11:30
    at Array.some (<anonymous>)
    at Object.normalizeLocalePath (/app/node_modules/next/dist/shared/lib/i18n/normalize-locale-path.js:10:21)
    at Object.getLocaleMetadata (/app/node_modules/next/dist/shared/lib/i18n/get-locale-metadata.js:14:44)
    at Object.parseNextUrl (/app/node_modules/next/dist/shared/lib/router/utils/parse-next-url.js:18:52)
    at Server.handleRequest (/app/node_modules/next/dist/server/next-server.js:202:40)
    at /app/node_modules/next/dist/server/next.js:52:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I checked the code used in the 'normalize-locale-path.js' file, and I see there is no check to see if `pathnameParts[1]` exists.
Current code: 
```
if (pathnameParts[1].toLowerCase() === locale.toLowerCase()) 
```
Possible fix code: 
```
if (pathnameParts[1] && pathnameParts[1].toLowerCase() === locale.toLowerCase()) 
```
Easy fix would be to add a check if `pathnameParts[1]` exists?

### Expected Behavior

I would expect a check if `pathnameParts[1]` exists, so this error doesn't occur, and the server doesn't crash.

### To Reproduce
https://codesandbox.io/s/crazy-pike-zx8vu?file=/next.config.js
Surf to http://localhost:3000/fr-be/pmeeee

We are using a basePath, and we are using the following i18n config:
```js
i18n: {
    defaultLocale: 'fr',
    locales: ['fr'],
},
```
When I start my server, and go to http://localhost:3000/fr-be/pmeee the error occurs.
I'm guessing because /fr-be/pme is detected in the URL, so it gets confused about the basepath/i18n routing?

### PR DESCRIPTION
**Pull request by styfle**
This fixes our `basePath` detection/replacing server-side as we were incorrectly considering `/docss` a match for a `basePath` of `/docs` which caused us to have an unexpected value in the `normalizeLocalePath` function. 

- Fixes #22429
- Regression introduced in #17757 
- Fixes: https://github.com/vercel/next.js/issues/31423

### CODE REVIEW

File: packages/next/shared/lib/i18n/normalize-locale-path.ts [hunk 1]
```diff
@@ -21,7 +21,10 @@ export function normalizeLocalePath(
   const pathnameParts = pathname.split('/')
 
   ;(locales || []).some((locale) => {
-    if (pathnameParts[1].toLowerCase() === locale.toLowerCase()) {
+    if (
+      pathnameParts[1] &&
```
Comment (ijjk) [inline packages/next/shared/lib/i18n/normalize-locale-path.ts:25]: Are you able to reproduce this? This might cause issues elsewhere in the server if the `pathname` is being passed as an empty string here. Splitting `/` should yield `[ '', '' ]` which is handled properly here

Comment (styfle) [reply packages/next/shared/lib/i18n/normalize-locale-path.ts:25]: It only happens if `pathname = ''` which might mean the issue is earlier

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| buildDuration | 24.1s | 23.7s | -320ms |
| buildDurationCached | 4.7s | 4.8s | ⚠️ +36ms |
| nodeModulesSize | 332 MB | 332 MB | ⚠️ +39 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.099 | 3.957 | -0.14 |
| / avg req/sec | 609.98 | 631.78 | +21.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.115 | 2.149 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1181.94 | 1163.27 | ⚠️ -18.67 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ⚠️ +5 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| index.html gzip | 523 B | 520 B | -3 B |
| link.html gzip | 535 B | 532 B | -3 B |
| withRouter.html gzip | 516 B | 514 B | -2 B |
| Overall change | 1.57 kB | 1.57 kB | -8 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -3612,7 +3612,10 @@
         // first item will be empty string from splitting at first char
         var pathnameParts = pathname.split("/");
         (locales || []).some(function(locale) {
-          if (pathnameParts[1].toLowerCase() === locale.toLowerCase()) {
+          if (
+            pathnameParts[1] &&
+            pathnameParts[1].toLowerCase() === locale.toLowerCase()
+          ) {
             detectedLocale = locale;
             pathnameParts.splice(1, 1);
             pathname = pathnameParts.join("/") || "/";
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-71494cc649b12162.js"
+      src="/_next/static/chunks/main-d86fe066c47f2722.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-71494cc649b12162.js"
+      src="/_next/static/chunks/main-d86fe066c47f2722.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-71494cc649b12162.js"
+      src="/_next/static/chunks/main-d86fe066c47f2722.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| buildDuration | 25.7s | 26.1s | ⚠️ +367ms |
| buildDurationCached | 4.7s | 4.7s | ⚠️ +24ms |
| nodeModulesSize | 332 MB | 332 MB | ⚠️ +39 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.964 | 3.958 | -0.01 |
| / avg req/sec | 630.62 | 631.57 | +0.95 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.152 | 2.193 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1161.5 | 1140.01 | ⚠️ -21.49 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ⚠️ +7 B |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 536 B | ⚠️ +1 B |
| withRouter.html gzip | 516 B | 517 B | ⚠️ +1 B |
| Overall change | 1.57 kB | 1.57 kB | ⚠️ +2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -3612,7 +3612,10 @@
         // first item will be empty string from splitting at first char
         var pathnameParts = pathname.split("/");
         (locales || []).some(function(locale) {
-          if (pathnameParts[1].toLowerCase() === locale.toLowerCase()) {
+          if (
+            pathnameParts[1] &&
+            pathnameParts[1].toLowerCase() === locale.toLowerCase()
+          ) {
             detectedLocale = locale;
             pathnameParts.splice(1, 1);
             pathname = pathnameParts.join("/") || "/";
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-71494cc649b12162.js"
+      src="/_next/static/chunks/main-d86fe066c47f2722.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-71494cc649b12162.js"
+      src="/_next/static/chunks/main-d86fe066c47f2722.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-71494cc649b12162.js"
+      src="/_next/static/chunks/main-d86fe066c47f2722.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 99824ad6525167c3fc984805d09bbdfcd7a198b6

File: packages/next/shared/lib/i18n/normalize-locale-path.ts (hunk 1 above)
Comment (ijjk) [reply packages/next/shared/lib/i18n/normalize-locale-path.ts:25]: Looks like we got a test case in https://github.com/vercel/next.js/issues/31423 so added that in and fixed the original error it uncovered.

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| buildDuration | 25.6s | 25.1s | -541ms |
| buildDurationCached | 4.9s | 4.7s | -231ms |
| nodeModulesSize | 335 MB | 335 MB | ⚠️ +1.15 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.315 | 4.334 | ⚠️ +0.02 |
| / avg req/sec | 579.4 | 576.89 | ⚠️ -2.51 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.247 | 2.354 | ⚠️ +0.11 |
| /error-in-render avg req/sec | 1112.46 | 1062.06 | ⚠️ -50.4 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ⚠️ +6 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| index.html gzip | 521 B | 523 B | ⚠️ +2 B |
| link.html gzip | 534 B | 536 B | ⚠️ +2 B |
| withRouter.html gzip | 515 B | 517 B | ⚠️ +2 B |
| Overall change | 1.57 kB | 1.58 kB | ⚠️ +6 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -3703,7 +3703,10 @@
         // first item will be empty string from splitting at first char
         var pathnameParts = pathname.split("/");
         (locales || []).some(function(locale) {
-          if (pathnameParts[1].toLowerCase() === locale.toLowerCase()) {
+          if (
+            pathnameParts[1] &&
+            pathnameParts[1].toLowerCase() === locale.toLowerCase()
+          ) {
             detectedLocale = locale;
             pathnameParts.splice(1, 1);
             pathname = pathnameParts.join("/") || "/";
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-9e7b6529420042b3.js"
+      src="/_next/static/chunks/main-7d9df3f169873f18.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-9e7b6529420042b3.js"
+      src="/_next/static/chunks/main-7d9df3f169873f18.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-9e7b6529420042b3.js"
+      src="/_next/static/chunks/main-7d9df3f169873f18.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| buildDuration | 27.1s | 27.2s | ⚠️ +118ms |
| buildDurationCached | 4.8s | 4.7s | -79ms |
| nodeModulesSize | 335 MB | 335 MB | ⚠️ +1.15 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.191 | 4.381 | ⚠️ +0.19 |
| / avg req/sec | 596.46 | 570.69 | ⚠️ -25.77 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.307 | 2.242 | -0.06 |
| /error-in-render avg req/sec | 1083.78 | 1114.94 | +31.16 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.5 kB | 28.6 kB | ⚠️ +4 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-pathnameparts-undefined | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -3703,7 +3703,10 @@
         // first item will be empty string from splitting at first char
         var pathnameParts = pathname.split("/");
         (locales || []).some(function(locale) {
-          if (pathnameParts[1].toLowerCase() === locale.toLowerCase()) {
+          if (
+            pathnameParts[1] &&
+            pathnameParts[1].toLowerCase() === locale.toLowerCase()
+          ) {
             detectedLocale = locale;
             pathnameParts.splice(1, 1);
             pathname = pathnameParts.join("/") || "/";
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-9e7b6529420042b3.js"
+      src="/_next/static/chunks/main-7d9df3f169873f18.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-9e7b6529420042b3.js"
+      src="/_next/static/chunks/main-7d9df3f169873f18.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-9e7b6529420042b3.js"
+      src="/_next/static/chunks/main-7d9df3f169873f18.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: ed9de3e9698fc8de48d77d957d876003cfca5547

File: test/integration/i18n-support/test/shared.js [hunk 2]
```diff
@@ -35,6 +35,27 @@ async function addDefaultLocaleCookie(browser) {
 }
 
 export function runTests(ctx) {
+  if (ctx.basePath) {
+    it.only('should handle basePath like pathname', async () => {
```
Comment (styfle) [inline test/integration/i18n-support/test/shared.js:39]: Let's use `it()` instead so it doesn't skip all the test

Comment (ijjk) [reply test/integration/i18n-support/test/shared.js:39]: Updated in https://github.com/vercel/next.js/pull/31456
