### PR TITLE
fix: fixes cookie override during redirection from server action

### LINKED ISSUE #61611: Cookies in POST response from server action + redirect() are overridden by streamed GET response cookies
### Link to the code that reproduces this issue

https://github.com/technikhil314/nextjs-parallel-routes-sample/tree/chore/steaming-cookie-issue?expand=1

### To Reproduce

1. Clone the repo `git clone -b chore/steaming-cookie-issue git@github.com:technikhil314/nextjs-parallel-routes-sample.git`
2. run `npm ci`
3. run `npm run dev`
4. open `http://localhost:3000`
5. click on `Redirect me to /route1` button
6. Observe that on redirection [the cookie set in server action](https://github.com/technikhil314/nextjs-parallel-routes-sample/blob/chore/steaming-cookie-issue/src/app/page.tsx#L6) does not get dropped on browser

### Current vs. Expected behavior

*Expected Result*
After sucessful redirection with streaming both cookies should be dropped on browser

*Actual Result*
Only one of the cookie gets dropped on browser (more explanation in demo example)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.10
  pnpm: 7.17.0
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Other (Deployed)

### Additional context

This is possible only in custom server setup based on top of self created express app and/or as per nextjs docs as well

### PR DESCRIPTION
**Pull request by technikhil314**
### What?
Fixes #61611

### Why?
Any one having custom server may be having logic to set cookies during GET requests too. Currently nextjs in app directory does not allow to do so but with custom server its very much possible.

### How?
By merging cookies of redirect response and server action POSt response

### Tests
I have added one more test to existing suite and it passing with fix in place.
image

### Notes
This bug is reproducible only if developer has custom server on top of next app but still very probable

### CODE REVIEW

File: packages/next/src/server/app-render/action-handler.ts [hunk 1]
```diff
@@ -216,22 +216,38 @@ async function createRedirectRenderResult(
...
         })
+        //copy cookies from the redirect response to respose we're sending before copying other headers
+        //this is needed only in case of custom server created by developer
+        //cause nextjs app dir does not allow to set cookies from components
+        const redirectResponseCookies = new ResponseCookies(
+          redirectResponse.headers
+        )
+        const responseCookies = new ResponseCookies(
+          fromNodeOutgoingHttpHeaders(res.getHeaders())
+        )
```
Comment (shuding) [inline packages/next/src/server/app-render/action-handler.ts:235]: It doesn't seem like `responseCookies` is getting used?

Comment (technikhil314) [reply packages/next/src/server/app-render/action-handler.ts:235]: No its getting used on line 238 and 240. And `res` is the final response that browser receives as response to server action + redirect invocation hence have to carry those cookies from redirectResponse to response.

Comment (shuding) [reply packages/next/src/server/app-render/action-handler.ts:235]: I saw that it's mutated (`.delete` and `.set`) on these 2 lines, but `responseCookies` itself is never get used/returned?

Comment (technikhil314) [reply packages/next/src/server/app-render/action-handler.ts:235]: Understood. we used to copy cookie header as a whole before as per [this line](https://github.com/vercel/next.js/pull/61633/files#diff-c809d50461027cdba7c092e564818b1172133d337abc5c513f829c94c8483dc6L230) but it overrides cookie header fully instead of merging cookies. Hence I made this change to merge cookies. 

While your question is valid that responseCookies does not seem to be used but those are cookies from `res`. and this `res` is getting in turn returned to browser via [this line](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/app-render/app-render.tsx#L1318) eventually dropping the merged cookies on browser.

**Review by gggneo — APPROVED** [review]
Noted

**Comment by technikhil314** [comment]
@gggneo I see you have approved the PR and thank you for that. Please let me know if I am missing anything. Cause I dont see merge button enabled yet.

**Review by shuding — APPROVED** [review]

**Comment by technikhil314** [comment]
@shuding Thanks a lot for approval but I see the merge button is still disabled for me. Let me know if I am missing any steps.

**Comment by OlegLustenko** [comment]
Hi team, we are implementing some auth flow that will be simplified a lot with these changes.

We are currently working around it via returning cookies to a client and then shooting another request and then redirect.

Can attract some attention to this, maybe @ztanner ?

I saw you fixed a bunch of things in recent months, could you take your eyes on it please?

🙏🏻🙏🏻

**Review by ijjk — APPROVED** [review]
