### PR TITLE
fix: Narrow down from `string | undefined` to `string`

### LINKED ISSUE #64832: Empty `NEXT_PUBLIC_*` environment variables are evaluated as `undefined` rather than as empty strings
### Link to the code that reproduces this issue

https://github.com/bryan-hoang/repro-undefined-next-public-env-vars

### To Reproduce

1. Run `pnpm exec next dev`
2. Observe that the website is displaying `process.env.NEXT_PUBLIC_FOO: undefined`.

### Current vs. Expected behavior

I expected `process.env.NEXT_PUBLIC_FOO: ` to be displayed instead, since the `.env` file contains `NEXT_PUBLIC_FOO=`. The environment variable is defined as an empty string, but it's not being evaluated as one.

I find it surprising that environment variables that are defined as empty strings be treated as undefined.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2
  Available memory (MB): 773973
  Available CPU cores: 48
Binaries:
  Node: 21.7.3
  npm: 10.5.2
  Yarn: N/A
  pnpm: 9.0.4
Relevant Packages:
  next: 14.3.0-canary.13 // Latest available version is detected (14.3.0-canary.13).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Output (export/standalone), Pages Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

It looks like this issue was first introduced in `next@14.2.0-canary-14`, as reverting to `next@14.2.0-canary-13` fixes the issue.

After looking at the commits between those canary versions, I think the commit that introduced the issue is 76c9496027a47ded72fb78baee628b9121f447c1. Specifically, this part of the diff: https://github.com/vercel/next.js/commit/76c9496027a47ded72fb78baee628b9121f447c1#diff-28c0329619b90836564a7769c43ff473dbd28e8e31b75e650624da4d06911763R68. 

Since empty strings are falsey, the environment variable doesn't end up being set.

The same guard against falsey values is present on the current canary version as of writing this.

### PR DESCRIPTION
**Pull request by icyJoseph**
### What?

Fixes #64832 

Having empty strings in `.env`, and family of files, causes the variable to be assigned to `undefined`, rather than an empty string.

### Why?

The issue breaks behavior between canaries

### How?

The value read from `process.env[key]`, is `string | undefined`, and we need to narrow down to `string`, but the current check also filters out `''`. A quick way to fix that is to `value != null` ~

Fixes #64832

~Not sure if there's anywhere, where this is tested in the codebase~

- [x] Test that empty value strings are consistent before and after hydration

The root issue here is that the value before hydration is `''`, but during hydration `undefined` is used, and using something like, template string interpolations, `${NEXT_PUBLIC_EMPTY_ENV_VAR}`,  would cause a hydration error. That's what is happening in #64832. For clarity's sake, the error would be that the HTML contained an empty string, but hydration has `"undefined"` string cast.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 40f3075ef77955e0caa0c83141fb54d233ce6643

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by eps1lon — CHANGES_REQUESTED** [review]
Thank you. Please add a test here: test/integration/env-config/test/index.test.js

Ideally split the PR in two commits: one commit with just the test asserting the current behavior and another commit with the fix+updated test assertions.

**Comment by icyJoseph** [comment]
> Thank you. Please add a test here: test/integration/env-config/test/index.test.js
> 
> Ideally split the PR in two commits: one commit with just the test asserting the current behavior and another commit with the fix+updated test assertions.

Yeah I tried to first write a test, but I failed to find that file, but made the fix anyway. Thanks for that! I'll work on a test to prevent further regressions.

**Comment by icyJoseph** [comment]
While setting up a test, I also got to understand the bug a bit better. The problem is that even though the HTML source has the expected "empty string", it is during hydration, that it is getting replaced by `undefined` ~ I will continue investigating tomorrow.

File: test/integration/env-config/app/pages/index.js [hunk 1]
```diff
@@ -25,13 +25,14 @@ const variables = [
...
   'NEXT_PUBLIC_HELLO_WORLD',
+  'NEXT_PUBLIC_EMPTY_ENV_VAR',
 ]
 
 export async function getStaticProps() {
   const items = {}
 
   variables.forEach((variable) => {
-    if (process.env[variable]) {
+    if (typeof process.env[variable] !== 'undefined') {
```
Comment (icyJoseph) [inline test/integration/env-config/app/pages/index.js:35]: the other test pages on this integration suite, do the very same check

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 744b5301e8b0440bbec3ca72b5944a97e161f435

`pnpm test-dev test/e2e/cancel-request/stream-cancel.test.ts`
- streaming responses cancel inner stream after disconnect > edge app route handler > cancels stream that never sent data

<details>
<summary>Expand output</summary>

  ● streaming responses cancel inner stream after disconnect › edge app route handler › cancels stream that never sent data

    thrown: "Exceeded timeout of 2500 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      74 |     }, 2500)
      75 |
    > 76 |     it('cancels stream that never sent data', async () => {
         |     ^
      77 |       // If the client has never sent any data (including headers), then we
      78 |       // haven't even established the response object yet.
      79 |       await prime(path + '?write=0', true)

      at it (e2e/cancel-request/stream-cancel.test.ts:76:5)
          at Array.forEach (<anonymous>)
      at e2e/cancel-request/stream-cancel.test.ts:57:4
      at Object.describe (e2e/cancel-request/stream-cancel.test.ts:5:1)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/empty_NEXT_PUBLIC_env_vars | Change |
| - | - | - | - |
| buildDuration | 17.6s | 16s | N/A |
| buildDurationCached | 9.4s | 7.8s | N/A |
| nodeModulesSize | 360 MB | 360 MB | ⚠️ +176 B |
| nextStartRea..uration (ms) | 441ms | 438ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/empty_NEXT_PUBLIC_env_vars | Change |
| - | - | - | - |
| 1103-HASH.js gzip | 31.9 kB | 31.9 kB | N/A |
| 1a9f679d-HASH.js gzip | 53.5 kB | 53.5 kB | N/A |
| 335-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| 7953.HASH.js gzip | 169 B | 169 B | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 230 B | 228 B | N/A |
| main-HASH.js gzip | 31.6 kB | 31.6 kB | N/A |
| webpack-HASH.js gzip | 1.65 kB | 1.65 kB | N/A |
| Overall change | 50.4 kB | 50.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/empty_NEXT_PUBLIC_env_vars | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/empty_NEXT_PUBLIC_env_vars | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 193 B | N/A |
| _error-HASH.js gzip | 192 B | 193 B | N/A |
| amp-HASH.js gzip | 507 B | 511 B | N/A |
| css-HASH.js gzip | 341 B | 343 B | N/A |
| dynamic-HASH.js gzip | 2.52 kB | 2.52 kB | ✓ |
| edge-ssr-HASH.js gzip | 266 B | 265 B | N/A |
| head-HASH.js gzip | 362 B | 365 B | N/A |
| hooks-HASH.js gzip | 392 B | 392 B | ✓ |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | ✓ |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.69 kB | 2.7 kB | N/A |
| routerDirect..HASH.js gzip | 329 B | 328 B | N/A |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 324 B | 324 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 8.27 kB | 8.27 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/empty_NEXT_PUBLIC_env_vars | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/empty_NEXT_PUBLIC_env_vars | Change |
| - | - | - | - |
| index.html gzip | 527 B | 526 B | N/A |
| link.html gzip | 540 B | 538 B | N/A |
| withRouter.html gzip | 522 B | 521 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/empty_NEXT_PUBLIC_env_vars | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94.7 kB | 94.7 kB | N/A |
| page.js gzip | 182 kB | 182 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/empty_NEXT_PUBLIC_env_vars | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 623 B | 622 B | N/A |
| middleware-r..fest.js gzip | 156 B | 156 B | ✓ |
| middleware.js gzip | 25.7 kB | 25.7 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 995 B | 995 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/empty_NEXT_PUBLIC_env_vars | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | ✓ |
| app-page-exp..prod.js gzip | 98.7 kB | 98.7 kB | ✓ |
| app-page-tur..prod.js gzip | 100 kB | 100 kB | ✓ |
| app-page-tur..prod.js gzip | 94.5 kB | 94.5 kB | ✓ |
| app-page.run...dev.js gzip | 157 kB | 157 kB | ✓ |
| app-page.run..prod.js gzip | 93.2 kB | 93.2 kB | ✓ |
| app-route-ex...dev.js gzip | 21.5 kB | 21.5 kB | ✓ |
| app-route-ex..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 15 kB | 15 kB | ✓ |
| app-route.ru...dev.js gzip | 21.3 kB | 21.3 kB | ✓ |
| app-route.ru..prod.js gzip | 15 kB | 15 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 21.5 kB | 21.5 kB | ✓ |
| pages.runtim...dev.js gzip | 22.1 kB | 22.1 kB | ✓ |
| pages.runtim..prod.js gzip | 21.5 kB | 21.5 kB | ✓ |
| server.runti..prod.js gzip | 51.6 kB | 51.6 kB | ✓ |
| Overall change | 963 kB | 963 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/empty_NEXT_PUBLIC_env_vars | Change |
| - | - | - | - |
| 0.pack gzip | 1.62 MB | 1.62 MB | ⚠️ +678 B |
| index.pack gzip | 114 kB | 114 kB | N/A |
| Overall change | 1.62 MB | 1.62 MB | ⚠️ +678 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: a8b4075bc932f450e752d467445dd8bfc8ce7777

**Review by timlindsk — APPROVED** [review]

File: packages/next/src/build/webpack/plugins/define-env-plugin.ts [hunk 2]
```diff
@@ -63,7 +63,7 @@ function getNextPublicEnvironmentVariables(): DefineEnv {
   for (const key in process.env) {
     if (key.startsWith('NEXT_PUBLIC_')) {
       const value = process.env[key]
-      if (value) {
+      if (value != null) {
         defineEnv[`process.env.${key}`] = value
       }
```
Comment (devjiwonchoi) [inline packages/next/src/build/webpack/plugins/define-env-plugin.ts:68]:
```suggestion
      defineEnv[`process.env.${key}`] = process.env[key] ?? ''
```

Since the value is either string or undefined, how about nullish coalescing?

**Comment by omerman** [comment]
Is this going to be merges any time soon?

File: packages/next/src/build/webpack/plugins/define-env-plugin.ts [hunk 3]
```diff
@@ -63,7 +63,7 @@ function getNextPublicEnvironmentVariables(): DefineEnv {
   for (const key in process.env) {
     if (key.startsWith('NEXT_PUBLIC_')) {
       const value = process.env[key]
-      if (value) {
+      if (value != null) {
```
Comment (devjiwonchoi) [inline packages/next/src/build/webpack/plugins/define-env-plugin.ts:66]:
```suggestion
      if (typeof value === 'string') {
```

Why don't we check if is string? It'd be `''` right?

File: packages/next/src/build/webpack/plugins/define-env-plugin.ts [hunk 4]
```diff
@@ -80,7 +80,7 @@ function getNextConfigEnv(config: NextConfigComplete): DefineEnv {
   const env = config.env
   for (const key in env) {
     const value = env[key]
-    if (value) {
+    if (value != null) {
```
Comment (devjiwonchoi) [inline packages/next/src/build/webpack/plugins/define-env-plugin.ts:83]:
```suggestion
    if (typeof value === 'string') {
```

This as well!

File: packages/next/src/build/webpack/plugins/define-env-plugin.ts (hunk 3 above)
Comment (icyJoseph) [reply packages/next/src/build/webpack/plugins/define-env-plugin.ts:66]: Yeah, it is a noop

**Review by devjiwonchoi — APPROVED** [review]

**Review by eps1lon — APPROVED** [review]
Thank you. Test breaks without the runtime changes 👍🏻
