### PR TITLE
Fix `next/script` unhandled promise rejection

### LINKED ISSUE #27747: next/script creates unhandled promise rejection with empty error for every script that fails to load
### What version of Next.js are you using?

11

### What version of Node.js are you using?

12.14.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Loading any script which fails to load generates an unhandled rejection error "Uncaught (in promise) undefined"

This is due to this code

https://github.com/vercel/next.js/blob/canary/packages/next/client/script.tsx#L58
```
const loadPromise = new Promise<void>((resolve, reject) => {
    el.addEventListener('load', function () {
      resolve()
      if (onLoad) {
        onLoad.call(this)
      }
    })
    el.addEventListener('error', function () {
      reject()
      if (onError) {
        onError()
      }
    })
  })
```

reject is called but loadPromise never has an error handler attached unless you create two tags for the same script which will do `ScriptCache.get(src).then(onLoad, onError)`

### Expected Behavior

No unhandled rejection error for errors and pass the real error to the onError

### To Reproduce

```
<Script
        src="https://somebrokenlink.doesntexist"
        strategy="lazyOnload"
        onLoad={() => {
          console.log('success');
        }}
        onLoad={(e) => {
          console.log('error');
          console.log(e); // this doesn't exist either
        }}
      />
```

### PR DESCRIPTION
**Pull request by janicklas-ralph**
## Bug

- [x] fixes #27747
- [x] Integration tests added

### CODE REVIEW

File: test/integration/script-loader/pages/page3.js [hunk 1]
```diff
@@ -15,6 +15,14 @@ const Page = () => {
         src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.20/lodash.min.js?a=scriptLazyOnload"
         strategy="lazyOnload"
       ></Script>
+      <Script
+        src="https://somebrokenlink.doesntexist"
```
Comment (styfle) [inline test/integration/script-loader/pages/page3.js:19]:
```suggestion
        src="https://example.com/doesntexist"
```

**Review by housseindjirdeh — DISMISSED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| buildDuration | 18.2s | 17.8s | -315ms |
| buildDurationCached | 4s | 4s | ⚠️ +5ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ⚠️ +165 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.344 | 3.398 | ⚠️ +0.05 |
| / avg req/sec | 747.7 | 735.67 | ⚠️ -12.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.112 | 2.081 | -0.03 |
| /error-in-render avg req/sec | 1183.71 | 1201.39 | +17.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.1 kB | 23.1 kB | ⚠️ +6 B |
| webpack-HASH.js gzip | 1.5 kB | 1.5 kB | ✓ |
| Overall change | 67 kB | 67 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _app-HASH.js gzip | 980 B | 980 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.52 kB | 2.52 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 904 B | 904 B | ✓ |
| image-HASH.js gzip | 4.12 kB | 4.12 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 12.8 kB | 12.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _buildManifest.js gzip | 490 B | 490 B | ✓ |
| Overall change | 490 B | 490 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| index.html gzip | 532 B | 531 B | -1 B |
| link.html gzip | 543 B | 544 B | ⚠️ +1 B |
| withRouter.html gzip | 523 B | 523 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -3250,20 +3250,20 @@
 
         var el = document.createElement("script");
         var loadPromise = new Promise(function(resolve, reject) {
-          el.addEventListener("load", function() {
+          el.addEventListener("load", function(e) {
             resolve();
 
             if (onLoad) {
-              onLoad.call(this);
+              onLoad.call(this, e);
             }
           });
-          el.addEventListener("error", function() {
-            reject();
-
-            if (onError) {
-              onError();
-            }
+          el.addEventListener("error", function(e) {
+            reject(e);
           });
+        })["catch"](function(e) {
+          if (onError) {
+            onError(e);
+          }
         });
 
         if (src) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-93972797ff4e7b271197.js"
+      src="/_next/static/chunks/main-bfac2c856fac944512ab.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-93972797ff4e7b271197.js"
+      src="/_next/static/chunks/main-bfac2c856fac944512ab.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-93972797ff4e7b271197.js"
+      src="/_next/static/chunks/main-bfac2c856fac944512ab.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| buildDuration | 14.8s | 15s | ⚠️ +243ms |
| buildDurationCached | 5.8s | 5.7s | -126ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ⚠️ +165 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.237 | 3.253 | ⚠️ +0.02 |
| / avg req/sec | 772.33 | 768.57 | ⚠️ -3.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.08 | 2.057 | -0.02 |
| /error-in-render avg req/sec | 1201.95 | 1215.11 | +13.16 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| 17.HASH.js gzip | 185 B | 185 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14 kB | 14 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.6 kB | 10.6 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 67.8 kB | 67.9 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _app-HASH.js gzip | 965 B | 965 B | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.71 kB | 2.71 kB | ✓ |
| head-HASH.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 2.94 kB | 2.95 kB | ⚠️ +9 B |
| withRouter-HASH.js gzip | 294 B | 294 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 17.7 kB | 17.7 kB | ⚠️ +9 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _buildManifest.js gzip | 498 B | 498 B | ✓ |
| Overall change | 498 B | 498 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| index.html gzip | 577 B | 577 B | ✓ |
| link.html gzip | 590 B | 589 B | -1 B |
| withRouter.html gzip | 570 B | 570 B | ✓ |
| Overall change | 1.74 kB | 1.74 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -21,7 +21,7 @@ self.__BUILD_MANIFEST = {
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-6969fe7df87ea0f513b7.js"
   ],
   "/script": [
-    "static\u002Fchunks\u002Fpages\u002Fscript-72fdd0aacc5133678fb0.js"
+    "static\u002Fchunks\u002Fpages\u002Fscript-4f37d5d753427e16b66e.js"
   ],
   "/withRouter": [
     "static\u002Fchunks\u002Fpages\u002FwithRouter-d324ed0c40e148c2c3fc.js"
```
</details>
<details>
<summary>Diff for <strong>script-HASH.js</strong></summary>

```diff
@@ -166,20 +166,20 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
         var el = document.createElement("script");
         var loadPromise = new Promise(function(resolve, reject) {
-          el.addEventListener("load", function() {
+          el.addEventListener("load", function(e) {
             resolve();
 
             if (onLoad) {
-              onLoad.call(this);
+              onLoad.call(this, e);
             }
           });
-          el.addEventListener("error", function() {
-            reject();
-
-            if (onError) {
-              onError();
-            }
+          el.addEventListener("error", function(e) {
+            reject(e);
           });
+        })["catch"](function(e) {
+          if (onError) {
+            onError(e);
+          }
         });
 
         if (src) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -748,20 +748,20 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
         var el = document.createElement("script");
         var loadPromise = new Promise(function(resolve, reject) {
-          el.addEventListener("load", function() {
+          el.addEventListener("load", function(e) {
             resolve();
 
             if (onLoad) {
-              onLoad.call(this);
+              onLoad.call(this, e);
             }
           });
-          el.addEventListener("error", function() {
-            reject();
-
-            if (onError) {
-              onError();
-            }
+          el.addEventListener("error", function(e) {
+            reject(e);
           });
+        })["catch"](function(e) {
+          if (onError) {
+            onError(e);
+          }
         });
 
         if (src) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -23,7 +23,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-12dc0b93eed90c767139.js"
+      src="/_next/static/chunks/main-a81f837869d1a2a9b638.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -23,7 +23,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-12dc0b93eed90c767139.js"
+      src="/_next/static/chunks/main-a81f837869d1a2a9b638.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -23,7 +23,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-12dc0b93eed90c767139.js"
+      src="/_next/static/chunks/main-a81f837869d1a2a9b638.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 1c77210f048669b07855d48b861275f04cad9681

**Review by ijjk — APPROVED** [review]
