### PR TITLE
Prevent CSS script tags in granular chunks

### LINKED ISSUE #9302: Issues with Granular chunking on client side navigation
# Bug report

## Describe the bug

We are currently still experiencing issues with the experimental granular chunking on the latest next.js version. On client side navigation the page specific css is then loaded twice which causes problems with styles on our side.  

The css is once loaded correctly as style tag and once with a script tag. I went trough the next.js sourcode to see if i could pinpoint the issue somehow and i am pretty sure it is related to this bit of code https://github.com/zeit/next.js/blob/8dd394a05586741fe613bb6ba330539e75f53fcf/packages/next/client/page-loader.js#L126 , since the wrongly used script tag for the css file is apended at the end of the document body and it is without the async or defer attribute unlike the scripts in the _document

## To Reproduce

i will try and see if i can put together an example repo later as i would have strip out almost anything from our project to be allowed to post it.

## Expected behavior

I would expect the css to only added once to the dom via a style tag

## System information

- OS: macOs
- Version of Next.js: 9.1.3-canary.1

### PR DESCRIPTION
**Pull request by atcastle**
This prevents page-loader.js from inserting script tags for CSS dependencies with granualr chunks enabled. This fixes https://github.com/zeit/next.js/issues/9302

### CODE REVIEW

File: packages/next/client/page-loader.js [hunk 1]
```diff
@@ -98,7 +98,7 @@ export default class PageLoader {
         if (process.env.__NEXT_GRANULAR_CHUNKS) {
           this.getDependencies(route).then(deps => {
             deps.forEach(d => {
-              if (!document.querySelector(`script[src^="${d}"]`)) {
+              if (!/\.css$/.test(d) && !document.querySelector(`script[src^="${d}"]`)) {
```
Comment (Timer) [inline packages/next/client/page-loader.js]: Would it be better to test that it ends with `.js`? Users can customize their webpack config to emit all sorts of things...

**Review by Timer — CHANGES_REQUESTED** [review]

File: packages/next/client/page-loader.js (hunk 1 above)
Comment (atcastle) [reply packages/next/client/page-loader.js]: Right now the build-manifest-plugin filters out everything except css and JS from the client side manifest, but sure--I'm fine making that change for future-proofing.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| buildDuration | 14.3s | 14.7s | ⚠️ +427ms |
| nodeModulesSize | 48.5 MB | 48.5 MB | ⚠️ +40 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ⚠️ +18 B |
| main-HASH.js gzip | 5.87 kB | 5.88 kB | ⚠️ +14 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..7459734ec.js | 20.1 kB | 20.1 kB | ✓ |
| 16b1a7225520..34ec.js gzip | 7.38 kB | 7.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..254ddadd9.js | 28.7 kB | 28.7 kB | ✓ |
| de003c3a9d30..add9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ⚠️ +18 B |
| main-HASH.module.js gzip | 5.29 kB | 5.3 kB | ⚠️ +14 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0d.module.js | 16.2 kB | 16.2 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.2 kB | 20.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.03 kB | 1.04 kB | ⚠️ +3 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.11 kB | 1.12 kB | ⚠️ +2 B |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.1 kB | ⚠️ +1 B |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1347,7 +1347,7 @@ function () {
           if (true) {
             _this3.getDependencies(route).then(function (deps) {
               deps.forEach(function (d) {
-                if (!document.querySelector("script[src^=\"" + d + "\"]")) {
+                if (!/\.css$/.test(d) && !document.querySelector("script[src^=\"" + d + "\"]")) {
                   _this3.loadScript(d, route, false);
                 }
               });
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1177,7 +1177,7 @@ class PageLoader {
         if (true) {
           this.getDependencies(route).then(deps => {
             deps.forEach(d => {
-              if (!document.querySelector("script[src^=\"" + d + "\"]")) {
+              if (!/\.css$/.test(d) && !document.querySelector("script[src^=\"" + d + "\"]")) {
                 this.loadScript(d, route, false);
               }
             });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,7 +12,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-97cefed373c10c800b7f.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
@@ -44,9 +44,9 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-108e86883c2fd794bd5c.js"
+        <script src="/_next/static/runtime/main-b83585a6be4a41f32b2d.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
+        <script src="/_next/static/runtime/main-97cefed373c10c800b7f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/chunks/framework.219514909c9db8a9ff76.js"
         async="" crossorigin="anonymous" nomodule=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -20,7 +20,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/16b1a72255206b7853bf6603dc58ec83de39b142.13a61a2410d3fe9a0cb1.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-97cefed373c10c800b7f.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -67,9 +67,9 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/16b1a72255206b7853bf6603dc58ec83de39b142.13a61a2410d3fe9a0cb1.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-108e86883c2fd794bd5c.js"
+        <script src="/_next/static/runtime/main-b83585a6be4a41f32b2d.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
+        <script src="/_next/static/runtime/main-97cefed373c10c800b7f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
         crossorigin="anonymous" nomodule=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -20,7 +20,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/16b1a72255206b7853bf6603dc58ec83de39b142.13a61a2410d3fe9a0cb1.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-97cefed373c10c800b7f.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -65,9 +65,9 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/16b1a72255206b7853bf6603dc58ec83de39b142.13a61a2410d3fe9a0cb1.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-108e86883c2fd794bd5c.js"
+        <script src="/_next/static/runtime/main-b83585a6be4a41f32b2d.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
+        <script src="/_next/static/runtime/main-97cefed373c10c800b7f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
         crossorigin="anonymous" nomodule=""></script>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| buildDuration | 14.8s | 14.8s | ⚠️ +7ms |
| nodeModulesSize | 48.5 MB | 48.5 MB | ⚠️ +40 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ⚠️ +18 B |
| main-HASH.js gzip | 5.87 kB | 5.88 kB | ⚠️ +14 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..7459734ec.js | 20.1 kB | 20.1 kB | ✓ |
| 16b1a7225520..34ec.js gzip | 7.38 kB | 7.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..254ddadd9.js | 28.7 kB | 28.7 kB | ✓ |
| de003c3a9d30..add9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ⚠️ +18 B |
| main-HASH.module.js gzip | 5.29 kB | 5.3 kB | ⚠️ +14 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0d.module.js | 16.2 kB | 16.2 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.2 kB | 20.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _error.js | 248 kB | 248 kB | ✓ |
| _error.js gzip | 65.6 kB | 65.6 kB | ⚠️ +1 B |
| hooks.html | 4.19 kB | 4.19 kB | ✓ |
| hooks.html gzip | 1.07 kB | 1.07 kB | ⚠️ +2 B |
| index.js | 248 kB | 248 kB | ✓ |
| index.js gzip | 65.8 kB | 65.8 kB | ✓ |
| link.js | 280 kB | 280 kB | ✓ |
| link.js gzip | 74.7 kB | 74.7 kB | ⚠️ +1 B |
| routerDirect.js | 273 kB | 273 kB | ✓ |
| routerDirect.js gzip | 72.8 kB | 72.8 kB | ⚠️ +1 B |
| withRouter.js | 273 kB | 273 kB | ✓ |
| withRouter.js gzip | 72.9 kB | 72.9 kB | ⚠️ +1 B |
| Overall change | 1.33 MB | 1.33 MB | ✓ |

</details>

</details>


Commit: f92076b292fe2ac7b1f6051d4a4c4a65c4360546

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| buildDuration | 14s | 14.3s | ⚠️ +249ms |
| nodeModulesSize | 48.5 MB | 48.5 MB | ⚠️ +36 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ⚠️ +18 B |
| main-HASH.js gzip | 5.87 kB | 5.89 kB | ⚠️ +16 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..7459734ec.js | 20.1 kB | 20.1 kB | ✓ |
| 16b1a7225520..34ec.js gzip | 7.38 kB | 7.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..254ddadd9.js | 28.7 kB | 28.7 kB | ✓ |
| de003c3a9d30..add9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ⚠️ +18 B |
| main-HASH.module.js gzip | 5.29 kB | 5.31 kB | ⚠️ +16 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0d.module.js | 16.2 kB | 16.2 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.2 kB | 20.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.03 kB | 1.03 kB | ⚠️ +2 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.11 kB | 1.11 kB | ✓ |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.1 kB | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1347,7 +1347,7 @@ function () {
           if (true) {
             _this3.getDependencies(route).then(function (deps) {
               deps.forEach(function (d) {
-                if (!document.querySelector("script[src^=\"" + d + "\"]")) {
+                if (/\.js$/.test(d) && !document.querySelector("script[src^=\"" + d + "\"]")) {
                   _this3.loadScript(d, route, false);
                 }
               });
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1177,7 +1177,7 @@ class PageLoader {
         if (true) {
           this.getDependencies(route).then(deps => {
             deps.forEach(d => {
-              if (!document.querySelector("script[src^=\"" + d + "\"]")) {
+              if (/\.js$/.test(d) && !document.querySelector("script[src^=\"" + d + "\"]")) {
                 this.loadScript(d, route, false);
               }
             });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,7 +12,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-15cb5dadee4f0afb723f.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
@@ -44,9 +44,9 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-108e86883c2fd794bd5c.js"
+        <script src="/_next/static/runtime/main-020b2ad683e68ed1ee2f.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
+        <script src="/_next/static/runtime/main-15cb5dadee4f0afb723f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/chunks/framework.219514909c9db8a9ff76.js"
         async="" crossorigin="anonymous" nomodule=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -20,7 +20,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/16b1a72255206b7853bf6603dc58ec83de39b142.13a61a2410d3fe9a0cb1.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-15cb5dadee4f0afb723f.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -67,9 +67,9 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/16b1a72255206b7853bf6603dc58ec83de39b142.13a61a2410d3fe9a0cb1.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-108e86883c2fd794bd5c.js"
+        <script src="/_next/static/runtime/main-020b2ad683e68ed1ee2f.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
+        <script src="/_next/static/runtime/main-15cb5dadee4f0afb723f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
         crossorigin="anonymous" nomodule=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -20,7 +20,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/16b1a72255206b7853bf6603dc58ec83de39b142.13a61a2410d3fe9a0cb1.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-15cb5dadee4f0afb723f.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -65,9 +65,9 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/16b1a72255206b7853bf6603dc58ec83de39b142.13a61a2410d3fe9a0cb1.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-108e86883c2fd794bd5c.js"
+        <script src="/_next/static/runtime/main-020b2ad683e68ed1ee2f.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
+        <script src="/_next/static/runtime/main-15cb5dadee4f0afb723f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
         crossorigin="anonymous" nomodule=""></script>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| buildDuration | 14.8s | 14.5s | -338ms |
| nodeModulesSize | 48.5 MB | 48.5 MB | ⚠️ +36 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ⚠️ +18 B |
| main-HASH.js gzip | 5.87 kB | 5.89 kB | ⚠️ +16 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..7459734ec.js | 20.1 kB | 20.1 kB | ✓ |
| 16b1a7225520..34ec.js gzip | 7.38 kB | 7.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..254ddadd9.js | 28.7 kB | 28.7 kB | ✓ |
| de003c3a9d30..add9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ⚠️ +18 B |
| main-HASH.module.js gzip | 5.29 kB | 5.31 kB | ⚠️ +16 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0d.module.js | 16.2 kB | 16.2 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.2 kB | 20.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | atcastle/next.js prevent-double-css-in-gc | Change |
| - | - | - | - |
| _error.js | 248 kB | 248 kB | ✓ |
| _error.js gzip | 65.6 kB | 65.6 kB | ⚠️ +3 B |
| hooks.html | 4.19 kB | 4.19 kB | ✓ |
| hooks.html gzip | 1.07 kB | 1.07 kB | ⚠️ +2 B |
| index.js | 248 kB | 248 kB | ✓ |
| index.js gzip | 65.8 kB | 65.8 kB | ⚠️ +3 B |
| link.js | 280 kB | 280 kB | ✓ |
| link.js gzip | 74.7 kB | 74.7 kB | ⚠️ +3 B |
| routerDirect.js | 273 kB | 273 kB | ✓ |
| routerDirect.js gzip | 72.8 kB | 72.8 kB | ⚠️ +4 B |
| withRouter.js | 273 kB | 273 kB | ✓ |
| withRouter.js gzip | 72.9 kB | 72.9 kB | ⚠️ +4 B |
| Overall change | 1.33 MB | 1.33 MB | ✓ |

</details>

</details>


Commit: 26ffb48a17eff4e4f28100fda72426527b5d91ad

**Review by timneutkens — APPROVED** [review]
