### PR TITLE
fix: gracefully shutdown server

### LINKED ISSUE #53661: Close http server in cleanup
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.3.1
      npm: 9.6.7
      Yarn: 1.22.18
      pnpm: 7.29.3
    Relevant Packages:
      next: 13.4.13-canary.18
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Standalone mode (output: "standalone")

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Meemaw/next-server-shutdown-reproducer

### To Reproduce

1. yarn build
2. yarn start
3. Visit http://localhost:3000
4. Close the server before the page renders
5. Get a "This site can’t be reached" error

### Describe the Bug

NextJS doesn't gracefully handle inflight HTTP server connections. There is a cleanup code
https://github.com/vercel/next.js/blob/498692b69812a096178eaabfea766f4d8fa82413/packages/next/src/server/lib/start-server.ts#L262

, but it doesn't call `server.cleanup()`.

There also seems to be a `teardown` function defined https://github.com/vercel/next.js/blob/498692b69812a096178eaabfea766f4d8fa82413/packages/next/src/server/lib/start-server.ts#L500)

, which does the correct thing, but is never called?

### Expected Behavior

`server.cleanup()` should be called & awaited so any inflight requests are gracefully handled.

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

<sub>[NEXT-1961](https://linear.app/vercel/issue/NEXT-1961/close-http-server-in-cleanup)</sub>

### PR DESCRIPTION
**Pull request by redbmk**
- Both the standalone server and the `startServer` function it calls attempt to stop the server on `SIGINT` and `SIGTERM` in different ways. This lets `server.js` yield to `startServer`
- The cleanup function in `startServer` was not waiting for the server to close before calling `process.exit`. This lets it wait for any in-flight requests to finish processing before exiting the process

fixes: #53661

### CODE REVIEW

File: packages/next/src/server/lib/start-server.ts [hunk 1]
```diff
@@ -266,8 +266,9 @@ export async function startServer(
       try {
         const cleanup = (code: number | null) => {
           debug('start-server process cleanup')
-          server.close()
-          process.exit(code ?? 0)
+          server.close(() => {
```
Comment (redbmk) [inline packages/next/src/server/lib/start-server.ts:269]: https://nodejs.org/api/net.html#serverclosecallback

> This function is asynchronous, the server is finally closed when all connections are ended and the server emits a ['close'](https://nodejs.org/api/net.html#event-close) event. The optional callback will be called once the 'close' event occurs.

File: packages/next/src/build/utils.ts [hunk 2]
```diff
@@ -2026,13 +2026,6 @@ const dir = path.join(__dirname)
 process.env.NODE_ENV = 'production'
 process.chdir(__dirname)
 
-// Make sure commands gracefully respect termination signals (e.g. from Docker)
-// Allow the graceful termination to be manually configurable
```
Comment (huozhi) [inline packages/next/src/build/utils.ts:2030]: can we move this comment to next server?

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 75f884d4c319b743ddac4129c4548f703c4a6a69

`pnpm test-dev test/development/typescript-auto-install/index.test.ts` 
- typescript-auto-install > should detect TypeScript being added and auto setup

<details>
<summary>Expand output</summary>

  ● typescript-auto-install › should detect TypeScript being added and auto setup

    TIMED OUT: /hello world/

    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="next-head-count" content="2"><noscript data-n-css=""></noscript><script src="/_next/static/chunks/c4a26_next_4d4353._.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/c8460_react_22c55a._.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/4e99c_react-dom_cjs_react-dom_development_c0b264.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/4e99c_react-dom_55c180._.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/node_modules__pnpm_8959e2._.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/%5Broot%20of%20the%20server%5D__272bc4._.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/c4a26_next_dist_pages_ec8094._.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/%5Bnext%5D_entry_page-loader_ts_a3717c._.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/%5Bnext%5D_entry_page-loader_ts_1f4585._.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/pages/_app.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/c4a26_next_87fa23._.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/%5Broot%20of%20the%20server%5D__2d61be._.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/c4a26_next_dist_pages_468469._.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/%5Bnext%5D_entry_page-loader_ts_e489bb._.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/%5Bnext%5D_entry_page-loader_ts_f73e3f._.js?ts=1702476643834" defer=""></script><script src="/_next/static/chunks/pages/_error.js?ts=1702476643834" defer=""></script><script src="/_next/static/development/_ssgManifest.js?ts=1702476643834" defer=""></script><script src="/_next/static/development/_buildManifest.js?ts=1702476643834" defer=""></script><noscript id="__next_css__DO_NOT_USE__"></noscript></head><body style="overflow: hidden;"><div id="__next"></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":500}},"page":"/_error","query":{},"buildId":"development","isFallback":false,"err":{"name":"Error","source":"server","message":"./tsconfig.json\nAn issue occurred while parsing a tsconfig.json file.\ntsconfig is not parseable: invalid JSON: text content doesn't contain any json data\n\n\n","stack":"Error: ./tsconfig.json\nAn issue occurred while parsing a tsconfig.json file.\ntsconfig is not parseable: invalid JSON: text content doesn't contain any json data\n\n\n\n    at Object.getCompilationErrors (/tmp/next-install-dc9a3ea72a377a33fae472992c2b4fc465645066383a70ef9b94ba62991a0ab3/node_modules/.pnpm/file+..+next-repo-ddd1f12d337821861da36515bc00ad30c25c422679e0153c3adaf6e0d5c2f382+packages+n_4uv6p5ozrpvh3w7lh6js4pvmry/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:980:37)\n    at DevBundlerService.getCompilationError (/tmp/next-install-dc9a3ea72a377a33fae472992c2b4fc465645066383a70ef9b94ba62991a0ab3/node_modules/.pnpm/file+..+next-repo-ddd1f12d337821861da36515bc00ad30c25c422679e0153c3adaf6e0d5c2f382+packages+n_4uv6p5ozrpvh3w7lh6js4pvmry/node_modules/next/dist/server/lib/dev-bundler-service.js:36:55)\n    at DevServer.getCompilationError (/tmp/next-install-dc9a3ea72a377a33fae472992c2b4fc465645066383a70ef9b94ba62991a0ab3/node_modules/.pnpm/file+..+next-repo-ddd1f12d337821861da36515bc00ad30c25c422679e0153c3adaf6e0d5c2f382+packages+n_4uv6p5ozrpvh3w7lh6js4pvmry/node_modules/next/dist/server/dev/next-dev-server.js:582:42)\n    at DevServer.findPageComponents (/tmp/next-install-dc9a3ea72a377a33fae472992c2b4fc465645066383a70ef9b94ba62991a0ab3/node_modules/.pnpm/file+..+next-repo-ddd1f12d337821861da36515bc00ad30c25c422679e0153c3adaf6e0d5c2f382+packages+n_4uv6p5ozrpvh3w7lh6js4pvmry/node_modules/next/dist/server/dev/next-dev-server.js:541:43)\n    at async DevServer.renderErrorToResponseImpl (/tmp/next-install-dc9a3ea72a377a33fae472992c2b4fc465645066383a70ef9b94ba62991a0ab3/node_modules/.pnpm/file+..+next-repo-ddd1f12d337821861da36515bc00ad30c25c422679e0153c3adaf6e0d5c2f382+packages+n_4uv6p5ozrpvh3w7lh6js4pvmry/node_modules/next/dist/server/base-server.js:2050:26)"},"gip":true,"scriptLoader":[]}</script><div id="__next-build-watcher" style="position: fixed; bottom: 10px; right: 20px; width: 0px; height: 0px; z-index: 99999;"></div><next-route-announcer><p aria-live="assertive" id="__next-route-announcer__" role="alert" style="border: 0px; clip: rect(0px, 0px, 0px, 0px); height: 1px; margin: -1px; overflow: hidden; padding: 0px; position: absolute; top: 0px; width: 1px; white-space: nowrap; overflow-wrap: normal;"></p></next-route-announcer><nextjs-portal></nextjs-portal></body>

    undefined

      626 |
      627 |   if (hardError) {
    > 628 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      629 |   }
      630 |   return false
      631 | }

      at check (lib/next-test-utils.ts:628:11)
      at Object.<anonymous> (development/typescript-auto-install/index.test.ts:54:5)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js fix-53661 | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.8s | N/A |
| buildDurationCached | 7.2s | 6.1s | N/A |
| nodeModulesSize | 200 MB | 200 MB | N/A |
| nextStartRea..uration (ms) | 422ms | 425ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js fix-53661 | Change |
| - | - | - | - |
| 170-HASH.js gzip | 26.8 kB | 26.8 kB | N/A |
| 199.HASH.js gzip | 181 B | 185 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 240 B | 241 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js fix-53661 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js fix-53661 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 195 B | 194 B | N/A |
| _error-HASH.js gzip | 183 B | 182 B | N/A |
| amp-HASH.js gzip | 501 B | 501 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 255 B | ✓ |
| head-HASH.js gzip | 349 B | 350 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.6 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 309 B | N/A |
| script-HASH.js gzip | 384 B | 384 B | ✓ |
| withRouter-HASH.js gzip | 307 B | 306 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js fix-53661 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js fix-53661 | Change |
| - | - | - | - |
| index.html gzip | 529 B | 527 B | N/A |
| link.html gzip | 542 B | 540 B | N/A |
| withRouter.html gzip | 524 B | 521 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js fix-53661 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.7 kB | 93.7 kB | N/A |
| page.js gzip | 146 kB | 146 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js fix-53661 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 619 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | redbmk/next.js fix-53661 | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 94.1 kB | 94.1 kB | ✓ |
| app-page-tur..prod.js gzip | 94.8 kB | 94.8 kB | ✓ |
| app-page-tur..prod.js gzip | 89.4 kB | 89.4 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.7 kB | 88.7 kB | ✓ |
| app-route-ex...dev.js gzip | 24 kB | 24 kB | ✓ |
| app-route-ex..prod.js gzip | 16.6 kB | 16.6 kB | ✓ |
| app-route-tu..prod.js gzip | 16.6 kB | 16.6 kB | ✓ |
| app-route-tu..prod.js gzip | 16.2 kB | 16.2 kB | ✓ |
| app-route.ru...dev.js gzip | 23.4 kB | 23.4 kB | ✓ |
| app-route.ru..prod.js gzip | 16.2 kB | 16.2 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| Overall change | 930 kB | 930 kB | ✓ |

</details>

</details>
Commit: 75f884d4c319b743ddac4129c4548f703c4a6a69

File: packages/next/src/build/utils.ts (hunk 2 above)
Comment (redbmk) [reply packages/next/src/build/utils.ts:2030]: sure - I just moved them to `start-server.ts` just before the process.env check.

Also added a Log.Info to let users know the cleanup process started in case they wonder why it's not shutting down immediately.

**Comment by redbmk** [comment]
I'm having a hard time thinking of a good way to test this in an automated way. The way I've tested manually is by hitting an endpoint with a long-lived (~10s) response and then send a `kill -TERM` signal to the process. Without this change it stops immediately and interrupts the response. With this change it waits for the response to finish before the process exits

**Comment by redbmk** [comment]
An interesting behavior that's more noticeable after adding the log is that `process.exit` triggers the `on('exit'` callback, which will also log `Shutting down server`, but right as its exiting. Might make more sense to either use a slightly different callback for that or just remove the `exit` handler and let it shut down immediately (essentially the same behavior as before since `server.close` is asynchronous)

File: packages/next/src/server/lib/start-server.ts [hunk 3]
```diff
@@ -279,7 +281,8 @@ export async function startServer(
           // This is the render worker, we keep the process alive
           console.error(err)
         }
-        process.on('exit', (code) => cleanup(code))
```
Comment (redbmk) [inline packages/next/src/server/lib/start-server.ts:282]: https://nodejs.org/api/process.html#event-exit

> Listener functions **must** only perform **synchronous** operations. The Node.js process will exit immediately after calling the `'exit'` event listeners causing any additional work still queued in the event loop to be abandoned.

Once `process.exit` is called we don't really have a chance to clean up. Best we could do is log a message, but not sure that's very useful.

Also calling the same cleanup code, now that there's a log, was resulting in the log printing twice after a signal was received.

File: packages/next/src/server/lib/start-server.ts [hunk 4]
```diff
@@ -266,8 +266,10 @@ export async function startServer(
       try {
         const cleanup = (code: number | null) => {
           debug('start-server process cleanup')
-          server.close()
-          process.exit(code ?? 0)
+          Log.info('Shutting down server...')
```
Comment (huozhi) [inline packages/next/src/server/lib/start-server.ts:269]: Let's not add extra logging for now. We can add this in other PR if necessary for other visualizing purpose
```suggestion
```

**Review by huozhi — DISMISSED** [review]

**Review by huozhi — COMMENTED** [review]
This is breaking the test `test/integration/config-output-export/test/index.test.ts`

File: packages/next/src/cli/next-dev.ts [hunk 5]
```diff
@@ -333,16 +343,4 @@ const nextDev: CliCommand = async (args) => {
...
-  if (!child) {
-    return
-  }
-
-  child.kill('SIGTERM')
-}
-
-process.on('exit', cleanup)
-process.on('SIGINT', cleanup)
-process.on('SIGTERM', cleanup)
```
Comment (redbmk) [inline packages/next/src/cli/next-dev.ts:346]: the other handlers were already killing the child - this one always sends SIGTERM. However, we still need to add a special handler for the exit event since it needs to be synchronous

File: packages/next/src/cli/next-dev.ts [hunk 6]
```diff
@@ -108,8 +111,15 @@ const handleSessionStop = async (signal: string | null) => {
   process.exit(0)
 }
 
-process.on('SIGINT', () => handleSessionStop('SIGINT'))
-process.on('SIGTERM', () => handleSessionStop('SIGTERM'))
+process.on('SIGINT', (code) => handleSessionStop(code))
+process.on('SIGTERM', (code) => handleSessionStop(code))
```
Comment (redbmk) [inline packages/next/src/cli/next-dev.ts:115]: just sending `handleSessionStop` works as well but typescript seems to do better with this (e.g. if I set `signal: object` this way would give a typescript error, but `process.on("SIGINT", handleSessionStop)` wouldn't raise any errors.

File: test/lib/next-test-utils.ts [hunk 7]
```diff
@@ -521,6 +521,17 @@ export async function killProcess(
...
     })
   })
+
+  await waitForCondition(2000, () => {
+    try {
+      process.kill(pid, 0)
+      // pid still exists, server still running
+      return false
+    } catch {
+      // kill throws an error if the pid doesn't exist
```
Comment (redbmk) [inline test/lib/next-test-utils.ts:531]: wasn't sure if we needed these comments. I didn't think it was very clear why we're calling `process.kill` but maybe refactoring to `function checkIfPIDExists` would be better

Comment (redbmk) [reply test/lib/next-test-utils.ts:531]: Also thinking about this a bit more, it might make more sense to move this check into `killApp` and then we could add a test that calls `killProcess` instead, checks that it hasn't finished until some task is complete, then checks to make sure it's been killed separately.

**Comment by redbmk** [comment]
@huozhi I did a little more cleanup and got the tests passing. I have an idea on how to add a test for this but not really sure where to put it.

It might involve adding an example app with a route that forces a response to take a while, then having a test that calls the route, sends a SIGTERM (or SIGINT), then makes sure the request comes back successfully before the server finishes.

File: test/lib/next-test-utils.ts (hunk 7 above)
Comment (redbmk) [reply test/lib/next-test-utils.ts]: refactored this and I think it's more clear now even without the comments

**Comment by redbmk** [comment]
Woah, the tests were passing before I refactored. I must have gotten some logic backwards. I'll take a look in a bit

**Comment by redbmk** [comment]
still one test failing related to teardown. I need to look into how to run these tests locally

File: packages/next/src/cli/next-dev.ts [hunk 8]
```diff
@@ -108,8 +111,11 @@ const handleSessionStop = async (signal: string | null) => {
   process.exit(0)
 }
 
-process.on('SIGINT', () => handleSessionStop('SIGINT'))
-process.on('SIGTERM', () => handleSessionStop('SIGTERM'))
+process.on('SIGINT', () => handleSessionStop('SIGKILL'))
+process.on('SIGTERM', () => handleSessionStop('SIGKILL'))
+
+// exit event must be synchronous
+process.on('exit', () => child?.kill('SIGKILL'))
```
Comment (redbmk) [inline packages/next/src/cli/next-dev.ts:118]: changed these to SIGKILL to make sure the child process stops immediately. In a production server we would want to pass along the SIGINT or SIGTERM but if you're killing the dev server you probably wouldn't expect it to do any cleanup. This should also be consistent with the current behavior that exits right away with `process.exit`

**Comment by redbmk** [comment]
@huozhi I was able to debug the issue and got tests all passing. I think it's ready for review again.

File: test/lib/next-test-utils.ts [hunk 9]
```diff
@@ -523,10 +523,28 @@ export async function killProcess(
...
+
 // Kill a launched app
 export async function killApp(instance: ChildProcess) {
   if (instance && instance.pid) {
     await killProcess(instance.pid)
+    try {
+      await waitForCondition(2000, () => !isAppRunning(instance))
+    } catch {
+      await killProcess(instance.pid, 'SIGKILL')
+    }
```
[the remark this answers is not in the document]
Comment (redbmk) [reply test/lib/next-test-utils.ts:547]: Because it's throwing `SIGTERM` by default, the apps will run indefinitely. Maybe we just have it throw `SIGKILL` by default instead and then adding a separate test for the clean shutdown would look like sending a `SIGTERM` instead and making sure it shuts down properly.

Since `SIGTERM` now waits for the app to shut down properly, it'll still require at least that change to the util

**Review by huozhi — APPROVED** [review]
Thank you!

**Comment by redbmk** [comment]
Hi @huozhi - thanks for your patience with me on this one :)

Just checking if there was anything else before it was ready to merge - I saw you approved it yesterday.

**Comment by huozhi** [comment]
@redbmk sorry The PR is reverted on canary branch due to showing failing tests after merging with canary. If you'd like to file another one we can take another round of look again. Would be awesome if we can get a new test associated with it 🙏

**Comment by redbmk** [comment]
Ah bummer - OK yeah I'll see if I can get a test for it and see if I can figure out why the tests were failing in canary. Do more tests run in the `canary` branch that wouldn't run in the PR?

**Comment by huozhi** [comment]
Should be the same, feels like it was reported incorrectly on the PR. It was failing in [this job](https://github.com/vercel/next.js/actions/runs/7252180427/job/19756182104) but marked as successful
