### PR TITLE
fix: correctly set `x-forwarded-*` in Middleware

### LINKED ISSUE #52266: Incorrect X-Forwarded-Proto header
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103
Binaries:
  Node: 16.20.0
  npm: 8.19.4
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 13.4.7
  eslint-config-next: 13.4.7
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/alphabeat/infinite-loop-middleware

### To Reproduce

Use this middleware on a production environment:

```ts
import { NextRequest, NextResponse } from 'next/server';

export function middleware(req: NextRequest) {
    if (process.env.NODE_ENV === 'production' && req.headers.get('x-forwarded-proto') !== 'https') {
        return NextResponse.redirect(`https://${req.headers.get('host')}${req.nextUrl.pathname}`, 301);
    }

    return NextResponse.next();
}
```

### Describe the Bug

The `X-Forwarded-Proto` header never equals `https` as expected: nextjs returns `http,http` or `https,http`. This creates an infinite loop and ends up with an ERR_TOO_MANY_REDIRECTS error on production.

### Expected Behavior

The `X-Forwarded-Proto` header should either return `http` or `https` as described on the MDN docs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

Heroku

### PR DESCRIPTION
**Pull request by balazsorban44**
### What?

Follow-up of #56797

While working on this, I noticed that some logic around stripping internal headers was duplicated, so I did some cleanup too.

### Why?

In #56797 we set these headers, but it only affected Route Handlers, Middleware is still missing them, which is a regression introduced in #52492

(Related: https://github.com/vercel/next-learn/issues/252)

### How?

Move to set these headers up to `base-server.ts` so they are present in Middleware too.

> Note: All headers are set with `??=` to respect the original value if set (with other words, only add these headers if they aren't set yet)

Closes NEXT-
Fixes #52266

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 187a8e09ceb7ac2b5bbfe4b002d719a72ae7896f

`pnpm test-dev test/e2e/app-dir/x-forwarded-headers/x-forwarded-headers.test.ts` 
- x-forwarded-headers > should include x-forwarded-* headers

<details>
<summary>Expand output</summary>

  ● x-forwarded-headers › should include x-forwarded-* headers

    expect(received).toBe(expected) // Object.is equality

    Expected: "localhost:40433"
    Received: "wrong"

       9 |     expect(headers['x-forwarded-port']).toBe(url.port)
      10 |     expect(headers['x-forwarded-proto']).toBe(url.protocol.replace(':', ''))
    > 11 |     expect(headers['middleware-x-forwarded-host']).toBe(url.host)
         |                                                    ^
      12 |     expect(headers['middleware-x-forwarded-port']).toBe(url.port)
      13 |     expect(headers['middleware-x-forwarded-proto']).toBe(
      14 |       url.protocol.replace(':', '')

      at Object.toBe (e2e/app-dir/x-forwarded-headers/x-forwarded-headers.test.ts:11:52)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers-middleware | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.5s | N/A |
| buildDurationCached | 6s | 6.6s | ⚠️ +523ms |
| nodeModulesSize | 175 MB | 175 MB | ✓ |
| nextStartRea..uration (ms) | 398ms | 400ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers-middleware | Change |
| - | - | - | - |
| 199-HASH.js gzip | 30 kB | 30 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.2 kB | 53.2 kB | ✓ |
| 494.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.5 kB | 45.5 kB | ✓ |
| main-app-HASH.js gzip | 252 B | 252 B | ✓ |
| main-HASH.js gzip | 33.1 kB | 33.1 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 99.2 kB | 99.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers-middleware | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers-middleware | Change |
| - | - | - | - |
| _app-HASH.js gzip | 205 B | 205 B | ✓ |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 505 B | 507 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.59 kB | 2.59 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.38 kB | 4.38 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 319 B | 320 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 885 B | 885 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers-middleware | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 484 B | ✓ |
| Overall change | 484 B | 484 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers-middleware | Change |
| - | - | - | - |
| index.html gzip | 527 B | 529 B | N/A |
| link.html gzip | 540 B | 543 B | N/A |
| withRouter.html gzip | 523 B | 523 B | ✓ |
| Overall change | 523 B | 523 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers-middleware | Change |
| - | - | - | - |
| edge-ssr.js gzip | 96.1 kB | 96.1 kB | N/A |
| page.js gzip | 140 kB | 140 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers-middleware | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 627 B | N/A |
| middleware-r..fest.js gzip | 148 B | 151 B | N/A |
| middleware.js gzip | 23 kB | 23 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

</details>
Commit: 187a8e09ceb7ac2b5bbfe4b002d719a72ae7896f

File: packages/next/src/server/lib/router-utils/proxy-request.ts [hunk 1]
```diff
@@ -24,7 +24,6 @@ export async function proxyRequest(
     target,
     changeOrigin: true,
     ignorePath: true,
-    xfwd: true,
```
Comment (balazsorban44) [inline packages/next/src/server/lib/router-utils/proxy-request.ts:27]: `http-proxy` attempts to set these headers, even if they are already present. Since we are setting these headers higher up in `base-server.ts`, this should not be necessary to set here anymore.

See: https://github.com/http-party/node-http-proxy/blob/9b96cd725127a024dabebec6c7ea8c807272223d/lib/http-proxy/passes/web-incoming.js#L58-L86

File: packages/next/src/server/lib/router-utils/proxy-request.ts [hunk 2]
```diff
@@ -24,11 +24,13 @@ export async function proxyRequest(
...
     ws: true,
     // we limit proxy requests to 30s by default, in development
     // we don't time out WebSocket requests to allow proxying
     proxyTimeout: proxyTimeout === null ? undefined : proxyTimeout || 30_000,
+    headers: {
+      'x-forwarded-host': req.headers.host || '',
```
Comment (balazsorban44) [inline packages/next/src/server/lib/router-utils/proxy-request.ts:32]: Still set this header, but without concating with existing ones. See https://github.com/vercel/next.js/pull/57815/files#r1378313718

**Review by huozhi — APPROVED** [review]

**Comment by controversial** [comment]
I believe this is missing an edge case that breaks my application’s behavior—in the old implementation (prior to #52492) the `x-forwarded-host` header of the dev server would include subdomains of localhost (e.g. `abc.localhost:3000`). In this new implementation, `host
