### PR TITLE
Ensure constructor for `useSearchParams` can be imported for `instanceof` checks

### LINKED ISSUE #86501: `useSearchParams() instanceof ReadonlyURLSearchParams` returns `false` on the server and `true` on the client.
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/adoring-nobel-36s846?file=%2Fapp%2Fclient.tsx

### To Reproduce

Refresh the CodeSandbox preview and see the page content change from `false` to `true`.

### Current vs. Expected behavior

According to type definitions, `useSearchParams()` returns a `ReadonlyURLSearchParams` instance. While rendering a client component on the server, `useSearchParams() instanceof ReadonlyURLSearchParams` returns `false`, but when hydration starts and the client component is rendered on the client, `useSearchParams() instanceof ReadonlyURLSearchParams` returns `true`.

This happens only while using the dev server, with the prod server, `useSearchParams() instanceof ReadonlyURLSearchParams` always returns `true`.

I expect `useSearchParams() instanceof ReadonlyURLSearchParams` to always return `true` when using the dev server.

### Provide environment information

```bash
CodeSandbox environment:

Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.12.1
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: 8.15.6
Relevant Packages:
  next: 16.1.0-canary.2 // Latest available version is detected (16.1.0-canary.2).
  eslint-config-next: N/A
  react: 19.2.0
  react-dom: 19.2.0
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I tested my reproduction against different canary releases, and the first one that introduced the bug was "16.0.0-canary.16", since reverting to "16.0.0-canary.15" works.

For context, I'm trying to write a `SearchParams` wrapper class that can take both the result of `useSearchParams()` or the `searchParams` object passed to page components in its constructor, and do different things based on what was passed.

### PR DESCRIPTION
**Pull request by eps1lon**
Fixes https://github.com/vercel/next.js/issues/86501
Closes https://github.com/vercel/next.js/pull/86649

The same constructor is relevant for `instanceof` checks. Previously `useSearchParams() instanceof ReadonlyURLSearchParams` lead to hydration mismatches.

### CODE REVIEW

File: packages/next/src/client/components/navigation.ts [hunk 1]
```diff
@@ -61,15 +61,15 @@ export function useSearchParams(): ReadonlyURLSearchParams {
...
     if (!searchParams) {
       // When the router is not ready in pages, we won't have the search params
       // available.
-      return null
+      return null!
     }
 
     return new ReadonlyURLSearchParams(searchParams)
-  }, [searchParams]) as ReadonlyURLSearchParams
+  }, [searchParams])
```
Comment (eps1lon) [inline packages/next/src/client/components/navigation.ts:72]: drive-by type refactor to make it clear we only want the non-nullable case not an arbitrary type-case

File: packages/next/src/shared/lib/hooks-client-context.shared-runtime.ts [hunk 2]
```diff
@@ -17,8 +18,8 @@ export type InstrumentedPromise<T> = Promise<T> & {
 
 export type NavigationPromises = {
   pathname: InstrumentedPromise<string>
-  searchParams: InstrumentedPromise<any> // ReadonlyURLSearchParams
-  params: InstrumentedPromise<any> // Params
+  searchParams: InstrumentedPromise<ReadonlyURLSearchParams>
+  params: InstrumentedPromise<Params>
```
Comment (eps1lon) [inline packages/next/src/shared/lib/hooks-client-context.shared-runtime.ts:22]: Unclear why these were typed as `any`

**Review by unstubbable — APPROVED** [review]
