### PR TITLE
Normalize root path according to trailingSlash option in default next/image loader  #21337

### LINKED ISSUE #21337: trailingSlash: true redirects /_next/image? to /_next/image/? for each image request
**What version of Next.js are you using?**

10.0.2

**What version of Node.js are you using?**

12.4.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**How are you deploying your application?**

Other platform

**Describe the Bug**

When trailingSlash is set to 'true' the /_next/image directory used for serving optimized images is also affected.

Instead of requesting the resource on:
 /_next/image?url=/uploads/...

the user is redirected with 308 to
/_next/image/?url=/uploads/...

This creates a huge amount of unnecessary redirects for a page full of images. I couldn't find any additional config options for the trailingSlash option whatsoever.

**Expected Behavior**

The optimized images path to not be redirected to a path with a trailing slash.

**To Reproduce**

1. Create a NextJS application.
2. Add a couple of next/image images.
3. Set trailingSlash to true.
4. Check the network tab and verify that the requests for the images have been redirected with status code 308.
5. Disable trailingSlash and verify that there are no redirects.

### PR DESCRIPTION
**Pull request by fliptheweb**
Normalize path by trailing slash in `next/images` package for default image loader according to `trailingSlash` option in config.
Otherwise, Next.js does unnecessary 308 redirects to the normalized path.

Fixes: https://github.com/vercel/next.js/issues/21337

**Tests:**
I wonder to cover that case by [integration test](https://github.com/vercel/next.js/blob/canary/test/integration/image-component/default/test/index.test.js#L606), but don't want to add complexity with one more `mode` with custom `next.config` just with `trailingSlash: true` option.
Any other option to do that?
Perhaps I could make a new `mode`, but only with a case that checks `getSrc`, out of `runTests` function?

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| buildDuration | 12s | 11.8s | -176ms |
| nodeModulesSize | 42.6 MB | 42.6 MB | ⚠️ +256 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.228 | 2.194 | -0.03 |
| / avg req/sec | 1121.93 | 1139.28 | +17.35 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.584 | 1.587 | 0 |
| /error-in-render avg req/sec | 1578.76 | 1574.91 | ⚠️ -3.85 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| 677f882d2ed8..854c.js gzip | 13.2 kB | 13.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| buildDuration | 13.9s | 13.7s | -227ms |
| nodeModulesSize | 42.6 MB | 42.6 MB | ⚠️ +256 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| 677f882d2ed8..854c.js gzip | 13.2 kB | 13.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _error.js | 1.01 MB | 1.01 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| 500.html | 2.65 kB | 2.65 kB | ✓ |
| amp.amp.html | 10.4 kB | 10.4 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.01 MB | 1.01 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.06 MB | 1.06 MB | ✓ |
| withRouter.js | 1.06 MB | 1.06 MB | ✓ |
| Overall change | 5.21 MB | 5.21 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| buildDuration | 14s | 14.1s | ⚠️ +116ms |
| nodeModulesSize | 42.6 MB | 42.6 MB | ⚠️ +256 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.246 | 2.206 | -0.04 |
| / avg req/sec | 1113.2 | 1133.5 | +20.3 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.585 | 1.572 | -0.01 |
| /error-in-render avg req/sec | 1577.45 | 1590.28 | +12.83 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| 597-dc8125e2..ef24.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 60 kB | 60 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _app-aedc815..1421.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-71ec2..1a96.js gzip | 3.38 kB | 3.38 kB | ✓ |
| amp-33a09cb0..6745.js gzip | 536 B | 536 B | ✓ |
| hooks-4e968a..f870.js gzip | 902 B | 902 B | ✓ |
| index-5c6845..f75c.js gzip | 230 B | 230 B | ✓ |
| link-99f0c6c..b84a.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..bb56.js gzip | 306 B | 306 B | ✓ |
| withRouter-7..2133.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.57 kB | 8.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 326 B | 326 B | ✓ |
| Overall change | 326 B | 326 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 591 B | 591 B | ✓ |
| withRouter.html gzip | 579 B | 579 B | ✓ |
| Overall change | 1.75 kB | 1.75 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "eP8R9Kw9EzCDX01lAbo1l",
+        "buildId": "Sm9c2ZVWQNNhMjvTL31-q",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/eP8R9Kw9EzCDX01lAbo1l/_buildManifest.js"
+      src="/_next/static/Sm9c2ZVWQNNhMjvTL31-q/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/eP8R9Kw9EzCDX01lAbo1l/_ssgManifest.js"
+      src="/_next/static/Sm9c2ZVWQNNhMjvTL31-q/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "eP8R9Kw9EzCDX01lAbo1l",
+        "buildId": "Sm9c2ZVWQNNhMjvTL31-q",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/eP8R9Kw9EzCDX01lAbo1l/_buildManifest.js"
+      src="/_next/static/Sm9c2ZVWQNNhMjvTL31-q/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/eP8R9Kw9EzCDX01lAbo1l/_ssgManifest.js"
+      src="/_next/static/Sm9c2ZVWQNNhMjvTL31-q/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "eP8R9Kw9EzCDX01lAbo1l",
+        "buildId": "Sm9c2ZVWQNNhMjvTL31-q",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/eP8R9Kw9EzCDX01lAbo1l/_buildManifest.js"
+      src="/_next/static/Sm9c2ZVWQNNhMjvTL31-q/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/eP8R9Kw9EzCDX01lAbo1l/_ssgManifest.js"
+      src="/_next/static/Sm9c2ZVWQNNhMjvTL31-q/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: c2d045509a9209cc349897cec0f0a5fc7540fd8e

**Comment by docforcedev** [comment]
@fliptheweb Any updates on this?

**Comment by eprothro** [comment]
We're experiencing multiple 308s using the Image component as well. Any estimate on timing for this fix?

File: packages/next/client/image.tsx [hunk 1]
```diff
@@ -761,5 +762,7 @@ function defaultLoader({
     }
   }
 
-  return `${root}?url=${encodeURIComponent(src)}&w=${width}&q=${quality || 75}`
+  return `${normalizePathTrailingSlash(root)}?url=${encodeURIComponent(
+    src
+  )}&w=${width}&q=${quality || 75}`
 }
```
Comment (styfle) [inline packages/next/client/image.tsx:768]: Thanks! Please add an integration test so we don't regress in the future.

You can copy/paste this one and set `trailingSlash: true` 

https://github.com/vercel/next.js/blob/76dee14db47381e8daab8fc5be4f1314115af9e0/test/integration/image-optimizer/test/index.test.js#L1158-L1193

**Comment by balazsorban44** [comment]
Hi @fliptheweb, are you still interested in getting this PR merged?

There seems to be a merge conflict, and https://github.com/vercel/next.js/pull/22453#discussion_r711806947 kindly asked to add some tests so we don't regress on it.

Let me know if you want to finish this off, or you are OK with someone else doing it! :+1:

**Comment by fliptheweb** [comment]
@balazsorban44 got it, gonna update the PR till next monday. Thank you for notifying me.

**Comment by fliptheweb** [comment]
@balazsorban44 Balázs, please check it out😇

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| buildDuration | 15.7s | 15.7s | -45ms |
| buildDurationCached | 6.1s | 6.1s | -14ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.103 | 3.132 | ⚠️ +0.03 |
| / avg req/sec | 805.59 | 798.12 | ⚠️ -7.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.353 | 1.357 | 0 |
| /error-in-render avg req/sec | 1847.98 | 1842.04 | ⚠️ -5.94 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.5 kB | 71.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.06 kB | 5.09 kB | ⚠️ +31 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.8 kB | 14.8 kB | ⚠️ +31 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-35c32b80abf212d2.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-8642d114a09c62c5.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-3b0e98cd8174c02a.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-6052261a372c369a.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-0b3d72804dab6202.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-00527c3f2207a902.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -133,6 +133,7 @@
       var _useIntersection = __webpack_require__(9246);
       var _imageConfigContext = __webpack_require__(8730);
       var _utils = __webpack_require__(670);
+      var _normalizeTrailingSlash = __webpack_require__(2700);
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -910,7 +911,12 @@
           return src;
         }
         return ""
-          .concat(config.path, "?url=")
+          .concat(
+            (0, _normalizeTrailingSlash).normalizePathTrailingSlash(
+              config.path
+            ),
+            "?url="
+          )
           .concat(encodeURIComponent(src), "&w=")
           .concat(width, "&q=")
           .concat(quality || 75);
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| buildDuration | 18.9s | 18.9s | ⚠️ +46ms |
| buildDurationCached | 6.2s | 5.9s | -291ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.092 | 2.882 | -0.21 |
| / avg req/sec | 808.54 | 867.31 | +58.77 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.358 | 1.258 | -0.1 |
| /error-in-render avg req/sec | 1840.38 | 1986.75 | +146.37 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.2 kB | 5.23 kB | ⚠️ +28 B |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.9 kB | 15 kB | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 459 B | ⚠️ +1 B |
| Overall change | 458 B | 459 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-35c32b80abf212d2.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-8642d114a09c62c5.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-3b0e98cd8174c02a.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-6052261a372c369a.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-0b3d72804dab6202.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-00527c3f2207a902.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -133,6 +133,7 @@
       var _useIntersection = __webpack_require__(9246);
       var _imageConfigContext = __webpack_require__(8730);
       var _utils = __webpack_require__(670);
+      var _normalizeTrailingSlash = __webpack_require__(2700);
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -910,7 +911,12 @@
           return src;
         }
         return ""
-          .concat(config.path, "?url=")
+          .concat(
+            (0, _normalizeTrailingSlash).normalizePathTrailingSlash(
+              config.path
+            ),
+            "?url="
+          )
           .concat(encodeURIComponent(src), "&w=")
           .concat(width, "&q=")
           .concat(quality || 75);
```
</details>
</details>
Commit: d23b27f6abadd492444bca2ed9de6adba282f144

**Review by styfle — APPROVED** [review]
Great, thanks!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| buildDuration | 20.6s | 20.9s | ⚠️ +366ms |
| buildDurationCached | 7.8s | 7.9s | ⚠️ +63ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.521 | 4.405 | -0.12 |
| / avg req/sec | 552.92 | 567.56 | +14.64 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.203 | 2.267 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1135.01 | 1103 | ⚠️ -32.01 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.5 kB | 71.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.06 kB | 5.09 kB | ⚠️ +31 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.8 kB | 14.8 kB | ⚠️ +31 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-35c32b80abf212d2.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-8642d114a09c62c5.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-3b0e98cd8174c02a.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-6052261a372c369a.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-0b3d72804dab6202.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-00527c3f2207a902.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -133,6 +133,7 @@
       var _useIntersection = __webpack_require__(9246);
       var _imageConfigContext = __webpack_require__(8730);
       var _utils = __webpack_require__(670);
+      var _normalizeTrailingSlash = __webpack_require__(2700);
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -910,7 +911,12 @@
           return src;
         }
         return ""
-          .concat(config.path, "?url=")
+          .concat(
+            (0, _normalizeTrailingSlash).normalizePathTrailingSlash(
+              config.path
+            ),
+            "?url="
+          )
           .concat(encodeURIComponent(src), "&w=")
           .concat(width, "&q=")
           .concat(quality || 75);
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| buildDuration | 24.8s | 24.9s | ⚠️ +15ms |
| buildDurationCached | 7.7s | 8.1s | ⚠️ +396ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +194 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.368 | 4.42 | ⚠️ +0.05 |
| / avg req/sec | 572.28 | 565.59 | ⚠️ -6.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.122 | 2.147 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1178.05 | 1164.41 | ⚠️ -13.64 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.2 kB | 5.23 kB | ⚠️ +28 B |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.9 kB | 15 kB | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 459 B | ⚠️ +1 B |
| Overall change | 458 B | 459 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | fliptheweb/next.js fix-next-image-with-trailing-slash | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-35c32b80abf212d2.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-8642d114a09c62c5.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-3b0e98cd8174c02a.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-6052261a372c369a.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-0b3d72804dab6202.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-00527c3f2207a902.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -133,6 +133,7 @@
       var _useIntersection = __webpack_require__(9246);
       var _imageConfigContext = __webpack_require__(8730);
       var _utils = __webpack_require__(670);
+      var _normalizeTrailingSlash = __webpack_require__(2700);
       function Image(_param) {
         var src = _param.src,
           sizes = _param.sizes,
@@ -910,7 +911,12 @@
           return src;
         }
         return ""
-          .concat(config.path, "?url=")
+          .concat(
+            (0, _normalizeTrailingSlash).normalizePathTrailingSlash(
+              config.path
+            ),
+            "?url="
+          )
           .concat(encodeURIComponent(src), "&w=")
           .concat(width, "&q=")
           .concat(quality || 75);
```
</details>
</details>
Commit: 76b9b39cf861f5644435055de4282e692676e6a7

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 76b9b39cf861f5644435055de4282e692676e6a7

`yarn testheadless test/integration/async-modules/test/index.test.js` 
- Async modules > dev mode > can render async AMP pages
- Async modules > production mode > can render async AMP pages

<details>
<summary>Expand output</summary>

  ● Async modules › dev mode › can render async AMP pages

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:44003/config", waiting until "load"
    ============================================================

      149 |       this.activeTrace = encodeURIComponent(url)
      150 |     }
    > 151 |     await page.goto(url, { waitUntil: 'load' })
          |                ^
      152 |   }
      153 |
      154 |   back(): BrowserInterface {

      at Playwright.loadPage (lib/browsers/playwright.ts:151:16)
      at Object.webdriver [as default] (lib/next-webdriver.ts:98:3)
      at Object.<anonymous> (integration/async-modules/test/index.test.js:84:17)

  ● Async modules › production mode › can render async AMP pages

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:43191/config", waiting until "load"
    ============================================================

      149 |       this.activeTrace = encodeURIComponent(url)
      150 |     }
    > 151 |     await page.goto(url, { waitUntil: 'load' })
          |                ^
      152 |   }
      153 |
      154 |   back(): BrowserInterface {

      at Playwright.loadPage (lib/browsers/playwright.ts:151:16)
      at Object.webdriver [as default] (lib/next-webdriver.ts:98:3)
      at Object.<anonymous> (integration/async-modules/test/index.test.js:84:17)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by fliptheweb** [comment]
@balazsorban44 some tests failed, was it a flaky test?

**Comment by balazsorban44** [comment]
Thanks for the heads up, let's follow https://github.com/vercel/next.js/actions/runs/1947085695

I thought I saw all tests passing but I might have overlooked.

**Comment by balazsorban44** [comment]
It _was_ just a flaky test, all good. :+1:
