### PR TITLE
Ensure env is loaded before next config

### LINKED ISSUE #22811: 10.0.8: Env variables redefined within next.config.js are undefined in dev mode
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

14.15.1

### What browser are you using?

Tested in Firefox and Safari 

### What operating system are you using?

macOS Big Sur 11.2.1

### How are you deploying your application?

yarn dev, yarn build && yarn start

### Describe the Bug

Environment variables defined in `next.config.js` return undefined in page components when on dev mode (yarn dev).
But running the same project on production (yarn build && yarn start) the env variables work as expected.

### Expected Behavior

If env variables are set in an `.env` file at the root of the project and then exposed to Next.js within the `next.config.js` file I would expect them to be accessible in component code in both production and development environments. 

### To Reproduce

1. Clone example project. https://github.com/krall12/nextjs-env-config-dev-bug
2. Install deps
3. run yarn dev and open browser. You should see the test environment variable not defined. 
4. run yarn build && yarn start and open your browser. You should see the test environment variable correctly defined. 

As a control: 
1. yarn add next@10.0.7
2. in both dev and production modes the environment variable is returned correctly.

### LINKED ISSUE #22843: basePath not working after updating to 10.0.8
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

14

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOs 11.2.2

### How are you deploying your application?

next start

### Describe the Bug

I've updated to 10.0.8, and basePath stoped working I'm getting:

```
 http://localhost:3000/brand/it 404 (Not Found)
it:1 GET http://localhost:3000/brand/_next/static/chunks/main-093be8720c3bcc128712.js net::ERR_ABORTED 404 (Not Found)
it:1 GET http://localhost:3000/brand/_next/static/chunks/commons.1869cbd23f3f8cc4be00.js net::ERR_ABORTED 404 (Not Found)
it:1 GET http://localhost:3000/brand/_next/static/chunks/pages/_error-4c1af142aef0a484e71f.js net::ERR_ABORTED 404 (Not Found)
it:1 GET http://localhost:3000/brand/fonts/styles.css net::ERR_ABORTED 404 (Not Found)
it:25 GET http://localhost:3000/brand/_next/static/2tJDBmRSU0I806yikZrLc/_buildManifest.js net::ERR_ABORTED 404 (Not Found)
it:25 GET http://localhost:3000/brand/_next/static/2tJDBmRSU0I806yikZrLc/_ssgManifest.js net::ERR_ABORTED 404 (Not Found)
it:25 GET http://localhost:3000/brand/chat.js net::ERR_ABORTED 404 (Not Found)
it:25 GET http://localhost:3000/brand/brand-dark-bg.png 404 (Not Found)
it:25 GET http://localhost:3000/brand/_next/static/chunks/main-093be8720c3bcc128712.js net::ERR_ABORTED 404 (Not Found)
it:25 GET http://localhost:3000/brand/_next/static/chunks/commons.1869cbd23f3f8cc4be00.js net::ERR_ABORTED 404 (Not Found)
it:25 GET http://localhost:3000/brand/_next/static/chunks/pages/_error-4c1af142aef0a484e71f.js net::ERR_ABORTED 404 (Not Found)
it:25 GET http://localhost:3000/brand/_next/static/2tJDBmRSU0I806yikZrLc/_buildManifest.js net::ERR_ABORTED 404 (Not Found)
it:25 GET http://localhost:3000/brand/_next/static/2tJDBmRSU0I806yikZrLc/_ssgManifest.js net::ERR_ABORTED 404 (Not Found)
favicon-brand.ico:1 GET http://localhost:3000/brand/favicon/favicon-brand.ico 404 (Not Found)
```

### Expected Behavior

to be able to load scripts via basePath

### To Reproduce

```js
/* eslint-disable @typescript-eslint/no-var-requires */
const dotenv = require("dotenv");
const fs = require("fs");
const path = require("path");
const nextTranslate = require("next-translate");

dotenv.config();
const domain = process.env["NEXT_PUBLIC_SERVER_DOMAIN"];
const secretCookiePassword = process.env["SECRET_COOKIE_PASSWORD"];
const endpoint = process.env.NEXT_PUBLIC_GQL_API_DOMAIN;
const dip = process.env.NEXT_PUBLIC_DIP_DOMAIN;
const trackingID = process.env.NEXT_PUBLIC_TRACKING_ID ?? "UA-190484440-1";
const brand = process.env.NEXT_PUBLIC_BRAND;
const isProd = process.env.NODE_ENV === "production";

module.exports = nextTranslate({
  basePath: isProd ? `/${brand}` : "",
  env: {
    NEXT_PUBLIC_SERVER_DOMAIN: domain,
    SECRET_COOKIE_PASSWORD: secretCookiePassword,
    NEXT_PUBLIC_BRAND: brand,
    NEXT_PUBLIC_GQL_API_DOMAIN: endpoint,
    NEXT_PUBLIC_DIP_DOMAIN: dip,
    NEXT_PUBLIC_TRACKING_ID: trackingID
  },
  images: {
    domains: ["mydomain.com"]
  }
});
```

it was working fine since 10.0.7. It still works on dev mode, but when I build and start the project either on localhost or on production server, it stop working.

I hade problem with environmental variable not been read on browser after updating to 10.0.8, that I solved by prefixing them with NEXT_PUBLIC_.

### PR DESCRIPTION
**Pull request by ijjk**
This ensures we load all env values before loading `next.config.js` since these values can be used in there. This also updates to ensure we're testing these values are available while loading `next.config.js` so we don't regress on this. 

Fixes: https://github.com/vercel/next.js/issues/22811
Fixes: https://github.com/vercel/next.js/issues/22843

### CODE REVIEW

File: packages/next/next-server/server/config-utils.ts [hunk 1]
```diff
@@ -23,6 +25,8 @@ export async function shouldLoadWithWebpack5(
   phase: string,
   dir: string
 ): Promise<boolean> {
+  await loadEnvConfig(dir, phase === PHASE_DEVELOPMENT_SERVER, Log)
```
Comment (timneutkens) [inline packages/next/next-server/server/config-utils.ts:28]: This should be handled in `loadConfig` of `next-server/server/config.ts`

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| buildDuration | 13s | 12.6s | -332ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +1.65 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.337 | 2.284 | -0.05 |
| / avg req/sec | 1069.82 | 1094.75 | +24.93 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.582 | 1.513 | -0.07 |
| /error-in-render avg req/sec | 1580.06 | 1652.27 | +72.21 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| 677f882d2ed8..a2e7.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.8 kB | 59.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| buildDuration | 15.2s | 14.2s | -1s |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +1.65 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| 677f882d2ed8..a2e7.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.8 kB | 59.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| _error.js | 1.02 MB | 1.02 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| 500.html | 2.65 kB | 2.65 kB | ✓ |
| amp.amp.html | 10.5 kB | 10.5 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.02 MB | 1.02 MB | ✓ |
| link.js | 1.08 MB | 1.08 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.27 MB | 5.27 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| buildDuration | 15.2s | 14s | -1.2s |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +1.65 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.355 | 2.219 | -0.14 |
| / avg req/sec | 1061.77 | 1126.57 | +64.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.594 | 1.446 | -0.15 |
| /error-in-render avg req/sec | 1568.36 | 1729.5 | +161.14 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| 597-2bc2376a..203d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| _app-aedc815..1421.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-71ec2..1a96.js gzip | 3.38 kB | 3.38 kB | ✓ |
| amp-33a09cb0..6745.js gzip | 536 B | 536 B | ✓ |
| hooks-4e968a..f870.js gzip | 902 B | 902 B | ✓ |
| index-5c6845..f75c.js gzip | 230 B | 230 B | ✓ |
| link-99f0c6c..b84a.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..bb56.js gzip | 306 B | 306 B | ✓ |
| withRouter-7..2133.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.57 kB | 8.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| _buildManifest.js gzip | 326 B | 326 B | ✓ |
| Overall change | 326 B | 326 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/env-loading | Change |
| - | - | - | - |
| index.html gzip | 586 B | 586 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 580 B | 580 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "CjN_0SkxkBnrQZF5rYOl8",
+        "buildId": "OMyCD-ntzlHKcMG02XW9l",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/CjN_0SkxkBnrQZF5rYOl8/_buildManifest.js"
+      src="/_next/static/OMyCD-ntzlHKcMG02XW9l/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/CjN_0SkxkBnrQZF5rYOl8/_ssgManifest.js"
+      src="/_next/static/OMyCD-ntzlHKcMG02XW9l/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "CjN_0SkxkBnrQZF5rYOl8",
+        "buildId": "OMyCD-ntzlHKcMG02XW9l",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/CjN_0SkxkBnrQZF5rYOl8/_buildManifest.js"
+      src="/_next/static/OMyCD-ntzlHKcMG02XW9l/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/CjN_0SkxkBnrQZF5rYOl8/_ssgManifest.js"
+      src="/_next/static/OMyCD-ntzlHKcMG02XW9l/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "CjN_0SkxkBnrQZF5rYOl8",
+        "buildId": "OMyCD-ntzlHKcMG02XW9l",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/CjN_0SkxkBnrQZF5rYOl8/_buildManifest.js"
+      src="/_next/static/OMyCD-ntzlHKcMG02XW9l/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/CjN_0SkxkBnrQZF5rYOl8/_ssgManifest.js"
+      src="/_next/static/OMyCD-ntzlHKcMG02XW9l/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 932a530e820a1dc047fadeef07df8d00c6174b75

File: packages/next/next-server/server/config-utils.ts (hunk 1 above)
Comment (ijjk) [reply packages/next/next-server/server/config-utils.ts:28]: This is run inside of a separate process so we need to load it separately here

**Review by timneutkens — APPROVED** [review]
