### PR TITLE
Fix IPv6 hostname formatting in CLI

### LINKED ISSUE #21979: IPv6 addresses not properly formatted when using `next dev`
**What version of Next.js are you using?**

10.0.6, 10.0.7-canary.6

**What version of Node.js are you using?**

15.8.0

**What browser are you using?**

Firefox, this is a CLI issue

**What operating system are you using?**

Windows

**How are you deploying your application?**

next dev -H :: , next start -H ::

**Describe the Bug**

When running `next dev` or ` next start` with an IPv6 host parameter, the "started server" message does not format URIs correctly

```
> next dev -H ::

ready - started server on :::3000, url: http://:::3000
```

**Expected Behavior**

```
> next dev -H ::

ready - started server on [::]:3000, url: http://[::1]:3000
```

**To Reproduce**

Run `next dev` or `next start` with an ipv6 address as the `-H` parameter

### PR DESCRIPTION
**Pull request by akshitsinha**
Checks if CLI `--hostname` parameter is an IPv6 IP address, and formats it correctly in `stdout`.

**Before** / **After**
Untitled

Fixes #21979

### CODE REVIEW

**Review by jankaifer — CHANGES_REQUESTED** [review]
Thanks for the PR, could you try adding tests covering this?
And it would be great if you could achieve this without the nested `? :` operators - it's a little hard to read.

File: packages/next/server/lib/start-server.ts [hunk 1]
```diff
@@ -60,10 +62,13 @@ export function startServer(opts: StartServerOptions) {
 
     server.on('listening', () => {
       const addr = server.address()
-      const hostname =
+      let hostname =
         !opts.hostname || opts.hostname === '0.0.0.0'
           ? 'localhost'
           : opts.hostname
+      if (isIPv6(hostname)) {
+        hostname = hostname === '::' ? `[${hostname}1]` : `[${hostname}]`
```
Comment (JanKaifer) [inline packages/next/server/lib/start-server.ts:70]:
```suggestion
        if (hostname === '::') hostname = '::1'
        hostname = `[${hostname}]`
```

**Review by jankaifer — CHANGES_REQUESTED** [review]
Thanks for following up. Just a small nitpick to make the intention a bit clearer and we are good to go.

File: packages/next/server/lib/start-server.ts (hunk 1 above)
Comment (akshitsinha) [reply packages/next/server/lib/start-server.ts]: Should be good now. 👍

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| buildDuration | 36.9s | 36.8s | -113ms |
| buildDurationCached | 10.2s | 11s | ⚠️ +797ms |
| nodeModulesSize | 95 MB | 95 MB | ⚠️ +2.44 kB |
| nextStartRea..uration (ms) | 276ms | 272ms | -4ms |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| 246.HASH.js gzip | 181 B | 181 B | ✓ |
| 437-HASH.js gzip | 64.5 kB | 64.5 kB | -6 B |
| main-app-HASH.js gzip | 206 B | 205 B | -1 B |
| main-HASH.js gzip | 79.1 kB | 79.1 kB | ✓ |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ⚠️ +1 B |
| Overall change | 146 kB | 146 kB | -6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 192 B | ✓ |
| _error-HASH.js gzip | 179 B | 178 B | -1 B |
| amp-HASH.js gzip | 482 B | 483 B | ⚠️ +1 B |
| css-HASH.js gzip | 803 B | 804 B | ⚠️ +1 B |
| dynamic-HASH.js gzip | 2.29 kB | 2.29 kB | -3 B |
| edge-ssr-HASH.js gzip | 259 B | 258 B | -1 B |
| head-HASH.js gzip | 830 B | 828 B | -2 B |
| hooks-HASH.js gzip | 850 B | 848 B | -2 B |
| image-HASH.js gzip | 4.25 kB | 4.25 kB | ✓ |
| index-HASH.js gzip | 253 B | 253 B | ✓ |
| link-HASH.js gzip | 2.68 kB | 2.68 kB | -3 B |
| routerDirect..HASH.js gzip | 781 B | 781 B | ✓ |
| script-HASH.js gzip | 859 B | 856 B | -3 B |
| withRouter-HASH.js gzip | 781 B | 781 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.6 kB | 15.6 kB | -13 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 483 B | -2 B |
| Overall change | 485 B | 483 B | -2 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| index.html gzip | 490 B | 490 B | ✓ |
| link.html gzip | 505 B | 505 B | ✓ |
| withRouter.html gzip | 484 B | 486 B | ⚠️ +2 B |
| Overall change | 1.48 kB | 1.48 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| edge-ssr.js gzip | 110 kB | 110 kB | -5 B |
| page.js gzip | 98.4 kB | 98.4 kB | -1 B |
| Overall change | 209 kB | 209 kB | -6 B |

</details>

<details>
<summary><strong>Middleware size</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 586 B | 585 B | -1 B |
| middleware-r..fest.js gzip | 145 B | 144 B | -1 B |
| middleware.js gzip | 27.2 kB | 27.2 kB | -1 B |
| edge-runtime..pack.js gzip | 1.83 kB | 1.83 kB | ✓ |
| Overall change | 29.7 kB | 29.7 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware-b..-manifest.js</strong></summary>

```diff
@@ -7,81 +7,81 @@ self.__BUILD_MANIFEST = {
     "static/BUILD_ID/_ssgManifest.js"
   ],
   rootMainFiles: [
-    "static/chunks/webpack-778ee737b42dbd09.js",
-    "static/chunks/437-ff60c979a5ae56b7.js",
-    "static/chunks/main-app-12a4424998444d69.js"
+    "static/chunks/webpack-078d588fd47873c4.js",
+    "static/chunks/745-3123b95ecb3ba326.js",
+    "static/chunks/main-app-1cfbd6c767615cfe.js"
   ],
   pages: {
     "/": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/index-72f4ed6964652f6a.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/index-a1c4d9d8497dbefb.js"
     ],
     "/_app": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/_app-02fdba2e11c62c3b.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/_app-b68f71a961b48916.js"
     ],
     "/_error": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/_error-c6d6c7c386122218.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/_error-a22ef5f48ba8184b.js"
     ],
     "/amp": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/amp-b62e7c28809c13e0.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/amp-eaaa44ffdc03cc2c.js"
     ],
     "/css": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
       "static/css/94fdbc56eafa2039.css",
-      "static/chunks/pages/css-860762b9808f5e42.js"
+      "static/chunks/pages/css-ce50591629177489.js"
     ],
     "/dynamic": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/dynamic-16c73801272b45fa.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/dynamic-fa1df0b4842534e4.js"
     ],
     "/edge-ssr": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/edge-ssr-a57e88de1ff426bd.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/edge-ssr-18640e2c6cb99ab4.js"
     ],
     "/head": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/head-b5894c626904a778.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/head-f756eefe15b9eed2.js"
     ],
     "/hooks": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/hooks-874b5779f127e436.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/hooks-74323ca92508884f.js"
     ],
     "/image": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/image-854b6400b5b29f63.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/image-a27f28e834bc3106.js"
     ],
     "/link": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/link-64f5c14f89f65607.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/link-2dd5f16503707acd.js"
     ],
     "/routerDirect": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/routerDirect-0be908911bf83c00.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/routerDirect-cdbb1d3e934b20a6.js"
     ],
     "/script": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/script-fa22c9b29b4b53ec.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/script-58920c0195960d69.js"
     ],
     "/withRouter": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/withRouter-9bdea6c06adf2771.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/withRouter-7121e5a8488cd783.js"
     ]
   },
   ampFirstPages: []
```
</details>
<details>
<summary>Diff for <strong>middleware-r..-manifest.js</strong></summary>

```diff
@@ -1,6 +1,6 @@
 self.__REACT_LOADABLE_MANIFEST = {
   "dynamic.js -> ../components/hello": {
-    id: 1246,
-    files: ["static/chunks/246.a0afad3905ddc3ff.js"]
+    id: 7363,
+    files: ["static/chunks/363.ab0825baf290f32b.js"]
   }
 };
```
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [826],
   {
-    /***/ 1675: /***/ (
+    /***/ 5653: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -14,7 +14,7 @@
       __webpack_require__.d(__webpack_exports__, {
         default: () =>
           /* binding */ next_middleware_loaderabsolutePagePath_private_next_root_dir_2Fmiddleware_js_page_2Fmiddleware_rootDir_2Ftmp_2Fnext_stats_2Fstats_app_matchers_
-      }); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/error.js
+      }); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/error.js
 
       class PageSignatureError extends Error {
         constructor({ page }) {
@@ -41,7 +41,7 @@
   Read more: https://nextjs.org/docs/messages/middleware-parse-user-agent
   `);
         }
-      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/utils.js
+      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/utils.js
 
       //# sourceMappingURL=error.js.map
       function fromNodeHeaders(object) {
@@ -157,7 +157,7 @@
             }
           );
         }
-      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/fetch-event.js
+      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/fetch-event.js
 
       //# sourceMappingURL=utils.js.map
       const responseSymbol = Symbol("response");
@@ -203,7 +203,7 @@
             page: this.sourcePage
           });
         }
-      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/i18n/detect-domain-locale.js
+      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/i18n/detect-domain-locale.js
 
       //# sourceMappingURL=fetch-event.js.map
       function detectDomainLocale(domainItems, hostname, detectedLocale) {
@@ -232,7 +232,7 @@
           }
         }
         return domainItem;
-      } //# sourceMappingURL=detect-domain-locale.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/remove-trailing-slash.js
+      } //# sourceMappingURL=detect-domain-locale.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/remove-trailing-slash.js
 
       /**
        * Removes the trailing slash for a given route or page path. Preserves the
@@ -242,7 +242,7 @@
        *   - `/` -> `/`
        */ function removeTrailingSlash(route) {
         return route.replace(/\/$/, "") || "/";
-      } //# sourceMappingURL=remove-trailing-slash.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/parse-path.js
+      } //# sourceMappingURL=remove-trailing-slash.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/parse-path.js
 
       /**
        * Given a path this function will find the pathname, query and hash and return
@@ -270,7 +270,7 @@
           query: "",
           hash: ""
         };
-      } //# sourceMappingURL=parse-path.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/add-path-prefix.js
+      } //# sourceMappingURL=parse-path.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/add-path-prefix.js
 
       /**
        * Adds the provided prefix to the given path. It first ensures that the path
@@ -281,7 +281,7 @@
         }
         const { pathname, query, hash } = parsePath(path);
         return `${prefix}${pathname}${query}${hash}`;
-      } //# sourceMappingURL=add-path-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/add-path-suffix.js
+      } //# sourceMappingURL=add-path-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/add-path-suffix.js
 
       /**
        * Similarly to `addPathPrefix`, this function adds a suffix at the end on the
@@ -293,7 +293,7 @@
         }
         const { pathname, query, hash } = parsePath(path);
         return `${pathname}${suffix}${query}${hash}`;
-      } //# sourceMappingURL=add-path-suffix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/path-has-prefix.js
+      } //# sourceMappingURL=add-path-suffix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/path-has-prefix.js
 
       /**
        * Checks if a given path starts with a given prefix. It ensures it matches
@@ -307,7 +307,7 @@
         }
         const { pathname } = parsePath(path);
         return pathname === prefix || pathname.startsWith(prefix + "/");
-      } //# sourceMappingURL=path-has-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/add-locale.js
+      } //# sourceMappingURL=path-has-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/add-locale.js
 
       /**
        * For a given path and a locale, if the locale is given, it will prefix the
@@ -324,7 +324,7 @@
           return addPathPrefix(path, `/${locale}`);
         }
         return path;
-      } //# sourceMappingURL=add-locale.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/format-next-pathname-info.js
+      } //# sourceMappingURL=add-locale.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/format-next-pathname-info.js
 
       function formatNextPathnameInfo(info) {
         let pathname = addLocale(
@@ -348,7 +348,7 @@
             ? addPathSuffix(pathname, "/")
             : pathname
           : removeTrailingSlash(pathname);
-      } //# sourceMappingURL=format-next-pathname-info.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/get-hostname.js
+      } //# sourceMappingURL=format-next-pathname-info.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/get-hostname.js
 
       /**
        * Takes an object with a hostname property (like a parsed URL) and some
@@ -363,7 +363,7 @@
           parsed.hostname) == null
           ? void 0
           : ref.split(":")[0].toLowerCase();
-      } //# sourceMappingURL=get-hostname.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/i18n/normalize-locale-path.js
+      } //# sourceMappingURL=get-hostname.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/i18n/normalize-locale-path.js
 
       /**
        * For a pathname that may include a locale from a list of locales, it
@@ -393,7 +393,7 @@
           pathname,
           detectedLocale
         };
-      } //# sourceMappingURL=normalize-locale-path.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/remove-path-prefix.js
+      } //# sourceMappingURL=normalize-locale-path.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/remove-path-prefix.js
 
       /**
        * Given a path and a prefix it will remove the prefix when it exists in the
@@ -409,7 +409,7 @@
             : `/${withoutPrefix}`;
         }
         return path;
-      } //# sourceMappingURL=remove-path-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/get-next-pathname-info.js
+      } //# sourceMappingURL=remove-path-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/get-next-pathname-info.js
 
       function getNextPathnameInfo(pathname, options) {
         var _nextConfig;
@@ -446,7 +446,7 @@
             info.pathname;
         }
         return info;
-      } //# sourceMappingURL=get-next-pathname-info.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/next-url.js
+      } //# sourceMappingURL=get-next-pathname-info.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/next-url.js
 
       const REGEX_LOCALHOST_HOSTNAME = /(?!^https?:\/\/)(127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}|::1|localhost)/;
       function parseURL(url, base) {
@@ -655,7 +655,7 @@
         clone() {
           return new NextURL(String(this), this[Internal].options);
         }
-      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/cookies/serialize.js
+      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/cookies/serialize.js
 
       //# sourceMappingURL=next-url.js.map
       const SAME_SITE = ["strict", "lax", "none"];
@@ -737,7 +737,7 @@
           })
         };
         return compact(cookie);
-      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/cookies/request-cookies.js
+      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/cookies/request-cookies.js
 
       //# sourceMappingURL=serialize.js.map
       /**
@@ -830,7 +830,7 @@
             Object.fromEntries(this._parsed)
           )}`;
         }
-      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/cookies/response-cookies.js
+      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/cookies/response-cookies.js
 
       //# sourceMappingURL=request-cookies.js.map
       function replace(bag, headers) {
@@ -925,7 +925,7 @@
             Object.fromEntries(this._parsed)
           )}`;
         }
-      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/cookies/index.js // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/request.js
+      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/cookies/index.js // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/request.js
 
       //# sourceMappingURL=response-cookies.js.map
       //# sourceMappingURL=index.js.map
@@ -1000,7 +1000,7 @@
         get url() {
           return this[INTERNALS].url.toString();
         }
-      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/response.js
+      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/response.js
 
       //# sourceMappingURL=request.js.map
       const response_INTERNALS = Symbol("internal response");
@@ -1100,7 +1100,7 @@
             headers
           });
         }
-      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/relativize-url.js
+      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/relativize-url.js
 
       //# sourceMappingURL=response.js.map
       /**
@@ -1114,7 +1114,7 @@
         return `${relative.protocol}//${relative.host}` === origin
           ? relative.toString().replace(origin, "")
           : relative.toString();
-      } //# sourceMappingURL=relativize-url.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/internal-utils.js
+      } //# sourceMappingURL=relativize-url.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/internal-utils.js
 
       const INTERNAL_QUERY_NAMES = [
         "__nextFallback",
@@ -1138,7 +1138,7 @@
           }
         }
         return searchParams;
-      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/app-paths.js
+      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/app-paths.js
 
       //# sourceMappingURL=internal-utils.js.map
       // remove (name) from pathname as it's not considered for routing
@@ -1162,7 +1162,7 @@
       }
       function normalizeRscPath(pathname, enabled) {
         return enabled ? pathname.replace(/\.rsc($|\?)/, "") : pathname;
-      } //# sourceMappingURL=app-paths.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/client/components/app-router-headers.js
+      } //# sourceMappingURL=app-paths.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/client/components/app-router-headers.js
 
       const RSC = "RSC";
       const NEXT_ROUTER_STATE_TREE = "Next-Router-State-Tree";
@@ -1173,7 +1173,7 @@
         [RSC],
         [NEXT_ROUTER_STATE_TREE],
         [NEXT_ROUTER_PREFETCH]
-      ]; //# sourceMappingURL=app-router-headers.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/adapter.js
+      ]; //# sourceMappingURL=app-router-headers.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/adapter.js
 
       class NextRequestHint extends NextRequest {
         constructor(params) {
@@ -1396,12 +1396,12 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           enumerable: false,
           configurable: false
         });
-      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/loaders/next-middleware-loader.js?absolutePagePath=private-next-root-dir%2Fmiddleware.js&page=%2Fmiddleware&rootDir=%2Ftmp%2Fnext-stats%2Fstats-app&matchers=!
+      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/loaders/next-middleware-loader.js?absolutePagePath=private-next-root-dir%2Fmiddleware.js&page=%2Fmiddleware&rootDir=%2Ftmp%2Fnext-stats%2Fstats-app&matchers=!
 
       //# sourceMappingURL=adapter.js.map
       enhanceGlobals();
 
-      var mod = __webpack_require__(1085);
+      var mod = __webpack_require__(8775);
       var handler = mod.middleware || mod.default;
 
       if (typeof handler !== "function") {
@@ -1425,7 +1425,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 1085: /***/ (
+    /***/ 8775: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -1437,7 +1437,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         /* harmony export */
       });
       /* harmony import */ var next_server__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
-        8352
+        9541
       );
       /* harmony import */ var next_server__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/ __webpack_require__.n(
         next_server__WEBPACK_IMPORTED_MODULE_0__
@@ -1450,7 +1450,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 4989: /***/ (__unused_webpack_module, exports) => {
+    /***/ 8239: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -1470,7 +1470,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 1962: /***/ (__unused_webpack_module, exports) => {
+    /***/ 7034: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -1508,7 +1508,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 6450: /***/ (__unused_webpack_module, exports) => {
+    /***/ 4375: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -1540,15 +1540,19 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 12: /***/ (__unused_webpack_module, exports, __webpack_require__) => {
+    /***/ 9312: /***/ (
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
       exports.addLocale = addLocale;
-      var _addPathPrefix = __webpack_require__(3120);
-      var _pathHasPrefix = __webpack_require__(3245);
+      var _addPathPrefix = __webpack_require__(623);
+      var _pathHasPrefix = __webpack_require__(3002);
       function addLocale(path, locale, defaultLocale, ignorePrefix) {
         if (
           locale &&
@@ -1568,7 +1572,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 3120: /***/ (
+    /***/ 623: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1579,7 +1583,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         value: true
       });
       exports.addPathPrefix = addPathPrefix;
-      var _parsePath = __webpack_require__(7718);
+      var _parsePath = __webpack_require__(5655);
       function addPathPrefix(path, prefix) {
         if (!path.startsWith("/") || !prefix) {
           return path;
@@ -1591,7 +1595,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 5839: /***/ (
+    /***/ 7928: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1602,7 +1606,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         value: true
       });
       exports.addPathSuffix = addPathSuffix;
-      var _parsePath = __webpack_require__(7718);
+      var _parsePath = __webpack_require__(5655);
       function addPathSuffix(path, suffix) {
         if (!path.startsWith("/") || !suffix) {
           return path;
@@ -1614,7 +1618,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 9364: /***/ (
+    /***/ 3580: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1625,10 +1629,10 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         value: true
       });
       exports.formatNextPathnameInfo = formatNextPathnameInfo;
-      var _removeTrailingSlash = __webpack_require__(9944);
-      var _addPathPrefix = __webpack_require__(3120);
-      var _addPathSuffix = __webpack_require__(5839);
-      var _addLocale = __webpack_require__(12);
+      var _removeTrailingSlash = __webpack_require__(7088);
+      var _addPathPrefix = __webpack_require__(623);
+      var _addPathSuffix = __webpack_require__(7928);
+      var _addLocale = __webpack_require__(9312);
       function formatNextPathnameInfo(info) {
         let pathname = (0, _addLocale).addLocale(
           info.pathname,
@@ -1659,7 +1663,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 9551: /***/ (
+    /***/ 1547: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1670,9 +1674,9 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         value: true
       });
       exports.getNextPathnameInfo = getNextPathnameInfo;
-      var _normalizeLocalePath = __webpack_require__(6450);
-      var _removePathPrefix = __webpack_require__(4933);
-      var _pathHasPrefix = __webpack_require__(3245);
+      var _normalizeLocalePath = __webpack_require__(4375);
+      var _removePathPrefix = __webpack_require__(5620);
+      var _pathHasPrefix = __webpack_require__(3002);
       function getNextPathnameInfo(pathname, options) {
         var _nextConfig;
         const { basePath, i18n, trailingSlash } =
@@ -1722,7 +1726,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 7718: /***/ (__unused_webpack_module, exports) => {
+    /***/ 5655: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -1756,7 +1760,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 3245: /***/ (
+    /***/ 3002: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1767,7 +1771,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         value: true
       });
       exports.pathHasPrefix = pathHasPrefix;
-      var _parsePath = __webpack_require__(7718);
+      var _parsePath = __webpack_require__(5655);
       function pathHasPrefix(path, prefix) {
         if (typeof path !== "string") {
           return false;
@@ -1779,7 +1783,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 4933: /***/ (
+    /***/ 5620: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -1790,7 +1794,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         value: true
       });
       exports.removePathPrefix = removePathPrefix;
-      var _pathHasPrefix = __webpack_require__(3245);
+      var _pathHasPrefix = __webpack_require__(3002);
       function removePathPrefix(path, prefix) {
         if ((0, _pathHasPrefix).pathHasPrefix(path, prefix)) {
           const withoutPrefix = path.slice(prefix.length);
@@ -1804,7 +1808,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 9944: /***/ (__unused_webpack_module, exports) => {
+    /***/ 7088: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -1818,7 +1822,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 6166: /***/ (module, exports, __webpack_require__) => {
+    /***/ 6204: /***/ (module, exports, __webpack_require__) => {
       var __dirname = "/";
       var __WEBPACK_AMD_DEFINE_RESULT__;
       (() => {
@@ -2660,7 +2664,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 4524: /***/ (__unused_webpack_module, exports) => {
+    /***/ 8666: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -2701,7 +2705,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 3062: /***/ (
+    /***/ 4901: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -2711,10 +2715,10 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
-      var _detectDomainLocale = __webpack_require__(1962);
-      var _formatNextPathnameInfo = __webpack_require__(9364);
-      var _getHostname = __webpack_require__(4989);
-      var _getNextPathnameInfo = __webpack_require__(9551);
+      var _detectDomainLocale = __webpack_require__(7034);
+      var _formatNextPathnameInfo = __webpack_require__(3580);
+      var _getHostname = __webpack_require__(8239);
+      var _getNextPathnameInfo = __webpack_require__(1547);
       const REGEX_LOCALHOST_HOSTNAME = /(?!^https?:\/\/)(127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}|::1|localhost)/;
       function parseURL(url, base) {
         return new URL(
@@ -2934,7 +2938,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 6915: /***/ (
+    /***/ 4580: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -2956,15 +2960,15 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           return _responseCookies.ResponseCookies;
         }
       });
-      var _requestCookies = __webpack_require__(6079);
-      var _responseCookies = __webpack_require__(9442);
+      var _requestCookies = __webpack_require__(7205);
+      var _responseCookies = __webpack_require__(9618);
 
       //# sourceMappingURL=index.js.map
 
       /***/
     },
 
-    /***/ 6079: /***/ (
+    /***/ 7205: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -2974,7 +2978,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
-      var _serialize = __webpack_require__(8213);
+      var _serialize = __webpack_require__(8477);
       class RequestCookies {
         _parsed = new Map();
         constructor(requestHeaders) {
@@ -3071,7 +3075,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 9442: /***/ (
+    /***/ 9618: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -3081,7 +3085,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
-      var _serialize = __webpack_require__(8213);
+      var _serialize = __webpack_require__(8477);
       function replace(bag, headers) {
         headers.delete("set-cookie");
         for (const [, value] of bag) {
@@ -3178,7 +3182,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 8213: /***/ (__unused_webpack_module, exports) => {
+    /***/ 8477: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -3269,7 +3273,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 5829: /***/ (
+    /***/ 5985: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -3281,10 +3285,10 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         value: true
       };
       __webpack_unused_export__ = void 0;
-      var _nextUrl = __webpack_require__(3062);
-      var _utils = __webpack_require__(88);
-      var _error = __webpack_require__(4524);
-      var _cookies = __webpack_require__(6915);
+      var _nextUrl = __webpack_require__(4901);
+      var _utils = __webpack_require__(30);
+      var _error = __webpack_require__(8666);
+      var _cookies = __webpack_require__(4580);
       const INTERNALS = Symbol("internal request");
       __webpack_unused_export__ = INTERNALS;
       class NextRequest extends Request {
@@ -3365,7 +3369,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 5277: /***/ (
+    /***/ 5165: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -3376,9 +3380,9 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       __webpack_unused_export__ = {
         value: true
       };
-      var _nextUrl = __webpack_require__(3062);
-      var _utils = __webpack_require__(88);
-      var _cookies = __webpack_require__(6915);
+      var _nextUrl = __webpack_require__(4901);
+      var _utils = __webpack_require__(30);
+      var _cookies = __webpack_require__(4580);
       const INTERNALS = Symbol("internal response");
       const REDIRECTS = new Set([301, 302, 303, 307, 308]);
       function handleMiddlewareField(init, headers) {
@@ -3487,7 +3491,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 7873: /***/ (
+    /***/ 9132: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -3501,7 +3505,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       __webpack_unused_export__ = isBot;
       exports.Nf = userAgentFromString;
       exports.WE = userAgent;
-      var _uaParserJs = _interopRequireDefault(__webpack_require__(6166));
+      var _uaParserJs = _interopRequireDefault(__webpack_require__(6204));
       function _interopRequireDefault(obj) {
         return obj && obj.__esModule
           ? obj
@@ -3529,7 +3533,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 88: /***/ (__unused_webpack_module, exports) => {
+    /***/ 30: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -3646,14 +3650,14 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 8352: /***/ (module, exports, __webpack_require__) => {
+    /***/ 9541: /***/ (module, exports, __webpack_require__) => {
       const serverExports = {
-        NextRequest: __webpack_require__(5829) /* .NextRequest */.Im,
-        NextResponse: __webpack_require__(5277) /* .NextResponse */.x,
+        NextRequest: __webpack_require__(5985) /* .NextRequest */.Im,
+        NextResponse: __webpack_require__(5165) /* .NextResponse */.x,
         userAgentFromString: __webpack_require__(
-          7873
+          9132
         ) /* .userAgentFromString */.Nf,
-        userAgent: __webpack_require__(7873) /* .userAgent */.WE
+        userAgent: __webpack_require__(9132) /* .userAgent */.WE
       };
 
       if (typeof URLPattern !== "undefined") {
@@ -3679,7 +3683,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = moduleId =>
       __webpack_require__((__webpack_require__.s = moduleId));
-    /******/ var __webpack_exports__ = __webpack_exec__(1675);
+    /******/ var __webpack_exports__ = __webpack_exec__(5653);
     /******/ (_ENTRIES =
       typeof _ENTRIES === "undefined"
         ? {}
```
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,28 +1,28 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-72f4ed6964652f6a.js"],
-  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-c6d6c7c386122218.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-b62e7c28809c13e0.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-a1c4d9d8497dbefb.js"],
+  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-a22ef5f48ba8184b.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-eaaa44ffdc03cc2c.js"],
   "/css": [
     "static\u002Fcss\u002F94fdbc56eafa2039.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-860762b9808f5e42.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-ce50591629177489.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-16c73801272b45fa.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-fa1df0b4842534e4.js"
   ],
   "/edge-ssr": [
-    "static\u002Fchunks\u002Fpages\u002Fedge-ssr-a57e88de1ff426bd.js"
+    "static\u002Fchunks\u002Fpages\u002Fedge-ssr-18640e2c6cb99ab4.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-b5894c626904a778.js"],
-  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-874b5779f127e436.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-854b6400b5b29f63.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-64f5c14f89f65607.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-f756eefe15b9eed2.js"],
+  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-74323ca92508884f.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-a27f28e834bc3106.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-2dd5f16503707acd.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-0be908911bf83c00.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-cdbb1d3e934b20a6.js"
   ],
-  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-fa22c9b29b4b53ec.js"],
+  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-58920c0195960d69.js"],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-9bdea6c06adf2771.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-7121e5a8488cd783.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 3115: /***/ function(
+    /***/ 1113: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_app",
         function() {
-          return __webpack_require__(5791);
+          return __webpack_require__(9203);
         }
       ]);
       if (false) {
@@ -24,7 +24,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [179], function() {
-      return __webpack_exec__(3115), __webpack_exec__(8995);
+      return __webpack_exec__(1113), __webpack_exec__(2830);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [820],
   {
-    /***/ 5374: /***/ function(
+    /***/ 3363: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_error",
         function() {
-          return __webpack_require__(9437);
+          return __webpack_require__(169);
         }
       ]);
       if (false) {
@@ -24,7 +24,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function() {
-      return __webpack_exec__(5374);
+      return __webpack_exec__(3363);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>amp-HASH.js</strong></summary>

```diff
@@ -1,17 +1,17 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [216],
   {
-    /***/ 8510: /***/ function(
+    /***/ 8753: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(6146);
+      module.exports = __webpack_require__(893);
 
       /***/
     },
 
-    /***/ 7010: /***/ function(
+    /***/ 5348: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -19,7 +19,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/amp",
         function() {
-          return __webpack_require__(2725);
+          return __webpack_require__(1542);
         }
       ]);
       if (false) {
@@ -28,7 +28,7 @@
       /***/
     },
 
-    /***/ 6146: /***/ function(module, exports, __webpack_require__) {
+    /***/ 893: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -37,9 +37,9 @@
       exports.useAmp = useAmp;
       var _interop_require_default = __webpack_require__(1322) /* ["default"] */
         .Z;
-      var _react = _interop_require_default(__webpack_require__(2947));
-      var _ampContext = __webpack_require__(7298);
-      var _ampMode = __webpack_require__(3798);
+      var _react = _interop_require_default(__webpack_require__(465));
+      var _ampContext = __webpack_require__(2218);
+      var _ampMode = __webpack_require__(3734);
       function useAmp() {
         // Don't assign the context value to a variable to save bytes
         return (0, _ampMode).isInAmpMode(
@@ -61,7 +61,7 @@
       /***/
     },
 
-    /***/ 2725: /***/ function(
+    /***/ 1542: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -78,7 +78,7 @@
         /* harmony export */
       });
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
-        8510
+        8753
       );
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/ __webpack_require__.n(
         next_amp__WEBPACK_IMPORTED_MODULE_0__
@@ -102,7 +102,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function() {
-      return __webpack_exec__(7010);
+      return __webpack_exec__(5348);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>css-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [706],
   {
-    /***/ 860: /***/ function(
+    /***/ 6437: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/css",
         function() {
-          return __webpack_require__(2998);
+          return __webpack_require__(5892);
         }
       ]);
       if (false) {
@@ -18,14 +18,14 @@
       /***/
     },
 
-    /***/ 5189: /***/ function(module) {
+    /***/ 2501: /***/ function(module) {
       // extracted by mini-css-extract-plugin
       module.exports = { helloWorld: "css_helloWorld__qqNwY" };
 
       /***/
     },
 
-    /***/ 2998: /***/ function(
+    /***/ 5892: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -33,10 +33,10 @@
       "use strict";
       __webpack_require__.r(__webpack_exports__);
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
-        3268
+        9701
       );
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        5189
+        2501
       );
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         _css_module_css__WEBPACK_IMPORTED_MODULE_1__
@@ -56,7 +56,7 @@
       /***/
     },
 
-    /***/ 6205: /***/ function(
+    /***/ 1963: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -71,7 +71,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      var f = __webpack_require__(2947),
+      var f = __webpack_require__(465),
         k = Symbol.for("react.element"),
         l = Symbol.for("react.fragment"),
         m = Object.prototype.hasOwnProperty,
@@ -106,7 +106,7 @@
       /***/
     },
 
-    /***/ 3268: /***/ function(
+    /***/ 9701: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
@@ -114,7 +114,7 @@
       "use strict";
 
       if (true) {
-        module.exports = __webpack_require__(6205);
+        module.exports = __webpack_require__(1963);
       } else {
       }
 
@@ -127,7 +127,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function() {
-      return __webpack_exec__(860);
+      return __webpack_exec__(6437);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [739],
   {
-    /***/ 3995: /***/ function(
+    /***/ 7753: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/dynamic",
         function() {
-          return __webpack_require__(9780);
+          return __webpack_require__(685);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 3685: /***/ function(
+    /***/ 3831: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -32,8 +32,8 @@
       exports.suspense = suspense;
       var _interop_require_default = __webpack_require__(1322) /* ["default"] */
         .Z;
-      var _react = _interop_require_default(__webpack_require__(2947));
-      var _noSsrError = __webpack_require__(8763);
+      var _react = _interop_require_default(__webpack_require__(465));
+      var _noSsrError = __webpack_require__(3298);
       function NoSSR(param) {
         let { children } = param;
         if (false) {
@@ -49,7 +49,7 @@
       /***/
     },
 
-    /***/ 4648: /***/ function(module, exports, __webpack_require__) {
+    /***/ 9809: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -63,9 +63,9 @@
       var _interop_require_wildcard = __webpack_require__(
         6687
       ) /* ["default"] */.Z;
-      var _react = _interop_require_wildcard(__webpack_require__(2947));
-      var _loadable = _interop_require_default(__webpack_require__(7007));
-      var _dynamicNoSsr = _interop_require_default(__webpack_require__(3685));
+      var _react = _interop_require_wildcard(__webpack_require__(465));
+      var _loadable = _interop_require_default(__webpack_require__(7936));
+      var _dynamicNoSsr = _interop_require_default(__webpack_require__(3831));
       function dynamic(dynamicOptions, options) {
         let loadableFn = _loadable.default;
         let loadableOptions = {
@@ -170,7 +170,7 @@
       /***/
     },
 
-    /***/ 1446: /***/ function(
+    /***/ 9851: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -183,7 +183,7 @@
       exports.LoadableContext = void 0;
       var _interop_require_default = __webpack_require__(1322) /* ["default"] */
         .Z;
-      var _react = _interop_require_default(__webpack_require__(2947));
+      var _react = _interop_require_default(__webpack_require__(465));
       const LoadableContext = _react.default.createContext(null);
       exports.LoadableContext = LoadableContext;
       if (false) {
@@ -192,7 +192,7 @@
       /***/
     },
 
-    /***/ 7007: /***/ function(
+    /***/ 7936: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -206,8 +206,8 @@
       var _extends = __webpack_require__(5321) /* ["default"] */.Z;
       var _interop_require_default = __webpack_require__(1322) /* ["default"] */
         .Z;
-      var _react = _interop_require_default(__webpack_require__(2947));
-      var _loadableContext = __webpack_require__(1446);
+      var _react = _interop_require_default(__webpack_require__(465));
+      var _loadableContext = __webpack_require__(9851);
       const ALL_INITIALIZERS = [];
       const READY_INITIALIZERS = [];
       let initialized = false;
@@ -426,7 +426,7 @@
       /***/
     },
 
-    /***/ 9780: /***/ function(
+    /***/ 685: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -440,10 +440,10 @@
         /* harmony export */
       });
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
-        3268
+        9701
       );
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        6113
+        2677
       );
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_dynamic__WEBPACK_IMPORTED_MODULE_1__
@@ -452,11 +452,11 @@
       const DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
         () =>
           __webpack_require__
-            .e(/* import() */ 246)
-            .then(__webpack_require__.bind(__webpack_require__, 1246)),
+            .e(/* import() */ 363)
+            .then(__webpack_require__.bind(__webpack_require__, 7363)),
         {
           loadableGenerated: {
-            webpack: () => [/*require.resolve*/ 1246]
+            webpack: () => [/*require.resolve*/ 7363]
           }
         }
       );
@@ -483,7 +483,7 @@
       /***/
     },
 
-    /***/ 6205: /***/ function(
+    /***/ 1963: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -498,7 +498,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      var f = __webpack_require__(2947),
+      var f = __webpack_require__(465),
         k = Symbol.for("react.element"),
         l = Symbol.for("react.fragment"),
         m = Object.prototype.hasOwnProperty,
@@ -533,7 +533,7 @@
       /***/
     },
 
-    /***/ 3268: /***/ function(
+    /***/ 9701: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
@@ -541,19 +541,19 @@
       "use strict";
 
       if (true) {
-        module.exports = __webpack_require__(6205);
+        module.exports = __webpack_require__(1963);
       } else {
       }
 
       /***/
     },
 
-    /***/ 6113: /***/ function(
+    /***/ 2677: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(4648);
+      module.exports = __webpack_require__(9809);
 
       /***/
     }
@@ -564,7 +564,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function() {
-      return __webpack_exec__(3995);
+      return __webpack_exec__(7753);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>edge-ssr-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [800],
   {
-    /***/ 6219: /***/ function(
+    /***/ 6027: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/edge-ssr",
         function() {
-          return __webpack_require__(5260);
+          return __webpack_require__(699);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 5260: /***/ function(
+    /***/ 699: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -50,7 +50,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function() {
-      return __webpack_exec__(6219);
+      return __webpack_exec__(6027);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>head-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [645],
   {
-    /***/ 2899: /***/ function(
+    /***/ 6955: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/head",
         function() {
-          return __webpack_require__(6603);
+          return __webpack_require__(8620);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 6603: /***/ function(
+    /***/ 8620: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -32,10 +32,10 @@
         /* harmony export */
       });
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
-        3268
+        9701
       );
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        8412
+        9046
       );
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         next_head__WEBPACK_IMPORTED_MODULE_1__
@@ -69,7 +69,7 @@
       /***/
     },
 
-    /***/ 6205: /***/ function(
+    /***/ 1963: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -84,7 +84,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      var f = __webpack_require__(2947),
+      var f = __webpack_require__(465),
         k = Symbol.for("react.element"),
         l = Symbol.for("react.fragment"),
         m = Object.prototype.hasOwnProperty,
@@ -119,7 +119,7 @@
       /***/
     },
 
-    /***/ 3268: /***/ function(
+    /***/ 9701: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
@@ -127,19 +127,19 @@
       "use strict";
 
       if (true) {
-        module.exports = __webpack_require__(6205);
+        module.exports = __webpack_require__(1963);
       } else {
       }
 
       /***/
     },
 
-    /***/ 8412: /***/ function(
+    /***/ 9046: /***/ function(
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(9461);
+      module.exports = __webpack_require__(2483);
 
       /***/
     }
@@ -150,7 +150,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function() {
-      return __webpack_exec__(2899);
+      return __webpack_exec__(6955);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>hooks-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [757],
   {
-    /***/ 2304: /***/ function(
+    /***/ 7819: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/hooks",
         function() {
-          return __webpack_require__(8586);
+          return __webpack_require__(708);
         }
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 8586: /***/ function(
+    /***/ 708: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -26,10 +26,10 @@
       "use strict";
       __webpack_require__.r(__webpack_exports__);
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
-        3268
+        9701
       );
       /* harmony import */ var react__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        2947
+        465
       );
 
       /* harmony default export */ __webpack_exports__["defau
Post job cleanup.
[command]/usr/bin/git version
git version 2.38.2
Temporarily overriding HOME='/home/runner/work/_temp/6dd40a6c-d822-4674-96ad-4860ae079ae1' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
[command]/usr/bin/git config --global --add safe.directory /home/runner/work/next.js/next.js
[command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
[command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
[command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
[command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
[command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
Cleaning up orphan processes
Commit: 3c4eaa5264e98417eb439517aae32952b8181b05

**Review by jankaifer — DISMISSED** [review]

**Comment by akshitsinha** [comment]
I've resolved any merge conflicts of the past few weeks. Let me know if I'm missing anything for this to be merged. Thanks.

File: packages/next/src/cli/next-dev.ts [hunk 2]
```diff
@@ -403,7 +404,11 @@ If you cannot make the changes above, but still want to try out\nNext.js v13 wit
       startServer(devServerOptions)
         .then(async (app) => {
           const appUrl = `http://${app.hostname}:${app.port}`
```
Comment (JanKaifer) [inline packages/next/src/cli/next-dev.ts:406]: We don't need to change this?

**Review by jankaifer — COMMENTED** [review]
Hey sorry it's taking so long. I'll make sure we merge this quickly.

File: packages/next/src/cli/next-dev.ts (hunk 2 above)
Comment (JanKaifer) [reply packages/next/src/cli/next-dev.ts:406]: Great. lets <picture data-single-emoji=":shipit:" title=":shipit:">:shipit:</picture>

**Review by timneutkens — APPROVED** [review]
Looks good!
