### PR TITLE
docs: update `revalidatePath` & fix cache debug logic

### LINKED ISSUE #62071: `revalidatePath` with `type = "layout" | "page"` does not invalidate the data cache
### Link to the code that reproduces this issue

https://github.com/juliesaia/revalidate-path-test

### To Reproduce

1. next dev
2. Click revalidate dynamic route (page) or (layout)
3. Wait 5 seconds, click revalidate dynamic route again
4. Click link to dynamic route, verify that server (rendered) time and fetched (external from API) are not in sync

### Current vs. Expected behavior

`revalidatePath("/dynamic/1", "layout")` should invalidate the cached result from `fetch`. Without this functionality, it's impossible to invalidate a subset of paths.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Thu Oct 5 21:02:42 UTC 2023
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.54 // Latest available version is detected (14.1.1-canary.54).
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed)

### Additional context

_No response_

<sub>[NEXT-3302](https://linear.app/vercel/issue/NEXT-3302/revalidatepath-with-type-=-layout-or-page-does-not-invalidate-the-data)</sub>

### PR DESCRIPTION
**Pull request by ztanner**
When revalidating a page that corresponds with a dynamic path and when using the “type” parameter, eg `revalidatePath(“/dynamic/1”, “page”)` corresponding with `/dynamic/[id]`, the wrong cache tags would be checked to determine if a revalidation occurred.

This is because the “derived” cache tags created for a `/dynamic/[id]/page` are: 
- /dynamic/[id]/layout
- /dynamic/[id]/page

Additionally, a tag is added for the current canonical URL, so the final tag would be:
- /dynamic/1

Thus a fetch on `/dynamic/1` would be tagged with the following:
- /layout
- /dynamic/layout
- /dynamic/[id]/layout
- /dynamic/[id]/page
- /dynamic/1

Calling `revalidatePath(“/dynamic/1”, “page”)` would signal to revalidate caches tagged `/dynamic/1/page` in the current logic. However, this tag doesn’t exist given the above, so it would be a no-op and wouldn't properly re-invoke the fetch. 

This updates the docs to explicitly call out that if you are attempting to revalidate a path that corresponds with a dynamic page, that you should not provide a "type" argument. 

Fixes #62071
Closes NEXT-3302

### CODE REVIEW

**Comment by ztanner** [comment]
* **#65365** <a href="https://app.graphite.dev/github/pr/vercel/next.js/65365?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ztanner and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 50c7a7c9fcbc79f3d4c83a0ab99a9d8035f09f8a

`pnpm test test/integration/edge-runtime-module-errors/test/module-imports.test.js`
- Edge runtime code with imports > Edge API statically importing node.js module > throws unsupported module error in dev at runtime and highlights the faulty line

<details>
<summary>Expand output</summary>

  ● Edge runtime code with imports › Edge API statically importing node.js module › throws unsupported module error in dev at runtime and highlights the faulty line

    expect(received).toBe(expected) // Object.is equality

    Expected: 500
    Received: 404

      86 |       context.app = await launchApp(context.appDir, context.appPort, appOption)
      87 |       const res = await fetchViaHTTP(context.appPort, url)
    > 88 |       expect(res.status).toBe(500)
         |                          ^
      89 |
      90 |       const text = await res.text()
      91 |       await check(async () => {

      at Object.toBe (integration/edge-runtime-module-errors/test/module-imports.test.js:88:26)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: packages/next/src/server/lib/incremental-cache/file-system-cache.ts [hunk 1]
```diff
@@ -50,31 +50,33 @@ export default class FileSystemCache implements CacheHandler {
     this.experimental = ctx.experimental
     this.debug = !!process.env.NEXT_PRIVATE_DEBUG_CACHE
 
-    if (ctx.maxMemoryCacheSize && !memoryCache) {
-      if (this.debug) {
-        console.log('using memory store for fetch cache')
-      }
+    if (ctx.maxMemoryCacheSize) {
+      if (!memoryCache) {
```
Comment (ztanner) [inline packages/next/src/server/lib/incremental-cache/file-system-cache.ts:54]: This change should be reviewed without whitespace. I updated this to be consistent with how it's structured in fetch-cache, to prevent debug mode from printing:

> not using memory store for fetch cache

Even though it was, because the memory cache had already been instantiated.

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 05-04-fix_ensure_revalidatePath_consistently_revalidates_fetches_on_dynamic_routes | Change |
| - | - | - | - |
| buildDuration | 15.2s | 14s | N/A |
| buildDurationCached | 8.2s | 7.1s | N/A |
| nodeModulesSize | 360 MB | 360 MB | ⚠️ +5.72 kB |
| nextStartRea..uration (ms) | 409ms | 412ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 05-04-fix_ensure_revalidatePath_consistently_revalidates_fetches_on_dynamic_routes | Change |
| - | - | - | - |
| 1103-HASH.js gzip | 31.9 kB | 31.9 kB | N/A |
| 1a9f679d-HASH.js gzip | 53.5 kB | 53.5 kB | N/A |
| 335-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| 7953.HASH.js gzip | 169 B | 169 B | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 231 B | 228 B | N/A |
| main-HASH.js gzip | 31.6 kB | 31.6 kB | N/A |
| webpack-HASH.js gzip | 1.65 kB | 1.65 kB | N/A |
| Overall change | 50.4 kB | 50.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 05-04-fix_ensure_revalidatePath_consistently_revalidates_fetches_on_dynamic_routes | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 05-04-fix_ensure_revalidatePath_consistently_revalidates_fetches_on_dynamic_routes | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 193 B | N/A |
| _error-HASH.js gzip | 192 B | 193 B | N/A |
| amp-HASH.js gzip | 507 B | 511 B | N/A |
| css-HASH.js gzip | 341 B | 343 B | N/A |
| dynamic-HASH.js gzip | 2.52 kB | 2.52 kB | ✓ |
| edge-ssr-HASH.js gzip | 266 B | 265 B | N/A |
| head-HASH.js gzip | 362 B | 365 B | N/A |
| hooks-HASH.js gzip | 392 B | 392 B | ✓ |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | ✓ |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.69 kB | 2.7 kB | N/A |
| routerDirect..HASH.js gzip | 329 B | 328 B | N/A |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 324 B | 324 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 8.27 kB | 8.27 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 05-04-fix_ensure_revalidatePath_consistently_revalidates_fetches_on_dynamic_routes | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 05-04-fix_ensure_revalidatePath_consistently_revalidates_fetches_on_dynamic_routes | Change |
| - | - | - | - |
| index.html gzip | 528 B | 528 B | ✓ |
| link.html gzip | 540 B | 540 B | ✓ |
| withRouter.html gzip | 523 B | 524 B | N/A |
| Overall change | 1.07 kB | 1.07 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 05-04-fix_ensure_revalidatePath_consistently_revalidates_fetches_on_dynamic_routes | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94.8 kB | 94.8 kB | N/A |
| page.js gzip | 182 kB | 182 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 05-04-fix_ensure_revalidatePath_consistently_revalidates_fetches_on_dynamic_routes | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 623 B | 623 B | ✓ |
| middleware-r..fest.js gzip | 156 B | 156 B | ✓ |
| middleware.js gzip | 25.7 kB | 25.7 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 05-04-fix_ensure_revalidatePath_consistently_revalidates_fetches_on_dynamic_routes | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | ✓ |
| app-page-exp..prod.js gzip | 98.8 kB | 98.8 kB | ✓ |
| app-page-tur..prod.js gzip | 100 kB | 100 kB | ✓ |
| app-page-tur..prod.js gzip | 94.6 kB | 94.6 kB | ✓ |
| app-page.run...dev.js gzip | 157 kB | 157 kB | ✓ |
| app-page.run..prod.js gzip | 93.3 kB | 93.3 kB | ✓ |
| app-route-ex...dev.js gzip | 21.5 kB | 21.5 kB | ✓ |
| app-route-ex..prod.js gzip | 15.3 kB | 15.3 kB | ✓ |
| app-route-tu..prod.js gzip | 15.3 kB | 15.3 kB | ✓ |
| app-route-tu..prod.js gzip | 15 kB | 15 kB | ✓ |
| app-route.ru...dev.js gzip | 21.3 kB | 21.3 kB | ✓ |
| app-route.ru..prod.js gzip | 15 kB | 15 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 21.5 kB | 21.5 kB | ✓ |
| pages.runtim...dev.js gzip | 22.1 kB | 22.1 kB | ✓ |
| pages.runtim..prod.js gzip | 21.5 kB | 21.5 kB | ✓ |
| server.runti..prod.js gzip | 51.7 kB | 51.6 kB | N/A |
| Overall change | 912 kB | 912 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 05-04-fix_ensure_revalidatePath_consistently_revalidates_fetches_on_dynamic_routes | Change |
| - | - | - | - |
| 0.pack gzip | 1.62 MB | 1.62 MB | ⚠️ +1.22 kB |
| index.pack gzip | 113 kB | 114 kB | ⚠️ +1.42 kB |
| Overall change | 1.73 MB | 1.74 MB | ⚠️ +2.64 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 50c7a7c9fcbc79f3d4c83a0ab99a9d8035f09f8a

File: packages/next/src/server/web/spec-extension/revalidate.ts [hunk 2]
```diff
@@ -31,12 +31,21 @@ export function revalidatePath(originalPath: string, type?: 'layout' | 'page') {
...
-  if (type) {
-    normalizedPath += `${normalizedPath.endsWith('/') ? '' : '/'}${type}`
-  } else if (isDynamicRoute(originalPath)) {
-    console.warn(
-      `Warning: a dynamic page path "${originalPath}" was passed to "revalidatePath", but the "type" parameter is missing. This has no effect by default, see more info here https://nextjs.org/docs/app/api-reference/functions/revalidatePath`
-    )
+  // A static route should not have a type, because a cache tag belonging to a dynamic
+  // page won't ever be tagged with `/page` or `/layout` -- it'd just be the canonical URL.
+  // We only append the type in the dynamic case, or for the root layout.
+  if (isDynamicRoute(originalPath)) {
```
Comment (ijjk) [inline packages/next/src/server/web/spec-extension/revalidate.ts:37]: Maybe we add a note about this in the docs as well https://nextjs.org/docs/app/api-reference/functions/revalidatePath

**Review by ijjk — APPROVED** [review]
