### PR TITLE
Wait for pending Webpack Hot Updates before evaluating JS from RSC responses

### LINKED ISSUE #67783: create-next-app (canary): Import of *.module.scss in Client Component causes `__webpack_require__.n is not a function` crash
### Link to the code that reproduces this issue

https://github.com/karlhorky/repro-next-js-v15-react-rc-0-sass-webpack-require-not-a-function

### To Reproduce

1. Clone the reproduction repo above (see reproduction repo setup steps below)
2. Start the app in development (`next dev`)
3. Click on the link to navigate to the `/non-home` page
4. Observe the error (if the error doesn't appear, it's possible that webpack reloaded the page for you automatically - ` ⚠ Fast Refresh had to perform a full reload due to a runtime error.` warning in the terminal as seen in the video - you may need to repeat step 2 and 3 a few times to see the page-blocking warning):

```
TypeError: __webpack_require__.n is not a function
    at eval (ClientComponent.tsx:7:127)
    at (app-pages-browser)/app/ClientComponent.tsx (http://localhost:3000/_next/static/chunks/app/non-home/page.js:48:1)
    at options.factory (webpack.js?v=1721063046656:701:31)
    at __webpack_require__ (webpack.js?v=1721063046656:37:33)
    at fn (webpack.js?v=1721063046656:357:21)
    at requireAsyncModule (react-server-dom-webpack-client.browser.development.js:143:17)
    at eval (react-server-dom-webpack-client.browser.development.js:198:16)

The above error occurred in the <NotFoundErrorBoundary> component.

React will try to recreate this component tree from scratch using the error boundary you provided, ReactDevOverlay.

    at Lazy
    at NonHome (Server)
    at InnerLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:229:11)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:327:11)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/error-boundary.js:160:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:139:9)
    at ScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:214:11)
    at RenderFromTemplateContext (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at OuterLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:348:11)
    at InnerLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:229:11)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:327:11)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/error-boundary.js:160:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:139:9)
    at ScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:214:11)
    at RenderFromTemplateContext (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at OuterLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:348:11)
    at body
    at html
    at RootLayout (Server)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at DevRootNotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/dev-root-not-found-boundary.js:33:11)
    at ReactDevOverlay (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/react-dev-overlay/app/ReactDevOverlay.js:87:9)
    at HotReload (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js:344:11)
    at Router (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/app-router.js:156:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/error-boundary.js:113:9)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/error-boundary.js:160:11)
    at AppRouter (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/app-router.js:551:11)
    at ServerRoot (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/app-index.js:143:46)
    at Root (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/app-index.js:151:11)
```

Screenshot 2024-07-15 at 19 16 14

https://github.com/user-attachments/assets/d832814f-cc72-4945-911e-ffffeed05a52

#### Reproduction setup steps

How the reproduction repo was created:

1. Use `create-next-app` with TypeScript - adds `react@19.0.0-rc.0` and `react-dom@19.0.0-rc.0`
2. Remove starter content from pages and layout
3. `pnpm add sass`
6. Add a `non-home/page.tsx`
7. Create `ClientComponent.tsx` and `ClientComponent.module.scss` with `'use client'`
8. Import `<ClientComponent>` in `non-home/page.tsx`
9. Link to `/non-home` from `app/page.tsx` using `next/link`

### Current vs. Expected behavior

I expected no error when using `next/link` to navigate to a Client Component with a `*.module.scss` import, but I observed an error

Maybe the `canary` template for `create-next-app` needs to be updated to the `react@19.0.0-rc-6f23540c7d-20240528` and `react-dom@19.0.0-rc-6f23540c7d-20240528` versions

While this demo does not crash with a page-blocking error very often (as seen in the video) more complicated apps crash consistently.

### Provide environment information

```bash
Node.js v20.15.0

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.15.0
  npm: 10.7.0
  Yarn: N/A
  pnpm: 9.5.0
Relevant Packages:
  next: 15.0.0-canary.67 // Latest available version is detected (15.0.0-canary.67).
  eslint-config-next: N/A
  react: 19.0.0-rc.0
  react-dom: 19.0.0-rc.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app, Navigation, Webpack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Updating to the `react@19.0.0-rc-6f23540c7d-20240528` and `react-dom@19.0.0-rc-6f23540c7d-20240528` versions as are in [the App Router reproduction template](https://github.com/vercel/next.js/tree/canary/examples/reproduction-template)

But most users using `create-next-app@canary` will not know to do this.

### PR DESCRIPTION
**Pull request by eps1lon**
The Webpack runtime always tries to be minimal.
Since all pages share the same chunk, the prod runtime supports all pages.
However, in dev, the webpack runtime only supports the current page.

If we navigate to a new page, the Webpack runtime may need more functionality. Previously, we eagerly evaluated the RSC payload before any Hot Update was applied. This could lead to type errors (e.g. most notably `TypeError: __webpack_require__.n is not a function`).

For RSC payloads specifically, we just fell back to an MPA navigation.
We could continue to rely on this fallback. It may be disorienting though since we flash the error toast. We would also need to adjust this logic since `createFromFetch` no longer throws in these cases in later React version and instead lets the nearest Error Boundary handle these cases.

Closes https://github.com/vercel/next.js/issues/67783
Related NDX-61

### CODE REVIEW

**Comment by eps1lon** [comment]
* **#67673** <a href="https://app.graphite.dev/github/pr/vercel/next.js/67673?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @eps1lon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: b8230261734743bdb1c58f4667f5b7f87f170ec6

`__NEXT_EXPERIMENTAL_PPR=true pnpm test-dev test/development/app-hmr/hmr.test.ts` (PPR)
- app-dir-hmr > filesystem changes > should update server components pages when env files is changed (nodejs)
- app-dir-hmr > filesystem changes > should update server components pages when env files is changed (edge)

<details>
<summary>Expand output</summary>

  ● app-dir-hmr › filesystem changes › should update server components pages when env files is changed (nodejs)

    TIMED OUT: /success/

    undefined

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "ipad"
    Received: "mac"

      709 |
      710 |   if (hardError) {
    > 711 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      712 |   }
      713 |   return false
      714 | }

      at check (lib/next-test-utils.ts:711:11)
      at Object.<anonymous> (development/app-hmr/hmr.test.ts:65:9)

  ● app-dir-hmr › filesystem changes › should update server components pages when env files is changed (edge)

    TIMED OUT: /success/

    undefined

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "ipad"
    Received: "mac"

      709 |
      710 |   if (hardError) {
    > 711 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      712 |   }
      713 |   return false
      714 | }

      at check (lib/next-test-utils.ts:711:11)
      at Object.<anonymous> (development/app-hmr/hmr.test.ts:81:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sebbie/hmr-await | Change |
| - | - | - | - |
| buildDuration | 18.3s | 19.2s | ⚠️ +893ms |
| buildDurationCached | 8.5s | 7.3s | N/A |
| nodeModulesSize | 359 MB | 359 MB | N/A |
| nextStartRea..uration (ms) | 401ms | 416ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sebbie/hmr-await | Change |
| - | - | - | - |
| 1780.HASH.js gzip | 167 B | 167 B | ✓ |
| 5453-HASH.js gzip | 37.4 kB | N/A | N/A |
| 7514-HASH.js gzip | 5.06 kB | 5.05 kB | N/A |
| a7a62840-HASH.js gzip | 51.7 kB | 51.7 kB | N/A |
| framework-HASH.js gzip | 56.7 kB | 56.7 kB | N/A |
| main-app-HASH.js gzip | 221 B | 221 B | ✓ |
| main-HASH.js gzip | 32.3 kB | 32.3 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.77 kB | N/A |
| 8268-HASH.js gzip | N/A | 82.6 kB | N/A |
| Overall change | 388 B | 388 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sebbie/hmr-await | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sebbie/hmr-await | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 509 B | 510 B | N/A |
| css-HASH.js gzip | 341 B | 341 B | ✓ |
| dynamic-HASH.js gzip | 2.52 kB | 2.52 kB | ✓ |
| edge-ssr-HASH.js gzip | 264 B | 266 B | N/A |
| head-HASH.js gzip | 362 B | 363 B | N/A |
| hooks-HASH.js gzip | 391 B | 390 B | N/A |
| image-HASH.js gzip | 4.26 kB | 4.26 kB | ✓ |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.69 kB | 2.69 kB | N/A |
| routerDirect..HASH.js gzip | 326 B | 325 B | N/A |
| script-HASH.js gzip | 396 B | 397 B | N/A |
| withRouter-HASH.js gzip | 320 B | 321 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 7.89 kB | 7.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sebbie/hmr-await | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 483 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sebbie/hmr-await | Change |
| - | - | - | - |
| index.html gzip | 521 B | 525 B | N/A |
| link.html gzip | 538 B | 538 B | ✓ |
| withRouter.html gzip | 519 B | 520 B | N/A |
| Overall change | 538 B | 538 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js sebbie/hmr-await | Change |
| - | - | - | - |
| edge-ssr.js gzip | 127 kB | 127 kB | N/A |
| page.js gzip | 167 kB | 194 kB | ⚠️ +26.9 kB |
| Overall change | 167 kB | 194 kB | ⚠️ +26.9 kB |

</details>

<details>
<summary><strong>Middleware size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js sebbie/hmr-await | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 660 B | 659 B | N/A |
| middleware-r..fest.js gzip | 156 B | 155 B | N/A |
| middleware.js gzip | 29.7 kB | 29.5 kB | N/A |
| edge-runtime..pack.js gzip | 1.03 kB | 1.18 kB | ⚠️ +148 B |
| Overall change | 1.03 kB | 1.18 kB | ⚠️ +148 B |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sebbie/hmr-await | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 184 kB | 183 kB | N/A |
| app-page-exp..prod.js gzip | 112 kB | 112 kB | N/A |
| app-page-tur..prod.js gzip | 123 kB | 123 kB | N/A |
| app-page-tur..prod.js gzip | 119 kB | 119 kB | N/A |
| app-page.run...dev.js gzip | 178 kB | 178 kB | N/A |
| app-page.run..prod.js gzip | 108 kB | 108 kB | N/A |
| app-route-ex...dev.js gzip | 23.3 kB | 23.3 kB | N/A |
| app-route-ex..prod.js gzip | 18.7 kB | 18.7 kB | N/A |
| app-route-tu..prod.js gzip | 18.7 kB | 18.7 kB | N/A |
| app-route-tu..prod.js gzip | 18.6 kB | 18.6 kB | N/A |
| app-route.ru...dev.js gzip | 24.6 kB | 24.6 kB | N/A |
| app-route.ru..prod.js gzip | 18.6 kB | 18.6 kB | N/A |
| pages-api-tu..prod.js gzip | 9.6 kB | 9.55 kB | N/A |
| pages-api.ru...dev.js gzip | 9.87 kB | 9.82 kB | N/A |
| pages-api.ru..prod.js gzip | 9.59 kB | 9.55 kB | N/A |
| pages-turbo...prod.js gzip | 21.6 kB | 21.6 kB | ✓ |
| pages.runtim...dev.js gzip | 22.1 kB | 22.1 kB | ✓ |
| pages.runtim..prod.js gzip | 21.6 kB | 21.6 kB | ✓ |
| server.runti..prod.js gzip | 56.6 kB | 51.7 kB | N/A |
| Overall change | 65.3 kB | 65.3 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js sebbie/hmr-await | Change |
| - | - | - | - |
| 0.pack gzip | 1.68 MB | 2.3 MB | ⚠️ +625 kB |
| index.pack gzip | 132 kB | 155 kB | ⚠️ +23.1 kB |
| Overall change | 1.81 MB | 2.46 MB | ⚠️ +648 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-runtime-webpack.js</strong></summary>

```diff
@@ -16,8 +16,8 @@
     }
     /******/ // Create a new module (and put it into the cache)
     /******/ var module = (__webpack_module_cache__[moduleId] = {
-      /******/ // no module.id needed
-      /******/ // no module.loaded needed
+      /******/ id: moduleId,
+      /******/ loaded: false,
       /******/ exports: {},
       /******/
     });
@@ -37,6 +37,9 @@
       /******/
     }
     /******/
+    /******/ // Flag the module as loaded
+    /******/ module.loaded = true;
+    /******/
     /******/ // Return the exports of the module
     /******/ return module.exports;
     /******/
@@ -196,6 +199,12 @@
     /******/
   })();
   /******/
+  /******/ /* webpack/runtime/getFullHash */
+  /******/ (() => {
+    /******/ __webpack_require__.h = () => "855e65bfa4f3f195";
+    /******/
+  })();
+  /******/
   /******/ /* webpack/runtime/global */
   /******/ (() => {
     /******/ __webpack_require__.g = (function () {
@@ -212,6 +221,28 @@
     /******/
   })();
   /******/
+  /******/ /* webpack/runtime/harmony module decorator */
+  /******/ (() => {
+    /******/ __webpack_require__.hmd = (module) => {
+      /******/ module = Object.create(module);
+      /******/ if (!module.children) module.children = [];
+      /******/ Object.defineProperty(module, "exports", {
+        /******/ enumerable: true,
+        /******/ set: () => {
+          /******/ throw new Error(
+            "ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: " +
+              module.id
+          );
+          /******/
+        },
+        /******/
+      });
+      /******/ return module;
+      /******/
+    };
+    /******/
+  })();
+  /******/
   /******/ /* webpack/runtime/hasOwnProperty shorthand */
   /******/ (() => {
     /******/ __webpack_require__.o = (obj, prop) =>
```
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [8358],
   {
-    /***/ 1362: /***/ (
+    /***/ 9618: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function () {
-          return __webpack_require__(2160);
+          return __webpack_require__(699);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 537: /***/ (module, exports, __webpack_require__) => {
+    /***/ 9451: /***/ (module, exports, __webpack_require__) => {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -40,15 +40,15 @@
         __webpack_require__(3537)
       );
       const _head = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(7092)
+        __webpack_require__(6490)
       );
-      const _getimgprops = __webpack_require__(9834);
-      const _imageconfig = __webpack_require__(5676);
-      const _imageconfigcontextsharedruntime = __webpack_require__(387);
-      const _warnonce = __webpack_require__(451);
-      const _routercontextsharedruntime = __webpack_require__(5357);
+      const _getimgprops = __webpack_require__(3646);
+      const _imageconfig = __webpack_require__(535);
+      const _imageconfigcontextsharedruntime = __webpack_require__(4724);
+      const _warnonce = __webpack_require__(6321);
+      const _routercontextsharedruntime = __webpack_require__(1759);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(3945)
+        __webpack_require__(1882)
       );
       // This is replaced by webpack define plugin
       const configEnv = {
@@ -376,7 +376,7 @@
       /***/
     },
 
-    /***/ 9834: /***/ (
+    /***/ 3646: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -392,9 +392,9 @@
           return getImgProps;
         },
       });
-      const _warnonce = __webpack_require__(451);
-      const _imageblursvg = __webpack_require__(3547);
-      const _imageconfig = __webpack_require__(5676);
+      const _warnonce = __webpack_require__(6321);
+      const _imageblursvg = __webpack_require__(8297);
+      const _imageconfig = __webpack_require__(535);
       const VALID_LOADING_VALUES =
         /* unused pure expression or super */ null && [
           "lazy",
@@ -766,7 +766,7 @@
       /***/
     },
 
-    /***/ 3547: /***/ (__unused_webpack_module, exports) => {
+    /***/ 8297: /***/ (__unused_webpack_module, exports) => {
       "use strict";
       /**
        * A shared function, used on both client and server, to generate a SVG blur placeholder.
@@ -821,7 +821,7 @@
       /***/
     },
 
-    /***/ 6850: /***/ (
+    /***/ 973: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -848,10 +848,10 @@
         },
       });
       const _interop_require_default = __webpack_require__(1478);
-      const _getimgprops = __webpack_require__(9834);
-      const _imagecomponent = __webpack_require__(537);
+      const _getimgprops = __webpack_require__(3646);
+      const _imagecomponent = __webpack_require__(9451);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(3945)
+        __webpack_require__(1882)
       );
       function getImageProps(imgProps) {
         const { props } = (0, _getimgprops.getImgProps)(imgProps, {
@@ -883,7 +883,7 @@
       /***/
     },
 
-    /***/ 3945: /***/ (__unused_webpack_module, exports) => {
+    /***/ 1882: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -918,7 +918,7 @@
       /***/
     },
 
-    /***/ 2160: /***/ (
+    /***/ 699: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -935,8 +935,8 @@
 
       // EXTERNAL MODULE: ./node_modules/.pnpm/react@19.0.0-rc-6230622a1a-20240610/node_modules/react/jsx-runtime.js
       var jsx_runtime = __webpack_require__(898);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-6230622a1a-20240610__zehaskxadtwcczqqbmt6koh6bq/node_modules/next/image.js
-      var next_image = __webpack_require__(6793);
+      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-6230622a1a-20240610__uulzbengwsfwhwaa2ambxampcy/node_modules/next/image.js
+      var next_image = __webpack_require__(1428);
       var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // CONCATENATED MODULE: ./pages/nextjs.png
       /* harmony default export */ const nextjs = {
         src: "/_next/static/media/nextjs.cae0b805.png",
@@ -966,12 +966,12 @@
       /***/
     },
 
-    /***/ 6793: /***/ (
+    /***/ 1428: /***/ (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) => {
-      module.exports = __webpack_require__(6850);
+      module.exports = __webpack_require__(973);
 
       /***/
     },
@@ -981,7 +981,7 @@
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [2888, 9774, 179], () =>
-      __webpack_exec__(1362)
+      __webpack_exec__(9618)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>5453-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
@@ -16,8 +16,8 @@
     }
     /******/ // Create a new module (and put it into the cache)
     /******/ var module = (__webpack_module_cache__[moduleId] = {
-      /******/ // no module.id needed
-      /******/ // no module.loaded needed
+      /******/ id: moduleId,
+      /******/ loaded: false,
       /******/ exports: {},
       /******/
     });
@@ -37,6 +37,9 @@
       /******/
     }
     /******/
+    /******/ // Flag the module as loaded
+    /******/ module.loaded = true;
+    /******/
     /******/ // Return the exports of the module
     /******/ return module.exports;
     /******/
@@ -205,7 +208,7 @@
     /******/ __webpack_require__.u = (chunkId) => {
       /******/ // return url for filenames based on template
       /******/ return (
-        "static/chunks/" + chunkId + "." + "b718f995461ce466" + ".js"
+        "static/chunks/" + chunkId + "." + "3646e1801184f56b" + ".js"
       );
       /******/
     };
@@ -223,6 +226,12 @@
     /******/
   })();
   /******/
+  /******/ /* webpack/runtime/getFullHash */
+  /******/ (() => {
+    /******/ __webpack_require__.h = () => "ef4772318be4d442";
+    /******/
+  })();
+  /******/
   /******/ /* webpack/runtime/global */
   /******/ (() => {
     /******/ __webpack_require__.g = (function () {
@@ -330,6 +339,17 @@
     /******/
   })();
   /******/
+  /******/ /* webpack/runtime/node module decorator */
+  /******/ (() => {
+    /******/ __webpack_require__.nmd = (module) => {
+      /******/ module.paths = [];
+      /******/ if (!module.children) module.children = [];
+      /******/ return module;
+      /******/
+    };
+    /******/
+  })();
+  /******/
   /******/ /* webpack/runtime/trusted types policy */
   /******/ (() => {
     /******/ var policy;
```
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page-exp..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page.runtime.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.ru..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-api-tu..time.prod.js</strong></summary>

```diff
@@ -17,5 +17,5 @@
  * Copyright(c) 2012 TJ Holowaychuk
  * Copyright(c) 2016-2017 Douglas Christopher Wilson
  * MIT Licensed
- */var t=/(?:^|,)\s*?no-cache\s*?(?:,|$)/;function r(e){var t=e&&Date.parse(e);return"number"==typeof t?t:NaN}e.exports=function(e,n){var o=e["if-modified-since"],i=e["if-none-match"];if(!o&&!i)return!1;var a=e["cache-control"];if(a&&t.test(a))return!1;if(i&&"*"!==i){var s=n.etag;if(!s)return!1;for(var d=!0,p=function(e){for(var t=0,r=[],n=0,o=0,i=e.length;o<i;o++)switch(e.charCodeAt(o)){case 32:n===t&&(n=t=o+1);break;case 44:r.push(e.substring(n,t)),n=t=o+1;break;default:t=o+1}return r.push(e.substring(n,t)),r}(i),u=0;u<p.length;u++){var l=p[u];if(l===s||l==="W/"+s||"W/"+l===s){d=!1;break}}if(d)return!1}if(o){var c=n["last-modified"];if(!c||!(r(c)<=r(o)))return!1}return!0}}},r={};function n(e){var o=r[e];if(void 0!==o)return o.exports;var i=r[e]={exports:{}},a=!0;try{t[e](i,i.exports,n),a=!1}finally{a&&delete r[e]}return i.exports}n.ab=__dirname+"/";var o=n(695);e.exports=o})()},"./dist/esm/server/crypto-utils.js":(e,t,r)=>{"use strict";r.r(t),r.d(t,{decryptWithSecret:()=>s,encryptWithSecret:()=>a});let n=require("crypto");var o=r.n(n);let i="aes-256-gcm";function a(e,t){let r=o().randomBytes(16),n=o().randomBytes(64),a=o().pbkdf2Sync(e,n,1e5,32,"sha512"),s=o().createCipheriv(i,a,r),d=Buffer.concat([s.update(t,"utf8"),s.final()]),p=s.getAuthTag();return Buffer.concat([n,r,p,d]).toString("hex")}function s(e,t){let r=Buffer.from(t,"hex"),n=r.slice(0,64),a=r.slice(64,80),s=r.slice(80,96),d=r.slice(96),p=o().pbkdf2Sync(e,n,1e5,32,"sha512"),u=o().createDecipheriv(i,p,a);return u.setAuthTag(s),u.update(d)+u.final("utf8")}},"next/dist/compiled/jsonwebtoken":e=>{"use strict";e.exports=require("next/dist/compiled/jsonwebtoken")},"next/dist/compiled/node-html-parser":e=>{"use strict";e.exports=require("next/dist/compiled/node-html-parser")},"next/dist/compiled/raw-body":e=>{"use strict";e.exports=require("next/dist/compiled/raw-body")},querystring:e=>{"use strict";e.exports=require("querystring")}},t={};function r(n){var o=t[n];if(void 0!==o)return o.exports;var i=t[n]={exports:{}};return e[n](i,i.exports,r),i.exports}r.n=e=>{var t=e&&e.__esModule?()=>e.default:()=>e;return r.d(t,{a:t}),t},r.d=(e,t)=>{for(var n in t)r.o(t,n)&&!r.o(e,n)&&Object.defineProperty(e,n,{enumerable:!0,get:t[n]})},r.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),r.r=e=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})};var n={};(()=>{"use strict";r.r(n),r.d(n,{PagesAPIRouteModule:()=>U,default:()=>F});class e{static get(e,t,r){let n=Reflect.get(e,t,r);return"function"==typeof n?n.bind(e):n}static set(e,t,r,n){return Reflect.set(e,t,r,n)}static has(e,t){return Reflect.has(e,t)}static deleteProperty(e,t){return Reflect.deleteProperty(e,t)}}class t extends Error{constructor(){super("Headers cannot be modified. Read more: https://nextjs.org/docs/app/api-reference/functions/headers")}static callable(){throw new t}}class o extends Headers{constructor(t){super(),this.headers=new Proxy(t,{get(r,n,o){if("symbol"==typeof n)return e.get(r,n,o);let i=n.toLowerCase(),a=Object.keys(t).find(e=>e.toLowerCase()===i);if(void 0!==a)return e.get(r,a,o)},set(r,n,o,i){if("symbol"==typeof n)return e.set(r,n,o,i);let a=n.toLowerCase(),s=Object.keys(t).find(e=>e.toLowerCase()===a);return e.set(r,s??n,o,i)},has(r,n){if("symbol"==typeof n)return e.has(r,n);let o=n.toLowerCase(),i=Object.keys(t).find(e=>e.toLowerCase()===o);return void 0!==i&&e.has(r,i)},deleteProperty(r,n){if("symbol"==typeof n)return e.deleteProperty(r,n);let o=n.toLowerCase(),i=Object.keys(t).find(e=>e.toLowerCase()===o);return void 0===i||e.deleteProperty(r,i)}})}static seal(r){return new Proxy(r,{get(r,n,o){switch(n){case"append":case"delete":case"set":return t.callable;default:return e.get(r,n,o)}}})}merge(e){return Array.isArray(e)?e.join(", "):e}static from(e){return e instanceof Headers?e:new o(e)}append(e,t){let r=this.headers[e];"string"==typeof r?this.headers[e]=[r,t]:Array.isArray(r)?r.push(t):this.headers[e]=t}delete(e){delete this.headers[e]}get(e){let t=this.headers[e];return void 0!==t?this.merge(t):null}has(e){return void 0!==this.headers[e]}set(e,t){this.headers[e]=t}forEach(e,t){for(let[r,n]of this.entries())e.call(t,n,r,this)}*entries(){for(let e of Object.keys(this.headers)){let t=e.toLowerCase(),r=this.get(t);yield[t,r]}}*keys(){for(let e of Object.keys(this.headers)){let t=e.toLowerCase();yield t}}*values(){for(let e of Object.keys(this.headers)){let t=this.get(e);yield t}}[Symbol.iterator](){return this.entries()}}let i="x-prerender-revalidate",a="x-prerender-revalidate-if-generated",s={shared:"shared",reactServerComponents:"rsc",serverSideRendering:"ssr",actionBrowser:"action-browser",api:"api",middleware:"middleware",instrument:"instrument",edgeAsset:"edge-asset",appPagesBrowser:"app-pages-browser",appMetadataRoute:"app-metadata-route"};({...s,GROUP:{builtinReact:[s.reactServerComponents,s.actionBrowser,s.appMetadataRoute],serverOnly:[s.reactServerComponents,s.actionBrowser,s.appMetadataRoute,s.instrument,s.middleware],neutralTarget:[s.api],clientOnly:[s.serverSideRendering,s.appPagesBrowser],bundled:[s.reactServerComponents,s.actionBrowser,s.appMetadataRoute,s.serverSideRendering,s.appPagesBrowser,s.shared,s.instrument]}});let d=require("next/dist/server/lib/trace/tracer");(function(e){e.handleRequest="BaseServer.handleRequest",e.run="BaseServer.run",e.pipe="BaseServer.pipe",e.getStaticHTML="BaseServer.getStaticHTML",e.render="BaseServer.render",e.renderToResponseWithComponents="BaseServer.renderToResponseWithComponents",e.renderToResponse="BaseServer.renderToResponse",e.renderToHTML="BaseServer.renderToHTML",e.renderError="BaseServer.renderError",e.renderErrorToResponse="BaseServer.renderErrorToResponse",e.renderErrorToHTML="BaseServer.renderErrorToHTML",e.render404="BaseServer.render404"})(y||(y={})),function(e){e.loadDefaultErrorComponents="LoadComponents.loadDefaultErrorComponents",e.loadComponents="LoadComponents.loadComponents"}(x||(x={})),function(e){e.getRequestHandler="NextServer.getRequestHandler",e.getServer="NextServer.getServer",e.getServerRequestHandler="NextServer.getServerRequestHandler",e.createServer="createServer.createServer"}(b||(b={})),function(e){e.compression="NextNodeServer.compression",e.getBuildId="NextNodeServer.getBuildId",e.createComponentTree="NextNodeServer.createComponentTree",e.clientComponentLoading="NextNodeServer.clientComponentLoading",e.getLayoutOrPageModule="NextNodeServer.getLayoutOrPageModule",e.generateStaticRoutes="NextNodeServer.generateStaticRoutes",e.generateFsStaticRoutes="NextNodeServer.generateFsStaticRoutes",e.generatePublicRoutes="NextNodeServer.generatePublicRoutes",e.generateImageRoutes="NextNodeServer.generateImageRoutes.route",e.sendRenderResult="NextNodeServer.sendRenderResult",e.proxyRequest="NextNodeServer.proxyRequest",e.runApi="NextNodeServer.runApi",e.render="NextNodeServer.render",e.renderHTML="NextNodeServer.renderHTML",e.imageOptimizer="NextNodeServer.imageOptimizer",e.getPagePath="NextNodeServer.getPagePath",e.getRoutesManifest="NextNodeServer.getRoutesManifest",e.findPageComponents="NextNodeServer.findPageComponents",e.getFontManifest="NextNodeServer.getFontManifest",e.getServerComponentManifest="NextNodeServer.getServerComponentManifest",e.getRequestHandler="NextNodeServer.getRequestHandler",e.renderToHTML="NextNodeServer.renderToHTML",e.renderError="NextNodeServer.renderError",e.renderErrorToHTML="NextNodeServer.renderErrorToHTML",e.render404="NextNodeServer.render404",e.startResponse="NextNodeServer.startResponse",e.route="route",e.onProxyReq="onProxyReq",e.apiResolver="apiResolver",e.internalFetch="internalFetch"}(w||(w={})),(S||(S={})).startServer="startServer.startServer",function(e){e.getServerSideProps="Render.getServerSideProps",e.getStaticProps="Render.getStaticProps",e.renderToString="Render.renderToString",e.renderDocument="Render.renderDocument",e.createBodyResult="Render.createBodyResult"}(R||(R={})),function(e){e.renderToString="AppRender.renderToString",e.renderToReadableStream="AppRender.renderToReadableStream",e.getBodyResult="AppRender.getBodyResult",e.fetch="AppRender.fetch"}(C||(C={})),(N||(N={})).executeRoute="Router.executeRoute",(j||(j={})).runHandler="Node.runHandler",(T||(T={})).runHandler="AppRouteRouteHandlers.runHandler",function(e){e.generateMetadata="ResolveMetadata.generateMetadata",e.generateViewport="ResolveMetadata.generateViewport"}(_||(_={})),(A||(A={})).execute="Middleware.execute";let p="__prerender_bypass",u="__next_preview_data",l=Symbol(u),c=Symbol(p);function f(e,t={}){if(c in e)return e;let{serialize:n}=r("./dist/compiled/cookie/index.js"),o=e.getHeader("Set-Cookie");return e.setHeader("Set-Cookie",[..."string"==typeof o?[o]:Array.isArray(o)?o:[],n(p,"",{expires:new Date(0),httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==t.path?{path:t.path}:void 0}),n(u,"",{expires:new Date(0),httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==t.path?{path:t.path}:void 0})]),Object.defineProperty(e,c,{value:!0,enumerable:!1}),e}class h extends Error{constructor(e,t){super(t),this.statusCode=e}}function m(e,t,r){e.statusCode=t,e.statusMessage=r,e.end(r)}function v({req:e},t,r){let n={configurable:!0,enumerable:!0},o={...n,writable:!0};Object.defineProperty(e,t,{...n,get:()=>{let n=r();return Object.defineProperty(e,t,{...o,value:n}),n},set:r=>{Object.defineProperty(e,t,{...o,value:r})}})}class g{constructor({userland:e,definition:t}){this.userland=e,this.definition=t}}var y,x,b,w,S,R,C,N,j,T,_,A,M=r("./dist/compiled/bytes/index.js"),O=r.n(M);let P=e=>{let t=e.length,r=0,n=0,o=8997,i=0,a=33826,s=0,d=40164,p=0,u=52210;for(;r<t;)o^=e.charCodeAt(r++),n=435*o,i=435*a,s=435*d,p=435*u,s+=o<<8,p+=a<<8,i+=n>>>16,o=65535&n,s+=i>>>16,a=65535&i,u=p+(s>>>16)&65535,d=65535&s;return(15&u)*281474976710656+4294967296*d+65536*a+(o^u>>4)},k=(e,t=!1)=>(t?'W/"':'"')+P(e).toString(36)+e.length.toString(36)+'"';"undefined"!=typeof performance&&["mark","measure","getEntriesByName"].every(e=>"function"==typeof performance[e]);var E=r("./dist/compiled/fresh/index.js"),H=r.n(E);let L=require("stream");function B(e){return"object"==typeof e&&null!==e&&"name"in e&&"message"in e}var q=r("./dist/compiled/@edge-runtime/cookies/index.js"),$=r("./dist/compiled/content-type/index.js");async function I(e,t){let n,o;try{n=(0,$.parse)(e.headers["content-type"]||"text/plain")}catch{n=(0,$.parse)("text/plain")}let{type:i,parameters:a}=n,s=a.charset||"utf-8";try{let n=r("next/dist/compiled/raw-body");o=await n(e,{encoding:s,limit:t})}catch(e){if(B(e)&&"entity.too.large"===e.type)throw new h(413,`Body exceeded ${t} limit`);throw new h(400,"Invalid body")}let d=o.toString();return"application/json"===i||"application/ld+json"===i?function(e){if(0===e.length)return{};try{return JSON.parse(e)}catch(e){throw new h(400,"Invalid JSON")}}(d):"application/x-www-form-urlencoded"===i?r("querystring").decode(d):d}function D(e){return"string"==typeof e&&e.length>=16}async function K(e,t,r,n){if("string"!=typeof e||!e.startsWith("/"))throw Error(`Invalid urlPath provided to revalidate(), must be a path e.g. /blog/post-1, received ${e}`);let o={[i]:n.previewModeId,...t.unstable_onlyGenerated?{[a]:"1"}:{}},s=[...n.allowedRevalidateHeaderKeys||[],...n.trustHostHeader?["cookie","x-vercel-protection-bypass"]:[]];for(let e of Object.keys(r.headers))s.includes(e)&&(o[e]=r.headers[e]);try{if(n.trustHostHeader){let n=await fetch(`https://${r.headers.host}${e}`,{method:"HEAD",headers:o}),i=n.headers.get("x-vercel-cache")||n.headers.get("x-nextjs-cache");if((null==i?void 0:i.toUpperCase())!=="REVALIDATED"&&!(404===n.status&&t.unstable_onlyGenerated))throw Error(`Invalid response ${n.status}`)}else if(n.revalidate)await n.revalidate({urlPath:e,revalidateHeaders:o,opts:t});else throw Error("Invariant: required internal revalidate method not passed to api-utils")}catch(t){throw Error(`Failed to revalidate ${e}: ${B(t)?t.message:t}`)}}async function z(e,t,n,s,d,c,g,y,x){try{var b,w,S,R;if(!s){t.statusCode=404,t.end("Not Found");return}let c=s.config||{},h=(null==(b=c.api)?void 0:b.bodyParser)!==!1,m=(null==(w=c.api)?void 0:w.responseLimit)??!0;null==(S=c.api)||S.externalResolver,v({req:e},"cookies",(R=e.headers,function(){let{cookie:e}=R;if(!e)return{};let{parse:t}=r("./dist/compiled/cookie/index.js");return t(Array.isArray(e)?e.join("; "):e)})),e.query=n,v({req:e},"previewData",()=>(function(e,t,n){var s,d;let c;if(n&&function(e,t){let r=o.from(e.headers);return{isOnDemandRevalidate:r.get(i)===t.previewModeId,revalidateOnlyGenerated:r.has(a)}}(e,n).isOnDemandRevalidate)return!1;if(l in e)return e[l];let h=o.from(e.headers),m=new q.RequestCookies(h),v=null==(s=m.get(p))?void 0:s.value,g=null==(d=m.get(u))?void 0:d.value;if(v&&!g&&v===n.previewModeId){let t={};return Object.defineProperty(e,l,{value:t,enumerable:!1}),t}if(!v&&!g)return!1;if(!v||!g||v!==n.previewModeId)return f(t),!1;try{c=r("next/dist/compiled/jsonwebtoken").verify(g,n.previewModeSigningKey)}catch{return f(t),!1}let{decryptWithSecret:y}=r("./dist/esm/server/crypto-utils.js"),x=y(Buffer.from(n.previewModeEncryptionKey),c.data);try{let t=JSON.parse(x);return Object.defineProperty(e,l,{value:t,enumerable:!1}),t}catch{return!1}})(e,t,d)),v({req:e},"preview",()=>!1!==e.previewData||void 0),v({req:e},"draftMode",()=>e.preview),h&&!e.body&&(e.body=await I(e,c.api&&c.api.bodyParser&&c.api.bodyParser.sizeLimit?c.api.bodyParser.sizeLimit:"1mb"));let g=0,y=m&&"boolean"!=typeof m?O().parse(m):4194304,x=t.write,C=t.end;t.write=(...e)=>(g+=Buffer.byteLength(e[0]||""),x.apply(t,e)),t.end=(...r)=>(r.length&&"function"!=typeof r[0]&&(g+=Buffer.byteLength(r[0]||"")),m&&g>=y&&console.warn(`API response for ${e.url} exceeds ${O().format(y)}. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit`),C.apply(t,r)),t.status=e=>(t.statusCode=e,t),t.send=r=>(function(e,t,r){var n;if(null==r){t.end();return}if(204===t.statusCode||304===t.statusCode){t.removeHeader("Content-Type"),t.removeHeader("Content-Length"),t.removeHeader("Transfer-Encoding"),t.end();return}let o=t.getHeader("Content-Type");if(r instanceof L.Stream){o||t.setHeader("Content-Type","application/octet-stream"),r.pipe(t);return}let i=["object","number","boolean"].includes(typeof r),a=i?JSON.stringify(r):r;if((n=k(a))&&t.setHeader("ETag",n),!H()(e.headers,{etag:n})||(t.statusCode=304,t.end(),0)){if(Buffer.isBuffer(r)){o||t.setHeader("Content-Type","application/octet-stream"),t.setHeader("Content-Length",r.length),t.end(r);return}i&&t.setHeader("Content-Type","application/json; charset=utf-8"),t.setHeader("Content-Length",Buffer.byteLength(a)),t.end(a)}})(e,t,r),t.json=e=>{t.setHeader("Content-Type","application/json; charset=utf-8"),t.send(JSON.stringify(e))},t.redirect=(e,r)=>(function(e,t,r){if("string"==typeof t&&(r=t,t=307),"number"!=typeof t||"string"!=typeof r)throw Error("Invalid redirect arguments. Please use a single argument URL, e.g. res.redirect('/destination') or use a status code and URL, e.g. res.redirect(307, '/destination').");return e.writeHead(t,{Location:r}),e.write(r),e.end(),e})(t,e,r),t.setDraftMode=(e={enable:!0})=>(function(e,t){if(!D(t.previewModeId))throw Error("invariant: invalid previewModeId");let n=t.enable?void 0:new Date(0),{serialize:o}=r("./dist/compiled/cookie/index.js"),i=e.getHeader("Set-Cookie");return e.setHeader("Set-Cookie",[..."string"==typeof i?[i]:Array.isArray(i)?i:[],o(p,t.previewModeId,{httpOnly:!0,sameSite:"none",secure:!0,path:"/",expires:n})]),e})(t,Object.assign({},d,e)),t.setPreviewData=(e,n={})=>(function(e,t,n){if(!D(n.previewModeId))throw Error("invariant: invalid previewModeId");if(!D(n.previewModeEncryptionKey))throw Error("invariant: invalid previewModeEncryptionKey");if(!D(n.previewModeSigningKey))throw Error("invariant: invalid previewModeSigningKey");let o=r("next/dist/compiled/jsonwebtoken"),{encryptWithSecret:i}=r("./dist/esm/server/crypto-utils.js"),a=o.sign({data:i(Buffer.from(n.previewModeEncryptionKey),JSON.stringify(t))},n.previewModeSigningKey,{algorithm:"HS256",...void 0!==n.maxAge?{expiresIn:n.maxAge}:void 0});if(a.length>2048)throw Error("Preview data is limited to 2KB currently, reduce how much data you are storing as preview data to continue");let{serialize:s}=r("./dist/compiled/cookie/index.js"),d=e.getHeader("Set-Cookie");return e.setHeader("Set-Cookie",[..."string"==typeof d?[d]:Array.isArray(d)?d:[],s(p,n.previewModeId,{httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==n.maxAge?{maxAge:n.maxAge}:void 0,...void 0!==n.path?{path:n.path}:void 0}),s(u,a,{httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==n.maxAge?{maxAge:n.maxAge}:void 0,...void 0!==n.path?{path:n.path}:void 0})]),e})(t,e,Object.assign({},d,n)),t.clearPreviewData=(e={})=>f(t,e),t.revalidate=(t,r)=>K(t,r||{},e,d);let N=s.default||s;await N(e,t)}catch(r){if(null==x||x(r,e,{routerKind:"Pages Router",routePath:y||"",routeType:"route"}),r instanceof h)m(t,r.statusCode,r.message);else{if(g)throw B(r)&&(r.page=y),r;if(console.error(r),c)throw r;m(t,500,"Internal Server Error")}}}class U extends g{constructor(e){if(super(e),"function"!=typeof e.userland.default)throw Error(`Page ${e.definition.page} does not export a default function.`);this.apiResolverWrapped=function(e,t){return(...r)=>{var n;return null==(n=(0,d.getTracer)().getRootSpanAttributes())||n.set("next.route",e),(0,d.getTracer)().trace(j.runHandler,{spanName:`executing api route (pages) ${e}`},()=>t(...r))}}(e.definition.page,z)}async render(e,t,r){let{apiResolverWrapped:n}=this;await n(e,t,r.query,this.userland,{...r.previewProps,revalidate:r.revalidate,trustHostHeader:r.trustHostHeader,allowedRevalidateHeaderKeys:r.allowedRevalidateHeaderKeys,hostname:r.hostname},r.minimalMode,r.dev,r.page,r.onError)}}let F=U})(),module.exports=n})();
+ */var t=/(?:^|,)\s*?no-cache\s*?(?:,|$)/;function r(e){var t=e&&Date.parse(e);return"number"==typeof t?t:NaN}e.exports=function(e,n){var o=e["if-modified-since"],i=e["if-none-match"];if(!o&&!i)return!1;var a=e["cache-control"];if(a&&t.test(a))return!1;if(i&&"*"!==i){var s=n.etag;if(!s)return!1;for(var d=!0,p=function(e){for(var t=0,r=[],n=0,o=0,i=e.length;o<i;o++)switch(e.charCodeAt(o)){case 32:n===t&&(n=t=o+1);break;case 44:r.push(e.substring(n,t)),n=t=o+1;break;default:t=o+1}return r.push(e.substring(n,t)),r}(i),u=0;u<p.length;u++){var l=p[u];if(l===s||l==="W/"+s||"W/"+l===s){d=!1;break}}if(d)return!1}if(o){var c=n["last-modified"];if(!c||!(r(c)<=r(o)))return!1}return!0}}},r={};function n(e){var o=r[e];if(void 0!==o)return o.exports;var i=r[e]={exports:{}},a=!0;try{t[e](i,i.exports,n),a=!1}finally{a&&delete r[e]}return i.exports}n.ab=__dirname+"/";var o=n(695);e.exports=o})()},"./dist/esm/server/crypto-utils.js":(e,t,r)=>{"use strict";r.r(t),r.d(t,{decryptWithSecret:()=>s,encryptWithSecret:()=>a});let n=require("crypto");var o=r.n(n);let i="aes-256-gcm";function a(e,t){let r=o().randomBytes(16),n=o().randomBytes(64),a=o().pbkdf2Sync(e,n,1e5,32,"sha512"),s=o().createCipheriv(i,a,r),d=Buffer.concat([s.update(t,"utf8"),s.final()]),p=s.getAuthTag();return Buffer.concat([n,r,p,d]).toString("hex")}function s(e,t){let r=Buffer.from(t,"hex"),n=r.slice(0,64),a=r.slice(64,80),s=r.slice(80,96),d=r.slice(96),p=o().pbkdf2Sync(e,n,1e5,32,"sha512"),u=o().createDecipheriv(i,p,a);return u.setAuthTag(s),u.update(d)+u.final("utf8")}},"next/dist/compiled/jsonwebtoken":e=>{"use strict";e.exports=require("next/dist/compiled/jsonwebtoken")},"next/dist/compiled/node-html-parser":e=>{"use strict";e.exports=require("next/dist/compiled/node-html-parser")},"next/dist/compiled/raw-body":e=>{"use strict";e.exports=require("next/dist/compiled/raw-body")},querystring:e=>{"use strict";e.exports=require("querystring")}},t={};function r(n){var o=t[n];if(void 0!==o)return o.exports;var i=t[n]={exports:{}};return e[n](i,i.exports,r),i.exports}r.n=e=>{var t=e&&e.__esModule?()=>e.default:()=>e;return r.d(t,{a:t}),t},r.d=(e,t)=>{for(var n in t)r.o(t,n)&&!r.o(e,n)&&Object.defineProperty(e,n,{enumerable:!0,get:t[n]})},r.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),r.r=e=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})};var n={};(()=>{"use strict";r.r(n),r.d(n,{PagesAPIRouteModule:()=>U,default:()=>F});class e{static get(e,t,r){let n=Reflect.get(e,t,r);return"function"==typeof n?n.bind(e):n}static set(e,t,r,n){return Reflect.set(e,t,r,n)}static has(e,t){return Reflect.has(e,t)}static deleteProperty(e,t){return Reflect.deleteProperty(e,t)}}class t extends Error{constructor(){super("Headers cannot be modified. Read more: https://nextjs.org/docs/app/api-reference/functions/headers")}static callable(){throw new t}}class o extends Headers{constructor(t){super(),this.headers=new Proxy(t,{get(r,n,o){if("symbol"==typeof n)return e.get(r,n,o);let i=n.toLowerCase(),a=Object.keys(t).find(e=>e.toLowerCase()===i);if(void 0!==a)return e.get(r,a,o)},set(r,n,o,i){if("symbol"==typeof n)return e.set(r,n,o,i);let a=n.toLowerCase(),s=Object.keys(t).find(e=>e.toLowerCase()===a);return e.set(r,s??n,o,i)},has(r,n){if("symbol"==typeof n)return e.has(r,n);let o=n.toLowerCase(),i=Object.keys(t).find(e=>e.toLowerCase()===o);return void 0!==i&&e.has(r,i)},deleteProperty(r,n){if("symbol"==typeof n)return e.deleteProperty(r,n);let o=n.toLowerCase(),i=Object.keys(t).find(e=>e.toLowerCase()===o);return void 0===i||e.deleteProperty(r,i)}})}static seal(r){return new Proxy(r,{get(r,n,o){switch(n){case"append":case"delete":case"set":return t.callable;default:return e.get(r,n,o)}}})}merge(e){return Array.isArray(e)?e.join(", "):e}static from(e){return e instanceof Headers?e:new o(e)}append(e,t){let r=this.headers[e];"string"==typeof r?this.headers[e]=[r,t]:Array.isArray(r)?r.push(t):this.headers[e]=t}delete(e){delete this.headers[e]}get(e){let t=this.headers[e];return void 0!==t?this.merge(t):null}has(e){return void 0!==this.headers[e]}set(e,t){this.headers[e]=t}forEach(e,t){for(let[r,n]of this.entries())e.call(t,n,r,this)}*entries(){for(let e of Object.keys(this.headers)){let t=e.toLowerCase(),r=this.get(t);yield[t,r]}}*keys(){for(let e of Object.keys(this.headers)){let t=e.toLowerCase();yield t}}*values(){for(let e of Object.keys(this.headers)){let t=this.get(e);yield t}}[Symbol.iterator](){return this.entries()}}let i="x-prerender-revalidate",a="x-prerender-revalidate-if-generated",s={shared:"shared",reactServerComponents:"rsc",serverSideRendering:"ssr",actionBrowser:"action-browser",api:"api",middleware:"middleware",instrument:"instrument",edgeAsset:"edge-asset",appPagesBrowser:"app-pages-browser",appMetadataRoute:"app-metadata-route"};({...s,GROUP:{builtinReact:[s.reactServerComponents,s.actionBrowser,s.appMetadataRoute],serverOnly:[s.reactServerComponents,s.actionBrowser,s.appMetadataRoute,s.instrument,s.middleware],neutralTarget:[s.api],clientOnly:[s.serverSideRendering,s.appPagesBrowser],bundled:[s.reactServerComponents,s.actionBrowser,s.appMetadataRoute,s.serverSideRendering,s.appPagesBrowser,s.shared,s.instrument]}});let d=require("next/dist/server/lib/trace/tracer");(function(e){e.handleRequest="BaseServer.handleRequest",e.run="BaseServer.run",e.pipe="BaseServer.pipe",e.getStaticHTML="BaseServer.getStaticHTML",e.render="BaseServer.render",e.renderToResponseWithComponents="BaseServer.renderToResponseWithComponents",e.renderToResponse="BaseServer.renderToResponse",e.renderToHTML="BaseServer.renderToHTML",e.renderError="BaseServer.renderError",e.renderErrorToResponse="BaseServer.renderErrorToResponse",e.renderErrorToHTML="BaseServer.renderErrorToHTML",e.render404="BaseServer.render404"})(y||(y={})),function(e){e.loadDefaultErrorComponents="LoadComponents.loadDefaultErrorComponents",e.loadComponents="LoadComponents.loadComponents"}(x||(x={})),function(e){e.getRequestHandler="NextServer.getRequestHandler",e.getServer="NextServer.getServer",e.getServerRequestHandler="NextServer.getServerRequestHandler",e.createServer="createServer.createServer"}(b||(b={})),function(e){e.compression="NextNodeServer.compression",e.getBuildId="NextNodeServer.getBuildId",e.createComponentTree="NextNodeServer.createComponentTree",e.clientComponentLoading="NextNodeServer.clientComponentLoading",e.getLayoutOrPageModule="NextNodeServer.getLayoutOrPageModule",e.generateStaticRoutes="NextNodeServer.generateStaticRoutes",e.generateFsStaticRoutes="NextNodeServer.generateFsStaticRoutes",e.generatePublicRoutes="NextNodeServer.generatePublicRoutes",e.generateImageRoutes="NextNodeServer.generateImageRoutes.route",e.sendRenderResult="NextNodeServer.sendRenderResult",e.proxyRequest="NextNodeServer.proxyRequest",e.runApi="NextNodeServer.runApi",e.render="NextNodeServer.render",e.renderHTML="NextNodeServer.renderHTML",e.imageOptimizer="NextNodeServer.imageOptimizer",e.getPagePath="NextNodeServer.getPagePath",e.getRoutesManifest="NextNodeServer.getRoutesManifest",e.findPageComponents="NextNodeServer.findPageComponents",e.getFontManifest="NextNodeServer.getFontManifest",e.getServerComponentManifest="NextNodeServer.getServerComponentManifest",e.getRequestHandler="NextNodeServer.getRequestHandler",e.renderToHTML="NextNodeServer.renderToHTML",e.renderError="NextNodeServer.renderError",e.renderErrorToHTML="NextNodeServer.renderErrorToHTML",e.render404="NextNodeServer.render404",e.startResponse="NextNodeServer.startResponse",e.route="route",e.onProxyReq="onProxyReq",e.apiResolver="apiResolver",e.internalFetch="internalFetch"}(w||(w={})),(S||(S={})).startServer="startServer.startServer",function(e){e.getServerSideProps="Render.getServerSideProps",e.getStaticProps="Render.getStaticProps",e.renderToString="Render.renderToString",e.renderDocument="Render.renderDocument",e.createBodyResult="Render.createBodyResult"}(R||(R={})),function(e){e.renderToString="AppRender.renderToString",e.renderToReadableStream="AppRender.renderToReadableStream",e.getBodyResult="AppRender.getBodyResult",e.fetch="AppRender.fetch"}(C||(C={})),(N||(N={})).executeRoute="Router.executeRoute",(j||(j={})).runHandler="Node.runHandler",(T||(T={})).runHandler="AppRouteRouteHandlers.runHandler",function(e){e.generateMetadata="ResolveMetadata.generateMetadata",e.generateViewport="ResolveMetadata.generateViewport"}(_||(_={})),(A||(A={})).execute="Middleware.execute";let p="__prerender_bypass",u="__next_preview_data",l=Symbol(u),c=Symbol(p);function f(e,t={}){if(c in e)return e;let{serialize:n}=r("./dist/compiled/cookie/index.js"),o=e.getHeader("Set-Cookie");return e.setHeader("Set-Cookie",[..."string"==typeof o?[o]:Array.isArray(o)?o:[],n(p,"",{expires:new Date(0),httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==t.path?{path:t.path}:void 0}),n(u,"",{expires:new Date(0),httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==t.path?{path:t.path}:void 0})]),Object.defineProperty(e,c,{value:!0,enumerable:!1}),e}class h extends Error{constructor(e,t){super(t),this.statusCode=e}}function m(e,t,r){e.statusCode=t,e.statusMessage=r,e.end(r)}function v({req:e},t,r){let n={configurable:!0,enumerable:!0},o={...n,writable:!0};Object.defineProperty(e,t,{...n,get:()=>{let n=r();return Object.defineProperty(e,t,{...o,value:n}),n},set:r=>{Object.defineProperty(e,t,{...o,value:r})}})}class g{constructor({userland:e,definition:t}){this.userland=e,this.definition=t}}var y,x,b,w,S,R,C,N,j,T,_,A,M=r("./dist/compiled/bytes/index.js"),O=r.n(M);let P=e=>{let t=e.length,r=0,n=0,o=8997,i=0,a=33826,s=0,d=40164,p=0,u=52210;for(;r<t;)o^=e.charCodeAt(r++),n=435*o,i=435*a,s=435*d,p=435*u,s+=o<<8,p+=a<<8,i+=n>>>16,o=65535&n,s+=i>>>16,a=65535&i,u=p+(s>>>16)&65535,d=65535&s;return(15&u)*281474976710656+4294967296*d+65536*a+(o^u>>4)},k=(e,t=!1)=>(t?'W/"':'"')+P(e).toString(36)+e.length.toString(36)+'"';"undefined"!=typeof performance&&["mark","measure","getEntriesByName"].every(e=>"function"==typeof performance[e]);var H=r("./dist/compiled/fresh/index.js"),E=r.n(H);let L=require("stream");function B(e){return"object"==typeof e&&null!==e&&"name"in e&&"message"in e}var q=r("./dist/compiled/@edge-runtime/cookies/index.js"),$=r("./dist/compiled/content-type/index.js");async function I(e,t){let n,o;try{n=(0,$.parse)(e.headers["content-type"]||"text/plain")}catch{n=(0,$.parse)("text/plain")}let{type:i,parameters:a}=n,s=a.charset||"utf-8";try{let n=r("next/dist/compiled/raw-body");o=await n(e,{encoding:s,limit:t})}catch(e){if(B(e)&&"entity.too.large"===e.type)throw new h(413,`Body exceeded ${t} limit`);throw new h(400,"Invalid body")}let d=o.toString();return"application/json"===i||"application/ld+json"===i?function(e){if(0===e.length)return{};try{return JSON.parse(e)}catch(e){throw new h(400,"Invalid JSON")}}(d):"application/x-www-form-urlencoded"===i?r("querystring").decode(d):d}function D(e){return"string"==typeof e&&e.length>=16}async function z(e,t,r,n){if("string"!=typeof e||!e.startsWith("/"))throw Error(`Invalid urlPath provided to revalidate(), must be a path e.g. /blog/post-1, received ${e}`);let o={[i]:n.previewModeId,...t.unstable_onlyGenerated?{[a]:"1"}:{}},s=[...n.allowedRevalidateHeaderKeys||[],...n.trustHostHeader?["cookie","x-vercel-protection-bypass"]:[]];for(let e of Object.keys(r.headers))s.includes(e)&&(o[e]=r.headers[e]);try{if(n.trustHostHeader){let n=await fetch(`https://${r.headers.host}${e}`,{method:"HEAD",headers:o}),i=n.headers.get("x-vercel-cache")||n.headers.get("x-nextjs-cache");if((null==i?void 0:i.toUpperCase())!=="REVALIDATED"&&!(404===n.status&&t.unstable_onlyGenerated))throw Error(`Invalid response ${n.status}`)}else if(n.revalidate)await n.revalidate({urlPath:e,revalidateHeaders:o,opts:t});else throw Error("Invariant: required internal revalidate method not passed to api-utils")}catch(t){throw Error(`Failed to revalidate ${e}: ${B(t)?t.message:t}`)}}async function K(e,t,n,s,d,c,g,y){try{var x,b,w,S;if(!s){t.statusCode=404,t.end("Not Found");return}let c=s.config||{},h=(null==(x=c.api)?void 0:x.bodyParser)!==!1,m=(null==(b=c.api)?void 0:b.responseLimit)??!0;null==(w=c.api)||w.externalResolver,v({req:e},"cookies",(S=e.headers,function(){let{cookie:e}=S;if(!e)return{};let{parse:t}=r("./dist/compiled/cookie/index.js");return t(Array.isArray(e)?e.join("; "):e)})),e.query=n,v({req:e},"previewData",()=>(function(e,t,n){var s,d;let c;if(n&&function(e,t){let r=o.from(e.headers);return{isOnDemandRevalidate:r.get(i)===t.previewModeId,revalidateOnlyGenerated:r.has(a)}}(e,n).isOnDemandRevalidate)return!1;if(l in e)return e[l];let h=o.from(e.headers),m=new q.RequestCookies(h),v=null==(s=m.get(p))?void 0:s.value,g=null==(d=m.get(u))?void 0:d.value;if(v&&!g&&v===n.previewModeId){let t={};return Object.defineProperty(e,l,{value:t,enumerable:!1}),t}if(!v&&!g)return!1;if(!v||!g||v!==n.previewModeId)return f(t),!1;try{c=r("next/dist/compiled/jsonwebtoken").verify(g,n.previewModeSigningKey)}catch{return f(t),!1}let{decryptWithSecret:y}=r("./dist/esm/server/crypto-utils.js"),x=y(Buffer.from(n.previewModeEncryptionKey),c.data);try{let t=JSON.parse(x);return Object.defineProperty(e,l,{value:t,enumerable:!1}),t}catch{return!1}})(e,t,d)),v({req:e},"preview",()=>!1!==e.previewData||void 0),v({req:e},"draftMode",()=>e.preview),h&&!e.body&&(e.body=await I(e,c.api&&c.api.bodyParser&&c.api.bodyParser.sizeLimit?c.api.bodyParser.sizeLimit:"1mb"));let g=0,y=m&&"boolean"!=typeof m?O().parse(m):4194304,R=t.write,C=t.end;t.write=(...e)=>(g+=Buffer.byteLength(e[0]||""),R.apply(t,e)),t.end=(...r)=>(r.length&&"function"!=typeof r[0]&&(g+=Buffer.byteLength(r[0]||"")),m&&g>=y&&console.warn(`API response for ${e.url} exceeds ${O().format(y)}. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit`),C.apply(t,r)),t.status=e=>(t.statusCode=e,t),t.send=r=>(function(e,t,r){var n;if(null==r){t.end();return}if(204===t.statusCode||304===t.statusCode){t.removeHeader("Content-Type"),t.removeHeader("Content-Length"),t.removeHeader("Transfer-Encoding"),t.end();return}let o=t.getHeader("Content-Type");if(r instanceof L.Stream){o||t.setHeader("Content-Type","application/octet-stream"),r.pipe(t);return}let i=["object","number","boolean"].includes(typeof r),a=i?JSON.stringify(r):r;if((n=k(a))&&t.setHeader("ETag",n),!E()(e.headers,{etag:n})||(t.statusCode=304,t.end(),0)){if(Buffer.isBuffer(r)){o||t.setHeader("Content-Type","application/octet-stream"),t.setHeader("Content-Length",r.length),t.end(r);return}i&&t.setHeader("Content-Type","application/json; charset=utf-8"),t.setHeader("Content-Length",Buffer.byteLength(a)),t.end(a)}})(e,t,r),t.json=e=>{t.setHeader("Content-Type","application/json; charset=utf-8"),t.send(JSON.stringify(e))},t.redirect=(e,r)=>(function(e,t,r){if("string"==typeof t&&(r=t,t=307),"number"!=typeof t||"string"!=typeof r)throw Error("Invalid redirect arguments. Please use a single argument URL, e.g. res.redirect('/destination') or use a status code and URL, e.g. res.redirect(307, '/destination').");return e.writeHead(t,{Location:r}),e.write(r),e.end(),e})(t,e,r),t.setDraftMode=(e={enable:!0})=>(function(e,t){if(!D(t.previewModeId))throw Error("invariant: invalid previewModeId");let n=t.enable?void 0:new Date(0),{serialize:o}=r("./dist/compiled/cookie/index.js"),i=e.getHeader("Set-Cookie");return e.setHeader("Set-Cookie",[..."string"==typeof i?[i]:Array.isArray(i)?i:[],o(p,t.previewModeId,{httpOnly:!0,sameSite:"none",secure:!0,path:"/",expires:n})]),e})(t,Object.assign({},d,e)),t.setPreviewData=(e,n={})=>(function(e,t,n){if(!D(n.previewModeId))throw Error("invariant: invalid previewModeId");if(!D(n.previewModeEncryptionKey))throw Error("invariant: invalid previewModeEncryptionKey");if(!D(n.previewModeSigningKey))throw Error("invariant: invalid previewModeSigningKey");let o=r("next/dist/compiled/jsonwebtoken"),{encryptWithSecret:i}=r("./dist/esm/server/crypto-utils.js"),a=o.sign({data:i(Buffer.from(n.previewModeEncryptionKey),JSON.stringify(t))},n.previewModeSigningKey,{algorithm:"HS256",...void 0!==n.maxAge?{expiresIn:n.maxAge}:void 0});if(a.length>2048)throw Error("Preview data is limited to 2KB currently, reduce how much data you are storing as preview data to continue");let{serialize:s}=r("./dist/compiled/cookie/index.js"),d=e.getHeader("Set-Cookie");return e.setHeader("Set-Cookie",[..."string"==typeof d?[d]:Array.isArray(d)?d:[],s(p,n.previewModeId,{httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==n.maxAge?{maxAge:n.maxAge}:void 0,...void 0!==n.path?{path:n.path}:void 0}),s(u,a,{httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==n.maxAge?{maxAge:n.maxAge}:void 0,...void 0!==n.path?{path:n.path}:void 0})]),e})(t,e,Object.assign({},d,n)),t.clearPreviewData=(e={})=>f(t,e),t.revalidate=(t,r)=>z(t,r||{},e,d);let N=s.default||s;await N(e,t)}catch(e){if(e instanceof h)m(t,e.statusCode,e.message);else{if(g)throw B(e)&&(e.page=y),e;if(console.error(e),c)throw e;m(t,500,"Internal Server Error")}}}class U extends g{constructor(e){if(super(e),"function"!=typeof e.userland.default)throw Error(`Page ${e.definition.page} does not export a default function.`);this.apiResolverWrapped=function(e,t){return(...r)=>{var n;return null==(n=(0,d.getTracer)().getRootSpanAttributes())||n.set("next.route",e),(0,d.getTracer)().trace(j.runHandler,{spanName:`executing api route (pages) ${e}`},()=>t(...r))}}(e.definition.page,K)}async render(e,t,r){let{apiResolverWrapped:n}=this;await n(e,t,r.query,this.userland,{...r.previewProps,revalidate:r.revalidate,trustHostHeader:r.trustHostHeader,allowedRevalidateHeaderKeys:r.allowedRevalidateHeaderKeys,hostname:r.hostname},r.minimalMode,r.dev,r.page)}}let F=U})(),module.exports=n})();
 //# sourceMappingURL=pages-api-turbo.runtime.prod.js.map
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>pages-api.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-api.ru..time.prod.js</strong></summary>

```diff
@@ -17,5 +17,5 @@
  * Copyright(c) 2012 TJ Holowaychuk
  * Copyright(c) 2016-2017 Douglas Christopher Wilson
  * MIT Licensed
- */var t=/(?:^|,)\s*?no-cache\s*?(?:,|$)/;function r(e){var t=e&&Date.parse(e);return"number"==typeof t?t:NaN}e.exports=function(e,n){var o=e["if-modified-since"],i=e["if-none-match"];if(!o&&!i)return!1;var a=e["cache-control"];if(a&&t.test(a))return!1;if(i&&"*"!==i){var s=n.etag;if(!s)return!1;for(var d=!0,p=function(e){for(var t=0,r=[],n=0,o=0,i=e.length;o<i;o++)switch(e.charCodeAt(o)){case 32:n===t&&(n=t=o+1);break;case 44:r.push(e.substring(n,t)),n=t=o+1;break;default:t=o+1}return r.push(e.substring(n,t)),r}(i),u=0;u<p.length;u++){var l=p[u];if(l===s||l==="W/"+s||"W/"+l===s){d=!1;break}}if(d)return!1}if(o){var c=n["last-modified"];if(!c||!(r(c)<=r(o)))return!1}return!0}}},r={};function n(e){var o=r[e];if(void 0!==o)return o.exports;var i=r[e]={exports:{}},a=!0;try{t[e](i,i.exports,n),a=!1}finally{a&&delete r[e]}return i.exports}n.ab=__dirname+"/";var o=n(695);e.exports=o})()},"./dist/esm/server/crypto-utils.js":(e,t,r)=>{"use strict";r.r(t),r.d(t,{decryptWithSecret:()=>s,encryptWithSecret:()=>a});let n=require("crypto");var o=r.n(n);let i="aes-256-gcm";function a(e,t){let r=o().randomBytes(16),n=o().randomBytes(64),a=o().pbkdf2Sync(e,n,1e5,32,"sha512"),s=o().createCipheriv(i,a,r),d=Buffer.concat([s.update(t,"utf8"),s.final()]),p=s.getAuthTag();return Buffer.concat([n,r,p,d]).toString("hex")}function s(e,t){let r=Buffer.from(t,"hex"),n=r.slice(0,64),a=r.slice(64,80),s=r.slice(80,96),d=r.slice(96),p=o().pbkdf2Sync(e,n,1e5,32,"sha512"),u=o().createDecipheriv(i,p,a);return u.setAuthTag(s),u.update(d)+u.final("utf8")}},"next/dist/compiled/jsonwebtoken":e=>{"use strict";e.exports=require("next/dist/compiled/jsonwebtoken")},"next/dist/compiled/node-html-parser":e=>{"use strict";e.exports=require("next/dist/compiled/node-html-parser")},"next/dist/compiled/raw-body":e=>{"use strict";e.exports=require("next/dist/compiled/raw-body")},querystring:e=>{"use strict";e.exports=require("querystring")}},t={};function r(n){var o=t[n];if(void 0!==o)return o.exports;var i=t[n]={exports:{}};return e[n](i,i.exports,r),i.exports}r.n=e=>{var t=e&&e.__esModule?()=>e.default:()=>e;return r.d(t,{a:t}),t},r.d=(e,t)=>{for(var n in t)r.o(t,n)&&!r.o(e,n)&&Object.defineProperty(e,n,{enumerable:!0,get:t[n]})},r.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),r.r=e=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})};var n={};(()=>{"use strict";r.r(n),r.d(n,{PagesAPIRouteModule:()=>U,default:()=>F});class e{static get(e,t,r){let n=Reflect.get(e,t,r);return"function"==typeof n?n.bind(e):n}static set(e,t,r,n){return Reflect.set(e,t,r,n)}static has(e,t){return Reflect.has(e,t)}static deleteProperty(e,t){return Reflect.deleteProperty(e,t)}}class t extends Error{constructor(){super("Headers cannot be modified. Read more: https://nextjs.org/docs/app/api-reference/functions/headers")}static callable(){throw new t}}class o extends Headers{constructor(t){super(),this.headers=new Proxy(t,{get(r,n,o){if("symbol"==typeof n)return e.get(r,n,o);let i=n.toLowerCase(),a=Object.keys(t).find(e=>e.toLowerCase()===i);if(void 0!==a)return e.get(r,a,o)},set(r,n,o,i){if("symbol"==typeof n)return e.set(r,n,o,i);let a=n.toLowerCase(),s=Object.keys(t).find(e=>e.toLowerCase()===a);return e.set(r,s??n,o,i)},has(r,n){if("symbol"==typeof n)return e.has(r,n);let o=n.toLowerCase(),i=Object.keys(t).find(e=>e.toLowerCase()===o);return void 0!==i&&e.has(r,i)},deleteProperty(r,n){if("symbol"==typeof n)return e.deleteProperty(r,n);let o=n.toLowerCase(),i=Object.keys(t).find(e=>e.toLowerCase()===o);return void 0===i||e.deleteProperty(r,i)}})}static seal(r){return new Proxy(r,{get(r,n,o){switch(n){case"append":case"delete":case"set":return t.callable;default:return e.get(r,n,o)}}})}merge(e){return Array.isArray(e)?e.join(", "):e}static from(e){return e instanceof Headers?e:new o(e)}append(e,t){let r=this.headers[e];"string"==typeof r?this.headers[e]=[r,t]:Array.isArray(r)?r.push(t):this.headers[e]=t}delete(e){delete this.headers[e]}get(e){let t=this.headers[e];return void 0!==t?this.merge(t):null}has(e){return void 0!==this.headers[e]}set(e,t){this.headers[e]=t}forEach(e,t){for(let[r,n]of this.entries())e.call(t,n,r,this)}*entries(){for(let e of Object.keys(this.headers)){let t=e.toLowerCase(),r=this.get(t);yield[t,r]}}*keys(){for(let e of Object.keys(this.headers)){let t=e.toLowerCase();yield t}}*values(){for(let e of Object.keys(this.headers)){let t=this.get(e);yield t}}[Symbol.iterator](){return this.entries()}}let i="x-prerender-revalidate",a="x-prerender-revalidate-if-generated",s={shared:"shared",reactServerComponents:"rsc",serverSideRendering:"ssr",actionBrowser:"action-browser",api:"api",middleware:"middleware",instrument:"instrument",edgeAsset:"edge-asset",appPagesBrowser:"app-pages-browser",appMetadataRoute:"app-metadata-route"};({...s,GROUP:{builtinReact:[s.reactServerComponents,s.actionBrowser,s.appMetadataRoute],serverOnly:[s.reactServerComponents,s.actionBrowser,s.appMetadataRoute,s.instrument,s.middleware],neutralTarget:[s.api],clientOnly:[s.serverSideRendering,s.appPagesBrowser],bundled:[s.reactServerComponents,s.actionBrowser,s.appMetadataRoute,s.serverSideRendering,s.appPagesBrowser,s.shared,s.instrument]}});let d=require("next/dist/server/lib/trace/tracer");(function(e){e.handleRequest="BaseServer.handleRequest",e.run="BaseServer.run",e.pipe="BaseServer.pipe",e.getStaticHTML="BaseServer.getStaticHTML",e.render="BaseServer.render",e.renderToResponseWithComponents="BaseServer.renderToResponseWithComponents",e.renderToResponse="BaseServer.renderToResponse",e.renderToHTML="BaseServer.renderToHTML",e.renderError="BaseServer.renderError",e.renderErrorToResponse="BaseServer.renderErrorToResponse",e.renderErrorToHTML="BaseServer.renderErrorToHTML",e.render404="BaseServer.render404"})(y||(y={})),function(e){e.loadDefaultErrorComponents="LoadComponents.loadDefaultErrorComponents",e.loadComponents="LoadComponents.loadComponents"}(x||(x={})),function(e){e.getRequestHandler="NextServer.getRequestHandler",e.getServer="NextServer.getServer",e.getServerRequestHandler="NextServer.getServerRequestHandler",e.createServer="createServer.createServer"}(b||(b={})),function(e){e.compression="NextNodeServer.compression",e.getBuildId="NextNodeServer.getBuildId",e.createComponentTree="NextNodeServer.createComponentTree",e.clientComponentLoading="NextNodeServer.clientComponentLoading",e.getLayoutOrPageModule="NextNodeServer.getLayoutOrPageModule",e.generateStaticRoutes="NextNodeServer.generateStaticRoutes",e.generateFsStaticRoutes="NextNodeServer.generateFsStaticRoutes",e.generatePublicRoutes="NextNodeServer.generatePublicRoutes",e.generateImageRoutes="NextNodeServer.generateImageRoutes.route",e.sendRenderResult="NextNodeServer.sendRenderResult",e.proxyRequest="NextNodeServer.proxyRequest",e.runApi="NextNodeServer.runApi",e.render="NextNodeServer.render",e.renderHTML="NextNodeServer.renderHTML",e.imageOptimizer="NextNodeServer.imageOptimizer",e.getPagePath="NextNodeServer.getPagePath",e.getRoutesManifest="NextNodeServer.getRoutesManifest",e.findPageComponents="NextNodeServer.findPageComponents",e.getFontManifest="NextNodeServer.getFontManifest",e.getServerComponentManifest="NextNodeServer.getServerComponentManifest",e.getRequestHandler="NextNodeServer.getRequestHandler",e.renderToHTML="NextNodeServer.renderToHTML",e.renderError="NextNodeServer.renderError",e.renderErrorToHTML="NextNodeServer.renderErrorToHTML",e.render404="NextNodeServer.render404",e.startResponse="NextNodeServer.startResponse",e.route="route",e.onProxyReq="onProxyReq",e.apiResolver="apiResolver",e.internalFetch="internalFetch"}(w||(w={})),(S||(S={})).startServer="startServer.startServer",function(e){e.getServerSideProps="Render.getServerSideProps",e.getStaticProps="Render.getStaticProps",e.renderToString="Render.renderToString",e.renderDocument="Render.renderDocument",e.createBodyResult="Render.createBodyResult"}(R||(R={})),function(e){e.renderToString="AppRender.renderToString",e.renderToReadableStream="AppRender.renderToReadableStream",e.getBodyResult="AppRender.getBodyResult",e.fetch="AppRender.fetch"}(C||(C={})),(N||(N={})).executeRoute="Router.executeRoute",(j||(j={})).runHandler="Node.runHandler",(T||(T={})).runHandler="AppRouteRouteHandlers.runHandler",function(e){e.generateMetadata="ResolveMetadata.generateMetadata",e.generateViewport="ResolveMetadata.generateViewport"}(_||(_={})),(A||(A={})).execute="Middleware.execute";let p="__prerender_bypass",u="__next_preview_data",l=Symbol(u),c=Symbol(p);function f(e,t={}){if(c in e)return e;let{serialize:n}=r("./dist/compiled/cookie/index.js"),o=e.getHeader("Set-Cookie");return e.setHeader("Set-Cookie",[..."string"==typeof o?[o]:Array.isArray(o)?o:[],n(p,"",{expires:new Date(0),httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==t.path?{path:t.path}:void 0}),n(u,"",{expires:new Date(0),httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==t.path?{path:t.path}:void 0})]),Object.defineProperty(e,c,{value:!0,enumerable:!1}),e}class h extends Error{constructor(e,t){super(t),this.statusCode=e}}function m(e,t,r){e.statusCode=t,e.statusMessage=r,e.end(r)}function v({req:e},t,r){let n={configurable:!0,enumerable:!0},o={...n,writable:!0};Object.defineProperty(e,t,{...n,get:()=>{let n=r();return Object.defineProperty(e,t,{...o,value:n}),n},set:r=>{Object.defineProperty(e,t,{...o,value:r})}})}class g{constructor({userland:e,definition:t}){this.userland=e,this.definition=t}}var y,x,b,w,S,R,C,N,j,T,_,A,M=r("./dist/compiled/bytes/index.js"),O=r.n(M);let P=e=>{let t=e.length,r=0,n=0,o=8997,i=0,a=33826,s=0,d=40164,p=0,u=52210;for(;r<t;)o^=e.charCodeAt(r++),n=435*o,i=435*a,s=435*d,p=435*u,s+=o<<8,p+=a<<8,i+=n>>>16,o=65535&n,s+=i>>>16,a=65535&i,u=p+(s>>>16)&65535,d=65535&s;return(15&u)*281474976710656+4294967296*d+65536*a+(o^u>>4)},k=(e,t=!1)=>(t?'W/"':'"')+P(e).toString(36)+e.length.toString(36)+'"';"undefined"!=typeof performance&&["mark","measure","getEntriesByName"].every(e=>"function"==typeof performance[e]);var E=r("./dist/compiled/fresh/index.js"),H=r.n(E);let L=require("stream");function B(e){return"object"==typeof e&&null!==e&&"name"in e&&"message"in e}var q=r("./dist/compiled/@edge-runtime/cookies/index.js"),$=r("./dist/compiled/content-type/index.js");async function I(e,t){let n,o;try{n=(0,$.parse)(e.headers["content-type"]||"text/plain")}catch{n=(0,$.parse)("text/plain")}let{type:i,parameters:a}=n,s=a.charset||"utf-8";try{let n=r("next/dist/compiled/raw-body");o=await n(e,{encoding:s,limit:t})}catch(e){if(B(e)&&"entity.too.large"===e.type)throw new h(413,`Body exceeded ${t} limit`);throw new h(400,"Invalid body")}let d=o.toString();return"application/json"===i||"application/ld+json"===i?function(e){if(0===e.length)return{};try{return JSON.parse(e)}catch(e){throw new h(400,"Invalid JSON")}}(d):"application/x-www-form-urlencoded"===i?r("querystring").decode(d):d}function D(e){return"string"==typeof e&&e.length>=16}async function K(e,t,r,n){if("string"!=typeof e||!e.startsWith("/"))throw Error(`Invalid urlPath provided to revalidate(), must be a path e.g. /blog/post-1, received ${e}`);let o={[i]:n.previewModeId,...t.unstable_onlyGenerated?{[a]:"1"}:{}},s=[...n.allowedRevalidateHeaderKeys||[],...n.trustHostHeader?["cookie","x-vercel-protection-bypass"]:[]];for(let e of Object.keys(r.headers))s.includes(e)&&(o[e]=r.headers[e]);try{if(n.trustHostHeader){let n=await fetch(`https://${r.headers.host}${e}`,{method:"HEAD",headers:o}),i=n.headers.get("x-vercel-cache")||n.headers.get("x-nextjs-cache");if((null==i?void 0:i.toUpperCase())!=="REVALIDATED"&&!(404===n.status&&t.unstable_onlyGenerated))throw Error(`Invalid response ${n.status}`)}else if(n.revalidate)await n.revalidate({urlPath:e,revalidateHeaders:o,opts:t});else throw Error("Invariant: required internal revalidate method not passed to api-utils")}catch(t){throw Error(`Failed to revalidate ${e}: ${B(t)?t.message:t}`)}}async function z(e,t,n,s,d,c,g,y,x){try{var b,w,S,R;if(!s){t.statusCode=404,t.end("Not Found");return}let c=s.config||{},h=(null==(b=c.api)?void 0:b.bodyParser)!==!1,m=(null==(w=c.api)?void 0:w.responseLimit)??!0;null==(S=c.api)||S.externalResolver,v({req:e},"cookies",(R=e.headers,function(){let{cookie:e}=R;if(!e)return{};let{parse:t}=r("./dist/compiled/cookie/index.js");return t(Array.isArray(e)?e.join("; "):e)})),e.query=n,v({req:e},"previewData",()=>(function(e,t,n){var s,d;let c;if(n&&function(e,t){let r=o.from(e.headers);return{isOnDemandRevalidate:r.get(i)===t.previewModeId,revalidateOnlyGenerated:r.has(a)}}(e,n).isOnDemandRevalidate)return!1;if(l in e)return e[l];let h=o.from(e.headers),m=new q.RequestCookies(h),v=null==(s=m.get(p))?void 0:s.value,g=null==(d=m.get(u))?void 0:d.value;if(v&&!g&&v===n.previewModeId){let t={};return Object.defineProperty(e,l,{value:t,enumerable:!1}),t}if(!v&&!g)return!1;if(!v||!g||v!==n.previewModeId)return f(t),!1;try{c=r("next/dist/compiled/jsonwebtoken").verify(g,n.previewModeSigningKey)}catch{return f(t),!1}let{decryptWithSecret:y}=r("./dist/esm/server/crypto-utils.js"),x=y(Buffer.from(n.previewModeEncryptionKey),c.data);try{let t=JSON.parse(x);return Object.defineProperty(e,l,{value:t,enumerable:!1}),t}catch{return!1}})(e,t,d)),v({req:e},"preview",()=>!1!==e.previewData||void 0),v({req:e},"draftMode",()=>e.preview),h&&!e.body&&(e.body=await I(e,c.api&&c.api.bodyParser&&c.api.bodyParser.sizeLimit?c.api.bodyParser.sizeLimit:"1mb"));let g=0,y=m&&"boolean"!=typeof m?O().parse(m):4194304,x=t.write,C=t.end;t.write=(...e)=>(g+=Buffer.byteLength(e[0]||""),x.apply(t,e)),t.end=(...r)=>(r.length&&"function"!=typeof r[0]&&(g+=Buffer.byteLength(r[0]||"")),m&&g>=y&&console.warn(`API response for ${e.url} exceeds ${O().format(y)}. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit`),C.apply(t,r)),t.status=e=>(t.statusCode=e,t),t.send=r=>(function(e,t,r){var n;if(null==r){t.end();return}if(204===t.statusCode||304===t.statusCode){t.removeHeader("Content-Type"),t.removeHeader("Content-Length"),t.removeHeader("Transfer-Encoding"),t.end();return}let o=t.getHeader("Content-Type");if(r instanceof L.Stream){o||t.setHeader("Content-Type","application/octet-stream"),r.pipe(t);return}let i=["object","number","boolean"].includes(typeof r),a=i?JSON.stringify(r):r;if((n=k(a))&&t.setHeader("ETag",n),!H()(e.headers,{etag:n})||(t.statusCode=304,t.end(),0)){if(Buffer.isBuffer(r)){o||t.setHeader("Content-Type","application/octet-stream"),t.setHeader("Content-Length",r.length),t.end(r);return}i&&t.setHeader("Content-Type","application/json; charset=utf-8"),t.setHeader("Content-Length",Buffer.byteLength(a)),t.end(a)}})(e,t,r),t.json=e=>{t.setHeader("Content-Type","application/json; charset=utf-8"),t.send(JSON.stringify(e))},t.redirect=(e,r)=>(function(e,t,r){if("string"==typeof t&&(r=t,t=307),"number"!=typeof t||"string"!=typeof r)throw Error("Invalid redirect arguments. Please use a single argument URL, e.g. res.redirect('/destination') or use a status code and URL, e.g. res.redirect(307, '/destination').");return e.writeHead(t,{Location:r}),e.write(r),e.end(),e})(t,e,r),t.setDraftMode=(e={enable:!0})=>(function(e,t){if(!D(t.previewModeId))throw Error("invariant: invalid previewModeId");let n=t.enable?void 0:new Date(0),{serialize:o}=r("./dist/compiled/cookie/index.js"),i=e.getHeader("Set-Cookie");return e.setHeader("Set-Cookie",[..."string"==typeof i?[i]:Array.isArray(i)?i:[],o(p,t.previewModeId,{httpOnly:!0,sameSite:"none",secure:!0,path:"/",expires:n})]),e})(t,Object.assign({},d,e)),t.setPreviewData=(e,n={})=>(function(e,t,n){if(!D(n.previewModeId))throw Error("invariant: invalid previewModeId");if(!D(n.previewModeEncryptionKey))throw Error("invariant: invalid previewModeEncryptionKey");if(!D(n.previewModeSigningKey))throw Error("invariant: invalid previewModeSigningKey");let o=r("next/dist/compiled/jsonwebtoken"),{encryptWithSecret:i}=r("./dist/esm/server/crypto-utils.js"),a=o.sign({data:i(Buffer.from(n.previewModeEncryptionKey),JSON.stringify(t))},n.previewModeSigningKey,{algorithm:"HS256",...void 0!==n.maxAge?{expiresIn:n.maxAge}:void 0});if(a.length>2048)throw Error("Preview data is limited to 2KB currently, reduce how much data you are storing as preview data to continue");let{serialize:s}=r("./dist/compiled/cookie/index.js"),d=e.getHeader("Set-Cookie");return e.setHeader("Set-Cookie",[..."string"==typeof d?[d]:Array.isArray(d)?d:[],s(p,n.previewModeId,{httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==n.maxAge?{maxAge:n.maxAge}:void 0,...void 0!==n.path?{path:n.path}:void 0}),s(u,a,{httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==n.maxAge?{maxAge:n.maxAge}:void 0,...void 0!==n.path?{path:n.path}:void 0})]),e})(t,e,Object.assign({},d,n)),t.clearPreviewData=(e={})=>f(t,e),t.revalidate=(t,r)=>K(t,r||{},e,d);let N=s.default||s;await N(e,t)}catch(r){if(null==x||x(r,e,{routerKind:"Pages Router",routePath:y||"",routeType:"route"}),r instanceof h)m(t,r.statusCode,r.message);else{if(g)throw B(r)&&(r.page=y),r;if(console.error(r),c)throw r;m(t,500,"Internal Server Error")}}}class U extends g{constructor(e){if(super(e),"function"!=typeof e.userland.default)throw Error(`Page ${e.definition.page} does not export a default function.`);this.apiResolverWrapped=function(e,t){return(...r)=>{var n;return null==(n=(0,d.getTracer)().getRootSpanAttributes())||n.set("next.route",e),(0,d.getTracer)().trace(j.runHandler,{spanName:`executing api route (pages) ${e}`},()=>t(...r))}}(e.definition.page,z)}async render(e,t,r){let{apiResolverWrapped:n}=this;await n(e,t,r.query,this.userland,{...r.previewProps,revalidate:r.revalidate,trustHostHeader:r.trustHostHeader,allowedRevalidateHeaderKeys:r.allowedRevalidateHeaderKeys,hostname:r.hostname},r.minimalMode,r.dev,r.page,r.onError)}}let F=U})(),module.exports=n})();
+ */var t=/(?:^|,)\s*?no-cache\s*?(?:,|$)/;function r(e){var t=e&&Date.parse(e);return"number"==typeof t?t:NaN}e.exports=function(e,n){var o=e["if-modified-since"],i=e["if-none-match"];if(!o&&!i)return!1;var a=e["cache-control"];if(a&&t.test(a))return!1;if(i&&"*"!==i){var s=n.etag;if(!s)return!1;for(var d=!0,p=function(e){for(var t=0,r=[],n=0,o=0,i=e.length;o<i;o++)switch(e.charCodeAt(o)){case 32:n===t&&(n=t=o+1);break;case 44:r.push(e.substring(n,t)),n=t=o+1;break;default:t=o+1}return r.push(e.substring(n,t)),r}(i),u=0;u<p.length;u++){var l=p[u];if(l===s||l==="W/"+s||"W/"+l===s){d=!1;break}}if(d)return!1}if(o){var c=n["last-modified"];if(!c||!(r(c)<=r(o)))return!1}return!0}}},r={};function n(e){var o=r[e];if(void 0!==o)return o.exports;var i=r[e]={exports:{}},a=!0;try{t[e](i,i.exports,n),a=!1}finally{a&&delete r[e]}return i.exports}n.ab=__dirname+"/";var o=n(695);e.exports=o})()},"./dist/esm/server/crypto-utils.js":(e,t,r)=>{"use strict";r.r(t),r.d(t,{decryptWithSecret:()=>s,encryptWithSecret:()=>a});let n=require("crypto");var o=r.n(n);let i="aes-256-gcm";function a(e,t){let r=o().randomBytes(16),n=o().randomBytes(64),a=o().pbkdf2Sync(e,n,1e5,32,"sha512"),s=o().createCipheriv(i,a,r),d=Buffer.concat([s.update(t,"utf8"),s.final()]),p=s.getAuthTag();return Buffer.concat([n,r,p,d]).toString("hex")}function s(e,t){let r=Buffer.from(t,"hex"),n=r.slice(0,64),a=r.slice(64,80),s=r.slice(80,96),d=r.slice(96),p=o().pbkdf2Sync(e,n,1e5,32,"sha512"),u=o().createDecipheriv(i,p,a);return u.setAuthTag(s),u.update(d)+u.final("utf8")}},"next/dist/compiled/jsonwebtoken":e=>{"use strict";e.exports=require("next/dist/compiled/jsonwebtoken")},"next/dist/compiled/node-html-parser":e=>{"use strict";e.exports=require("next/dist/compiled/node-html-parser")},"next/dist/compiled/raw-body":e=>{"use strict";e.exports=require("next/dist/compiled/raw-body")},querystring:e=>{"use strict";e.exports=require("querystring")}},t={};function r(n){var o=t[n];if(void 0!==o)return o.exports;var i=t[n]={exports:{}};return e[n](i,i.exports,r),i.exports}r.n=e=>{var t=e&&e.__esModule?()=>e.default:()=>e;return r.d(t,{a:t}),t},r.d=(e,t)=>{for(var n in t)r.o(t,n)&&!r.o(e,n)&&Object.defineProperty(e,n,{enumerable:!0,get:t[n]})},r.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),r.r=e=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})};var n={};(()=>{"use strict";r.r(n),r.d(n,{PagesAPIRouteModule:()=>U,default:()=>F});class e{static get(e,t,r){let n=Reflect.get(e,t,r);return"function"==typeof n?n.bind(e):n}static set(e,t,r,n){return Reflect.set(e,t,r,n)}static has(e,t){return Reflect.has(e,t)}static deleteProperty(e,t){return Reflect.deleteProperty(e,t)}}class t extends Error{constructor(){super("Headers cannot be modified. Read more: https://nextjs.org/docs/app/api-reference/functions/headers")}static callable(){throw new t}}class o extends Headers{constructor(t){super(),this.headers=new Proxy(t,{get(r,n,o){if("symbol"==typeof n)return e.get(r,n,o);let i=n.toLowerCase(),a=Object.keys(t).find(e=>e.toLowerCase()===i);if(void 0!==a)return e.get(r,a,o)},set(r,n,o,i){if("symbol"==typeof n)return e.set(r,n,o,i);let a=n.toLowerCase(),s=Object.keys(t).find(e=>e.toLowerCase()===a);return e.set(r,s??n,o,i)},has(r,n){if("symbol"==typeof n)return e.has(r,n);let o=n.toLowerCase(),i=Object.keys(t).find(e=>e.toLowerCase()===o);return void 0!==i&&e.has(r,i)},deleteProperty(r,n){if("symbol"==typeof n)return e.deleteProperty(r,n);let o=n.toLowerCase(),i=Object.keys(t).find(e=>e.toLowerCase()===o);return void 0===i||e.deleteProperty(r,i)}})}static seal(r){return new Proxy(r,{get(r,n,o){switch(n){case"append":case"delete":case"set":return t.callable;default:return e.get(r,n,o)}}})}merge(e){return Array.isArray(e)?e.join(", "):e}static from(e){return e instanceof Headers?e:new o(e)}append(e,t){let r=this.headers[e];"string"==typeof r?this.headers[e]=[r,t]:Array.isArray(r)?r.push(t):this.headers[e]=t}delete(e){delete this.headers[e]}get(e){let t=this.headers[e];return void 0!==t?this.merge(t):null}has(e){return void 0!==this.headers[e]}set(e,t){this.headers[e]=t}forEach(e,t){for(let[r,n]of this.entries())e.call(t,n,r,this)}*entries(){for(let e of Object.keys(this.headers)){let t=e.toLowerCase(),r=this.get(t);yield[t,r]}}*keys(){for(let e of Object.keys(this.headers)){let t=e.toLowerCase();yield t}}*values(){for(let e of Object.keys(this.headers)){let t=this.get(e);yield t}}[Symbol.iterator](){return this.entries()}}let i="x-prerender-revalidate",a="x-prerender-revalidate-if-generated",s={shared:"shared",reactServerComponents:"rsc",serverSideRendering:"ssr",actionBrowser:"action-browser",api:"api",middleware:"middleware",instrument:"instrument",edgeAsset:"edge-asset",appPagesBrowser:"app-pages-browser",appMetadataRoute:"app-metadata-route"};({...s,GROUP:{builtinReact:[s.reactServerComponents,s.actionBrowser,s.appMetadataRoute],serverOnly:[s.reactServerComponents,s.actionBrowser,s.appMetadataRoute,s.instrument,s.middleware],neutralTarget:[s.api],clientOnly:[s.serverSideRendering,s.appPagesBrowser],bundled:[s.reactServerComponents,s.actionBrowser,s.appMetadataRoute,s.serverSideRendering,s.appPagesBrowser,s.shared,s.instrument]}});let d=require("next/dist/server/lib/trace/tracer");(function(e){e.handleRequest="BaseServer.handleRequest",e.run="BaseServer.run",e.pipe="BaseServer.pipe",e.getStaticHTML="BaseServer.getStaticHTML",e.render="BaseServer.render",e.renderToResponseWithComponents="BaseServer.renderToResponseWithComponents",e.renderToResponse="BaseServer.renderToResponse",e.renderToHTML="BaseServer.renderToHTML",e.renderError="BaseServer.renderError",e.renderErrorToResponse="BaseServer.renderErrorToResponse",e.renderErrorToHTML="BaseServer.renderErrorToHTML",e.render404="BaseServer.render404"})(y||(y={})),function(e){e.loadDefaultErrorComponents="LoadComponents.loadDefaultErrorComponents",e.loadComponents="LoadComponents.loadComponents"}(x||(x={})),function(e){e.getRequestHandler="NextServer.getRequestHandler",e.getServer="NextServer.getServer",e.getServerRequestHandler="NextServer.getServerRequestHandler",e.createServer="createServer.createServer"}(b||(b={})),function(e){e.compression="NextNodeServer.compression",e.getBuildId="NextNodeServer.getBuildId",e.createComponentTree="NextNodeServer.createComponentTree",e.clientComponentLoading="NextNodeServer.clientComponentLoading",e.getLayoutOrPageModule="NextNodeServer.getLayoutOrPageModule",e.generateStaticRoutes="NextNodeServer.generateStaticRoutes",e.generateFsStaticRoutes="NextNodeServer.generateFsStaticRoutes",e.generatePublicRoutes="NextNodeServer.generatePublicRoutes",e.generateImageRoutes="NextNodeServer.generateImageRoutes.route",e.sendRenderResult="NextNodeServer.sendRenderResult",e.proxyRequest="NextNodeServer.proxyRequest",e.runApi="NextNodeServer.runApi",e.render="NextNodeServer.render",e.renderHTML="NextNodeServer.renderHTML",e.imageOptimizer="NextNodeServer.imageOptimizer",e.getPagePath="NextNodeServer.getPagePath",e.getRoutesManifest="NextNodeServer.getRoutesManifest",e.findPageComponents="NextNodeServer.findPageComponents",e.getFontManifest="NextNodeServer.getFontManifest",e.getServerComponentManifest="NextNodeServer.getServerComponentManifest",e.getRequestHandler="NextNodeServer.getRequestHandler",e.renderToHTML="NextNodeServer.renderToHTML",e.renderError="NextNodeServer.renderError",e.renderErrorToHTML="NextNodeServer.renderErrorToHTML",e.render404="NextNodeServer.render404",e.startResponse="NextNodeServer.startResponse",e.route="route",e.onProxyReq="onProxyReq",e.apiResolver="apiResolver",e.internalFetch="internalFetch"}(w||(w={})),(S||(S={})).startServer="startServer.startServer",function(e){e.getServerSideProps="Render.getServerSideProps",e.getStaticProps="Render.getStaticProps",e.renderToString="Render.renderToString",e.renderDocument="Render.renderDocument",e.createBodyResult="Render.createBodyResult"}(R||(R={})),function(e){e.renderToString="AppRender.renderToString",e.renderToReadableStream="AppRender.renderToReadableStream",e.getBodyResult="AppRender.getBodyResult",e.fetch="AppRender.fetch"}(C||(C={})),(N||(N={})).executeRoute="Router.executeRoute",(j||(j={})).runHandler="Node.runHandler",(T||(T={})).runHandler="AppRouteRouteHandlers.runHandler",function(e){e.generateMetadata="ResolveMetadata.generateMetadata",e.generateViewport="ResolveMetadata.generateViewport"}(_||(_={})),(A||(A={})).execute="Middleware.execute";let p="__prerender_bypass",u="__next_preview_data",l=Symbol(u),c=Symbol(p);function f(e,t={}){if(c in e)return e;let{serialize:n}=r("./dist/compiled/cookie/index.js"),o=e.getHeader("Set-Cookie");return e.setHeader("Set-Cookie",[..."string"==typeof o?[o]:Array.isArray(o)?o:[],n(p,"",{expires:new Date(0),httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==t.path?{path:t.path}:void 0}),n(u,"",{expires:new Date(0),httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==t.path?{path:t.path}:void 0})]),Object.defineProperty(e,c,{value:!0,enumerable:!1}),e}class h extends Error{constructor(e,t){super(t),this.statusCode=e}}function m(e,t,r){e.statusCode=t,e.statusMessage=r,e.end(r)}function v({req:e},t,r){let n={configurable:!0,enumerable:!0},o={...n,writable:!0};Object.defineProperty(e,t,{...n,get:()=>{let n=r();return Object.defineProperty(e,t,{...o,value:n}),n},set:r=>{Object.defineProperty(e,t,{...o,value:r})}})}class g{constructor({userland:e,definition:t}){this.userland=e,this.definition=t}}var y,x,b,w,S,R,C,N,j,T,_,A,M=r("./dist/compiled/bytes/index.js"),O=r.n(M);let P=e=>{let t=e.length,r=0,n=0,o=8997,i=0,a=33826,s=0,d=40164,p=0,u=52210;for(;r<t;)o^=e.charCodeAt(r++),n=435*o,i=435*a,s=435*d,p=435*u,s+=o<<8,p+=a<<8,i+=n>>>16,o=65535&n,s+=i>>>16,a=65535&i,u=p+(s>>>16)&65535,d=65535&s;return(15&u)*281474976710656+4294967296*d+65536*a+(o^u>>4)},k=(e,t=!1)=>(t?'W/"':'"')+P(e).toString(36)+e.length.toString(36)+'"';"undefined"!=typeof performance&&["mark","measure","getEntriesByName"].every(e=>"function"==typeof performance[e]);var H=r("./dist/compiled/fresh/index.js"),E=r.n(H);let L=require("stream");function B(e){return"object"==typeof e&&null!==e&&"name"in e&&"message"in e}var q=r("./dist/compiled/@edge-runtime/cookies/index.js"),$=r("./dist/compiled/content-type/index.js");async function I(e,t){let n,o;try{n=(0,$.parse)(e.headers["content-type"]||"text/plain")}catch{n=(0,$.parse)("text/plain")}let{type:i,parameters:a}=n,s=a.charset||"utf-8";try{let n=r("next/dist/compiled/raw-body");o=await n(e,{encoding:s,limit:t})}catch(e){if(B(e)&&"entity.too.large"===e.type)throw new h(413,`Body exceeded ${t} limit`);throw new h(400,"Invalid body")}let d=o.toString();return"application/json"===i||"application/ld+json"===i?function(e){if(0===e.length)return{};try{return JSON.parse(e)}catch(e){throw new h(400,"Invalid JSON")}}(d):"application/x-www-form-urlencoded"===i?r("querystring").decode(d):d}function D(e){return"string"==typeof e&&e.length>=16}async function z(e,t,r,n){if("string"!=typeof e||!e.startsWith("/"))throw Error(`Invalid urlPath provided to revalidate(), must be a path e.g. /blog/post-1, received ${e}`);let o={[i]:n.previewModeId,...t.unstable_onlyGenerated?{[a]:"1"}:{}},s=[...n.allowedRevalidateHeaderKeys||[],...n.trustHostHeader?["cookie","x-vercel-protection-bypass"]:[]];for(let e of Object.keys(r.headers))s.includes(e)&&(o[e]=r.headers[e]);try{if(n.trustHostHeader){let n=await fetch(`https://${r.headers.host}${e}`,{method:"HEAD",headers:o}),i=n.headers.get("x-vercel-cache")||n.headers.get("x-nextjs-cache");if((null==i?void 0:i.toUpperCase())!=="REVALIDATED"&&!(404===n.status&&t.unstable_onlyGenerated))throw Error(`Invalid response ${n.status}`)}else if(n.revalidate)await n.revalidate({urlPath:e,revalidateHeaders:o,opts:t});else throw Error("Invariant: required internal revalidate method not passed to api-utils")}catch(t){throw Error(`Failed to revalidate ${e}: ${B(t)?t.message:t}`)}}async function K(e,t,n,s,d,c,g,y){try{var x,b,w,S;if(!s){t.statusCode=404,t.end("Not Found");return}let c=s.config||{},h=(null==(x=c.api)?void 0:x.bodyParser)!==!1,m=(null==(b=c.api)?void 0:b.responseLimit)??!0;null==(w=c.api)||w.externalResolver,v({req:e},"cookies",(S=e.headers,function(){let{cookie:e}=S;if(!e)return{};let{parse:t}=r("./dist/compiled/cookie/index.js");return t(Array.isArray(e)?e.join("; "):e)})),e.query=n,v({req:e},"previewData",()=>(function(e,t,n){var s,d;let c;if(n&&function(e,t){let r=o.from(e.headers);return{isOnDemandRevalidate:r.get(i)===t.previewModeId,revalidateOnlyGenerated:r.has(a)}}(e,n).isOnDemandRevalidate)return!1;if(l in e)return e[l];let h=o.from(e.headers),m=new q.RequestCookies(h),v=null==(s=m.get(p))?void 0:s.value,g=null==(d=m.get(u))?void 0:d.value;if(v&&!g&&v===n.previewModeId){let t={};return Object.defineProperty(e,l,{value:t,enumerable:!1}),t}if(!v&&!g)return!1;if(!v||!g||v!==n.previewModeId)return f(t),!1;try{c=r("next/dist/compiled/jsonwebtoken").verify(g,n.previewModeSigningKey)}catch{return f(t),!1}let{decryptWithSecret:y}=r("./dist/esm/server/crypto-utils.js"),x=y(Buffer.from(n.previewModeEncryptionKey),c.data);try{let t=JSON.parse(x);return Object.defineProperty(e,l,{value:t,enumerable:!1}),t}catch{return!1}})(e,t,d)),v({req:e},"preview",()=>!1!==e.previewData||void 0),v({req:e},"draftMode",()=>e.preview),h&&!e.body&&(e.body=await I(e,c.api&&c.api.bodyParser&&c.api.bodyParser.sizeLimit?c.api.bodyParser.sizeLimit:"1mb"));let g=0,y=m&&"boolean"!=typeof m?O().parse(m):4194304,R=t.write,C=t.end;t.write=(...e)=>(g+=Buffer.byteLength(e[0]||""),R.apply(t,e)),t.end=(...r)=>(r.length&&"function"!=typeof r[0]&&(g+=Buffer.byteLength(r[0]||"")),m&&g>=y&&console.warn(`API response for ${e.url} exceeds ${O().format(y)}. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit`),C.apply(t,r)),t.status=e=>(t.statusCode=e,t),t.send=r=>(function(e,t,r){var n;if(null==r){t.end();return}if(204===t.statusCode||304===t.statusCode){t.removeHeader("Content-Type"),t.removeHeader("Content-Length"),t.removeHeader("Transfer-Encoding"),t.end();return}let o=t.getHeader("Content-Type");if(r instanceof L.Stream){o||t.setHeader("Content-Type","application/octet-stream"),r.pipe(t);return}let i=["object","number","boolean"].includes(typeof r),a=i?JSON.stringify(r):r;if((n=k(a))&&t.setHeader("ETag",n),!E()(e.headers,{etag:n})||(t.statusCode=304,t.end(),0)){if(Buffer.isBuffer(r)){o||t.setHeader("Content-Type","application/octet-stream"),t.setHeader("Content-Length",r.length),t.end(r);return}i&&t.setHeader("Content-Type","application/json; charset=utf-8"),t.setHeader("Content-Length",Buffer.byteLength(a)),t.end(a)}})(e,t,r),t.json=e=>{t.setHeader("Content-Type","application/json; charset=utf-8"),t.send(JSON.stringify(e))},t.redirect=(e,r)=>(function(e,t,r){if("string"==typeof t&&(r=t,t=307),"number"!=typeof t||"string"!=typeof r)throw Error("Invalid redirect arguments. Please use a single argument URL, e.g. res.redirect('/destination') or use a status code and URL, e.g. res.redirect(307, '/destination').");return e.writeHead(t,{Location:r}),e.write(r),e.end(),e})(t,e,r),t.setDraftMode=(e={enable:!0})=>(function(e,t){if(!D(t.previewModeId))throw Error("invariant: invalid previewModeId");let n=t.enable?void 0:new Date(0),{serialize:o}=r("./dist/compiled/cookie/index.js"),i=e.getHeader("Set-Cookie");return e.setHeader("Set-Cookie",[..."string"==typeof i?[i]:Array.isArray(i)?i:[],o(p,t.previewModeId,{httpOnly:!0,sameSite:"none",secure:!0,path:"/",expires:n})]),e})(t,Object.assign({},d,e)),t.setPreviewData=(e,n={})=>(function(e,t,n){if(!D(n.previewModeId))throw Error("invariant: invalid previewModeId");if(!D(n.previewModeEncryptionKey))throw Error("invariant: invalid previewModeEncryptionKey");if(!D(n.previewModeSigningKey))throw Error("invariant: invalid previewModeSigningKey");let o=r("next/dist/compiled/jsonwebtoken"),{encryptWithSecret:i}=r("./dist/esm/server/crypto-utils.js"),a=o.sign({data:i(Buffer.from(n.previewModeEncryptionKey),JSON.stringify(t))},n.previewModeSigningKey,{algorithm:"HS256",...void 0!==n.maxAge?{expiresIn:n.maxAge}:void 0});if(a.length>2048)throw Error("Preview data is limited to 2KB currently, reduce how much data you are storing as preview data to continue");let{serialize:s}=r("./dist/compiled/cookie/index.js"),d=e.getHeader("Set-Cookie");return e.setHeader("Set-Cookie",[..."string"==typeof d?[d]:Array.isArray(d)?d:[],s(p,n.previewModeId,{httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==n.maxAge?{maxAge:n.maxAge}:void 0,...void 0!==n.path?{path:n.path}:void 0}),s(u,a,{httpOnly:!0,sameSite:"none",secure:!0,path:"/",...void 0!==n.maxAge?{maxAge:n.maxAge}:void 0,...void 0!==n.path?{path:n.path}:void 0})]),e})(t,e,Object.assign({},d,n)),t.clearPreviewData=(e={})=>f(t,e),t.revalidate=(t,r)=>z(t,r||{},e,d);let N=s.default||s;await N(e,t)}catch(e){if(e instanceof h)m(t,e.statusCode,e.message);else{if(g)throw B(e)&&(e.page=y),e;if(console.error(e),c)throw e;m(t,500,"Internal Server Error")}}}class U extends g{constructor(e){if(super(e),"function"!=typeof e.userland.default)throw Error(`Page ${e.definition.page} does not export a default function.`);this.apiResolverWrapped=function(e,t){return(...r)=>{var n;return null==(n=(0,d.getTracer)().getRootSpanAttributes())||n.set("next.route",e),(0,d.getTracer)().trace(j.runHandler,{spanName:`executing api route (pages) ${e}`},()=>t(...r))}}(e.definition.page,K)}async render(e,t,r){let{apiResolverWrapped:n}=this;await n(e,t,r.query,this.userland,{...r.previewProps,revalidate:r.revalidate,trustHostHeader:r.trustHostHeader,allowedRevalidateHeaderKeys:r.allowedRevalidateHeaderKeys,hostname:r.hostname},r.minimalMode,r.dev,r.page)}}let F=U})(),module.exports=n})();
 //# sourceMappingURL=pages-api.runtime.prod.js.map
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: b8230261734743bdb1c58f4667f5b7f87f170ec6

File: packages/next/src/client/components/react-dev-overlay/app/hot-reloader-client.tsx [hunk 1]
```diff
@@ -294,6 +316,9 @@ function processMessage(
   switch (obj.action) {
     case HMR_ACTIONS_SENT_TO_BROWSER.BUILDING: {
       startLatency = Date.now()
+      if (!process.env.TURBOPACK) {
+        setPendingHotUpdateWebpack()
+      }
```
Comment (eps1lon) [inline packages/next/src/client/components/react-dev-overlay/app/hot-reloader-client.tsx:321]: The downside here is that we always get a hot update on client-side navigations as far as I can tell. Even if the runtime doesn't get new functionality, it does get updates to  `getFullHash` so we'd be waiting on something we don't necessarily need.


```js
"use strict";
/*
 * ATTENTION: An "eval-source-map" devtool has been used.
 * This devtool is neither made for production nor for readable output files.
 * It uses "eval()" calls to create a separate source file with attached SourceMaps in the browser devtools.
 * If you are trying to read the output file, select a different devtool (https://webpack.js.org/configuration/devtool/)
 * or disable the default devtool with "devtool: false".
 * If you are looking for production-ready output files, see mode: "production" (https://webpack.js.org/configuration/mode/).
 */
self["webpackHotUpdate_N_E"]("webpack",{},
/******/ function(__webpack_require__) { // webpackRuntimeModules
/******/ /* webpack/runtime/getFullHash */
/******/ (() => {
/******/ 	__webpack_require__.h = () => ("d60fe58ebbed83dc")
/******/ })();
/******/ 
/******/ }
);
```

File: packages/next/src/client/components/router-reducer/fetch-server-response.ts [hunk 2]
```diff
@@ -152,6 +153,14 @@ export async function fetchServerResponse(
       return doMpaNavigation(responseUrl.toString())
     }
 
+    // We may navigate to a page that requires a different Webpack runtime.
+    // In prod, every page will have the same Webpack runtime.
+    // In dev, the Webpack runtime is minimal for each page.
+    // We need to ensure the Webpack runtime is updated before executing client-side JS of the new page.
+    if (process.env.NODE_ENV !== 'production') {
+      await waitForWebpackRuntimeHotUpdate()
+    }
```
Comment (eps1lon) [inline packages/next/src/client/components/router-reducer/fetch-server-response.ts:162]: I guess we can safely ignore prefetches here?

File: packages/next/src/client/components/react-dev-overlay/app/hot-reloader-client.tsx [hunk 3]
```diff
@@ -46,17 +46,35 @@ let __nextDevClientId = Math.round(Math.random() * 100 + Date.now())
...
+  dispatcher: Dispatcher,
+  hasUpdates: boolean
+) {
   if (hasUpdates) {
     dispatcher.onBeforeRefresh()
   }
 }
 
-function onFastRefresh(
+function handleSuccessfulHotUpdateWebpack(
```
Comment (eps1lon) [inline packages/next/src/client/components/react-dev-overlay/app/hot-reloader-client.tsx:72]: drive-by rename. We only call this in Webpack implying there's no Fast Refresh in Turbopack. Fast Refresh is also a React feature that's enabled by HMR so it is a bit confusing to invoke that name at all.

File: packages/next/src/client/components/router-reducer/fetch-server-response.ts (hunk 2 above)
Comment (ztanner) [reply packages/next/src/client/components/router-reducer/fetch-server-response.ts:162]: right, in dev this function won't see any prefetches

File: packages/next/src/client/components/router-reducer/fetch-server-response.ts [hunk 4]
```diff
@@ -152,6 +153,14 @@ export async function fetchServerResponse(
       return doMpaNavigation(responseUrl.toString())
     }
 
+    // We may navigate to a page that requires a different Webpack runtime.
+    // In prod, every page will have the same Webpack runtime.
+    // In dev, the Webpack runtime is minimal for each page.
+    // We need to ensure the Webpack runtime is updated before executing client-side JS of the new page.
+    if (process.env.NODE_ENV !== 'production') {
```
Comment (eps1lon) [inline packages/next/src/client/components/router-reducer/fetch-server-response.ts:160]: TODO: Gate this behind `!process.env.TURBOPACK`

File: packages/next/src/client/components/router-reducer/fetch-server-response.ts (hunk 2 above)
Comment (ztanner) [reply packages/next/src/client/components/router-reducer/fetch-server-response.ts:162]: Which wording are you referring to?

Comment (eps1lon) [reply packages/next/src/client/components/router-reducer/fetch-server-response.ts:162]: "prefetchKind" being defined even though we're not prefetching. In my head I'm mixing this in with prefetches in the browser e.g. `<Link prefetch />` but it seems these are different concepts?

Comment (ztanner) [reply packages/next/src/client/components/router-reducer/fetch-server-response.ts:162]: Yeah I agree it's a bit confusing.  Part of what's confusing is that prefetches are tightly coupled to navigations. A navigation cannot exist without a prefetch (it's what the reducer acts upon when changing the router state), so that's why we have the concept of an "temporary" prefetch.

I don't think you're mixing the concepts though, `<Link prefetch />` does indeed _mostly_ map to what `prefetchKind` is, with the exception of the temporary one as you've noted. The comments in this file could use updating.

- `PrefetchKind.FULL` = `prefetch={true}`
- `PrefetchKind.AUTO` = prefetch left unspecified, or `prefetch={null}`
- `PrefetchKind.TEMPORARY` = A placeholder for a navigation that occurred without a regular prefetch. For example if you have `prefetch={false}`, or you're in dev, a temporary prefetch is created. If we later discover a prefetch intent, `TEMPORARY` will get replaced with whatever that intent is.

Comment (ztanner) [reply packages/next/src/client/components/router-reducer/fetch-server-response.ts:162]: > I haven't looked into 'temporary' vs undefined more. 

The `undefined` case is any other time we need to retrieve RSC data from the server when not directly associated with the navigation event. These come to mind but might not be exhaustive:

- "Lazy fetching" missing segments in layout-router (this is pre-PPR behavior)
- The dynamic data request in PPR (analogous to the lazy fetch above, but doesn't happen during render)
- Refreshing segment data as a result of something like `router.refresh()`

**Review by huozhi — APPROVED** [review]

File: test/development/app-hmr/hmr.test.ts [hunk 5]
```diff
@@ -92,39 +90,38 @@ describe(`app-dir-hmr`, () => {
...
         }
-        const envValue = await browser.elementByCss('p').text()
-        const mpa = await browser.eval('window.__TEST_NO_RELOAD === undefined')
-        // Flaky sometimes in Webpack:
-        // A. misses update and just receives `{ envValue: 'mac', mpa: false }`
-        // B. triggers error on server resulting in MPA: `{ envValue: 'ipad', mpa: true }` and server logs: ⨯ [TypeError: Cannot read properties of undefined (reading 'polyfillFiles')] ⨯ [TypeError: Cannot read properties of null (reading 'default')]
-        // A is more common than B.
-        expect({ envValue, mpa }).toEqual({
-          envValue:
-            isPPREnabledByDefault && !process.env.TURBOPACK
```
Comment (eps1lon) [inline test/development/app-hmr/hmr.test.ts:122]: no Hot Updates in this test fixed for PPR

**Review by gnoff — APPROVED** [review]

**Review by ztanner — APPROVED** [review]

File: packages/next/src/client/components/router-reducer/fetch-server-response.ts [hunk 6]
```diff
@@ -152,6 +156,30 @@ export async function fetchServerResponse(
...
+      process.env.NODE_ENV !== 'production' &&
+      isNavigation &&
+      !process.env.TURBOPACK
+    ) {
+      const webpackHMRTimedOut = await Promise.race([
+        waitForWebpackRuntimeHotUpdate().then(() => false),
+        new Promise((resolve) => setTimeout(() => resolve(true), 2000)),
+      ])
+
+      // Work around existing bugs where we receive an HRM update but no message that it was finished.
```
[the remark this answers is not in the document]
Comment (eps1lon) [reply packages/next/src/client/components/router-reducer/fetch-server-response.ts:203]: what if I meant human resource management here? 😅

**Comment by eps1lon** [comment]
I feel very uneasy about this fix. I'm kind of expecting that now any HMR update becomes an MPA since they can oftentimes take more than 2s. Any value we'd choose would be wrong. I still have to fix an issue in the React sync so maybe I think of a better fix until then.

**Comment by eps1lon** [comment]
With https://github.com/vercel/next.js/pull/67699, we no longer need to handle an indefinitely pending Hot Update by falling back to MPA after a timeout since the one case (that we know of) where we had an indefinitely pending Hot Update was fixed.

File: test/development/app-hmr/hmr.test.ts [hunk 7]
```diff
@@ -73,70 +70,77 @@ describe(`app-dir-hmr`, () => {
...
-              ? // FIXME: Should be 'ipad' but PPR+Webpack swallows the update reliably
-                'mac'
-              : 'ipad',
-          mpa: false,
-        })
       } finally {
-        await next.patchFile(envFile, envContent)
+        // TOOD: use sandbox instead
+        await next.patchFile(envFile, 'MY_DEVICE="mac"')
```
[the remark this answers is not in the document]
Comment (eps1lon) [reply test/development/app-hmr/hmr.test.ts:136]: Don't we already have `sandbox` for that?

File: packages/next/src/client/components/router-reducer/fetch-server-response.ts [hunk 8]
```diff
@@ -92,11 +93,14 @@ export async function fetchServerResponse(
...
 
   /**
-   * Three cases:
+   * Four cases:
    * - `prefetchKind` is `undefined`, it means it's a normal navigation, so we want to prefetch the page data fully
+   * - `prefetchKind` is `temporary` - it means it's a normal navigation, so we want to prefetch the page data fully
    * - `prefetchKind` is `full` - we want to prefetch the whole page so same as above
    * - `prefetchKind` is `auto` - if the page is dynamic, prefetch the page data partially, if static prefetch the page data fully
    */
+  const isNavigation =
```
[the remark this answers is not in the document]
Comment (eps1lon) [reply packages/next/src/client/components/router-reducer/fetch-server-response.ts:102]: >for example router.refresh will call this function without a prefetch kind. 

That is the terminology that used in the existing comment:
> `prefetchKind` is `undefined`, it means it's a normal navigation

> Is there significance to gating this logic behind the prefetchKind value or would it make sense to always do this check in development?

I thought that's what we originally discussed? https://github.com/vercel/next.js/pull/67673#discussion_r1674372468

I can remove this gating but this whole block seems a bit problematic since the comment seems to no longer reflect it's functionality. Or maybe it's just the wording that needs updating.

[the remark this answers is not in the document]
Comment (eps1lon) [reply packages/next/src/client/components/router-reducer/fetch-server-response.ts:102]: I've reverted the changes surrounding `isNavigating` for now until we can clarify the wording around `prefetchKind`

File: test/development/app-hmr/hmr.test.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (unstubbable) [reply test/development/app-hmr/hmr.test.ts]: `sandbox` stops and starts the server. The third argument of `patchFile` is useful for when you want to edit a file while the server is running, e.g. for HMR, without needing to manually cleanup the changes afterwards, so that they don't affect other tests.

[the remark this answers is not in the document]
Comment (eps1lon) [reply test/development/app-hmr/hmr.test.ts]: Huh, that's slightly confusing. If `sandbox` takes initial files that it patches, why doesn't it revert that patch on `cleanup()`?

[the remark this answers is not in the document]
Comment (unstubbable) [reply test/development/app-hmr/hmr.test.ts]: Yeah, that was confusingly phrased. Both are doing the cleanup, one implicitly, the other by calling `cleanup`. The difference is only whether you want to use the already running server without restarting.

[the remark this answers is not in the document]
Comment (eps1lon) [reply test/development/app-hmr/hmr.test.ts]: I also looked at the code and `cleanup()` from `sandbox` does not clean the initial files it was passed. It only calls `next.clean()` so if the `initialFiles` passed to `sandbox` are not the `initialFiles` passed to the `next` instance, it doesn't cleanup the patch.

I personally don't like the programmatic `initialFiles` since it doesn't allow to just run the test fixture without starting the test. So it seems to me we should get rid of `initialFiles` and make sure `sandbox` reverts patched files.

**Comment by eps1lon** [comment]
### Merge activity

* **Jul 22, 7:25 PM GMT+2**: @eps1lon started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/67673).

**Comment by karlhorky** [comment]
@eps1lon thanks for the PR, merge and publish in [`next@15.0.0-canary.77`](https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.77)

I've confirmed that this resolves issue https://github.com/vercel/next.js/issues/67783 in my reproduction:

```
pnpm dev

> @ dev /Users/k/p/repro-next-js-v15-react-rc-0-sass-webpack-require-not-a-function
> next dev

  ▲ Next.js 15.0.0-canary.77
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 3s
 ○ Compiling / ...
 ✓ Compiled / in 2.7s (482 modules)
 GET / 200 in 2884ms
 ✓ Compiled /favicon.ico in 176ms (275 modules)
 GET /favicon.ico 200 in 273ms
 ○ Compiling /non-home ...
 ✓ Compiled /non-home in 831ms (546 modules)
 GET /non-home 200 in 426ms
 GET /non-home 200 in 921ms
 GET /non-home 200 in 18ms
 GET / 200 in 80ms
 GET /favicon.ico 200 in 21ms
 GET /non-home 200 in 7ms
```

Here's the diff in the branch:

- https://github.com/karlhorky/repro-next-js-v15-react-rc-0-sass-webpack-require-not-a-function/compare/next-15.0.0-canary.77
