### PR TITLE
Re-enable scroll restoration behind flag

### LINKED ISSUE #12530: Using getServerSideProps breaks scroll restoration
# Bug report

## Describe the bug

When using getServerSideProps, a server roundtrip is made every time the user navigates to a page, to load the page's data json (generated by getServerSideProps).

This _also_ happens when the page is navigated to _via the browser's back and forward buttons_. The latency of the request, even when cached, breaks browser-native scroll restoration.

As there is no way to intervene with the request on the client side (using getServerSideProps, the request is made Next-internally), it can't be blocked. Using getInitialProps, it was possible to cache data on the client side and return it immediately. This is not possible anymore with getServerSideProps.

## To Reproduce

The issue is sufficiently documented [here](https://github.com/zeit/next.js/issues/3303).

## Expected behavior

Pages using getServerSideProps do not break scroll restoration when navigated to via the browser's back/forward buttons.

### LINKED ISSUE #13990: Experimental scroll restoration broken on forward nav
https://i.imgur.com/sGr07Tp.gif

### PR DESCRIPTION
**Pull request by ijjk**
This updates the scroll position saving to occur as the scroll position changes instead of trying to do it when the navigation is changing since the `popState` event doesn't allow us to update the leaving history state once the `popState` has occurred. 

The order of events that was previously attempted to save scroll position on a `popState` event (back/forward navigation)

1. history.state is already updated with state from `popState`
2. we replace state with the currently rendered page adding scroll info
3. we replace state again with the `popState` event state overriding scroll info

Using this approach the above event order is no longer in conflict since we don't attempt to populate the state with scroll position while it's leaving the state and instead do it while it is still the active state in history

This approach resembles existing solutions:
https://www.npmjs.com/package/scroll-behavior
https://twitter.com/ryanflorence/status/1029121580855488512

Fixes: https://github.com/vercel/next.js/issues/13990
Fixes: #12530
x-ref: https://github.com/vercel/next.js/pull/14075

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| buildDuration | 9.5s | 9.9s | ⚠️ +404ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | ⚠️ +541 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.62 | 1.611 | -0.01 |
| / avg req/sec | 1542.78 | 1552.05 | ⚠️ +9.27 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 0.976 | 0.92 | -0.06 |
| /error-in-render avg req/sec | 2561.58 | 2718.17 | ⚠️ +156.59 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f367.js gzip | 10.9 kB | 10.9 kB | ⚠️ +32 B |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.3 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 7.27 kB | 7.29 kB | ⚠️ +24 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.8 kB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 171 B | ✓ |
| _buildManife..dule.js gzip | 180 B | 180 B | ✓ |
| Overall change | 351 B | 351 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| index.html gzip | 896 B | 897 B | ⚠️ +1 B |
| link.html gzip | 902 B | 902 B | ✓ |
| withRouter.html gzip | 889 B | 890 B | ⚠️ +1 B |
| Overall change | 2.69 kB | 2.69 kB | ⚠️ +2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..83.module.js</strong></summary>

```diff
@@ -899,6 +899,29 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
             if (manualScrollRestoration) {
               window.history.scrollRestoration = "manual";
+              var scrollDebounceTimeout;
+
+              var debouncedScrollSave = () => {
+                if (scrollDebounceTimeout) clearTimeout(scrollDebounceTimeout);
+                scrollDebounceTimeout = setTimeout(() => {
+                  var { url, as: curAs, options } = history.state;
+                  this.changeState(
+                    "replaceState",
+                    url,
+                    curAs,
+                    _objectSpread(
+                      _objectSpread({}, options),
+                      {},
+                      {
+                        _N_X: window.scrollX,
+                        _N_Y: window.scrollY
+                      }
+                    )
+                  );
+                }, 10);
+              };
+
+              window.addEventListener("scroll", debouncedScrollSave);
             }
           }
         } // @deprecated backwards compatibility even though it's a private method.
@@ -1084,28 +1107,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                 }
 
                 Router.events.emit("beforeHistoryChange", as);
-
-                if (manualScrollRestoration && history.state) {
-                  var {
-                    url: curUrl,
-                    as: curAs,
-                    options: curOptions
-                  } = history.state;
-                  this.changeState(
-                    "replaceState",
-                    curUrl,
-                    curAs,
-                    _objectSpread(
-                      _objectSpread({}, curOptions),
-                      {},
-                      {
-                        _N_X: window.scrollX,
-                        _N_Y: window.scrollY
-                      }
-                    )
-                  );
-                }
-
                 this.changeState(method, url, as, options);
 
                 if (false) {
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..1e94a881a.js</strong></summary>

```diff
@@ -1037,6 +1037,33 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
             if (manualScrollRestoration) {
               window.history.scrollRestoration = "manual";
+              var scrollDebounceTimeout;
+
+              var debouncedScrollSave = function debouncedScrollSave() {
+                if (scrollDebounceTimeout) clearTimeout(scrollDebounceTimeout);
+                scrollDebounceTimeout = setTimeout(function() {
+                  var _history$state = history.state,
+                    url = _history$state.url,
+                    curAs = _history$state.as,
+                    options = _history$state.options;
+
+                  _this.changeState(
+                    "replaceState",
+                    url,
+                    curAs,
+                    _objectSpread(
+                      _objectSpread({}, options),
+                      {},
+                      {
+                        _N_X: window.scrollX,
+                        _N_Y: window.scrollY
+                      }
+                    )
+                  );
+                }, 10);
+              };
+
+              window.addEventListener("scroll", debouncedScrollSave);
             }
           }
         } // @deprecated backwards compatibility even though it's a private method.
@@ -1253,27 +1280,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
                       Router.events.emit("beforeHistoryChange", as);
 
-                      if (manualScrollRestoration && history.state) {
-                        var _history$state = history.state,
-                          curUrl = _history$state.url,
-                          curAs = _history$state.as,
-                          curOptions = _history$state.options;
-
-                        _this2.changeState(
-                          "replaceState",
-                          curUrl,
-                          curAs,
-                          _objectSpread(
-                            _objectSpread({}, curOptions),
-                            {},
-                            {
-                              _N_X: window.scrollX,
-                              _N_Y: window.scrollY
-                            }
-                          )
-                        );
-                      }
-
                       _this2.changeState(method, url, as, options);
 
                       if (false) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.5432a710f5f6d1c3d083.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.dc054caf758ac593c1e1.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.7c1823be9c21e94a881a.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.821b3671c54c6f1feeb8.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.5432a710f5f6d1c3d083.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.dc054caf758ac593c1e1.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.5432a710f5f6d1c3d083.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.dc054caf758ac593c1e1.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -122,13 +122,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.7c1823be9c21e94a881a.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.821b3671c54c6f1feeb8.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.5432a710f5f6d1c3d083.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.dc054caf758ac593c1e1.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.5432a710f5f6d1c3d083.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.dc054caf758ac593c1e1.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.7c1823be9c21e94a881a.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.821b3671c54c6f1feeb8.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.5432a710f5f6d1c3d083.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.dc054caf758ac593c1e1.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.4s | ⚠️ +50ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | ⚠️ +541 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f367.js gzip | 10.9 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..312b.js gzip | N/A | 10.9 kB | N/A |
| Overall change | 57.2 kB | 57.3 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 7.27 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | N/A | 7.29 kB | N/A |
| Overall change | 52.7 kB | 52.8 kB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 171 B | ✓ |
| _buildManife..dule.js gzip | 180 B | 180 B | ✓ |
| Overall change | 351 B | 351 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _error.js | 875 kB | 875 kB | ✓ |
| 404.html | 4.13 kB | 4.13 kB | ✓ |
| hooks.html | 3.71 kB | 3.71 kB | ✓ |
| index.js | 875 kB | 875 kB | ✓ |
| link.js | 915 kB | 914 kB | -386 B |
| routerDirect.js | 907 kB | 907 kB | -386 B |
| withRouter.js | 907 kB | 907 kB | -386 B |
| Overall change | 4.49 MB | 4.48 MB | -1.16 kB |

</details>

</details>

File: packages/next/next-server/lib/router/router.ts [hunk 1]
```diff
@@ -256,6 +261,29 @@ export default class Router implements BaseRouter {
...
+
+        let scrollDebounceTimeout: undefined | NodeJS.Timeout
+
+        const debouncedScrollSave = () => {
+          if (scrollDebounceTimeout) clearTimeout(scrollDebounceTimeout)
+
+          scrollDebounceTimeout = setTimeout(() => {
+            const { url, as: curAs, options } = history.state
+            this.changeState('replaceState', url, curAs, {
+              ...options,
```
Comment (Timer) [inline packages/next/next-server/lib/router/router.ts:278]: This added an object spread helper. Can we use `Object.assign` instead?

Comment (ijjk) [reply packages/next/next-server/lib/router/router.ts]: Updated

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.8s | ⚠️ +509ms |
| nodeModulesSize | 67 MB | 67 MB | ⚠️ +3.44 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.081 | 2.025 | -0.06 |
| / avg req/sec | 1201.36 | 1234.49 | ⚠️ +33.13 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.236 | 1.197 | -0.04 |
| /error-in-render avg req/sec | 2022.66 | 2089.38 | ⚠️ +66.72 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..4dd5.js gzip | 10.5 kB | 10.7 kB | ⚠️ +138 B |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 57.1 kB | ⚠️ +138 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 7.05 kB | ⚠️ +128 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.5 kB | ⚠️ +128 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| index.html gzip | 953 B | 955 B | ⚠️ +2 B |
| link.html gzip | 960 B | 961 B | ⚠️ +1 B |
| withRouter.html gzip | 947 B | 948 B | ⚠️ +1 B |
| Overall change | 2.86 kB | 2.86 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..ce095b7e0.js</strong></summary>

```diff
@@ -768,6 +768,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         };
       }
 
+      var manualScrollRestoration = false && false;
+
       function fetchNextData(pathname, query, isServerRender, cb) {
         var attempts = isServerRender ? 3 : 1;
 
@@ -987,7 +989,35 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               );
             }
 
-            window.addEventListener("popstate", this.onPopState);
+            window.addEventListener("popstate", this.onPopState); // enable custom scroll restoration handling when available
+            // otherwise fallback to browser's default handling
+
+            if (manualScrollRestoration) {
+              window.history.scrollRestoration = "manual";
+              var scrollDebounceTimeout;
+
+              var debouncedScrollSave = function debouncedScrollSave() {
+                if (scrollDebounceTimeout) clearTimeout(scrollDebounceTimeout);
+                scrollDebounceTimeout = setTimeout(function() {
+                  var _history$state = history.state,
+                    url = _history$state.url,
+                    curAs = _history$state.as,
+                    options = _history$state.options;
+
+                  _this.changeState(
+                    "replaceState",
+                    url,
+                    curAs,
+                    Object.assign({}, options, {
+                      _N_X: window.scrollX,
+                      _N_Y: window.scrollY
+                    })
+                  );
+                }, 10);
+              };
+
+              window.addEventListener("scroll", debouncedScrollSave);
+            }
           }
         } // @deprecated backwards compatibility even though it's a private method.
 
@@ -1218,6 +1248,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                           }
 
                           Router.events.emit("routeChangeComplete", as);
+
+                          if (manualScrollRestoration && "_N_X" in options) {
+                            window.scrollTo(options._N_X, options._N_Y);
+                          }
+
                           return resolve(true);
                         });
                     }, reject);
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..84.module.js</strong></summary>

```diff
@@ -639,6 +639,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         };
       }
 
+      var manualScrollRestoration = false && false;
+
       function fetchNextData(pathname, query, isServerRender, cb) {
         var attempts = isServerRender ? 3 : 1;
 
@@ -849,7 +851,31 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               );
             }
 
-            window.addEventListener("popstate", this.onPopState);
+            window.addEventListener("popstate", this.onPopState); // enable custom scroll restoration handling when available
+            // otherwise fallback to browser's default handling
+
+            if (manualScrollRestoration) {
+              window.history.scrollRestoration = "manual";
+              var scrollDebounceTimeout;
+
+              var debouncedScrollSave = () => {
+                if (scrollDebounceTimeout) clearTimeout(scrollDebounceTimeout);
+                scrollDebounceTimeout = setTimeout(() => {
+                  var { url, as: curAs, options } = history.state;
+                  this.changeState(
+                    "replaceState",
+                    url,
+                    curAs,
+                    Object.assign({}, options, {
+                      _N_X: window.scrollX,
+                      _N_Y: window.scrollY
+                    })
+                  );
+                }, 10);
+              };
+
+              window.addEventListener("scroll", debouncedScrollSave);
+            }
           }
         } // @deprecated backwards compatibility even though it's a private method.
 
@@ -1053,6 +1079,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                   }
 
                   Router.events.emit("routeChangeComplete", as);
+
+                  if (manualScrollRestoration && "_N_X" in options) {
+                    window.scrollTo(options._N_X, options._N_Y);
+                  }
+
                   return resolve(true);
                 });
               },
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.576eef86000901d238cd.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.7216f2ab6d0b109d4b27.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.576eef86000901d238cd.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.576eef86000901d238cd.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -122,13 +122,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.7216f2ab6d0b109d4b27.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.576eef86000901d238cd.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.576eef86000901d238cd.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.7216f2ab6d0b109d4b27.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.576eef86000901d238cd.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.3s | ⚠️ +96ms |
| nodeModulesSize | 67 MB | 67 MB | ⚠️ +3.44 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..4dd5.js gzip | 10.5 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..7e58.js gzip | N/A | 10.7 kB | N/A |
| Overall change | 56.9 kB | 57.1 kB | ⚠️ +138 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | N/A | 7.05 kB | N/A |
| Overall change | 52.4 kB | 52.5 kB | ⚠️ +128 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _error.js | 875 kB | 875 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 875 kB | 875 kB | ✓ |
| link.js | 914 kB | 914 kB | ⚠️ +183 B |
| routerDirect.js | 906 kB | 906 kB | ⚠️ +183 B |
| withRouter.js | 906 kB | 906 kB | ⚠️ +183 B |
| Overall change | 4.48 MB | 4.49 MB | ⚠️ +549 B |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| buildDuration | 12s | 12.2s | ⚠️ +176ms |
| nodeModulesSize | 67 MB | 67 MB | ⚠️ +3.82 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.046 | 1.923 | -0.12 |
| / avg req/sec | 1221.82 | 1300.34 | ⚠️ +78.52 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.231 | 1.21 | -0.02 |
| /error-in-render avg req/sec | 2030.6 | 2066.38 | ⚠️ +35.78 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..4dd5.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| index.html gzip | 953 B | 953 B | ✓ |
| link.html gzip | 960 B | 961 B | ⚠️ +1 B |
| withRouter.html gzip | 947 B | 947 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..ce095b7e0.js</strong></summary>

```diff
@@ -768,6 +768,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         };
       }
 
+      var manualScrollRestoration = false && false;
+
       function fetchNextData(pathname, query, isServerRender, cb) {
         var attempts = isServerRender ? 3 : 1;
 
@@ -987,7 +989,12 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               );
             }
 
-            window.addEventListener("popstate", this.onPopState);
+            window.addEventListener("popstate", this.onPopState); // enable custom scroll restoration handling when available
+            // otherwise fallback to browser's default handling
+
+            if (false) {
+              var debouncedScrollSave, scrollDebounceTimeout;
+            }
           }
         } // @deprecated backwards compatibility even though it's a private method.
 
@@ -1218,6 +1225,10 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                           }
 
                           Router.events.emit("routeChangeComplete", as);
+
+                          if (false) {
+                          }
+
                           return resolve(true);
                         });
                     }, reject);
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..84.module.js</strong></summary>

```diff
@@ -639,6 +639,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         };
       }
 
+      var manualScrollRestoration = false && false;
+
       function fetchNextData(pathname, query, isServerRender, cb) {
         var attempts = isServerRender ? 3 : 1;
 
@@ -849,7 +851,12 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               );
             }
 
-            window.addEventListener("popstate", this.onPopState);
+            window.addEventListener("popstate", this.onPopState); // enable custom scroll restoration handling when available
+            // otherwise fallback to browser's default handling
+
+            if (false) {
+              var debouncedScrollSave, scrollDebounceTimeout;
+            }
           }
         } // @deprecated backwards compatibility even though it's a private method.
 
@@ -1053,6 +1060,10 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                   }
 
                   Router.events.emit("routeChangeComplete", as);
+
+                  if (false) {
+                  }
+
                   return resolve(true);
                 });
               },
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.800a8d81efc68324eb73.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.1056ef63501c727344d9.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.800a8d81efc68324eb73.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.800a8d81efc68324eb73.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -122,13 +122,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.1056ef63501c727344d9.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.800a8d81efc68324eb73.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.800a8d81efc68324eb73.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.1056ef63501c727344d9.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.800a8d81efc68324eb73.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| buildDuration | 13s | 12.9s | -106ms |
| nodeModulesSize | 67 MB | 67 MB | ⚠️ +3.82 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..4dd5.js gzip | 10.5 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..ffcb.js gzip | N/A | 10.5 kB | N/A |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | N/A | 6.92 kB | N/A |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _error.js | 875 kB | 875 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 875 kB | 875 kB | ✓ |
| link.js | 914 kB | 914 kB | ⚠️ +76 B |
| routerDirect.js | 906 kB | 906 kB | ⚠️ +76 B |
| withRouter.js | 906 kB | 906 kB | ⚠️ +76 B |
| Overall change | 4.48 MB | 4.48 MB | ⚠️ +228 B |

</details>

</details>

**Review by timneutkens — DISMISSED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| buildDuration | 12s | 11.6s | -416ms |
| nodeModulesSize | 66.1 MB | 66.1 MB | ⚠️ +3.8 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.896 | 1.913 | ⚠️ +0.02 |
| / avg req/sec | 1318.37 | 1306.55 | ⚠️ -11.82 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.191 | 1.19 | 0 |
| /error-in-render avg req/sec | 2098.93 | 2099.97 | +1.04 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| index.html gzip | 954 B | 953 B | -1 B |
| link.html gzip | 958 B | 959 B | ⚠️ +1 B |
| withRouter.html gzip | 945 B | 945 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>19b7e98f51cc..13.module.js</strong></summary>

```diff
@@ -705,6 +705,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         };
       }
 
+      var manualScrollRestoration = false && false;
+
       function fetchNextData(dataHref, isServerRender, cb) {
         var attempts = isServerRender ? 3 : 1;
 
@@ -903,7 +905,12 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               );
             }
 
-            window.addEventListener("popstate", this.onPopState);
+            window.addEventListener("popstate", this.onPopState); // enable custom scroll restoration handling when available
+            // otherwise fallback to browser's default handling
+
+            if (false) {
+              var debouncedScrollSave, scrollDebounceTimeout;
+            }
           }
         } // @deprecated backwards compatibility even though it's a private method.
 
@@ -1108,6 +1115,9 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                       throw error;
                     }
 
+                    if (false) {
+                    }
+
                     Router.events.emit("routeChangeComplete", as);
                     return resolve(true);
                   }
```
</details>
<details>
<summary>Diff for <strong>19b7e98f51cc..079014588.js</strong></summary>

```diff
@@ -835,6 +835,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         };
       }
 
+      var manualScrollRestoration = false && false;
+
       function fetchNextData(dataHref, isServerRender, cb) {
         var attempts = isServerRender ? 3 : 1;
 
@@ -1040,7 +1042,12 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               );
             }
 
-            window.addEventListener("popstate", this.onPopState);
+            window.addEventListener("popstate", this.onPopState); // enable custom scroll restoration handling when available
+            // otherwise fallback to browser's default handling
+
+            if (false) {
+              var debouncedScrollSave, scrollDebounceTimeout;
+            }
           }
         } // @deprecated backwards compatibility even though it's a private method.
 
@@ -1276,6 +1283,9 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                             throw error;
                           }
 
+                          if (false) {
+                          }
+
                           Router.events.emit("routeChangeComplete", as);
                           return resolve(true);
                         });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.15dc873ded6079014588.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.6923cb7455cbfa930db3.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -122,13 +122,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.15dc873ded6079014588.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.6923cb7455cbfa930db3.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.15dc873ded6079014588.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.6923cb7455cbfa930db3.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.8s | ⚠️ +67ms |
| nodeModulesSize | 66.1 MB | 66.1 MB | ⚠️ +3.8 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| 19b7e98f51cc..6834.js gzip | N/A | 10.7 kB | N/A |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| 19b7e98f51cc..dule.js gzip | N/A | 7.09 kB | N/A |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 876 kB | 876 kB | ✓ |
| link.js | 915 kB | 915 kB | ⚠️ +75 B |
| routerDirect.js | 908 kB | 908 kB | ⚠️ +75 B |
| withRouter.js | 908 kB | 908 kB | ⚠️ +75 B |
| Overall change | 4.49 MB | 4.49 MB | ⚠️ +225 B |

</details>

</details>
Commit: df69d15c7a7fcc2ae3a3ccb90d0a9a55670f13c0

**Review by timneutkens — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| buildDuration | 10.1s | 10.9s | ⚠️ +743ms |
| nodeModulesSize | 66.1 MB | 66.1 MB | ⚠️ +3.8 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.7 | 1.692 | -0.01 |
| / avg req/sec | 1471.02 | 1477.71 | +6.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 0.991 | 1.016 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2521.91 | 2460.31 | ⚠️ -61.6 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| index.html gzip | 954 B | 953 B | -1 B |
| link.html gzip | 958 B | 959 B | ⚠️ +1 B |
| withRouter.html gzip | 945 B | 945 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>19b7e98f51cc..13.module.js</strong></summary>

```diff
@@ -705,6 +705,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         };
       }
 
+      var manualScrollRestoration = false && false;
+
       function fetchNextData(dataHref, isServerRender, cb) {
         var attempts = isServerRender ? 3 : 1;
 
@@ -903,7 +905,12 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               );
             }
 
-            window.addEventListener("popstate", this.onPopState);
+            window.addEventListener("popstate", this.onPopState); // enable custom scroll restoration handling when available
+            // otherwise fallback to browser's default handling
+
+            if (false) {
+              var debouncedScrollSave, scrollDebounceTimeout;
+            }
           }
         } // @deprecated backwards compatibility even though it's a private method.
 
@@ -1108,6 +1115,9 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                       throw error;
                     }
 
+                    if (false) {
+                    }
+
                     Router.events.emit("routeChangeComplete", as);
                     return resolve(true);
                   }
```
</details>
<details>
<summary>Diff for <strong>19b7e98f51cc..079014588.js</strong></summary>

```diff
@@ -835,6 +835,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         };
       }
 
+      var manualScrollRestoration = false && false;
+
       function fetchNextData(dataHref, isServerRender, cb) {
         var attempts = isServerRender ? 3 : 1;
 
@@ -1040,7 +1042,12 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               );
             }
 
-            window.addEventListener("popstate", this.onPopState);
+            window.addEventListener("popstate", this.onPopState); // enable custom scroll restoration handling when available
+            // otherwise fallback to browser's default handling
+
+            if (false) {
+              var debouncedScrollSave, scrollDebounceTimeout;
+            }
           }
         } // @deprecated backwards compatibility even though it's a private method.
 
@@ -1276,6 +1283,9 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                             throw error;
                           }
 
+                          if (false) {
+                          }
+
                           Router.events.emit("routeChangeComplete", as);
                           return resolve(true);
                         });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.15dc873ded6079014588.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.6923cb7455cbfa930db3.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -122,13 +122,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.15dc873ded6079014588.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.6923cb7455cbfa930db3.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.15dc873ded6079014588.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.6923cb7455cbfa930db3.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| buildDuration | 11.2s | 10.9s | -244ms |
| nodeModulesSize | 66.1 MB | 66.1 MB | ⚠️ +3.8 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| 19b7e98f51cc..6834.js gzip | N/A | 10.7 kB | N/A |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| 19b7e98f51cc..dule.js gzip | N/A | 7.09 kB | N/A |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 876 kB | 876 kB | ✓ |
| link.js | 915 kB | 915 kB | ⚠️ +75 B |
| routerDirect.js | 908 kB | 908 kB | ⚠️ +75 B |
| withRouter.js | 908 kB | 908 kB | ⚠️ +75 B |
| Overall change | 4.49 MB | 4.49 MB | ⚠️ +225 B |

</details>

</details>
Commit: 4704125888e99baaef365cb97ba2fc24ff993c7a

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 4704125888e99baaef365cb97ba2fc24ff993c7a

**test/integration/create-next-app/index.test.js** 
- create next app > valid example
- create next app > should allow example with GitHub URL
- create next app > should allow example with GitHub URL and example-path
- create next app > should use --example-path over the file path in the GitHub URL

<details>
<summary>Expand output</summary>

  ● create next app › valid example

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js valid-example --example basic-css

      90 |     await usingTempDir(async (cwd) => {
      91 |       const projectName = 'valid-example'
    > 92 |       const res = await run(cwd, projectName, '--example', 'basic-css')
         |                   ^
      93 |       expect(res.exitCode).toBe(0)
      94 | 
      95 |       expect(

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:92:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:90:5)

  ● create next app › should allow example with GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-app --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages

      109 |     await usingTempDir(async (cwd) => {
      110 |       const projectName = 'github-app'
    > 111 |       const res = await run(
          |                   ^
      112 |         cwd,
      113 |         projectName,
      114 |         '--example',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:111:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:109:5)

  ● create next app › should allow example with GitHub URL and example-path

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path --example https://github.com/zeit/next-learn-demo/tree/master --example-path 1-navigate-between-pages

      135 |     await usingTempDir(async (cwd) => {
      136 |       const projectName = 'github-example-path'
    > 137 |       const res = await run(
          |                   ^
      138 |         cwd,
      139 |         projectName,
      140 |         '--example',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:137:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:135:5)

  ● create next app › should use --example-path over the file path in the GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path-2 --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages --example-path 1-navigate-between-pages

      163 |     await usingTempDir(async (cwd) => {
      164 |       const projectName = 'github-example-path-2'
    > 165 |       const res = await run(
          |                   ^
      166 |         cwd,
      167 |         projectName,
      168 |         '--example',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:165:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:163:5)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| buildDuration | 11.4s | 11.5s | ⚠️ +41ms |
| nodeModulesSize | 66.1 MB | 66.1 MB | ⚠️ +3.8 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.918 | 1.925 | ⚠️ +0.01 |
| / avg req/sec | 1303.75 | 1298.95 | ⚠️ -4.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.146 | 1.229 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 2182.39 | 2034.59 | ⚠️ -147.8 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| index.html gzip | 954 B | 953 B | -1 B |
| link.html gzip | 958 B | 959 B | ⚠️ +1 B |
| withRouter.html gzip | 945 B | 945 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>19b7e98f51cc..13.module.js</strong></summary>

```diff
@@ -705,6 +705,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         };
       }
 
+      var manualScrollRestoration = false && false;
+
       function fetchNextData(dataHref, isServerRender, cb) {
         var attempts = isServerRender ? 3 : 1;
 
@@ -903,7 +905,12 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               );
             }
 
-            window.addEventListener("popstate", this.onPopState);
+            window.addEventListener("popstate", this.onPopState); // enable custom scroll restoration handling when available
+            // otherwise fallback to browser's default handling
+
+            if (false) {
+              var debouncedScrollSave, scrollDebounceTimeout;
+            }
           }
         } // @deprecated backwards compatibility even though it's a private method.
 
@@ -1108,6 +1115,9 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                       throw error;
                     }
 
+                    if (false) {
+                    }
+
                     Router.events.emit("routeChangeComplete", as);
                     return resolve(true);
                   }
```
</details>
<details>
<summary>Diff for <strong>19b7e98f51cc..079014588.js</strong></summary>

```diff
@@ -835,6 +835,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         };
       }
 
+      var manualScrollRestoration = false && false;
+
       function fetchNextData(dataHref, isServerRender, cb) {
         var attempts = isServerRender ? 3 : 1;
 
@@ -1040,7 +1042,12 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               );
             }
 
-            window.addEventListener("popstate", this.onPopState);
+            window.addEventListener("popstate", this.onPopState); // enable custom scroll restoration handling when available
+            // otherwise fallback to browser's default handling
+
+            if (false) {
+              var debouncedScrollSave, scrollDebounceTimeout;
+            }
           }
         } // @deprecated backwards compatibility even though it's a private method.
 
@@ -1276,6 +1283,9 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                             throw error;
                           }
 
+                          if (false) {
+                          }
+
                           Router.events.emit("routeChangeComplete", as);
                           return resolve(true);
                         });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.15dc873ded6079014588.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.6923cb7455cbfa930db3.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -122,13 +122,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.15dc873ded6079014588.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.6923cb7455cbfa930db3.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      href="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.15dc873ded6079014588.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.6923cb7455cbfa930db3.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.12a66c28dfec2bca8613.module.js"
+      src="/_next/static/chunks/19b7e98f51cc0d86c45d01159bbbfb942bfe49b8.8104a4c3863c1c7362eb.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.8s | ⚠️ +201ms |
| nodeModulesSize | 66.1 MB | 66.1 MB | ⚠️ +3.8 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| 19b7e98f51cc..6834.js gzip | N/A | 10.7 kB | N/A |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| 19b7e98f51cc..dule.js gzip | N/A | 7.09 kB | N/A |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/forward-scroll-restoration | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 876 kB | 876 kB | ✓ |
| link.js | 915 kB | 915 kB | ⚠️ +75 B |
| routerDirect.js | 908 kB | 908 kB | ⚠️ +75 B |
| withRouter.js | 908 kB | 908 kB | ⚠️ +75 B |
| Overall change | 4.49 MB | 4.49 MB | ⚠️ +225 B |

</details>

</details>
Commit: 9c86e3dabcf5bb44af2d56bee391d951006988cf
