### PR TITLE
fix(turbopack): Next.js package not found panics in Turbopack

### LINKED ISSUE #3980: How can I embed script into my next.js page?
I want to embed Sendpulse into my next.js page, how can I do this?

Their code: 
```
<script charset="UTF-8" src="//cdn.sendpulse.com/9dae6d62c816560a842268bde2cd317d/js/push/998014b3613c5ffdd01ac8c8a6390391_1.js" async></script>
```

- [X] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by Cy-Tek**
### What?
This PR enhances the lockfile detection logic to identify multiple lockfiles in a project hierarchy and use the highest level one as the tracing root.

### Why?
When multiple lockfiles exist in a project, it can cause confusion and potential issues. By detecting this situation, we can warn users about redundant lockfiles and consistently use the highest level one.

### How?
- Modified `findRootDir` to recursively search for lockfiles up the directory tree
- Added a warning when multiple lockfiles are detected, showing the paths to redundant lockfiles
- Updated comment in config.ts to clarify we use the "highest level lockfile" rather than "closest lockfile"
- Added support for passing root directory as an argument in telemetry flush

Fixes #3980

This is a draft PR currently because the logging is duplicated across processes which I am currently working on a fix for.

### CODE REVIEW

**Comment by Cy-Tek** [comment]
* **#79572** <a href="https://app.graphite.dev/github/pr/vercel/next.js/79572?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/vercel/next.js/79572?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: a2adba7a9ef98606fc42b4c433833cc9fc6cc859

`__NEXT_EXPERIMENTAL_PPR=true pnpm test-dev test/development/acceptance-app/undefined-default-export.test.ts` (PPR)
- Undefined default export > should error when page component export is not valid

<details>
<summary>Expand output</summary>

  ● Undefined default export › should error when page component export is not valid

    page.waitForSelector: Timeout 10000ms exceeded.
    Call log:
      - waiting for locator('#__next')

      454 |   waitForElementByCss(selector: string, timeout = 10_000) {
      455 |     return this.startChain(async () => {
    > 456 |       const el = await page.waitForSelector(selector, {
          |                             ^
      457 |         timeout,
      458 |         state: 'attached',
      459 |       })

      at waitForSelector (lib/browsers/playwright.ts:456:29)
      at Playwright._chain (lib/browsers/playwright.ts:568:23)
      at Playwright._chain [as startChain] (lib/browsers/playwright.ts:549:17)
      at Playwright.startChain [as waitForElementByCss] (lib/browsers/playwright.ts:455:17)
      at Object.waitForElementByCss (development/acceptance-app/undefined-default-export.test.ts:93:19)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

File: packages/next/src/lib/find-root.ts [hunk 1]
```diff
@@ -17,6 +18,33 @@ export function findRootLockFile(cwd: string) {
...
+      Log.warnOnce(
+        `Warning: Found multiple lockfiles. Consider removing the lockfiles at ${lockFiles
+          .slice(0, lockFiles.length - 1)
+          .map((str) => '\n   * ' + str)
+          .join('')}\n`
+      )
+    }
+  }
+
   return lockFile ? dirname(lockFile) : undefined
```
Comment (lukesandberg) [inline packages/next/src/lib/find-root.ts:49]: afaict the `lockFile === undefined` case is impossible from this position

File: packages/next/src/lib/find-root.ts [hunk 2]
```diff
@@ -17,6 +18,33 @@ export function findRootLockFile(cwd: string) {
 }
 
 export function findRootDir(cwd: string) {
-  const lockFile = findRootLockFile(cwd)
+  let lockFile = findRootLockFile(cwd)
+  if (!lockFile) return undefined
+
+  let lockFiles = [lockFile]
```
Comment (lukesandberg) [inline packages/next/src/lib/find-root.ts:24]:
```suggestion
  const lockFiles = [lockFile]
```

File: packages/next/src/lib/find-root.ts [hunk 3]
```diff
@@ -18,5 +19,29 @@ export function findRootLockFile(cwd: string) {
...
+  }
+
+  // Only warn if not in a build worker to avoid duplicate warnings
+  if (typeof process.send !== 'function' && lockFiles.length > 1) {
+    Log.warnOnce(
+      `Warning: Found multiple lockfiles. Consider removing the lockfiles at ${lockFiles
+        .slice(0, lockFiles.length - 1)
+        .map((str) => '\n   * ' + str)
+        .join('')}\n`
+    )
```
Comment (lukesandberg) [inline packages/next/src/lib/find-root.ts:43]: nit: maybe include the selected file in the message?
```suggestion
    Log.warnOnce(
      `Warning: Found multiple lockfiles. Selecting ${lockFile}. Consider removing the lockfiles at: ${lockFiles
        .slice(0, lockFiles.length - 1)
        .map((str) => '\n   * ' + str)
        .join('')}\n`
    )
```

**Review by lukesandberg — APPROVED** [review]
