### PR TITLE
fix(route-handlers): make sure preflight has CORS headers

### LINKED ISSUE #57999: Route Handler has CORS errors if GET is not present
### Link to the code that reproduces this issue

https://github.com/C-3-F/nextjs13-cors-bug-example

### To Reproduce

Start both the client and server by using the above commands.

In the request payload box, type some sample JSON. The requests will just take that request and return it.

The 'works' box will return the payload with a 200.

The 'doesntwork' box will fail the request with a CORS error.

### Current vs. Expected behavior

The expected behavior is that Global CORS headers set in next-config.js should be applied to all request method types.

Current behavior is that if you have a POST method alone, the CORS headers are not set. If you add a GET method to the same route, then the POST request magically works.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:30 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T8103
Binaries:
  Node: 20.7.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.7.6
Relevant Packages:
  next: 14.0.2-canary.10
  eslint-config-next: 13.4.19
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Middleware / Edge (API routes, runtime)

### Additional context

I'm pretty sure this issue was introduced with the App router. I haven't been able to get it to work with any versions ^13.4. I'm also using the Brave browser. But also tested in Chrome which is broken too.

### PR DESCRIPTION
**Pull request by samcx**
## Why?

When we just have a POST route handler, it seems CORs is not working properly. This is because we break out of the loop here https://github.com/vercel/next.js/blob/768a92b15bd72002df0f9f893d78e094a8e3165f/packages/next/src/server/future/route-modules/app-route/helpers/auto-implement-methods.ts#L38 when a `GET` isn't present before we add the correct headers and status to the preflight `OPTION`.

- Closes https://github.com/vercel/next.js/issues/57999

Closes NEXT-2813

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | samcx/next.js sam/route-handlers/cors-fix | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.7s | N/A |
| buildDurationCached | 7.4s | 6.3s | N/A |
| nodeModulesSize | 198 MB | 198 MB | N/A |
| nextStartRea..uration (ms) | 438ms | 435ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | samcx/next.js sam/route-handlers/cors-fix | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 30.4 kB | 30.4 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | N/A |
| 8299-HASH.js gzip | 5.04 kB | 5.04 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 242 B | N/A |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 45.4 kB | 45.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | samcx/next.js sam/route-handlers/cors-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | samcx/next.js sam/route-handlers/cors-fix | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.21 kB | 4.21 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.57 kB | 6.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | samcx/next.js sam/route-handlers/cors-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | samcx/next.js sam/route-handlers/cors-fix | Change |
| - | - | - | - |
| index.html gzip | 529 B | 529 B | ✓ |
| link.html gzip | 542 B | 541 B | N/A |
| withRouter.html gzip | 525 B | 523 B | N/A |
| Overall change | 529 B | 529 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | samcx/next.js sam/route-handlers/cors-fix | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.1 kB | 95.1 kB | N/A |
| page.js gzip | 3.05 kB | 3.05 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | samcx/next.js sam/route-handlers/cors-fix | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 627 B | 624 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | samcx/next.js sam/route-handlers/cors-fix | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | ✓ |
| app-page-exp..prod.js gzip | 96.6 kB | 96.6 kB | ✓ |
| app-page-tur..prod.js gzip | 98.3 kB | 98.3 kB | ✓ |
| app-page-tur..prod.js gzip | 92.8 kB | 92.8 kB | ✓ |
| app-page.run...dev.js gzip | 149 kB | 149 kB | ✓ |
| app-page.run..prod.js gzip | 91.3 kB | 91.3 kB | ✓ |
| app-route-ex...dev.js gzip | 21.3 kB | 21.3 kB | N/A |
| app-route-ex..prod.js gzip | 15 kB | 15 kB | ✓ |
| app-route-tu..prod.js gzip | 15 kB | 15 kB | ✓ |
| app-route-tu..prod.js gzip | 14.8 kB | 14.8 kB | N/A |
| app-route.ru...dev.js gzip | 21 kB | 21 kB | N/A |
| app-route.ru..prod.js gzip | 14.8 kB | 14.8 kB | N/A |
| pages-api-tu..prod.js gzip | 9.52 kB | 9.52 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.8 kB | 9.8 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.52 kB | 9.52 kB | ✓ |
| pages-turbo...prod.js gzip | 22.3 kB | 22.3 kB | ✓ |
| pages.runtim...dev.js gzip | 22.9 kB | 22.9 kB | ✓ |
| pages.runtim..prod.js gzip | 22.3 kB | 22.3 kB | ✓ |
| server.runti..prod.js gzip | 50.6 kB | 50.6 kB | ✓ |
| Overall change | 876 kB | 876 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | samcx/next.js sam/route-handlers/cors-fix | Change |
| - | - | - | - |
| 0.pack gzip | 1.55 MB | 1.55 MB | N/A |
| index.pack gzip | 105 kB | 105 kB | ⚠️ +472 B |
| Overall change | 105 kB | 105 kB | ⚠️ +472 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.ru..time.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 9ffc3860ec534cf427a0ea0188f2b6cb48fff64f

File: packages/next/src/server/future/route-modules/app-route/helpers/auto-implement-methods.ts [hunk 1]
```diff
@@ -34,8 +34,8 @@ export function autoImplementMethods(
     // exists).
     if (method === 'HEAD') {
```
Comment (ijjk) [inline packages/next/src/server/future/route-modules/app-route/helpers/auto-implement-methods.ts:35]:
```suggestion
    if (method === 'HEAD' && handles.GET) {
```

File: packages/next/src/server/future/route-modules/app-route/helpers/auto-implement-methods.ts [hunk 2]
```diff
@@ -34,8 +34,8 @@ export function autoImplementMethods(
...
       // If the userland module doesn't implement the GET method, then
-      // we're done.
-      if (!handlers.GET) break
+      // we can continue to check the OPTION method below.
+      if (!handlers.GET) continue
```
Comment (ijjk) [inline packages/next/src/server/future/route-modules/app-route/helpers/auto-implement-methods.ts:38]: Let's move this to the `if` condition to make it more clear and clarify this is just re-using GET for HEAD if available.

File: packages/next/src/server/future/route-modules/app-route/helpers/auto-implement-methods.ts [hunk 3]
```diff
@@ -32,11 +32,7 @@ export function autoImplementMethods(
     // If the userland module doesn't implement the HEAD method, then
     // we'll automatically implement it by calling the GET method (if it
     // exists).
-    if (method === 'HEAD') {
-      // If the userland module doesn't implement the GET method, then
-      // we're done.
-      if (!handlers.GET) break
-
+    if (method === 'HEAD' && implemented.has('GET')) {
```
Comment (ijjk) [inline packages/next/src/server/future/route-modules/app-route/helpers/auto-implement-methods.ts:35]:
```suggestion
    if (method === 'HEAD' && handles.GET) {
```

**Review by ijjk — APPROVED** [review]
Good catch, test and change looks good
