### PR TITLE
fix: support multiple icon formats with same base name (icon.png + icon.svg)

### LINKED ISSUE #85496: Turbopack build fails if multiple app/ icons have same name
### Link to the code that reproduces this issue

https://github.com/paschun/next-app-icon-repro

### To Reproduce

1. Place icons in app dir, like [docs](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons) say. Two of them should have the same name. Like icon.png + icon.svg.
2. `next build`
3. Error:
```
> Build error occurred
Error [TurbopackInternalError]: Dependency tracking is disabled so invalidation is not allowed at /Users/geist/dev/actions-runner/_work/next.js/next.js/turbopack/crates/turbo-tasks-backend/src/backend/mod.rs:1514:13
```
4. Remove either icon.png or icon.svg, or place in public/
5. `next build`
6. Build succeeds

### Current vs. Expected behavior

I expcted the build to succeed even with icon.png and icon.svg in the app/ directory.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 25.0.0: Wed Sep 17 21:35:32 PDT 2025; root:xnu-12377.1.9~141/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 12
Binaries:
  Node: 24.10.0
  npm: 11.6.0
  Yarn: N/A
  pnpm: 10.20.0
Relevant Packages:
  next: 16.0.1 // Latest available version is detected (16.0.1).
  eslint-config-next: N/A
  react: 19.2.0
  react-dom: 19.2.0
  typescript: 5.9.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Output

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

Safari <26 needs icon.png, doesn't support icon.svg.  https://caniuse.com/link-icon-svg

Relevant discussions: 
https://github.com/vercel/next.js/discussions/85232
https://github.com/vercel/next.js/discussions/84585

### PR DESCRIPTION
**Pull request by lukesandberg**
## What?

Fixes a crash in Turbopack and incorrect behavior in Webpack when users have multiple icon files with the same base name but different extensions (e.g., `icon.png` and `icon.svg`) in their app directory.

## Why?

This is a valid use case for browser fallback support - modern browsers can use SVG icons while older browsers (Safari <26) need to fall back to PNG. Previously:

- **Turbopack**: Crashed during `next build` with "Dependency tracking is disabled so invalidation is not allowed"
- **Webpack**: Silently ignored all but one format

## How?

**Turbopack**: Changed virtual source filename from `{stem}--route-entry.js` to `{filename}--route-entry.js` (e.g., `icon.png--route-entry.js` and `icon.svg--route-entry.js`) to avoid file conflicts that triggered invalidation.

**Webpack**: Changed `MetadataResolver` to return all matching files instead of just the first one.

Both icon formats are now properly rendered:
```html
<link rel="icon" type="image/png" sizes="114x114" href="/icon.png">
<link rel="icon" type="image/svg+xml" sizes="any" href="/icon.svg">
```

Fixes #85496
Fixes NEXT-4816

### CODE REVIEW

**Comment by lukesandberg** [comment]
* **#89504** <a href="https://app.graphite.com/github/pr/vercel/next.js/89504?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/vercel/next.js/89504?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/next/src/build/webpack/loaders/next-app-loader/index.ts [hunk 1]
```diff
@@ -987,21 +983,20 @@ const nextAppLoader: AppLoader = async function nextAppLoader() {
...
+        const exists = await fileExistsInDirectory(dirname, filenameWithExt)
+        // Call `addMissingDependency` for all files even if they didn't match,
+        // because they might be added or removed during development.
+        this.addMissingDependency(absolutePathWithExtension)
+        return exists ? absolutePathWithExtension : undefined
+      })
+    )
 
-    return result
+    return checks.filter((result): result is string => result !== undefined)
```
Comment (paschun) [inline packages/next/src/build/webpack/loaders/next-app-loader/index.ts]: this is odd, if you want to know it's a string you should probably check `typeof === 'string'`

Comment (lukesandberg) [reply packages/next/src/build/webpack/loaders/next-app-loader/index.ts]: `is string` is asserting that the type becomes `string` not `string|undefined`

i know apriori that the only values are string or undefined so i don't really need to check

however it appears that TSC can figure this out without the assertion so i can drop `result is string`

**Review by mischnic — APPROVED** [review]

**Comment by lukesandberg** [comment]
### Merge activity

* **Feb 13, 12:55 PM UTC**: @lukesandberg merged this pull request with [Graphite](https://app.graphite.com/github/pr/vercel/next.js/89504).
