### PR TITLE
fix(30724): clear "x-middleware-next" header when chaining middlewares

### LINKED ISSUE #30724: HTTP 403 response of second middleware is ignored
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

16.6.1

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

I have a first middleware in `pages` and another one in `pages/api`. This second middleware is supposed to return a 403 error if the request doesn't contain proper authentication. When calling an API page (e.g. `/api/hello`), the 403 response is never returned. If the first middleware is removed then the 403 response is correctly returned.

Simplified code:

```js
// pages/_middleware.js
export default function firstMiddleware(req) {
  console.log('first middleware:', req.nextUrl.pathname)
  return NextResponse.next()
}
```

```js
// pages/api/_middleware.js
export default function secondMiddleware(req) {
  console.log('second middleware:', req.nextUrl.pathname)
  return new NextResponse(null, { status: 403 })
}
```

```js
// pages/api/hello.js
export default (req, res) => {
  console.log('executing api')
  res.status(200).json({ name: 'John Doe' })
}
```

A hack to make it work is to add the Location header in the response of the second middleware, see https://github.com/vercel/next.js/discussions/30579.

### Expected Behavior

Even with the presence of the first middleware, the 403 response should be returned to the browser.

### To Reproduce

Create a new project with `npx create-next-app` and add the two middlewares provided above. Run `npm run dev` and go to http://localhost:3000/api/hello.

### PR DESCRIPTION
**Pull request by hi-ogawa**
Fixes https://github.com/vercel/next.js/issues/30724

The linked issue wasn't triaged yet, so I wasn't sure if the current behavior was by design.
But, it seemed the issue was relatively simple, so I submit a possible fix here.
I hope this fix aligns to the intended behavior, but if that's not the case, I would appreciate any guidance to improve my code.
Thanks for the review!

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| buildDuration | 21.7s | 21.7s | -16ms |
| buildDurationCached | 4.2s | 4.1s | -116ms |
| nodeModulesSize | 335 MB | 335 MB | ⚠️ +230 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.807 | 3.735 | -0.07 |
| / avg req/sec | 656.75 | 669.3 | +12.55 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.008 | 2.036 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1245.05 | 1227.62 | ⚠️ -17.43 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| buildDuration | 22.3s | 22.7s | ⚠️ +366ms |
| buildDurationCached | 4s | 4s | ⚠️ +30ms |
| nodeModulesSize | 335 MB | 335 MB | ⚠️ +230 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.59 | 3.599 | ⚠️ +0.01 |
| / avg req/sec | 696.33 | 694.67 | ⚠️ -1.66 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.955 | 1.923 | -0.03 |
| /error-in-render avg req/sec | 1279.06 | 1300.35 | +21.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.5 kB | 28.5 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 534 B | 534 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: 7f14a14af58721a9c6811d8364c05a46eeb55c3d

File: packages/next/server/next-server.ts [hunk 1]
```diff
@@ -700,6 +700,8 @@ export default class Server {
         })
 
         for (let [key, value] of result.response.headers) {
+          // Do not accumulate "next" header so that chaining middlewares can intercept
+          if (key === 'x-middleware-next') continue
           allHeaders.append(key, value)
```
Comment (javivelasco) [inline packages/next/server/next-server.ts:705]:
```suggestion
          if (key !== 'x-middleware-next') {
            allHeaders.append(key, value)
          }
```

**Review by javivelasco — DISMISSED** [review]
Thanks for this contribution! I'd change the semantics a bit though, seems more straightforward.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| buildDuration | 24.3s | 23.3s | -1s |
| buildDurationCached | 4.5s | 4.4s | -159ms |
| nodeModulesSize | 335 MB | 335 MB | ⚠️ +125 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.013 | 4.04 | ⚠️ +0.03 |
| / avg req/sec | 622.91 | 618.85 | ⚠️ -4.06 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.113 | 2.046 | -0.07 |
| /error-in-render avg req/sec | 1183 | 1221.66 | +38.66 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| buildDuration | 25.4s | 24.6s | -729ms |
| buildDurationCached | 4.5s | 4.5s | -77ms |
| nodeModulesSize | 335 MB | 335 MB | ⚠️ +125 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.944 | 4.021 | ⚠️ +0.08 |
| / avg req/sec | 633.91 | 621.75 | ⚠️ -12.16 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.104 | 2.085 | -0.02 |
| /error-in-render avg req/sec | 1188.29 | 1199.2 | +10.91 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.5 kB | 28.5 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 534 B | 534 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: e7c50d8bd5999bf34e5565a95c8d19f72417722f

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| buildDuration | 18.6s | 18.2s | -381ms |
| buildDurationCached | 3.7s | 3.5s | -212ms |
| nodeModulesSize | 335 MB | 335 MB | ⚠️ +130 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.016 | 3.008 | -0.01 |
| / avg req/sec | 828.83 | 831.04 | +2.21 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.468 | 1.474 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1702.46 | 1695.91 | ⚠️ -6.55 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 517 B | 517 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| buildDuration | 19.1s | 19s | -86ms |
| buildDurationCached | 3.6s | 3.6s | ⚠️ +42ms |
| nodeModulesSize | 335 MB | 335 MB | ⚠️ +130 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.855 | 2.911 | ⚠️ +0.06 |
| / avg req/sec | 875.7 | 858.67 | ⚠️ -17.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.368 | 1.439 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1826.84 | 1737.77 | ⚠️ -89.07 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.5 kB | 28.5 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | hi-ogawa/next.js 30724-clear-next-header-when-chaining-middlewares | Change |
| - | - | - | - |
| index.html gzip | 521 B | 521 B | ✓ |
| link.html gzip | 533 B | 533 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: 9f992a70c5f5e8a833f1acf61c59dfe65151b52d

File: packages/next/server/next-server.ts [hunk 2]
```diff
@@ -700,7 +700,9 @@ export default class Server {
         })
 
         for (let [key, value] of result.response.headers) {
-          allHeaders.append(key, value)
+          if (key !== 'x-middleware-next') {
+            allHeaders.append(key, value)
+          }
```
Comment (Izhaki) [inline packages/next/server/next-server.ts:705]: Why was this change made?

It means that a middleware cannot longer set headers without breaking the middleware chain as we have below:

```js
        if (!result.response.headers.has('x-middleware-next')) {
          break
        }
```

This will break some of the examples, like [this one](https://github.com/vercel/examples/blob/30577906af4090c2031b8f18e4ecd0fcf6df1e65/edge-functions/ip-blocking-datadome/lib/datadome.ts#L133).

It also means that a middleware cannot simply add a cookie and keep the rest as is. For example, you may want to add a `csrf` cookie if missing, but not break the middleware chain or return a custom `Response`.
