### PR TITLE
Fix example extraction when branch name contains slash

### LINKED ISSUE #37138: Slashed `/` branch name in --example flag causes create-next-app failure
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      create-next-app: 12.1.6
```

### What browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

n/a

### Describe the Bug

`create-next-app` fails to extract example project files when the `--example` flag points to a branch with a slash in the name (i.e. `apm/canary`).

I've traced this back to the [`downloadAndExtractRepo` function](https://github.com/vercel/next.js/blob/d64512f02fbd580e55d8cda2c51b338f43f26598/packages/create-next-app/helpers/examples.ts#L71-L84). Taking `https://github.com/apmatthews/next.js/tree/apm/canary` as an example branch, this function:

1. Downloads the branch as a `.tar.gz` from `https://codeload.github.com/apmatthews/next.js/tar.gz/apm/canary`.
2. Attempts to extract files from `next.js-apm/canary.tar.gz`.

Extracting files will fail because the actual downloaded archive filename is `next.js-apm-canary.tar.gz`. It appears GitHub replaces `/` with `-` in filenames, so `create-next-app` should too.

I'll follow up with a PR 🙂 

### Expected Behavior

`create-next-app` successfully creates projects when the `--example` flag points to a branch with a slash in the name.

### To Reproduce

1. Run `npx create-next-app --example=https://github.com/apmatthews/next.js/tree/apm/canary --example-path=examples/hello-world hello-world`
2. `ls hello-world/`
3. See that there is only a `node_modules` and `yarn.lock`. None of the expected [example project files](https://github.com/apmatthews/next.js/tree/apm/canary/examples/hello-world) are present.

### PR DESCRIPTION
**Pull request by apmatthews**
Fixes #37138

I looked into adding an integration test, but I'm not sure it's possible without having a reliably persistent, slashed branch name to use in the test. Any suggestions to work around this?

## Bug

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [x] Errors have helpful link attached, see `contributing.md`

### CODE REVIEW

File: packages/create-next-app/helpers/examples.ts [hunk 1]
```diff
@@ -78,7 +78,7 @@ export function downloadAndExtractRepo(
     ),
     tar.extract(
       { cwd: root, strip: filePath ? filePath.split('/').length + 1 : 1 },
-      [`${name}-${branch}${filePath ? `/${filePath}` : ''}`]
+      [`${name}-${branch.replace(/\//, '-')}${filePath ? `/${filePath}` : ''}`]
```
Comment (ijjk) [inline packages/create-next-app/helpers/examples.ts:81]:
```suggestion
      [`${name}-${branch.replace(/\//g, '-')}${filePath ? `/${filePath}` : ''}`]
```
Looks like we might need to handle multiple slashes

**Review by ijjk — APPROVED** [review]
Thanks!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| buildDuration | 14.9s | 14.8s | -54ms |
| buildDurationCached | 5.6s | 5.6s | ✓ |
| nodeModulesSize | 479 MB | 479 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.255 | 3.251 | 0 |
| / avg req/sec | 767.97 | 768.9 | +0.93 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.067 | 1.096 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2342.97 | 2281.02 | ⚠️ -61.95 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 29.2 kB | 29.2 kB | ✓ |
| webpack-HASH.js gzip | 1.54 kB | 1.54 kB | ✓ |
| Overall change | 73 kB | 73 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 308 B | 308 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.71 kB | 2.71 kB | ✓ |
| head-HASH.js gzip | 359 B | 359 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.73 kB | 5.73 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.65 kB | 2.65 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 391 B | 391 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16 kB | 16 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| buildDuration | 17.4s | 17.2s | -209ms |
| buildDurationCached | 5.5s | 5.5s | -2ms |
| nodeModulesSize | 479 MB | 479 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.227 | 3.235 | ⚠️ +0.01 |
| / avg req/sec | 774.66 | 772.71 | ⚠️ -1.95 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.084 | 1.096 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2305.87 | 2280.25 | ⚠️ -25.62 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.7 kB | 42.7 kB | ✓ |
| main-HASH.js gzip | 29.7 kB | 29.7 kB | ✓ |
| webpack-HASH.js gzip | 1.54 kB | 1.54 kB | ✓ |
| Overall change | 74.1 kB | 74.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 311 B | 311 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.89 kB | 2.89 kB | ✓ |
| head-HASH.js gzip | 357 B | 357 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.82 kB | 5.82 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.78 kB | 2.78 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.3 kB | 16.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| _buildManifest.js gzip | 457 B | 457 B | ✓ |
| Overall change | 457 B | 457 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | apmatthews/next.js bug/37138-slashed-branches | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 9c74bd3cf5f9a48fa54e7903f40709b9a7875540
