### PR TITLE
[turbopack] Fix CSS HMR on Safari

### LINKED ISSUE #91818: 16.2 broke Safari HMR for SCSS files
### Link to the code that reproduces this issue

https://github.com/berkaytheunicorn/nextjs-hmr-scss

### To Reproduce

Just open Safari 26.3.1 and update a SCSS file (not nested)

### Current vs. Expected behavior

HMR triggers won't update css in the Safari.

Downgrading to 16.0.11 fix the issue. (16.1.x won't)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 25.3.0: Wed Jan 28 20:55:08 PST 2026; root:xnu-12377.91.3~2/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 12
Binaries:
  Node: 22.21.1
  npm: 10.9.4
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 16.0.11 // There is a newer version (16.2.1) available, upgrade recommended!
  eslint-config-next: 14.2.33
  react: 19.2.4
  react-dom: 19.2.4
  typescript: 5.9.3
```

### Which area(s) are affected? (Select all that apply)

CSS

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lukesandberg**
Fixes #91818

**Regression source:** Commit `b7e4c6a011` ("Turbopack: transpile CHUNK_SUFFIX") introduced `getChunkSuffixFromScriptSrc()` which reads query strings from `<script>` tags. On Safari, this picks up the `?ts=` param injected by the server-side cache-busting workaround in `render.tsx` (for [WebKit #187726](https://bugs.webkit.org/show_bug.cgi?id=187726)), baking it into `ASSET_SUFFIX`. This causes HMR CSS URLs to match the preloaded URL exactly, re-triggering the Safari preload cache bug and preventing style updates.

**Changes:**

- **`dev-backend-dom.ts`**: Match existing `<link>` elements by base path (strip query string) so selectors work across HMR updates with different `?ts=` values. Add Safari to the Firefox cache-busting branch so new stylesheet links always get a fresh `?ts=`.
- **`hmr-client.ts`**: Fix `mergeChunkUpdates` so a `total` update always supersedes any prior update type.

### CODE REVIEW

**Comment by lukesandberg** [comment]
* **#92124** <a href="https://app.graphite.com/github/pr/vercel/next.js/92124?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#92123** <a href="https://app.graphite.com/github/pr/vercel/next.js/92123?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/vercel/next.js/92123?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts [hunk 1]
```diff
@@ -18,12 +18,15 @@ let DEV_BACKEND: DevRuntimeBackend
     unloadChunk(chunkUrl) {
       deleteResolver(chunkUrl)
 
+      // Strip query string so we match links regardless of cache-busting
+      // params (e.g. ?ts=) that may differ between HMR updates.
+      const baseChunkUrl = chunkUrl.split('?')[0]
```
Comment (mmastrac) [inline turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts:23]: Better to use new URL(chunkUrl).pathname?

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts [hunk 2]
```diff
@@ -51,9 +54,12 @@ let DEV_BACKEND: DevRuntimeBackend
           return
         }
 
-        const decodedChunkUrl = decodeURI(chunkUrl)
+        // Strip query string so we match links regardless of cache-busting
+        // params (e.g. ?ts=) that may differ between HMR updates.
+        const baseChunkUrl = chunkUrl.split('?')[0]
```
Comment (mmastrac) [inline turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts:59]: Better to use new URL(chunkUrl).pathname?

**Comment by wbinnssmith** [comment]
Looks good, can we add a test to catch this?

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts (hunk 1 above)
Comment (lukesandberg) [reply turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts:23]: in this case it is a relative url

/_next/static/chunks/abc.css

so it seems like overkill?

**Comment by lukesandberg** [comment]
> Looks good, can we add a test to catch this?

​not easily. afaict we don't have any hmr tests for safari or firefox in CI

**Comment by lukesandberg** [comment]
i did manually test this with firefox and safari (and chrome) so css loading is working, but yeah it is a risk

**Comment by lukesandberg** [comment]
ok, this is easy we actualyl already have css hmr tests, just not for firefox and safari

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts (hunk 1 above)
Comment (lukesandberg) [reply turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts:23]: plus we would have to pass an origin as well `new URK(chunkUrl, origin).pathname`  but since we know there is no host/scheme/etc a split is pretty good

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts (hunk 2 above)
Comment (lukesandberg) [reply turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts:59]: same as above

**Review by mmastrac — APPROVED** [review]

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts [hunk 3]
```diff
@@ -64,15 +70,28 @@ let DEV_BACKEND: DevRuntimeBackend
...
-          link.href = `${chunkUrl}?ts=${Date.now()}`
+          // Replace or add a fresh `ts` cache-busting param without
+          // discarding other query parameters that may already be present.
+          const url = new URL(chunkUrl, location.origin)
+          url.searchParams.set('ts', String(Date.now()))
+          // Reduced timer precision in some browers could lead to an update getting dropped
+          // in firefox if it happens fast enough (in firefox precision is sometimes 100ms!).
+          // So trust that the server is only updating us when it is important and use a
+          // random number to bust the cache.
+          url.searchParams.set('_next_rand', String(Math.random()))
```
Comment (sokra) [inline turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts:93]: Could we append the random value to `ts`, so we avoid an extra query param. Also I dislike the mention of `next` in Turbopack code. It should be independent of next.js

Comment (lukesandberg) [reply turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts:93]: Appending to ts sounds good👍

Comment (lukesandberg) [reply turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/dom/dev-backend-dom.ts:93]: https://github.com/vercel/next.js/pull/92214
