### PR TITLE
Don't look up for TS files in dev

### LINKED ISSUE #8312: hasTypeScript is very slow with big directories
# Bug report

## Describe the bug

I'm creating an app with the latest version of Next.js. 
This app contains a symlinked folder to a network drive with tons of files. 

When starting `next dev` there is a check to know if there is a TypeScript file. ( https://github.com/zeit/next.js/blob/master/packages/next/lib/verifyTypeScriptSetup.ts#L19-L27 )

This check is very fast on a small folder but seems very inefficient on bigger folders. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Start a new app
2. Have a folder with gigabytes of small files (in my case 200'000 files, more than 300GB)
3. Start `yarn dev`
4. I waited for ~10 minutes and it didn't start

## Expected behavior

I'd hope for it to start within a few seconds

## Screenshots

No Screenshots available

## System information

- OS: macOS
- Browser (if applies) -
- Version of Next.js: 12.6.0

## Additional context

I can remove the symlink to have it start fast. But the function seems inefficient, counting all TypeScript files to know if there is at least one.

My suggestions: 
* bail on the first positive result
* skip if there is a tsconfig.json
* add an option to skip this check.

I'm willing to make a pull request for the option you prefer

### PR DESCRIPTION
**Pull request by lfades**
This change may save some startup time for projects with many files that are already using TypeScript.

Fixes #8312

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 22.3s | 22s | -258ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -109 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 849 B | 848 B | -1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 842 B | 839 B | -3 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 836 B | 832 B | -4 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 23.3s | 23.4s | ⚠️ +118ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -109 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.2 kB | 66.2 kB | ✓ |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | ✓ |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.7 kB | 68.7 kB | ⚠️ +1 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | ✓ |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

</details>

**Review by Timer — CHANGES_REQUESTED** [review]
Let's just remove file searching and rely on `tsconfig.json` presence only.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 24.2s | 23.9s | -323ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -95 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 847 B | 848 B | ⚠️ +1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 842 B | 842 B | ✓ |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 832 B | 832 B | ✓ |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 24.7s | 25.6s | ⚠️ +818ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -95 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.2 kB | 66.2 kB | -4 B |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | -2 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.7 kB | 68.7 kB | -3 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | -3 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 21.7s | 21.9s | ⚠️ +169ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -711 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 846 B | 847 B | ⚠️ +1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 838 B | 839 B | ⚠️ +1 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 831 B | 832 B | ⚠️ +1 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 23s | 23s | -30ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -711 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.2 kB | 66.2 kB | ⚠️ +1 B |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | ⚠️ +2 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.7 kB | 68.7 kB | ✓ |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | ⚠️ +1 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | ⚠️ +1 B |
| Overall change |  |  | ✓ |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 22.6s | 22.6s | -47ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -711 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 846 B | 846 B | ✓ |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 837 B | 838 B | ⚠️ +1 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 830 B | 831 B | ⚠️ +1 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 24.1s | 24.2s | ⚠️ +12ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -711 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.2 kB | 66.2 kB | ⚠️ +2 B |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | ⚠️ +1 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.7 kB | 68.7 kB | ⚠️ +1 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | ⚠️ +1 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | ⚠️ +1 B |
| Overall change |  |  | ✓ |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 21.1s | 22s | ⚠️ +915ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -913 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 846 B | 847 B | ⚠️ +1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 837 B | 838 B | ⚠️ +1 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 833 B | 830 B | -3 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 22.5s | 22.9s | ⚠️ +391ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -913 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | -91 B |
| _error.js gzip | 66.2 kB | 66.2 kB | -44 B |
| index.js | 247 kB | 247 kB | -91 B |
| index.js gzip | 66.6 kB | 66.5 kB | -47 B |
| link.js | 255 kB | 255 kB | -91 B |
| link.js gzip | 68.7 kB | 68.7 kB | -44 B |
| routerDirect.js | 248 kB | 248 kB | -91 B |
| routerDirect.js gzip | 66.5 kB | 66.4 kB | -45 B |
| withRouter.js | 248 kB | 248 kB | -91 B |
| withRouter.js gzip | 66.6 kB | 66.5 kB | -45 B |
| Overall change |  |  | -455 B |

</details>

</details>

File: packages/next/lib/verifyTypeScriptSetup.ts [hunk 1]
```diff
@@ -98,10 +87,10 @@ export async function verifyTypeScriptSetup(dir: string): Promise<void> {
 
   const hasTsConfig = await fileExists(tsConfigPath)
   const isYarn = await fileExists(yarnLockFile)
-  const hasTypeScriptFiles = await hasTypeScript(dir)
-  let firstTimeSetup = !hasTsConfig && hasTypeScriptFiles
 
-  if (!(hasTsConfig || hasTypeScriptFiles)) {
+  let firstTimeSetup = false
```
Comment (Timer) [inline packages/next/lib/verifyTypeScriptSetup.ts]: Let's read the TsConfig here and check if it's empty or a `{}` string.

**Review by Timer — CHANGES_REQUESTED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 24.1s | 23.5s | -637ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -749 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ⚠️ +28 B |
| main-HASH.js gzip | 4.86 kB | 4.87 kB | ⚠️ +9 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ⚠️ +28 B |
| main-HASH.module.js gzip | 4.3 kB | 4.31 kB | ⚠️ +8 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 847 B | 846 B | -1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 838 B | 837 B | -1 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 836 B | 830 B | -6 B |
| Overall change |  |  | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -705,11 +705,7 @@ function markRenderComplete() {
 
 function clearMarks() {
   performance.clearMarks();
-  /*
-  * TODO: uncomment the following line when we have a way to
-  * expose this to user code.
-  */
-  // performance.clearMeasures()
+  performance.clearMeasures();
 }
 
 function AppContainer(_ref4) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -587,11 +587,7 @@ function markRenderComplete() {
 
 function clearMarks() {
   performance.clearMarks();
-  /*
-  * TODO: uncomment the following line when we have a way to
-  * expose this to user code.
-  */
-  // performance.clearMeasures()
+  performance.clearMeasures();
 }
 
 function AppContainer(_ref4) {
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 24.5s | 25.1s | ⚠️ +582ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -749 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ⚠️ +28 B |
| main-HASH.js gzip | 4.86 kB | 4.87 kB | ⚠️ +9 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ⚠️ +28 B |
| main-HASH.module.js gzip | 4.3 kB | 4.31 kB | ⚠️ +8 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | -91 B |
| _error.js gzip | 66.3 kB | 66.2 kB | -45 B |
| index.js | 247 kB | 247 kB | -91 B |
| index.js gzip | 66.6 kB | 66.5 kB | -47 B |
| link.js | 255 kB | 255 kB | -91 B |
| link.js gzip | 68.7 kB | 68.7 kB | -44 B |
| routerDirect.js | 248 kB | 248 kB | -91 B |
| routerDirect.js gzip | 66.5 kB | 66.4 kB | -44 B |
| withRouter.js | 248 kB | 248 kB | -91 B |
| withRouter.js gzip | 66.6 kB | 66.5 kB | -45 B |
| Overall change |  |  | -455 B |

</details>

</details>

**Review by Timer — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 23.9s | 24s | ⚠️ +96ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -804 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ⚠️ +28 B |
| main-HASH.js gzip | 4.86 kB | 4.87 kB | ⚠️ +9 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ⚠️ +28 B |
| main-HASH.module.js gzip | 4.3 kB | 4.31 kB | ⚠️ +8 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 848 B | 843 B | -5 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 843 B | 838 B | -5 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 838 B | 831 B | -7 B |
| Overall change |  |  | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[2],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
@@ -705,11 +705,7 @@ function markRenderComplete() {
 
 function clearMarks() {
   performance.clearMarks();
-  /*
-  * TODO: uncomment the following line when we have a way to
-  * expose this to user code.
-  */
-  // performance.clearMeasures()
+  performance.clearMeasures();
 }
 
 function AppContainer(_ref4) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[2],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
@@ -587,11 +587,7 @@ function markRenderComplete() {
 
 function clearMarks() {
   performance.clearMarks();
-  /*
-  * TODO: uncomment the following line when we have a way to
-  * expose this to user code.
-  */
-  // performance.clearMeasures()
+  performance.clearMeasures();
 }
 
 function AppContainer(_ref4) {
```
</details>
<details>
<summary>Diff for <strong>_app.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[2],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
 
 /***/ "B5Ud":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_error.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
 
 /***/ "+iuc":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>index.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
 
 /***/ "RNiq":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
 
 /***/ "LtRI":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
 
 /***/ "0Hlz":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_app.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[2],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_error.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
 
 /***/ "+iuc":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>index.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
 
 /***/ "RNiq":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>routerDirect.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
 
 /***/ "LtRI":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>withRouter.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
 
 /***/ "0Hlz":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 24.4s | 24.9s | ⚠️ +518ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -804 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ⚠️ +28 B |
| main-HASH.js gzip | 4.86 kB | 4.87 kB | ⚠️ +9 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ⚠️ +28 B |
| main-HASH.module.js gzip | 4.3 kB | 4.31 kB | ⚠️ +8 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | -91 B |
| _error.js gzip | 66.3 kB | 66.2 kB | -44 B |
| index.js | 247 kB | 247 kB | -91 B |
| index.js gzip | 66.6 kB | 66.5 kB | -46 B |
| link.js | 255 kB | 255 kB | -91 B |
| link.js gzip | 68.7 kB | 68.7 kB | -44 B |
| routerDirect.js | 248 kB | 248 kB | -91 B |
| routerDirect.js gzip | 66.5 kB | 66.4 kB | -45 B |
| withRouter.js | 248 kB | 248 kB | -91 B |
| withRouter.js gzip | 66.6 kB | 66.5 kB | -47 B |
| Overall change |  |  | -455 B |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 24.2s | 24.1s | -51ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -404 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.86 kB | 4.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.3 kB | 4.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 848 B | 847 B | -1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 839 B | 841 B | ⚠️ +2 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 836 B | 836 B | ✓ |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 24.7s | 25.4s | ⚠️ +650ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -404 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.86 kB | 4.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.3 kB | 4.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.2 kB | 66.3 kB | ⚠️ +1 B |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.6 kB | 66.6 kB | ⚠️ +1 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.7 kB | 68.7 kB | ⚠️ +1 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.5 kB | 66.5 kB | ⚠️ +1 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.6 kB | 66.6 kB | ⚠️ +2 B |
| Overall change |  |  | ✓ |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 23.8s | 23s | -779ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -404 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.86 kB | 4.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.3 kB | 4.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 847 B | 847 B | ✓ |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 841 B | 837 B | -4 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 836 B | 836 B | ✓ |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| buildDuration | 23.7s | 23.9s | ⚠️ +187ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | -404 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.86 kB | 4.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.3 kB | 4.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 286 B | -1 B |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | -1 B |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | lfades/next.js readdir-typescript | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.2 kB | 66.2 kB | -1 B |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.6 kB | 66.6 kB | ✓ |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.7 kB | 68.7 kB | -1 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.5 kB | 66.5 kB | ✓ |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.6 kB | 66.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

</details>
