### PR TITLE
Handle pnpm-workspace.yaml while searching for monorepo root

### LINKED ISSUE #74731: Turbopack: "Next.js package not found" in monorepo setup
### Link to the code that reproduces this issue

https://github.com/erisol-dev/nova-ai.git

### To Reproduce

Just clone my repo I guess for now and try and run it, it supposed to be a python backend with a next js front end.

https://github.com/erisol-dev/nova-ai.git

### Current vs. Expected behavior

I encountered the error "Next.js package not found" while using Turbopack in a monorepo setup. The issue occurs when running pnpm dev or next dev --turbopack in my project.

This error appears after adding or modifying configurations in my Next.js project. Turbopack was working previously, but after some changes (detailed below), it started failing.

### Provide environment information

```bash
'yarn' is not recognized as an internal or external command,
operable program or batch file.

Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
  Available memory (MB): 32652
  Available CPU cores: 12
Binaries:
  Node: 22.12.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: 9.15.3
Relevant Packages:
  next: 15.1.4 // Latest available version is detected (15.1.4).
  eslint-config-next: 15.1.4
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.7.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by timneutkens**
## What?

In order for Next.js to know where the root of the project (i.e. monorepo) is we have a heuristic for searching for the root by looking upwards from the application's directory trying to find the package manager lockfiles. This works really well and in practice you rarely have to provide the root directory. In some cases, e.g. when you're creating a monorepo based on an existing repository you might forget to delete the previous repository lockfile. E.g. in #74731 that was the cause for the issue. While having that lockfile in the repo doesn't do anything it does affect the project root heuristic because that unused lockfile is matched on the filesystem and is higher up than the actual root (in the application directory).

While looking at the reproduction in #74731 I realized we can consider `pnpm-workspace.yaml` first before matching the lockfiles. Still need to verify if we need a separate findup call for that or if it will recursively look up per item first.

Fixes #74731

### CODE REVIEW

**Comment by timneutkens** [comment]
* **#74818** <a href="https://app.graphite.com/github/pr/vercel/next.js/74818?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/vercel/next.js/74818?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ijjk** [comment]
## Tests Passed

<!-- ## Failing test suites -- >

File: packages/next/src/lib/find-root.ts [hunk 1]
```diff
@@ -1,7 +1,21 @@
 import { dirname } from 'path'
 import findUp from 'next/dist/compiled/find-up'
 
-export function findRootLockFile(cwd: string) {
+function findRootLockFile(cwd: string) {
```
Comment (eps1lon) [inline packages/next/src/lib/find-root.ts:4]: should rename this since we no longer look for the lockfile but the workroot

**Review by huozhi — APPROVED** [review]

File: test/e2e/app-dir/pnpm-workspace-root/pnpm-workspace-root.test.ts [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+      'package-lock.json': JSON.stringify({
+        name: 'parent-workspace',
+        version: '1.0.0',
+        lockfileVersion: 3,
+      }),
+      // Write pnpm-workspace.yaml in the same parent directory.
+      // This file should be prioritized over lockfiles when determining root.
+      // Note: pnpm-workspace.yaml will be detected by pnpm, but since we also
+      // include a proper package.json, it should work correctly.
+      '../pnpm-workspace.yaml': 'packages:\n  - "test"\n',
```
Comment (huozhi) [inline test/e2e/app-dir/pnpm-workspace-root/pnpm-workspace-root.test.ts:33]: ~~will this be able to cleaned when tear down the test?~~ it's using `subDir` should be fine

Comment (timneutkens) [reply test/e2e/app-dir/pnpm-workspace-root/pnpm-workspace-root.test.ts:33]: It's still part of the test directory because of the `subDir: 'test'` it's already nested :eyes:
