### PR TITLE
Make jest config serializable

### LINKED ISSUE #47407: [NEXT-901] Jest configuration generated with `next/jest` is not JSON-serializable
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
❯ ./node_modules/.bin/next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1-NixOS SMP Mon Mar 13 09:20:37 UTC 2023
    Binaries:
      Node: 18.14.1
      npm: 9.3.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Jest (next/jest)

### Link to the code that reproduces this issue

https://github.com/cprussin/create-jest-runner-issue-repro

### To Reproduce

- Clone repo
- `npm install`
- `npm exec jest`

### Describe the Bug

While investigating https://github.com/jest-community/create-jest-runner/issues/201, I discovered that `next/jest` generates a jest config that is not JSON-serializable [by attaching the next config to the transformer config](https://github.com/vercel/next.js/blob/bbd79ac9977e03010e09ff90d933f2ec614b031f/packages/next/src/build/jest/jest.ts#L144).

The Jest docs [clearly state](https://jestjs.io/docs/configuration) that the config should always be JSON-serializable, and violating that results in tasks run with [Jest's child process worker](https://github.com/facebook/jest/blob/main/packages/jest-worker/src/workers/ChildProcessWorker.ts) failing with the error message `()=>null could not be cloned.` (basically the serialization to send the job to the child process fails).

The most consistent way I've found to reproduce the issue is to use something based on `create-jest-runner`, such as `jest-runner-eslint`, alongside the next jest runner, but it's most certainly not the only way to get jest to put work on the child process worker (I'm a bit hazy on the details of exactly what causes jest to use the child process worker and what doesn't TBH).

The simplest fix here is to strip non-serializable elements from the next config before passing it to the transformer [here](https://github.com/vercel/next.js/blob/bbd79ac9977e03010e09ff90d933f2ec614b031f/packages/next/src/build/jest/jest.ts#L144).  In my testing, it seems like `generateBuildId` is the function that causes the problem for my minimal repro case.  However, I'm sure there are other functions that will make their way into the config and cause problems, so it may be more appropriate to create an allowlist of parts of the next config that get passed down to the swc jest transformer rather than trying to delete non-serializable elements out of it.

### Expected Behavior

The jest config generated by `next/jest` should be serializable and should not cause `()=>null could not be cloned.` when sending workers to a child process.

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

<sub>[NEXT-901](https://linear.app/vercel/issue/NEXT-901/jest-configuration-generated-with-nextjest-is-not-json-serializable)</sub>

### PR DESCRIPTION
**Pull request by cprussin**
### What?

This PR ensures the jest configuration is json-serializable.  It also adds a bunch of typescript types.

### Why?

Jest requires that the configuration be json-serializable.  See #47407 for details on the issues caused when it isn't.  However, prior to this commit, we were passing the entire next config as a property in the swc jest transformer options.  The next config includes some fields that are not serializable, such as some functions.

### How?

In this PR we instead pluck the fields out of the next config that we actually need and pass only those into the swc transformer.

This PR also adds a bunch of more precise typescript types where we were previously just using `any`.  This helps confirm that the configs are being threaded through correctly.  I think this type safety is enough to confirm this commit and adding tests would just be redundant.

Closes NEXT-901
Fixes #47407
fix NEXT-901 ([link](https://linear.app/vercel/issue/NEXT-901))

### CODE REVIEW

**Comment by cprussin** [comment]
FWIW I also confirmed this fixes the [minimal repro case](https://github.com/cprussin/create-jest-runner-issue-repro) mentioned in #47407

File: packages/next/src/build/swc/jest-transformer.ts [hunk 1]
```diff
@@ -29,49 +29,79 @@ DEALINGS IN THE SOFTWARE.
...
-function getJestConfig(jestConfig: any) {
+function getJestConfig(
+  jestConfig: TransformOptions<JestTransformerConfig>
+): Config.ProjectConfig {
   return 'config' in jestConfig
     ? // jest 27
       jestConfig.config
     : // jest 26
-      jestConfig
+      (jestConfig as unknown as Config.ProjectConfig)
```
Comment (mrazauskas) [inline packages/next/src/build/swc/jest-transformer.ts:62]: The `ProjectConfig` type represents already normalized config. Configs supplied by a user are defined in types prefixed with `Initial`: `InitialConfig`, `InitialProjectConfig`.

Comment (mrazauskas) [reply packages/next/src/build/swc/jest-transformer.ts:62]: Jest is passing `ProjectConfig` to transformers, that is right. If transformer is called directly, you should pass `ProjectConfig` to it.

If we talk about the type of the object of the default export of `jest.config` file, this is `InitialOptions`.

If a function is exported it should return `InitialOption`.

The `projects` option if typed as: `Array<string | InitialProjectOptions>`.

Comment (cprussin) [reply packages/next/src/build/swc/jest-transformer.ts:62]: sorry, I'm not following -- this is in the transformer, this is not part of the `jest.config` file -- am I missing something?

Comment (mrazauskas) [reply packages/next/src/build/swc/jest-transformer.ts:62]: Must be right then.

Sorry, my mind got stuck with the problem you had with a function ending up in `jest.config`. Did not realise you are tweaking something inside a transformer.

Comment (cprussin) [reply packages/next/src/build/swc/jest-transformer.ts:62]: got it!  yeah this change ended up needing to go deeper than I expected, mostly because everything was typed as `any` which made it hard to be confident about the change until I added real types

**Review by timneutkens — DISMISSED** [review]

**Comment by timneutkens** [comment]
Thanks! Seems there's a merge conflict blocking the merge.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | cprussin/next.js canary | Change |
| - | - | - | - |
| buildDuration | 38.2s | 36.5s | -1.7s |
| buildDurationCached | 10.1s | 9.9s | -158ms |
| nodeModulesSize | 120 MB | 114 MB | -5.89 MB |
| nextStartRea..uration (ms) | 287ms | 287ms | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | cprussin/next.js canary | Change |
| - | - | - | - |
| 182-HASH.js gzip | 20.7 kB | N/A | N/A |
| 869.HASH.js gzip | 181 B | 180 B | -1 B |
| 974ec2d0-HASH.js gzip | 50.2 kB | N/A | N/A |
| main-app-HASH.js gzip | 216 B | 212 B | -4 B |
| main-HASH.js gzip | 83.9 kB | 82.8 kB | -1.04 kB |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | -2 B |
| 893-HASH.js gzip | N/A | 69.5 kB | N/A |
| Overall change | 157 kB | 154 kB | -2.37 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | cprussin/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | cprussin/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 192 B | ✓ |
| _error-HASH.js gzip | 180 B | 179 B | -1 B |
| amp-HASH.js gzip | 483 B | 481 B | -2 B |
| css-HASH.js gzip | 801 B | 799 B | -2 B |
| dynamic-HASH.js gzip | 2.27 kB | 2.27 kB | -4 B |
| edge-ssr-HASH.js gzip | 259 B | 259 B | ✓ |
| head-HASH.js gzip | 828 B | 827 B | -1 B |
| hooks-HASH.js gzip | 849 B | 847 B | -2 B |
| image-HASH.js gzip | 4.44 kB | 4.43 kB | -6 B |
| index-HASH.js gzip | 252 B | 254 B | ⚠️ +2 B |
| link-HASH.js gzip | 2.76 kB | 2.76 kB | ✓ |
| routerDirect..HASH.js gzip | 781 B | 782 B | ⚠️ +1 B |
| script-HASH.js gzip | 858 B | 856 B | -2 B |
| withRouter-HASH.js gzip | 782 B | 779 B | -3 B |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.8 kB | 15.8 kB | -20 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | cprussin/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 483 B | ✓ |
| Overall change | 483 B | 483 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | cprussin/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 547 B | 547 B | ✓ |
| link.html gzip | 557 B | 559 B | ⚠️ +2 B |
| withRouter.html gzip | 544 B | 544 B | ✓ |
| Overall change | 1.65 kB | 1.65 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | cprussin/next.js canary | Change |
| - | - | - | - |
| edge-ssr.js gzip | 132 kB | 131 kB | -952 B |
| page.js gzip | 117 kB | 117 kB | ⚠️ +409 B |
| Overall change | 249 kB | 248 kB | -543 B |

</details>

<details>
<summary><strong>Middleware size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | cprussin/next.js canary | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 604 B | 586 B | -18 B |
| middleware-r..fest.js gzip | 145 B | 144 B | -1 B |
| middleware.js gzip | 18.4 kB | 27.3 kB | ⚠️ +8.92 kB |
| edge-runtime..pack.js gzip | 1.83 kB | 1.83 kB | ✓ |
| Overall change | 21 kB | 29.9 kB | ⚠️ +8.9 kB |

</details>

#### Diffs
<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware-b..-manifest.js</strong></summary>

```diff
@@ -7,82 +7,81 @@ self.__BUILD_MANIFEST = {
     "static/BUILD_ID/_ssgManifest.js",
   ],
   rootMainFiles: [
-    "static/chunks/webpack-d9965445ebce461e.js",
-    "static/chunks/974ec2d0-4c2565133a55f6e5.js",
-    "static/chunks/182-65bde066f4b02699.js",
-    "static/chunks/main-app-0189348c8170d51e.js",
+    "static/chunks/webpack-c61449b956bd4ddc.js",
+    "static/chunks/893-39e04132d5a8d389.js",
+    "static/chunks/main-app-e28fb7a620af526c.js",
   ],
   pages: {
     "/": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
-      "static/chunks/pages/index-96b4df8f97c0f01a.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
+      "static/chunks/pages/index-b21e2d2005e858d6.js",
     ],
     "/_app": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
-      "static/chunks/pages/_app-39c49a32fdfb4902.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
+      "static/chunks/pages/_app-fd2fd11c0153c1f4.js",
     ],
     "/_error": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
-      "static/chunks/pages/_error-d79135b4d7090152.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
+      "static/chunks/pages/_error-65d572d29e2548b7.js",
     ],
     "/amp": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
-      "static/chunks/pages/amp-3e73e98c5f333ae8.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
+      "static/chunks/pages/amp-62aee2a49812a08f.js",
     ],
     "/css": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
       "static/css/94fdbc56eafa2039.css",
-      "static/chunks/pages/css-5e256e56d8e26951.js",
+      "static/chunks/pages/css-62cc12dcb475f18b.js",
     ],
     "/dynamic": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
-      "static/chunks/pages/dynamic-c81f7204b8a7f946.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
+      "static/chunks/pages/dynamic-b2fe956bab12dbce.js",
     ],
     "/edge-ssr": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
-      "static/chunks/pages/edge-ssr-36372aa7b0810cd4.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
+      "static/chunks/pages/edge-ssr-53842fa626eeba30.js",
     ],
     "/head": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
-      "static/chunks/pages/head-bba3641f74516a0d.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
+      "static/chunks/pages/head-0b621999ef90df87.js",
     ],
     "/hooks": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
-      "static/chunks/pages/hooks-5bc49a85e3a1ebb1.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
+      "static/chunks/pages/hooks-2b5b04fc08660760.js",
     ],
     "/image": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
-      "static/chunks/pages/image-e4e98b3ddd87094f.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
+      "static/chunks/pages/image-6f22db55fbf57ed3.js",
     ],
     "/link": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
-      "static/chunks/pages/link-ee4f7deeb8112e61.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
+      "static/chunks/pages/link-6af118e4c6f497bb.js",
     ],
     "/routerDirect": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
-      "static/chunks/pages/routerDirect-5d7d47d901e3719c.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
+      "static/chunks/pages/routerDirect-99b080df5d4700e8.js",
     ],
     "/script": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
-      "static/chunks/pages/script-7181948a834b7ae4.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
+      "static/chunks/pages/script-1cb960fab1da586d.js",
     ],
     "/withRouter": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-8d29548a1f649ea2.js",
-      "static/chunks/pages/withRouter-ebac16c2d9b51247.js",
+      "static/chunks/webpack-c61449b956bd4ddc.js",
+      "static/chunks/main-fb41ef740a1a6570.js",
+      "static/chunks/pages/withRouter-00f6845c2afd30e2.js",
     ],
   },
   ampFirstPages: [],
```
</details>
<details>
<summary>Diff for <strong>middleware-r..-manifest.js</strong></summary>

```diff
@@ -1,6 +1,6 @@
 self.__REACT_LOADABLE_MANIFEST = {
   "dynamic.js -> ../components/hello": {
-    id: 4869,
-    files: ["static/chunks/869.cb3f1602da3175db.js"],
+    id: 959,
+    files: ["static/chunks/959.34508e89b1d2d329.js"],
   },
 };
```
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,28 +1,28 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-96b4df8f97c0f01a.js"],
-  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-d79135b4d7090152.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-3e73e98c5f333ae8.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-b21e2d2005e858d6.js"],
+  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-65d572d29e2548b7.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-62aee2a49812a08f.js"],
   "/css": [
     "static\u002Fcss\u002F94fdbc56eafa2039.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-5e256e56d8e26951.js",
+    "static\u002Fchunks\u002Fpages\u002Fcss-62cc12dcb475f18b.js",
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-c81f7204b8a7f946.js",
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-b2fe956bab12dbce.js",
   ],
   "/edge-ssr": [
-    "static\u002Fchunks\u002Fpages\u002Fedge-ssr-36372aa7b0810cd4.js",
+    "static\u002Fchunks\u002Fpages\u002Fedge-ssr-53842fa626eeba30.js",
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-bba3641f74516a0d.js"],
-  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-5bc49a85e3a1ebb1.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-e4e98b3ddd87094f.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-ee4f7deeb8112e61.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-0b621999ef90df87.js"],
+  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-2b5b04fc08660760.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-6f22db55fbf57ed3.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-6af118e4c6f497bb.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-5d7d47d901e3719c.js",
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-99b080df5d4700e8.js",
   ],
-  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-7181948a834b7ae4.js"],
+  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-1cb960fab1da586d.js"],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-ebac16c2d9b51247.js",
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-00f6845c2afd30e2.js",
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 3115: /***/ function (
+    /***/ 1113: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_app",
         function () {
-          return __webpack_require__(9618);
+          return __webpack_require__(6822);
         },
       ]);
       if (false) {
@@ -24,7 +24,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [179], function () {
-      return __webpack_exec__(3115), __webpack_exec__(5038);
+      return __webpack_exec__(1113), __webpack_exec__(1556);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [820],
   {
-    /***/ 5374: /***/ function (
+    /***/ 3363: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_error",
         function () {
-          return __webpack_require__(1261);
+          return __webpack_require__(3972);
         },
       ]);
       if (false) {
@@ -24,7 +24,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function () {
-      return __webpack_exec__(5374);
+      return __webpack_exec__(3363);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>amp-HASH.js</strong></summary>

```diff
@@ -1,17 +1,17 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [216],
   {
-    /***/ 8510: /***/ function (
+    /***/ 8753: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(6863);
+      module.exports = __webpack_require__(1088);
 
       /***/
     },
 
-    /***/ 7010: /***/ function (
+    /***/ 5348: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -19,7 +19,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/amp",
         function () {
-          return __webpack_require__(8381);
+          return __webpack_require__(1458);
         },
       ]);
       if (false) {
@@ -28,7 +28,7 @@
       /***/
     },
 
-    /***/ 6863: /***/ function (module, exports, __webpack_require__) {
+    /***/ 1088: /***/ function (module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -37,9 +37,9 @@
       exports.useAmp = useAmp;
       var _interop_require_default =
         __webpack_require__(1322) /* ["default"] */.Z;
-      var _react = _interop_require_default(__webpack_require__(2947));
-      var _ampContext = __webpack_require__(7218);
-      var _ampMode = __webpack_require__(9569);
+      var _react = _interop_require_default(__webpack_require__(465));
+      var _ampContext = __webpack_require__(583);
+      var _ampMode = __webpack_require__(8881);
       function useAmp() {
         // Don't assign the context value to a variable to save bytes
         return (0, _ampMode).isInAmpMode(
@@ -61,7 +61,7 @@
       /***/
     },
 
-    /***/ 8381: /***/ function (
+    /***/ 1458: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -78,7 +78,7 @@
         /* harmony export */
       });
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(8510);
+        __webpack_require__(8753);
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_amp__WEBPACK_IMPORTED_MODULE_0__
@@ -102,7 +102,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function () {
-      return __webpack_exec__(7010);
+      return __webpack_exec__(5348);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>css-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [706],
   {
-    /***/ 860: /***/ function (
+    /***/ 6437: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/css",
         function () {
-          return __webpack_require__(3215);
+          return __webpack_require__(5701);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 3215: /***/ function (
+    /***/ 5701: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -26,9 +26,9 @@
       "use strict";
       __webpack_require__.r(__webpack_exports__);
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(3268);
+        __webpack_require__(9701);
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(4294);
+        __webpack_require__(2775);
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           _css_module_css__WEBPACK_IMPORTED_MODULE_1__
@@ -48,14 +48,14 @@
       /***/
     },
 
-    /***/ 4294: /***/ function (module) {
+    /***/ 2775: /***/ function (module) {
       // extracted by mini-css-extract-plugin
       module.exports = { helloWorld: "css_helloWorld__qqNwY" };
 
       /***/
     },
 
-    /***/ 6205: /***/ function (
+    /***/ 1963: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -70,7 +70,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      var f = __webpack_require__(2947),
+      var f = __webpack_require__(465),
         k = Symbol.for("react.element"),
         l = Symbol.for("react.fragment"),
         m = Object.prototype.hasOwnProperty,
@@ -105,7 +105,7 @@
       /***/
     },
 
-    /***/ 3268: /***/ function (
+    /***/ 9701: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
@@ -113,7 +113,7 @@
       "use strict";
 
       if (true) {
-        module.exports = __webpack_require__(6205);
+        module.exports = __webpack_require__(1963);
       } else {
       }
 
@@ -126,7 +126,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function () {
-      return __webpack_exec__(860);
+      return __webpack_exec__(6437);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [739],
   {
-    /***/ 3995: /***/ function (
+    /***/ 7753: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/dynamic",
         function () {
-          return __webpack_require__(8267);
+          return __webpack_require__(825);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 6854: /***/ function (module, exports, __webpack_require__) {
+    /***/ 1678: /***/ function (module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -29,8 +29,8 @@
       var _extends = __webpack_require__(5321) /* ["default"] */.Z;
       var _interop_require_default =
         __webpack_require__(1322) /* ["default"] */.Z;
-      var _react = _interop_require_default(__webpack_require__(2947));
-      var _loadable = _interop_require_default(__webpack_require__(8673));
+      var _react = _interop_require_default(__webpack_require__(465));
+      var _loadable = _interop_require_default(__webpack_require__(899));
       function dynamic(dynamicOptions, options) {
         let loadableFn = _loadable.default;
         let loadableOptions = {
@@ -127,7 +127,7 @@
       /***/
     },
 
-    /***/ 3611: /***/ function (
+    /***/ 6601: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -140,7 +140,7 @@
       exports.LoadableContext = void 0;
       var _interop_require_default =
         __webpack_require__(1322) /* ["default"] */.Z;
-      var _react = _interop_require_default(__webpack_require__(2947));
+      var _react = _interop_require_default(__webpack_require__(465));
       const LoadableContext = _react.default.createContext(null);
       exports.LoadableContext = LoadableContext;
       if (false) {
@@ -149,7 +149,7 @@
       /***/
     },
 
-    /***/ 8673: /***/ function (
+    /***/ 899: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -163,8 +163,8 @@
       var _extends = __webpack_require__(5321) /* ["default"] */.Z;
       var _interop_require_default =
         __webpack_require__(1322) /* ["default"] */.Z;
-      var _react = _interop_require_default(__webpack_require__(2947));
-      var _loadableContext = __webpack_require__(3611);
+      var _react = _interop_require_default(__webpack_require__(465));
+      var _loadableContext = __webpack_require__(6601);
       function resolve(obj) {
         return obj && obj.default ? obj.default : obj;
       }
@@ -404,7 +404,7 @@
       /***/
     },
 
-    /***/ 8267: /***/ function (
+    /***/ 825: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -418,9 +418,9 @@
         /* harmony export */
       });
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(3268);
+        __webpack_require__(9701);
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(6113);
+        __webpack_require__(2677);
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_dynamic__WEBPACK_IMPORTED_MODULE_1__
@@ -429,11 +429,11 @@
       const DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
         () =>
           __webpack_require__
-            .e(/* import() */ 869)
-            .then(__webpack_require__.bind(__webpack_require__, 4869)),
+            .e(/* import() */ 959)
+            .then(__webpack_require__.bind(__webpack_require__, 959)),
         {
           loadableGenerated: {
-            webpack: () => [/*require.resolve*/ 4869],
+            webpack: () => [/*require.resolve*/ 959],
           },
         }
       );
@@ -460,7 +460,7 @@
       /***/
     },
 
-    /***/ 6205: /***/ function (
+    /***/ 1963: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -475,7 +475,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      var f = __webpack_require__(2947),
+      var f = __webpack_require__(465),
         k = Symbol.for("react.element"),
         l = Symbol.for("react.fragment"),
         m = Object.prototype.hasOwnProperty,
@@ -510,7 +510,7 @@
       /***/
     },
 
-    /***/ 3268: /***/ function (
+    /***/ 9701: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
@@ -518,19 +518,19 @@
       "use strict";
 
       if (true) {
-        module.exports = __webpack_require__(6205);
+        module.exports = __webpack_require__(1963);
       } else {
       }
 
       /***/
     },
 
-    /***/ 6113: /***/ function (
+    /***/ 2677: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(6854);
+      module.exports = __webpack_require__(1678);
 
       /***/
     },
@@ -541,7 +541,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function () {
-      return __webpack_exec__(3995);
+      return __webpack_exec__(7753);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>edge-ssr-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [800],
   {
-    /***/ 6219: /***/ function (
+    /***/ 6027: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/edge-ssr",
         function () {
-          return __webpack_require__(7322);
+          return __webpack_require__(9526);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 7322: /***/ function (
+    /***/ 9526: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -50,7 +50,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function () {
-      return __webpack_exec__(6219);
+      return __webpack_exec__(6027);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>head-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [645],
   {
-    /***/ 2899: /***/ function (
+    /***/ 6955: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/head",
         function () {
-          return __webpack_require__(4463);
+          return __webpack_require__(157);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 4463: /***/ function (
+    /***/ 157: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -32,9 +32,9 @@
         /* harmony export */
       });
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(3268);
+        __webpack_require__(9701);
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(8412);
+        __webpack_require__(9046);
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_head__WEBPACK_IMPORTED_MODULE_1__
@@ -68,7 +68,7 @@
       /***/
     },
 
-    /***/ 6205: /***/ function (
+    /***/ 1963: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -83,7 +83,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      var f = __webpack_require__(2947),
+      var f = __webpack_require__(465),
         k = Symbol.for("react.element"),
         l = Symbol.for("react.fragment"),
         m = Object.prototype.hasOwnProperty,
@@ -118,7 +118,7 @@
       /***/
     },
 
-    /***/ 3268: /***/ function (
+    /***/ 9701: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
@@ -126,19 +126,19 @@
       "use strict";
 
       if (true) {
-        module.exports = __webpack_require__(6205);
+        module.exports = __webpack_require__(1963);
       } else {
       }
 
       /***/
     },
 
-    /***/ 8412: /***/ function (
+    /***/ 9046: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(6593);
+      module.exports = __webpack_require__(6732);
 
       /***/
     },
@@ -149,7 +149,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function () {
-      return __webpack_exec__(2899);
+      return __webpack_exec__(6955);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>hooks-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [757],
   {
-    /***/ 2304: /***/ function (
+    /***/ 7819: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/hooks",
         function () {
-          return __webpack_require__(59);
+          return __webpack_require__(58);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 59: /***/ function (
+    /***/ 58: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -26,9 +26,9 @@
       "use strict";
       __webpack_require__.r(__webpack_exports__);
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(3268);
+        __webpack_require__(9701);
       /* harmony import */ var react__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(2947);
+        __webpack_require__(465);
 
       /* harmony default export */ __webpack_exports__["default"] = () => {
         const [clicks1, setClicks1] =
@@ -73,7 +73,7 @@
       /***/
     },
 
-    /***/ 6205: /***/ function (
+    /***/ 1963: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -88,7 +88,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      var f = __webpack_require__(2947),
+      var f = __webpack_require__(465),
         k = Symbol.for("react.element"),
         l = Symbol.for("react.fragment"),
         m = Object.prototype.hasOwnProperty,
@@ -123,7 +123,7 @@
       /***/
     },
 
-    /***/ 3268: /***/ function (
+    /***/ 9701: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
@@ -131,7 +131,7 @@
       "use strict";
 
       if (true) {
-        module.exports = __webpack_require__(6205);
+        module.exports = __webpack_require__(1963);
       } else {
       }
 
@@ -144,7 +144,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function () {
-      return __webpack_exec__(2304);
+      return __webpack_exec__(7819);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [358],
   {
-    /***/ 5885: /***/ function (
+    /***/ 801: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function () {
-          return __webpack_require__(3428);
+          return __webpack_require__(2018);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 2957: /***/ function (module, exports, __webpack_require__) {
+    /***/ 1568: /***/ function (module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -32,13 +32,13 @@
         __webpack_require__(6687) /* ["default"] */.Z;
       var _object_without_properties_loose =
         __webpack_require__(6239) /* ["default"] */.Z;
-      var _react = _interop_require_wildcard(__webpack_require__(2947));
-      var _head = _interop_require_default(__webpack_require__(6593));
-      var _imageBlurSvg = __webpack_require__(3811);
-      var _imageConfig = __webpack_require__(8419);
-      var _imageConfigContext = __webpack_require__(8147);
-      var _warnOnce = __webpack_require__(5664);
-      var _imageLoader = _interop_require_default(__webpack_require__(5324));
+      var _react = _interop_require_wildcard(__webpack_require__(465));
+      var _head = _interop_require_default(__webpack_require__(6732));
+      var _imageBlurSvg = __webpack_require__(3681);
+      var _imageConfig = __webpack_require__(8394);
+      var _imageConfigContext = __webpack_require__(11);
+      var _warnOnce = __webpack_require__(2485);
+      var _imageLoader = _interop_require_default(__webpack_require__(4439));
       const configEnv = {
         deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
         imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
@@ -559,7 +559,7 @@
           src = typeof src === "string" ? src : staticSrc;
           let isLazy =
             !priority && (loading === "lazy" || typeof loading === "undefined");
-          if (!src || src.startsWith("data:") || src.startsWith("blob:")) {
+          if (src.startsWith("data:") || src.startsWith("blob:")) {
             // https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
             unoptimized = true;
             isLazy = false;
@@ -732,7 +732,7 @@
       /***/
     },
 
-    /***/ 3811: /***/ function (__unused_webpack_module, exports) {
+    /***/ 3681: /***/ function (__unused_webpack_module, exports) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -785,7 +785,7 @@
       /***/
     },
 
-    /***/ 5324: /***/ function (__unused_webpack_module, exports) {
+    /***/ 4439: /***/ function (__unused_webpack_module, exports) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -811,7 +811,7 @@
       /***/
     },
 
-    /***/ 3428: /***/ function (
+    /***/ 2018: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -830,10 +830,10 @@
         },
       });
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react/jsx-runtime.js
-      var jsx_runtime = __webpack_require__(3268);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/image.js
-      var next_image = __webpack_require__(3960);
+      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react/jsx-runtime.js
+      var jsx_runtime = __webpack_require__(9701);
+      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/image.js
+      var next_image = __webpack_require__(8249);
       var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // CONCATENATED MODULE: ./pages/nextjs.png
       /* harmony default export */ var nextjs = {
         src: "/_next/static/media/nextjs.cae0b805.png",
@@ -863,7 +863,7 @@
       /***/
     },
 
-    /***/ 6205: /***/ function (
+    /***/ 1963: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -878,7 +878,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      var f = __webpack_require__(2947),
+      var f = __webpack_require__(465),
         k = Symbol.for("react.element"),
         l = Symbol.for("react.fragment"),
         m = Object.prototype.hasOwnProperty,
@@ -913,7 +913,7 @@
       /***/
     },
 
-    /***/ 3268: /***/ function (
+    /***/ 9701: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
@@ -921,19 +921,19 @@
       "use strict";
 
       if (true) {
-        module.exports = __webpack_require__(6205);
+        module.exports = __webpack_require__(1963);
       } else {
       }
 
       /***/
     },
 
-    /***/ 3960: /***/ function (
+    /***/ 8249: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(2957);
+      module.exports = __webpack_require__(1568);
 
       /***/
     },
@@ -944,7 +944,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function () {
-      return __webpack_exec__(5885);
+      return __webpack_exec__(801);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>index-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [405],
   {
-    /***/ 3558: /***/ function (
+    /***/ 6481: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/",
         function () {
-          return __webpack_require__(580);
+          return __webpack_require__(7126);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 580: /***/ function (
+    /***/ 7126: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -44,7 +44,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function () {
-      return __webpack_exec__(3558);
+      return __webpack_exec__(6481);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [644],
   {
-    /***/ 8662: /***/ function (
+    /***/ 7014: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/link",
         function () {
-          return __webpack_require__(2592);
+          return __webpack_require__(4920);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 8651: /***/ function (module, exports) {
+    /***/ 9147: /***/ function (module, exports) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -48,7 +48,7 @@
       /***/
     },
 
-    /***/ 681: /***/ function (module, exports, __webpack_require__) {
+    /***/ 3051: /***/ function (module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -59,17 +59,17 @@
         __webpack_require__(1322) /* ["default"] */.Z;
       var _object_without_properties_loose =
         __webpack_require__(6239) /* ["default"] */.Z;
-      var _react = _interop_require_default(__webpack_require__(2947));
-      var _resolveHref = __webpack_require__(9560);
-      var _isLocalUrl = __webpack_require__(2790);
-      var _formatUrl = __webpack_require__(8782);
-      var _utils = __webpack_require__(1205);
-      var _addLocale = __webpack_require__(31);
-      var _routerContext = __webpack_require__(562);
-      var _appRouterContext = __webpack_require__(8557);
-      var _useIntersection = __webpack_require__(4723);
-      var _getDomainLocale = __webpack_require__(8651);
-      var _addBasePath = __webpack_require__(695);
+      var _react = _interop_require_default(__webpack_require__(465));
+      var _resolveHref = __webpack_require__(7247);
+      var _isLocalUrl = __webpack_require__(4552);
+      var _formatUrl = __webpack_require__(7090);
+      var _utils = __webpack_require__(9452);
+      var _addLocale = __webpack_require__(5899);
+      var _routerContext = __webpack_require__(9718);
+      var _appRouterContext = __webpack_require__(3651);
+      var _useIntersection = __webpack_require__(3882);
+      var _getDomainLocale = __webpack_require__(9147);
+      var _addBasePath = __webpack_require__(3852);
       const prefetched = new Set();
       function prefetch(router, href, as, options, isAppRouter) {
         if (false) {
@@ -475,15 +475,15 @@
       /***/
     },
 
-    /***/ 4723: /***/ function (module, exports, __webpack_require__) {
+    /***/ 3882: /***/ function (module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
         value: true,
       });
       exports.useIntersection = useIntersection;
-      var _react = __webpack_require__(2947);
-      var _requestIdleCallback = __webpack_require__(235);
+      var _react = __webpack_require__(465);
+      var _requestIdleCallback = __webpack_require__(5426);
       const hasIntersectionObserver =
         typeof IntersectionObserver === "function";
       const observers = new Map();
@@ -596,7 +596,7 @@
       /***/
     },
 
-    /***/ 2592: /***/ function (
+    /***/ 4920: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -610,9 +610,9 @@
         /* harmony export */
       });
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(3268);
+        __webpack_require__(9701);
       /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(4595);
+        __webpack_require__(9495);
       /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_link__WEBPACK_IMPORTED_MODULE_1__
@@ -643,7 +643,7 @@
       /***/
     },
 
-    /***/ 6205: /***/ function (
+    /***/ 1963: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -658,7 +658,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      var f = __webpack_require__(2947),
+      var f = __webpack_require__(465),
         k = Symbol.for("react.element"),
         l = Symbol.for("react.fragment"),
         m = Object.prototype.hasOwnProperty,
@@ -693,7 +693,7 @@
       /***/
     },
 
-    /***/ 3268: /***/ function (
+    /***/ 9701: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
@@ -701,19 +701,19 @@
       "use strict";
 
       if (true) {
-        module.exports = __webpack_require__(6205);
+        module.exports = __webpack_require__(1963);
       } else {
       }
 
       /***/
     },
 
-    /***/ 4595: /***/ function (
+    /***/ 9495: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(681);
+      module.exports = __webpack_require__(3051);
 
       /***/
     },
@@ -724,7 +724,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function () {
-      return __webpack_exec__(8662);
+      return __webpack_exec__(7014);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>routerDirect-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [58],
   {
-    /***/ 2188: /***/ function (
+    /***/ 7288: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/routerDirect",
         function () {
-          return __webpack_require__(2453);
+          return __webpack_require__(3223);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 2453: /***/ function (
+    /***/ 3223: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -32,9 +32,9 @@
         /* harmony export */
       });
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(3268);
+        __webpack_require__(9701);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(5866);
+        __webpack_require__(5664);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_router__WEBPACK_IMPORTED_MODULE_1__
@@ -54,7 +54,7 @@
       /***/
     },
 
-    /***/ 6205: /***/ function (
+    /***/ 1963: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -69,7 +69,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      var f = __webpack_require__(2947),
+      var f = __webpack_require__(465),
         k = Symbol.for("react.element"),
         l = Symbol.for("react.fragment"),
         m = Object.prototype.hasOwnProperty,
@@ -104,7 +104,7 @@
       /***/
     },
 
-    /***/ 3268: /***/ function (
+    /***/ 9701: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
@@ -112,19 +112,19 @@
       "use strict";
 
       if (true) {
-        module.exports = __webpack_require__(6205);
+        module.exports = __webpack_require__(1963);
       } else {
       }
 
       /***/
     },
 
-    /***/ 5866: /***/ function (
+    /***/ 5664: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(5038);
+      module.exports = __webpack_require__(1556);
 
       /***/
     },
@@ -135,7 +135,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function () {
-      return __webpack_exec__(2188);
+      return __webpack_exec__(7288);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>script-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [797],
   {
-    /***/ 1136: /***/ function (
+    /***/ 6695: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/script",
         function () {
-          return __webpack_require__(6159);
+          return __webpack_require__(3323);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 6159: /***/ function (
+    /***/ 3323: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -32,9 +32,9 @@
         /* harmony export */
       });
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(3268);
+        __webpack_require__(9701);
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(9096);
+        __webpack_require__(6071);
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_script__WEBPACK_IMPORTED_MODULE_1__
@@ -67,7 +67,7 @@
       /***/
     },
 
-    /***/ 6205: /***/ function (
+    /***/ 1963: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -82,7 +82,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      var f = __webpack_require__(2947),
+      var f = __webpack_require__(465),
         k = Symbol.for("react.element"),
         l = Symbol.for("react.fragment"),
         m = Object.prototype.hasOwnProperty,
@@ -117,7 +117,7 @@
       /***/
     },
 
-    /***/ 3268: /***/ function (
+    /***/ 9701: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
@@ -125,19 +125,19 @@
       "use strict";
 
       if (true) {
-        module.exports = __webpack_require__(6205);
+        module.exports = __webpack_require__(1963);
       } else {
       }
 
       /***/
     },
 
-    /***/ 9096: /***/ function (
+    /***/ 6071: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(550);
+      module.exports = __webpack_require__(1787);
 
       /***/
     },
@@ -148,7 +148,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function () {
-      return __webpack_exec__(1136);
+      return __webpack_exec__(6695);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>withRouter-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [807],
   {
-    /***/ 3551: /***/ function (
+    /***/ 8118: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/withRouter",
         function () {
-          return __webpack_require__(1459);
+          return __webpack_require__(7107);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 1459: /***/ function (
+    /***/ 7107: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -32,9 +32,9 @@
         /* harmony export */
       });
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(3268);
+        __webpack_require__(9701);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(5866);
+        __webpack_require__(5664);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_router__WEBPACK_IMPORTED_MODULE_1__
@@ -53,7 +53,7 @@
       /***/
     },
 
-    /***/ 6205: /***/ function (
+    /***/ 1963: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -68,7 +68,7 @@
        * This source code is licensed under the MIT license found in the
        * LICENSE file in the root directory of this source tree.
        */
-      var f = __webpack_require__(2947),
+      var f = __webpack_require__(465),
         k = Symbol.for("react.element"),
         l = Symbol.for("react.fragment"),
         m = Object.prototype.hasOwnProperty,
@@ -103,7 +103,7 @@
       /***/
     },
 
-    /***/ 3268: /***/ function (
+    /***/ 9701: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
@@ -111,19 +111,19 @@
       "use strict";
 
       if (true) {
-        module.exports = __webpack_require__(6205);
+        module.exports = __webpack_require__(1963);
       } else {
       }
 
       /***/
     },
 
-    /***/ 5866: /***/ function (
+    /***/ 5664: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(5038);
+      module.exports = __webpack_require__(1556);
 
       /***/
     },
@@ -134,7 +134,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 179], function () {
-      return __webpack_exec__(3551);
+      return __webpack_exec__(8118);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>182-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>869.HASH.js</strong></summary>

```diff
@@ -1,8 +1,8 @@
 "use strict";
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
-  [869],
+  [959],
   {
-    /***/ 4869: /***/ function (
+    /***/ 959: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -15,7 +15,7 @@
         /* harmony export */
       });
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(3268);
+        __webpack_require__(9701);
 
       const Hello = () => {
         return /*#__PURE__*/ (0,
```
</details>
<details>
<summary>Diff for <strong>893-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>974ec2d0-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>page-f9cd5c792bfd6681.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [760, 185, 952],
   {
-    /***/ 8372: /***/ function () {
+    /***/ 7746: /***/ function () {
       /***/
     },
   },
@@ -10,8 +10,8 @@
     /******/ var __webpack_exec__ = function (moduleId) {
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
-    /******/ __webpack_require__.O(0, [961, 182, 744], function () {
-      return __webpack_exec__(8372);
+    /******/ __webpack_require__.O(0, [893, 744], function () {
+      return __webpack_exec__(7746);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>page-285019c21c8d0bd5.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [952, 185, 760],
   {
-    /***/ 8372: /***/ function () {
+    /***/ 7746: /***/ function () {
       /***/
     },
   },
@@ -10,8 +10,8 @@
     /******/ var __webpack_exec__ = function (moduleId) {
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
-    /******/ __webpack_require__.O(0, [961, 182, 744], function () {
-      return __webpack_exec__(8372);
+    /******/ __webpack_require__.O(0, [893, 744], function () {
+      return __webpack_exec__(7746);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>layout-478ab..42390bf5e.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [185, 952, 760],
   {
-    /***/ 8372: /***/ function () {
+    /***/ 7746: /***/ function () {
       /***/
     },
   },
@@ -10,8 +10,8 @@
     /******/ var __webpack_exec__ = function (moduleId) {
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
-    /******/ __webpack_require__.O(0, [961, 182, 744], function () {
-      return __webpack_exec__(8372);
+    /******/ __webpack_require__.O(0, [893, 744], function () {
+      return __webpack_exec__(7746);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-app-HASH.js</strong></summary>

```diff
@@ -1,25 +1,25 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [744],
   {
-    /***/ 4206: /***/ function (
+    /***/ 5725: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 8579, 23)
+        __webpack_require__.t.bind(__webpack_require__, 3762, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 265, 23)
+        __webpack_require__.t.bind(__webpack_require__, 9349, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 5708, 23)
+        __webpack_require__.t.bind(__webpack_require__, 4309, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 1687, 23)
+        __webpack_require__.t.bind(__webpack_require__, 1233, 23)
       );
       Promise.resolve(/* import() eager */).then(
-        __webpack_require__.t.bind(__webpack_require__, 3900, 23)
+        __webpack_require__.t.bind(__webpack_require__, 8478, 23)
       );
 
       /***/
@@ -30,8 +30,8 @@
     /******/ var __webpack_exec__ = function (moduleId) {
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
-    /******/ __webpack_require__.O(0, [961, 182], function () {
-      return __webpack_exec__(1843), __webpack_exec__(4206);
+    /******/ __webpack_require__.O(0, [893], function () {
+      return __webpack_exec__(7756), __webpack_exec__(5725);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
@@ -219,7 +219,7 @@
     /******/ __webpack_require__.u = function (chunkId) {
       /******/ // return url for filenames based on template
       /******/ return (
-        "static/chunks/" + chunkId + "." + "cb3f1602da3175db" + ".js"
+        "static/chunks/" + chunkId + "." + "34508e89b1d2d329" + ".js"
       );
       /******/
     };
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -5,22 +5,22 @@
     <link
       rel="preload"
       as="script"
-      href="/_next/static/chunks/webpack-d9965445ebce461e.js"
+      href="/_next/static/chunks/webpack-c61449b956bd4ddc.js"
     />
     <link
       rel="preload"
       as="script"
-      href="/_next/static/chunks/main-8d29548a1f649ea2.js"
+      href="/_next/static/chunks/main-fb41ef740a1a6570.js"
     />
     <link
       rel="preload"
       as="script"
-      href="/_next/static/chunks/pages/_app-39c49a32fdfb4902.js"
+      href="/_next/static/chunks/pages/_app-fd2fd11c0153c1f4.js"
     />
     <link
       rel="preload"
       as="script"
-      href="/_next/static/chunks/pages/index-96b4df8f97c0f01a.js"
+      href="/_next/static/chunks/pages/index-b21e2d2005e858d6.js"
     />
     <link
       rel="preload"
@@ -41,19 +41,19 @@
       src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-d9965445ebce461e.js"
+      src="/_next/static/chunks/webpack-c61449b956bd4ddc.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8d29548a1f649ea2.js"
+      src="/_next/static/chunks/main-fb41ef740a1a6570.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-39c49a32fdfb4902.js"
+      src="/_next/static/chunks/pages/_app-fd2fd11c0153c1f4.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/index-96b4df8f97c0f01a.js"
+      src="/_next/static/chunks/pages/index-b21e2d2005e858d6.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -5,22 +5,22 @@
     <link
       rel="preload"
       as="script"
-      href="/_next/static/chunks/webpack-d9965445ebce461e.js"
+      href="/_next/static/chunks/webpack-c61449b956bd4ddc.js"
     />
     <link
       rel="preload"
       as="script"
-      href="/_next/static/chunks/main-8d29548a1f649ea2.js"
+      href="/_next/static/chunks/main-fb41ef740a1a6570.js"
     />
     <link
       rel="preload"
       as="script"
-      href="/_next/static/chunks/pages/_app-39c49a32fdfb4902.js"
+      href="/_next/static/chunks/pages/_app-fd2fd11c0153c1f4.js"
     />
     <link
       rel="preload"
       as="script"
-      href="/_next/static/chunks/pages/link-ee4f7deeb8112e61.js"
+      href="/_next/static/chunks/pages/link-6af118e4c6f497bb.js"
     />
     <link
       rel="preload"
@@ -41,19 +41,19 @@
       src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-d9965445ebce461e.js"
+      src="/_next/static/chunks/webpack-c61449b956bd4ddc.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8d29548a1f649ea2.js"
+      src="/_next/static/chunks/main-fb41ef740a1a6570.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-39c49a32fdfb4902.js"
+      src="/_next/static/chunks/pages/_app-fd2fd11c0153c1f4.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-ee4f7deeb8112e61.js"
+      src="/_next/static/chunks/pages/link-6af118e4c6f497bb.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -5,22 +5,22 @@
     <link
       rel="preload"
       as="script"
-      href="/_next/static/chunks/webpack-d9965445ebce461e.js"
+      href="/_next/static/chunks/webpack-c61449b956bd4ddc.js"
     />
     <link
       rel="preload"
       as="script"
-      href="/_next/static/chunks/main-8d29548a1f649ea2.js"
+      href="/_next/static/chunks/main-fb41ef740a1a6570.js"
     />
     <link
       rel="preload"
       as="script"
-      href="/_next/static/chunks/pages/_app-39c49a32fdfb4902.js"
+      href="/_next/static/chunks/pages/_app-fd2fd11c0153c1f4.js"
     />
     <link
       rel="preload"
       as="script"
-      href="/_next/static/chunks/pages/withRouter-ebac16c2d9b51247.js"
+      href="/_next/static/chunks/pages/withRouter-00f6845c2afd30e2.js"
     />
     <link
       rel="preload"
@@ -41,19 +41,19 @@
       src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-d9965445ebce461e.js"
+      src="/_next/static/chunks/webpack-c61449b956bd4ddc.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8d29548a1f649ea2.js"
+      src="/_next/static/chunks/main-fb41ef740a1a6570.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-39c49a32fdfb4902.js"
+      src="/_next/static/chunks/pages/_app-fd2fd11c0153c1f4.js"
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/withRouter-ebac16c2d9b51247.js"
+      src="/_next/static/chunks/pages/withRouter-00f6845c2afd30e2.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
</details>
Commit: 864bfa59f8687b028941ae64cf3a43bd2a5e73b0

**Comment by cprussin** [comment]
@timneutkens conflict resolved

**Comment by timneutkens** [comment]
Seems there's some failing tests: https://github.com/vercel/next.js/actions/runs/4576906407/jobs/8081661683?pr=47620#step:17:278

**Comment by cprussin** [comment]
@timneutkens ah looks like my merge conflict fix didn't quite fix the merge conflict.  Sorry.  I've fixed it again and pulled and verified this time, that should do it.  Apologies on the churn.

**Comment by cprussin** [comment]
@huozhi looks like there's another conflict again in this PR, and looks like the changes you're making to `modularizeImports` is causing them.  I'm happy to fix the conflict but given it looks like there's been some churn there can you let me know when you think it's settled so I don't have to keep resolving conflicts?

**Comment by cprussin** [comment]
Merge conflict fixed, thanks @huozhi .

cc @timneutkens I think this should be good to merge whenever the checks pass.  Thanks yall!

**Comment by cprussin** [comment]
I'm no expert but as far as I can tell the failed tests in the last run were unrelated to the change here.

**Comment by huozhi** [comment]
You can leave the failing status here, it can be auto merge later once all passed and approved. Since this is your 1st contribution, we need to approve the CI every time you commit or merge branch. Leaving it there can let us check which tests are failling easily.

**Comment by cprussin** [comment]
apologies @huozhi are these tests generally reliable?  It's hard to understand what they're actually doing but the failures really don't look related to this change.  I'm happy to spelunk more if the tests are considered reliable though, but looking through the recent commit log, it looks like there's a lot of flakiness in the tests so it's hard to see what's related to the change and what isn't.

Definitely happy to keep working on the PR if it needs work but could use advice navigating the tests to understand what's related and what isn't.

**Comment by huozhi** [comment]
swc options related tests are failing, seems related

**Comment by cprussin** [comment]
Ah, apologies!  I totally misunderstood the test output when I was reading it before.  I took a closer look through and now I understand the test output better.  Will dig more and fix whatever it is that's failing, thanks for the patience and sorry for my misunderstanding @huozhi

**Comment by cprussin** [comment]
@huozhi apologies on the churn here, I wasn't able to get the tests to reproduce locally for a while so I was shooting in the dark a bit--turns out I needed to build the rust code in next-swc.  Got it reproducing now and I'm fairly sure my latest commit fixed at least most of the test failures.

**Comment by huozhi** [comment]
You also need to update precompiled files. Seems I'm not able to modify your PR. Please run the command `./scripts/check-pre-compiled.sh` after pnpm install, then commit the changes to the PR. Thanks.

**Comment by cprussin** [comment]
Done, thanks @huozhi

**Review by huozhi — APPROVED** [review]
Thanks!
