### PR TITLE
Use `render` after `hydrate`

### LINKED ISSUE #19399: Using Preact, some components get rendered multiple times as duplicates
# Bug report

## Describe the bug

When using Preact (via `next-plugin-preact`), some components get rendered multiple times as duplicates.

Unfortunately, I still haven't found the root cause. The only information I have right now is that the issue doesn't occur if I use React instead.

## To Reproduce

Please see the following video (it's only about 1 minute) to see how to reproduce it.
https://streamable.com/nbkpuz

For references:
1. This is the site that is using preact in the video: 
    - https://jackyef-git-using-preact.jackyef.vercel.app/posts/6-things-i-learned-during-my-remote-job-search
    - code: https://github.com/jackyef/my-site/pull/40
2. This is the site that is using react: 
    - https://jackyef-git-using-react.jackyef.vercel.app/posts/6-things-i-learned-during-my-remote-job-search
    - code: https://github.com/jackyef/my-site/pull/39

## Expected behavior

Using Preact should have the same result with using React.

## System information

- OS: Windows
- Browser: Chrome
- Version of Next.js: 10.0.2
- Version of Node.js: 12.18.0
- Deployment: Vercel

## Additional context

The duplicated component was rendered lazily using a combination of IntersectionObserver and `next/dynamic`. The code for the component can be seen [here](https://github.com/jackyef/my-site/blob/master/src/components/Webmention/LazyWebmentionWidget.tsx) and it is rendered [here](https://github.com/jackyef/my-site/blob/master/src/components/Blog/Post/Post.tsx#L63). The component basically fetches data from an API using `react-query` and then renders some UI.

### PR DESCRIPTION
**Pull request by Timer**
Fixes #19399

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/hydrate-then-render | Change |
| - | - | - | - |
| buildDuration | 9.6s | 9.7s | ⚠️ +112ms |
| nodeModulesSize | 84.9 MB | 84.9 MB | ⚠️ +213 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/hydrate-then-render | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.186 | 2.171 | -0.02 |
| / avg req/sec | 1143.8 | 1151.42 | +7.62 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.278 | 1.265 | -0.01 |
| /error-in-render avg req/sec | 1956.06 | 1976.06 | +20 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/hydrate-then-render | Change |
| - | - | - | - |
| 677f882d2ed8..8b81.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-9cc22a8..b04f.js gzip | 6.53 kB | 6.54 kB | ⚠️ +12 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ⚠️ +12 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/hydrate-then-render | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/hydrate-then-render | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-b618194..5477.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 8.01 kB | 8.01 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/hydrate-then-render | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/hydrate-then-render | Change |
| - | - | - | - |
| index.html gzip | 615 B | 614 B | -1 B |
| link.html gzip | 622 B | 622 B | ✓ |
| withRouter.html gzip | 609 B | 608 B | -1 B |
| Overall change | 1.85 kB | 1.84 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-fd9cc05..e16fcf6c4.js</strong></summary>

```diff
@@ -884,6 +884,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
       }
 
       var reactRoot = null;
+      var shouldUseHydrate = typeof _reactDom["default"].hydrate === "function";
 
       function renderReactElement(reactEl, domEl) {
         if (false) {
@@ -894,8 +895,10 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
             performance.mark("beforeRender");
           } // The check for `.hydrate` is there to support React alternatives like preact
 
-          if (typeof _reactDom["default"].hydrate === "function") {
+          if (shouldUseHydrate) {
             _reactDom["default"].hydrate(reactEl, domEl, markHydrateComplete);
+
+            shouldUseHydrate = false;
           } else {
             _reactDom["default"].render(reactEl, domEl, markRenderComplete);
           }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-fd9cc05fa10e16fcf6c4.js"
+      href="/_next/static/chunks/main-87b094a9c5b46d633258.js"
       as="script"
     />
     <link
@@ -53,7 +53,7 @@
       src="/_next/static/chunks/polyfills-f73ba3fc145972ef83e9.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-fd9cc05fa10e16fcf6c4.js"
+      src="/_next/static/chunks/main-87b094a9c5b46d633258.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-fd9cc05fa10e16fcf6c4.js"
+      href="/_next/static/chunks/main-87b094a9c5b46d633258.js"
       as="script"
     />
     <link
@@ -58,7 +58,7 @@
       src="/_next/static/chunks/polyfills-f73ba3fc145972ef83e9.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-fd9cc05fa10e16fcf6c4.js"
+      src="/_next/static/chunks/main-87b094a9c5b46d633258.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-fd9cc05fa10e16fcf6c4.js"
+      href="/_next/static/chunks/main-87b094a9c5b46d633258.js"
       as="script"
     />
     <link
@@ -53,7 +53,7 @@
       src="/_next/static/chunks/polyfills-f73ba3fc145972ef83e9.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-fd9cc05fa10e16fcf6c4.js"
+      src="/_next/static/chunks/main-87b094a9c5b46d633258.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/hydrate-then-render | Change |
| - | - | - | - |
| buildDuration | 11.3s | 11.4s | ⚠️ +73ms |
| nodeModulesSize | 84.9 MB | 84.9 MB | ⚠️ +213 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/hydrate-then-render | Change |
| - | - | - | - |
| 677f882d2ed8..8b81.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-9cc22a8..b04f.js gzip | 6.53 kB | N/A | N/A |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| main-28805a1..f51f.js gzip | N/A | 6.54 kB | N/A |
| Overall change | 59 kB | 59 kB | ⚠️ +12 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/hydrate-then-render | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/hydrate-then-render | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-b618194..5477.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 8.01 kB | 8.01 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/hydrate-then-render | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | Timer/next.js hotfix/hydrate-then-render | Change |
| - | - | - | - |
| _error.js | 915 kB | 915 kB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 915 kB | 915 kB | ✓ |
| link.js | 973 kB | 973 kB | ✓ |
| routerDirect.js | 966 kB | 966 kB | ✓ |
| withRouter.js | 966 kB | 966 kB | ✓ |
| Overall change | 4.74 MB | 4.74 MB | ✓ |

</details>

</details>
Commit: 4f98808e9ba813257135d7d64d8485629096e54d

File: packages/next/client/index.tsx [hunk 1]
```diff
@@ -494,8 +495,9 @@ function renderReactElement(reactEl: JSX.Element, domEl: HTMLElement) {
     }
 
     // The check for `.hydrate` is there to support React alternatives like preact
-    if (typeof ReactDOM.hydrate === 'function') {
+    if (shouldUseHydrate) {
       ReactDOM.hydrate(reactEl, domEl, markHydrateComplete)
+      shouldUseHydrate = false
```
Comment (styfle) [inline packages/next/client/index.tsx:500]: How about moving `shouldUseHydrate = false` before the call to `hydrate()`?

**Review by timneutkens — APPROVED** [review]
