### PR TITLE
Monkey patch `next-sass` and `next-less`

### LINKED ISSUE #541: ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.  - options has an unknown property 'minimize'. These properties are valid:
I did correct by document and I import ./style.scss file in my js file 
but i have this error  i asked in stackoverflow but i dont get answer
please help me to fix it

package.json
dependencies{
    "@zeit/next-sass": "^1.0.1",
    "next": "^9.0.6",
    "node-sass": "^4.12.0",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
}

next.config.js
```
const withSass = require('@zeit/next-sass')
module.exports = withSass({
  /* config options here */
})
```
Screenshot (247)
Screenshot (248)
Screenshot (246)

### LINKED ISSUE #543: next-css 0.2.1-canary.4 incompatible with Next.js 9.0.7
## Bug Report

I have been using the canary version of `zeit@/next-css` because version 1.0.1 does not minify my CSS chunk in production. 

After upgrading to Next.js 9.0.7, I receive this error when starting my application using the `now dev` command or using the script `'dev': 'next'` ->

Screen Shot 2019-09-30 at 12 47 38 PM

I was able to reproduce my error on a blank slate Next.js application with the same dependencies: 
- @zeit/next-css: ^0.2.1-canary.4
- next: 9.0.7
- react: 16.10.1
- react-dom: 16.10.1
...
- now-cli: 16.3.0

Previous Next.js versions (9.0.6 and lower 9 versions) have been working flawlessly.

## System Information
- OS: MacOS Mojave Version 10.14.6
- Browser: Chrome 77.0.3865.90 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by Timer**
These two legacy Next.js plugins use poor webpack practices: they define plugins without resolving it themselves.

As a result, the resolution root is unknown by webpack and you get into package hoisting bugs.

To fix this, we emulate the logic these packages should've performed themselves on a best-effort basis.

---

Fixes https://github.com/zeit/next-plugins/issues/543
Fixes https://github.com/zeit/next-plugins/issues/541

### CODE REVIEW

**Comment by timneutkens** [comment]
Could you add a test for this?

File: packages/next/build/webpack-config.ts [hunk 1]
```diff
@@ -892,6 +892,88 @@ export default async function getBaseWebpackConfig(
...
+              'css-loader',
+              correctNextCss
+            )
+            if (correctCssLoader) {
+              // We saved the user from a failed build!
+              use.loader = correctCssLoader
+            }
+          }
+        } catch (_) {
+          // ooh noo :-(
```
Comment (timneutkens) [inline packages/next/build/webpack-config.ts]:
```suggestion
          // The error is not required to be handled.
```

**Review by timneutkens — APPROVED** [review]
