### PR TITLE
Disable image optimization for Data URLs

### LINKED ISSUE #18372: Image component fails when using image data URI
# Bug report

## Describe the bug

When passing an image data URI to the Next.js image component an error is thrown.

## To Reproduce

Pass data URI to the Next.js image component:

Example:

```javascript
import Image from 'next/image';
<Image src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=">
```

## Expected behavior

The simplest solution and expectation would be to pass the URI directly to the `img` tag without any modification or optimization.

## Screenshots

Not applicable but error reported on the debug overlay is:

```
Error: Invalid src prop (data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=) on `next/image`, hostname is not configured under images in your `next.config.js`
```

## System information

- OS: Windows
- Browser (if applies) Chrome, Firefox, Edge
- Version of Next.js: 10.0.0
- Version of Node.js: 12.9.0

## Additional context

None.

### LINKED ISSUE #18692: Investigate failing image-component tests
These tests appear to be failing sometimes and should be stabilized https://github.com/vercel/next.js/pull/18687#pullrequestreview-521780495

### PR DESCRIPTION
**Pull request by styfle**
This PR disables image optimization and lazy loading for [Data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs), because the image data is already inlined.

Fixes #18372 
Fixes #18692

### CODE REVIEW

**Review by atcastle — DISMISSED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| buildDuration | 10.9s | 10.9s | ⚠️ +23ms |
| nodeModulesSize | 90.5 MB | 90.5 MB | ⚠️ +407 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.069 | 2.098 | ⚠️ +0.03 |
| / avg req/sec | 1208.35 | 1191.67 | ⚠️ -16.68 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.088 | 1.114 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2297.63 | 2243.71 | ⚠️ -53.92 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-be398bc..d262.js gzip | 7.33 kB | 7.33 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-378f0c6..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 994 B | 994 B | ✓ |
| Overall change | 3 kB | 3 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.5s | ⚠️ +68ms |
| nodeModulesSize | 90.5 MB | 90.5 MB | ⚠️ +407 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-be398bc..d262.js gzip | 7.33 kB | 7.33 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-378f0c6..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _error.js | 1.07 MB | 1.07 MB | ✓ |
| 404.html | 4.73 kB | 4.73 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.07 MB | 1.07 MB | ✓ |
| link.js | 1.12 MB | 1.12 MB | ✓ |
| routerDirect.js | 1.11 MB | 1.11 MB | ✓ |
| withRouter.js | 1.11 MB | 1.11 MB | ✓ |
| Overall change | 5.48 MB | 5.48 MB | ✓ |

</details>

</details>
Commit: fbf10b4e4751485d9b6cf47f00ca6cc243d6ee0f

**Review by Timer — DISMISSED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.4s | -169ms |
| nodeModulesSize | 90.5 MB | 90.5 MB | ⚠️ +407 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.604 | 2.524 | -0.08 |
| / avg req/sec | 959.91 | 990.53 | +30.62 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.365 | 1.333 | -0.03 |
| /error-in-render avg req/sec | 1831.24 | 1875.63 | +44.39 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-be398bc..d262.js gzip | 7.33 kB | 7.33 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-378f0c6..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 994 B | 994 B | ✓ |
| Overall change | 3 kB | 3 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| buildDuration | 15.2s | 15.4s | ⚠️ +212ms |
| nodeModulesSize | 90.5 MB | 90.5 MB | ⚠️ +407 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-be398bc..d262.js gzip | 7.33 kB | 7.33 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-378f0c6..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _error.js | 1.07 MB | 1.07 MB | ✓ |
| 404.html | 4.73 kB | 4.73 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.07 MB | 1.07 MB | ✓ |
| link.js | 1.12 MB | 1.12 MB | ✓ |
| routerDirect.js | 1.11 MB | 1.11 MB | ✓ |
| withRouter.js | 1.11 MB | 1.11 MB | ✓ |
| Overall change | 5.48 MB | 5.48 MB | ✓ |

</details>

</details>
Commit: 5db09581fbc14bf50339ba679ee55ff347dea21a

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 5db09581fbc14bf50339ba679ee55ff347dea21a

**test/integration/image-component/default/test/index.test.js** 
- Image Component Tests > server mode > should load the images
- Image Component Tests > server mode > should work when using flexbox
- Image Component Tests > server mode > should work with layout-fixed so resizing window does not resize image
- Image Component Tests > server mode > should work with layout-intrinsic so resizing window maintains image aspect ratio
- Image Component Tests > server mode > should work with layout-responsive so resizing window maintains image aspect ratio
- Image Component Tests > server mode > should work with layout-fill to fill the parent but NOT stretch with viewport
- Image Component Tests > server mode > should work with layout-fill to fill the parent and stretch with viewport
- Image Component Tests > server mode > should correctly rotate image
- Image Component Tests > serverless mode > should load the images
- Image Component Tests > serverless mode > should work when using flexbox
- Image Component Tests > serverless mode > should work with layout-fixed so resizing window does not resize image
- Image Component Tests > serverless mode > should work with layout-intrinsic so resizing window maintains image aspect ratio
- Image Component Tests > serverless mode > should work with layout-responsive so resizing window maintains image aspect ratio
- Image Component Tests > serverless mode > should work with layout-fill to fill the parent but NOT stretch with viewport
- Image Component Tests > serverless mode > should work with layout-fill to fill the parent and stretch with viewport
- Image Component Tests > serverless mode > should correctly rotate image

<details>
<summary>Expand output</summary>

  ● Image Component Tests › server mode › should load the images

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › server mode › should work when using flexbox

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › server mode › should work with layout-fixed so resizing window does not resize image

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › server mode › should work with layout-intrinsic so resizing window maintains image aspect ratio

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › server mode › should work with layout-responsive so resizing window maintains image aspect ratio

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › server mode › should work with layout-fill to fill the parent but NOT stretch with viewport

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › server mode › should work with layout-fill to fill the parent and stretch with viewport

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › server mode › should correctly rotate image

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › serverless mode › should load the images

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › serverless mode › should work when using flexbox

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › serverless mode › should work with layout-fixed so resizing window does not resize image

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › serverless mode › should work with layout-intrinsic so resizing window maintains image aspect ratio

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › serverless mode › should work with layout-responsive so resizing window maintains image aspect ratio

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › serverless mode › should work with layout-fill to fill the parent but NOT stretch with viewport

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › serverless mode › should work with layout-fill to fill the parent and stretch with viewport

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● Image Component Tests › serverless mode › should correctly rotate image

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.3s | -234ms |
| nodeModulesSize | 90.5 MB | 90.5 MB | ⚠️ +425 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.167 | 2.138 | -0.03 |
| / avg req/sec | 1153.58 | 1169.16 | +15.58 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.186 | 1.159 | -0.03 |
| /error-in-render avg req/sec | 2108.57 | 2157.55 | +48.98 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-be398bc..d262.js gzip | 7.33 kB | 7.33 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-378f0c6..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 994 B | 994 B | ✓ |
| Overall change | 3 kB | 3 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| buildDuration | 12.8s | 13s | ⚠️ +164ms |
| nodeModulesSize | 90.5 MB | 90.5 MB | ⚠️ +425 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-be398bc..d262.js gzip | 7.33 kB | 7.33 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-378f0c6..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _error.js | 1.07 MB | 1.07 MB | ✓ |
| 404.html | 4.73 kB | 4.73 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.07 MB | 1.07 MB | ✓ |
| link.js | 1.12 MB | 1.12 MB | ✓ |
| routerDirect.js | 1.11 MB | 1.11 MB | ✓ |
| withRouter.js | 1.11 MB | 1.11 MB | ✓ |
| Overall change | 5.48 MB | 5.48 MB | ✓ |

</details>

</details>
Commit: 96ab2c61fc5b2787d8abfbdb863608d3d55bf02b

File: packages/next/client/image.tsx [hunk 1]
```diff
@@ -238,7 +238,7 @@ function getInt(x: unknown): number | undefined {
 }
 
 export default function Image({
-  src,
+  src = '',
```
Comment (Timer) [inline packages/next/client/image.tsx:241]:
```suggestion
  src,
```

This doesn't handle the `null` case.

File: packages/next/client/image.tsx [hunk 2]
```diff
@@ -310,6 +310,12 @@ export default function Image({
     lazy = false
   }
 
+  if (src.startsWith('data:')) {
```
Comment (Timer) [inline packages/next/client/image.tsx:313]: Let's check it here unless we want to make it throw in prod:

```suggestion
  if (src && src.startsWith('data:')) {
```

**Review by Timer — CHANGES_REQUESTED** [review]

**Review by Timer — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.9s | ⚠️ +369ms |
| nodeModulesSize | 90.5 MB | 90.5 MB | ⚠️ +430 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.235 | 2.193 | -0.04 |
| / avg req/sec | 1118.72 | 1139.78 | +21.06 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.202 | 1.164 | -0.04 |
| /error-in-render avg req/sec | 2080.38 | 2147.7 | +67.32 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-be398bc..d262.js gzip | 7.33 kB | 7.33 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-378f0c6..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 994 B | 994 B | ✓ |
| Overall change | 3 kB | 3 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.2s | -180ms |
| nodeModulesSize | 90.5 MB | 90.5 MB | ⚠️ +430 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-be398bc..d262.js gzip | 7.33 kB | 7.33 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-378f0c6..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _error.js | 1.07 MB | 1.07 MB | ✓ |
| 404.html | 4.73 kB | 4.73 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.07 MB | 1.07 MB | ✓ |
| link.js | 1.12 MB | 1.12 MB | ✓ |
| routerDirect.js | 1.11 MB | 1.11 MB | ✓ |
| withRouter.js | 1.11 MB | 1.11 MB | ✓ |
| Overall change | 5.48 MB | 5.48 MB | ✓ |

</details>

</details>
Commit: 808f13720d7d9aeca5bc90c0b36ba29365825ead

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| buildDuration | 11.2s | 10.9s | -358ms |
| nodeModulesSize | 90.5 MB | 90.5 MB | ⚠️ +429 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.061 | 2.04 | -0.02 |
| / avg req/sec | 1212.72 | 1225.2 | +12.48 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.082 | 1.084 | 0 |
| /error-in-render avg req/sec | 2310.49 | 2306.51 | ⚠️ -3.98 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-be398bc..d262.js gzip | 7.33 kB | 7.33 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-378f0c6..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 994 B | 994 B | ✓ |
| Overall change | 3 kB | 3 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.9s | ⚠️ +264ms |
| nodeModulesSize | 90.5 MB | 90.5 MB | ⚠️ +429 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-be398bc..d262.js gzip | 7.33 kB | 7.33 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-378f0c6..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | vercel/next.js img-data-proto-unoptimize | Change |
| - | - | - | - |
| _error.js | 1.07 MB | 1.07 MB | ✓ |
| 404.html | 4.73 kB | 4.73 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.07 MB | 1.07 MB | ✓ |
| link.js | 1.12 MB | 1.12 MB | ✓ |
| routerDirect.js | 1.11 MB | 1.11 MB | ✓ |
| withRouter.js | 1.11 MB | 1.11 MB | ✓ |
| Overall change | 5.48 MB | 5.48 MB | ✓ |

</details>

</details>
Commit: f8bc67cb0f086beaa948639a4fad1a27fa36b06e
