### PR TITLE
Use ReadableStream in client hydration for Firefox compatibility

### LINKED ISSUE #35763: ReferenceError: TransformStream is not defined when running Server Components in Firefox
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.0
      npm: 8.5.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.4-canary.1
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

Firefox 98.0.2

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

Any page that has server components do not work in Firefox.

### Expected Behavior

**Expected**

Expected Firefox to load like Chrome.
Expected 3 components to show up (each one saying I am a server component).

**Actual**

ReferenceError: TransformStream is not defined 

In production, Application error: a client-side exception has occurred (see the browser console for more information).

```
 1 of 3 unhandled errors
Unhandled Runtime Error

ReferenceError: TransformStream is not defined
Call Stack
useServerResponse
node_modules/next/dist/client/index.js (685:22)
ServerRoot
node_modules/next/dist/client/index.js (711:43)
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js (16141:0)
mountIndeterminateComponent
node_modules/react-dom/cjs/react-dom.development.js (20838:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (22342:0)
callCallback
node_modules/react-dom/cjs/react-dom.development.js (4157:0)
```

### To Reproduce

**Production**
1. Open https://next-server-components-test.vercel.app/incremental-wait in Firefox.

**Development**
1. clone this repo, https://github.com/hrgui/next-server-components-test and do `npm install`
2. Run `npm run dev`
3. Open http://localhost:3000/incremental-wait

### PR DESCRIPTION
**Pull request by huozhi**
Firefox doesn't support `TransformStream` but `ReadableStream` at the moment, change the implmentation of hydration to make firefox work with RSC

## Bug

Fixes #35763
x-ref: https://github.com/vercel/next-react-server-components/issues/38

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [x] Errors have helpful link attached, see `contributing.md`

### CODE REVIEW

File: test/integration/react-streaming-and-server-components/test/rsc.js [hunk 1]
```diff
@@ -120,10 +120,13 @@ export default function (context, { runtime, env }) {
   })
 
   it('should handle streaming server components correctly', async () => {
+    const temp = process.env.BROWSER_NAME
+    process.env.BROWSER_NAME = 'firefox'
```
Comment (ijjk) [inline test/integration/react-streaming-and-server-components/test/rsc.js:124]:
```suggestion
```
This shouldn't be needed as the env should ideally be set when running `jest` or it will always be forced to run in firefox here

File: test/integration/react-streaming-and-server-components/test/rsc.js [hunk 2]
```diff
@@ -120,10 +120,13 @@ export default function (context, { runtime, env }) {
...
     const browser = await webdriver(context.appPort, '/streaming-rsc')
     const content = await browser.eval(
       `document.querySelector('#content').innerText`
     )
+    process.env.BROWSER_NAME = temp
```
Comment (ijjk) [inline test/integration/react-streaming-and-server-components/test/rsc.js:129]:
```suggestion
```

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| buildDuration | 15.6s | 15.6s | ⚠️ +15ms |
| buildDurationCached | 6.2s | 6.2s | -19ms |
| nodeModulesSize | 477 MB | 477 MB | -5 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.212 | 3.202 | -0.01 |
| / avg req/sec | 778.42 | 780.8 | +2.38 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.406 | 1.394 | -0.01 |
| /error-in-render avg req/sec | 1778.25 | 1793.77 | +15.52 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.48 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.7 kB | 15.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| buildDuration | 18.4s | 18.6s | ⚠️ +160ms |
| buildDurationCached | 6.1s | 6.2s | ⚠️ +105ms |
| nodeModulesSize | 477 MB | 477 MB | -5 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.194 | 3.19 | 0 |
| / avg req/sec | 782.75 | 783.78 | +1.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.405 | 1.411 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1779.96 | 1772.02 | ⚠️ -7.94 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.59 kB | 5.59 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.8 kB | 15.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js firefox-transform-stream | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 5b74809c133230bd0412a5afca4f50b9a058ed24
