### PR TITLE
fix: NPM Workspace throws`ENOWORKSPACES` error when fetching registry

### LINKED ISSUE #47121: [NEXT-832] Dev Server NPM error code ENOWORKSPACES
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.6.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.3
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Dev server and NPM

### Link to the code that reproduces this issue

https://github.com/joepetrillo/workspace-issue

### To Reproduce

Clone the repo then `npm install` then `cd reproduction-app` then `npm run dev`

image

### Describe the Bug

**I have determined that this error happens when a nextjs (versions after 13.1.6) dev server runs in an npm workspace.**

`npm config get registry` is getting called sometime during the dev server startup and is throwing an error since it is not supported in workspaces. 

`error code ENOWORKSPACES`
`error This command does not support workspaces.`

I initially thought this could be a turborepo issue, but it is not. More details are in the issue I initially opened (linked below).

https://github.com/vercel/turbo/issues/4183

And here is a sample error log:

```
0 verbose cli /Users/jpetrillo/Library/Application Support/fnm/node-versions/v18.15.0/installation/bin/node /Users/jpetrillo/Library/Caches/fnm_multishells/18620_1678811038524/bin/npm
1 info using npm@9.6.1
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/Users/jpetrillo/Library/Application Support/fnm/node-versions/v18.15.0/installation/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 0ms
8 timing config:load:env Completed in 0ms
9 info found workspace root at /Users/jpetrillo/Documents/Projects/workspace-bug
10 timing config:load:file:/Users/jpetrillo/Documents/Projects/workspace-bug/.npmrc Completed in 0ms
11 timing config:load:project Completed in 3ms
12 timing config:load:file:/Users/jpetrillo/.npmrc Completed in 0ms
13 timing config:load:user Completed in 0ms
14 timing config:load:file:/Users/jpetrillo/Library/Application Support/fnm/node-versions/v18.15.0/installation/etc/npmrc Completed in 0ms
15 timing config:load:global Completed in 0ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 5ms
18 timing npm:load:configload Completed in 5ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm config get registry
22 verbose argv "config" "get" "registry"
23 timing npm:load:setTitle Completed in 5ms
24 timing config:load:flatten Completed in 1ms
25 timing npm:load:display Completed in 1ms
26 verbose logfile logs-max:10 dir:/Users/jpetrillo/.npm/_logs/2023-03-14T16_37_32_128Z-
27 verbose logfile /Users/jpetrillo/.npm/_logs/2023-03-14T16_37_32_128Z-debug-0.log
28 timing npm:load:logFile Completed in 2ms
29 timing npm:load:timers Completed in 0ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 15ms
32 timing command:config Completed in 0ms
33 verbose stack Error: This command does not support workspaces.
33 verbose stack     at Config.cmdExec (/Users/jpetrillo/Library/Application Support/fnm/node-versions/v18.15.0/installation/lib/node_modules/npm/lib/base-command.js:123:29)
33 verbose stack     at Npm.exec (/Users/jpetrillo/Library/Application Support/fnm/node-versions/v18.15.0/installation/lib/node_modules/npm/lib/npm.js:154:20)
33 verbose stack     at async module.exports (/Users/jpetrillo/Library/Application Support/fnm/node-versions/v18.15.0/installation/lib/node_modules/npm/lib/cli.js:134:5)
34 verbose cwd /Users/jpetrillo/Documents/Projects/workspace-bug/reproduction-app
35 verbose Darwin 22.2.0
36 verbose node v18.15.0
37 verbose npm  v9.6.1
38 error code ENOWORKSPACES
39 error This command does not support workspaces.
40 verbose exit 1
41 timing npm Completed in 21ms
42 verbose code 1
43 error A complete log of this run can be found in:
43 error     /Users/jpetrillo/.npm/_logs/2023-03-14T16_37_32_128Z-debug-0.log
```

### Expected Behavior

No error

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

<sub>[NEXT-832](https://linear.app/vercel/issue/NEXT-832/dev-server-npm-error-code-enoworkspaces)</sub>

### PR DESCRIPTION
**Pull request by devjiwonchoi**
### Why?

This issue occurs when a project is NPM Workspace, and has no other package managers but NPM is installed.

Next.js runs [npm config get registry](https://github.com/vercel/next.js/blob/e35710f71f8e0f2844add1a97513a65a54a6f2a3/packages/next/src/lib/helpers/get-registry.ts#L13) to fetch the registry.
However, running `npm config get registry` at a NPM Workspace is not allowed resulting a `ENOWORKSPACES` error.

```
$ npm config get registry  
npm error code ENOWORKSPACES
npm error This command does not support workspaces.
```

As we didn't consume the error, it threw when the enabled `next telemetry` [triggered getVersionInfo](https://github.com/vercel/next.js/blame/fb2d2dd01a5f73ac62c4809b7b9c1490617f8705/packages/next/src/server/dev/hot-reloader-webpack.ts#L725-L728) calling `getRegistry` which threw as above.

### How?

Add `--no-workspaces` flag when the pkgManager is `'npm'`.
It is safe for non-workspace projects as it's equivalent to default `--workspaces=false`.

Fixes #47121
Fixes NEXT-832
Fixes NDX-150

### CODE REVIEW

**Comment by devjiwonchoi** [comment]
* **#68522** <a href="https://app.graphite.dev/github/pr/vercel/next.js/68522?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @devjiwonchoi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by eps1lon — CHANGES_REQUESTED** [review]
We should only swallow where we expect the error. We expect it in a very specific situation according to the PR desc so we should only swallow in those.

We should never swallow any error. There might be other runtime errors in here.

**Comment by eps1lon** [comment]
Shouldn't we instead use a separate function that ignores the npm config and use that in the specific instance were we errored? Silently ignoring the config will be hard to debug if we ignore the registry in a place where we shouldn't.

It's important to be very accurate here because regressions may remain undetected until months later somebody realizes some download is taking longer because we stopped using the configured registry.

File: packages/next/src/lib/helpers/get-registry.ts [hunk 1]
```diff
@@ -8,22 +8,38 @@ import { getFormattedNodeOptionsWithoutInspect } from '../../server/lib/utils'
...
 
     if (output.startsWith('http')) {
       registry = output.endsWith('/') ? output : `${output}/`
     }
-  } finally {
-    return registry
+  } catch (err) {
+    if (err instanceof Error) {
+      throw new Error(
+        `Failed to get registry from "${pkgManager}".\n\n${err.message}`
```
Comment (devjiwonchoi) [inline packages/next/src/lib/helpers/get-registry.ts:39]: Screenshot 2024-08-06 at 4 47 59 PM

**Comment by devjiwonchoi** [comment]
@eps1lon What do you think of passing `--no-workspace` for non-workspaces?
I could just nest it down to the `catch` and add only if `ENOWORKSPACES` error.

File: packages/next/src/lib/helpers/get-registry.ts [hunk 2]
```diff
@@ -8,22 +8,38 @@ import { getFormattedNodeOptionsWithoutInspect } from '../../server/lib/utils'
...
+      )
+    }
```
Comment (eps1lon) [inline packages/next/src/lib/helpers/get-registry.ts:41]: Can we start using `cause` i.e. `throw new Error(`your message here`, { cause: error })`? This'll also make sure we handle the cases where non-errors are thrown.

File: packages/next/src/lib/helpers/get-registry.ts [hunk 3]
```diff
@@ -8,22 +8,38 @@ import { getFormattedNodeOptionsWithoutInspect } from '../../server/lib/utils'
...
       .toString()
       .trim()
 
     if (output.startsWith('http')) {
       registry = output.endsWith('/') ? output : `${output}/`
     }
-  } finally {
-    return registry
+  } catch (err) {
+    if (err instanceof Error) {
```
Comment (eps1lon) [inline packages/next/src/lib/helpers/get-registry.ts:37]: why is this check still needed?

File: packages/next/src/lib/helpers/get-registry.ts [hunk 4]
```diff
@@ -8,22 +8,38 @@ import { getFormattedNodeOptionsWithoutInspect } from '../../server/lib/utils'
  * @default https://registry.npmjs.org/
  */
 export function getRegistry(baseDir: string = process.cwd()) {
+  const pkgManager = getPkgManager(baseDir)
+  // Since `npm config` command fails in npm workspace to prevent workspace config conflicts,
+  // add `--no-workspaces` flag to run under the context of the root project only.
+  // Safe for non-workspace projects as it's equivalent to default `--workspaces=false`.
+  // x-ref: https://github.com/vercel/next.js/issues/47121#issuecomment-1499044345
+  // x-ref: https://github.com/npm/statusboard/issues/371#issue-920669998
```
Comment (eps1lon) [inline packages/next/src/lib/helpers/get-registry.ts:16]: New implementation has way more confidence given the explainer. This is valueable context, thank you!

File: packages/next/src/lib/helpers/get-registry.ts (hunk 3 above)
Comment (devjiwonchoi) [reply packages/next/src/lib/helpers/get-registry.ts:37]: should be removed..

**Review by eps1lon — APPROVED** [review]
