### PR TITLE
CNA: Add warning about permission

### LINKED ISSUE #14744: Cannot execute create-next-app because of permission
# Bug report

## Describe the bug

Cannot execute create-next-app in`/User`(Not Allowed) because of **permission**.

## To Reproduc

1. Go to `/Users`
2. `npx create-next-app --example hello-world hello-world-app` (any example)
3. See error

## Expected behavior

Explicitly indicate that the error is due to permission.

## Screenshots

console

## System information

- OS: macOS
- Version of Node.js: 12.7.0

## Additional context

An example of npm

```
npm ERR! path /Users/package.json
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
npm ERR! Error: EACCES: permission denied, open '/Users/package.json'
npm ERR!  [Error: EACCES: permission denied, open '/Users/package.json'] {
npm ERR!   stack: "Error: EACCES: permission denied, open '/Users/package.json'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/Users/package.json'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
```

### PR DESCRIPTION
**Pull request by matamatanot**
close #14744

screen_shot

I have some concerns.

- `import { isWriteable } from '../next/build/is-writeable'` **not** from `create-next-app ` package.
- The warning sentence is from npm. Not for Next.js. I'm not a native English speaker. I'd like to know the natural expression for this.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 10.2s | 10.5s | ⚠️ +278ms |
| nodeModulesSize | 66.1 MB | 66.1 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.701 | 1.661 | -0.04 |
| / avg req/sec | 1469.8 | 1505.12 | +35.32 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.027 | 0.978 | -0.05 |
| /error-in-render avg req/sec | 2433.52 | 2557.34 | +123.82 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..6834.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| index.html gzip | 953 B | 953 B | ✓ |
| link.html gzip | 959 B | 959 B | ✓ |
| withRouter.html gzip | 945 B | 945 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 11.1s | 11s | -103ms |
| nodeModulesSize | 66.1 MB | 66.1 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..6834.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 876 kB | 876 kB | ✓ |
| link.js | 915 kB | 915 kB | ✓ |
| routerDirect.js | 908 kB | 908 kB | ✓ |
| withRouter.js | 908 kB | 908 kB | ✓ |
| Overall change | 4.49 MB | 4.49 MB | ✓ |

</details>

</details>
Commit: 449d2fd85978473604456cd96b82729f71e37926

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 449d2fd85978473604456cd96b82729f71e37926

**test/integration/create-next-app/index.test.js** 
- create next app > empty directory
- create next app > valid example
- create next app > should allow example with GitHub URL
- create next app > should allow example with GitHub URL and example-path
- create next app > should use --example-path over the file path in the GitHub URL
- create next app > should fall back to default template
- create next app > should allow an example named default

<details>
<summary>Expand output</summary>

  ● create next app › empty directory

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js empty-directory

      58 |       await usingTempDir(async (cwd) => {
      59 |         const projectName = 'empty-directory'
    > 60 |         const res = await runStarter(cwd, projectName)
         |                     ^
      61 | 
      62 |         expect(res.exitCode).toBe(0)
      63 |         expect(

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:60:21
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:58:7)

  ● create next app › valid example

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js valid-example --example basic-css

      90 |     await usingTempDir(async (cwd) => {
      91 |       const projectName = 'valid-example'
    > 92 |       const res = await run(cwd, projectName, '--example', 'basic-css')
         |                   ^
      93 |       expect(res.exitCode).toBe(0)
      94 | 
      95 |       expect(

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:92:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:90:5)

  ● create next app › should allow example with GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-app --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages

      109 |     await usingTempDir(async (cwd) => {
      110 |       const projectName = 'github-app'
    > 111 |       const res = await run(
          |                   ^
      112 |         cwd,
      113 |         projectName,
      114 |         '--example',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:111:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:109:5)

  ● create next app › should allow example with GitHub URL and example-path

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path --example https://github.com/zeit/next-learn-demo/tree/master --example-path 1-navigate-between-pages

      135 |     await usingTempDir(async (cwd) => {
      136 |       const projectName = 'github-example-path'
    > 137 |       const res = await run(
          |                   ^
      138 |         cwd,
      139 |         projectName,
      140 |         '--example',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:137:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:135:5)

  ● create next app › should use --example-path over the file path in the GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path-2 --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages --example-path 1-navigate-between-pages

      163 |     await usingTempDir(async (cwd) => {
      164 |       const projectName = 'github-example-path-2'
    > 165 |       const res = await run(
          |                   ^
      166 |         cwd,
      167 |         projectName,
      168 |         '--example',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:165:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:163:5)

  ● create next app › should fall back to default template

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js fail-example --example __internal-testing-retry

      212 |         }
      213 | 
    > 214 |         const res = await runExample(
          |                     ^
      215 |           'fail-example',
      216 |           '--example',
      217 |           '__internal-testing-retry'

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:214:21
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:194:7)

  ● create next app › should allow an example named default

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js default-example --example default

      225 |     await usingTempDir(async (cwd) => {
      226 |       const projectName = 'default-example'
    > 227 |       const res = await run(cwd, projectName, '--example', 'default')
          |                   ^
      228 |       expect(res.exitCode).toBe(0)
      229 | 
      230 |       expect(

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:227:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:225:5)

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 9cc28843ac67ef37bf603e0cec43652262004ea5

**test/integration/create-next-app/index.test.js** 
- create next app > empty directory
- create next app > valid example
- create next app > should allow example with GitHub URL
- create next app > should allow example with GitHub URL and example-path
- create next app > should use --example-path over the file path in the GitHub URL
- create next app > should fall back to default template
- create next app > should allow an example named default

<details>
<summary>Expand output</summary>

  ● create next app › empty directory

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js empty-directory

      58 |       await usingTempDir(async (cwd) => {
      59 |         const projectName = 'empty-directory'
    > 60 |         const res = await runStarter(cwd, projectName)
         |                     ^
      61 | 
      62 |         expect(res.exitCode).toBe(0)
      63 |         expect(

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:60:21
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:58:7)

  ● create next app › valid example

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js valid-example --example basic-css

      90 |     await usingTempDir(async (cwd) => {
      91 |       const projectName = 'valid-example'
    > 92 |       const res = await run(cwd, projectName, '--example', 'basic-css')
         |                   ^
      93 |       expect(res.exitCode).toBe(0)
      94 | 
      95 |       expect(

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:92:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:90:5)

  ● create next app › should allow example with GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-app --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages

      109 |     await usingTempDir(async (cwd) => {
      110 |       const projectName = 'github-app'
    > 111 |       const res = await run(
          |                   ^
      112 |         cwd,
      113 |         projectName,
      114 |         '--example',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:111:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:109:5)

  ● create next app › should allow example with GitHub URL and example-path

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path --example https://github.com/zeit/next-learn-demo/tree/master --example-path 1-navigate-between-pages

      135 |     await usingTempDir(async (cwd) => {
      136 |       const projectName = 'github-example-path'
    > 137 |       const res = await run(
          |                   ^
      138 |         cwd,
      139 |         projectName,
      140 |         '--example',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:137:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:135:5)

  ● create next app › should use --example-path over the file path in the GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path-2 --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages --example-path 1-navigate-between-pages

      163 |     await usingTempDir(async (cwd) => {
      164 |       const projectName = 'github-example-path-2'
    > 165 |       const res = await run(
          |                   ^
      166 |         cwd,
      167 |         projectName,
      168 |         '--example',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:165:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:163:5)

  ● create next app › should fall back to default template

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js fail-example --example __internal-testing-retry

      212 |         }
      213 | 
    > 214 |         const res = await runExample(
          |                     ^
      215 |           'fail-example',
      216 |           '--example',
      217 |           '__internal-testing-retry'

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:214:21
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:194:7)

  ● create next app › should allow an example named default

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js default-example --example default

      225 |     await usingTempDir(async (cwd) => {
      226 |       const projectName = 'default-example'
    > 227 |       const res = await run(cwd, projectName, '--example', 'default')
          |                   ^
      228 |       expect(res.exitCode).toBe(0)
      229 | 
      230 |       expect(

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:227:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:225:5)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 10.2s | 10.3s | ⚠️ +165ms |
| nodeModulesSize | 57.6 MB | 57.6 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.894 | 1.89 | 0 |
| / avg req/sec | 1319.72 | 1323.04 | +3.32 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.04 | 1.071 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2403.97 | 2334.52 | ⚠️ -69.45 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..4e55.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1ea360d..8d32.js gzip | 7.16 kB | 7.16 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.1 kB | 57.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.11 kB | 6.11 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-ece3b39..dule.js gzip | 6.18 kB | 6.18 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52 kB | 52 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| index.html gzip | 947 B | 947 B | ✓ |
| link.html gzip | 952 B | 952 B | ✓ |
| withRouter.html gzip | 938 B | 938 B | ✓ |
| Overall change | 2.84 kB | 2.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 11.7s | 11.6s | -101ms |
| nodeModulesSize | 57.6 MB | 57.6 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..4e55.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1ea360d..8d32.js gzip | 7.16 kB | 7.16 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.1 kB | 57.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.11 kB | 6.11 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-ece3b39..dule.js gzip | 6.18 kB | 6.18 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52 kB | 52 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _error.js | 1.03 MB | 1.03 MB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.82 kB | 3.82 kB | ✓ |
| index.js | 1.03 MB | 1.03 MB | ✓ |
| link.js | 1.07 MB | 1.07 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.27 MB | 5.27 MB | ✓ |

</details>

</details>
Commit: 9cc28843ac67ef37bf603e0cec43652262004ea5

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 530b91c48294ea523dfe2823d5dd8deae4c32faa

**test/integration/create-next-app/index.test.js** 
- create next app > empty directory
- create next app > valid example
- create next app > should allow example with GitHub URL
- create next app > should allow example with GitHub URL and example-path
- create next app > should use --example-path over the file path in the GitHub URL
- create next app > should fall back to default template
- create next app > should allow an example named default

<details>
<summary>Expand output</summary>

  ● create next app › empty directory

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js empty-directory

      58 |       await usingTempDir(async (cwd) => {
      59 |         const projectName = 'empty-directory'
    > 60 |         const res = await runStarter(cwd, projectName)
         |                     ^
      61 | 
      62 |         expect(res.exitCode).toBe(0)
      63 |         expect(

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:60:21
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:58:7)

  ● create next app › valid example

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js valid-example --example basic-css

      90 |     await usingTempDir(async (cwd) => {
      91 |       const projectName = 'valid-example'
    > 92 |       const res = await run(cwd, projectName, '--example', 'basic-css')
         |                   ^
      93 |       expect(res.exitCode).toBe(0)
      94 | 
      95 |       expect(

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:92:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:90:5)

  ● create next app › should allow example with GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-app --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages

      109 |     await usingTempDir(async (cwd) => {
      110 |       const projectName = 'github-app'
    > 111 |       const res = await run(
          |                   ^
      112 |         cwd,
      113 |         projectName,
      114 |         '--example',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:111:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:109:5)

  ● create next app › should allow example with GitHub URL and example-path

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path --example https://github.com/zeit/next-learn-demo/tree/master --example-path 1-navigate-between-pages

      135 |     await usingTempDir(async (cwd) => {
      136 |       const projectName = 'github-example-path'
    > 137 |       const res = await run(
          |                   ^
      138 |         cwd,
      139 |         projectName,
      140 |         '--example',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:137:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:135:5)

  ● create next app › should use --example-path over the file path in the GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path-2 --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages --example-path 1-navigate-between-pages

      163 |     await usingTempDir(async (cwd) => {
      164 |       const projectName = 'github-example-path-2'
    > 165 |       const res = await run(
          |                   ^
      166 |         cwd,
      167 |         projectName,
      168 |         '--example',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:165:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:163:5)

  ● create next app › should fall back to default template

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js fail-example --example __internal-testing-retry

      212 |         }
      213 | 
    > 214 |         const res = await runExample(
          |                     ^
      215 |           'fail-example',
      216 |           '--example',
      217 |           '__internal-testing-retry'

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:214:21
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:194:7)

  ● create next app › should allow an example named default

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js default-example --example default

      225 |     await usingTempDir(async (cwd) => {
      226 |       const projectName = 'default-example'
    > 227 |       const res = await run(cwd, projectName, '--example', 'default')
          |                   ^
      228 |       expect(res.exitCode).toBe(0)
      229 | 
      230 |       expect(

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/create-next-app/index.test.js:227:19
      at usingTempDir (integration/create-next-app/index.test.js:30:12)
      at Object.<anonymous> (integration/create-next-app/index.test.js:225:5)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 10.2s | 10.1s | -105ms |
| nodeModulesSize | 57.6 MB | 57.6 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.82 | 1.853 | ⚠️ +0.03 |
| / avg req/sec | 1373.87 | 1348.94 | ⚠️ -24.93 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.018 | 1.022 | 0 |
| /error-in-render avg req/sec | 2455.07 | 2445.54 | ⚠️ -9.53 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..4e55.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1ea360d..8d32.js gzip | 7.16 kB | 7.16 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.1 kB | 57.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.11 kB | 6.11 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-ece3b39..dule.js gzip | 6.18 kB | 6.18 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52 kB | 52 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| index.html gzip | 947 B | 947 B | ✓ |
| link.html gzip | 952 B | 952 B | ✓ |
| withRouter.html gzip | 938 B | 938 B | ✓ |
| Overall change | 2.84 kB | 2.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.5s | ⚠️ +66ms |
| nodeModulesSize | 57.6 MB | 57.6 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..4e55.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1ea360d..8d32.js gzip | 7.16 kB | 7.16 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.1 kB | 57.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.11 kB | 6.11 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-ece3b39..dule.js gzip | 6.18 kB | 6.18 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52 kB | 52 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _error.js | 1.03 MB | 1.03 MB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.82 kB | 3.82 kB | ✓ |
| index.js | 1.03 MB | 1.03 MB | ✓ |
| link.js | 1.07 MB | 1.07 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.27 MB | 5.27 MB | ✓ |

</details>

</details>
Commit: 530b91c48294ea523dfe2823d5dd8deae4c32faa

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 9.8s | 9.9s | ⚠️ +154ms |
| nodeModulesSize | 57.7 MB | 57.7 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.808 | 1.863 | ⚠️ +0.05 |
| / avg req/sec | 1382.95 | 1342.26 | ⚠️ -40.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.019 | 1.072 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 2454.45 | 2331.91 | ⚠️ -122.54 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..4e55.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-8da9cf5..55dc.js gzip | 7.18 kB | 7.18 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.1 kB | 57.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.11 kB | 6.11 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-e458620..dule.js gzip | 6.2 kB | 6.2 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52 kB | 52 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| index.html gzip | 947 B | 947 B | ✓ |
| link.html gzip | 953 B | 953 B | ✓ |
| withRouter.html gzip | 938 B | 938 B | ✓ |
| Overall change | 2.84 kB | 2.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 11.1s | 11.6s | ⚠️ +500ms |
| nodeModulesSize | 57.7 MB | 57.7 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..4e55.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-8da9cf5..55dc.js gzip | 7.18 kB | 7.18 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.1 kB | 57.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.11 kB | 6.11 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-e458620..dule.js gzip | 6.2 kB | 6.2 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52 kB | 52 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _error.js | 1.03 MB | 1.03 MB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.82 kB | 3.82 kB | ✓ |
| index.js | 1.03 MB | 1.03 MB | ✓ |
| link.js | 1.07 MB | 1.07 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.27 MB | 5.27 MB | ✓ |

</details>

</details>
Commit: 2d5e18e3dcbdf2e4723c67b92d16e9093b01adc7

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.8s | -23ms |
| nodeModulesSize | 57.7 MB | 57.7 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.413 | 2.445 | ⚠️ +0.03 |
| / avg req/sec | 1035.92 | 1022.48 | ⚠️ -13.44 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.451 | 1.486 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1722.84 | 1682.68 | ⚠️ -40.16 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..4e55.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-8da9cf5..55dc.js gzip | 7.18 kB | 7.18 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.1 kB | 57.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.11 kB | 6.11 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-e458620..dule.js gzip | 6.2 kB | 6.2 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52 kB | 52 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| index.html gzip | 947 B | 947 B | ✓ |
| link.html gzip | 953 B | 953 B | ✓ |
| withRouter.html gzip | 938 B | 938 B | ✓ |
| Overall change | 2.84 kB | 2.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 14.6s | 14.3s | -335ms |
| nodeModulesSize | 57.7 MB | 57.7 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..4e55.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-8da9cf5..55dc.js gzip | 7.18 kB | 7.18 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.1 kB | 57.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.11 kB | 6.11 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-e458620..dule.js gzip | 6.2 kB | 6.2 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52 kB | 52 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _error.js | 1.03 MB | 1.03 MB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.82 kB | 3.82 kB | ✓ |
| index.js | 1.03 MB | 1.03 MB | ✓ |
| link.js | 1.07 MB | 1.07 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.27 MB | 5.27 MB | ✓ |

</details>

</details>
Commit: 5f46a0121f232c7d1257d89b3bb2f95bfcbea550

**Review by lfades — COMMENTED** [review]
Hi @matamatanot Thank you for the PR and sorry for the late review, it was missing some changes and tests

@ijjk @Timer Could one of you do a review of the PR 🙏 . I updated it and I shouldn't review my own changes.

File: packages/create-next-app/create-app.ts [hunk 1]
```diff
@@ -93,6 +94,15 @@ export async function createApp({
   }
 
   const root = path.resolve(appPath)
+
+  if (!(await isWriteable(path.dirname(root)))) {
+    console.error('The operation was rejected by your operating system.')
```
Comment (ijjk) [inline packages/create-next-app/create-app.ts:99]:
```suggestion
    console.error('The application path is not writable, please check folder permissions and try again.')
```
Should we be more descriptive here and suggest what they need to check, maybe something like this?

File: packages/create-next-app/create-app.ts [hunk 2]
```diff
@@ -93,6 +94,15 @@ export async function createApp({
...
+    console.error(
+      'It is likely you do not have write permissions for this folder as the current user'
```
Comment (ijjk) [inline packages/create-next-app/create-app.ts:101]: Not sure we want to mention "as the current user" this might inadvertently suggest they elevate privileges to admin/root since it mentions lacking permission 🤔

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.4s | -136ms |
| nodeModulesSize | 57.7 MB | 57.7 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.242 | 2.252 | ⚠️ +0.01 |
| / avg req/sec | 1115.08 | 1110.07 | ⚠️ -5.01 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.316 | 1.247 | -0.07 |
| /error-in-render avg req/sec | 1900.17 | 2004.61 | +104.44 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..4e55.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-512d5b9..081a.js gzip | 7.2 kB | 7.2 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.11 kB | 6.11 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-1203ff1..dule.js gzip | 6.21 kB | 6.21 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52 kB | 52 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| index.html gzip | 949 B | 949 B | ✓ |
| link.html gzip | 955 B | 955 B | ✓ |
| withRouter.html gzip | 940 B | 940 B | ✓ |
| Overall change | 2.84 kB | 2.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 14.3s | 13.7s | -590ms |
| nodeModulesSize | 57.7 MB | 57.7 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..4e55.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-512d5b9..081a.js gzip | 7.2 kB | 7.2 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.11 kB | 6.11 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-1203ff1..dule.js gzip | 6.21 kB | 6.21 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52 kB | 52 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _error.js | 1.03 MB | 1.03 MB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.82 kB | 3.82 kB | ✓ |
| index.js | 1.03 MB | 1.03 MB | ✓ |
| link.js | 1.07 MB | 1.07 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.27 MB | 5.27 MB | ✓ |

</details>

</details>
Commit: e5479a7d6ad772966421e80b72ef0463d16941a2

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 12.2s | 12.5s | ⚠️ +267ms |
| nodeModulesSize | 57.7 MB | 57.7 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.24 | 2.241 | 0 |
| / avg req/sec | 1116.22 | 1115.78 | ⚠️ -0.44 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.231 | 1.207 | -0.02 |
| /error-in-render avg req/sec | 2030.5 | 2071.2 | +40.7 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..4e55.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-512d5b9..081a.js gzip | 7.2 kB | 7.2 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.11 kB | 6.11 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-1203ff1..dule.js gzip | 6.21 kB | 6.21 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52 kB | 52 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| index.html gzip | 949 B | 949 B | ✓ |
| link.html gzip | 955 B | 955 B | ✓ |
| withRouter.html gzip | 940 B | 940 B | ✓ |
| Overall change | 2.84 kB | 2.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| buildDuration | 13.9s | 14s | ⚠️ +118ms |
| nodeModulesSize | 57.7 MB | 57.7 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..4e55.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-512d5b9..081a.js gzip | 7.2 kB | 7.2 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.11 kB | 6.11 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-1203ff1..dule.js gzip | 6.21 kB | 6.21 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52 kB | 52 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js cna-warning-permission | Change |
| - | - | - | - |
| _error.js | 1.03 MB | 1.03 MB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.82 kB | 3.82 kB | ✓ |
| index.js | 1.03 MB | 1.03 MB | ✓ |
| link.js | 1.07 MB | 1.07 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.27 MB | 5.27 MB | ✓ |

</details>

</details>
Commit: 896f7b19b503cf3e97dc5f7efded58d36a0ec062
