### PR TITLE
speeds O(n^2) execution of detectConflictingPaths

### LINKED ISSUE #46079: Slow detectConflictingPaths causes Error: Static page generation for <PATH> is still timing out after 3 attempts
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64
    Binaries:
      Node: 19.6.0
      npm: 9.4.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.3.1
      eslint-config-next: 12.3.1
      react: 17.0.2
      react-dom: 17.0.2
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

* CLI (create-next-app) `next build`

### Link to the code that reproduces this issue

https://github.com/0xadada/nextjs-detect-conflicts-slow

### To Reproduce

create a site that returns 200,000 dynamically generated pages

```javascript
// pages/[id].js
export const getStaticPaths = async () => {
  paths = [...(new Array(200000))].map((_i, x) => ({ params: { id: x }}))
  return {
    paths,
    fallback: false,
  };
};
```

`next build` will take a long time ~`1h 20m`, and eventually stop responding.

### Describe the Bug

During the build process, a Next app builds an array of paths for all of its pages, a [function called `detectConflictingPaths`](https://github.com/vercel/next.js/blob/canary/packages/next/src/build/utils.ts#L1558-L1590) iterates over those paths and checks for conflicts that would result in duplicate paths. If any conflicts are detected, it throws an error `Conflicting paths returned from getStaticPaths, paths must be unique per page` and exits the process.

During the build process, the CLI progress indicator reports "Collecting page data ..."

This function gets exponentially slower as the paths array increases:

- 100 paths `0.002461s`
- 200 paths `0.006019s`
- 400 paths `0.020899s`
- 800 paths `0.062096s`
- 1600 paths `0.224554s`
- 3200 paths `0.874216s`
- 6400 paths `3.370s`
- 12800 paths `14.280s` 💥 at this size, the CLI progress indicator stopped working
- 25600 paths `60.795s`
- 51200 paths `4m 01.98s`
- 102,400 paths  `14m 10.272`
- 204,800 paths `1.6h`

### Expected Behavior

`detectConflictingPaths` should not take more than a second to run.

### Which browser are you using? (if relevant)

irrelevant

### How are you deploying your application? (if relevant)

next build && next export

### PR DESCRIPTION
**Pull request by 0xadada**
## Bug

- [x] Related issues linked using `fixes #46079` https://github.com/vercel/next.js/issues/46079
- [ ] Integration tests added
- [ ] Errors have a helpful link attached, see [`contributing.md`](https://github.com/vercel/next.js/blob/canary/contributing.md)

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] [e2e](https://github.com/vercel/next.js/blob/canary/contributing/core/testing.md#writing-tests-for-nextjs) tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have a helpful link attached, see [`contributing.md`](https://github.com/vercel/next.js/blob/canary/contributing.md)

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm build && pnpm lint`
- [ ] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

### CODE REVIEW

File: packages/next/src/build/utils.ts [hunk 1]
```diff
@@ -1573,9 +1582,7 @@ export function detectConflictingPaths(
         conflictingPage = dynamicSsgPages.find((page) => {
           if (page === pathsPage) return false
 
-          conflictingPath = additionalSsgPaths
-            .get(page)
-            ?.find((compPath) => compPath.toLowerCase() === lowerPath)
```
Comment (0xadada) [inline packages/next/src/build/utils.ts:1578]: this `?.find(...)...` is an array search _within_ an array search, in sites with hundreds of thousands of paths, this becomes a huge problem.

File: packages/next/src/build/utils.ts [hunk 2]
```diff
@@ -1554,6 +1554,15 @@ export function detectConflictingPaths(
...
   const dynamicSsgPages = [...ssgPages].filter((page) => isDynamicRoute(page))
+  const additionalSsgPathsByPath: {[key: string]: {[key: string]: string}} = {};
+
+  additionalSsgPaths.forEach((paths, pathsPage)=>{
+    additionalSsgPathsByPath[pathsPage] ||= {};
+    paths.forEach((curPath)=>{
+      const currentPath = curPath.toLowerCase();
+      additionalSsgPathsByPath[pathsPage][currentPath] = curPath;
+    });
+  });
```
Comment (0xadada) [inline packages/next/src/build/utils.ts:1565]: instead of a `[].find(x => x.find())` (see comment below),  we first create a lookup-table of routes that contain full paths. This lets us get O(1) lookup speeds inside the surrounding `dynamicSsgPages.find()` search, dramatically increasing the performance of this function when sites have hundreds of thousands of paths.

**Review by shuding — DISMISSED** [review]
Great fix, thank you!

File: packages/next/src/build/utils.ts (hunk 2 above)
Comment (shuding) [reply packages/next/src/build/utils.ts:1565]: You probably need to fix some lint errors here.

Comment (0xadada) [reply packages/next/src/build/utils.ts]: @shuding should be fixed in https://github.com/vercel/next.js/pull/46080/commits/3582b66e180f2484b7efefc1d5ff127192c7a5b0

**Comment by 0xadada** [comment]
@ijjk this touches code you most recently changed, so i'd appreciate your opinion.

What do i need to do/read to back-port this to next.js v12 as a hotfix?

**Comment by shuding** [comment]
@0xadada curious to know what's blocking you from upgrading to v13?

**Review by ijjk — APPROVED** [review]
Looks good, thanks!
