### PR TITLE
[example] Fix fast refresh in with-slate example

### LINKED ISSUE #29740: with-slate: Unhandled Runtime Error Error: Cannot find a descendant at path [0] in node
### What example does this report relate to?

with-slate

### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.15.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

npm run dev

### Describe the Bug

Example throws a runtime error occurs upon hot reload

`Unhandled Runtime Error`
`Error: Cannot find a descendant at path [0] in node: {"children":[],"operations":[],"selection":null,"marks":null,"history":{"undos":[],"redos":[]}}`

image

### Expected Behavior

Should not have a runtime error upon hot reload

### To Reproduce

- `git clone git@github.com:vercel/next.js.git`
- `cd next.js/examples/with-slate`
- `npm i`
- `npm run dev`
- view http://localhost:3000 in Chrome
- trigger a hot reload by making some change to index.js (like adding whitespace) and saving the file
- observe a runtime error:
`Unhandled Runtime Error`
`Error: Cannot find a descendant at path [0] in node: {"children":[],"operations":[],"selection":null,"marks":null,"history":{"undos":[],"redos":[]}}`

image

### PR DESCRIPTION
**Pull request by HaNdTriX**
This PR fixes #29740 and updates the with-slate example to match slates latest version.

[more info](https://docs.slatejs.org/walkthroughs/01-installing-slate)

## Bug

- [x] Related issues linked using `fixes #number`

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

File: examples/with-slate/pages/index.js [hunk 1]
```diff
@@ -1,24 +1,21 @@
...
 
-const IndexPage = () => {
-  const [value, setValue] = useState(initialValue)
-  const editor = useMemo(() => withHistory(withReact(createEditor())), [])
+export default function IndexPage() {
+  const [editor] = useState(() => withReact(withHistory(createEditor())), [])
+  const [value, setValue] = useState([
+    {
+      children: [
+        { text: 'This is edidtable plain text, just like a <textarea>!' },
```
Comment (ijjk) [inline examples/with-slate/pages/index.js:11]:
```suggestion
        { text: 'This is editable plain text, just like a <textarea>!' },
```

**Review by ijjk — APPROVED** [review]
Thanks for the PR!
