### PR TITLE
Pass through arguments of the next cli correctly

### LINKED ISSUE #6263: Building a specific directory is broken in 8.0.0
# Bug report

## Describe the bug

`next build` is supposed to support an optional `<dir>` argument that specifies which directory will be built. In 8.0.0, that argument is ignored, and attempting to run a build with that argument specified will fail incorrectly.

## To Reproduce

Create a minimal Next.js project:
* `mkdir example && cd example`
* `npm init`, accept all defaults
* `npm install --save next react react-dom`
* `mkdir -p build/pages`
* `touch build/pages/index.js`
* Edit `build/pages/index.js` to include a minimum working page:
```jsx
function Home() {
  return <div>Welcome to next.js!</div>
}

export default Home
```

After creating this example, run `npx next build build` in the root of the `example` directory that was created. Observe the following output:

```
Couldn't find a `pages` directory. Please create one under the project root
```

## Expected behavior
In Next.js 7.0.3, running `npx next build build` with the above directory structure would build the site in `./build/.next/`. You can test this by running `npm i next@7.0.3` in the above example and then running `npx next build build`

## System information
 - OS: macOS
 - Browser: N/A
 - Version of Next.js: 8.0.0

## Additional context

I tried to do a little bit of debugging here. Adding `console.log(args)` right before https://github.com/zeit/next.js/blob/canary/packages/next/bin/next-build.ts#L29 shows that `args._` is an empty array, even with the `build` argument specified. It looks like this issue could somehow be caused by the switch to using the `arg` package, as v7.x used `minimist` instead.

### PR DESCRIPTION
**Pull request by timneutkens**
Arguments that held the same name as one of the default commands were filtered out, causing issues.

For example `next build build` would get rid of the second `build` parameter.

Fixes #6263

### CODE REVIEW

File: packages/next/bin/next.ts [hunk 1]
```diff
@@ -73,8 +73,10 @@ if (args['--inspect']) {
   nodeArguments.push('--inspect')
 }
 
-const command = foundCommand || defaultCommand
-const forwardedArgs = args._.filter((arg) => arg !== command)
+const command = foundCommand ? args._[0] : defaultCommand
+const forwardedArgs = foundCommand ? args._.slice(1) : args._
+
+console.log({command, foundCommand, forwardedArgs})
```
Comment (Timer) [inline packages/next/bin/next.ts]: ❌

Comment (timneutkens) [reply packages/next/bin/next.ts]:
```suggestion
```

File: packages/next/bin/next.ts [hunk 2]
```diff
@@ -73,8 +73,9 @@ if (args['--inspect']) {
   nodeArguments.push('--inspect')
 }
 
-const command = foundCommand || defaultCommand
-const forwardedArgs = args._.filter((arg) => arg !== command)
+const command = foundCommand ? args._[0] : defaultCommand
+const forwardedArgs = foundCommand ? args._.slice(1) : args._
+
```
Comment (timneutkens) [inline packages/next/bin/next.ts]:
```suggestion
```

**Review by Timer — APPROVED** [review]
