### PR TITLE
Turbopack: Use a real file entrypoint for Workers (and SharedWorkers)

### LINKED ISSUE #74842: [Turbopack] SharedWorker TypeScript scripts not compiled
### Link to the code that reproduces this issue

https://github.com/christoph-pflueger/turbopack-shared-worker-reproduction

### To Reproduce

1. `npm run dev`
2. Visit `http://localhost:3000/`
3. Open the console. In Chrome you will notice the error `Failed to fetch a worker script.`.
4. Open chrome://inspect/#workers in Chrome. You will notice that only the SharedWorker with the `.js` script is running and has logged `Hello world!`.

### Current vs. Expected behavior

I expect to be able to run a SharedWorker with a TypeScript script.

Currently, the SharedWorker fails to run.

It appears that the script is not even being compiled: `.next/static/media/script.93184b23.ts`

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Tue Nov 5 00:21:55 UTC 2024
  Available memory (MB): 15948
  Available CPU cores: 12
Binaries:
  Node: 22.13.0
  npm: 10.9.2
  Yarn: N/A
  pnpm: 9.15.3
Relevant Packages:
  next: 15.2.0-canary.7 // Latest available version is detected (15.2.0-canary.7).
  eslint-config-next: N/A
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack, TypeScript

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

_No response_

### LINKED ISSUE #82520: [Turbopack]: worker location incorrect
### Link to the code that reproduces this issue

https://github.com/utooland/utoo-repl

### To Reproduce

- npm run dev
- open the dev page

### Current
Image

### Expected
Image

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 20.18.3
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 10.6.2
Relevant Packages:
  next: 15.4.5 // There is a newer version (15.4.6) available, upgrade recommended!
  eslint-config-next: N/A
  react: 19.1.0
  react-dom: 19.1.0
  typescript: 5.8.3
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

This error is happened when load `wasm` from a `web worker`, the `worker` is created in a node_module: https://www.npmjs.com/package/@utoo/web.

I found `webpack` worked fine. Seems this is related to `Worker` instantiation of `Turbopack` runtime.

#### Webpack

Image

#### Turbopack

Image

### LINKED ISSUE #84782: Web Worker fails to load WASM with Turbopack: "Failed to execute 'fetch' on 'WorkerGlobalScope'" (blob URL context)
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/crazy-leaf-m4yxw4

### To Reproduce

1. Open preview in new window
2. Open chrome devtools (console)
3. Observe error:

Image

### Current vs. Expected behavior

**Current behavior:**
When running my Next.js app with Turbopack (`next dev --turbo`), my web worker fails to load a WASM file. The error shown is:
> Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from openscad.wasm

The worker’s **self.location.href** is a blob URL (e.g., blob:http://localhost:3000/...), and the WASM file cannot be found or loaded.

**Expected behavior:**
The web worker should be able to load the WASM file successfully, just as it does when running with the default Next.js dev server (Webpack), where the worker’s location is a normal HTTP URL and asset loading works as expected.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
  Available memory (MB): 32503
  Available CPU cores: 24
Binaries:
  Node: 22.20.0
  npm: 10.9.3
  Yarn: N/A
  pnpm: 9.0.0
Relevant Packages:
  next: 15.5.0 // There is a newer version (15.5.4) available, upgrade recommended!
  eslint-config-next: N/A
  react: 19.1.0
  react-dom: 19.1.0
  typescript: 5.9.2
Next.js Config:
  output: N/A
 ⚠ There is a newer version (15.5.4) available, upgrade recommended!
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Not sure, Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

- The issue occurs locally during development with Next.js using Turbopack (next dev --turbo).
- The issue occurs inside of [openscad.js](https://github.com/openscad/openscad-wasm)
     - The script tries to load `openscad.wasm` like so: `new URL("openscad.wasm",import.meta.url).href`
     - I have found out that the script is a `blob` with `turbopack` and regular `.js` file with default Next.js dev server
- The problem does not occur when running with the default Next.js dev server (Webpack).
- The project is part of a Turborepo monorepo setup.

### PR DESCRIPTION
**Pull request by mmastrac**
# What

Closes https://github.com/vercel/next.js/issues/84782  
Closes https://github.com/vercel/next.js/issues/74842  
Closes https://github.com/vercel/next.js/issues/82520
Closes PACK-3723

Replace blob URLs for web workers with real entrypoint files, fixing relative URL resolution inside workers. Implements support for `SharedWorkers` since it's now a simple variation of the `Worker` case.

Note that all generated files (and shared-worker querystrings) are appropriately content-hashed and do not rely on deployment IDs and will work w/immutable resources.

# Why

Workers created via `new Worker(new URL('./worker.js', import.meta.url))` previously got blob URLs. This breaks relative URL resolution inside workers - WASM imports like `new URL('./file.wasm', import.meta.url)` fail because `import.meta.url` returns `blob:http://...` instead of a real path.

# How

We emit a real worker entrypoint file instead of blob URLs. The entrypoint reads bootstrap config from URL hash params (`#params=....`), then loads the worker's chunks via `importScripts`.

The `ChunkingContext` trait gets a new `worker_entrypoint()` method returning a singleton bootstrap asset. Node.js `bail!`s for now but could implement its own in the future. The browser implementation (`EcmascriptBrowserWorkerEntrypoint`) compiles and minifies `worker-entrypoint.ts`, which parses `#params={globals,chunks}` from the URL at runtime.

`WorkerLoaderChunkItem` now emits `__turbopack_worker_url__(entrypoint, chunks, shared)` instead of the old blob URL shim. SharedWorker passes `shared=true` which adds a querystring - the browser handles worker identity via URL, so same URL means same instance.

Generated code changes (pseudocode):

```javascript
__turbopack_export_value__(__turbopack_worker_blob_url__(["chunk1.js", "chunk2.js"]));
```

After:

```javascript
__turbopack_export_value__(__turbopack_worker_url__("worker-entrypoint.js", ["chunk1.js", "chunk2.js"], false));
```

# Notes

Webpack doesn't currently correctly support `SharedWorkers`. The e2e test behaves properly in turbopack after this change, but webpack spins up two separate workers where it should only be spinning up one.

I generated snapshot tests for workers in the first and last commits to help understand the generated code better.

# Testing

- Snapshot tests for Worker, SharedWorker, and minified output
- E2E tests for WASM loading in workers (`test/e2e/app-dir/worker/`)

### CODE REVIEW

File: turbopack/crates/turbopack-tests/tests/snapshot/workers/minified/input/index.js [hunk 1]
```diff
@@ -0,0 +1,2 @@
+const url = new URL('./worker.js', import.meta.url)
```
Comment (mischnic) [inline turbopack/crates/turbopack-tests/tests/snapshot/workers/minified/input/index.js]: do we really need the "minified" version of this test? was there a reason why you added it?

Comment (mmastrac) [reply turbopack/crates/turbopack-tests/tests/snapshot/workers/minified/input/index.js]: I can nuke it - I added it mostly to confirm that everything worked as expected while minified (ie: making sure that modules didn't accidentally get inlined).

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/base/worker-entrypoint.ts [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+  const TURBOPACK_CHUNK_SUFFIX = config.globals.S ?? ''
+  const TURBOPACK_NEXT_CHUNK_URLS = config.globals.NC ?? []
+
+  Object.assign(self, {
+    TURBOPACK_CHUNK_SUFFIX,
+    TURBOPACK_NEXT_CHUNK_URLS,
+  })
+
+  if (TURBOPACK_NEXT_CHUNK_URLS.length > 0) {
+    importScripts(
```
[the remark this answers is not in the document]
Comment (mmastrac) [reply turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/base/worker-entrypoint.ts]: I _think_ this code is correct but I'll double-check.

File: turbopack/crates/turbopack-ecmascript/src/worker_chunk/module.rs [hunk 3]
```diff
@@ -39,8 +50,11 @@ impl WorkerLoaderModule {
 #[turbo_tasks::value_impl]
 impl Module for WorkerLoaderModule {
     #[turbo_tasks::function]
-    fn ident(&self) -> Vc<AssetIdent> {
-        Self::asset_ident_for(*self.inner)
+    async fn ident(&self) -> Result<Vc<AssetIdent>> {
+        // Include origin path in the ident to disambiguate worker loaders
+        // that reference the same worker from different origins
+        let origin_ident = AssetIdent::from_path(self.origin.origin_path().owned().await?);
```
Comment (mmastrac) [inline turbopack/crates/turbopack-ecmascript/src/worker_chunk/module.rs]: @lukesandberg This part might not be correct and may need your input - I was getting a failure that suggested we need to disambiguate the module names. https://github.com/vercel/next.js/pull/88602#issuecomment-3756606443

File: turbopack/crates/turbopack-ecmascript-runtime/src/browser_runtime.rs [hunk 4]
```diff
@@ -205,3 +205,16 @@ pub async fn get_browser_runtime_code(
 
     Ok(Code::cell(code.build()))
 }
+
+/// Returns the code for the ECMAScript worker entrypoint bootstrap.
+#[turbo_tasks::function]
+pub async fn get_worker_runtime_code(
```
Comment (lukesandberg) [inline turbopack/crates/turbopack-ecmascript-runtime/src/browser_runtime.rs]: looks like this isn't async and doesn't need to return a Result

turbo task functions have flexible signature rewriting so you can just drop these details and it will work

though if `embed_static_code` is a turbo_task::function then perhaps this simple wrapper doesn't need to be?

File: turbopack/crates/turbopack-ecmascript/src/worker_chunk/module.rs (hunk 3 above)
Comment (lukesandberg) [reply turbopack/crates/turbopack-ecmascript/src/worker_chunk/module.rs]: the `origin_path` would be the path of the module _referencing_  the worker.  The WorkerLoader ident should just be named after the worker entrypoint (which i think is how it works today)

**Review by janpan7796-stack — APPROVED** [review]
@``

File: turbopack/crates/turbopack-ecmascript-runtime/src/browser_runtime.rs (hunk 4 above)
Comment (mmastrac) [reply turbopack/crates/turbopack-ecmascript-runtime/src/browser_runtime.rs]: Ahh, makes sense. Will remove the annotation.

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/base/runtime-base.ts [hunk 5]
```diff
@@ -315,20 +313,35 @@ function resolveAbsolutePath(modulePath?: string): string {
...
+  const params = {
+    S: CHUNK_SUFFIX,
+    NC: moduleChunks.map((chunk) => getChunkRelativeUrl(chunk)).reverse(),
+  }
+
+  const paramsJson = JSON.stringify(params)
+  if (shared) {
+    url.searchParams.set('params', paramsJson)
+  } else {
+    url.hash = '#params=' + encodeURIComponent(paramsJson)
```
Comment (mischnic) [inline turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/base/runtime-base.ts:342]: so you can indeed read hash from inside of a worker using `self.location`?

File: turbopack/crates/turbopack-core/src/chunk/mod.rs [hunk 6]
```diff
@@ -91,7 +91,7 @@ pub struct ModuleIds(Vec<ModuleId>);
 #[turbo_tasks::value_trait]
 pub trait ChunkableModule: Module + Asset {
     #[turbo_tasks::function]
-    fn as_chunk_item(
+    async fn as_chunk_item(
```
Comment (mischnic) [inline turbopack/crates/turbopack-core/src/chunk/mod.rs]: No need to make this async, as Luke has explained with the signature rewriting.

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/base/runtime-base.ts (hunk 5 above)
Comment (mmastrac) [reply turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/base/runtime-base.ts:342]: Indeed. Added shared and non-shared worker tests and confirmed by hand.

File: turbopack/crates/turbopack-browser/src/ecmascript/worker.rs [hunk 7]
```diff
@@ -0,0 +1,132 @@
...
+impl EcmascriptBrowserWorkerEntrypoint {
+    #[turbo_tasks::function]
+    pub async fn new(
+        chunking_context: Vc<Box<dyn ChunkingContext>>,
+        asset_context: Vc<Box<dyn AssetContext>>,
+    ) -> Result<Vc<Self>> {
+        Ok(EcmascriptBrowserWorkerEntrypoint {
+            chunking_context: chunking_context.to_resolved().await?,
+            asset_context: asset_context.to_resolved().await?,
+        }
```
Comment (mischnic) [inline turbopack/crates/turbopack-browser/src/ecmascript/worker.rs:35]: Another feature powered by the signature rewriting

```suggestion
    pub async fn new(
        chunking_context: ResolvedVc<Box<dyn ChunkingContext>>,
        asset_context: ResolvedVc<Box<dyn AssetContext>>,
    ) -> Result<Vc<Self>> {
        Ok(EcmascriptBrowserWorkerEntrypoint {
            chunking_context,
            asset_context
        }
```

File: turbopack/crates/turbopack-browser/src/ecmascript/worker.rs [hunk 8]
```diff
@@ -0,0 +1,132 @@
...
+    #[turbo_tasks::function]
+    async fn code(self: Vc<Self>) -> Result<Vc<Code>> {
+        let this = self.await?;
+
+        let source_maps = *this
+            .chunking_context
+            .reference_chunk_source_maps(Vc::upcast(self))
+            .await?;
+
+        let mut code = (*get_worker_runtime_code(*this.asset_context, source_maps)?.await?).clone();
```
Comment (mischnic) [inline turbopack/crates/turbopack-browser/src/ecmascript/worker.rs]:
```suggestion
        let mut code = get_worker_runtime_code(*this.asset_context, source_maps)?.owned().await?;
```

File: turbopack/crates/turbopack-ecmascript/src/worker_chunk/chunk_item.rs [hunk 9]
```diff
@@ -28,20 +30,22 @@ pub struct WorkerLoaderChunkItem {
...
-
-        Ok(self.chunking_context.evaluated_chunk_group_assets(
+        let worker = self.chunking_context.evaluated_chunk_group_assets(
             module.inner.ident().with_modifier(rcstr!("worker")),
             ChunkGroup::Isolated(ResolvedVc::upcast(module.inner)),
             *self.module_graph,
             AvailabilityInfo::root(),
-        ))
+        );
+        Ok(worker)
```
Comment (mischnic) [inline turbopack/crates/turbopack-ecmascript/src/worker_chunk/chunk_item.rs]: Nit:

```suggestion
        Ok(self.chunking_context.evaluated_chunk_group_assets(
            module.inner.ident().with_modifier(rcstr!("worker")),
            ChunkGroup::Isolated(ResolvedVc::upcast(module.inner)),
            *self.module_graph,
            AvailabilityInfo::root(),
        ))
```

File: turbopack/crates/turbopack-tests/tests/snapshot/workers/shared/issues/Invalid module type-4d174e.txt [hunk 10]
```diff
@@ -0,0 +1,11 @@
+error - [process module] /turbopack/crates/turbopack-tests/tests/snapshot/workers/shared/input/worker.js  Invalid module type
+  
+  The module type must be Ecmascript or Typescript to add Ecmascript transforms
+  
+  Import traces:
```
Comment (mischnic) [inline turbopack/crates/turbopack-tests/tests/snapshot/workers/shared/issues/Invalid module type-4d174e.txt]: This test failed to compile. 

For snapshot tests, this doesn't fail `cargo test` (so that you can assert errors)

File: turbopack/crates/turbopack-browser/src/ecmascript/worker.rs [hunk 11]
```diff
@@ -0,0 +1,134 @@
...
+impl OutputAssetsReference for EcmascriptBrowserWorkerEntrypoint {
+    #[turbo_tasks::function]
+    async fn references(self: Vc<Self>) -> Result<Vc<OutputAssetsWithReferenced>> {
+        let mut references = Vec::new();
+        references.push(ResolvedVc::upcast(self.to_resolved().await?));
+        Ok(OutputAssetsWithReferenced::from_assets(Vc::cell(
+            references,
+        )))
+    }
+}
```
Comment (mischnic) [inline turbopack/crates/turbopack-browser/src/ecmascript/worker.rs:94]: If anything, this should be referencing the sourcemap.

It certainly shouldn't reference itself.

```rust
    #[turbo_tasks::function]
    async fn references(self: Vc<Self>) -> Result<Vc<OutputAssetsWithReferenced>> {
        Ok(OutputAssetsWithReferenced::from_assets(Vc::cell(vec![
            ResolvedVc::upcast(self.source_map().to_resolved().await?),
        ])))
    }
```

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/base/worker-entrypoint.ts [hunk 12]
```diff
@@ -0,0 +1,39 @@
...
+      ...TURBOPACK_NEXT_CHUNK_URLS.map((chunk) =>
+        new URL(chunk, location.origin).toString()
+      ).reverse()
+    )
```
Comment (mischnic) [inline turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/base/worker-entrypoint.ts]: Why is this reversed?

File: turbopack/crates/turbopack-ecmascript/src/worker_chunk/module.rs [hunk 13]
```diff
@@ -74,19 +86,22 @@ impl Asset for WorkerLoaderModule {
...
             WorkerLoaderChunkItem {
                 module: self,
                 module_graph,
                 chunking_context,
+                worker_type: this.worker_type,
+                asset_context: this.asset_context,
             }
             .cell(),
-        )
+        ))
```
Comment (mischnic) [inline turbopack/crates/turbopack-ecmascript/src/worker_chunk/module.rs:104]: Not that it makes a huge difference, but you could also not have `worker_type` and `asset_context` passed as separate fields, but instead do `self.module.await?.worker_type` in the chunk item

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/base/worker-entrypoint.ts (hunk 12 above)
Comment (mmastrac) [reply turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/base/worker-entrypoint.ts]: The previous version reversed the URLs to allow `getPathFromScript` to work: https://github.com/vercel/next.js/pull/88602/files#diff-6f08490fc1ecd55b152422569201bbdfcb582813688e4ff1952685b2496e2e35L327

EDIT: I'll restore the previous comment which explains it well.

**Comment by mmastrac** [comment]
* **#88815** <a href="https://app.graphite.com/github/pr/vercel/next.js/88815?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#88773** <a href="https://app.graphite.com/github/pr/vercel/next.js/88773?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#88602** <a href="https://app.graphite.com/github/pr/vercel/next.js/88602?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/vercel/next.js/88602?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: test/e2e/app-dir/worker/worker.test.ts [hunk 14]
```diff
@@ -17,7 +17,7 @@ describe('app dir - workers', () => {
       const url = request.url()
       // TODO fix deployment id for webpack
       if (isTurbopack) {
-        if (url.includes('_next')) {
+        if (url.includes('_next') && !url.includes('wasm')) {
```
Comment (sokra) [inline test/e2e/app-dir/worker/worker.test.ts:20]: Actually that's an independent bug that wasm urls do not have deployment id. I'll fix it in a separate PR.

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/base/worker-entrypoint.ts (hunk 12 above)
Comment (sokra) [reply turbopack/crates/turbopack-ecmascript-runtime/js/src/browser/runtime/base/worker-entrypoint.ts]: That's correct, as we pop from TURBOPACK_NEXT_CHUNK_URLS, so it need to be in reverse order

File: turbopack/crates/turbopack-ecmascript/src/worker_chunk/module.rs (hunk 13 above)
Comment (sokra) [reply turbopack/crates/turbopack-ecmascript/src/worker_chunk/module.rs:104]: I tried, but it's not better. The current approach is more incremental since only this function depends on the full module.

**Review by sokra — DISMISSED** [review]
Ok... Maybe we are creating a XSS problem due to this approach...
We need to review that

File: turbopack/crates/turbopack-ecmascript/src/worker_chunk/chunk_item.rs [hunk 15]
```diff
@@ -83,8 +110,14 @@ impl EcmascriptChunkItem for WorkerLoaderChunkItem {
...
-    fn references(self: Vc<Self>) -> Vc<OutputAssetsWithReferenced> {
-        self.chunk_group()
+    async fn references(self: Vc<Self>) -> Result<Vc<OutputAssetsWithReferenced>> {
+        let this = self.await?;
+        let asset_context = *this.asset_context;
+        Ok(self.chunk_group().concatenate(
+            this.chunking_context
+                .worker_entrypoint(asset_context)
+                .references(),
+        ))
```
Comment (mischnic) [inline turbopack/crates/turbopack-ecmascript/src/worker_chunk/chunk_item.rs]: That `.references()` shouldn't be there  
Conceptually, this should be `.concatenate(this.chunking_context.worker_entrypoint(asset_context))`, though you might have to massage the datatypes a little bit.

Comment (mmastrac) [reply turbopack/crates/turbopack-ecmascript/src/worker_chunk/chunk_item.rs]: Fixed - I added a `concatenate_asset` helper that calls a new `push` method that pushes a single output asset to an `OutputAssets` collection. The code here was a workaround for those missing methods.

File: turbopack/crates/turbopack-core/src/output.rs [hunk 16]
```diff
@@ -82,6 +82,13 @@ impl OutputAssets {
         Ok(Vc::cell(assets.into_iter().collect()))
     }
 
+    #[turbo_tasks::function]
+    pub async fn push(&self, asset: ResolvedVc<Box<dyn OutputAsset>>) -> Result<Vc<Self>> {
```
Comment (sokra) [inline turbopack/crates/turbopack-core/src/output.rs]: push sounds like a mutating method:

```suggestion
    pub async fn concate_asset(&self, asset: ResolvedVc<Box<dyn OutputAsset>>) -> Result<Vc<Self>> {
```

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/nodejs/runtime.ts [hunk 17]
```diff
@@ -178,11 +178,15 @@ function loadWebAssemblyModule(
...
 contextPrototype.u = loadWebAssemblyModule
 
-function getWorkerBlobURL(_chunks: ChunkPath[]): string {
-  throw new Error('Worker blobs are not implemented yet for Node.js')
+function getWorkerURL(
+  _entrypoint: ChunkPath,
+  _moduleChunks: ChunkPath[],
+  _shared: boolean
+): URL {
+  throw new Error('Worker urls are not implemented yet for Node.js')
```
Comment (sokra) [inline turbopack/crates/turbopack-ecmascript-runtime/js/src/nodejs/runtime.ts:186]: Eventually we probably want to support that too, since node.js supports Workers too

File: turbopack/crates/turbopack-tests/tests/snapshot/workers/basic/static/worker.60655f93.js
Comment (sokra) [inline turbopack/crates/turbopack-tests/tests/snapshot/workers/basic/static/worker.60655f93.js:1]: Technically this file shouldn't be there, but that's a preexisting bug...

**Review by sokra — APPROVED** [review]

File: turbopack/crates/turbopack-tests/tests/snapshot/workers/basic/static/worker.60655f93.js
Comment (mmastrac) [reply turbopack/crates/turbopack-tests/tests/snapshot/workers/basic/static/worker.60655f93.js:1]: Is there an issue for this one already? I could try to take a look.

File: turbopack/crates/turbopack-ecmascript-runtime/js/src/nodejs/runtime.ts (hunk 17 above)
Comment (lukesandberg) [reply turbopack/crates/turbopack-ecmascript-runtime/js/src/nodejs/runtime.ts:186]: the api is different (no urls, no worker-global scope), and that was more or less my PR that got rolled back.  so we will support it but not through this mechanism

**Comment by mmastrac** [comment]
### Merge activity

* **Jan 21, 4:50 PM UTC**: [Graphite](https://app.graphite.com/github/pr/vercel/next.js/88602) couldn't merge this PR because it failed for an unknown reason (GitHub is reporting that this PR is not mergeable, despite passing required status checks defined by your branch protection rules. Please check your rulesets for additional blocking criteria. Graphite Merge Queue does not currently support rulesets. Please contact Graphite support for further assistance.).
