### PR TITLE
Fix next dynamic import named export from client components

### LINKED ISSUE #61046: Error: Could not find the module ... in the React Client Manifest.
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/keen-swartz-k22cmx?file=%2Fapp%2Fpage.js%3A9%2C34

### To Reproduce

The error is obviously visible on the codesandbox link provided but here is how to reproduce it:
- create a component with "use client" `/component/Button.js`
- export this component as named `export function Button`
- dynamically import this component from page `const Button = dynamic(() =>
  import("@/components/Button").then((mod) => mod.Button),
);`

Note: default export works as expected

### Current vs. Expected behavior

Error: Could not find the module "/workspaces/sandbox/components/Button.js#Button#default" in the React Client Manifest. This is probably a bug in the React Server Components bundler.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

_No response_

<sub>[NEXT-2229](https://linear.app/vercel/issue/NEXT-2229/error-could-not-find-the-module-in-the-react-client-manifest)</sub>

### PR DESCRIPTION
**Pull request by huozhi**
When using `next/dynamic` in server components to load a client component with named export, we shouldn't dot into the prop name since client component reference as it's already a valid react component type. It would work with `default` prop but not other named exports.

Let's say `mod` is a dynamic imported module
```
mod.Button.default
```

will become the client reference key
```
mod#Button#default
```
Which means in module `mod`, get `Button` export, then `default` property of it, which is wrong but it's a valid key in the client reference roxy.

This PR checks if they're client module, then return itself as dynamic imported component type for `next/dynamic` if it is one.

Fixes #61046
Closes NEXT-2229

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 4874f28f800a2c3d805de1fd5aaad17278c4fe55

`pnpm test-dev test/e2e/app-dir/dynamic/dynamic.test.ts` (PPR)
- app dir - next/dynamic > should handle next/dynamic in SSR correctly
- app dir - next/dynamic > should handle next/dynamic in hydration correctly

<details>
<summary>Expand output</summary>

  ● app dir - next/dynamic › should handle next/dynamic in SSR correctly

    expect(received).toContain(expected) // indexOf

    Expected substring: "next-dynamic server import client"
    Received string:    "next-dynamic lazynext-dynamic use clientnext-dynamic dynamic on servernext-dynamic dynamic on client"

      28 |       expect(serverContent).toContain('next-dynamic dynamic on server')
      29 |       expect(serverContent).toContain('next-dynamic dynamic on client')
    > 30 |       expect(serverContent).toContain('next-dynamic server import client')
         |                             ^
      31 |       expect(serverContent).not.toContain(
      32 |         'next-dynamic dynamic no ssr on client'
      33 |       )

      at Object.toContain (e2e/app-dir/dynamic/dynamic.test.ts:30:29)

  ● app dir - next/dynamic › should handle next/dynamic in hydration correctly

    expect(received).toContain(expected) // indexOf

    Expected substring: "next-dynamic dynamic no ssr on server"
    Received string:    "·
    1 of 1 unhandled error
    Unhandled Runtime Error·
    Error: Cannot read properties of undefined (reading 'lastIndexOf')·
    Call Stack
    <unknown>
    /tmp/next-install-36ce42187646ab362b730071093ca533115b809e81ae68465df0d9347a46a41a/node_modules/.pnpm/file+..+next-repo-7653c587ef8f51555b6d056559e22994f192e8dd5a007b6a654d1dbff7ff518b+packages+n_gszyohsuntnrjfvedg46i5qgsy/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js (35:367979)
    eQ
    /tmp/next-install-36ce42187646ab362b730071093ca533115b809e81ae68465df0d9347a46a41a/node_modules/.pnpm/file+..+next-repo-7653c587ef8f51555b6d056559e22994f192e8dd5a007b6a654d1dbff7ff518b+packages+n_gszyohsuntnrjfvedg46i5qgsy/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js (35:368246)
    <unknown>
    /tmp/next-install-36ce42187646ab362b730071093ca533115b809e81ae68465df0d9347a46a41a/node_modules/.pnpm/file+..+next-repo-7653c587ef8f51555b6d056559e22994f192e8dd5a007b6a654d1dbff7ff518b+packages+n_gszyohsuntnrjfvedg46i5qgsy/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js (35:380203)
    Array.toJSON
    /tmp/next-install-36ce42187646ab362b730071093ca533115b809e81ae68465df0d9347a46a41a/node_modules/.pnpm/file+..+next-repo-7653c587ef8f51555b6d056559e22994f192e8dd5a007b6a654d1dbff7ff518b+packages+n_gszyohsuntnrjfvedg46i5qgsy/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js (35:385987)
    stringify
    <anonymous>
    <unknown>
    /tmp/next-install-36ce42187646ab362b730071093ca533115b809e81ae68465df0d9347a46a41a/node_modules/.pnpm/file+..+next-repo-7653c587ef8f51555b6d056559e22994f192e8dd5a007b6a654d1dbff7ff518b+packages+n_gszyohsuntnrjfvedg46i5qgsy/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js (35:370410)
    e7
    /tmp/next-install-36ce42187646ab362b730071093ca533115b809e81ae68465df0d9347a46a41a/node_modules/.pnpm/file+..+next-repo-7653c587ef8f51555b6d056559e22994f192e8dd5a007b6a654d1dbff7ff518b+packages+n_gszyohsuntnrjfvedg46i5qgsy/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js (35:370489)
    te
    /tmp/next-install-36ce42187646ab362b730071093ca533115b809e81ae68465df0d9347a46a41a/node_modules/.pnpm/file+..+next-repo-7653c587ef8f51555b6d056559e22994f192e8dd5a007b6a654d1dbff7ff518b+packages+n_gszyohsuntnrjfvedg46i5qgsy/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js (35:370990)
    Timeout._onTimeout
    /tmp/next-install-36ce42187646ab362b730071093ca533115b809e81ae68465df0d9347a46a41a/node_modules/.pnpm/file+..+next-repo-7653c587ef8f51555b6d056559e22994f192e8dd5a007b6a654d1dbff7ff518b+packages+n_gszyohsuntnrjfvedg46i5qgsy/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js (35:367325)
    listOnTimeout
    node:internal/timers (573:17)
    process.processTimers
    node:internal/timers (514:7)"

      45 |       const browser = await next.browser('/dynamic')
      46 |       const clientContent = await browser.elementByCss(selector).text()
    > 47 |       expect(clientContent).toContain('next-dynamic dynamic no ssr on server')
         |                             ^
      48 |       expect(clientContent).toContain('client component under sever no ssr')
      49 |       await browser.waitForElementByCss('#css-text-dynamic-no-ssr-client')
      50 |

      at Object.toContain (e2e/app-dir/dynamic/dynamic.test.ts:47:29)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/bundling-error-dynamic-import | Change |
| - | - | - | - |
| buildDuration | 11.7s | 11.8s | N/A |
| buildDurationCached | 6s | 5s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +1.99 kB |
| nextStartRea..uration (ms) | 427ms | 432ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/bundling-error-dynamic-import | Change |
| - | - | - | - |
| 3f784ff6-HASH.js gzip | 53.4 kB | 53.4 kB | ✓ |
| 423.HASH.js gzip | 185 B | 181 B | N/A |
| 68-HASH.js gzip | 29.9 kB | 29.9 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 240 B | 239 B | N/A |
| main-HASH.js gzip | 31.8 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 100 kB | 100 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/bundling-error-dynamic-import | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/bundling-error-dynamic-import | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 502 B | 502 B | ✓ |
| css-HASH.js gzip | 320 B | 322 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 256 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.18 kB | 4.18 kB | N/A |
| index-HASH.js gzip | 257 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | N/A |
| routerDirect..HASH.js gzip | 310 B | 311 B | N/A |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 306 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 608 B | 608 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/bundling-error-dynamic-import | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 484 B | ✓ |
| Overall change | 484 B | 484 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/bundling-error-dynamic-import | Change |
| - | - | - | - |
| index.html gzip | 528 B | 527 B | N/A |
| link.html gzip | 541 B | 540 B | N/A |
| withRouter.html gzip | 523 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/bundling-error-dynamic-import | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94 kB | 94 kB | N/A |
| page.js gzip | 150 kB | 150 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/bundling-error-dynamic-import | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 624 B | ✓ |
| middleware-r..fest.js gzip | 151 B | 149 B | N/A |
| middleware.js gzip | 37.6 kB | 37.6 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.55 kB | 2.55 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/bundling-error-dynamic-import | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | ✓ |
| app-page-exp..prod.js gzip | 95.8 kB | 95.8 kB | ✓ |
| app-page-tur..prod.js gzip | 96.4 kB | 96.4 kB | ✓ |
| app-page-tur..prod.js gzip | 91 kB | 91 kB | ✓ |
| app-page.run...dev.js gzip | 142 kB | 142 kB | ✓ |
| app-page.run..prod.js gzip | 90.3 kB | 90.3 kB | ✓ |
| app-route-ex...dev.js gzip | 22.2 kB | 22.2 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.5 kB | 14.5 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.5 kB | 14.5 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.7 kB | 9.7 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-turbo...prod.js gzip | 22 kB | 22 kB | ✓ |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | ✓ |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | ✓ |
| server.runti..prod.js gzip | 49.7 kB | 49.7 kB | ✓ |
| Overall change | 933 kB | 933 kB | ✓ |

</details>

</details>
Commit: 4874f28f800a2c3d805de1fd5aaad17278c4fe55

**Review by shuding — APPROVED** [review]

File: test/e2e/app-dir/dynamic/app/dynamic/named-export/page.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import dynamic from 'next/dynamic'
+
+const Button = dynamic(() =>
```
Comment (A7med3bdulBaset) [inline test/e2e/app-dir/dynamic/app/dynamic/named-export/page.js:3]: https://github.com/vercel/next.js/issues/49454#issuecomment-1830053413

What does `dynamic()` do between Server Component and Client Component?
