### PR TITLE
fix: coerce HEAD to GET for internal images

### LINKED ISSUE #84129: HEAD requests for Next.js image return 400 Bad Request when image is not yet cached
### Link to the code that reproduces this issue

https://github.com/Git-I985/next-head-image-empty-cache

## Description

When making a HEAD request to an image served via the Next.js Image Optimizer (/_next/image) before the image is cached, the server returns 400 Bad Request.

- **On Next.js 15.3.x:**
  - A first HEAD request poisoned the cache by storing an empty file, causing subsequent GET requests to return an empty response.
- **On Next.js 15.5.x:**
  - The cache poisoning seems fixed (no empty files are written). 
  - However, the first uncached HEAD request still fails with 400 Bad Request. 
  - Only after a GET request succeeds and the image is cached, subsequent HEAD requests return 200 OK.

This behavior breaks CDNs/proxies that issue HEAD requests for validation or preflight, since they receive a 400 instead of headers describing the resource.

### To Reproduce

**Current version**

1. Build and start `npm run build && npm run start`
2. Clear cache
```bash
rm -rf .next/cache/images
```
3. Make HTTP HEAD request to the image resource
```bash
curl -IL "http://localhost:3000/_next/image?url=/_next/static/media/test-image.daca9759.jpg&w=3840&q=75"
```
**Result (problem):**
```bash
HTTP/1.1 400 Bad Request
Date: Tue, 23 Sep 2025 09:44:29 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```
```bash
 ⨯ The requested resource isn't a valid image for /_next/static/media/test-image.daca9759.jpg received null
 ⨯ The requested resource isn't a valid image for /_next/static/media/test-image.daca9759.jpg received null
 ⨯ The requested resource isn't a valid image for /_next/static/media/test-image.daca9759.jpg received null

```
4. Make HTTP GET request to the image resource
```bash
curl -D -- -o test.webp "http://localhost:3000/_next/image?url=/_next/static/media/test-image.daca9759.jpg&w=3840&q=75"
```
Result
```bash
HTTP/1.1 200 OK
Vary: Accept
Cache-Control: public, max-age=315360000, immutable
ETag: RyS1td48qGQV0eM3i0m8noPJ3D5-WZfkAMCZjHfkHHo
Content-Type: image/jpeg
Content-Disposition: attachment; filename="test-image.jpeg"
Content-Security-Policy: script-src 'none'; frame-src 'none'; sandbox;
X-Nextjs-Cache: HIT
Content-Length: 134217
Date: Tue, 23 Sep 2025 09:47:14 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```
_Now image cached properly and next HTTP HEAD request will be OK_
5. Make HTTP HEAD request to the image resource again
```bash
curl -IL "http://localhost:3000/_next/image?url=/_next/static/media/test-image.daca9759.jpg&w=3840&q=75"
```
Result:
```bash
HTTP/1.1 200 OK
Vary: Accept
Cache-Control: public, max-age=315360000, immutable
ETag: RyS1td48qGQV0eM3i0m8noPJ3D5-WZfkAMCZjHfkHHo
Content-Type: image/jpeg
Content-Disposition: attachment; filename="test-image.jpeg"
Content-Security-Policy: script-src 'none'; frame-src 'none'; sandbox;
X-Nextjs-Cache: HIT
Content-Length: 134217
Date: Tue, 23 Sep 2025 09:48:48 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```
---

**Older versions (reproducible on `15.3.X`)**

**first HEAD request** (when the image was not yet in the cache) **poisoned the cache**, and an empty file was stored there, so the following GET requests returned an empty file. 

```bash
# Next 15.3.0

# clear next cache

# DO HTTP GET
$ curl  -D - -o test.jpg "http://localhost:4000/_next/image?url=/_next/static/media/file.e2ff9d29.jpg&w=3840&q=74&t=12"

Cache-Control: public, max-age=315360000, immutable
Vary: Accept
ETag: Vy8iMWYyZjkxLTE5OTcxOTNjZjIzIg
Content-Type: image/jpeg
Content-Disposition: attachment; filename="file.jpeg"
Content-Security-Policy: script-src 'none'; frame-src 'none'; sandbox;
Date: Mon, 22 Sep 2025 13:42:28 GMT
Content-Length: 2043793
Cache-Tag: nextjs-source
X-Nextjs-Cache: MISS

# DO HTTP GET AGAIN
$ curl  -D - -o test.jpg "http://localhost:4000/_next/image?url=/_next/static/media/file.e2ff9d29.jpg&w=3840&q=74&t=12"

Cache-Control: public, max-age=315360000, immutable
Vary: Accept
ETag: Vy8iMWYyZjkxLTE5OTcxOTNjZjIzIg
Content-Type: image/jpeg
Content-Disposition: attachment; filename="file.jpeg"
Content-Security-Policy: script-src 'none'; frame-src 'none'; sandbox;
Date: Mon, 22 Sep 2025 13:42:33 GMT
Content-Length: 2043793
Cache-Tag: nextjs-source
X-Nextjs-Cache: HIT

# Stable, normal, cached the response with the correct content-length.

# I cleared the cache inside the container, now I make a HEAD request.

$ curl  -IL "http://localhost:4000/_next/image?url=/_next/static/media/file.e2ff9d29.jpg&w=3840&q=74&t=12"
HTTP/1.1 200 OK
Cache-Control: public, max-age=315360000, immutable
Vary: Accept
ETag: Vy8iMWYyZjkxLTE5OTcxOTNjZjIzIg
Content-Type: image/jpeg
Content-Disposition: attachment; filename="file.jpeg"
Content-Security-Policy: script-src 'none'; frame-src 'none'; sandbox;
Date: Mon, 22 Sep 2025 13:43:23 GMT
Content-Length: 0 # <--- PROBLEM
Cache-Tag: nextjs-source
X-Nextjs-Cache: MISS # <--- CACHED AFTER THIS REQUEST

# DO HTTP GET
$ curl  -D - -o test.jpg "http://localhost:4000/_next/image?url=/_next/static/media/file.e2ff9d29.jpg&w=3840&q=74&t=12"

Cache-Control: public, max-age=315360000, immutable
Vary: Accept
ETag: Vy8iMWYyZjkxLTE5OTcxOTNjZjIzIg
Content-Type: image/jpeg
Content-Disposition: attachment; filename="file.jpeg"
Content-Security-Policy: script-src 'none'; frame-src 'none'; sandbox;
Date: Mon, 22 Sep 2025 13:44:22 GMT
Content-Length: 0 # <--- PROBLEM
Cache-Tag: nextjs-source
X-Nextjs-Cache: HIT

# Check downloaded file size
xdd test.jpg | head
# empty...
# Something went wrong. The first HEAD cached an empty response, and now GET returns it.

# I cleared the cache inside the container. 
# First, I do a GET to cache a normal response.
$ curl  -D - -o test.jpg "http://localhost:4000/_next/image?url=/_next/static/media/file.e2ff9d29.jpg&w=3840&q=74&t=12"

Cache-Control: public, max-age=315360000, immutable
Vary: Accept
ETag: Vy8iMWYyZjkxLTE5OTcxOTNjZjIzIg
Content-Type: image/jpeg
Content-Disposition: attachment; filename="file.jpeg"
Content-Security-Policy: script-src 'none'; frame-src 'none'; sandbox;
Date: Mon, 22 Sep 2025 13:45:28 GMT
Content-Length: 2043793 # Normal response
Cache-Tag: nextjs-source
X-Nextjs-Cache: MISS

$ curl  -IL "http://localhost:4000/_next/image?url=/_next/static/media/file.e2ff9d29.jpg&w=3840&q=74&t=12"
HTTP/1.1 200 OK
Cache-Control: public, max-age=315360000, immutable
Vary: Accept
ETag: Vy8iMWYyZjkxLTE5OTcxOTNjZjIzIg
Content-Type: image/jpeg
Content-Disposition: attachment; filename="file.jpeg"
Content-Security-Policy: script-src 'none'; frame-src 'none'; sandbox;
Date: Mon, 22 Sep 2025 13:45:31 GMT
Content-Length: 2043793 # # Normal response
Cache-Tag: nextjs-source
X-Nextjs-Cache: HIT
```

### Current vs. Expected behavior

**Current (15.5.x):**
- First uncached HEAD request → 400 Bad Request with error logs (received null).
- No image written to cache.
- Only after a successful GET request, HEAD starts returning 200 OK.

**Expected:**
- HEAD request should behave like a GET request but without streaming the body.
- Even if the image is not cached yet, the first HEAD should:
- Return 200 OK.
- Include correct headers (Content-Type, Content-Length, ETag, etc.).
- Either skip writing to cache or safely populate cache metadata without breaking.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:40 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6041
  Available memory (MB): 49152
  Available CPU cores: 12
Binaries:
  Node: 22.17.0
  npm: 10.9.2
  Yarn: N/A
  pnpm: 9.11.0
Relevant Packages:
  next: 15.5.3 // Latest available version is detected (15.5.3).
  eslint-config-next: 15.5.3
  react: 19.1.0
  react-dom: 19.1.0
  typescript: 5.9.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Image (next/image), Not sure

### Which stage(s) are affected? (Select all that apply)

Other (Deployed), next dev (local), next start (local)

### Versions
- Next.js 15.3.x → cache poisoned by HEAD (empty files stored).
- Next.js 15.5.x → cache poisoning fixed, but HEAD requests still fail with 400 Bad Request.

### Impact
- CDNs/load balancers (e.g. Cloudflare, Fastly, etc.) that send HEAD may treat the image route as broken.
- It prevents reliable header-only introspection of images before cache warming.

<sub>[NEXT-4731](https://linear.app/vercel/issue/NEXT-4731/head-requests-for-nextjs-image-return-400-bad-request-when-image-is)</sub>

### PR DESCRIPTION
**Pull request by icyJoseph**
Fixes: https://github.com/vercel/next.js/issues/84129

TODO:

- [x] e2e test (?)
- [x] verify against repro steps in source issue

### CODE REVIEW

**Comment by ijjk** [comment]
## Tests Passed

<!-- ## Failing test suites -- >

**Comment by icyJoseph** [comment]
I reckon we should return an empty body for HEAD requests here?

https://github.com/vercel/next.js/blob/f0653d4a45807a8d239eccb00e34f40c3cece71a/packages/next/src/server/image-optimizer.ts#L1092-L1095

```ts
   if (req.method === 'HEAD') {
      res.end()
    } else {
      res.end(buffer)
    }
```

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/next-image-coerce-head-to-get | Change |
| - | - | - | - |
| buildDuration | 17.3s | 17.9s | ⚠️ +653ms |
| buildDurationCached | 13.9s | 11s | N/A |
| nodeModulesSize | 456 MB | 457 MB | ⚠️ +944 kB |
| nextStartRea..uration (ms) | 716ms | 718ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/next-image-coerce-head-to-get | Change |
| - | - | - | - |
| 4292-HASH.js gzip | 4.46 kB | N/A | N/A |
| 436-HASH.js gzip | 5.39 kB | 5.32 kB | N/A |
| 4779.HASH.js gzip | 169 B | 169 B | ✓ |
| 9760-HASH.js gzip | 50.9 kB | 52.7 kB | ⚠️ +1.75 kB |
| c57d0559-HASH.js gzip | 62.3 kB | 62.3 kB | N/A |
| framework-HASH.js gzip | 59.8 kB | 59.8 kB | ✓ |
| main-app-HASH.js gzip | 253 B | 256 B | N/A |
| main-HASH.js gzip | 38.6 kB | 38.3 kB | N/A |
| webpack-HASH.js gzip | 1.69 kB | 1.69 kB | ✓ |
| Overall change | 113 kB | 114 kB | ⚠️ +1.75 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/next-image-coerce-head-to-get | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/next-image-coerce-head-to-get | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 194 B | N/A |
| _error-HASH.js gzip | 182 B | 182 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| dynamic-HASH.js gzip | 1.81 kB | 1.81 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 254 B | N/A |
| head-HASH.js gzip | 350 B | 351 B | N/A |
| hooks-HASH.js gzip | 384 B | 384 B | ✓ |
| image-HASH.js gzip | 580 B | 4.77 kB | ⚠️ +4.19 kB |
| index-HASH.js gzip | 260 B | 259 B | N/A |
| link-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| routerDirect..HASH.js gzip | 316 B | 320 B | N/A |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 316 B | 314 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.97 kB | 6.17 kB | ⚠️ +4.19 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/next-image-coerce-head-to-get | Change |
| - | - | - | - |
| _buildManifest.js gzip | 737 B | 720 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/next-image-coerce-head-to-get | Change |
| - | - | - | - |
| index.html gzip | 524 B | 521 B | N/A |
| link.html gzip | 538 B | 537 B | N/A |
| withRouter.html gzip | 521 B | 517 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/next-image-coerce-head-to-get | Change |
| - | - | - | - |
| edge-ssr.js gzip | 124 kB | 126 kB | ⚠️ +1.74 kB |
| page.js gzip | 238 kB | 235 kB | N/A |
| Overall change | 124 kB | 126 kB | ⚠️ +1.74 kB |

</details>

<details>
<summary><strong>Middleware size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/next-image-coerce-head-to-get | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 655 B | 638 B | N/A |
| middleware-r..fest.js gzip | 156 B | 156 B | ✓ |
| middleware.js gzip | 32.8 kB | 33 kB | ⚠️ +168 B |
| edge-runtime..pack.js gzip | 846 B | 846 B | ✓ |
| Overall change | 33.8 kB | 34 kB | ⚠️ +168 B |

</details>

<details>
<summary><strong>Next Runtimes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/next-image-coerce-head-to-get | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 301 kB | 299 kB | N/A |
| app-page-exp..prod.js gzip | 156 kB | 154 kB | N/A |
| app-page-tur...dev.js gzip | 301 kB | 299 kB | N/A |
| app-page-tur..prod.js gzip | 156 kB | 154 kB | N/A |
| app-page-tur...dev.js gzip | 298 kB | 296 kB | N/A |
| app-page-tur..prod.js gzip | 154 kB | 152 kB | N/A |
| app-page.run...dev.js gzip | 298 kB | 296 kB | N/A |
| app-page.run..prod.js gzip | 154 kB | 152 kB | N/A |
| app-route-ex...dev.js gzip | 68.6 kB | 68.5 kB | N/A |
| app-route-ex..prod.js gzip | 47.4 kB | 47.3 kB | N/A |
| app-route-tu...dev.js gzip | 68.6 kB | 68.5 kB | N/A |
| app-route-tu..prod.js gzip | 47.5 kB | 47.3 kB | N/A |
| app-route-tu...dev.js gzip | 68.2 kB | 68.1 kB | N/A |
| app-route-tu..prod.js gzip | 47.2 kB | 47.1 kB | N/A |
| app-route.ru...dev.js gzip | 68.2 kB | 68.1 kB | N/A |
| app-route.ru..prod.js gzip | 47.2 kB | 47.1 kB | N/A |
| dist_client_...dev.js gzip | 324 B | 326 B | N/A |
| dist_client_...dev.js gzip | 326 B | 328 B | N/A |
| dist_client_...dev.js gzip | 318 B | 320 B | N/A |
| dist_client_...dev.js gzip | 317 B | 318 B | N/A |
| pages-api-tu...dev.js gzip | 41 kB | 40.9 kB | N/A |
| pages-api-tu..prod.js gzip | 31.1 kB | 31 kB | N/A |
| pages-api.ru...dev.js gzip | 41 kB | 40.8 kB | N/A |
| pages-api.ru..prod.js gzip | 31.1 kB | 30.9 kB | N/A |
| pages-turbo....dev.js gzip | 50.6 kB | 50.3 kB | N/A |
| pages-turbo...prod.js gzip | 38.1 kB | 37.8 kB | N/A |
| pages.runtim...dev.js gzip | 50.6 kB | 50.3 kB | N/A |
| pages.runtim..prod.js gzip | 38.1 kB | 37.8 kB | N/A |
| server.runti..prod.js gzip | 59.8 kB | 60.8 kB | ⚠️ +988 B |
| Overall change | 59.8 kB | 60.8 kB | ⚠️ +988 B |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/next-image-coerce-head-to-get | Change |
| - | - | - | - |
| 0.pack gzip | 3.61 MB | 3.1 MB | N/A |
| index.pack gzip | 99.9 kB | 93.4 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware-b..-manifest.js</strong></summary>

```diff
@@ -3,92 +3,91 @@ globalThis.__BUILD_MANIFEST = {
   devFiles: [],
   lowPriorityFiles: [],
   rootMainFiles: [
-    "static/chunks/webpack-fcf10f51cee06933.js",
-    "static/chunks/c57d0559-0cc41add60bbb856.js",
-    "static/chunks/9760-a0032c5ef792a10e.js",
-    "static/chunks/main-app-93f4a89e15c49f6c.js",
+    "static/chunks/webpack-c7aff218e9eee7c3.js",
+    "static/chunks/fc3b8630-0aedb1ec9a13f0cd.js",
+    "static/chunks/4936-7a64514a9da327e4.js",
+    "static/chunks/main-app-faefd596e69a8ec4.js",
   ],
   rootMainFilesTree: {},
   pages: {
     "/": [
-      "static/chunks/webpack-fcf10f51cee06933.js",
-      "static/chunks/framework-9097e8e7f9a0f6cb.js",
-      "static/chunks/main-1196549aef796aec.js",
-      "static/chunks/pages/index-9b1f076e9fac03f4.js",
+      "static/chunks/webpack-c7aff218e9eee7c3.js",
+      "static/chunks/framework-e894a2c73c6746db.js",
+      "static/chunks/main-6f21364ace1e4850.js",
+      "static/chunks/pages/index-5523fac5e3835d81.js",
     ],
     "/_app": [
-      "static/chunks/webpack-fcf10f51cee06933.js",
-      "static/chunks/framework-9097e8e7f9a0f6cb.js",
-      "static/chunks/main-1196549aef796aec.js",
-      "static/chunks/pages/_app-443eabb8a4e5c909.js",
+      "static/chunks/webpack-c7aff218e9eee7c3.js",
+      "static/chunks/framework-e894a2c73c6746db.js",
+      "static/chunks/main-6f21364ace1e4850.js",
+      "static/chunks/pages/_app-8c07b9dcfad803bd.js",
     ],
     "/_error": [
-      "static/chunks/webpack-fcf10f51cee06933.js",
-      "static/chunks/framework-9097e8e7f9a0f6cb.js",
-      "static/chunks/main-1196549aef796aec.js",
-      "static/chunks/pages/_error-6b752512a6c1df59.js",
+      "static/chunks/webpack-c7aff218e9eee7c3.js",
+      "static/chunks/framework-e894a2c73c6746db.js",
+      "static/chunks/main-6f21364ace1e4850.js",
+      "static/chunks/pages/_error-d96fc1a54d61a013.js",
     ],
     "/css": [
-      "static/chunks/webpack-fcf10f51cee06933.js",
-      "static/chunks/framework-9097e8e7f9a0f6cb.js",
-      "static/chunks/main-1196549aef796aec.js",
+      "static/chunks/webpack-c7aff218e9eee7c3.js",
+      "static/chunks/framework-e894a2c73c6746db.js",
+      "static/chunks/main-6f21364ace1e4850.js",
       "static/css/ded6b86ab9cc0a1f.css",
-      "static/chunks/pages/css-9049095f8d68fcf0.js",
+      "static/chunks/pages/css-a4befe2475e7b7f1.js",
     ],
     "/dynamic": [
-      "static/chunks/webpack-fcf10f51cee06933.js",
-      "static/chunks/framework-9097e8e7f9a0f6cb.js",
-      "static/chunks/main-1196549aef796aec.js",
-      "static/chunks/pages/dynamic-13423b508b9357ba.js",
+      "static/chunks/webpack-c7aff218e9eee7c3.js",
+      "static/chunks/framework-e894a2c73c6746db.js",
+      "static/chunks/main-6f21364ace1e4850.js",
+      "static/chunks/pages/dynamic-5982726453bd01a1.js",
     ],
     "/edge-ssr": [
-      "static/chunks/webpack-fcf10f51cee06933.js",
-      "static/chunks/framework-9097e8e7f9a0f6cb.js",
-      "static/chunks/main-1196549aef796aec.js",
-      "static/chunks/pages/edge-ssr-69e1b3a57e819753.js",
+      "static/chunks/webpack-c7aff218e9eee7c3.js",
+      "static/chunks/framework-e894a2c73c6746db.js",
+      "static/chunks/main-6f21364ace1e4850.js",
+      "static/chunks/pages/edge-ssr-6611d49d885b4aee.js",
     ],
     "/head": [
-      "static/chunks/webpack-fcf10f51cee06933.js",
-      "static/chunks/framework-9097e8e7f9a0f6cb.js",
-      "static/chunks/main-1196549aef796aec.js",
-      "static/chunks/pages/head-f7d913c23a1370c9.js",
+      "static/chunks/webpack-c7aff218e9eee7c3.js",
+      "static/chunks/framework-e894a2c73c6746db.js",
+      "static/chunks/main-6f21364ace1e4850.js",
+      "static/chunks/pages/head-5b00d0ab61ce4b2b.js",
     ],
     "/hooks": [
-      "static/chunks/webpack-fcf10f51cee06933.js",
-      "static/chunks/framework-9097e8e7f9a0f6cb.js",
-      "static/chunks/main-1196549aef796aec.js",
-      "static/chunks/pages/hooks-497c26b761107c7b.js",
+      "static/chunks/webpack-c7aff218e9eee7c3.js",
+      "static/chunks/framework-e894a2c73c6746db.js",
+      "static/chunks/main-6f21364ace1e4850.js",
+      "static/chunks/pages/hooks-fc936af610663c47.js",
     ],
     "/image": [
-      "static/chunks/webpack-fcf10f51cee06933.js",
-      "static/chunks/framework-9097e8e7f9a0f6cb.js",
-      "static/chunks/main-1196549aef796aec.js",
-      "static/chunks/4292-613c99333dbaee50.js",
-      "static/chunks/pages/image-7e7769e30c0e02dc.js",
+      "static/chunks/webpack-c7aff218e9eee7c3.js",
+      "static/chunks/framework-e894a2c73c6746db.js",
+      "static/chunks/main-6f21364ace1e4850.js",
+      "static/chunks/pages/image-50232676a62af73d.js",
     ],
     "/link": [
-      "static/chunks/webpack-fcf10f51cee06933.js",
-      "static/chunks/framework-9097e8e7f9a0f6cb.js",
-      "static/chunks/main-1196549aef796aec.js",
-      "static/chunks/pages/link-7fdc135fa2024739.js",
+      "static/chunks/webpack-c7aff218e9eee7c3.js",
+      "static/chunks/framework-e894a2c73c6746db.js",
+      "static/chunks/main-6f21364ace1e4850.js",
+      "static/chunks/pages/link-67afc54938b48e5b.js",
     ],
     "/routerDirect": [
-      "static/chunks/webpack-fcf10f51cee06933.js",
-      "static/chunks/framework-9097e8e7f9a0f6cb.js",
-      "static/chunks/main-1196549aef796aec.js",
-      "static/chunks/pages/routerDirect-41aacbe853e5a2d3.js",
+      "static/chunks/webpack-c7aff218e9eee7c3.js",
+      "static/chunks/framework-e894a2c73c6746db.js",
+      "static/chunks/main-6f21364ace1e4850.js",
+      "static/chunks/pages/routerDirect-d780b8e463346e70.js",
     ],
     "/script": [
-      "static/chunks/webpack-fcf10f51cee06933.js",
-      "static/chunks/framework-9097e8e7f9a0f6cb.js",
-      "static/chunks/main-1196549aef796aec.js",
-      "static/chunks/pages/script-02909c5224d7541d.js",
+      "static/chunks/webpack-c7aff218e9eee7c3.js",
+      "static/chunks/framework-e894a2c73c6746db.js",
+      "static/chunks/main-6f21364ace1e4850.js",
+      "static/chunks/pages/script-fadf26f818c6a9d9.js",
     ],
     "/withRouter": [
-      "static/chunks/webpack-fcf10f51cee06933.js",
-      "static/chunks/framework-9097e8e7f9a0f6cb.js",
-      "static/chunks/main-1196549aef796aec.js",
-      "static/chunks/pages/withRouter-44eb1a330ebc9a95.js",
+      "static/chunks/webpack-c7aff218e9eee7c3.js",
+      "static/chunks/framework-e894a2c73c6746db.js",
+      "static/chunks/main-6f21364ace1e4850.js",
+      "static/chunks/pages/withRouter-f061effa2d48ed55.js",
     ],
   },
 };
```
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -611,35 +611,32 @@ self.__BUILD_MANIFEST = (function (a, b, c) {
       numHashes: NaN,
       bitArray: [],
     },
-    "/": ["static\u002Fchunks\u002Fpages\u002Findex-9b1f076e9fac03f4.js"],
+    "/": ["static\u002Fchunks\u002Fpages\u002Findex-5523fac5e3835d81.js"],
     "/_error": [
-      "static\u002Fchunks\u002Fpages\u002F_error-6b752512a6c1df59.js",
+      "static\u002Fchunks\u002Fpages\u002F_error-d96fc1a54d61a013.js",
     ],
     "/css": [
       "static\u002Fcss\u002Fded6b86ab9cc0a1f.css",
-      "static\u002Fchunks\u002Fpages\u002Fcss-9049095f8d68fcf0.js",
+      "static\u002Fchunks\u002Fpages\u002Fcss-a4befe2475e7b7f1.js",
     ],
     "/dynamic": [
-      "static\u002Fchunks\u002Fpages\u002Fdynamic-13423b508b9357ba.js",
+      "static\u002Fchunks\u002Fpages\u002Fdynamic-5982726453bd01a1.js",
     ],
     "/edge-ssr": [
-      "static\u002Fchunks\u002Fpages\u002Fedge-ssr-69e1b3a57e819753.js",
+      "static\u002Fchunks\u002Fpages\u002Fedge-ssr-6611d49d885b4aee.js",
     ],
-    "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-f7d913c23a1370c9.js"],
-    "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-497c26b761107c7b.js"],
-    "/image": [
-      "static\u002Fchunks\u002F4292-613c99333dbaee50.js",
-      "static\u002Fchunks\u002Fpages\u002Fimage-7e7769e30c0e02dc.js",
-    ],
-    "/link": ["static\u002Fchunks\u002Fpages\u002Flink-7fdc135fa2024739.js"],
+    "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-5b00d0ab61ce4b2b.js"],
+    "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-fc936af610663c47.js"],
+    "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-50232676a62af73d.js"],
+    "/link": ["static\u002Fchunks\u002Fpages\u002Flink-67afc54938b48e5b.js"],
     "/routerDirect": [
-      "static\u002Fchunks\u002Fpages\u002FrouterDirect-41aacbe853e5a2d3.js",
+      "static\u002Fchunks\u002Fpages\u002FrouterDirect-d780b8e463346e70.js",
     ],
     "/script": [
-      "static\u002Fchunks\u002Fpages\u002Fscript-02909c5224d7541d.js",
+      "static\u002Fchunks\u002Fpages\u002Fscript-fadf26f818c6a9d9.js",
     ],
     "/withRouter": [
-      "static\u002Fchunks\u002Fpages\u002FwithRouter-44eb1a330ebc9a95.js",
+      "static\u002Fchunks\u002Fpages\u002FwithRouter-f061effa2d48ed55.js",
     ],
     sortedPages: [
       "\u002F",
```
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [2291],
   {
-    /***/ 1033: /***/ (
+    /***/ 431: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/dynamic",
         function () {
-          return __webpack_require__(6490);
+          return __webpack_require__(8084);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 5323: /***/ (
+    /***/ 2699: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -60,7 +60,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       const _react = /*#__PURE__*/ _interop_require_default._(
         __webpack_require__(2223)
       );
-      const _loadablecontextsharedruntime = __webpack_require__(9289);
+      const _loadablecontextsharedruntime = __webpack_require__(3785);
       function resolve(obj) {
         return obj && obj.default ? obj.default : obj;
       }
@@ -293,73 +293,34 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       /***/
     },
 
-    /***/ 6490: /***/ (
+    /***/ 3785: /***/ (
       __unused_webpack_module,
-      __webpack_exports__,
+      exports,
       __webpack_require__
     ) => {
       "use strict";
-      __webpack_require__.r(__webpack_exports__);
-      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
-        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
-        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
-        /* harmony export */
+      /* __next_internal_client_entry_do_not_use__  cjs */
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
       });
-      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(1503);
-      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(7320);
-      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default =
-        /*#__PURE__*/ __webpack_require__.n(
-          next_dynamic__WEBPACK_IMPORTED_MODULE_1__
-        );
-
-      const DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
-        () =>
-          __webpack_require__
-            .e(/* import() */ 4779)
-            .then(__webpack_require__.bind(__webpack_require__, 4779))
-            .then((mod) => mod.Hello),
-        {
-          loadableGenerated: {
-            webpack: () => [/*require.resolve*/ 4779],
-          },
-        }
+      Object.defineProperty(exports, "LoadableContext", {
+        enumerable: true,
+        get: function () {
+          return LoadableContext;
+        },
+      });
+      const _interop_require_default = __webpack_require__(1532);
+      const _react = /*#__PURE__*/ _interop_require_default._(
+        __webpack_require__(2223)
       );
-      const Page = () =>
-        /*#__PURE__*/ (0, react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)(
-          react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.Fragment,
-          {
-            children: [
-              /*#__PURE__*/ (0,
-              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("p", {
-                children: "testing next/dynamic size",
-              }),
-              /*#__PURE__*/ (0,
-              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
-                DynamicHello,
-                {}
-              ),
-            ],
-          }
-        );
-      var __N_SSP = true;
-      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = Page;
-
-      /***/
-    },
-
-    /***/ 7320: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(7340);
+      const LoadableContext = _react.default.createContext(null);
+      if (false) {
+      } //# sourceMappingURL=loadable-context.shared-runtime.js.map
 
       /***/
     },
 
-    /***/ 7340: /***/ (module, exports, __webpack_require__) => {
+    /***/ 6828: /***/ (module, exports, __webpack_require__) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -392,7 +353,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
         __webpack_require__(2223)
       );
       const _loadablesharedruntime = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(5323)
+        __webpack_require__(2699)
       );
       const isServerSide = "object" === "undefined";
       // Normalize loader to return the module as form { default: Component } for `React.lazy`.
@@ -492,29 +453,68 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       /***/
     },
 
-    /***/ 9289: /***/ (
+    /***/ 7514: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(6828);
+
+      /***/
+    },
+
+    /***/ 8084: /***/ (
       __unused_webpack_module,
-      exports,
+      __webpack_exports__,
       __webpack_require__
     ) => {
       "use strict";
-      /* __next_internal_client_entry_do_not_use__  cjs */
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "LoadableContext", {
-        enumerable: true,
-        get: function () {
-          return LoadableContext;
-        },
+      __webpack_require__.r(__webpack_exports__);
+      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
+        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
+        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
+        /* harmony export */
       });
-      const _interop_require_default = __webpack_require__(1532);
-      const _react = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(2223)
+      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
+        __webpack_require__(1503);
+      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ =
+        __webpack_require__(7514);
+      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default =
+        /*#__PURE__*/ __webpack_require__.n(
+          next_dynamic__WEBPACK_IMPORTED_MODULE_1__
+        );
+
+      const DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
+        () =>
+          __webpack_require__
+            .e(/* import() */ 9573)
+            .then(__webpack_require__.bind(__webpack_require__, 9573))
+            .then((mod) => mod.Hello),
+        {
+          loadableGenerated: {
+            webpack: () => [/*require.resolve*/ 9573],
+          },
+        }
       );
-      const LoadableContext = _react.default.createContext(null);
-      if (false) {
-      } //# sourceMappingURL=loadable-context.shared-runtime.js.map
+      const Page = () =>
+        /*#__PURE__*/ (0, react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)(
+          react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.Fragment,
+          {
+            children: [
+              /*#__PURE__*/ (0,
+              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("p", {
+                children: "testing next/dynamic size",
+              }),
+              /*#__PURE__*/ (0,
+              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
+                DynamicHello,
+                {}
+              ),
+            ],
+          }
+        );
+      var __N_SSP = true;
+      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = Page;
 
       /***/
     },
@@ -524,7 +524,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(1033)
+      __webpack_exec__(431)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>edge-ssr-HASH.js</strong></summary>

```diff
@@ -1,24 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [676],
   {
-    /***/ 1819: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/edge-ssr",
-        function () {
-          return __webpack_require__(7521);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 7521: /***/ (
+    /***/ 983: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -37,13 +20,30 @@
 
       /***/
     },
+
+    /***/ 985: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/edge-ssr",
+        function () {
+          return __webpack_require__(983);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(1819)
+      __webpack_exec__(985)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>head-HASH.js</strong></summary>

```diff
@@ -1,34 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [5350],
   {
-    /***/ 619: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/head",
-        function () {
-          return __webpack_require__(9891);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 7997: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(6705);
-
-      /***/
-    },
-
-    /***/ 9891: /***/ (
+    /***/ 1417: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -43,7 +16,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(1503);
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(7997);
+        __webpack_require__(5171);
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_head__WEBPACK_IMPORTED_MODULE_1__
@@ -76,13 +49,40 @@
 
       /***/
     },
+
+    /***/ 1937: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/head",
+        function () {
+          return __webpack_require__(1417);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 5171: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(7505);
+
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(619)
+      __webpack_exec__(1937)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>hooks-HASH.js</strong></summary>

```diff
@@ -1,24 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [9804],
   {
-    /***/ 1679: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/hooks",
-        function () {
-          return __webpack_require__(4655);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 4655: /***/ (
+    /***/ 1598: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -76,13 +59,30 @@
 
       /***/
     },
+
+    /***/ 3925: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/hooks",
+        function () {
+          return __webpack_require__(1598);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(1679)
+      __webpack_exec__(3925)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -1,7 +1,338 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [4672],
   {
-    /***/ 69: /***/ (module, exports, __webpack_require__) => {
+    /***/ 1511: /***/ (module, exports, __webpack_require__) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "useMergedRef", {
+        enumerable: true,
+        get: function () {
+          return useMergedRef;
+        },
+      });
+      const _react = __webpack_require__(2223);
+      function useMergedRef(refA, refB) {
+        const cleanupA = (0, _react.useRef)(null);
+        const cleanupB = (0, _react.useRef)(null);
+        // NOTE: In theory, we could skip the wrapping if only one of the refs is non-null.
+        // (this happens often if the user doesn't pass a ref to Link/Form/Image)
+        // But this can cause us to leak a cleanup-ref into user code (previously via `<Link legacyBehavior>`),
+        // and the user might pass that ref into ref-merging library that doesn't support cleanup refs
+        // (because it hasn't been updated for React 19)
+        // which can then cause things to blow up, because a cleanup-returning ref gets called with `null`.
+        // So in practice, it's safer to be defensive and always wrap the ref, even on React 19.
+        return (0, _react.useCallback)(
+          (current) => {
+            if (current === null) {
+              const cleanupFnA = cleanupA.current;
+              if (cleanupFnA) {
+                cleanupA.current = null;
+                cleanupFnA();
+              }
+              const cleanupFnB = cleanupB.current;
+              if (cleanupFnB) {
+                cleanupB.current = null;
+                cleanupFnB();
+              }
+            } else {
+              if (refA) {
+                cleanupA.current = applyRef(refA, current);
+              }
+              if (refB) {
+                cleanupB.current = applyRef(refB, current);
+              }
+            }
+          },
+          [refA, refB]
+        );
+      }
+      function applyRef(refA, current) {
+        if (typeof refA === "function") {
+          const cleanup = refA(current);
+          if (typeof cleanup === "function") {
+            return cleanup;
+          } else {
+            return () => refA(null);
+          }
+        } else {
+          refA.current = current;
+          return () => {
+            refA.current = null;
+          };
+        }
+      }
+      if (
+        (typeof exports.default === "function" ||
+          (typeof exports.default === "object" && exports.default !== null)) &&
+        typeof exports.default.__esModule === "undefined"
+      ) {
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true,
+        });
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
+      } //# sourceMappingURL=use-merged-ref.js.map
+
+      /***/
+    },
+
+    /***/ 2025: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/link",
+        function () {
+          return __webpack_require__(4591);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 3267: /***/ (module, exports, __webpack_require__) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "getDomainLocale", {
+        enumerable: true,
+        get: function () {
+          return getDomainLocale;
+        },
+      });
+      const _normalizetrailingslash = __webpack_require__(2371);
+      const basePath =
+        /* unused pure expression or super */ null && (false || "");
+      function getDomainLocale(path, locale, locales, domainLocales) {
+        if (false) {
+        } else {
+          return false;
+        }
+      }
+      if (
+        (typeof exports.default === "function" ||
+          (typeof exports.default === "object" && exports.default !== null)) &&
+        typeof exports.default.__esModule === "undefined"
+      ) {
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true,
+        });
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
+      } //# sourceMappingURL=get-domain-locale.js.map
+
+      /***/
+    },
+
+    /***/ 4591: /***/ (
+      __unused_webpack_module,
+      __webpack_exports__,
+      __webpack_require__
+    ) => {
+      "use strict";
+      __webpack_require__.r(__webpack_exports__);
+      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
+        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
+        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
+        /* harmony export */
+      });
+      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
+        __webpack_require__(1503);
+      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ =
+        __webpack_require__(6929);
+      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default =
+        /*#__PURE__*/ __webpack_require__.n(
+          next_link__WEBPACK_IMPORTED_MODULE_1__
+        );
+
+      function aLink(props) {
+        return /*#__PURE__*/ (0,
+        react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)("div", {
+          children: [
+            /*#__PURE__*/ (0,
+            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("h3", {
+              children: "A Link page!",
+            }),
+            /*#__PURE__*/ (0,
+            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
+              next_link__WEBPACK_IMPORTED_MODULE_1___default(),
+              {
+                href: "/",
+                children: "Go to /",
+              }
+            ),
+          ],
+        });
+      }
+      var __N_SSP = true;
+      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = aLink;
+
+      /***/
+    },
+
+    /***/ 6929: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(8885);
+
+      /***/
+    },
+
+    /***/ 7686: /***/ (module, exports, __webpack_require__) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "useIntersection", {
+        enumerable: true,
+        get: function () {
+          return useIntersection;
+        },
+      });
+      const _react = __webpack_require__(2223);
+      const _requestidlecallback = __webpack_require__(901);
+      const hasIntersectionObserver =
+        typeof IntersectionObserver === "function";
+      const observers = new Map();
+      const idList = [];
+      function createObserver(options) {
+        const id = {
+          root: options.root || null,
+          margin: options.rootMargin || "",
+        };
+        const existing = idList.find(
+          (obj) => obj.root === id.root && obj.margin === id.margin
+        );
+        let instance;
+        if (existing) {
+          instance = observers.get(existing);
+          if (instance) {
+            return instance;
+          }
+        }
+        const elements = new Map();
+        const observer = new IntersectionObserver((entries) => {
+          entries.forEach((entry) => {
+            const callback = elements.get(entry.target);
+            const isVisible =
+              entry.isIntersecting || entry.intersectionRatio > 0;
+            if (callback && isVisible) {
+              callback(isVisible);
+            }
+          });
+        }, options);
+        instance = {
+          id,
+          observer,
+          elements,
+        };
+        idList.push(id);
+        observers.set(id, instance);
+        return instance;
+      }
+      function observe(element, callback, options) {
+        const { id, observer, elements } = createObserver(options);
+        elements.set(element, callback);
+        observer.observe(element);
+        return function unobserve() {
+          elements.delete(element);
+          observer.unobserve(element);
+          // Destroy observer when there's nothing left to watch:
+          if (elements.size === 0) {
+            observer.disconnect();
+            observers.delete(id);
+            const index = idList.findIndex(
+              (obj) => obj.root === id.root && obj.margin === id.margin
+            );
+            if (index > -1) {
+              idList.splice(index, 1);
+            }
+          }
+        };
+      }
+      function useIntersection({ rootRef, rootMargin, disabled }) {
+        const isDisabled = disabled || !hasIntersectionObserver;
+        const [visible, setVisible] = (0, _react.useState)(false);
+        const elementRef = (0, _react.useRef)(null);
+        const setElement = (0, _react.useCallback)((element) => {
+          elementRef.current = element;
+        }, []);
+        (0, _react.useEffect)(() => {
+          if (hasIntersectionObserver) {
+            if (isDisabled || visible) return;
+            const element = elementRef.current;
+            if (element && element.tagName) {
+              const unobserve = observe(
+                element,
+                (isVisible) => isVisible && setVisible(isVisible),
+                {
+                  root: rootRef?.current,
+                  rootMargin,
+                }
+              );
+              return unobserve;
+            }
+          } else {
+            if (!visible) {
+              const idleCallback = (0,
+              _requestidlecallback.requestIdleCallback)(() => setVisible(true));
+              return () =>
+                (0, _requestidlecallback.cancelIdleCallback)(idleCallback);
+            }
+          }
+          // eslint-disable-next-line react-hooks/exhaustive-deps
+        }, [isDisabled, rootMargin, rootRef, visible, elementRef.current]);
+        const resetVisible = (0, _react.useCallback)(() => {
+          setVisible(false);
+        }, []);
+        return [setElement, visible, resetVisible];
+      }
+      if (
+        (typeof exports.default === "function" ||
+          (typeof exports.default === "object" && exports.default !== null)) &&
+        typeof exports.default.__esModule === "undefined"
+      ) {
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true,
+        });
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
+      } //# sourceMappingURL=use-intersection.js.map
+
+      /***/
+    },
+
+    /***/ 8101: /***/ (__unused_webpack_module, exports) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "errorOnce", {
+        enumerable: true,
+        get: function () {
+          return errorOnce;
+        },
+      });
+      let errorOnce = (_) => {};
+      if (false) {
+      } //# sourceMappingURL=error-once.js.map
+
+      /***/
+    },
+
+    /***/ 8885: /***/ (module, exports, __webpack_require__) => {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -28,17 +359,17 @@
       const _react = /*#__PURE__*/ _interop_require_wildcard._(
         __webpack_require__(2223)
       );
-      const _resolvehref = __webpack_require__(2275);
-      const _islocalurl = __webpack_require__(3179);
-      const _formaturl = __webpack_require__(5486);
-      const _utils = __webpack_require__(3708);
-      const _addlocale = __webpack_require__(8225);
-      const _routercontextsharedruntime = __webpack_require__(6046);
-      const _useintersection = __webpack_require__(2678);
-      const _getdomainlocale = __webpack_require__(4499);
-      const _addbasepath = __webpack_require__(7434);
-      const _usemergedref = __webpack_require__(2263);
-      const _erroronce = __webpack_require__(2197);
+      const _resolvehref = __webpack_require__(7379);
+      const _islocalurl = __webpack_require__(4843);
+      const _formaturl = __webpack_require__(9374);
+      const _utils = __webpack_require__(3116);
+      const _addlocale = __webpack_require__(8065);
+      const _routercontextsharedruntime = __webpack_require__(5470);
+      const _useintersection = __webpack_require__(7686);
+      const _getdomainlocale = __webpack_require__(3267);
+      const _addbasepath = __webpack_require__(1450);
+      const _usemergedref = __webpack_require__(1511);
+      const _erroronce = __webpack_require__(8101);
       const prefetched = new Set();
       function prefetch(router, href, as, options) {
         if (false) {
@@ -416,344 +747,13 @@
 
       /***/
     },
-
-    /***/ 2197: /***/ (__unused_webpack_module, exports) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "errorOnce", {
-        enumerable: true,
-        get: function () {
-          return errorOnce;
-        },
-      });
-      let errorOnce = (_) => {};
-      if (false) {
-      } //# sourceMappingURL=error-once.js.map
-
-      /***/
-    },
-
-    /***/ 2263: /***/ (module, exports, __webpack_require__) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "useMergedRef", {
-        enumerable: true,
-        get: function () {
-          return useMergedRef;
-        },
-      });
-      const _react = __webpack_require__(2223);
-      function useMergedRef(refA, refB) {
-        const cleanupA = (0, _react.useRef)(null);
-        const cleanupB = (0, _react.useRef)(null);
-        // NOTE: In theory, we could skip the wrapping if only one of the refs is non-null.
-        // (this happens often if the user doesn't pass a ref to Link/Form/Image)
-        // But this can cause us to leak a cleanup-ref into user code (previously via `<Link legacyBehavior>`),
-        // and the user might pass that ref into ref-merging library that doesn't support cleanup refs
-        // (because it hasn't been updated for React 19)
-        // which can then cause things to blow up, because a cleanup-returning ref gets called with `null`.
-        // So in practice, it's safer to be defensive and always wrap the ref, even on React 19.
-        return (0, _react.useCallback)(
-          (current) => {
-            if (current === null) {
-              const cleanupFnA = cleanupA.current;
-              if (cleanupFnA) {
-                cleanupA.current = null;
-                cleanupFnA();
-              }
-              const cleanupFnB = cleanupB.current;
-              if (cleanupFnB) {
-                cleanupB.current = null;
-                cleanupFnB();
-              }
-            } else {
-              if (refA) {
-                cleanupA.current = applyRef(refA, current);
-              }
-              if (refB) {
-                cleanupB.current = applyRef(refB, current);
-              }
-            }
-          },
-          [refA, refB]
-        );
-      }
-      function applyRef(refA, current) {
-        if (typeof refA === "function") {
-          const cleanup = refA(current);
-          if (typeof cleanup === "function") {
-            return cleanup;
-          } else {
-            return () => refA(null);
-          }
-        } else {
-          refA.current = current;
-          return () => {
-            refA.current = null;
-          };
-        }
-      }
-      if (
-        (typeof exports.default === "function" ||
-          (typeof exports.default === "object" && exports.default !== null)) &&
-        typeof exports.default.__esModule === "undefined"
-      ) {
-        Object.defineProperty(exports.default, "__esModule", {
-          value: true,
-        });
-        Object.assign(exports.default, exports);
-        module.exports = exports.default;
-      } //# sourceMappingURL=use-merged-ref.js.map
-
-      /***/
-    },
-
-    /***/ 2369: /***/ (
-      __unused_webpack_module,
-      __webpack_exports__,
-      __webpack_require__
-    ) => {
-      "use strict";
-      __webpack_require__.r(__webpack_exports__);
-      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
-        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
-        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
-        /* harmony export */
-      });
-      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(1503);
-      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(6691);
-      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default =
-        /*#__PURE__*/ __webpack_require__.n(
-          next_link__WEBPACK_IMPORTED_MODULE_1__
-        );
-
-      function aLink(props) {
-        return /*#__PURE__*/ (0,
-        react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)("div", {
-          children: [
-            /*#__PURE__*/ (0,
-            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("h3", {
-              children: "A Link page!",
-            }),
-            /*#__PURE__*/ (0,
-            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
-              next_link__WEBPACK_IMPORTED_MODULE_1___default(),
-              {
-                href: "/",
-                children: "Go to /",
-              }
-            ),
-          ],
-        });
-      }
-      var __N_SSP = true;
-      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = aLink;
-
-      /***/
-    },
-
-    /***/ 2678: /***/ (module, exports, __webpack_require__) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "useIntersection", {
-        enumerable: true,
-        get: function () {
-          return useIntersection;
-        },
-      });
-      const _react = __webpack_require__(2223);
-      const _requestidlecallback = __webpack_require__(4213);
-      const hasIntersectionObserver =
-        typeof IntersectionObserver === "function";
-      const observers = new Map();
-      const idList = [];
-      function createObserver(options) {
-        const id = {
-          root: options.root || null,
-          margin: options.rootMargin || "",
-        };
-        const existing = idList.find(
-          (obj) => obj.root === id.root && obj.margin === id.margin
-        );
-        let instance;
-        if (existing) {
-          instance = observers.get(existing);
-          if (instance) {
-            return instance;
-          }
-        }
-        const elements = new Map();
-        const observer = new IntersectionObserver((entries) => {
-          entries.forEach((entry) => {
-            const callback = elements.get(entry.target);
-            const isVisible =
-              entry.isIntersecting || entry.intersectionRatio > 0;
-            if (callback && isVisible) {
-              callback(isVisible);
-            }
-          });
-        }, options);
-        instance = {
-          id,
-          observer,
-          elements,
-        };
-        idList.push(id);
-        observers.set(id, instance);
-        return instance;
-      }
-      function observe(element, callback, options) {
-        const { id, observer, elements } = createObserver(options);
-        elements.set(element, callback);
-        observer.observe(element);
-        return function unobserve() {
-          elements.delete(element);
-          observer.unobserve(element);
-          // Destroy observer when there's nothing left to watch:
-          if (elements.size === 0) {
-            observer.disconnect();
-            observers.delete(id);
-            const index = idList.findIndex(
-              (obj) => obj.root === id.root && obj.margin === id.margin
-            );
-            if (index > -1) {
-              idList.splice(index, 1);
-            }
-          }
-        };
-      }
-      function useIntersection({ rootRef, rootMargin, disabled }) {
-        const isDisabled = disabled || !hasIntersectionObserver;
-        const [visible, setVisible] = (0, _react.useState)(false);
-        const elementRef = (0, _react.useRef)(null);
-        const setElement = (0, _react.useCallback)((element) => {
-          elementRef.current = element;
-        }, []);
-        (0, _react.useEffect)(() => {
-          if (hasIntersectionObserver) {
-            if (isDisabled || visible) return;
-            const element = elementRef.current;
-            if (element && element.tagName) {
-              const unobserve = observe(
-                element,
-                (isVisible) => isVisible && setVisible(isVisible),
-                {
-                  root: rootRef?.current,
-                  rootMargin,
-                }
-              );
-              return unobserve;
-            }
-          } else {
-            if (!visible) {
-              const idleCallback = (0,
-              _requestidlecallback.requestIdleCallback)(() => setVisible(true));
-              return () =>
-                (0, _requestidlecallback.cancelIdleCallback)(idleCallback);
-            }
-          }
-          // eslint-disable-next-line react-hooks/exhaustive-deps
-        }, [isDisabled, rootMargin, rootRef, visible, elementRef.current]);
-        const resetVisible = (0, _react.useCallback)(() => {
-          setVisible(false);
-        }, []);
-        return [setElement, visible, resetVisible];
-      }
-      if (
-        (typeof exports.default === "function" ||
-          (typeof exports.default === "object" && exports.default !== null)) &&
-        typeof exports.default.__esModule === "undefined"
-      ) {
-        Object.defineProperty(exports.default, "__esModule", {
-          value: true,
-        });
-        Object.assign(exports.default, exports);
-        module.exports = exports.default;
-      } //# sourceMappingURL=use-intersection.js.map
-
-      /***/
-    },
-
-    /***/ 4499: /***/ (module, exports, __webpack_require__) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "getDomainLocale", {
-        enumerable: true,
-        get: function () {
-          return getDomainLocale;
-        },
-      });
-      const _normalizetrailingslash = __webpack_require__(1379);
-      const basePath =
-        /* unused pure expression or super */ null && (false || "");
-      function getDomainLocale(path, locale, locales, domainLocales) {
-        if (false) {
-        } else {
-          return false;
-        }
-      }
-      if (
-        (typeof exports.default === "function" ||
-          (typeof exports.default === "object" && exports.default !== null)) &&
-        typeof exports.default.__esModule === "undefined"
-      ) {
-        Object.defineProperty(exports.default, "__esModule", {
-          value: true,
-        });
-        Object.assign(exports.default, exports);
-        module.exports = exports.default;
-      } //# sourceMappingURL=get-domain-locale.js.map
-
-      /***/
-    },
-
-    /***/ 6691: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(69);
-
-      /***/
-    },
-
-    /***/ 6771: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/link",
-        function () {
-          return __webpack_require__(2369);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(6771)
+      __webpack_exec__(2025)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>routerDirect-HASH.js</strong></summary>

```diff
@@ -1,7 +1,34 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [188],
   {
-    /***/ 97: /***/ (
+    /***/ 417: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/routerDirect",
+        function () {
+          return __webpack_require__(5491);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 1840: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(3252);
+
+      /***/
+    },
+
+    /***/ 5491: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -16,7 +43,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(1503);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(7798);
+        __webpack_require__(1840);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_router__WEBPACK_IMPORTED_MODULE_1__
@@ -35,40 +62,13 @@
 
       /***/
     },
-
-    /***/ 4283: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/routerDirect",
-        function () {
-          return __webpack_require__(97);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 7798: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(9300);
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(4283)
+      __webpack_exec__(417)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>script-HASH.js</strong></summary>

```diff
@@ -1,17 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [1209],
   {
-    /***/ 5964: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(2010);
-
-      /***/
-    },
-
-    /***/ 7758: /***/ (
+    /***/ 1312: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -26,7 +16,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(1503);
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(5964);
+        __webpack_require__(2398);
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_script__WEBPACK_IMPORTED_MODULE_1__
@@ -59,7 +49,17 @@
       /***/
     },
 
-    /***/ 8803: /***/ (
+    /***/ 2398: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(8954);
+
+      /***/
+    },
+
+    /***/ 4305: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -67,7 +67,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/script",
         function () {
-          return __webpack_require__(7758);
+          return __webpack_require__(1312);
         },
       ]);
       if (false) {
@@ -81,7 +81,7 @@
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(8803)
+      __webpack_exec__(4305)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>withRouter-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [3263],
   {
-    /***/ 184: /***/ (
+    /***/ 358: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -16,7 +16,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(1503);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(7798);
+        __webpack_require__(1840);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_router__WEBPACK_IMPORTED_MODULE_1__
@@ -35,7 +35,17 @@
       /***/
     },
 
-    /***/ 3163: /***/ (
+    /***/ 1840: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(3252);
+
+      /***/
+    },
+
+    /***/ 4041: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -43,7 +53,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/withRouter",
         function () {
-          return __webpack_require__(184);
+          return __webpack_require__(358);
         },
       ]);
       if (false) {
@@ -51,23 +61,13 @@
 
       /***/
     },
-
-    /***/ 7798: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(9300);
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(3163)
+      __webpack_exec__(4041)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>4292-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>436-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>9760-HASH.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>c57d0559-HASH.js</strong></summary>

```diff
@@ -1,13 +1,13 @@
 "use strict";
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
-  [9137],
+  [2494],
   {
-    /***/ 739: /***/ (
+    /***/ 8313: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
     ) => {
-      /* provided dependency */ var process = __webpack_require__(9136);
+      /* provided dependency */ var process = __webpack_require__(6454);
       /**
        * @license React
        * react-dom-client.production.js
@@ -22,9 +22,9 @@
  Modernizr 3.0.0pre (Custom Build) | MIT
 */
 
-      var Scheduler = __webpack_require__(3113),
-        React = __webpack_require__(1260),
-        ReactDOM = __webpack_require__(3869);
+      var Scheduler = __webpack_require__(6583),
+        React = __webpack_require__(1774),
+        ReactDOM = __webpack_require__(7499);
       function formatProdErrorMessage(code) {
         var url = "https://react.dev/errors/" + code;
         if (1 < arguments.length) {
@@ -14151,6 +14151,16 @@
           ? actionProp
           : sanitizeURL("" + actionProp);
       }
+      function createFormDataWithSubmitter(form, submitter) {
+        var temp = submitter.ownerDocument.createElement("input");
+        temp.name = submitter.name;
+        temp.value = submitter.value;
+        form.id && temp.setAttribute("form", form.id);
+        submitter.parentNode.insertBefore(temp, submitter);
+        form = new FormData(form);
+        temp.parentNode.removeChild(temp);
+        return form;
+      }
       function extractEvents$1(
         dispatchQueue,
         domEventName,
@@ -14189,7 +14199,12 @@
                 listener: function () {
                   if (nativeEvent.defaultPrevented) {
                     if (0 !== currentEventTransitionLane) {
-                      var formData = new FormData(nativeEventTarget, submitter);
+                      var formData = submitter
+                        ? createFormDataWithSubmitter(
+                            nativeEventTarget,
+                            submitter
+                          )
+                        : new FormData(nativeEventTarget);
                       startHostTransition(
                         maybeTargetInst,
                         {
@@ -14205,7 +14220,12 @@
                   } else
                     "function" === typeof action &&
                       (event.preventDefault(),
-                      (formData = new FormData(nativeEventTarget, submitter)),
+                      (formData = submitter
+                        ? createFormDataWithSubmitter(
+                            nativeEventTarget,
+                            submitter
+                          )
+                        : new FormData(nativeEventTarget)),
                       startHostTransition(
                         maybeTargetInst,
                         {
@@ -16514,7 +16534,6 @@
             types: transitionTypes,
           });
           ownerDocument.__reactViewTransition = transition;
-          var viewTransitionAnimations = [];
           transition.ready.then(
             function () {
               for (
@@ -16525,26 +16544,25 @@
                 i < animations.length;
                 i++
               ) {
-                var animation = animations[i],
-                  effect = animation.effect,
+                var effect = animations[i].effect,
                   pseudoElement = effect.pseudoElement;
                 if (
                   null != pseudoElement &&
                   pseudoElement.startsWith("::view-transition")
                 ) {
-                  viewTransitionAnimations.push(animation);
-                  animation = effect.getKeyframes();
+                  pseudoElement = effect.getKeyframes();
                   for (
-                    var height = (pseudoElement = void 0),
+                    var width = void 0,
+                      height = void 0,
                       unchangedDimensions = !0,
                       j = 0;
-                    j < animation.length;
+                    j < pseudoElement.length;
                     j++
                   ) {
-                    var keyframe = animation[j],
+                    var keyframe = pseudoElement[j],
                       w = keyframe.width;
-                    if (void 0 === pseudoElement) pseudoElement = w;
-                    else if (pseudoElement !== w) {
+                    if (void 0 === width) width = w;
+                    else if (width !== w) {
                       unchangedDimensions = !1;
                       break;
                     }
@@ -16559,22 +16577,23 @@
                     "none" === keyframe.transform && delete keyframe.transform;
                   }
                   unchangedDimensions &&
-                    void 0 !== pseudoElement &&
+                    void 0 !== width &&
                     void 0 !== height &&
-                    (effect.setKeyframes(animation),
+                    (effect.setKeyframes(pseudoElement),
                     (unchangedDimensions = getComputedStyle(
                       effect.target,
                       effect.pseudoElement
                     )),
-                    unchangedDimensions.width !== pseudoElement ||
+                    unchangedDimensions.width !== width ||
                       unchangedDimensions.height !== height) &&
-                    ((unchangedDimensions = animation[0]),
-                    (unchangedDimensions.width = pseudoElement),
+                    ((unchangedDimensions = pseudoElement[0]),
+                    (unchangedDimensions.width = width),
                     (unchangedDimensions.height = height),
-                    (unchangedDimensions = animation[animation.length - 1]),
-                    (unchangedDimensions.width = pseudoElement),
+                    (unchangedDimensions =
+                      pseudoElement[pseudoElement.length - 1]),
+                    (unchangedDimensions.width = width),
                     (unchangedDimensions.height = height),
-                    effect.setKeyframes(animation));
+                    effect.setKeyframes(pseudoElement));
                 }
               }
               spawnedWorkCallback();
@@ -16605,8 +16624,21 @@
             }
           );
           transition.finished.finally(function () {
-            for (var i = 0; i < viewTransitionAnimations.length; i++)
-              viewTransitionAnimations[i].cancel();
+            for (
+              var scope = ownerDocument.documentElement,
+                animations = scope.getAnimations({ subtree: !0 }),
+                i = 0;
+              i < animations.length;
+              i++
+            ) {
+              var anim = animations[i],
+                effect = anim.effect,
+                pseudo = effect.pseudoElement;
+              null != pseudo &&
+                pseudo.startsWith("::view-transition") &&
+                effect.target === scope &&
+                anim.cancel();
+            }
             ownerDocument.__reactViewTransition === transition &&
               (ownerDocument.__reactViewTransition = null);
             passiveCallback();
@@ -19116,16 +19148,16 @@
           0 === i && attemptExplicitHydrationTarget(target);
         }
       };
-      var isomorphicReactPackageVersion$jscomp$inline_2040 = React.version;
+      var isomorphicReactPackageVersion$jscomp$inline_2047 = React.version;
       if (
-        "19.3.0-canary-65eec428-20251218" !==
-        isomorphicReactPackageVersion$jscomp$inline_2040
+        "19.3.0-canary-fd524fe0-20251121" !==
+        isomorphicReactPackageVersion$jscomp$inline_2047
       )
         throw Error(
           formatProdErrorMessage(
             527,
-            isomorphicReactPackageVersion$jscomp$inline_2040,
-            "19.3.0-canary-65eec428-20251218"
+            isomorphicReactPackageVersion$jscomp$inline_2047,
+            "19.3.0-canary-fd524fe0-20251121"
           )
         );
       ReactDOMSharedInternals.findDOMNode = function (componentOrElement) {
@@ -19145,24 +19177,24 @@
           null === componentOrElement ? null : componentOrElement.stateNode;
         return componentOrElement;
       };
-      var internals$jscomp$inline_2628 = {
+      var internals$jscomp$inline_2635 = {
         bundleType: 0,
-        version: "19.3.0-canary-65eec428-20251218",
+        version: "19.3.0-canary-fd524fe0-20251121",
         rendererPackageName: "react-dom",
         currentDispatcherRef: ReactSharedInternals,
-        reconcilerVersion: "19.3.0-canary-65eec428-20251218",
+        reconcilerVersion: "19.3.0-canary-fd524fe0-20251121",
       };
       if ("undefined" !== typeof __REACT_DEVTOOLS_GLOBAL_HOOK__) {
-        var hook$jscomp$inline_2629 = __REACT_DEVTOOLS_GLOBAL_HOOK__;
+        var hook$jscomp$inline_2636 = __REACT_DEVTOOLS_GLOBAL_HOOK__;
         if (
-          !hook$jscomp$inline_2629.isDisabled &&
-          hook$jscomp$inline_2629.supportsFiber
+          !hook$jscomp$inline_2636.isDisabled &&
+          hook$jscomp$inline_2636.supportsFiber
         )
           try {
-            (rendererID = hook$jscomp$inline_2629.inject(
-              internals$jscomp$inline_2628
+            (rendererID = hook$jscomp$inline_2636.inject(
+              internals$jscomp$inline_2635
             )),
-              (injectedHook = hook$jscomp$inline_2629);
+              (injectedHook = hook$jscomp$inline_2636);
           } catch (err) {}
       }
       exports.createRoot = function (container, options) {
@@ -19252,7 +19284,7 @@
         listenToAllSupportedEvents(container);
         return new ReactDOMHydrationRoot(initialChildren);
       };
-      exports.version = "19.3.0-canary-65eec428-20251218";
+      exports.version = "19.3.0-canary-fd524fe0-20251121";
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page-exp..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..ntime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..ntime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page.runtime.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.ru..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>dist_client_..ntime.dev.js</strong></summary>

```diff
@@ -1,2 +1,2 @@
-"use strict";exports.ids=["dist_client_dev_noop-turbopack-hmr_js"],exports.modules={"./dist/client/dev/noop-turbopack-hmr.js"(module,exports1){function connect(){}Object.defineProperty(exports1,"__esModule",{value:!0}),Object.defineProperty(exports1,"connect",{enumerable:!0,get:function(){return connect}}),("function"==typeof exports1.default||"object"==typeof exports1.default&&null!==exports1.default)&&void 0===exports1.default.__esModule&&(Object.defineProperty(exports1.default,"__esModule",{value:!0}),Object.assign(exports1.default,exports1),module.exports=exports1.default)}};
+"use strict";exports.ids=["dist_client_dev_noop-turbopack-hmr_js"],exports.modules={"./dist/client/dev/noop-turbopack-hmr.js":function(module,exports1){function connect(){}Object.defineProperty(exports1,"__esModule",{value:!0}),Object.defineProperty(exports1,"connect",{enumerable:!0,get:function(){return connect}}),("function"==typeof exports1.default||"object"==typeof exports1.default&&null!==exports1.default)&&void 0===exports1.default.__esModule&&(Object.defineProperty(exports1.default,"__esModule",{value:!0}),Object.assign(exports1.default,exports1),module.exports=exports1.default)}};
 //# sourceMappingURL=dist_client_dev_noop-turbopack-hmr_js-experimental.runtime.dev.js.map
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>dist_client_..ntime.dev.js</strong></summary>

```diff
@@ -1,2 +1,2 @@
-"use strict";exports.ids=["dist_client_dev_noop-turbopack-hmr_js"],exports.modules={"./dist/client/dev/noop-turbopack-hmr.js"(module,exports1){function connect(){}Object.defineProperty(exports1,"__esModule",{value:!0}),Object.defineProperty(exports1,"connect",{enumerable:!0,get:function(){return connect}}),("function"==typeof exports1.default||"object"==typeof exports1.default&&null!==exports1.default)&&void 0===exports1.default.__esModule&&(Object.defineProperty(exports1.default,"__esModule",{value:!0}),Object.assign(exports1.default,exports1),module.exports=exports1.default)}};
+"use strict";exports.ids=["dist_client_dev_noop-turbopack-hmr_js"],exports.modules={"./dist/client/dev/noop-turbopack-hmr.js":function(module,exports1){function connect(){}Object.defineProperty(exports1,"__esModule",{value:!0}),Object.defineProperty(exports1,"connect",{enumerable:!0,get:function(){return connect}}),("function"==typeof exports1.default||"object"==typeof exports1.default&&null!==exports1.default)&&void 0===exports1.default.__esModule&&(Object.defineProperty(exports1.default,"__esModule",{value:!0}),Object.assign(exports1.default,exports1),module.exports=exports1.default)}};
 //# sourceMappingURL=dist_client_dev_noop-turbopack-hmr_js-turbo-experimental.runtime.dev.js.map
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>dist_client_..ntime.dev.js</strong></summary>

```diff
@@ -1,2 +1,2 @@
-"use strict";exports.ids=["dist_client_dev_noop-turbopack-hmr_js"],exports.modules={"./dist/client/dev/noop-turbopack-hmr.js"(module,exports1){function connect(){}Object.defineProperty(exports1,"__esModule",{value:!0}),Object.defineProperty(exports1,"connect",{enumerable:!0,get:function(){return connect}}),("function"==typeof exports1.default||"object"==typeof exports1.default&&null!==exports1.default)&&void 0===exports1.default.__esModule&&(Object.defineProperty(exports1.default,"__esModule",{value:!0}),Object.assign(exports1.default,exports1),module.exports=exports1.default)}};
+"use strict";exports.ids=["dist_client_dev_noop-turbopack-hmr_js"],exports.modules={"./dist/client/dev/noop-turbopack-hmr.js":function(module,exports1){function connect(){}Object.defineProperty(exports1,"__esModule",{value:!0}),Object.defineProperty(exports1,"connect",{enumerable:!0,get:function(){return connect}}),("function"==typeof exports1.default||"object"==typeof exports1.default&&null!==exports1.default)&&void 0===exports1.default.__esModule&&(Object.defineProperty(exports1.default,"__esModule",{value:!0}),Object.assign(exports1.default,exports1),module.exports=exports1.default)}};
 //# sourceMappingURL=dist_client_dev_noop-turbopack-hmr_js-turbo.runtime.dev.js.map
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>dist_client_..ntime.dev.js</strong></summary>

```diff
@@ -1,2 +1,2 @@
-"use strict";exports.ids=["dist_client_dev_noop-turbopack-hmr_js"],exports.modules={"./dist/client/dev/noop-turbopack-hmr.js"(module,exports1){function connect(){}Object.defineProperty(exports1,"__esModule",{value:!0}),Object.defineProperty(exports1,"connect",{enumerable:!0,get:function(){return connect}}),("function"==typeof exports1.default||"object"==typeof exports1.default&&null!==exports1.default)&&void 0===exports1.default.__esModule&&(Object.defineProperty(exports1.default,"__esModule",{value:!0}),Object.assign(exports1.default,exports1),module.exports=exports1.default)}};
+"use strict";exports.ids=["dist_client_dev_noop-turbopack-hmr_js"],exports.modules={"./dist/client/dev/noop-turbopack-hmr.js":function(module,exports1){function connect(){}Object.defineProperty(exports1,"__esModule",{value:!0}),Object.defineProperty(exports1,"connect",{enumerable:!0,get:function(){return connect}}),("function"==typeof exports1.default||"object"==typeof exports1.default&&null!==exports1.default)&&void 0===exports1.default.__esModule&&(Object.defineProperty(exports1.default,"__esModule",{value:!0}),Object.assign(exports1.default,exports1),module.exports=exports1.default)}};
 //# sourceMappingURL=dist_client_dev_noop-turbopack-hmr_js.runtime.dev.js.map
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>pages-api-tu..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-api-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-api.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-api.ru..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-turbo...ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-turbo...time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 942f01d7aa94b8e55cac6b6735ab0854549fe4a4

File: packages/next/src/server/image-optimizer.ts [hunk 1]
```diff
@@ -795,9 +795,12 @@ export async function fetchInternalImage(
   ) => Promise<void>
 ): Promise<ImageUpstream> {
   try {
+    // Coerce HEAD to GET to avoid issues with the image optimizer
+    const method = _req.method === 'HEAD' ? 'GET' : _req.method
+
     const mocked = createRequestResponseMocks({
       url: href,
-      method: _req.method || 'GET',
+      method: method || 'GET',
```
Comment (styfle) [inline packages/next/src/server/image-optimizer.ts]:
```suggestion
    const method = (!_req.method || _req.method === 'HEAD') ? 'GET' : _req.method

    const mocked = createRequestResponseMocks({
      url: href,
      method,
```

Can do this in one line

File: test/e2e/app-dir/next-image/next-image.test.ts [hunk 2]
```diff
@@ -11,6 +11,17 @@ describe('app dir - next-image', () => {
...
   describe('ssr content', () => {
+    it('should handle HEAD requests for uncached images', async () => {
+      // Run this test first to ensure the image cache is empty
+      const $ = await next.render$('/')
+      const imageUrl = $('#app-layout').attr('src')
+
+      // With an empty cache, HEAD requests should return 200
+      const headRes = await next.fetch(imageUrl, { method: 'HEAD' })
+      expect(headRes.status).toBe(200)
+      expect(headRes.headers.get('content-type')).toMatch(/^image\//)
```
Comment (styfle) [inline test/e2e/app-dir/next-image/next-image.test.ts:25]: I think you need to do two requests sequentially - one for HEAD followed by one for GET.

The HEAD should return 0 byte body and the GET should return the actual image in the body.

Comment (styfle) [reply test/e2e/app-dir/next-image/next-image.test.ts:25]: See the tests in `test/integration/image-optimizer/test/util.ts` which test the cache directory output too. Like this:

https://github.com/vercel/next.js/blob/8d415853f73c72263d24be3ea92b497d41f242f0/test/integration/image-optimizer/test/util.ts#L1313

File: test/e2e/app-dir/next-image/next-image.test.ts [hunk 3]
```diff
@@ -11,6 +13,34 @@ describe('app dir - next-image', () => {
   }
 
   describe('ssr content', () => {
+    it('should handle HEAD requests for uncached images', async () => {
+      const imagesDir = join(next.testDir, '.next/cache/images')
+      await fs.remove(imagesDir).catch(() => {})
+
+      const $ = await next.render$('/')
```
Comment (styfle) [inline test/e2e/app-dir/next-image/next-image.test.ts:20]: I don't think you can do `render()` here since I think it causes the browser to render the html and make a GET request to the img right?

We need to make the HEAD request before the GET request, so it needs to call the `/_next/image` endpoint directly without rendering.

It might be easier to move this test into the existing test suite here: https://github.com/vercel/next.js/blob/8d415853f73c72263d24be3ea92b497d41f242f0/test/integration/image-optimizer/test/util.ts#L1313

Comment (icyJoseph) [reply test/e2e/app-dir/next-image/next-image.test.ts:20]: Is that render a browser render though? I think it might be a misnomer. 

> Fetch the HTML for the provided page. This is a shortcut for `renderViaHTTP().then(html => cheerio.load(html))

- https://github.com/vercel/next.js/blob/2446efeaa631e3262c714c72695d7db63d20b283/test/lib/next-modes/base.ts#L836

I don't think cherio.load, executes anything right? I was also running this test locally, with and without changes to see that we go from pass to fail.

File: test/e2e/app-dir/next-image/next-image.test.ts [hunk 4]
```diff
@@ -11,6 +13,34 @@ describe('app dir - next-image', () => {
...
+      const imageUrl = $('#app-layout').attr('src')
+
+      const headRes = await next.fetch(imageUrl, { method: 'HEAD' })
+      expect(headRes.status).toBe(200)
+      expect(headRes.headers.get('content-type')).toMatch(/^image\//)
+      expect(headRes.headers.get('X-Nextjs-Cache')).toBe('MISS')
+
+      const contentLength = headRes.headers.get('content-length')
+      expect(Number(contentLength || '0')).toBeGreaterThan(0)
```
Comment (styfle) [inline test/e2e/app-dir/next-image/next-image.test.ts:29]: This should also assert that the body is empty here

```suggestion
      expect(Number(contentLength || '0')).toBeGreaterThan(0)
      const headBody = await getRes.arrayBuffer()
      expect(headBody.byteLength).toBe(0)
```

File: test/e2e/app-dir/next-image/next-image.test.ts (hunk 3 above)
Comment (styfle) [reply test/e2e/app-dir/next-image/next-image.test.ts:20]: Yeah you're right 👍

**Review by styfle — APPROVED** [review]
Great work, thanks! 🎉
