### PR TITLE
Print error during `next export` with default image loader

### LINKED ISSUE #18356: _next/image 404 on next build && next export
# Bug report

## Describe the bug

Images are 404 on next build && next export. Works properly next build && next start

## To Reproduce

1. npx create-next-app --example image-component image-app
2. cd image-app
3. npx next build && npx next export && cd out && npx serve
4. visit localhost:5000

## Screenshots

image

## System information

- OS: macOS Mojave
- Version of Next.js: [e.g. 10.0.0]
- Version of Node.js: [e.g. 12.18.4]

### PR DESCRIPTION
**Pull request by styfle**
Fixes #18356

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: d78ce251c51feaa13d55924e36be912531ac4c5e

**test/integration/absolute-assetprefix/test/index.test.js** 
- absolute assetPrefix with path prefix > should not fetch static data from a CDN
- absolute assetPrefix with path prefix > should fetch from cache correctly
- absolute assetPrefix with path prefix > should work with getStaticPaths prerendered
- absolute assetPrefix with path prefix > should work with getStaticPaths fallback
- absolute assetPrefix with path prefix > should work with getServerSideProps

<details>
<summary>Expand output</summary>

  ● absolute assetPrefix with path prefix › should not fetch static data from a CDN

    command failed with code 1

      138 |         code !== 0
      139 |       ) {
    > 140 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      141 |       }
      142 | 
      143 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:140:23)

  ● absolute assetPrefix with path prefix › should fetch from cache correctly

    command failed with code 1

      138 |         code !== 0
      139 |       ) {
    > 140 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      141 |       }
      142 | 
      143 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:140:23)

  ● absolute assetPrefix with path prefix › should work with getStaticPaths prerendered

    command failed with code 1

      138 |         code !== 0
      139 |       ) {
    > 140 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      141 |       }
      142 | 
      143 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:140:23)

  ● absolute assetPrefix with path prefix › should work with getStaticPaths fallback

    command failed with code 1

      138 |         code !== 0
      139 |       ) {
    > 140 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      141 |       }
      142 | 
      143 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:140:23)

  ● absolute assetPrefix with path prefix › should work with getServerSideProps

    command failed with code 1

      138 |         code !== 0
      139 |       ) {
    > 140 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      141 |       }
      142 | 
      143 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:140:23)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      281 | export async function killApp(instance) {
      282 |   await new Promise((resolve, reject) => {
    > 283 |     treeKill(instance.pid, (err) => {
          |                       ^
      284 |       if (err) {
      285 |         if (
      286 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:283:23
      at killApp (lib/next-test-utils.js:282:9)
      at integration/absolute-assetprefix/test/index.test.js:65:18

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 3f70572da391240bbe6ecb4e88a37bf9de211dfb

**test/integration/export-intent/test/index.test.js** 
- Application Export Intent Output > Bad Export > should have the expected outputs for export
- Application Export Intent Output > Custom Export > should have the expected outputs for export
- Application Export Intent Output > Custom Out > should have the expected outputs for export
- Application Export Intent Output > Default Export > should have the expected outputs for export
- Application Export Intent Output > No Export > should have the expected outputs for export

<details>
<summary>Expand output</summary>

  ● Application Export Intent Output › Default Export › should have the expected outputs for export

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `Application Export Intent Output Default Export should have the expected outputs for export 1`

    - Snapshot  - 0
    + Received  + 1

      Object {
        "exportTrailingSlash": false,
        "hasExportPathMap": false,
    +   "isNextImageImported": false,
        "version": 1,
      }

      27 |       expect(
      28 |         JSON.parse(fs.readFileSync(join(distDir, 'export-marker.json'), 'utf8'))
    > 29 |       ).toMatchInlineSnapshot(`
         |         ^
      30 |         Object {
      31 |           "exportTrailingSlash": false,
      32 |           "hasExportPathMap": false,

      at Object.<anonymous> (integration/export-intent/test/index.test.js:29:9)

  ● Application Export Intent Output › Custom Export › should have the expected outputs for export

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `Application Export Intent Output Custom Export should have the expected outputs for export 1`

    - Snapshot  - 0
    + Received  + 1

      Object {
        "exportTrailingSlash": false,
        "hasExportPathMap": true,
    +   "isNextImageImported": false,
        "version": 1,
      }

      67 |       expect(
      68 |         JSON.parse(fs.readFileSync(join(distDir, 'export-marker.json'), 'utf8'))
    > 69 |       ).toMatchInlineSnapshot(`
         |         ^
      70 |         Object {
      71 |           "exportTrailingSlash": false,
      72 |           "hasExportPathMap": true,

      at Object.<anonymous> (integration/export-intent/test/index.test.js:69:9)

  ● Application Export Intent Output › Custom Out › should have the expected outputs for export

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `Application Export Intent Output Custom Out should have the expected outputs for export 1`

    - Snapshot  - 0
    + Received  + 1

      Object {
        "exportTrailingSlash": true,
        "hasExportPathMap": false,
    +   "isNextImageImported": false,
        "version": 1,
      }

      107 |       expect(
      108 |         JSON.parse(fs.readFileSync(join(distDir, 'export-marker.json'), 'utf8'))
    > 109 |       ).toMatchInlineSnapshot(`
          |         ^
      110 |         Object {
      111 |           "exportTrailingSlash": true,
      112 |           "hasExportPathMap": false,

      at Object.<anonymous> (integration/export-intent/test/index.test.js:109:9)

  ● Application Export Intent Output › Bad Export › should have the expected outputs for export

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `Application Export Intent Output Bad Export should have the expected outputs for export 1`

    - Snapshot  - 0
    + Received  + 1

      Object {
        "exportTrailingSlash": false,
        "hasExportPathMap": false,
    +   "isNextImageImported": false,
        "version": 1,
      }

      147 |       expect(
      148 |         JSON.parse(fs.readFileSync(join(distDir, 'export-marker.json'), 'utf8'))
    > 149 |       ).toMatchInlineSnapshot(`
          |         ^
      150 |         Object {
      151 |           "exportTrailingSlash": false,
      152 |           "hasExportPathMap": false,

      at Object.<anonymous> (integration/export-intent/test/index.test.js:149:9)

  ● Application Export Intent Output › No Export › should have the expected outputs for export

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `Application Export Intent Output No Export should have the expected outputs for export 1`

    - Snapshot  - 0
    + Received  + 1

      Object {
        "exportTrailingSlash": false,
        "hasExportPathMap": false,
    +   "isNextImageImported": false,
        "version": 1,
      }

      186 |       expect(
      187 |         JSON.parse(fs.readFileSync(join(distDir, 'export-marker.json'), 'utf8'))
    > 188 |       ).toMatchInlineSnapshot(`
          |         ^
      189 |         Object {
      190 |           "exportTrailingSlash": false,
      191 |           "hasExportPathMap": false,

      at Object.<anonymous> (integration/export-intent/test/index.test.js:188:9)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| buildDuration | 11.2s | 11.1s | -136ms |
| nodeModulesSize | 85 MB | 85 MB | ⚠️ +2.73 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.15 | 2.125 | -0.02 |
| / avg req/sec | 1162.94 | 1176.27 | +13.33 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.29 | 1.324 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1938.28 | 1887.93 | ⚠️ -50.35 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| 677f882d2ed8..7d3b.js gzip | 11.3 kB | 11.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-673683e..14c7.js gzip | 7.48 kB | 7.48 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.5 kB | 58.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.04 kB | 7.04 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-0c7333c..dule.js gzip | 6.47 kB | 6.47 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.2 kB | 53.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-8a9d104..0e42.js gzip | 1.55 kB | 1.55 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.96 kB | 7.96 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-d1cfb87..dule.js gzip | 1.49 kB | 1.49 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.59 kB | 5.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| index.html gzip | 970 B | 970 B | ✓ |
| link.html gzip | 978 B | 978 B | ✓ |
| withRouter.html gzip | 964 B | 964 B | ✓ |
| Overall change | 2.91 kB | 2.91 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.4s | -69ms |
| nodeModulesSize | 85 MB | 85 MB | ⚠️ +2.73 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| 677f882d2ed8..7d3b.js gzip | 11.3 kB | 11.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-673683e..14c7.js gzip | 7.48 kB | 7.48 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.5 kB | 58.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.04 kB | 7.04 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-0c7333c..dule.js gzip | 6.47 kB | 6.47 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.2 kB | 53.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-8a9d104..0e42.js gzip | 1.55 kB | 1.55 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.96 kB | 7.96 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-d1cfb87..dule.js gzip | 1.49 kB | 1.49 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.59 kB | 5.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _error.js | 915 kB | 915 kB | ✓ |
| 404.html | 4.61 kB | 4.61 kB | ✓ |
| hooks.html | 3.86 kB | 3.86 kB | ✓ |
| index.js | 916 kB | 916 kB | ✓ |
| link.js | 965 kB | 965 kB | ✓ |
| routerDirect.js | 957 kB | 957 kB | ✓ |
| withRouter.js | 957 kB | 957 kB | ✓ |
| Overall change | 4.72 MB | 4.72 MB | ✓ |

</details>

</details>
Commit: 3510ea2ae6caa6a678a8d93153b5a3d9676386a2

File: packages/next/export/index.ts [hunk 1]
```diff
@@ -283,14 +284,33 @@ export default async function exportApp(
...
+    .then((text) => JSON.parse(text))
+    .catch(() => ({}))
+
+  if (
+    isNextImageImported &&
+    loader === 'default' &&
+    !options.buildExport &&
+    !hasNextSupport
+  ) {
+    throw new Error(
```
Comment (Timer) [inline packages/next/export/index.ts:309]: Let's explicitly call out Vercel as compatible here.

**Review by Timer — CHANGES_REQUESTED** [review]

File: packages/next/export/index.ts (hunk 1 above)
Comment (styfle) [reply packages/next/export/index.ts:309]: Done 👍

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.7s | ⚠️ +68ms |
| nodeModulesSize | 84.8 MB | 84.8 MB | ⚠️ +3.04 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.345 | 2.345 | ✓ |
| / avg req/sec | 1066.02 | 1066.17 | +0.15 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.231 | 1.218 | -0.01 |
| /error-in-render avg req/sec | 2030.85 | 2053.08 | +22.23 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| 677f882d2ed8..3888.js gzip | 11.3 kB | 11.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-673683e..14c7.js gzip | 7.48 kB | 7.48 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.5 kB | 58.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-0c7333c..dule.js gzip | 6.47 kB | 6.47 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.2 kB | 53.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-8a9d104..0e42.js gzip | 1.55 kB | 1.55 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.96 kB | 7.96 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-d1cfb87..dule.js gzip | 1.49 kB | 1.49 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.59 kB | 5.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| index.html gzip | 969 B | 969 B | ✓ |
| link.html gzip | 977 B | 977 B | ✓ |
| withRouter.html gzip | 963 B | 963 B | ✓ |
| Overall change | 2.91 kB | 2.91 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| buildDuration | 14.5s | 14.4s | -56ms |
| nodeModulesSize | 84.8 MB | 84.8 MB | ⚠️ +3.04 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| 677f882d2ed8..3888.js gzip | 11.3 kB | 11.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-673683e..14c7.js gzip | 7.48 kB | 7.48 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.5 kB | 58.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-0c7333c..dule.js gzip | 6.47 kB | 6.47 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.2 kB | 53.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-8a9d104..0e42.js gzip | 1.55 kB | 1.55 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.96 kB | 7.96 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-d1cfb87..dule.js gzip | 1.49 kB | 1.49 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.59 kB | 5.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _error.js | 916 kB | 916 kB | ✓ |
| 404.html | 4.61 kB | 4.61 kB | ✓ |
| hooks.html | 3.86 kB | 3.86 kB | ✓ |
| index.js | 916 kB | 916 kB | ✓ |
| link.js | 965 kB | 965 kB | ✓ |
| routerDirect.js | 958 kB | 958 kB | ✓ |
| withRouter.js | 958 kB | 958 kB | ✓ |
| Overall change | 4.72 MB | 4.72 MB | ✓ |

</details>

</details>
Commit: d3b901c603ca91388e1441e81dd8509e59f51867

**Review by Timer — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| buildDuration | 13.9s | 13.4s | -455ms |
| nodeModulesSize | 84.8 MB | 84.8 MB | ⚠️ +3.04 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.459 | 2.42 | -0.04 |
| / avg req/sec | 1016.62 | 1033.1 | +16.48 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.347 | 1.321 | -0.03 |
| /error-in-render avg req/sec | 1855.88 | 1891.88 | +36 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| 677f882d2ed8..01e7.js gzip | 11.3 kB | 11.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-3e470be..d458.js gzip | 7.48 kB | 7.48 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.5 kB | 58.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-0c7333c..dule.js gzip | 6.47 kB | 6.47 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.2 kB | 53.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-0abe79e..7616.js gzip | 1.55 kB | 1.55 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.96 kB | 7.96 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-d1cfb87..dule.js gzip | 1.49 kB | 1.49 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.59 kB | 5.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| index.html gzip | 970 B | 970 B | ✓ |
| link.html gzip | 977 B | 977 B | ✓ |
| withRouter.html gzip | 963 B | 963 B | ✓ |
| Overall change | 2.91 kB | 2.91 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| buildDuration | 14.9s | 15.5s | ⚠️ +551ms |
| nodeModulesSize | 84.8 MB | 84.8 MB | ⚠️ +3.04 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| 677f882d2ed8..01e7.js gzip | 11.3 kB | 11.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-3e470be..d458.js gzip | 7.48 kB | 7.48 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.5 kB | 58.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-0c7333c..dule.js gzip | 6.47 kB | 6.47 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.2 kB | 53.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-0abe79e..7616.js gzip | 1.55 kB | 1.55 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.96 kB | 7.96 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-d1cfb87..dule.js gzip | 1.49 kB | 1.49 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.59 kB | 5.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 18356-export-img | Change |
| - | - | - | - |
| _error.js | 916 kB | 916 kB | ✓ |
| 404.html | 4.61 kB | 4.61 kB | ✓ |
| hooks.html | 3.86 kB | 3.86 kB | ✓ |
| index.js | 916 kB | 916 kB | ✓ |
| link.js | 965 kB | 965 kB | ✓ |
| routerDirect.js | 958 kB | 958 kB | ✓ |
| withRouter.js | 958 kB | 958 kB | ✓ |
| Overall change | 4.72 MB | 4.72 MB | ✓ |

</details>

</details>
Commit: 0dac6eedc88adc4dd9bab28381755757f8c4925c
