### PR TITLE
Fix `onLoadingComplete()` callback when image src is Data URL

### LINKED ISSUE #29363: OnLoadingComplete not working when passing function, but works when console log
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

10.20.1

### What browser are you using?

chrome

### What operating system are you using?

codesandbox

### How are you deploying your application?

codesandbox

### Describe the Bug

I'm trying to get the naturalWidth and naturalHeight from onLoadingComplete props: https://nextjs.org/docs/api-reference/next/image#onloadingcomplete but its not working? Perhaps I'm doing it wrong?

I have a codesandbox, lines 62, 63: https://codesandbox.io/s/proud-rain-d51sv?file=/pages/index.js

When you upload an image, console log only works, but it doesn't work when I'm trying to pass handleImageLoad function listed in the sandbox. 

### Expected Behavior

Trying to get naturalWidth and naturalHeight

### To Reproduce

https://codesandbox.io/s/proud-rain-d51sv?file=/pages/index.js lines 62, 63

### PR DESCRIPTION
**Pull request by styfle**
Fixes #29363 

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| buildDuration | 16.8s | 17s | ⚠️ +156ms |
| buildDurationCached | 4.2s | 4.3s | ⚠️ +84ms |
| nodeModulesSize | 182 MB | 182 MB | ⚠️ +67 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.798 | 3.7 | -0.1 |
| / avg req/sec | 658.29 | 675.76 | +17.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.156 | 2.191 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1159.78 | 1140.78 | ⚠️ -19 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27 kB | 27 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 70.8 kB | 70.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 977 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 311 B | 311 B | ✓ |
| css-HASH.js gzip | 328 B | 328 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.15 kB | ⚠️ +5 B |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 493 B | 494 B | ⚠️ +1 B |
| Overall change | 493 B | 494 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| index.html gzip | 538 B | 538 B | ✓ |
| link.html gzip | 550 B | 550 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -17,7 +17,7 @@ self.__BUILD_MANIFEST = {
     "static\u002Fchunks\u002Fpages\u002Fhooks-b247d7d93b59ee105030.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002Fpages\u002Fimage-a44f9781a95a9ce41ff2.js"
+    "static\u002Fchunks\u002Fpages\u002Fimage-ac34fa70dbc1572d05a7.js"
   ],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-6c203ee999e47493e19d.js"],
   "/routerDirect": [
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -110,6 +110,8 @@
       }
 
       var loadedImageURLs = new Set();
+      var emptyDataURL =
+        "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";
 
       if (false) {
       }
@@ -328,7 +330,7 @@
         }
 
         var handleLoad = function handleLoad() {
-          if (!img.src.startsWith("data:")) {
+          if (img.src !== emptyDataURL) {
             var p = "decode" in img ? img.decode() : Promise.resolve();
             p["catch"](function() {}).then(function() {
               if (placeholder === "blur") {
@@ -591,8 +593,7 @@
         }
 
         var imgAttributes = {
-          src:
-            "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
+          src: emptyDataURL,
           srcSet: undefined,
           sizes: undefined
         };
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| buildDuration | 8.7s | 8.6s | -153ms |
| buildDurationCached | 4.1s | 4.2s | ⚠️ +48ms |
| nodeModulesSize | 182 MB | 182 MB | ⚠️ +67 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.742 | 3.739 | 0 |
| / avg req/sec | 668.03 | 668.71 | +0.68 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.13 | 2.118 | -0.01 |
| /error-in-render avg req/sec | 1173.78 | 1180.63 | +6.85 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| 675-HASH.js gzip | 13.8 kB | 13.8 kB | ⚠️ +4 B |
| 770.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 50.7 kB | 50.7 kB | ✓ |
| main-HASH.js gzip | 34.9 kB | 34.9 kB | ✓ |
| webpack-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| Overall change | 101 kB | 101 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 315 B | 315 B | ✓ |
| css-HASH.js gzip | 331 B | 331 B | ✓ |
| dynamic-HASH.js gzip | 2.8 kB | 2.8 kB | ✓ |
| head-HASH.js gzip | 356 B | 356 B | ✓ |
| hooks-HASH.js gzip | 637 B | 637 B | ✓ |
| image-HASH.js gzip | 573 B | 573 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 2.2 kB | 2.2 kB | ✓ |
| routerDirect..HASH.js gzip | 326 B | 326 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 322 B | 322 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 511 B | 511 B | ✓ |
| Overall change | 511 B | 511 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 551 B | 551 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -17,7 +17,7 @@ self.__BUILD_MANIFEST = {
     "static\u002Fchunks\u002Fpages\u002Fhooks-57657d9807f56726f7b7.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002F675-3a2a4d3823c95ac202d4.js",
+    "static\u002Fchunks\u002F675-e36478c6435f19ec761d.js",
     "static\u002Fchunks\u002Fpages\u002Fimage-ffd5f0bef0d7723148e9.js"
   ],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-7f8f722ace4fedf0a7aa.js"],
```
</details>
<details>
<summary>Diff for <strong>675-HASH.js</strong></summary>

```diff
@@ -2452,6 +2452,8 @@
         return target;
       }
       var loadedImageURLs = new Set();
+      var emptyDataURL =
+        "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";
       if (typeof window === "undefined") {
         __webpack_require__.g.__NEXT_IMAGE_IMPORTED = true;
       }
@@ -2645,7 +2647,7 @@
           return;
         }
         var handleLoad = function() {
-          if (!img.src.startsWith("data:")) {
+          if (img.src !== emptyDataURL) {
             var p = "decode" in img ? img.decode() : Promise.resolve();
             p.catch(function() {}).then(function() {
               if (placeholder === "blur") {
@@ -2884,8 +2886,7 @@
           }
         }
         var imgAttributes = {
-          src:
-            "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
+          src: emptyDataURL,
           srcSet: undefined,
           sizes: undefined
         };
```
</details>
</details>
Commit: 742526ecbb35d72b162ac0241fa78ad7dde613e3

File: test/integration/image-component/default/pages/on-loading-complete.js [hunk 1]
```diff
@@ -32,6 +35,22 @@ const Page = () => (
         objectFit="contain"
       />
     </div>
+    <hr />
+    <ImageWithMessage
+      id="5"
+      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAFCAYAAACAcVaiAAAAE0lEQVR42mNk+P+/ngEKGMngAADDdwx3Uz/3AAAAAABJRU5ErkJggg=="
+      layout="fixed"
+      width={64}
```
Comment (ijjk) [inline test/integration/image-component/default/pages/on-loading-complete.js:43]: Should we test onLoadComplete is called here as well?

Comment (styfle) [reply test/integration/image-component/default/pages/on-loading-complete.js:43]: The component `ImageWithMessage` is using `onLoadingComplete` and it will print `loaded img6 with dimensions 3x`

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| buildDuration | 15.6s | 15.9s | ⚠️ +243ms |
| buildDurationCached | 4s | 4.1s | ⚠️ +87ms |
| nodeModulesSize | 182 MB | 182 MB | ⚠️ +68 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.522 | 3.503 | -0.02 |
| / avg req/sec | 709.9 | 713.61 | +3.71 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.956 | 1.976 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1277.9 | 1265.48 | ⚠️ -12.42 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27 kB | 27 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 70.8 kB | 70.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 977 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 311 B | 311 B | ✓ |
| css-HASH.js gzip | 328 B | 328 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.15 kB | ⚠️ +5 B |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 493 B | 494 B | ⚠️ +1 B |
| Overall change | 493 B | 494 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| index.html gzip | 538 B | 538 B | ✓ |
| link.html gzip | 550 B | 550 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -17,7 +17,7 @@ self.__BUILD_MANIFEST = {
     "static\u002Fchunks\u002Fpages\u002Fhooks-b247d7d93b59ee105030.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002Fpages\u002Fimage-a44f9781a95a9ce41ff2.js"
+    "static\u002Fchunks\u002Fpages\u002Fimage-ac34fa70dbc1572d05a7.js"
   ],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-6c203ee999e47493e19d.js"],
   "/routerDirect": [
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -110,6 +110,8 @@
       }
 
       var loadedImageURLs = new Set();
+      var emptyDataURL =
+        "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";
 
       if (false) {
       }
@@ -328,7 +330,7 @@
         }
 
         var handleLoad = function handleLoad() {
-          if (!img.src.startsWith("data:")) {
+          if (img.src !== emptyDataURL) {
             var p = "decode" in img ? img.decode() : Promise.resolve();
             p["catch"](function() {}).then(function() {
               if (placeholder === "blur") {
@@ -591,8 +593,7 @@
         }
 
         var imgAttributes = {
-          src:
-            "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
+          src: emptyDataURL,
           srcSet: undefined,
           sizes: undefined
         };
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| buildDuration | 8.1s | 8.1s | ⚠️ +2ms |
| buildDurationCached | 3.9s | 3.9s | -61ms |
| nodeModulesSize | 182 MB | 182 MB | ⚠️ +68 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.596 | 3.626 | ⚠️ +0.03 |
| / avg req/sec | 695.26 | 689.53 | ⚠️ -5.73 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.959 | 1.898 | -0.06 |
| /error-in-render avg req/sec | 1276.06 | 1317.34 | +41.28 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| 675-HASH.js gzip | 13.8 kB | 13.8 kB | ⚠️ +4 B |
| 770.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 50.7 kB | 50.7 kB | ✓ |
| main-HASH.js gzip | 34.9 kB | 34.9 kB | ✓ |
| webpack-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| Overall change | 101 kB | 101 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 315 B | 315 B | ✓ |
| css-HASH.js gzip | 331 B | 331 B | ✓ |
| dynamic-HASH.js gzip | 2.8 kB | 2.8 kB | ✓ |
| head-HASH.js gzip | 356 B | 356 B | ✓ |
| hooks-HASH.js gzip | 637 B | 637 B | ✓ |
| image-HASH.js gzip | 573 B | 573 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 2.2 kB | 2.2 kB | ✓ |
| routerDirect..HASH.js gzip | 326 B | 326 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 322 B | 322 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 511 B | 511 B | ✓ |
| Overall change | 511 B | 511 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 551 B | 551 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -17,7 +17,7 @@ self.__BUILD_MANIFEST = {
     "static\u002Fchunks\u002Fpages\u002Fhooks-57657d9807f56726f7b7.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002F675-3a2a4d3823c95ac202d4.js",
+    "static\u002Fchunks\u002F675-e36478c6435f19ec761d.js",
     "static\u002Fchunks\u002Fpages\u002Fimage-ffd5f0bef0d7723148e9.js"
   ],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-7f8f722ace4fedf0a7aa.js"],
```
</details>
<details>
<summary>Diff for <strong>675-HASH.js</strong></summary>

```diff
@@ -2452,6 +2452,8 @@
         return target;
       }
       var loadedImageURLs = new Set();
+      var emptyDataURL =
+        "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";
       if (typeof window === "undefined") {
         __webpack_require__.g.__NEXT_IMAGE_IMPORTED = true;
       }
@@ -2645,7 +2647,7 @@
           return;
         }
         var handleLoad = function() {
-          if (!img.src.startsWith("data:")) {
+          if (img.src !== emptyDataURL) {
             var p = "decode" in img ? img.decode() : Promise.resolve();
             p.catch(function() {}).then(function() {
               if (placeholder === "blur") {
@@ -2884,8 +2886,7 @@
           }
         }
         var imgAttributes = {
-          src:
-            "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
+          src: emptyDataURL,
           srcSet: undefined,
           sizes: undefined
         };
```
</details>
</details>
Commit: 8b6bff89ac8bcd25f78f85a23ab5384354183b9a

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: bb5a198dc89a866d13da5b9973f8f6200f15ebad

**test/development/acceptance/ReactRefresh.test.ts** 
- ReactRefresh > can edit a component without losing state
- ReactRefresh > cyclic dependencies

<details>
<summary>Expand output</summary>

  ● ReactRefresh › can edit a component without losing state

    EEXIST: file already exists, mkdir '/tmp/next-test-1632516854278'



  ● ReactRefresh › cyclic dependencies

    EEXIST: file already exists, mkdir '/tmp/next-test-1632516854278'




  ● Test suite failed to run

    TypeError: Cannot read property 'destroy' of undefined

      13 |     })
      14 |   })
    > 15 |   afterAll(() => next.destroy())
         |                       ^
      16 |
      17 |   test('can edit a component without losing state', async () => {
      18 |     const { session, cleanup } = await sandbox(next)

      at development/acceptance/ReactRefresh.test.ts:15:23

  ● Test suite failed to run

    next instance not destroyed before exiting, make sure to call .destroy() after the tests after finished

      75 |     if (nextInstance) {
      76 |       await nextInstance.destroy()
    > 77 |       throw new Error(
         |             ^
      78 |         `next instance not destroyed before exiting, make sure to call .destroy() after the tests after finished`
      79 |       )
      80 |     }

      at lib/e2e-utils.ts:77:13

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| buildDuration | 14.9s | 15.1s | ⚠️ +193ms |
| buildDurationCached | 3.8s | 3.8s | ⚠️ +1ms |
| nodeModulesSize | 182 MB | 182 MB | ⚠️ +64 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.244 | 3.304 | ⚠️ +0.06 |
| / avg req/sec | 770.75 | 756.57 | ⚠️ -14.18 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.606 | 1.627 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1557.1 | 1536.16 | ⚠️ -20.94 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27 kB | 27 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 70.8 kB | 70.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 977 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 311 B | 311 B | ✓ |
| css-HASH.js gzip | 328 B | 328 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.15 kB | ⚠️ +5 B |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 493 B | 494 B | ⚠️ +1 B |
| Overall change | 493 B | 494 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| index.html gzip | 538 B | 538 B | ✓ |
| link.html gzip | 550 B | 550 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -17,7 +17,7 @@ self.__BUILD_MANIFEST = {
     "static\u002Fchunks\u002Fpages\u002Fhooks-b247d7d93b59ee105030.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002Fpages\u002Fimage-a44f9781a95a9ce41ff2.js"
+    "static\u002Fchunks\u002Fpages\u002Fimage-ac34fa70dbc1572d05a7.js"
   ],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-6c203ee999e47493e19d.js"],
   "/routerDirect": [
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -110,6 +110,8 @@
       }
 
       var loadedImageURLs = new Set();
+      var emptyDataURL =
+        "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";
 
       if (false) {
       }
@@ -328,7 +330,7 @@
         }
 
         var handleLoad = function handleLoad() {
-          if (!img.src.startsWith("data:")) {
+          if (img.src !== emptyDataURL) {
             var p = "decode" in img ? img.decode() : Promise.resolve();
             p["catch"](function() {}).then(function() {
               if (placeholder === "blur") {
@@ -591,8 +593,7 @@
         }
 
         var imgAttributes = {
-          src:
-            "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
+          src: emptyDataURL,
           srcSet: undefined,
           sizes: undefined
         };
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| buildDuration | 7.7s | 7.7s | -4ms |
| buildDurationCached | 4.2s | 3.7s | -495ms |
| nodeModulesSize | 182 MB | 182 MB | ⚠️ +64 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.336 | 3.308 | -0.03 |
| / avg req/sec | 749.51 | 755.81 | +6.3 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.607 | 1.617 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1556.09 | 1546.19 | ⚠️ -9.9 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| 675-HASH.js gzip | 13.8 kB | 13.8 kB | ⚠️ +4 B |
| 770.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 50.7 kB | 50.7 kB | ✓ |
| main-HASH.js gzip | 34.9 kB | 34.9 kB | ✓ |
| webpack-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| Overall change | 101 kB | 101 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 315 B | 315 B | ✓ |
| css-HASH.js gzip | 331 B | 331 B | ✓ |
| dynamic-HASH.js gzip | 2.8 kB | 2.8 kB | ✓ |
| head-HASH.js gzip | 356 B | 356 B | ✓ |
| hooks-HASH.js gzip | 637 B | 637 B | ✓ |
| image-HASH.js gzip | 573 B | 573 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 2.2 kB | 2.2 kB | ✓ |
| routerDirect..HASH.js gzip | 326 B | 326 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 322 B | 322 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 511 B | 511 B | ✓ |
| Overall change | 511 B | 511 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 551 B | 551 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -17,7 +17,7 @@ self.__BUILD_MANIFEST = {
     "static\u002Fchunks\u002Fpages\u002Fhooks-57657d9807f56726f7b7.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002F675-3a2a4d3823c95ac202d4.js",
+    "static\u002Fchunks\u002F675-e36478c6435f19ec761d.js",
     "static\u002Fchunks\u002Fpages\u002Fimage-ffd5f0bef0d7723148e9.js"
   ],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-7f8f722ace4fedf0a7aa.js"],
```
</details>
<details>
<summary>Diff for <strong>675-HASH.js</strong></summary>

```diff
@@ -2452,6 +2452,8 @@
         return target;
       }
       var loadedImageURLs = new Set();
+      var emptyDataURL =
+        "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";
       if (typeof window === "undefined") {
         __webpack_require__.g.__NEXT_IMAGE_IMPORTED = true;
       }
@@ -2645,7 +2647,7 @@
           return;
         }
         var handleLoad = function() {
-          if (!img.src.startsWith("data:")) {
+          if (img.src !== emptyDataURL) {
             var p = "decode" in img ? img.decode() : Promise.resolve();
             p.catch(function() {}).then(function() {
               if (placeholder === "blur") {
@@ -2884,8 +2886,7 @@
           }
         }
         var imgAttributes = {
-          src:
-            "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
+          src: emptyDataURL,
           srcSet: undefined,
           sizes: undefined
         };
```
</details>
</details>
Commit: bb5a198dc89a866d13da5b9973f8f6200f15ebad

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.9s | ⚠️ +72ms |
| buildDurationCached | 3.4s | 3.4s | -59ms |
| nodeModulesSize | 182 MB | 182 MB | ⚠️ +68 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.919 | 2.922 | 0 |
| / avg req/sec | 856.58 | 855.46 | ⚠️ -1.12 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.407 | 1.39 | -0.02 |
| /error-in-render avg req/sec | 1776.67 | 1798.47 | +21.8 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27 kB | 27 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 70.8 kB | 70.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 977 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 311 B | 311 B | ✓ |
| css-HASH.js gzip | 328 B | 328 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.15 kB | ⚠️ +5 B |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 493 B | 494 B | ⚠️ +1 B |
| Overall change | 493 B | 494 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| index.html gzip | 538 B | 538 B | ✓ |
| link.html gzip | 550 B | 550 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -17,7 +17,7 @@ self.__BUILD_MANIFEST = {
     "static\u002Fchunks\u002Fpages\u002Fhooks-b247d7d93b59ee105030.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002Fpages\u002Fimage-a44f9781a95a9ce41ff2.js"
+    "static\u002Fchunks\u002Fpages\u002Fimage-ac34fa70dbc1572d05a7.js"
   ],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-6c203ee999e47493e19d.js"],
   "/routerDirect": [
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -110,6 +110,8 @@
       }
 
       var loadedImageURLs = new Set();
+      var emptyDataURL =
+        "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";
 
       if (false) {
       }
@@ -328,7 +330,7 @@
         }
 
         var handleLoad = function handleLoad() {
-          if (!img.src.startsWith("data:")) {
+          if (img.src !== emptyDataURL) {
             var p = "decode" in img ? img.decode() : Promise.resolve();
             p["catch"](function() {}).then(function() {
               if (placeholder === "blur") {
@@ -591,8 +593,7 @@
         }
 
         var imgAttributes = {
-          src:
-            "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
+          src: emptyDataURL,
           srcSet: undefined,
           sizes: undefined
         };
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| buildDuration | 6.7s | 6.8s | ⚠️ +98ms |
| buildDurationCached | 3.4s | 3.3s | -91ms |
| nodeModulesSize | 182 MB | 182 MB | ⚠️ +68 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.865 | 2.991 | ⚠️ +0.13 |
| / avg req/sec | 872.68 | 835.87 | ⚠️ -36.81 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.333 | 1.454 | ⚠️ +0.12 |
| /error-in-render avg req/sec | 1875.19 | 1719.5 | ⚠️ -155.69 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| 675-HASH.js gzip | 13.8 kB | 13.8 kB | ⚠️ +4 B |
| 770.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 50.7 kB | 50.7 kB | ✓ |
| main-HASH.js gzip | 34.9 kB | 34.9 kB | ✓ |
| webpack-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| Overall change | 101 kB | 101 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 315 B | 315 B | ✓ |
| css-HASH.js gzip | 331 B | 331 B | ✓ |
| dynamic-HASH.js gzip | 2.8 kB | 2.8 kB | ✓ |
| head-HASH.js gzip | 356 B | 356 B | ✓ |
| hooks-HASH.js gzip | 637 B | 637 B | ✓ |
| image-HASH.js gzip | 573 B | 573 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 2.2 kB | 2.2 kB | ✓ |
| routerDirect..HASH.js gzip | 326 B | 326 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 322 B | 322 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 511 B | 511 B | ✓ |
| Overall change | 511 B | 511 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-onload-for-data-url | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 551 B | 551 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -17,7 +17,7 @@ self.__BUILD_MANIFEST = {
     "static\u002Fchunks\u002Fpages\u002Fhooks-57657d9807f56726f7b7.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002F675-3a2a4d3823c95ac202d4.js",
+    "static\u002Fchunks\u002F675-e36478c6435f19ec761d.js",
     "static\u002Fchunks\u002Fpages\u002Fimage-ffd5f0bef0d7723148e9.js"
   ],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-7f8f722ace4fedf0a7aa.js"],
```
</details>
<details>
<summary>Diff for <strong>675-HASH.js</strong></summary>

```diff
@@ -2452,6 +2452,8 @@
         return target;
       }
       var loadedImageURLs = new Set();
+      var emptyDataURL =
+        "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";
       if (typeof window === "undefined") {
         __webpack_require__.g.__NEXT_IMAGE_IMPORTED = true;
       }
@@ -2645,7 +2647,7 @@
           return;
         }
         var handleLoad = function() {
-          if (!img.src.startsWith("data:")) {
+          if (img.src !== emptyDataURL) {
             var p = "decode" in img ? img.decode() : Promise.resolve();
             p.catch(function() {}).then(function() {
               if (placeholder === "blur") {
@@ -2884,8 +2886,7 @@
           }
         }
         var imgAttributes = {
-          src:
-            "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
+          src: emptyDataURL,
           srcSet: undefined,
           sizes: undefined
         };
```
</details>
</details>
Commit: 53126aef00ca1a609fab979d906fd1d11584e7b3

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 53126aef00ca1a609fab979d906fd1d11584e7b3

**test/development/basic/hmr.test.ts** 
- basic HMR > Error Recovery > should recover after undefined exported as default
- basic HMR > Error Recovery > should recover from errors in getInitialProps in client
- basic HMR > Error Recovery > should recover after an error reported via SSR

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should recover after undefined exported as default

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `basic HMR Error Recovery should recover after undefined exported as default 1`

    - Snapshot  - 3
    + Received  + 1

       1 of 1 unhandled error
    - Server Error
    + Unhandled Runtime Error

      Error: The default export is not a React Component in page: "/hmr/about7"
    -
    - This error happened while generating the page. Any console logs will be displayed in the terminal window.

      600 |         await next.patchFile(aboutPage, aboutContent)
      601 |
    > 602 |         if (browser) {
          |                       ^
      603 |           await check(
      604 |             () => getBrowserBodyText(browser),
      605 |             /This is the about page/

      at Object.<anonymous> (development/basic/hmr.test.ts:602:23)

  ● basic HMR › Error Recovery › should recover from errors in getInitialProps in client

    TIMED OUT: /Hello/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:659:8)

  ● basic HMR › Error Recovery › should recover after an error reported via SSR

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      701 |
      702 |         throw err
    > 703 |       } finally {
          |                  ^
      704 |         if (browser) {
      705 |           await browser.close()
      706 |         }

      at Object.<anonymous> (development/basic/hmr.test.ts:703:18)

</details>
