### PR TITLE
Fix next node buildin module error message for edge runtime

### LINKED ISSUE #36237: Invalid "Native Node.js APIs are not supported in the Edge Runtime" error message
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.6.0: Tue Feb 15 21:39:11 PST 2022; root:xnu-6153.141.59~1/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.3
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

When there is a page like the following, `next build` shows the error message `> Native Node.js APIs are not supported in the Edge Runtime. Found "child_process" imported, on index.`, even when there is no middleware used.

```js
import { spawn } from 'child_process';

export default function Page() {
  return <div>ok</div>
}
```

This is the same for the compilation error using `next dev`.

Also, a related problem, but when you use react version 17, this message is NOT shown for middleware importing `child_process`.

### Expected Behavior

The error message is shown only for edge functions certainly, even with older react version.

### To Reproduce

Import the `child_process` module on a page, without middleware, with react@18.

### PR DESCRIPTION
**Pull request by nkzawa**
- improve the message for importing node builtin module on edge runtime
- fix to show the message on overlay of error browser with `next dev`
- fix https://github.com/vercel/next.js/issues/36237

The message is NOT shown when using edge runtime (not middleware) since I cannot find a way to detect a webpack compilation is for edge runtime.

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 04eff87448fce3d5c274412e6a12752d77c11df2

`yarn testheadless test/integration/middleware/with-builtin-module/test/index.test.js` 
- Middleware importing Node.js built-in module > dev mode > shows error when importing path module
- Middleware importing Node.js built-in module > dev mode > shows error when importing child_process module

<details>
<summary>Expand output</summary>

  ● Middleware importing Node.js built-in module › dev mode › shows error when importing path module

    TypeError: s.replaceAll is not a function

      25 |
      26 |   function escapeLF(s) {
    > 27 |     return s.replaceAll('\n', '\\n')
         |              ^
      28 |   }
      29 |
      30 |   describe('dev mode', () => {

      at escapeLF (integration/middleware/with-builtin-module/test/index.test.js:27:14)
      at Object.<anonymous> (integration/middleware/with-builtin-module/test/index.test.js:58:30)

  ● Middleware importing Node.js built-in module › dev mode › shows error when importing child_process module

    TypeError: s.replaceAll is not a function

      25 |
      26 |   function escapeLF(s) {
    > 27 |     return s.replaceAll('\n', '\\n')
         |              ^
      28 |   }
      29 |
      30 |   describe('dev mode', () => {

      at escapeLF (integration/middleware/with-builtin-module/test/index.test.js:27:14)
      at Object.<anonymous> (integration/middleware/with-builtin-module/test/index.test.js:72:30)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| buildDuration | 15.3s | 15.1s | -135ms |
| buildDurationCached | 6.1s | 6s | -61ms |
| nodeModulesSize | 481 MB | 481 MB | ⚠️ +6.29 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.007 | 2.993 | -0.01 |
| / avg req/sec | 831.47 | 835.17 | +3.7 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.167 | 1.16 | -0.01 |
| /error-in-render avg req/sec | 2142.85 | 2154.96 | +12.11 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.73 kB | 5.73 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16 kB | 16 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 461 B | 461 B | ✓ |
| Overall change | 461 B | 461 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| buildDuration | 17.3s | 17.4s | ⚠️ +135ms |
| buildDurationCached | 6s | 6.1s | ⚠️ +35ms |
| nodeModulesSize | 481 MB | 481 MB | ⚠️ +6.29 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.015 | 2.979 | -0.04 |
| / avg req/sec | 829.31 | 839.17 | +9.86 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.171 | 1.156 | -0.02 |
| /error-in-render avg req/sec | 2135.02 | 2163.09 | +28.07 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 29.1 kB | 29.1 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.9 kB | 72.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.02 kB | 3.02 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.78 kB | 5.78 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.44 kB | 2.44 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.1 kB | 16.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 457 B | 457 B | ✓ |
| Overall change | 457 B | 457 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | nkzawa/next.js fix-next-node-buildin-module-error-message | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 74b7066cb15597bcf7d317ef7ad428cc3952c33a

File: packages/next/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.ts [hunk 1]
```diff
@@ -107,6 +114,15 @@ export async function getNotFoundError(
       importTrace() +
       '\nhttps://nextjs.org/docs/messages/module-not-found'
 
+    if (await isEdgeRuntimeCompiled(compilation, input.module, config)) {
+      const moduleName = getUnresolvedModuleFromError(input.message)
+      if (moduleName) {
```
Comment (sokra) [inline packages/next/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.ts:119]:
```suggestion
    const moduleName = getUnresolvedModuleFromError(input.message)
    if (moduleName) {
      if (await isEdgeRuntimeCompiled(compilation, input.module, config)) {
```

It might be a little bit faster to swap these lines...

Comment (nkzawa) [reply packages/next/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.ts]: thanks

File: test/integration/middleware/with-builtin-module/test/index.test.js [hunk 2]
```diff
@@ -22,14 +23,16 @@ describe('Middleware importing Node.js built-in module', () => {
...
-    return `Native Node.js APIs are not supported in the Edge Runtime. Found \`${name}\` imported.\n`
+  function escapeLF(s) {
+    return s.replace(/\n/g, '\\n')
   }
 
   describe('dev mode', () => {
     let output = ''
 
-    beforeAll(async () => {
+    // restart the app for every test since the latest error is not shown sometimes
```
Comment (ijjk) [inline test/integration/middleware/with-builtin-module/test/index.test.js:33]: This sounds like a bug, was this the case before these changes?

Comment (ijjk) [reply test/integration/middleware/with-builtin-module/test/index.test.js:33]: Sounds good to investigate separately x-ref: https://github.com/vercel/next.js/issues/36575

**Review by ijjk — APPROVED** [review]
