### PR TITLE
Fix IE11 incompatibility due to string litterals

### LINKED ISSUE #22270: Error in ie11 in the dev env after 10.0.5 -> 10.0.6 upgrade. Nextjs with custom server.
**What version of Next.js are you using?**

10.0.6

**What version of Node.js are you using?**

14.14.0

**What browser are you using?**

ie11, chrome

**What operating system are you using?**

win7, win10, linux mint

**How are you deploying your application?**

`next({ dev }).prepare()`

**Describe the Bug**

After 10.0.5 -> 10.0.6 upgrade I get an error in the dev env: "Error was not caught SyntaxError: invalid character".

With next 10.0.5 there is no error in ie11.

**Expected Behavior**

Work without errors.

**To Reproduce**

I use custom webpack config in next.config.js:

```
webpack: (config) => {
    config.entry = async () => {
      const entries = await originalEntry();
      if (
        entries["main.js"] && !entries["main.js"].includes("./polyfills.js")
      ) {
        entries["main.js"].unshift("./polyfills.js");
      }
      return entries;
   };
    config.module.rules.push({
      test: /\.js$/,
      use:
      { loader: "babel-loader",
        options: {
          presets: [[
              "@babel/preset-env", {
                corejs: 3,
                useBuiltIns: "entry",
                targets: {
                  browsers: ["defaults"],
                }},
            ]],
          exclude: [/node_modules/],
        }},
    });
    return config;
  }
```
polyfills.js:
```
import "@webcomponents/shadydom";
```
babel.config.json:
```
{
  "presets": ["next/babel"],
  "plugins": [["styled-components", { "ssr": true }]]
}
```

ie_err_1
ie_err_2

### PR DESCRIPTION
**Pull request by malixsys**
Fixes #22270

## Bug

- [X] Related issues linked using `fixes #number`
- [  ] Integration tests added

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.9s | ⚠️ +217ms |
| nodeModulesSize | 46 MB | 46 MB | ⚠️ +79 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.74 | 2.939 | ⚠️ +0.2 |
| / avg req/sec | 912.53 | 850.55 | ⚠️ -61.98 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.626 | 1.838 | ⚠️ +0.21 |
| /error-in-render avg req/sec | 1537.2 | 1360.32 | ⚠️ -176.88 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 677f882d2ed8..e6c6.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-8fbabfc..6440.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-d07ca..ef4d.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-9716187d..0aa8.js gzip | 536 B | 536 B | ✓ |
| hooks-107e90..74c7.js gzip | 888 B | 888 B | ✓ |
| index-ac435c..ecf2.js gzip | 227 B | 227 B | ✓ |
| link-c31053f..c329.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..dc9d.js gzip | 303 B | 303 B | ✓ |
| withRouter-6..0e02.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.89 kB | 8.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 371 B | 371 B | ✓ |
| Overall change | 371 B | 371 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 15.4s | 14.2s | -1.2s |
| nodeModulesSize | 46 MB | 46 MB | ⚠️ +79 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 677f882d2ed8..e6c6.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-8fbabfc..6440.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-d07ca..ef4d.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-9716187d..0aa8.js gzip | 536 B | 536 B | ✓ |
| hooks-107e90..74c7.js gzip | 888 B | 888 B | ✓ |
| index-ac435c..ecf2.js gzip | 227 B | 227 B | ✓ |
| link-c31053f..c329.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..dc9d.js gzip | 303 B | 303 B | ✓ |
| withRouter-6..0e02.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.89 kB | 8.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 371 B | 371 B | ✓ |
| Overall change | 371 B | 371 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _error.js | 1.37 MB | 1.37 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| 500.html | 2.65 kB | 2.65 kB | ✓ |
| amp.amp.html | 10.7 kB | 10.7 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.37 MB | 1.37 MB | ✓ |
| link.js | 1.42 MB | 1.42 MB | ✓ |
| routerDirect.js | 1.42 MB | 1.42 MB | ✓ |
| withRouter.js | 1.42 MB | 1.42 MB | ✓ |
| Overall change | 7.01 MB | 7.01 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 14.6s | 14.9s | ⚠️ +287ms |
| nodeModulesSize | 46 MB | 46 MB | ⚠️ +79 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.73 | 2.723 | -0.01 |
| / avg req/sec | 915.71 | 918.06 | +2.35 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.602 | 1.511 | -0.09 |
| /error-in-render avg req/sec | 1560.53 | 1654.36 | +93.83 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 597-3f457946..288d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-5cc798ac..5c25.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-5cc66b2..6f03.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-55112..054d.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-89a5460c..567f.js gzip | 558 B | 558 B | ✓ |
| hooks-8c2e74..be37.js gzip | 924 B | 924 B | ✓ |
| index-fec729..83b2.js gzip | 243 B | 243 B | ✓ |
| link-dd34d9b..0ade.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..5759.js gzip | 336 B | 336 B | ✓ |
| withRouter-1..98bf.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 610 B | 610 B | ✓ |
| link.html gzip | 617 B | 617 B | ✓ |
| withRouter.html gzip | 605 B | 605 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "K4-QBMJi4Qqg4DP82PYJC",
+        "buildId": "DU61jFcK1G_NyImj5gm5J",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/K4-QBMJi4Qqg4DP82PYJC/_buildManifest.js"
+      src="/_next/static/DU61jFcK1G_NyImj5gm5J/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/K4-QBMJi4Qqg4DP82PYJC/_ssgManifest.js"
+      src="/_next/static/DU61jFcK1G_NyImj5gm5J/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "K4-QBMJi4Qqg4DP82PYJC",
+        "buildId": "DU61jFcK1G_NyImj5gm5J",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/K4-QBMJi4Qqg4DP82PYJC/_buildManifest.js"
+      src="/_next/static/DU61jFcK1G_NyImj5gm5J/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/K4-QBMJi4Qqg4DP82PYJC/_ssgManifest.js"
+      src="/_next/static/DU61jFcK1G_NyImj5gm5J/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "K4-QBMJi4Qqg4DP82PYJC",
+        "buildId": "DU61jFcK1G_NyImj5gm5J",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/K4-QBMJi4Qqg4DP82PYJC/_buildManifest.js"
+      src="/_next/static/DU61jFcK1G_NyImj5gm5J/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/K4-QBMJi4Qqg4DP82PYJC/_ssgManifest.js"
+      src="/_next/static/DU61jFcK1G_NyImj5gm5J/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 4c66f00082ad3001d9c38d49a46be708a1ff5e76

File: packages/next/build/webpack/loaders/next-style-loader/runtime/injectStylesIntoStyleTag.js [hunk 1]
```diff
@@ -189,9 +189,8 @@ function applyToTag(style, options, obj) {
   }
 
   if (sourceMap && typeof btoa !== 'undefined') {
-    css += `\n/*# sourceMappingURL=data:application/json;base64,${btoa(
-      unescape(encodeURIComponent(JSON.stringify(sourceMap)))
-    )} */`
+    css += '\n/*# sourceMappingURL=data:application/jsonbase64,' +
```
Comment (ijjk) [inline packages/next/build/webpack/loaders/next-style-loader/runtime/injectStylesIntoStyleTag.js:192]:
```suggestion
    css += '\n/*# sourceMappingURL=data:application/json;base64,' +
```

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 13.7s | 13.5s | -221ms |
| nodeModulesSize | 46 MB | 46 MB | ⚠️ +87 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.949 | 2.843 | -0.11 |
| / avg req/sec | 847.63 | 879.29 | +31.66 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.653 | 1.615 | -0.04 |
| /error-in-render avg req/sec | 1512.17 | 1548.13 | +35.96 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 677f882d2ed8..e6c6.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-8fbabfc..6440.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-d07ca..ef4d.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-9716187d..0aa8.js gzip | 536 B | 536 B | ✓ |
| hooks-107e90..74c7.js gzip | 888 B | 888 B | ✓ |
| index-ac435c..ecf2.js gzip | 227 B | 227 B | ✓ |
| link-c31053f..c329.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..dc9d.js gzip | 303 B | 303 B | ✓ |
| withRouter-6..0e02.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.89 kB | 8.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 371 B | 371 B | ✓ |
| Overall change | 371 B | 371 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 16s | 15.6s | -339ms |
| nodeModulesSize | 46 MB | 46 MB | ⚠️ +87 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 677f882d2ed8..e6c6.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-8fbabfc..6440.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-d07ca..ef4d.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-9716187d..0aa8.js gzip | 536 B | 536 B | ✓ |
| hooks-107e90..74c7.js gzip | 888 B | 888 B | ✓ |
| index-ac435c..ecf2.js gzip | 227 B | 227 B | ✓ |
| link-c31053f..c329.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..dc9d.js gzip | 303 B | 303 B | ✓ |
| withRouter-6..0e02.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.89 kB | 8.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 371 B | 371 B | ✓ |
| Overall change | 371 B | 371 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _error.js | 1.37 MB | 1.37 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| 500.html | 2.65 kB | 2.65 kB | ✓ |
| amp.amp.html | 10.7 kB | 10.7 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.37 MB | 1.37 MB | ✓ |
| link.js | 1.42 MB | 1.42 MB | ✓ |
| routerDirect.js | 1.42 MB | 1.42 MB | ✓ |
| withRouter.js | 1.42 MB | 1.42 MB | ✓ |
| Overall change | 7.01 MB | 7.01 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 16.3s | 16.9s | ⚠️ +576ms |
| nodeModulesSize | 46 MB | 46 MB | ⚠️ +87 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.019 | 3.007 | -0.01 |
| / avg req/sec | 827.96 | 831.38 | +3.42 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.715 | 1.789 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1458.04 | 1397.15 | ⚠️ -60.89 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 597-3f457946..288d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-5cc798ac..5c25.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-5cc66b2..6f03.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-55112..054d.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-89a5460c..567f.js gzip | 558 B | 558 B | ✓ |
| hooks-8c2e74..be37.js gzip | 924 B | 924 B | ✓ |
| index-fec729..83b2.js gzip | 243 B | 243 B | ✓ |
| link-dd34d9b..0ade.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..5759.js gzip | 336 B | 336 B | ✓ |
| withRouter-1..98bf.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 610 B | 610 B | ✓ |
| link.html gzip | 617 B | 617 B | ✓ |
| withRouter.html gzip | 605 B | 605 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "D1RlPjHjyIHXU28c3v4pq",
+        "buildId": "H4oFiJHqIkA10JVlH8mtf",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/D1RlPjHjyIHXU28c3v4pq/_buildManifest.js"
+      src="/_next/static/H4oFiJHqIkA10JVlH8mtf/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/D1RlPjHjyIHXU28c3v4pq/_ssgManifest.js"
+      src="/_next/static/H4oFiJHqIkA10JVlH8mtf/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "D1RlPjHjyIHXU28c3v4pq",
+        "buildId": "H4oFiJHqIkA10JVlH8mtf",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/D1RlPjHjyIHXU28c3v4pq/_buildManifest.js"
+      src="/_next/static/H4oFiJHqIkA10JVlH8mtf/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/D1RlPjHjyIHXU28c3v4pq/_ssgManifest.js"
+      src="/_next/static/H4oFiJHqIkA10JVlH8mtf/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "D1RlPjHjyIHXU28c3v4pq",
+        "buildId": "H4oFiJHqIkA10JVlH8mtf",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/D1RlPjHjyIHXU28c3v4pq/_buildManifest.js"
+      src="/_next/static/H4oFiJHqIkA10JVlH8mtf/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/D1RlPjHjyIHXU28c3v4pq/_ssgManifest.js"
+      src="/_next/static/H4oFiJHqIkA10JVlH8mtf/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 4cf2c081e53e09fc7cb25c0d9318a833d466ab75

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.5s | ⚠️ +253ms |
| nodeModulesSize | 46 MB | 46 MB | ⚠️ +89 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.845 | 2.782 | -0.06 |
| / avg req/sec | 878.66 | 898.6 | +19.94 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.69 | 1.674 | -0.02 |
| /error-in-render avg req/sec | 1479.64 | 1493.49 | +13.85 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 677f882d2ed8..e6c6.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-8fbabfc..6440.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-d07ca..ef4d.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-9716187d..0aa8.js gzip | 536 B | 536 B | ✓ |
| hooks-107e90..74c7.js gzip | 888 B | 888 B | ✓ |
| index-ac435c..ecf2.js gzip | 227 B | 227 B | ✓ |
| link-c31053f..c329.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..dc9d.js gzip | 303 B | 303 B | ✓ |
| withRouter-6..0e02.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.89 kB | 8.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 371 B | 371 B | ✓ |
| Overall change | 371 B | 371 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 15.7s | 15.4s | -300ms |
| nodeModulesSize | 46 MB | 46 MB | ⚠️ +89 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 677f882d2ed8..e6c6.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-8fbabfc..6440.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-d07ca..ef4d.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-9716187d..0aa8.js gzip | 536 B | 536 B | ✓ |
| hooks-107e90..74c7.js gzip | 888 B | 888 B | ✓ |
| index-ac435c..ecf2.js gzip | 227 B | 227 B | ✓ |
| link-c31053f..c329.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..dc9d.js gzip | 303 B | 303 B | ✓ |
| withRouter-6..0e02.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.89 kB | 8.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 371 B | 371 B | ✓ |
| Overall change | 371 B | 371 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _error.js | 1.37 MB | 1.37 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| 500.html | 2.65 kB | 2.65 kB | ✓ |
| amp.amp.html | 10.7 kB | 10.7 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.37 MB | 1.37 MB | ✓ |
| link.js | 1.42 MB | 1.42 MB | ✓ |
| routerDirect.js | 1.42 MB | 1.42 MB | ✓ |
| withRouter.js | 1.42 MB | 1.42 MB | ✓ |
| Overall change | 7.01 MB | 7.01 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 15.8s | 16.1s | ⚠️ +231ms |
| nodeModulesSize | 46 MB | 46 MB | ⚠️ +89 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.881 | 2.923 | ⚠️ +0.04 |
| / avg req/sec | 867.86 | 855.4 | ⚠️ -12.46 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.657 | 1.69 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1508.67 | 1479.63 | ⚠️ -29.04 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 597-3f457946..288d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-5cc798ac..5c25.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-5cc66b2..6f03.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-55112..054d.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-89a5460c..567f.js gzip | 558 B | 558 B | ✓ |
| hooks-8c2e74..be37.js gzip | 924 B | 924 B | ✓ |
| index-fec729..83b2.js gzip | 243 B | 243 B | ✓ |
| link-dd34d9b..0ade.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..5759.js gzip | 336 B | 336 B | ✓ |
| withRouter-1..98bf.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 610 B | 610 B | ✓ |
| link.html gzip | 617 B | 617 B | ✓ |
| withRouter.html gzip | 605 B | 605 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "fYJnKE9EfGOMThKOl2nOW",
+        "buildId": "ThdQNXo_HGmgE_5jCyA0G",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/fYJnKE9EfGOMThKOl2nOW/_buildManifest.js"
+      src="/_next/static/ThdQNXo_HGmgE_5jCyA0G/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/fYJnKE9EfGOMThKOl2nOW/_ssgManifest.js"
+      src="/_next/static/ThdQNXo_HGmgE_5jCyA0G/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "fYJnKE9EfGOMThKOl2nOW",
+        "buildId": "ThdQNXo_HGmgE_5jCyA0G",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/fYJnKE9EfGOMThKOl2nOW/_buildManifest.js"
+      src="/_next/static/ThdQNXo_HGmgE_5jCyA0G/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/fYJnKE9EfGOMThKOl2nOW/_ssgManifest.js"
+      src="/_next/static/ThdQNXo_HGmgE_5jCyA0G/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "fYJnKE9EfGOMThKOl2nOW",
+        "buildId": "ThdQNXo_HGmgE_5jCyA0G",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/fYJnKE9EfGOMThKOl2nOW/_buildManifest.js"
+      src="/_next/static/ThdQNXo_HGmgE_5jCyA0G/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/fYJnKE9EfGOMThKOl2nOW/_ssgManifest.js"
+      src="/_next/static/ThdQNXo_HGmgE_5jCyA0G/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: e207abf93f164763d2ad13f0b5f39f7434925acb

**Review by timneutkens — DISMISSED** [review]
Thanks!

**Comment by jasonwilliams** [comment]
I've just been testing this against my local build.
Although this fixes the error in the related issue it seems IE falls into another error.

```
"SyntaxError: Expected ':'
 at ./node_modules/next/dist/build/webpack/loaders/next-style-loader/runtime/injectStylesIntoStyleTag.js (https://www.test.com/_next/static/chunks/pages/_app.js?ts=1617879187598:1155:1)
```

**Comment by jasonwilliams** [comment]
The [short function syntax](https://github.com/vercel/next.js/blob/e207abf93f164763d2ad13f0b5f39f7434925acb/packages/next/build/webpack/loaders/next-style-loader/runtime/injectStylesIntoStyleTag.js#L254) also needs changing to `function`

**Comment by jasonwilliams** [comment]
https://github.com/vercel/next.js/blob/e207abf93f164763d2ad13f0b5f39f7434925acb/packages/next/build/webpack/loaders/next-style-loader/runtime/injectStylesIntoStyleTag.js#L86 needs to be `identifier: identifier`

**Comment by jasonwilliams** [comment]
with those above changes we should be good, but its not clear how long this fix will last, it doesn't look to me like this file was ever designed to run in IE in the first place so I'm not sure what's happening here: @timneutkens ?

**Comment by jasonwilliams** [comment]
https://github.com/vercel/next.js/blob/bf16e5879d49e56419917ee6e82a0c123edf987c/packages/next/build/webpack/loaders/next-style-loader/runtime/injectStylesIntoStyleTag.js#L254 is still short function syntax

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 14.5s | 14.4s | -90ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.531 | 2.455 | -0.08 |
| / avg req/sec | 987.67 | 1018.32 | +30.65 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.369 | 1.296 | -0.07 |
| /error-in-render avg req/sec | 1826.7 | 1928.83 | +102.13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 597-3f457946..288d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-6834d41c..48a9.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-5cc66b2..6f03.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-55112..054d.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-89a5460c..567f.js gzip | 558 B | 558 B | ✓ |
| hooks-8c2e74..be37.js gzip | 924 B | 924 B | ✓ |
| index-fec729..83b2.js gzip | 243 B | 243 B | ✓ |
| link-dd34d9b..0ade.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..5759.js gzip | 336 B | 336 B | ✓ |
| withRouter-1..98bf.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 610 B | 610 B | ✓ |
| link.html gzip | 617 B | 617 B | ✓ |
| withRouter.html gzip | 605 B | 605 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 18.2s | 17.9s | -307ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 597-3f457946..288d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-6834d41c..48a9.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-5cc66b2..6f03.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-55112..054d.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-89a5460c..567f.js gzip | 558 B | 558 B | ✓ |
| hooks-8c2e74..be37.js gzip | 924 B | 924 B | ✓ |
| index-fec729..83b2.js gzip | 243 B | 243 B | ✓ |
| link-dd34d9b..0ade.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..5759.js gzip | 336 B | 336 B | ✓ |
| withRouter-1..98bf.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _error.js | 1.35 MB | 1.35 MB | ✓ |
| 404.html | 2.76 kB | 2.76 kB | ✓ |
| 500.html | 2.75 kB | 2.75 kB | ✓ |
| amp.amp.html | 10.7 kB | 10.7 kB | ✓ |
| amp.html | 1.96 kB | 1.96 kB | ✓ |
| hooks.html | 2.01 kB | 2.01 kB | ✓ |
| index.js | 1.35 MB | 1.35 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.4 MB | 1.4 MB | ✓ |
| withRouter.js | 1.4 MB | 1.4 MB | ✓ |
| Overall change | 6.91 MB | 6.91 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.4s | ⚠️ +282ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.504 | 2.606 | ⚠️ +0.1 |
| / avg req/sec | 998.5 | 959.29 | ⚠️ -39.21 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.32 | 1.311 | -0.01 |
| /error-in-render avg req/sec | 1893.92 | 1907.54 | +13.62 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 597-3f457946..288d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-6834d41c..48a9.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-5cc66b2..6f03.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-55112..054d.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-89a5460c..567f.js gzip | 558 B | 558 B | ✓ |
| hooks-8c2e74..be37.js gzip | 924 B | 924 B | ✓ |
| index-fec729..83b2.js gzip | 243 B | 243 B | ✓ |
| link-dd34d9b..0ade.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..5759.js gzip | 336 B | 336 B | ✓ |
| withRouter-1..98bf.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 610 B | 610 B | ✓ |
| link.html gzip | 617 B | 617 B | ✓ |
| withRouter.html gzip | 605 B | 605 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "8mUpERk4EcMujDew6OcwK",
+        "buildId": "wArbqtvrV6sUMdkXSHBMc",
         "isFallback": false,
         "gip": true
       }
@@ -86,11 +86,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/8mUpERk4EcMujDew6OcwK/_buildManifest.js"
+      src="/_next/static/wArbqtvrV6sUMdkXSHBMc/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/8mUpERk4EcMujDew6OcwK/_ssgManifest.js"
+      src="/_next/static/wArbqtvrV6sUMdkXSHBMc/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -53,7 +53,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "8mUpERk4EcMujDew6OcwK",
+        "buildId": "wArbqtvrV6sUMdkXSHBMc",
         "isFallback": false,
         "gip": true
       }
@@ -91,11 +91,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/8mUpERk4EcMujDew6OcwK/_buildManifest.js"
+      src="/_next/static/wArbqtvrV6sUMdkXSHBMc/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/8mUpERk4EcMujDew6OcwK/_ssgManifest.js"
+      src="/_next/static/wArbqtvrV6sUMdkXSHBMc/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "8mUpERk4EcMujDew6OcwK",
+        "buildId": "wArbqtvrV6sUMdkXSHBMc",
         "isFallback": false,
         "gip": true
       }
@@ -86,11 +86,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/8mUpERk4EcMujDew6OcwK/_buildManifest.js"
+      src="/_next/static/wArbqtvrV6sUMdkXSHBMc/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/8mUpERk4EcMujDew6OcwK/_ssgManifest.js"
+      src="/_next/static/wArbqtvrV6sUMdkXSHBMc/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 2888c44cd610692c4a92fe8a19997752ea3e3d7f

**Review by jasonwilliams — DISMISSED** [review]

**Review by timneutkens — DISMISSED** [review]
Can you add an integration test to test_ie11_production for this, just to make sure it keeps working in the future.

**Comment by malixsys** [comment]
> Can you add an integration test to test_ie11_production for this, just to make sure it keeps working in the future.

@timneutkens I can't find where to add one that would force loading `next-style-loader` in IE 🤔

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.2s | -588ms |
| nodeModulesSize | 46.2 MB | 46.2 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.226 | 2.159 | -0.07 |
| / avg req/sec | 1122.93 | 1157.85 | +34.92 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.119 | 1.12 | 0 |
| /error-in-render avg req/sec | 2233.79 | 2232.2 | ⚠️ -1.59 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 597-3f457946..288d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-9c11a899..1178.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-5cc66b2..6f03.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-55112..054d.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-89a5460c..567f.js gzip | 558 B | 558 B | ✓ |
| hooks-8c2e74..be37.js gzip | 924 B | 924 B | ✓ |
| index-fec729..83b2.js gzip | 243 B | 243 B | ✓ |
| link-dd34d9b..0ade.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..5759.js gzip | 336 B | 336 B | ✓ |
| withRouter-1..98bf.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 609 B | 609 B | ✓ |
| link.html gzip | 616 B | 616 B | ✓ |
| withRouter.html gzip | 605 B | 605 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 15.9s | 16.4s | ⚠️ +484ms |
| nodeModulesSize | 46.2 MB | 46.2 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 597-3f457946..288d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-9c11a899..1178.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-5cc66b2..6f03.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-55112..054d.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-89a5460c..567f.js gzip | 558 B | 558 B | ✓ |
| hooks-8c2e74..be37.js gzip | 924 B | 924 B | ✓ |
| index-fec729..83b2.js gzip | 243 B | 243 B | ✓ |
| link-dd34d9b..0ade.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..5759.js gzip | 336 B | 336 B | ✓ |
| withRouter-1..98bf.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _error.js | 1.39 MB | 1.39 MB | ✓ |
| 404.html | 2.76 kB | 2.76 kB | ✓ |
| 500.html | 2.75 kB | 2.75 kB | ✓ |
| amp.amp.html | 10.7 kB | 10.7 kB | ✓ |
| amp.html | 1.96 kB | 1.96 kB | ✓ |
| hooks.html | 2.01 kB | 2.01 kB | ✓ |
| index.js | 1.39 MB | 1.39 MB | ✓ |
| link.js | 1.45 MB | 1.45 MB | ✓ |
| routerDirect.js | 1.44 MB | 1.44 MB | ✓ |
| withRouter.js | 1.44 MB | 1.44 MB | -2 B |
| Overall change | 7.14 MB | 7.14 MB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.4s | -220ms |
| nodeModulesSize | 46.2 MB | 46.2 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.259 | 2.243 | -0.02 |
| / avg req/sec | 1106.6 | 1114.64 | +8.04 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.193 | 1.181 | -0.01 |
| /error-in-render avg req/sec | 2096.31 | 2116.85 | +20.54 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 597-3f457946..288d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-9c11a899..1178.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-5cc66b2..6f03.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-55112..054d.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-89a5460c..567f.js gzip | 558 B | 558 B | ✓ |
| hooks-8c2e74..be37.js gzip | 924 B | 924 B | ✓ |
| index-fec729..83b2.js gzip | 243 B | 243 B | ✓ |
| link-dd34d9b..0ade.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..5759.js gzip | 336 B | 336 B | ✓ |
| withRouter-1..98bf.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 609 B | 609 B | ✓ |
| link.html gzip | 616 B | 616 B | ✓ |
| withRouter.html gzip | 605 B | 605 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "MUnrJhpJj17cx74PVXcTc",
+        "buildId": "23hysp-nwVpfmK06pr93V",
         "isFallback": false,
         "gip": true
       }
@@ -86,11 +86,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/MUnrJhpJj17cx74PVXcTc/_buildManifest.js"
+      src="/_next/static/23hysp-nwVpfmK06pr93V/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/MUnrJhpJj17cx74PVXcTc/_ssgManifest.js"
+      src="/_next/static/23hysp-nwVpfmK06pr93V/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -53,7 +53,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "MUnrJhpJj17cx74PVXcTc",
+        "buildId": "23hysp-nwVpfmK06pr93V",
         "isFallback": false,
         "gip": true
       }
@@ -91,11 +91,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/MUnrJhpJj17cx74PVXcTc/_buildManifest.js"
+      src="/_next/static/23hysp-nwVpfmK06pr93V/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/MUnrJhpJj17cx74PVXcTc/_ssgManifest.js"
+      src="/_next/static/23hysp-nwVpfmK06pr93V/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "MUnrJhpJj17cx74PVXcTc",
+        "buildId": "23hysp-nwVpfmK06pr93V",
         "isFallback": false,
         "gip": true
       }
@@ -86,11 +86,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/MUnrJhpJj17cx74PVXcTc/_buildManifest.js"
+      src="/_next/static/23hysp-nwVpfmK06pr93V/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/MUnrJhpJj17cx74PVXcTc/_ssgManifest.js"
+      src="/_next/static/23hysp-nwVpfmK06pr93V/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 473dccd03946c70817780b8a27ad36ce4226be17

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 15.3s | 15.3s | -14ms |
| buildDurationCached | 4.7s | 4.7s | -4ms |
| nodeModulesSize | 46.2 MB | 46.2 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.715 | 2.821 | ⚠️ +0.11 |
| / avg req/sec | 920.7 | 886.25 | ⚠️ -34.45 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.585 | 1.599 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1577.08 | 1563.44 | ⚠️ -13.64 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 611 B | 611 B | ✓ |
| link.html gzip | 616 B | 616 B | ✓ |
| withRouter.html gzip | 605 B | 605 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 19.2s | 18.8s | -422ms |
| buildDurationCached | 6.8s | 6.8s | -4ms |
| nodeModulesSize | 46.2 MB | 46.2 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _error.js | 1.39 MB | 1.39 MB | ✓ |
| 404.html | 2.76 kB | 2.76 kB | ✓ |
| 500.html | 2.75 kB | 2.75 kB | ✓ |
| amp.amp.html | 10.7 kB | 10.7 kB | ✓ |
| amp.html | 1.96 kB | 1.96 kB | ✓ |
| hooks.html | 2.01 kB | 2.01 kB | ✓ |
| index.js | 1.39 MB | 1.39 MB | ✓ |
| link.js | 1.45 MB | 1.45 MB | ✓ |
| routerDirect.js | 1.44 MB | 1.44 MB | ✓ |
| withRouter.js | 1.44 MB | 1.44 MB | ✓ |
| Overall change | 7.14 MB | 7.14 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 12.9s | 13.1s | ⚠️ +208ms |
| buildDurationCached | 5.4s | 5.2s | -167ms |
| nodeModulesSize | 46.2 MB | 46.2 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.72 | 2.679 | -0.04 |
| / avg req/sec | 919.2 | 933.21 | +14.01 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.598 | 1.58 | -0.02 |
| /error-in-render avg req/sec | 1564.41 | 1582.18 | +17.77 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| hooks-HASH.js gzip | 888 B | 888 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.89 kB | 8.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 371 B | 371 B | ✓ |
| Overall change | 371 B | 371 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 612 B | 612 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: 06be761aed13f47d301aeaa8b689f7ea88c1153f

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 15.1s | 15s | -99ms |
| buildDurationCached | 4.5s | 4.7s | ⚠️ +136ms |
| nodeModulesSize | 46.2 MB | 46.2 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.819 | 2.654 | -0.17 |
| / avg req/sec | 886.83 | 942.01 | +55.18 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.57 | 1.481 | -0.09 |
| /error-in-render avg req/sec | 1592.27 | 1687.76 | +95.49 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 611 B | 611 B | ✓ |
| link.html gzip | 616 B | 616 B | ✓ |
| withRouter.html gzip | 605 B | 605 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 18.5s | 18.3s | -134ms |
| buildDurationCached | 6.5s | 6.5s | -30ms |
| nodeModulesSize | 46.2 MB | 46.2 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _error.js | 1.39 MB | 1.39 MB | ✓ |
| 404.html | 2.76 kB | 2.76 kB | ✓ |
| 500.html | 2.75 kB | 2.75 kB | ✓ |
| amp.amp.html | 10.7 kB | 10.7 kB | ✓ |
| amp.html | 1.96 kB | 1.96 kB | ✓ |
| hooks.html | 2.01 kB | 2.01 kB | ✓ |
| index.js | 1.39 MB | 1.39 MB | -2 B |
| link.js | 1.45 MB | 1.45 MB | ✓ |
| routerDirect.js | 1.44 MB | 1.44 MB | -2 B |
| withRouter.js | 1.44 MB | 1.44 MB | ✓ |
| Overall change | 7.14 MB | 7.14 MB | -4 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.6s | -258ms |
| buildDurationCached | 5.4s | 5s | -377ms |
| nodeModulesSize | 46.2 MB | 46.2 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.727 | 2.824 | ⚠️ +0.1 |
| / avg req/sec | 916.65 | 885.26 | ⚠️ -31.39 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.605 | 1.532 | -0.07 |
| /error-in-render avg req/sec | 1557.48 | 1631.88 | +74.4 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| hooks-HASH.js gzip | 888 B | 888 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.89 kB | 8.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 371 B | 371 B | ✓ |
| Overall change | 371 B | 371 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | malixsys/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 612 B | 612 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: a0fe54edcee58f74c2a635c2635aa6b1a9cc35eb
