### PR TITLE
Fix: HMR in multi-zone handling 🌱

### LINKED ISSUE #54454: Multi-zone not working on version 13.4.19. 13.4.3 works fine
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.19
      pnpm: 7.32.2
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A


warn  - Latest canary version not detected, detected: "13.4.19", newest: "13.4.20-canary.3".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
✨  Done in 5.96s.
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

yarn dev

### To Reproduce

on `next.config.js` add 

```
const { APP_URL } = process.env

/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return [
      {
        source: '/:path*',
        destination: `/:path*`,
      },
      {
        source: '/app',
        destination: `${APP_URL}/app`,
      },
      {
        source: '/app/:path*',
        destination: `${APP_URL}/app/:path*`,
      },
    ]
  },
}

module.exports = nextConfig
```
on `.env.local` add
APP_URL=http://localhost:3001

http://localhost:3001 references another nextjs app on port 3001

### Describe the Bug

When using Multi-zone to video a second app. The app refreshes indefinitely. The terminal prints https://nextjs.org/docs/messages/fast-refresh-reload 

### Expected Behavior

Downgrading to version 13.4.3 works fine. The app doesn't refresh indefinitely when using multi-zone

### Which browser are you using? (if relevant)

Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

not deployed yet

### LINKED ISSUE #56615: Rewrite loop when using next-dev with localhost and different ports e.g. MultiZone setup
### Link to the code that reproduces this issue

https://github.com/PacoSoftwerft/multi-zone-microfrontends

## Start main-site

```bash
cd main-site
npm run dev
```

## Start blog

Start the blog in a new shell

```bash
cd blog
npm run dev
```

## Bug

Open `http://localhost:3000/blog`, it is loading in a loop.

### Current vs. Expected behavior

Expected behavior:

rewrite to same domain "localhost" with different port should work like they did in 13.4.12

Version `next@13.4.12` is working just fine.
Stop the `main-site` then

```bash
cd main-site
npm i next@13.4.12 --save-exact
npm run dev
```

open `http://localhost:3000/blog`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

Node:           v18.18.0
npm:            10.1.0
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Additional context

This bug was introduced with **13.4.13**

The bug only appears when using the **Pages Router**

The bug depends on the version of the app that rewrites, here **main-site**.

It seems like the **port** is stripped/not respected somewhere.

The rewrite works if it points to another domain.

Additional info 2023-10-20

The bug only appears when **both** zones are started with `npm run dev`

| main (3000) | blog (3001) | works?  |
|---|---|---|
| `npm run dev` | `npm run dev` | ❌ |
| `npm run dev` | `npm run build`  `npm run start`   | ✅ |
|  `npm run build`  `npm run start` | `npm run dev` | ✅ |
| `npm run build`  `npm run start` | `npm run build`  `npm run start` | ✅|

### LINKED ISSUE #59161: Bug: Apps under rewrites() rules are reloaded indefinitely at the development side only.
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #99~20.04.1-Ubuntu SMP Thu Nov 2 15:16:47 UTC 2023
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.18
  pnpm: 8.6.7
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 13.0.7
  react: 0.0.0-experimental-ee8509801-20230117
  react-dom: 0.0.0-experimental-ee8509801-20230117
  typescript: 4.9.4
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

https://github.com/vercel/next.js/tree/canary/examples/with-zones

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

When using Multi-zone example, the app under rewrites() rules are reload indefinitely only at development side.
Terminal prints (at each auto refreshes):
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload

PS: I know this issue is a duplicate of https://github.com/vercel/next.js/issues/54454#issuecomment-1835418576, but this is becoming a matter of urgency, as we can no longer update Next beyond version 13.4.6 because it's impossible for us to develop. (and some many security updates related to nextjs packages are really high)

### Expected Behavior

Shouldn't reload applications behind rewrites() rules in a loop.

### To Reproduce

Start both or checkout https://github.com/vercel/next.js/tree/canary/examples/with-zones:
https://codesandbox.io/p/sandbox/multi-zones-1-m79cw8?file=%2F.env%3A2%2C1
https://codesandbox.io/p/sandbox/multi-zones-2-xfk4d9?file=%2Fmiddleware.js%3A11%2C2

And click on "Zone 2" inside the navbar.

### PR DESCRIPTION
**Pull request by agustints**
### What?
When running a [multi-zone](https://github.com/vercel/next.js/tree/canary/examples/with-zones) app in dev, guest app pages would infinitely reload if you change the basePath of the host app to the default one (omit basePath settings in next.config.js) (empty string `""` as per Next.js docs).

### Why?
The HMR upgrade request would fail and get caught into a retry loop. In the multi-zone case, they fail because the upgrade request would be sent again for a request that had already been upgraded. This resulted in a "server.handleUpgrade() was called more than once with the same socket" error, causing the upgrade request to fail.

Every time a retry occurred, the page would trigger a full refresh since certain HMR errors cause the browser to reload.

### How?
This ensures the upgrade handler only responds to requests that match the configured basePath (considering when there is no basePath). Default basePath for Next.js applications it's an empty string `""`.
 
Ref: https://nextjs.org/docs/app/api-reference/next-config-js/basePath

Other fixes & updates related to the bug:
- Updated test apps to avoid having issues regarding client & server mismatch for dates
- Added default use case in e2e tests, where you have a default Next.js application where the basePath it's the default one and a guest app that it's being routed by the main one through Next.js rewrites.

Closes NEXT-1797
Fixes #59161
Fixes #56615
Fixes #54454

### CODE REVIEW

File: packages/next/src/server/lib/router-server.ts [hunk 1]
```diff
@@ -583,13 +583,19 @@ export async function initialize(opts: {
...
       if (opts.dev && developmentBundler && req.url) {
-        const isHMRRequest = req.url.includes('/_next/webpack-hmr')
+        const { basePath } = config
+
+        const isHMRRequestForHostApp =
+          !basePath && req.url.startsWith('/_next/webpack-hmr')
+
+        const isHMRRequestForGuestApp = pathHasPrefix(req.url, basePath)
+
+        const isHMRRequestForCurrentBasepath =
```
Comment (jamaybyrone) [inline packages/next/src/server/lib/router-server.ts:593]: With this being a solution for the HMR multizone, is this line correct?

Given zone 1 is called from zone 2 during hmr, at least one of those Boolean values would always return true, which would mean line 598 would always be true

Comment (jamaybyrone) [reply packages/next/src/server/lib/router-server.ts:593]: Would you not want something like:
` isHMRRequestForHostApp && !isHMRRequestForGuestApp`

Comment (jamaybyrone) [reply packages/next/src/server/lib/router-server.ts:593]: I tried your solution locally, and the infinite refresh still happened 
as` isHMRRequestForHostApp || isHMRRequestForGuestApp`, one of those values would always be true, i changed it to:
` isHMRRequestForHostApp && !isHMRRequestForGuestApp` and this worked.

File: packages/next/src/server/lib/router-server.ts [hunk 2]
```diff
@@ -583,13 +583,19 @@ export async function initialize(opts: {
...
+          isHMRRequestForHostApp || isHMRRequestForGuestApp
```
Comment (jamaybyrone) [inline packages/next/src/server/lib/router-server.ts:594]: One of these values would always return true. I have tried this locally and the infinite refresh still happens because of this.

You don't need to check ifs the guestApp, the same check your making for the guestApp just make for the hostApp:

Tried the below locally and it works:
`const { basePath } = config

                const isHMRRequestForHostApp =
                    pathHasPrefix(req.url, basePath) && req.url.startsWith('/_next/webpack-hmr')

                if (isHMRRequestForHostApp) {
                    return developmentBundler.hotReloader.onHMR(req, socket, head)
                }`

Comment (agustints) [reply packages/next/src/server/lib/router-server.ts:594]: Hi @jamaybyrone, thanks for your review, I tried to reproduce the thing that you mention in the example app locally and it seems to be working as it expected (without any change). 
Could you provide more details so I can help you?

CMD's that I used to test multi-zone example (provided by Next.js team)
> [!WARNING]  
> If you run the app without `next-with-deps` part the apps will use the current canary version that have the bug.

`pnpm run dev` (For next.js dev mode)
`pnpm next-with-deps ./examples/with-zones/home` (For Home App)
`pnpm next-with-deps ./examples/with-zones/blog` (For Blog App)

> [!IMPORTANT]  
> This PR also updates e2e test cases so it should prevent this behaviour to appear in the future again!

Let me know if I can help you in any way, I will be happy to help!

Video:

https://github.com/vercel/next.js/assets/20648944/224322d1-0aa7-44ce-9d26-8af9d7cba7dd

Comment (jamaybyrone) [reply packages/next/src/server/lib/router-server.ts:594]: Hmm this is odd....
For me: 
Zone B Calls Zone A

Zone A nextserver is hit:
```
       const isHMRRequestForHostApp =
          !basePath && req.url.startsWith('/_next/webpack-hmr') // returns false

        const isHMRRequestForGuestApp = pathHasPrefix(req.url, basePath) // returns true
```

which then means:
```
const isHMRRequestForCurrentBasepath =
          isHMRRequestForHostApp || isHMRRequestForGuestApp // becomes true in zone A because isHMRRequestForGuestApp is true
```

which then triggers:
```
    if (isHMRRequestForCurrentBasepath) {
          return developmentBundler.hotReloader.onHMR(req, socket, head) // which this to all be hit again in zone A
        }
```

I'm not quite sure how this is working for you isHMRRequestForCurrentBasepath would always be true, there would not be an instant where this is false as its either for the host app or (||) for the guest app.

Comment (agustints) [reply packages/next/src/server/lib/router-server.ts:594]: Hi @jamaybyrone, thanks for your answer, could you provide a reproduction environment in [codesandbox](https://codesandbox.io/) or share your next.config.js setup so I can reproduce it locally? (maybe the basePath configuration it's different than the one that was reported with the issue initially #54454)

Comment (jamaybyrone) [reply packages/next/src/server/lib/router-server.ts:594]: Ahhhhhhh I had:
```
async rewrites() {
    return [
      {
        source: '/:path*',
        destination: `/:path*`,
      }
    ]
```
In the second zone! Sorry for that.

I am still very confused as to when:
isHMRRequestForCurrentBasepath would ever return false, do you have any scenarios for it?

**Comment by exneval** [comment]
Kindly review this PR cc @ztanner :pray:

File: packages/next/src/server/lib/router-server.ts (hunk 2 above)
Comment (agustints) [reply packages/next/src/server/lib/router-server.ts:594]: isHMRRequestForCurrentBasepath will be true in the host app that contains the next.js rewrites and a default base path (the scenario for it it's the one that I shared in the video) 👍

**Comment by agustints** [comment]
Hi @ztanner, @huozhi, could you help us here with a review? 
This will allow many projects to be updated to the latest version, since this issue is blocking people from updating since Next.js v13.4.3.

Thank you!

**Comment by ddeisadze** [comment]
Any updates on this, its blocking deployments for me.

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | agustints/next.js fix-hmr-dev-environment | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.9s | ⚠️ +151ms |
| buildDurationCached | 7.1s | 6.3s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +1.95 kB |
| nextStartRea..uration (ms) | 428ms | 427ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | agustints/next.js fix-hmr-dev-environment | Change |
| - | - | - | - |
| 193.HASH.js gzip | 181 B | 182 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 433-HASH.js gzip | 28.6 kB | 28.6 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 240 B | 242 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | agustints/next.js fix-hmr-dev-environment | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | agustints/next.js fix-hmr-dev-environment | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 183 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 502 B | N/A |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 253 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.28 kB | 4.28 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | ✓ |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.4 kB | 3.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | agustints/next.js fix-hmr-dev-environment | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | agustints/next.js fix-hmr-dev-environment | Change |
| - | - | - | - |
| index.html gzip | 528 B | 527 B | N/A |
| link.html gzip | 538 B | 540 B | N/A |
| withRouter.html gzip | 521 B | 523 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | agustints/next.js fix-hmr-dev-environment | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.8 kB | 93.8 kB | N/A |
| page.js gzip | 147 kB | 147 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | agustints/next.js fix-hmr-dev-environment | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 625 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | agustints/next.js fix-hmr-dev-environment | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 169 kB | 169 kB | N/A |
| app-page-exp..prod.js gzip | 94.2 kB | 94.3 kB | N/A |
| app-page-tur..prod.js gzip | 94.9 kB | 94.9 kB | N/A |
| app-page-tur..prod.js gzip | 89.5 kB | 89.5 kB | N/A |
| app-page.run...dev.js gzip | 139 kB | 139 kB | N/A |
| app-page.run..prod.js gzip | 88.8 kB | 88.8 kB | N/A |
| app-route-ex...dev.js gzip | 24.1 kB | 24.1 kB | N/A |
| app-route-ex..prod.js gzip | 16.7 kB | 16.7 kB | N/A |
| app-route-tu..prod.js gzip | 16.7 kB | 16.7 kB | N/A |
| app-route-tu..prod.js gzip | 16.3 kB | 16.3 kB | N/A |
| app-route.ru...dev.js gzip | 23.5 kB | 23.5 kB | N/A |
| app-route.ru..prod.js gzip | 16.3 kB | 16.3 kB | N/A |
| pages-api-tu..prod.js gzip | 9.38 kB | 9.38 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.65 kB | 9.65 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | N/A |
| pages.runtim...dev.js gzip | 22.6 kB | 22.6 kB | N/A |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | N/A |
| server.runti..prod.js gzip | 49.5 kB | 49.5 kB | N/A |
| Overall change | 28.4 kB | 28.4 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

```diff
@@ -16,7 +16,7 @@
       /***/
     },
 
-    /***/ 7604: /***/ (
+    /***/ 1678: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -35,7 +35,7 @@
       __webpack_require__.r(middleware_namespaceObject);
       __webpack_require__.d(middleware_namespaceObject, {
         default: () => middleware,
-      }); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/globals.js
+      }); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/globals.js
 
       async function registerInstrumentation() {
         if (
@@ -105,7 +105,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         // Eagerly fire instrumentation hook to make the startup faster.
         void ensureInstrumentationRegistered();
       }
-      enhanceGlobals(); //# sourceMappingURL=globals.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/error.js
+      enhanceGlobals(); //# sourceMappingURL=globals.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/error.js
 
       class PageSignatureError extends Error {
         constructor({ page }) {
@@ -132,7 +132,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
   Read more: https://nextjs.org/docs/messages/middleware-parse-user-agent
   `);
         }
-      } //# sourceMappingURL=error.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/utils.js
+      } //# sourceMappingURL=error.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/utils.js
 
       /**
        * Converts a Node.js IncomingHttpHeaders object to a Headers object. Any
@@ -267,7 +267,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
             }
           );
         }
-      } //# sourceMappingURL=utils.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/fetch-event.js
+      } //# sourceMappingURL=utils.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/fetch-event.js
 
       const responseSymbol = Symbol("response");
       const passThroughSymbol = Symbol("passThrough");
@@ -313,7 +313,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
             page: this.sourcePage,
           });
         }
-      } //# sourceMappingURL=fetch-event.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/i18n/detect-domain-locale.js
+      } //# sourceMappingURL=fetch-event.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/i18n/detect-domain-locale.js
 
       function detectDomainLocale(domainItems, hostname, detectedLocale) {
         if (!domainItems) return;
@@ -339,7 +339,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
             return item;
           }
         }
-      } //# sourceMappingURL=detect-domain-locale.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/remove-trailing-slash.js
+      } //# sourceMappingURL=detect-domain-locale.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/remove-trailing-slash.js
 
       /**
        * Removes the trailing slash for a given route or page path. Preserves the
@@ -349,7 +349,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
        *   - `/` -> `/`
        */ function removeTrailingSlash(route) {
         return route.replace(/\/$/, "") || "/";
-      } //# sourceMappingURL=remove-trailing-slash.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/parse-path.js
+      } //# sourceMappingURL=remove-trailing-slash.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/parse-path.js
 
       /**
        * Given a path this function will find the pathname, query and hash and return
@@ -377,7 +377,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           query: "",
           hash: "",
         };
-      } //# sourceMappingURL=parse-path.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/add-path-prefix.js
+      } //# sourceMappingURL=parse-path.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/add-path-prefix.js
 
       /**
        * Adds the provided prefix to the given path. It first ensures that the path
@@ -388,7 +388,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         }
         const { pathname, query, hash } = parsePath(path);
         return "" + prefix + pathname + query + hash;
-      } //# sourceMappingURL=add-path-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/add-path-suffix.js
+      } //# sourceMappingURL=add-path-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/add-path-suffix.js
 
       /**
        * Similarly to `addPathPrefix`, this function adds a suffix at the end on the
@@ -400,7 +400,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         }
         const { pathname, query, hash } = parsePath(path);
         return "" + pathname + suffix + query + hash;
-      } //# sourceMappingURL=add-path-suffix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/path-has-prefix.js
+      } //# sourceMappingURL=add-path-suffix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/path-has-prefix.js
 
       /**
        * Checks if a given path starts with a given prefix. It ensures it matches
@@ -413,8 +413,10 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           return false;
         }
         const { pathname } = parsePath(path);
-        return pathname === prefix || pathname.startsWith(prefix + "/");
-      } //# sourceMappingURL=path-has-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/add-locale.js
+        return (
+          pathname === prefix || (!!prefix && pathname.startsWith(prefix + "/"))
+        );
+      } //# sourceMappingURL=path-has-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/add-locale.js
 
       /**
        * For a given path and a locale, if the locale is given, it will prefix the
@@ -433,7 +435,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         }
         // Add the locale prefix to the path.
         return addPathPrefix(path, "/" + locale);
-      } //# sourceMappingURL=add-locale.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/format-next-pathname-info.js
+      } //# sourceMappingURL=add-locale.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/format-next-pathname-info.js
 
       function formatNextPathnameInfo(info) {
         let pathname = addLocale(
@@ -457,7 +459,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
             ? addPathSuffix(pathname, "/")
             : pathname
           : removeTrailingSlash(pathname);
-      } //# sourceMappingURL=format-next-pathname-info.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/get-hostname.js
+      } //# sourceMappingURL=format-next-pathname-info.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/get-hostname.js
 
       /**
        * Takes an object with a hostname property (like a parsed URL) and some
@@ -477,7 +479,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           hostname = parsed.hostname;
         } else return;
         return hostname.toLowerCase();
-      } //# sourceMappingURL=get-hostname.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/i18n/normalize-locale-path.js
+      } //# sourceMappingURL=get-hostname.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/i18n/normalize-locale-path.js
 
       /**
        * For a pathname that may include a locale from a list of locales, it
@@ -507,7 +509,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           pathname,
           detectedLocale,
         };
-      } //# sourceMappingURL=normalize-locale-path.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/remove-path-prefix.js
+      } //# sourceMappingURL=normalize-locale-path.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/remove-path-prefix.js
 
       /**
        * Given a path and a prefix it will remove the prefix when it exists in the
@@ -541,7 +543,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         // If the path without the prefix doesn't start with a `/` we need to add it
         // back to the path to make sure it's a valid path.
         return "/" + withoutPrefix;
-      } //# sourceMappingURL=remove-path-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/get-next-pathname-info.js
+      } //# sourceMappingURL=remove-path-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/get-next-pathname-info.js
 
       function getNextPathnameInfo(pathname, options) {
         var _options_nextConfig;
@@ -599,7 +601,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           }
         }
         return info;
-      } //# sourceMappingURL=get-next-pathname-info.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/next-url.js
+      } //# sourceMappingURL=get-next-pathname-info.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/next-url.js
 
       const REGEX_LOCALHOST_HOSTNAME =
         /(?!^https?:\/\/)(127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}|\[::1\]|localhost)/;
@@ -826,8 +828,8 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         }
       } //# sourceMappingURL=next-url.js.map
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@edge-runtime/cookies/index.js
-      var _edge_runtime_cookies = __webpack_require__(7220); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/cookies.js // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/request.js
+      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@edge-runtime/cookies/index.js
+      var _edge_runtime_cookies = __webpack_require__(2738); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/cookies.js // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/request.js
       //# sourceMappingURL=cookies.js.map
 
       const INTERNALS = Symbol("internal request");
@@ -904,7 +906,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         get url() {
           return this[INTERNALS].url;
         }
-      } //# sourceMappingURL=request.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/response.js
+      } //# sourceMappingURL=request.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/response.js
 
       const response_INTERNALS = Symbol("internal response");
       const REDIRECTS = new Set([301, 302, 303, 307, 308]);
@@ -1002,7 +1004,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
             headers,
           });
         }
-      } //# sourceMappingURL=response.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/relativize-url.js
+      } //# sourceMappingURL=response.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/relativize-url.js
 
       /**
        * Given a URL as a string and a base URL it will make the URL relative
@@ -1015,7 +1017,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         return relative.protocol + "//" + relative.host === origin
           ? relative.toString().replace(origin, "")
           : relative.toString();
-      } //# sourceMappingURL=relativize-url.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/client/components/app-router-headers.js
+      } //# sourceMappingURL=relativize-url.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/client/components/app-router-headers.js
 
       const RSC_HEADER = "RSC";
       const ACTION = "Next-Action";
@@ -1039,8 +1041,8 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       const NEXT_RSC_UNION_QUERY = "_rsc";
       const NEXT_DID_POSTPONE_HEADER = "x-nextjs-postponed"; //# sourceMappingURL=app-router-headers.js.map
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/modern-browserslist-target.js
-      var modern_browserslist_target = __webpack_require__(8739); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/constants.js
+      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/modern-browserslist-target.js
+      var modern_browserslist_target = __webpack_require__(3297); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/constants.js
       const COMPILER_NAMES = {
         client: "client",
         server: "server",
@@ -1193,7 +1195,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         CLIENT_STATIC_FILES_RUNTIME_REACT_REFRESH,
         CLIENT_STATIC_FILES_RUNTIME_AMP,
         CLIENT_STATIC_FILES_RUNTIME_MAIN_APP,
-      ]); //# sourceMappingURL=constants.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/internal-utils.js
+      ]); //# sourceMappingURL=constants.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/internal-utils.js
 
       const INTERNAL_QUERY_NAMES = [
         "__nextFallback",
@@ -1230,7 +1232,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         for (const key of INTERNAL_HEADERS) {
           delete headers[key];
         }
-      } //# sourceMappingURL=internal-utils.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/app-paths.js
+      } //# sourceMappingURL=internal-utils.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/shared/lib/router/utils/app-paths.js
 
       /**
        * Normalizes an app route so it represents the actual request path. Essentially
@@ -1281,7 +1283,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
        * Since this function is used on full urls it checks `?` for searchParams handling.
        */ function normalizeRscURL(url) {
         return url.replace(/\.rsc($|\?)/, "$1");
-      } //# sourceMappingURL=app-paths.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/lib/constants.js
+      } //# sourceMappingURL=app-paths.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/lib/constants.js
 
       const NEXT_QUERY_PARAM_PREFIX = "nxtP";
       const PRERENDER_REVALIDATE_HEADER = "x-prerender-revalidate";
@@ -1453,7 +1455,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         metadata: "__next_metadata__",
         metadataRoute: "__next_metadata_route__",
         metadataImageMeta: "__next_metadata_image_meta__",
-      }; // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/adapters/reflect.js
+      }; // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/adapters/reflect.js
       //# sourceMappingURL=constants.js.map
 
       class ReflectAdapter {
@@ -1473,7 +1475,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         static deleteProperty(target, prop) {
           return Reflect.deleteProperty(target, prop);
         }
-      } //# sourceMappingURL=reflect.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/adapters/headers.js
+      } //# sourceMappingURL=reflect.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/adapters/headers.js
 
       /**
        * @internal
@@ -1654,7 +1656,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         [Symbol.iterator]() {
           return this.entries();
         }
-      } //# sourceMappingURL=headers.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/adapters/request-cookies.js
+      } //# sourceMappingURL=headers.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/spec-extension/adapters/request-cookies.js
 
       /**
        * @internal
@@ -1787,7 +1789,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
             },
           });
         }
-      } //# sourceMappingURL=request-cookies.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/api-utils/index.js
+      } //# sourceMappingURL=request-cookies.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/api-utils/index.js
 
       /**
        *
@@ -1842,7 +1844,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         if (SYMBOL_CLEARED_COOKIES in res) {
           return res;
         }
-        const { serialize } = __webpack_require__(2792);
+        const { serialize } = __webpack_require__(6664);
         const previous = res.getHeader("Set-Cookie");
         res.setHeader(`Set-Cookie`, [
           ...(typeof previous === "string"
@@ -1939,7 +1941,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
             });
           },
         });
-      } //# sourceMappingURL=index.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/async-storage/draft-mode-provider.js
+      } //# sourceMappingURL=index.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/async-storage/draft-mode-provider.js
 
       class DraftModeProvider {
         constructor(previewProps, req, cookies, mutableCookies) {
@@ -1992,7 +1994,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
             expires: new Date(0),
           });
         }
-      } //# sourceMappingURL=draft-mode-provider.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/async-storage/request-async-storage-wrapper.js
+      } //# sourceMappingURL=draft-mode-provider.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/async-storage/request-async-storage-wrapper.js
 
       function getHeaders(headers) {
         const cleaned = HeadersAdapter.from(headers);
@@ -2077,10 +2079,10 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         },
       }; //# sourceMappingURL=request-async-storage-wrapper.js.map
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/client/components/async-local-storage.js
-      var async_local_storage = __webpack_require__(7987); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/client/components/request-async-storage.external.js
+      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/client/components/async-local-storage.js
+      var async_local_storage = __webpack_require__(7564); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/client/components/request-async-storage.external.js
       const requestAsyncStorage = (0,
-      async_local_storage /* createAsyncLocalStorage */.P)(); //# sourceMappingURL=request-async-storage.external.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/lib/trace/constants.js
+      async_local_storage /* createAsyncLocalStorage */.P)(); //# sourceMappingURL=request-async-storage.external.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/lib/trace/constants.js
 
       /**
        * Contains predefined constants for the trace span name in next/server.
@@ -2211,7 +2213,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         "AppRouteRouteHandlers.runHandler",
         "ResolveMetadata.generateMetadata",
         "ResolveMetadata.generateViewport",
-      ]; // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/lib/trace/tracer.js
+      ]; // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/lib/trace/tracer.js
       //# sourceMappingURL=constants.js.map
 
       let api;
@@ -2223,7 +2225,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       // the version that is bundled with Next.js.
       // the API is ~stable, so this should be fine
       if (true) {
-        api = __webpack_require__(7932);
+        api = __webpack_require__(3084);
       } else {
       }
       const {
@@ -2428,7 +2430,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       const getTracer = (() => {
         const tracer = new NextTracerImpl();
         return () => tracer;
-      })(); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/adapter.js
+      })(); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/adapter.js
       //# sourceMappingURL=tracer.js.map
 
       class NextRequestHint extends NextRequest {
@@ -2466,7 +2468,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           testApisIntercepted = true;
           if (process.env.NEXT_PRIVATE_TEST_PROXY === "true") {
             const { interceptTestApis, wrapRequestHandler } =
-              __webpack_require__(1146);
+              __webpack_require__(7089);
             interceptTestApis();
             propagator = wrapRequestHandler(propagator);
           }
@@ -2710,14 +2712,14 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           waitUntil: Promise.all(event[waitUntilSymbol]),
           fetchMetrics: request.fetchMetrics,
         };
-      } //# sourceMappingURL=adapter.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/exports/next-response.js // CONCATENATED MODULE: ./middleware.js
+      } //# sourceMappingURL=adapter.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/exports/next-response.js // CONCATENATED MODULE: ./middleware.js
 
       // This file is for modularized imports for next/server to get fully-treeshaking.
       //# sourceMappingURL=next-response.js.map
 
       async function middleware() {
         return NextResponse.next();
-      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-middleware-loader.js?absolutePagePath=private-next-root-dir%2Fmiddleware.js&page=%2Fmiddleware&rootDir=%2Ftmp%2Fnext-statsS764JB%2Fstats-app&matchers=&preferredRegion=&middlewareConfig=e30%3D!
+      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-middleware-loader.js?absolutePagePath=private-next-root-dir%2Fmiddleware.js&page=%2Fmiddleware&rootDir=%2Ftmp%2Fnext-statsS764JB%2Fstats-app&matchers=&preferredRegion=&middlewareConfig=e30%3D!
 
       // Import the userland code.
 
@@ -2744,7 +2746,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 7220: /***/ (module) => {
+    /***/ 2738: /***/ (module) => {
       "use strict";
 
       var __defProp = Object.defineProperty;
@@ -3165,7 +3167,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 7932: /***/ (
+    /***/ 3084: /***/ (
       module,
       __unused_webpack_exports,
       __webpack_require__
@@ -4804,7 +4806,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 2792: /***/ (module) => {
+    /***/ 6664: /***/ (module) => {
       "use strict";
       var __dirname = "/";
 
@@ -4934,7 +4936,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 8739: /***/ (module) => {
+    /***/ 3297: /***/ (module) => {
       "use strict";
       // Note: This file is JS because it's used by the taskfile-swc.js file, which is JS.
       // Keep file changes in sync with the corresponding `.d.ts` files.
@@ -4956,7 +4958,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 3896: /***/ (
+    /***/ 592: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -5019,7 +5021,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 1254: /***/ (
+    /***/ 8689: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -5050,7 +5052,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           return interceptFetch;
         },
       });
-      const _context = __webpack_require__(3896);
+      const _context = __webpack_require__(592);
       const reader = {
         url(req) {
           return req.url;
@@ -5179,7 +5181,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 1146: /***/ (
+    /***/ 7089: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -5205,8 +5207,8 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           return wrapRequestHandler;
         },
       });
-      const _context = __webpack_require__(3896);
-      const _fetch = __webpack_require__(1254);
+      const _context = __webpack_require__(592);
+      const _fetch = __webpack_require__(8689);
       function interceptTestApis() {
         return (0, _fetch.interceptFetch)(__webpack_require__.g.fetch);
       }
@@ -5218,7 +5220,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 7987: /***/ (
+    /***/ 7564: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -5264,7 +5266,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
-    /******/ var __webpack_exports__ = __webpack_exec__(7604);
+    /******/ var __webpack_exports__ = __webpack_exec__(1678);
     /******/ (_ENTRIES =
       typeof _ENTRIES === "undefined" ? {} : _ENTRIES).middleware_middleware =
       __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>433-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.ru..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-turbo...time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 80b8edd7706c26d8780491ad14b3af2d571164ea

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 80b8edd7706c26d8780491ad14b3af2d571164ea

`pnpm test test/integration/ondemand/test/index.test.js` 
- On Demand Entries > should navigate to pages with dynamic imports

<details>
<summary>Expand output</summary>

  ● On Demand Entries › should navigate to pages with dynamic imports

    TIMED OUT: /Hello/

    /nav/dynamic

    undefined

      626 |
      627 |   if (hardError) {
    > 628 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      629 |   }
      630 |   return false
      631 | }

      at check (lib/next-test-utils.ts:628:11)
      at Object.<anonymous> (integration/ondemand/test/index.test.js:90:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ztanner** [comment]
Hi @agustints, thanks for the PR! Looks like there are some failing tests, do you have time to look into them?

**Comment by agustints** [comment]
Hi @ztanner thank you so much for taking a look here, I appreciate that 🚀 
I'm glad to let you know that I've addressed all the issues and fixed the tests that failed after your merge commit 👌 

Let me know if I can help you in any way, I will be happy to help and contribute 👍

File: packages/next/src/server/lib/router-server.ts [hunk 3]
```diff
@@ -585,13 +585,20 @@ export async function initialize(opts: {
       })
 
       if (opts.dev && developmentBundler && req.url) {
-        const isHMRRequest = req.url.includes('/_next/webpack-hmr')
+        const { basePath } = config
+
+        const isHMRRequestForHostApp =
+          !basePath && req.url.startsWith('/_next/webpack-hmr')
```
Comment (ztanner) [inline packages/next/src/server/lib/router-server.ts:591]: What about a single application that specifies a `basePath`? A request to that application still seems like the "host app" as multi-zone is not the only use-case for the `basePath` property.

**Review by ztanner — COMMENTED** [review]
Thanks @agustints! It still looks like one of the same tests from before is still failing. I've also left some comments around confusion I had with the logic that was introduced.

File: packages/next/src/server/lib/router-server.ts (hunk 3 above)
Comment (agustints) [reply packages/next/src/server/lib/router-server.ts]: @ztanner I decided to improve verbiage here to make it clear, so now I updated it from `isHMRRequestForHostApp` to `isHMRRequestWithoutBasePath` and `isHMRRequestForGuestApp` to `isHMRRequestWithBasePath`.
Now a single application that have basePath will be handled by `isHMRRequestWithBasePath` condition 🚀

File: packages/next/src/server/lib/router-server.ts [hunk 4]
```diff
@@ -585,13 +585,20 @@ export async function initialize(opts: {
...
+
+        const isHMRRequestForGuestApp =
+          basePath && pathHasPrefix(req.url, basePath)
```
[the remark this answers is not in the document]
Comment (agustints) [reply packages/next/src/server/lib/router-server.ts]: You are correct @ztanner, the new implementation now accurately identifies HMR requests based on specific criteria, including the presence of 'webpack-hmr' in the URL for both scenarios. This ensures that only relevant requests are treated as HMR requests. 🚀 
Also I added support to [assetPrefix](https://nextjs.org/docs/pages/api-reference/next-config-js/assetPrefix) HMR request for non basePath scenario (for the other scenario is already being handled by pathHasPrefix function) since that was the cause of the failing test (as far I read in docs & code assetPrefix rewrites assets urls for CMS use-cases so now it's handled there too)!
Thank you for bringing this to my attention, and I hope the updated logic aligns with the intended functionality 👌

**Comment by agustints** [comment]
Hi @ztanner thanks for your comments, I appreciate that, I updated the branch & logic and now seems that tests are working again 🚀

Screenshot 2024-01-07 at 16 42 16

File: packages/next/src/server/lib/router-server.ts [hunk 5]
```diff
@@ -585,13 +585,24 @@ export async function initialize(opts: {
...
+        const isHMRRequestForCurrentBasepath =
+          isHMRRequestWithBasePath || isHMRRequestWithoutBasePath
+
         // only handle HMR requests if the basePath in the request
         // matches the basePath for the handler responding to the request
-        const isRequestForCurrentBasepath =
-          !config.basePath || pathHasPrefix(req.url, config.basePath)
-
-        if (isHMRRequest && isRequestForCurrentBasepath) {
+        if (isHMRRequestForCurrentBasepath) {
```
Comment (ztanner) [inline packages/next/src/server/lib/router-server.ts:605]: I wonder if all these conditions could be simplified to:

```ts
import { ensureLeadingSlash } from '../../shared/lib/page-path/ensure-leading-slash'

// ....

const { basePath, assetPrefix } = config;

const isHMRRequest = req.url.startsWith(
  ensureLeadingSlash(`${basePath || assetPrefix || ""}/_next/webpack-hmr`),
);

if (isHMRRequest) {
  return developmentBundler.hotReloader.onHMR(req, socket, head);
}

```

What do you think?

Comment (agustints) [reply packages/next/src/server/lib/router-server.ts]: Hi @ztanner, that's brilliant, thanks for sharing this utility! 
I changed the logic there in `router-server.ts`, also I removed the "" from the `or` condition since it's not needed there 👌 (if we don't have basePath defined Next.js defaults it to an empty string so it's covered) 🚀

After changing it I manually tested it locally and it's working as expected, also tests are passing ✅  
Screenshot 2024-01-08 at 17 28 41

**Review by ztanner — APPROVED** [review]
Thank you!
