### PR TITLE
Turbopack: properly set NODE_ENV for SWC plugins

### LINKED ISSUE #92547: Turbopack passes "development" to SWC plugins during next build
### Link to the code that reproduces this issue

https://github.com/jantimon/repro-turbopack-swc-plugin-environment

### To Reproduce

1. Clone the repo (contains a minimal SWC plugin that reads TransformPluginMetadataContextKind::Env and replaces ENV_CHECK with the value)
2. Build the SWC plugin: cd swc-plugin-env-check && cargo build --target wasm32-wasip1 --release && cd ..
3. npm install
4. Run next build (uses turbopack by default in Next 16)
5. Check the output: grep -o 'strong>[^<]*</strong' .next/server/app/index.html
6. You'll see development instead of production
7. Compare with next build --webpack which correctly outputs production

### Current vs. Expected behavior

Current: next build --turbopack passes "development" as the env to SWC plugins via TransformPluginMetadataContextKind::Env, regardless of whether it's a dev or prod build.

Expected: next build --turbopack should pass "production", same as webpack does.

| Mode | Bundler | Env received | Correct? |
|------|---------|----------------|----------|
| Dev | Turbopack | "development" | Yes |
| Dev | Webpack | "development" | Yes |
| Prod | Webpack | "production" | Yes |
| Prod | Turbopack | *"development"** | No |

The root cause looks like a hardcoded "development" in turbopack:

https://github.com/vercel/next.js/blob/b5da7b7f7d20802dd5f786c546c47a874612af13/turbopack/crates/turbopack-ecmascript-plugins/src/transform/swc_ecma_transform_plugins.rs#L240-L241

```rust
//[TODO]: Support env-related variable injection, i.e process.env.NODE_ENV
"development".to_string(),
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 25.3.0

Binaries:
  Node: 24.13.0
  npm: 11.6.2
  Yarn: 1.22.22
  pnpm: 10.17.1

Relevant Packages:
  next: 16.2.1-canary.28
  eslint-config-next: N/A
  react: 19.2.5
  react-dom: 19.2.5
  typescript: 6.0.2

Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack, SWC

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

Tested on both 16.2.3 (stable) and 16.2.1-canary.28 (latest canary) — same behavior.

We hit this migrating [galaxus.ch](https://galaxus.ch) to turbopack. Our [translation SWC plugin](https://github.com/DigitecGalaxus/swc-plugin-translation-importer) uses the env to split imports per-key in prod vs bundling all translations in dev. With turbopack always reporting dev, prod builds ship the full dictionary +1.4 MB JS transferred.

### PR DESCRIPTION
**Pull request by mischnic**
### What?

Closes https://github.com/vercel/next.js/pull/92650
Closes https://github.com/vercel/next.js/issues/92547

When Turbopack runs SWC transform plugins, it passes a `TransformPluginMetadataContext` that includes the current `NODE_ENV`. Previously this value was hardcoded to `"development"` regardless of the actual build mode, causing SWC plugins to misbehave during production builds.

### Why?

`SwcPluginMetadataContext` is used by SWC plugins (e.g. `babel-plugin-styled-components`, `@swc/plugin-emotion`) to conditionally produce development vs. production output — for instance, injecting display names and data attributes only in development. With `NODE_ENV` always set to `"development"`, plugins could never produce their optimised production output, resulting in larger bundles and missing minification in `next build`.

Fixes https://github.com/vercel/next.js/issues/92547

### How?

`NODE_ENV` is now derived from the `process.env.NODE_ENV` compile-time define that is already part of `CompileTimeInfo` (the same source of truth used for dead-code elimination). The resolution happens in `EcmascriptModuleAsset::parse()` via a new shared helper `node_env_from_compile_time_info()` in `parse.rs`, and the value is stored on `TransformContext` so every `CustomTransformer` implementation can read it from `ctx.node_env` without needing access to the broader compilation context.

Key design decisions:

- **`TransformContext`** is the right place: it is the per-file context passed to every `CustomTransformer::transform()` call, so storing `node_env` there follows the existing pattern and avoids coupling the plugin struct to the build mode.
- **Webpack analysis path**: `compile_time_info` is now threaded through `webpack_runtime()`, `module_references()`, and the webpack reference structs (`WebpackModuleAsset`, `WebpackChunkAssetReference`, `WebpackEntryAssetReference`, `WebpackRuntimeAssetReference`) so that webpack-bundled files with SWC plugin transforms also receive the correct `NODE_ENV`.
- **`segment_config.rs`**: passes a placeholder but includes a comment explaining it is irrelevant since `EcmascriptInputTransforms::empty()` means no transforms run.

### CODE REVIEW

File: turbopack/crates/turbopack-ecmascript/src/webpack/parse.rs [hunk 1]
```diff
@@ -189,11 +189,14 @@ fn get_require_prefix(stmts: &Vec<Stmt>) -> Option<Lit> {
 pub async fn webpack_runtime(
     source: Vc<Box<dyn Source>>,
     transforms: Vc<EcmascriptInputTransforms>,
+    compile_time_info: Vc<CompileTimeInfo>,
 ) -> Result<Vc<WebpackRuntime>> {
+    let node_env = crate::parse::node_env_from_compile_time_info(compile_time_info).await?;
```
Comment (bgw) [inline turbopack/crates/turbopack-ecmascript/src/webpack/parse.rs]: Import this?

**Review by bgw — APPROVED** [review]

**Comment by mischnic** [comment]
* **#92579** <a href="https://app.graphite.com/github/pr/vercel/next.js/92579?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/vercel/next.js/92579?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#92770** <a href="https://app.graphite.com/github/pr/vercel/next.js/92770?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
