### PR TITLE
Avoid unnecessary router state changes

### LINKED ISSUE #37139: Unnecessary top-level render from the router
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 12.1.7-canary.11
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

If you have `rewrites` in next config:

```js
module.exports = {
  async rewrites() {
    // ...
```

Then Next.js will cause a top-level re-render right after the initial navigation:

https://github.com/vercel/next.js/blob/e57e2753f12076a99173a80787e6d1a2cdb3a0fc/packages/next/client/index.tsx#L118-L121

This has negative performance implications (if you don't have a bunch of memos, it may render the entire app twice 🙃 ), and can lead to cascading updates in userland effects which in turn may cause Suspense boundaries to get dehydrated (https://github.com/vercel/next.js/pull/33861#issuecomment-1135071203).

### Expected Behavior

I would not expect Next.js to call `replaceState` on every single initial navigation for every page if I have defined `rewrites` in my config. (I only used `rewrites` for the RSS feed.) It is not obvious that just having `rewrites` in the config degrades the perf of every page in the application. In either case, even if `replaceState` is called, I would not expect the router component to propagate a context update if nothing in the route context actually changed (the path is the same, etc). 

### To Reproduce

Here's the branch:

https://github.com/gaearon/sc-bug-repro/tree/render-twice

`yarn`, `yarn build`, `yarn start`.

Notice that **in production** the effect runs twice. However, it should run once because there is no reason for the second render in production. If you remove `rewrites` from the config, it will run once as expected.

### PR DESCRIPTION
**Pull request by shuding**
We don’t need to do a re-render if the router state doesn’t change at all. Currently it’s always triggered in certain cases such as when the `rewrites` option is set. Fixes #37139.

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm lint`
- [ ] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

### CODE REVIEW

File: packages/next/shared/lib/router/router.ts [hunk 1]
```diff
@@ -110,6 +110,29 @@ function buildCancellationError() {
...
+      }
+    } else if (
+      a[key as keyof Router['state']] !== b[key as keyof Router['state']]
+    ) {
+      return false
+    }
+  }
+
+  return true
+}
```
Comment (SukkaW) [inline packages/next/shared/lib/router/router.ts:134]:
```suggestion
function compareRouterStates(a: Router['state'], b: Router['state']) {
  const aKeys = Object.keys(a);
  const aKeysLen = aKeys.length;
  if (aKeysLen !== Object.keys(b).length) return false

  // It is most likely that shapes of parsed queries are different
  const aQueryKeys = Object.keys(a.query);
  const aQueryKeysLen = aKeys.length;
  if (aQueryKeysLen !== Object.keys(b.query).length) return false
  for (let j = aQueryKeysLen; j-- !== 0;) {
    if (!Object.prototype.hasOwnProperty.call(b.query, aQueryKeys[j])) return false
  }
  // Only compare the value when shapes are the same
  for (let j = aQueryKeysLen; j-- !== 0;) {
    const queryKey = aQueryKeys[j]
    if (a.query[queryKey] !== b.query[queryKey]) return false;
  }

  for (let i = aKeysLen; i-- !== 0;) {  
    const key = aKeys[i];
    if (key === 'query') continue;

    // It is less likely that shapes of router states are different
    // So compare the shape and the value together
    if (
      !Object.prototype.hasOwnProperty.call(b, key)
      || a[key as keyof Router['state']] !== b[key as keyof Router['state']]
    ) {
      return false;
    }
  }

  return true
}
```

A more performant version of `compareRouterStates`.

Comment (shuding) [reply packages/next/shared/lib/router/router.ts:134]: Thanks! Would you mind explaining why is it more performant? Because it checks `query` before other properties?

Comment (SukkaW) [reply packages/next/shared/lib/router/router.ts:134]: > Thanks! Would you mind explaining why is it more performant? Because it checks `query` before other properties?

It contains serveral optimizations:

- Use `for .. in` on an object will iterate over object's prototype. Use `for .. in` on `Object.keys` fixes that.
- `Route['state'].query` comes from `querystring.parse` where the shape is likely to change. The code checks the shape of the object before checking the value.
- The shape of `Route['state']` is not likely to change, so it is not necessary to check the shape before value.
- The implementation caches the result of `Object.keys` (and its length)

Comment (shuding) [reply packages/next/shared/lib/router/router.ts:134]: Thanks for the reply! Could be wrong but here's what I think:
- I think the state is created as literal object, hence I didn't add the `hasOwnProperty` check;
- "The code checks the shape of the object before checking the value. " — Makes sense, I think those two loops from your code can be merged too?
- Regarding state and query, I'm not sure which one is more likely to change. In many cases that a route state change is caused by pushing a new route, where the `.route` value updates;
- "The implementation also caches / re-use the result of Object.keys" — I don't think this is a problem in the code from this PR?

Comment (SukkaW) [reply packages/next/shared/lib/router/router.ts:134]: > * I think the state is created as a literal object, hence I didn't add the `hasOwnProperty` check;

Since `Object.keys` is being used already, IMHO it make sense to re-use it (and also prevent potential prototype literation)

> * "The code checks the shape of the object before checking the value. " — Makes sense, I think those two loops from your code can be merged too?

I haven't run a benchmark yet, but yes.

> * Regarding state and query, I'm not sure which one is more likely to change. In many cases that a route state change is caused by pushing a new route, where the `.route` value updates;

My original idea was that we are not re-creating a fast-shallow-equal library, the `compareRouterStates` function should be optimized specifically for route state.

> * "The implementation also caches / re-use the result of Object.keys" — I don't think this is a problem in the code from this PR?

It is just a micro-optimization in my code.

Comment (shuding) [reply packages/next/shared/lib/router/router.ts:134]: Let me polish it a bit, thanks! :)

Comment (shuding) [reply packages/next/shared/lib/router/router.ts]: One thing to point out here though, if two projects have the same number of own properties (`Object.keys(a).length === Object.keys(b).length`), and all values from one object are equal to the value from the other, these two objects are equal. We don't need to check their shapes.

Comment (SukkaW) [reply packages/next/shared/lib/router/router.ts]: > One thing to point out here though, if two projects have the same number of own properties (`Object.keys(a).length === Object.keys(b).length`), and all values from one object are equal to the value from the other, these two objects are equal. We don't need to check their shapes.

Make sense. But since both `fast-equals`, `fast-deep-equals` and `fast-shallow-equals` run `Object.prototype.hasOwnproperty` before comparing the value, I guess there is a reason of they doing it.

We could skip the shape check for the entire router state (its shape is not likely to change) though.

Comment (shuding) [reply packages/next/shared/lib/router/router.ts]: Yeah, the exception will be something like this:

```js
const a = { foo: 1 }
const b = Object.create({ foo: 1 })
b.bar = 1
```

Although it should not happen in our specific context, but totally understand your concern here. Since router state  comparison isn’t a heavy operation, I’ll apply the hasOwnProperty check here.

Thanks again!

**Review by huozhi — APPROVED** [review]
