### PR TITLE
fix(next/image): washed out blur placeholder

### LINKED ISSUE #52548: <Image /> placeholder image appears "washed out" due to feathered edges
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020
    Binaries:
      Node: 19.7.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.4.10-canary.3
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/competent-agnesi-sw4tsq?file=%2Fpages%2Findex.tsx%3A30%2C9

### To Reproduce

- Open DevTools network tab,
- Check the "disable cache" checkbox,
- Set network throttling to "Slow 3G",
- Click "Refresh" button in Codesandbox and wait for placeholder images to show up

### Describe the Bug

When placeholder image file type is different than JPEG, placeholder images have feathered / washed out edges around them:

Screenshot 2023-07-11 at 14 30 45

### Expected Behavior

Placeholder images should keep hard/solid edges around them no matter what type of file extensions is used for the placeholder image (JPEG, JPG, GIF, WEBP).

Here's a comparison between how it is now, and how it could be when fixed. Having hard edges around the image makes UI look crispier.

Feathered edges (current state):
Screenshot 2023-07-11 at 14 36 36

Hard edges (expected):
Screenshot 2023-07-11 at 14 36 47

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by arturbien**
Fixes #52548

See this tweet thread for more info: https://twitter.com/artur_bien/status/1688626080016437249

This PR fixes the issue of the `<Image />` "blur" placeholder where the placeholder image appears "washed out" and feathered around the edges.

The fix does NOT involve any API changes - only the underlying SVG filter is updated.
The filter works for any image type (JPEG, GIF, WEBP) no matter if it contains transparency or not.

## How it works

```html
  <filter id='b' color-interpolation-filters='sRGB'>
    <feMorphology in='SourceAlpha' operator='dilate' radius='15' result='dilate' />
    <feGaussianBlur in='dilate' stdDeviation='15' result='mask' />
    <feGaussianBlur in='SourceGraphic' stdDeviation='20' result='blur' />
    <feComponentTransfer in='blur' result='solid'>
      <feFuncA type='table' tableValues='1 1' />
    </feComponentTransfer>
    <feComposite in2='mask' in='solid' operator='in' result="comp" />
    <feMerge>
      <feMergeNode in="SourceGraphic" />
      <feMergeNode in="comp" />
    </feMerge>
  </filter>
  ```
Currently the underlying filter uses `feComponentTransfer ` to get rid of the feathered edges but only for JPEG images. This is because if alpha channel was to be mapped to 1 for images with transparency in it, all of the transparent pixels would turn black (which is obviously undesirable).

The way I fixed it is by creating a mask from the SourceAlpha (effectively the "shape" of the object in an image), slightly blurring it for a smoother look (feMorphology + feGaussianBlur), and then clipping the `feComponentTransfer` result to the shape of the mask (`<feComposite in2='mask' in='solid' operator='in' result="comp" />`). 

Then finally `feMerge` is used to stack original image and the clipping result from the previous step just to make sure that any left over artifacts from clipping are hidden.

## Result

Here's a comparison between the current implementation (left column), and the filter above (right column)

Screenshot 2023-07-12 at 10 44 56

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: bd03f45594d4a81dfd923273aa86dd8caaffba57

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 897e15cd3586b55683944c58c42938d405733a93

`pnpm testheadless test/integration/next-image-new/default/test/static.test.ts` 
- Static Image Component Tests > dev mode > should add placeholder even when blurDataURL aspect ratio does not match width/height ratio
- Static Image Component Tests > production mode > should add a blur placeholder a statically imported jpg
- Static Image Component Tests > production mode > should add a blur placeholder a statically imported png
- Static Image Component Tests > production mode > should add a blur placeholder a statically imported png with fill
- Static Image Component Tests > production mode > should add placeholder even when blurDataURL aspect ratio does not match width/height ratio

<details>
<summary>Expand output</summary>

  ● Static Image Component Tests › production mode › should add a blur placeholder a statically imported jpg

    expect(received).toBe(expected) // Object.is equality

    Expected: "color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 8 6'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='1'/%3E%3CfeComponentTransfer%3E%3CfeFuncA type='discrete' tableValues='1 1'/%3E%3C/feComponentTransfer%3E%%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/sBCgoKCgoKCwwMCw8QDhAPFhQTExQWIhgaGBoYIjMgJSAgJSAzLTcsKSw3LVFAODhAUV5PSk9ecWVlcY+Ij7u7+//CABEIAAYACAMBIgACEQEDEQH/xAAnAAEBAAAAAAAAAAAAAAAAAAAABwEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEAMQAAAAmgP/xAAcEAACAQUBAAAAAAAAAAAAAAASFBMAAQMFERX/2gAIAQEAAT8AZ1HjrKZX55JysIc4Ff/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQIBAT8Af//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQMBAT8Af//Z'/%3E%3C/svg%3E\")"
    Received: "color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3csvg viewBox='0 0 8 6' xmlns='http://www.w3.org/2000/svg' width='8' height='6'%3e%3cfilter id='b' color-interpolation-filters='sRGB'%3e%3cfeMorphology in='SourceAlpha' operator='dilate' radius='15' result='dilate'%3e%3c/feMorphology%3e%3cfeGaussianBlur in='dilate' stdDeviation='15' result='mask'%3e%3c/feGaussianBlur%3e%3cfeGaussianBlur in='SourceGraphic' stdDeviation='1' result='blur'%3e%3c/feGaussianBlur%3e%3cfeComponentTransfer in='blur' result='solid'%3e%3cfeFuncA type='table' tableValues='1 1'%3e%3c/feFuncA%3e%3c/feComponentTransfer%3e%3cfeComposite in2='mask' in='solid' operator='in' result='comp'%3e%3c/feComposite%3e%3cfeMerge%3e%3cfeMergeNode in='SourceGraphic'/%3e%3cfeMergeNode in='comp'/%3e%3c/feMerge%3e%3c/filter%3e%3cimage style='filter: url(%23b);' x='0' y='0' width='100%25' height='100%25' preserveAspectRatio='none' href='data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/sBCgoKCgoKCwwMCw8QDhAPFhQTExQWIhgaGBoYIjMgJSAgJSAzLTcsKSw3LVFAODhAUV5PSk9ecWVlcY+Ij7u7+//CABEIAAYACAMBIgACEQEDEQH/xAAnAAEBAAAAAAAAAAAAAAAAAAAABwEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEAMQAAAAmgP/xAAcEAACAQUBAAAAAAAAAAAAAAASFBMAAQMFERX/2gAIAQEAAT8AZ1HjrKZX55JysIc4Ff/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQIBAT8Af//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQMBAT8Af//Z'%3e%3c/image%3e%3c/svg%3e\")"

       98 |       )
       99 |     } else {
    > 100 |       expect(style).toBe(
          |                     ^
      101 |         `color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 8 6'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='1'/%3E%3CfeComponentTransfer%3E%3CfeFuncA type='discrete' tableValues='1 1'/%3E%3C/feComponentTransfer%3E%%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/sBCgoKCgoKCwwMCw8QDhAPFhQTExQWIhgaGBoYIjMgJSAgJSAzLTcsKSw3LVFAODhAUV5PSk9ecWVlcY+Ij7u7+//CABEIAAYACAMBIgACEQEDEQH/xAAnAAEBAAAAAAAAAAAAAAAAAAAABwEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEAMQAAAAmgP/xAAcEAACAQUBAAAAAAAAAAAAAAASFBMAAQMFERX/2gAIAQEAAT8AZ1HjrKZX55JysIc4Ff/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQIBAT8Af//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQMBAT8Af//Z'/%3E%3C/svg%3E")`
      102 |       )
      103 |     }

      at Object.<anonymous> (integration/next-image-new/default/test/static.test.ts:100:21)

  ● Static Image Component Tests › production mode › should add a blur placeholder a statically imported png

    expect(received).toBe(expected) // Object.is equality

    Expected: "color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='1'/%3E%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAAAAADhZOFXAAAAOklEQVR42iWGsQkAIBDE0iuIdiLOJjiGIzjiL/Meb4okiNYIlLjK3hJMzCQG1/0qmXXOUkjAV+m9wAMe3QiV6Ne8VgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E\")"
    Received: "color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3csvg viewBox='0 0 8 8' xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3e%3cfilter id='b' color-interpolation-filters='sRGB'%3e%3cfeMorphology in='SourceAlpha' operator='dilate' radius='15' result='dilate'%3e%3c/feMorphology%3e%3cfeGaussianBlur in='dilate' stdDeviation='15' result='mask'%3e%3c/feGaussianBlur%3e%3cfeGaussianBlur in='SourceGraphic' stdDeviation='1' result='blur'%3e%3c/feGaussianBlur%3e%3cfeComponentTransfer in='blur' result='solid'%3e%3cfeFuncA type='table' tableValues='1 1'%3e%3c/feFuncA%3e%3c/feComponentTransfer%3e%3cfeComposite in2='mask' in='solid' operator='in' result='comp'%3e%3c/feComposite%3e%3cfeMerge%3e%3cfeMergeNode in='SourceGraphic'/%3e%3cfeMergeNode in='comp'/%3e%3c/feMerge%3e%3c/filter%3e%3cimage style='filter: url(%23b);' x='0' y='0' width='100%25' height='100%25' preserveAspectRatio='none' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAAAAADhZOFXAAAAOklEQVR42iWGsQkAIBDE0iuIdiLOJjiGIzjiL/Meb4okiNYIlLjK3hJMzCQG1/0qmXXOUkjAV+m9wAMe3QiV6Ne8VgAAAABJRU5ErkJggg=='%3e%3c/image%3e%3c/svg%3e\")"

      111 |       )
      112 |     } else {
    > 113 |       expect(style).toBe(
          |                     ^
      114 |         `color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='1'/%3E%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAAAAADhZOFXAAAAOklEQVR42iWGsQkAIBDE0iuIdiLOJjiGIzjiL/Meb4okiNYIlLjK3hJMzCQG1/0qmXXOUkjAV+m9wAMe3QiV6Ne8VgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E")`
      115 |       )
      116 |     }

      at Object.<anonymous> (integration/next-image-new/default/test/static.test.ts:113:21)

  ● Static Image Component Tests › production mode › should add a blur placeholder a statically imported png with fill

    expect(received).toBe(expected) // Object.is equality

    Expected: "position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='1'/%3E%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAAAAADhZOFXAAAAOklEQVR42iWGsQkAIBDE0iuIdiLOJjiGIzjiL/Meb4okiNYIlLjK3hJMzCQG1/0qmXXOUkjAV+m9wAMe3QiV6Ne8VgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E\")"
    Received: "position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3csvg viewBox='0 0 8 8' xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3e%3cfilter id='b' color-interpolation-filters='sRGB'%3e%3cfeMorphology in='SourceAlpha' operator='dilate' radius='15' result='dilate'%3e%3c/feMorphology%3e%3cfeGaussianBlur in='dilate' stdDeviation='15' result='mask'%3e%3c/feGaussianBlur%3e%3cfeGaussianBlur in='SourceGraphic' stdDeviation='1' result='blur'%3e%3c/feGaussianBlur%3e%3cfeComponentTransfer in='blur' result='solid'%3e%3cfeFuncA type='table' tableValues='1 1'%3e%3c/feFuncA%3e%3c/feComponentTransfer%3e%3cfeComposite in2='mask' in='solid' operator='in' result='comp'%3e%3c/feComposite%3e%3cfeMerge%3e%3cfeMergeNode in='SourceGraphic'/%3e%3cfeMergeNode in='comp'/%3e%3c/feMerge%3e%3c/filter%3e%3cimage style='filter: url(%23b);' x='0' y='0' width='100%25' height='100%25' preserveAspectRatio='none' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAAAAADhZOFXAAAAOklEQVR42iWGsQkAIBDE0iuIdiLOJjiGIzjiL/Meb4okiNYIlLjK3hJMzCQG1/0qmXXOUkjAV+m9wAMe3QiV6Ne8VgAAAABJRU5ErkJggg=='%3e%3c/image%3e%3c/svg%3e\")"

      124 |       )
      125 |     } else {
    > 126 |       expect(style).toBe(
          |                     ^
      127 |         `position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='1'/%3E%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAAAAADhZOFXAAAAOklEQVR42iWGsQkAIBDE0iuIdiLOJjiGIzjiL/Meb4okiNYIlLjK3hJMzCQG1/0qmXXOUkjAV+m9wAMe3QiV6Ne8VgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E")`
      128 |       )
      129 |     }

      at Object.<anonymous> (integration/next-image-new/default/test/static.test.ts:126:21)

  ● Static Image Component Tests › production mode › should add placeholder even when blurDataURL aspect ratio does not match width/height ratio

    expect(received).toBe(expected) // Object.is equality

    Expected: "color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 100 200'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='20'/%3E%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNM/s/wBwAFjwJgf8HDLgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E\")"
    Received: "color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3csvg viewBox='0 0 100 200' xmlns='http://www.w3.org/2000/svg' width='100' height='200'%3e%3cfilter id='b' color-interpolation-filters='sRGB'%3e%3cfeMorphology in='SourceAlpha' operator='dilate' radius='15' result='dilate'%3e%3c/feMorphology%3e%3cfeGaussianBlur in='dilate' stdDeviation='15' result='mask'%3e%3c/feGaussianBlur%3e%3cfeGaussianBlur in='SourceGraphic' stdDeviation='20' result='blur'%3e%3c/feGaussianBlur%3e%3cfeComponentTransfer in='blur' result='solid'%3e%3cfeFuncA type='table' tableValues='1 1'%3e%3c/feFuncA%3e%3c/feComponentTransfer%3e%3cfeComposite in2='mask' in='solid' operator='in' result='comp'%3e%3c/feComposite%3e%3cfeMerge%3e%3cfeMergeNode in='SourceGraphic'/%3e%3cfeMergeNode in='comp'/%3e%3c/feMerge%3e%3c/filter%3e%3cimage style='filter: url(%23b);' x='0' y='0' width='100%25' height='100%25' preserveAspectRatio='none' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNM/s/wBwAFjwJgf8HDLgAAAABJRU5ErkJggg=='%3e%3c/image%3e%3c/svg%3e\")"

      139 |   it('should add placeholder even when blurDataURL aspect ratio does not match width/height ratio', async () => {
      140 |     const style = $('#blurdataurl-ratio').attr('style')
    > 141 |     expect(style).toBe(
          |                   ^
      142 |       `color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 100 200'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='20'/%3E%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNM/s/wBwAFjwJgf8HDLgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E")`
      143 |     )
      144 |   })

      at Object.<anonymous> (integration/next-image-new/default/test/static.test.ts:141:19)

  ● Static Image Component Tests › dev mode › should add placeholder even when blurDataURL aspect ratio does not match width/height ratio

    expect(received).toBe(expected) // Object.is equality

    Expected: "color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 100 200'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='20'/%3E%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNM/s/wBwAFjwJgf8HDLgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E\")"
    Received: "color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(\"data:image/svg+xml;charset=utf-8,%3csvg viewBox='0 0 100 200' xmlns='http://www.w3.org/2000/svg' width='100' height='200'%3e%3cfilter id='b' color-interpolation-filters='sRGB'%3e%3cfeMorphology in='SourceAlpha' operator='dilate' radius='15' result='dilate'%3e%3c/feMorphology%3e%3cfeGaussianBlur in='dilate' stdDeviation='15' result='mask'%3e%3c/feGaussianBlur%3e%3cfeGaussianBlur in='SourceGraphic' stdDeviation='20' result='blur'%3e%3c/feGaussianBlur%3e%3cfeComponentTransfer in='blur' result='solid'%3e%3cfeFuncA type='table' tableValues='1 1'%3e%3c/feFuncA%3e%3c/feComponentTransfer%3e%3cfeComposite in2='mask' in='solid' operator='in' result='comp'%3e%3c/feComposite%3e%3cfeMerge%3e%3cfeMergeNode in='SourceGraphic'/%3e%3cfeMergeNode in='comp'/%3e%3c/feMerge%3e%3c/filter%3e%3cimage style='filter: url(%23b);' x='0' y='0' width='100%25' height='100%25' preserveAspectRatio='none' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNM/s/wBwAFjwJgf8HDLgAAAABJRU5ErkJggg=='%3e%3c/image%3e%3c/svg%3e\")"

      139 |   it('should add placeholder even when blurDataURL aspect ratio does not match width/height ratio', async () => {
      140 |     const style = $('#blurdataurl-ratio').attr('style')
    > 141 |     expect(style).toBe(
          |                   ^
      142 |       `color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 100 200'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='20'/%3E%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNM/s/wBwAFjwJgf8HDLgAAAABJRU5ErkJggg=='/%3E%3C/svg%3E")`
      143 |     )
      144 |   })

      at Object.<anonymous> (integration/next-image-new/default/test/static.test.ts:141:19)
          at runMicrotasks (<anonymous>)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by styfle** [comment]
Thanks! Please update the [failing tests](https://github.com/vercel/next.js/pull/52583#issuecomment-1632773640)

File: packages/next/src/shared/lib/image-blur-svg.ts [hunk 1]
```diff
@@ -16,14 +16,13 @@ export function getImageBlurSvg({
...
+    const std = blurWidth && blurHeight ? 1 : 20
+    const smoothenMask = 15
+    return `%3csvg viewBox='0 0 ${svgWidth} ${svgHeight}' xmlns='http://www.w3.org/2000/svg' width='${svgWidth}' height='${svgHeight}'%3e%3cfilter id='b' color-interpolation-filters='sRGB'%3e%3cfeMorphology in='SourceAlpha' operator='dilate' radius='${smoothenMask}' result='dilate'%3e%3c/feMorphology%3e%3cfeGaussianBlur in='dilate' stdDeviation='${smoothenMask}' result='mask'%3e%3c/feGaussianBlur%3e%3cfeGaussianBlur in='SourceGraphic' stdDeviation='${std}' result='blur'%3e%3c/feGaussianBlur%3e%3cfeComponentTransfer in='blur' result='solid'%3e%3cfeFuncA type='table' tableValues='1 1'%3e%3c/feFuncA%3e%3c/feComponentTransfer%3e%3cfeComposite in2='mask' in='solid' operator='in' result='comp'%3e%3c/feComposite%3e%3cfeMerge%3e%3cfeMergeNode in='SourceGraphic'/%3e%3cfeMergeNode in='comp'/%3e%3c/feMerge%3e%3c/filter%3e%3cimage style='filter: url(%23b);' x='0' y='0' width='100%25' height='100%25' preserveAspectRatio='none' href='${blurDataURL}'%3e%3c/image%3e%3c/svg%3e`
```
Comment (styfle) [inline packages/next/src/shared/lib/image-blur-svg.ts:25]:
```suggestion
    return `%3csvg viewBox='0 0 ${svgWidth} ${svgHeight}' xmlns='http%3A//www.w3.org/2000/svg' width='${svgWidth}' height='${svgHeight}'%3e%3cfilter id='b' color-interpolation-filters='sRGB'%3e%3cfeMorphology in='SourceAlpha' operator='dilate' radius='${smoothenMask}' result='dilate'%3e%3c/feMorphology%3e%3cfeGaussianBlur in='dilate' stdDeviation='${smoothenMask}' result='mask'%3e%3c/feGaussianBlur%3e%3cfeGaussianBlur in='SourceGraphic' stdDeviation='${std}' result='blur'%3e%3c/feGaussianBlur%3e%3cfeComponentTransfer in='blur' result='solid'%3e%3cfeFuncA type='table' tableValues='1 1'%3e%3c/feFuncA%3e%3c/feComponentTransfer%3e%3cfeComposite in2='mask' in='solid' operator='in' result='comp'%3e%3c/feComposite%3e%3cfeMerge%3e%3cfeMergeNode in='SourceGraphic'/%3e%3cfeMergeNode in='comp'/%3e%3c/feMerge%3e%3c/filter%3e%3cimage style='filter: url(%23b);' x='0' y='0' width='100%25' height='100%25' preserveAspectRatio='none' href='${blurDataURL}'%3e%3c/image%3e%3c/svg%3e`
```

I believe the colon needs to be escaped

File: packages/next/src/shared/lib/image-blur-svg.ts [hunk 2]
```diff
@@ -16,14 +16,13 @@ export function getImageBlurSvg({
...
 }): string {
-  const std = blurWidth && blurHeight ? '1' : '20'
   const svgWidth = blurWidth || widthInt
   const svgHeight = blurHeight || heightInt
-  const feComponentTransfer = blurDataURL.startsWith('data:image/jpeg')
-    ? `%3CfeComponentTransfer%3E%3CfeFuncA type='discrete' tableValues='1 1'/%3E%3C/feComponentTransfer%3E%`
-    : ''
+
   if (svgWidth && svgHeight) {
-    return `%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 ${svgWidth} ${svgHeight}'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='${std}'/%3E${feComponentTransfer}%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='${blurDataURL}'/%3E%3C/svg%3E`
```
Comment (styfle) [inline packages/next/src/shared/lib/image-blur-svg.ts:26]: Looks like the order of `viewBox` and `xmlns` was swapped. Can you swap it back so the diff is a little easier to read?

**Review by styfle — COMMENTED** [review]
A couple suggestions

File: packages/next/src/shared/lib/image-blur-svg.ts (hunk 1 above)
Comment (arturbien) [reply packages/next/src/shared/lib/image-blur-svg.ts]: So I've tested multiple SVG to dara uri converters and looked up some threads on it and it looks like the colon does not have to be escaped:

https://css-tricks.com/probably-dont-base64-svg/
https://codepen.io/tigt/post/optimizing-svgs-in-data-uris
https://codepen.io/elliz/pen/ygvgay

The `encodeURI` function also keeps the colon.

If I am missing something I'll of course change that part!

**Comment by arturbien** [comment]
@styfle hard for me to decypher the failing CI message. Seems like some workflows have to be first enabled by some maintainer? When I've updated the tests and ran them locally they completed 🤔

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | arturbien/next.js fix/image-blur-placeholder | Change |
| - | - | - | - |
| buildDuration | 59.6s | 58.4s | -1.2s |
| buildDurationCached | 20.4s | 18.4s | -2s |
| nodeModulesSize | 137 MB | 137 MB | ⚠️ +2.68 kB |
| nextStartRea..uration (ms) | 580ms | 613ms | ⚠️ +33ms |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | arturbien/next.js fix/image-blur-placeholder | Change |
| - | - | - | - |
| 0d536507-HASH.js gzip | 50.5 kB | 50.5 kB | ✓ |
| 174-HASH.js gzip | 25.2 kB | 25.2 kB | ⚠️ +19 B |
| 511.HASH.js gzip | 180 B | 183 B | ⚠️ +3 B |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 217 B | 214 B | -3 B |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ⚠️ +1 B |
| Overall change | 151 kB | 151 kB | ⚠️ +20 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | arturbien/next.js fix/image-blur-placeholder | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | arturbien/next.js fix/image-blur-placeholder | Change |
| - | - | - | - |
| _app-HASH.js gzip | 195 B | 195 B | ✓ |
| _error-HASH.js gzip | 183 B | 182 B | -1 B |
| amp-HASH.js gzip | 503 B | 504 B | ⚠️ +1 B |
| css-HASH.js gzip | 321 B | 323 B | ⚠️ +2 B |
| dynamic-HASH.js gzip | 1.82 kB | 1.82 kB | -2 B |
| edge-ssr-HASH.js gzip | 255 B | 255 B | ✓ |
| head-HASH.js gzip | 349 B | 351 B | ⚠️ +2 B |
| hooks-HASH.js gzip | 369 B | 368 B | -1 B |
| image-HASH.js gzip | 4.17 kB | 4.33 kB | ⚠️ +153 B |
| index-HASH.js gzip | 255 B | 256 B | ⚠️ +1 B |
| link-HASH.js gzip | 2.63 kB | 2.62 kB | -4 B |
| routerDirect..HASH.js gzip | 312 B | 312 B | ✓ |
| script-HASH.js gzip | 385 B | 384 B | -1 B |
| withRouter-HASH.js gzip | 309 B | 308 B | -1 B |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 12.2 kB | 12.3 kB | ⚠️ +149 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | arturbien/next.js fix/image-blur-placeholder | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 483 B | ✓ |
| Overall change | 483 B | 483 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | arturbien/next.js fix/image-blur-placeholder | Change |
| - | - | - | - |
| index.html gzip | 511 B | 510 B | -1 B |
| link.html gzip | 525 B | 525 B | ✓ |
| withRouter.html gzip | 504 B | 505 B | ⚠️ +1 B |
| Overall change | 1.54 kB | 1.54 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | arturbien/next.js fix/image-blur-placeholder | Change |
| - | - | - | - |
| edge-ssr.js gzip | 89.6 kB | 89.6 kB | ⚠️ +6 B |
| page.js gzip | 146 kB | 146 kB | ⚠️ +15 B |
| Overall change | 236 kB | 236 kB | ⚠️ +21 B |

</details>

<details>
<summary><strong>Middleware size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | arturbien/next.js fix/image-blur-placeholder | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 623 B | -2 B |
| middleware-r..fest.js gzip | 150 B | 152 B | ⚠️ +2 B |
| middleware.js gzip | 16.6 kB | 16.6 kB | ⚠️ +6 B |
| edge-runtime..pack.js gzip | 1.83 kB | 1.83 kB | ✓ |
| Overall change | 19.2 kB | 19.2 kB | ⚠️ +6 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware-b..-manifest.js</strong></summary>

```diff
@@ -7,96 +7,96 @@ self.__BUILD_MANIFEST = {
     "static/BUILD_ID/_ssgManifest.js",
   ],
   rootMainFiles: [
-    "static/chunks/webpack-735eb851a26a56f3.js",
-    "static/chunks/0d536507-730746fee67b2885.js",
-    "static/chunks/174-9cd8fe779236b0b2.js",
-    "static/chunks/main-app-bb6cb362b9e8929d.js",
+    "static/chunks/webpack-3059af3822a3ea04.js",
+    "static/chunks/c9a40420-04236801760bd2a4.js",
+    "static/chunks/365-890f3473616fe9e4.js",
+    "static/chunks/main-app-cc07a8bfa5282e1b.js",
   ],
   pages: {
     "/": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
-      "static/chunks/pages/index-3eeb184a3b01069a.js",
+      "static/chunks/main-11f65725aea796af.js",
+      "static/chunks/pages/index-42327f7ac4cb0b58.js",
     ],
     "/_app": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
-      "static/chunks/pages/_app-ce5ab6de9e19c26b.js",
+      "static/chunks/main-11f65725aea796af.js",
+      "static/chunks/pages/_app-a739417fb3ebd628.js",
     ],
     "/_error": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
-      "static/chunks/pages/_error-1ca214e380344f72.js",
+      "static/chunks/main-11f65725aea796af.js",
+      "static/chunks/pages/_error-a1fe554f661ca2f4.js",
     ],
     "/amp": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
-      "static/chunks/pages/amp-add4644085c74c96.js",
+      "static/chunks/main-11f65725aea796af.js",
+      "static/chunks/pages/amp-30c8a1780ede07c9.js",
     ],
     "/css": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
+      "static/chunks/main-11f65725aea796af.js",
       "static/css/ded6b86ab9cc0a1f.css",
-      "static/chunks/pages/css-5378d3d7af820c29.js",
+      "static/chunks/pages/css-aa735f5e2aa226b3.js",
     ],
     "/dynamic": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
-      "static/chunks/pages/dynamic-42da64dc2c2fce13.js",
+      "static/chunks/main-11f65725aea796af.js",
+      "static/chunks/pages/dynamic-b10d57b71862877f.js",
     ],
     "/edge-ssr": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
-      "static/chunks/pages/edge-ssr-a2fee5412c431f04.js",
+      "static/chunks/main-11f65725aea796af.js",
+      "static/chunks/pages/edge-ssr-8503741982090fd1.js",
     ],
     "/head": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
-      "static/chunks/pages/head-2b297fce1a4227af.js",
+      "static/chunks/main-11f65725aea796af.js",
+      "static/chunks/pages/head-83fa8b512be5ddac.js",
     ],
     "/hooks": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
-      "static/chunks/pages/hooks-fd524b5719dd436b.js",
+      "static/chunks/main-11f65725aea796af.js",
+      "static/chunks/pages/hooks-ccc88816344bfb3b.js",
     ],
     "/image": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
-      "static/chunks/pages/image-886584a4c844df2f.js",
+      "static/chunks/main-11f65725aea796af.js",
+      "static/chunks/pages/image-cc8e9ba47d3439b3.js",
     ],
     "/link": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
-      "static/chunks/pages/link-703b373f2d606656.js",
+      "static/chunks/main-11f65725aea796af.js",
+      "static/chunks/pages/link-ddfe4479277cba32.js",
     ],
     "/routerDirect": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
-      "static/chunks/pages/routerDirect-21c04c160c1f5f7e.js",
+      "static/chunks/main-11f65725aea796af.js",
+      "static/chunks/pages/routerDirect-ec52a13385b3d2cd.js",
     ],
     "/script": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
-      "static/chunks/pages/script-7bebe95abbd437dc.js",
+      "static/chunks/main-11f65725aea796af.js",
+      "static/chunks/pages/script-d4167f0109c5dc8f.js",
     ],
     "/withRouter": [
-      "static/chunks/webpack-735eb851a26a56f3.js",
+      "static/chunks/webpack-3059af3822a3ea04.js",
       "static/chunks/framework-114cbddc60b679b8.js",
-      "static/chunks/main-43bb2c62e5be9926.js",
-      "static/chunks/pages/withRouter-8bb2114b113c11ef.js",
+      "static/chunks/main-11f65725aea796af.js",
+      "static/chunks/pages/withRouter-c8f30e923eada3a5.js",
     ],
   },
   ampFirstPages: [],
```
</details>
<details>
<summary>Diff for <strong>middleware-r..-manifest.js</strong></summary>

```diff
@@ -1,2 +1,2 @@
 self.__REACT_LOADABLE_MANIFEST =
-  '{"dynamic.js -> ../components/hello":{"id":5511,"files":["static/chunks/511.403860df3d0944c6.js"]}}';
+  '{"dynamic.js -> ../components/hello":{"id":3685,"files":["static/chunks/370.bb05f43a23695be1.js"]}}';
```
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

```diff
@@ -2,7 +2,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [826],
   {
-    /***/ 191: /***/ (
+    /***/ 6186: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -22,7 +22,7 @@
       __webpack_require__.r(middleware_namespaceObject);
       __webpack_require__.d(middleware_namespaceObject, {
         default: () => middleware,
-      }); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/globals.js
+      }); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/globals.js
 
       async function registerInstrumentation() {
         if (
@@ -92,7 +92,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         // Eagerly fire instrumentation hook to make the startup faster.
         void ensureInstrumentationRegistered();
       }
-      enhanceGlobals(); //# sourceMappingURL=globals.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/error.js
+      enhanceGlobals(); //# sourceMappingURL=globals.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/error.js
 
       class PageSignatureError extends Error {
         constructor({ page }) {
@@ -119,7 +119,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
   Read more: https://nextjs.org/docs/messages/middleware-parse-user-agent
   `);
         }
-      } //# sourceMappingURL=error.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/utils.js
+      } //# sourceMappingURL=error.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/utils.js
 
       /**
        * Converts a Node.js IncomingHttpHeaders object to a Headers object. Any
@@ -254,7 +254,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
             }
           );
         }
-      } //# sourceMappingURL=utils.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/fetch-event.js
+      } //# sourceMappingURL=utils.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/fetch-event.js
 
       const responseSymbol = Symbol("response");
       const passThroughSymbol = Symbol("passThrough");
@@ -300,7 +300,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
             page: this.sourcePage,
           });
         }
-      } //# sourceMappingURL=fetch-event.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/i18n/detect-domain-locale.js
+      } //# sourceMappingURL=fetch-event.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/i18n/detect-domain-locale.js
 
       function detectDomainLocale(domainItems, hostname, detectedLocale) {
         if (!domainItems) return;
@@ -326,7 +326,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
             return item;
           }
         }
-      } //# sourceMappingURL=detect-domain-locale.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/remove-trailing-slash.js
+      } //# sourceMappingURL=detect-domain-locale.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/remove-trailing-slash.js
 
       /**
        * Removes the trailing slash for a given route or page path. Preserves the
@@ -336,7 +336,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
        *   - `/` -> `/`
        */ function removeTrailingSlash(route) {
         return route.replace(/\/$/, "") || "/";
-      } //# sourceMappingURL=remove-trailing-slash.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/parse-path.js
+      } //# sourceMappingURL=remove-trailing-slash.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/parse-path.js
 
       /**
        * Given a path this function will find the pathname, query and hash and return
@@ -364,7 +364,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           query: "",
           hash: "",
         };
-      } //# sourceMappingURL=parse-path.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/add-path-prefix.js
+      } //# sourceMappingURL=parse-path.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/add-path-prefix.js
 
       /**
        * Adds the provided prefix to the given path. It first ensures that the path
@@ -375,7 +375,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         }
         const { pathname, query, hash } = parsePath(path);
         return "" + prefix + pathname + query + hash;
-      } //# sourceMappingURL=add-path-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/add-path-suffix.js
+      } //# sourceMappingURL=add-path-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/add-path-suffix.js
 
       /**
        * Similarly to `addPathPrefix`, this function adds a suffix at the end on the
@@ -387,7 +387,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         }
         const { pathname, query, hash } = parsePath(path);
         return "" + pathname + suffix + query + hash;
-      } //# sourceMappingURL=add-path-suffix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/path-has-prefix.js
+      } //# sourceMappingURL=add-path-suffix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/path-has-prefix.js
 
       /**
        * Checks if a given path starts with a given prefix. It ensures it matches
@@ -401,7 +401,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         }
         const { pathname } = parsePath(path);
         return pathname === prefix || pathname.startsWith(prefix + "/");
-      } //# sourceMappingURL=path-has-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/add-locale.js
+      } //# sourceMappingURL=path-has-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/add-locale.js
 
       /**
        * For a given path and a locale, if the locale is given, it will prefix the
@@ -420,7 +420,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         }
         // Add the locale prefix to the path.
         return addPathPrefix(path, "/" + locale);
-      } //# sourceMappingURL=add-locale.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/format-next-pathname-info.js
+      } //# sourceMappingURL=add-locale.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/format-next-pathname-info.js
 
       function formatNextPathnameInfo(info) {
         let pathname = addLocale(
@@ -444,7 +444,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
             ? addPathSuffix(pathname, "/")
             : pathname
           : removeTrailingSlash(pathname);
-      } //# sourceMappingURL=format-next-pathname-info.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/get-hostname.js
+      } //# sourceMappingURL=format-next-pathname-info.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/get-hostname.js
 
       /**
        * Takes an object with a hostname property (like a parsed URL) and some
@@ -464,7 +464,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           hostname = parsed.hostname;
         } else return;
         return hostname.toLowerCase();
-      } //# sourceMappingURL=get-hostname.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/i18n/normalize-locale-path.js
+      } //# sourceMappingURL=get-hostname.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/i18n/normalize-locale-path.js
 
       /**
        * For a pathname that may include a locale from a list of locales, it
@@ -494,7 +494,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           pathname,
           detectedLocale,
         };
-      } //# sourceMappingURL=normalize-locale-path.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/remove-path-prefix.js
+      } //# sourceMappingURL=normalize-locale-path.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/remove-path-prefix.js
 
       /**
        * Given a path and a prefix it will remove the prefix when it exists in the
@@ -528,7 +528,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         // If the path without the prefix doesn't start with a `/` we need to add it
         // back to the path to make sure it's a valid path.
         return "/" + withoutPrefix;
-      } //# sourceMappingURL=remove-path-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/get-next-pathname-info.js
+      } //# sourceMappingURL=remove-path-prefix.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/get-next-pathname-info.js
 
       function getNextPathnameInfo(pathname, options) {
         var _options_nextConfig;
@@ -579,7 +579,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
               : info.pathname;
         }
         return info;
-      } //# sourceMappingURL=get-next-pathname-info.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/next-url.js
+      } //# sourceMappingURL=get-next-pathname-info.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/next-url.js
 
       const REGEX_LOCALHOST_HOSTNAME =
         /(?!^https?:\/\/)(127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}|::1|localhost)/;
@@ -806,8 +806,8 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         }
       } //# sourceMappingURL=next-url.js.map
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@edge-runtime/cookies/index.js
-      var cookies = __webpack_require__(7560); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/cookies.js // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/request.js
+      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@edge-runtime/cookies/index.js
+      var cookies = __webpack_require__(909); // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/cookies.js // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/request.js
       //# sourceMappingURL=cookies.js.map
 
       const INTERNALS = Symbol("internal request");
@@ -883,7 +883,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         get url() {
           return this[INTERNALS].url;
         }
-      } //# sourceMappingURL=request.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/response.js
+      } //# sourceMappingURL=request.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/spec-extension/response.js
 
       const response_INTERNALS = Symbol("internal response");
       const REDIRECTS = new Set([301, 302, 303, 307, 308]);
@@ -982,7 +982,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
             headers,
           });
         }
-      } //# sourceMappingURL=response.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/relativize-url.js
+      } //# sourceMappingURL=response.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/relativize-url.js
 
       /**
        * Given a URL as a string and a base URL it will make the URL relative
@@ -995,7 +995,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         return relative.protocol + "//" + relative.host === origin
           ? relative.toString().replace(origin, "")
           : relative.toString();
-      } //# sourceMappingURL=relativize-url.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/client/components/app-router-headers.js
+      } //# sourceMappingURL=relativize-url.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/client/components/app-router-headers.js
 
       const RSC = "RSC";
       const ACTION = "Next-Action";
@@ -1011,7 +1011,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         [NEXT_ROUTER_STATE_TREE],
         [NEXT_ROUTER_PREFETCH],
       ];
-      const NEXT_RSC_UNION_QUERY = "_rsc"; //# sourceMappingURL=app-router-headers.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/internal-utils.js
+      const NEXT_RSC_UNION_QUERY = "_rsc"; //# sourceMappingURL=app-router-headers.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/internal-utils.js
 
       const INTERNAL_QUERY_NAMES = [
         "__nextFallback",
@@ -1039,7 +1039,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           }
         }
         return isStringUrl ? instance.toString() : instance;
-      } //# sourceMappingURL=internal-utils.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/app-paths.js
+      } //# sourceMappingURL=internal-utils.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/shared/lib/router/utils/app-paths.js
 
       /**
        * Normalizes an app route so it represents the actual request path. Essentially
@@ -1090,7 +1090,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
        * Since this function is used on full urls it checks `?` for searchParams handling.
        */ function normalizeRscPath(pathname, enabled) {
         return enabled ? pathname.replace(/\.rsc($|\?)/, "$1") : pathname;
-      } //# sourceMappingURL=app-paths.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/lib/constants.js
+      } //# sourceMappingURL=app-paths.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/lib/constants.js
 
       const NEXT_QUERY_PARAM_PREFIX = "nxtP";
       const PRERENDER_REVALIDATE_HEADER = "x-prerender-revalidate";
@@ -1207,7 +1207,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
         metadata: "__next_metadata__",
         metadataRoute: "__next_metadata_route__",
         metadataImageMeta: "__next_metadata_image_meta__",
-      }; //# sourceMappingURL=constants.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/adapter.js
+      }; //# sourceMappingURL=constants.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/adapter.js
 
       class NextRequestHint extends NextRequest {
         constructor(params) {
@@ -1436,14 +1436,14 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
           response: finalResponse,
           waitUntil: Promise.all(event[waitUntilSymbol]),
         };
-      } //# sourceMappingURL=adapter.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/exports/next-response.js // CONCATENATED MODULE: ./middleware.js
+      } //# sourceMappingURL=adapter.js.map // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/exports/next-response.js // CONCATENATED MODULE: ./middleware.js
 
       // This file is for modularized imports for next/server to get fully-treeshaking.
       //# sourceMappingURL=next-response.js.map
 
       async function middleware() {
         return NextResponse.next();
-      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/loaders/next-middleware-loader.js?absolutePagePath=private-next-root-dir%2Fmiddleware.js&page=%2Fmiddleware&rootDir=%2Ftmp%2Fnext-statsddgaKR%2Fstats-app&matchers=&preferredRegion=&middlewareConfig=e30%3D!
+      } // CONCATENATED MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/loaders/next-middleware-loader.js?absolutePagePath=private-next-root-dir%2Fmiddleware.js&page=%2Fmiddleware&rootDir=%2Ftmp%2Fnext-statsddgaKR%2Fstats-app&matchers=&preferredRegion=&middlewareConfig=e30%3D!
 
       const mod = { ...middleware_namespaceObject };
       const handler = mod.middleware || mod.default;
@@ -1467,7 +1467,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
       /***/
     },
 
-    /***/ 7560: /***/ (module) => {
+    /***/ 909: /***/ (module) => {
       "use strict";
 
       var __defProp = Object.defineProperty;
@@ -1864,7 +1864,7 @@ Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`;
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
-    /******/ var __webpack_exports__ = __webpack_exec__(191);
+    /******/ var __webpack_exports__ = __webpack_exec__(6186);
     /******/ (_ENTRIES =
       typeof _ENTRIES === "undefined" ? {} : _ENTRIES).middleware_middleware =
       __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,28 +1,28 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-3eeb184a3b01069a.js"],
-  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-1ca214e380344f72.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-add4644085c74c96.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-42327f7ac4cb0b58.js"],
+  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-a1fe554f661ca2f4.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-30c8a1780ede07c9.js"],
   "/css": [
     "static\u002Fcss\u002Fded6b86ab9cc0a1f.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-5378d3d7af820c29.js",
+    "static\u002Fchunks\u002Fpages\u002Fcss-aa735f5e2aa226b3.js",
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-42da64dc2c2fce13.js",
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-b10d57b71862877f.js",
   ],
   "/edge-ssr": [
-    "static\u002Fchunks\u002Fpages\u002Fedge-ssr-a2fee5412c431f04.js",
+    "static\u002Fchunks\u002Fpages\u002Fedge-ssr-8503741982090fd1.js",
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-2b297fce1a4227af.js"],
-  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-fd524b5719dd436b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-886584a4c844df2f.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-703b373f2d606656.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-83fa8b512be5ddac.js"],
+  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ccc88816344bfb3b.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-cc8e9ba47d3439b3.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-ddfe4479277cba32.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-21c04c160c1f5f7e.js",
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-ec52a13385b3d2cd.js",
   ],
-  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-7bebe95abbd437dc.js"],
+  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-d4167f0109c5dc8f.js"],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-8bb2114b113c11ef.js",
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-c8f30e923eada3a5.js",
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 3115: /***/ function (
+    /***/ 1113: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_app",
         function () {
-          return __webpack_require__(1821);
+          return __webpack_require__(8908);
         },
       ]);
       if (false) {
@@ -24,7 +24,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 179], function () {
-      return __webpack_exec__(3115), __webpack_exec__(8853);
+      return __webpack_exec__(1113), __webpack_exec__(5233);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [820],
   {
-    /***/ 5374: /***/ function (
+    /***/ 3363: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_error",
         function () {
-          return __webpack_require__(8665);
+          return __webpack_require__(7433);
         },
       ]);
       if (false) {
@@ -24,7 +24,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function () {
-      return __webpack_exec__(5374);
+      return __webpack_exec__(3363);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>amp-HASH.js</strong></summary>

```diff
@@ -1,17 +1,17 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [216],
   {
-    /***/ 8510: /***/ function (
+    /***/ 8753: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(9386);
+      module.exports = __webpack_require__(8861);
 
       /***/
     },
 
-    /***/ 7010: /***/ function (
+    /***/ 5348: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -19,7 +19,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/amp",
         function () {
-          return __webpack_require__(264);
+          return __webpack_require__(313);
         },
       ]);
       if (false) {
@@ -28,7 +28,7 @@
       /***/
     },
 
-    /***/ 9386: /***/ function (module, exports, __webpack_require__) {
+    /***/ 8861: /***/ function (module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -44,8 +44,8 @@
       const _react = /*#__PURE__*/ _interop_require_default._(
         __webpack_require__(959)
       );
-      const _ampcontext = __webpack_require__(5810);
-      const _ampmode = __webpack_require__(9433);
+      const _ampcontext = __webpack_require__(6101);
+      const _ampmode = __webpack_require__(443);
       function useAmp() {
         // Don't assign the context value to a variable to save bytes
         return (0, _ampmode.isInAmpMode)(
@@ -67,7 +67,7 @@
       /***/
     },
 
-    /***/ 264: /***/ function (
+    /***/ 313: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -84,7 +84,7 @@
         /* harmony export */
       });
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(8510);
+        __webpack_require__(8753);
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_amp__WEBPACK_IMPORTED_MODULE_0__
@@ -108,7 +108,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function () {
-      return __webpack_exec__(7010);
+      return __webpack_exec__(5348);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>css-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [706],
   {
-    /***/ 860: /***/ function (
+    /***/ 6437: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/css",
         function () {
-          return __webpack_require__(9006);
+          return __webpack_require__(9670);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 9006: /***/ function (
+    /***/ 9670: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -28,7 +28,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(1527);
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(4790);
+        __webpack_require__(3935);
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           _css_module_css__WEBPACK_IMPORTED_MODULE_1__
@@ -48,7 +48,7 @@
       /***/
     },
 
-    /***/ 4790: /***/ function (module) {
+    /***/ 3935: /***/ function (module) {
       // extracted by mini-css-extract-plugin
       module.exports = { helloWorld: "css_helloWorld__aUdUq" };
 
@@ -61,7 +61,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function () {
-      return __webpack_exec__(860);
+      return __webpack_exec__(6437);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [739],
   {
-    /***/ 3995: /***/ function (
+    /***/ 7753: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/dynamic",
         function () {
-          return __webpack_require__(2060);
+          return __webpack_require__(651);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 684: /***/ function (module, exports, __webpack_require__) {
+    /***/ 4253: /***/ function (module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -45,7 +45,7 @@
         __webpack_require__(959)
       );
       const _loadable = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(1295)
+        __webpack_require__(7139)
       );
       const isServerSide = "object" === "undefined";
       // Normalize loader to return the module as form { default: Component } for `React.lazy`.
@@ -146,7 +146,7 @@
       /***/
     },
 
-    /***/ 3441: /***/ function (
+    /***/ 5185: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -173,7 +173,7 @@
       /***/
     },
 
-    /***/ 1295: /***/ function (
+    /***/ 7139: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -215,7 +215,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       const _react = /*#__PURE__*/ _interop_require_default._(
         __webpack_require__(959)
       );
-      const _loadablecontext = __webpack_require__(3441);
+      const _loadablecontext = __webpack_require__(5185);
       function resolve(obj) {
         return obj && obj.default ? obj.default : obj;
       }
@@ -450,7 +450,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       /***/
     },
 
-    /***/ 2060: /***/ function (
+    /***/ 651: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -466,7 +466,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(1527);
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(6113);
+        __webpack_require__(2677);
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_dynamic__WEBPACK_IMPORTED_MODULE_1__
@@ -475,11 +475,11 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       const DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
         () =>
           __webpack_require__
-            .e(/* import() */ 511)
-            .then(__webpack_require__.bind(__webpack_require__, 5511)),
+            .e(/* import() */ 370)
+            .then(__webpack_require__.bind(__webpack_require__, 3685)),
         {
           loadableGenerated: {
-            webpack: () => [/*require.resolve*/ 5511],
+            webpack: () => [/*require.resolve*/ 3685],
           },
         }
       );
@@ -506,12 +506,12 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       /***/
     },
 
-    /***/ 6113: /***/ function (
+    /***/ 2677: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(684);
+      module.exports = __webpack_require__(4253);
 
       /***/
     },
@@ -522,7 +522,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function () {
-      return __webpack_exec__(3995);
+      return __webpack_exec__(7753);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>edge-ssr-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [800],
   {
-    /***/ 6219: /***/ function (
+    /***/ 1902: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/edge-ssr",
         function () {
-          return __webpack_require__(2102);
+          return __webpack_require__(5892);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 2102: /***/ function (
+    /***/ 5892: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -48,7 +48,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function () {
-      return __webpack_exec__(6219);
+      return __webpack_exec__(1902);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>head-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [645],
   {
-    /***/ 2899: /***/ function (
+    /***/ 6955: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/head",
         function () {
-          return __webpack_require__(145);
+          return __webpack_require__(9910);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 145: /***/ function (
+    /***/ 9910: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -34,7 +34,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(1527);
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(8412);
+        __webpack_require__(9046);
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_head__WEBPACK_IMPORTED_MODULE_1__
@@ -68,12 +68,12 @@
       /***/
     },
 
-    /***/ 8412: /***/ function (
+    /***/ 9046: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(2379);
+      module.exports = __webpack_require__(4337);
 
       /***/
     },
@@ -84,7 +84,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function () {
-      return __webpack_exec__(2899);
+      return __webpack_exec__(6955);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>hooks-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [757],
   {
-    /***/ 2304: /***/ function (
+    /***/ 7819: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/hooks",
         function () {
-          return __webpack_require__(5715);
+          return __webpack_require__(1052);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 5715: /***/ function (
+    /***/ 1052: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -79,7 +79,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function () {
-      return __webpack_exec__(2304);
+      return __webpack_exec__(7819);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [358],
   {
-    /***/ 5885: /***/ function (
+    /***/ 801: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function () {
-          return __webpack_require__(410);
+          return __webpack_require__(7011);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 678: /***/ function (module, exports, __webpack_require__) {
+    /***/ 1690: /***/ function (module, exports, __webpack_require__) {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -36,14 +36,14 @@
         __webpack_require__(959)
       );
       const _head = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(2379)
+        __webpack_require__(4337)
       );
-      const _getimgprops = __webpack_require__(884);
-      const _imageconfig = __webpack_require__(4543);
-      const _imageconfigcontext = __webpack_require__(7393);
-      const _warnonce = __webpack_require__(6403);
+      const _getimgprops = __webpack_require__(8800);
+      const _imageconfig = __webpack_require__(942);
+      const _imageconfigcontext = __webpack_require__(5037);
+      const _warnonce = __webpack_require__(2910);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(7610)
+        __webpack_require__(8713)
       );
       // This is replaced by webpack define plugin
       const configEnv = {
@@ -346,7 +346,7 @@
       /***/
     },
 
-    /***/ 884: /***/ function (
+    /***/ 8800: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -362,9 +362,9 @@
           return getImgProps;
         },
       });
-      const _warnonce = __webpack_require__(6403);
-      const _imageblursvg = __webpack_require__(7101);
-      const _imageconfig = __webpack_require__(4543);
+      const _warnonce = __webpack_require__(2910);
+      const _imageblursvg = __webpack_require__(609);
+      const _imageconfig = __webpack_require__(942);
       const VALID_LOADING_VALUES =
         /* unused pure expression or super */ null && [
           "lazy",
@@ -729,7 +729,7 @@
       /***/
     },
 
-    /***/ 7101: /***/ function (__unused_webpack_module, exports) {
+    /***/ 609: /***/ function (__unused_webpack_module, exports) {
       "use strict";
       /**
        * A shared function, used on both client and server, to generate a SVG blur placeholder.
@@ -752,25 +752,29 @@
           blurDataURL,
           objectFit,
         } = param;
-        const std = blurWidth && blurHeight ? "1" : "20";
         const svgWidth = blurWidth || widthInt;
         const svgHeight = blurHeight || heightInt;
-        const feComponentTransfer = blurDataURL.startsWith("data:image/jpeg")
-          ? "%3CfeComponentTransfer%3E%3CfeFuncA type='discrete' tableValues='1 1'/%3E%3C/feComponentTransfer%3E%"
-          : "";
         if (svgWidth && svgHeight) {
+          const std = blurWidth && blurHeight ? 1 : 20;
+          const smoothenMask = 15;
           return (
-            "%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 " +
+            "%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 " +
             svgWidth +
             " " +
             svgHeight +
-            "'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='" +
+            "' width='" +
+            svgWidth +
+            "' height='" +
+            svgHeight +
+            "'%3e%3cfilter id='b' color-interpolation-filters='sRGB'%3e%3cfeMorphology in='SourceAlpha' operator='dilate' radius='" +
+            smoothenMask +
+            "' result='dilate'%3e%3c/feMorphology%3e%3cfeGaussianBlur in='dilate' stdDeviation='" +
+            smoothenMask +
+            "' result='mask'%3e%3c/feGaussianBlur%3e%3cfeGaussianBlur in='SourceGraphic' stdDeviation='" +
             std +
-            "'/%3E" +
-            feComponentTransfer +
-            "%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='" +
+            "' result='blur'%3e%3c/feGaussianBlur%3e%3cfeComponentTransfer in='blur' result='solid'%3e%3cfeFuncA type='table' tableValues='1 1'%3e%3c/feFuncA%3e%3c/feComponentTransfer%3e%3cfeComposite in2='mask' in='solid' operator='in' result='comp'%3e%3c/feComposite%3e%3cfeMerge%3e%3cfeMergeNode in='SourceGraphic'/%3e%3cfeMergeNode in='comp'/%3e%3c/feMerge%3e%3c/filter%3e%3cimage style='filter: url(%23b);' x='0' y='0' width='100%25' height='100%25' preserveAspectRatio='none' href='" +
             blurDataURL +
-            "'/%3E%3C/svg%3E"
+            "'%3e%3c/image%3e%3c/svg%3e"
           );
         }
         const preserveAspectRatio =
@@ -791,7 +795,7 @@
       /***/
     },
 
-    /***/ 8054: /***/ function (
+    /***/ 3744: /***/ function (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -818,11 +822,11 @@
         },
       });
       const _interop_require_default = __webpack_require__(8266);
-      const _getimgprops = __webpack_require__(884);
-      const _warnonce = __webpack_require__(6403);
-      const _imagecomponent = __webpack_require__(678);
+      const _getimgprops = __webpack_require__(8800);
+      const _warnonce = __webpack_require__(2910);
+      const _imagecomponent = __webpack_require__(1690);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(7610)
+        __webpack_require__(8713)
       );
       const unstable_getImgProps = (imgProps) => {
         (0, _warnonce.warnOnce)(
@@ -854,7 +858,7 @@
       /***/
     },
 
-    /***/ 7610: /***/ function (__unused_webpack_module, exports) {
+    /***/ 8713: /***/ function (__unused_webpack_module, exports) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -889,7 +893,7 @@
       /***/
     },
 
-    /***/ 410: /***/ function (
+    /***/ 7011: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -910,8 +914,8 @@
 
       // EXTERNAL MODULE: ./node_modules/.pnpm/react@18.2.0/node_modules/react/jsx-runtime.js
       var jsx_runtime = __webpack_require__(1527);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/image.js
-      var next_image = __webpack_require__(3960);
+      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/image.js
+      var next_image = __webpack_require__(8249);
       var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // CONCATENATED MODULE: ./pages/nextjs.png
       /* harmony default export */ var nextjs = {
         src: "/_next/static/media/nextjs.cae0b805.png",
@@ -941,12 +945,12 @@
       /***/
     },
 
-    /***/ 3960: /***/ function (
+    /***/ 8249: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(8054);
+      module.exports = __webpack_require__(3744);
 
       /***/
     },
@@ -957,7 +961,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function () {
-      return __webpack_exec__(5885);
+      return __webpack_exec__(801);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>index-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [405],
   {
-    /***/ 3558: /***/ function (
+    /***/ 6481: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/",
         function () {
-          return __webpack_require__(8391);
+          return __webpack_require__(8121);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 8391: /***/ function (
+    /***/ 8121: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -44,7 +44,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function () {
-      return __webpack_exec__(3558);
+      return __webpack_exec__(6481);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [644],
   {
-    /***/ 8662: /***/ function (
+    /***/ 7014: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/link",
         function () {
-          return __webpack_require__(5181);
+          return __webpack_require__(6513);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 4506: /***/ function (module, exports) {
+    /***/ 1385: /***/ function (module, exports) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -86,7 +86,7 @@
       /***/
     },
 
-    /***/ 2918: /***/ function (module, exports, __webpack_require__) {
+    /***/ 4900: /***/ function (module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -98,7 +98,7 @@
           return getDomainLocale;
         },
       });
-      const _normalizetrailingslash = __webpack_require__(5311);
+      const _normalizetrailingslash = __webpack_require__(8810);
       const basePath =
         /* unused pure expression or super */ null && (false || "");
       function getDomainLocale(path, locale, locales, domainLocales) {
@@ -122,7 +122,7 @@
       /***/
     },
 
-    /***/ 3461: /***/ function (module, exports, __webpack_require__) {
+    /***/ 3916: /***/ function (module, exports, __webpack_require__) {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -138,17 +138,17 @@
       const _react = /*#__PURE__*/ _interop_require_default._(
         __webpack_require__(959)
       );
-      const _resolvehref = __webpack_require__(3613);
-      const _islocalurl = __webpack_require__(7746);
-      const _formaturl = __webpack_require__(4462);
-      const _utils = __webpack_require__(2195);
-      const _addlocale = __webpack_require__(8033);
-      const _routercontext = __webpack_require__(6508);
-      const _approutercontext = __webpack_require__(6493);
-      const _useintersection = __webpack_require__(8581);
-      const _getdomainlocale = __webpack_require__(2918);
-      const _addbasepath = __webpack_require__(2419);
-      const _routerreducertypes = __webpack_require__(4506);
+      const _resolvehref = __webpack_require__(7691);
+      const _islocalurl = __webpack_require__(7076);
+      const _formaturl = __webpack_require__(3838);
+      const _utils = __webpack_require__(6625);
+      const _addlocale = __webpack_require__(7134);
+      const _routercontext = __webpack_require__(912);
+      const _approutercontext = __webpack_require__(7542);
+      const _useintersection = __webpack_require__(1848);
+      const _getdomainlocale = __webpack_require__(4900);
+      const _addbasepath = __webpack_require__(3657);
+      const _routerreducertypes = __webpack_require__(1385);
       const prefetched = new Set();
       function prefetch(router, href, as, options, appOptions, isAppRouter) {
         if (false) {
@@ -567,7 +567,7 @@
       /***/
     },
 
-    /***/ 8581: /***/ function (module, exports, __webpack_require__) {
+    /***/ 1848: /***/ function (module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -580,7 +580,7 @@
         },
       });
       const _react = __webpack_require__(959);
-      const _requestidlecallback = __webpack_require__(3211);
+      const _requestidlecallback = __webpack_require__(2944);
       const hasIntersectionObserver =
         typeof IntersectionObserver === "function";
       const observers = new Map();
@@ -693,7 +693,7 @@
       /***/
     },
 
-    /***/ 5181: /***/ function (
+    /***/ 6513: /***/ function (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -709,7 +709,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(1527);
       /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(4595);
+        __webpack_require__(9495);
       /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_link__WEBPACK_IMPORTED_MODULE_1__
@@ -740,12 +740,12 @@
       /***/
     },
 
-    /***/ 4595: /***/ function (
+    /***/ 9495: /***/ function (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      module.exports = __webpack_require__(3461);
+      module.exports = __webpack_require__(3916);
 
       /***/
     },
@@ -756,7 +756,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 888, 179], function () {
-      return __webpack_exec__(8662);
+      return __webpack_exec__(7014);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>routerDirect-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [58],
   {
-    /***/ 2188: /***/ function (
+    /***/ 7288: /***/ function (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/routerDirect",
         function () {
-          return __webpack_require__(4769);
+          return __webpack_require__(762);
         },
    
Post job cleanup.
[command]/usr/bin/git version
git version 2.41.0
Temporarily overriding HOME='/home/runner/work/_temp/4667da32-29d5-474e-a1f0-79fe0ce5842b' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
[command]/usr/bin/git config --global --add safe.directory /home/runner/work/next.js/next.js
[command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
[command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
[command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
[command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
[command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
Cleaning up orphan processes
Commit: 15e2ca8483d7c3895f10b739df11c59f94972237

**Comment by styfle** [comment]
@arturbien Something looks wrong with the `id="blur-wide"` image. 

Try this before and after your change:

1. `pnpm next build test/integration/next-image-new/default`
2. `pnpm next start test/integration/next-image-new/default`
3. Visit `http://localhost:3000/static-img`
4. Look at the blur placeholder for the image with id `blur-wide`

### Before

```html
<img id="blur-wide" loading="lazy" width="1200" height="700" decoding="async" data-nimg="1" style="color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(&quot;data:image/svg+xml;charset=utf-8,%3Csvg xmlns=&#x27;http%3A//www.w3.org/2000/svg&#x27; viewBox=&#x27;0 0 8 5&#x27;%3E%3Cfilter id=&#x27;b&#x27; color-interpolation-filters=&#x27;sRGB&#x27;%3E%3CfeGaussianBlur stdDeviation=&#x27;1&#x27;/%3E%3C/filter%3E%3Cimage preserveAspectRatio=&#x27;none&#x27; filter=&#x27;url(%23b)&#x27; x=&#x27;0&#x27; y=&#x27;0&#x27; height=&#x27;100%25&#x27; width=&#x27;100%25&#x27; href=&#x27;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAFCAAAAABd+vKJAAAANklEQVR42mNg4GRwdWBgZ2BgUGI4dYhBmYFBgiHy308PBlEGKYbr//9fYJBlYDBYv3nzGkUGANGMDBq2MCnBAAAAAElFTkSuQmCC&#x27;/%3E%3C/svg%3E&quot;)" srcSet="[/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fwide.8744c79a.png&amp;w=1200&amp;q=75 1x](http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fwide.8744c79a.png&amp;w=1200&amp;q=75),[ /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fwide.8744c79a.png&amp;w=3840&amp;q=75 2x](http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fwide.8744c79a.png&amp;w=3840&amp;q=75)" src="[/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fwide.8744c79a.png&amp;w=3840&amp;q=75](http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fwide.8744c79a.png&w=3840&q=75)"/>
```

image

### After

```html
<img id="blur-wide" loading="lazy" width="1200" height="700" decoding="async" data-nimg="1" style="color:transparent;background-size:cover;background-position:50% 50%;background-repeat:no-repeat;background-image:url(&quot;data:image/svg+xml;charset=utf-8,%3csvg xmlns=&#x27;http://www.w3.org/2000/svg&#x27; viewBox=&#x27;0 0 8 5&#x27; width=&#x27;8&#x27; height=&#x27;5&#x27;%3e%3cfilter id=&#x27;b&#x27; color-interpolation-filters=&#x27;sRGB&#x27;%3e%3cfeMorphology in=&#x27;SourceAlpha&#x27; operator=&#x27;dilate&#x27; radius=&#x27;15&#x27; result=&#x27;dilate&#x27;%3e%3c/feMorphology%3e%3cfeGaussianBlur in=&#x27;dilate&#x27; stdDeviation=&#x27;15&#x27; result=&#x27;mask&#x27;%3e%3c/feGaussianBlur%3e%3cfeGaussianBlur in=&#x27;SourceGraphic&#x27; stdDeviation=&#x27;1&#x27; result=&#x27;blur&#x27;%3e%3c/feGaussianBlur%3e%3cfeComponentTransfer in=&#x27;blur&#x27; result=&#x27;solid&#x27;%3e%3cfeFuncA type=&#x27;table&#x27; tableValues=&#x27;1 1&#x27;%3e%3c/feFuncA%3e%3c/feComponentTransfer%3e%3cfeComposite in2=&#x27;mask&#x27; in=&#x27;solid&#x27; operator=&#x27;in&#x27; result=&#x27;comp&#x27;%3e%3c/feComposite%3e%3cfeMerge%3e%3cfeMergeNode in=&#x27;SourceGraphic&#x27;/%3e%3cfeMergeNode in=&#x27;comp&#x27;/%3e%3c/feMerge%3e%3c/filter%3e%3cimage style=&#x27;filter: url(%23b);&#x27; x=&#x27;0&#x27; y=&#x27;0&#x27; width=&#x27;100%25&#x27; height=&#x27;100%25&#x27; preserveAspectRatio=&#x27;none&#x27; href=&#x27;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAFCAAAAABd+vKJAAAANklEQVR42mNg4GRwdWBgZ2BgUGI4dYhBmYFBgiHy308PBlEGKYbr//9fYJBlYDBYv3nzGkUGANGMDBq2MCnBAAAAAElFTkSuQmCC&#x27;%3e%3c/image%3e%3c/svg%3e&quot;)" srcSet="[/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fwide.8744c79a.png&amp;w=1200&amp;q=75 1x](http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fwide.8744c79a.png&amp;w=1200&amp;q=75),[ /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fwide.8744c79a.png&amp;w=3840&amp;q=75 2x](http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fwide.8744c79a.png&amp;w=3840&amp;q=75)" src="[/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fwide.8744c79a.png&amp;w=3840&amp;q=75](http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fwide.8744c79a.png&w=3840&q=75)"/>
```

image

**Comment by arturbien** [comment]
@styfle Looks like I didn't handle the 1px blur case properly. I'll look into this tomorrow. Thank you for your patience and sorry for taking your time!

**Comment by styfle** [comment]
There are a lot of cases to consider:

1. When the user provides a static import: `import img from './img.jpg'`
2. When the user provides a remote image: `<Image src="https://example.com" width={200} height={500} placeholder="blur" />`
3. When the user provides a remote image with blurDataURL: `<Image src="https://example.com" width={200} height={500} placeholder="blur" blurDataURL="data:..." />`
4. When the user provides an transparent image (for example PNG)
5. When the user provides blurDataURL with slightly different aspect ratio then the provided width and height

**Comment by arturbien** [comment]
@styfle Been busy over the weekend so I didn't make any progress. But I am getting back to it today

**Comment by arturbien** [comment]
@styfle I've switched implementation for the filter for better results. It works by artificially extending the source image before applying the actual blur which fixes the feathered edges issue.

```html
  <filter id='b' color-interpolation-filters='sRGB'>
    <feGaussianBlur stdDeviation='20' />
    <!-- Takes blur result and turns all semi-transparent pixels solid  -->
    <feColorMatrix values='1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 100 -1' result='s' />
    <feFlood x='0' y='0' width='100%' height='100%' />
    <!--  Clips the "solid" blur result leaving only the pixels placed on the outside of the SourceGraphic. -->
    <!-- This extends the SourceImage (making it bigger) which helps us remove the feathered edges issue. -->
    <feComposite operator='out' in='s' />
    <!-- Merges original image with the solid blur outline  -->
    <feComposite in2='SourceGraphic' />
    <!-- Blurs everything -->
    <feGaussianBlur stdDeviation='20' />
  </filter>
```


Pages I've tested:
- `/static-img`
- `/blurry-placeholder`
- `/fill-blur`

Had some troubles running `test/integration/next-image-new/app-dir/test/index.test.ts` and `test/integration/next-image-new/default/test/index.test.ts` - it seemed like the tests were stuck in some weird fail/retry loop.

File: packages/next/src/shared/lib/image-blur-svg.ts [hunk 3]
```diff
@@ -16,20 +16,21 @@ export function getImageBlurSvg({
...
-  return `%3Csvg xmlns='http%3A//www.w3.org/2000/svg'%3E%3Cimage style='filter:blur(20px)' preserveAspectRatio='${preserveAspectRatio}' x='0' y='0' height='100%25' width='100%25' href='${blurDataURL}'/%3E%3C/svg%3E`
+  const preserveAspectRatio = svgDimensions
+    ? 'none'
+    : objectFit === 'contain'
+    ? 'xMidYMid'
+    : objectFit === 'cover'
+    ? 'xMidYMid slice'
+    : 'none'
+
+  return `%3csvg xmlns='http://www.w3.org/2000/svg' ${svgSizeAttributes}%3e%3cfilter id='b' color-interpolation-filters='sRGB'%3e%3cfeGaussianBlur stdDeviation='${std}'/%3e%3cfeColorMatrix values='1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 100 -1' result='s'/%3e%3cfeFlood x='0' y='0' width='100%25' height='100%25'/%3e%3cfeComposite operator='out' in='s'/%3e%3cfeComposite in2='SourceGraphic'/%3e%3cfeGaussianBlur stdDeviation='${std}'/%3e%3c/filter%3e%3cimage width='100%25' height='100%25' x='0' y='0' preserveAspectRatio='${preserveAspectRatio}' style='filter: url(%23b);' href='${blurDataURL}'/%3e%3c/svg%3e`
```
Comment (styfle) [inline packages/next/src/shared/lib/image-blur-svg.ts:35]: Previously this was `%3C` but now I see `%3c`.

Any reason you chose to encode with lowercase instead of uppercase?

I think uppercase is more common since due to `encodeURI('<')` which outputs `%3C`.

File: packages/next/src/shared/lib/image-blur-svg.ts [hunk 4]
```diff
@@ -16,20 +16,21 @@ export function getImageBlurSvg({
   blurDataURL: string
   objectFit?: string
 }): string {
-  const std = blurWidth && blurHeight ? '1' : '20'
+  const std = blurWidth && blurHeight ? 0.5 : 20
```
Comment (styfle) [inline packages/next/src/shared/lib/image-blur-svg.ts:19]: Any reason why `1` was changed to `0.5`?

Did you take any screenshots comparing the two?

File: packages/next/src/shared/lib/image-blur-svg.ts [hunk 5]
```diff
@@ -16,20 +16,21 @@ export function getImageBlurSvg({
...
   const svgWidth = blurWidth || widthInt
   const svgHeight = blurHeight || heightInt
-  const feComponentTransfer = blurDataURL.startsWith('data:image/jpeg')
-    ? `%3CfeComponentTransfer%3E%3CfeFuncA type='discrete' tableValues='1 1'/%3E%3C/feComponentTransfer%3E%`
+
+  const svgDimensions = svgWidth && svgHeight
+  const svgSizeAttributes = svgDimensions
```
Comment (styfle) [inline packages/next/src/shared/lib/image-blur-svg.ts:24]:
```suggestion
  const viewBox = svgWidth && svgHeight
```

I think you can remove the `svgDimensions` variable since the viewbox is falsy

File: packages/next/src/shared/lib/image-blur-svg.ts [hunk 6]
```diff
@@ -16,20 +16,21 @@ export function getImageBlurSvg({
...
-    return `%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 ${svgWidth} ${svgHeight}'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='${std}'/%3E${feComponentTransfer}%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='${blurDataURL}'/%3E%3C/svg%3E`
-  }
-  const preserveAspectRatio =
-    objectFit === 'contain'
-      ? 'xMidYMid'
-      : objectFit === 'cover'
-      ? 'xMidYMid slice'
-      : 'none'
-  return `%3Csvg xmlns='http%3A//www.w3.org/2000/svg'%3E%3Cimage style='filter:blur(20px)' preserveAspectRatio='${preserveAspectRatio}' x='0' y='0' height='100%25' width='100%25' href='${blurDataURL}'/%3E%3C/svg%3E`
+  const preserveAspectRatio = svgDimensions
```
Comment (styfle) [inline packages/next/src/shared/lib/image-blur-svg.ts:27]:
```suggestion
  const preserveAspectRatio = viewBox
```

Then you can check if the viewBox is truthy or falsy here

File: packages/next/src/shared/lib/image-blur-svg.ts (hunk 3 above)
Comment (styfle) [inline packages/next/src/shared/lib/image-blur-svg.ts:35]:
```suggestion
  return `%3csvg xmlns='http://www.w3.org/2000/svg' ${viewBox}%3e%3cfilter id='b' color-interpolation-filters='sRGB'%3e%3cfeGaussianBlur stdDeviation='${std}'/%3e%3cfeColorMatrix values='1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 100 -1' result='s'/%3e%3cfeFlood x='0' y='0' width='100%25' height='100%25'/%3e%3cfeComposite operator='out' in='s'/%3e%3cfeComposite in2='SourceGraphic'/%3e%3cfeGaussianBlur stdDeviation='${std}'/%3e%3c/filter%3e%3cimage width='100%25' height='100%25' x='0' y='0' preserveAspectRatio='${preserveAspectRatio}' style='filter: url(%23b);' href='${blurDataURL}'/%3e%3c/svg%3e`
```

I think `viewBox` is a better name than `svgSizeAttributes`

**Comment by styfle** [comment]
Great work! I left a few comments. Also there are a few tests that need to be updated:

```
      ✕ should remove blurry placeholder after image loads (156 ms)
      ✕ should render correct objectFit when blurDataURL and fill (10 ms)

      ✕ should emit blur svg when width is 8 in dev but not prod (179 ms)
      ✕ should emit blur svg when width is less than 8 in dev but not prod (36 ms)
```

File: packages/next/src/shared/lib/image-blur-svg.ts (hunk 4 above)
Comment (arturbien) [reply packages/next/src/shared/lib/image-blur-svg.ts:19]: Ok so for me there was quite a big visual difference between 1px and 20px blur placeholder images (1px blur images seemed to be too blurry). I started digging in to find out why and I've found this part right here

https://github.com/vercel/next.js/blob/946c9c5c46091604b8a9c73260bfe26ece70de23/packages/next/src/build/webpack/loaders/next-image-loader/blur.ts#L4
https://github.com/vercel/next.js/blob/946c9c5c46091604b8a9c73260bfe26ece70de23/packages/next/src/build/webpack/loaders/next-image-loader/blur.ts#L42-L54

https://github.com/vercel/next.js/blob/e17218fcba36ef148797dfefd5147e01cb29843b/packages/next/src/shared/lib/get-img-props.ts#L355-L356

So it looks like the "1px" blur is only used for blur placeholders generated by Next.js for staticly imported images (please correct me if I am wrong here) and they're at most 8px wide .

How I tried to figure out a better blur value for these small placeholders (8px wide/high maximum) is by doing simple calculations.

Taking two example images, one 390px wide (an iPhone 12 PRO screen width) and the second one 1512px wide (14" laptop screen width) I calculated the blur ratio bounds assuming the default blur is 20px.

20/1512 = 0.013 ----> 20/390 = 0.05 

Now translating that to 8px wide images:

0.013 * 8 = 0.1 ----> 0.05 * 8 = 0.4

Given that most traffic happens on mobile devices I've decided to go for the upper bound (images of smart phone screen width) and round it to 0.5 (because I know that SVG filters handle decimal halves values well).

## Alternative approach

Switching between different blur values depending on `blurWidth` and `blurHeight` being present seems a bit hacky to me. What we could do instead is to scale the `viewBox` attribute when `blurWidth` and `blurHeight` are set (since we know these values are at most 8px). Instead of doing `viewbox='0 0 8 5'` we could scale it by a 100 (to get closer to a normal image size) and do `viewbox='0 0 800 500'`. This way proportions are kept and blur stays consistent.

File: packages/next/src/shared/lib/image-blur-svg.ts (hunk 3 above)
Comment (arturbien) [reply packages/next/src/shared/lib/image-blur-svg.ts:35]: Yeah I've used some online encoder and it returned lowercase. I'll change that

File: packages/next/src/shared/lib/image-blur-svg.ts (hunk 4 above)
Comment (styfle) [reply packages/next/src/shared/lib/image-blur-svg.ts:19]: @arturbien Sound good!

A few things:

> 390px wide (an iPhone 12 PRO screen width)

This is not accounting for the 3x DPR. You can confirm this by looking in dev tools emulation or by logging `window.devicePixelRatio` which prints `3`.

image

So the 390px is really 1170px wide. 

Its quite common to have displays for 2x or 3x today, even on older devices.

> Instead of doing viewbox='0 0 8 5' we could scale it by 50 (to get closer to the normal image size ~ 400px ) and do viewbox='0 0 400 250'. This way proportions are kept and blur stays fixed at 20px.

That sounds like it could be a good approach, but where did you get the number `50`?

Comment (arturbien) [reply packages/next/src/shared/lib/image-blur-svg.ts:19]: > This is not accounting for the 3x DPR. You can confirm this by looking in dev tools emulation or by logging window.devicePixelRatio which prints 3.

AFAIK the viewBox doesn't 'care' about the DPI because it just specifies SVG dimensions in user space in px length unit (just like in CSS - width: 1px is actually 2 physical pixels wide for screens of DPI=2):

> The viewBox attribute defines the position and dimension, in user space, of an SVG viewport.

Also if DPI was problematic it would also have to break for the current viewBox/1px blur approach (As it remains constant across all possible DPIs)

> That sounds like it could be a good approach, but where did you get the number 50?

Well I just picked a 400px wide imaginary image for which 20px blur looks perfect. Then calculated the scale value 400px/8px (max blur width) = 50. The scale value of course can be tweaked but from my brief testing round it looked fine. 

Maybe I'll just implement that now, we'll test it and if you approve I'll update all tests so that we're ready to merge.

I think its worth a try because then we'll just have one simple filter that handles all cases no matter where the placeholder blur comes from 🤓

Comment (styfle) [reply packages/next/src/shared/lib/image-blur-svg.ts:19]: Yeah lets try it out, as long as it works for all image sizes and not just the "400px wide imaginary image" 😄

Comment (arturbien) [reply packages/next/src/shared/lib/image-blur-svg.ts]: @styfle I've pushed the changes and fixed the blur value to 20px. Here's comparison for the `/fill-blur` demo page.
Other demos look good to, but take a second look and if you approve it I'll update all the test cases.

Screenshot 2023-07-24 at 09 00 38
Screenshot 2023-07-24 at 09 00 47

**Comment by arturbien** [comment]
@styfle I've pushed the changes and fixed the blur value to 20px. Here's comparison for the `/fill-blur` demo page.
Other demos look good to, but take a second look and if you approve it I'll update all the test cases.

Screenshot 2023-07-24 at 09 00 38
Screenshot 2023-07-24 at 09 00 47

**Comment by arturbien** [comment]
@styfle I've updated all relevant tests but some of the `build-and-test / test turbopack integration (*)` are failing. From the logs it looks like its unrelated to my changes but maybe I am missing something?

File: packages/next/src/shared/lib/image-blur-svg.ts (hunk 4 above)
Comment (arturbien) [reply packages/next/src/shared/lib/image-blur-svg.ts]: FYI I went with 40x multiplier as it looked better compared to 50x

File: test/integration/image-optimizer/test/index.test.ts [hunk 7]
```diff
@@ -704,7 +704,7 @@ describe('Image Optimizer', () => {
       const opts = { headers: { accept: 'image/webp' } }
       const res = await fetchViaHTTP(appPort, '/_next/image', query, opts)
       expect(res.status).toBe(200)
-      await expectWidth(res, 8)
+      await expectWidth(res, 320)
     })
```
[the remark this answers is not in the document]
Comment (styfle) [reply test/integration/image-optimizer/test/index.test.ts:708]: No, I think the name is correct because the `8` is talking about the input.

File: packages/next/src/shared/lib/image-blur-svg.ts [hunk 8]
```diff
@@ -16,20 +16,19 @@ export function getImageBlurSvg({
...
+    svgWidth && svgHeight ? `viewBox='0 0 ${svgWidth} ${svgHeight}'` : ''
+  const preserveAspectRatio = viewBox
+    ? 'none'
+    : objectFit === 'contain'
+    ? 'xMidYMid'
+    : objectFit === 'cover'
+    ? 'xMidYMid slice'
+    : 'none'
+
+  return `%3Csvg xmlns='http://www.w3.org/2000/svg' ${viewBox}%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='${std}'/%3E%3CfeColorMatrix values='1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 100 -1' result='s'/%3E%3CfeFlood x='0' y='0' width='100%25' height='100%25'/%3E%3CfeComposite operator='out' in='s'/%3E%3CfeComposite in2='SourceGraphic'/%3E%3CfeGaussianBlur stdDeviation='${std}'/%3E%3C/filter%3E%3Cimage width='100%25' height='100%25' x='0' y='0' preserveAspectRatio='${preserveAspectRatio}' style='filter: url(%23b);' href='${blurDataURL}'/%3E%3C/svg%3E`
```
Comment (styfle) [inline packages/next/src/shared/lib/image-blur-svg.ts:33]: Can you change the order of the props so that the diff is easier to read:

Lets keep it: style, preserveAspectRatio, x, y, height, width, href

**Review by styfle — APPROVED** [review]
Great work, thanks! 🎉

**Comment by arturbien** [comment]
@styfle should I try to squash all of the commits first before we merge?

**Comment by styfle** [comment]
No need - we automatically squash on merge. 

However, You can update the PR description.

**Comment by arturbien** [comment]
@styfle sorry I didn't manage to update the PR description - it was a night time for me.

Thank you @styfle and @ijjk for assisting me on this PR. ❤️

**Comment by styfle** [comment]
@arturbien Since you have been spending a lot of time in this area, I wonder if you could solve this problem too:

- https://github.com/vercel/next.js/issues/47639

**Comment by arturbien** [comment]
@styfle I'll look into it tomorrow 🤙

File: packages/next/src/shared/lib/image-blur-svg.ts [hunk 9]
```diff
@@ -16,20 +16,19 @@ export function getImageBlurSvg({
...
-    return `%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 ${svgWidth} ${svgHeight}'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='${std}'/%3E${feComponentTransfer}%3C/filter%3E%3Cimage preserveAspectRatio='none' filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='${blurDataURL}'/%3E%3C/svg%3E`
-  }
-  const preserveAspectRatio =
-    objectFit === 'contain'
-      ? 'xMidYMid'
-      : objectFit === 'cover'
-      ? 'xMidYMid slice'
-      : 'none'
-  return `%3Csvg xmlns='http%3A//www.w3.org/2000/svg'%3E%3Cimage style='filter:blur(20px)' preserveAspectRatio='${preserveAspectRatio}' x='0' y='0' height='100%25' width='100%25' href='${blurDataURL}'/%3E%3C/svg%3E`
+  const std = 20
```
Comment (gruckion) [inline packages/next/src/shared/lib/image-blur-svg.ts:19]: Magic number why 20? Also we should consider renaming std, what is it short for?

Comment (arturbien) [reply packages/next/src/shared/lib/image-blur-svg.ts:19]: Yeah "std" was supposed to stand for "standard deviation" but I agree that it sounds bad now that I think about it 😂

It should be renamed to "blur".

And the blur value is set to 20 because it looks good.
