### PR TITLE
next-swc: fix ssg code elimination when used in render

### LINKED ISSUE #31536: Unwanted code elimination when using a component in `getStaticProps`
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

v14.15.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

-

### Describe the Bug

I'm encountering a runtime error, since Next.js seems to be eliminating a component from a function where it is needed.

It seems to occur when a component is used both on the page and in `getStaticProps`.

```tsx
function PageLayout({children}) {
  return <div style={{background: 'gray'}}>{children}</div>;
}

export default function Index() {
  // ReferenceError: PageLayout is not defined
  return <PageLayout>Index</PageLayout>
}

export function getStaticProps() {
  // When this line is removed, the page no longer breaks
  console.log(PageLayout.name);
  
  return {
    props: {}
  };
}
```

Screenshot 2021-11-17 at 16 05 44

Note that the example is intended to be minimal, in my application the usage of the layout component in `getStaticProps` serves a meaningful purpose. In Next.js 11 the above code works flawlessly.

### Expected Behavior

No runtime error

### To Reproduce

1. Clone https://github.com/amannn/next-compile-bug
2. Follow the reproduction steps in the README

### PR DESCRIPTION
**Pull request by pveyes**
This PR marks all JSXElement AST nodes to make sure that any components used inside both render and SSG exports are not removed

Fixes #31536 

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.4s | ⚠️ +371ms |
| buildDurationCached | 3.1s | 3.1s | ⚠️ +4ms |
| nodeModulesSize | 348 MB | 348 MB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.881 | 2.908 | ⚠️ +0.03 |
| / avg req/sec | 867.86 | 859.71 | ⚠️ -8.15 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.327 | 1.306 | -0.02 |
| /error-in-render avg req/sec | 1884.24 | 1914.1 | +29.86 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.1 kB | 27.1 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 70.9 kB | 70.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.74 kB | 4.74 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.13 kB | 2.13 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| buildDuration | 15.5s | 15.4s | -111ms |
| buildDurationCached | 3.2s | 3.1s | -41ms |
| nodeModulesSize | 348 MB | 348 MB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.878 | 2.882 | 0 |
| / avg req/sec | 868.54 | 867.35 | ⚠️ -1.19 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.322 | 1.327 | 0 |
| /error-in-render avg req/sec | 1890.64 | 1884.03 | ⚠️ -6.61 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.1 kB | 71.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 906 B | 906 B | ✓ |
| image-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | pveyes/next.js swc-fix-ssg-code-elimination | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: abecb0d4ed59ca72b8d1e25b443d5a7dc6c1b3c4

File: packages/next-swc/crates/core/src/next_ssg.rs [hunk 1]
```diff
@@ -143,6 +143,21 @@ impl Fold for Analyzer<'_> {
...
+            JSXElementName::Ident(i) => {
+                self.add_ref(i.to_id());
+            }
+            _ => {}
+        }
+
+        jsx.fold_children_with(self)
+    }
+
+    fn fold_export_default_decl(&mut self, export: ExportDefaultDecl) -> ExportDefaultDecl {
```
Comment (kdy1) [inline packages/next-swc/crates/core/src/next_ssg.rs:157]: This seems like a redudant implementation as default implementation of `fold_export_default_decl` does the exactly same thing.

File: packages/next-swc/crates/core/src/next_ssg.rs [hunk 2]
```diff
@@ -143,6 +143,21 @@ impl Fold for Analyzer<'_> {
         e
     }
 
+    fn fold_jsx_element(&mut self, jsx: JSXElement) -> JSXElement {
+        match &jsx.opening.name {
+            JSXElementName::Ident(i) => {
+                self.add_ref(i.to_id());
+            }
+            _ => {}
```
Comment (kdy1) [inline packages/next-swc/crates/core/src/next_ssg.rs:151]: I think the leftmost identifier of `JSXElementName::JSXMemberExpr` should be added as a ref.

**Review by kdy1 — CHANGES_REQUESTED** [review]

File: packages/next-swc/crates/core/src/next_ssg.rs (hunk 1 above)
Comment (pveyes) [reply packages/next-swc/crates/core/src/next_ssg.rs]: you're right, this doesn't do anything. removed

File: packages/next-swc/crates/core/src/next_ssg.rs (hunk 2 above)
Comment (pveyes) [reply packages/next-swc/crates/core/src/next_ssg.rs:165]: thanks, I've added the fix alongside the updated test. lmk what you think

**Review by kdy1 — APPROVED** [review]
LGTM. Thanks!
