### PR TITLE
fix parallel catch-all route normalization

### LINKED ISSUE #58272: parallel routes: catch all nested under dynamic segment matches to the root
### Link to the code that reproduces this issue

https://github.com/wlechowicz/next14-catchall-repro

### To Reproduce

Caused by #58215, see https://github.com/vercel/next.js/pull/58215#issuecomment-1804319813

1. Start the application with `npm run dev`
2. Observe the error:
```
 ○ Compiling / ...
 ⨯ app\page.tsx
You cannot have two parallel pages that resolve to the same path. Please check /page and /[lang]/@modal/[...catchAll]/page. Refer to the route group docs for more information: https://nextjs.org/docs/app/building-your-application/routing/route-groups
```
3. If the `@modal`, `foo` and `bar` are moved up to the app root (outside of `[lang]`), no such error appears and the `catchAll` closes the "modal" as expected when any `/bar/*` non-intercepted Link is clicked.

### Current vs. Expected behavior

Previous behavior (prior to #58215) was that that `[...catchAll]` was not matching non-intercepted routes at all. See #50284
Current behavior with this change is that error quoted above is thrown at compile time.
Expected behavior is that catch-all matches to the correct parallel route, not root.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:        
  Platform: win32        
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 20.9.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.2-canary.27
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

_No response_

<sub>[NEXT-1808](https://linear.app/vercel/issue/NEXT-1808/parallel-routes-catch-all-nested-under-dynamic-segment-matches-to-the)</sub>

### LINKED ISSUE #58312: Catch-all and root page throws error of conflicting route if the catch-all is inside routegroup with parallel route.
### Link to the code that reproduces this issue

https://github.com/omerman/catchall-routegroup-parallel

### To Reproduce

Start the application, yarn dev, and you'll get an error.

### Current vs. Expected behavior

/ route should render Home,
anything else should render the Catcher.

Please help

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: 7.29.3
Relevant Packages:
  next: 14.0.3-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

_No response_

### LINKED ISSUE #58660: Multiple levels of catch-all routes with intercepted + parallel routes loads the wrong route on intercept, but the correct route on initial page load
### Link to the code that reproduces this issue

https://github.com/augustl/nextjs-intercepting-modal-bug

### To Reproduce

1. Open the home page at localhost:3000/
2. Click either "Show thing 1" or "Show thing 2"
3. Observe the error 

### Current vs. Expected behavior

I expected the click of "Show thing 1" or "Show thing 2" to load the intercepted route, `src/app/@modal/(.)things/[...ids]/page.tsx`. Instead, it attempts to load the top-level catch all route `src/app/[...slug]/page.tsx`, as evident by the error message that refers to a line in that file caused by parameters being null due to the route loading mismatch.

Also observe that when refreshing the page to go directly to localhost:3000/things/1, the page loads correctly and without error.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.4
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

The combination of a top level catch-all route and a catch-all segment in the `/things/[...ids]` route are both needed to trigger this issue. If you remove the top level catch-all `[...slug]`, or change `/things/[...ids]` to something like `/things/[id]`, it works fine.

<sub>[NEXT-1809](https://linear.app/vercel/issue/NEXT-1809/multiple-levels-of-catch-all-routes-with-intercepted-parallel-routes)</sub>

### LINKED ISSUE #59782: Slug parameters in main route is incorrect when using intercepted routes
### Link to the code that reproduces this issue

https://github.com/mastoj/interceptingbug

### To Reproduce

1. Run application 
2. Click the "Click me"
3. Click the "Click stuff (11111111111)"

### Current vs. Expected behavior

*Actual*
After the last click you should be on the intercepted route: http://localhost:3000/stuff/11111111111. The text in read is from the "main" route, but the slug has now turned into a string instead of an array. I print the text that has an issue in red on the screen.

*Expected*
When I am on the intercepted route http://localhost:3000/stuff/11111111111 I would still expect the main route to have the slug as an array property, or at least be consistent.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
Binaries:
  Node: 18.17.0
  npm: 9.6.7
  Yarn: N/A
  pnpm: 8.6.10
Relevant Packages:
  next: 14.0.5-canary.18
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I tested against latest canary, 14.0.5-canary.18,  and also 14.0.4. 

<sub>[NEXT-1910](https://linear.app/vercel/issue/NEXT-1910/slug-parameters-in-main-route-is-incorrect-when-using-intercepted)</sub>

### LINKED ISSUE #59784: Intercepting routes is broken with Catch-all Segments
### Link to the code that reproduces this issue

https://github.com/padupuy/nextgram

### To Reproduce

I try to implement intercepting routes with catch-all segments.
I fork the [nextgram repo](https://github.com/padupuy/nextgram) and i replace the hardcoded photos folder with a dynamic route [...slug] to catch the route photos/[id] to mimic a CMS behviour

1. The result is buggy : behind the photo modal we can see the photo page instead of the grid feed.
2. When the modal is open : the params.slug is equal to [ 'photos2' ] instead of ['photos', 2]

Check the live example here : https://nextgram-three.vercel.app/

Capture d’écran 2023-12-19 à 23 06 30

### Current vs. Expected behavior

The intercepting routes with catch-all segments must work as the "standard" intercepting route , see this example https://nextgram.vercel.app/.  
When the user click on a picture, a modal is open. The grid feed behind should be still displayed. 

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:26 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_X86_64
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.5-canary.18
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

_No response_

<sub>[NEXT-1906](https://linear.app/vercel/issue/NEXT-1906/intercepting-routes-is-broken-with-catch-all-segments)</sub>

### PR DESCRIPTION
**Pull request by ztanner**
### What?
Catch-all routes are being matched to parallel routes which causes issues like an interception route being handled by the wrong page component, or a page component being associated with multiple pages resulting in a "You cannot have two parallel pages that resolve to the same path" build error.

### Why?
#58215 fixed a bug that caused catchall paths to not properly match when used with parallel routes. In other words, a catchall slot wouldn't render on a page that could match that catch all. Or a catchall page wouldn't match a slot. At build time, a normalization step was introduced to take application paths and attempt to perform this matching behavior.

However in it's current form, this causes the errors mentioned above to manifest. To better illustrate the problem, here are a few examples:

Given:
```
{
  '/': [ '/page' ],
  '/[...slug]': [ '/[...slug]/page' ],
  '/items/[...ids]': [ '/items/[...ids]/page' ],
  '/(.)items/[...ids]': [ '/@modal/(.)items/[...ids]/page' ]
}
```

The normalization logic would produce:
```
{
  '/': [ '/page' ],
  '/[...slug]': [ '/[...slug]/page' ],
  '/items/[...ids]': [ '/items/[...ids]/page' ],
  '/(.)items/[...ids]': [ '/@modal/(.)items/[...ids]/page', '/[...slug]/page' ]
}
```
The interception route will now be improperly handled by `[...slug]/page` rather than the interception handler.

Another example, which rather than incorrectly handling a match, will produce a build error:

Given:
```
{
  '/': [ '/(group-b)/page' ],
  '/[...catcher]': [ '/(group-a)/@parallel/[...catcher]/page' ]
}
```

The normalization logic would produce:

```
{
  '/': [ '/(group-b)/page', '/(group-a)/@parallel/[...catcher]/page' ],
  '/[...catcher]': [ '/(group-a)/@parallel/[...catcher]/page' ]
}
```
The parallel catch-all slot is now part of `/`. This means when building the loader tree, two `children` parallel segments (aka page components) will be found when hitting `/`, which is an error. 

The error that was added here was originally intended to help catch scenarios like:
`/app/(group-a)/page` and `/app/(group-b)/page`. However it also throws for parallel slots, which isn't necessarily an error (especially since the normalization logic will push potential matches). 

### How?
There are two small fixes in this PR, the rest are an abundance of e2e tests to help prevent regressions. 

- When normalizing catch-all routes, we will not attempt to push any page entrypoints for interception routes. These should already have all the information they need in `appPaths`.
- Before throwing the error about duplicate page segments in `next-app-loader`, we check to see if it's because we already matched a page component but we also detected a parallel slot that would have matched the page slot. In this case, we don't error, since the app can recover from this. 
- Loading a client reference manifest shouldn't throw a cryptic require error. `loadClientReferenceManifest` is already potentially returning undefined, so this case should already be handled gracefully

Separately, we'll need to follow-up on the Turbopack side to:
- Make sure the duplicate matching matches the Webpack implementation (I believe Webpack is sorting, but Turbopack isn't)
- Implement #58215 in Turbopack. Once this is done, we should expect the tests added in this PR to start failing.

Fixes #58272
Fixes #58660
Fixes #58312
Fixes #59782
Fixes #59784

Closes NEXT-1809

### CODE REVIEW

**Comment by ztanner** [comment]
Current dependencies on/for this PR:
* `canary`
  * **PR #59791** <a href="https://app.graphite.dev/github/pr/vercel/next.js/59791?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/59791?utm_source=stack-comment).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 222925b69a15a7c0019b51f99907396da11442a4

`pnpm test test/integration/telemetry/test/page-features.test.js` 
- page features telemetry > detects --turbo correctly for `next dev` stopped

<details>
<summary>Expand output</summary>

  ● page features telemetry › detects --turbo correctly for `next dev` stopped

    TIMED OUT: /NEXT_CLI_SESSION_STOPPED/

    [telemetry] {
      "eventName": "NEXT_CLI_SESSION_STARTED",
      "payload": {
        "nextVersion": "14.0.5-canary.19",
        "nodeVersion": "v18.17.0",
        "cliCommand": "dev",
        "isSrcDir": false,
        "hasNowJson": false,
        "isCustomServer": false,
        "hasNextConfig": false,
        "buildTarget": "default",
        "hasWebpackConfig": false,
        "hasBabelConfig": false,
        "imageEnabled": true,
        "imageFutureEnabled": true,
        "basePathEnabled": false,
        "i18nEnabled": false,
        "locales": null,
        "localeDomainsCount": null,
        "localeDetectionEnabled": null,
        "imageDomainsCount": 0,
        "imageRemotePatternsCount": 0,
        "imageSizes": "16,32,48,64,96,128,256,384",
        "imageLoader": "default",
        "imageFormats": "image/webp",
        "nextConfigOutput": null,
        "trailingSlashEnabled": false,
        "reactStrictMode": false,
        "webpackVersion": 5,
        "turboFlag": true,
        "appDir": true,
        "pagesDir": true
      }
    }


    undefined

      626 |
      627 |   if (hardError) {
    > 628 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      629 |   }
      630 |   return false
      631 | }

      at check (lib/next-test-utils.ts:628:11)
      at Object.<anonymous> (integration/telemetry/test/page-features.test.js:105:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-fix_parallel_catch-all_route_normalization | Change |
| - | - | - | - |
| buildDuration | 12.9s | 12.7s | N/A |
| buildDurationCached | 7s | 6.2s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +1.22 kB |
| nextStartRea..uration (ms) | 425ms | 423ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-fix_parallel_catch-all_route_normalization | Change |
| - | - | - | - |
| 170-HASH.js gzip | 26.8 kB | 26.9 kB | N/A |
| 199.HASH.js gzip | 181 B | 185 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 240 B | 241 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-fix_parallel_catch-all_route_normalization | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-fix_parallel_catch-all_route_normalization | Change |
| - | - | - | - |
| _app-HASH.js gzip | 195 B | 194 B | N/A |
| _error-HASH.js gzip | 183 B | 182 B | N/A |
| amp-HASH.js gzip | 501 B | 501 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 255 B | ✓ |
| head-HASH.js gzip | 349 B | 350 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.6 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 309 B | N/A |
| script-HASH.js gzip | 384 B | 384 B | ✓ |
| withRouter-HASH.js gzip | 307 B | 306 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-fix_parallel_catch-all_route_normalization | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-fix_parallel_catch-all_route_normalization | Change |
| - | - | - | - |
| index.html gzip | 529 B | 526 B | N/A |
| link.html gzip | 542 B | 539 B | N/A |
| withRouter.html gzip | 523 B | 523 B | ✓ |
| Overall change | 523 B | 523 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-fix_parallel_catch-all_route_normalization | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.7 kB | 93.7 kB | N/A |
| page.js gzip | 146 kB | 146 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-fix_parallel_catch-all_route_normalization | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 626 B | 624 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-fix_parallel_catch-all_route_normalization | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 94.1 kB | 94.1 kB | ✓ |
| app-page-tur..prod.js gzip | 94.8 kB | 94.8 kB | ✓ |
| app-page-tur..prod.js gzip | 89.4 kB | 89.4 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.7 kB | 88.7 kB | ✓ |
| app-route-ex...dev.js gzip | 24 kB | 24 kB | ✓ |
| app-route-ex..prod.js gzip | 16.6 kB | 16.6 kB | ✓ |
| app-route-tu..prod.js gzip | 16.6 kB | 16.6 kB | ✓ |
| app-route-tu..prod.js gzip | 16.2 kB | 16.2 kB | ✓ |
| app-route.ru...dev.js gzip | 23.4 kB | 23.4 kB | ✓ |
| app-route.ru..prod.js gzip | 16.2 kB | 16.2 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| Overall change | 931 kB | 931 kB | ✓ |

</details>

</details>
Commit: 222925b69a15a7c0019b51f99907396da11442a4

File: packages/next/src/server/future/route-matcher-providers/dev/dev-app-page-route-matcher-provider.ts [hunk 1]
```diff
@@ -59,6 +59,11 @@ export class DevAppPageRouteMatcherProvider extends FileCacheRouteMatcherProvide
 
     normalizeCatchAllRoutes(appPaths)
 
+    // Make sure to sort parallel routes to make the result deterministic.
+    appPaths = Object.fromEntries(
+      Object.entries(appPaths).map(([k, v]) => [k, v.sort()])
+    )
```
Comment (ztanner) [inline packages/next/src/server/future/route-matcher-providers/dev/dev-app-page-route-matcher-provider.ts:65]: noticed this was in `build` but not `dev`, so copied from [here](https://github.com/vercel/next.js/blob/canary/packages/next/src/build/entries.ts#L552-L555)

File: test/e2e/app-dir/parallel-routes-and-interception/parallel-routes-and-interception.test.ts [hunk 2]
```diff
@@ -187,38 +186,6 @@ createNextDescribe(
         expect(pageText).toContain('parallel/(new)/@baz/nested/page')
       })
 
-      it('should throw an error when a route groups causes a conflict with a parallel segment', async () => {
```
Comment (ztanner) [inline test/e2e/app-dir/parallel-routes-and-interception/parallel-routes-and-interception.test.ts:190]: this test was reworked and moved [here](https://github.com/vercel/next.js/pull/59791/files#diff-0d5e642ee398c97861073a49292d556fed32e72bd738cdc793509572e89409b3)

File: packages/next/src/server/load-components.ts [hunk 3]
```diff
@@ -86,11 +86,11 @@ async function loadClientReferenceManifest(
   manifestPath: string,
   entryName: string
 ): Promise<ClientReferenceManifest | undefined> {
-  process.env.NEXT_MINIMAL
-    ? // @ts-ignore
-      __non_webpack_require__(manifestPath)
-    : require(manifestPath)
   try {
+    process.env.NEXT_MINIMAL
```
Comment (feedthejim) [inline packages/next/src/server/load-components.ts:90]: What is this fixing?

File: packages/next/src/server/future/route-matcher-providers/dev/dev-app-page-route-matcher-provider.ts (hunk 1 above)
Comment (feedthejim) [reply packages/next/src/server/future/route-matcher-providers/dev/dev-app-page-route-matcher-provider.ts:65]: leaning into that abstraction, is there some place where we could have added it only once?

File: packages/next/src/build/normalize-catchall-routes.test.ts [hunk 4]
```diff
@@ -0,0 +1,99 @@
+import { normalizeCatchAllRoutes } from './normalize-catchall-routes'
+
+describe('normalizeCatchallRoutes', () => {
```
Comment (feedthejim) [inline packages/next/src/build/normalize-catchall-routes.test.ts:3]: beautiful

**Review by feedthejim — APPROVED** [review]

File: packages/next/src/server/load-components.ts (hunk 3 above)
Comment (ztanner) [reply packages/next/src/server/load-components.ts:90]: Since I'm no longer throwing a build error if there are two matching `children` parallel segments, appPaths will technically contain 2 pages and will throw an error when attempting to `require` it because the `FlightManifestPlugin` will have only generated a manifest for a single entrypoint. Since the other entry won't be used it seems safe to ignore, and `loadClientReferenceManifest` could potentially return undefined so I just lifted the try a bit higher.
