### PR TITLE
Omit svg static imports if custom webpack config is defined

### LINKED ISSUE #25950: Webpack: @svgr/webpack broken since 10.2.4-canary.5
### What version of Next.js are you using?

10.2.4-canary.12

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

Node

### What operating system are you using?

Ubuntu

### How are you deploying your application?

Not yet

### Describe the Bug

In order to import SVG files as React component we are currently extending the webpack config with

```js
webpack(config) {
  config.module.rules.push({
    test: /\.svg$/,
    issuer: /\.(js|ts)x?$/,
    use: ['@svgr/webpack']
  });

  return config;
},
```

In the latest canary this seems to be broken and leads to:

```
error - ./public/icons/bars.svg
TypeError: unsupported file type: undefined (file: undefined)
```

See the codesandbox for a minimal reproduction.

### Expected Behavior

I expect the import to work and to render a React component.

### To Reproduce

https://codesandbox.io/s/polished-fire-z8w39

### LINKED ISSUE #26130: SVGR fails to load SVGs with Next 11
# **UPDATE**

## A temporary solution that seems to work and does not disable Webpack 5
If you find any issues with this solution, please tag me @scottagirs to update as appropriate.
By @dohomi

```javascript
  webpack (config) {
    const fileLoaderRule = config.module.rules.find(rule => rule.test && rule.test.test('.svg'))
    fileLoaderRule.exclude = /\.svg$/
    config.module.rules.push({
      test: /\.svg$/,
      loader: require.resolve('@svgr/webpack')
    })
    return config
  }
```
--- 
### What version of Next.js are you using?

Next 11.0.0

### What version of Node.js are you using?

14.x

### What browser are you using?

Chrome, Brave

### What operating system are you using?

macOS 11.4

### How are you deploying your application?

localhost atm

### Describe the Bug

https://discord.com/channels/752553802359505017/752668543891276009/854396809497673788

After upgrading from 10.x Next.js with webpack 4 config, to Nextjs 11, application fails to build with the below errors:
```
error - ./icon.svg
TypeError: unsupported file type: undefined (file: undefined)
```
Screen Shot 2021-06-15 at 1 12 25 PM

## Full stack trace when trying to load the app (open in browser tab)
<details><summary><span>----- Expand to view -----</span></summary>
<pre>
Error: Cannot find module '/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/.next/server/pages-manifest.json'
Require stack:
- /Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/next-server/server/require.js
- /Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/next-server/server/load-components.js
- /Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/next-server/server/api-utils.js
- /Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/next-server/server/next-server.js
- /Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/server/next.js
- /Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/server/lib/start-server.js
- /Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/cli/next-dev.js
- /Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.mod._resolveFilename (/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/build/webpack/require-hook.js:4:1855)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at getPagePath (/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/next-server/server/require.js:1:735)
    at requirePage (/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/next-server/server/require.js:1:1397)
    at loadComponents (/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/next-server/server/load-components.js:1:1289)
    at DevServer.findPageComponents (/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/next-server/server/next-server.js:77:296)
    at DevServer.renderErrorToHTML (/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/next-server/server/next-server.js:139:209) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/next-server/server/require.js',
    '/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/next-server/server/load-components.js',
    '/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/next-server/server/api-utils.js',
    '/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/server/next.js',
    '/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/server/lib/start-server.js',
    '/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/cli/next-dev.js',
    '/Users/scottagirs/workspace/iJS/ijs.to/iJStoFE/node_modules/next/dist/bin/next'
  ]
}
</pre>
</details>

### To Reproduce

Upgrade to Next 11 and add `next.config.js`

```javascript
module.exports = {
  webpack(config, options) {
    config.module.rules.push({
      test: /\.svg$/,
      use: ['@svgr/webpack'],
    });

    return config;
  },
};
```

in `package.json`
```
"@svgr/webpack": "^5.5.0",
"next": "^11.0.0",
"react": "^17.0.2",
"react-dom": "^17.0.2",
```

### LINKED ISSUE #26176: [next-image-loader] "TypeError: Invalid SVG" when importing SVG sprites
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

-

### What operating system are you using?

macOS

### How are you deploying your application?

Other platform

### Describe the Bug

When a svg sprite (like [this](https://s1.immobiliare.it/_next/static/images/logo-header-6b37a0684c36d0a02e8fef606099adcc.svg) one) is imported "TypeError: Invalid SVG" is thrown on build.

### Expected Behavior

The import should return the StaticImageData with an empty placeholder without throwing an error.

### To Reproduce

1. Start a new next project
2. Download [this](https://s1.immobiliare.it/_next/static/images/logo-header-6b37a0684c36d0a02e8fef606099adcc.svg) image
3. Import the svg in a javascript module (`import logo from "./logo-header.svg"`)
4. Run the build with `next build`

### LINKED ISSUE #26196: <image/> tag error in version 11.0.0
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

v14.15.3

### What browser are you using?

chrome

### What operating system are you using?

Windows

### How are you deploying your application?

none

### Describe the Bug

Hi,
I am getting a problem with an  tag when upgrading from 10.2.3 to 11.0.0 while changing nothing in my code.

error on the image src
```
Type 'StaticImageData' is not assignable to type 'string'.ts(2322)
index.d.ts(2145, 9): The expected type comes from property 'src' which is declared here on type 'DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>'
```
error from the console
```
error - ./public/images/logo.png
TypeError: unsupported file type: undefined (file: undefined)
```
my simple image tag
```
import logo from "../../../public/images/logo.png";
<img
src={logo}
alt="Picture of the author"
className="h-full"
/>

```

### Expected Behavior

I expected to have no problem when upgrading to 11.0.0

### To Reproduce

use an `` tag with a local image with version 10.2.3 and upgrade to version 11.0.0

### PR DESCRIPTION
**Pull request by styfle**
This PR does a couple things:

1. Omit svg static imports if the user has defined custom webpack config with svg rule
2. Change TS type to `any` for svg imports to avoid conflicts with other plugins

The idea is that some users want to use `next/image` with static imports for most image types but not for svg and instead inline those images with a plugin.

- Fixes #25950  
- Fixes #26130 
- Fixes #26176 
- Fixes #26196 
- Fixes #26067 

## Bug

- [x] Related issues linked using Fixes #26130 
- [x] Integration tests added

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| buildDuration | 14s | 13.9s | -52ms |
| buildDurationCached | 3.4s | 3.3s | -68ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +693 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.603 | 2.575 | -0.03 |
| / avg req/sec | 960.41 | 970.94 | +10.53 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.631 | 1.608 | -0.02 |
| /error-in-render avg req/sec | 1533.12 | 1554.78 | +21.66 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| buildDuration | 15.8s | 15.8s | ⚠️ +12ms |
| buildDurationCached | 4.5s | 4.5s | ⚠️ +65ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +693 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ⚠️ +2 B |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | ⚠️ +2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| buildDuration | 12.2s | 12.4s | ⚠️ +152ms |
| buildDurationCached | 4.9s | 4.9s | -66ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +693 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.583 | 2.559 | -0.02 |
| / avg req/sec | 967.68 | 976.94 | +9.26 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.59 | 1.63 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1572.06 | 1533.57 | ⚠️ -38.49 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 63.8 kB | 63.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.28 kB | 9.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| index.html gzip | 567 B | 567 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 561 B | 561 B | ✓ |
| Overall change | 1.71 kB | 1.71 kB | ✓ |

</details>

</details>
Commit: 38f97a90bfb13d5347be5c3d89bc44a9c37b1b8a

File: packages/next/build/webpack-config.ts [hunk 1]
```diff
@@ -1007,7 +1007,12 @@ export default async function getBaseWebpackConfig(
         ...(!config.images.disableStaticImages && isWebpack5
           ? [
               {
-                test: /\.(png|svg|jpg|jpeg|gif|webp|ico|bmp)$/i,
+                // Exclude svg if the user defined a custom webpack config
+                // because it might include the `@svgr/webpack` plugin or
+                // the `babel-plugin-inline-react-svg` plugin.
+                test: config.webpack
```
Comment (ijjk) [inline packages/next/build/webpack-config.ts:1013]: Should we look for the specific configuration that matches these imports similar to how we check for existing CSS configuration and disable the built-in config if custom config is detected?

Comment (styfle) [reply packages/next/build/webpack-config.ts:1013]: @ijjk Yeah that sounds good. How does this look?

```
const match = config.module.rules.find(rule => rule.test && rule.test.test('.svg'))
```

Comment (ijjk) [reply packages/next/build/webpack-config.ts:1013]: Yeah like that, here's [the CSS check](https://github.com/vercel/next.js/blob/51022d5819c382831a65f963dcf4e69f46072bc9/packages/next/build/webpack-config.ts#L1562-L1565) for reference

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| buildDuration | 10.8s | 10.6s | -202ms |
| buildDurationCached | 2.6s | 2.6s | ⚠️ +1ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +13 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.889 | 1.95 | ⚠️ +0.06 |
| / avg req/sec | 1323.36 | 1282.14 | ⚠️ -41.22 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.109 | 1.042 | -0.07 |
| /error-in-render avg req/sec | 2253.34 | 2398.31 | +144.97 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| buildDuration | 12.1s | 11.9s | -257ms |
| buildDurationCached | 3.5s | 3.4s | -40ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +13 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| buildDuration | 9.9s | 9.8s | -139ms |
| buildDurationCached | 3.8s | 3.8s | ⚠️ +46ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +13 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.076 | 1.993 | -0.08 |
| / avg req/sec | 1204.35 | 1254.54 | +50.19 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.151 | 1.143 | -0.01 |
| /error-in-render avg req/sec | 2172.27 | 2186.82 | +14.55 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 63.8 kB | 63.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.28 kB | 9.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| index.html gzip | 567 B | 567 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 561 B | 561 B | ✓ |
| Overall change | 1.71 kB | 1.71 kB | ✓ |

</details>

</details>
Commit: 2c1b9e5a30146b80960f9e5612f11ff97e9134c7

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 2c1b9e5a30146b80960f9e5612f11ff97e9134c7

**test/integration/typescript-version-warning/test/index.test.js** 
- Minimum TypeScript Warning > should not show warning during next build with new version
- Minimum TypeScript Warning > should not show warning during next dev with new version

<details>
<summary>Expand output</summary>

  ● Minimum TypeScript Warning › should not show warning during next build with new version

    expect(received).toContain(expected) // indexOf

    Expected substring: "Minimum recommended TypeScript version is"
    Received string:    "info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
    info  - Checking validity of types...
    info  - Creating an optimized production build...
    info  - Compiled successfully
    info  - Collecting page data...
    info  - Generating static pages (0/3)
    info  - Generating static pages (3/3)
    info  - Finalizing page optimization...·
    Page                             Size     First Load JS
    ┌ ○ /                            268 B            64 kB
    └ ○ /404                         3.17 kB        66.9 kB
    + First Load JS shared by all    63.7 kB
      ├ chunks/framework.2f18f3.js   42 kB
      ├ chunks/main.f10875.js        20.1 kB
      ├ chunks/pages/_app.0c8d78.js  801 B
      └ chunks/webpack.43375c.js     760 B·
    λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
    ○  (Static)  automatically rendered as static HTML (uses no initial props)
    ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
       (ISR)     incremental static regeneration (uses revalidate in getStaticProps)·
    "

      47 |       join(appDir, 'node_modules/typescript')
      48 |     )
    > 49 |     expect(res.stdout + res.stderr).toContain(
         |                                     ^
      50 |       'Minimum recommended TypeScript version is'
      51 |     )
      52 |   })

      at Object.<anonymous> (integration/typescript-version-warning/test/index.test.js:49:37)

  ● Minimum TypeScript Warning › should not show warning during next dev with new version

    expect(received).toContain(expected) // indexOf

    Expected substring: "Minimum recommended TypeScript version is"
    Received string:    "ready - started server on 0.0.0.0:33021, url: http://localhost:33021
    info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
    event - compiled successfully
    "

      72 |     )
      73 |
    > 74 |     expect(output).toContain('Minimum recommended TypeScript version is')
         |                    ^
      75 |   })
      76 | })
      77 |

      at Object.<anonymous> (integration/typescript-version-warning/test/index.test.js:74:20)

</details>

File: packages/next/build/webpack-config.ts (hunk 1 above)
Comment (styfle) [reply packages/next/build/webpack-config.ts]: Done, thanks! 👍

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.4s | ⚠️ +259ms |
| buildDurationCached | 3.4s | 3.4s | -28ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +1.37 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.701 | 2.62 | -0.08 |
| / avg req/sec | 925.56 | 954.04 | +28.48 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.668 | 1.667 | 0 |
| /error-in-render avg req/sec | 1498.52 | 1500.08 | +1.56 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 330 B | ⚠️ +1 B |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 392 B | ⚠️ +1 B |
| Overall change | 391 B | 392 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -7,7 +7,7 @@ self.__BUILD_MANIFEST = {
   "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-7f1c918feab47667356f.js"],
   "/css": [
     "static\u002Fcss\u002F59de118426c393f58653.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-fc196f2ef04da4c7630f.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-9892f9ef9b6f15db85a5.js"
   ],
   "/hooks": [
     "static\u002Fchunks\u002Fpages\u002Fhooks-4e38b05900fed34fcf34.js"
```
</details>
<details>
<summary>Diff for <strong>css-HASH.js</strong></summary>

```diff
@@ -12,7 +12,7 @@
         5893
       );
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        5964
+        9662
       );
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         _css_module_css__WEBPACK_IMPORTED_MODULE_1__
@@ -47,7 +47,7 @@
       /***/
     },
 
-    /***/ 5964: /***/ function(module) {
+    /***/ 9662: /***/ function(module) {
       // extracted by mini-css-extract-plugin
       module.exports = { helloWorld: "css_helloWorld__2Fhmt" };
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| buildDuration | 16s | 16s | ⚠️ +14ms |
| buildDurationCached | 4.6s | 4.6s | -39ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +1.37 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 330 B | ⚠️ +1 B |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 392 B | ⚠️ +1 B |
| Overall change | 391 B | 392 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | -2 B |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ⚠️ +2 B |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ⚠️ +2 B |
| Overall change | 105 kB | 105 kB | ⚠️ +2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.4s | -133ms |
| buildDurationCached | 5.2s | 5.1s | -69ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +1.37 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.705 | 2.631 | -0.07 |
| / avg req/sec | 924.21 | 950.33 | +26.12 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.653 | 1.647 | -0.01 |
| /error-in-render avg req/sec | 1512.68 | 1518.33 | +5.65 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 63.8 kB | 63.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.28 kB | 9.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| index.html gzip | 567 B | 567 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 561 B | 561 B | ✓ |
| Overall change | 1.71 kB | 1.71 kB | ✓ |

</details>

</details>
Commit: bbe6edf4d1cf639d990b88032117a4b7cfb4cfcf

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.5s | ⚠️ +287ms |
| buildDurationCached | 3.5s | 3.5s | -24ms |
| nodeModulesSize | 46.4 MB | 49.2 MB | ⚠️ +2.79 MB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.547 | 2.554 | ⚠️ +0.01 |
| / avg req/sec | 981.48 | 978.88 | ⚠️ -2.6 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.498 | 1.457 | -0.04 |
| /error-in-render avg req/sec | 1668.94 | 1715.86 | +46.92 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 330 B | ⚠️ +1 B |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 392 B | ⚠️ +1 B |
| Overall change | 391 B | 392 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -7,7 +7,7 @@ self.__BUILD_MANIFEST = {
   "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-7f1c918feab47667356f.js"],
   "/css": [
     "static\u002Fcss\u002F59de118426c393f58653.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-fc196f2ef04da4c7630f.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-9892f9ef9b6f15db85a5.js"
   ],
   "/hooks": [
     "static\u002Fchunks\u002Fpages\u002Fhooks-4e38b05900fed34fcf34.js"
```
</details>
<details>
<summary>Diff for <strong>css-HASH.js</strong></summary>

```diff
@@ -12,7 +12,7 @@
         5893
       );
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
-        5964
+        9662
       );
       /* harmony import */ var _css_module_css__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
         _css_module_css__WEBPACK_IMPORTED_MODULE_1__
@@ -47,7 +47,7 @@
       /***/
     },
 
-    /***/ 5964: /***/ function(module) {
+    /***/ 9662: /***/ function(module) {
       // extracted by mini-css-extract-plugin
       module.exports = { helloWorld: "css_helloWorld__2Fhmt" };
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| buildDuration | 16.2s | 16.4s | ⚠️ +190ms |
| buildDurationCached | 4.8s | 4.7s | -45ms |
| nodeModulesSize | 46.4 MB | 49.2 MB | ⚠️ +2.79 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 330 B | ⚠️ +1 B |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 392 B | ⚠️ +1 B |
| Overall change | 391 B | 392 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| buildDuration | 12.9s | 13s | ⚠️ +63ms |
| buildDurationCached | 5.1s | 5.1s | -51ms |
| nodeModulesSize | 46.4 MB | 49.2 MB | ⚠️ +2.79 MB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.589 | 2.633 | ⚠️ +0.04 |
| / avg req/sec | 965.49 | 949.65 | ⚠️ -15.84 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.583 | 1.549 | -0.03 |
| /error-in-render avg req/sec | 1579.42 | 1614.41 | +34.99 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 63.8 kB | 63.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.28 kB | 9.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix-issue-26130 | Change |
| - | - | - | - |
| index.html gzip | 567 B | 567 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 561 B | 561 B | ✓ |
| Overall change | 1.71 kB | 1.71 kB | ✓ |

</details>

</details>
Commit: ba64522341e43778ecc52e794a12c13f6990cf25

**Comment by snc** [comment]
For me `hasSvg` check is unfortunately false, because I define multiple rules based on the path of the images (I need different svgo settings):

```
const iconsRule = {
  test: /assets\/icons\/.*\.svg$/,
  use: [
    {
      loader: '@svgr/webpack',
      options: {
        typescript: false,
        dimensions: false,
        prettier: true,
        svgo: true,
        svgoConfig: {
          plugins: [
            {
              removeAttrs: {
                attrs: '*:(stroke|fill(-rule)?):((?!^none$).)*',
              },
            },
          ],
        },
      },
    },
  ],
}

const defaultRule = {
  test: /assets\/svg\/.*\.svg$/,
  use: [
    {
      loader: '@svgr/webpack',
      options: {
        typescript: false,
        dimensions: false,
        prettier: true,
        svgo: true,
      },
    },
  ],
}
```

Any idea how this could be supported? In NextJS v11.0.0 we had access to the rule in next.config.js to alter it.

**Comment by styfle** [comment]
See #26130 for workaround solutions

**Comment by snc** [comment]
@styfle I know this workaround, but this does not work anymore since next@11.0.1-canary.4, because the rule does not exists yet when running the `webpack` from `next.config.js`.

**Comment by styfle** [comment]
I see. I created PR #26548 to solve that use case, thanks!

**Comment by snc** [comment]
Thanks, with v11.0.2-canary.0 the workaround works again.

**Comment by buesing** [comment]
Hey, I think this broke my svg setup. I use typescript. Relevant `next.config.js`:
```
        config.module.rules.push({
          test: /\.svg$/,
          use: [
            {
              loader: "@svgr/webpack",
              options: {
                svgoConfig: {
                  plugins: {
                    removeViewBox: false,
                    removeDimensions: true,
                  },
                },
              },
            },
          ],
        })
```
and my `next-env.d.ts` used to look like this:
```
/// <reference types="next" />
/// <reference types="next/types/global" />

declare module "*.svg" {
  const content: any
  export default content
}
```
But after upgrading to next@11.0.1, the `svg` block is automatically removed during build, and I'm getting the error:
```
Type error: Cannot find module '@assets/illustrations/icon.svg' or its corresponding type declarations.
```
 Any ideas?

**Comment by styfle** [comment]
@buesing Try `yarn add next@canary`

**Comment by buesing** [comment]
@styfle just checked, getting the same error.

**Comment by snc** [comment]
@buesing You still have to remove the `.svg` handling from next-image-loader before you push your custom rule:

```
// remove .svg from next-image-loader
const fileLoaderRule = config.module.rules.find(
  (rule) => rule.test && rule.test.test('.svg')
)
fileLoaderRule.exclude = /\.svg$/

// add custom rules
config.module.rules.push(...svgrRules)
```
