### PR TITLE
fix: support --cache-strategy ESLint argument (fixes #29926)

### LINKED ISSUE #29926: Eslint's --cache-strategy argument is not supported
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

next start

### Describe the Bug

`--cache-strategy` is an argument introduced in ESLint [v7.21.0](https://github.com/eslint/eslint/commit/08ae31e539e381cd0eabf6393fa5c20f1d59125f), which can be set to either `content` or `metadata`. Before its addition, the default behavior was metadata, which doesn't help in CI context where the repository is cloned every time (the modification date of all the files are is to the clone time).
Using the `content` value for the argument, we can have an ESLint cache that works in CI.

Unfortunately, next doesn't support this argument yet, ie we can't pass it down to ESLint through `next lint`.

### Expected Behavior

No error when using `--cache-strategy` argument

### To Reproduce

Run in project root:
```
> yarn run next lint --cache --cache-strategy content --cache-location .cicache/eslint/.cache.json
```
Output:
```
yarn run v1.22.10
$ Path\to\project\node_modules\.bin\next lint --cache --cache-strategy content --cache-location .cicache/eslint/.cache.json
Unknown or unexpected option: --cache-strategy
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### PR DESCRIPTION
**Pull request by OKinane**
Fixes #29926 

## Bug

- [X] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

### CODE REVIEW

**Review by housseindjirdeh — COMMENTED** [review]
Thanks for this! Would it be possible to add an integration test for this flag similar to how we added one for [`--cache-location`](https://github.com/vercel/next.js/blob/canary/test/integration/eslint/test/index.test.js#L501-L508)?

**Comment by styfle** [comment]
Take a look at this test for an example 

https://github.com/vercel/next.js/blob/c8f25ba70b3fc17bc2ae26cf3f8bc036b0b5e323/test/integration/eslint/test/index.test.js#L530-L537

File: packages/next/cli/next-lint.ts [hunk 1]
```diff
@@ -134,6 +136,7 @@ const nextLint: cliCommand = async (argv) => {
         Caching:
           --no-cache                     Disable caching
           --cache-location path::String  Path to the cache file or directory - default: .eslintcache
+          --cache-strategy String        Strategy to use for detecting changed files in the cache - either: metadata or content - default: metadata
```
Comment (styfle) [inline packages/next/cli/next-lint.ts:139]:
```suggestion
          --cache-strategy String        Strategy to use for detecting changed files in the cache, either metadata or content - default: metadata
```

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 6e10258fbf8c5e3a62a964eaee98d6051af42e2b

**test/development/basic/hmr.test.ts** 
- basic HMR > Error Recovery > should recover after exporting an invalid page
- basic HMR > Error Recovery > should recover after undefined exported as default

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should recover after exporting an invalid page

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `basic HMR Error Recovery should recover after exporting an invalid page 1`

    - Snapshot  - 3
    + Received  + 1

       1 of 1 unhandled error
    - Server Error
    + Unhandled Runtime Error

      Error: The default export is not a React Component in page: "/hmr/about5"
    -
    - This error happened while generating the page. Any console logs will be displayed in the terminal window.

      502 |
      503 |         expect(await hasRedbox(browser)).toBe(true)
    > 504 |         expect(await getRedboxHeader(browser)).toMatchInlineSnapshot(`
          |                                                ^
      505 |           " 1 of 1 unhandled error
      506 |           Server Error
      507 |

      at Object.<anonymous> (development/basic/hmr.test.ts:504:48)

  ● basic HMR › Error Recovery › should recover after undefined exported as default

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `basic HMR Error Recovery should recover after undefined exported as default 1`

    - Snapshot  - 3
    + Received  + 1

       1 of 1 unhandled error
    - Server Error
    + Unhandled Runtime Error

      Error: The default export is not a React Component in page: "/hmr/about7"
    -
    - This error happened while generating the page. Any console logs will be displayed in the terminal window.

      614 |         await next.patchFile(aboutPage, aboutContent)
      615 |
    > 616 |         if (browser) {
          |                       ^
      617 |           await check(
      618 |             () => getBrowserBodyText(browser),
      619 |             /This is the about page/

      at Object.<anonymous> (development/basic/hmr.test.ts:616:23)

</details>

**Review by styfle — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| buildDuration | 22.4s | 20.3s | -2.2s |
| buildDurationCached | 4.2s | 4.6s | ⚠️ +369ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +315 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.73 | 3.376 | -0.35 |
| / avg req/sec | 670.23 | 740.62 | +70.39 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.892 | 1.791 | -0.1 |
| /error-in-render avg req/sec | 1321.06 | 1396.11 | +75.05 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| index.html gzip | 521 B | 521 B | ✓ |
| link.html gzip | 533 B | 533 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| buildDuration | 23.6s | 24.3s | ⚠️ +707ms |
| buildDurationCached | 4.6s | 4.6s | ⚠️ +33ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +315 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.578 | 3.662 | ⚠️ +0.08 |
| / avg req/sec | 698.79 | 682.76 | ⚠️ -16.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.853 | 1.853 | ✓ |
| /error-in-render avg req/sec | 1349.39 | 1349.06 | ⚠️ -0.33 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| index.html gzip | 521 B | 521 B | ✓ |
| link.html gzip | 534 B | 534 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: 9a5e883f1a9806e3ae33e083dfb0545bffc918df

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| buildDuration | 18.4s | 18.7s | ⚠️ +271ms |
| buildDurationCached | 3.9s | 3.9s | -38ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +327 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.947 | 2.972 | ⚠️ +0.02 |
| / avg req/sec | 848.27 | 841.1 | ⚠️ -7.17 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.358 | 1.375 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1840.86 | 1818.09 | ⚠️ -22.77 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| index.html gzip | 521 B | 521 B | ✓ |
| link.html gzip | 533 B | 533 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| buildDuration | 20.4s | 19.8s | -586ms |
| buildDurationCached | 4s | 4s | -12ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +327 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.996 | 2.871 | -0.12 |
| / avg req/sec | 834.45 | 870.83 | +36.38 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.395 | 1.374 | -0.02 |
| /error-in-render avg req/sec | 1792.39 | 1818.91 | +26.52 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| index.html gzip | 521 B | 521 B | ✓ |
| link.html gzip | 534 B | 534 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: c9515133fb29f65218e6a4cac55ab86067ab1e04

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c9515133fb29f65218e6a4cac55ab86067ab1e04

**test/integration/preload-viewport/test/index.test.js** 
- Prefetching Links in viewport > should not prefetch already loaded scripts

<details>
<summary>Expand output</summary>

  ● Prefetching Links in viewport › should not prefetch already loaded scripts

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      397 |     expect(hrefs).toEqual([...new Set(hrefs)])
      398 |
    > 399 |     // Verify encoding
          |     ^
      400 |     expect(hrefs.some((e) => e.includes(`%5Bhello%5D-`))).toBe(true)
      401 |   })
      402 |

      at Object.<anonymous> (integration/preload-viewport/test/index.test.js:399:5)

</details>

**Comment by OKinane** [comment]
All failed tests seem unrelated to my changes. Do you confirm @styfle @housseindjirdeh ?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| buildDuration | 20.9s | 20.5s | -394ms |
| buildDurationCached | 4.2s | 4.2s | ⚠️ +35ms |
| nodeModulesSize | 332 MB | 332 MB | ⚠️ +339 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.382 | 3.372 | -0.01 |
| / avg req/sec | 739.1 | 741.44 | +2.34 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.569 | 1.534 | -0.03 |
| /error-in-render avg req/sec | 1593.5 | 1630.24 | +36.74 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| buildDuration | 22.4s | 22.1s | -262ms |
| buildDurationCached | 4.2s | 4.2s | ⚠️ +85ms |
| nodeModulesSize | 332 MB | 332 MB | ⚠️ +339 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.335 | 3.368 | ⚠️ +0.03 |
| / avg req/sec | 749.53 | 742.34 | ⚠️ -7.19 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.569 | 1.569 | ✓ |
| /error-in-render avg req/sec | 1593.11 | 1593.56 | +0.45 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| index.html gzip | 521 B | 521 B | ✓ |
| link.html gzip | 534 B | 534 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: b3b75e16d8f01f80d5717e4464399b26ee6a401a

**Review by styfle — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| buildDuration | 17.6s | 17.7s | ⚠️ +86ms |
| buildDurationCached | 3.5s | 3.6s | ⚠️ +35ms |
| nodeModulesSize | 332 MB | 332 MB | ⚠️ +340 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.888 | 2.857 | -0.03 |
| / avg req/sec | 865.58 | 875.17 | +9.59 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.352 | 1.391 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1849.11 | 1796.95 | ⚠️ -52.16 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| buildDuration | 19s | 20.7s | ⚠️ +1.7s |
| buildDurationCached | 3.6s | 3.6s | ⚠️ +36ms |
| nodeModulesSize | 332 MB | 332 MB | ⚠️ +340 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.893 | 2.855 | -0.04 |
| / avg req/sec | 864.22 | 875.77 | +11.55 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.406 | 1.352 | -0.05 |
| /error-in-render avg req/sec | 1777.69 | 1849.56 | +71.87 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | OKinane/next.js support_cacheStrategy_eslint_arg | Change |
| - | - | - | - |
| index.html gzip | 521 B | 521 B | ✓ |
| link.html gzip | 534 B | 534 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: 12baf749ae8091a1d3f316d0e93735a1361f6b01
