### PR TITLE
Delete using realpath in HMR cache

### LINKED ISSUE #5620: After the initial render, any direct url visits to pages result in 404s
# Bug report

## Describe the bug

in `require.js#getPagePath`, the `pages-manifest.json` file is read using:

```
const pagesManifest = require(join(serverBuildPath, PAGES_MANIFEST))
```

But every time a new on-demand entry is added to the build, the `pages-manifest.json` file changes.

Using require though returns a cached version.

This causes `requirePage` to say `module could not be found`, which causes a 404.

## Fix

Strangely, deleting the require.cache entry didn't resolve it.

```
delete require.cache[join(serverBuildPath, PAGES_MANIFEST)]
```

But using the following resolved my issue:

```
  const pagesManifest = JSON.parse(require('fs').readFileSync(join(serverBuildPath, PAGES_MANIFEST), 'utf8'))
```

## System information
 - OS: [e.g. macOS, Windows] macOS
 - Browser (if applies) [e.g. chrome, safari] Chrome
 - Version of Next.js: [e.g. 6.0.2] v7.0.2-canary.20 / https://github.com/zeit/next.js/commit/b46d7e8f6fc31445801eab08d42e1c361bdaaf28

### PR DESCRIPTION
**Pull request by dav-is**
This will allow symlinked assets to be removed from the cache as well

Fixes: #5620

### CODE REVIEW

File: packages/next/build/webpack/plugins/nextjs-require-cache-hot-reloader.ts [hunk 1]
```diff
@@ -1,15 +1,20 @@
...
+import { Compiler, Plugin } from 'webpack'
+import { realpathSync } from 'fs'
 
-function deleteCache (path: string): void {
-  delete require.cache[path]
+function deleteCache (path: string) {
+  try {
+    delete require.cache[realpathSync(path)]
+  } catch(e) {
+    // probably doesn't exist
```
Comment (timneutkens) [inline packages/next/build/webpack/plugins/nextjs-require-cache-hot-reloader.ts]: Should we make sure it doesn't exist here? Any other errors should probably be shown as it'd indicate breakage.

**Review by timneutkens — APPROVED** [review]
