### PR TITLE
Display original failed fetch trace

### LINKED ISSUE #49896: "TypeError: fetch failed" is an incomplete error: `fetch` in Server Component, if throws and isn't caught, loses info
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.3-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/next-js-server-components-fetch-incomplete-error-if-uncaught-o09yqm

### To Reproduce

In server component, try to load data from an non-existent URL without try/catch.
```
await fetch('http://127.0.0.1:1337/non-existent')
```

### Describe the Bug

The terminal logs just:
```
TypeError: fetch failed
```

And with `next dev`, it will be surfaced to frontend with just the same:
```
Unhandled runtime error
TypeError: fetch failed
```

If I include my own `error.tsx` and try to destructure the error into `const { name, message, trace, cause, ...rest } = error`, it will still be incomplete, having only `name` and `message` (and `digest` in `...rest`), and there the `name` even will be dropped from `TypeError` to just `Error`.

Related: https://github.com/vercel/next.js/issues/44062, but there the focus isn't on error being incomplete, rather that it happens at all.

The issue seems that it only surfaces first line for low-level errors (ECONNREFUSED etc.). Which is why the #44062 seems like a mysterious thing, albeit if you look inside, you'd see that it's the `localhost` resolving to `::1` IPv6 issue at most cases.

### Expected Behavior

Given I `try/catch` and `console.error('FULL ERROR', e)` the error and get this out:
```
FULL ERROR:  TypeError: fetch failed
    at Object.fetch (/project/sandbox/node_modules/next/dist/compiled/undici/index.js:1:26669)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:1337
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 1337
  }
}
```

1. I would expect this to be shown by default in terminal logs. Without me having to try/catch + console.error to see the details.
2. I would expect the `error.tsx` to also have the full info available, as it is for any other (although with this I'm not sure) uncaught exception in Server Component.
3. I would expect the Error surfaced to `error.tsx` not to lose it's `name` (`error.tsx` shows `Error` instead of `TypeError`).

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### LINKED ISSUE #59153: Building production when using localhost:3000 in a fetch gives ECONNREFUSED
### Link to the code that reproduces this issue

https://github.com/douwepausma/build-with-routehandlers-reproduction

### To Reproduce

1. Create new next-app `npx create-next-app@latest`
2. Create a simple route.
```js
// /app/api/model/route.js
export async function GET() {
    return Response.json({ data: {message: 'Hello World!'} })
}
```
3. Fetch route from page.
```js
// /app/page.js
export default async function Home() {
  try {
    const res = await fetch('http://localhost:3000/api/model');
  } catch (error) {
    console.log(error);
  }
  
  return null;
}
```
4. `npm run build`

### Current vs. Expected behavior

**Current behavior**
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11372:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED ::1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 3000
  }
}
```

**Expected behavior**
Successful build

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.11.0
Relevant Packages:
  next: 14.0.4-canary.32
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Data fetching (gS(S)P, getInitialProps), Middleware / Edge (API routes, runtime)

### Additional context

**What I've tried**

1. Use `127.0.0.1` instead of `localhost`
2. Adding `export const runtime = 'edge'` to page fixed build issue, but breaks app later on (when deploying on vercel).*
3. Adding `const dynamic = 'force-dynamic'` to page fixed build issue, but breaks app later on (when deploying on vercel).*

*These fixes shouldn't be necessary as I've successfully used route handlers in the past without it.

### PR DESCRIPTION
**Pull request by huozhi**
### What

Show the original fetch error trace in the dev error overlay, which can show which line of the fetch call is failing.

#### After
image

#### Before
image

### Why

This helps a lot for unclear fetch failures that you only see an error on your screen and you don't have idea where it's coming from

### How

Fixed the async task error that swallowed by tracer, it should always throw in tracing after the metrics are traced.

Closes NEXT-1362
Fixes #59153
Fixes #49896

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js dx/fetch-error-tracing | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.8s | N/A |
| buildDurationCached | 7.1s | 6.2s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +67 kB |
| nextStartRea..uration (ms) | 423ms | 423ms | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js dx/fetch-error-tracing | Change |
| - | - | - | - |
| 193.HASH.js gzip | 181 B | 182 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 433-HASH.js gzip | 28.6 kB | 28.6 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 239 B | 241 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js dx/fetch-error-tracing | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js dx/fetch-error-tracing | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 183 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 502 B | N/A |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 253 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.28 kB | 4.28 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | ✓ |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.4 kB | 3.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js dx/fetch-error-tracing | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js dx/fetch-error-tracing | Change |
| - | - | - | - |
| index.html gzip | 528 B | 525 B | N/A |
| link.html gzip | 540 B | 540 B | ✓ |
| withRouter.html gzip | 523 B | 523 B | ✓ |
| Overall change | 1.06 kB | 1.06 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js dx/fetch-error-tracing | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.8 kB | 93.8 kB | N/A |
| page.js gzip | 147 kB | 147 kB | ⚠️ +156 B |
| Overall change | 147 kB | 147 kB | ⚠️ +156 B |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js dx/fetch-error-tracing | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 625 B | ✓ |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.7 kB | 2.7 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js dx/fetch-error-tracing | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 169 kB | 169 kB | ✓ |
| app-page-exp..prod.js gzip | 94.2 kB | 94.2 kB | ✓ |
| app-page-tur..prod.js gzip | 94.9 kB | 94.9 kB | ✓ |
| app-page-tur..prod.js gzip | 89.5 kB | 89.5 kB | ✓ |
| app-page.run...dev.js gzip | 139 kB | 139 kB | ✓ |
| app-page.run..prod.js gzip | 88.8 kB | 88.8 kB | ✓ |
| app-route-ex...dev.js gzip | 24.1 kB | 24.2 kB | ⚠️ +139 B |
| app-route-ex..prod.js gzip | 16.7 kB | 16.9 kB | ⚠️ +132 B |
| app-route-tu..prod.js gzip | 16.7 kB | 16.9 kB | ⚠️ +132 B |
| app-route-tu..prod.js gzip | 16.3 kB | 16.4 kB | ⚠️ +134 B |
| app-route.ru...dev.js gzip | 23.5 kB | 23.6 kB | ⚠️ +144 B |
| app-route.ru..prod.js gzip | 16.3 kB | 16.4 kB | ⚠️ +134 B |
| pages-api-tu..prod.js gzip | 9.38 kB | 9.38 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.65 kB | 9.65 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.6 kB | 22.6 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.5 kB | 49.5 kB | ✓ |
| Overall change | 932 kB | 933 kB | ⚠️ +815 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.ru..time.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: d6e879b7e317d914dd917b724816fe0acf6081ee

File: packages/next/src/client/components/react-dev-overlay/internal/helpers/stack-frame.ts [hunk 1]
```diff
@@ -121,6 +120,12 @@ export function getOriginalStackFrames(
   )
 }
 
+export function formaFrameSourceFile(file: string) {
```
Comment (ijjk) [inline packages/next/src/client/components/react-dev-overlay/internal/helpers/stack-frame.ts:123]:
```suggestion
export function formatFrameSourceFile(file: string) {
```

File: packages/next/src/server/lib/patch-fetch.ts [hunk 2]
```diff
@@ -191,10 +224,14 @@ export function patchFetch({
   const { DynamicServerError } = serverHooks
   const originFetch: typeof fetch = (globalThis as any)._nextOriginalFetch
 
-  globalThis.fetch = async (
+  async function patchedFetch(
     input: RequestInfo | URL,
     init: RequestInit | undefined
-  ) => {
+  ) {
+    const tracingError = new Error()
```
Comment (feedthejim) [inline packages/next/src/server/lib/patch-fetch.ts:231]: can we create it lazily?

Comment (feedthejim) [reply packages/next/src/server/lib/patch-fetch.ts:231]: comments explaining what this does would be nice

Comment (huozhi) [reply packages/next/src/server/lib/patch-fetch.ts:244]: Updated the comment to explain more. the error has to be created here to contain the call stack. But we don't need to throw it always. We only replace the stack trace when necessary

File: packages/next/src/server/lib/patch-fetch.ts [hunk 3]
```diff
@@ -191,10 +224,27 @@ export function patchFetch({
   const { DynamicServerError } = serverHooks
   const originFetch: typeof fetch = (globalThis as any)._nextOriginalFetch
 
-  globalThis.fetch = async (
+  async function patchedFetch(
```
Comment (sebmarkbage) [inline packages/next/src/server/lib/patch-fetch.ts:227]: `globalThis.fetch.name` should be `fetch` not `patchedFetch`.

File: packages/next/src/server/lib/patch-fetch.ts [hunk 4]
```diff
@@ -176,6 +176,39 @@ interface PatchableModule {
...
+      // If it's failed with internal fetch call, and there's only node:internal traces
+      if (
+        err instanceof Error &&
+        err.name === 'TypeError' &&
+        err.message === 'fetch failed'
+      ) {
+        const traces: string[] = err.stack?.split('\n') || []
+        // trace without the error message
+        const originStackTrace = traces.slice(1)
+        if (originStackTrace.every((line) => line.includes('node:internal'))) {
```
Comment (sebmarkbage) [inline packages/next/src/server/lib/patch-fetch.ts:200]: Why bother at all with the internal stack? Just do this for every error and every error message? What matters is it came from fetch.

**Review by sebmarkbage — APPROVED** [review]
