### PR TITLE
fix: bundle fetching with asset prefix

### LINKED ISSUE #63623: Bundles not found (404) when using relative assetPrefix
### Link to the code that reproduces this issue

https://github.com/Netail/asset-prefix-bundles-not-found

### To Reproduce

1. Create new next.js project
2. Added a relative assetPrefix (e.g. `/custom-asset-path`) in the next config
3. Open the local development instance 

### Current vs. Expected behavior

Bundles are not able to be retrieved from the server, throwing 404 not founds. Bundles should be able to retrieve

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.8.1
  npm: 10.1.0
  Yarn: 1.22.22
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.0-canary.39 // Latest available version is detected (14.2.0-canary.39).
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Netail**
Closes: https://github.com/vercel/next.js/issues/63623

When a relative assetPrefix was set (e.g. `/custom-asset-prefix`), bundle fetching would always return a 404 as the assetPrefix was not removed from filesystem path

### CODE REVIEW

**Comment by Netail** [comment]
We currently use 
```ts
    rewrites: () => [
        {
            source: '/custom-asset-prefix/:path*',
            destination: '/:path*',
        },
    ],
```
as a workaround, but isn't ideal

**Review by ijjk — COMMENTED** [review]
Hi, could we add a test case for this?

File: packages/next/src/server/lib/router-utils/filesystem.ts [hunk 1]
```diff
@@ -421,12 +421,17 @@ export async function setupFsCheck(opts: {
         return lruResult
       }
 
-      const { basePath } = opts.config
+      const { basePath, assetPrefix } = opts.config
 
-      if (basePath && !pathHasPrefix(itemPath, basePath)) {
+      if (
```
Comment (ijjk) [inline packages/next/src/server/lib/router-utils/filesystem.ts:426]: Instead of checking both each time we should have a source of truth value that is either the `basePath` or `assetPrefix`.

**Comment by Netail** [comment]
Hi @ijjk 👋 
Could you take a look at this solution as you've worked the most on filesystem.ts

File: packages/next/src/server/lib/router-utils/filesystem.ts (hunk 1 above)
Comment (Netail) [reply packages/next/src/server/lib/router-utils/filesystem.ts:426]: The problem with that is that if both a basePath and an assetPrefix are set, it could start from either one;
- bundles will be fetched with itemPath: `/custom-asset-prefix/_next/static/.....`
- pages with itemPath: `/custom-base-path/...`

So something like 
```ts
const prefix = assetPrefix || basePath;

if (prefix && !pathHasPrefix(itemPath, prefix)) {
  return null
}
itemPath = removePathPrefix(itemPath, prefix) || '/'
```
would result in a 404 for page, instead of bundles (The other way around to the current issue)

Comment (ijjk) [reply packages/next/src/server/lib/router-utils/filesystem.ts:426]: Hmm I see, it does look like we allow these values to diverge so keeping the checks separate like this seems alright.

**Comment by Netail** [comment]
> Hi, could we add a test case for this?

Added some e2e tests

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 9549ac8f7030ee0a7a5d754af8540f429b99e1dc

`pnpm test-dev test/development/basic/next-rs-api.test.ts`
- next.rs api > should allow to write root page to disk
- next.rs api > should allow to write pages edge page to disk
- next.rs api > should allow to write pages Node.js page to disk
- next.rs api > should have working HMR on client-side change on a page 0
- next.rs api > should have working HMR on client-side change on a page 1
- next.rs api > should have working HMR on client-side change on a page 2
- next.rs api > should have working HMR on server-side change on a page 0
- next.rs api > should have working HMR on server-side change on a page 1
- next.rs api > should have working HMR on server-side change on a page 2
- next.rs api > should have working HMR on client and server-side change on a page 0
- next.rs api > should have working HMR on client and server-side change on a page 1
- next.rs api > should have working HMR on client and server-side change on a page 2
- next.rs api > should have working HMR on client-side change on a app page 0
- next.rs api > should have working HMR on client-side change on a app page 1
- next.rs api > should have working HMR on client-side change on a app page 2
- next.rs api > should have working HMR on server-side change on a app page 0
- next.rs api > should have working HMR on server-side change on a app page 1
- next.rs api > should have working HMR on server-side change on a app page 2

<details>
<summary>Expand output</summary>

  ● next.rs api › should allow to write root page to disk

    expect(received).toMatchSnapshot(hint)

    Snapshot name: `next.rs api should allow to write root page to disk: issues 1`

    - Snapshot  -  1
    + Received  + 38

    - []
    + [
    +   {
    +     "description": {
    +       "type": "text",
    +       "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    + List all export names manually (`export { a, b, c } from "...") or rewrite the module to ESM, to avoid the additional runtime code.`",
    +     },
    +     "detail": undefined,
    +     "documentationLink": "",
    +     "filePath": "[project]/.../node_modules/next/dist/shared/lib/constants.js",
    +     "severity": "warning",
    +     "source": undefined,
    +     "stage": "analysis",
    +     "subIssues": [],
    +     "title": {
    +       "type": "text",
    +       "value": "unexpected export *",
    +     },
    +   },
    +   {
    +     "description": {
    +       "type": "text",
    +       "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    + List all export names manually (`export { a, b, c } from "...") or rewrite the module to ESM, to avoid the additional runtime code.`",
    +     },
    +     "detail": undefined,
    +     "documentationLink": "",
    +     "filePath": "[project]/.../node_modules/next/dist/shared/lib/constants.js",
    +     "severity": "warning",
    +     "source": undefined,
    +     "stage": "analysis",
    +     "subIssues": [],
    +     "title": {
    +       "type": "text",
    +       "value": "unexpected export *",
    +     },
    +   },
    + ]

      343 |           expect(result.type).toBe(runtime)
      344 |           expect(result.config).toEqual(config)
    > 345 |           expect(normalizeIssues(result.issues)).toMatchSnapshot('issues')
          |                                                  ^
      346 |           expect(normalizeDiagnostics(result.diagnostics)).toMatchSnapshot(
      347 |             'diagnostics'
      348 |           )

      at Object.toMatchSnapshot (development/basic/next-rs-api.test.ts:345:50)

  ● next.rs api › should allow to write pages edge page to disk

    expect(received).toMatchSnapshot(hint)

    Snapshot name: `next.rs api should allow to write pages edge page to disk: issues 1`

    - Snapshot  -  1
    + Received  + 38

    - []
    + [
    +   {
    +     "description": {
    +       "type": "text",
    +       "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    + List all export names manually (`export { a, b, c } from "...") or rewrite the module to ESM, to avoid the additional runtime code.`",
    +     },
    +     "detail": undefined,
    +     "documentationLink": "",
    +     "filePath": "[project]/.../node_modules/next/dist/shared/lib/constants.js",
    +     "severity": "warning",
    +     "source": undefined,
    +     "stage": "analysis",
    +     "subIssues": [],
    +     "title": {
    +       "type": "text",
    +       "value": "unexpected export *",
    +     },
    +   },
    +   {
    +     "description": {
    +       "type": "text",
    +       "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    + List all export names manually (`export { a, b, c } from "...") or rewrite the module to ESM, to avoid the additional runtime code.`",
    +     },
    +     "detail": undefined,
    +     "documentationLink": "",
    +     "filePath": "[project]/.../node_modules/next/dist/shared/lib/constants.js",
    +     "severity": "warning",
    +     "source": undefined,
    +     "stage": "analysis",
    +     "subIssues": [],
    +     "title": {
    +       "type": "text",
    +       "value": "unexpected export *",
    +     },
    +   },
    + ]

      343 |           expect(result.type).toBe(runtime)
      344 |           expect(result.config).toEqual(config)
    > 345 |           expect(normalizeIssues(result.issues)).toMatchSnapshot('issues')
          |                                                  ^
      346 |           expect(normalizeDiagnostics(result.diagnostics)).toMatchSnapshot(
      347 |             'diagnostics'
      348 |           )

      at Object.toMatchSnapshot (development/basic/next-rs-api.test.ts:345:50)

  ● next.rs api › should allow to write pages Node.js page to disk

    expect(received).toMatchSnapshot(hint)

    Snapshot name: `next.rs api should allow to write pages Node.js page to disk: issues 1`

    - Snapshot  -  1
    + Received  + 38

    - []
    + [
    +   {
    +     "description": {
    +       "type": "text",
    +       "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    + List all export names manually (`export { a, b, c } from "...") or rewrite the module to ESM, to avoid the additional runtime code.`",
    +     },
    +     "detail": undefined,
    +     "documentationLink": "",
    +     "filePath": "[project]/.../node_modules/next/dist/shared/lib/constants.js",
    +     "severity": "warning",
    +     "source": undefined,
    +     "stage": "analysis",
    +     "subIssues": [],
    +     "title": {
    +       "type": "text",
    +       "value": "unexpected export *",
    +     },
    +   },
    +   {
    +     "description": {
    +       "type": "text",
    +       "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    + List all export names manually (`export { a, b, c } from "...") or rewrite the module to ESM, to avoid the additional runtime code.`",
    +     },
    +     "detail": undefined,
    +     "documentationLink": "",
    +     "filePath": "[project]/.../node_modules/next/dist/shared/lib/constants.js",
    +     "severity": "warning",
    +     "source": undefined,
    +     "stage": "analysis",
    +     "subIssues": [],
    +     "title": {
    +       "type": "text",
    +       "value": "unexpected export *",
    +     },
    +   },
    + ]

      343 |           expect(result.type).toBe(runtime)
      344 |           expect(result.config).toEqual(config)
    > 345 |           expect(normalizeIssues(result.issues)).toMatchSnapshot('issues')
          |                                                  ^
      346 |           expect(normalizeDiagnostics(result.diagnostics)).toMatchSnapshot(
      347 |             'diagnostics'
      348 |           )

      at Object.toMatchSnapshot (development/basic/next-rs-api.test.ts:345:50)

  ● next.rs api › should have working HMR on client-side change on a page 0

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 6)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on client-side change on a page 1

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 2)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on client-side change on a page 2

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 15)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on server-side change on a page 0

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 27)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on server-side change on a page 1

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 1)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on server-side change on a page 2

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 0)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on client and server-side change on a page 0

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 0)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on client and server-side change on a page 1

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 0)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on client and server-side change on a page 2

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 6)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on client-side change on a app page 0

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 1)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on client-side change on a app page 1

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 5)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on client-side change on a app page 2

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 1)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on server-side change on a app page 0

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 36)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on server-side change on a app page 1

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 1)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

  ● next.rs api › should have working HMR on server-side change on a app page 2

    expect(received).toHaveProperty(path, value)

    Expected path: "issues"

    Expected value: toBeEmpty<>
    Received value: [{"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}, {"description": {"type": "text", "value": "export * used with module [project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js [client] (ecmascript) which is a CommonJS module with exports only available at runtime
    List all export names manually (`export { a, b, c } from \"...\") or rewrite the module to ESM, to avoid the additional runtime code.`"}, "documentationLink": "", "filePath": "[project]/node_modules/.pnpm/file+..+next-repo-195a2559e7732cdb2890bfd0bc608afca6fa3c4704bb5e898741005df5b1962c+packages+n_2cjvpzl6lrl3xrjutsph33mudy/node_modules/next/dist/shared/lib/constants.js", "severity": "warning", "stage": "analysis", "subIssues": [], "title": {"type": "text", "value": "unexpected export *"}}]

      498 |             expect(result.value).toHaveProperty('resource', expect.toBeObject())
      499 |             expect(result.value).toHaveProperty('type', 'issues')
    > 500 |             expect(result.value).toHaveProperty('issues', expect.toBeEmpty())
          |                                  ^
      501 |             expect(result.value).toHaveProperty(
      502 |               'diagnostics',
      503 |               expect.toBeEmpty()

      at toHaveProperty (development/basic/next-rs-api.test.ts:500:34)
          at async Promise.all (index 1)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:494:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Netail/next.js fix/bundle-fetching-with-asset-prefix | Change |
| - | - | - | - |
| buildDuration | 13.9s | 14.1s | ⚠️ +193ms |
| buildDurationCached | 7.7s | 6.3s | N/A |
| nodeModulesSize | 198 MB | 198 MB | ⚠️ +1.63 kB |
| nextStartRea..uration (ms) | 406ms | 415ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | Netail/next.js fix/bundle-fetching-with-asset-prefix | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 31 kB | 31 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | ✓ |
| 8299-HASH.js gzip | 5.04 kB | 5.04 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 243 B | 242 B | N/A |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 99 kB | 99 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Netail/next.js fix/bundle-fetching-with-asset-prefix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Netail/next.js fix/bundle-fetching-with-asset-prefix | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.21 kB | 4.21 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.57 kB | 6.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Netail/next.js fix/bundle-fetching-with-asset-prefix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Netail/next.js fix/bundle-fetching-with-asset-prefix | Change |
| - | - | - | - |
| index.html gzip | 529 B | 528 B | N/A |
| link.html gzip | 541 B | 541 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.06 kB | 1.06 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | Netail/next.js fix/bundle-fetching-with-asset-prefix | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.3 kB | 95.3 kB | N/A |
| page.js gzip | 3.04 kB | 3.04 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | Netail/next.js fix/bundle-fetching-with-asset-prefix | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 623 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | Netail/next.js fix/bundle-fetching-with-asset-prefix | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | ✓ |
| app-page-exp..prod.js gzip | 97 kB | 97 kB | ✓ |
| app-page-tur..prod.js gzip | 98.7 kB | 98.7 kB | ✓ |
| app-page-tur..prod.js gzip | 93 kB | 93 kB | ✓ |
| app-page.run...dev.js gzip | 144 kB | 144 kB | ✓ |
| app-page.run..prod.js gzip | 91.5 kB | 91.5 kB | ✓ |
| app-route-ex...dev.js gzip | 21.4 kB | 21.4 kB | ✓ |
| app-route-ex..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| app-route.ru...dev.js gzip | 21 kB | 21 kB | ✓ |
| app-route.ru..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim...dev.js gzip | 23.1 kB | 23.1 kB | ✓ |
| pages.runtim..prod.js gzip | 22.4 kB | 22.4 kB | ✓ |
| server.runti..prod.js gzip | 51 kB | 51 kB | ✓ |
| Overall change | 944 kB | 944 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Netail/next.js fix/bundle-fetching-with-asset-prefix | Change |
| - | - | - | - |
| 0.pack gzip | 1.57 MB | 1.57 MB | N/A |
| index.pack gzip | 106 kB | 106 kB | ⚠️ +159 B |
| Overall change | 106 kB | 106 kB | ⚠️ +159 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 9549ac8f7030ee0a7a5d754af8540f429b99e1dc

**Comment by Netail** [comment]
Can take a look at these tomorrow, off to bed right now

**Comment by Netail** [comment]
Mhm to fix the basepath.test.ts I think we should only allow a removal only once from either the assetPrefix or basePath (so the part after the if statement)

**Comment by Netail** [comment]
Should be resolved now :)

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 91fe9cc77270f491c0651bfc1097af19cd5392f9

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by Netail** [comment]
@timneutkens can you rerun the tests? Dankjewel :)

**Comment by Netail** [comment]
@ztanner can you rerun the tests for me? :)

**Comment by Netail** [comment]
@ijjk can you rerun the tests for me? :)

File: packages/next/src/server/lib/router-utils/filesystem.ts [hunk 2]
```diff
@@ -421,12 +421,22 @@ export async function setupFsCheck(opts: {
...
+      // Return null if either path doesn't start with basePath or assetPrefix
+      if ((basePath || assetPrefix) && !hasBasePath && !hasAssetPrefix) {
         return null
       }
-      itemPath = removePathPrefix(itemPath, basePath) || '/'
+
+      // Either remove basePath or assetPrefix, not both (due to routes with same name as basePath)
+      if (basePath && hasBasePath) {
+        itemPath = removePathPrefix(itemPath, basePath) || '/'
+      } else if (assetPrefix && hasAssetPrefix) {
```
Comment (shaunwarman) [inline packages/next/src/server/lib/router-utils/filesystem.ts:437]: What about CDN assetPrefix here? Are we removing that?
