### PR TITLE
Reimplement code frame rendering in native code

### LINKED ISSUE #85357: Turbopack stack overflow when compiling a page with `@techstark/opencv-js` import
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/opencv-turbo-stack-overflow-repro-7sp8kz

### To Reproduce

1. Open the Devbox, run the `dev:turbo` task and load the preview.
2. Turbopack crashes with `RangeError: Maximum call stack size exceeded`
3. Run the `dev:webpack` task instead and verify that Webpack compiles without issues.

### Current vs. Expected behavior

I expect Turbopack to compile without issues, just like Webpack.

### Provide environment information

```bash
(From Devbox)
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 16.0.1-canary.2 // Latest available version is detected (16.0.1-canary.2).
  eslint-config-next: N/A
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lukesandberg**
## What

Replaces the `@babel/code-frame` dependency with a new Rust-based implementation (`next-code-frame` crate) for rendering code frames in error messages.

### Why

- **Crash fix**: `@babel/code-frame` uses the `js-tokens` library for syntax highlighting, which has [known issues](https://github.com/lydell/js-tokens?tab=readme-ov-file#known-failures) with large string literals and long lines. This can cause Next.js to throw RangeErrors when rendering errors, hiding the original issue!
- **Long line support**: The old implementation had no concept of terminal width, dumping entire lines into the output. The new implementation uses "horizontal scrolling" — truncating lines and centering the error location in the visible window.
- **Performance**: The Rust implementation only processes the visible line range (typically ~6 lines), not the entire file. Syntax highlighting uses a skip-scan heuristic to start tokenizing near the visible window rather than from byte 0.
- **Dependency reduction**: Drops the semi-unmaintained `@babel/code-frame` bundled dependency in favor of code we control.

### Benchmarks

In-process benchmarks comparing `render_code_frame()` (Rust, via criterion) against `codeFrameColumns()` (Babel, via hrtime with DCE prevention). Both have syntax highlighting and color output enabled. No process startup or file I/O is included in the measurement.

| Scenario | `next-code-frame` (Rust) | `@babel/code-frame` | Speedup |
|---|---|---|---|
| Small file (~490 lines TSX) | **5.4 µs** | 507 µs | **~94x** |
| Large file (~39k lines JS) | **143 µs** | 82.9 ms | **~580x** |
| Large file minified | **51 µs** | - | **-** |

The gap widens with file size because Babel's `highlight()` runs a regex tokenizer over the **entire source** before slicing to the visible window, while the Rust implementation uses a windowed line index and skip-scan heuristic — only processing the visible window regardless of file size.  However, for minified files we do end up tokenizing the whole thing so we end up being only 8x faster

### How

- New `crates/next-code-frame/` Rust crate with:
  - Frame rendering with terminal-width-aware horizontal scrolling
  - Regex-based syntax highlighting (matching Babel's color scheme)
  - Skip-scan heuristic for O(1)-ish highlighting regardless of file size
  - Windowed line index that only scans/stores offsets for the visible region
  - Comprehensive test suite (800+ lines)
- Exposed via both NAPI (native) and WASM bindings
- JS wrappers in `packages/next/src/shared/lib/errors/`:
  - `code-frame.ts` — primary wrapper using native bindings
  - `optional-code-frame.ts` — graceful fallback returning `undefined` if bindings are unavailable
- All existing callsites (`diagnosticFormatter`, `parseScss`, dev overlay, turbopack utils) updated
- for `patch-error-inspect.ts` i adopted an `injection` style approach to avoid coupling to the native dependency

### Concerns / review focus areas

- **Reliability**: The regex-based tokenizer is best-effort and language-agnostic — it should never crash on invalid syntax, but highlighting accuracy may differ from Babel's `js-tokens` in edge cases.
- **Native dependency**: This moves code frame rendering into the native binary. Performance should be better, but worth verifying there are no regressions in environments where native bindings behave differently (e.g. WASM fallback path).
- **Regressions**: The output format and color scheme closely match Babel's, but there may be subtle differences. The horizontal scrolling behavior is new.

Fixes #85357
Closes PACK-5754

### CODE REVIEW

**Comment by lukesandberg** [comment]
* **#90534** <a href="https://app.graphite.com/github/pr/vercel/next.js/90534?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#85592** <a href="https://app.graphite.com/github/pr/vercel/next.js/85592?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/vercel/next.js/85592?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#85787** <a href="https://app.graphite.com/github/pr/vercel/next.js/85787?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ijjk** [comment]
## Tests Passed

<!-- ## Failing test suites -- >

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js code_frame_defence | Change |
| - | - | - | - |
| buildDuration | 32.1s | 30.6s | N/A |
| buildDurationCached | 27.2s | 22.8s | N/A |
| nodeModulesSize | 454 MB | 454 MB | ⚠️ +15.9 kB |
| nextStartRea..uration (ms) | 703ms | 656ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js code_frame_defence | Change |
| - | - | - | - |
| 436-HASH.js gzip | 5.32 kB | 5.32 kB | N/A |
| 4779.HASH.js gzip | 169 B | 169 B | ✓ |
| 9760-HASH.js gzip | 54.9 kB | 54.6 kB | N/A |
| c57d0559-HASH.js gzip | 62 kB | 62.1 kB | N/A |
| framework-HASH.js gzip | 59.8 kB | 59.8 kB | ✓ |
| main-app-HASH.js gzip | 254 B | 255 B | N/A |
| main-HASH.js gzip | 39.7 kB | 39.8 kB | N/A |
| webpack-HASH.js gzip | 1.69 kB | 1.69 kB | ✓ |
| Overall change | 61.7 kB | 61.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js code_frame_defence | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js code_frame_defence | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 194 B | N/A |
| _error-HASH.js gzip | 182 B | 182 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| dynamic-HASH.js gzip | 1.81 kB | 1.81 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 254 B | N/A |
| head-HASH.js gzip | 350 B | 351 B | N/A |
| hooks-HASH.js gzip | 384 B | 384 B | ✓ |
| image-HASH.js gzip | 4.78 kB | 4.77 kB | N/A |
| index-HASH.js gzip | 260 B | 259 B | N/A |
| link-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| routerDirect..HASH.js gzip | 316 B | 320 B | N/A |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 316 B | 314 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.39 kB | 1.39 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js code_frame_defence | Change |
| - | - | - | - |
| _buildManifest.js gzip | 718 B | 720 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js code_frame_defence | Change |
| - | - | - | - |
| index.html gzip | 524 B | 523 B | N/A |
| link.html gzip | 538 B | 538 B | ✓ |
| withRouter.html gzip | 521 B | 519 B | N/A |
| Overall change | 538 B | 538 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js code_frame_defence | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 259 kB | 260 kB | ⚠️ +1.12 kB |
| Overall change | 259 kB | 260 kB | ⚠️ +1.12 kB |

</details>

<details>
<summary><strong>Middleware size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js code_frame_defence | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 638 B | 638 B | ✓ |
| middleware-r..fest.js gzip | 156 B | 156 B | ✓ |
| middleware.js gzip | 32.7 kB | 32.9 kB | ⚠️ +264 B |
| edge-runtime..pack.js gzip | 846 B | 846 B | ✓ |
| Overall change | 34.3 kB | 34.6 kB | ⚠️ +264 B |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js code_frame_defence | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 296 kB | 296 kB | N/A |
| app-page-exp..prod.js gzip | 162 kB | 162 kB | ✓ |
| app-page-tur...dev.js gzip | 295 kB | 295 kB | ✓ |
| app-page-tur..prod.js gzip | 162 kB | 162 kB | ✓ |
| app-page-tur...dev.js gzip | 292 kB | 292 kB | N/A |
| app-page-tur..prod.js gzip | 159 kB | 159 kB | ✓ |
| app-page.run...dev.js gzip | 292 kB | 292 kB | N/A |
| app-page.run..prod.js gzip | 159 kB | 159 kB | ✓ |
| app-route-ex...dev.js gzip | 70.8 kB | 70.8 kB | ✓ |
| app-route-ex..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| app-route-tu...dev.js gzip | 70.8 kB | 70.8 kB | ✓ |
| app-route-tu..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| app-route-tu...dev.js gzip | 70.4 kB | 70.4 kB | ✓ |
| app-route-tu..prod.js gzip | 49.1 kB | 49.1 kB | ✓ |
| app-route.ru...dev.js gzip | 70.4 kB | 70.4 kB | ✓ |
| app-route.ru..prod.js gzip | 49.1 kB | 49.1 kB | ✓ |
| dist_client_...dev.js gzip | 326 B | 326 B | ✓ |
| dist_client_...dev.js gzip | 328 B | 328 B | ✓ |
| dist_client_...dev.js gzip | 320 B | 320 B | ✓ |
| dist_client_...dev.js gzip | 318 B | 318 B | ✓ |
| pages-api-tu...dev.js gzip | 43.3 kB | 43.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 33.2 kB | 33.2 kB | ✓ |
| pages-api.ru...dev.js gzip | 43.3 kB | 43.3 kB | ✓ |
| pages-api.ru..prod.js gzip | 33.1 kB | 33.1 kB | ✓ |
| pages-turbo....dev.js gzip | 52.8 kB | 52.8 kB | ✓ |
| pages-turbo...prod.js gzip | 40.1 kB | 40.1 kB | ✓ |
| pages.runtim...dev.js gzip | 52.8 kB | 52.8 kB | ✓ |
| pages.runtim..prod.js gzip | 40 kB | 40 kB | ✓ |
| server.runti..prod.js gzip | 78.9 kB | 78.9 kB | ✓ |
| Overall change | 1.83 MB | 1.83 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js code_frame_defence | Change |
| - | - | - | - |
| 0.pack gzip | 3.25 MB | 3.25 MB | ⚠️ +536 B |
| index.pack gzip | 94.6 kB | 95.1 kB | ⚠️ +539 B |
| Overall change | 3.34 MB | 3.34 MB | ⚠️ +1.07 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [2291],
   {
-    /***/ 1033: /***/ (
+    /***/ 431: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/dynamic",
         function () {
-          return __webpack_require__(6490);
+          return __webpack_require__(8084);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 5323: /***/ (
+    /***/ 2699: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -60,7 +60,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       const _react = /*#__PURE__*/ _interop_require_default._(
         __webpack_require__(2223)
       );
-      const _loadablecontextsharedruntime = __webpack_require__(9289);
+      const _loadablecontextsharedruntime = __webpack_require__(3785);
       function resolve(obj) {
         return obj && obj.default ? obj.default : obj;
       }
@@ -293,73 +293,34 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       /***/
     },
 
-    /***/ 6490: /***/ (
+    /***/ 3785: /***/ (
       __unused_webpack_module,
-      __webpack_exports__,
+      exports,
       __webpack_require__
     ) => {
       "use strict";
-      __webpack_require__.r(__webpack_exports__);
-      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
-        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
-        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
-        /* harmony export */
+      /* __next_internal_client_entry_do_not_use__  cjs */
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
       });
-      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(1503);
-      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(7320);
-      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default =
-        /*#__PURE__*/ __webpack_require__.n(
-          next_dynamic__WEBPACK_IMPORTED_MODULE_1__
-        );
-
-      const DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
-        () =>
-          __webpack_require__
-            .e(/* import() */ 4779)
-            .then(__webpack_require__.bind(__webpack_require__, 4779))
-            .then((mod) => mod.Hello),
-        {
-          loadableGenerated: {
-            webpack: () => [/*require.resolve*/ 4779],
-          },
-        }
+      Object.defineProperty(exports, "LoadableContext", {
+        enumerable: true,
+        get: function () {
+          return LoadableContext;
+        },
+      });
+      const _interop_require_default = __webpack_require__(1532);
+      const _react = /*#__PURE__*/ _interop_require_default._(
+        __webpack_require__(2223)
       );
-      const Page = () =>
-        /*#__PURE__*/ (0, react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)(
-          react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.Fragment,
-          {
-            children: [
-              /*#__PURE__*/ (0,
-              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("p", {
-                children: "testing next/dynamic size",
-              }),
-              /*#__PURE__*/ (0,
-              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
-                DynamicHello,
-                {}
-              ),
-            ],
-          }
-        );
-      var __N_SSP = true;
-      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = Page;
-
-      /***/
-    },
-
-    /***/ 7320: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(7340);
+      const LoadableContext = _react.default.createContext(null);
+      if (false) {
+      } //# sourceMappingURL=loadable-context.shared-runtime.js.map
 
       /***/
     },
 
-    /***/ 7340: /***/ (module, exports, __webpack_require__) => {
+    /***/ 6828: /***/ (module, exports, __webpack_require__) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -392,7 +353,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
         __webpack_require__(2223)
       );
       const _loadablesharedruntime = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(5323)
+        __webpack_require__(2699)
       );
       const isServerSide = "object" === "undefined";
       // Normalize loader to return the module as form { default: Component } for `React.lazy`.
@@ -492,29 +453,68 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       /***/
     },
 
-    /***/ 9289: /***/ (
+    /***/ 7514: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(6828);
+
+      /***/
+    },
+
+    /***/ 8084: /***/ (
       __unused_webpack_module,
-      exports,
+      __webpack_exports__,
       __webpack_require__
     ) => {
       "use strict";
-      /* __next_internal_client_entry_do_not_use__  cjs */
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "LoadableContext", {
-        enumerable: true,
-        get: function () {
-          return LoadableContext;
-        },
+      __webpack_require__.r(__webpack_exports__);
+      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
+        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
+        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
+        /* harmony export */
       });
-      const _interop_require_default = __webpack_require__(1532);
-      const _react = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(2223)
+      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
+        __webpack_require__(1503);
+      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ =
+        __webpack_require__(7514);
+      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default =
+        /*#__PURE__*/ __webpack_require__.n(
+          next_dynamic__WEBPACK_IMPORTED_MODULE_1__
+        );
+
+      const DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
+        () =>
+          __webpack_require__
+            .e(/* import() */ 9573)
+            .then(__webpack_require__.bind(__webpack_require__, 9573))
+            .then((mod) => mod.Hello),
+        {
+          loadableGenerated: {
+            webpack: () => [/*require.resolve*/ 9573],
+          },
+        }
       );
-      const LoadableContext = _react.default.createContext(null);
-      if (false) {
-      } //# sourceMappingURL=loadable-context.shared-runtime.js.map
+      const Page = () =>
+        /*#__PURE__*/ (0, react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)(
+          react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.Fragment,
+          {
+            children: [
+              /*#__PURE__*/ (0,
+              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("p", {
+                children: "testing next/dynamic size",
+              }),
+              /*#__PURE__*/ (0,
+              react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
+                DynamicHello,
+                {}
+              ),
+            ],
+          }
+        );
+      var __N_SSP = true;
+      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = Page;
 
       /***/
     },
@@ -524,7 +524,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(1033)
+      __webpack_exec__(431)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>edge-ssr-HASH.js</strong></summary>

```diff
@@ -1,24 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [676],
   {
-    /***/ 1819: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/edge-ssr",
-        function () {
-          return __webpack_require__(7521);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 7521: /***/ (
+    /***/ 983: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -37,13 +20,30 @@
 
       /***/
     },
+
+    /***/ 985: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/edge-ssr",
+        function () {
+          return __webpack_require__(983);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(1819)
+      __webpack_exec__(985)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>head-HASH.js</strong></summary>

```diff
@@ -1,34 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [5350],
   {
-    /***/ 619: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/head",
-        function () {
-          return __webpack_require__(9891);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 7997: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(6705);
-
-      /***/
-    },
-
-    /***/ 9891: /***/ (
+    /***/ 1417: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -43,7 +16,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(1503);
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(7997);
+        __webpack_require__(5171);
       /* harmony import */ var next_head__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_head__WEBPACK_IMPORTED_MODULE_1__
@@ -76,13 +49,40 @@
 
       /***/
     },
+
+    /***/ 1937: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/head",
+        function () {
+          return __webpack_require__(1417);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 5171: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(7505);
+
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(619)
+      __webpack_exec__(1937)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>hooks-HASH.js</strong></summary>

```diff
@@ -1,24 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [9804],
   {
-    /***/ 1679: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/hooks",
-        function () {
-          return __webpack_require__(7036);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 7036: /***/ (
+    /***/ 1598: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -76,13 +59,30 @@
 
       /***/
     },
+
+    /***/ 3925: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/hooks",
+        function () {
+          return __webpack_require__(1598);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(1679)
+      __webpack_exec__(3925)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1,24 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [2983],
   {
-    /***/ 797: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/image",
-        function () {
-          return __webpack_require__(5999);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 1713: /***/ (__unused_webpack_module, exports) => {
+    /***/ 881: /***/ (__unused_webpack_module, exports) => {
       "use strict";
       /**
        * A shared function, used on both client and server, to generate a SVG blur placeholder.
@@ -58,7 +41,7 @@
       /***/
     },
 
-    /***/ 2263: /***/ (module, exports, __webpack_require__) => {
+    /***/ 1511: /***/ (module, exports, __webpack_require__) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -136,7 +119,137 @@
       /***/
     },
 
-    /***/ 2728: /***/ (module, exports, __webpack_require__) => {
+    /***/ 1744: /***/ (
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "default", {
+        enumerable: true,
+        get: function () {
+          return _default;
+        },
+      });
+      const _findclosestquality = __webpack_require__(7054);
+      function defaultLoader({ config, src, width, quality }) {
+        if (
+          src.startsWith("/") &&
+          src.includes("?") &&
+          config.localPatterns?.length === 1 &&
+          config.localPatterns[0].pathname === "**" &&
+          config.localPatterns[0].search === ""
+        ) {
+          throw Object.defineProperty(
+            new Error(
+              `Image with src "${src}" is using a query string which is not configured in images.localPatterns.` +
+                `\nRead more: https://nextjs.org/docs/messages/next-image-unconfigured-localpatterns`
+            ),
+            "__NEXT_ERROR_CODE",
+            {
+              value: "E871",
+              enumerable: false,
+              configurable: true,
+            }
+          );
+        }
+        if (false) {
+        }
+        const q = (0, _findclosestquality.findClosestQuality)(quality, config);
+        return `${config.path}?url=${encodeURIComponent(
+          src
+        )}&w=${width}&q=${q}${
+          src.startsWith("/_next/static/media/") && false ? 0 : ""
+        }`;
+      }
+      // We use this to determine if the import is the default loader
+      // or a custom loader defined by the user in next.config.js
+      defaultLoader.__next_img_default = true;
+      const _default = defaultLoader; //# sourceMappingURL=image-loader.js.map
+
+      /***/
+    },
+
+    /***/ 2388: /***/ (
+      __unused_webpack_module,
+      __webpack_exports__,
+      __webpack_require__
+    ) => {
+      "use strict";
+      // ESM COMPAT FLAG
+      __webpack_require__.r(__webpack_exports__);
+
+      // EXPORTS
+      __webpack_require__.d(__webpack_exports__, {
+        __N_SSP: () => /* binding */ __N_SSP,
+        default: () => /* binding */ pages_image,
+      });
+
+      // EXTERNAL MODULE: ./node_modules/.pnpm/react@19.2.0/node_modules/react/jsx-runtime.js
+      var jsx_runtime = __webpack_require__(1503);
+      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.2.0_react@19.2.0__react@19.2.0/node_modules/next/image.js
+      var next_image = __webpack_require__(3866);
+      var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // ./pages/nextjs.png
+      /* harmony default export */ const nextjs = {
+        src: "/_next/static/media/nextjs.cae0b805.png",
+        height: 1347,
+        width: 1626,
+        blurDataURL:
+          "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAHCAMAAAACh/xsAAAAD1BMVEX////x8fH6+vrb29vo6Oh8o70bAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAH0lEQVR4nGNgwARMjIyMjCAGCzMzMwsTRISJCcRABwAEcAAkLCQfgAAAAABJRU5ErkJggg==",
+        blurWidth: 8,
+        blurHeight: 7,
+      }; // ./pages/image.js
+      function ImagePage(props) {
+        return /*#__PURE__*/ (0, jsx_runtime.jsxs)(jsx_runtime.Fragment, {
+          children: [
+            /*#__PURE__*/ (0, jsx_runtime.jsx)("h1", {
+              children: "next/image example",
+            }),
+            /*#__PURE__*/ (0, jsx_runtime.jsx)(image_default(), {
+              src: nextjs,
+              placeholder: "blur",
+            }),
+          ],
+        });
+      }
+      var __N_SSP = true;
+      /* harmony default export */ const pages_image = ImagePage;
+
+      /***/
+    },
+
+    /***/ 3866: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(6888);
+
+      /***/
+    },
+
+    /***/ 4483: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/image",
+        function () {
+          return __webpack_require__(2388);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 6600: /***/ (module, exports, __webpack_require__) => {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -158,17 +271,17 @@
         __webpack_require__(9507)
       );
       const _head = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(6705)
+        __webpack_require__(7505)
       );
-      const _getimgprops = __webpack_require__(3556);
-      const _imageconfig = __webpack_require__(3157);
-      const _imageconfigcontextsharedruntime = __webpack_require__(9323);
-      const _warnonce = __webpack_require__(6173);
-      const _routercontextsharedruntime = __webpack_require__(6046);
+      const _getimgprops = __webpack_require__(9588);
+      const _imageconfig = __webpack_require__(2645);
+      const _imageconfigcontextsharedruntime = __webpack_require__(5451);
+      const _warnonce = __webpack_require__(7549);
+      const _routercontextsharedruntime = __webpack_require__(5470);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(3744)
+        __webpack_require__(1744)
       );
-      const _usemergedref = __webpack_require__(2263);
+      const _usemergedref = __webpack_require__(1511);
       // This is replaced by webpack define plugin
       const configEnv = {
         deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
@@ -495,7 +608,96 @@
       /***/
     },
 
-    /***/ 3556: /***/ (
+    /***/ 6888: /***/ (
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      0 && 0;
+      function _export(target, all) {
+        for (var name in all)
+          Object.defineProperty(target, name, {
+            enumerable: true,
+            get: all[name],
+          });
+      }
+      _export(exports, {
+        default: function () {
+          return _default;
+        },
+        getImageProps: function () {
+          return getImageProps;
+        },
+      });
+      const _interop_require_default = __webpack_require__(1532);
+      const _getimgprops = __webpack_require__(9588);
+      const _imagecomponent = __webpack_require__(6600);
+      const _imageloader = /*#__PURE__*/ _interop_require_default._(
+        __webpack_require__(1744)
+      );
+      function getImageProps(imgProps) {
+        const { props } = (0, _getimgprops.getImgProps)(imgProps, {
+          defaultLoader: _imageloader.default,
+          // This is replaced by webpack define plugin
+          imgConf: {
+            deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
+            imageSizes: [32, 48, 64, 96, 128, 256, 384],
+            qualities: [75],
+            path: "/_next/image",
+            loader: "default",
+            dangerouslyAllowSVG: false,
+            unoptimized: false,
+          },
+        });
+        // Normally we don't care about undefined props because we pass to JSX,
+        // but this exported function could be used by the end user for anything
+        // so we delete undefined props to clean it up a little.
+        for (const [key, value] of Object.entries(props)) {
+          if (value === undefined) {
+            delete props[key];
+          }
+        }
+        return {
+          props,
+        };
+      }
+      const _default = _imagecomponent.Image; //# sourceMappingURL=image-external.js.map
+
+      /***/
+    },
+
+    /***/ 7054: /***/ (__unused_webpack_module, exports) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "findClosestQuality", {
+        enumerable: true,
+        get: function () {
+          return findClosestQuality;
+        },
+      });
+      function findClosestQuality(quality, config) {
+        const q = quality || 75;
+        if (!config?.qualities?.length) {
+          return q;
+        }
+        return config.qualities.reduce(
+          (prev, cur) => (Math.abs(cur - q) < Math.abs(prev - q) ? cur : prev),
+          0
+        );
+      } //# sourceMappingURL=find-closest-quality.js.map
+
+      /***/
+    },
+
+    /***/ 9588: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -511,9 +713,9 @@
           return getImgProps;
         },
       });
-      const _warnonce = __webpack_require__(6173);
-      const _imageblursvg = __webpack_require__(1713);
-      const _imageconfig = __webpack_require__(3157);
+      const _warnonce = __webpack_require__(7549);
+      const _imageblursvg = __webpack_require__(881);
+      const _imageconfig = __webpack_require__(2645);
       const VALID_LOADING_VALUES =
         /* unused pure expression or super */ null && [
           "lazy",
@@ -943,215 +1145,13 @@
 
       /***/
     },
-
-    /***/ 3744: /***/ (
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "default", {
-        enumerable: true,
-        get: function () {
-          return _default;
-        },
-      });
-      const _findclosestquality = __webpack_require__(8494);
-      function defaultLoader({ config, src, width, quality }) {
-        if (
-          src.startsWith("/") &&
-          src.includes("?") &&
-          config.localPatterns?.length === 1 &&
-          config.localPatterns[0].pathname === "**" &&
-          config.localPatterns[0].search === ""
-        ) {
-          throw Object.defineProperty(
-            new Error(
-              `Image with src "${src}" is using a query string which is not configured in images.localPatterns.` +
-                `\nRead more: https://nextjs.org/docs/messages/next-image-unconfigured-localpatterns`
-            ),
-            "__NEXT_ERROR_CODE",
-            {
-              value: "E871",
-              enumerable: false,
-              configurable: true,
-            }
-          );
-        }
-        if (false) {
-        }
-        const q = (0, _findclosestquality.findClosestQuality)(quality, config);
-        return `${config.path}?url=${encodeURIComponent(
-          src
-        )}&w=${width}&q=${q}${
-          src.startsWith("/_next/static/media/") && false ? 0 : ""
-        }`;
-      }
-      // We use this to determine if the import is the default loader
-      // or a custom loader defined by the user in next.config.js
-      defaultLoader.__next_img_default = true;
-      const _default = defaultLoader; //# sourceMappingURL=image-loader.js.map
-
-      /***/
-    },
-
-    /***/ 4292: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(7896);
-
-      /***/
-    },
-
-    /***/ 5999: /***/ (
-      __unused_webpack_module,
-      __webpack_exports__,
-      __webpack_require__
-    ) => {
-      "use strict";
-      // ESM COMPAT FLAG
-      __webpack_require__.r(__webpack_exports__);
-
-      // EXPORTS
-      __webpack_require__.d(__webpack_exports__, {
-        __N_SSP: () => /* binding */ __N_SSP,
-        default: () => /* binding */ pages_image,
-      });
-
-      // EXTERNAL MODULE: ./node_modules/.pnpm/react@19.2.0/node_modules/react/jsx-runtime.js
-      var jsx_runtime = __webpack_require__(1503);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.2.0_react@19.2.0__react@19.2.0/node_modules/next/image.js
-      var next_image = __webpack_require__(4292);
-      var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // ./pages/nextjs.png
-      /* harmony default export */ const nextjs = {
-        src: "/_next/static/media/nextjs.cae0b805.png",
-        height: 1347,
-        width: 1626,
-        blurDataURL:
-          "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAHCAMAAAACh/xsAAAAD1BMVEX////x8fH6+vrb29vo6Oh8o70bAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAH0lEQVR4nGNgwARMjIyMjCAGCzMzMwsTRISJCcRABwAEcAAkLCQfgAAAAABJRU5ErkJggg==",
-        blurWidth: 8,
-        blurHeight: 7,
-      }; // ./pages/image.js
-      function ImagePage(props) {
-        return /*#__PURE__*/ (0, jsx_runtime.jsxs)(jsx_runtime.Fragment, {
-          children: [
-            /*#__PURE__*/ (0, jsx_runtime.jsx)("h1", {
-              children: "next/image example",
-            }),
-            /*#__PURE__*/ (0, jsx_runtime.jsx)(image_default(), {
-              src: nextjs,
-              placeholder: "blur",
-            }),
-          ],
-        });
-      }
-      var __N_SSP = true;
-      /* harmony default export */ const pages_image = ImagePage;
-
-      /***/
-    },
-
-    /***/ 7896: /***/ (
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      0 && 0;
-      function _export(target, all) {
-        for (var name in all)
-          Object.defineProperty(target, name, {
-            enumerable: true,
-            get: all[name],
-          });
-      }
-      _export(exports, {
-        default: function () {
-          return _default;
-        },
-        getImageProps: function () {
-          return getImageProps;
-        },
-      });
-      const _interop_require_default = __webpack_require__(1532);
-      const _getimgprops = __webpack_require__(3556);
-      const _imagecomponent = __webpack_require__(2728);
-      const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(3744)
-      );
-      function getImageProps(imgProps) {
-        const { props } = (0, _getimgprops.getImgProps)(imgProps, {
-          defaultLoader: _imageloader.default,
-          // This is replaced by webpack define plugin
-          imgConf: {
-            deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
-            imageSizes: [32, 48, 64, 96, 128, 256, 384],
-            qualities: [75],
-            path: "/_next/image",
-            loader: "default",
-            dangerouslyAllowSVG: false,
-            unoptimized: false,
-          },
-        });
-        // Normally we don't care about undefined props because we pass to JSX,
-        // but this exported function could be used by the end user for anything
-        // so we delete undefined props to clean it up a little.
-        for (const [key, value] of Object.entries(props)) {
-          if (value === undefined) {
-            delete props[key];
-          }
-        }
-        return {
-          props,
-        };
-      }
-      const _default = _imagecomponent.Image; //# sourceMappingURL=image-external.js.map
-
-      /***/
-    },
-
-    /***/ 8494: /***/ (__unused_webpack_module, exports) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "findClosestQuality", {
-        enumerable: true,
-        get: function () {
-          return findClosestQuality;
-        },
-      });
-      function findClosestQuality(quality, config) {
-        const q = quality || 75;
-        if (!config?.qualities?.length) {
-          return q;
-        }
-        return config.qualities.reduce(
-          (prev, cur) => (Math.abs(cur - q) < Math.abs(prev - q) ? cur : prev),
-          0
-        );
-      } //# sourceMappingURL=find-closest-quality.js.map
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(797)
+      __webpack_exec__(4483)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -1,7 +1,338 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [4672],
   {
-    /***/ 69: /***/ (module, exports, __webpack_require__) => {
+    /***/ 1511: /***/ (module, exports, __webpack_require__) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "useMergedRef", {
+        enumerable: true,
+        get: function () {
+          return useMergedRef;
+        },
+      });
+      const _react = __webpack_require__(2223);
+      function useMergedRef(refA, refB) {
+        const cleanupA = (0, _react.useRef)(null);
+        const cleanupB = (0, _react.useRef)(null);
+        // NOTE: In theory, we could skip the wrapping if only one of the refs is non-null.
+        // (this happens often if the user doesn't pass a ref to Link/Form/Image)
+        // But this can cause us to leak a cleanup-ref into user code (previously via `<Link legacyBehavior>`),
+        // and the user might pass that ref into ref-merging library that doesn't support cleanup refs
+        // (because it hasn't been updated for React 19)
+        // which can then cause things to blow up, because a cleanup-returning ref gets called with `null`.
+        // So in practice, it's safer to be defensive and always wrap the ref, even on React 19.
+        return (0, _react.useCallback)(
+          (current) => {
+            if (current === null) {
+              const cleanupFnA = cleanupA.current;
+              if (cleanupFnA) {
+                cleanupA.current = null;
+                cleanupFnA();
+              }
+              const cleanupFnB = cleanupB.current;
+              if (cleanupFnB) {
+                cleanupB.current = null;
+                cleanupFnB();
+              }
+            } else {
+              if (refA) {
+                cleanupA.current = applyRef(refA, current);
+              }
+              if (refB) {
+                cleanupB.current = applyRef(refB, current);
+              }
+            }
+          },
+          [refA, refB]
+        );
+      }
+      function applyRef(refA, current) {
+        if (typeof refA === "function") {
+          const cleanup = refA(current);
+          if (typeof cleanup === "function") {
+            return cleanup;
+          } else {
+            return () => refA(null);
+          }
+        } else {
+          refA.current = current;
+          return () => {
+            refA.current = null;
+          };
+        }
+      }
+      if (
+        (typeof exports.default === "function" ||
+          (typeof exports.default === "object" && exports.default !== null)) &&
+        typeof exports.default.__esModule === "undefined"
+      ) {
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true,
+        });
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
+      } //# sourceMappingURL=use-merged-ref.js.map
+
+      /***/
+    },
+
+    /***/ 2025: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/link",
+        function () {
+          return __webpack_require__(4591);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 3267: /***/ (module, exports, __webpack_require__) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "getDomainLocale", {
+        enumerable: true,
+        get: function () {
+          return getDomainLocale;
+        },
+      });
+      const _normalizetrailingslash = __webpack_require__(2371);
+      const basePath =
+        /* unused pure expression or super */ null && (false || "");
+      function getDomainLocale(path, locale, locales, domainLocales) {
+        if (false) {
+        } else {
+          return false;
+        }
+      }
+      if (
+        (typeof exports.default === "function" ||
+          (typeof exports.default === "object" && exports.default !== null)) &&
+        typeof exports.default.__esModule === "undefined"
+      ) {
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true,
+        });
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
+      } //# sourceMappingURL=get-domain-locale.js.map
+
+      /***/
+    },
+
+    /***/ 4591: /***/ (
+      __unused_webpack_module,
+      __webpack_exports__,
+      __webpack_require__
+    ) => {
+      "use strict";
+      __webpack_require__.r(__webpack_exports__);
+      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
+        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
+        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
+        /* harmony export */
+      });
+      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
+        __webpack_require__(1503);
+      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ =
+        __webpack_require__(6929);
+      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default =
+        /*#__PURE__*/ __webpack_require__.n(
+          next_link__WEBPACK_IMPORTED_MODULE_1__
+        );
+
+      function aLink(props) {
+        return /*#__PURE__*/ (0,
+        react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)("div", {
+          children: [
+            /*#__PURE__*/ (0,
+            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("h3", {
+              children: "A Link page!",
+            }),
+            /*#__PURE__*/ (0,
+            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
+              next_link__WEBPACK_IMPORTED_MODULE_1___default(),
+              {
+                href: "/",
+                children: "Go to /",
+              }
+            ),
+          ],
+        });
+      }
+      var __N_SSP = true;
+      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = aLink;
+
+      /***/
+    },
+
+    /***/ 6929: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(8885);
+
+      /***/
+    },
+
+    /***/ 7686: /***/ (module, exports, __webpack_require__) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "useIntersection", {
+        enumerable: true,
+        get: function () {
+          return useIntersection;
+        },
+      });
+      const _react = __webpack_require__(2223);
+      const _requestidlecallback = __webpack_require__(901);
+      const hasIntersectionObserver =
+        typeof IntersectionObserver === "function";
+      const observers = new Map();
+      const idList = [];
+      function createObserver(options) {
+        const id = {
+          root: options.root || null,
+          margin: options.rootMargin || "",
+        };
+        const existing = idList.find(
+          (obj) => obj.root === id.root && obj.margin === id.margin
+        );
+        let instance;
+        if (existing) {
+          instance = observers.get(existing);
+          if (instance) {
+            return instance;
+          }
+        }
+        const elements = new Map();
+        const observer = new IntersectionObserver((entries) => {
+          entries.forEach((entry) => {
+            const callback = elements.get(entry.target);
+            const isVisible =
+              entry.isIntersecting || entry.intersectionRatio > 0;
+            if (callback && isVisible) {
+              callback(isVisible);
+            }
+          });
+        }, options);
+        instance = {
+          id,
+          observer,
+          elements,
+        };
+        idList.push(id);
+        observers.set(id, instance);
+        return instance;
+      }
+      function observe(element, callback, options) {
+        const { id, observer, elements } = createObserver(options);
+        elements.set(element, callback);
+        observer.observe(element);
+        return function unobserve() {
+          elements.delete(element);
+          observer.unobserve(element);
+          // Destroy observer when there's nothing left to watch:
+          if (elements.size === 0) {
+            observer.disconnect();
+            observers.delete(id);
+            const index = idList.findIndex(
+              (obj) => obj.root === id.root && obj.margin === id.margin
+            );
+            if (index > -1) {
+              idList.splice(index, 1);
+            }
+          }
+        };
+      }
+      function useIntersection({ rootRef, rootMargin, disabled }) {
+        const isDisabled = disabled || !hasIntersectionObserver;
+        const [visible, setVisible] = (0, _react.useState)(false);
+        const elementRef = (0, _react.useRef)(null);
+        const setElement = (0, _react.useCallback)((element) => {
+          elementRef.current = element;
+        }, []);
+        (0, _react.useEffect)(() => {
+          if (hasIntersectionObserver) {
+            if (isDisabled || visible) return;
+            const element = elementRef.current;
+            if (element && element.tagName) {
+              const unobserve = observe(
+                element,
+                (isVisible) => isVisible && setVisible(isVisible),
+                {
+                  root: rootRef?.current,
+                  rootMargin,
+                }
+              );
+              return unobserve;
+            }
+          } else {
+            if (!visible) {
+              const idleCallback = (0,
+              _requestidlecallback.requestIdleCallback)(() => setVisible(true));
+              return () =>
+                (0, _requestidlecallback.cancelIdleCallback)(idleCallback);
+            }
+          }
+          // eslint-disable-next-line react-hooks/exhaustive-deps
+        }, [isDisabled, rootMargin, rootRef, visible, elementRef.current]);
+        const resetVisible = (0, _react.useCallback)(() => {
+          setVisible(false);
+        }, []);
+        return [setElement, visible, resetVisible];
+      }
+      if (
+        (typeof exports.default === "function" ||
+          (typeof exports.default === "object" && exports.default !== null)) &&
+        typeof exports.default.__esModule === "undefined"
+      ) {
+        Object.defineProperty(exports.default, "__esModule", {
+          value: true,
+        });
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
+      } //# sourceMappingURL=use-intersection.js.map
+
+      /***/
+    },
+
+    /***/ 8101: /***/ (__unused_webpack_module, exports) => {
+      "use strict";
+
+      Object.defineProperty(exports, "__esModule", {
+        value: true,
+      });
+      Object.defineProperty(exports, "errorOnce", {
+        enumerable: true,
+        get: function () {
+          return errorOnce;
+        },
+      });
+      let errorOnce = (_) => {};
+      if (false) {
+      } //# sourceMappingURL=error-once.js.map
+
+      /***/
+    },
+
+    /***/ 8885: /***/ (module, exports, __webpack_require__) => {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -28,17 +359,17 @@
       const _react = /*#__PURE__*/ _interop_require_wildcard._(
         __webpack_require__(2223)
       );
-      const _resolvehref = __webpack_require__(2275);
-      const _islocalurl = __webpack_require__(3179);
-      const _formaturl = __webpack_require__(5486);
-      const _utils = __webpack_require__(3708);
-      const _addlocale = __webpack_require__(8225);
-      const _routercontextsharedruntime = __webpack_require__(6046);
-      const _useintersection = __webpack_require__(2678);
-      const _getdomainlocale = __webpack_require__(4499);
-      const _addbasepath = __webpack_require__(7434);
-      const _usemergedref = __webpack_require__(2263);
-      const _erroronce = __webpack_require__(2197);
+      const _resolvehref = __webpack_require__(7379);
+      const _islocalurl = __webpack_require__(4843);
+      const _formaturl = __webpack_require__(9374);
+      const _utils = __webpack_require__(3116);
+      const _addlocale = __webpack_require__(8065);
+      const _routercontextsharedruntime = __webpack_require__(5470);
+      const _useintersection = __webpack_require__(7686);
+      const _getdomainlocale = __webpack_require__(3267);
+      const _addbasepath = __webpack_require__(1450);
+      const _usemergedref = __webpack_require__(1511);
+      const _erroronce = __webpack_require__(8101);
       const prefetched = new Set();
       function prefetch(router, href, as, options) {
         if (false) {
@@ -416,344 +747,13 @@
 
       /***/
     },
-
-    /***/ 2197: /***/ (__unused_webpack_module, exports) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "errorOnce", {
-        enumerable: true,
-        get: function () {
-          return errorOnce;
-        },
-      });
-      let errorOnce = (_) => {};
-      if (false) {
-      } //# sourceMappingURL=error-once.js.map
-
-      /***/
-    },
-
-    /***/ 2263: /***/ (module, exports, __webpack_require__) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "useMergedRef", {
-        enumerable: true,
-        get: function () {
-          return useMergedRef;
-        },
-      });
-      const _react = __webpack_require__(2223);
-      function useMergedRef(refA, refB) {
-        const cleanupA = (0, _react.useRef)(null);
-        const cleanupB = (0, _react.useRef)(null);
-        // NOTE: In theory, we could skip the wrapping if only one of the refs is non-null.
-        // (this happens often if the user doesn't pass a ref to Link/Form/Image)
-        // But this can cause us to leak a cleanup-ref into user code (previously via `<Link legacyBehavior>`),
-        // and the user might pass that ref into ref-merging library that doesn't support cleanup refs
-        // (because it hasn't been updated for React 19)
-        // which can then cause things to blow up, because a cleanup-returning ref gets called with `null`.
-        // So in practice, it's safer to be defensive and always wrap the ref, even on React 19.
-        return (0, _react.useCallback)(
-          (current) => {
-            if (current === null) {
-              const cleanupFnA = cleanupA.current;
-              if (cleanupFnA) {
-                cleanupA.current = null;
-                cleanupFnA();
-              }
-              const cleanupFnB = cleanupB.current;
-              if (cleanupFnB) {
-                cleanupB.current = null;
-                cleanupFnB();
-              }
-            } else {
-              if (refA) {
-                cleanupA.current = applyRef(refA, current);
-              }
-              if (refB) {
-                cleanupB.current = applyRef(refB, current);
-              }
-            }
-          },
-          [refA, refB]
-        );
-      }
-      function applyRef(refA, current) {
-        if (typeof refA === "function") {
-          const cleanup = refA(current);
-          if (typeof cleanup === "function") {
-            return cleanup;
-          } else {
-            return () => refA(null);
-          }
-        } else {
-          refA.current = current;
-          return () => {
-            refA.current = null;
-          };
-        }
-      }
-      if (
-        (typeof exports.default === "function" ||
-          (typeof exports.default === "object" && exports.default !== null)) &&
-        typeof exports.default.__esModule === "undefined"
-      ) {
-        Object.defineProperty(exports.default, "__esModule", {
-          value: true,
-        });
-        Object.assign(exports.default, exports);
-        module.exports = exports.default;
-      } //# sourceMappingURL=use-merged-ref.js.map
-
-      /***/
-    },
-
-    /***/ 2369: /***/ (
-      __unused_webpack_module,
-      __webpack_exports__,
-      __webpack_require__
-    ) => {
-      "use strict";
-      __webpack_require__.r(__webpack_exports__);
-      /* harmony export */ __webpack_require__.d(__webpack_exports__, {
-        /* harmony export */ __N_SSP: () => /* binding */ __N_SSP,
-        /* harmony export */ default: () => __WEBPACK_DEFAULT_EXPORT__,
-        /* harmony export */
-      });
-      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
-        __webpack_require__(1503);
-      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(6691);
-      /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default =
-        /*#__PURE__*/ __webpack_require__.n(
-          next_link__WEBPACK_IMPORTED_MODULE_1__
-        );
-
-      function aLink(props) {
-        return /*#__PURE__*/ (0,
-        react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)("div", {
-          children: [
-            /*#__PURE__*/ (0,
-            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)("h3", {
-              children: "A Link page!",
-            }),
-            /*#__PURE__*/ (0,
-            react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(
-              next_link__WEBPACK_IMPORTED_MODULE_1___default(),
-              {
-                href: "/",
-                children: "Go to /",
-              }
-            ),
-          ],
-        });
-      }
-      var __N_SSP = true;
-      /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = aLink;
-
-      /***/
-    },
-
-    /***/ 2678: /***/ (module, exports, __webpack_require__) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "useIntersection", {
-        enumerable: true,
-        get: function () {
-          return useIntersection;
-        },
-      });
-      const _react = __webpack_require__(2223);
-      const _requestidlecallback = __webpack_require__(4213);
-      const hasIntersectionObserver =
-        typeof IntersectionObserver === "function";
-      const observers = new Map();
-      const idList = [];
-      function createObserver(options) {
-        const id = {
-          root: options.root || null,
-          margin: options.rootMargin || "",
-        };
-        const existing = idList.find(
-          (obj) => obj.root === id.root && obj.margin === id.margin
-        );
-        let instance;
-        if (existing) {
-          instance = observers.get(existing);
-          if (instance) {
-            return instance;
-          }
-        }
-        const elements = new Map();
-        const observer = new IntersectionObserver((entries) => {
-          entries.forEach((entry) => {
-            const callback = elements.get(entry.target);
-            const isVisible =
-              entry.isIntersecting || entry.intersectionRatio > 0;
-            if (callback && isVisible) {
-              callback(isVisible);
-            }
-          });
-        }, options);
-        instance = {
-          id,
-          observer,
-          elements,
-        };
-        idList.push(id);
-        observers.set(id, instance);
-        return instance;
-      }
-      function observe(element, callback, options) {
-        const { id, observer, elements } = createObserver(options);
-        elements.set(element, callback);
-        observer.observe(element);
-        return function unobserve() {
-          elements.delete(element);
-          observer.unobserve(element);
-          // Destroy observer when there's nothing left to watch:
-          if (elements.size === 0) {
-            observer.disconnect();
-            observers.delete(id);
-            const index = idList.findIndex(
-              (obj) => obj.root === id.root && obj.margin === id.margin
-            );
-            if (index > -1) {
-              idList.splice(index, 1);
-            }
-          }
-        };
-      }
-      function useIntersection({ rootRef, rootMargin, disabled }) {
-        const isDisabled = disabled || !hasIntersectionObserver;
-        const [visible, setVisible] = (0, _react.useState)(false);
-        const elementRef = (0, _react.useRef)(null);
-        const setElement = (0, _react.useCallback)((element) => {
-          elementRef.current = element;
-        }, []);
-        (0, _react.useEffect)(() => {
-          if (hasIntersectionObserver) {
-            if (isDisabled || visible) return;
-            const element = elementRef.current;
-            if (element && element.tagName) {
-              const unobserve = observe(
-                element,
-                (isVisible) => isVisible && setVisible(isVisible),
-                {
-                  root: rootRef?.current,
-                  rootMargin,
-                }
-              );
-              return unobserve;
-            }
-          } else {
-            if (!visible) {
-              const idleCallback = (0,
-              _requestidlecallback.requestIdleCallback)(() => setVisible(true));
-              return () =>
-                (0, _requestidlecallback.cancelIdleCallback)(idleCallback);
-            }
-          }
-          // eslint-disable-next-line react-hooks/exhaustive-deps
-        }, [isDisabled, rootMargin, rootRef, visible, elementRef.current]);
-        const resetVisible = (0, _react.useCallback)(() => {
-          setVisible(false);
-        }, []);
-        return [setElement, visible, resetVisible];
-      }
-      if (
-        (typeof exports.default === "function" ||
-          (typeof exports.default === "object" && exports.default !== null)) &&
-        typeof exports.default.__esModule === "undefined"
-      ) {
-        Object.defineProperty(exports.default, "__esModule", {
-          value: true,
-        });
-        Object.assign(exports.default, exports);
-        module.exports = exports.default;
-      } //# sourceMappingURL=use-intersection.js.map
-
-      /***/
-    },
-
-    /***/ 4499: /***/ (module, exports, __webpack_require__) => {
-      "use strict";
-
-      Object.defineProperty(exports, "__esModule", {
-        value: true,
-      });
-      Object.defineProperty(exports, "getDomainLocale", {
-        enumerable: true,
-        get: function () {
-          return getDomainLocale;
-        },
-      });
-      const _normalizetrailingslash = __webpack_require__(1379);
-      const basePath =
-        /* unused pure expression or super */ null && (false || "");
-      function getDomainLocale(path, locale, locales, domainLocales) {
-        if (false) {
-        } else {
-          return false;
-        }
-      }
-      if (
-        (typeof exports.default === "function" ||
-          (typeof exports.default === "object" && exports.default !== null)) &&
-        typeof exports.default.__esModule === "undefined"
-      ) {
-        Object.defineProperty(exports.default, "__esModule", {
-          value: true,
-        });
-        Object.assign(exports.default, exports);
-        module.exports = exports.default;
-      } //# sourceMappingURL=get-domain-locale.js.map
-
-      /***/
-    },
-
-    /***/ 6691: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(69);
-
-      /***/
-    },
-
-    /***/ 6771: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/link",
-        function () {
-          return __webpack_require__(2369);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(6771)
+      __webpack_exec__(2025)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>routerDirect-HASH.js</strong></summary>

```diff
@@ -1,7 +1,34 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [188],
   {
-    /***/ 97: /***/ (
+    /***/ 417: /***/ (
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/routerDirect",
+        function () {
+          return __webpack_require__(5491);
+        },
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 1840: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(3252);
+
+      /***/
+    },
+
+    /***/ 5491: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -16,7 +43,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(1503);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(7798);
+        __webpack_require__(1840);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_router__WEBPACK_IMPORTED_MODULE_1__
@@ -35,40 +62,13 @@
 
       /***/
     },
-
-    /***/ 4283: /***/ (
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/routerDirect",
-        function () {
-          return __webpack_require__(97);
-        },
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
-    /***/ 7798: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(9300);
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(4283)
+      __webpack_exec__(417)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>script-HASH.js</strong></summary>

```diff
@@ -1,17 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [1209],
   {
-    /***/ 5964: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(2010);
-
-      /***/
-    },
-
-    /***/ 7758: /***/ (
+    /***/ 1312: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -26,7 +16,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(1503);
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(5964);
+        __webpack_require__(2398);
       /* harmony import */ var next_script__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_script__WEBPACK_IMPORTED_MODULE_1__
@@ -59,7 +49,17 @@
       /***/
     },
 
-    /***/ 8803: /***/ (
+    /***/ 2398: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(8954);
+
+      /***/
+    },
+
+    /***/ 4305: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -67,7 +67,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/script",
         function () {
-          return __webpack_require__(7758);
+          return __webpack_require__(1312);
         },
       ]);
       if (false) {
@@ -81,7 +81,7 @@
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(8803)
+      __webpack_exec__(4305)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>withRouter-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [3263],
   {
-    /***/ 184: /***/ (
+    /***/ 358: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -16,7 +16,7 @@
       /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ =
         __webpack_require__(1503);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ =
-        __webpack_require__(7798);
+        __webpack_require__(1840);
       /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default =
         /*#__PURE__*/ __webpack_require__.n(
           next_router__WEBPACK_IMPORTED_MODULE_1__
@@ -35,7 +35,17 @@
       /***/
     },
 
-    /***/ 3163: /***/ (
+    /***/ 1840: /***/ (
+      module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) => {
+      module.exports = __webpack_require__(3252);
+
+      /***/
+    },
+
+    /***/ 4041: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -43,7 +53,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/withRouter",
         function () {
-          return __webpack_require__(184);
+          return __webpack_require__(358);
         },
       ]);
       if (false) {
@@ -51,23 +61,13 @@
 
       /***/
     },
-
-    /***/ 7798: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(9300);
-
-      /***/
-    },
   },
   /******/ (__webpack_require__) => {
     // webpackRuntimeModules
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [636, 6593, 8792], () =>
-      __webpack_exec__(3163)
+      __webpack_exec__(4041)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>436-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>9760-HASH.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 4e0b90c48e40760e1b62505a5707f7b96dad5580

File: crates/next-code-frame/src/frame.rs [hunk 1]
```diff
@@ -0,0 +1,504 @@
...
+///
+/// This follows standard programming range conventions `[start, end)`.
+///
+/// Example: To mark "123" at byte columns 11-13, use:
+/// ```ignore
+/// CodeFrameLocation {
+///     start: Location { line: 1, column: Some(11) },
+///     end: Some(Location { line: 1, column: Some(14) }),  // Exclusive
+/// }
+/// ```
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: this doc is too verbose

File: crates/next-code-frame/src/frame.rs [hunk 2]
```diff
@@ -0,0 +1,504 @@
...
+    start_line: usize,
+    end_line: usize,
+    column_offset: usize,
+    available_code_width: usize,
+) -> (usize, usize) {
+    // Allow columns to go one past line length (pointing after last char)
+    let max_col = line_length + 1;
+
+    // Determine the column range to mark on this line:
+    // We use exclusive ranges [start, end) internally
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: half-open is more accurate then exclusive

File: crates/next-code-frame/src/frame.rs [hunk 3]
```diff
@@ -0,0 +1,504 @@
...
+
+fn calculate_marker_position(
+    location_start_column: usize,
+    end_column: usize,
+    line_length: usize,
+    line_idx: usize,
+    start_line: usize,
+    end_line: usize,
+    column_offset: usize,
+    available_code_width: usize,
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: this API is too complex consider simplifications

File: crates/next-code-frame/src/frame.rs [hunk 4]
```diff
@@ -0,0 +1,504 @@
...
+        (location_start_column, line_length)
+    } else {
+        // Last line of multiline: mark from column 1 to end.column (exclusive)
+        (1, end_column)
+    };
+
+    // Clamp to reasonable bounds
+    let range_start = range_start.min(max_col);
+    // Allow small extension past line for off-by-one, but prevent excessive spans
+    let reasonable_max = max_col + 1;
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: simplify by inlining this variable, i also don't understadn the `+1` justification

File: crates/next-code-frame/src/frame.rs [hunk 5]
```diff
@@ -0,0 +1,504 @@
...
+    let marker_col = if column_offset > 0 {
+        // Convert original column to display column
+        // formula: display_col = (original_col - offset) + 4
+        // where 4 accounts for the "..." prefix (3 chars) plus 1-indexing
+        if range_start < column_offset {
+            // Error starts before visible window, mark from column 4 (after "...")
+            4
+        } else {
+            // Error starts in visible window
+            (range_start - column_offset) + 4
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: extact a `const` for `4`

File: crates/next-code-frame/src/frame.rs [hunk 6]
```diff
@@ -0,0 +1,504 @@
...
+        // No truncation, use column as-is
+        range_start.max(1)
+    };
+
+    // If range is invalid (end <= start), show single marker at start
+    let marker_length = if range_end > range_start {
+        range_end - range_start
+    } else {
+        1
+    };
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: this could be a saturating subtraction + a `min(1)`

File: crates/next-code-frame/src/frame.rs [hunk 7]
```diff
@@ -0,0 +1,504 @@
...
+
+    // Adjust marker_length if it would extend past available width
+    let marker_length = marker_length.min(available_code_width.saturating_sub(marker_col - 1));
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: justify this `-1`

File: crates/next-code-frame/src/frame.rs [hunk 8]
```diff
@@ -0,0 +1,504 @@
...
+    }
+
+    // Split source into lines, preserving trailing empty line.
+    // `str::lines()` strips a trailing newline — "foo\n" yields ["foo"] not ["foo", ""].
+    // Use `split('\n')` so that error locations pointing at the last line after a
+    // trailing newline still resolve correctly. Strip trailing '\r' for Windows line endings.
+    let lines: Vec<&str> = source
+        .split('\n')
+        .map(|l| l.strip_suffix('\r').unwrap_or(l))
+        .collect();
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: would it be simpler to use a regex? `[\r]\n`?

File: crates/next-code-frame/src/frame.rs [hunk 9]
```diff
@@ -0,0 +1,504 @@
...
+
+    // Validate location
+    let start_line = location.start.line.saturating_sub(1); // Convert to 0-indexed
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: idx should be in the names to clarify these are not line-nnumbers

File: crates/next-code-frame/src/frame.rs [hunk 10]
```diff
@@ -0,0 +1,504 @@
...
+    let start_column = location.start.column;
+
+    // Normalize end_column:
+    // API contract: end.column is always EXCLUSIVE (follows [start, end) convention)
+    // - If no end location, default to start.column + 1 (marks 1 char)
+    // - Otherwise use the provided end.column as-is (falling back to start + 1 if missing)
+    let end_column = match location.end {
+        Some(l) => l.column.or(start_column.map(|c| c + 1)),
+        None => start_column.map(|c| c + 1),
+    };
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: simplify this, something like `location.end.flatMap(|l|l.column).or(start_column.map(|c|c+1))`

File: crates/next-code-frame/src/frame.rs [hunk 11]
```diff
@@ -0,0 +1,504 @@
...
+
+    // For rendering, we'll clamp columns to valid ranges per-line
+
+    // Calculate window of lines to show
+    let first_line = start_line.saturating_sub(options.lines_above);
+    let last_line = (end_line + options.lines_below + 1).min(lines.len());
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: again put `idx` in the name

File: crates/next-code-frame/src/frame.rs [hunk 12]
```diff
@@ -0,0 +1,504 @@
...
+
+    // Extract syntax highlights if enabled, only for the visible line range
+    // first_line and last_line are already 0-indexed, perfect for the API
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: simplify comment

File: crates/next-code-frame/src/frame.rs [hunk 13]
```diff
@@ -0,0 +1,504 @@
...
+    let line_highlights: Vec<LineHighlight> = if options.highlight_code {
+        extract_highlights(source, first_line..last_line, options.language)
+    } else {
+        Vec::new()
+    };
+
+    // Calculate gutter width (space needed for line numbers)
+    let max_line_num = last_line;
+    let gutter_width = format!("{}", max_line_num).len();
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: there must be a simpler way to compute this... `ceil(log10(max_line_num))`?

File: crates/next-code-frame/src/frame.rs [hunk 14]
```diff
@@ -0,0 +1,504 @@
...
+
+    let max_width = options.max_width.unwrap_or_else(get_terminal_width);
+
+    // Calculate available width for code (accounting for gutter, markers, and padding)
+    // Format: "> N | code" or "  N | code"
+    // That's: 1 (marker) + 1 (space) + gutter_width + 3 (" | ")
+    let gutter_total_width = 1 + 1 + gutter_width + 3;
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: boring but we should just have 

const MARKER: &'static str = ">";

and use MARKER.len()

ditto for the `" | "` rule marker

File: crates/next-code-frame/src/frame.rs [hunk 15]
```diff
@@ -0,0 +1,504 @@
...
+    {
+        output.push_str(&" ".repeat(gutter_total_width));
+        output.push_str(color_scheme.marker);
+        output.push_str(message);
+        output.push_str(color_scheme.reset);
+        needs_newline = true;
+    }
+
+    // Render each line
+    for (line_idx, line_content) in lines.iter().enumerate().take(last_line).skip(first_line) {
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: take/skip seems a little complex... should we just iterate over `(first_line...last_line)` and fetch line content within the loop

File: crates/next-code-frame/src/frame.rs [hunk 16]
```diff
@@ -0,0 +1,504 @@
...
+        // Apply consistent truncation to all lines (all offsets in bytes)
+        let truncation = truncate_line(line_content, truncation_offset, available_code_width);
+
+        // Apply syntax highlighting if enabled
+        // line_highlights is indexed relative to first_line (0-indexed within the visible range)
+        let highlight_idx = line_idx.saturating_sub(first_line);
+        let visible_content = if options.highlight_code && highlight_idx < line_highlights.len() {
+            // Adjust highlights for truncation (byte offset, markers are byte-based)
+            let adjusted_highlight = adjust_highlights_for_truncation(
+                &line_highlights[highlight_idx],
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: linr_highlights should be an Option instead of repeating the `highlight_code` condition

additionally we can use `line_highlights.get(highlight_index)` to get an option instead of manually querying against length

and the `saturating_sub` on line 286 appears to be overly defensive, that can just be a normal subtraction

File: crates/next-code-frame/src/frame.rs [hunk 17]
```diff
@@ -0,0 +1,504 @@
...
+    // By prepending newlines instead of appending them we avoid a
+    // trailing newline that callers would have to strip.
+    let mut needs_newline = false;
+
+    // Add message if provided and no column specified
+    if let Some(ref message) = options.message
+        && start_column.is_none()
+    {
+        output.push_str(&" ".repeat(gutter_total_width));
+        output.push_str(color_scheme.marker);
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: it seems confusing that we highlight the `message` with the `marker` color

they could be the same color ofc but it should be `color_scheme.message`

File: crates/next-code-frame/src/frame.rs [hunk 18]
```diff
@@ -0,0 +1,504 @@
...
+            output.push('>');
+            output.push_str(color_scheme.reset);
+        } else {
+            output.push(' ');
+        }
+        output.push(' ');
+        output.push_str(color_scheme.gutter);
+        output.push_str(&format!("{:>width$}", line_num, width = gutter_width));
+        output.push_str(color_scheme.reset);
+        output.push_str(color_scheme.gutter);
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: there is no need to `reset` and then set `gutter` again

File: crates/next-code-frame/src/frame.rs [hunk 19]
```diff
@@ -0,0 +1,504 @@
...
+        if is_error_line && let Some(start_col) = start_column {
+            let (marker_col, marker_length) = calculate_marker_position(
+                start_col,
+                end_column.unwrap_or(start_col + 1),
+                line_content.len(),
+                line_idx,
+                start_line,
+                end_line,
+                truncation.byte_offset,
+                available_code_width,
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: seems like it should be possible to simplify this.... maybe we need an OO design?

File: crates/next-code-frame/src/frame.rs [hunk 20]
```diff
@@ -0,0 +1,504 @@
...
+            );
+
+            output.push('\n');
+            output.push(' ');
+            output.push(' ');
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: this should be one `push_str("\n   ")

File: crates/next-code-frame/src/frame.rs [hunk 21]
```diff
@@ -0,0 +1,504 @@
...
+            output.push_str(color_scheme.gutter);
+            output.push_str(&format!("{:>width$} |", "", width = gutter_width));
+            output.push_str(color_scheme.reset);
+            output.push(' ');
+            output.push_str(&" ".repeat(marker_col - 1));
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: this could be combined into 1 push_str

File: crates/next-code-frame/src/frame.rs [hunk 22]
```diff
@@ -0,0 +1,504 @@
...
+            output.push_str(color_scheme.marker);
+            output.push_str(&"^".repeat(marker_length));
+            output.push_str(color_scheme.reset);
+
+            // Add message only on the last error line's marker
+            if line_idx == end_line
+                && let Some(ref message) = options.message
+            {
+                output.push(' ');
+                output.push_str(color_scheme.marker);
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: again this sohuld be `color_scheme.message`

File: crates/next-code-frame/src/frame.rs [hunk 23]
```diff
@@ -0,0 +1,504 @@
...
+                output.push_str(message);
+                output.push_str(color_scheme.reset);
+            }
+        }
+    }
+
+    Ok(output)
+}
+const ELLIPSIS: &str = "...";
+const ELLIPSIS_LEN: usize = 3;
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: this should be an expression `ELLIPSIS.len()`

File: crates/next-code-frame/src/frame.rs [hunk 24]
```diff
@@ -0,0 +1,504 @@
...
+
+/// Calculate the truncation offset (in bytes) for all lines in the window.
+/// This ensures all lines are "scrolled" to the same horizontal position, centering the error
+/// range. All column values are byte offsets.
+///
+/// NOTE: We use byte length (`line.len()`) as a proxy for display width. This is exact for
+/// ASCII but overapproximates for multi-byte UTF-8 (e.g., CJK characters are 3 bytes but
+/// 2 display columns, emoji are 4 bytes but 1-2 columns). Properly computing display widths is high
+/// complexity and requires unicode tables and font information.
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: there are a few crates that handle this correctly.  notably `string-width` and `console`.  This should be a TODO

File: crates/next-code-frame/src/frame.rs [hunk 25]
```diff
@@ -0,0 +1,504 @@
...
+/// Snap a byte offset backward to the nearest UTF-8 character boundary.
+/// Returns the largest value <= `offset` that is a valid char boundary.
+fn snap_to_char_boundary_back(line: &str, offset: usize) -> usize {
+    let offset = offset.min(line.len());
+    let mut pos = offset;
+    while pos > 0 && !line.is_char_boundary(pos) {
+        pos -= 1;
+    }
+    pos
+}
```
Comment (lukesandberg) [inline crates/next-code-frame/src/frame.rs]: we should have some simple unit tests for these, in fact there might be library methods for these

File: crates/next-code-frame/src/highlight.rs [hunk 26]
```diff
@@ -0,0 +1,1460 @@
...
+// ---------------------------------------------------------------------------
+
+/// Compute the byte offset of each line start (0-indexed) in the source.
+/// The first entry is always 0 (the start of the first line).
+fn compute_line_starts(source: &str) -> Vec<usize> {
+    let mut starts = vec![0usize];
+    for (i, b) in source.bytes().enumerate() {
+        if b == b'\n' {
+            starts.push(i + 1);
+        }
```
Comment (lukesandberg) [inline crates/next-code-frame/src/highlight.rs]: there should be a faster way to do this that desugars to memchr calls...

File: crates/next-code-frame/src/highlight.rs [hunk 27]
```diff
@@ -0,0 +1,1460 @@
...
+
+    let (range_start, range_end) = byte_range;
+    if end <= range_start || start >= range_end {
+        return;
+    }
+
+    let start_line = lookup_line(line_starts, start);
+    let end_line = lookup_line(line_starts, end.saturating_sub(1));
+
+    if start_line != end_line {
```
Comment (lukesandberg) [inline crates/next-code-frame/src/highlight.rs]: need a short comment on this algorithm

basically if a marker spans a line boundary we want break the pair into a sequence of paiirs for each line in the range so they don't interfere with gutter drawing

File: crates/next-code-frame/src/highlight.rs [hunk 28]
```diff
@@ -0,0 +1,1460 @@
...
+///
+/// # Parameters
+/// - `source`: The source code to highlight
+/// - `line_range`: Range of line indices (0-indexed, start inclusive, end exclusive). Style markers
+///   are only produced for lines within this range. Pass `0..usize::MAX` to produce markers for all
+///   lines.
+pub fn extract_highlights(
+    source: &str,
+    line_range: Range<usize>,
+    language: Language,
```
Comment (lukesandberg) [inline crates/next-code-frame/src/highlight.rs:534]: maybe instead of language, we should just be passed a set of keywords?

File: crates/next-code-frame/src/highlight.rs [hunk 29]
```diff
@@ -0,0 +1,1460 @@
...
+        } else {
+            source.len()
+        };
+
+        (start_byte, end_byte)
+    };
+
+    let mut all_markers = extract_markers(source, &line_starts, byte_range, language);
+
+    all_markers.sort();
```
Comment (lukesandberg) [inline crates/next-code-frame/src/highlight.rs]: isn't it by definition already sorted?

File: crates/next-code-frame/src/highlight.rs [hunk 30]
```diff
@@ -0,0 +1,1460 @@
...
+/// Otherwise it returns `scan_end`.
+fn scan_tokens(
+    markers: &mut Vec<StyleMarker>,
+    line_starts: &[usize],
+    source: &str,
+    byte_range: (usize, usize),
+    language: Language,
+    start_pos: usize,
+    scan_end: usize,
+    mut brace_depth: u32,
```
Comment (lukesandberg) [inline crates/next-code-frame/src/highlight.rs]: this should probably be an Option<u32> instead of `0` being special

File: crates/next-code-frame/src/highlight.rs [hunk 31]
```diff
@@ -0,0 +1,1460 @@
...
+                    line_starts,
+                    len,
+                    start,
+                    end,
+                    TokenType::Comment,
+                    byte_range,
+                );
+                // Comments don't update last_token
+            }
+            GRP_POSTFIX => {
```
Comment (lukesandberg) [inline crates/next-code-frame/src/highlight.rs]: why do we need this case?

File: crates/next-code-frame/src/highlight.rs [hunk 32]
```diff
@@ -0,0 +1,1460 @@
...
+        r"|",
+        // Numbers: hex, octal, binary, then decimal (with optional fraction/exponent)
+        r"(?P<number>0[xX][\da-fA-F]+|0[oO][0-7]+|0[bB][01]+|(?:\d*\.\d+|\d+\.?)(?:[eE][+-]?\d+)?)",
+        r"|",
+        // Identifiers: letter/$/_/non-ASCII start, continue with alphanumeric/$/_/non-ASCII
+        r"(?P<ident>[A-Za-z_$\x80-\xff][\w$\x80-\xff]*)",
+        r"|",
+        r"(?P<close>[)\]])",
+        r"|",
+        r"(?P<open>[(\[{}])",
```
Comment (lukesandberg) [inline crates/next-code-frame/src/highlight.rs]: it is confusing that `open` contains `}` should it be in `close`?

File: crates/next-code-frame/src/highlight.rs [hunk 33]
```diff
@@ -0,0 +1,1460 @@
...
+    CloseBracket,
+    /// `++` or `--` — postfix operators end expressions
+    PostfixOp,
+    /// Operators, open brackets, commas, semicolons, `{`, `}` — regex follows
+    Operator,
+}
+
+impl LastToken {
+    /// Returns true if a `/` at this position should be treated as starting a regex literal.
+    fn expects_regex(self) -> bool {
```
Comment (lukesandberg) [inline crates/next-code-frame/src/highlight.rs]: this name is a bit confusing, maybe `slash_means_regex`?

File: crates/next-code-frame/src/highlight.rs [hunk 34]
```diff
@@ -0,0 +1,1460 @@
...
+
+// ---------------------------------------------------------------------------
+// Marker → LineHighlight grouping
+// ---------------------------------------------------------------------------
+
+/// Group markers by line using line_starts lookup.
+/// Complexity: O(markers + lines) using a single pass with marker index.
+/// Only returns LineHighlight entries for lines within the specified range.
+fn group_markers_by_line(
+    markers: &[StyleMarker],
```
Comment (lukesandberg) [inline crates/next-code-frame/src/highlight.rs]: isn't it the case that markers only contains markers in the valid range? it is already filtered

File: crates/next-code-frame/src/highlight.rs [hunk 35]
```diff
@@ -0,0 +1,1460 @@
...
+
+        while marker_idx < markers.len() {
+            let marker = &markers[marker_idx];
+            let abs_offset = marker.offset;
+
+            if abs_offset >= line_end {
+                break;
+            }
+            if abs_offset < line_start {
+                marker_idx += 1;
```
Comment (lukesandberg) [inline crates/next-code-frame/src/highlight.rs]: is this case really possible?

File: crates/next-code-frame/src/highlight.rs [hunk 36]
```diff
@@ -0,0 +1,1460 @@
...
+        }
+    }
+}
+
+// ---------------------------------------------------------------------------
+// Marker → LineHighlight grouping
+// ---------------------------------------------------------------------------
+
+/// Group markers by line using line_starts lookup.
+/// Complexity: O(markers + lines) using a single pass with marker index.
```
Comment (lukesandberg) [inline crates/next-code-frame/src/highlight.rs]: i think the complexity is just `O(markers)`

File: crates/next-code-frame/src/highlight.rs [hunk 37]
```diff
@@ -0,0 +1,1460 @@
...
+/// Adjust line highlights for a truncated view of the line.
+/// Returns a new LineHighlight with markers adjusted for the truncation offset.
+///
+/// - `truncation_offset`: byte offset in the original line where visible source content starts
+/// - `visible_length`: byte length of the visible content string (including any "..." prefix)
+/// - `prefix_len`: byte length of any prefix added before source content (e.g., "..." = 3)
+///
+/// Markers are shifted so that offset 0 in the adjusted markers corresponds to
+/// `prefix_len` in the visible content string.
+pub fn adjust_highlights_for_truncation(
```
Comment (lukesandberg) [inline crates/next-code-frame/src/highlight.rs]: this is used in conjuction with `apply_line_highlights` i suspect it would be simpler if apply_line_highglights handled the offsets

File: crates/next-code-frame/src/highlight.rs [hunk 38]
```diff
@@ -0,0 +1,1460 @@
...
+
+    if active_style.is_some() {
+        result.push_str(color_scheme.reset);
+    }
+
+    result
+}
+
+#[cfg(test)]
+pub mod tests {
```
Comment (lukesandberg) [inline crates/next-code-frame/src/highlight.rs:1026]: there are too many tests, we should reduce to a smaller set

File: packages/next/src/build/swc/generated-native.d.ts [hunk 39]
```diff
@@ -34,6 +34,51 @@ export declare class ExternalObject<T> {
...
+  language?: string
+}
+/**
+ * Renders a code frame showing the location of an error in source code
+ *
+ * This is a Rust implementation that replaces Babel's code-frame for better:
+ * - Performance on large files
+ * - Handling of long lines
+ * - Memory efficiency
+ *
```
Comment (lukesandberg) [inline packages/next/src/build/swc/generated-native.d.ts:98]: simplify comment

File: packages/next/src/lib/typescript/diagnosticFormatter.ts [hunk 40]
```diff
@@ -374,15 +373,16 @@ export function getFormattedDiagnostic(
...
+    const codeFrame = renderCodeFrame(
+      diagnostic.file.getFullText(diagnostic.file.getSourceFile()),
+      {
+        start: { line: line, column: character },
+      },
+      { forceColor: true }
+    )
+    if (codeFrame) {
+      message += '\n' + codeFrame
+    }
```
Comment (lukesandberg) [inline packages/next/src/lib/typescript/diagnosticFormatter.ts]: simplify the diff here, we can keep the old control flow

File: packages/next/src/next-devtools/server/shared.ts [hunk 41]
```diff
@@ -68,20 +68,21 @@ export function getOriginalCodeFrame(
...
-  return codeFrameColumns(
-    source,
-    {
-      start: {
-        // 1-based, but -1 means start line without highlighting
-        line: frame.line1 ?? -1,
-        // 1-based, but 0 means whole line without column highlighting
-        column: frame.column1 ?? 0,
+  return (
+    renderCodeFrameIfNativeBindingsAvailable(
```
Comment (lukesandberg) [inline packages/next/src/next-devtools/server/shared.ts]: this should just be `renderCodeFrame`, no need to be defensive i think

File: packages/next/src/shared/lib/errors/code-frame.ts [hunk 42]
```diff
@@ -0,0 +1,38 @@
...
+ * @param options - Optional configuration
+ * @returns The formatted code frame string
+ * @throws if the native bindings have not been installed
+ */
+export function renderCodeFrame(
+  file: string,
+  location: NapiCodeFrameLocation,
+  options?: NapiCodeFrameOptions
+): string {
+  return getBindingsSync().codeFrameColumns(
```
Comment (lukesandberg) [inline packages/next/src/shared/lib/errors/code-frame.ts]: we should probably keep the name `codeFrameColumns` instead of `renderCodeFrame`

File: crates/next-code-frame/src/bin/code_frame.rs [hunk 43]
```diff
@@ -0,0 +1,99 @@
...
+    eprintln!();
+    eprintln!("Options:");
+    eprintln!("  -m, --message <MSG>  Message to display with the error");
+    eprintln!();
+    eprintln!("Examples:");
+    eprintln!("  code_frame src/app.tsx 10:5");
+    eprintln!("  code_frame src/app.tsx 10:5 10:20");
+    eprintln!("  code_frame -m \"Unexpected token\" src/app.tsx 10:5 10:20");
+    ExitCode::FAILURE
+}
```
Comment (bgw) [inline crates/next-code-frame/src/bin/code_frame.rs]: Just pull in clap? We're already using it in some other places for small test CLIs.

File: crates/next-code-frame/src/frame.rs [hunk 44]
```diff
@@ -0,0 +1,411 @@
...
+    /// 1-indexed line number
+    pub line: usize,
+    /// 1-indexed column number as byte offset
+    #[serde(default)]
+    pub column: Option<usize>,
+}
+
+/// Location information for the error in the source code.
+///
+/// Columns are 1-indexed byte offsets, half-open: `[start.column, end.column)`.
```
Comment (bgw) [inline crates/next-code-frame/src/frame.rs]: Are lines zero indexed or one indexed?

File: crates/next-code-frame/src/frame.rs [hunk 45]
```diff
@@ -0,0 +1,411 @@
...
+) -> (usize, usize) {
+    // Map source column to display column, accounting for "..." prefix
+    let display_col = if truncation_offset > 0 {
+        if col_start <= truncation_offset {
+            ELLIPSIS_DISPLAY_OFFSET
+        } else {
+            (col_start - truncation_offset) + ELLIPSIS_DISPLAY_OFFSET
+        }
+    } else {
+        col_start.max(1)
```
Comment (bgw) [inline crates/next-code-frame/src/frame.rs]: Should it be an error if `col_start` is 0? Maybe a debug assertion?

File: crates/next-code-frame/src/frame.rs [hunk 46]
```diff
@@ -0,0 +1,411 @@
...
+    location: &CodeFrameLocation,
+    options: &CodeFrameOptions,
+) -> Result<String> {
+    if source.is_empty() {
+        return Ok(String::new());
+    }
+
+    // Single O(n) scan to compute line-start offsets. This replaces both the
+    // Vec<&str> allocation that split('\n').collect() would produce and the
+    // duplicate scan inside extract_highlights.
```
Comment (bgw) [inline crates/next-code-frame/src/frame.rs]: I don't think the `Vec<&str>` allocation is worth calling out here, because this does a `Vec<usize>` allocation. That's half the size because there are no slice lengths, but it's still a vec allocation.

File: crates/next-code-frame/src/highlight.rs [hunk 47]
```diff
@@ -0,0 +1,1248 @@
...
+        Self {
+            source,
+            line_starts,
+        }
+    }
+
+    /// Number of lines.
+    pub fn len(&self) -> usize {
+        self.line_starts.len()
+    }
```
Comment (bgw) [inline crates/next-code-frame/src/highlight.rs]: Maybe make this return a `NonZeroUsize`?

File: crates/next-code-frame/src/terminal.rs [hunk 48]
```diff
@@ -0,0 +1,35 @@
...
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+
+    #[test]
+    fn test_get_terminal_width() {
+        let width = get_terminal_width();
+        assert!(width > 0);
+        assert!(width >= 80); // Should be at least 80 chars
```
Comment (bgw) [inline crates/next-code-frame/src/terminal.rs]: This assertion doesn't make sense

File: crates/next-code-frame/src/terminal.rs [hunk 49]
```diff
@@ -0,0 +1,35 @@
...
+        }
+
+        // Try platform-specific terminal size detection
+        // For now, we'll use a simple approach
+        // TODO: Add terminfo/ioctl support if needed
+    }
+
+    // Default to 140 characters
+    140
+}
```
Comment (bgw) [inline crates/next-code-frame/src/terminal.rs]: Does this even make sense if the primary display output of the code frame is the redbox in the browser?  
  
Would it make more sense for the nextjs devtools to pass a (potentially hard-coded) width value down to us, instead of us trying to figure it out here? That would be the more sans-io thing to do.

File: crates/next-code-frame/src/highlight.rs [hunk 50]
```diff
@@ -0,0 +1,1248 @@
...
+        r"(?P<brace>[(\[{}])",
+        r"|",
+        r"(?P<postfix>\+\+|--)",
+        r"|",
+        r"(?P<slash>/)",
+        r"|",
+        // Operators and punctuation: =, +, -, *, %, <, >, &, |, ^, !, ~, ?, :, ;, ,, .
+        // Catch-all so we track last_token correctly for regex disambiguation
+        r"(?P<op>[=+\-*%<>&|^!~?:;,.])",
+    ))
```
Comment (bgw) [inline crates/next-code-frame/src/highlight.rs]: There's also https://docs.rs/regex/latest/regex/struct.RegexSet.html  
\- You're already avoiding matching regex groups by name anyways, so `RegexSet` seems like a closer match to what you're trying to do?  
\- Is `regex` building a map of group names, even though you're not accessing groups by name? These could just be comments.  
  
The use of non-capturing groups is good, I think non-matching groups are slightly cheaper for `regex`.

File: crates/next-code-frame/src/highlight.rs [hunk 51]
```diff
@@ -0,0 +1,1248 @@
...
+fn scan_tokens(
+    markers: &mut Vec<StyleSpan>,
+    line_starts: &[usize],
+    source: &str,
+    byte_range: (usize, usize),
+    language: Language,
+    start_pos: usize,
+    scan_end: usize,
+    mut brace_depth: Option<u32>,
+) -> usize {
```
Comment (bgw) [inline crates/next-code-frame/src/highlight.rs]: Similar to what you're doing with the `last_token` disambiguation, you need to do something for disambiguating the first token because it could be inside a multiline comment or string.  
  
Vim uses a similar regex-based highlighter, and they've got a few approaches: https://neovim.io/doc/user/syntax.html#_11.-synchronizing  
  
The simplest would be to start tokenizing 1000 bytes before `byte_range.0`.

File: crates/next-code-frame/src/highlight.rs [hunk 52]
```diff
@@ -0,0 +1,1248 @@
...
+/// Pass `None` for top-level scanning.
+fn scan_tokens(
+    markers: &mut Vec<StyleSpan>,
+    line_starts: &[usize],
+    source: &str,
+    byte_range: (usize, usize),
+    language: Language,
+    start_pos: usize,
+    scan_end: usize,
+    mut brace_depth: Option<u32>,
```
Comment (bgw) [inline crates/next-code-frame/src/highlight.rs]: - These arguments would benefit from being part of a named struct
- What's the difference between `byte_range` and `start_pos`/`scan_end`? Are `start_pos` and `scan_end` byte offsets? Why is `byte_range` a tuple, but `start_pos` and `scan_end` separate variables?

File: crates/next-code-frame/src/frame.rs [hunk 53]
```diff
@@ -0,0 +1,411 @@
...
+    let end_column = location
+        .end
+        .and_then(|l| l.column)
+        .or(start_column.map(|c| c + 1));
+
+    // Calculate window of lines to show (0-indexed, last is exclusive)
+    let first_line_idx = start_line_idx.saturating_sub(options.lines_above);
+    let last_line_idx = (end_line_idx + options.lines_below + 1).min(lines.len());
+
+    let line_highlights = if options.highlight_code {
```
Comment (bgw) [inline crates/next-code-frame/src/frame.rs]:
```suggestion
    let line_highlights = if options.color && options.highlight_code {
```

File: crates/next-code-frame/src/frame.rs [hunk 54]
```diff
@@ -0,0 +1,411 @@
...
+    // Single O(n) scan to compute line-start offsets. This replaces both the
+    // Vec<&str> allocation that split('\n').collect() would produce and the
+    // duplicate scan inside extract_highlights.
+    let lines = Lines::new(source);
+
+    // Validate location (convert 1-indexed to 0-indexed)
+    let start_line_idx = location.start.line.saturating_sub(1);
+    if start_line_idx >= lines.len() {
+        return Ok(String::new());
+    }
```
Comment (bgw) [inline crates/next-code-frame/src/frame.rs]: Should this be an error?

File: crates/next-code-frame/src/highlight.rs [hunk 55]
```diff
@@ -0,0 +1,1248 @@
...
+    source: &'a str,
+    /// Byte offset of the start of each line. First entry is always 0.
+    line_starts: Vec<usize>,
+}
+
+impl<'a> Lines<'a> {
+    /// Build the line index by scanning for newlines.
+    pub fn new(source: &'a str) -> Self {
+        let mut line_starts = vec![0usize];
+        for pos in memchr::memchr_iter(b'\n', source.as_bytes()) {
```
Comment (bgw) [inline crates/next-code-frame/src/highlight.rs]: You could implement the spec with a regex, at some performance cost: https://tc39.es/ecma262/#sec-line-terminators  
  
These are rare, but:  
\- Apparently some emacs users like to use the paragraph separator character?  
\- Windows uses CRLF, though I guess the resulting effect would be the same as just matching on LF

File: crates/next-code-frame/src/highlight.rs [hunk 56]
```diff
@@ -0,0 +1,1248 @@
...
+    pub fn is_keyword(self, ident: &str) -> bool {
+        match self {
+            Language::JavaScript => JS_KEYWORDS.binary_search(&ident).is_ok(),
+            Language::Css => false,
+        }
+    }
+}
+
+/// JavaScript/TypeScript keywords (sorted for binary search)
+static JS_KEYWORDS: &[&str] = &[
```
Comment (bgw) [inline crates/next-code-frame/src/highlight.rs]: Add a unit test that calls `.is_sorted()`.

File: crates/next-code-frame/src/frame.rs (hunk 44 above)
Comment (lukesandberg) [reply crates/next-code-frame/src/frame.rs]: one indexed, 

this comment is redundant with field level comments which already say this.  dropping

File: crates/next-code-frame/src/highlight.rs (hunk 50 above)
Comment (lukesandberg) [reply crates/next-code-frame/src/highlight.rs]: `RegexSet` doesn't work for us

but we can use the underlying regex::automata which has a multi-pattern support that will work.

File: crates/next-code-frame/src/highlight.rs (hunk 55 above)
Comment (lukesandberg) [reply crates/next-code-frame/src/highlight.rs]: yeah windows is covered by this, but no the unicode line terminators

but looks like we can use `memchr3`!

File: crates/next-code-frame/src/highlight.rs (hunk 51 above)
Comment (lukesandberg) [reply crates/next-code-frame/src/highlight.rs]: so we always scan from the beginning but we can exit earlier

we also only add spans that overlap with the range so we don't allocate unnecessary data.

i added a comment about these synchronizing approaches but for now i will just stick with the simple approach even if it isn't as efficient

File: crates/next-code-frame/src/frame.rs (hunk 54 above)
Comment (lukesandberg) [reply crates/next-code-frame/src/frame.rs]: settled on returning `None` for out of range and invalid source information, and `bail!` for 'the location makes no sense on its own'

File: test/e2e/app-dir/server-source-maps/server-source-maps.test.ts [hunk 57]
```diff
@@ -849,7 +849,9 @@ describe('app-dir - server source maps', () => {
              "description": "ignore-listed frames",
              "environmentLabel": null,
              "label": "Console Error",
-             "source": "internal-pkg/sourcemapped.ts (9:13) @ runSetOfSets",
+             "source": "app/ssr-anonymous-stack-frame-sandwich/page.js (7:29) @ Page
+         >  7 |   runHiddenSetOfSetsInternal('ssr-anonymous-stack-frame-sandwich: internal')
+              |                             ^",
```
Comment (mischnic) [inline test/e2e/app-dir/server-source-maps/server-source-maps.test.ts:854]: Should this be actually shown?

File: crates/next-code-frame/src/tests.rs [hunk 58]
```diff
@@ -0,0 +1,914 @@
...
+
+    let result = render_for_snapshot(&source, &location, &options)
+        .unwrap()
+        .unwrap();
+    assert_snapshot!(result, @r"
+      1 | ...
+    > 2 | ...aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
+        |                                                 ^
+      3 | ...
+    ");
```
Comment (mischnic) [inline crates/next-code-frame/src/tests.rs:246]: 😍

File: test/e2e/app-dir/server-source-maps/server-source-maps.test.ts (hunk 57 above)
Comment (lukesandberg) [reply test/e2e/app-dir/server-source-maps/server-source-maps.test.ts:854]: if you look down on line 888 you can see that webpack renders the same error

so this is, afaict, addressing a small regression.

File: crates/next-code-frame/src/tests.rs (hunk 58 above)
Comment (lukesandberg) [reply crates/next-code-frame/src/tests.rs:246]: and there it is folks, the entire motivation laid bare

File: test/e2e/app-dir/server-source-maps/server-source-maps.test.ts (hunk 57 above)
Comment (lukesandberg) [reply test/e2e/app-dir/server-source-maps/server-source-maps.test.ts:854]: quite possibly it shouldn't be shown, @eps1lon is looking into issues in our frame filtering

Comment (eps1lon) [reply test/e2e/app-dir/server-source-maps/server-source-maps.test.ts:854]: Was surprised by this as well. But this is a good change 👍🏻

File: crates/next-code-frame/benches/code_frame_bench.rs
Comment (sokra) [inline crates/next-code-frame/benches/code_frame_bench.rs:1]: A "miminimized" file would be a nice benchmark addition. A file with a single very long line.

File: crates/next-code-frame/src/frame.rs [hunk 59]
```diff
@@ -0,0 +1,469 @@
...
+        bail!("start.column must be 1-indexed (got 0)");
+    }
+    if let Some(end) = location.end
+        && let Some(0) = end.column
+    {
+        bail!("end.column must be 1-indexed (got 0)");
+    }
+
+    // Convert 1-indexed line to 0-indexed. line==0 is treated as line 1.
+    let start_line_idx = location.start.line.saturating_sub(1);
```
Comment (sokra) [inline crates/next-code-frame/src/frame.rs]: That's a bit inconsistent:  
column = 0 -> error  
line = 0 -> silently changed to 1

File: crates/next-code-frame/src/highlight.rs [hunk 60]
```diff
@@ -0,0 +1,1349 @@
...
+/// Each entry pairs a `TokenKind` with its regex pattern. Order matters:
+/// earlier patterns take priority when multiple can match at the same
+/// position (e.g. `//` before `/`). The `PatternID` returned by the
+/// multi-pattern regex indexes directly into this array.
+const TOKEN_RULES: &[(TokenKind, &str)] = &[
+    (
+        TokenKind::String,
+        r#""(?:[^"\\]|\\.)*"?|'(?:[^'\\]|\\.)*'?"#,
+    ),
+    (TokenKind::Template, r"`(?:[^`\\]|\\.)*`?"),
```
Comment (sokra) [inline crates/next-code-frame/src/highlight.rs]: This doesn't correctly account for `${ ... }`.  They are not part of the template, but they could also contain other token, which should be highlighted.

Comment (sokra) [reply crates/next-code-frame/src/highlight.rs]: Ok I see `scan_template_content` partially handles this, but the regexp is still not fully correct.

```
`some${`template`}literal`

`some${ /* ` */ ""}literal`

`some${ // `
}literal`

`some${"`"}literal`
```

Comment (sokra) [reply crates/next-code-frame/src/highlight.rs]: But it is quite complex to handle that...

TokenKind::TemplateStart -> `´...${`

TokenKind::TemplateInner -> `}...${`

TokenKind::TemplateEnd -> `}...´`

TemplateInner and TemplateEnd must only be matched when inside of a TemplateStart and the `{}`\-braces count matches. We probably need a `{}`\-braces stack to track if we are inside of a template literal at this level (since we could have nested template literals).

File: crates/next-code-frame/benches/code_frame_bench.rs
Comment (lukesandberg) [reply crates/next-code-frame/benches/code_frame_bench.rs:1]: Done.  This is indeed a worst case scenario since none of our skipping logic ends up working

File: crates/next-code-frame/src/frame.rs (hunk 59 above)
Comment (lukesandberg) [reply crates/next-code-frame/src/frame.rs]: good catch, fixed

File: crates/next-code-frame/src/highlight.rs (hunk 60 above)
Comment (lukesandberg) [reply crates/next-code-frame/src/highlight.rs]: nice catch, fixed.  added some tests as well

File: crates/next-code-frame/benches/code_frame_bench.rs
Comment (lukesandberg) [reply crates/next-code-frame/benches/code_frame_bench.rs:1]: but this does point out one simple opportunity, so it is now ~2x as fast and regular files with long lines will also get a small boost

File: packages/next/src/next-devtools/dev-overlay/styles/colors.css [hunk 61]
```diff
@@ -1,17 +1,19 @@
...
    *
-   * For example, in @babel/code-frame, the "keyword" is mapped to ANSI "cyan".
-   * We want the "keyword" to use the "syntax-keyword" color in the theme.
-   * So, we map the "cyan" to the "syntax-keyword" in the theme.
+   * next-code-frame color scheme:
+   *   cyan (36m):    keywords (const, function, return, etc.)
+   *   yellow (33m):  capitalized identifiers (Component names, types)
+   *   magenta (35m): numbers, regex literals
+   *   green (32m):   strings
+   *   gray (90m):    comments, gutter
```
Comment (bgw) [inline packages/next/src/next-devtools/dev-overlay/styles/colors.css:12]: We could change this?

File: crates/next-code-frame/src/tests.rs [hunk 62]
```diff
@@ -0,0 +1,914 @@
...
+        highlight_code: false,
+        ..Default::default()
+    };
+
+    let result = render_for_snapshot(source, &location, &options)
+        .unwrap()
+        .unwrap();
+    assert_snapshot!(result, @r"
+    > 1 | const x = '😀😀😀';
+        |            ^^^^^^^^^^^^
```
Comment (bgw) [inline crates/next-code-frame/src/tests.rs]: There's of course no right answer here, but should we use wcswidth? Should we try to use the fancy unicode width thing that ghostty supports? Throw up our hands and be okay with widths being wrong?

**Review by bgw — APPROVED** [review]

File: crates/next-code-frame/src/tests.rs [hunk 63]
```diff
@@ -0,0 +1,914 @@
...
+    assert_snapshot!(result, @r"
+    > 1 | const x = 1
+        |       ^ Expected semicolon
+    ");
+}
+
+#[test]
+fn test_long_line_single_error() {
+    // Create a very long line with error in the middle
+    let long_line = "a".repeat(500);
```
Comment (sokra) [inline crates/next-code-frame/src/tests.rs]: Insert an `x` at the `location` so we can see it in the snapshot

File: crates/next-code-frame/src/tests.rs [hunk 64]
```diff
@@ -0,0 +1,914 @@
...
+    > 1 | ...aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
+        |                                                ^
+    ");
+}
+
+#[test]
+fn test_long_line_multiline_aligned() {
+    // Multiple long lines should all be truncated at the same offset
+    let long_line1 = "b".repeat(500);
+    let long_line2 = "c".repeat(500);
```
Comment (sokra) [inline crates/next-code-frame/src/tests.rs]: Insert an `x` at the `location` so we can see it in the snapshot

File: crates/next-code-frame/src/tests.rs [hunk 65]
```diff
@@ -0,0 +1,914 @@
...
+            | ^
+      25001 | line 25001 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
+      25002 | line 25002 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
+    ");
+}
+
+#[test]
+fn test_long_error_span() {
+    // Test error span that is longer than available width
+    let long_line = "a".repeat(500);
```
Comment (sokra) [inline crates/next-code-frame/src/tests.rs:452]: Insert an `x` at the start `location` so we can see it in the snapshot

File: crates/next-code-frame/src/tests.rs (hunk 62 above)
Comment (sokra) [reply crates/next-code-frame/src/tests.rs]: added it

**Review by sokra — APPROVED** [review]

**Comment by lukesandberg** [comment]
### Merge activity

* **Mar 3, 12:59 PM UTC**: @lukesandberg merged this pull request with [Graphite](https://app.graphite.com/github/pr/vercel/next.js/85592).

File: packages/next/src/next-devtools/dev-overlay/styles/colors.css (hunk 61 above)
Comment (lukesandberg) [reply packages/next/src/next-devtools/dev-overlay/styles/colors.css:12]: yeah we can change all of this. i didn't want to change the terminal styling but now it is trivial
