### PR TITLE
Fix hostname message in dev/start

### LINKED ISSUE #20137: `next dev` default listens on all interfaces
# Bug report

## Describe the bug
`next dev` command listens on all interfaces by default

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. run any next.js project with `next dev`
2. run `sudo lsof -nP -iTCP:3000` to see all listeners for port 3000, outputs 
```
node    ...  TCP *:3000 (LISTEN)
```

## Expected behavior

Should only listen on localhost and output
```
node    ... TCP 127.0.0.1:3000 (LISTEN)
```

## Screenshots
I was first made aware of this via this tweet: https://twitter.com/rsms/status/1337845477283221504

## System information

- OS: macOS + WSL tested
- Version of Next.js: 10.0.3
- Version of Node.js: 12.19.0
- Deployment: next dev

### PR DESCRIPTION
**Pull request by chulkilee**
Node.js net.listen fallbacks to unspecified ipv6 or ipv4.

https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback

> If host is omitted, the server will accept connections on the unspecified IPv6 address (::) when IPv6 is available, or the unspecified IPv4 address (0.0.0.0) otherwise.

Thus.. `localhost` in the message is incorrect, and it may lead to expose the server to other machines *without knowledge*, which is bad.

This PR is just to fix the message, since changing the behavior of dev (#20156) is a breaking change.

Note: for simplicity, choose the default to IPv4, even IPv6 is available - that's different behavior from net module, but I believe this is acceptable since most people just use IPv4 :wink: If someone want to use IPv6 unspecified address, use `::`!

Fixes #20137

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 9.5s | 9.5s | ⚠️ +18ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +88 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.984 | 1.872 | -0.11 |
| / avg req/sec | 1260.35 | 1335.58 | +75.23 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.18 | 1.164 | -0.02 |
| /error-in-render avg req/sec | 2119.38 | 2147.79 | +28.41 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 612 B | 612 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 11.3s | 11.3s | ⚠️ +33ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +88 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.16 MB | 5.16 MB | ✓ |

</details>

</details>
Commit: c4c3d44f1b70d50295b84054cccb59c5128ae2e1

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 10s | 10.1s | ⚠️ +88ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +104 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.982 | 2.034 | ⚠️ +0.05 |
| / avg req/sec | 1261.08 | 1229.4 | ⚠️ -31.68 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.223 | 1.225 | 0 |
| /error-in-render avg req/sec | 2044.96 | 2040.18 | ⚠️ -4.78 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 612 B | 612 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 11.8s | 11.8s | ⚠️ +22ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +104 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.16 MB | 5.16 MB | ✓ |

</details>

</details>
Commit: f70ddfa35392bd5472f6144d28d46220470d4de1

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f70ddfa35392bd5472f6144d28d46220470d4de1

**test/integration/cli/test/index.test.js** 
- CLI Usage > dev > --port
- CLI Usage > dev > NODE_OPTIONS='--inspect'
- CLI Usage > dev > -p

<details>
<summary>Expand output</summary>

  ● CLI Usage › dev › --port

    expect(received).toMatch(expected)

    Expected pattern: /http:\/\/localhost:43585/
    Received string:  "ready - started server on http://0.0.0.0:43585
    "

      142 |       const port = await findPort()
      143 |       const output = await runNextCommandDev([dir, '--port', port], true)
    > 144 |       expect(output).toMatch(new RegExp(`http://localhost:${port}`))
          |                      ^
      145 |     })
      146 | 
      147 |     test("NODE_OPTIONS='--inspect'", async () => {

      at Object.<anonymous> (integration/cli/test/index.test.js:144:22)

  ● CLI Usage › dev › NODE_OPTIONS='--inspect'

    expect(received).toMatch(expected)

    Expected pattern: /http:\/\/localhost:36313/
    Received string:  "ready - started server on http://0.0.0.0:36313
    "

      152 |         env: { NODE_OPTIONS: '--inspect' },
      153 |       })
    > 154 |       expect(output).toMatch(new RegExp(`http://localhost:${port}`))
          |                      ^
      155 |     })
      156 | 
      157 |     test('-p', async () => {

      at Object.<anonymous> (integration/cli/test/index.test.js:154:22)

  ● CLI Usage › dev › -p

    expect(received).toMatch(expected)

    Expected pattern: /http:\/\/localhost:44499/
    Received string:  "ready - started server on http://0.0.0.0:44499
    "

      158 |       const port = await findPort()
      159 |       const output = await runNextCommandDev([dir, '-p', port], true)
    > 160 |       expect(output).toMatch(new RegExp(`http://localhost:${port}`))
          |                      ^
      161 |     })
      162 | 
      163 |     test('-p conflict', async () => {

      at Object.<anonymous> (integration/cli/test/index.test.js:160:22)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 8.6s | 9s | ⚠️ +393ms |
| nodeModulesSize | 80.9 MB | 80.8 MB | -10 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.769 | 1.786 | ⚠️ +0.02 |
| / avg req/sec | 1413.36 | 1400.05 | ⚠️ -13.31 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.136 | 1.112 | -0.02 |
| /error-in-render avg req/sec | 2200.19 | 2247.57 | +47.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..b025.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e66dcae..6635.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 619 B | 619 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 10.6s | 10.7s | ⚠️ +116ms |
| nodeModulesSize | 80.9 MB | 80.9 MB | ⚠️ +104 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..b025.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e66dcae..6635.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.18 MB | 5.18 MB | ✓ |

</details>

</details>
Commit: ad03d817cedd61d5f24e8cf34db03974d36ecd55

File: packages/next/cli/next-dev.ts [hunk 1]
```diff
@@ -106,13 +106,10 @@ const nextDev: cliCommand = (argv) => {
   }
 
   const port = args['--port'] || 3000
-  const appUrl = `http://${args['--hostname'] || 'localhost'}:${port}`
+  const host = args['--hostname'] || '0.0.0.0'
+  const appUrl = `http://${host}:${port}`
```
[the remark this answers is not in the document]
Comment (chulkilee) [reply packages/next/cli/next-dev.ts]: That's a great idea! I found followings code and made the change in this PR.

- https://github.com/vercel/next.js/blob/v10.0.6-canary.5/packages/next/cli/next-start.ts#L56
- https://github.com/vercel/next.js/blob/v10.0.6-canary.5/packages/next/cli/next-dev.ts#L117

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 11.1s | 11s | -64ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +474 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.14 | 2.148 | ⚠️ +0.01 |
| / avg req/sec | 1168.45 | 1164.11 | ⚠️ -4.34 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.32 | 1.356 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1894.06 | 1843.63 | ⚠️ -50.43 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 616 B | 616 B | ✓ |
| link.html gzip | 622 B | 622 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.85 kB | 1.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 12.8s | 13s | ⚠️ +190ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +474 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 12.9s | 13.2s | ⚠️ +259ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +474 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.128 | 2.11 | -0.02 |
| / avg req/sec | 1175.03 | 1185.06 | +10.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.478 | 1.303 | -0.18 |
| /error-in-render avg req/sec | 1691.02 | 1918.78 | +227.76 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 597-3bd7d6bd..868b.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.8 kB | 59.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-a5b2e84..33cf.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-6f1f9..5577.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-725de8..0a15.js gzip | 904 B | 904 B | ✓ |
| index-939503..6e1c.js gzip | 232 B | 232 B | ✓ |
| link-e0cc871..fdbb.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..9360.js gzip | 308 B | 308 B | ✓ |
| withRouter-6..44ec.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 587 B | 587 B | ✓ |
| link.html gzip | 593 B | 593 B | ✓ |
| withRouter.html gzip | 581 B | 581 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "X07zDW2-wtClalEG7imNj",
+        "buildId": "lrtTwKgbr-V4Yer330nxS",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/X07zDW2-wtClalEG7imNj/_buildManifest.js"
+      src="/_next/static/lrtTwKgbr-V4Yer330nxS/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/X07zDW2-wtClalEG7imNj/_ssgManifest.js"
+      src="/_next/static/lrtTwKgbr-V4Yer330nxS/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "X07zDW2-wtClalEG7imNj",
+        "buildId": "lrtTwKgbr-V4Yer330nxS",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/X07zDW2-wtClalEG7imNj/_buildManifest.js"
+      src="/_next/static/lrtTwKgbr-V4Yer330nxS/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/X07zDW2-wtClalEG7imNj/_ssgManifest.js"
+      src="/_next/static/lrtTwKgbr-V4Yer330nxS/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "X07zDW2-wtClalEG7imNj",
+        "buildId": "lrtTwKgbr-V4Yer330nxS",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/X07zDW2-wtClalEG7imNj/_buildManifest.js"
+      src="/_next/static/lrtTwKgbr-V4Yer330nxS/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/X07zDW2-wtClalEG7imNj/_ssgManifest.js"
+      src="/_next/static/lrtTwKgbr-V4Yer330nxS/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 877901eb09cc2f00848cb5bf04db225937d05a71

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 877901eb09cc2f00848cb5bf04db225937d05a71

**test/integration/cli/test/index.test.js** 
- CLI Usage > dev > --port
- CLI Usage > dev > NODE_OPTIONS='--inspect'
- CLI Usage > dev > -p
- CLI Usage > dev > --hostname
- CLI Usage > dev > -H

<details>
<summary>Expand output</summary>

  ● CLI Usage › dev › --port

    expect(received).toMatch(expected)

    Expected pattern: /http:\/\/0.0.0.0:33765/
    Received string:  "ready - started server on http://127.0.0.1:33765
    "

      205 |       const port = await findPort()
      206 |       const output = await runNextCommandDev([dir, '--port', port], true)
    > 207 |       expect(output).toMatch(new RegExp(`http://0.0.0.0:${port}`))
          |                      ^
      208 |     })
      209 | 
      210 |     test("NODE_OPTIONS='--inspect'", async () => {

      at Object.<anonymous> (integration/cli/test/index.test.js:207:22)

  ● CLI Usage › dev › NODE_OPTIONS='--inspect'

    expect(received).toMatch(expected)

    Expected pattern: /http:\/\/0.0.0.0:46561/
    Received string:  "ready - started server on http://127.0.0.1:46561
    "

      215 |         env: { NODE_OPTIONS: '--inspect' },
      216 |       })
    > 217 |       expect(output).toMatch(new RegExp(`http://0.0.0.0:${port}`))
          |                      ^
      218 |     })
      219 | 
      220 |     test('-p', async () => {

      at Object.<anonymous> (integration/cli/test/index.test.js:217:22)

  ● CLI Usage › dev › -p

    expect(received).toMatch(expected)

    Expected pattern: /http:\/\/0.0.0.0:39817/
    Received string:  "ready - started server on http://127.0.0.1:39817
    "

      221 |       const port = await findPort()
      222 |       const output = await runNextCommandDev([dir, '-p', port], true)
    > 223 |       expect(output).toMatch(new RegExp(`http://0.0.0.0:${port}`))
          |                      ^
      224 |     })
      225 | 
      226 |     test('-p conflict', async () => {

      at Object.<anonymous> (integration/cli/test/index.test.js:223:22)

  ● CLI Usage › dev › --hostname

    expect(received).toMatch(expected)

    Expected pattern: /http:\/\/0.0.0.0:45975/
    Received string:  "ready - started server on http://127.0.0.1:45975
    "

      263 |         true
      264 |       )
    > 265 |       expect(output).toMatch(new RegExp(`http://0.0.0.0:${port}`))
          |                      ^
      266 |     })
      267 | 
      268 |     test('-H', async () => {

      at Object.<anonymous> (integration/cli/test/index.test.js:265:22)

  ● CLI Usage › dev › -H

    expect(received).toMatch(expected)

    Expected pattern: /http:\/\/0.0.0.0:34315/
    Received string:  "ready - started server on http://127.0.0.1:34315
    "

      272 |         true
      273 |       )
    > 274 |       expect(output).toMatch(new RegExp(`http://0.0.0.0:${port}`))
          |                      ^
      275 |     })
      276 | 
      277 |     test('should warn when unknown argument provided', async () => {

      at Object.<anonymous> (integration/cli/test/index.test.js:274:22)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 9.8s | 9.7s | -103ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +474 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.945 | 1.976 | ⚠️ +0.03 |
| / avg req/sec | 1285.48 | 1265.05 | ⚠️ -20.43 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.234 | 1.186 | -0.05 |
| /error-in-render avg req/sec | 2026.74 | 2108.55 | +81.81 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 616 B | 616 B | ✓ |
| link.html gzip | 622 B | 622 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.85 kB | 1.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 11.8s | 11.8s | -17ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +474 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.7s | ⚠️ +226ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +474 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.936 | 1.962 | ⚠️ +0.03 |
| / avg req/sec | 1291.42 | 1274.53 | ⚠️ -16.89 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.223 | 1.224 | 0 |
| /error-in-render avg req/sec | 2043.95 | 2042.15 | ⚠️ -1.8 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 597-3bd7d6bd..868b.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.8 kB | 59.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-a5b2e84..33cf.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-6f1f9..5577.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-725de8..0a15.js gzip | 904 B | 904 B | ✓ |
| index-939503..6e1c.js gzip | 232 B | 232 B | ✓ |
| link-e0cc871..fdbb.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..9360.js gzip | 308 B | 308 B | ✓ |
| withRouter-6..44ec.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 587 B | 587 B | ✓ |
| link.html gzip | 593 B | 593 B | ✓ |
| withRouter.html gzip | 581 B | 581 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "H3IpGaRtR6uFiCdYfD90q",
+        "buildId": "ggC4liPmT-S8t7umR2Bfy",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/H3IpGaRtR6uFiCdYfD90q/_buildManifest.js"
+      src="/_next/static/ggC4liPmT-S8t7umR2Bfy/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/H3IpGaRtR6uFiCdYfD90q/_ssgManifest.js"
+      src="/_next/static/ggC4liPmT-S8t7umR2Bfy/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "H3IpGaRtR6uFiCdYfD90q",
+        "buildId": "ggC4liPmT-S8t7umR2Bfy",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/H3IpGaRtR6uFiCdYfD90q/_buildManifest.js"
+      src="/_next/static/ggC4liPmT-S8t7umR2Bfy/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/H3IpGaRtR6uFiCdYfD90q/_ssgManifest.js"
+      src="/_next/static/ggC4liPmT-S8t7umR2Bfy/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "H3IpGaRtR6uFiCdYfD90q",
+        "buildId": "ggC4liPmT-S8t7umR2Bfy",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/H3IpGaRtR6uFiCdYfD90q/_buildManifest.js"
+      src="/_next/static/ggC4liPmT-S8t7umR2Bfy/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/H3IpGaRtR6uFiCdYfD90q/_ssgManifest.js"
+      src="/_next/static/ggC4liPmT-S8t7umR2Bfy/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 727adc54bb3163d953be9cb7297db3649aa50e66

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 727adc54bb3163d953be9cb7297db3649aa50e66

**test/integration/cli/test/index.test.js** 
- CLI Usage > dev > --port
- CLI Usage > dev > NODE_OPTIONS='--inspect'
- CLI Usage > dev > -p
- CLI Usage > dev > --hostname
- CLI Usage > dev > -H

<details>
<summary>Expand output</summary>

  ● CLI Usage › dev › --port

    expect(received).toMatch(expected)

    Expected pattern: /0.0.0.0:43703/
    Received string:  "ready - started server on http://127.0.0.1:43703
    "

      205 |       const port = await findPort()
      206 |       const output = await runNextCommandDev([dir, '--port', port], true)
    > 207 |       expect(output).toMatch(new RegExp(`0.0.0.0:${port}`))
          |                      ^
      208 |       expect(output).toMatch(new RegExp(`http://127.0.0.1:${port}`))
      209 |     })
      210 | 

      at Object.<anonymous> (integration/cli/test/index.test.js:207:22)

  ● CLI Usage › dev › NODE_OPTIONS='--inspect'

    expect(received).toMatch(expected)

    Expected pattern: /0.0.0.0:35585/
    Received string:  "ready - started server on http://127.0.0.1:35585
    "

      216 |         env: { NODE_OPTIONS: '--inspect' },
      217 |       })
    > 218 |       expect(output).toMatch(new RegExp(`0.0.0.0:${port}`))
          |                      ^
      219 |       expect(output).toMatch(new RegExp(`127.0.0.1:${port}`))
      220 |     })
      221 | 

      at Object.<anonymous> (integration/cli/test/index.test.js:218:22)

  ● CLI Usage › dev › -p

    expect(received).toMatch(expected)

    Expected pattern: /0.0.0.0:33387/
    Received string:  "ready - started server on http://127.0.0.1:33387
    "

      223 |       const port = await findPort()
      224 |       const output = await runNextCommandDev([dir, '-p', port], true)
    > 225 |       expect(output).toMatch(new RegExp(`0.0.0.0:${port}`))
          |                      ^
      226 |       expect(output).toMatch(new RegExp(`http://127.0.0.1:${port}`))
      227 |     })
      228 | 

      at Object.<anonymous> (integration/cli/test/index.test.js:225:22)

  ● CLI Usage › dev › --hostname

    expect(received).toMatch(expected)

    Expected pattern: /0.0.0.0:45501/
    Received string:  "ready - started server on http://127.0.0.1:45501
    "

      266 |         true
      267 |       )
    > 268 |       expect(output).toMatch(new RegExp(`0.0.0.0:${port}`))
          |                      ^
      269 |       expect(output).toMatch(new RegExp(`http://127.0.0.1:${port}`))
      270 |     })
      271 | 

      at Object.<anonymous> (integration/cli/test/index.test.js:268:22)

  ● CLI Usage › dev › -H

    expect(received).toMatch(expected)

    Expected pattern: /0.0.0.0:43115/
    Received string:  "ready - started server on http://127.0.0.1:43115
    "

      276 |         true
      277 |       )
    > 278 |       expect(output).toMatch(new RegExp(`0.0.0.0:${port}`))
          |                      ^
      279 |       expect(output).toMatch(new RegExp(`http://127.0.0.1:${port}`))
      280 |     })
      281 | 

      at Object.<anonymous> (integration/cli/test/index.test.js:278:22)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 8.7s | 8.6s | -89ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +952 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.752 | 1.774 | ⚠️ +0.02 |
| / avg req/sec | 1427.33 | 1409.3 | ⚠️ -18.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.077 | 1.127 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 2322.17 | 2217.69 | ⚠️ -104.48 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 616 B | 616 B | ✓ |
| link.html gzip | 622 B | 622 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.85 kB | 1.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.5s | ⚠️ +34ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +952 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 10.7s | 10.3s | -429ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +952 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.831 | 1.801 | -0.03 |
| / avg req/sec | 1365.64 | 1387.82 | +22.18 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.075 | 1.118 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2324.88 | 2236.41 | ⚠️ -88.47 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 597-3bd7d6bd..868b.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.8 kB | 59.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-a5b2e84..33cf.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-6f1f9..5577.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-725de8..0a15.js gzip | 904 B | 904 B | ✓ |
| index-939503..6e1c.js gzip | 232 B | 232 B | ✓ |
| link-e0cc871..fdbb.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..9360.js gzip | 308 B | 308 B | ✓ |
| withRouter-6..44ec.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 587 B | 587 B | ✓ |
| link.html gzip | 593 B | 593 B | ✓ |
| withRouter.html gzip | 581 B | 581 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "5HvRP36fC2nbHiVjpZxcK",
+        "buildId": "hdLWZEvA8Cpov88WwCuk_",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/5HvRP36fC2nbHiVjpZxcK/_buildManifest.js"
+      src="/_next/static/hdLWZEvA8Cpov88WwCuk_/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/5HvRP36fC2nbHiVjpZxcK/_ssgManifest.js"
+      src="/_next/static/hdLWZEvA8Cpov88WwCuk_/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "5HvRP36fC2nbHiVjpZxcK",
+        "buildId": "hdLWZEvA8Cpov88WwCuk_",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/5HvRP36fC2nbHiVjpZxcK/_buildManifest.js"
+      src="/_next/static/hdLWZEvA8Cpov88WwCuk_/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/5HvRP36fC2nbHiVjpZxcK/_ssgManifest.js"
+      src="/_next/static/hdLWZEvA8Cpov88WwCuk_/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "5HvRP36fC2nbHiVjpZxcK",
+        "buildId": "hdLWZEvA8Cpov88WwCuk_",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/5HvRP36fC2nbHiVjpZxcK/_buildManifest.js"
+      src="/_next/static/hdLWZEvA8Cpov88WwCuk_/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/5HvRP36fC2nbHiVjpZxcK/_ssgManifest.js"
+      src="/_next/static/hdLWZEvA8Cpov88WwCuk_/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 6849a526c8cf68f82b26c8ca8c7f148bdb1d605c

File: packages/next/cli/next-dev.ts [hunk 2]
```diff
@@ -106,15 +106,12 @@ const nextDev: cliCommand = (argv) => {
   }
 
   const port = args['--port'] || 3000
-  const appUrl = `http://${args['--hostname'] || 'localhost'}:${port}`
+  const host = args['--hostname'] || '0.0.0.0'
+  const appUrl = `http://${host === '0.0.0.0' ? '127.0.0.1' : host}:${port}`
```
Comment (timneutkens) [inline packages/next/cli/next-dev.ts:110]: To mirror our current output:
```suggestion
  const appUrl = `http://${host === '0.0.0.0' ? 'localhost' : host}:${port}`
```

Otherwise people might think we started listening on another host and start creating bug reports for it.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 10.9s | 11.5s | ⚠️ +538ms |
| nodeModulesSize | 73.3 MB | 73.3 MB | ⚠️ +952 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.48 | 2.332 | -0.15 |
| / avg req/sec | 1007.98 | 1071.98 | +64 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.657 | 1.571 | -0.09 |
| /error-in-render avg req/sec | 1508.47 | 1591.24 | +82.77 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 616 B | 616 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.85 kB | 1.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.4s | -348ms |
| nodeModulesSize | 73.3 MB | 73.3 MB | ⚠️ +952 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 14.3s | 14.3s | -35ms |
| nodeModulesSize | 73.3 MB | 73.3 MB | ⚠️ +952 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.406 | 2.462 | ⚠️ +0.06 |
| / avg req/sec | 1039.18 | 1015.24 | ⚠️ -23.94 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.686 | 1.608 | -0.08 |
| /error-in-render avg req/sec | 1483.13 | 1554.61 | +71.48 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 597-3bd7d6bd..868b.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.8 kB | 59.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-a5b2e84..33cf.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-6f1f9..5577.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-725de8..0a15.js gzip | 904 B | 904 B | ✓ |
| index-939503..6e1c.js gzip | 232 B | 232 B | ✓ |
| link-e0cc871..fdbb.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..9360.js gzip | 308 B | 308 B | ✓ |
| withRouter-6..44ec.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 579 B | 579 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "Rl241fGDeUiKO26CuGaMj",
+        "buildId": "Hc42WmhkyI0QAL8Wy9_cW",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/Rl241fGDeUiKO26CuGaMj/_buildManifest.js"
+      src="/_next/static/Hc42WmhkyI0QAL8Wy9_cW/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/Rl241fGDeUiKO26CuGaMj/_ssgManifest.js"
+      src="/_next/static/Hc42WmhkyI0QAL8Wy9_cW/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "Rl241fGDeUiKO26CuGaMj",
+        "buildId": "Hc42WmhkyI0QAL8Wy9_cW",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/Rl241fGDeUiKO26CuGaMj/_buildManifest.js"
+      src="/_next/static/Hc42WmhkyI0QAL8Wy9_cW/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/Rl241fGDeUiKO26CuGaMj/_ssgManifest.js"
+      src="/_next/static/Hc42WmhkyI0QAL8Wy9_cW/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "Rl241fGDeUiKO26CuGaMj",
+        "buildId": "Hc42WmhkyI0QAL8Wy9_cW",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/Rl241fGDeUiKO26CuGaMj/_buildManifest.js"
+      src="/_next/static/Hc42WmhkyI0QAL8Wy9_cW/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/Rl241fGDeUiKO26CuGaMj/_ssgManifest.js"
+      src="/_next/static/Hc42WmhkyI0QAL8Wy9_cW/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 1059ca20bbe49e7a4a17cb78d3d9363a7c56e84c

File: packages/next/cli/next-dev.ts (hunk 2 above)
Comment (chulkilee) [reply packages/next/cli/next-dev.ts]: Done!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 10.9s | 10.9s | ⚠️ +69ms |
| nodeModulesSize | 73.3 MB | 73.3 MB | ⚠️ +952 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.121 | 2.226 | ⚠️ +0.1 |
| / avg req/sec | 1178.78 | 1122.97 | ⚠️ -55.81 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.32 | 1.331 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1894.64 | 1878.72 | ⚠️ -15.92 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 616 B | 616 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.85 kB | 1.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 12.9s | 12.9s | ⚠️ +22ms |
| nodeModulesSize | 73.3 MB | 73.3 MB | ⚠️ +952 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 13.3s | 13s | -305ms |
| nodeModulesSize | 73.3 MB | 73.3 MB | ⚠️ +952 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.129 | 2.1 | -0.03 |
| / avg req/sec | 1174.43 | 1190.46 | +16.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.307 | 1.344 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1912.17 | 1860.07 | ⚠️ -52.1 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 597-3bd7d6bd..868b.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.8 kB | 59.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-a5b2e84..33cf.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-6f1f9..5577.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-725de8..0a15.js gzip | 904 B | 904 B | ✓ |
| index-939503..6e1c.js gzip | 232 B | 232 B | ✓ |
| link-e0cc871..fdbb.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..9360.js gzip | 308 B | 308 B | ✓ |
| withRouter-6..44ec.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 579 B | 579 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "8aco6lZWv2lkAKlsv2FEo",
+        "buildId": "xEq1MNYYg4cWTdTNk087E",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/8aco6lZWv2lkAKlsv2FEo/_buildManifest.js"
+      src="/_next/static/xEq1MNYYg4cWTdTNk087E/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/8aco6lZWv2lkAKlsv2FEo/_ssgManifest.js"
+      src="/_next/static/xEq1MNYYg4cWTdTNk087E/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "8aco6lZWv2lkAKlsv2FEo",
+        "buildId": "xEq1MNYYg4cWTdTNk087E",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/8aco6lZWv2lkAKlsv2FEo/_buildManifest.js"
+      src="/_next/static/xEq1MNYYg4cWTdTNk087E/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/8aco6lZWv2lkAKlsv2FEo/_ssgManifest.js"
+      src="/_next/static/xEq1MNYYg4cWTdTNk087E/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "8aco6lZWv2lkAKlsv2FEo",
+        "buildId": "xEq1MNYYg4cWTdTNk087E",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/8aco6lZWv2lkAKlsv2FEo/_buildManifest.js"
+      src="/_next/static/xEq1MNYYg4cWTdTNk087E/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/8aco6lZWv2lkAKlsv2FEo/_ssgManifest.js"
+      src="/_next/static/xEq1MNYYg4cWTdTNk087E/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: ef5035e14b30ecbb0acc682083fffc56d22eb195

**Comment by ijjk** [comment]
## Failing test suites 
Commit: ef5035e14b30ecbb0acc682083fffc56d22eb195

**test/integration/cli/test/index.test.js** 
- CLI Usage > dev > NODE_OPTIONS='--inspect'

<details>
<summary>Expand output</summary>

  ● CLI Usage › dev › NODE_OPTIONS='--inspect'

    expect(received).toMatch(expected)

    Expected pattern: /https:\/\/localhost:44671/
    Received string:  "ready - started server on 0.0.0.0:44671, url: http://localhost:44671
    "

      217 |       })
      218 |       expect(output).toMatch(new RegExp(`on 0.0.0.0:${port}`))
    > 219 |       expect(output).toMatch(new RegExp(`https://localhost:${port}`))
          |                      ^
      220 |     })
      221 | 
      222 |     test('-p', async () => {

      at Object.<anonymous> (integration/cli/test/index.test.js:219:22)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 8.4s | 8.8s | ⚠️ +442ms |
| nodeModulesSize | 73.3 MB | 73.3 MB | ⚠️ +952 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.745 | 1.704 | -0.04 |
| / avg req/sec | 1432.4 | 1467.54 | +35.14 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.18 | 1.13 | -0.05 |
| /error-in-render avg req/sec | 2118.48 | 2212.84 | +94.36 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 616 B | 616 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.85 kB | 1.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.6s | ⚠️ +335ms |
| nodeModulesSize | 73.3 MB | 73.3 MB | ⚠️ +952 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| buildDuration | 10.9s | 10.6s | -275ms |
| nodeModulesSize | 73.3 MB | 73.3 MB | ⚠️ +952 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.729 | 1.784 | ⚠️ +0.05 |
| / avg req/sec | 1445.55 | 1401.32 | ⚠️ -44.23 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.105 | 1.148 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2263.38 | 2177.21 | ⚠️ -86.17 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| 597-3bd7d6bd..868b.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.8 kB | 59.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _app-a5b2e84..33cf.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-6f1f9..5577.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-725de8..0a15.js gzip | 904 B | 904 B | ✓ |
| index-939503..6e1c.js gzip | 232 B | 232 B | ✓ |
| link-e0cc871..fdbb.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..9360.js gzip | 308 B | 308 B | ✓ |
| withRouter-6..44ec.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js fix-hostname-message | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 579 B | 579 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "l7uqYslikcYV2fgGGC5kD",
+        "buildId": "ytZJ57H3U4pLAH9UUULiV",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/l7uqYslikcYV2fgGGC5kD/_buildManifest.js"
+      src="/_next/static/ytZJ57H3U4pLAH9UUULiV/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/l7uqYslikcYV2fgGGC5kD/_ssgManifest.js"
+      src="/_next/static/ytZJ57H3U4pLAH9UUULiV/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "l7uqYslikcYV2fgGGC5kD",
+        "buildId": "ytZJ57H3U4pLAH9UUULiV",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/l7uqYslikcYV2fgGGC5kD/_buildManifest.js"
+      src="/_next/static/ytZJ57H3U4pLAH9UUULiV/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/l7uqYslikcYV2fgGGC5kD/_ssgManifest.js"
+      src="/_next/static/ytZJ57H3U4pLAH9UUULiV/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "l7uqYslikcYV2fgGGC5kD",
+        "buildId": "ytZJ57H3U4pLAH9UUULiV",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/l7uqYslikcYV2fgGGC5kD/_buildManifest.js"
+      src="/_next/static/ytZJ57H3U4pLAH9UUULiV/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/l7uqYslikcYV2fgGGC5kD/_ssgManifest.js"
+      src="/_next/static/ytZJ57H3U4pLAH9UUULiV/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 22c49a7287f46db8541f596292674fd5bc1c1d24

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
Thanks @chulkilee, great PR 💯

**Comment by finnwoelm-sdsn** [comment]
Hi @chulkilee and @timneutkens, I believe that this PR introduced an unintentional regression for Windows users.

As you can see from this thread (#22214), fast refresh stopped working for Windows users as of Next v10.0.6. And I think it is due to the change made in this PR.

Fast refresh relies on Server-Sent Events (SSE). On Windows, SEE only seem to be working when Node's `http.createServer()` listens on the default unspecified IPv6 host (`::`).

If you have access to a Windows 10 machine, you can reproduce this by copying the files from this gist (server.js and index.html): https://gist.github.com/jareware/aae9748a1873ef8a91e5

If you modify the last line in `server.js` to `listen(8888, "0.0.0.0")`, you will notice that SSE are not working! If you remove the host or put `"::"`, SSE do work. I have been able to confirm that I can restore Next.js fast refresh ability by manually setting `-H ::` when running `next dev`.

However, it would of course be even better to have compatibility baked into Next.js. Not sure if there is a way to revert back to letting Node.js choose the default port (i.e., just calling `.listen(port)`, if no host is set) and still printing out the correct hostname?

Anyway, just wanted to let you know. Perhaps you have a good idea. Otherwise, we'll stick with `-H ::` for now :)
