### PR TITLE
Fix reading Component.__N_SSG

### LINKED ISSUE #10036: Error page not shown when page throws at module level on client side
# Bug report

If an exception is thrown at a module level of a page on the client side but not server side, a blank page is shown with "next": "9.1.7"

## To Reproduce

1. Clone https://github.com/WestonThayer/bug-nextjs-error-getinitialprops
2. Update package.json to use ```"next": "9.1.7", "react": "16.12.0", "react-dom": "16.12.0"```
3. `npm install && npm run build && npm run start`
4. Navigate to http://localhost:3000/ and observe blank page instead of error page

## Expected behavior

Show the "pages/_error" page

## System information

- OS: Linux
- Browser Chrome Version 79.0.3945.117 (Official Build) (64-bit)
- Version of Next.js: 9.1.7

## Additional context

An exception is thrown [here](https://github.com/zeit/next.js/blob/243c038222573050dff3923b876d99f5b64460c9/packages/next/client/index.js#L97) with a message `TypeError: Cannot read property '__NEXT_SPR' of undefined
` . Replacing `Component.__NEXT_SPR` with `Component && Component.__NEXT_SPR` results in the error page being shown correctly.

Seems that issue was introduced with [this commit](https://github.com/zeit/next.js/commit/45832e44219b281eab5569374f3b2cb2f651e755).

### PR DESCRIPTION
**Pull request by tomas-c**
Closes #10036

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 13s | 13.1s | ⚠️ +55ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ⚠️ +1 B |
| link.html gzip | 1.03 kB | 1.03 kB | -2 B |
| withRouter.html gzip | 1.02 kB | 1.02 kB | ✓ |
| Overall change | 3.07 kB | 3.07 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -475,7 +475,7 @@
                   (data.nextExport &&
                     ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                       location.search)) ||
-                  (Component.__NEXT_SPR && location.search)
+                  (Component && Component.__NEXT_SPR && location.search)
                 ) {
                   // update query on mount for exported pages
                   router.replace(
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -359,7 +359,7 @@
             (data.nextExport &&
               ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                 location.search)) ||
-            (Component.__NEXT_SPR && location.search)
+            (Component && Component.__NEXT_SPR && location.search)
           ) {
             // update query on mount for exported pages
             router.replace(
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-0bcb847ac444c3ba095b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-858e1e5b8678aa5d26c6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-0bcb847ac444c3ba095b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-0bcb847ac444c3ba095b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-858e1e5b8678aa5d26c6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-0bcb847ac444c3ba095b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-0bcb847ac444c3ba095b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-858e1e5b8678aa5d26c6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-0bcb847ac444c3ba095b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.6s | ⚠️ +56ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +2 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | -1 B |
| index.js gzip | 78 kB | 78 kB | ⚠️ +3 B |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +2 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +2 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +2 B |
| Overall change | 393 kB | 393 kB | ⚠️ +10 B |

</details>

</details>


Commit: 70667d98795e5bbdce270457343ffa2b7fcbbd83

File: packages/next/client/index.js [hunk 1]
```diff
@@ -94,7 +94,7 @@ class Container extends React.Component {
     if (
       (data.nextExport &&
         (isDynamicRoute(router.pathname) || location.search)) ||
-      (Component.__NEXT_SPR && location.search)
+      (Component && Component.__NEXT_SPR && location.search)
```
Comment (timneutkens) [inline packages/next/client/index.js]:
```suggestion
      (Component?.__NEXT_SPR && location.search)
```

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 12.2s | 363ms | -11.8s |
| nodeModulesSize | 49 MB | 48.9 MB | -87.7 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | N/A | N/A |
| webpack-HASH.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | N/A | N/A |
| commons.HASH.js gzip | 4.06 kB | N/A | N/A |
| de003c3a9d30..9881.js gzip | 13.7 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 67.4 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | N/A | N/A |
| webpack-HASH..dule.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 12.5 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 62.1 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | N/A | N/A |
| Overall change | 4.76 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | N/A | N/A |
| _error.js gzip | 4.07 kB | N/A | N/A |
| hooks.js gzip | 779 B | N/A | N/A |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.9 kB | N/A | N/A |
| routerDirect.js gzip | 283 B | N/A | N/A |
| withRouter.js gzip | 282 B | N/A | N/A |
| Overall change | 9.87 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | N/A | N/A |
| _error.module.js gzip | 3.06 kB | N/A | N/A |
| hooks.module.js gzip | 371 B | N/A | N/A |
| index.module.js gzip | 212 B | N/A | N/A |
| link.module.js gzip | 2.47 kB | N/A | N/A |
| routerDirect..dule.js gzip | 273 B | N/A | N/A |
| withRouter.m..dule.js gzip | 272 B | N/A | N/A |
| Overall change | 7.41 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | N/A | N/A |
| _buildManife..dule.js gzip | 61 B | N/A | N/A |
| Overall change | 122 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | N/A | N/A |
| link.html gzip | 1.03 kB | N/A | N/A |
| withRouter.html gzip | 1.02 kB | N/A | N/A |
| Overall change | 3.07 kB | 0 B | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_app.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_app.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_error.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_error.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>hooks.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>hooks.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>index.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>index.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>routerDirect.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>withRouter.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>4952ddcd88e7..16.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>4952ddcd88e7..92a927903.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>commons.HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..26.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..ba6a65095.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>framework.HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>framework.HASH.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>polyfills-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>webpack-HASH.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
deleted
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 12.7s | 407ms | -12.3s |
| nodeModulesSize | 49 MB | 48.9 MB | -87.7 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | N/A | N/A |
| webpack-HASH.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | N/A | N/A |
| commons.HASH.js gzip | 4.06 kB | N/A | N/A |
| de003c3a9d30..9881.js gzip | 13.7 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 67.4 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | N/A | N/A |
| webpack-HASH..dule.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 12.5 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 62.1 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | N/A | N/A |
| Overall change | 4.76 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | N/A | N/A |
| _error.js gzip | 4.07 kB | N/A | N/A |
| hooks.js gzip | 779 B | N/A | N/A |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.9 kB | N/A | N/A |
| routerDirect.js gzip | 283 B | N/A | N/A |
| withRouter.js gzip | 282 B | N/A | N/A |
| Overall change | 9.87 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | N/A | N/A |
| _error.module.js gzip | 3.06 kB | N/A | N/A |
| hooks.module.js gzip | 371 B | N/A | N/A |
| index.module.js gzip | 212 B | N/A | N/A |
| link.module.js gzip | 2.47 kB | N/A | N/A |
| routerDirect..dule.js gzip | 273 B | N/A | N/A |
| withRouter.m..dule.js gzip | 272 B | N/A | N/A |
| Overall change | 7.41 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | N/A | N/A |
| _buildManife..dule.js gzip | 61 B | N/A | N/A |
| Overall change | 122 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | N/A | N/A |
| hooks.html gzip | 1.05 kB | N/A | N/A |
| index.js gzip | 78 kB | N/A | N/A |
| link.js gzip | 80.4 kB | N/A | N/A |
| routerDirect.js gzip | 78.1 kB | N/A | N/A |
| withRouter.js gzip | 78.1 kB | N/A | N/A |
| Overall change | 393 kB | 0 B | ✓ |

</details>

</details>


Commit: 151b24cd88e735e4b7ec465f4eb6b34c41da9633

**Review by Timer — CHANGES_REQUESTED** [review]
This change doesn't make sense to me – Component should always be defined. Let's make sure we understand problem first.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 11.6s | 344ms | -11.3s |
| nodeModulesSize | 49 MB | 48.9 MB | -87.9 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | N/A | N/A |
| webpack-HASH.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | N/A | N/A |
| commons.HASH.js gzip | 4.06 kB | N/A | N/A |
| de003c3a9d30..9881.js gzip | 13.7 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 67.5 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | N/A | N/A |
| webpack-HASH..dule.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 12.5 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 62.1 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | N/A | N/A |
| Overall change | 4.76 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | N/A | N/A |
| _error.js gzip | 4.07 kB | N/A | N/A |
| hooks.js gzip | 779 B | N/A | N/A |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.9 kB | N/A | N/A |
| routerDirect.js gzip | 283 B | N/A | N/A |
| withRouter.js gzip | 282 B | N/A | N/A |
| Overall change | 9.87 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | N/A | N/A |
| _error.module.js gzip | 3.06 kB | N/A | N/A |
| hooks.module.js gzip | 371 B | N/A | N/A |
| index.module.js gzip | 212 B | N/A | N/A |
| link.module.js gzip | 2.47 kB | N/A | N/A |
| routerDirect..dule.js gzip | 273 B | N/A | N/A |
| withRouter.m..dule.js gzip | 272 B | N/A | N/A |
| Overall change | 7.41 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | N/A | N/A |
| _buildManife..dule.js gzip | 61 B | N/A | N/A |
| Overall change | 122 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | N/A | N/A |
| link.html gzip | 1.03 kB | N/A | N/A |
| withRouter.html gzip | 1.02 kB | N/A | N/A |
| Overall change | 3.06 kB | 0 B | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_app.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_app.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_error.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_error.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>hooks.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>hooks.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>index.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>index.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>routerDirect.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>withRouter.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>4952ddcd88e7..16.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>4952ddcd88e7..92a927903.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>commons.HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..26.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..ba6a65095.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>framework.HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>framework.HASH.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>polyfills-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>webpack-HASH.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
deleted
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 12.2s | 355ms | -11.8s |
| nodeModulesSize | 49 MB | 48.9 MB | -87.9 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | N/A | N/A |
| webpack-HASH.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | N/A | N/A |
| commons.HASH.js gzip | 4.06 kB | N/A | N/A |
| de003c3a9d30..9881.js gzip | 13.7 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 67.5 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | N/A | N/A |
| webpack-HASH..dule.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 12.5 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 62.1 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | N/A | N/A |
| Overall change | 4.76 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | N/A | N/A |
| _error.js gzip | 4.07 kB | N/A | N/A |
| hooks.js gzip | 779 B | N/A | N/A |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.9 kB | N/A | N/A |
| routerDirect.js gzip | 283 B | N/A | N/A |
| withRouter.js gzip | 282 B | N/A | N/A |
| Overall change | 9.87 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | N/A | N/A |
| _error.module.js gzip | 3.06 kB | N/A | N/A |
| hooks.module.js gzip | 371 B | N/A | N/A |
| index.module.js gzip | 212 B | N/A | N/A |
| link.module.js gzip | 2.47 kB | N/A | N/A |
| routerDirect..dule.js gzip | 273 B | N/A | N/A |
| withRouter.m..dule.js gzip | 272 B | N/A | N/A |
| Overall change | 7.41 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | N/A | N/A |
| _buildManife..dule.js gzip | 61 B | N/A | N/A |
| Overall change | 122 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | N/A | N/A |
| hooks.html gzip | 1.05 kB | N/A | N/A |
| index.js gzip | 78 kB | N/A | N/A |
| link.js gzip | 80.4 kB | N/A | N/A |
| routerDirect.js gzip | 78.1 kB | N/A | N/A |
| withRouter.js gzip | 78.1 kB | N/A | N/A |
| Overall change | 393 kB | 0 B | ✓ |

</details>

</details>


Commit: 17db0723ff2bae004392ed5a7819a0bc61ea12d0

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.9s | ⚠️ +49ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.12 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.18 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ⚠️ +1 B |
| link.html gzip | 1.03 kB | 1.03 kB | ⚠️ +1 B |
| withRouter.html gzip | 1.02 kB | 1.01 kB | -1 B |
| Overall change | 3.06 kB | 3.06 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -475,7 +475,7 @@
                   (data.nextExport &&
                     ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                       location.search)) ||
-                  (Component.__NEXT_SPR && location.search)
+                  (Component && Component.__NEXT_SPR && location.search)
                 ) {
                   // update query on mount for exported pages
                   router.replace(
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -359,7 +359,7 @@
             (data.nextExport &&
               ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                 location.search)) ||
-            (Component.__NEXT_SPR && location.search)
+            (Component && Component.__NEXT_SPR && location.search)
           ) {
             // update query on mount for exported pages
             router.replace(
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      href="/_next/static/runtime/main-5f72831cf35898f87caf.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-24e04d939f54ee455844.js"
+      src="/_next/static/runtime/main-8397b6ff07e28f7d8f3b.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      src="/_next/static/runtime/main-5f72831cf35898f87caf.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      href="/_next/static/runtime/main-5f72831cf35898f87caf.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-24e04d939f54ee455844.js"
+      src="/_next/static/runtime/main-8397b6ff07e28f7d8f3b.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      src="/_next/static/runtime/main-5f72831cf35898f87caf.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      href="/_next/static/runtime/main-5f72831cf35898f87caf.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-24e04d939f54ee455844.js"
+      src="/_next/static/runtime/main-8397b6ff07e28f7d8f3b.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      src="/_next/static/runtime/main-5f72831cf35898f87caf.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.4s | ⚠️ +195ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.12 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.18 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +2 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | -1 B |
| index.js gzip | 78 kB | 78 kB | ⚠️ +1 B |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +2 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +3 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +3 B |
| Overall change | 393 kB | 393 kB | ⚠️ +10 B |

</details>

</details>


Commit: a2bd2db530324e7f8fba52c36f6142fccccef8bb

**Review by Timer — APPROVED** [review]
Thanks!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 12.9s | 13.1s | ⚠️ +192ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.18 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | ✓ |
| withRouter.html gzip | 1.02 kB | 1.01 kB | -1 B |
| Overall change | 3.07 kB | 3.06 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -475,7 +475,7 @@
                   (data.nextExport &&
                     ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                       location.search)) ||
-                  (Component.__N_SSG && location.search)
+                  (Component && Component.__N_SSG && location.search)
                 ) {
                   // update query on mount for exported pages
                   router.replace(
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -359,7 +359,7 @@
             (data.nextExport &&
               ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                 location.search)) ||
-            (Component.__N_SSG && location.search)
+            (Component && Component.__N_SSG && location.search)
           ) {
             // update query on mount for exported pages
             router.replace(
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      href="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-958c0bb4c1297de8088f.js"
+      src="/_next/static/runtime/main-4dc7ee942236d9bde769.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      src="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      href="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-958c0bb4c1297de8088f.js"
+      src="/_next/static/runtime/main-4dc7ee942236d9bde769.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      src="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      href="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-958c0bb4c1297de8088f.js"
+      src="/_next/static/runtime/main-4dc7ee942236d9bde769.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      src="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.8s | ⚠️ +443ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.18 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +1 B |
| hooks.html gzip | 1.06 kB | 1.05 kB | -2 B |
| index.js gzip | 78 kB | 78 kB | ⚠️ +2 B |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +1 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +1 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +1 B |
| Overall change | 393 kB | 393 kB | ⚠️ +4 B |

</details>

</details>


Commit: 9b0c057932ebe15dfb1130d1ca528de1818c047c

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.7s | -109ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.18 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | ✓ |
| withRouter.html gzip | 1.02 kB | 1.01 kB | -1 B |
| Overall change | 3.07 kB | 3.06 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -475,7 +475,7 @@
                   (data.nextExport &&
                     ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                       location.search)) ||
-                  (Component.__N_SSG && location.search)
+                  (Component && Component.__N_SSG && location.search)
                 ) {
                   // update query on mount for exported pages
                   router.replace(
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -359,7 +359,7 @@
             (data.nextExport &&
               ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                 location.search)) ||
-            (Component.__N_SSG && location.search)
+            (Component && Component.__N_SSG && location.search)
           ) {
             // update query on mount for exported pages
             router.replace(
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      href="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-958c0bb4c1297de8088f.js"
+      src="/_next/static/runtime/main-4dc7ee942236d9bde769.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      src="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      href="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-958c0bb4c1297de8088f.js"
+      src="/_next/static/runtime/main-4dc7ee942236d9bde769.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      src="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      href="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-958c0bb4c1297de8088f.js"
+      src="/_next/static/runtime/main-4dc7ee942236d9bde769.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      src="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 14.3s | 14.4s | ⚠️ +127ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.18 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +1 B |
| hooks.html gzip | 1.06 kB | 1.05 kB | -2 B |
| index.js gzip | 78 kB | 78 kB | ⚠️ +2 B |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +1 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +1 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +1 B |
| Overall change | 393 kB | 393 kB | ⚠️ +4 B |

</details>

</details>


Commit: 391bf7a5bfc74dbb500003bc037ee4f2fe7b5ebb
