### PR TITLE
fix: force module format for virtual client-proxy file

### LINKED ISSUE #74062: Turbopack does not handle CommonJS modules properly when "type": "commonjs" is specified in package.json
### Link to the code that reproduces this issue

https://github.com/saoudi-h/commonjs-issue-next-turbopack

### To Reproduce

Create a Next.js app using npx create-next-app.
Install Jotai (pnpm install jotai) or any other library that specifies "type": "commonjs" in its package.json.
Run the application with Turbopack enabled (next dev --turbopack).
Import the library into your project and attempt to use it.

### Current vs. Expected behavior

Current Behavior: The application throws an error due to an incompatibility between the "type": "commonjs" field in the library's package.json and Turbopack's handling of ESModules. This breaks the development server and prevents the application from running.

Expected Behavior: Turbopack should handle CommonJS modules seamlessly, as per the Node.js module resolution standards, regardless of the "type" field in package.json.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32695
  Available CPU cores: 16
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.15.3
Relevant Packages:
  next: 15.1.1 // Latest available version is detected (15.1.1).
  eslint-config-next: 15.1.1
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

This issue was initially observed in a discussion in the [Jotai repository](https://github.com/pmndrs/jotai/discussions/2579). The maintainer pointed out that Turbopack does not respect the "type": "commonjs" field, leading to incompatibilities with libraries that follow the Node.js module conventions. While workarounds like patching the affected library or modifying its package.json exist, the root cause seems to be Turbopack's handling of CommonJS modules.

It would be great to address this issue as it could impact many libraries and developers using Turbopack in their Next.js projects.

### PR DESCRIPTION
**Pull request by lubieowoce**
Fixes #74062  (`jotai` ran into this error [when they added `"type": "commonjs"` to their package.json](https://github.com/pmndrs/jotai/discussions/2579#discussioncomment-9812492))

> this is a bug in the transform we do when a `'use client'` directive is encountered. I think what's happening is that we're creating a virtual file that uses ESM import/export syntax, but it's called proxy.js (not proxy.mjs), so the `"type": "commonjs" `makes turbopack "correctly" upset at the ESM syntax.
https://github.com/vercel/next.js/issues/74062#issuecomment-2555922867

The (slightly kludgy) solution is to use `proxy.mjs` or `proxy.cjs` to force the module format, bypassing the  issue where `proxy.js` changes meaning depending on `package.json#type`.

### CODE REVIEW

**Comment by lubieowoce** [comment]
Honestly, this feels like a bit of a workaround for the fact that we're creating this `proxy.js` module "beside" the original code, and thus are affected by its package.json. maybe we should just stop doing that, and place it somewhere else?

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js lubieowoce/fix-client-transform-mjs | Change |
| - | - | - | - |
| buildDuration | 19s | 15.9s | N/A |
| buildDurationCached | 15s | 12.7s | N/A |
| nodeModulesSize | 416 MB | 416 MB | N/A |
| nextStartRea..uration (ms) | 468ms | 481ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js lubieowoce/fix-client-transform-mjs | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 52.4 kB | 52.4 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.36 kB | 5.36 kB | N/A |
| bccd1874-HASH.js gzip | 52.8 kB | 52.8 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 232 B | 235 B | N/A |
| main-HASH.js gzip | 34.1 kB | 34.1 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js lubieowoce/fix-client-transform-mjs | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js lubieowoce/fix-client-transform-mjs | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js lubieowoce/fix-client-transform-mjs | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 746 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js lubieowoce/fix-client-transform-mjs | Change |
| - | - | - | - |
| index.html gzip | 522 B | 524 B | N/A |
| link.html gzip | 537 B | 537 B | ✓ |
| withRouter.html gzip | 518 B | 520 B | N/A |
| Overall change | 537 B | 537 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js lubieowoce/fix-client-transform-mjs | Change |
| - | - | - | - |
| edge-ssr.js gzip | 129 kB | 129 kB | N/A |
| page.js gzip | 206 kB | 206 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js lubieowoce/fix-client-transform-mjs | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 671 B | 666 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.3 kB | 31.3 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js lubieowoce/fix-client-transform-mjs | Change |
| - | - | - | - |
| 274-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 274.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 359 kB | 359 kB | ✓ |
| app-page-exp..prod.js gzip | 129 kB | 129 kB | ✓ |
| app-page-tur..prod.js gzip | 141 kB | 141 kB | ✓ |
| app-page-tur..prod.js gzip | 137 kB | 137 kB | ✓ |
| app-page.run...dev.js gzip | 348 kB | 348 kB | ✓ |
| app-page.run..prod.js gzip | 125 kB | 125 kB | ✓ |
| app-route-ex...dev.js gzip | 37.4 kB | 37.4 kB | ✓ |
| app-route-ex..prod.js gzip | 25.5 kB | 25.5 kB | ✓ |
| app-route-tu..prod.js gzip | 25.5 kB | 25.5 kB | ✓ |
| app-route-tu..prod.js gzip | 25.3 kB | 25.3 kB | ✓ |
| app-route.ru...dev.js gzip | 39.1 kB | 39.1 kB | ✓ |
| app-route.ru..prod.js gzip | 25.3 kB | 25.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.69 kB | 9.69 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.6 kB | 11.6 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.68 kB | 9.68 kB | ✓ |
| pages-turbo...prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| pages.runtim...dev.js gzip | 27.5 kB | 27.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| server.runti..prod.js gzip | 916 kB | 916 kB | ✓ |
| Overall change | 2.44 MB | 2.44 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | vercel/next.js lubieowoce/fix-client-transform-mjs | Change |
| - | - | - | - |
| 0.pack gzip | 2.08 MB | 2.08 MB | N/A |
| index.pack gzip | 74.3 kB | 74 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 103c65d3917580a7678822d875f39576c428fd3e

File: test/e2e/app-dir/client-module-with-package-type/app/import-cjs/page.tsx [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import * as React from 'react'
+
+import EsmFromCjs from 'lib-cjs'
```
Comment (lubieowoce) [inline test/e2e/app-dir/client-module-with-package-type/app/import-cjs/page.tsx:3]: this is the case that matches `jotai`s scenario. other permutations are just for completeness

File: test/e2e/app-dir/client-module-with-package-type/app/import-cjs/page.tsx
Comment (lubieowoce) [inline test/e2e/app-dir/client-module-with-package-type/app/import-cjs/page.tsx:1]: this is the case that matches jotais scenario. other permutations are just for completeness.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 2e01e20174204da5fdc93b94e7e326a1d00e751d

`pnpm test test/integration/export-default-map/test/index.test.js` (turbopack)
- Export with default map > production mode > should export with folder that has dot in name
- Export with default map > production mode > should export an amp only page to clean path
- Export with default map > production mode > should export hybrid amp page correctly
- Export with default map > production mode > should export nested hybrid amp page correctly
- Export with default map > production mode > should export nested hybrid amp page correctly with folder
- Export with default map > production mode > should export hybrid index amp page correctly

<details>
<summary>Expand output</summary>

  ● Export with default map › production mode › should export with folder that has dot in name

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       ▲ Next.js 15.1.1-canary.14 (Turbopack)

       Checking validity of types ...
       Creating an optimized production build ...
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Building (0/8) ...
       Building (2/8) 
       Building (4/8) 
       Building (6/8) 
     ✓ Building (8/8)
     ✓ Compiled successfully in 4.8s
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 
    Error occurred prerendering page "/info". Read more: https://nextjs.org/docs/messages/prerender-error
    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:102:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:103:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:104:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2238:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:1:20650)
      at validateAmp (../packages/next/dist/export/routes/pages.js:106:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:140:17)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:156:20)
      at async exportPage (../packages/next/dist/export/worker.js:337:18)
      Export encountered an error on /info, exiting the build.
       ⨯ Static worker exited with code: 1 and signal: null
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export an amp only page to clean path

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       ▲ Next.js 15.1.1-canary.14 (Turbopack)

       Checking validity of types ...
       Creating an optimized production build ...
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Building (0/8) ...
       Building (2/8) 
       Building (4/8) 
       Building (6/8) 
     ✓ Building (8/8)
     ✓ Compiled successfully in 4.8s
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 
    Error occurred prerendering page "/info". Read more: https://nextjs.org/docs/messages/prerender-error
    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:102:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:103:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:104:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2238:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:1:20650)
      at validateAmp (../packages/next/dist/export/routes/pages.js:106:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:140:17)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:156:20)
      at async exportPage (../packages/next/dist/export/worker.js:337:18)
      Export encountered an error on /info, exiting the build.
       ⨯ Static worker exited with code: 1 and signal: null
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export hybrid amp page correctly

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       ▲ Next.js 15.1.1-canary.14 (Turbopack)

       Checking validity of types ...
       Creating an optimized production build ...
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Building (0/8) ...
       Building (2/8) 
       Building (4/8) 
       Building (6/8) 
     ✓ Building (8/8)
     ✓ Compiled successfully in 4.8s
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 
    Error occurred prerendering page "/info". Read more: https://nextjs.org/docs/messages/prerender-error
    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:102:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:103:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:104:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2238:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:1:20650)
      at validateAmp (../packages/next/dist/export/routes/pages.js:106:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:140:17)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:156:20)
      at async exportPage (../packages/next/dist/export/worker.js:337:18)
      Export encountered an error on /info, exiting the build.
       ⨯ Static worker exited with code: 1 and signal: null
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export nested hybrid amp page correctly

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       ▲ Next.js 15.1.1-canary.14 (Turbopack)

       Checking validity of types ...
       Creating an optimized production build ...
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Building (0/8) ...
       Building (2/8) 
       Building (4/8) 
       Building (6/8) 
     ✓ Building (8/8)
     ✓ Compiled successfully in 4.8s
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 
    Error occurred prerendering page "/info". Read more: https://nextjs.org/docs/messages/prerender-error
    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:102:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:103:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:104:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2238:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:1:20650)
      at validateAmp (../packages/next/dist/export/routes/pages.js:106:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:140:17)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:156:20)
      at async exportPage (../packages/next/dist/export/worker.js:337:18)
      Export encountered an error on /info, exiting the build.
       ⨯ Static worker exited with code: 1 and signal: null
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export nested hybrid amp page correctly with folder

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       ▲ Next.js 15.1.1-canary.14 (Turbopack)

       Checking validity of types ...
       Creating an optimized production build ...
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Building (0/8) ...
       Building (2/8) 
       Building (4/8) 
       Building (6/8) 
     ✓ Building (8/8)
     ✓ Compiled successfully in 4.8s
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 
    Error occurred prerendering page "/info". Read more: https://nextjs.org/docs/messages/prerender-error
    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:102:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:103:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:104:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2238:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:1:20650)
      at validateAmp (../packages/next/dist/export/routes/pages.js:106:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:140:17)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:156:20)
      at async exportPage (../packages/next/dist/export/worker.js:337:18)
      Export encountered an error on /info, exiting the build.
       ⨯ Static worker exited with code: 1 and signal: null
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export hybrid index amp page correctly

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       ▲ Next.js 15.1.1-canary.14 (Turbopack)

       Checking validity of types ...
       Creating an optimized production build ...
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Building (0/8) ...
       Building (2/8) 
       Building (4/8) 
       Building (6/8) 
     ✓ Building (8/8)
     ✓ Compiled successfully in 4.8s
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 
    Error occurred prerendering page "/info". Read more: https://nextjs.org/docs/messages/prerender-error
    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:102:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:103:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:104:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2238:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:1:20650)
      at validateAmp (../packages/next/dist/export/routes/pages.js:106:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:140:17)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:156:20)
      at async exportPage (../packages/next/dist/export/worker.js:337:18)
      Export encountered an error on /info, exiting the build.
       ⨯ Static worker exited with code: 1 and signal: null
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by eps1lon — APPROVED** [review]
