### PR TITLE
Serverless build for API routes

### LINKED ISSUE #7633: Wrong output destination for API routes when building in `serverless` target
When running `next build` and having `serverless` set as `target`, API routes gets built at the wrong destination. Instead of getting built to `serverlesss/pages/api/route.js`, it's placed in `static/<BUILD_ID>/pages/api/route.js` with no entry in `pages-manifest.json`.

To reproduce, do the following:

1. Create a API route in `pages/api`
2. Run `next build` with `target: serverless`
3. Check the build folder and the API route should be in the wrong destination

### PR DESCRIPTION
**Pull request by huv1k**
Fixes #7633

### CODE REVIEW

File: packages/next/build/utils.ts [hunk 1]
```diff
@@ -242,13 +242,15 @@ export async function getCacheIdentifier({
...
+  target: string
 ): Promise<number> {
-  const clientBundle = path.join(
-    distPath,
-    `static/${buildId}/pages/`,
-    `${page}.js`
-  )
+  let clientBundle
+  if (target === 'serverless' && page.startsWith('/api')) {
+    clientBundle = path.join(distPath, 'serverless/pages', `${page}.js`)
```
Comment (Timer) [inline packages/next/build/utils.ts]: We don't need API bundle sizes -- we only care about the client bundles. You can revert these changes.

**Review by Timer — CHANGES_REQUESTED** [review]

File: packages/next/build/utils.ts (hunk 1 above)
Comment (huv1k) [reply packages/next/build/utils.ts]: @timneutkens said that we should display it

Comment (timneutkens) [reply packages/next/build/utils.ts]: I said display the modules etc, the size is fine to be n/a

**Review by Timer — APPROVED** [review]
