### PR TITLE
Compile next/client and next/pages

### LINKED ISSUE #274: Support Next.js v8
`next-routes` imports from `next/link`:

https://github.com/fridays/next-routes/blob/1.4.2/src/index.js#L4

But in Next.js v8.0.0-canary.3 that file contains ESM, presumably because Next.js expects it will always be imported within a Next.js project via a Webpack build:

https://unpkg.com/next@8.0.0-canary.3/dist/client/link.js

That causes this runtime error on the server:

```
[redacted]/node_modules/next/dist/client/link.js:2
import { resolve, format, parse } from 'url';
       ^

SyntaxError: Unexpected token {
```

Presumably `import NextRouter from 'next/router'` would have the same issue.

### LINKED ISSUE #6017: Upgrade to 8.0.0-canary.3 from 7.2.0.canary
When I update next js I got following error. Is there any I missed for my end

nextjs

### PR DESCRIPTION
**Pull request by timneutkens**
Because next-routes requires APIs outside of compilation we have to compile these

Fixes https://github.com/fridays/next-routes/issues/274
Fixes #6017

### CODE REVIEW

File: packages/next/taskfile.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ export async function nextbuild (task, opts) {
 }
 
 export async function client (task, opts) {
-  await task.source(opts.src || 'client/**/*.+(js|ts|tsx)').typescript().target('dist/client')
+  await task.source(opts.src || 'client/**/*.+(js|ts|tsx)').typescript({module: 'commonjs'}).target('dist/client')
```
Comment (timneutkens) [inline packages/next/taskfile.js]: We'll have to do `target: 'es5'` for this one too as otherwise we'll ship newer syntax to older browsers.
