### PR TITLE
await config

### LINKED ISSUE #6416: next-manifest works in 8.0.1 but stopped working in 8.0.2
# Bug report

[next-manifest](https://github.com/ragingwind/next-manifest) stopped working @ 8.0.2

Next.js 8.0.1 - works
Next.js 8.0.2 - exporting withManifest() produces:

```
Entry module not found: Error: Can't resolve './src' in '/Users/foo/site'
_document.js chunk not found
```

## To Reproduce

1. Install Next.js 8.0.2
2. Install next-manifest
2. Use `module.exports = withManifest()` in next.config.js

## Expected behavior
For it to work in Next.js 8.0.2

## System information
 - OS: macOS, Windows, Linux

### PR DESCRIPTION
**Pull request by timneutkens**
Fixes #6416

@ijjk can you update the test then we can ship this to canary :pray:

### CODE REVIEW

File: packages/next/build/index.ts [hunk 1]
```diff
@@ -56,14 +56,14 @@ export default async function build(dir: string, conf = null): Promise<void> {
   const pages = createPagesMapping(pagePaths, config.pageExtensions)
   const entrypoints = createEntrypoints(pages, config.target, buildId, config)
   const configs = [
```
Comment (ijjk) [inline packages/next/build/index.ts]: This used to be the below line, but if you prefer this it works 👌
```js
const configs: any = await Promise.all([
```

Comment (timneutkens) [reply packages/next/build/index.ts]: I'm aware 😄
