### PR TITLE
[ESLint] Remove error when file patterns are unmatched + ESLint setup changes

### LINKED ISSUE #26155: `next lint` does not work with `src` directory
### What version of Next.js are you using?

11

### What version of Node.js are you using?

16.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

If you run `next lint` when storing your code in a `src` directory, the CLI complains that there is no `/components` directory.

This also means that `next build` fails when using the ESLint config.

```
> site@1.6.0 build
> next build

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types

> Build error occurred
Error: No files matching '/Users/blp/Sites/site/components' were found.
    at FileEnumerator.iterateFiles (/Users/blp/Sites/site/node_modules/eslint/lib/cli-engine/file-enumerator.js:317:27)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (/Users/blp/Sites/site/node_modules/eslint/lib/cli-engine/cli-engine.js:765:48)
    at ESLint.lintFiles (/Users/blp/Sites/site/node_modules/eslint/lib/eslint/eslint.js:530:23)
    at lint (/Users/blp/Sites/site/node_modules/next/dist/lib/eslint/runLintCheck.js:2:1752)
    at async Object.runLintCheck (/Users/blp/Sites/site/node_modules/next/dist/lib/eslint/runLintCheck.js:8:8) {
  type: 'NoFilesFoundError',
  messageTemplate: 'file-not-found',
  messageData: { pattern: '/Users/blp/Sites/site/components', globDisabled: false }
}
```

### Expected Behavior

`next lint` should look inside a `src` directory.

### To Reproduce

Create a Next project, move source code into a `src` directory, and run `npx next lint`.

### PR DESCRIPTION
**Pull request by housseindjirdeh**
This PR does the following:

- Disables the `errorOnUnmatchedPattern` property for ESLint to not error when file patterns are unmatched (examples: empty directory, directory ignored in `.eslintignore`). Both `next lint` and `next build` are updated. Closes #26155
- Deletes `conformance` integration tests that are outdated and rely on the old webpack conformance plugin
- Includes a new `test/.eslintrc.json` file to configure ESLint specifically for test files
- Updates failing test cases where which were failing with the new `test/.eslintrc.json` config 
- Removed `.eslintignore` for `test/integration/async-modules` (ported from #26915)
- Added support for top level await to Next.js eslint preset (ported from #26915)

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| buildDuration | 15.3s | 15.5s | ⚠️ +287ms |
| buildDurationCached | 3.7s | 3.5s | -223ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +253 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.539 | 2.616 | ⚠️ +0.08 |
| / avg req/sec | 984.54 | 955.48 | ⚠️ -29.06 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.606 | 1.618 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1556.74 | 1545.41 | ⚠️ -11.33 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| 359.HASH.js gzip | 3.09 kB | 3.09 kB | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.9 kB | 20.9 kB | ✓ |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 67.6 kB | 67.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.18 kB | 3.18 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.69 kB | 5.69 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 419 B | 419 B | ✓ |
| Overall change | 419 B | 419 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12s | -103ms |
| buildDurationCached | 5s | 4.8s | -176ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +253 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.653 | 2.559 | -0.09 |
| / avg req/sec | 942.26 | 976.98 | +34.72 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.606 | 1.616 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1556.61 | 1546.69 | ⚠️ -9.92 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| 14.HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 8.17 kB | 8.17 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 230 B | 230 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 297 B | 297 B | ✓ |
| withRouter-HASH.js gzip | 293 B | 293 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.98 kB | 8.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 418 B | 418 B | ✓ |
| Overall change | 418 B | 418 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| index.html gzip | 575 B | 575 B | ✓ |
| link.html gzip | 586 B | 586 B | ✓ |
| withRouter.html gzip | 568 B | 568 B | ✓ |
| Overall change | 1.73 kB | 1.73 kB | ✓ |

</details>

</details>
Commit: 028d633cbf7b957ae96a2c3a72948e76fdd92bc8

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 028d633cbf7b957ae96a2c3a72948e76fdd92bc8

**test/integration/eslint/test/index.test.js** 
- ESLint > Next Lint > error on unmatched pattern flag shows error when unmatched patterns are present

<details>
<summary>Expand output</summary>

  ● ESLint › Next Lint › error on unmatched pattern flag shows error when unmatched patterns are present

    expect(received).toContain(expected) // indexOf

    Expected substring: "No files matching"
    Received string:    "info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5·
    ./pages/index.js
    4:5  Warning: External synchronous scripts are forbidden. See: https://nextjs.org/docs/messages/no-sync-scripts.  @next/next/no-sync-scripts·
    Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules·
    "

      256 |
      257 |       const output = stdout + stderr
    > 258 |       expect(output).toContain('No files matching')
          |                      ^
      259 |       expect(output).not.toContain(
      260 |         'Warning: External synchronous scripts are forbidden'
      261 |       )

      at Object.<anonymous> (integration/eslint/test/index.test.js:258:22)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.7s | ⚠️ +99ms |
| buildDurationCached | 2.9s | 2.8s | -38ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +253 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.141 | 2.114 | -0.03 |
| / avg req/sec | 1167.42 | 1182.39 | +14.97 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.314 | 1.288 | -0.03 |
| /error-in-render avg req/sec | 1902.53 | 1940.45 | +37.92 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| 359.HASH.js gzip | 3.09 kB | 3.09 kB | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.9 kB | 20.9 kB | ✓ |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 67.6 kB | 67.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.18 kB | 3.18 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.69 kB | 5.69 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 419 B | 419 B | ✓ |
| Overall change | 419 B | 419 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| buildDuration | 9.9s | 10s | ⚠️ +101ms |
| buildDurationCached | 4s | 4s | -23ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +253 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.108 | 2.091 | -0.02 |
| / avg req/sec | 1186.15 | 1195.34 | +9.19 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.299 | 1.285 | -0.01 |
| /error-in-render avg req/sec | 1924.4 | 1945.4 | +21 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| 14.HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 8.17 kB | 8.17 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 230 B | 230 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 297 B | 297 B | ✓ |
| withRouter-HASH.js gzip | 293 B | 293 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.98 kB | 8.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 418 B | 418 B | ✓ |
| Overall change | 418 B | 418 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| index.html gzip | 575 B | 575 B | ✓ |
| link.html gzip | 586 B | 586 B | ✓ |
| withRouter.html gzip | 568 B | 568 B | ✓ |
| Overall change | 1.73 kB | 1.73 kB | ✓ |

</details>

</details>
Commit: 3d0db1e53f26473c4feac24c6f7ebc9d3c36db78

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 1b515b07d5ceab7c6e6856d0bd13b5b7e7ead22e

**test/integration/404-page-app/test/index.test.js** 
- 404 Page Support with _app > production mode > should build successfully
- 404 Page Support with _app > production mode > should not output static 404 if _app has getInitialProps
- 404 Page Support with _app > production mode > specify to use the 404 page still in the routes-manifest
- 404 Page Support with _app > production mode > should still use 404 page

<details>
<summary>Expand output</summary>

  ● 404 Page Support with _app › production mode › should build successfully

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      32 |       })
      33 |
    > 34 |       expect(code).toBe(0)
         |                    ^
      35 |       expect(stderr).not.toMatch(gip404Err)
      36 |       expect(stdout).not.toMatch(gip404Err)
      37 |

      at Object.<anonymous> (integration/404-page-app/test/index.test.js:34:20)

  ● 404 Page Support with _app › production mode › should not output static 404 if _app has getInitialProps

    InvalidArgumentError: invalid argument
      (Session info: headless chrome=91.0.4472.114)

      177 |   console.log(`\n> Loading browser with ${url}\n`)
      178 |
    > 179 |   await browser.get(url)
          |   ^
      180 |   console.log(`\n> Loaded browser with ${url}\n`)
      181 |
      182 |   // Wait for application to hydrate

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at _default (lib/next-webdriver.js:179:3)
      at Object.<anonymous> (integration/404-page-app/test/index.test.js:43:23)

  ● 404 Page Support with _app › production mode › specify to use the 404 page still in the routes-manifest

    ENOENT: no such file or directory, open '/home/runner/work/next.js/next.js/test/integration/404-page-app/.next/routes-manifest.json'



  ● 404 Page Support with _app › production mode › should still use 404 page

    FetchError: request to http://localhost/:undefined/abc failed, reason: connect ECONNREFUSED 127.0.0.1:80

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      297 | export async function killApp(instance) {
      298 |   await new Promise((resolve, reject) => {
    > 299 |     treeKill(instance.pid, (err) => {
          |                       ^
      300 |       if (err) {
      301 |         if (
      302 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:299:23
      at killApp (lib/next-test-utils.js:298:9)
      at integration/404-page-app/test/index.test.js:26:20

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| buildDuration | 16.1s | 16s | -44ms |
| buildDurationCached | 3.8s | 3.7s | -137ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +253 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.72 | 2.739 | ⚠️ +0.02 |
| / avg req/sec | 919.22 | 912.62 | ⚠️ -6.6 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.702 | 1.72 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1468.65 | 1453.87 | ⚠️ -14.78 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| 359.HASH.js gzip | 3.09 kB | 3.09 kB | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.9 kB | 20.9 kB | ✓ |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 67.6 kB | 67.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.18 kB | 3.18 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.69 kB | 5.69 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 419 B | 419 B | ✓ |
| Overall change | 419 B | 419 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.4s | -422ms |
| buildDurationCached | 5.2s | 4.9s | -284ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +253 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.679 | 2.665 | -0.01 |
| / avg req/sec | 933.28 | 938.16 | +4.88 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.72 | 1.666 | -0.05 |
| /error-in-render avg req/sec | 1453.19 | 1500.2 | +47.01 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| 14.HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 8.17 kB | 8.17 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 230 B | 230 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 297 B | 297 B | ✓ |
| withRouter-HASH.js gzip | 293 B | 293 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.98 kB | 8.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 418 B | 418 B | ✓ |
| Overall change | 418 B | 418 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| index.html gzip | 575 B | 575 B | ✓ |
| link.html gzip | 586 B | 586 B | ✓ |
| withRouter.html gzip | 568 B | 568 B | ✓ |
| Overall change | 1.73 kB | 1.73 kB | ✓ |

</details>

</details>
Commit: 1b515b07d5ceab7c6e6856d0bd13b5b7e7ead22e

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.8s | ⚠️ +128ms |
| buildDurationCached | 3s | 3s | ⚠️ +38ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +253 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.05 | 2.082 | ⚠️ +0.03 |
| / avg req/sec | 1219.27 | 1200.53 | ⚠️ -18.74 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.133 | 1.141 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2206.07 | 2191.21 | ⚠️ -14.86 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| 359.HASH.js gzip | 3.09 kB | 3.09 kB | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.9 kB | 20.9 kB | ✓ |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 67.6 kB | 67.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.18 kB | 3.18 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.69 kB | 5.69 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 419 B | 419 B | ✓ |
| Overall change | 419 B | 419 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| buildDuration | 10.1s | 10.1s | ⚠️ +11ms |
| buildDurationCached | 4.1s | 4s | -62ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +253 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.111 | 2.131 | ⚠️ +0.02 |
| / avg req/sec | 1184.53 | 1173.01 | ⚠️ -11.52 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.149 | 1.145 | 0 |
| /error-in-render avg req/sec | 2176.11 | 2183.07 | +6.96 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| 14.HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 8.17 kB | 8.17 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 230 B | 230 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 297 B | 297 B | ✓ |
| withRouter-HASH.js gzip | 293 B | 293 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.98 kB | 8.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 418 B | 418 B | ✓ |
| Overall change | 418 B | 418 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| index.html gzip | 574 B | 574 B | ✓ |
| link.html gzip | 585 B | 585 B | ✓ |
| withRouter.html gzip | 568 B | 568 B | ✓ |
| Overall change | 1.73 kB | 1.73 kB | ✓ |

</details>

</details>
Commit: 6d7c24d2d719b30087a946bf675c29c3f570710d

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| buildDuration | 13s | 13.1s | ⚠️ +19ms |
| buildDurationCached | 3s | 3s | -14ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +253 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.086 | 1.959 | -0.13 |
| / avg req/sec | 1198.43 | 1276.23 | +77.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.193 | 1.119 | -0.07 |
| /error-in-render avg req/sec | 2096.1 | 2233.47 | +137.37 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| 359.HASH.js gzip | 3.09 kB | 3.09 kB | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.9 kB | 20.9 kB | ✓ |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 67.6 kB | 67.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.18 kB | 3.18 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.69 kB | 5.69 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 419 B | 419 B | ✓ |
| Overall change | 419 B | 419 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| buildDuration | 9.7s | 10.2s | ⚠️ +477ms |
| buildDurationCached | 3.9s | 4s | ⚠️ +135ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +253 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.033 | 2.001 | -0.03 |
| / avg req/sec | 1229.9 | 1249.68 | +19.78 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.088 | 1.217 | ⚠️ +0.13 |
| /error-in-render avg req/sec | 2298.44 | 2053.4 | ⚠️ -245.04 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| 14.HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 8.17 kB | 8.17 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 230 B | 230 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 297 B | 297 B | ✓ |
| withRouter-HASH.js gzip | 293 B | 293 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.98 kB | 8.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 418 B | 418 B | ✓ |
| Overall change | 418 B | 418 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| index.html gzip | 574 B | 574 B | ✓ |
| link.html gzip | 585 B | 585 B | ✓ |
| withRouter.html gzip | 568 B | 568 B | ✓ |
| Overall change | 1.73 kB | 1.73 kB | ✓ |

</details>

</details>
Commit: 244abca5d61aa07ad908ff39c38d88c8b18493ba

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 244abca5d61aa07ad908ff39c38d88c8b18493ba

**test/integration/client-navigation/test/index.test.js** 
- Client Navigation > with unexpected <a/> nested tag > should not redirect if passHref prop is not defined in Link

<details>
<summary>Expand output</summary>

  ● Client Navigation › with unexpected <a/> nested tag › should not redirect if passHref prop is not defined in Link

    thrown: "Exceeded timeout of 300000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      181 |
      182 |   describe('with unexpected <a/> nested tag', () => {
    > 183 |     it('should not redirect if passHref prop is not defined in Link', async () => {
          |     ^
      184 |       const browser = await webdriver(context.appPort, '/nav/pass-href-prop')
      185 |       const text = await browser
      186 |         .elementByCss('#without-href')

      at integration/client-navigation/test/index.test.js:183:5
      at integration/client-navigation/test/index.test.js:182:3
      at Object.<anonymous> (integration/client-navigation/test/index.test.js:22:1)

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 7a323309342ad49a71a94e9a6d43b65defb89945

**test/integration/build-indicator/test/index.test.js** 
- Build Activity Indicator > Enabled > Shows build indicator when page is built from modifying

<details>
<summary>Expand output</summary>

  ● Build Activity Indicator › Enabled › Shows build indicator when page is built from modifying

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: null

      62 |       const wasVisible = await browser.eval('window.showedBuilder')
      63 |
    > 64 |       expect(wasVisible).toBe(true)
         |                          ^
      65 |       await fs.writeFile(pagePath, origContent, 'utf8')
      66 |       await browser.close()
      67 |     })

      at Object.<anonymous> (integration/build-indicator/test/index.test.js:64:26)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| buildDuration | 11.8s | 11.8s | ⚠️ +46ms |
| buildDurationCached | 2.8s | 2.7s | -68ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +253 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.826 | 1.807 | -0.02 |
| / avg req/sec | 1369.32 | 1383.24 | +13.92 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.04 | 1.039 | 0 |
| /error-in-render avg req/sec | 2403.23 | 2406.19 | +2.96 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| 359.HASH.js gzip | 3.09 kB | 3.09 kB | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.9 kB | 20.9 kB | ✓ |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 67.6 kB | 67.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.18 kB | 3.18 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.69 kB | 5.69 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 419 B | 419 B | ✓ |
| Overall change | 419 B | 419 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| buildDuration | 9.4s | 9.5s | ⚠️ +51ms |
| buildDurationCached | 3.7s | 3.7s | -29ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +253 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.933 | 1.995 | ⚠️ +0.06 |
| / avg req/sec | 1293.42 | 1252.96 | ⚠️ -40.46 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.015 | 1.045 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2463.76 | 2393.17 | ⚠️ -70.59 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| 14.HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 8.17 kB | 8.17 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 230 B | 230 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 297 B | 297 B | ✓ |
| withRouter-HASH.js gzip | 293 B | 293 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.98 kB | 8.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 418 B | 418 B | ✓ |
| Overall change | 418 B | 418 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | housseindjirdeh/next.js bug/26155 | Change |
| - | - | - | - |
| index.html gzip | 574 B | 574 B | ✓ |
| link.html gzip | 585 B | 585 B | ✓ |
| withRouter.html gzip | 568 B | 568 B | ✓ |
| Overall change | 1.73 kB | 1.73 kB | ✓ |

</details>

</details>
Commit: f09a6cea7d29fda5dcd515da2fd7ddf203b01f24

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f09a6cea7d29fda5dcd515da2fd7ddf203b01f24

**test/acceptance/ReactRefreshLogBox.dev.test.js** 
-  > server-side only compilation errors

<details>
<summary>Expand output</summary>

  ● server-side only compilation errors

    ScriptTimeoutError: script timeout
      (Session info: headless chrome=91.0.4472.114)

      72 |
      73 |             // Wait for application to re-hydrate:
    > 74 |             await browser.executeAsyncScript(function () {
         |             ^
      75 |               var callback = arguments[arguments.length - 1]
      76 |               if (window.__NEXT_HYDRATED) {
      77 |                 callback()

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
          at runMicrotasks (<anonymous>)
      at Proxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.patch (acceptance/helpers.js:74:13)
      at Object.<anonymous> (acceptance/ReactRefreshLogBox.dev.test.js:1415:3)

</details>

File: .eslintignore [hunk 1]
```diff
@@ -6,6 +6,10 @@ e2e-tests/**
 examples/with-eslint/**
 examples/with-typescript-eslint-jest/**
 examples/with-kea/**
+examples/with-custom-babel-config/**
+examples/with-flow/**
+examples/with-mobx-state-tree/**
+examples/with-mobx/**
```
Comment (housseindjirdeh) [inline .eslintignore:12]: ESLint is erroring any examples with experimental syntax. They're not picking up their local `.babelrc` files for some reason and don't want to inherently change user-facing examples (hence why I threw them in `.eslintignore` for now).

TODO: I still need to add `eslint-config-next` to all the examples and ensure they work with all the latest features

File: packages/next/cli/next-lint.ts [hunk 2]
```diff
@@ -120,7 +122,7 @@ const nextLint: cliCommand = (argv) => {
           --cache-location path::String  Path to the cache file or directory - default: .eslintcache
         
         Miscellaneous:
-          --no-error-on-unmatched-pattern  Prevent errors when pattern is unmatched - default: false
+          --error-on-unmatched-pattern   Show errors when any file patterns are unmatched - default: false
```
Comment (housseindjirdeh) [inline packages/next/cli/next-lint.ts:125]: Technically a breaking API change, but the previous behavior was faulty (empty file directories or folders with all files ignored by ESLint would fail `next lint`) so I don't think we have to wait for the next major version to include this fix.

File: test/.eslintrc.json [hunk 3]
```diff
@@ -0,0 +1,16 @@
+{
+  "extends": ["next"],
+  "rules": {
+    "import/no-anonymous-default-export": "off",
```
Comment (housseindjirdeh) [inline test/.eslintrc.json:4]: @timneutkens I noticed you enabled this and updated a ton of unnamed exports in tests. Can do the same here if you like, but didn't want to duplicate efforts.

Comment (timneutkens) [reply test/.eslintrc.json:4]: It's fine to disable it for this. The tests can be kept as-is.

**Review by timneutkens — APPROVED** [review]
Looks great, thanks for fixing/porting these @housseindjirdeh 💯
